### ISSUE TITLE
Lengthy fsck on systems without an RTC. timesyncd runs after fsck-root.

### ISSUE THREAD

**Issue by XECDesign** [systemd/systemd#10000]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch Linux ARM

**Expected behaviour you didn't see**
 > systemd-timesyncd runs, restores time from the saved timestamp before systemd-fsck-root runs.

**Unexpected behaviour you saw**
 > systemd-fsck-root runs before systemd-timesyncd, thinks that the last write and mount times are in the future, triggering a full filesystem check. Depending on the size and speed of the drive, this can take a very long time.

**Steps to reproduce the problem**

> Enable filesystem checking by setting rootfs' fs_passno to 1 in fstab.  Set 'ro' kernel parameter. Make sure the last write time on the filesystem is the present time. Reboot and check the output of fsck-root.

**Comment by sourcejedi** [comment]
I think there will be resistance to making systemd-fsck-root wait for network-online.target and time-sync.target.  We don't normally even enable network-online.target.

There is a Debian bug for fsck.ext* which discusses this.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=559776#10

> Your system is broken already because it doesn't have a usable RTC.
> Having correct system time is important!  Indeed, there are certain
> hueristics (such as detecting losted orphaned inodes) that depends on
> the system time being correct.
> 
> I will add an e2fsck.conf option for systems with busted system
> clocks, but it won't be the default.

(See the section for `broken_system_clock` in `man e2fsck.conf`).

**Comment by poettering** [comment]
Pretty much all distros patch out the timestamp check from fsck, because it makes little sense. The assumption that the clock was right and the disk was wrong is a really questionable one, and it contradicts any logic that restores/montonizes the clock based on timestamps stored on disk (as we shouldn't access the disk before fsck, but need the disk to initialize the clock, which requires disk access).

Let's close this here: do what the big distros do: patch out this broken logic from fsck, there's very little we can do about this otherwise.

I hope this makes sense.

**Comment by XECDesign** [comment]
Thanks for the response, Lennart.

What would be an example of a distro that does this? I've tried Raspbian, Debian and Arch Linux, all of which exhibit this behaviour. I haven't tried to reproduce the behaviour on Ubuntu, but I don't see any relevant patches in their e2fsprogs source package.

Given that before fsck runs, we're already reading from the disk (loading systemd itself, reading fstab and so on), why not read the timestamp a little earlier too? It seems nicer to address the underlying issue rather than working around it.

**Comment by poettering** [comment]
> Thanks for the response, Lennart.
> 
> What would be an example of a distro that does this? I've tried Raspbian, Debian and Arch Linux, all of which exhibit this behaviour. I haven't tried to reproduce the behaviour on Ubuntu, but I don't see any relevant patches in their e2fsprogs source package.

On Fedora broken_system_clock in e2fsck.conf is set by default, and I am pretty sure Debian does that too. Not sure how they do that, please inquire the Debian folks for help.

See this for example:

https://bugzilla.redhat.com/show_bug.cgi?id=1365594

or this:

https://src.fedoraproject.org/rpms/e2fsprogs/blob/master/f/e2fsprogs.spec#_488

> Given that before fsck runs, we're already reading from the disk (loading systemd itself, reading fstab and so on), why not read the timestamp a little earlier too? It seems nicer to address the underlying issue rather than working around it.

On common systems we do not read fsck from the OS disk, but run fsck from the initrd in a version stored in the initrd. We hence won't access the OS file system at all before the fsck completed. But even if you run systems without initrd, we still distuingish between the root fs and /var and make different assumptions about those file systems: the root fs is assumed to be (mostly) read-only while /var is assumed to be writable and possibly split out. Thus we carefully schedule access to it so that we only rely on the safe, restricted root fs initially and only progress to accessing the writable (and thus more fragile) /var later on after is has been fscked...
