### ISSUE TITLE
document in systemd.special(5) that user-xyz.slice don't need ordering before slices.target

### ISSUE THREAD

**Issue by Skarlso** [systemd/systemd#10015]
**systemd version the issue has been seen with**
> 239

**Expected behaviour you didn't see**
 > No cyclic dependency error

**Unexpected behaviour you saw**

```bash
$ systemd-analyze verify default.target
systemd-user-sessions.service: Found ordering cycle on basic.target/start
systemd-user-sessions.service: Found dependency on slices.target/start
systemd-user-sessions.service: Found dependency on user-1000-test.slice/start
systemd-user-sessions.service: Found dependency on user-1000.slice/start
systemd-user-sessions.service: Found dependency on systemd-user-sessions.service/start
systemd-user-sessions.service: Job slices.target/start deleted to break ordering cycle starting with systemd-user-sessions.service/start
```

**Steps to reproduce the problem**

- [ ] Create a slice like this:
```bash
cat /etc/systemd/system/user-1000-test.slice
[Unit]
Description=Test Slicet

[Slice]
CPUAccounting=true
MemoryAccounting=true

[Install]
WantedBy=slices.target
```
- [ ] Run enable on it:

```bash
systemctl daemon-reload
systemctl enable user-1000-test.slice
Created symlink /etc/systemd/system/slices.target.wants/user-1000-test.slice → /etc/systemd/system/user-1000-test.slice.
```

According to this document: https://www.freedesktop.org/software/systemd/man/systemd.special.html#slices.target 
> It's a good idea to add WantedBy=slices.target lines to the "[Install]" section of all slices units that may be installed dynamically.

However if this is done, enabling the service will result in a cycle dependency because enable those this:

>   enable NAME..., enable PATH...
      Enable one or more units or unit instances. This will create a set of symlinks, as
      encoded in the "[Install]" sections of the indicated unit files.

For which the result can be seen above when running analyze.

Q: What am I missing? Is this a bug? What's the problem here? Or do we just simply don't user [Install] in this case?

Thanks!

**Comment by filbranden** [comment]
This is happening because slice units with dashes have an implicit dependency on their "parent" unit, so `user-1000-test.slice` has a dependency on `user-1000.slice`.

The `user-*.slice` are special in that they're slices reserved for users. For that reason, they include an explicit ordering dependency on `systemd-user-sessions.service`, which you can easily see with:

```
$ systemctl cat user-1000.slice
# /usr/lib/systemd/system/user-.slice.d/10-defaults.conf

[Unit]
Description=User Slice of UID %j
Documentation=man:user@.service(5)
After=systemd-user-sessions.service

[Slice]
TasksMax=33%
```

I think since this is (at least hierarchically) a *user* slice, it doesn't really make sense to add it to `slices.target`, since that is meant to be used for system targets... (Having said that, I'm not sure what's the right approach here, to have that slice automatically initialized, or even if it's OK to define a slice under `user-1000`.)

**Comment by Skarlso** [comment]
@filbranden Thanks for the explanation! So, basically, for now, I should be ok by just removing the WantedBy, which will be okay, since this is implicitly depending on user anyways and should automatically be initialized?

**Comment by Skarlso** [comment]
@poettering Thank you! That explains the behaviour at hand! A documentation fix would be quiet welcomed, yes. The slices way of building up the dependency tree is complicated enough. :)

One question though.. I'm not a 100% sure I understand the English in this sentence:
> For the latter you actually don't need to do anything at all, as setting Slice=user-1000-test.slice in some service unit is enough

The first part of the sentences tells me, that I don't have to do anything as this is enough:

```bash
[Unit]
Description=Test Slicet

[Slice]
CPUAccounting=true
MemoryAccounting=true
```

But the second part says, I have to set `Slice=user-1000-test.slice` in some service unit? Would you be so kind as to clarify this part for me? Those this happen automatically, or do I have to actually write that somewhere?

Thanks!

**Comment by filbranden** [comment]
Yes, @poettering meant that the two ways to have that slice started on boot are:

- Explicitly add it to a dependency of, say, `multi-user.target` (as pointed out, `slices.target` doesn't work, but a later unit will work); or
- List your slice unit as `Slice=...` in a service unit that gets started.

The latter will work since the unit will have an implicit dependency on the slice, so starting that unit will require that systemd starts the slice first, therefore accomplishing what you're expecting.

(One thing is not fully clear to me here, is it possible to have this slice listed in a *user* service unit instead of system service unit? I think not, since that would require the user unit to start the slice and I don't think it has enough privileges to start a new slice under `user-*.slice`... Maybe it should? @poettering what do you think?)

**Comment by Skarlso** [comment]
Well those buttons are annoying... :)
<img width="1194" alt="screen shot 2018-09-18 at 06 32 24" src="https://user-images.githubusercontent.com/182850/45664550-b4ac6a00-bb0c-11e8-8704-10fd68d04379.png">

**Comment by Skarlso** [comment]
Thank you @poettering!
