### ISSUE TITLE
document that .socket units create sockets in the host's network namespaces, and that these can be passed to services living in other network namespaces just fine

### ISSUE THREAD

**Issue by najamelan** [systemd/systemd#10018]
I don't know if this "feature" is desired, but it sure is not documented and quite surprising, so I just want to inform here. 

I wanted to run dnscrypt in a different network namespace, in order to give it internet access. I did this with the workarounds described in this issue:[ #2741](https://github.com/systemd/systemd/issues/2741#issuecomment-341312994) . However I forgot that there is dnscrypt-proxy.socket, so I didn't disable that. I didn't count on using it anymore so I told dsncrypt-proxy in it's configuration file to open a port, and there is the `AmbientCapabilities=CAP_NET_BIND_SERVICE` which allows it to do so. 

So dnscrypt-proxy runs as an unprivileged process in another network namespace, listening to port 53 on `lo` while also listening on port 53 on `lo`in the default network namespace thanks to the `.socket` file. 

And it works! It serves dns requests on both (same pid). Black magic offered to you by systemd.

**Comment by poettering** [comment]
On Linux namespace association is a per-socket property, and the socket pins the namespace. This means if you create a socket namespace X then it will remain associated with namespace X for its entire life-time, and thus if you change namespaces during process runtime or receive fds from other namespaces through SCM_RIGHTS you can have fds referring to sockets in multiple different namespaces easily.

This is not so much a property of systemd hence, but simply the effect of implementation details in the Linux kernel. That said, we should probably document this explicitly in the .socket documentation, since it is indeed an interesting (and sometimes useful) feature.

**Comment by poettering** [comment]
Fix waiting in #10569
