### ISSUE TITLE
Improve libc portability

### ISSUE THREAD

**Issue by jameshilliard** [systemd/systemd#10130]
**Is your feature request related to a problem? Please describe.**
I do a lot of embedded systems development and have designed embedded firmware that uses systemd and have found systemd to be far superior to any other init systems. However most embedded distributions such as buildroot only support building systemd when using glibc which significantly increases the minimum system requirements.

Unlike with more traditional linux distros the embedded industry has been much slower when it comes to adoption of systemd overall, I think a big reason for this is that very few embedded linux distributions support systemd on anything other than glibc(openembedded is the only one I'm aware of that goes through the effort of maintaining a patchset for building systemd with alternative libc's).

I was looking into what could be done to improve systemd portability but noticed that pull requests that add fall-backs to missing glibc functionality are generally rejected by systemd developers with the reasoning that the libc should be changed instead to add the missing glibc functionality. The problem here is that a lot of embedded libc's are intentionally designed to be lightweight in order to support systems with very limited resources and as such many of the embedded libc upstreams will generally reject patches to add in the missing glibc functions.

**Describe the solution you'd like**
I would like to see systemd change policy in regards to accepting patches that add fallbacks/workarounds for missing glibc functionality so that adoption of systemd in the embedded industry will improve.

**Describe alternatives you've considered**
The only current way for embedded distributions to support systemd on alternative libc's is to maintain a compatibility patchset for systemd themselves which is generally too high of a maintenance burden for all but the largest distributions. Alternatives such as trying to upstream the missing glibc functions to the embedded libc's have effectively failed it would appear.

**Comment by fsateler** [comment]
> The only current way for embedded distributions to support systemd on alternative libc's is to maintain a compatibility patchset for systemd themselves which is generally too high of a maintenance burden for all but the largest distributions

Have you considered creating a glibc-compat library? Something like [libbsd](https://libbsd.freedesktop.org/wiki/), but the other way around: provide functions glibc provides but other libc don't. This way the maintainance burden is shared among all tiny-libc distros, and can be used by other projects as well.

A quick google yields already an [alpine glibc stub](https://github.com/sgerrand/alpine-pkg-glibc) and a [musl glibc stub](https://code.foxkit.us/adelie/gcompat). I think effort is better spent improving some of these libraries instead of reimplementing them in systemd.

**Comment by jameshilliard** [comment]
> Have you considered creating a glibc-compat library?

I did consider that but it didn't seem creating a generalized compat library would be all that viable as the fallbacks/workarounds often require specific knowledge of how systemd is using the function in order be done properly.

It would appears some of the libc compatibility issues effectively require compile-time workarounds within systemd including disabling/limiting certain features when they have dependencies that can't be emulated easily(features that use NSS for example).

I'm also not sure how a glibc-compat library would work when doing static only builds(common when using musl/uclibc).

Are you aware of any other projects going this route?

**Comment by yuwata** [comment]
I thought that NSS can be disabled by the compile option. Doesn't it work?

**Comment by jameshilliard** [comment]
I think so...however I recall NSS being a case where fallbacks could be provided for a number of systemd services that would otherwise be disabled entirely.

**Comment by yuwata** [comment]
I checked the [systemd repository for openembedded](https://github.com/openembedded/openembedded-core/tree/master/meta/recipes-core/systemd/systemd), but some of them are already merged in some form, and some of them are quite musl specific, and the others are custumizations for Openembedded.

**Comment by jameshilliard** [comment]
Yeah, it's mostly the musl patches that should probably be integrated into upstream systemd since they would be needed by any other distro that uses musl. I think uclibc also needs patches as well but it doesn't appear openembedded provides those.

**Comment by poettering** [comment]
This is hardly actionable as it lacks specificity. Do you have specific issues in mind, that haven't been fixed yet?

Generally: glibc defines the Linux API pretty much, and we hack against that. I am pretty sure it should be the job for alternative libs to provide compat with that API as much as possible, and the alternative of instead expecting that each and every other package accomodates for limitations for these other libcs is infinitely worse. Fix the source of the problem, don't expect everybody else to work-around it individually instead. Fix the one project responsible for these problems, don't multiply the problem by expecting evreybody else to adjust instead. If each and every libc-using project has to carry its own implementations of functionality musl/dietlibc/ulibc/… doesn't want to support then the net result is more code needs to be maintained by everybody and the overall system footprint and amount of copied code just grows.

The APIs provided by glibc systemd uses are not picked randomly, but because they are very very useful. Note that if there both GNU and POSIX flavours of the same interface and the POSIX flavour is as good as the GNU one we are happy to merge patches that ensure we use the POSIX flavours and not the GNU one (and have done so in the past multiple times, just grep the git history for "musl"), but in general: if something is a good API to use we are happy to use it even if it is Linux (or GNU specific), and we expect other libcs to catch up on it.

Moreover, pretty much all of the more recent additions of glibc APIs systemd uses (for example explicit_bzero()) aren't even glibc so much, as copies from BSD and suchlike. which kinda means they are already somewhat industry standard across UNIXes, and it really should be musl/uclibc/… that needs to catch up there.

We aren't particularly interested in carrying more ifdeffery in systemd than necessary, it makes everything a lot harder to maintain, and is unlikely to help anyway, as such ifdeffery for exotic systems is guaranteed to break sooner or later if no testing infrastructure for it is in place. Moreover, the burden for maintaining the support really shouldn't be on us...

Anyway, long story short: let's talk about individual cases instead, and please always work with musl/uclibc upstreams first, so that they add the missing APIs so that the overall footprint on code, ifdeffery and work is minimized.

Let's close this bug here for now. If you have specific issues, and you are sure that they aren't better fixed in musl/uclibc/… then please file explicit issues and PRs about this, like other folks previously did, for example in #8629, #7218, #5980, …

Thank you for understanding.

**Comment by jameshilliard** [comment]
> This is hardly actionable as it lacks specificity. Do you have specific issues in mind, that haven't been fixed yet?

Most of the [openembedded patches](https://github.com/openembedded/openembedded-core/tree/master/meta/recipes-core/systemd/systemd) for musl support are marked as rejected upstream due to being musl specific. I'm trying to see if there's some acceptable way of providing musl support without having each distro carry a fairly large patchset like that.
> 
> Generally: glibc defines the Linux API pretty much, and we hack against that. I am pretty sure it should be the job for alternative libs to provide compat with that API as much as possible, and the alternative of instead expecting that each and every other package accomodates for limitations for these other libcs is infinitely worse. Fix the source of the problem, don't expect everybody else to work-around it individually instead. Fix the one project responsible for these problems, don't multiply the problem by expecting evreybody else to adjust instead. If each and every libc-using project has to carry its own implementations of functionality musl/dietlibc/ulibc/… doesn't want to support then the net result is more code needs to be maintained by everybody and the overall system footprint and amount of copied code just grows.

On normal desktops/servers I would agree that glibc largely defines the Linux API but I think the situation in the embedded ecosystem is quite a bit different there, especially on very low end devices. In that area you're much more likely to see a busybox userspace with uclibc/musl than a GNU userspace and glibc.
> 
> The APIs provided by glibc systemd uses are not picked randomly, but because they are very very useful. Note that if there both GNU and POSIX flavours of the same interface and the POSIX flavour is as good as the GNU one we are happy to merge patches that ensure we use the POSIX flavours and not the GNU one (and have done so in the past multiple times, just grep the git history for "musl"), but in general: if something is a good API to use we are happy to use it even if it is Linux (or GNU specific), and we expect other libcs to catch up on it.

I don't necessarily disagree that an ideal approach would be to try and get other libc's to add GNU features, however this has effectively failed and I've not seen much in the way of other viable options that would allow for many embedded distros to build systemd on musl(other than attempting to carry maintain their own patchset). 

It's likely that most of the common embedded linux applications you see on devices running musl already carry patches/workarounds for missing glibc functionality or just avoid glibc specific functions in the first place.

While this issue may not be caused by systemd...systemd is in the best position to fix it from what I see.
> 
> Moreover, pretty much all of the more recent additions of glibc APIs systemd uses (for example explicit_bzero()) aren't even glibc so much, as copies from BSD and suchlike. which kinda means they are already somewhat industry standard across UNIXes, and it really should be musl/uclibc/… that needs to catch up there.

Unfortunately it seems musl is intentionally limiting their API to reduce size and would not accept many of those API's.
> 
> We aren't particularly interested in carrying more ifdeffery in systemd than necessary, it makes everything a lot harder to maintain, and is unlikely to help anyway, as such ifdeffery for exotic systems is guaranteed to break sooner or later if no testing infrastructure for it is in place. Moreover, the burden for maintaining the support really shouldn't be on us...

Yeah, I'm unfortunately quite aware of the maintainability issues with ifdeffery to work around portability/compatibility issues, sometimes it's unavoidable though if you want to support certain systems. Would you be open to a pull request to add testing infrastructure for musl/uclibc? There can be some advantages to testing against many libc implementations, it can expose some classes of bugs that otherwise would not be exposed due to implementation quirks in glibc.
> 
> Anyway, long story short: let's talk about individual cases instead, and please always work with musl/uclibc upstreams first, so that they add the missing APIs so that the overall footprint on code, ifdeffery and work is minimized.

What should be done when musl/uclibc upstreams reject missing glibc API's outright?
> 
> Let's close this bug here for now. If you have specific issues, and you are sure that they aren't better fixed in musl/uclibc/… then please file explicit issues and PRs about this, like other folks previously did, for example in #8629, #7218, #5980, …

I think essentially all of the systemd patches in openembedded were already submitted to upstream systemd and rejected for being musl/distro specific. I was wanting to come up with an acceptable approach of improving musl compatibility before working on specific issues since it seems the approach taken in the openembedded patches was not acceptable to systemd upstream.
> 
> Thank you for understanding.


I really like how systemd has standardized management of Linux systems, standardization is something desperately needed in embedded systems world where everyone seems to constantly be reinventing the wheel(the amount of embedded systems vendors that roll their own update systems from scratch is quite scary).

**Comment by keszybz** [comment]
OK, I looked at the first from the openembedded patches at random:
https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0001-Use-getenv-when-secure-versions-are-not-available.patch
First, the function is really just **one** **line**: https://github.com/walac/glibc/blob/master/stdlib/secure-getenv.c#L30. If musl maintainers think this is too much of a burden for them to implement, then maybe openembedded developers should consider maintaining a fork of musl with trivial additions like that.
Second, the patch itself is quite dangerous. It is equivalent to privilege escalation to root in the general case. Maybe for openembedded it is OK, but it is not something that we could ever merge upstream in systemd.

A second one:
https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0001-login-use-parse_uid-when-unmounting-user-runtime-dir.patch
This looks generally useful. Why not submit this here?

A third one:
https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0003-comparison_fn_t-is-glibc-specific-use-raw-signature-.patch
A one-line typedef is missing in musl.

A fourth one:
https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0011-src-basic-missing.h-check-for-missing-__compar_fn_t-.patch
Again, a one-line typedef is missing in musl.

I can only repeat what @poettering said: please submit generally-useful patches here, and try to get musl to add the simple missing stuff. The argument of trying to keep musl lean by rejecting those things is completely bogus, because those are either trivial typedefs or very simple functions. glibc is "bloated" because it provides architecture-specific and heavily optimized implementations, but it is totally OK for alternate libcs to provide the simplest implementation possible.

**Comment by keszybz** [comment]
> I think essentially all of the systemd patches in openembedded were already submitted to upstream systemd and rejected for being musl/distro specific.

I don't think so. At least I don't recall seeing some of those patches.

> Would you be open to a pull request to add testing infrastructure for musl/uclibc?

Yes, that would be welcome.

**Comment by jameshilliard** [comment]
> OK, I looked at the first from the openembedded patches at random:
> https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0001-Use-getenv-when-secure-versions-are-not-available.patch
> First, the function is really just **one** **line**: https://github.com/walac/glibc/blob/master/stdlib/secure-getenv.c#L30. If musl maintainers think this is too much of a burden for them to implement, then maybe openembedded developers should consider maintaining a fork of musl with trivial additions like that.

Well I don't think it's quite that simple due to __libc_enable_secure which doesn't appear to be present in musl. The default [musl return](https://git.musl-libc.org/cgit/musl/tree/src/env/getenv.c#n12) is also different from the [glibc one](https://github.com/walac/glibc/blob/264aad1e6aca30efddfcfae05c44ad38bb5e137d/stdlib/getenv.c#L91) for the regular getenv, I'm unsure if there are security implications there as well.
> Second, the patch itself is quite dangerous. It is equivalent to privilege escalation to root in the general case. Maybe for openembedded it is OK, but it is not something that we could ever merge upstream in systemd.

Yeah, having a proper workaround would def be important...upstream systemd or the libc is probably better suited for handling that due to likely understanding the implications better. Embedded systems very often run everything as root so for some this probably doesn't make a difference, but not all do that at least.
> 
> A second one:
> https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0001-login-use-parse_uid-when-unmounting-user-runtime-dir.patch
> This looks generally useful. Why not submit this here?

That's a backport of #9543 .
> 
> A third one:
> https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0003-comparison_fn_t-is-glibc-specific-use-raw-signature-.patch
> A one-line typedef is missing in musl.
> 
> A fourth one:
> https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/systemd/systemd/0011-src-basic-missing.h-check-for-missing-__compar_fn_t-.patch
> Again, a one-line typedef is missing in musl.

I'll see if I can get those added to musl upstream.
> 
> I can only repeat what @poettering said: please submit generally-useful patches here, and try to get musl to add the simple missing stuff. The argument of trying to keep musl lean by rejecting those things is completely bogus, because those are either trivial typedefs or very simple functions. glibc is "bloated" because it provides architecture-specific and heavily optimized implementations, but it is totally OK for alternate libcs to provide the simplest implementation possible.

Yeah, I don't disagree, I'll see if musl will accept those trivial missing things. I recall reading that those things had been rejected by musl but didn't find anything specific when I looked just now so I could have been thinking of something else that was rejected.
> > I think essentially all of the systemd patches in openembedded were already submitted to upstream systemd and rejected for being musl/distro specific.
> 
> I don't think so. At least I don't recall seeing some of those patches.

The patches mostly appear to be marked with upstream status in them.
> 
> > Would you be open to a pull request to add testing infrastructure for musl/uclibc?
> 
> Yes, that would be welcome.

I'll see what I can do there when I get some more time.

**Comment by poettering** [comment]
> Well I don't think it's quite that simple due to __libc_enable_secure which doesn't appear to be present in musl.

These variables are not really part of the API. whether to provide compat with those or not should be treated separetely from providing secure_getenv()... it could just shortcut things to getauxval(AT_SECURE) directly.

**Comment by poettering** [comment]
> musl is widely used in embedded linux systems including both rack-based servers(and its BMC firmwares) and containers, it's essentially the glibc for non-desktops, where in most of the cases size does matter, it will be great if systemd can officially support musl.

Barking up the wrong tree. Why put this on us? Put it on musl instead and ask them to stop creating these needless incompabilities comapred to musl. I am not sure what people are smoking that they even consider musl with an attitude like this, and I really don't understand what makes you think everyone should change to accomodate for their weird ideas instead of just fixing musl to not do nonsensical incompatibilities like that. If they did, then all of a sudden all projects would just magically work, without having to add messy ifdeffery to *all* of them.

Sorry. Fix musl, don#t make systemd adjust. If musl upstream is toxic, then fork it, or maintain a downstream "portable" copy of it. But dropping this on our doorstep is just unfair.

> make systemd fit for embedded systems(most if not all use musl these days, uclibc, dietlibc etc are rarely deployed now) will also open systemd to an even larger market and benefit us all.

Frankly, if all your choices of software are secondary to your choice of libc, then you are doing IT engineering wrong...

**Comment by poettering** [comment]
> musl stands out as the popular choice for more devices than desktop and servers combined, i.e. those embedded devices where storage and memory usage are constrained, yes it is not 100% glibc compatible, it can't due to its size

Due to its size? That's nonsense. It mostly departs from glibc because it likes to do things differenlty, that has nothing to do with size.

> by supporting musl, systemd will be so much more useful, from embedded to smaller size docker images, some of those embedded devices are actually central to data centers, e.g. openbmc that uses yocto to manage all the server racks, that could be useful if systemd+musl can work well there too as the DCSCM board does not have lots of memory and storage.

Hey, so why don't you direct something similar to musl, that they just fix their pointless incompatibilities and thus make their project a lot more useful in the wide world where systemd exists? It cuts both ways, you know, and by just being compatible they'd save so much more porting work not just for us, but for any project that uses regular Linux APIs

**Comment by richfelker** [comment]
If you're going to accuse us of having "pointless incompatibilities" it would be nice to know what you claim those are.

**Comment by evverx** [comment]
I'm not sure how I ended up being subscribed to this issue but it seems some differences between `glibc` and `musl` are discussed so the last thing I saw was https://github.com/lathiat/avahi/issues/34#issuecomment-1344285882. (I'm not sure it's exactly what was meant here by incompatibilities though).

**Comment by poettering** [comment]
> If you're going to accuse us of having "pointless incompatibilities" it would be nice to know what you claim those are.

Uh, there were many. From the top of my head. getdents64() prototype is pointlessly different in musl than in glibc. The XSI strerror_r() that musl implements exclusively is just nasty to use (error handling in your error path, yuck), GNU definition much better. Pointless missing of GNU comparison_fn_t definition. No parse_printf_format(). No strndupa(). Missing definitionfs for nftw() (FTW_CONTINUE and similar). No AT_SYMLINK_NOFOLLOW on faccessat(). The posix version of basename() is stupid, the GNU one is usable.

**Comment by richfelker** [comment]
> The XSI strerror_r() that musl implements exclusively is just nasty to use (error handling in your error path, yuck), GNU definition much better
> ...
> The posix version of basename() is stupid, the GNU one is usable.

Sounds like glibc is the one that has "pointless incompatibilities" with every other system out there. They could have introduced new interfaces that would be candidates for standardization with their "improvements", but instead they gratuitously made functions with the same names but different behaviors (and even signatures) than the standard ones. Matching that is a non-starter. I'm pretty sure glibc would not do things like that if they had it to do over now. That it happened that way was a historical artifact of the attitude of a single toxic person, who's thankfully moved on, towards compatibility and consensus.

> getdents64() prototype is pointlessly different in musl than in glibc

We don't actually have a "getdents64" at all. The one there is part of the deprecated LFS64 name mapping via macros, which was a bad idea and in the process of being dropped.

We do have a getdents, which differs gratuitously as a historical accident. I'm not sure if this is fixable in an ABI-safe way; if so, we might change it.

But perhaps more to the point, there is almost certainly no good reason to be calling this instead of the portable readdir.

> Pointless missing of GNU comparison_fn_t definition

It's not pointless. Having this definition is completely useless unless you have a guarantee that all systems have it, and you don't. It's not abstacting something that could vary from one implementation to another. It's just facilitating writing code that breaks when you try to compile it somewhere other than GNU/Linux. Catching that and getting it fixed is one of the features of musl.

> No parse_printf_format().

This is completely random functionality orthogonal to anything in libc, and the glibc interface is both bitrotted (lacking support for recent additions to printf, or at least they're undocumented) and overly coupled with glibc's printf implementation's handling of arguments. No program but systemd has ever deman^H^H^H^H^Hrequested us to support this.

> No strndupa().

This is purely a macro. Programs that want it can define their own, and already need to do this to be portable to BSDs etc. We will probably be removing the strdupa macro too since both of these are inherently unsafe (as is basically all use of alloca) and all existing programs that are remotely portable provide their own definitions if they want it.

> Missing definitionfs for nftw() (FTW_CONTINUE and similar).

These may be considered. Our `nftw` is due for some major changes to deal with unwanted/unsafe stack usage via recursion. But this is another case where systemd is basically the only project we've seen requests to add these for. Our criteria for inclusion of nonstandard functionality generally require relevance to a significant number of real-world programs.

> No AT_SYMLINK_NOFOLLOW on faccessat().

This is supported on any kernel with the faccessat2 syscall. On kernels too old to have that, very nasty emulation is needed to implement flags at all, and since AT_SYMLINK_NOFOLLOW was not among the standard flags for this function, we didn't bother to do that one.

**Comment by saolof** [comment]
I like the focus on individual examples in the latter part of the conversation. One thing I am noticing in them is that there seems to be three categories of non-posix glibc APIs:

1) Functions that can be exported portably and which are actually quite useful to have in a standard library for a sane language, like comparison_fn_t . C is unfortunately not always that sane, but having extensions for somewhat generic code is useful.
2) Cases where glibc behaves differently from every other libc in existence (i.e. the application developers nightmare), like getbase 
3) Functions that are not portable because they are literally just a syscall, like getdents

I feel that category 1) is something that musl could plausibly support to facilitate migrating glibc applications. Category 2 is just a nightmare and not something you can really do much about. Category 3 naturally belongs in a separate library from the libc imo, much like how you would go to liburing for io_uring wrapper functions instead of expecting glibc to wrap that
