### ISSUE TITLE
systemd-boot color menu customization

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#10139]
**Is your feature request related to a problem? Please describe.**
Colors shown by systemd-boot are hardcoded and can't be changed via parameters 

**Describe the solution you'd like**
Maybe adding a new option for bootctl.

**Describe alternatives you've considered**
Grub can do it

Thanks

**Comment by poettering** [comment]
I am not sure a boot loader needs to support coloring themes... it's a boot loader, not a desktop UI.

**Comment by ryandward** [comment]
Meh. I would actually like to see something minimal implemented, some of my very non-techy coworkers think their system is reporting errors when they see a black screen with white writing.

**Comment by msmafra** [comment]
Hum! Theming the boot loader besides being cool is I find it necessary if you're going to install it for people that is coming from other systems, for example. MacOS or Windows users, common non technical ones, see that on their screens and it looks like problems, like last minute solution. It should just be that way when you have a problem. For that matter I don't like to see a plain GRUB. Simple theming like OpenSUSE or Manjaro, for example, helps a lot.

**Comment by izzy** [comment]
It's 2020 and this still hasn't gotten any consideration. Just.. What? 

And it's not just about non-tech workers. Not everyone has an aversion to good design and not everyone ignores the fact that good graphical design is a feature beyond aesthetics. Not to mention quite a few people see their bootloader on more occasions(dual boot is a thing, as is regular kernel/distro switching)

**Comment by vcaputo** [comment]
@izzy I'm pretty sure if someone created a PR sanely implementing configurable colors it would receive fair consideration.

**Comment by Batcastle** [comment]
Throwing my opinion in the ring since this issue is still open in 2021. 

As a distro maintainer for a distro that uses `systemd-boot` out of the box, having the ability to theme it would make the entire experience feel much more polished and cohesive. Some sort of basic configuration to change the coloration of the text and text background can go a long way to making a distro look better. Beyond that, as others have said, it would also make it so user can easily tell from the color of text if something has gone wrong.

While it may be a bit of a hassle to implement, this would be a welcome addition in my book!

**Comment by msmafra** [comment]
Hello there!

Some distros, like Fedora that uses Plymouth, are setting GRUB's default behaviour to hide the menu if not called or if is not a boot because of some error. That is already a good presentation. But even doing it, showing a menu in black with white text (wouldn't matter the combinations of colours in my opinion) is an alarming thing even if one rebooted from the logging screen (which is treated as a failed boot).
Showing a distro themed menu is less alarming and one can understand better what's happening showing some integration. Or a friend's computer that one installed some distro in dual-boot with Windows and wants to reboot to change systems. Even BIOS (UEFI) these days have a more (some with few unnecessary) readable, friendly interface.

Things like that and systemd-boot graphical integration (most likely DE's integration) to select from the shutdown menu where to go to.

Rambling... better stop :)

**Comment by jatin-cbs** [comment]
:+1:  for this ! systemd-boot is great and is not an overwhelming boot loader/menu. Distros that use this by default are Pop OS and  the default Arch installation (in the guided installer as well).

I would love to see some themes/color customization like we have in GRUB. Distros that do this by default are Debian, Kali Linux, Open SUSE.

**Comment by Icy-Thought** [comment]
> :+1:  for this ! 
> 
> I would love to see some themes/color customization like we have in GRUB. Distros that do this by default are Debian, Kali Linux, Open SUSE.  They all have a but themed boot menu which is missing in systemd-boot.
> 
> systemd-boot is great and is not an overwhelming boot loader/menu. Distros that use this by default are Pop OS and  the default Arch installation (in the guided installer as well). 
> 
> 

Juding by their previous reaction towards this request, you should either give up or submit a PR and hope for the best.

Not the solution you are looking for? Use either Grub or rEFInd to fulfill your needs!

**Comment by q2dg** [comment]
Just compile-time support has merged. Is it intended? Thanks

**Comment by ChrisTitusTech** [comment]
I know many Linux desktop users Dual boot and without themes support Grub will always be the preferred option.

**Comment by NovaViper** [comment]
> Just compile-time support has merged. Is it intended? Thanks

How do you go about changing the colors? Also thanks for merging the patch!

**Comment by walderf** [comment]
> > Just compile-time support has merged. Is it intended? Thanks
> 
> How do you go about changing the colors? Also thanks for merging the patch!

did you ever figure this out?

**Comment by NovaViper** [comment]
> > > Just compile-time support has merged. Is it intended? Thanks
> > 
> > 
> > How do you go about changing the colors? Also thanks for merging the patch!
> 
> did you ever figure this out?

No, I didn't. I eventually just jumped back to Grub

**Comment by marfier** [comment]
Assuming the merge actually implemented this feature, is there any official documentation we can reference?

**Comment by aaronliu0130** [comment]
You'd have to [use meson to set the options](https://mesonbuild.com/Commands.html) specified in the commit's alterations to [meson_options.txt](https://github.com/systemd/systemd/commit/e313e934db2baab43f64ad47b8c4be3c3e746b46#diff-76ea9078099f2ee8cc0e760a874dd153f225ba16ad10375c24ab6cd53518f3c4)

**Comment by max-ishere** [comment]
I want themes too, it's one of the reasons I'm hesitant to switch to systemd-boot.

One of my goals recently is to make the boot process as modern looking on my system as it is on cool distros/win/mac. I don't remember what the menu looks like but probably not the way I want it to be. My stock bios menu looks like a real gui (with mouse support!) and I want that in my next bootloader too (I mean the cool look, not mouse support).

**Comment by samuelvw01** [comment]
> My stock bios menu looks like a real gui (with mouse support!) and I want that in my next bootloader too (I mean the cool look, not mouse support).

Actually, having a mouse support in systemd-boot isn't a bad idea.

**Comment by aaronliu0130** [comment]
Systemd-boot currently has a minimal TUI interface that relies on text mode, which can be processed by the machine natively. Turning it into a GUI, which would also be necessary for a mouse, or even just adding support for displaying every pixel of an image (without stuff like TerminalImageViewer), would require rewriting a lot of stuff, probably including the addition of a display interface.

**Comment by SalvatoreNoschese** [comment]
just a background wallpaper + custom icon by entry id will be a good improvement.

**Comment by mahyarmirrashed** [comment]
I wanted to follow up on this. Is it possible to allow base16 colours? (16x16x16 goes far.) If it doesn't use ASCII (and instead uses UTF-8), then we could add patched fonts with logos of the major distros.
