### ISSUE TITLE
Please adopt the Code of Conduct

### ISSUE THREAD

**Issue by amandahnb** [systemd/systemd#10148]
As a non-binary transgender person I am deeply concerned by lack of diversity in the systemd project. It does not look like a safe space for marginalized groups.

Linux kernel community has successfully adopted the CoC recently. Please share their success and send the signal that your project welcoming and inclusive.

I strongly suggest to use this most popular https://github.com/ContributorCovenant/contributor_covenant developed by wonderful @CoralineAda

**Comment by keszybz** [comment]
I am concerned by the lack of diversity in systemd project too. The "contributor covenant" is quite good, and if decide to adopt anything, it would certainly be a good choice. Nevertheless, I don't think a lack of a CoC has anything to do with the lack of diversity in this project, since we seem to be getting along politely without codified rules. If you have any examples to the contrary, I would be very interested to see them.

We'll discuss during the upcoming AllSystemsGo conference in Berlin. You — and anyone else — is welcome to join.

**Comment by alban** [comment]
I think the CoC is a good idea too. It seems good to me to signal we agree with the text. Of course that would not solve everything but I don't see any downsides.

I'd like to join that discussion at AllSystemsGo too. Will it be on the Sunday?

**Comment by kirbyfan64** [comment]
As a Hispanic person living in an area where we're *definitely* a minority... I'd say that feeling safe largely correlates with the mods and community, not necessarily a CoC's presence. 

On that note, I really like Ruby's, because it leaves enough to human discretion (which is the only thing that can accurately judge human behavior) rather than codified rules. 

Personally, the community *not* being racist morons is enough for me. ¯\\\_(ツ)\\_/¯

**Comment by keszybz** [comment]
> I'd like to join that discussion at AllSystemsGo too. Will it be on the Sunday?

There are two possibilities: Thursday during bpf hackfest, and Sunday morning.

**Comment by Kiyuubi** [comment]
Please don't bring politics into code.

**Comment by okeesan9012124** [comment]
I agree with Kiyuubi, it's not a great idea to bring politics into these kinds of projects. I think rules can be a good idea if you want to set some standards for equal treatment and have some ways to make sure people do not be offensive. However, I also don't think developers who happen to be a minority should be given more power simply because they are making it more diverse; rather everyone should be treated as equals and things should be based on people's coding skills/contributions rather than whether or not they are a minority. It's coding, we should keep the focus on good coding regardless of gender identity, ethnicity, race, orientation, etc. I think the goal of equality and inclusivity is a better goal than diversity, as equality treats everyone equally and diversity treats people different based on their background and lifestyle.

**Comment by GioMetal** [comment]
Is this a bug? Why is this an issue on something that should report problems with code only?

**Comment by poettering** [comment]
I will pre-emptively lock the discussion on this issue now, as this topic looks like something that might quickly attract the worst kind of offenders, and shows signs of already doing so.

Let's discuss this offline at the systemd hackfest at All Systems Go! on sunday. Many systemd core contributors will be around then, and I think discussing this off-line is a much better approach than doing so online where things could be derailed easily.

Regarding the actual request made here: we regularly have blocked people on the github project page who have misbehave beyond limits (in fact I have even reported a number to github maintainers as well, if it has been too bad), as well as blocked/moderated people who did so on the mailing list. I am very sure this is the right and necessary thing to do if we want to keep our community a nice and civil place. So far the standards by which we did so have been intransparent, i.e. we, the administrators of these forums, have done so by ad-hoc rules, if we felt the transgression went too far. I figure it's not a bad idea to formalize this somewhat through a CoC.

**Comment by poettering** [comment]
> Is this a bug? Why is this an issue on something that should report problems with code only?

This is a general request tracker. We have no other, hence I think it's fine to make such a request here. We have previously discussed licensing issues here too, which isn't strictly relevant to the technical side either.
