### ISSUE TITLE
systemd-nspawn should support IPv6 too for exposing ports (currently it only does ipv4)

### ISSUE THREAD

**Issue by Ejxqzgds** [systemd/systemd#10254]
The following entry in an `.nspawn` file leads to forwarding IPv4 TCP port, but not IPv6:
```
Port=tcp:1234:1234
```
AFAIK, there is not even support for IPv6 port forwarding. IMHO, the statement should forward both protocol ports equally, which is probably most useful when running exposed services in a container.

Thanks for considering!

**Comment by Ejxqzgds** [comment]
Thanks, Lennart, for the better issue title!

**Comment by mikroskeem** [comment]
Any updates on this?

**Comment by eliasp** [comment]
I ran into a few trouble due to this, as my applications just used whatever `systemd-resolved` returned when resolving names of machines.
I worked around it for now in my Ubuntu 18.04 machines by doing:
- `cp -rp /usr/lib/systemd/network/80-container-host0.network /etc/systemd/network/80-container-host0.network`
- Set `LinkLocalAddressing=yes` in the `[Network]` section to `ipv4`
- restarting the corresponding machine

**Comment by lahwaacz** [comment]
@eliasp How is domain resolution relevant to this? The port mapping is done with iptables rules such as

    iptables -t nat -A PREROUTING -p tcp -m tcp --dport 8000 -m addrtype --dst-type LOCAL -j DNAT --to-destination 192.168.62.233:80
    iptables -t nat -A OUTPUT ! -d 127.0.0.0/8 -p tcp -m tcp --dport 8000 -m addrtype --dst-type LOCAL -j DNAT --to-destination 192.168.62.233:80

So ports on _localhost_ are remapped into the container. Once you resolve the container name and get its address, you don't talk to localhost and there is nothing to remap.
