### ISSUE TITLE
Asynchronous logging support in journald

### ISSUE THREAD

**Issue by a13xb** [systemd/systemd#10301]
**Is your feature request related to a problem? Please describe.**
Processes running on the same machine keep logging off the main codepath. They take a high-precision timestamp at the call site, but offload actual formatting and writing into a separate thread. Problem: journald doesn't seem to support the process supplying its own timestamp, and journald's own timestamp will be off, and messages may appear out of order from different processes.

**Describe the solution you'd like**
Structured log writes could include a timestamp field supplied by the process itself that would take precedence over the timestamp taken by journald.

**Describe alternatives you've considered**
I considered just including "actual" timestamp in a custom field when writing a structured log, but that means I lose the ability to use standard tools, e.g. easily inspect logs with journalctl and have logs in chronological order.

**Comment by poettering** [comment]
the journal does store the send timestamp to all log messages received by the syslog or native protocols as the `_SOURCE_REALTIME_TIMESTAMP=` field (as supplied by the kernel). If the syslog protocol is used we also store the original sender-supplied timestamp in the `SYSLOG_TIMESTAMP=` field away (in order to be able to fully reproduce the original byte string we received from the journal data).

We do not reorder messages by either of that though. At reception time this would mean having to add jitter buffers which is nasty and can only work within bounds anyway. And at display time it also contradicts the "endless stream" style of access...

When the journal receives log data from a service's stdout/stderr then it will have neither timestamp, as the kernel does not embedd timestamp info in such streams and the sender usually sends free-form text data without any such info included.

Hence, we pretty much do whatever we can do already, and I do not see how we can provide anything better or more reliable there...

(if your app sends log data through the native protocol, then you can add in SYSLOG_TIMESTAMP= yourself btw, just make sure you follow classic syslog-style timezone-less formatting, which is nasty, but what can we do...)

**Comment by poettering** [comment]
Anyway, closing as I really don't see anything we can do here... Sorry!

**Comment by a13xb** [comment]
The journal can't be ordered by `SYSLOG_TIMESTAMP`, correct?

**Comment by poettering** [comment]
we don't support that, no, see my earlier comment.

**Comment by woodz-** [comment]
@a13xb: are you logging on per process basis or on per thread basis?

If per process basis, you might have a look on the [namespace mechanism](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html#Journal%20Namespaces).

It enables you for each of your custom processes to have a separate logging service process. This kind of isolation guarantees, that on any time only one process writes to one journal. Thus you can be sure to have an ascending ordered time base (when using `_SOURCE_REALTIME_TIMESTAMP`).

When querying one namespace journal you give a `journalctl --namespce <myns>` argument.
The downside is (AFAIK), you cannot merge all namespace journals to one big one for inspection.
But the [journal API](https://www.freedesktop.org/software/systemd/man/sd_journal.html#) supports it.
