### ISSUE TITLE
Release uploading at freedesktop.org

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#10405]
Either upload recent releases at https://www.freedesktop.org/software/systemd/ or delete all releases from there.  The current situation is inconsistent.

**Comment by poettering** [comment]
We changed our release model some time in 2015. Previously we used automake's "make dist" to build release tarballs (which meant an additional build step, and non-reproducible releases), while today we just tag releases (in order to simplify stuff and to keep things perfectly reproducible). Since old distribution's packages might reference the old versions of the tarballs upstream we really need to keep them around, but we also odn't want to generate tarballs like that for new releases.

hence, sorry, but we simply changed the mode of operation and we should neither forget the history, nor fake it...

Sorry!

**Comment by dilyanpalauzov** [comment]
That is fine.  Include there a file, stating where the current releases can be found.

**Comment by dilyanpalauzov** [comment]
For the old distribution packages referencing ald releases, send 302 redirect to github with the releases, otherwise that file can be overseen and people can unintentionally install old systemd.

**Comment by poettering** [comment]
> That is fine. Include there a file, stating where the current releases can be found.

I added a file `RELEASES_HAVE_MOVED` now to that dir. I hope people look there.

Sorry, but I do not have control over the web server, I can't set up 302 redirects for you. Also I don't think that's really advisable, the directory should really stay around the way it is, for old releases.

And given that systemd is a very core component of the OS, not an app people install I think we can expect that folks build it from sources are careful enough to figure out whether the software they are using is three years old or not...
