### ISSUE TITLE
The ability to know if a process is stopped

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#10458]
I run a transient unit and I send a SIGSTOP using `systemctl --user --signal=STOP kill myunit.service`. I checked the properties of the running unit to see if something changed and I didn't find anything relevant. I would like to send a SIGCONT if the process is stopped and a SIGSTOP if the process is running.

It would be nice to find out if my process received the SIGSTOP using systemd tools rather than ps, pgrep, grep, awk etc.

**Comment by boucman** [comment]
well, that only makes sense if your service has a single process. If there are multiple processes, the concept of "the service is stopped" makes very little sense and I don't know what systemd would/should report in that case...

**Comment by pr10n** [comment]
Well, there is, for example, a ExecMainPID.

**Comment by boucman** [comment]
That would allow to publish the status of the main process, but that's not the only process in a service. A service can be a lot of processes. User sessions are a single service (for the system instance of systemd) and the have all the user's processes, shells, desktop etc... A single "is stopped" status doesn't really make sense to me...

**Comment by pr10n** [comment]
Doesn't `MainPIDStopped` with yes/no as values, for example, make sense?

**Comment by poettering** [comment]
systemd manages services, not individual processes, and I am very sure we shouldn't blur that line, it's just skewed, if people would assume a service was fully paused just because one of the processes making it up is paused.

So, I am sorry, but I don't think we should implement what you are asking for.

That said, I think it would make a ton of sense to expose a new "freezed" state or so as soon as cgroupsv2 adds support for the freezer again and a usable fashion. In that case we could add "systemctl freeze" and "systemctl thaw" or so as high level verbs and show the freezer state in "systemctl status".

**Comment by pr10n** [comment]
Well, I don't know who could possibly be confused by "MainPIDStopped". The name itself **shouts** that solely the main pid in the service is stopped.
