### ISSUE TITLE
something is wrong with the i386 version of the ubuntu Ci 

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#10497]
Something seems to be wrong with lightdm in Ubuntu, and that since quite a while.

See this for example:

https://github.com/systemd/systemd/pull/10476
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/i386/s/systemd-upstream/20181021_052721_5709e@/log.gz

```
Oct 21 04:44:40 autopkgtest lightdm[431]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
Oct 21 04:44:40 autopkgtest systemd[1]: Started Light Display Manager.
Oct 21 04:44:41 autopkgtest lightdm[446]: PAM unable to dlopen(pam_gnome_keyring.so): /lib/security/pam_gnome_keyring.so: cannot open shared object file: No such file or directory
Oct 21 04:44:41 autopkgtest lightdm[446]: PAM adding faulty module: pam_gnome_keyring.so
Oct 21 04:44:41 autopkgtest lightdm[446]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
Oct 21 04:44:41 autopkgtest lightdm[446]: PAM adding faulty module: pam_kwallet.so
Oct 21 04:44:41 autopkgtest lightdm[446]: PAM unable to dlopen(pam_kwallet5.so): /lib/security/pam_kwallet5.so: cannot open shared object file: No such file or directory
Oct 21 04:44:41 autopkgtest lightdm[446]: PAM adding faulty module: pam_kwallet5.so
Oct 21 04:44:41 autopkgtest lightdm[446]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
Oct 21 04:44:41 autopkgtest lightdm[446]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)
Oct 21 04:44:43 autopkgtest systemd[1]: lightdm.service: Main process exited, code=exited, status=1/FAILURE
Oct 21 04:44:43 autopkgtest systemd[1]: lightdm.service: Failed with result 'exit-code'.
Oct 21 04:44:43 autopkgtest systemd[1]: lightdm.service: Service RestartSec=100ms expired, scheduling restart.
Oct 21 04:44:43 autopkgtest systemd[1]: lightdm.service: Scheduled restart job, restart counter is at 1.
```

It appears accounts-service is missing from the image for some reason?

**Comment by poettering** [comment]
@martinpitt @xnox any idea about this?

**Comment by martinpitt** [comment]
The "accountsservice" package is not installed in the [amd64 test run](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/amd64/s/systemd-upstream/20181024_124641_0abe5@/log.gz) either, so that might be a red herring.

But let's try: I [added an accountsservice test dependency](https://salsa.debian.org/systemd-team/systemd/commit/42a377a7f5dd), and now wait until it gets imported into the [mirror that the tests use](https://code.launchpad.net/~pitti/systemd/+git/debian) (perhaps we can get rid of that now). Then I'll retrigger a failed test, and we see how it goes.

**Comment by martinpitt** [comment]
I retriggered i386 test on #10501 using the original debian salsa git repo. I hope the networking issue that caused the git clone to take like half an hour (from the old alioth git repo) is gone now, so if that works, we can kill the cloned git repo on Launchpad.

**Comment by xnox** [comment]
@poettering lightdm is removed from the test in favor of gdm3 in all ubuntu-archive builds, and ubuntu archive tests.... I believe debian edition of the tests has not merged that change in.

**Comment by xnox** [comment]
It is a bit odd that ubuntu's and debian's packaging has diverged a bit lately, especially bits in autopkgtests, and that debian's repo is pulled instead of an ubuntu's one to fetch the tests.

**Comment by martinpitt** [comment]
@xnox: I was not aware of that; if they permanently diverge (that would be sad), then I suppose the webhooks should be updated to point to the ubuntu git. Or is that a temporary thing? I honestly don't want to encourage a long-term delta there.. I checked the diff between debian's tests and [ubuntu's](https://git.launchpad.net/ubuntu/+source/systemd/tree/debian/tests); some stuff (like using gdm instead of lightdm) seems fine, but there is a lot of obviously obsolete stuff and temporary hacks, which should not be applied to upstream testing.

I tried to reproduce this locally:

    autopkgtest-buildvm-ubuntu-cloud -r bionic -a i386
    autopkgtest --test-name boot-and-services systemd -- qemu autopkgtest-bionic-i386.img

and the test succeeds. So apparently that's something specific to the BootStack VMs, maybe slightly different CPU/graphics emulation?

I pushed the change to [use gdm instead of lightdm](https://salsa.debian.org/systemd-team/systemd/commit/1044f758b66c1d09). This works fine for me locally, let's see how that fares on the infra.

**Comment by robert-ancell** [comment]
@poettering the logs are written to `/var/log/lightdm` (which reminds me I really should support the journal at some point). Hopefully you can extract them from the CI?

**Comment by martinpitt** [comment]
PR #10522 succeeded now on [i386](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-pitti-systemd-semaphore/bionic/i386/s/systemd-upstream/20181025_223028_89479@/log.gz;) the amd64 test worked as well.

Moreover, git clone from salsa directly is now fast, so we can get rid of the git mirror on Launchpad \o/.  I changed the webhooks accordingly. @mbiebl, @xnox: That now means that every change committed to https://salsa.debian.org/systemd-team/systemd will directly apply to CI here.

**Comment by martinpitt** [comment]
I retried the i386 tests of the current PRs where it made sense, and marked a few "harmless" ones as ci-failure-appears-unrelated (after checking they only failed on the lightdm issue).

**Comment by martinpitt** [comment]
@poettering, @keszybz : I updated http://piware.de/tools/bin/retry-gh-systemd-test for the new URL (not using the mirror any more). If you use this script, please update your local copy. At some point I'll remove the git mirror.

**Comment by keszybz** [comment]
Thanks, I updated my copy of the script.
