### ISSUE TITLE
udev: uscmisc devices missing builtin parameters

### ISSUE THREAD

**Issue by christersson** [systemd/systemd#10515]
I would expect devices of the "usbmisc" subsystem (which necessarily sit on a USB bus) to receive the standard USB builtin parameters... ID_BUS, ID_USB_INTERFACE_NUM, etc.  Instead, they end up with just the following:

udevadm info --query all --name cdc-wdm0
P: /devices/pci0000:00/0000:00:1c.4/0000:03:00.0/0000:04:02.0/0000:39:00.0/usb3/3-1/3-1:1.4/usbmisc/cdc-wdm0
N: cdc-wdm0
E: DEVNAME=/dev/cdc-wdm0
E: DEVPATH=/devices/pci0000:00/0000:00:1c.4/0000:03:00.0/0000:04:02.0/0000:39:00.0/usb3/3-1/3-1:1.4/usbmisc/cdc-wdm0
E: ID_MM_CANDIDATE=1
E: MAJOR=180
E: MINOR=0
E: SUBSYSTEM=usbmisc
E: USEC_INITIALIZED=585543158474

The udev code seems to determine which builtin commands to run on the device based on some token received from the kernel via netlink (?), but it's not clear to me what decision actually leads to the USB builtins being applied.  So this bug report boils down to:

i)  Can you confirm that I'm not mistaken in thinking that the 'usbmisc' devices should be receiving these parameters.
ii)  Could someone familiar with the udev code see to it that these parameters be applied?

**Comment by poettering** [comment]
Only USB devices for which a udev rule does `IMPORT{builtin}="usb_id"` will get these properties. At least in systemd upstream there is no rule shippfed by default that does that for `usbmisc` devices afaics.

If it makes sense to add that (i.e. something actually using that, for example to do by-path device nodes or such) then by all means send a PR adding it, but this is all strictly opt-in: devices for which no rules are supplied won't get this stuff...

Anyway, closing this, since there isn't really a bug here and things do work the way they should.
