### ISSUE TITLE
nspawn fails with "Short read while reading cgroup mode."

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#10526]
```console
$ sudo systemd-nspawn -i image
Spawning container image on /home/zbyszek/src/mkosi/image.
Press ^] three times within 1s to kill container.
Short read while reading cgroup mode.
```

I'm at a loss how to debug this. Seems to some kind of race, because it fails in maybe 25% of tries.

This is with systemd-nspawn from git.

Additional info: I have unified cgroups v2 on the host, and "image" is a squashfs image from mkosi.

**Comment by poettering** [comment]
do you have an strace of this maybe?

**Comment by poettering** [comment]
my edcuated guess is that something else actually fails, and causes the child to die, so that nspawn's main process when reading from the fd that the cgroup mode is supposed to be passed across gets EOF and that results in the message you see...

question though is what precisely fails there.

if this is a race, maybe strace will hide it, in that case, does SYSTEMD_LOG_LEVEL=debug show more?

**Comment by yuwata** [comment]
Could you try to boot with 'udev.children_max=1'?

**Comment by keszybz** [comment]
I didn't want to reboot, so I added parsing of "children-max" to udev.conf. See #10759.

> Could you try to boot with 'udev.children_max=1'?

Doesn't seem to make a difference.

BTW, I find it fairly easy to reproduce with:
```bash
for i in {1..40}; do sudo build/systemd-nspawn -i ~/src/mkosi/fedora29/fedora28.2018.11.06.amd64.snap echo || break;done
```
It usually fails within the first 5 iterations of the loop.

**Comment by poettering** [comment]
hmm, if you do that test with current nspawn but udev/systemd and so on from v239, does it work there?

**Comment by yuwata** [comment]
Yeah, this seems an independent issue...

**Comment by yuwata** [comment]
Does #10919 help this issue?

**Comment by keszybz** [comment]
> Does #10919 help this issue?

Doesn't seem to have an effect. I see the same behaviour with current git master.

**Comment by poettering** [comment]
So, is this still reproducible? I am running systemd git on my laptop, and I issue this:

```
# for i in {1..400}; do echo $i ; sudo build/systemd-nspawn -i image.raw echo || break;done
```

and easily reach the 400... seems totally stable to me with nspawn, pid1, udev from current git.

**Comment by keszybz** [comment]
Still reproducible with current git master.

Good news is that `systemctl restart systemd-udevd` doesn't immediately bring down gnome-shell. I'm very pleasantly surprised.

I even restarted the machine to make sure everything is fresh.

**Comment by poettering** [comment]
> Still reproducible with current git master.

urks, so what do we do about this now? I can't reproduce this here, not sure what I can do to get this closed.

Can you provide the debug log when this happens as well as an output of "strace -f -s 500"?

**Comment by coling** [comment]
It would be lovely if this fix made it into RHEL8 (and eventually CentOS 8).... if someone happens to know the maintainer. Sadly I don't have an appropriate license to request this myself via RHEL BZ (although I should really set that up). Been sufferning from this issue for ages and can't work out why some mkosi container images I build work fine and others always fail - so odd, but hoping this fix puts it to bed.

**Comment by coling** [comment]
> It would be lovely if this fix made it into RHEL8 (and eventually CentOS 8).... if someone happens to know the maintainer. Sadly I don't have an appropriate license to request this myself via RHEL BZ (although I should really set that up). Been sufferning from this issue for ages and can't work out why some mkosi container images I build work fine and others always fail - so odd, but hoping this fix puts it to bed.

FTR, adding these patches to the systemd in RHEL 8 is a pain. Lots of changes here so it's not an easy job.

On the plus side, while this bug *might* be an issue sometimes (it's a race after all), I've discovered that although the symptoms were the same for me, the actual issue I had in the end turned out to be different. I'm running gpt_squashfs containers made via mkosi. The machine I was building them on at some point had it's mksquashfs updated. It changed the default compression method from xz to zstd. This caused the resulting container not to run inside CentOS 8 where zstd+squashfs doesn't work. A quick check of systemd-dissect on the build vs run host showed very different results. Forcing Compress=xz worked a treat.

Just documenting this for anyone else who may get tripped up!!
