### ISSUE TITLE
systemd-sysctl: respecting duplicate value assignments in custom .conf

### ISSUE THREAD

**Issue by justinrernst** [systemd/systemd#10521]
We've run into a fairly specific corner case with systemd-sysctl

On our machines we have a custom .conf that sets:
 kernel.perf_event_max_sample_rate = 10000
 kernel.perf_cpu_time_max_percent = 0
 
Because of kernel patch ab7fdefba6, we are unable to set kernel.perf_event_max_sample_rate = 10000 when kernel.perf_cpu_time_max_percent = 0.
Our custom .conf is successfully applied on boot as kernel.perf_cpu_time_max_percent != 0 yet, but subsequent restarts of systemd-sysctl cause failures in the form of:

Oct 24 17:08:53 systemd[1]: Starting Apply Kernel Variables...
Oct 24 17:08:53 systemd-sysctl[13074]: Failed to write '10000' to '/proc/sys/kernel/perf_event_max_sample_rate': Invalid argument
Oct 24 17:08:53 systemd[1]: systemd-sysctl.service: main process exited, code=exited, status=1/FAILURE
Oct 24 17:08:53 systemd[1]: Failed to start Apply Kernel Variables.
Oct 24 17:08:53 systemd[1]: Unit systemd-sysctl.service entered failed state.
Oct 24 17:08:53 systemd[1]: systemd-sysctl.service failed.

We've hit the code introduced by the kernel patch. In an attempt to work around the issue, we changed our custom .conf to:
 kernel.perf_cpu_time_max_percent = 25
 kernel.perf_event_max_sample_rate = 10000
 kernel.perf_cpu_time_max_percent = 0
 
What we have found is that systemd-sysctl removes duplicate variables, using the last listed version. And so our kernel.perf_cpu_time_max_percent = 25 does not apply, and we receive the same failed state for systemd-sysctl.
sysctl does not remove duplicate variables, and so running "sysctl -p foo.conf" results in each of the variables being set, in order, and no errors appearing.

Are there any current methods for making systemd-sysctl behave in the same manner as sysctl when it comes to setting variables from custom .conf files?
If not, could there be? It would be an option to the user.

Thanks

**Comment by coretemp** [comment]
This just sounds like misery that you have created yourself and now you expect systemd to fix that for you. Please just close this.

**Comment by poettering** [comment]
Urks, this sounds like a really really bad idea from the kernel side, they should not do APIs like this, seriously: how is userspace supposed to know? We cannot possibly keep a database in which order the kernel expects which sysctls to be written...

We expect sysctls to be purely declarative, which allows us to do nice things, such as conflict detection in systemd-sysctl, i.e. filter out conflicting settings and log about it. And that's kinda important, since the tool combines data from multiple drop-ins, i.e. the focus is clearly on merging data from multiple sources. If these settings now suddenly require a specific algorithm for writing all that falls apart.

Quite frankly, the kernel guys should really fix their API in this regard. Any chance you can file a bug against the kernel? (I don't have high hopes they'll fix it, but this should be attempted at least).

So I am pretty sure we shouldn't change the logic in systemd-sysctl regarding this, sysctls have been declarative so far, and that's a good thing. The kernel should be fixed instead, and either accept the controls to be written in any order, or export somewhere the order in which they want stuff to be written, if they really want this to be written by an iterative program rather than being declarative.

If you need a short term fix, I'd suggest to use a shell script for these two options, and write to sysctl directly in the right order. I mean, if the kernel requires programmatic behaviour from userspace when writing these, then I think a shell script is an appropriate option. Sorry if this is disappointing :-(

Yes, this sucks, but I don't think there's anything to do on our side really regarding this. Hence I will close this now. I hope this makes some sense? Sorry if this is not very satisfying...
