### ISSUE TITLE
flicker-free and smooth transition with UEFI->systemd-boot->plymouth->DM

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#10666]
**Is your feature request related to a problem? Please describe.**
Currently we got flickers during screen transition like UEFI->systemd-boot->plymouth->DM for non-fedora distro.

**Describe the solution you'd like**
We need a general solution for flicker-free and smooth transition with UEFI->systemd-boot->plymouth->DM
For example: [Fedora Demo](http://www.phoronix.com/scan.php?page=news_item&px=Plymouth-0.9.4-Released)

Concretely,
1. For systemd-boot, the loader menu needs to be hidden unless any key is pressed.
2. Able to change monitor refresh rate during UEFI stage.

**Describe alternatives you've considered**

**Comment by poettering** [comment]
Both is already implemented. If the timeout is off, then we won't initialize the screen at all. Moreover we check the kbd for keypresses and show the menu if any key is pressed at the moment sd-boot is initialized, and then react to that. This even allows some nice tricks we implemented. For example, if you press the "w" key while sd-boot initializes then sd-boot boots directly into windows if that exists.

in very recent sd-boot (since #8086 got merged) there's also the console-mode option in loader.conf to tweak the screen resolution if necessary.

Hence, I think everything needed should already be there. Closing hence.
