### ISSUE TITLE
[RFE] If unprivileged systemd-nspawn are'nt possible, at least offer a privileged "systemd-nspawn" user group to be able to run containers without sudo

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#10680]
I'm a teacher in a computer science school where students aren't administrator of their machines. They do everything in VMs but it's a pity. So I would like to give them the possibility to run systemd-nspawn containers to they could be "root" user inside them to be able to do everything in a much more comfortable manner. But systemd-nspawn command (and many options of machinectl command too) only work with sudo, so I'm stuck. On the other hand, I've read here and in mailist that systemd-nspawn can't be run by a regular user so...I throw the question: could it be possible to use a "systemd-nspawn" group of users to put inside regular ones to give them the ability of running systemd-nspawn command without using sudo? Something like systemd-journald does with the "systemd-journal" group or LXC/LXD does with the "lxd" group (in Ubuntu, at least). Thanks a lot!

**Comment by poettering** [comment]
access management through UNIX groups is highly problematic, since you can never take away privs again anymore like that (since users can create setgid binaries that gives them back the privs whenever they want.)

Moreover, doing something like this means to either have suid binaries in place or a centralized daemon. that checks client credentials. We really don't want to have new suid binaries however. Which leaves the centralized daemon idea... Now, there's already "systemd-machined" for that, with its client tool "machinectl". You can start a container with "machinectl start" with that, and get a shell in a container with "machinectl shell" and "machinectl login". These commands are propelry polkit enabled hence you can open them up for unprivileged users without the "group membership is sticky" property explained above. It is more limited than directly starting nspawn though, as it only runs containers with the configuration written down in .nspawn files, it does not allow additional manual opts passed in on the cmdline. But that's definitely a good thing, as exposing arbitrary nspawn cmdline options to unpriv users is a major security issue.

Hence, afaics we do deliver already what you are asking for, though in a different way. 

Closing this hence, I hope this makes sense?

**Comment by q2dg** [comment]
Yes, a lot. I'll try this solution you propose. Thanks very much!
