### ISSUE TITLE
networkd: RoutingPolicyRule fib flags

### ISSUE THREAD

**Issue by SomeoneSerge** [systemd/systemd#10706]
**Is your feature request related to a problem? Please describe.**
I need to setup an inverted rule, as in `ip rule add not ...`,
e.g. ```ip rule add not to $vpn_server_ip table $forward_through_vpn```

**Describe the solution you'd like**
Add "Not" field or "Flags" field, similar to https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/ip/iprule.c#n715
I'd have done it myself, but I'm neither familiar with netlink or networkd codebase, nor yet sure how much code needs to be updated (it seems there are a couple places where RoutingPolicyRule gets copied member-by-member or its fields passed as plain function parameters -- don't recall exactly, but sure saw smth like that).

**Describe alternatives you've considered**
Ugh, adding that rule manually on each boot

P.S. Am I right thinking that libsystemd/sd-netlink is basically a re-implementation of some part of libnl? If so, why wasn't the latter used?

**Comment by amishmm** [comment]
Instead of "Not" field or "Flags" field, I would propose "`InvertRule=boolean`" (default false)

Also on a side note here, "not" keyword is actually a global inversion and not per SELECTOR (from, to, etc)

i.e.
`ip rule add not from 1.1.1.1 to 2.2.2.2 table xyz`
`ip rule add from 1.1.1.1 not to 2.2.2.2 table xyz`
`ip rule add not from 1.1.1.1 not to 2.2.2.2 table xyz`

are (currently) treated as same.

All three **do not do** what one would expect naturally.

Earlier I thought we can have a "!" (not) flag prepended to PREFIX, in config file. For e.g.:
```
From=**!**1.1.1.1
To=**!**2.2.2.2

```

But thats not the case here.

PS: That said - iproute2 developers may implement ability to negate individual SELECTOR in future.
