### ISSUE TITLE
/etc on seperate filesystem

### ISSUE THREAD

**Issue by davispuh** [systemd/systemd#1075]
It would be cool if systemd would support this, basically accept some kernel parameter which points to fstab like `rd.rootfstab=/etc/fstab_real` (it would be located in initramfs) and then after `/sysroot` is mounted it would use this fstab.

Currently I achieved this with custom service and script which I put in initramfs.

`/usr/lib/systemd/system/initrd-root-fs.target.wants/mount-etc.service`

```
[Unit]
Description=Mount /etc
DefaultDependencies=no
ConditionPathExists=/etc/initrd-release
OnFailure=emergency.target
OnFailureJobMode=replace-irreversibly
Requires=sysroot.mount
After=sysroot.mount
Before=initrd-root-fs.target

[Service]
ExecStart=/bin/mount-etc.sh
Type=oneshot
KillMode=none
SendSIGKILL=no
```

`/bin/mount-etc.sh`

``` bash
#!/usr/bin/ash
local mountpoint source mountopts realtab=/etc/fstab_real sysroot=/sysroot
if [ -f "$realtab" ]; then
    for mountpoint in "/etc" "/var"; do
        if [ $(cat /proc/self/mounts | grep -c " ${sysroot}${mountpoint} ") -eq 0 ]; then
            if source=$(findmnt -snero source --tab-file="$realtab" -T $mountpoint); then
                mountopts=$(findmnt -snero options --tab-file="$realtab" -T $mountpoint)
                echo "Mounting '$source' on $mountpoint"
                mount "$source" "${sysroot}${mountpoint}" -o "$mountopts"
                if [ $? -ne 0 ]; then
                    exit 1
                fi
            fi
        fi
    done
fi
```

Need to mount `/var` too because of #832 
This works fine, but it would be better with systemd support as then wouldn't need to use this script.

**Comment by poettering** [comment]
What's the rationale for this? Why would you split out `/etc`? Pretty much no Linux distro supports that, or ever has,  I don't really see a reason to support this in systemd upstream either. What's the rationale?

**Comment by davispuh** [comment]
Basically it's same as `/usr` on separate filesystem, just in reverse. Instead of mounting `/usr`, `/opt` and `/srv` can mount `/etc`, `/home` and `/var` as everything else can be read-only and shared across multiple systems. It's alternative and it have advantage that if these fail to mount you have all applications from `/usr` and can do any recovery (eg. even start full desktop) while if `/usr` fails to mount then you're left with only what's in initramfs (usually just busybox). Also distributions don't have to support it because once filesystems are mounted it doesn't matter from where they come, thus systemd when used as initrd is only one for which it matters.

**Comment by xnox** [comment]
I don't follow. When provisioning brand new systems, one can boot off a read-only /usr only (and nothing else at all) which would create and populate /etc, /home, /var. And it's feasibly by default to have those completely empty (see e.g. stateless in https://clearlinux.org ). Instead of having many read-write parts, it's easier to consolidate all of read-only data into /usr.

**Comment by poettering** [comment]
I see a good reason to separate /etc from /home, from /usr and from /var. However, I really see no point in supporting /etc being separate from the root dir. I mean, it makes a lot of sense if the root dir besides empty dirs to use as mount points contains information what to mount on them. Splitting this out is just a headache... And for what? so that the stub dirs are on a separate partitions? Totally not seeing the benefit, sorry!

**Comment by biergaizi** [comment]
As suggested by @Thaodan, when using Btrfs, separating `/etc` has a useful application: a Btrfs subvolume. If `/etc` is a Btrfs subvolume, it can be snapshotted independently from other files on the same Btrfs filesystem. A subvolume also allows one to specify different file policies such as CoW and compression algorithms. I independently discovered this system configuration. 

Although "using `/etc` on a separate mountpoint on the same filesystem" is not a supported use case, it's not as bad as "having `/etc` on a different filesystem". When `/` is mounted as read-only during early boot, all files under `/etc` are always available (since mounting a Btrfs filesystem implicitly mounts all subvolumes). So having `/etc` as a Btrfs subvolume almost works on systemd, by accident.

Almost. Except that there's a small timing issue here: if the OS disk image is copied to another machine, it's considered a good practice to delete `/etc/machine-id` to remove sensitive per-machine UUID, and to retrigger first-boot jobs (such as SSH key generations). During early boot, systemd wants to create a `/etc/machine-id`. At this the point, rootfs is still read-only, systemd bind-mount a `/etc/machine-id`, and will later commit it to disk via `systemd-machine-id-commit.service`. But later, systemd will remount `/etc` with several new options such as `subvol=etc,rw,nosuid,compress=zstd` according to `/etc/fstab`. This shadows the earlier `/etc/machine-id` bind-mount created by systemd.  This prevents systemd from committing the generated `/etc/machine-id` to disk, making every boot "first boot".

The workaround is simple. Just mount `/etc` in initramfs before systemd runs to create a good environment expected by systemd. On Debian, my workaround is to create `/etc/initramfs-tools/scripts/local-bottom/mount-etc`:

```bash
#!/bin/sh

# We don't need any dependencies here.
case $1 in
    prereqs)
        echo ""
        exit 0
        ;;
esac

. /scripts/functions

# /etc must be mounted during early boot, /etc/fstab is too late.
#
# At startup, systemd uses a missing /etc/machine-id to detect a fresh
# OS image for triggering services marked with ConditionFirstBoot=yes,
# such as sshd-keygen.service on Debian. Afterwards, /etc/machine-id
# is created by systemd.
#
# This means the rootfs must ideally be mounted as read-write during
# early boot. If the rootfs is read-only, systemd falls back to bind-
# mounting a /etc/machine-id, which is later committed to disk when
# the filesystem becomes read-write via systemd-machine-id-commit.service.
#
# But there's an implicit assumption in the fallback case: /etc must not
# be a dedicated mountpoint, otherwise a new mount in /etc/fstab shadows
# systemd's /etc/machine-id, making it inaccessible, breaking first-boot
# logic entirely because the file is never committed to disk.
#
# Break this circular dependency by mounting /etc in initramfs.
read_fstab_entry /etc || panic
if [ ! -e "$MNT_FSNAME" ]; then
    MNT_FSNAME="$(blkid --match-token "$MNT_FSNAME" --output device)"
fi

mount -t "$MNT_TYPE" -o "$MNT_OPTS" "$MNT_FSNAME" "${rootmnt}${MNT_DIR}" || panic
```

Unsupported, but not too bad.

**Comment by Thaodan** [comment]
biergaizi ***@***.***> writes:

> As suggested by @Thaodan, when using Btrfs, separating `/etc` has a useful application: a Btrfs subvolume. If `/etc` is a Btrfs subvolume, it can be snapshotted independently from other files on the same Btrfs filesystem. A subvolume also allows one to specify different file policies such as CoW and compression algorithms. I independently discovered this system configuration. 
>
> Although "using `/etc` on a separate mountpoint on the same filesystem" is not a supported use case, it's not as bad as "having `/etc` on a different filesystem". When `/` is mounted as read-only during early boot, all files under `/etc` are always available (since mounting a Btrfs filesystem implicitly mounts all subvolumes). So having `/etc` as a Btrfs subvolume almost works on systemd, by accident.

That's a good point and actually what I'm already doing.

openSUSE MicroOS is doing something similar, I haven't checked exactly
what they are doing to have / still read-only at the same time but I
think it can't be that different.
