### ISSUE TITLE
boot as init=/root/init.sh and exec init 3 in shell, init is symlink of systemd, why X Window launched?

### ISSUE THREAD

**Issue by joshuafc** [systemd/systemd#10752]
Ubuntu 16.04.5 default environment.

I want to do some custom job before init. grub.cfg as 

`linux    /boot/vmlinuz ... ro init=/root/init.sh`

init.sh:

    #!/bin/bash
    # do some task
    exec init 3

**where `/sbin/init` is a symlink of `/lib/systemd/systemd`.**
after boot, X Windows launched.

if grub 
`linux    /boot/vmlinuz ... ro init=/root/init.sh 3`,can success boot into text mode.

according to https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html , 3 is not a kernel’s command-line parameters, kernel will pass it as an argument to init, here is /root/init.sh.

change /root/init.sh to :

    #!/bin/bash
    # do some task
    echo $1
    sleep 3s
    exec init 3

I can see the value passed from kernel.

In my submission，no matter what value grub -> kernel -> /root/init.sh , I will discard the value and exec init as runlevel 3. why it doesn't work.

**Comment by poettering** [comment]
we generally read /proc/cmdline, not argv[], since the kernel removes some bits from the latter that we need to know. We essentially ignore argv[] altogether.

Hence, what you are trying to do doesn't work, you'd have to overmount /proc/cmdline instead with some file with the new arguments.

And sorry, but this is unlikely to change, because of the aforementione dissue that the kernel removes some bits from argv[] that we need, hence we really have to check /proc/cmdline instead.

Closing hence.
