### ISSUE TITLE
Makefile uses gcc-ar instead of ar

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#1077]
Looks like configure script uses gcc-ar instead of "ar". In case when default compiler is different that gcc this gives error for systemd-225:

Makefile:11299: recipe for target 'systemd-stdio-bridge' failed
/usr/bin/ld: error: ./.libs/libbus-proxy-core.a: no archive symbol table (run ranlib)
/usr/bin/ld: error: ./.libs/libshared.a: no archive symbol table (run ranlib)

Same goes to nm and ranlib.

Evnironment is OpenMandriva with LLVM/clang with enabled LTO

This patch fixes issue:
https://abf.io/openmandriva/systemd/blob/master/systemd-222-do-not-use-gcc-ar-nm-ranlib.patch

**Comment by poettering** [comment]
See 4fecbe59dadaed314b792ed35ef5dc24c7047a18 and #604.

Maybe make this conditional on the used compiler? @heftig?

**Comment by heftig** [comment]
No patching is necessary. If you're not using gcc, you can override using configure AR=ar NM=nm RANLIB=ranlib.

**Comment by tpgxyz** [comment]
Anyways this is still a hardcode.

**Comment by heftig** [comment]
As I noted in 4fecbe5, binutils 2.25 / GCC 5.1 seems to find the needed plugin without help from the `gcc-*` wrappers, and (according to this issue) this is also the case for Clang (LLVMgold plugin). So for these setups you could remove the `AC_CHECK_TOOLS` lines. However, there seems to be a set of configurations (just GCC 4.9? cross-compiling?) where you need either `-ffat-lto-objects` or the `gcc-*` wrappers. So the options I see are:
1. Do nothing and tell people that want to compile using Clang use `CC=clang AR=ar NM=nm RANLIB=ranlib` instead of just `CC=clang`.
2. Strip the `AC_CHECK_TOOLS` lines and tell people who have problems to use `AR=gcc-ar NM=gcc-nm RANLIB=gcc-ranlib`.
3. Completely revert 4fecbe5 and take the compile-time hit and reduced optimization (if it's needed, it means LTO isn't done) of `-ffat-lto-objects`.
4. Use `AX_COMPILER_VERSION` or something similar to restrict the use of the `gcc-*` wrappers to GCC.
5. Drop automatic LTO from the build system.

**Comment by tpgxyz** [comment]
Sounds like #4 is best option here

**Comment by poettering** [comment]
I'd be fine with options 1, 2 and 3... 

4 is certainly the option friendliest to people. Would be happy to take a patch for that.

**Comment by tpgxyz** [comment]
Thanks for fixing this!
