### ISSUE TITLE
networkd: Implement dhcpv6 prefix delegation

### ISSUE THREAD

**Issue by brain0** [systemd/systemd#1080]
networkd should support dhcpv6 prefix delegation.

A router can delegate ipv6 prefixes via dhcpv6. When a client receives them, it may delegate them to local "downstream" interfaces.

Example: A router has control over the prefix 2001:DB8:DEAD::/48. When requesting a prefix from the router, networkd may receive 2001:DB8:DEAD:100::/56. It should then do the following:

1) Set a prohibited route on 2001:DB8:DEAD:100::/56.
2) Delegate sub-prefixes to downstream interfaces, for example 2001:DB8:DEAD:101::/64 to tap0 and 2001:DB8:DEAD:102::/64 tap1. For each of these prefixes, it configures routes to the correct interfaces.
3) Add a policy route as follows: when forwarding a packet with a source within 2001:DB8:DEAD:100::/56, use the router that delegated this prefix as default gateway (this is needed for multihoming, if you only have a single gateway it is unnecessary).
4) optionally, networkd could allow a dhcpv6 server to receive sub-prefixes of 2001:DB8:DEAD:100::/56 to delegate them further downstream to dhcpv6 clients (for example, a dhcpv6 server could delegate a /60 prefix).

Right now, the only clients to support prefix delegation are OpenWRT's netifd and dhclient (the latter includes no dhclient-script that handles this case though).

Some ideas on configuration: http://wiki.openwrt.org/doc/uci/network6#downstream_configuration_for_lan-interfaces

**Comment by teg** [comment]
@pfl care to comment on this?

**Comment by pfl** [comment]
Eventually systemd-networkd should be able to propagate IPv6 prefix information and act as a router for some of its networks. This is a mid-sized problem and takes a while to implement.

To cut down on the complexity, initially only static prefixes should be supported as some amount of support code should be written, most notably Router Advertisement sending and proper Router Solicitation handling. systemd-networkd should also implement capabilities of being an IPv6 router so that the same level of functionality would be achieved as it now has when being a DHCPv4 server. The Linux kernel takes care of some of the route handling on the client side also in the multihoming case; how well the kernel selects the most appropriate router needs to be verified.

Once the static prefix delegaion has been implemented, DHCPv6 prefix delegation option should be considered. This second part stresses automatic prefix assignment between the downstream interfaces; something that one might want to add also to the .network configuration files.

**Comment by grawity** [comment]
> The Linux kernel takes care of some of the route handling on the client side also in the multihoming case; how well the kernel selects the most appropriate router needs to be verified.

At least in IPv4 – not very well at all, unless policy routes are added (to consider the source, not just destination). Which might be a wish list item of its own.

**Comment by brain0** [comment]
For IPv6, OpenWRT's netifd adds the default routes as policy routes only, in order to route upstream prefixes properly and not route ULA-prefixes at all. I think this is how it is supposed to be done.

If networkd should supports multihoming for IPv6, it should do the same.

**Comment by wido** [comment]
Has there been any progress on this part?

The reason I'm asking is that I would like to have PD working on CoreOS.

By obtaining a IPv6 prefix I can use the delegated prefix for giving Docker containers on CoreOS native IPv6 access.

**Comment by pfl** [comment]
I looked at it briefly, but that's about it. The idea I had was to re-use struct sd_ndisc to handle also router advertisments. I'd initially thought of starting by announcing configured static IPv6 address prefixes as they must be on link by definition, and then immediately afterwards add a configuration section for prefixes since they can be off-link, not autoconfigurable, use dhcp etc.

I pushed the very quick and dirty result of 1h hacking as https://github.com/pfl/systemd-dhcp6/commit/1e57ca31f661f539956be3db90913c1aedc30fa5 if anone needs it. It doesn't really do anything but this was the direction I was going to take.

Edit: I'm stuck with something else at the moment, I'm not going to have time for implementation right now.

**Comment by wido** [comment]
@pfl Thank you!

Not sure if I understand your post properly. This issue is about Prefix Delegation where you perform a IA_PD request towards the DHCPv6 server.

It will return with for example an /56, /48 or anything else which is routed towards that host.

**Comment by pfl** [comment]
So I seem to have replied only to point 2) above. To implement all of this the simplest approach is to first to implement prefix delegation, which will provide the IPv6 prefixes to the managed interfaces. This means implementing sending of periodic Router Advertisments as well as responses to Router Solicitations. With that eventually done, request prefixes from DHCPv6 (easy) and update the set of prefixes to delegate distributed over the available interfaces (less easy).

And as edited above, I'll be passing the implementation baton to someone else...

**Comment by wido** [comment]
@pfl Ah yes.

To get it right, a machine has eth0 (upstream), eth1 and eth2.
- On eth0 it sends a Router Solliciation and obtains an address through Autoconf/SLAAC
- On eth0 it sends out a IA_PD Prefix Delegation Request
- Using the prefix obtained it configures eth1 and eth2 and starts sending out Router Advertisements

The last point is not required to be done. My use-case is CoreOS where I want to use the Prefix for Docker Containers.

In this case I just need to instruct Docker to use the obtained prefix and that's all.

If systemd-networkd would be able to send out the IA_PD request that would be great to start with!

**Comment by halvors** [comment]
Any progress on this? This is much needed!

**Comment by tomc603** [comment]
Just wanted to bump this for attention. Any forward progress?

**Comment by pfl** [comment]
I got an urge start scratching this itch, so far just toying around with a [Prefix] section in the network configuration file. Right now I only have in mind static configuration of prefixes and sending Router Advertisments as a result. Once this is done, sending an IA_PD sounds much easier. No promises of any delivery or dates, though. I'll at least cough up the code if I feel like having failed or otherwise run out of time...

**Comment by poettering** [comment]
@pfl i figure this is similar to how we do dhcp address pool management right now (which isn't too configurable yet, but kinda does a similar thing...). I am pretty sure we should align this, so that the dhcp address pool management is really just a manually-configured version of the more automatic prefix delegation if you follow what i mean...

**Comment by wido** [comment]
Great! This would really work well with CoreOS and Docker for example. The CoreOS host does a Router Solicitation to get a IPv6 Address and a DHCPv6 IA_PD afterwards to obtain a prefix which it can use for all local containers.

**Comment by pfl** [comment]
@poettering , I was initially thinking of adding the following syntax to .network files due to just reading the Neighbor Discovery RFC, but these are fine to change (and a bit too RFCish):
[PrefixDelegation]
PrefixDelegation=true // this should go into the [Network] section, actually?
RouterLifetime=12000 // in seconds
EnableManaged=false
EnableOther=true

[Prefix] // there can be more than one prefix assigned for IPv6
Prefix=2001:db8::/60
OnLink=true
AddressAutoconfiguration=true
PreferredLifetime=7000 // in seconds
ValidLifetime=9000 // in seconds

Looking at DHCPv4, there is PoolOffset and Poolsize, these should then be consolidated (at some point) with the [Prefix] section, I think. The syntax of a "prefix" should then allow things like Prefix=192.168.1.16-192.168.1.125 and Prefix=192.168.1.16/28, if I got your comment correctly? The above variable names and syntax are easy to change, so far I've just been poking around these.

Adding DHCPv6 PD is step number two, let's have the manually configured prefixes and sending of Router Advertisments working first.

**Comment by da2ce7** [comment]
This is a very needed feature for networkd. :)

**Comment by pfl** [comment]
Just an update on this issue, prefix delegation is coming along nicely and taking the time I expected as I cannot work full time on this feature. The focus is to first get RA and RS working, then to do the IA_PD.

**Comment by pfl** [comment]
Static Router Advertisement support is now in upstream systemd(-networkd), documentation in the individual commits. Man page should be written. DHCPv6 PD that gets a prefix (easy) and distributes it over the links (a bit less easy) is up for grabs. Any takers?

**Comment by halvors** [comment]
@pfl Any progess on requesting prefix from DHCPv6 server with IA_PD?

**Comment by pfl** [comment]
That is almost next on the agenda, after #6948 and possibly fixing DHCPv4 to do the same thing...

**Comment by halvors** [comment]
@pfl Thanks, combining prefix delegation IA_PD request and being able to assign it automatically is a great feature i have been waiting a long time for :) Keep up the good work!

**Comment by pfl** [comment]
Working on it, caused a bit of refactoring along the way.

**Comment by vanaf** [comment]
Will it be possible to get prefix from non-networkd managed device - ppp (pppoe connection)?

We all know that pppoe is not so supported by modern linux network management, but status of dhcpv6-pd over pppoe is even worse.

We are going to use networkd as network solution for linux router with multiple pppoe connections as upstreams. We have to manage pppoe separately, as networkd haven't desided to support it or not. But it will be great if all PD stuff will be handled by networkd, if it will be able to request IA_PD on ppp device.

**Comment by pfl** [comment]
Phew, initial code is at pull request #7582. Somebody with a decent non-production system could perhaps give the code a beating.

**Comment by pfl** [comment]
> We are going to use networkd as network solution for linux router with multiple pppoe connections as upstreams. We have to manage pppoe separately, as networkd haven't desided to support it or not. But it will be great if all PD stuff will be handled by networkd, if it will be able to request IA_PD on ppp device.

To get prefix delegation working, systemd needs to handle DHCPv6 on the upstream link. But the PPPoE interface could be assembled/created by other means with systemd handling IP configuration of the interface once up, unless there is someting in the details of PPPoE that I'm not aware of.

**Comment by brain0** [comment]
@pfl: You are correct. On a PPP look, the PPP handshake only assigns a link local address, any SLAAC or DHCPv6 is then performed by other tools (I use an old OpenWRT version that does it this way, no idea of newer versions change this).

**Comment by pfl** [comment]
Done and merged! Time and testing will tell when it works as expected. Open new issues for those artefacts.

**Comment by pfl** [comment]
Done and merged! Time and testing will tell when it works as expected. Open new issues for those artefacts.

**Comment by vanaf** [comment]
I finally checked it on real environments and was able to debug some issues:

- PD requests are sent only if RAs have managed flag. #9745
- If upstream link is configured before downstream it never knows that someone wants prefix delegation, as downstream is not considered as managed yet.

**Comment by pfl** [comment]
> PD requests are sent only if RAs have managed flag. #9745

That's handled by #9745 

> If upstream link is configured before downstream it never knows that someone wants prefix delegation, as downstream is not considered as managed yet.

This I added as #9758.
