### ISSUE TITLE
Systemd /networkd does not release DHCP ipaddress / dns after shutdown

### ISSUE THREAD

**Issue by dirkpetersen** [systemd/systemd#10820]
**systemd version **
> 237 or 239

**Used distribution**
 > Ubuntu 18.04 / 18.10

**Expected behaviour you didn't see**
 > if using infoblox DHCP server, /etc/hostname will automatically be registered in dns (if hostname is not already taken) by infoblox DHCP server. If one executes "shutdown -h now" on a Ubuntu 14.04/16.04 system dhclient will send a dhcprelease and and infoblox will remove the dns name. This will allow users to reinstall virtual test systems many times using the same hostname

**Unexpected behaviour you saw**
 > When executing "shutdown -h now" on a Ubuntu 18.04/18.10 system the dnsentry will not be removed since networkd does not seem to send a dhcprelease.  This does not allow me to shutdown a test system and bring up a new virtual or physical system with the same hostname within the DHCP lease period (3 days in our case) 

**Steps to reproduce the problem**
"shutdown -h now" a ubuntu 18.04 or 18.10 system that was configured with  DHCP, then use the host command from another system to verify that the ubuntu host is still registered in DNS

This seems to be similar to #1546 .  The new behavior is a departure from dhclient default behavior for many years even though is is still within the scope of dhcp RFC which says dhcprelease is optional. Can this either be fixed or config option be added 

In #1546 the issue was closed with this comment:
"The correct way would perhaps be for the client to send a DHCPRELEASE but that will likely end the lease and might open doors for a different address on networkd restart. So the current solution is perhaps the better solution"

Yes there should be a  DHCPRELEASE but only when a host shutdown occurs and not when network is restarted. This worked all just fine with dhclient, I wonder why it was required to change this behavior

**Comment by atopia** [comment]
This has been a real life issue affecting users since 2015 (see #780, #1546).
In my case, an interface set up by an initrd is handed over to the main system's systemd-networkd. Because the IP is not released, the new DHCPDISCOVER gets a different address. This is despite a static hostname  <-> IP configuration in the DHCP server and with and without manually flushing and bringing the interface down when the initrd service stops.
While I agree with @teg that DHCP servers [should match](https://github.com/systemd/systemd/issues/1546#issuecomment-220636576) a DHCPDISCOVER to an existing client, as shown by [other affected users](https://github.com/systemd/systemd/issues/1546#issuecomment-230745833), this cannot be relied on.
CriticalConnection (as suggested [here](https://github.com/systemd/systemd/issues/780#issuecomment-168807139)) is an orthogonal use case, as a) it merely leaves the configuration in place, without renewing existing leases, and b) does not solve the OPs use case either.
I understand that release on service restart may [not be a good idea](https://github.com/systemd/systemd/issues/1546#issuecomment-220662273), but even udhcpc has `--release`, why do you insist on breaking real world use cases by refusing to at least optionally send DHCPRELEASE when stopping the service?

**Comment by dirkpetersen** [comment]
Just checking in on this one. I realize this may be a lower priority  for many but I was wondering if there is anything I can do to move this along. Can I pay you in cupcakes, bourbon or otherwise to nudge this to the next step?

**Comment by ssahani** [comment]
I am working on this . There are few other changes needed in the architecture to implement this.

**Comment by ssahani** [comment]
@dirkpetersen I have a WIP version . I am not actually sure this works for you. Could you please test.

**Comment by dirkpetersen** [comment]
Awesome Susant @ssahani, I will be able to test this later this month, could you send me some info to which address I can send you your goodie: Go to http://www.fredhutch.org, search for 'dirk' and send me an email with your mailing address.

**Comment by ssahani** [comment]
Haha Thanks much for this :) . Please test it out so that we can merge it .

**Comment by robert-scheck** [comment]
Does the release also flush the IP address from the interface? I've somehow in my mind that `systemd-networkd` never removes any IP address from the interface…

**Comment by cherusk** [comment]
@edevolder  Hold on, I'm of opinion that both ways should be supported. That's **KeepConfiguration=** was for me to tell networkd to keep the DHCP configuration over system reboots if I intended. Release should only be sent if that option is not specified. For me that breaks a major use case of that **KeepConfiguration=**. :(
