### ISSUE TITLE
Document that Alias= (and friends) may not be used in in drop-ins

### ISSUE THREAD

**Issue by jmorgensen** [systemd/systemd#1090]
The `Alias` directive does not seem to work when it is supplied in a drop-in, yet it works if the entire service file is shadowed, e.g. `/etc/systemd/service/foobar.service` shadows `/lib/systemd/service/foobar.service`.

I spent a couple hours searching through the manual, google, and this bug-tracker, and I have found nothing saying why this should not work. If this is intended behavior (though I see no reason why it should be), it should at least be noted in the documentation.

**Repro on Debian 8:**

```
root@core ~# systemd --version
systemd 215
+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR

root@core ~# systemctl cat foobar
# /etc/systemd/system/foobar.service
[Unit]
Description=Foobar test service

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo 'Foobar started' | systemd-cat"

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/foobar.service.d/override.conf
[Install]
Alias=barfoo.service

root@core ~# systemctl enable foobar
Created symlink from /etc/systemd/system/multi-user.target.wants/foobar.service to /etc/systemd/system/foobar.service.

root@core ~# systemctl start barfoo
Failed to start barfoo.service: Unit barfoo.service failed to load: No such file or directory.
```

Yet with the full file replaced:

```
root@core ~# systemctl disable foobar
Removed symlink /etc/systemd/system/multi-user.target.wants/foobar.service.

root@core ~# systemctl daemon-reload

root@core ~# systemctl cat foobar
# /etc/systemd/system/foobar.service
[Unit]
Description=Foobar test service

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo 'Foobar started' | systemd-cat"

[Install]
WantedBy=multi-user.target
Alias=barfoo.service

root@core ~# systemctl enable foobar
Created symlink from /etc/systemd/system/barfoo.service to /etc/systemd/system/foobar.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/foobar.service to /etc/systemd/system/foobar.service.

root@core ~# systemctl start barfoo

root@core ~# systemctl status barfoo
* foobar.service - Foobar test service
   Loaded: loaded (/etc/systemd/system/foobar.service; enabled)
   Active: inactive (dead) since Mon 2015-08-31 05:53:50 UTC; 5s ago
  Process: 8887 ExecStart=/bin/sh -c echo 'Foobar started' | systemd-cat (code=exited, status=0/SUCCESS)
 Main PID: 8887 (code=exited, status=0/SUCCESS)

Aug 31 05:53:50 core systemd[1]: Starting Foobar test service...
Aug 31 05:53:50 core cat[8889]: Foobar started
Aug 31 05:53:50 core systemd[1]: Started Foobar test service.
```

**Comment by poettering** [comment]
This is actually by desing.

The idea is that /usr is for vendor config and /etc is for local config. [Install] contains information from the vendor how to enable vendor unit files locally. On top of that: .d/ drop-ins are a way how to extend vendor config with local config. Now, putting this together: it would be weird to honour [Install] extension in .d/ drop-ins since those are inherently not vendor data...

Or in other words: [install] info should really be about vendor bits and not be confused by local configuration, since its supposed to create local configuration.

But yeah, this should be documented better.

**Comment by jmorgensen** [comment]
That makes more sense.

In that case, what would the correct way be to add a non-vendor alias? For example, if one of your utilities expectd foo-daemon but your vendor named the service food.

**Comment by poettering** [comment]
just create the symlink in /etc/systemd/system? why bother with drop-ins then?

**Comment by jmorgensen** [comment]
Ah, I can't believe I was that dense!  I was for some reason thinking of all those symlinks as managed solely by systemd. I don't think the documentation is at fault for that bit.

As for the original issue, I think it would certainly be helpful to indicate in the documentation what can and can't be put in a drop in.

**Comment by mustafakemalgilor** [comment]
> This is actually by desing.
> 
> The idea is that /usr is for vendor config and /etc is for local config. [Install] contains information from the vendor how to enable vendor unit files locally. On top of that: .d/ drop-ins are a way how to extend vendor config with local config. Now, putting this together: it would be weird to honour [Install] extension in .d/ drop-ins since those are inherently not vendor data...
> 
> Or in other words: [install] info should really be about vendor bits and not be confused by local configuration, since its supposed to create local configuration.
> 
> But yeah, this should be documented better.

If 'Install' section is intended for vendor-specific attributes, then I think 'Alias' should not belong to 'Install' section of an unit. I'm having issues aliasing templated unit files with symlink approach, and it seems there is no convenient way of doing it.

**Comment by keszybz** [comment]
The thinking on this has changed quite a bit since those early days.
> .d/ drop-ins are a way how to extend vendor config with local config.

It is now generally accepted that drop-ins can be used for any purpose, e.g. drop-ins in /usr may be provided by the vendor when the configuration of a unit is split between packages.

> If 'Install' section is intended for vendor-specific attributes

No, it is not.

[Install] is now fully supported in drop-ins. If it doesn't work identically to [Install] in the main file, please report this as a bug.

**Comment by mustafakemalgilor** [comment]
> The thinking on this has changed quite a bit since those early days.
> 
> > .d/ drop-ins are a way how to extend vendor config with local config.
> 
> It is now generally accepted that drop-ins can be used for any purpose, e.g. drop-ins in /usr may be provided by the vendor when the configuration of a unit is split between packages.
> 
> > If 'Install' section is intended for vendor-specific attributes
> 
> No, it is not.
> 
> [Install] is now fully supported in drop-ins. If it doesn't work identically to [Install] in the main file, please report this as a bug.

Then I think I'm experiencing a bug while trying to alias a service. The scenario is as follows;

I have a unit template for creating postgresql clusters, named postgresql@.service . The actual clusters use postgresql@[pgsqlversion]-[clustername].service pattern. As an example, let's assume we have a cluster service named **postgresql@11-main.service** .

**systemctl status** output for such a service looks like this;

> systemctl status postgresql@11-main.service 
● postgresql@11-main.service - PostgreSQL Cluster 11-main
     Loaded: loaded (/lib/systemd/system/postgresql@.service; enabled-runtime; vendor preset: enabled)
     Active: active (running) since Wed 2019-12-18 09:40:09 +03; 2h 27min ago
   Main PID: 1026 (postgres)
      Tasks: 7 (limit: 19045)
     Memory: 29.5M
     CGroup: /system.slice/system-postgresql.slice/postgresql@11-main.service
             ├─1026 /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/11/main -c config_file=/etc/postgresql/11/main/>
             ├─1080 postgres: 11/main: checkpointer
             ├─1081 postgres: 11/main: background writer
             ├─1082 postgres: 11/main: walwriter
             ├─1083 postgres: 11/main: autovacuum launcher
             ├─1084 postgres: 11/main: stats collector
             └─1085 postgres: 11/main: logical replication launcher
 
And I want to alias this service to another name, let's say foo.service. In order to do that, I've created a directory named  **postgresql@11-main.service.d** under **/etc/systemd/system** , and a file named **alias.conf** under this newly created directory. The contents of the alias.conf file is as follows;

> [Install]
> Alias=foo.service

 Then, I executed **systemctl daemon-reload** in order to reload unit files. Then, I've executed **systemctl status** for "postgresql@11-main.service" to see whether override file is recognized by the systemd.

The output of **systemctl status**  after aliasing attempt as follows;

> ● postgresql@11-main.service - PostgreSQL Cluster 11-main
>      Loaded: loaded (/lib/systemd/system/postgresql@.service; enabled-runtime; vendor preset: enabled)
>     Drop-In: /etc/systemd/system/postgresql@11-main.service.d
>              └─alias.conf
>      Active: active (running) since Wed 2019-12-18 09:40:09 +03; 2h 33min ago
>    Main PID: 1026 (postgres)
>       Tasks: 7 (limit: 19045)
>      Memory: 29.5M
>      CGroup: /system.slice/system-postgresql.slice/postgresql@11-main.service
>              ├─1026 /usr/lib/postgresql/11/bin/postgres -D /var/lib/postgresql/11/main -c config_file=/etc/postgresql/11/main/>
>              ├─1080 postgres: 11/main: checkpointer
>              ├─1081 postgres: 11/main: background writer
>              ├─1082 postgres: 11/main: walwriter
>              ├─1083 postgres: 11/main: autovacuum launcher
>              ├─1084 postgres: 11/main: stats collector
>              └─1085 postgres: 11/main: logical replication launcher

As we can clearly see, the drop-in folder and alias.conf is recognized by the system. But the alias I've specified, **foo.service** is not working.

> systemctl status foo.service
> Unit foo.service could not be found.

Is this a bug or am I missing something?

Thanks,

**Comment by keszybz** [comment]
Aliasing `postgresql@11-main.service` to `foo.service` is not allowed. See #13990.

**Comment by mustafakemalgilor** [comment]
> Aliasing `postgresql@11-main.service` to `foo.service` is not allowed. See #13990.

Thanks for reply, I'll look into that.
