### ISSUE TITLE
Tweak the regex in `test-execute`

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#10934]
**systemd version the issue has been seen with**
> latest master

**Used distribution**
 > CentOS  7.5

The regex in `test-execute` doesn't cover all possible interface names, thus causes unexpected fails on some systems:

```
exec-privatenetwork-yes.service: Executing: /bin/sh -x -c '! ip link | grep ": " | grep -Ev ": (lo|(sit0|ip6tnl0|ip6gre0)@.*):"'
+ ip link
+ grep ': '
+ grep -Ev ': (lo|(sit0|ip6tnl0|ip6gre0)@.*):'
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
Received SIGCHLD from PID 456 (sh).
Child 456 (sh) died (code=exited, status=1/FAILURE)
```

This was also mentioned by @evverx in https://github.com/systemd/systemd/pull/10331#discussion_r223745613.

**Comment by poettering** [comment]
what is tunl0 though?

**Comment by yuwata** [comment]
Does `test-execute` run after `systemd-networkd-test.py`?

**Comment by mrc0mmand** [comment]
No, but it does run after `ninja test`, which executes `test-netlink-manual`, which creates such interface.

Just to be more clear, right now the tests run in following order:
1) `ninja test`
2) `for test in test/TEST-??-*; then ...`
3) Other tests

And the issue mentioned here occurs either after running `ninja test` twice, or by running `test/TEST-24-UNIT-TESTS` after `ninja test`.

**Comment by ssahani** [comment]
@poettering it's the kernel default.  loading the  kernel module makes the "xxx0" devices appear in all network namespaces.

```
MODULE_ALIAS_NETDEV("tunl0");
"net/ipv4/ipip.c" 729L, 19188C  
```

**Comment by evverx** [comment]
We generally can't stop anyone from loading kernel modules manually with `modprobe` before running the tests so even if the tests cleaned up after themselves it wouldn't help to prevent the links from popping up in network namespaces. As I see it, there are two ways to fix it: extending the regular expression or removing `exec-privatenetwork-yes.service` (because frankly, I'm having trouble understanding what it's trying to test).
