### ISSUE TITLE
"systemctl enable" should error on .service without [Install] section

### ISSUE THREAD

**Issue by techtonik** [systemd/systemd#10956]
**systemd version the issue has been seen with**
> systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

**Used distribution**
 > Ubuntu 16.04

**Expected behaviour you didn't see**

    # systemctl enable webhook
    /full/path/to/webhook.service is missing required "[Install]" section.
    # echo $?
    1

**Unexpected behaviour you saw**

    # systemctl enable webhook
    # echo $?
    0

**Steps to reproduce the problem**

    [Unit]
    Wants=network-online.target
    After=network-online.target

    [Service]
    ExecStart=/usr/local/bin/webhook

**Comment by poettering** [comment]
Please read the submission form. You'll find that we only track issues in the two most recent upstream versions of systemd here. That's 238+239. Your's is *a lot* older than that. Moreover, the issue you are reporting has long been fixed.

**Comment by mbiebl** [comment]
@poettering with git master:
```
# systemctl enable test.service
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.
# echo $?
0
```
While we do have a verbose warning/failure message, the return code *is* 0 and the bug submitter asked for that to be 1 aiui.

**Comment by techtonik** [comment]
@poettering thanks. I could not [find](https://github.com/systemd/systemd/issues?q=is%3Aissue+%22systemctl+enable%22+in%3Atitle+is%3Aclosed) the report here, and there is no mention of downstream tracker for Ubuntu in [CONTRIBUTING.md](https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#filing-issues).

**Comment by poettering** [comment]
> While we do have a verbose warning/failure message, the return code _is_ 0 and the bug submitter asked for that to be 1 aiui.

Oh right. But I am very sure that a missing [Install] should mean "there is nothing to install, all good"... I mean, if in doubt whether something is an error or not I am usually keenly on the side of not considering things errors needlessly...

Hence I am very sure we shouldn't change the return code in this case.

(I mean, there's also the issue of compat, which alone is probably already reason enough not to change this)

**Comment by techtonik** [comment]
If I execute "systemctl enable", I for sure want the service to autostart on boot, so the final result that "there is nothing to install" is no good at all.

**Comment by techtonik** [comment]
And I want the server bootstrap script to fail if somebody replaces `.service` file with new version that is missing `[Install]` section. How should I handle this in a bash script?

**Comment by poettering** [comment]
> If I execute "systemctl enable", I for sure want the service to autostart on boot, so the final result that "there is nothing to install" is no good at all.

autostart-on-boot is *one* possible outcome of "systemctl enable". The command is used for hooking in a unit to the recommended places, which can be the boot-up phase, but can be various other things too or instead. Units without [Install] section generally don't need hooking in apparently, and hence no error is generated.

**Comment by poettering** [comment]
> And I want the server bootstrap script to fail if somebody replaces `.service` file with new version that is missing `[Install]` section. How should I handle this in a bash script?

In general, a unit needs no [Install] section to be fully valid. There are plenty of units which have no [Install] section, and which function perfectly and are pulled in differently.

**Comment by techtonik** [comment]
> autostart-on-boot is one possible outcome of "systemctl enable". The command is used for hooking in a unit to the recommended places, which can be the boot-up phase, but can be various other things too or instead.

Can you be explicit about "various other things"? I don't want to complicate things in my head more than they are already. Spending 3+ days just to get autostart running is not something I can accept easily. I would be very glad for most explicit and obvious `enable-autostart` command, and explicit `[Autostart]` sections instead of `[Install]`. Because I expected `[Install]` section to be related to phase where I "install" my .service by moving its content from the location in my repository to `/etc/systemd/system/`.

**Comment by poettering** [comment]
> Can you be explicit about "various other things"? I don't want to complicate things in my head more than they are already.

"systemctl enable" can mean plenty of things: it might hook something into hw activation, into dbus activation, into socket activation, and all kinds of other stuff. activation at boot is just one kind of activation. hw activation is usually implemented through WantsBy=bluetooth.target (to activate a service when bluetooth hw shows up for example), dbus activation by doing `Alias=dbus-<somedbusname>.service`, socket activation by doing "Also=somesocketunit.socket", and so on.

What services place into their [Install] section is really up to them. It can be a multitude of things and it can even be absent entirely. For example, systemd-poweroff.service is not a service that needs enabling but still is executed quite regularly because it is listed as Wants= dependency in poweroff.target.

**Comment by techtonik** [comment]
I see. So if `[Install]` section contains target that is not linked in boot up target tree, the `.service` won't be started at boot? Is there any cheatsheet that shows default tree and those independent targets in some graphical form?

```
boot.target
+--- network.target
       +---- network-online.target

bluetooth.target

dbus-<name>.target
```

**Comment by boucman** [comment]
not all target but man:bootup should answer most of your question

**Comment by dubrowgn** [comment]
For an additional data point, we got bit by this today. A bash script with proper error handling thought it was enabling a service when it actually wasn't. Instead of stopping with a relatively clear error message (can't enable service because install section is missing), it continued on it's way and triage became much more difficult:
1. Why is "the thing" not working? The service isn't running.
2. Why is the service not running? It was never started.
3. Why was it never started? It is not enabled.
4. Why is it not enabled? The service file is missing the "install" section.

If `systemctl` had returned an error code, triage would have been much easier and more localized to the actual problem. We would have also caught the problem much earlier as a result.

```
# systemctl enable test.service
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
...
```
`systemctl` clearly knows that it can't enable the service. It doesn't seem all that controversial to me for `systemctl` to return an error code when it knows it can't do what you asked it to.
