### ISSUE TITLE
systemd-nspawn: by default vulkan can't access /dev/dri/renderD*

### ISSUE THREAD

**Issue by tinywrkb** [systemd/systemd#10960]
**systemd version the issue has been seen with**
> 239.300-2

**Used distribution**
 > arch linux

**Expected behaviour you didn't see**
 > rw access permission to /dev/dri/renderD*

**Unexpected behaviour you saw**
 >  openat(AT_FDCWD, "/dev/dri/renderD128", O_RDWR|O_CLOEXEC) = -1 EPERM (Operation not permitted)

**Steps to reproduce the problem**

#### on host

```
$ xhost +local:
# systemd-nspawn -b -D nspawn \
  --volatile=no \
  --bind-ro=/home/user/.Xauthority \
  --bind-ro=/run/user/1000/bus \
  --bind-ro=/tmp/.X11-unix/X0 \
  --bind=/dev/shm \
  --bind=/dev/dri \
  -E DISPLAY=$DISPLAY
```

#### on guest container

`$ vulkaninfo`

**workarounds**

Add specific  DeviceAllow property like:  
`--property=DeviceAllow="/dev/dri/renderD128"`  
or allow access to all devices with something like  
`$ echo a | sudo tee /sys/fs/cgroup/devices/machine.slice/machine-nspawn\\x2dwine.scope/devices.allow`

**not working workaround**

`--property=DevicePolicy=auto`

**Comment by poettering** [comment]
I am sorry, but the Linux kernel does not virtualize device access, and we won't claim otherwise. If you make device nodes available it's an awful hack, as the device node will miss its counterparts in /sys, and ownership for the device is not managed and handed over exclusively.

Because this is always a hack to do, we require you to do some manual work if you do this anyway, and that means you need to use --bind= and you might need `-p "DeviceAllow=char-drm rwx"` or so... (such `DeviceAllow` expression will allow access to all DRM devices. This is of course  a security nightmare, but this is your call...

But as long as the kernel doesn't do proper virtualized access to devices we won't support this any better either sorry. The kernel has to do something about this first...

Hence, closing. Hope this makes some sense...

**Comment by tinywrkbee** [comment]
Fair enough, thank you for the prompt reply.

**Comment by bl33pbl0p** [comment]
@poettering

The kernel supports uevent namespacing now since 26045a7b14bc7a5455e411d820110f66557d6589 and a3498436b3a0f8ec289e6847e1de40b4123e1639, not sure if that helps here (I think support needs to be added to udev or something else to forward them with correct tags to the right network namespace).

**Comment by poettering** [comment]
@bl33pbl0p well, as long as /sys is not virtualized that doesn't help

**Comment by sfan5** [comment]
please excuse the necro-post, but I wanted to note down the working combination of flags for people arriving from google (as of systemd 252):
```sh
--property="DeviceAllow=char-drm rw" --bind=/dev/dri
```
