### ISSUE TITLE
dbus methods: fall back to checking Linux capabilities when compiled without PolKit.

### ISSUE THREAD

**Issue by fbaeuerle** [systemd/systemd#11034]
**Is your feature request related to a problem? Please describe.**

I'm building an embedded system. Due to reasons (customers blocking NTP ports in their networks), I need to set the system clock. Since I trust systemd developers much more being able to do this correctly than myself, I'd like to use the `org.freedesktop.timedate1.SetTime` Method. The system, however does not have polkit installed, and due to storage space restrictions (js dependency) most probably never will.

The process calling the SetTime method has CAP_SYS_TIME, but the call fails like this:

```
‣ Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=6  ReplyCookie=34
  Sender=:1.10  Destination=:1.9
  ErrorName=org.freedesktop.DBus.Error.AccessDenied  ErrorMessage="Operation not permitted"
  UniqueName=:1.10
  MESSAGE "s" {
          STRING "Operation not permitted";
  };
```

From reading the sources, it looks a bit like there was the intention of falling back to checking Linux capabilities when compiled without POLKIT:

1: https://github.com/systemd/systemd/blob/master/src/timedate/timedated.c#L771
2: https://github.com/systemd/systemd/blob/master/src/shared/bus-util.c#L441
3: https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/bus-convenience.c#L549

However, `sd_bus_query_sender_creds()` does not query the effective capabilities (through `sd_bus_get_name_creds`, even though `SD_BUS_CREDS_EFFECTIVE_CAPS` is set) without also having `SD_BUS_CREDS_AUGMENT` set. When using "augmented creds", the assert a few lines below will return `-EPERM`, because, apparently reading capablities from procfs is not safe.

**Describe the solution you'd like**

Is the described use-case considered valid by systemd developers?

If so, `sd_bus_query_sender_creds()` could use `sd_bus_creds_new_from_pid()`, as, according to the documentation, this is the only way to get a trustworthy credential object. Since this is public API, I am not sure how this change would interfere with other use of the API.

I'm willing to send a patch, if you think it's the correct approach.

**Describe alternatives you've considered**

Polkit is not really an option, so I'd need to fall back to not using org.freedesktop.timedate1.

**Comment by poettering** [comment]
Sorry, but this cannot be implemented safey. We need the creds at a well-defined point in time. Either at connection time or at the moment the method is enqueued. But for caps we can have neither, AF_UNIX doesn't attach them for us to sockets (unlike uid, pid, gid, selinux label and auxiliary gids), hence we cannot safely acquire them. We could derive them from the pid by going through /proc/$PID/, but that is racy, and hence suitable for informational purposes but not suitable for security decisions. (why racy? because pids easily overrun, and thus you could fool the service that it thinks you have caps, because once upon a time there way a process with the same PID that had caps)

The reason why there's code for handling this in systemd is kdbus: it had that functionality, it would attach the creds safely with messages, and hence we could make such decisions.

The SD_BUS_CREDS_AUGMENT logic in sd-bus is for retrieving the caps from /proc/$PID/, but when doing security decisions we explicitly do not take such creds into account, due to their racy nature.

Anyway, would love to add support to make this safe and support it, but for this the kernel would first have to learn attaching the caps to a socket safely. I.e. introduce SO_PEERCAPS to match the existing SO_PEERCREDS, SO_PEERSEC and SO_PEERGROUPS…

Hence, please work with the kernel community first to add such a sockopt, and then we can easily add this to sd-bus too, and would love to do so.

Closing this here hence, since this is not actionable for us right now. Hope that makes sense. Sorry!

**Comment by mrflow** [comment]
Wow, thanks for the very quick and detailed reply.

I think I will fall back to using polkit 0.105 for now.

**Comment by ptsneves** [comment]
If the bus(d-bus) already has it's own permission policies why do we need to have another mechanism to verify whether it is allowed? This leads tosystemd dbus buses being unusable even when they are explicitly allowed on dbus policy configuration and the result being a need for sudo.

With polkit and dbus policies, in most configurations this leads to authorisation being required in 2 places, if i am not mistaken. If i am correct the question is: Why is polkit more authoritative than the dbus policies?

**Comment by poettering** [comment]
dbus policies are pretty useless. non-interactive for starters, and they have no understanding about anything but method calls. that's usually not what you should authenticate though, you want something smarter that can actually authenticate the operations done onto objects taking the object identity into consideration. something that just matches function names as strings can never do that.

dbus policies are good for one thing: restricting UID access to bus name ownership. Other than that they are pretty much garbage.

**Comment by ptsneves** [comment]
> dbus policies are pretty useless. non-interactive for starters, and they have no understanding about anything but method calls. that's usually not what you should authenticate though, you want something smarter that can actually authenticate the operations done onto objects taking the object identity into consideration. something that just matches function names as strings can never do that.

Then even the caps mechanism on the sockets you suggested would not get you this smarter functionality you mention. As an example on setting the timezone, the CAP_SYS_TIME would say nothing on what timezone or formats you would allow, leading to my assertion that you may be being over-restrictive unnecessarily. The whole it's just a string argument is just not covered by the fix you propose.

> dbus policies are good for one thing: restricting UID access to bus name ownership. Other than that they are pretty much garbage.

You may think that, and i find it debatable, first because most core functionality in linux is controlled by gid/uid access to files. With simple uid/gid one can access /dev/mem!; A user may desire more security granularity, and for that need other systems are available on top and separatly, like xattrs, selinux or polkit to provide that granularity.

Second, because the bus system is a transport which is external to systemd. If a user desires the extra security granularity you rightfully support it through polkit. When a user does not support/want the extra granularity it should not systemd's right to force it's requirement.
