### ISSUE TITLE
systemctl show always returns 0 even when service isn't found

### ISSUE THREAD

**Issue by bcoca** [systemd/systemd#1105]
to reproduce:
`systemctl show idontexist; echo $?`

Though the output does show `LoadState=not-found` I would expect the return code to be non 0 as an easy way to detect failure.

Also the output shows a lot of misleading information, like `CanStart=Yes`

Another puzzling output is that `LoadError` is sometimes populated with 'No such file or directory', but not always, this seems to happen when certain symbols are mistakenly added to the service name input.: `systemctl show {{`

**Comment by poettering** [comment]
I prepped a fix for the CanStart=yes issue you pointed out in PR #1165.

I am not convinced that `systemctl show` should convey load state via the exit code, because that would be misleading. If we were unable to load a unit file that doesn't mean that it isn't running (for example, because somebody started a service, then removed its unit file and reloaded things, which leaves the service running but the load state failed). However, I am pretty sure that if we'd convey state via the exit code, then people will rather assume it's about the runtime state and not about whether the unit loaded or not. Also note that `systemctl status` _does_ report an exit code that indicates runtime state, however `systemctl show` only returns errors if we were completely unable to acquire the desired data.

I think ultimately this all comes down to the fact that systemd is completely fine with units that couldn't be loaded but are kept track of for a variety of reasons, and that this is not an issue that should be considered an error, and that should be reported as one. If that makes any sense.

Closing this now, as I am not convinced we really should change `systemctl show` to return an exit code conveying the load state of a unit.
