### ISSUE TITLE
Can systemd-run --uid, while root, work with systemctl --user commands?

### ISSUE THREAD

**Issue by heronhaye** [systemd/systemd#11216]
**Is your feature request related to a problem? Please describe.**
I want to, as root, run `systemctl --user` commands as another user, *and* get stdout and the exit code. I can `systemd-run --wait --uid myuser echo foobar`, and parse the output to get the unit filename and look at `journalctl`, but I can't get this to work for the command `systemctl --user status myservice.service`; `journalctl` shows

```Dec 19 12:09:30 myhostname systemctl[1639]: Failed to connect to bus: No such file or directory
Dec 19 12:09:30 myhostname systemd[1]: run-u357387.service: Main process exited, code=exited, status=1/FAILURE
Dec 19 12:09:30 myhostname systemd[1]: run-u357387.service: Failed with result 'exit-code'.
``` 

Passing `--user` to `systemd-run` doesn't seem to help either, I immediately get `Failed to create bus connection: No such file or directory`.

**Describe the solution you'd like**
Instructions on how `systemd-run` can be used to run `systemctl --user` commands while root, for another user.

**Describe alternatives you've considered**
I can use `machinectl shell myuser@ /usr/bin/echo foobar`, and this method works for `systemctl --user` commands, but this loses the exit code.

Setting the `XDG_RUNTIME_DIR` and the `DBUS_SESSION_BUS_ADDRESS` explicitly with `-E` in the `systemd-run` command works, but I have to get that info via `machinectl`. It seems a bit unwieldy to run both `machinectl` and `systemd-run`, and I'm also not sure if this is best practice or there is other config I should set up other than those environment variables.

**Comment by keszybz** [comment]
See #11000. Your use case is the same problem: you want to connect to the user manager instance from root.

**Comment by heronhaye** [comment]
Thanks for the pointer @keszybz. It would be great if `systemctl` could accept a `uid` command, for example, but I figured it was a design decision to disallow this.

Regarding the workaround I mentioned, am I correct that I need `machinectl` to find the `XDG_RUNTIME_DIR` for a user? I know it's usually `/run/user/{uid}` but I'm not sure if that's reliable or there are users using systemd with alternate runtime directories. The information in `/run/systemd/users/1000` is useful, but that file starts with `# This is private data. Do not parse.` so I didn't want to rely on that either.

**Comment by anitazha** [comment]
In systemd 248 you can do `systemctl --user -M <username>@foobar status myservice.service` to query a user's bus on the same host. I think this solves your request?

**Comment by poettering** [comment]
I think so too. Let's close.

**Comment by Lamieur** [comment]
@anitazha

systemctl -M claims to be for containers, which are not the issue. The issue was that it's impossible for a system administrator to check status of a user's unit, not to mention: control it.

All the -M syntax does for me  (RHEL9, systemd 250, which is > 248) is say "Failed to connect to bus: Host is down" if I put anything behind the @, or "Failed to start transient service unit: Connection reset by peer" if I say -M user@ without a host. No XDG_RUNTIME_DIR tricks work for root ("Failed to connect to bus: Operation not permitted"), no su - <user>  / systemctl --user status works either ("Failed to connect to bus: No medium found"), so we're back to su - <user> and only then the XDG_RUNTIME_DIR tricks. Try figuring this out from man systemctl.

**Comment by keszybz** [comment]
With recent versions, `systemctl -M <uid>@.host --user` can be used to connect to a user manager.

For example those two commands are equaivalent:
```console
$ systemctl -q --user -t socket
  dbus.socket           loaded active running D-Bus User Message Bus Socket
  pipewire-pulse.socket loaded active running PipeWire PulseAudio
  pipewire.socket       loaded active running PipeWire Multimedia System Socket
$ sudo systemctl --user -M $USER@.host --no-legend -t socket
  dbus.socket           loaded active running D-Bus User Message Bus Socket
  pipewire-pulse.socket loaded active running PipeWire PulseAudio
  pipewire.socket       loaded active running PipeWire Multimedia System Socket
```

If it doesn't work in RHEL, please report in the the RH bugzilla.

**Comment by Lamieur** [comment]
Hi Zbyszek, yes, your example (sudo from a desktop session) works.

But if I log in on tty2 and su -, or log in as root on tty2, or ssh root@machine, it doesn't.

I'm testing on F37 (systemd 251.14), not much more recent than RHEL9's systemd 250.

(I do take back the comment about containers, while jumping between machines and testing, I saw man systemctl from an older version, where there was no mention of user@.host, but it is there in 250+, sorry about that!)

**Comment by keszybz** [comment]
Most likely, `user@.service` is not running.

**Comment by akostadinov** [comment]
@keszybz , could you be more specific? What does it mean "`user@.service` is not running"?

I have this issue that when I run `sudo systemctl --user -M myuser@.host stop myservice` it works from a ssh session. But if I run `systemctl --user -M myuser@.host stop myservice` from a service file, I'm getting this connection reset error. 

Specifically this is a borgmatic hook, I cannot use normal systemd dependencies, because the services should stop momentarily while LVM snapshots are created and restarted before the backup service completes.
