### ISSUE TITLE
What are the "clear indications" of C.UTF-8 existing soon upstream?

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#11259]
v240 NEWS mentions that systemd now depends on C.UTF-8 "clear indications that upstream
glibc is going to make it available too." I'd like to understand what those indications are, because it's entirely non-obvious to me.

The last time I see this discussed on [libc-alpha](https://sourceware.org/ml/libc-alpha/2015-02/msg00293.html) is 2015. Similarly, there's a proposal on the [glibc wiki](https://sourceware.org/glibc/wiki/Proposals/C.UTF-8) which was added in 2015, but there's been no updates/followup since then.

The wiki page for the glibc 2.29 [release](https://sourceware.org/glibc/wiki/Release/2.29) makes no mention of this new locale, but does mention that glibc is about a month away (Feb 1 2019) from a release. I'd expect that given multiple distros have invented their own C.UTF-8 and that the indications of its upstream inclusion are now clear, that this would be mention-worthy. Cloning the glibc git repo yields no evidence that such a locale has been added.

Indeed, what have I missed in the intervening 3 years? IMO, the news item should have linked to the obvious indicator that this will be coming in a future release of glibc. Otherwise, this just looks like a losing bet to me.

**Comment by poettering** [comment]
The main upstream maintainer of glibc regularly posts on fedora devel, and blessed the fedora change in this regard. I took that as indication that this will sooner or later end up upstream too.

**Comment by falconindy** [comment]
As I see it, there's currently 2 problems that block inclusion of C.UTF-8 into glibc upstream:

* Added runtime bloat. Concern was raised about the addition 1.5MB that this adds as runtime overhead. "Consensus needs to be reached" as per this [upstream bug](https://sourceware.org/bugzilla/show_bug.cgi?id=17318). I'm not aware of any progress on this front.
* The locale, as shipped by Fedora and Debian, is broken with regard to sorting. This is pointed out on the aforementioned bug as well as on [fedora-devel](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/VRIO4YQV2B2G2DUUYNRTVYQDFCMZSZGX/) itself. Fixing this sorting problem has potential ABI breaking implications, and further runtime size bloat.

That fedora-devel thread is actually pretty interesting, as it contradicts your statement. Another Redhat employee and glibc contributor, Florian Weimer, states:

```
I think this is a very bad idea. The C.UTF-8 locale is Fedora-specific.
It is not upstream, and it is known to be broken in many ways. It may
or may not match what other distributions use.

I have argued for some time that the locale must be upstreamed, but
unfortunately, I'm not getting anywhere.
```

Arch Linux has zero interest in maintaining this out of tree locale especially if it's known to be broken, potentially in unfixable ways. We've rejected feature requests to do so, largely because of our distro-wide policy of not carrying distro-local features on top of upstream software. Systemd's adoption of this fedora/debian-specific feature means that we now have to carry a patch on top of systemd to either functionally revert 0db9bd200f62a5707ea16552537dcaad2d9e9331 (it doesn't revert cleanly), or default to `LANG=C`. Currently, programs *will* fallback to C (the same as any other invalid locale), but some complain loudly:

```
$ LANG=C.UTF-8 perl
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_COLLATE = "C",
        LC_NUMERIC = "C",
        LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

There's also a non-zero amount of bad behavior that programs might exhibit when being fed an invalid locale (we've surfaced a few of these in our build environment which previously use LANG=C, and now needs to pick an arbitrary UTF-8 locale). It's unclear what side effects setting a non-vetted C.UTF-8 will have on programs whereas C is simply a safe default with known behaviors and limitations.

For the sake of most distros who do not provide their own C.UTF-8 implementation, can we just default to a locale that exists upstream until the problems with C.UTF-8 are *actually* resolved and the feature is merged? I really don't see any strong evidence that this is going to happen any time soon.

**Comment by poettering** [comment]
I am not sure defaulting to a non-UTF-8 locale is a particularly great idea in 2018. That said, I figure it would be OK to merge a patch that mkes this a meson configurable param at build time so that people can pick en_US.UTF-8 or even C as default if they really feel the urge to...

**Comment by boucman** [comment]
I'm of two mind on that... @poettering has a point... it's 2018 and it's really time to move forward, but OTOH , as long as upstream doesn't have C.UTF-8 this is going to create a lot of problems at the distribution level...

especially for small distros that don't have the manpower to maintain glibc patches... and glibc is known to not being reactive and realying on downstream to fix problems in releases.

so... yeah. I think most small distro would have to revert to C anyway, and making it a compile option would ease that quite a bit until upstream merges some sort of utf-8 support

**Comment by michaelolbrich** [comment]
And embedded systems often don't have any locale data at all, so a build-time option for this would be great.

**Comment by falconindy** [comment]
#11286 is the pull request, but I wonder -- if you truly believe this is the right thing to do, why not make Fedora's glibc default to C.UTF-8? Why is systemd owning this change?

**Comment by Scimmia22** [comment]
While it's true that defaulting to non-UTF-8 isn't great, neither is relying on fedora's fork of glibc instead of upstream behavior.

**Comment by poettering** [comment]
> #11286 is the pull request, but I wonder -- if you truly believe this is the right thing to do, why not make Fedora's glibc default to C.UTF-8? Why is systemd owning this change?

Well, how would that even look like in Fedora? assume that unset env vars mean C.UTF-8 rather than C? That's quite a compat borkage I think, as programs that check the env vars would be quite mislead compared to the old behaviour... With the approach we picked however I think we are on a much safer side there, as the env vars are always in sync with what glibc does...

Or to say this differently: glibc is probably not the right piece of software for setting env vars, only for reading them. And for compat reasons it's probably a lot safer to change the env vars to update behaviour, not to change the behaviour when they aren't set...

And then there's also the fact that while for systemd compat is important, it's even more important for glibc. i.e. we have slightly more freedom to change things in systemd, than glibc has, if you will.

**Comment by boucman** [comment]
Embedded distro are usually C only since they don't have... users.

**Comment by barthalion** [comment]
> But dunno, I think the approach now found (to make it build-time configurable, but defaulting to UTF-8) is workable. It allows distros that still don't want to accept UTF-8 to stick with 7bit ASCII for the time being, but doesn't hold back the others.

I think you keep missing the point. The entire problem comes from the fact that v240 insisted on using a locale that is not merged upstream and nothing indicates it's going to happen anytime soon. Even mentioning Debian is flawed as locale is implemented slightly differently than on Fedora.

**Comment by keszybz** [comment]
I agree that changing this in glibc does not seem right. It's systemd that configures the locale (through localed or otherwise), and hence we should own the defaults.

It's unfortunately that glibc is dragging this out. I don't think it's intentional, but rather that there were implementation bugs (the collation issue, worries about bloat), and there wasn't enough manpower to figure out the details. Hopefully, with the renewed interest, this will finally get finished.

Anyway, I think that with #11286 merged, we're good, because the new default only takes effect on systems which have C.UTF-8.

Python now defaults to C.UTF-8 (https://fedoraproject.org/wiki/Changes/python3_c.utf-8_locale, https://www.python.org/dev/peps/pep-0538/), so actually we're not the first implement this kind of change. Also, please note that "not having users" doesn't actually matter. Python is a good counterexample: locale settings matter for i/o, and those problems are the same with or without a console user.

**Comment by poettering** [comment]
> I think you keep missing the point. The entire problem comes from the fact that v240 insisted on using a locale that is not merged upstream and nothing indicates it's going to happen anytime soon. 

Hmm, I still think the fact that the upstream maintainer of glibc and the downstream maintainer of it in Fedora are the same and that he said he works on it, and supports it in Fedora already is indication this will be added upstream too once the remaining issues are fixed. Yes, it's a pity this has been taking so long, but the players involved not only all agree that doing C.UTF-8 is a good thing apparently, but also said publicly they are working it, and the two big distributions already adopted it beforehand, even though some issues remain, and they picked slightly different implementations.

Also, while v240 insisted on it, a PR has been merged now that allows downstreams to change the default locale used during build time.

**Comment by codonell** [comment]
For the record I'm stating my clear intent to get C.UTF-8 upstream and checked into glibc master. So far I have only succeeded in getting it into Fedora. The reasons for the delay are varied and technical (problems with full code-point sorting need fixing, issues with the size of the full collation tables and collation compression), but I think we will solve them. Adding C.UTF-8 upstream is one of my goals, and I keep cleaning up the locale handling code to get more of the prerequisites in place.

Just to be clear, the current C.UTF-8 in Fedora and in all other distribution has real bugs when trying to fully exercise all of the code-points for collation or transliteration, but I expect these bugs to be outside the average use cases.

It is up to systemd maintainers to decide if they are ready to use C.UTF-8 as a distribution default setting, worst case you fall back to C/POSIX if it's not present. I'm aware that Python wants the same thing, which is why we did a C.UTF-8 in Fedora, specifically for Python. Many other distributions are adopting a C.UTF-8 derived from either Fedora or Debian locale sources, and both are OK for their intended uses. This doesn't cover all downstream distributions, and this is really what this issue is about.

I'll work harder to get C.UTF-8 upstream ;-)

**Comment by poettering** [comment]
@codonell thanks a ton for weighing in. I figure I should have pinged you in advance about this all. Sorry for that!

**Comment by codonell** [comment]
@poettering I happy to provide answers whenever needed. I trust the systemd developers to decide to reach out when needed. In this case I was asked by @falconindy to comment on this issue. Dave and I have been having a discussion about C.UTF-8 and the problems with full support.

**Comment by heftig** [comment]
Has there been any progress in the last year?

**Comment by codonell** [comment]
@heftig No progress. We fixed up C.UTF-8 in Fedora and RHEL though to contain full weights for all code points, and prioritized other work. It is still high on my list of things to fix (top 5).

**Comment by codonell** [comment]
glibc 2.35 will have C.UTF-8 which harmonizes all the downstream distribution changes, resolves collation issues, and is minimally sized given LC_CTYPE expectations for Unicode (~380KiB). It did require a new LC_COLLATE directive, "codepoint_collation", to support the expected semantics (though the code for zero collation rules always supported fallback to strcmp/wcscmp).

See: https://sourceware.org/git/?p=glibc.git;a=commit;h=466f2be6c08070e9113ae2fdc7acd5d8828cba50
See: https://sourceware.org/pipermail/libc-alpha/2021-September/130759.html

**Comment by DaanDeMeyer** [comment]
@codonell Thanks so much for making this happen!
