### ISSUE TITLE
tmpfiles.d: allow "C" lines to copy stuff into pre-existing empty destination dirs

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#11287]
Hello!

I'm trying to support factory resetting on my distro, which entails the ability to boot with an empty `/var` and `/etc`. I use OSTree, so I cannot delete the folders completely without messing things up, but I can make them empty.

The only type in tmpfiles.d I've been able to find that actually copies content is `C`, but it doesn't copy anything if the destination exists. Something like `C /etc - - - /usr/etc` would not work because `/etc` exists, even though it is empty. 

Could there be a new type that recursively copies content, just like `C`, but will do so even if the destination exists (as long as it is empty)? Is there some better solution to doing this?

Thank you!

**Comment by cgwalters** [comment]
Well, we could easily define a systemd unit in libostree that runs just before tmpfiles.d that does this, something like:

```
[Unit]
ConditionDirectoryEmpty=/etc
DefaultDepenencies=no
Before=systemd-tmpfiles.service
After=ostree-remount.service

[Service]
ExecStart=ostree admin prepare-etc
```

**Comment by AdrianVovk** [comment]
@cgwalters the documentation didn't mention anything about `ConditionDirectoryEmpty` and `ostree admin prepare-etc`. I'll try these and close this issue if it works!

Thank you!

**Comment by yuwata** [comment]
`ConditionDirectoryNotEmpty=` is the correct setting name.

**Comment by AdrianVovk** [comment]
@yuwata What if I want to check that the directory exists and **is** empty?

```
ConditionPathExists=/etc
ConditionDirectoryNoEmpty=!/etc
```

Would the above snippet work?

**Comment by AdrianVovk** [comment]
@cgwalters I might have misunderstood your response. Are you saying `ostree admin prepare-etc` exists or you could implement it?

**Comment by poettering** [comment]
Hmm, I think we should probably tweak the "C" line type to do a merge copy if all of the following conditions hold:

1. The source is a directory
2. The souce is non-empty
3. The destination is a directory
4. The destination is empty

(And of course keep the current behaviour of copying if destination doesn't exist in place, too)

I think such an extension would be a relatively nice, minor change in behaviour we probably can get away with without considering that a compat breakage.

**Comment by poettering** [comment]
@AdrianVovk what I just proposed there would cover your usecase, right?

**Comment by poettering** [comment]
> @poettering Yes, it should. I'm a little confused about the "merge copy". What are you merging if the destination is empty?

Well, normally during the copy operation none of the inodes we copy already exist in the destination. All inodes processed during the copy are created anew. This is different in what you are asking for, as in that case the top-level destination inode already exists, and hence we have to "merge" both trees, even if the destination tree is otherwise empty at that moment. The resulting tree after all will be a combination of the inodes from the source and the destination (specifically: the top-level directory inode that already existed in the destination, plus all the copies of the other inodes).

**Comment by kirbyfan64** [comment]
So from a bit of poking around in the source code, I'm thinking there are two ways to solve this:

- Change fd_copy_directory to always merge empty directories, even if COPY_MERGE isn't given.
- Add a COPY_MERGE_EMPTY flag that only merges if the target is empty.

Personally, I'm kind of feeling like the former would be better, because from looking through everywhere copy_tree_at is used, they all seem to cautiously benefit from merging with empty directories by default.

**Comment by poettering** [comment]
@kirbyfan64 second option looks a tiny bit nicer to me too. Happy to take a patch ;-)
