### ISSUE TITLE
Bring back DBUS_SESSION_BUS_ADDRESS

### ISSUE THREAD

**Issue by foutrelis** [systemd/systemd#11293]
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Xfce 4.12 starting normally and Chromium having access to its encrypted cookies.

**Unexpected behaviour you saw**
 > [Xfce not starting](https://forum.manjaro.org/t/systemd-240-update-breaks-graphical-login/69396/20). After xfce4-session was patched to avoid launching its own dbus session, Chromium was next in the list of broken things:

    ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server
    address: Unknown address type (examples of valid types are "tcp" and on
    UNIX "unix")

> And that's because [Chromium sets `DBUS_SESSION_BUS_ADDRESS` to `disabled:` if it's unset](https://cs.chromium.org/chromium/src/services/service_manager/embedder/main.cc?rcl=26d457a8e90b216b29932d587a183a00bcfb2c09&l=334).

**Steps to reproduce the problem**

Try to use Xfce and/or other desktop environments that have grown to depend on `DBUS_SESSION_BUS_ADDRESS` being set in order not to use dbus-launch themselves.

Also try to use Chromium (or Chrome, I guess) when `DBUS_SESSION_BUS_ADDRESS` is unset; all cookies should be inaccessible because the "Safe Storage" secret cannot be fetched from the keyring.

**Comment by foutrelis** [comment]
Having pam_systemd set this important envvar was pretty neat; IMO revert commit 2b2b7228bffef626fe8e9f131095995f3d50ee3b.

**Comment by poettering** [comment]
Not sure we should change this back. Chromium really shouldn't do what it is doing there. Given that it is open source and they appear to have a bug tracker I think it's better to file a bug there asking them to find a different solution for their problem.

Moreover a local fix is easy to do, just set the session bus env variable in a wrapper script around chromium. As long as it is set somewhere all is good, and it doesn't have to be systemd that sets this.

(/cc @smcv)

**Comment by andrevmatos** [comment]
Flatpak apps which communicate with DBUS are also broken after this change. Opening external links through xdg-open/portals doesn't work, as well as exported app/globalmenus and systrays.

**Comment by LionNatsu** [comment]
Maybe related to https://github.com/systemd/systemd/issues/1600 .

**Comment by smcv** [comment]
> Chromium really shouldn't do what it is doing there.

For context, they set `DBUS_SESSION_BUS_ADDRESS` to avoid the implicit default to the equivalent of[1] `unix:path=$XDG_RUNTIME_DIR/bus;autolaunch:`, because their malloc reimplementation deadlocks when the libdbus `autolaunch:` code path tries to use readdir() in /proc to close all fds before executing dbus-launch.

libdbus could in principle have an API call that globally disables all subprocess-based transports, which Chromium could call; but nobody has contributed that yet, and if someone did, Chromium couldn't call it yet because it needs to be compatible with deployed libdbus versions.

libdbus could in principle use the getdents64 syscall instead of readdir, but nobody has contributed that either, and I'm reluctant to rely on specific syscalls that glibc deliberately doesn't wrap.

Chromium could in principle change their malloc to behave more like glibc's by using pthread_atfork(), but they haven't.

> just set the session bus env variable in a wrapper script around chromium

You can't do this without making assumptions about what the correct default is in the absence of the environment variable, duplicating what happens in libdbus, GDBus etc. (and until recently, in libpam_systemd). This would be one more place that needs to change if that logic ever changes again.

> Flatpak apps which communicate with DBUS are also broken after this change.

To fix this, Flatpak (or possibly xdg-dbus-proxy) would have to duplicate the logic from libdbus, GDBus etc. that selects a default session bus address in the absence of the environment variable, or call into `g_dbus_address_get_for_bus_sync()` to get the same address GDBus would have used. This would be one more place that needs to change if that logic ever changes again.

[1] I say "the equivalent of" because it's not *exactly* `unix:path=$XDG_RUNTIME_DIR/bus`: the code path that looks there also checks for the right directory ownership, is hard-coded to be tried before the configure-time default of `autolaunch:`, and cannot be reached by specifying an address string. I proposed an `xdg-runtime:` transport that would be exactly equivalent, but @poettering rejected that during review of [fd.o#61303](https://bugs.freedesktop.org/show_bug.cgi?id=61303).

**Comment by loqs** [comment]
A lot of session managers broke with this change because they have code similar to https://gitlab.gnome.org/GNOME/gnome-session/blob/3296bdcdb87bfd853d497254fba53d9a69deb62f/gnome-session/main.c#L180

**Comment by heftig** [comment]
Since the user `dbus.socket` sets this environment variable, maybe this can be solved more generically by having pam_systemd merge the manager's environment into the session environment?

**Comment by raveit65** [comment]
slick-greeter and lightdm-gtk DMs doesn't start anymore in current fedora 30 (rawhide) because of latest systemd-240-2.fc30.
With systemd-239-10.git3bf819c.fc30 all is fine.
That means that MATE, Cinnamon and xfce spins can't be used in f30 because those DEs are using slick-greeter and lightdm-gtk.
Please fix before we branch f30.

**Comment by poettering** [comment]
@smcv hmm, what#s your take on this? We could override the env var in pam_systemd again and hardcode it to "unix:path=$XDG_RUNTIME_DIR/bus", right after setting XDG_RUNTIME_DIR.

I noticed that the dbus spec never documents this as the default, so there's some validity in saying that setting the env var always is probably more in line with the dbus spec than saying that every body should rely on the implied logic, as the implied logic is not formalized and might thus depend on the dbus client library implementation...

Opinion?

**Comment by smcv** [comment]
In the short term I would say that reverting 2b2b7228 would be the best plan.

> I noticed that the dbus spec never documents this as the default

Right, the implicit default is really a quality-of-implementation thing for client libraries at the moment, rather than part of the spec. In at least libdbus (possibly others) it's compile-time configurable.

I would not be comfortable with documenting a default in the spec unless it was something we could express as an address literal. At the moment `unix:runtime=yes` is available as a listenable address but not as a connectable address. We could potentially make `unix:runtime=yes` work as a connectable address too, meaning "if $XDG_RUNTIME_DIR is set and owned by us, and $XDG_RUNTIME_DIR/bus is a socket owned by us, then use it, else fail" (the same as the `xdg-runtime:` that I proposed previously). If we had that, then an unset `DBUS_SESSION_BUS_ADDRESS` on Unix would normally be equivalent to `unix:runtime=yes;autolaunch:`.

I know sd-bus doesn't implement `autolaunch:` and you probably don't want it to, but in that case we can think of it as having a trivial implementation of `autolaunch:`, which is "fail to connect, and move on to the next address in the semicolon-separated list if there is one" - just like any other unimplemented address.

> We could override the env var in pam_systemd again and hardcode it to "unix:path=$XDG_RUNTIME_DIR/bus", right after setting XDG_RUNTIME_DIR.

That's essentially the same as reverting 2b2b7228, right? (Assuming that XDG_RUNTIME_DIR doesn't need to be escaped in a D-Bus address, but systemd's value for XDG_RUNTIME_DIR has been chosen to not need escaping, so that's OK.)

**Comment by smcv** [comment]
In Debian, the distro X11 integration scripts in `/etc/X11/Xsession.d` do this: https://salsa.debian.org/utopia-team/dbus/blob/debian/master/debian/20dbus_xdg-runtime

That might explain why systemd 240 (with commit 2b2b722) breaks some X11 session implementations in Fedora that work in Debian.

**Comment by raveit65** [comment]
@poettering 
Is this really tested?
I added https://github.com/systemd/systemd/pull/11327 and did a koji scratch build.
https://koji.fedoraproject.org/koji/taskinfo?taskID=31879037 for fedora30.
I am sorry to say that doesn't fix the problem , slick-greeter DM doesn't start.
It is impossible to reach graphical target.

Maybe someone other can test this scratch build for fedora?

**Comment by smcv** [comment]
> Since the user dbus.socket sets this environment variable, maybe this can be solved more generically by having pam_systemd merge the manager's environment into the session environment?

If that's possible, then that would ensure that they don't get out of sync. At the end of the day the manager (systemd --user) is really the only thing that knows whether it has dbus.socket.

**Comment by DwarfFighterCleric** [comment]
> A lot of session managers broke with this change because they have code similar to https://gitlab.gnome.org/GNOME/gnome-session/blob/3296bdcdb87bfd853d497254fba53d9a69deb62f/gnome-session/main.c#L180

OMG, this is still happening... So is this something that affects all desktops, not only Xfce? In Xfce, it broke even the settings not being saved across reboots anymore.
Some time had passed ever since. Did you notice if this issue was ever resolved? Are desktop session saving mechanisms still non-functional because of this? Any recommendation of desktop that fixed and stayed up-to-date with this? I'm considering having to migrate away from Xfce.

**Comment by DwarfFighterCleric** [comment]
>
> If that's possible, then that would ensure that they don't get out of sync. At the end of the day the manager (systemd --user) is really the only thing that knows whether it has dbus.socket.

Does anyone know if there's a way forcefully "unload" or "reload" the entire Xfce desktop from Systemd or to re-init it somehow? Without requiring a reboot.  
Reboots are not really an option for Live-Session management across multiple machines and remote chroot environments.

**Comment by smcv** [comment]
> OMG, this is still happening

This issue was closed long ago, so I suspect you are seeing a different issue with the same superficial symptoms. Please contact your OS distribution vendor for support.
