### ISSUE TITLE
systemctl daemon-reexec fails when run from a PID namespace

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#11300]
**systemd version the issue has been seen with**
systemd-240

**Used distribution**
Gentoo
https://bugs.gentoo.org/673794

**Expected behaviour you didn't see**
`systemctl daemon-reexec` should succeed.

**Unexpected behaviour you saw**
`systemctl daemon-reexec` fails with message `Failed to connect to bus: No data available`.

**Steps to reproduce the problem**
Run systemctl daemon-reexec in a PID namespace.
```
unshare -f -p systemctl daemon-reexec
```
I think the the following call stack fails:
```
pid_is_valid()
getpeercred()
bus_check_peercred()
bus_connect_system_systemd()
bus_connect_transport_systemd()
acquire_bus()
daemon_reload()
```

**Comment by floppym** [comment]
Some additional data: the equivalent `busctl` command succeeds under the same conditions.
```
unshare -f -p busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager Reexecute
```

**Comment by poettering** [comment]
hmm, so you want to talk to the host PID 1 from a process in a PID namespace further down the tree? Why would that even be a good idea? I mean, PIDs are exposed all over the place over dbus, and the assumption is always that every peer on the bus lives in the same environment, and sees the same processes, and the same PIDs hence.

I mean, PID namespaces are probably the most defining type of namespace for containers. Why would it be a good idea to allow a container down the tree talk to the host as if it was part of the host?

**Comment by bl33pbl0p** [comment]
I don't think tying PID namespaces to just containers is nice. They're useful for isolation on their own (and making use of them in user sessions is useful too, since hidepid is totally broken with many things). As can be seen, they're being used in Gentoo's sandbox tool here, which just uses it for isolation (during the build, but also to do post installation tasks like reexec after an upgrade). The manager can still see the client's PID, it's just the client who'd see any credentials of the manager as PID 0 (translated across the namespace boundary).

It seems the pid_is_valid's greater than 0 check is causing this, which then returns -ENODATA on failure.

**Comment by floppym** [comment]
Gentoo's package manager (Portage) uses PID namespacing primarily so it can catch any rogue processes left over after a package build and/or install. This is relatively new feature, so it might require some tweaking.

Alternatively, Portage can use cgroups for this purpose, but systemd makes this more difficult since it insists on owning all cgroups. Portage doesn't speak D-BUS at the moment.

> Why would it be a good idea to allow a container down the tree talk to the host as if it was part of the host?

A full container would have a separate root filesystem (chroot), and would be unable to access the system bus socket.

> so you want to talk to the host PID 1 from a process in a PID namespace further down the tree? Why would that even be a good idea?

I'm not an expert on this stuff, so I'm not sure if it is a good idea or not. If it poses some security problem, we can drop this request and I will ask the Portage maintainer to run post-install tasks in the root PID namespace instead of a child namespace.

**Comment by floppym** [comment]
> The manager can still see the client's PID, it's just the client who'd see any credentials of the manager as PID 0 (translated across the namespace boundary).

Ah, this makes more sense now. I guess I don't see why the client would need to do any credential checking at all. So long as it can send the reload message, why should it care what is listening on the other end of the socket?

**Comment by cdown** [comment]
> Alternatively, Portage can use cgroups for this purpose, but systemd makes this more difficult since it insists on owning all cgroups. Portage doesn't speak D-BUS at the moment.

Another alternative for the short term is to use `Delegate=` to get a delegated subtree, if you need time to migrate to using DBus. Buyer beware long term though -- if you end up actually needing any kind of real cgroup management, DBus is the way to go, otherwise you'll end up implementing yet another cgroup manager (and certainly not as cohesively or sanely as systemd).

**Comment by floppym** [comment]
> Another alternative for the short term is to use Delegate= to get a delegated subtree, if you need time to migrate to using DBus.

It's not clear to me how we would use Delegate, given that Portage knows nothing about systemd service or slice units.

**Comment by poettering** [comment]
> I don't think tying PID namespaces to just containers is nice. They're useful for isolation on their own (and making use of them in user sessions is useful too, since hidepid is totally broken system wide). As can be seen, they're being used in Gentoo's sandbox tool here, which just uses it for isolation (during the build, but also to do post installation tasks like reexec after an upgrade). The manager can still see the client's PID, it's just the client who'd see any credentials of the manager as PID 0 (translated across the namespace boundary).

Well, PID namespaces are not just a way to sandbox stuff, they explicitly introduce a notion of a sub-init, i.e. a new PID 1, and hence it appears to me that it would only be natural to expect clients talk to that instead of the host's PID 1. 

i.e. it's not clear to me to two accept the notion of allowing two different init systems within the same context is a good idea. If you have your own PID 1, then stick to that. if you are a child of the host PID 1 then use that, but don't mix and match that stuff...

This thinking is btw why in systemd I never added a "PrivateProcesses=" concept: it's just weird if there's always a second-level PID 1 placed in the middle, and you get a mixture of two init programs there...

There has been work on fix the kernel's hide_pid  option to be a true mount option by @tixxdz so that we can make use of it for sandboxing. I think that'd be a much better way out here.

**Comment by bl33pbl0p** [comment]
@poettering 

I agree, but in context of the sandbox tool it is using it by launching the build stuff as PID2 under a sub init in the PID namespace. This was being discussed elsewhere, and the other option would be to use cgroups (but then that either requires portage to ship its own wrapper/service that turns on Delegate=yes for it to manage hierarchy on its own for tracking processes or talk to systemd over D-Bus to do other things (maybe use a scope unit and so on, even through systemd-run). That however becomes a much bigger change. That said, I guess it might be acceptable to just use busctl instead of systemctl here (since the former is a more low level tool and I guess allowing the user facing tool to talk to something other than the system PID1 is not desirable).

**Comment by floppym** [comment]
Portage has been updated to run the post-install phase without creating a separate pid namespace.
