### ISSUE TITLE
`systemctl poweroff` makes some systems reboot while `/sbin/halt` succeeds

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#11311]
With systemd 239 and Linux 4.14.x on some Dell desktop systems `sudo systemctl poweroff` does not power them off, and they still reboot. Using `/sbin/halt` works though. `halt` from the GRUB CLI works too.

**Comment by floppym** [comment]
systemd just calls `reboot(LINUX_REBOOT_CMD_POWER_OFF)`. If something fails, it is likely a kernel problem, not a bug ins systemd.

**Comment by poettering** [comment]
"does not power them off, and they still reboot"? what do you mean by "they still reboot"? Do they reboot instead of powering off?

Do they power off correctly if you do "systemctl poweroff -f"? Do they power off correctly if you do "systemctl poweroff -ff"?

The latter just calles the kernel reboot() syscall. If the system doesn't reboot in that case this is clear indication that systemd is not at fault, but the kernel is.

**Comment by poettering** [comment]
Let's close this due to lack of response, and since this really looks like a kernel/firmware issue and not a systemd issue. We just ask the kernel to reboot, that's all.
