### ISSUE TITLE
core: transaction building logic recursively adds jobs for deps wrt anchor job, causing unwanted jobs to get enqueued and start up unit

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#11338]
transaction_add_job_and_dependencies ignores unit masked errors, unit not found errors, and units where job type is not applicable errors when walking through UNIT_WANTS. This means that since recursive traversal is done wrt anchor job, checks happen there recursively causing unwanted jobs to successfully get enaqueued and startup even when not intended, because anchor job has Wants= dep type (so not-found/mask/job type not supported errors get ignored) by the parent function (with UNIT_WANTS).

Test case:
```ini
# foo.service
[Unit]
Description=anchor unit foo
Wants=bar.service
After=bar.service
[Service]
ExecStart=/bin/sleep infinity

#bar.service, baz.service is non existent
[Unit]
Description=bar
Requires=baz.service
After=baz.service
[Service]
ExecStart=/bin/sleep infinity
```

Doing a `systemctl start foo.service` will start both foo.service and bar.service, due to the aforementioned logic, instead of bar failing (since UNIT_REQUIRES has no check to ignore ENOENT nout-found). However, as expected, if one changes anchor job's dep to UNIT_REQUIRES, bar fails, as expected.

What exactly is seen:

```
Jan 05 11:03:40 jupiter systemd[925]: foo.service: Trying to enqueue job foo.service/start/replace
Jan 05 11:03:40 jupiter systemd[925]: bar.service: Cannot add dependency job, ignoring: Unit baz.service not found.
Jan 05 11:03:40 jupiter systemd[925]: foo.service: Installed new job foo.service/start as 4199
Jan 05 11:03:40 jupiter systemd[925]: bar.service: Installed new job bar.service/start as 4216
Jan 05 11:03:40 jupiter systemd[925]: foo.service: Enqueued job foo.service/start as 4199
```

Bug-Reported-by: user booya_ on #systemd IRC.

**Comment by bl33pbl0p** [comment]
This is what happens, I think:

* foo.service start job is added, then it is set as anchor job.
* The loop for UNIT_WANTS calls transaction_add_job_dependencies for it's dependency bar.service
* bar.service job is added, it is linked to anchor job (by), then the UNIT_REQUIRES loop calls transaction_add_job_dependencies for it's dep baz.service, which is not existing. bus_unit_validate_load_state returns with r, r < 0 but not -EBADR, so it goes to fail, which returns to foo.service's loop, which then logs and discards the error.

**Comment by bl33pbl0p** [comment]
foo.service Wants= bar.service BindsTo= baz.service (with ordering), BindsTo= doesn't let bar.service start only as a consequence of the unit_check_binds_to call on state change, which takes it down as the bound unit is not active. It's still a problem though with Requisite=/Requires=/Conflicts=.

**Comment by bl33pbl0p** [comment]
Someone got bit by this: https://serverfault.com/questions/952668/systemd-starting-service-even-if-service-in-requires-wont-start/

**Comment by dovi5988** [comment]
That would be. Bump!

**Comment by bl33pbl0p** [comment]
@poettering

Anything we can do about this? Two people mentioned here and 5 more I have seen hitting this so far (on IRC), some are hitting this in ways that are not immediately obvious (through RequiresMountsFor=).

**Comment by dovi5988** [comment]
PING!

**Comment by Laxen** [comment]
I think I'm hitting the same bug on systemd version 243 and it's also related to this issue created in 2016: https://github.com/systemd/systemd/issues/4937

I have this very simple a.service file:
```
[Unit]
Description=The A Service
Requires=nonexisting.service
After=nonexisting.service

[Service]
Type=oneshot
ExecStart=/usr/sbin/a.sh
```
Where nonexisting.service does not exist (duh). You would assume that a.service would not start at all since it requires a service that doesn't exist. But it starts up fine _when systemd starts up_. However if i do `systemctl restart a.service` it fails with the message:
```
Failed to restart a.service: Unit nonexisting.service not found.
```
The Requires= unit can be anything, it doesn't have to be a service. For example this bug makes mount units useless since any service that Requires= a mount unit would start up anyway even if that mount unit doesn't exist. 

This seems like a critical bug that shows up in so many different ways and is super easy to reproduce, so I'm a bit worried that it hasn't been solved yet. I don't know anything about the internals of systemd, but is there some fundamental issue in the way systemd is built that makes this impossible to solve?

**Comment by msekletar** [comment]
@Laxen I've tested your scenario on v246 and I can't reproduce anymore. Please double check my findings and if you still can reproduce please file a separate issue since your issue is related but different (much more serious!).
