### ISSUE TITLE
Timer's start/stop job waits until the service's stop job finishes

### ISSUE THREAD

**Issue by kalgynirae** [systemd/systemd#11354]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > `systemctl start foo.timer` (or `systemctl stop foo.timer`) finishes immediately regardless of the state of foo.service.

**Unexpected behaviour you saw**
 > If foo.service is deactivating, `systemctl start foo.timer` (or `systemctl stop foo.timer`) blocks until foo.service's stop job finishes.
> 
> Perhaps I'm missing something, but I can't understand why the state of the service should affect whether the timer can start or stop (and even if so, why deactivating is the only state that affects it).

**Steps to reproduce the problem**
1. Define a service that takes a while to stop (foo.service) and a corresponding timer (foo.timer).
    ```
    $ systemctl cat foo.service foo.timer
    # /etc/systemd/system/foo.service
    [Service]
    Type=oneshot
    RemainAfterExit=yes
    ExecStop=/bin/sleep 60
    TimeoutStopSec=60s

    # /etc/systemd/system/foo.timer
    [Timer]
    OnCalendar=hourly
    ```

2. Start and stop the service (with `--no-block`).
    ```
    $ systemctl start foo.service
    $ systemctl stop foo.service --no-block
    ```

3. While the service is deactivating, attempt to start (or stop) the timer.
    ```
    $ systemctl start foo.timer
    ```

4. Observe that start/stop job for the timer waits until the service's stop job finishes.
    ```
    ^C
    $ systemctl list-jobs
      JOB UNIT        TYPE  STATE
    20132 foo.timer   start waiting
    20131 foo.service stop  running

    2 jobs listed.

5. If desired, repeat the above steps with a service that takes a while to start, and observe that the start/stop job for the timer finishes immediately while the service is still activating.

**Comment by bl33pbl0p** [comment]
This is expected and working as designed.

Timer units automatically gain Before= dependency on service (implicitly, so cannot be overriden) they are supposed to activate, hence this ordering is symmetrically opposite of what it will be on startup. Therefore, ordering is maintained when both are in run queue.

Now, to understand why timer start job will be ordered after stop job of service is complete (ordering only has effect as long as both are in queue):

* foo.timer has Before=foo.service, so if start jobs are in queue timer's job is dispatched before service's start job.
* This means if stop job for both are in queue in stop job of foo.timer will be dispatched *after* stop job of foo.service (since when stopping it must stop after service, since it starts before service).
* A special case is start foo.timer and stop foo.service, this means that foo.timer job is changing state so it must wait for foo.service's stop/restart job (and restart job is defined only until the unit is stopping, after which it is converted to start job, where your foo.timer will be triggered had this been restart, before starting foo.service over again).

start foo.timer + stop foo.service -> stop foo.service, then start foo.timer

Understand it as if both have a pair stop jobs and start jobs in transaction and what order things will be dispatched in, so same logic is followed here:
If I have restart job for foo.timer, and restart job for foo.service (restart job just stops before converting itself to start job):
restart job foo.service, restart job foo.timer, start foo.timer, start foo.service
^-- stopping                        ^-- stopping

By this logic, any type of combination is synchronized like restarts.

**Comment by kalgynirae** [comment]
Thanks for the detailed explanation. The stop foo.timer + stop foo.service case makes a lot of sense. The start foo.timer + stop foo.service case is still unintuitive to me, but with your explanation I can understand why it behaves the way it does. I see now that this is explained in the documentation for `Before=` and `After=`, but before your explanation I hadn't realized that `Before=` was at play here:

> Given two units with any ordering dependency between them, if one unit is shut down and the other is started up, the shutdown is ordered before the start-up. It doesn't matter if the ordering dependency is After= or Before=, in this case. It also doesn't matter which of the two is shut down, as long as one is shut down and the other is started up. The shutdown is ordered before the start-up in all cases.
