### ISSUE TITLE
Systemd stuck in Activating(Start)

### ISSUE THREAD

**Issue by rajatrj16** [systemd/systemd#11430]

**Comment by poettering** [comment]
This is not useful as bug report. Also, before reporting a bug here, make sure that it really is an upstream issue and reproducible in one of the two most recent upstream versions of systemd. Otherwise, please always report issues to your downstream distro first. Thank you for understanding. Closing hence.

**Comment by danielkrajnik** [comment]
systemd doesn't make it clear why unit gets stuck in Activating(Start) state (which does happen)
