### ISSUE TITLE
lang: missing translations for AR and NL

### ISSUE THREAD

**Issue by MeggyCal** [systemd/systemd#11480]
It would be nice if somebody translated the strings to these languages. I guess there are some users who would appreciate it.

**Comment by keszybz** [comment]
Yes, it would be nice. The same applies to most other languages — we only a dozen translations or so. Patches are welcome!

I'll close this ticket, not because it's invalid, but because it is "obvious" — if somebody submits a PR that adds a translation, for those languages or any others, we'll gladly merge it, but there's no point in having a hundred tickets for various languages cluttering up the issue list.
