### ISSUE TITLE
kernel-install fails to add initrd to the boot loader entry

### ISSUE THREAD

**Issue by solpeth** [systemd/systemd#11572]
**systemd version the issue has been seen with**
> systemd 241-RC1

**Used distribution**
 > Gentoo Linux

**Expected behaviour you didn't see**
 > kernel-install add <kernel-version> <kernel-image> should add the initrd line to the boot loader entry

**Unexpected behaviour you saw**
 > The initrd line is left out of the boot loader entry, despite being successfully generated.

**Steps to reproduce the problem**

1. Compile kernel (in this case, 4.20.5-gentoo)
2. run `kernel-install add 4.20.5-gentoo arch/x86_64/boot/bzImage`
3. Observe dracut correctly building an initramfs
4. Run `bootctl list` and observe that no initrd line has been added to the loader entry.

I am unsure if this is at all related to PR https://github.com/systemd/systemd/pull/11570

**Comment by yuwata** [comment]
Yeah, we already have PR #11570 for this issue. If possible, please test the PR. Thank you.

**Comment by solpeth** [comment]
@yuwata this patch does not resolve the issue on my machine.

To provide some further information:

1. I applied the patch to the systemd sources using Gentoo's user patching facility
2. I rebuilt systemd
3. I ran the relevant `kernel-install` commands as above
4. The same unexpected behaviour resulted, so I updated systemd-boot and restarted my system for good measure
5. I again ran the relevant `kernel-install` commands, and I still encounter the same unexpected behaviour.

I'm a little out of my depth in this area, but if I can help test anything or provide more information, please let me know.

**Comment by ikelos** [comment]
@solpeth, could you please copy the exact command line you're running so that we can try to replicate the issue?

**Comment by solpeth** [comment]
@ikelos sure.

In `/usr/src/linux-4.20.5-gentoo/`, I run
`kernel-install add 4.20.5-gentoo arch/x86_64/boot/bzImage`

**Comment by ikelos** [comment]
Thanks! (I just spotted it in the initial report, sorry for the spam)  5:S

**Comment by ikelos** [comment]
@solpeth Could you please check your `/boot/<machine-id>/4.20.5-gentoo/` directory and see whether the `bzImage` file got copied into it or not?

**Comment by solpeth** [comment]
@ikelos yep, both `initrd` and `linux` are there in that directory as copied by `kernel-install`

**Comment by ikelos** [comment]
@solpeth Hmmm, very strange.  Using the command-line you entered, I'd almost expect it to fail because the correct syntax for kernel-install is `kernel-install KERNEL-VERSION *KERNEL-IMAGE* [INITRD-IMAGES ...]`, and the command line you entered didn't provide a kernel image.  

So firstly could you please try again including `vmlinux` in the parameters?  It may be that it makes some assumptions in places and so doesn't throw a nice error message...

**Comment by solpeth** [comment]
@ikelos `bzImage` is a valid parameter for the kernel image, is it not? I've used it this way for years based on documentation from back then. But if that is not correct, that's good to know.

Regardless, I used `/usr/src/linux-4.20.5-gentoo/vmlinux` in place of `/usr/src/linux-4.20.5-gentoo/arch/x86_64/boot/bzImage`, and it gave me the same result.

**Comment by ikelos** [comment]
Hehehe, they're not, I run Gentoo myself.  5;)  We figured out that I broke backwards compatibility because originally it just checked and automagically added everything for an initrd if the specific file `initrd` was present.  Then I came along and added support for both specifying it and allowing multiple ones, and that broke stuff (also `installkernel` assumed that future parameters would always be ignored).  We've got a plan over on #11570 to try to get this resolved, I need to knock up a PR but we should get it fixed soon (reviews pending)...

**Comment by solpeth** [comment]
@ikelos cool! Let me know if you want me to test any patches.

**Comment by Keruspe** [comment]
@solpeth just added another commit to #11570 which should fix your issue

**Comment by solpeth** [comment]
@Keruspe thanks, compiling with your patch, I'll let you know how it goes

**Comment by solpeth** [comment]
@Keruspe perfect. Works as expected.
