### ISSUE TITLE
What exit code should a service send if its state is fatal, and it doesn't want to be respawned?

### ISSUE THREAD

**Issue by dothebart** [systemd/systemd#11597]
So I saw systemd in top:
```
   522 root      20   0   32.4g 842900 179604 S   0.0   1.3   3:49.86 /lib/systemd/systemd-journald                                                          
```
which led me to https://github.com/systemd/systemd/issues/9141 - so yes, its not ram allocated but memory mappings. I still think that 32G mappings aren't whats supposed to be. 

However, my cause was a service exiting with error:
```
Jan 28 17:18:17 bruecklinux systemd[1]: arangodb3.service: Main process exited, code=exited, status=1/FAILURE
````
and systemd instantly trying to respawn it over and over again - hence my question, how is a service to indicate that it doesn't want to be respawned since it suffers from an error? I found [the exit code documentation](https://freedesktop.org/software/systemd/man/systemd.exec.html#id-1.20.8) - but it doesn't specify any behaviour that systemd will do - will it allways respawn?

**Comment by boucman** [comment]
First, this is a bug-reporting tool, not a support tool (no big deal, just saying so you are aware for next time)

in man:systemd.service look for RestartPreventExitStatus= which will tell systemd what exit code means "do not restart the service" you can set it to whatever value your service returns...

**Comment by boucman** [comment]
well... exit codes do not have well-defined meanings, so it makes no sense for systemd to force "exit-code X means Y"

once you've ruled out exit-codes as a way to determine when to restart, and since your unit states that the service must be restarted on failure, you just are left to decide what is and what isn't a failure.

systemd defaults to 0 is success everything else is failure, so yes... I believe that's the only default that makes sense...

**Comment by poettering** [comment]
in systemd we keep restarting services that have Restart= set. Moreover services might be restarted automatically if they are triggered by a socket and there's data queued in the socket and the service dies before dequeuing that data, so that it remains queued continiously.

The first kind of restart you can tweak with RestartPreventExitStatus= and the precise Restart= parameter.

Both types of repeated activation are subject to `StartLimitIntervalSec=`, `StartLimitBurst=` which put a limit in how many retries are attempted within a certain time window. If the limit is hit, then not only the service unit is failed for good but also all triggering socket units and such. 

Hence, yes, the journal is suppsoed to be restarted when it fails for some reason, and if this ends up being too fast then systemd should eventually step in, and shutdown the service and its socket again.

Anyway, this is all documented, and I think the current behaviour is pretty OK. Let's hence close this here.
