### ISSUE TITLE
"systemctl start xdm" hangs in emergency console

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#11615]
**systemd version the issue has been seen with**
240-5

**Used distribution**
Debian unstable

**Expected behaviour you didn't see**
"systemctl start xdm" works, or shows an error message and returns. It reacts to ctrl+c while doing transient work. It does so even in an emergency login (see #11614 for the case I experienced).

**Unexpected behaviour you saw**
"systemctl start xdm" basically freezes. I didn't react to ctrl+c. There are also not any other virtual consoles where you could log in and e.g. kill systemctl. After a while it returned, probably due to a timeout. There was no terminal output at all.

There was not actually a reason for xdm not to start, as most of the system was present (root filesystem mounted, drivers present and loaded, xdm binaries and libraries present).

(Actually, I would have preferred that it ignored the error that caused the emergency stop in the first place, and had continued booting, or offered a choice on the emergency prompt to do so.)

**Steps to reproduce the problem**
Boot into emergency login (e.g. via #11614), run the command.

**Comment by yuwata** [comment]
Please see the comment in #11616.

**Comment by wm4** [comment]
Should that really explain why it's hanging, not showing any error messages or warnings, and not interruptible?

It also feels like this uninterruptible state could happen with any "systemctl start" call.

**Comment by poettering** [comment]
> Should that really explain why it's hanging, not showing any error messages or warnings, and not interruptible?

well, these kind of deadlocks are hard to detect. The hang you see is because your emergency shell is blocking continuation of boot, and thus startup of dbus, logind, … and all the stuff that graphical UIs need to permit users to log in. i.e. the cyclic block goes like this: while the emergency shell is running boot is paused, so that you can debug things without things interfering with it. But that means no dependencies of your gaphical session can be processed, they all wait for the emergency shell to exit first, but that's what you are blocking by starting X in it.

If X doesn't react to C-c while it is waiting for depending services, then this can only be dealt with in the X codebase. X tends to take over kbd management in full, thus disabling the kernel's own handling of C-c, and thus C-c loses its magic features unless X itself is prepared to deal with this while waiting on some backends, such as logind/dbus.

Now you could file a bug against X, maybe they do something about it. However, I am not sure its worth doing that, if I was them. The thing is, semantically you are starting a graphical session from a place that pretty much means "hey, don't start anything yet, let me inspect the system first, before anything is started". so you basically have to contradicting directives here: "start something" and "start nothing". This is semantically not resolvable. Or in other words: if you want start-up to continue, then exit emergency mode, and continue the boot. There's no concept of "don't start-up now" and "please start-up now" that wouldn't semantically conflict.

Hope that makes some sense.
