### ISSUE TITLE
There's no busctl's equivalent to "gdbus emit" or "dbus-send --type=signal"

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#11622]
**Is your feature request related to a problem? Please describe.**
I want to emit D-Bus signals with busctl command line tool (for my bash scripts) but I've not able to find any documentation regarding this possibility, so I've inferred it isn't possible yet.

**Describe the solution you'd like**
Adding another verb like "busctl emit ..." to busctl tool, or similar 

Thanks!

**Comment by poettering** [comment]
So the reason I didn't add that is because I didn't see how that could be useful. Signals are after all how services report that something interesting happened, so that clients can subscribe to it. They thus originate in service with a name, so that subscribing to that name is possible to get these signals. but busctl is a client tool pretty much, it doesn't acquire names, it remains shortlived and anonymous if you so will, only carrying a unique, but no well-known name, for a brief instance. Hence it isn't really obvious how you'd subscribe to signals it sends, since you#d not know where they would come from...

I mean we can certainly add this, and @yuwata prepped a patch for it. But I wonder about the usecase. what kind of signal do you want to generate with busctl where it doesn't matter that the sender has no name?

**Comment by boucman** [comment]
I'd mainly see that as usefull for test/debug scenario

If I understand dbus correctly, the signal has a destination (which normal signas don't have) so they would be correctly routed by the dbus daemon

if the receiving code doesn't filter on sender (which would be the case for a daemon that is under test) we could easily script some automated testing with that...

**Comment by q2dg** [comment]
Well, my request was mainly for completeness to be on pair with similar tools. But if you consider it's not useful enough, no problem
