### ISSUE TITLE
Make environment expansion in ExecStart= and friends optional

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#11654]
As discussed offline before Devconf.CZ, we're interested in a way to use ExecStart= (and potentially similar options) over dbus without environment variable expansion. Maybe a new option called ExecStartRaw= that will just pass things without changes to execve(). Happy to work on a PR for this.

**Comment by boucman** [comment]
For those of us that were not at DevConf, could you detail a bit more why you need that ? what sort of calls would need unexpanded $VAR in a command line ? is it expanded by the process itself ?

**Comment by anitazha** [comment]
At Facebook we use systemd in our containers to execute commands through the dbus API. We want the invocations to behave more like passing arguments directly to execv(). And it pretty much does that, except for the environment variable expansion.

**Comment by johannbg** [comment]
Probably better to call this something like BusStart, BusExec or  DbusStart or DbusExecStart rather than ExecStartRaw which more likely than not will cause misunderstanding for what purpose this is.

**Comment by johannbg** [comment]
Bus$FOO is probably best for this so this does not end up sounding like being "dbus" specific if the bus is ever changed

**Comment by poettering** [comment]
As discussed, this makes sense to me to have, and quite frankly it should have been the default behaviour...

1. In unit files, add a new magic character similar to the existing `@`, `!`, `-`, `+` that turns off variable expansion. Maybe use `$` for it, that would be quite obvious I think.

2. On the wire (i.e. via dbus) things are a bit more complex, given that dbus propers cannot change type without this being considered api breake. dbus doesn't really know a nice way to extend existing props in a safe manner. We so far sidestepped this issue, and simply don't support some of the magic characters in ExecStart= and friends, when configured or requested via dbus. I figure we need to clear this up now. Hence I think we should add for each ExecStartXYZ= property another property ExecStartXYZEx= or so, which is similar to ExecStart, but instead of having the dbus type `(sasb)` it should probably have `(sasas)`, i.e. the binary to execute, the argv[] array to pass, plus an array of extra flags to configure, which map the special chars. This array would contain short identifiers that map directly to those special chars. For example `+` would map to `privileged` and `!` would map to `no-setuid` or so. And then of course the new `$` special character would map to `no-env`... If you follow what I am proposing?

**Comment by anitazha** [comment]
Yup makes sense to me!

**Comment by poettering** [comment]
(actually using `$ as the special character for disabling env var expansion is probably a bad idea, since it creates the ambiguity what `ExecStart=$foo` means... Could mean: resolve $foo and run it, or it could mean, run "foo", but turn off env var expansion...)

Mayb ":" could work, or something like that

**Comment by anitazha** [comment]
@poettering Any particularly reason for recommending `(sasas)` over `(sasu)` or `(sast)`? The special characters map to `ExecCommandFlags` which would map nicely to a numerical type with the existing bit masks.

**Comment by poettering** [comment]
it's an open question how to best encode flags parameters in dbus. There are two schools: as integers, so that the client side needs to know what each bit means. And as array of strings, which is a bit more self-explanatory if you see a dbus message trace for example, as you then use string identifiers in the traffic.

So far we adopted a scheme in the midlde of both: for bitflags defined by other APIs (for example bitmasks defined by libc, such as capability masks and so) we used integers on the wire, but for bitflags defined by us ourselves we'd use strings instead so far. (there are exceptions to this rule however)
