### ISSUE TITLE
RFE: add tmpfiles.d line type for backups

### ISSUE THREAD

**Issue by BryanQuigley** [systemd/systemd#11712]
**Is your feature request related to a problem? Please describe.**
Want to move more items away from cron, specifically passwd/dpkg backup jobs.
https://salsa.debian.org/dpkg-team/dpkg/blob/master/debian/dpkg.cron.daily
https://salsa.debian.org/debian/shadow/blob/master/debian/passwd.cron.daily

**Describe the solution you'd like**
I think I can use tmpfiles for both of these cases, but tmpfiles doesn't seem to indicate backing up files on a regular basis as part of it's reason for existing.  I don't want to suggest that passwd/dpkg start doing something unless I'm certain it's the right direction to go in.

It would be something like:
C  /var/backup/passwd.bak       /etc/passwd
And then clearing /var/backup/ before the next copy.

**Describe alternatives you've considered**
Just use timers.

**Comment by poettering** [comment]
hmm, interesting. So currently tmpfiles.d/ "ages" files (i.e. removes them if the mtime is too old), and that's why the tmpfiles timer exists. When that timer triggers only the aging logic is run, nothing else. In particular, "C" lines are not executed then...

That said I figure adding a concept like you are proposing makes sense, but it probably should get a new line type, explicitly for this purpose, which is also run whenever the timer is triggered.

Hence, maybe intrdouce a new line type "B" (for "backup") that is very similar to "C", but is applied during the timer event logic. Would be happy to review a patch for that.

**Comment by BryanQuigley** [comment]
Thanks for the quick answer!  Really appreciate it.

I've dug more into both use cases (passwd and dpkg) over the last few days and don't think a general solution makes sense anymore..  For completeness:
passwd backups would be perfect for the "B" for backup line, but in my testing I've determined the editing backups might be more useful.   (more here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922935)
dpkg - was more compex then I expected and wants to do a compare and only copy files if they have changed. that does not lend itself to a simple backup line.

As such I'm going to close this issue.  Thanks again
