### ISSUE TITLE
Delay /var/lib/machines mount until needed

### ISSUE THREAD

**Issue by esmil** [systemd/systemd#1175]
Mounting /var/lib/machines as part of local-fs.target doesn't work when it is on a network attached filesystem, so delay mounting until it is needed.
Eg. make system-nspawn@.services want it or make /var/lib/machines an automount.

**Comment by fsateler** [comment]
There is a related issue, that there is currently no ordering relationship between `var-lib-machines.mount`  and `systemd-nspawn@`. So, what about the following plan:

1. Add a `var-lib-machines.automount`, with same `ConditionPathExists` as currently present in the `.mount` unit.
2. Unhook `var-lib-machines.mount` from `local-fs.target`.
3. Hook up `var-lib-machines.automount` into `sysinit.target`.
4. Add `RequiresMountsFor=/var/lib/machines` to `systemd-nspawn@`.

The first three make sure the path is always mounted when required (ie, even if there is no machine hooked up at boot), the fourth one ensures the unmount is not attempted until all machines have stopped.

I can post a PR if this is a reasonable solution.

**Comment by poettering** [comment]
Hmm, I am wondering about the hook into sysinit.target... I mean, sure, if we don't know what the thing will be backed by neither local-fs.target nor remote-fs.target are really the right place. But hooking this into sysinit means that the thing will be established when we boot into single-user mode, and that sounds like quite a bit. I think hooking this into "machines.target" would be better, which is where nspawn containers are hooked into as well, hence looks like a natural place.

Otherwise looks great!

**Comment by keszybz** [comment]
@fsateler hm, what's up with this? You had a commit, but @poettering made some comments, and you never submitted a PR afaict…

**Comment by fsateler** [comment]
Yeah, sorry I got sidetracked. I was missing some testing and then I just forgot. Now that point 4 is already implemented, all that is missing is adding meson integration and testing my commit. Will try to wrap this up this week.
