### ISSUE TITLE
a strange behavior of sd-pam

### ISSUE THREAD

**Issue by chqfeiyang** [systemd/systemd#11753]
recently i find that my cpu is occupied by a process named 'sd-pam'.

In top, it's

 4472 user      20   0   54932  45392      0 S  2293  0.1 469:30.88 libserv                                                                                                                                 

it occupies 2300% of my cpu. After i killed it, it appears soon.
so what's wrong, and how to solve it?
Thanks!

**Comment by chqfeiyang** [comment]
![image](https://user-images.githubusercontent.com/26836044/52961464-f3a15d00-33d5-11e9-98f5-17d51b467fc1.png)

**Comment by poettering** [comment]
what service do those processes belong to? Try `ps -eo pid,comm,unit` to list processes along with their unit memberships to determine that.

Also, please provide the fields requested in the issue submission form, i.e. which distro and systemd version you are using. Otherwise we cannot help you. Please don't ignore the submission form, it exists for a reason.

**Comment by chqfeiyang** [comment]
Thanks for your reply!
I tried to kill that process again and i found it didn't appear any more, though I still don't know why...

**Comment by linrio** [comment]
> what service do those processes belong to? Try `ps -eo pid,comm,unit` to list processes along with their unit memberships to determine that.
> 
> Also, please provide the fields requested in the issue submission form, i.e. which distro and systemd version you are using. Otherwise we cannot help you. Please don't ignore the submission form, it exists for a reason.

Hi, after command `ps -eo pid,comm,unit` : 

```
...
41778 kworker/u113:0  -
41807 libserv         cron.service
41849 top             session-28759.scope
...
```
