### ISSUE TITLE
RFE: add sd_is_inet() or so for checking whether an fd is bound to a specific IP address and port

### ISSUE THREAD

**Issue by tsmetana** [systemd/systemd#1188]
Hello.

I have tried to implement socket activation for the tvheadend media streaming applictaion. The service listens on several sockets/interfaces and each of them needs to serve different content (the stream itself or administration web interface). When using socket activation, all I get from systemd is a bunch of file descritptors, so it's necessary to call getsockname on each of them to find out the correct one and the sd_is_socket_inet call doesn't allow me to check the interface (only port).

Would it make sense for the systemd API to provide some simpler way to obtain the right descriptor?
For the reference: the pull request for tvheadend illustrates better what I mean:
https://github.com/tvheadend/tvheadend/pull/703

**Comment by utezduyar** [comment]
Also, do we have an API to figure out which socket caused the activation?

**Comment by grooverdan** [comment]
the TODO contains:

<pre>
* Introduce $LISTEN_NAMES to complement $LISTEN_FDS, containing a
  colon separated list of identifiers for the fds passed.
</pre>

**Comment by lemenkov** [comment]
+1 from me. I really love to see this so I'm subscribing on that issue. Sorry for the noise.

**Comment by poettering** [comment]
So, I think we should push developers to a scheme where they iterate through the fds passed, match them up with their config and do something with the ones they cannot match up (either close them and log about it, or extend their config about it). Hence I am very sure we should not turn this around and add an API that instead allows developers to search for a specific fd, since that would allow them to ignore additional fds, which would then leak and the connecting clients would hang...

@tsmetana regarding the interface check, I figure we could add another call to sd-daemon, that allows to quickly check the incoming interface of a connection, using IP_PKTINFO on the connected socket. Besides that so, what else are you asking for?

@utezduyar well, there is no "one" socket that caused activaton, it might be be many, after all we coalesce activation requests, and queue them, and thus multiple sockets might have queued events. Also, I fail to see the usecase for querying that... Note though that you can easily check if a socket has queued traffic on it, by just doing a poll() for POLLIN with a zero timeout out. This will return immediately and just tell you whether a specific socket has something on it.

Anyway, would be good to know what precisely is being asked for here... @tsmetana, please elaborate on "a simpler way"...

**Comment by grooverdan** [comment]
@tsmetana seems to be asking for a tag to associate to a socket to mark which content it has even though the interface is an indirect indicator of this.

The case I'm working on for mariadb, (admittedly exceptionally heavy for socket activation) is:
- extra_port, gets special priority so a discoverable tag in systemd config rather than specifying the same port once in mariadb.socket and once in /etc/my.cnf
- galera ports have a different communication interface than the normal database connection ports

Keeping a config file and a x.socket in sync somehow, sounds a little redundant and fraught with potential errors. Thanks for listening.

**Comment by poettering** [comment]
@grooverdan there's a PR for being able to name sockets in #1247. I figure we should review that... Anything else being asked for? @tsmetana?

**Comment by grooverdan** [comment]
works for me. thanks.

**Comment by tsmetana** [comment]
Heya! Thanks for the answers... Yes, I wanted to get rid of the iteration over the file descriptors passed from systemd and actually ask systemd for a specific descriptor.

So, originally I thought a function that would look like this (sort of):

```
int sd_can_i_have_this_socket(int family, int port, const char *address);
```

...and I would either get the corresponding descriptor or -1 when systemd would not know of such a socket. The point was that there existed quite a many applications that needed to listen on more then one port/interface and all of them had to implement this file descriptor iteration. Therefore it made sense to move it to the API.

However yes, @poettering is right that the application has to iterate over the descriptors anyway... So being able to match a descriptor with a given interface and port (whereas only port matching is possible now) would be good enough: sd_is_socket_inet able to check also address would work for me. Just free me from the getsockname calls in the loop.

**Comment by poettering** [comment]
What do you mean by interface precisely? the actual interface index? Or just the IP address the socket is bound to? How would you suggest such a checking function would look like?

**Comment by davidstrauss** [comment]
An alternative to text naming is defining the order sockets should be
specified in systemd. On activation, systemd will always pass in the
complete set of sockets in the order configured.

So, for the MariaDB case, I would suggest the primary socket being first,
followed by the extra_port, and then optionally followed by the Galera
ones. Daemon startup can explain what it's using for each so admins can
sanity-check the configuration. I don't think configuring an extra_port is
a big burden for people wanting to use Galera.

Generally, I think it's better for daemons to have a single listener and
distinguish requests at the protocol level, but that can be a hard
transition for existing services. NFSv4 moved to that sort of model, though.

**Comment by grooverdan** [comment]
I really like explicit names. Relying on daemons to determine protocol could be problematic when you also are applying network access control on ports. Explicit order without falls down when there are a variable number of socket types. I'm not sure an explicit FileDescriptorName applying to all Listen directives is an intuitive way to configure services with listening service with different purposes (https://github.com/poettering/systemd/blob/df9d6993b677c05c7f502acafc5c8efa642792fe/man/systemd.socket.xml#L752).

My preference would be something like:

<pre>
ListenStream=127.0.0.1:3306
ListenStream=127.0.0.1:3308,extraport
ListenStream=127.0.0.1:4444,galerasst
</pre>

probably has few edge case compatibility issues however general principle applies.

**Comment by poettering** [comment]
The fd naming stuff is implmented already, as PR #1247 got merged.

@davidstrauss systemd already guarantees that the order is preserved if you list multiple sockets in the same .socket file. However. if you have multiple .socket units that activate the same service the order between the fds of each individual unit file is not defined.

@grooverdan note that you can have multiple .socket units for the same service. Many of the settings in .socket units already apply globally to all sockets of that specific unit, and the FileDescriptorName= thing is just one more, that applies to all of them. The idea is basically that you use the same .socket unit only of sockets of the same kind, i.e. when you have a http server that shall listen on five different IP addresses with three different ports, but always speak http on it, so that furthr distinction between those fds doesn't matter, and they should all carry the same name. Now, if that same http server also would support a control socket, speaking a completely different protocol, then it should do that in a separate .socket unit, where it then can apply different settings, including a different name. What matters is that both those .socket units carry Service=httpd.service, so that both activate the same http server daemon.

**Comment by poettering** [comment]
Anyway, my question from yesterday was primarily intended for @tsmetana asking for details on the iface he is asking for.

**Comment by tsmetana** [comment]
Yes, by interface I meant an IP address.

**Comment by poettering** [comment]
@tsmetana but how would you suggest that a new API in sd-daemon would look like? I mean, if you encode the address as sockaddr (so that we can cover sockaddr_in and sockaddr_in6 the same), then such an API would be hardly easier to use than doing getsockname(), or?

```
int is_socket_sockaddr(int fd, int type, struct sockaddr* sa);
```

Would such a call make you happy? (where type is either 0 or SOCK_DGRAM or SOCK_STREAM)

**Comment by tsmetana** [comment]
I wanted to get rid of getsockname in the loop mostly to avoid the fiddling with sockaddr structs preparations, guessing the IP version, etc. I assume most of the services look similar: get an address and port in a string form from the configuration or arguments and then turning them to struct sockaddr just to call getsockname to find out which descriptor to use. And repeat for all the other addresses and ports... Looked like a good thing to be moved to the API since it's a common pattern.

And I'm apparently horribly  failing at explaining myself here...
