### ISSUE TITLE
systemctl hibernate does not hibernate on swapfile on Btrfs after kernel 5.0

### ISSUE THREAD

**Issue by helloworld1** [systemd/systemd#11939]
**systemd version the issue has been seen with**
241.7

**Used distribution**
Archlinux

**Expected behaviour you didn't see**
`systemctl hibernate` should hibernate on swap file on Btrfs after kernel 5.0

**Unexpected behaviour you saw**
Btrfs supports swapfile after kernel 5.0. `echo disk > /sys/power/state`  works fine to hibernate but `systemctl hibernate` failed.
Since Btrfs is using virtual physical offset of the file. The current logic in sleep.c does not get the correct physical offset of the file. The resume_offset kernel parameter is also ignored and overriden by systemd so it is unable to get the correct offset.

https://github.com/systemd/systemd/blob/c5e6f734c6477d1347a42074b208b4ef71c3095a/src/sleep/sleep.c#L80

**Steps to reproduce the problem**
1. Create swapfile on btrfs according to man 5 btrfs
2. Activate swap file in fstab
3. Calculate the physical offset of swapfile and add kernel parameter
resume=/dev/nvme1n1p2 resume_offset=52761856
4. echo disk > /sys/power/state works fine to hibernate 
5. systemctl hibernate failed.
[   26.828436] PM: Cannot find swap device, try swapon -a
[   26.828441] PM: Cannot get swap writer

**Comment by helloworld1** [comment]
The related discussion is in https://bugzilla.kernel.org/show_bug.cgi?id=202803.

**Comment by poettering** [comment]
Hmm, so why does btrfs not follow the same APIs as other file systems on this? Isn#t this a btrfs interface issue?

**Comment by helloworld1** [comment]
I think this is by design for Btrfs since it can handle multiple storage devices. virtual physical offsets are provided to have a consistent view of file addressing.  Seems like hibernation on swapfile requires real physical offset to work. 
Feel free to comment on the https://bugzilla.kernel.org/show_bug.cgi?id=202803 with Btrfs developer so we can have a consensus on how to address the issue.
Maybe systemd should also read kernel parameter for the manually set resume_offset instead of calculating.

**Comment by osandov** [comment]
Yes, as @helloworld1 said, Btrfs gives you a virtual device number for stat and a virtual offset for fiemap by design. Even in the single device case, we make use of the virtual offsets to simplify block allocation.

In my opinion, the issue is that the hibernate interface is stupid. We should have an interface (system call? ioctl?) that just takes an fd and sets that swap device or file as the resume device. @poettering, would systemd make use of that if we were to implement it in the kernel? Or do you have any better ideas?

**Comment by poettering** [comment]
> In my opinion, the issue is that the hibernate interface is stupid. We should have an interface (system call? ioctl?) that just takes an fd and sets that swap device or file as the resume device. @poettering, would systemd make use of that if we were to implement it in the kernel? Or do you have any better ideas?

Yes, please add that. Would love to simply remove the previous code then and just use the new API. The ioctl mucking is really terrible for this purpose.

**Comment by Snoop05** [comment]
May i ask how would people (with rights to merge pull requests) like to have this one solved?
a) Wait for btrfs to change till this magically starts working?
b) Implement btrfs swapfile support on systemd side?
c) Rewrite this component from scratch?
d) Honor _resume_ and _resume_offset_ parameters set in _cmdline_ instead of wizardry?

Current status: neither _resume_, nor _resume_offset_ gets detected properly, yet systemd will override both

**Comment by poettering** [comment]
anything specified on the kernel cmdline should take precedence over any automatic discovery. Hence, yes, I'd be happy to merge a patch that makes sure we always use the kernel parameters if they are specified.

That said, given that btrfs hibernation is a pretty new feature I think we'd also be fine to wait until the kernel learns a new hibernation API that allows us to just pass an fd in, and only support it when that's done.

The sleep code could generally use some love though. For example the s2h code uses RTC ioctls, where it probably should just use `CLOCK_BOOTTIME_ALARM`. Or we currently parse sleep.conf multiple times, which sucks too.

**Comment by zachsmith** [comment]
I was able to reproduce this bug on a virtual machine running Arch using the steps @helloworld1 provided in the initial report. I did have to use [the utility](https://github.com/osandov/osandov-linux/blob/master/scripts/btrfs_map_physical.c) @osandov provided in the issue reported in [bugzilla](https://bugzilla.kernel.org/show_bug.cgi?id=202803) to calculate the offset for `btrfs` correctly (in case anybody else tries it).

I submitted https://github.com/systemd/systemd/pull/12760 which solves the general issue of ignoring the `resume_offset` by implementing `d)` in @Snoop05's [list](https://github.com/systemd/systemd/issues/11939#issuecomment-476439422) above.

The route I took is fairly simple but I think it serves the purpose. Rather than inspecting the kernel cmdline for `resume=` and `resume_offset=` (which was how I originally started), it simply checks for any value already present in `/sys/power/resume`. If it finds a value `> 0` will assume that was set previously and return without any offset calculation. I've confirmed that this works in the VM I setup and confirmed that the calculation continues to take place in absence of a `resume_offset` being set.

If anybody using `brtfs` with a `swapfile` is game, please give the PR a spin.
