### ISSUE TITLE
Set uaccess tag for U2F/FIDO2 keys

### ISSUE THREAD

**Issue by nickray** [systemd/systemd#11996]
**Is your feature request related to a problem? Please describe.**
To use FIDO2 hardware authenticators, users need access to to the corresponding HIDRAW device. Some methods in use are
- user adds rule manually
- install package [libu2f-host](https://github.com/Yubico/libu2f-host) which includes a file `70-u2f.rules`. This needs manual updating upstream. Debian does this I believe.
- install packaged [u2f-hidraw-policy](https://github.com/amluto/u2f-hidraw-policy) which checks if the HID usage page is 0xf1d0

The first is tedious for the user, the second tedious for the vendor.

**Describe the solution you'd like**
I  would like udev to subsume the functionality of `u2f-hidraw-policy` and tag FIDO devices as `uaccess`. This seems like the correct solution, given https://www.usb.org/sites/default/files/hutrr48.pdf

**Describe alternatives you've considered**
Listed above.

**Comment by poettering** [comment]
It would probably be fine to fold the u2f-hidraw-policy callout stuff into usb_id, given that it is relatively short and simple. But this really needs a contributed patch

**Comment by FabianHenneke** [comment]
Since I need a generic udev rule such as the one provided by [u2f-hidraw-policy](https://github.com/amluto/u2f-hidraw-policy) for a personal project, I would be willing to supply the patch.

Even though so far all available security tokens have used USB transport, all implementations I know of accept any kind of HID device with the right usage and usage page. Would it also be acceptable to go with the original proposal and add a hidraw_id module instead of integrating into usb_id?

The security concerns could potentially be alleviated by adding a libfuzz target for the HID descriptor parser. I could make the required modifications.

**Comment by FabianHenneke** [comment]
I just created a pull request #13357 that combines a systemd-ized version of `u2f-hidraw-policy` with a test suite and a fuzzer for the descriptor parser.  Please let me know what you think.
