### ISSUE TITLE
Support time-limited sessions in logind

### ISSUE THREAD

**Issue by pwithnall** [systemd/systemd#12035]
We’re [looking at implementing parental controls and digital wellbeing](https://wiki.gnome.org/Hackfests/ParentalAndMetered2019) in GNOME, and are looking at a feature which only allows a user account (typically for a child) to only be used during certain hours of the day. That means only allowing logins during that period, and locking the session or logging it out at the end of that period.

I’m wondering about the best place to enforce this. Either we:
 1. Implement it in systemd-logind and `pam_time.so`, ending the session (or not allowing it to start) once the time is up.
 2. Implement it in a separate daemon which monitors the time and calls `Lock()` or `Terminate()` on the session D-Bus interface when the time is up. This would also use `pam_time.so` to prevent logins outside the allowed period.

If we go with option #1, that would be quite simple, and it means other desktops could reuse the implementation. If we go with option #2, there is currently no way to pass a reason for the session being locked/terminated to the method. gdm/gnome-shell would need some kind of reason/hint to be able to tell the user why their session was being locked/terminated.

Ideally, we wouldn’t have to use `pam_time.so` either, as that means writing human-readable and -editable configuration to `/etc/security/time.conf` and having to parse them back again, which would be a pain.

So this is not a concrete proposal as such, but more of a question about what the upstream logind feelings are about this kind of feature and how it should be implemented.

**Comment by cassidyjames** [comment]
This would also be useful to us in elementary OS for our Parental Controls and Digital Wellbeing features.

**Comment by poettering** [comment]
Hmm, I'd probably opt for your first proposal, or something similar to that.

A few ideas:

1. On the systemd side (i.e. in PID 1) we currently have a RuntimeMaxSec= property for service units, which specifies the maximum runtime for a service unit, after which it is terminated (in a friendly way first, but hard if that doesn't work). I figure it would make a lot of sense to add similar functionality to scope units, too (doing that would be pretty easy I guess given the same code for service units already exists, i.e. it's an educated copy/paste operation in a way). Since logind sessions are ultimately just scope units, if we can set a time limit on those logind doesn't really have to know much about time limits at all, but we could still put an easy and effective time limit on the sessions.

2. pam_systemd currently can pass on memory limits and such that are configured via a pam_set_data() variable of the pam session object to the scope allocated for the login session. It would be very easy to extend that to also pass along a maximum runtime the same way. This would allow a PAM module earlier in the stack to set this variable via pam_set_data() and then pam_systemd would simply read it out and pass it on further.

3. You could then either patch pam_time to set this pam_set_data() variable for pam_systemd to pick it up or just write your own PAM module (I have the suspicion you want to write your own for many reasons). It could also set this timeout as env var for the PAM session so that whatever is called as the session process then knows about the time limit and maybe can show a warning a bit before the time runs out.

With such a solution from my systemd PoV would be really simple, as it I wouldn't have to care about how you decide when to allow logins or not, and all I do is enforce your time limit on sessions. And all that fairly generic and in a way probably useful for plenty other usecases too.

Would love to review/merge a PR for items 1 + 2 in the list above.  ;-)
