### ISSUE TITLE
cannot change options for tracefs

### ISSUE THREAD

**Issue by azat** [systemd/systemd#12038]
**systemd version the issue has been seen with**
systemd 241 (241.7-2-arch)

**Used distribution**
arch linux

**Expected behaviour you didn't see**

```shell
# mount -t tracefs
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime,mode=755)
tracefs on /sys/kernel/tracing type tracefs (rw,relatime,mode=755)
```

**Unexpected behaviour you saw**
 
No `mode=755` for `/sys/kernel/tracing`

```shell
# mount -t tracefs
tracefs on /sys/kernel/tracing type tracefs (rw,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime)
```

**Steps to reproduce the problem**

- `echo "tracefs         /sys/kernel/tracing             tracefs         defaults,mode=755       0       0" >> /etc/fstab`
- reboot the machine

P.S. AFAIK you cannot use `.mount` for `APIVFS` hence the only option is to use `/etc/fstab` according to:
- #8394
- https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems

**Comment by poettering** [comment]
/sys/kernel/tracing is not a file system systemd mounts, and it should work just fine to mount it via /etc/fstab. While technically tracefs should be considered an API VFS (given that it exposes a kernel API, not really data files the user could create and it would store away), from systemd it's not one of them, since systemd doesn't actually mount it or care about it at all.

Now, my educated guess is this: according to this: https://www.kernel.org/doc/Documentation/trace/ftrace.txt the kernel will mount tracefs to /sys/kernel/debug/tracing on its own if /sys/kernel/debug is mounted (what a stupid behaviour, christ!). It picks some mount options for that it likes. This means if you then mount it to /sys/kernel/tracing you just mount the superblock a second time, similar to a bind mount. In that case the mount options you specify are ignored by the kernel (yay, linux!), hence they have no effect.

Quite frankly the kernel shouldn#t be so stupid on this, but there's little we can do about that, it's the kernel's fault really, we are not involved in mounting this or picking the mount options.

Please bring this up with the kernel folks. They shouldn't establish mounts like that on their own (at least not by default, this definitely should be something to turn off in the kernel build settings) since it takes away the ability to set the mount options from userspace, since userspace is not involved in mounting this.

Now, you can probably tape over this by writing an early boot service that explicitly remounts the superblock of tracefs, but it's kinda awful that that's necessary.

Anyway, let's close this here, as this is nothing we can or should fix here. Please talk to the kernel people instead, so that they stop mounting file systems behind userspace's backs. If they want to maintain /sys/kernel/debug/tracing as a compat concept they should maybe synthesize it as a symlink to "../tracing", so that userspace can then decide to mount tracefs there, but it that should really be a userspace decision.

**Comment by azat** [comment]
>kernel will mount tracefs to /sys/kernel/debug/tracing on its own if /sys/kernel/debug is mounted (what a stupid behaviour, christ!). It picks some mount options for that it likes. This means if you then mount it to /sys/kernel/tracing you just mount the superblock a second time, similar to a bind mount. In that case the mount options you specify are ignored by the kernel (yay, linux!), hence they have no effect.

Hm, I was aware of this, but didn't know that kernel automount (which is `/sys/kernel/debug/tracing` is) will change mount options, but this is exactly what happens:

```
# mount -t tracefs
tracefs on /sys/kernel/tracing type tracefs (rw,relatime,mode=755)
# ls /sys/kernel/debug/tracing > /dev/null
# mount -t tracefs
tracefs on /sys/kernel/tracing type tracefs (rw,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,relatime)
```

**Comment by farnoy** [comment]
Looks like this will get fixed _soon_ https://lore.kernel.org/lkml/20220826174353.2.Iab6e5ea57963d6deca5311b27fb7226790d44406@changeid/
