### ISSUE TITLE
document in incompatibilities list that sysv init scripts without PID file header will be considered running forever even if their main daemon is gone.

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#1211]
Current behavior of sysv-generator and systemd is fine for "oneshot" initscripts, but there are issues with daemons. When the deamon is killed, the service remains in active (exited) state which is still represented as running.

```
[root@notas ~]# systemctl stop rsyslog.service 
[root@notas ~]# systemctl start rsyslog
[root@notas ~]# pkill -9 rsyslog
[root@notas ~]# systemctl is-active rsyslog; echo $? 
active
0
[root@notas ~]# systemctl show -p ActiveState -p SubState rsyslog 
ActiveState=active
SubState=exited
[root@notas ~]# systemctl cat rsyslog
# /run/systemd/generator.late/rsyslog.service
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/rc.d/init.d/rsyslog
Description=LSB: Enhanced system logging and kernel message trapping daemons

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/etc/rc.d/init.d/rsyslog start
ExecStop=/etc/rc.d/init.d/rsyslog stop
ExecReload=/etc/rc.d/init.d/rsyslog reload
```

**Comment by michich** [comment]
The old SysV parser in service.c had a heuristic where the RemainAfterExit property was set to false if the initscript specified a PID file in its chkconfig header:
  s->remain_after_exit = !s->pid_file;
(where s->pid_file was initialized from the "pidfile:" chkconfig header if present).
The idea was that if the service had a PID file, it was likely a real daemon and not a oneshot thing. 

There's no such heuristic in sysv-generator.c. It was likely dropped intentionally, but I don't remember.

**Comment by lnykryn** [comment]
That logic seems to still be there, so this is only problem for initscripts without that in LSB header.
But if am I not mistaken pidfile in header is not mentioned in LSB at all. https://refspecs.linuxbase.org/LSB_2.1.0/LSB-generic/LSB-generic/initscrcomconv.html

**Comment by michich** [comment]
> That logic seems to still be there

You're right. I missed that at first.

> But if am I not mistaken pidfile in header is not mentioned in LSB at all.

chkconfig headers in SysV scripts were mostly RH-specific.

In general it is impossible to say whether a SysV service is active or not without asking the script itself by calling its "status" operation. Of course systemd never does that, because it tracks the activeness state of all services at all times and asking for the state on-demand does not fit into this model.

**Comment by lnykryn** [comment]
> chkconfig headers in SysV scripts were mostly RH-specific.

It was not in chkconfig header either:
https://fedoraproject.org/wiki/Packaging:SysVInitScript#Chkconfig_Header

Most of the initscripts just had PIDFILE variable somewhere in the initscript.

**Comment by michich** [comment]
I don't know if there ever was a specification for the pidfile header. Nevertheless, many init scripts in RHEL6 have it.

Where does this rsyslog init script come from?

**Comment by lnykryn** [comment]
Its basically the same as the one in rhel6.

**Comment by mbiebl** [comment]
We had the same/a similar bug report in Debian.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=768178#49

@keszybz suggested there to use RemainAfterExit=false by default for SysV init scripts to be more backwards compatible behaviour wise.

Does anyone know, why we would _not_ want  RemainAfterExit=false ?

**Comment by poettering** [comment]
@mbiebl yes, because it breaks init scripts like the alsa save/restore scripts, that want to run at start and add boot, and if you set RemainAfterExit=false would only start at boot, but never stay around to run something at shutdown anymore.

I doubt we can do anything about the init script here. Maybe document it in the sysv incompatibilities list, but that's about it. We cannot guess whether a service shall be of the kind that claims its stopped when we still think it is up, or not..

**Comment by poettering** [comment]
This has been documented actually in the incompatibilities list already. Closing.
