### ISSUE TITLE
Allow units with PrivateTmp=yes to start earlier

### ISSUE THREAD

**Issue by sruggier** [systemd/systemd#12220]
Currently, use of the `PrivateTmp` feature in a unit requires that unit to be ordered after `systemd-tmpfiles-setup.service`, which I assume is specifically so any actions it performs on `/tmp` and `/var/tmp` happen before such units start. However, systemd-tmpfiles-setup is ordered after `local-fs.target`, which forces units that use `PrivateTmp` to execute much later than they otherwise would.

This can be a problem in virtualized systems, where entropy tends to be in short supply. In some cases, `haveged` is going to be the only good source of entropy during the first boot, but its unit file uses `PrivateTmp`, which forces it to run after `local-fs.target` finishes. Delaying initialization of the urandom source until after `local-fs.target` seems problematic to me in general (what if the root filesystem is on an encrypted volume?), but more specifically, I'm working with a system that tries to set up one or more local mounts using configuration information fetched via SSL. The setup process is ordered before `local-fs.target`. so that the mounts are available along with all other local mounts. This transitively forces it to run before `haveged.service`, which sometimes results in `EAGAIN` error codes from getrandom.

I'm wondering if we can improve this situation by splitting `systemd-tmpfiles-setup.service` further, along the lines of the `systemd-tmpfiles-setup-dev.service` unit, but instead splitting off a `systemd-tmpfiles-setup-tmp.service` unit with `--prefix=/tmp --prefix=/var/tmp`. Then, units that use `PrivateTmp` can depend on `systemd-tmpfiles-setup-tmp.service` instead of waiting for `local-fs.target` to finish in its entirely. Am I missing anything, or is this a reasonable solution to the problem?

**Comment by poettering** [comment]
Some folks have /tmp and or /var/tmp on the root fs (which comes up read-only likely), and others as external mounts. Hence it's not just s-tf-s.s we need to wait for, but local-fs.target and its deps too, including those which mount the rootfs rw if needed.

The general rule is: /tmp and /var/tmp are late boot facilities. If you need a temporary directory earlier you need to use something else really, you cannot use either of that.

My question is: why does haveged.service need temporary files anyway? If it really needs them and they need to be large, then using /var/tmp would indeed be the right choice, and then it has to be started later at boot. But if it doesn't need that, why bother with PrivateTmp= at all? And if it needs something small, why not use memfds or so instead? They are backed by the same kind of swappable memory that tmpfs (i.e. /tmp) is.

Also note that systemd itself also reads from the random pool, for example it uses it to generate 128bit "invocation" ids for each service invocation, and thus running a tool such as haveged after systemd is long running is not going to do much good anyway (after all, specifically in order to start haveged we assign an invocation id, and thus the service that is supposed to fill up the pool already needs the pool filled, hence what's the point?

(despite that I wonder what the benefit of haveged is in general: what could it do good that the kernel's own random pool filling algorithms couldn't do better?)

Hence, I have doubts about the usecase here: the PrivateTmp= option should probably not be used anyway for the service, the service would run too late regardless what PrivateTmp= does to solve the issue

**Comment by sruggier** [comment]
Thanks for your quick response, and I think that's a good question, I don't yet know exactly why haveged relies on `/tmp`, and it's worth figuring out, because that angle will get it starting earlier than improvements to systemd-tmpfiles-setup would.

Even if improvements aren't necessary here, it still seems possible to make /tmp available before `local-fs.target`. When /tmp is part of the rootfs, `After=systemd-remount-fs.service` would ensure it's writable, right? For cases where `/tmp` and `/var/tmp` are separate mounts, it looks like `RequiresMountsFor=/tmp /var/tmp` would do it. The two of those together would cover it, are safe to combine, and are both already before `local-fs.target`, so there's no chance of accidentally introducing a circular dependency by moving from `local-fs.target` to those two. Am I missing anything there?

**Comment by DemiMarie** [comment]
@sruggier Would it be possible to use the virtio RNG instead of `haveged`?

**Comment by sruggier** [comment]
@DemiMarie The initial motivation for this issue came from an EC2 instance, where it doesn't look like any paravirtualized RNG is available, so I guess not.

On the other hand, this issue applies to more than `haveged`. I think it makes general sense to factor out a `systemd-tmpfiles-setup-tmp.service` target that finishes earlier, given commit d71f050, so that the implicit dependency for `PrivateTmp`-using units can be more specific. This would improve boot concurrency, and allow use of `PrivateTmp` earlier in the boot process. I'm currently waiting for someone more knowledgeable than I am to tell me that I'm missing something, otherwise it seems like an incremental improvement to me.

**Comment by poettering** [comment]
I guess we can close this, now that PrivateTmp=disconnected exists, see 0e551b04efb911d38b586cca1a6a462c87a2cb1b
