### ISSUE TITLE
Black screen instead of password prompt for /home dir

### ISSUE THREAD

**Issue by Ilya87** [systemd/systemd#12264]
**systemd version the issue has been seen with**
> systemd 241

**Used distribution**
 > AntergOS x86_64

**Expected behaviour you didn't see**
 > Prompt on boot, where I can type password for /home dir

**Unexpected behaviour you saw**
 > Black (NOT turned off) screen

**Steps to reproduce the problem**
/etc/crypttab:
home         /dev/disk/by-partuuid/8276b89d-05             none tcrypt-veracrypt

/etc/mkinitcpio.conf
HOOKS="base udev autodetect modconf block encrypt keyboard keymap resume filesystems fsck"

Password can be entered, the screen at this time is black.

**Comment by poettering** [comment]
Please talk to your downstream distro first about this, and let them escalate this here if there's an actual bug here according to the downstream maintainers. There's little indication that this is a systemd issue and an exotic distro is used we know nothing about as upstreams, hence this is not really actionable to use. Thank you for understanding.
