### ISSUE TITLE
gperf --ignore-case

### ISSUE THREAD

**Issue by b1tninja** [systemd/systemd#12277]
Are options intended to be case sensitive across the board? There is currently a mix of build files using --ignore-case and others that are not. For instance 8ff213fd65e2c0614d183e594bb779b5b27f4121 removes it... 

A user on irc noticed that .link files are case sensitive... Is gperfs_generator the proper thing to use?

./src/network/meson.build
./src/timesync/meson.build
./src/journal/meson.build
./src/login/meson.build
./src/nspawn/meson.build
./src/shared/meson.build
./src/basic/meson.build
./src/resolve/meson.build
./src/core/meson.build
./src/udev/meson.build

Are other potential instances

**Comment by keszybz** [comment]
dns_type – it uses `--ignore-case` and it should
ip-protocol-from-name — the same
af, arphrd, cap, errno — likewise
load-fragment.gperf — it does not, and it shouldn't
journald-gperf.gperf — it does not, and it shouldn't
networkd-gperf.gperf networkd-network-gperf.gperf netdev/netdev-gperf.gperf — they do not, and shouldn't

Looks fine to me.

The rule is that our own configuration directives should be case sensitive ([Section], VariableName=), but stuff like errno names, protocol names, that are originally defined as uppercase case, but are more conveniently written lowercase, should be case insensitive. If you find a case where the case-sensitiveness is wrong, please report a specific case.

**Comment by b1tninja** [comment]
Thanks for clarification / verification. Wasn't sure what desired behavior was, in the alluded to IRC conversation user had MacAddress instead of MACAddress and it was not immediately obvious that was incorrect. Do you know the reasoning for case sensitivity, perhaps third party syntax checking, or something of the sort? Pragmatics?

**Comment by keszybz** [comment]
Mostly everything is case sensitive by design. In particular, option and section names are case sensitive. Option values are also case sensitive when defined by us, because then we can define them lowercase. The only stuff is things "defined" externally, that is traditionally case-insensitive like errno names. Please don't open a PR to make our own stuff case-insensitive, it'll be rejected. The only stuff that could be made case insensitive is the values of some options, but this is something to be decided on a case-by-base basis.
