### ISSUE TITLE
Provide way what container interface requirements are violated

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#1233]
Systemd defines a [container interface](http://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/).

It’d be great to have some command, like `lxc-checkconfig`, that can be run in a container, which lists the unmet requirements.

**Comment by poettering** [comment]
I am not convinced that this is really that useful, I mean, this kind of stuff should just work, and container managers should just set this up right anyway... It's mostly a contract between container managers and systemd, and hence between developers. I am pretty sure between developers docs like we have them are a better choice.

Dumping this problem on users is simply wrong, it should not be the responsibility of the users to configure the container manager manually (and first detect what's necessary to do so) so that it can run a modern distro in it. The container manager should default it.

Please ask the LXC people to just default to settings that we documented. Pretty much _all_ of today's distros will require this setup anyway.

**Comment by paulmenzel** [comment]
I think that tool would tremendously help container managers to verify that. It’s a “simple” test. The same for systemd/nspawn(?) if it fulfills the “container specification”.
