### ISSUE TITLE
systemctl reboot -f floods serial console

### ISSUE THREAD

**Issue by jkloetzke** [systemd/systemd#12337]
Recently MR #12153 (specifically 827156b33098cebcfb78e8afd17970c446394665) introduced the behaviour that the kernel console log level is raised to `info` in `systemd-shutdown` *before* the remaining processes are killed. This dramatically slows down `systemctl reboot/shutdown -f` in our embedded systems where systemd and all services log to kmsg. The kernel console is a 115200 baud serial tty that saturates at 10kiB per second. Now the shutdown takes 10..30s instead of being almost instantaneous.

I think there are several options how this can be resolved:

* only bump the log level if something needs to be printed
* print the list of stuck processes on some elevated log level
* make it an optional feature somehow

@benjarobin What do you think?

**systemd version the issue has been seen with**
v242-rc2-15-g827156b330

**Used distribution**
 Self-build embedded system

**Expected behaviour you didn't see**
`systemctl reboot -f` is quick and serial console is quiet.

**Unexpected behaviour you saw**
Console log level changes and logs of all services that go to kmsg are printed. Systemctl reboot takes very long because serial line is saturated.

**Steps to reproduce the problem**
`systemctl reboot -f`

**Comment by benjarobin** [comment]
Honestly, I was not really agree to change the current printk logging level in order to see on the console all the "info" messages.

The list of stuck processes are currently printed at a more elevated log level than "info": Using "notice" level.

My proposal is to:
 - Maybe print the list of stuck processes at "warning" level
 - And add a build option to configure the log level that needs to be set/bumped at the beginning of systemd-shutdown. 

@poettering What do you thing about my proposal ? I will be happy to implement it.

**Comment by benjarobin** [comment]
@jkloetzke One think that I do not understand, is that you should only see about 50 lines mostly about unmounting stuff since the printk log level is bumped only when all service are stopped.

Which give about 100 * 50 bytes to be printed, which is (at 115200) about 0.43 second => That does not match your bug description.

**Comment by jkloetzke** [comment]
> @jkloetzke One think that I do not understand, is that you should only see about 50 lines mostly about unmounting stuff since the printk log level is bumped only when all service are stopped.
> 
> Which give about 100 * 50 bytes to be printed, which is (at 115200) about 0.43 second => That does not match your bug description.

That's the case for the regular shutdown and there it's ok. The problem is that `systemctl reboot -f` does not terminate any services but directly hands over to `systemd-shutdown` with all processes still alive. Now our system is configured in a way that everything logs via kmsg (`LogTarget=kmsg`, `DefaultStandardOutput=kmsg`) . There are some notoriously chatty services among them that instantly saturate the serial line once the log level is bumped.

> My proposal is to:
>
> * Maybe print the list of stuck processes at "warning" level
>  * And add a build option to configure the log level that needs to be set/bumped at the beginning of systemd-shutdown.

I would be more inclined to the latter option. Having a knob for that could prove helpful to debug nasty problems during the final shutdown stage. But I'm fine with either option (or maybe both).

**Comment by benjarobin** [comment]
@poettering What do you think we can do ? Do you think that my proposal is acceptable ?

**Comment by poettering** [comment]
@benjarobin yupp i think it's acceptable, but i'd like to avoid making this configurable for now. 

I prepped #13037 now, which does this, and does some other minor refactoring. @benjarobin @jkloetzke would be great if you could have a closer look and maybe test this if this solves everything.
