### ISSUE TITLE
SYSTEMD_COLORS=1 should not imply urlification

### ISSUE THREAD

**Issue by eMPee584** [systemd/systemd#12356]
**systemd version the issue has been seen with**
> 241-3

**Used distribution**
 > debian unstable

**Expected behaviour you didn't see**
 > SYSTEMD_COLORS should not imply SYSTEMD_URLIFY

**Unexpected behaviour you saw**
 > SYSTEMD_COLORS does imply SYSTEMD_URLIFY

**Steps to reproduce the problem**
1. `watch -c SYSTEMD_COLORS=1 systemctl status {foo}.service`
2. see broken escape sequences and urlified paths in plain sight that go away with `SYSTEMD_URLIFY=0`

**Comment by poettering** [comment]
Hmm, what? If you don't want the URL sequences, then turn them off, no?

Generally, SYSTEMD_COLORS=0/1 is our main control to enable/disable generation of ANSI sequences. Thus if you explicitly enable it, then this means both colors and hyperlinks are enabled, if you explicitly disable it, then both colors/hyperlinks are disabled. SYSTEMD_URLIFY is then the control to override the latter, since in some cases you might want coloring but not hyperlinks or vice versa.

We generally default to a "turn on as much as we can" policy, since we believe these concepts are useful and helpful to the user. I don't think we should revisit that policy at this moment, since so far this has shown to work out. Yes, in your case you found an app where you'd like to enable color support but disable hyperlink support, but it appears to me that this shouldn't affect our policy on this, but would best be fixed in "watch" so that it can deal with the hyperlink sequences as well. That way the problem would be solved for every call you invoke that way, not just systemd's tools, and things would be fully automatic.

I hope the above makes some sense. Closing hence.

**Comment by eMPee584** [comment]
> Generally, SYSTEMD_COLORS=0/1 is our main control to enable/disable generation of ANSI sequences.

So how about calling it SYSTEMD_ANSI?

> Thus if you explicitly enable it, then this means both colors and hyperlinks are enabled, if you explicitly disable it, then both colors/hyperlinks are disabled. SYSTEMD_URLIFY is then the control to override the latter, since in some cases you might want coloring but not hyperlinks or vice versa.

Yes so SYSTEMD_COLORS is semantically misleading, right? At least it would need a "Also enables SYSTEMD_URLIFY" in the man page.

> *       $SYSTEMD_COLORS
>             … Controls whether colorized output should be generated. …

> We generally default to a "turn on as much as we can" policy, since we believe these concepts are useful and helpful to the user.

Yes I believe in features too. This is about semantics however. Calling a horse a horse.

> would best be fixed in "watch" so that it can deal with the hyperlink sequences as well.

that actually is a good idea though :grinning:
