### ISSUE TITLE
$BOOT/<machine-id> is created without a purpose

### ISSUE THREAD

**Issue by blochl** [systemd/systemd#12363]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > `bootctl install` installs only the needed files and directories for booting.

**Unexpected behaviour you saw**
 > `bootctl install` creates an empty `/boot/<machine-id>` directory, which is not used for anything.

**Steps to reproduce the problem**
> `bootctl install`, on recently updated Arch Linux.

The functionality of creating `$BOOT/<machine-id>` directory was introduced here: 341890de866f2ee34919a47ce3fc6c8cd3c1924c, as far as I understand, in order to overcome some [Fedora-specific problem](https://bugzilla.redhat.com/show_bug.cgi?id=1648907). This should not effect other distributions, where the boot entries may reside in other places (like directly in `/boot`, if it is the ESP).

**Comment by keszybz** [comment]
`/boot/<machine-id>` was previously created by `kernel-install`. The change is that `kernel-install` doesn't do this anymore, but instead the directory is created by `bootctl install`. This is more logical, because the directory is something that is part of the sd-boot logic, and kernel-install supports other bootloaders and plugins can override parts of its logic, so it cannot assume that sd-boot is used.

If `bootctl install` creates the directory in the wrong place for you, then we should teach it to detect the correct location, or you should override its detection with commandline arguments.

**Comment by blochl** [comment]
@keszybz, `bootctl install` does not create it in the wrong location, it just creates it without a purpose. It is not used or needed at all.

```
# tree /boot
/boot
├── initramfs-linux-fallback.img
├── initramfs-linux.img
├── intel-ucode.img
├── vmlinuz-linux
├── 753664e9c63e48e7a012e92d3c6c1327  # <-- An empty and unused directory
├── EFI
│   ├── BOOT
│   │   └── BOOTX64.EFI
│   └── systemd
│       └── systemd-bootx64.efi
└── loader
    ├── entries
    │   └── system.conf
    └── loader.conf
```

**Comment by DaanDeMeyer** [comment]
The requirement for a machine-id to exist is rather awkward when generating images as its not guaranteed for one to exist if we haven't booted the image yet. mkosi currently suffers from this issue.

Can we make kernel-install and bootctl work without a dependency on the machine-id?

**Comment by poettering** [comment]
I guess we can close this given 31e57550b552e113bd3d44355b237c41e42beb58
