### ISSUE TITLE
systemd-run and user services don't respect cgroup properties

### ISSUE THREAD

**Issue by prasannavl** [systemd/systemd#12362]
**systemd version the issue has been seen with**
> systemd 240
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu 19.04

**Expected behaviour you didn't see**
 > When using systemd-run to execute ad-hoc services, one would expect that it respects cgroup limits when run with `--user` in user mode as well.  

**Unexpected behaviour you saw**
 > It ignores the cgroup limits when run as `--user`

**Steps to reproduce the problem**

### What works: 

`sudo systemd-run -p CPUQuota=25% --slice=stress -- stress -c 4`

Monitoring the CPU shows expected behaviour, where it's limited to 25%. 

### What should work as well, ideally:

`systemd-run --user -p CPUQuota=25% --slice=stress -- stress -c 4`

The cgroup properties are completely ignored. 

Exploring further and look at the process shows that: 

```
> cat /proc/19347/cgroup

12:perf_event:/
11:rdma:/
10:net_cls,net_prio:/
9:freezer:/
8:pids:/user.slice/user-1000.slice/user@1000.service
7:hugetlb:/
6:memory:/user.slice/user-1000.slice/user@1000.service
5:cpu,cpuacct:/user.slice
4:devices:/user.slice
3:blkio:/user.slice
2:cpuset:/
1:name=systemd:/user.slice/user-1000.slice/user@1000.service/stress.slice/run-rf5cda2be3fe7444ea748ed5e85344a0d.service
0::/user.slice/user-1000.slice/user@1000.service/stress.slice/run-rf5cda2be3fe7444ea748ed5e85344a0d.service
```

The generated service still uses `/user.slice` for all practical purposes, and the `--slice` option that's given is functionally not being very useful.

**Comment by poettering** [comment]
cgroup controller access on cgroupv1 is not safe, which is why we don't delegate access to it to unprivileged clients ever. On cgroupv2 delegating access to controllers to unpriv clients is safe for the first time, which allows us to support that, and we do. However, delegation is opt-in individually for security reasons, and right now we only delegate the memory and pids controllers since the other controllers by default (i.e. cpu and io) have too big a performance impact on the system still. You can tweak that however, by extending user@.service globally or for your user with a `Delegate=cpu` line. If the "cpu" controller impact becomes less of a problem we hope to delegate it by default, but that requires more kernel work.

Hence, to do what you want to do:

1. Please switch to cgroupv2, for example by adding `systemd.unified_cgroup_hierarchy=1` to your kernel cmdline.
2. Delegate the "cpu" controller to your user systemd instance. For that run `systemctl edit user@.service` and add a line `Delegate=cpu` in the `[Service]` section.

Yupp, this is not easy, and I am really looking forward to making this all the default, but we can't do this until the kernel folks say it's OK to do so. Sorry!

(And in case you ask why we don#t log about this: we actually do, but only at debug level. if you turn on debug logging you will see this. The reason it's only on debug level, is to not annoy everyone with these error messages all the time since it's a "known-doesn't-work" thing.)

**Comment by prasannavl** [comment]
@poettering Thank you so much for taking the time to provide a detailed answer and potential way to do this as well. This is extremely helpful!

**Comment by benzea** [comment]
So, I just tried that:

 * `/proc/cmdline` contains: `systemd.unified_cgroup_hierarchy=1`
 * Added `Delegate=cpu` into `user@.service`

However, nothing changes. And looking at the cgroup hierarchy in /sys/fs/cgroup I see:
 * `cgroup.controllers`: cpuset cpu io memory pids
 * `user.slice/cgroup.controllers`: memory pids
 * `user.slice/user-1000.slice/cgroup.controllers`: memory pids
 * `user.slice/user-1000.slice/user@1000.service/cgroup.controllers`: memory pids

Could it be that I need to do something so that `user.slice` is getting the delegation in the first place? I tried adding a `user.slice` drop-in, but that did not seem to help.
