### ISSUE TITLE
Dracut can no longer start systemd-crypt@ service

### ISSUE THREAD

**Issue by paulvt** [systemd/systemd#12371]
**systemd version the issue has been seen with**
 > 237

**Used distribution**
 >Ubuntu 18.04 LTS (Bionic)
   (with systemd source package version 237-3ubuntu10.20)

**Expected behaviour you didn't see**
 >Dracut initrd opened the encrypted system filesystem and booted the OS

**Unexpected behaviour you saw**
 >Dracut timed out waiting for the filesystem to become available and jumped to the rescue shell.

**Steps to reproduce the problem**
This is the hard part because it is a very specific situation.  We deliver a Ubuntu-derived OS to our customers on several hardware (PC-type) models that is OSTree-based and uses Dracut to boot it.

When Ubuntu merged #11121 in version 237-3ubuntu10.17, the models we have that tend to have "slow I/O" no longer booted but timed out waiting for the root filesystem to unlock.
When using the dracut rescue shell I could determine that it was stuck on starting the `systemd-crypt@crypt_system.service`.  If I run:

> systemctl start systemd-crypt@crypt_system.service

the command just hangs, while I can perfectly manually run the ExecStart command that is in this service unit:

```ini
# Automatically generated by systemd-cryptsetup-generator

[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
IgnoreOnIsolate=true
After=cryptsetup-pre.target
Before=cryptsetup.target
RequiresMountsFor=/tmp/path/to/some_keyfile
BindsTo=dev-disk-by\x2dpartlabel-something.device
After=dev-disk-by\x2dpartlabel-something.device
Before=umount.target

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
KeyringMode=shared
ExecStart=/lib/systemd/systemd-cryptsetup attach 'crypt_system' '/dev/disk/by-partlabel/something' '/tmp/path/to/some_keyfile' 
ExecStop=/lib/systemd/systemd-cryptsetup detach 'crypt_system'
```

It seems that the fix backfired for us? I do not know well how to provide more information from the Dracut rescue shell, but please let me know what I can do to add information either for reproducing this or of the context.

**Comment by poettering** [comment]
Hmm, I wasn't aware ubuntu uses dracut? 

So please contact ubuntu or the dracut communities about this for help first. In this bug tracker we only cover issues in the two most recently released systemd versions, specifically 242 + 241 right now. For everything else, please let the downstreams have a look first, and they'll propagate this to us if they find it's still in issue with current systemd versions.

Please understand that we cannot really cover all downstreams issues here, in particular for out of date stuff. To minimize disappointments because of this we actually try to make this clear in the issue submission form...

Sorry!
