### ISSUE TITLE
DHCP=both not documented

### ISSUE THREAD

**Issue by simonsmiley** [systemd/systemd#124]
the man files don't include "both". I found it on some wiki because I knew there has to be some option to enable both. I think this should be added to the network manpage.

**Comment by poettering** [comment]
Yeah, it's an old name for "yes", we unified a few things, and renamed it in the process. The documentation only carries the new name, but we still accept the old name for compatibility.

**Comment by simonsmiley** [comment]
hmm. had been using "true" before which only enabled ipv4.
I only have ipv6 on my dedicated server, so I don't restart that often. 
Is "true" different from "yes"?

**Comment by poettering** [comment]
Oh, well, this is a bit confusing. Basically, it's now considered a boolean with two additional values "ipv4" and "ipv6". Because it is a boolean in the systemd sense it takes "yes", "no", "1", "0", "true", "false" and so on, and they positive ones are all equivalent. Hence, "both", "yes", "1", "true" are now all considered equivalent.

I hope this makes more sense now?

**Comment by simonsmiley** [comment]
thanks for the clarification. Will have to check why dhcp didn't work for ipv6... I guess I should configure it manually in my case anyway.
