### ISSUE TITLE
RFE: hwdb: Add Corsair K70 keyboard

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#1243]
I'm not sure what the correct way to specify the entry should look like, but https://bugzilla.redhat.com/show_bug.cgi?id=1262132 has a working "patch".

**Comment by poettering** [comment]
I figure you mean these lines?

```
# Corsair K70 keyboard
#keyboard:name:*Corsair*:dmi:bvn*:bvr*:bd*:svn*:pn*:pvr*
keyboard:usb:v1B1Cp1B09*
 KEYBOARD_KEY_70032=reserved
```

**Comment by poettering** [comment]
@martinpitt, maybe something for you?

**Comment by jsynacek** [comment]
@poettering Yes, those lines. I didn't want to create a proper patch myself, since those lines are unlike the rest in the file and I don't know _the way_ to add entries into hwdb.

**Comment by martinpitt** [comment]
I created a pull request which translates this to the current format; 219 is already quite old and used a different syntax. I'm reasonably sure that this is correct, but testing again can't hurt of course.

**Comment by gboesebeck** [comment]
Hi,
bad Fix. On a german keyboard layout the #-key won´t work with the Fix. 
KEYBOARD_KEY_70032 is the "#" and "'" Key

**Comment by martinpitt** [comment]
@jsynacek, @gboesebeck : Argh, so that has the exact vendor/product number and same scan code, but the English version sends two scan codes and the German one just one (which this patch then disabled)? I mean, this patch is a rather weird hack around a keyboard driver bug anyway, but if this breaks stuff it needs to go. I reverted this in current master in https://github.com/systemd/systemd/commit/10f4371fd7e0ec2670300cef137fdbfce55c7acb .

@jsynacek : Can you please get an "evtest" output of that keyboard when the faulty key gets pressed? I wonder what really happens there.

**Comment by jsynacek** [comment]
I don't have the keyboard, I just forwarded the original bug...

**Comment by DeltaNova** [comment]
@martinpitt : Same issue with # key on UK layout. evtest result below.

#Event: time 1443427054.710239, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70032
Event: time 1443427054.710239, type 1 (EV_KEY), code 43 (KEY_BACKSLASH), value 0
Event: time 1443427054.710239, -------------- SYN_REPORT ------------

**Comment by martinpitt** [comment]
@DeltaNova : Within the realm of udev keymaps this looks okay. If you have an US keyboard but configured an UK layout on your desktop, X.org will translate the keys accordingly. udev's keymaps are not the place to do this kind of layout specific translations, but only to add missing key codes to scan codes.

**Comment by poettering** [comment]
@gboesebeck can you provide the evtest output @martinpitt requested? Otherwise we can only close the bug I fear, since there's nobody able to provide us with the necessary data to fix it...

**Comment by poettering** [comment]
Closing, due to lack of response.
