### ISSUE TITLE
bootctl not fully functional is EFI partition is mirrored

### ISSUE THREAD

**Issue by Uglymotha** [systemd/systemd#12468]
Systemd 242:

When the EFI system partition is mirrored bootctl is not fully functional, because it tries to get the partition table in an unsupported way. Because of this bootctl cannot install boot loader on the EFI partition.

EFI partition is mirrored and mouonted on /boot:
[root@rdsan01 log]# mount |grep boot
/dev/md124 on /boot type vfat (rw,nosuid,nodev,noexec,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)

[root@rdsan01 log]# cat /proc/mdstat |grep md124
md124 : active raid1 sdw1[0] sdx1[2]

Device       Start      End  Sectors  Size Type
/dev/sdw1     2048  4196351  4194304    2G EFI System
/dev/sdw2  4196352 30218808 26022457 12,4G Linux filesystem

The system is started by systemd boot loader, but bootctl gives error:
[root@rdsan01 log]# bootctl
Failed to probe partition scheme of "/dev/block/9:124": Input/output error
Failed to probe partition scheme of "/dev/block/9:124": Input/output error
System:
     Firmware: UEFI 2.31 (American Megatrends 4.653)
  Secure Boot: disabled
   Setup Mode: setup

Current Boot Loader:
      Product: systemd-boot 242
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
          ESP: /dev/disk/by-partuuid/86bb3d8a-1f8b-6146-a63d-77a435eec907
         File: └─systemd-bootx64.efi

Boot Loaders Listed in EFI Variables:
        Title: 1-uglylinux
           ID: 0x0000
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/86bb3d8a-1f8b-6146-a63d-77a435eec907
         File: └─systemd-bootx64.efi

        Title: 2-uglylinux
           ID: 0x0001
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/a944bbf3-5dc2-244c-87b5-f112fb61807e
         File: └─systemd-bootx64.efi

An strace shows:
openat(AT_FDCWD, "/sys/dev/block/9:124", O_RDONLY|O_CLOEXEC) = 4
faccessat(4, "partition", F_OK)         = -1 ENOENT (No such file or directory)
openat(4, "dm/uuid", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
close(4)                                = 0

And later:
openat(AT_FDCWD, "/dev/block/9:124", O_RDONLY|O_CLOEXEC) = 3
fadvise64(3, 0, 0, POSIX_FADV_RANDOM)   = 0
fstat(3, {st_mode=S_IFBLK|0660, st_rdev=makedev(0x9, 0x7c), ...}) = 0
ioctl(3, BLKGETSIZE64, [2147418112])    = 0
.....
lseek(3, 2097152, SEEK_SET)             = 2097152
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
writev(2, [{iov_base="Failed to probe partition scheme"..., iov_len=74}, {iov_base="\n", iov_len=1}], 2Failed to probe partition scheme of "/dev/block/9:124": Input/output error
) = 75
close(3)                                = 0

**Comment by poettering** [comment]
ESP partitions need to be on the top-level GPT partition table. Nothing else is supported. Sorry. It's by EFI spec. The EFI spec doesn't know Linux mdraid...

**Comment by andrejpodzimek** [comment]
The EFI spec doesn't need to know Linux `mdadm` stuff as long as it's "undetectable", e.g. like this:

```
[Unit]
Description=UEFI partition replication RAID
Before=boot-efi.mount

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=mdadm --build efi --level=raid1 --raid-devices=2 /dev/disk/by-id/usb-Samsung_Flash_Drive_0374718070015469-0:0-part1 /dev/disk/by-id/usb-Samsung_Flash_Drive_0362920010004877-0:0-part1
ExecStop=mdadm --stop /dev/md/efi

[Install]
RequiredBy=dev-md-efi.device
RequiredBy=boot-efi.mount
```

The partitions involved are both valid EFI partitions and there is no wannabe-RAID metadata on them. EFI can boot from any of them without any issue. (Most EFI implementations will likely list only one, because of the UUID clash, but that's not a big deal as long as at least one is available.) Unfortunately, with the partition probe (a.k.a. *anti-feature*) in place, I'm still getting this error:

```
Failed to probe partition scheme of "/dev/block/9:127": Input/output error
```


It would be awesome to have an option that would bypass the check, like `--force-and-i-really-mean-it` or perhaps `--it-is-none-of-your-business-to-probe-my-partition`. The obvious alternative is to mount just one of the partitions involved and then re-sync them, but that doesn't work with automatic `systemd` update hooks, such as [`systemd-boot-pacman-hook`](https://aur.archlinux.org/packages/systemd-boot-pacman-hook/).

**Comment by poettering** [comment]
First of all, you can set the `SYSTEMD_RELAX_ESP_CHECKS=1` env var if you want to shoot yourself in the foot

But just doing mirroring from linux side is not sufficient. The firmware/boot loader can write to the ESP too, and since they don't do RAID things will fall apart badly. And yes, sd-boot writes to the ESP if boot counting/boot assessment is enabled.

On top of that, the ESP is shared between OSes, so as soon as you do multi boot things fall apart even worse.

RAID is supposed to be about increasing reliability. Using RAID for the ESP is gaming, it's risk. Maybe if all your assumptions are right and nothing interferes with your setup the way the specs permit it you might get away with it, but it's certainly nothing we should officially support because it cannot work in the general case. Sorry.

**Comment by andrejpodzimek** [comment]
> First of all, you can set the `SYSTEMD_RELAX_ESP_CHECKS=1` env var if you want to shoot yourself in the foot

Tried that (also combined with `SYSTEMD_ESP_PATH=/boot`), but `bootctl update` still fails the same way. :disappointed:

Otherwise I fully agree that the ESP mirroring idea is risky and can fail in surprising ways.

**Comment by poettering** [comment]
> > First of all, you can set the `SYSTEMD_RELAX_ESP_CHECKS=1` env var if you want to shoot yourself in the foot
> 
> Tried that (also combined with `SYSTEMD_ESP_PATH=/boot`), but `bootctl update` still fails the same way. disappointed

Hmm, can you file a bug about that? if the relax env var is set it should just work regardless what the backing storage is.

**Comment by er2805620** [comment]
BTW, if you using mdadm metadata should be version 1.0
example
```
mdadm --create --verbose --level=1 --metadata=1.0 --raid-devices=2 /dev/md/ESP /dev/sdaX /dev/sdbY
```

**Comment by MartinX3** [comment]
@er2805620 in theory yes because metadata 1.0 is at the end of the partition.
But it doesn't work.
See https://github.com/systemd/systemd/issues/17298
