### ISSUE TITLE
journalctl’s light gray unreadable

### ISSUE THREAD

**Issue by yath** [systemd/systemd#12482]
**systemd version the issue has been seen with**
% journalctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
Debian sid, amd64

**Expected behaviour you didn't see**
* Enable debugging for e.g. BlueZ (`-d`)
* Run `journalctl -efu bluetooth.service`
* Have debug messages printed readable on the console

**Unexpected behaviour you saw**
* Debug messages show up in gray, which is unreadable on a white background.

**Steps to reproduce the problem**
* Configure your terminal to a white background
* Emit a message with level DEBUG to the journal
* Try reading this message

I couldn’t find any option to turn this coloring off or to have it use different colors; I could only get around this using `journalctl|cat`.

**Comment by poettering** [comment]
which terminal (and color scheme) is that? I played around with some when I picked the grey color, and it always looked quite OK. I am a bit surprised that it doesn't work on yours.

**Comment by yath** [comment]
That’s rxvt-unicode with (relevant for the output) only “Rxvt*reverseVideo: false” set, no special color scheme or anything. I think running `urxvt +rv` should give you the same configuration for the terminal.

**Comment by keszybz** [comment]
urxvt: ![Screenshot from 2019-05-08 08-54-22](https://user-images.githubusercontent.com/349618/57355710-eee77c00-716e-11e9-8652-48904a90ed95.png)
Yep, it's fairly hard to read.

I'm inclined to treat it is a bug in the terminal emulator. What's the point of having a terminal colour that cannot be distinguished from the background? A terminal emulator is not a paint program, and the basic 8 colours are there to output text.

Even xterm does this better: 
![Screenshot from 2019-05-08 08-56-17](https://user-images.githubusercontent.com/349618/57355870-543b6d00-716f-11e9-8b86-910fb0fd9b22.png)

gnome-terminal: 
![Screenshot from 2019-05-08 08-58-04](https://user-images.githubusercontent.com/349618/57355922-6f0de180-716f-11e9-897c-79d6ab19154e.png)
gnome-terminal with different background: 
![Screenshot from 2019-05-08 08-58-47](https://user-images.githubusercontent.com/349618/57355956-85b43880-716f-11e9-9b1f-58c477dbe5fc.png)
konsole with default black-on-white profile: 
![Screenshot from 2019-05-08 09-06-09](https://user-images.githubusercontent.com/349618/57356377-987b3d00-7170-11e9-8e3b-2d2f0044fd19.png)

**Comment by jdebp** [comment]
You are using SGR 37 to set a white foreground, on a bright white background.  It is unreasonable to blame terminal emulators for the fact that white on white is difficult to read.

Part of your problem is talking of the "basic 8 colours", and then pretending in `terminal-util.h` that you have _nine_ of them, with "white" magically distinct from "grey".  You are using SGR 37 _for both_.

And no, SGR 1 is not required to mean bright and SGR 2 to mean dim.  That's a PC-ism.  On several terminal emulators, and indeed on real terminals such as a genuine DEC VT, SGR 1 means **boldface** and is not a colour change but a _font weight change_ to a heavier font, and likewise SGR 2 means faint, a lighter font weight.  Your only _proper colour change_ for both your "white" and your "grey" is SGR 37.

If you want a ninth "grey" colour that is _both_ significantly different from bright white (the background colour in this particular case: SGR 107, one of the AIXterm extensions) _and_ different from your SGR 37 "white", then you have to similarly use the AIXterm 16-colour mechanism and use bright black (SGR 90) or resort to 256-colour control sequences.

**Comment by poettering** [comment]
SGR 90 is not recognizable on default gnome terminal, it's too dark. Somehow I believe that matters more than urxvt...

256 color sequences don't work on the linux console iirc

**Comment by poettering** [comment]
so SGR 2 ("dim") sounds like an option to me. does the right thing on gnome-terminal and linux console. If it doesn't do the right thing on a genuine DEC VT I am not too concerned I must say.

```sh
echo -e "\e[2mHello World\e[0m"
```
only (big) minus point: it doesn't do anything on terminals with a bright background... just looks like regular text there...

**Comment by poettering** [comment]
Please have a look at #12535. I decided to go for 256 color sequences, as the Linux console supports those for a while now too.

**Comment by oliverpool** [comment]
Since https://github.com/systemd/systemd/pull/17702 has been merged (released in version 248), you can use set the `SYSTEMD_COLORS` environement variable to `16` to accommodate your palette.

> Various tools now accept SYSTEMD_COLORS=16|256 to configure what colours are used in output.
