### ISSUE TITLE
systemd should try not execute non regular files

### ISSUE THREAD

**Issue by crrodriguez** [systemd/systemd#12495]
**systemd version the issue has been seen with**
> git HEAD

**Expected behaviour you didn't see**
 > Failed to find executable ./foo: Not a regular file

**Unexpected behaviour you saw**
 > strace of pid 1 shows systemd is actually executing fifos 
strace  -eexecve -f -p 1
strace: Process 1 attached
strace: Process 26236 attached
[pid 26236] execve("/home/crrodriguez/./foo", ["/home/crrodriguez/./foo"], 0x560269dc4be0 /* 4 vars */) = -1 EACCES (Permission denied)

Since this linux kernel commit https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=73601ea5b7b18eb234219ae2adf77530f389da79 , it returns EACESS but in older kernel versions executing non regular files will result in unexpected behaviour.

**Steps to reproduce the problem**
mkfifo foo
chmod 755 foo
systemd-run -t ./foo

**Comment by vcaputo** [comment]
There's no way for systemd to actually prevent this without a TOCTOU race since it's not like we pass an opened fd to some nonexistant `fdexecve()` syscall, so I don't think there's much value in even bothering with trying to police this in systemd.

It's the kernel's responsibility to determine what is and isn't executable within the `execve()` implementation.

**Comment by crrodriguez** [comment]
> There's no way for systemd to actually prevent this without a TOCTOU race since it's not like we pass an opened fd to some nonexistant `fdexecve()` syscall, so I don't think there's much value in even bothering with trying to police this in systemd.
> 
> It's the kernel's responsibility to determine what is and isn't executable within the `execve()` implementation.

systemd already checks if the file can be executed, using access(..X_OK) ...

**Comment by crrodriguez** [comment]
> There's no way for systemd to actually prevent this without a TOCTOU race since it's not like we pass an opened fd to some nonexistant `fdexecve()` syscall,

You are looking for execveat(2) with  AT_EMPTY_PATH. (kernel 3.19 or later)

**Comment by poettering** [comment]
why would we check this explicitly? the kernel does that already, so why second-guess that?

**Comment by vcaputo** [comment]
> > There's no way for systemd to actually prevent this without a TOCTOU race since it's not like we pass an opened fd to some nonexistant `fdexecve()` syscall,
> 
> You are looking for execveat(2) with AT_EMPTY_PATH. (kernel 3.19 or later)

Negative.  The *at() class of functions take a `dirfd` to omit the *parent* *directory* path lookup, they do not take the already opened file descriptor.  The file name must still be looked up within the pre-opened directory, there's still a race window there.

But I do think there's a contortion to achieve this race-free via the magic of `/proc`.  If the file were opened, its mode checked using `fstat()` on its file descriptor, then its path in `/proc/self/fd/$fdnum` supplied to `execve()` if deemed a regular file, it would be race-free.  I'm not sure if that results in all sorts of ugly artifacts elsewhere however (ps, top, etc), showing the process' `exe` as some path in proc instead of its configured path.

Regardless, this doesn't seem like a problem which needs solving, unless maybe we're not handling the error case very well when `execve()` fails on non-regular files?  That would be a different issue.

**Comment by floppym** [comment]
> why would we check this explicitly? the kernel does that already, so why second-guess that?

According to the original comment, there is a kernel bug that allows fifos to be executed. I think this issue is suggesting that system work around the kernel bug.

**Comment by poettering** [comment]
> 

Well, but systemd is hardly the only program that executes stuff. There are so many other tools. This really sounds like something you want to fix the kernel on, not something you want to patch into each and every single program that does execve(). I mean the average "bash" script probably triggers a bazillion excve()s more than systemd ever does...

**Comment by poettering** [comment]
> Negative. The `*at()` class of functions take a `dirfd` to omit the _parent_ _directory_ path lookup, they do not take the already opened file descriptor. The file name must still be looked up within the pre-opened directory, there's still a race window there.

As @crrodriguez pointed out AT_EMPTY_PATH helps you with that. it means that the dir fd passed is actually the fd executed, i.e. there's no further path lookup done.

I wonder if execve() with a binary path in /proc/self/fd/X would work too though.

But anyway, I am not convinced we should litter every userspace program calling execve() with this (which is practically every single one), this really sounds like something to fix in the kernel and backport everywhere...

**Comment by vcaputo** [comment]
Ah I missed the `AT_EMPTY_PATH` flag detail, my bad!

I still think it's awkward to be attempting to enforce this in userspace.  It's akin to enforcing file permissions manually before opening a file, at that point I can't help but think "what the hell is going on here?"

**Comment by poettering** [comment]
I very much agree with @vcaputo I must say.

**Comment by floppym** [comment]
I agree this request makes little sense, and I don't see what real world problem it would solve.

**Comment by poettering** [comment]
Ok, let's close this then. @crrodriguez i hope this makes some sense?
