### ISSUE TITLE
Don't fallback to Google NTP and DNS.

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#12499]
For obvious privacy reasons, Google servers shouldn't be used as fallback DNS and NTP servers. In case of FallbackNTP, having two different vendors as fallback will also aid in stability if Google NTP happens to be inaccessible (fe. due to an outage or a block).

In case of FallbackDNS, Google DNS should be replaced with Quad9 DNS, another non-profit without a counter-privacy incentives and a good privacy policy or at least Cloudflare DNS which has a better privacy policy than Google DNS.

**Comment by poettering** [comment]
we currently use cloudflare and google as upstream defaults. There's a build time option to change these defaults and we invite downstreams to make use of that to adjust these servers to what's most suitable to their userbase. Moreover, users can depart from that too.

Anyway, let's close this, as this is really just a default if downstreams don't specify anything explicitly. If you are unhappy with the choice your downstream distro made, please talk to them. Thank you for understanding.

**Comment by OmgImAlexis** [comment]
Any chance this could be re-evaluated and possibly re-opened?

**Comment by poettering** [comment]
> With the above response, might I ask the developers a question: has this project received any donations from Google?

Christ, what's next? You accuse us of controlling people's minds with vaccinations we get directly from Bill Gates? And that systemd uses 5G to spread CoV-2?

Google is running fuzzing infrastructure for us, like for a lot of other open source projects. Other than that I think Google is pretty anti-systemd though, and no Google dev works on systemd, and Google doesn't have anyone related to systemd on their payroll. For example ChromeOS doesn't do systemd, and Kubernetes doesn't play nice at all with systemd, by all I see Google is somewhere between "dislike" and "doesn't care" about systemd.

Anyway, if there's a well respected network of community DNS servers that can roughly match Cloudflare/Google we can add, sure. But in general: please work with your downstreams: it's explicitly configurable in the build scripts so that distros can make their own educated decisions. Don't complain to us, complain to your distro if they leave these settings unmodified.

**Comment by poettering** [comment]
I will block discussions here now, since I don't think we need the input from the script kiddie peanut gallery here.

**Comment by mbiebl** [comment]
> I will block discussions here now, since I don't think we need the input from the script kiddie peanut gallery here.

Thank you @poettering . All those lame conspiracy theories have become boring indeed.

That said, I think all this fuzz is just not worth it. Personally, I would just not define any default NTP and DNS servers and let meson fail hard if not explicitly set via `-Dntp-servers=` and `-Ddns-servers=`. Most distros set those explicitly anyway and users building systemd on their own will have to make a decision on there own, what they want.
Is there a compelling downside to this approach?
