### ISSUE TITLE
systemd-socket-proxyd unix socket support

### ISSUE THREAD

**Issue by cchamplin** [systemd/systemd#1252]
According to the man page systemd-socket-proxyd supports unix sockets, but it appears that this functionality is currently broken. 

When attempting to socket activate between a unix socket systemd-socket-proxyd fails with "Failed to splice: Invalid argument"

http://ogris.de/howtos/splice.html has a note at the top that reports kernel 4.1.6 will not splice unix sockets.

**Comment by poettering** [comment]
I figure we should rework this to use the copy_bytes() call instead of splice() directly. copy_bytes() has a fallback to sendfile() and read()/write()

**Comment by dvdhrm** [comment]
`systemd-socket-proxyd` intentionally allocates pipes to shovel data between the client and server FDs. If we use `copy_bytes()`, we should get rid of that indirection and let the kernel deal with it (which it should be capable of since some time).

However, I'd first like to hear an explanation why `splice(2)` does not work between a pipe and a unix-socket. I couldn't find the patch that breaks this, care to point to a kernel commit? All I found was the commit below, which should not break splice between pipes and UDS:

```
commit 2b514574f7e88c8498027ee366fd6e7aae5aa4b5
Author: Hannes Frederic Sowa <hannes@stressinduktion.org>
Date:   Thu May 21 17:00:01 2015 +0200

    net: af_unix: implement splice for stream af_unix sockets

    unix_stream_recvmsg is refactored to unix_stream_read_generic in this
    patch and enhanced to deal with pipe splicing. The refactoring is
    inneglible, we mostly have to deal with a non-existing struct msghdr
    argument.

    Signed-off-by: Hannes Frederic Sowa <hannes@stressinduktion.org>
    Signed-off-by: David S. Miller <davem@davemloft.net>
```

**Comment by poettering** [comment]
So, just using copy_bytes() is not an option btw, as that only sensibly works for blocking fds, and these ones are non-blocking, for a good reason.

I'd really like to know why the kernel broke splice() for AF_UNIX there. It really looks like a bug, not an intended breakage. As such, this should be reported upstream in the kernel bugzilla or so. @cchamplin could you take care of that? I am tempted to close this here as "not-our-bug"...

**Comment by poettering** [comment]
So, looking at this again, if the kernel doesn't allow splice() between AF_UNIX and a pipe anymore, then splice() kinda lost any value at all... Because splice() was very much created for cases like this...

**Comment by poettering** [comment]
@cchamplin which kernel version did you test this btw?

**Comment by poettering** [comment]
So, I tested this on kernel 4.3.0 here, with current git. And it works perfectly. I used the socket proxy to connect UDP to TCP, TCP to UDP and UDP to UDP, and all worked fine. I presume this was a kernel issue that since has been fixed. Closing hence. If you can reproduce this with a current kernel and current systemd, please reopen.

**Comment by dm-coding** [comment]
For anyone experiencing the same issue, I can confirm this was a problem as far back as Debian Jessie's 3.16.7 (systemd 215). Looks like I'll have to try a system which uses a more recent kernel...

Steps to reproduce: run vagrant in this repository -- https://github.com/djcf/wordpress-fpm-docker/tree/df71d11aee4eb0595892317b82e8d66ab209e64d
