### ISSUE TITLE
Currently outstanding CI issues

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#12570]
As the current CI issues are seriously affecting reliablity of our CI's, and are scattered over (mostly) closed threads, let's track them in one place, so they can be fixed as soon as possible.

1. `journalctl --flush` is unreliable
 Since the introduction of journald varlink interface in https://github.com/systemd/systemd/pull/12230 `journalctl --flush` became pretty unreliable, which makes Azure Pipelines fail quite often. Apart from that, it looks there is a particularly nasty security issue (reported by oss-fuzz).
 See this particular comment: https://github.com/systemd/systemd/pull/12230#issuecomment-491593897

2. This was fixed in https://github.com/systemd/systemd/issues/12425. `TEST-31-OOMPOLICY` is unstable in CentOS CI (and possibly Ubuntu CI)
 It looks like under certain coditions the SIGKILL sent by OOM killer is not caught by systemd and the `oomtest.service` ends up in an *unexpected* state (unexpected for the test), i.e. `ActiveState=signal` instead of the expected `ActiveState=oom-kill`.
 See: https://github.com/systemd/systemd/issues/12425

3. This one was fixed in https://github.com/systemd/systemd/pull/12577. `test_bond_operstate` is unstable
 For the past few weeks the `systemd-networkd-tests.py` testsuite has been pretty stable except for the `test_bond_operstate` case:

 ```
 ======================================================================
FAIL: test_bond_operstate (__main__.NetworkdNetWorkBondTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 1581, in test_bond_operstate
    self.assertRegex(output, 'State: no-carrier \(configured\)')
AssertionError: Regex didn't match: 'State: no-carrier \\(configured\\)' not found in '● 104: bond99\n       Link File: /usr/lib/systemd/network/99-default.link\n    Network File: /run/systemd/network/bond99.network\n            Type: bond\n           State: degraded-carrier (configured)\n          Driver: bonding\n      HW Address: 9e:41:e0:00:13:e1\n         Address: 192.168.123.45\n                  fe80::9c41:e0ff:fe00:13e1'
```

 This might need some attention.
 Related thread: https://github.com/systemd/systemd-centos-ci/pull/104#issuecomment-491440822
 See also: https://github.com/systemd/systemd/issues/12344

@evverx I'm not sure if I haven't forgotten something, so feel free to add anything you may consider relevant.

**Comment by evverx** [comment]
Regarding that bug found by ClusterFuzz, I singled it out mainly because I'd never seen the label "security: high" there before. They might have improved their automatic rating system or given that I don't always stare at bug reports very closely to notice all the tags and labels I just might have missed it :-) Anyway, it's not worse or better than the 4 or 5 other bugs in varlink ClusterFuzz has found. It would probably make sense to fix them all by the next release.

**Comment by poettering** [comment]
So, the OOM thing is probably a race. unlike the current code assumes the SIGCHLD for a OOM-killed process is not guaranteed to arrive after the OOM event we receive via cgroups. That sucks hard. Not sure how to fix this best, because this means we'll learn about the reason for a service failure only after the fact sometimes...

**Comment by keszybz** [comment]
I'll look into the oss-fuzz reports. I wouldn't worry too much about the security rating: it's unreleased code, so a bug is a bug to be fixed, but has no security impact really.

**Comment by keszybz** [comment]
I fired off rebuilds of all oss-fuzz varlink issues. Let's see how many are still reproducible.

**Comment by evverx** [comment]
Looks like ClusterFuzz has just opened two new issues (that look suspiciously similar to the ones that were opened) and marked them as "flaky". I'm not sure what happened but if I did I'd report it on https://github.com/google/oss-fuzz (apparently deduplication doesn't always work as expected) :-)

**Comment by evverx** [comment]
By the way, as far as know, ClusterFuzz usually pulls the code once a day in the morning and starts fuzzing it (if it compiles) or fall back to the last version that can be built. I'm not sure it's possible to find out whether the bugs are fixed until tomorrow.

**Comment by keszybz** [comment]
Yep. It's "latest" commit is cb367b17853d215ebcf2816118c1f53d003e5088 which is a few days old. So all the rebuilds I did are useless. Let's wait.

**Comment by keszybz** [comment]
Two of the three issues are fixed, and the third one has it's own bug too. Let's track the remaining stuff there.

**Comment by evverx** [comment]
I'm not sure I understand why you think two of the three issues are fixed.

`journalctl --flush` is still flaky and the test fails from time to time on CentOS CI (though not as often as it failed on Travis CI and Azure Pipelines where it was simply turned off).

Regarding TEST-31-OOMPOLICY, I think it'd would make sense to simply skip it on CentOS.

**Comment by keszybz** [comment]
I don't see much point in creating meta-bugs. Let's track individual bugs in their own tickets. At least here, `--flush` seems to work OK with the latest fixes. If not, let's create a new bug for it.

**Comment by evverx** [comment]
> At least here, --flush seems to work OK with the latest fixes.

I suspect that's because you don't very often run TEST-01-BASIC (where systemd built with ASan+UBSan is run in VMs) (which had never failed before varlink was merged).

> I don't see much point in creating meta-bugs

I edited the description so now it should be more or less clear that the only bug tracked here is about `journalctl --flush`. I think it should be possible to remove unnecessary parts to make it less "meta".

> If not, let's create a new bug for it.

Well, you just closed the issue without opening a new one regrading `journalctl --flush`.

**Comment by yuwata** [comment]
Now all CIs are green. Is the last issue was fixed??

**Comment by evverx** [comment]
@yuwata unfortunately no, it wasn't. The test was just turned off where it failed too often and keep failing on Cent OS CI from time to time. To find out whether the issue is fixed it should be possible to uncomment the following:

https://github.com/systemd/systemd/blob/de26d715e3482bd406ad45f698428d4179d013da/travis-ci/managers/xenial.sh#L59-L60

and try to run it, say, 20 times in a row.

**Comment by yuwata** [comment]
> The test was just turned off

Ugh...

**Comment by yuwata** [comment]
(I do not think it is a good idea to hide the errors. We, at least I, often forget if errors are hidden.)

**Comment by evverx** [comment]
I don't think it's a good idea either. Ideally, issues should be fixed right away as soon as they're discovered (which is kind of the point of CI in general). In practice it's not always possible so as a last resort tests are skipped to keep the status "green" (so that people can keep paying attention to it to prevent news bugs from making it to the repository). Known issues (like this one) are tracked via a bug tracker as usual.
