### ISSUE TITLE
Offer option to umount stale NFS shares lazily

### ISSUE THREAD

**Issue by twwn** [systemd/systemd#1257]
By design, NFS mounts wait indefinitely for an unreachable/stale share to reappear. Umounts will thus return a "device busy".

This means systemd currently stalls during a shutdown with one of these shares, and needlessly so when there are no pending transfers.

A solution for this case is to do a lazy (resp. if required, forced) umount, perhaps as an option like the 7x C-A-Del combo.

**Comment by poettering** [comment]
I am not sure this could work. I mean, we automatically order unmounting by path prefix, so that /foo is unmounted after /foo/bar. Now, if you lazily unmount /foo/bar, and then go for unmounting /foo, then things will not work, since the thing is not actually unmounted, and keeps /foo busy. 

Not sure what we can do about this, but I doubt that lazy unmounting is really a comprehensive solution for anything...

**Comment by poettering** [comment]
Fixed by #3827.
