### ISSUE TITLE
bootctl rejects loader entries with boot counting

### ISSUE THREAD

**Issue by juergbi** [systemd/systemd#12572]
**systemd version the issue has been seen with**
> v242
> Issue was likely introduced by commit eed7210a5c13299364cddf3600c2e76d4889ab36.

**Used distribution**
 > paldo

**Expected behaviour you didn't see**
 > bootctl working without errors.

**Unexpected behaviour you saw**
 > bootctl reports errors for loader entries that use boot counting, i.e., entry filenames with a `+`:

```
$ bootctl
Invalid loader entry filename: /boot/loader/entries/5.0.13-paldo1-x86_64+1.conf
System:
...
```

**Steps to reproduce the problem**
* Install boot loader entry with boot counting, e.g., using `kernel-install` after writing a positive integer to `/etc/kernel/tries`.
* Run `bootctl`
* Observe error message `Invalid loader entry filename`

**Comment by poettering** [comment]
ouch

**Comment by alexeymuranov** [comment]
I have a tilde `~` in entry names (because i want them to be sorted to the end of the list), and i get:
```console
$ sudo nixos-rebuild boot
building Nix...
building the system configuration...
Invalid loader entry: ~1-ubuntu.conf
Invalid loader entry: ~2-mx19.conf
```

**Comment by keszybz** [comment]
Tilde is a special character in shell syntax, and we don't want add it to the list of allowed characters. Please use `+` instead.

**Comment by alexeymuranov** [comment]
@keszybz, I do not understand the point of this restriction. Why not to allow all ASCII character?

**Comment by poettering** [comment]
The text editor thing is precisely one reason why allowing them in drop-ins is not a good idea: we don't want to get confused by left-over backups of text editors...

There are some chars that we avoid, since they have special meaning in various contexts, and we are fine if they are used in those contexts and don't want to step in their territory and allow conflicting use. For example, we want that people can concat boot loader entry names with ":" or "," as separators, hence we don't allow that either. 

There's a point to be made here, admittedly: we should document the acceptable set precisely.
