### ISSUE TITLE
keyboard freezes after exiting X

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#12616]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929229

After applying the changes from #12378 to the Debian package, the above regression was reported. Starting an X session via `startx` (tested with fvwm) and exiting the X session will lead to an unusable keyboard, where no input is possible anymore.

**Comment by mbiebl** [comment]
@rbalint ^

**Comment by rbalint** [comment]
In a separate terminal could you please run sysdig in an other terminal/screen session like in https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1803993/comments/14 ?
Also please check the state of the keyboard with `kbd_mode -C /dev/tty0` (with the correct VT) before starting and after exiting X. I suspect exiting X leaves the keyboard in raw mode while it should restore it to the original state.

**Comment by mbiebl** [comment]
I don't have access to the system anymore, so I can't switch terminals and I don't have a second system atm so I could use SSH to remotely access the system.
If you can't reproduce the issue yourself, I'll need to setup a VM and test it there.

**Comment by mbiebl** [comment]
```
# loginctl 
SESSION  UID USER    SEAT  TTY  
      1 1000 michael seat0 tty1 
      3 1000 michael       pts/0

2 sessions listed.
# kbd_mode -C /dev/tty1
The keyboard is in Unicode (UTF-8) mode

<startx /usr/bin/openbox && exit >

# kbd_mode -C /dev/tty1
The keyboard is in some unknown mode
```
sysdig.txt attached 
[sysdig.txt](https://github.com/systemd/systemd/files/3195589/sysdig.txt)

**Comment by rbalint** [comment]
@mbiebl Thanks! in the meantime I found that stopping GDM also leaves the keyboard in an unusable state on VT1 without login prompt on Disco.

**Comment by mbiebl** [comment]
Should we revert this PR for the time being or is a fix likely to happen soon?

**Comment by fbuihuu** [comment]
@mbiebl could you share the details to build a similar setup so I can try to reproduce locally ?

**Comment by mbiebl** [comment]
@fbuihuu to reproduce the freeze/regression or the original (security) issue?

If it's the former, you can install Debian sid in VM. The bug is easily reproducible there.

**Comment by fbuihuu** [comment]
@mbiebl sorry for not being cleared at all: I'm trying to reproduce the original security issue currently as I fail seeing how logind can set K_UNICODE if a tty has still an active controller.

**Comment by fbuihuu** [comment]
The regression you reported is expected if you backported 13a43c73d8cbac4b65472de04bb88ea1bacdeb89 since logind stops restoring the VT (and therefore the keyboard mode) after a controller (X server in your case) exits.

**Comment by mbiebl** [comment]
Any updates @rbalint ?

**Comment by poettering** [comment]
@rbalint ping?

**Comment by poettering** [comment]
Do these "startx" X11 instances actually talk to logind to become controllers of their session?

So here's the thing: when a client asks logind to become the "controller" of a session, then logind will put the VT of the session into a special mode, where kbd is off, and a couple of other things are turned off before returning to the client. THen, when the user switches away from the VT it will reset the tty again, so that the user can type stuff in properly again. When the user switches back to the VT of the client, then logind doesn't do anything though (what could it do, after all, we don#t know what the client actually likes its settings to be), so the kbd remains on, and hence the double password thing was seen.

Now, with @rbalint's patch we simply don't muck around with the kbd mode anymore if it's not in unicode/xlate mode, which basically means we never reset the kbd at all anymore, in particular not when a client gives up being a controller. which then breaks things.

(So much at least, how I puzzle things together from the distance: i don't want to install X anymore tbh, kinda happy in wayland land)

So, the right fix appears to me would be that X11 whenenever the VT is switched back to it restores the mode it actually likes before continuing. (Alternatively we could save/restore the mode in logind, i.e. remember what the mode was set to when we switch away, and restore it when switching back, but I#d rather not have that, I think this is something that X11 should set the way it wants.)

Anyway, I think I am going to revert this patch the way it is, it doesn't look right to me. And I think this should be fixed in X11. @nwnk @whot, who's the right one to ping about this in X11?

**Comment by poettering** [comment]
I filed https://gitlab.freedesktop.org/xorg/xserver/issues/857 now I hope this gets some attention there.

**Comment by poettering** [comment]
I filed a full revert in #13109 now, ptal

**Comment by poettering** [comment]
Let's close this now, and continue discussion in #13109 which replaces this one I guess

**Comment by fbuihuu** [comment]
Back to that matter again.

@poettering I'm reading your answer and I'm not sure to understand...

> THen, when the user switches away from the VT it will reset the tty again, so that the user can type stuff in properly again. 

I'm not sure what "it" is supposed to mean in your sentence but neither X nor logind reset the target tty.

In my understanding when a VT switch happens and X is the process controller of the current VT, X server basically acknowledges the VT switch signal and the kernel ends up activating the new VT. And the new state is the one that the kernel has set by default (VT_AUTO, KD_TEXT, ...), the state set by X set on its own VT is not reused on the target VT.

And AFAICS logind doesn't reset anything on VT switch neither (it does but only when the process that took control exits).

> When the user switches back to the VT of the client, then logind doesn't do anything though (what could it do, after all, we don#t know what the client actually likes its settings to be), so the kbd remains on, and hence the double password thing was seen.

Again I don't get the "the kbd remains on" part. It sounds like we have one global state that is shared across all VTs.

When we switch back to the VT which X took control, its state is like it was by X initially before it switched away from it hence with VT_PROCESS, KD_GRAPHICS. 

The kbd remains ON only for the VT we switched from, No ?
