### ISSUE TITLE
Update the homepage about current communication tooling

### ISSUE THREAD

**Issue by ShalokShalom** [systemd/systemd#12648]
Hi there :)

Currently, the homepage directs to Google Plus and the IRC Channel bans every new user by default (as it seems)

Suggestion: Remove the Google Plus links and mention how to actually come into the IRC. 

Thanks a lot

**Comment by mrc0mmand** [comment]
> Currently, the homepage directs to Google Plus and the IRC Channel bans every new user by default (as it seems)

The `#systemd` channel @ Freenode has the `+r` mode set, which means you must have an account on Freenode and identify yourself with NickServ. Otherwise, you'll end up in `#systemd-unregistered` where all this info should be in the topic.

For more information please see https://freenode.net/kb/answer/registration

**Comment by mbiebl** [comment]
I've replaced the Google+ reference with https://twitter.com/pid_eins

**Comment by ShalokShalom** [comment]
I am outright banned. I have visited the channel like 1-2 times before and had never issues with anyone. 
Could you enable me, if I am on some list?

**Comment by keszybz** [comment]
I did `/mode +e $a:shalok` as directed by @mrc0mmand. HTH. If not, please PM in IRC. My nick is "zbyszek".
