### ISSUE TITLE
systemd should validate CPUAffinity mask before applying it

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#12712]
**systemd version the issue has been seen with**
* Current git

**Used distribution**
* Fedora

**Expected behaviour you didn't see**
 * systemd should refuse CPUAffinity values outside of currently installed (online?) CPU range.

**Unexpected behaviour you saw**
```
$ lscpu | grep On-line
On-line CPU(s) list: 0,1
$ systemd-run -p CPUAffinity=0-100 sleep 100
Running as unit: run-r119f69a466994734bbae44e639b3de04.service
$ systemctl show -p CPUAffinity run-r119f69a466994734bbae44e639b3de04.service
CPUAffinity=0-100
$ systemctl show -p MainPID run-r119f69a466994734bbae44e639b3de04.service
MainPID=2798
$ taskset -p 2798
pid 2798's current affinity mask: 3
```

**Comment by keszybz** [comment]
I thought about this when working on the PR, and I wasn't convinced. Why do we care? Online cpus is a dynamic thing, and it seems OK to specify a bigger mask than available CPUs. Also please note that if a strict check was implemented, on a big machine where CPUs can be offlined because of failure at any time, CPUAffinity would suddenly turn into a setting that can cause the unit to fail. I don't think we want this.

**Comment by msekletar** [comment]
I don't know either what a policy should be. I mean we have options which can cause a unit to fail if system state changed (e.g. ExecStart=, if binary is not present anymore the restart of the unit could leave the unit in failed state). On the other hand we have options which are sort of best effort.

Also kernel does AND with the mask that you put in and allowed CPUs mask from cpuset (which contains all online CPUs by default) so AFAICT it won't start scheduling unit automatically on other CPUs if you later bring them online. Maybe we could listen to udev uevents and try to reapply the mask if more cpus were brought online.

**Comment by poettering** [comment]
I agree with @keszybz . We couldnt do this properly even if we wanted as the cpuset might be masked by the cgroupsv2 cpuset. I.e. the actual mask in effect is the AND mask of the process mask we configure, the cpuset Of the cgroup, isolcpus on the kernel cmdline and the cpus actually plugged in and most of these can change dynamicallly. Hence the mask in effect is even more dynamic since its the combination of all four masks and we couldnt possibly follow changes correctly and deal with all.

I am pretty sure its best to leave this all to the kernel to figure out and thus pass the bits in the original user specification the the kernel. It knows best what to do with it and what to accept and what not.
