### ISSUE TITLE
systemd does not allow user names with a dot in them

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#12754]
**systemd version the issue has been seen with**
> master

User names with a dot in them are considered an error. Reading the code in `src/basic/user-util.c`, the comment there says:
```
 - We don't allow any dots (this would break chown syntax which permits dots as user/group name separator)
```

As far as I can tell, nothing is broken on a recent Fedora or RHEL-8 and chown handles such names fine.

Systemd shouldn't enforce artificial restrictions just because another tool *might* misinterpret the data. It should be chown's decision, not systemd's. Besides that, user names with dots in them are perfectly valid.

**Comment by poettering** [comment]
I am not convinced we should allow that. We don't have to support every user name under the sun. I am very sure we should be conservative and not allow services to be run with user names that are not even remotely portable or are ambiguous.

On my Fedora machine I can do this:

```
mkdir foo
chown root.root foo
```

And it just works, with no user `root.root` existing. If we'd allow users with dots, then the above would be ambiguous, it could mean "chown to user `root` + chrgp to a group `root`" or it could mean "chown to a user `root.root` and leave group untouched". And sorry, "chown" is not just *any* tool. It's *the* tool to change file ownership, and if the one major tool everybody knows and uses has this ambiguity then that's what matters.

I mean, it's fine if people have groups or users with dots in them, we won't choke on them, but on the other hand it's a really really bad idea to have that and I am not convinced at all we should allow system services to run with such users. I mean, services are supposed to be portable, and people can just pick a different name easily, we don't have to allow any user/group name under the sun, and dots are really too far off in ambiguous territory...

Sorry, but no, let's please not do that. We should care more about well defined, portable unit files, than allowing users to shoot themselves in the foot needlessly.

Note that this restriction hsa been in place since a long long time in systemd, hence we don't even break compatibility here: it's not that we suddenly broke unit files that previously worked with systemd that no longer work. 

I hope that makes some sense at least, even if we disagree diametrically on this topic?

**Comment by jsynacek** [comment]
> And it just works, with no user `root.root` existing. If we'd allow users with dots, then the above would be ambiguous, it could mean "chown to user `root` + chrgp to a group `root`" or it could mean "chown to a user `root.root` and leave group untouched". 

If you tried that, you would find out that chown is clever enough to recognize that root.root exists if it really does and not interpret the dot as a group separator. And again, that's chown's own interpretation, very likely for "historical reasons" that so plague the modern linux-ish systems.

Anyway, I don't really care strongly about this.

**Comment by wiad** [comment]
As a RHEL customer this is a breaking change for us going from RHEL7 to RHEL8. Making the behaviour configurable in systemd, with the current behaviour as default, would be a good way to make this manageable for organisations with old stupid user/groupnames naming schemes like ours.

**Comment by wiad** [comment]
> > And it just works, with no user `root.root` existing. If we'd allow users with dots, then the above would be ambiguous, it could mean "chown to user `root` + chrgp to a group `root`" or it could mean "chown to a user `root.root` and leave group untouched".
> 
> If you tried that, you would find out that chown is clever enough to recognize that root.root exists if it really does and not interpret the dot as a group separator. And again, that's chown's own interpretation, very likely for "historical reasons" that so plague the modern linux-ish systems.
> 

So, given that chown apparantly works fine with usernames with dots, is there any reason for disallowing it in systemd? Are there any specific problems that has been reported leading to this decision? I understand that this is an old commit, but as I said before, as a RHEL customer this is new behaviour for us, causing quite a bit of extra work.

**Comment by MurzNN** [comment]
My servers very active use user names with dots, and all other software works well with them! Can you describe why systemd don't want to add support for dot in username?

**Comment by keszybz** [comment]
Hmm, chown actually documents `:` as the separator, so support for `.` is just a convenience thing. Would anything break in systemd itself if we allowed `.` too?

**Comment by poettering** [comment]
Let's not add ambiguity about this, see above...

**Comment by poettering** [comment]
I mean, it's fine if people have systems with users like that, but I doubt sysusers.d or User= in systemd should bother with that

**Comment by MurzNN** [comment]
This is serious problem for many users, because systems, that have username with dots, can't use even simple systemd startup scripts! When I write `User=a.korepov` in `.service` file - this not works!

**Comment by poettering** [comment]
Well, system services are *system* services really.

**Comment by MurzNN** [comment]
What about [syncthing](https://docs.syncthing.net/users/autostart.html#linux) (or similar) service, that must work as user service?

**Comment by zdzichu** [comment]
@MurzNN run is as an user service (within `systemd --user`), not system one.

**Comment by MurzNN** [comment]
@zdzichu `systemd --user` not work too, if I have username with dot (eg `a.korepov`) :(

**Comment by poettering** [comment]
@MurzNN hmm? systemd --user should just work, it doesn't resolve any users. Note that in --user services you wouldn't say User=, because everything runs under that UID anyway

**Comment by xundeenergie** [comment]
A possible solution could be, to make it configurable. So administrators who need to start system-services as a user on systems with usernames with dots, should be able to configure it explicitly.

my systems get their usernames from LDAP. The usernames are also the base for their email-addresses... so dots are in their usernames... and I start a tmux-server-session for each users as a system-service with user=..., who needs it, to be able to start working remote from one machine, and change to another machine and continue working from there (start working at home per ssh, and continue at work).

I will understand your thoughts @poettering, but there are really needs for usernames with dots.

I think, a list of additional allowed characters in /etc/systemd/system.conf for usernames can do this job.

**Comment by x670** [comment]
Absolutely agree with @xundeenergie 
Linux supports users with dots, so systemd must. At least with need of explicit configuration

**Comment by keszybz** [comment]
@xundeenergie, @x670 guys, did you notice that this was closed by a patch, and systemd now allows dots is usernames?

**Comment by xundeenergie** [comment]
sorry... i did really not recognize, that there is a patch...

wether debian testing nor fedora 30 contains the new systemd-version... 

now i have only to wait, that my distros implement this new systemd-version.

thank you
