### ISSUE TITLE
hwdb for kernel module parameters

### ISSUE THREAD

**Issue by vfjpl** [systemd/systemd#12915]
Hello. Is there something simillar to hwdb from systemd for kernel module parameters? hwdb let's you applay device specific quirks for your devices. My problem is that video module have brightness_switch_enabled set to true on default. But for my specific hardware it should be set to false. I know how to fix this for myself but it would be great if I could fix it for everyone using the same laptop.

There was change to default value of this parameter
https://github.com/torvalds/linux/commit/886129a8eebebec260165741fe31421482371006

But it was reverted:
https://github.com/torvalds/linux/commit/2843768b701971ab10e62c77d5c75ad7c306f1bd

**Comment by poettering** [comment]
uh, hwdb runs too late for that. @jwrdegoede do you have a comment about this?

What to i don't get: why not just fix that in userspace? i.e. the tool that changes brightness should just keep track of the current whitespace, and when it receives a key press and notices the brightness has not been changed yet it should just change it itself. That should work everywhere and expose the same behaviour everywhere...

**Comment by jwrdegoede** [comment]
@poettering you are right that setting module parameters from hwdb will not work.

@vfjpl: after the revert a fix was added to the kernel which waits for 100ms before responding to a keypress and if userspace changes the brightness within 100ms then the kernel initiated change gets cancelled, iow if userspace sets the brightness within 100ms then the kernel behaves as if brightness_switch_enabled=0 is passed.

This is definitely not a systemd issue, but since we are discussing this here now anyways can you explain how your laptop is special and why you need this option?

**Comment by boucman** [comment]
isn't that what man:modprobe.d is for ? specifying module parameters that will be used for all sources of module loading ?

**Comment by vfjpl** [comment]
@jwrdegoede 
> This is definitely not a systemd issue, but since we are discussing this here now anyways can you explain how your laptop is special and why you need this option?

My laptop is special because it sets brightness itself in hardware.
So it's looks like.
Brightness up key -> laptop raises brightness -> video module reads brightness up key and sends it to userspace -> userspace or video module raises brightness

So brightness is raised 2 times :(

**Comment by jwrdegoede** [comment]
On 01-07-19 09:17, vfjpl wrote:
> @jwrdegoede <https://github.com/jwrdegoede>
> 
>     This is definitely not a systemd issue, but since we are discussing this here now anyways can you explain how your laptop is special and why you need this option?
> 
> My laptop is special because it sets brightness itself in hardware.
> So it's looks like.
> Brightness up key -> laptop raises brightness -> video module reads brightness up key and sends it to userspace -> userspace or video module raises brightness
> 
> So brightness is raised 2 times :(

So the problem here really is that a brightness up key event is generated at all.

Setting brightness_switch_enabled=0 just disables the kernel adjustment of the brightness, userspace will still respond to the event.

So if we go with a brightness_switch_enabled=0 fix then to "fix it for everyone using the same laptop" we would also need some userspace level quirk for this laptop.

It would be better to just disable the sending of the brightnesskey press and we have done this for other laptops.

Can you install and then run sudo evemu-record and then for *all* input devices listed there see if they generate events when pressing the brightness hotkeys?

Note to do this you need to run sudo evemu-record once per input device. I would expect at least the "Video Bus" input node to generate events, but on some laptops the events the events are delivered through multiple devices.

What model laptop is this?

**Comment by jwrdegoede** [comment]
Also what kernel version are you using?

**Comment by vfjpl** [comment]
> Also what kernel version are you using?
tested 4.14 to 5.0
Right now I'm using 5.0


> So the problem here really is that a brightness up key event is generated at all. Setting brightness_switch_enabled=0 just disables the kernel adjustment of the brightness, userspace will still respond to the event.

We should send brightness up key event so userspace can show notification of brightness change. And userspace brightness adjustment can be turned off separately.

Right now there are 2 scenarios:
1. Brightness up key -> laptop raises brightness -> video module raises brightness up and sends event userspace -> userspace don't change brightness and show notification on brightness change.

2. Brightness up key -> laptop raises brightness -> video module sends event to userspace -> userspace change brightness and show notification.

both of this scenarios result in changing brightness two times:
1. laptop and video module
2. laptop and userspace

What I want is
3. Brightness up key -> laptop raises brightness -> video module sends event to userspace -> userspace show notification

now we have only one brightness change and notification

**Comment by jwrdegoede** [comment]
> What I want is
> 3. Brightness up key -> laptop raises brightness -> video module sends event to userspace -> userspace show notification

Right, but we should not send a brightness-up key-press input event in that case.

Instead we should send a "brightness changed" event on the /sys/class/backlight/foo interface your laptop is using, specifically the kernel should call backlight_force_update(foo, BACKLIGHT_UPDATE_HOTKEY) in this case.

So fixing this will require some kernel changes at a minimum we must disable the sending of the key-presses and if the backlight code is not already reporting "brightness changed" events on the keypresses then we need to fix that too.

Can you file a new bug for this at:
https://bugzilla.kernel.org/enter_bug.cgi?product=Drivers

Selecting "Platform_x86" as component, please?

Please include the following there:

1. "dmesg" output (after a fresh boot of 5.0)
2. "ls -l /sys/class/backlight" output
3. "lsmod" output
4. The results of seeing which input nodes currently generate the brightness key events, as I requested before.
5. The manufacturer and model of your laptop, as I requested before.
6. The output of: "grep . /sys/class/dmi/id/* 2> /dev/null" run as a _normal_ user

Also please try the following:

1. Adding both "video.brightness_switch_enabled=0" and "video.report_key_events=1" to the kernel commandline and then retest the keys, do things work properly now?
2. Adding "acpi_backlight=vendor" to your kernel commandline and hen retest the keys, do things work properly now? Please also redo the "ls -l /sys/class/backlight" for this case and record its output separately.
3. Adding "acpi_backlight=native" to your kernel commandline and hen retest the keys, do things work properly now? Please also redo the "ls -l /sys/class/backlight" for this case and record its output separately.

Note I need *all* of the above data otherwise I cannot help you further.

**Comment by vfjpl** [comment]
@jwrdegoede  
> Right, but we should not send a brightness-up key-press input event in that case.

sorry, I didn't know there was separate just brightness_change event and thought that we have to send _something_ to userspace.

https://bugzilla.kernel.org/show_bug.cgi?id=204077

**Comment by poettering** [comment]
OK, the bug apparently has been filed there now. Let's close this here. Any further discussion on that bug please.
