### ISSUE TITLE
Allow to manually trigger timer unit activation

### ISSUE THREAD

**Issue by eMPee584** [systemd/systemd#12998]
The post https://unix.stackexchange.com/questions/526150/force-systemd-timer-to-run-immediately says it cannot be done, which I presume is factual (?).
When writing a unit file, it is mandatory to test correctness of `.service` and `.timer` file. Changing the `OnCalendar` value temporarily to minimize waiting is a crude workaround. Manually executing the service as in `systemctl restart {foo}.service` produces a `Failed to restart {foo}.service: Operation refused, unit {foo}.service may be requested by dependency only.`
Invoking the external program being executed by that service file does not give the same context as it would be run by systemd and thus will not expose relevant error conditions.
So there should be a way to manually trigger timer execution on demand, please.

**Comment by keszybz** [comment]
Just start the service normally with `systemctl start {foo}.service`.

> Manually executing the service as in systemctl restart {foo}.service produces a Failed to restart {foo}.service: Operation refused, unit {foo}.service may be requested by dependency only.

That only happens if the service has RefuseManualStart=yes. Just don't set that.

**Comment by poettering** [comment]
Yes, starting the .service unit directly should be fine, except if you use RefuseManualStart=, which you really shouldn't if you want this to work.

Let's close this.

**Comment by eMPee584** [comment]
To follow up, thanks for the hint. Indeed the file (`update-indico-translation.service` from https://talk.getindico.io/t/translation-workflow/547/4) had 
```
RefuseManualStart=no <= !
RefuseManualStop=yes
```
which I didn't notice / know about. But with `RefuseManualStart=no`, the issue I experienced shouldn't really have occurred. But as I can not reproduce it now, whatever. Thanks for the hint.

**Comment by gdsotirov** [comment]
Just to note that starting the .service unit for the timer directly does not update the status of the timer (e.g. LAST time ran).

**Comment by keszybz** [comment]
That is expected. There are two timestamps: one for the timer, one for the service. When the service is started independently of the timer, the one for the service should be updated, the one for the timer shouldn't.

**Comment by gdsotirov** [comment]
I understood this, but it may be what I want to see that the timer was started successfully at least once (i.e. after deployment), especially if this is a timer with long interval between runs (e.g. I won't like a surprise in few months).

**Comment by gqqnbig** [comment]
> Just to note that starting the .service unit for the timer directly does not update the status of the timer (e.g. LAST time ran).

How would I update the timer status?

**Comment by Hi-Angel** [comment]
Yeah, right. Here's a usecase for this: I created a `foo.service` with `foo.timer` that gets executed once a day. Now I want to see it works correctly, but for various internal reasons the service has been a no-op for half a month, so I can't tell if it works by looking it what it should do.

However, when I look at the logs I see weirdness: the last time systemd logged `foo.service` activation is "March 17", but the last time `foo.timer` was activated is "18min ago". Err, what…? 🤷‍♂️ The timer is simple, so no idea, could it be a bug in the older systemd logging…? I need to activate the timer to see this. Activating the service per se won't do my any good, I know it's working, that part I tested.

**Comment by ShellCode33** [comment]
Here's another use case which is not for testing purposes:

I have a systemd timer that regularly check if the running kernel and the one on disk differ. If they do, I send a desktop notification telling me I should reboot my system.

I also have a package manager hook that triggers this systemd service if the kernel has been updated.
The thing is that when I do that, the timer is not being reset, and the service might end up being run twice in a short period of time because of that.

This is obviously not that big of a deal but is IMO a valid enough scenario to consider implementing timers triggering. An alternative option would be to reset the timer when the associated service is started.

@poettering please would you mind considering reopening this issue ?

**Comment by wallart1** [comment]
I know this is closed. But has anyone considered that one might want to test the timer unit?

**Comment by ajgringo619** [comment]
My use-case for this feature involves VMs, which I use for testing software. Since my tests usually only last a few minutes, maybe a little longer if I'm also updating the system, many of my weekly timers don't fire. My "solution" is to leave each system running until the timers/services are complete.

**Comment by poettering** [comment]
as mentioned, just start the service unit directly with "systemctl start", that always worked.

**Comment by ajgringo619** [comment]
> as mentioned, just start the service unit directly with "systemctl start", that always worked.

That's not what's being discussed here. Starting a service has always worked, what doesn't is forcing a timer to trigger before it's scheduled and update the timer's status in the process.

**Comment by poettering** [comment]
Starting the service directly is equivalent to triggering the timer, in almost all ways.

**Comment by Hi-Angel** [comment]
> Starting the service directly is equivalent to triggering the timer, in almost all ways.

It is not at all, which why everyone asking for this feature. The timer itself has various additional code that you may get wrong, and you need to somehow test it to make sure it's working correctly. Although I myself didn't work with timers for a long time so I forgot the details, but I remember the way timers work was very nuanced and easy to get wrong, which is why [I needed back when I worked with timers a way to trigger them](https://github.com/systemd/systemd/issues/12998#issuecomment-1499015344).

**Comment by poettering** [comment]
Please be less vague. What precisely is different between starting the service directly and triggering it via a timer, in a way that matters?

**Comment by andreaskem** [comment]
I guess people want to check their timer units for typos and are afraid there is could be some syntax error preventing the timer from working? And the expectation is that somehow triggering the timer would show problems? However, I would imagine that is why `systemd-analyze verify` and `systemctl list-timers` exist.

**Comment by gqqnbig** [comment]
`systemd-analyze verify` and `systemctl list-timers` could be sufficient.

**Comment by majal** [comment]
I have another use case which does not involve testing, but an **update to a script.** I have a service that runs a long-running script, and the service is triggered by a timer with `OnUnitInactiveSec=1d`.

Not often, but from time to time, the script needs updating. When that happens I don't want to wait for another 24 hours for the timer to trigger. I'd like a way to trigger it manually. So something like `systemctl trigger my.timer`?
