### ISSUE TITLE
dmesg is spammed with "Journal effective settings seal=..." debug messages

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#13007]
If debug logs are enabled, journald spams the kernel log buffer with:

> systemd-journald[407]: Journal effective settings seal=no compress=yes compress_threshold_bytes=512B

It doesn't seem that the same message needs to be emitted so many times:
```
# dmesg | grep "Journal effective" | wc -l
2223
```

This happens with current master (f34635bcda4e725f72da4ae982b83daf36609b41) but it might also be the case for previous versions.

**Comment by Trippy-Tux** [comment]
I don't want to hijack this thread nor use it to request help, but are you saying this always happen with debug logs on f34635b or relating to a particular crash problem? I'm asking because I'm trying to fix a kali linux in vitrualbox who was not updated for a long time (the kali linux I mean). So this exact message I have (256 times in 27 minutes) is not related to my problem then?

**Comment by fbuihuu** [comment]
IIRC It always happens with debug logs on.

**Comment by keszybz** [comment]
Should be fixed by 170a434c784fc7919e6ad7c269ea4f7abcc6065a.
