### ISSUE TITLE
Add a new kernel cmdline option `systemd.crash_reboot=1` that reboots the machine on a PID 1 crash  after a 10s timeout or so

### ISSUE THREAD

**Issue by Harvie** [systemd/systemd#1300]
I tried to boot debian jessie with systemd on openvz kernel (linux-image-2.6.32-openvz-042stab111), it fails with following message:

> [    6.559835] <27>systemd[1]: Failed to mount tmpfs at /sys/fs/cgroup: No such file or directory

I would appreciate two things:

1.) if systemd at least rebooted system after some timeout, so grub can reboot to fallback kernel entry. Not only in this case, but in all cases that means systemd can't boot because of kernel.

2.) if systemd had some fallback mode for older kernels (disable some features, but still boot at least partially usable system. i'd rather have partially working systemd with fully loaded services, ssh, apache, openvz, etc, than completely unbootable system)

eg.: you can mkdir /sys/fs/cgroup before mounting tmpfs...

**Comment by poettering** [comment]
Nope, we cannot continue with /sys/fs/cgroup missing, and we cannot create the directory, as /sys is a virtual kernel file system, and we cannot create new dirs there from userspace...

It is widely documented that we don't support such old kernels, see README for example.

It's really hard to properly recognize old kernels, as we don#t even know in many cases which features are missing, and they might trigger problems later on, rather than immediately.

I am not convinced that automatically rebooting would be helpful... we'd just enter a reboot loop then...

**Comment by Harvie** [comment]
I understand your concerns. If you think that you cannot run systemd without cgroups, there's probably nothing to be done about it. Also you are true about reboot loop, however if i understand this problem and setup grub to reboot to different kernel after failure it can be really handy. What if this feature will be optional? It can be enabled when needed using kernel commandline from grub. Something like "rebootoncrash" flag, which you specify in bootloader if you need this behavior...

**Comment by poettering** [comment]
So we already have options to do a chvt and spawn a shell on crash, I figure we could add another option to reboot after a timeout... Will turn this issue into an RFE.

**Comment by Harvie** [comment]
Cool, i'm really satisfied with this kind of resolution. I didn't known about systemd.crash_shell=1.
BTW would be awesome if there was also way to interactively abort reboot in case i need to work with crash shell (if it's enabled alongside with crash reboot).
