### ISSUE TITLE
tmpfiles cannot create directory in unprivileged path

### ISSUE THREAD

**Issue by nbardiuk** [systemd/systemd#13052]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > NixOs

**Expected behaviour you didn't see**
 > `/home/nazarii/a/b` is created where `b` is owned by `nazarii`

**Unexpected behaviour you saw**
 > Detected unsafe path transition /home/nazarii → /home/nazarii/a during canonicalization of /home/nazarii/a.

**Steps to reproduce the problem**

Given config to create directory in some unprivileged scope (for example user folder)
```
cat /home/nazarii/temp.conf
d '/home/nazarii/a/b' 0750 nazarii users - -
```
Try to create the directory
```
sudo systemd-tmpfiles --create /home/nazarii/temp.conf
Detected unsafe path transition /home/nazarii → /home/nazarii/a during canonicalization of /home/nazarii/a.
```

The `b` folder is absent and folder `a` is owned by root
```
ls -la /home/nazarii/a
total 8
drwxr-xr-x  2 root    root  4096 Jul 13 17:34 .
drwx------ 48 nazarii users 4096 Jul 13 17:34 ..
```

**Comment by poettering** [comment]
This is a feature, not a bug: the system component makes sure not to pass through directories/symlinks owned by unprivileged users, so that it cannot be tricked into creating stuff privileged, where it shouldn't. Generally, having privileged code create stuff in areas controlled by unprivileged code is problematic, security-wise.

If you want to do what you are trying to do, consider doing so from the tmpfiles.d/ files of the user itself, which allows this without problems.
