### ISSUE TITLE
restarting systemd service on dependency failure

### ISSUE THREAD

**Issue by shayts7** [systemd/systemd#1312]
Hi,

According to this post: http://lists.freedesktop.org/archives/systemd-devel/2015-July/033513.html, starting from systemd 220, when service B requires service A, but fails due to lack of dependency, even after service A was restarted successfully, service B won't be restart.

I see the benefits of changing the behavior from RESTART to TRY_RESTART (if I intentionally stop service B I probably don't want service B to be restarted if service A is restarted), but on the other side in case of environmental failures on startup (network timeout, etc...) this behavior change is problematic, it means that a manual intervention need to be made to start service B.

**Comment by poettering** [comment]
So, what precisely are you proposing or asking for?

**Comment by shayts7** [comment]
The question is what the behavior change served? If it's only for the situation that someone stopped service B and wants to keep it like that - then I think the right approach would be switch to "TRY_RESTART" only in that case (maybe the one that stopped the service will have to say it explicitly).
After the service is back to live again it can be switched back to RESTART. 

In any case, I believe that the automatic flows are more important, and due to that RESTART should be the default option.

**Comment by binarybana** [comment]
I would request that if service B has a `Restart` policy in place, then systemd should do it's 'best' to keep that service running, including retrying it when upstream dependencies are restarted (based off of their restart policies).

I think this proposal (or something similar) is reasonable given the [brittle (but necessary) workarounds being recommended](http://unix.stackexchange.com/a/216254/32405) as a result of the currently implemented behavior.

**Comment by skozin** [comment]
I'm hitting this issue too; seemingly there is no non-hacky way to ensure that a dependent service is restarted after one of its dependencies fails and then successfully restarts.

I agree with @binarybana that systemd should do its best to keep the invariant that, at any given time, any service that satisfies the following conditions is either running, starting or restarting:
1. the service was started, either manually or as a dependency of some other unit;
2. the service was not manually stopped;
3. the service was not failed/exited, or restart policy allows restarting after exit/failure;
4. all dependencies of the service are satisfied.

This behavior, apart from its apparent usefulness, is the most intuitive one (imho), given the declarative nature of systemd units. Without it, one needs to resort to ugly workarounds, like the one linked from the previous comment, in almost any production server system.

**Comment by cgag** [comment]
We just ran into this here:https://github.com/coreos/coreos-kubernetes/issues/545.  I've been bitten by it in the past but was unable to figure out the cause until I saw this issue. 

In our case, the suggestion is to remove the dependency from the service, and rely on the fact that the dependency is socket activated.  This is a pretty ugly workaround, and the suggestions in the stackoverflow answer @binarybana linked don't seem much better. 

My understanding is that the behavior was changed to avoid starting a manually stopped service, but being unable to rely on systemd to ensure my services are running seems like a more significant problem than that.  

I agree with @shayts7 that `RESTART` should be restored as the default, and any special casing should be around manual stopping.  Poking at the internals it looks like systemd can differentiate between `UNIT_FAILED` and `UNIT_INACTIVE`. Instead of changing what's propagated, could we instead change how a `RESTART` message is handled in an inactive unit?

**Comment by nrvnrvn** [comment]
@poettering do I understand correctly that what you propose [here](https://lists.freedesktop.org/archives/systemd-devel/2015-July/033730.html) is to set up `Restart=always` or `Restart=on-failure` along with dependencies. Thus when the dependency is up again any dependent unit with defined restart policy will also be started?

**Comment by simonklb** [comment]
@nicorevin but this is currently not the case. After chatting with some folks on IRC it was explained to me that the Restart option is evaluated after Requires which makes the dependency fail before Restart is considered, resulting in the service staying dead.

I would really like to see this behavior changed. A service like flannel could basically kill an entire machine by a quick hiccup leaving all the dependent services dead, even though flannel comes back online.

Tested on systemd 229

**Comment by nrvnrvn** [comment]
@simonklb yeah it turns out that the only way to workaround this right now is to follow http://unix.stackexchange.com/a/216254
and replace `Requires=` with `Wants=` and `After=` with `ExecStartPre=systemctl is-active <dependecy>`...

**Comment by simonklb** [comment]
@nicorevin Thanks, that will have to do for now. `RestartSec` was also required (like the example from the StackExchange link), otherwise I got the `Start request repeated too quickly` error. Not sure what the limit is but 2 seconds seemed to be enough in my case.

Still hope to see a proper solution for this.

**Comment by marcovc** [comment]
@nicorevin I am wondering if that workaround leads to the same behavior. If I understood correctly, using the Wants directive implies that the unit will continue running while its dependency is failed. The ideal case for me is if systemd could restart the units that it stopped due to failed Requires dependencies, and thus never allowing a unit running with a failed dependency. But perhaps I misunderstood something...

**Comment by monder** [comment]
Any updates on this?
And a not for those who's trying the workaround:
`ExecStartPre=systemctl is-active ...` doesn't work.
Systemd requires full path e.g. `ExecStartPre=/usr/bin/systemctl is-active ...`

**Comment by arehmandev** [comment]
Has  anyone tried:
 Type=notify
 NotifyAccess=all
 ExecStart=/usr/bin/systemd-notify --ready --status="succussfully done task"

**Comment by MarcelMue** [comment]
Hello @poettering - could this issue be reconsidered? Or can we do something to get more traction on this?

It seems like people are running into this limitation quite frequently. All the workarounds presented here are rather clumsy to maintain in a larger codebase and a built in solution for this would be great.

**Comment by MarcelMue** [comment]
Or is `PartOf` is designed to fill this gap here?

**Comment by chrisd8088** [comment]
Out of interest, is the new `Upholds=`, introduced in commit 0bc488c99ab2ed3464237607e381f4d72cd321d5 of PR #19322, be something that would help here?

Specifically, suppose `b.service` is configured with `Wants=a.service` and `After=a.service` and `Restart=on-failure`.  Then `a.service` times out while starting so that `b.service` also then fails with `b.service/start failed with result 'dependency'`.  Next, `a.service` succeeds after being restarted, but `b.service` never starts because, apparently, dependency failures are not considered as triggers by the `Restart=on-failure` mode.

(This is exactly the situation reported in the already-linked Stack Exchange [question](https://unix.stackexchange.com/questions/213185/restarting-systemd-service-on-dependency-failure) for which one of the answer comments also links back to this issue.)

Having bumped into this long-standing issue, I'm wondering if the `Upholds=` directive would have an effect if it was specified such that `a.service` was configured with `Upholds=b.service`?  Would that cause `b.service` to be started when `a.service` finally comes up?

**Comment by maruina** [comment]
I can confirm I was able to use `Upholds=`.
I have `serviceB` depending on `serviceA` and I just added `Upholds=serviceB.service` in `serviceA` systemd unit

**Comment by mailinglists35** [comment]
Until a systemd release containing `Upholds=` will be picked up by major distros, is the suggestion in comment https://github.com/systemd/systemd/issues/1312#issuecomment-228874771 safe to use?

**Comment by gui-don** [comment]
I don’t think `Upholds=` is the correct solution.

A classic case: If unit **Service** `BindsTo` unit **Backend**: systemd is gonna make sure **Service** cannot be active if **Backend** is not active.

But, setting `Upholds` on unit **Backend** is yet another trick: if unit **Service** is stopped, the `Upheld` relationship is gonna restart **Service** automatically… oops. That’s not how the dependency was intended: my **Service** unit should be able to be stopped.

**Comment by YHNdnzj** [comment]
With `RestartMode=direct` (#27584) I think this can be closed?

**Comment by tmccombs** [comment]
@YHNdnzj I'm struggling to see how `RestartMode=direct`  solves this.  Maybe I'm misunderstanding how `RestartMode=direct` works. 

If service B never starts because service A failed, and it has a `Requires` dependency on A. Then adding `RestartMode=direct` to B doesn't help, because it will never receive a Restart, since it never started to begin with. And adding it to service A doesn't help either, because the service was  already in a Failed state, so  having it skip the transition to the failed state won't have any impact, and it doesn't change the fact that it triggers a TryRestart on service B instead of a full Restart.

**Comment by YHNdnzj** [comment]
> And adding it to service A doesn't help either, because the service was already in a Failed state

I can't follow. With `RestartMode=direct`, `A.service` should only enter failed state if unit start rate limit (i.e. `StartLimitIntervalSec=`) was triggered.

> and it doesn't change the fact that it triggers a TryRestart on service B instead of a full Restart

That's not what the original issue is about IIUC. If `A.service` is required by `B.service`, _manually_ restarting `A.service` after it fails should definitely not (re-)start `B.service`. But if you use `RestartMode=direct`, `A.service` will never enter failed/inactive state, so units depending on it should not fail in the first place.

**Comment by tmccombs** [comment]
> With RestartMode=direct, A.service should only enter failed state if unit start rate limit (i.e. StartLimitIntervalSec=) was triggered.

So with `RestartMode=direct`, what state is the service in while it is failing to start? If service A never successfully started, when B is triggered, will B be started once A does succeed? 

> manually restarting A.service after it fails should definitely not (re-)start B.service

It's been a long time since I started following this issue, and I don't remember the exact details, but I think that is what I wanted. IIRC, I had a service that failed to start because of a misconfiguration. And I think it either had Restart=no or had hit the limit of StartLimitIntervalSec. After fixing the configuration problem I restarted that service, but a dependent service, which I had previously tried to restart, didn't restart as I expected.  That is probably a fairly niche scenario though.

**Comment by rbeuque74** [comment]
Hello,

In my opinion, this issue is still relevant, is not fixed by `RestartMode=direct`.
Here a easy reproducer:

_service-A.service_
```
[Unit]
Description=service-A
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
ExecStart=/home/debian/service-A.sh
RestartMode=direct
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

_service-B.service_


```
[Unit]
Description=service-B
After=service-A.service
Wants=service-A.service
Requires=service-A.service

[Service]
ExecStart=/home/debian/service-B.sh
#ExecStartPre=/usr/bin/systemctl is-active gosystemd.service
RestartMode=direct
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
```

service-A is a `Type=Notify`, and service-B depends on service-A.
service-A is failing during its first start, never get active. service-B, just after the first fail of service-A is considered as failed as well, and is never restarted when service-A finally gets active.

Here is service-A.sh
```sh
#!/bin/bash
set -e

sleep 10
if [[ -e /home/debian/foo ]]; then
	systemd-notify --ready
	sleep 600
fi

touch /home/debian/foo
exit 1
```

Here is service-B.sh
```sh
#!/bin/bash
set -e

echo "Correctly started after service-A"
sleep 600
```

Here is a quick snapshot of what's happening on the system

> root@rbeuque-systemd:/home/debian# systemctl status service-A.service ; systemctl status service-B.service
> ● service-A.service - service-A
>      Loaded: loaded (/etc/systemd/system/service-A.service; enabled; preset: enabled)
>      Active: activating (start) since Tue 2024-06-04 18:15:32 UTC; 5s ago
>    Main PID: 438 (service-A.sh)
>       Tasks: 2 (limit: 8114)
>      Memory: 1.7M
>         CPU: 5ms
>      CGroup: /system.slice/service-A.service
>              ├─438 /bin/bash /home/debian/service-A.sh
>              └─442 sleep 10
> 
> Jun 04 18:15:32 rbeuque-systemd systemd[1]: Starting service-A.service - service-A...
> ○ service-B.service - service-B
>      Loaded: loaded (/etc/systemd/system/service-B.service; enabled; preset: enabled)
>      Active: inactive (dead)
>      
>   
>      
> root@rbeuque-systemd:/home/debian# systemctl status service-A.service ; systemctl status service-B.service
> ● service-A.service - service-A
>      Loaded: loaded (/etc/systemd/system/service-A.service; enabled; preset: enabled)
>      Active: activating (auto-restart) (Result: exit-code) since Tue 2024-06-04 18:15:42 UTC; 1s ago
>     Process: 438 ExecStart=/home/debian/service-A.sh (code=exited, status=1/FAILURE)
>    Main PID: 438 (code=exited, status=1/FAILURE)
>         CPU: 11ms
> 
> Jun 04 18:15:42 rbeuque-systemd systemd[1]: Failed to start service-A.service - service-A.
> ○ service-B.service - service-B
>      Loaded: loaded (/etc/systemd/system/service-B.service; enabled; preset: enabled)
>      Active: inactive (dead)
> 
> Jun 04 18:15:42 rbeuque-systemd systemd[1]: Dependency failed for service-B.service - service-B.
> Jun 04 18:15:42 rbeuque-systemd systemd[1]: service-B.service: Job service-B.service/start failed with result 'dependency'.
> 
> 
> 
> 
> root@rbeuque-systemd:/home/debian# systemctl status service-A.service ; systemctl status service-B.service
> ● service-A.service - service-A
>      Loaded: loaded (/etc/systemd/system/service-A.service; enabled; preset: enabled)
>      Active: activating (start) since Tue 2024-06-04 18:15:47 UTC; 1s ago
>    Main PID: 512 (service-A.sh)
>       Tasks: 2 (limit: 8114)
>      Memory: 552.0K
>         CPU: 9ms
>      CGroup: /system.slice/service-A.service
>              ├─512 /bin/bash /home/debian/service-A.sh
>              └─513 sleep 10
> 
> Jun 04 18:15:47 rbeuque-systemd systemd[1]: Starting service-A.service - service-A...
> ○ service-B.service - service-B
>      Loaded: loaded (/etc/systemd/system/service-B.service; enabled; preset: enabled)
>      Active: inactive (dead)
> 
> Jun 04 18:15:42 rbeuque-systemd systemd[1]: Dependency failed for service-B.service - service-B.
> Jun 04 18:15:42 rbeuque-systemd systemd[1]: service-B.service: Job service-B.service/start failed with result 'dependency'.
> 
> 
> 
> 
> root@rbeuque-systemd:/home/debian# systemctl status service-A.service ; systemctl status service-B.service
> ● service-A.service - service-A
>      Loaded: loaded (/etc/systemd/system/service-A.service; enabled; preset: enabled)
>      Active: active (running) since Tue 2024-06-04 18:15:57 UTC; 2s ago
>    Main PID: 512 (service-A.sh)
>       Tasks: 2 (limit: 8114)
>      Memory: 580.0K
>         CPU: 30ms
>      CGroup: /system.slice/service-A.service
>              ├─512 /bin/bash /home/debian/service-A.sh
>              └─537 sleep 600
> 
> Jun 04 18:15:47 rbeuque-systemd systemd[1]: Starting service-A.service - service-A...
> Jun 04 18:15:57 rbeuque-systemd systemd[1]: Started service-A.service - service-A.
> ○ service-B.service - service-B
>      Loaded: loaded (/etc/systemd/system/service-B.service; enabled; preset: enabled)
>      Active: inactive (dead)
> 
> Jun 04 18:15:42 rbeuque-systemd systemd[1]: Dependency failed for service-B.service - service-B.
> Jun 04 18:15:42 rbeuque-systemd systemd[1]: service-B.service: Job service-B.service/start failed with result 'dependency'.
> 

Workaround described here https://github.com/systemd/systemd/issues/1312#issuecomment-228874771 by @nrvnrvn is working, but I think this should not be the default behavior of systemd.
What do you think ?

**Comment by asteven** [comment]
Sorry for necro-bumping. I found this ticket while looking for a solution to this problem.
Posting our workaround here to maybe spare any future fellow sufferer some grief.

We use target unit's to synchronize the 'subsystems' and related services of our nodes (e.g. gpu.target, lustre.target, node.target, slurm.target, ...). So we mainly use this approach to restart target units and thereby all other units that are part of that target.

But it should/may also work for other units. Maybe also helps with #4468.
I'll leave that for someone else to test.

(edit: moved files to gist)
https://gist.github.com/asteven/efbfa94f968b2f704c643de27ed559ab

**Comment by rsyring** [comment]
Since it took me quite a bit of reading in this issue to figure out the correct incantation, I thought I'd try and add clarity:

My scenario is:

- I have a service (`tooling-updates.service`) that should only run when the GitHub API is up.  I have a separate service (`github-online.service`) that monitors GitHub's API and changes states accordingly.
- If the API is down, then `tooling-updates` should just wait to start.  It **should not fail** and use up it's retry counters if the API is down.
- If the API is up, and `tooling-updates` is failing for other reasons, it should retry a number of times and eventually quit when it reaches the retry limit.

`RestartMode=direct` does address this scenario but it needs to be put on the _upstream_ service (e.g. `github-online`).  `BindTo=` is used on the downstream service.

Example files are at: https://gist.github.com/rsyring/b479997e8c9cc7dc89b6d744c8b7ba5e

With this configuration, if `github-online` is not active (presumably b/c it's failed and restarting waiting for the GitHub API to come back up), `systemctl start tooling-updates` will hang waiting for `github-online` to reach it's active state.  If `RestartMode=direct` is not set on `github-online` then `tooling-updates.service` fails to start instead.

HTH.
