### ISSUE TITLE
A Way to Clear AmbientInherited Capabilities

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#13163]
If I set `AmbientCapabilities=` in a user manager, that gets propagated to all further processes spawned by that user manager. I would like a way to clear all ambient and inhertied capabilities in some of the spawned processes (maybe with a `AmbientCapabilities=clear` or some other keyword since setting `AmbientCapabilities=` does not clear if it was inherited).

**Comment by poettering** [comment]
makes sense

**Comment by keur** [comment]
Unless I'm misunderstanding this, you would want to able to set `AmbientCapabilities=CAP_CHOWN clear`, and the user manager has `CAP_CHOWN` but the processes it spawns have empty ambient and inheritable sets? The only way I could see this being possible is the spawned process execs into a privileged file or drops its own ambient set.

**Comment by topimiettinen** [comment]
It would be nice if the user manager could be more privileged in other aspects too (setting up mounts etc) in order to make all systemd features available also to user services. Now I use Firejail (I could also use Bubblewrap), which uses a setuid root helper, but I think I would prefer using systemd user manager if it was possible.
