### ISSUE TITLE
add ext4 to systemd-nspawn -D / -xb

### ISSUE THREAD

**Issue by alkorsan** [systemd/systemd#13192]
**Is your feature request related to a problem? Please describe.**
 systemd-nspawn gave me an error if I creat a temporary snapshot of the host itself with:
`systemd-nspawn -D / -xb`
after reading in internet, I found that nspawn need btrfs or xfs (I hope I m wrong), but:
-My Host offer Proxmox but they use ext4 filesystem. nspawn gave this error : 
`Failed to create snapshot /.#machine.c0405e5856555afb from /: Inappropriate ioctl for device`
-Proxmox offer xfs, but it gave me the same error as with ext4 (I tested it in my local pc)
-Proxmox do not offer btrfs :(

**Describe the solution you'd like**
I like that you add ext4, or a another way to use a temporal snapshot of the host
**Describe alternatives you've considered**
Only a Windows software called Sandboxie can do this. no Linux alternative found yet.
an offline solution that I m using is: copy all my host files to a folder , then` run systemd-nspawn -bD dir` ; the problem with this method, is that i have to copy all my host files every time i want a fresh snapshot of my host.

**Comment by johannbg** [comment]
xfs and ext4 filesystems dont have a built-in snapshot feature so it cant be added. You need ( and should ) use btrfs if you want or need snapshot capabilities. 

That  Sandboxie windows application is using somekind of lvm or device mapper trickery to do snapshot of xfs/ext4 since those filesystems dont have a built-in snapshot features.

On top of that does not proxmox use LXC for it's containers not systemd-nspawn?

**Comment by alkorsan** [comment]
thank you for confirming that.

> On top of that does not proxmox use LXC for it's containers not systemd-nspawn?

yes it uses LXC, but in the proxmox host itself I do not know a method to do what I described above (like with nspawn+btrfs or win sandboxie), to have a live snapshot of the host OS.

**Comment by poettering** [comment]
Please always fill in the supplied form when reporting and RFEs. If you don't provide the info the form requested it's much harder to help you.

Also, this appears to be a support question. The form should have made very clear that for help regarding using systemd you should contact the mailing list or so, but not file an issue. This makes things less frustrating for both you and us.

Also, all current nspawn version should work fine on ext4 too for `-x` mode. However, since ext4 doesn't support snapshotting or reflinking natively it falls back to a slow file copy operations, i.e. we have to copy byte-by-byte and thus invoking via "-x" will take a bit longer.
