### ISSUE TITLE
RFE: CPUAffinity=NUMA to simplify unification of CPU and Memory resource contraints

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#13248]
From #3097: thanks for adding [NUMAPolicy](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#NUMAPolicy=) and [NUMAMask](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#NUMAMask=).

A `CPUAffinity=NUMA` would be a useful extension to align `CPUAffinity` to the same node as memory.

**Is your feature request related to a problem? Please describe.**

The ability to set [NUMAMask](#12764) to constrain (per NUMAPolicy) memory allocated to a node usually has a concurrent thought to constrain CPUAffinity to the same NUMAMask nodes as the memory.

The determination of which CPUs are associated with the same memory nodes used in NUMAMask is left as a fragile exercise to the sysadmin leading to faults especially when one settings is changed without another.

**Describe the solution you'd like**

A setting of `CPUAffinity=NUMA` could concisely equate the memory and CPU constraints without the possibility of error.

**Describe alternatives you've considered**

Manually entering `CPUAffinity=` explicit list of CPUs. - Fragile.

`CPUAffinity=NUMA:{numanode1}, NUMA:{numanode1}`, less fragile, however duplication of the list of nodes in `NUMAMask` and not sure what practical use it is to constrain a service to number of CPUs on one node, but memory from two nodes. There might be a cause - if there is this could still be implemented later.

As a libnuma function the start of this is [numa_node_to_cpus](https://linux.die.net/man/3/numa_node_to_cpus), returning a set of cpus.

**Comment by mrc0mmand** [comment]
cc @msekletar

**Comment by msekletar** [comment]
@grooverdan makes a lot of sense. Thanks for filling the issue. I plan to work on this in the following weeks.

**Comment by poettering** [comment]
hmm, wouldn#t it make sense to just do this as default behaviour? i.e. if CPUAffinity= is not specified but NUMAMask= is, then automatically use the numa mask also as CPUAffinity=?

i.e. isn't it more common to set both to the same masks than to separate ones, and thus automatica propagation from numa mask to cpu affinity makes sense, and only if people don't want that they should configure CPUAffinity= explicitly?

that would not only be simpler semantically, but also in code.

**Comment by msekletar** [comment]
I don't know if it is necessarily a good idea to do this by default. 

Also on the code level, NUMAMask= and CPUAffinity= are too different objects. NUMAMask= lists NUMA nodes while CPUAffinity= list CPU indices.

**Comment by grooverdan** [comment]
A `CPUAffinity=NUMA` seems a consistent default given `NUMAMask=` is all nodes. I've no objection. As `NUMAMask` hasn't been in a release we're not introducing any incompatibility by changing this default though that may change quick with v243 being in RC.

Regarding two different objects they do have significant coupling at an architectural and practical level. The Linux concepts of NUMA seem much more focused on memory (was cpu binding concepts already implemented?) though the original concept of numa node is the tying of cpu and memory.

This RFE encompasses a pragmatism needed by sysadmins to isolate services at a hardware level.

**Comment by Werkov** [comment]
I find the use case invalid. If the user specifies NUMAMask=, it's the kernel scheduler's job to balance tasks so that they converge to the CPUs closest to the used memory (if you don't observe that despite CONFIG_NUMA_BALANCING, then it's possibly a bug).

Note that there can be  [CPU-less NUMA nodes](https://marc.info/?l=linux-cgroups&m=156458862929379) making the proposed semantics broken. Furthermore, interpretation of the special value would need to be done by the kernel, otherwise there would be no way to respond to CPU/memory hotplug events.

**Comment by msekletar** [comment]
> I find the use case invalid. If the user specifies `NUMAMask=`, it's the kernel scheduler's job to balance tasks so that they converge to the CPUs closest to the used memory (if you don't observe that despite `CONFIG_NUMA_BALANCING`, then it's possibly a bug).

Not sure what you find invalid on administrator's desire to make sure that service (workload) is running with the desired NUMA/CPUAffinity setting from the very beginning w/o relying on rather untransparent behavior on the kernel side. Moreover, if `CONFIG_NUMA_BALANCING` is disabled then your only option is to configure things manually (since `numad` doesn't seem to be a thing anymore).

**Comment by Werkov** [comment]
The proposed value would lead to false believe that the unit will always run on the specified NUMA nodes' CPUs. I see the point that it is a valid requirement.

However, if the administrator's goal is to confine the unit to a particular node, then neither of these settings would help as they can be overriden by the executing process. If the objective is to minimize access distance, then the kernel is the component that has full information (hotplugging, access patterns) and can facilitate that.

**Comment by shibumi** [comment]
@msekletar  do you have an example configuration for this? I would like to create tmpfs mounts based on the number of available NUMA nodes. 

for example, if I have 8 NUMA nodes, I would like to automatically set up tmpfs mounts with these options here:

```
rw,relatime,size=400G,mpol=prefer:<NUMA NODE>" "tmpfs<NODE ID>" "/FOO/tmpfs<NODE ID>/FOOBAR"
```

How would I do this with your change?

Here is an example of what I would like to generate automatically:

```
# systemctl cat /FOO/tmpfs0/BAR

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target

[Mount]
Where=/FOO/tmpfs0/BAR
What=tmpfsBAR0
Type=tmpfs
Options=rw,relatime,size=400G,mpol=prefer:0

# systemctl cat /FOO/tmpfs1/BAR

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target

[Mount]
Where=/FOO/tmpfs1/BAR
What=tmpfsBAR1
Type=tmpfs
Options=rw,relatime,size=400G,mpol=prefer:1
```

Also: If the numa node size changes on reboot.. there should be no mount for the invalid NUMA node ID, because this would lead to a system crash.

**Comment by msekletar** [comment]
@shibumi unfortunately I don't have any example for this specific use case. AFAICT, it is not possible to do it with the current functionality. This seems like a job for a generator which could determine number of numa nodes and generate corresponding mount units.
