### ISSUE TITLE
MurmurHash2 function causes conflict symbols

### ISSUE THREAD

**Issue by yang-g** [systemd/systemd#13295]
It seems `MurmurHash2` function can cause symbol conflict if other C modules happen to define the same function. https://github.com/protocolbuffers/upb used to have the exact same copy of the function, which caused issues when someone depends on both.

Upb was fixed in https://github.com/protocolbuffers/upb/pull/205. I think it would be better for systemd to do a similar fix in case other libraries include that function as is.

**Comment by poettering** [comment]
we don't export the symbol in any shared library, so why would anyone care? 

Is this a real issue or just a theoretical?

**Comment by yang-g** [comment]
This was reported by our user so it was real, though they likely have their own bazel BUILD file to build systemd.

**Comment by keszybz** [comment]
We make our symbols private. Using bazel to reimplement the build system sounds like a bad idea.

**Comment by poettering** [comment]
People can do with our source tree any way they like, but sorry, we won't support alternative build systems maintained downstream, that apparently aren't building things correctly, since we explicitly turn off any exporting of functions not explicitly listed for exporting. And the murmurhash stuff is certainly not exported at all.. Sorry.
