### ISSUE TITLE
[networkd] setting DNS for tun device via .network file stops openvpn setting IP

### ISSUE THREAD

**Issue by bits-fritz** [systemd/systemd#13398]
**systemd version the issue has been seen with** [1]
> 242.84, 241.93

**Used distribution**
 > archlinux

**want** to manually add vpn's dnsserver. Network configuration of openvpn client already works. 

**Expected behaviour you didn't see**
 > device tun0 is created and has IP from openvpn

**Unexpected behaviour you saw**
 > device tun0 is created and doesn't have IP from openvpn

**Steps to reproduce the problem**
**environment:**
- connection to an openvpn server *not providing dns via dhcp*, but pushing IP
  and route(s) for the vpn successfully, if not configured as described.
- systemd-resolved

**steps:**
- create file /etc/systemd/network/70-tun0.network [0]
- restart systemd-networkd.service
- restart systemd-resolved.service
- connect to openvpn server
- issue "ip a show dev tun0" to check the IP
- issue "ip r " to check the route(s)
- issue "resolvectl status tun0" to check the DNSserver ist set

**result**
- tunnel is created but no IP set for tun0
- vpn routes are not set due to missing IP
- (VPN's)DNS for tun0 is set

[0] file: 70-tun0.network
#========
[Match]
Name=tun0

[Network]
DNS=<your vpn's dns>
Domains=<your vpn's domain(s)>
#========
 [1]
**systemd version working**
> 240.95

**Comment by yuwata** [comment]
The .network file does not contain any IP address assignment. So, it is natural that the interface does not have any IP addresses. The vpn client must set IP addresses for the interface. Or, please enable `DHCP=` setting in the .network file.

BTW, please provide the debugging logs if `networkd` causes the issue. Otherwise, there is almost nothing we can do.

**Comment by bits-fritz** [comment]
Information appears to be too scarce. Updated description and hope it's more clear now.

The vpn client *does* set the IP address, but networkd changes things.
Didn't succeed in no way to put the log files in this form, so I've put them here:
.networkfile applied, tun device having IP address, failed:  https://bits-fritz.de/File/bug/openvpn-start_dot_networkfile_fail.log
very seldom it works as I would expect it with .networkfile applied. Luckily happend while testing ;o)): https://bits-fritz.de/File/bug/openvpn-start_dot_networkfile_success.log
This is how it always works with no .network file applied but no DNS: https://bits-fritz.de/File/bug/openvpn-start_no-dot_networkfile.log

It would be nice if someone with better skills downloads the files here.

**Comment by yuwata** [comment]
Thanks. There seems a race between openvpn and networkd. Please try to set `CriticalConnection=yes` in `[DHCP]` section even if you do not use DHCP client of networkd. That is,
```
[Match]
Name=tun0

[Network]
DNS=<your vpn's dns>
Domains=<your vpn's domain(s)>

[DHCP]
CriticalConnection=yes
```

Note that since v243 the setting `CriticalConnection=` has been renamed to `KeepConfiguration=` and moved to `[Network]` section. Please see NEWS and system.network(5) for the details.

**Comment by bits-fritz** [comment]
Am 27.08.19 um 01:28 schrieb Yu Watanabe:
[..]

> [DHCP]
> CriticalConnection=yes

That works..  Yay!! :o))

> Note that since v243 the setting `CriticalConnection=` has been renamed to `KeepConfiguration=` and moved to `[Network]` section. Please see NEWS and system.network(5) for the details.

Thanks for pointing.

BTW: Cool work, Guys! :o))
