### ISSUE TITLE
Poweroff/Reboot and Sleep-mode Issues

### ISSUE THREAD

**Issue by intervisionlord** [systemd/systemd#13413]
**systemd version the issue has been seen with**
> 241

**Used distribution**
 > Debian 10 (Buster)

**Used kernel**
 > 4.19.0.5

**Expected behaviour you didn't see**
 > Correct poweroff, reboot and sleep/hybernate

**Unexpected behaviour you saw**
 > At poweroff stuck at message "Reached target Poweroff"
at reboot stuck after turning display off
at sleep-mode stuck after turning display off

**Steps to reproduce the problem**
Try to reboot or power off system through GUI or through terminal (using "poweroff", "poweroff -f", "reboot" commands) or enter in sleep mode...

**Comment by poettering** [comment]
This is not actionable to us, and very likely not caused by systemd anyway (as the little information you provided suggest systemd actually did shutdown correctly, but then the final logic coming after that froze, which feels like an initrd or kernel issue.

Please contact your distro first about this, and provide logs to them. if they find an issue in systemd they'll then escalate this back to us. Thank you very much for understanding.
