### ISSUE TITLE
Per-service log rate limiting before forwarding to syslog

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#13425]
**Is your feature request related to a problem? Please describe.**

We use `ForwardToSyslog=` and would like to rate limit logs before they get forwarded. The current per-service level log rate limiting only applies to the journal and is processed after the raw message is sent to syslog.

**Describe the solution you'd like**

We could make use of the same `LogRateLimitBurst=/LogRateLimitInterval=` service properties and move the check before forwarding. Or we could introduce new properties specifically to rate limit the forwarded messages. A suppression message could be sent to let readers know systemd rate limiting was applied.

**Describe alternatives you've considered**

`imjournal` works for this use case because it reads the journal database, post rate limits. However, the [documentation](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html) states there is a performance penalty, as well as the risk of journal database corruption making it risky for production use cases.

There is rate limiting in syslog, but it is global, not per service.

**Comment by poettering** [comment]
I am not convinced this is desirable. ForwardToSyslog= is supposed to be as raw as possible, it's the direct connector, that bypasses all our magic otherwise. If we process stuff in between it kinda loses it's conceptual purpose.

Right now we support to ways to acquire the logged data as it happens: the "raw", "immediate", "naked" data via the ForwardToSyslog= stuff, and the "cooked", "augmented", "processed" data via the journal files. I am not sure we should blur the lines between the two. 

The "database corruption" stuff sounds like nonsense to me, seems to be a comment by the rsyslog author due to his dislike of systemd. I figure it's mostly a misunderstand how the journal works: if you turn off the system hard, while the journal is writing to journal files, as with any system this means the file is half written and data not yet synced is lost. That's entirely OK and expected though, not different from any other system writing to disk. We never "fix" this partially synced journal files though, but just start new ones, and instead expect journalctl while reading them to do the best to read what it can. i.e. it's better to fix "on-the-fly" while viewng the files, while potentially doing further damage when changing the files on disk.

Anyway, yes, reading the stuff from journal files is slower in many ways, in particular latency-wise, since we collect more data, and index by all. But I am not sure this matters at all. Overall-throughput wise things wouldn't be different anyway, as the forward-to-syslog stuff is in the same loop as the writing to journal file stuff.

hence, I am not convinced this is desirable at all. Having one low-level, unprocessed feed, and one high-level processed feed makes sense, but doing various degrees in between sounds unnecessarily complicating to me.

Do this reservations make sense to you?

**Comment by cstockton** [comment]
Hello, I wanted to provide a user opinion here. Unless this setting allowed disabling rate limiting all together- I would really like to avoid another rate limiting configuration value.

I've invested considerable time throughout the years since systemd was adopted in trying to figure out how to ensure my application logs are not dropped. My conclusion is that it's not possible. I understand it's a false conclusion of course, there must be a way to disable it I just can't seem to invest enough time and research to figure out the right configuration settings. It doesn't help each time I end up looking into the issue it's during an incident of some kind where seeing the log data my applications are producing is critical. 

Journald has the config items commented out- which specifics the same as disabling the setting:
```
#RateLimitInterval=30s
#RateLimitBurst=1000
```

But that still omits messages. I've also tried setting them to 0 with the same outcome after a daemon reload and restart of the service. I've also tried various settings in my unit files, as well as a LogRateLimitBurst I saw mentioned here and also in a git commit, among many other things with no success. I've tried tweaking configuration options in rsyslog as well- but the journal cfg values are set to 0 for rate limiting which seems to indicate they are disabled. In addition the messages in /var/log/messages have a journald tag, making me think rsyslog is not the cause.

I guess at the end of the day I understand the rationale for this feature. Systemd is written defensively, it prioritizes the greater good of the system it seems with all defaults. But in this case, the only reason these machines exist (thus only reason the systemd instances exist) is for the software I have written. I want said software to be treated like the most important thing on the server. Any output they produce, any CPU cycle they need, nothing is more critical than their operation. When there is a problem at 2am for a service I wrote many years ago it's .. frustrating to see:
```
journal: Suppressed 4 messages from /system.
journal: Suppressed 34 messages from /system.
journal: Suppressed 87 messages from /system.
journal: Suppressed 61 messages from /system.
journal: Suppressed 21 messages from /system.
journal: Suppressed 3931 messages from /system.
journal: Suppressed 4217 messages from /system.
journal: Suppressed 13 messages from /system.
journal: Suppressed 47 messages from /system.
journal: Suppressed 121 messages from /system.
journal: Suppressed 103 messages from /system.
journal: Suppressed 152 messages from /system.
journal: Suppressed 234 messages from /system.
journal: Suppressed 35 messages from /system.
journal: Suppressed 8 messages from /system.
journal: Suppressed 24 messages from /system.
journal: Suppressed 160 messages from /system.
journal: Suppressed 170 messages from /system.
journal: Suppressed 8 messages from /system.
journal: Suppressed 243 messages from /system.
journal: Suppressed 1 messages from /system.
journal: Suppressed 8 messages from /system.
journal: Suppressed 14 messages from /system.
journal: Suppressed 974 messages from /system.
journal: Suppressed 4537 messages from /system.
journal: Suppressed 20940 messages from /system.
journal: Suppressed 57622 messages from /system.
journal: Suppressed 20756 messages from /system.
```

Missing critical portions of stack traces or other debug information I carefully crafted in the software to help me in that very moment when I need it most. I'm left each time writing a wrapper shell script to send the log data to a file (in such circumstances I never have the time or patience to determine the correct way to add log redirection in the systemd config file like I would in a shell, thus opting to just add a .sh suffix to wherever the binary is). Over time I've slowly started to handle logging to a file myself within the app, e.g. no stdout/stderr. However this works against me in that the default log collectors that have been adopted in recent years that run on the machines don't pick up my logs by default, requiring custom configuration.

The point here being the I really don't want another way to tweak rate limiting. If anything- I want a way to say that without any uncertainty that my log data will be accepted. A single flag saying hey- this is the only reason systemd exists on this machine: to serve the business purposes provided by this systemd service: treat it as such, no truncation, suppression or compromises with the intent of the systems greater good - the system exists for this application.

Better would be bypassing journald all together, which probably exists somehow. I always am stuck googling for basic ways to troubleshoot with journalctl .. how to disable pager, horizontal scrolling.. disabling the truncation, syntax / flags for date ranges. Really all I want is `/var/log/<service-name>/messages.log` with auto log rotate so I can use grep. It's the way all my services were configured the years before the wide adoption of systemd. While systemd has done a lot of good I'm sure in other areas, my only interactions with it have been painful since it's introduction solely because I use it _only_ for diagnosis of issues through log inspection in a pinch. Distributed tracing and such helps, but there is additional granularity in logging that by sheer volume wouldn't fit through tracing ingest and sometimes I need it.

I guess consider this an experience report for systemd usage, maybe a position you've seen before and there is already solutions to my problems that I just haven't invested enough time to find. In any case I do appreciate the work systemd is doing and understand to many, many people it's a big operations win. As an app owner I feel it's very clean and simple to deploy and manage services as well. Come to think of it, logging really is my only complaint, it just so happens to be the only thing I do besides `systemctl restart service`. Thanks.

**Comment by poettering** [comment]
> Journald has the config items commented out- which specifics the same as disabling the setting:

No. commenting out just means "do not change from default"... The default enables the ratelimiter.

Also, please don#t hijack unrelated bug reports. That's very bad style. Thank you for understanding.

**Comment by cstockton** [comment]
> Journald has the config items commented out- which specifics the same as disabling the setting:

The very next line I wrote was:
>  I've also tried setting them to 0 with the same outcome after a daemon reload and restart of the service.

But thank you for the clarification.

> Also, please don#t hijack unrelated bug reports. That's very bad style. Thank you for understanding.

Every aspect of my post was about systemd  `log rate limiting`, this issue is about `log rate limiting` - in fact it contains it in the issue subject:
> Per-service `log rate limiting` before forwarding to syslog

Which is why it came up when I was googling how to "disable service log rate limiting". Given I am a user affected by this issue for maybe years I left my opinion as well as general experience report to help provide insight on how I formed it.

While I can't "understand" because I don't feel my comment was in bad style, I am able to identify that further communication here will be ineffective so I'll see myself out. Thanks for your work on the project.

**Comment by anitazha** [comment]
Well this is a very late response from me, but thanks for the details @poettering! Your reservations about processing logs before forwarding make a lot of sense.

I don't think we'll be pursuing `imjournal` as an option since journal namespacing is coming soon™ (plus internally we have other concerns with `imjournal`). I imagine that we can instead use journal namespaces to put "noisy" services into their own journal namespace and configure `ForwardToSyslog=false`.
