### ISSUE TITLE
logind: 243~rc2 break VT/tty switching on Fedora 31

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#13437]
On a fully up2date Fedora 31 system with systemd 243~rc2 VT/tty switching is broken.

To reproduce:

1. Take fully up2date default Fedora 31 workstation install (so using the GNOME desktop in Wayland mode)
2. Log in
3. Switch to VT6 by pressing CTRL + ALT + F6
4. Now try to switch to VT5 with either ALT + F6 or with ALT + cursor-left
5. Notice how the VT is now stuck and stays at VT6, switching back to the GNOME user session by pressing ALT+F2 is also broken

Downgrading systemd (and only systemd) to 242-6.git9d34e79.fc31 fixes things, after this switching to VT5 or back to the GNOME user session works normally.

This was originally reported against gnome-shell but after debugging this it appears to be a systemd bug, see here for the gnome-shell issue: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1549

**Comment by keszybz** [comment]
I guess we'll need to look into this before v243 is released. Hence might not make it today.

**Comment by AdamWill** [comment]
I think https://bugzilla.redhat.com/show_bug.cgi?id=1745554 is probably related to this too - at least my problem looks the same as @jwrdegoede 's, and I suspect Lukas' is likely related too.

**Comment by keszybz** [comment]
I couldn't figure out what is going on based on the logs, because they are full of various warnings and errors, and I don't know what is relevant. In addition, even with systemd-242, switching to a tty and back gnome-session doesn't work: Xwayland crashes and the session is aborted. So things were already broken with v242, and they are slightly more broken with v243-rc2.

Nevertheless, I settled on the following bisect strategy: is is possible to switch from gdm *login prompt* to tty and back? Bisecting on this gives the following answer:
3b92c086a8d5338e2164ffa0ae48b3d03d10cfb5 is the first bad commit
logind: make "self" and "auto" magic strings when operating on seats + sessions

**Comment by jwrdegoede** [comment]
@keszybz thank you for bisecting this.

As for your troubles with switching to / from a login session IIRC that did work for me, but switching to / from gdm is a perfectly fine reproduction strategy too.

**Comment by keszybz** [comment]
I made a PR that resolves the issue that I described above (https://github.com/systemd/systemd/issues/13437#issuecomment-526903983). I don't know if it fixes all the issues people are having, but I'm confident that it is a correct thing to do anyway. Testing would be appreciated.

**Comment by jwrdegoede** [comment]
> I made a PR that resolves the issue that I described above (#13437 (comment) <https://github.com/systemd/systemd/issues/13437#issuecomment-526903983>). I don't know if it fixes all the issues people are having, but I'm confident that it is a correct thing to do anyway. Testing would be appreciated.

I've done a local build of systemd-243~rc2-2.fc31.x86_64 (and subpkgs) with the patch from #13454 and I can confirm that this fixes this issue for me. Thank you for fixing this.
