### ISSUE TITLE
PAMName= and unprivileged pam_close_session()

### ISSUE THREAD

**Issue by dvdhrm** [systemd/systemd#1350]
Currently, the "(sd-pam)"-helper runs unprivileged as the user and has a comment that `pam_close_session()` does not need privileges. However, is that really true? For instance, `PAMName=login` fails this way, as pam_systemd.so needs privilegeds to run pam_close_session(). Sure, I can make `ReleaseSession()` on logind work for the uid of the session, but I wonder whether other PAM modules need privileges as well?

Any comment? Should I just make ReleaseSession() allow unprivileged access? Or should we just tell people to _not_ use PAMName= for anything non-trivial?

**Comment by poettering** [comment]
I figure https://bugs.freedesktop.org/show_bug.cgi?id=72759 is caused by this.

**Comment by DmitryKey** [comment]
Hi guys.

Not sure what's the status of this bug, but wanted to pass over some additional context. It is only a hypothesis, but looks like this issue might have been used recently as an exploit to get control of one of our ubuntu boxes. The following process was hanging around:

jetty     57894  57889  0 Mar23 ?        00:00:00 (sd-pam)

I cannot blame systemd directly on this, because the attacked managed to deploy a series of the scripts, binaries and passfiles to bruteforce ssh to remote IP addresses. Attacker was running 2000+ processes on the box to perform the action. Cleaning these up first time did not help.

Not sure if this helps you prioritize this issue, as it seems to have been utilized by a malicious hacker.

**Comment by aplsms** [comment]
reached this issue.

**Comment by jmoellers** [comment]
Setting
`SendSIGKILL=no`
in user@.service allowed pam_close_session to finish.
It's not the solution, but it may help getting forward.

**Comment by jmoellers** [comment]
A colleague just offered this solution if pam_mount.so is involved:
Add the following line just before the line containing the "session" pam_mount.so:
session [success=1 default=ignore] pam_succeed_if.so service = systemd-user
Franck pointed out that "The only (minor) downside I see is that any user services spawned by the systemd user instance won't be able to access $HOME."

**Comment by poettering** [comment]
Let's close this as duplicate of #8598 which is newer but more comprehensive.
