### ISSUE TITLE
"Failed to acquire RNG protocol: Not Found" on boot

### ISSUE THREAD

**Issue by MateusRodCosta** [systemd/systemd#13503]
**systemd version the issue has been seen with**
> 243.0-1

**Used distribution**
 > Arch Linux 64-bits

**Expected behaviour you didn't see**
 > No message between EFI OEM logo and plymouth

**Unexpected behaviour you saw**
 > A message appears on the top-left corner of the screen saying:

```
SHA256 validated
Failed to acquire RNG protocol: Not Found
``` 

**Steps to reproduce the problem**

1. Update systemd
1. Regenerate initramfs
1. Update systemd-boot version on ESP 
1. Reboot

Do note that: the initramfs uses systemd as its init and systemd-boot is the bootloader

The following is a picture of the message: 
![scaled_Screenshot_20190908-190339 png](https://user-images.githubusercontent.com/24463334/64495317-d8f9dd00-d26e-11e9-977d-672dd1650b86.jpg)

**Comment by shibumi** [comment]
Hi, what does `systemctl status systemd-boot-system-token.service` say?
And did you do `sudo bootctl random-seed` to initialize the random seed?

Normally you should be able to skip this message.

**Comment by kewlfft** [comment]
I have the same issue and the status (copied below) seems fine. Note that the error only appears when ```/boot/loader/random-seed``` exists, after deleting this file there is no issue at the next book. Then the 512 bytes random seed file is created again and the message appears at the following boot.

```
● systemd-boot-system-token.service - Store a System Token in an EFI Variable
   Loaded: loaded (/usr/lib/systemd/system/systemd-boot-system-token.service; static; vendor preset: disabled)
   Active: active (exited) since Mon 2019-09-09 07:42:34 BST; 9h ago
     Docs: man:systemd-boot-system-token.service(8)
 Main PID: 450 (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
   CGroup: /system.slice/systemd-boot-system-token.service

Sep 09 07:42:34 pc systemd[1]: Starting Store a System Token in an EFI Variable...
Sep 09 07:42:34 pc bootctl[450]: Random seed file /boot/loader/random-seed successfully written (512 bytes).
Sep 09 07:42:34 pc systemd[1]: Started Store a System Token in an EFI Variable.
```

**Comment by MateusRodCosta** [comment]
> Hi, what does `systemctl status systemd-boot-system-token.service` say?

```
[mateusrc@delart ~]$ systemctl status systemd-boot-system-token.service
● systemd-boot-system-token.service - Store a System Token in an EFI Variable
   Loaded: loaded (/usr/lib/systemd/system/systemd-boot-system-token.service; static; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Sun 2019-09-08 18:54:19 -03; 17h ago
     Docs: man:systemd-boot-system-token.service(8)

set 08 18:54:19 delart systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
set 08 18:54:19 delart systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
```

> And did you do `sudo bootctl random-seed` to initialize the random seed?

Yes, in fact I have the following on `bootctl` output:

```
Random Seed:
 Passed to OS: yes
 System Token: set
       Exists: yes
```

> Normally you should be able to skip this message.

Well, the message appears only for a second (or less) during the boot sequence. It would be nice if it didn't appear though, since I went through the trouble of setting the bgrt theme so the boot sequence looks nice.

**Comment by DougTy** [comment]
I've just started getting this ("SHA256 validated") on a fresh Arch install with 243.0 -- this was not previously present on 242

```
x@xxx:[~]:$ systemctl status systemd-boot-system-token.service
● systemd-boot-system-token.service - Store a System Token in an EFI Variable
   Loaded: loaded (/usr/lib/systemd/system/systemd-boot-system-token.service; static; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2019-09-09 22:08:22 MDT; 1min 47s ago
           ├─ ConditionPathExists=|!/sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f was not met
           └─ ConditionPathExists=|!/sys/firmware/efi/efivars/LoaderRandomSeed-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f was not met
     Docs: man:systemd-boot-system-token.service(8)

Sep 09 22:08:22 xxx systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
Sep 09 22:08:22 xxx systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
Sep 09 22:08:22 xxx systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
Sep 09 22:08:22 xxx systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
```

```
Random Seed:
 Passed to OS: yes
 System Token: set
       Exists: yes
```

`/sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f` and `/sys/firmware/efi/efivars/LoaderRandomSeed-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f` both exist.

I've never had to do anything with `systemd-boot-system-token.service` or run `bootctl random-seed` before, even on the exact same machine.

If it makes any difference, I'm on a 3700X, which I know had problems with systemd and rdrand previously -- could this be related? I'm on AGESA 1.0.0.3ABB, which should have resolved this.

**Comment by diabonas** [comment]
> Note it is possible to skip this message by adding the line `random-seed-mode off` in `/boot/loader/loader.conf`.

To clarify, it is possible to skip the "Failed to acquire RNG protocol" message in this way, "SHA256 validated" will be printed regardless of the `random-seed-mode` setting. This is because [`validate_sha256` is called by `process_random_seed` before checking the random seed mode](https://github.com/systemd/systemd/blob/4c858c6fd5d588b30d9851bb576520e74b041739/src/boot/efi/random-seed.c#L234-L239).

While it is debatable whether actual warnings/errors like "Failed to acquire RNG protocol" should be shown, "SHA256 validated" is a success message of the SHA-256 implementation self-test. I don't think showing this is necessary at all, given that it is to be expected that the implementation is correct and that we would get a "SHA256 failed validation." message in the unlikely event of an error. This seems more like a debug message put in during testing that has been forgotten to comment out.

**Comment by MateusRodCosta** [comment]
> While it is debatable whether actual warnings/errors like "Failed to acquire RNG protocol" should be shown, "SHA256 validated" is a success message of the SHA-256 implementation self-test. I don't think showing this is necessary at all, given that it is to be expected that the implementation is correct and that we would get a "SHA256 failed validation." message in the unlikely event of an error. This seems more like a debug message put in during testing that has been forgotten to comment out. #13510 removes the message.

I do have a question about the RNG protocol. [It seems to be available on UEFI 2.4](https://uefi.blogspot.com/2013/09/uefi-24-review-part-12-random-number.html), which is the UEFI version my bios supports according to bootctl:

```
System:
     Firmware: UEFI 2.40 (American Megatrends 5.11)
  Secure Boot: disabled
   Setup Mode: user
```

Is the problem that my firmware doesn't support the RNG protocol or that systemd-boot can't access? It seems to be the latter based on what the message says.

**Comment by poettering** [comment]
It's not a problem that the firmware doesn't support the RNG protocol. We use it if we can, but it's not a problem if we can't.

**Comment by RPigott** [comment]
If it is not a serious problem, would it be possible to allow for configuring sd-boot to not show the RNG protocol error message?

I would like sd-boot to make its best effort to seed the kernel rng, so I don't want to turn random-seed-mode off, but I'd like to be able to boot silently.

**Comment by poettering** [comment]
neither message should be visible during boot. The RNG one should just go. And the other one should go in optimized builds. The bug here is not that the msg is shown in non-optimized builds, it's really just that the production builds for some reason are non-optimized.

**Comment by shibumi** [comment]
> If it is not a serious problem, would it be possible to allow for configuring sd-boot to not show the RNG protocol error message?
> 
> I would like sd-boot to make its best effort to seed the kernel rng, so I don't want to turn random-seed-mode off, but I'd like to be able to boot silently.

Note: You can always just set `random-seed-mode off` in `/boot/loader/loader.conf`. This will disable the random-seed-mode and the message.

**Comment by brunnre8** [comment]
>>so I don't want to turn random-seed-mode off

>Note: You can always just set random-seed-mode off

...
You really need a cup of coffee

**Comment by nanoant** [comment]
I have the same problem, I have also `UEFI 2.40 (American Megatrends 5.11)` on my Lenovo PC and I have infamous `Failed to acquire RNG protocol: Not Found` despite `sudo bootctl random-seed` being run and the `random-seed` being present on the EFI partition.

@poettering So can you please confirm that if UEFI implementation does not provide RNG functionality then `Not found` error for missing `EFI_RNG_PROTOCOL_GUID` is expected, thus this should not pollute users screen, since there is **absolutely nothing** that user can do about this?

If so can you please correct this, as I believe you are the original author of this functionality introduced in July by e4dcf7aa528343fc81262d7043bb81f697941619. I know you are probably super-busy, but since you are the original author of this, and I think the actions should be taken from your side, instead of having others proposing PRs (such as @medhefgo) take later are not merged anyway.

Also, I have annoying `SHA256 validated`, which is simply completely useless. Therefore, again I ask you to remove it.

Take my apologies if I sound too harsh, I really respect your work, but I am bit disappointed that this could be fixed really quickly by you, but instead we this issue hanging there for over a month.

**Comment by lnicola** [comment]
@nanoant there is a pending PR to fix the annoying message, but it's currently failing CI.

**Comment by nanoant** [comment]
@lnicola That's right. But this PR #13510 was not linked anyhow with this issue. We only had above a link to isolated commit in @medhefgo fork. Hopefully my comment here creates a reference.

Nevertheless, what are we waiting for now? CI was apparently failing already on September 15, when PR was submitted. CI is failing because compiler started to believe that `err` variable may be uninitialized, even IMHO it should. This is probably the problem due to optimization now being turned on. Still the CI is complaining about `boot.c` that is not touched by the PR itself. And simple fix to have `err = RETURN_SUCCESS` just to satisfy the compiler. But let's continue there at PR #13510.

**Comment by s1ncla** [comment]
Hello!

It's a normal if systemctl status systemd-boot-system-token.service

```
● systemd-boot-system-token.service - Store a System Token in an EFI Variable
   Loaded: loaded (/usr/lib/systemd/system/systemd-boot-system-token.service; static; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2019-11-25 17:37:03 MSK; 18min ago
           ├─ ConditionPathExists=|!/sys/firmware/efi/efivars/LoaderSystemToken-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f was not met
           └─ ConditionPathExists=|!/sys/firmware/efi/efivars/LoaderRandomSeed-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f was not met
     Docs: man:systemd-boot-system-token.service(8)

ноя 25 17:37:03 evgarch systemd[1]: Condition check resulted in Store a System Token in an EFI Variable being skipped.
```
bootctl

`System:
     Firmware: UEFI 2.60 (American Megatrends 5.12)
  Secure Boot: disabled
   Setup Mode: user

Current Boot Loader:
      Product: systemd-boot 243.162-2-arch
     Features: ✓ Boot counting
               ✓ Menu timeout control
               ✓ One-shot menu timeout control
               ✓ Default entry control
               ✓ One-shot entry control
               ✓ Support for XBOOTLDR partition
               ✓ Support for passing random seed to OS
          ESP: /dev/disk/by-partuuid/baf32b09-e11f-4948-bd61-d44cd7bce64c
         File: └─/EFI/SYSTEMD/SYSTEMD-BOOTX64.EFI

Random Seed:
 Passed to OS: yes
 System Token: set
       Exists: yes

Available Boot Loaders on ESP:
          ESP: /boot (/dev/disk/by-partuuid/baf32b09-e11f-4948-bd61-d44cd7bce64c)
         File: └─/EFI/systemd/systemd-bootx64.efi (systemd-boot 243.162-2-arch)
         File: └─/EFI/BOOT/BOOTX64.EFI (systemd-boot 243.162-2-arch)
`
