### ISSUE TITLE
hwdb being regenerated when its already present

### ISSUE THREAD

**Issue by rpurdie** [systemd/systemd#13581]
We're using systemd 243 (also seen with 242) in the Yocto Project and are finding the hwdb is being regenerated at first boot despite us having already generated it at image creation time (as /etc/udev/hwdb.bin).

I don't understand the conditions in systemd-hwdb-update.service. It has:

ConditionPathExists=|!@udevlibexecdir@/hwdb.bin
ConditionPathExists=|/etc/udev/hwdb.bin
ConditionDirectoryNotEmpty=|/etc/udev/hwdb.d/

which means that if we already have an /etc/udev/hwdb.bin it will regenerate it. Some other distros (e.g. Fedora30) appear to ship such a file which is then just regenerated too.

I tried to come up with a better set of rules and wondered about:

ConditionPathExists=!/lib/udev/hwdb.bin
ConditionPathExists=!/etc/udev/hwdb.bin
ConditionPathExists=|!/lib/udev/hwdb.bin
ConditionPathExists=|!/etc/udev/hwdb.bin

which would only trigger if both hwdb.bin files were not present and which may be the desired behavior.

I appreciate a different answer may be requiring any pre-generated file should be in /lib/ however that would complicate things for us and it appears other distros have different expectations as well. 

Is any pre-existing file in /etc/ meant to be regenerated?

This is a particular issue for us as on slow emulated platforms/architectures we're hitting timeouts. We can change those but it would be better if we could use the file we're pre-generating.

**Comment by ahkok** [comment]
FWIW clearlinux removes `/usr/lib/systemd/system/systemd-hwdb-update.service` in favor or a post-software-update trigger.

**Comment by poettering** [comment]
The full Condition list is actually this:

```
ConditionNeedsUpdate=/etc
ConditionPathExists=|!@udevlibexecdir@/hwdb.bin
ConditionPathExists=|/etc/udev/hwdb.bin
ConditionDirectoryNotEmpty=|/etc/udev/hwdb.d/
```

Which means: run this when:

"(/etc is older than /usr) && ((@udevlibexecdir@/hwdb.bin is missing) || (/etc/udev/hwdb.bin exists) || (/etc/udev/hwdb.d/ is populated)"

The part left of && hence means: update me if /usr got updated but /etc is from an older version of /usr. And the part right of && means: if there's any reason to have the /etc version of the hwdb binary database (i.e. that it was used before, that it doesn't exist in /usr or that there are local hwdb files).

Or in other words, if you have a totally immutable image, then drop the hwdb from /etc, place it in @udevlibexecdir@ instead, and don't ship any rules files in /etc. Then the right-hand side of && should never trigger.

On Fedora (i.e. generally mutable installation) it's the job of the left-hand side to disable regeneration on later boots, as then /etc is no longer older than /usr...

Hope this makes sense?

That said, questions (in contrast to bug reports and feature requests) should better be discussed on the mailing list. This tracker is intended to be a bug and issue tracker really. Hence let's close this here, since afaics there's nothing wrong here, and no bug or feature request included.
