### ISSUE TITLE
reading a volatile sysfs attribute wih fread() is not safe

### ISSUE THREAD

**Issue by neilbrown** [systemd/systemd#13585]
udev uses fread() to read a sysfs attribute.  If it doesn't get the requested number of bytes on the first read (which it won't), it reads again - and normally gets zero bytes on second read.

However some sysfs attributes can change value spontaneously.  In such cases it is possible that udev will see one value and part of another.

Specifically the "md/array_state" attribute of md RAID arrays can change from "clear" to "inactive" while the initial "add" event is happening.
If fread() reads at this time, it can see "clear\nve\n", which is unexpected.

rules/99-systemd.rules.in contains a rule that checks for ATTR{md/array_state}=="|clear|inactive".
(mdadm has a udev rules file with a similar condition).
This rule will fail when udev sees "clear\nve\n", which is fairly clearly not the intention.

To fix the reading of sysfs attributes, we need to avoid using fread(), or possibly use some other technique such as read repeatedly until two consecutive results are the same.

I suspect that means changing the read_full_file() call in sd_device_get_sysattr_value() to something else - probably a new function.
Is there any other call to read_full_file() that might need to be changed?
Any guidance as to how the new function should behave, before I start writing it?

**Comment by fbuihuu** [comment]
Hi Neil,

> Is there any other call to read_full_file() that might need to be changed?

Most likely the same issue might happen when reading from /proc, see get_proc_field() for instance.

> Any guidance as to how the new function should behave, before I start writing it?

At a first glance, I would avoid using fread() in read_full_file() and adding a new flag which would specify that short read means EOF that could be used when reading from /sys or /proc.

**Comment by neilbrown** [comment]
Just by-the-way, the old udev_device_get_sysattr_value() prior to 
Commit f4ac4d1a82e2 ("libudev: device - replace by a thin wrapper around sd-device")
(in 2015) read the sysfs attribute correctly with read().
This commit changed that function to use sd_device_get_sysattr_value() which uses read_full_file which uses fread() which causes the problem.  Maybe we should just revert to the old code??

**Comment by poettering** [comment]
How large are your attributes that the first read done by fread is not sufficient?

**Comment by vcaputo** [comment]
@poettering That's not the issue, the problem is the fread() approach isn't considering a short read as EOF - it performs a subsequent read() looking for a 0 return for EOF.

This makes the sample non-atomic, so for cases like the mentioned RAID array changing from "clear" to "inactive", if the change coincides with the first short read of "clear\n", the second read instead of finding EOF immediately will read "ve\n", resuling in a "clear\nve\n" sample.

Attribute size is irrelevant, it's just a simple race condition.  The read code for sampling these virtual filesystems has to assume the entire sample will come in a single read call for atomicity, and treat short reads as including EOF.

**Comment by fbuihuu** [comment]
An attempt to fix this is waiting in https://github.com/systemd/systemd/pull/13819, PTAL.
