### ISSUE TITLE
Regression in crypttab parsing of keyfile with ":" character

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#13615]
**systemd version the issue has been seen with**
v243

**Used distribution**
Arch Linux

Prior to v243, a colon character was only meaningful in the argument to rd.luks.keyfile in order to specify a path to a file within a device. This behavior, however, was **not** applied to /etc/crypttab parsing of the third column. 50d2eba27b9bfc77ef6b40e5721713846815418b changed this, causing previously working setups to be broken. There doesn't appear to be any way to escape colon characters, rendering use of some udev paths (e.g. /dev/disk/by-id), potentially no longer working.

ref: https://bugs.archlinux.org/task/63880
cc @shinygold

**Comment by jaystrictor** [comment]
I originally reported this bug to the archlinux bug tracker. I have got a line in `/etc/crypttab` that reads roughly
```
luks-home UUID=04cc5203d1-737f-836f-7354-e342a1c6a89f /dev/disk/by-id/usb-Kingston_DataTraveler_2.0_985874B75CD64-0:0-part2 keyfile-offset=0,keyfile-size=512
```
As you can see the file `/dev/disk/by-id/usb-Kingston_DataTraveler_2.0_985874B75CD64-0:0-part2` has a colon (`:`) in its filname (as have many files inside `/dev/disk/by-path`).
I believe this setup used to work for at least the last 7 years. I could save the keyfile on an unmounted partition on my usb stick.

PR #13004 now breaks my setup and introduces this regression.
It has been over a month now, since this was reported here, so I would like to ask, how it is supposed to continue from here. @shinygold does not seem to be active anymore, so I would like to get feedback from the core team for how to approach this.

The easiest way would be to revert PR #13004. This would of course break the new feature, but would allow the 7 years old feature to be usable again.

**Comment by keszybz** [comment]
We screwed this one up badly. I don't see any good option for supporting the syntax introduced in 50d2eba. I think we should revert that part, and come up with a different way to specify the keydev argument. This will break users of the v243 keydev syntax, but hopefully that's not that many.

Other options?

**Comment by keszybz** [comment]
We could try to be smart. The keydev part supports the same syntax as the keyfile part, including /dev/something, LABEL=, UUID=, PARTUUID=, PARTLABEL=. So there is no fully unambiguous way to distinguish this, but should work OK in practice would be to check if the second part matches any of those syntaxes, and if not, assume it is part of the first name.

I'll whip up a patch for review.
