### ISSUE TITLE
SendRelease=yes but DHCP Release message is not sent

### ISSUE THREAD

**Issue by andreir0** [systemd/systemd#13625]
**systemd version the issue has been seen with**
> systemd 243

**Used distribution**
 > Clear Linux OS 31070

**Expected behaviour you didn't see**

new SendRelease option is set to yes but DHCP Release message is not sent when powering the system off with "shutdown now".

cat /etc/systemd/network/ens192.network
[Match]
Name=en*

[Network]
DHCP=yes

[DHCPv4]
UseDomains=yes
UseMTU=yes
SendRelease=yes

Sep 21 18:03:43 clr-1694bf38eaad4808923e50674710dabe systemd-networkd[261]: Bus bus-api-network: changing state RUNNING → CLOSING
Sep 21 18:03:43 clr-1694bf38eaad4808923e50674710dabe systemd-networkd[261]: Bus bus-api-network: changing state CLOSING → CLOSED
Sep 21 18:03:43 clr-1694bf38eaad4808923e50674710dabe systemd-networkd[261]: NDISC: Stopping IPv6 Router Solicitation client
Sep 21 18:03:43 clr-1694bf38eaad4808923e50674710dabe systemd-networkd[261]: DHCP CLIENT (0xb009e516): FREE
Sep 21 18:03:43 clr-1694bf38eaad4808923e50674710dabe systemd[1]: Stopping Network Service…
Sep 21 18:03:43 clr-1694bf38eaad4808923e50674710dabe systemd[1]: systemd-networkd.service: Succeeded.
Sep 21 18:03:43 clr-1694bf38eaad4808923e50674710dabe systemd[1]: Stopped Network Service.

[systemd-networkd-debug-log.txt](https://github.com/systemd/systemd/files/3640690/systemd-networkd-debug-log.txt)

**Comment by andreir0** [comment]
After poking a bit more at this I discovered that if I set SendRelease=yes _and_ KeepConfiguration=no, then DHCP Release message is sent as expected. 

If that's intended behavior, can you please update your man page to reflect the fact that SendRelease needs KeepConfiguration=no in order to work, since KeepConfiguration is set to "dhcp-on-stop" by default? Thanks!

**Comment by ssahani** [comment]
```KeepConfiguration=``` means you want to keep the configurations hence DHCP ip won't be released.  Yes we should update that.

**Comment by keszybz** [comment]
That is pretty ugly. If there is an setting that unconditionally requires another setting, then the standard solution is to update the code to make the first setting imply the second setting.

That said, I don't quite understand current defaults at all. I would expect the following semantics: the default is to drop dhcp configuration on systemd-networkd stop, and keep dhcp configuration on systemd-network restart. 95355a281c06c5970b7355c38b066910c3be4958 is a work-around that make the restart case better at the cost of making the stop case worse.

My proposal: let's add a mechanism so that systemd-networkd knows that it is being restarted or stopped, and make the default behaviour to keep configuration on restarts and drop on stop. And then, the default for SendRelease should be changed to true.

@yuwata?

**Comment by yuwata** [comment]
> My proposal: let's add a mechanism so that systemd-networkd knows that it is being restarted or stopped, 

How can we detect that?

**Comment by keszybz** [comment]
Right, we don't have a good mechanism right now.
One option that comes to mind is simply calling org.freedesktop.systemd1.Manager.ListJobs. If we find a job that matches  `org.freedesktop.systemd1.Manager.GetUnitByPID(getpid())`, and the job type is restart, we could behave differently.

Another approach would be to add a new unit setting: RestartKillSignal=, and let the unit specify a signal. This would be relatively simple and generic without requiring many changes. I'd lean towards this option.

**Comment by pakair** [comment]
systemd version 255 
added in /etc/systemd/networkd.conf 
[DHCPv4]
SendRelease=True

shutdown, restart laptop
syslog says, 2026-04-02T10:46:57.752588-07:00 toshi systemd-networkd[7398]: /etc/systemd/networkd.conf:30: Unknown key name 'SendRelease' in section 'DHCPv4', ignoring.
