### ISSUE TITLE
Kill all services and watchdog after kernel panic

### ISSUE THREAD

**Issue by Jookia** [systemd/systemd#13672]
On preemptive kernels since Linux v2.6.11 and earlier, userspace can continue to run after a kernel panic. [upstream bug](https://lore.kernel.org/linux-arm-kernel/BX1W47JXPMR8.58IYW53H6M5N@dragonstone/)

It would be good if systemd would detect a kernel panic and kill all running services and stop the system watchdog.

**Comment by poettering** [comment]
How would we detect a kernel panic? Scraping kmsg is not acceptable...

**Comment by Werkov** [comment]
This clearly should be tagged (and closed?) as not-our-bug. This must be fixed on the kernel side.

**Comment by poettering** [comment]
yeah, i have the suspicion too that the kernel should optionally just send PID 1 a SIGINT on oops. Both on systemd and on sysvinit that triggers a clean reboot. @Jookia can you maybe bring this up with the kernel people? I should be possible to convince them to add that... I mean, there's already panic= on the kernel cmdline that triggers a hard reboot, so adding another option for a clean reboot is not that far off... maybe combine a new option for doing a soft reboot with panic= even, so that first a soft/clean reboot is tried, and if it doesn't succeed a hard reboot is tried again.

But let's close this here, I think I agree with @Werkov, this is better done in kernel.
