### ISSUE TITLE
systemd recent versions use more time to load units

### ISSUE THREAD

**Issue by Shuangistan** [systemd/systemd#13778]
**systemd version the issue has been seen with**
> using v239 but also in all recent versions.

**Used distribution**
 > embedded

**Steps to reproduce the problem**
 > We found that the time used by "Loading units and determining initial transaction" is slow than before in the recent systemd (could be since v237).
 > We compared to a very old version, i.e. v225. We compared the performance with the same setting. It takes almost 3 times more in v239 than v225.

> On a small set variant, it is 80ms against 240ms.
> On a large set variant, it is 220ms against 810ms.
![225vs239](https://user-images.githubusercontent.com/12132949/66842194-20107780-ef6b-11e9-9a7d-f3e13b7a69fb.png)
> (The first one is with v225, loading uses 80ms, the bottom two are with v239, both loadings use ~240ms)

> We understand that current there are more features in systemd and it will take more times. But the values we got is not fully understandable. So we ask if there is something could be wrong in the system or it is expected behavior.
> Thanks.

**Comment by keszybz** [comment]
In systemd-243 the way unit files are located was changed. This could cause a slow-down (or not, I didn't really benchmark it). But if you're seeing a slowdown in systemd-239, then it is a different issue. There haven't been any significant changes in this area, but various small modifications are being done constantly, in particular because new features are being added.

If you are able to consistently show a slowdown, then it would help a lot if you could pin it down to specific commits. If there is something concrete to look at, we could try to speed things up. A general "it got slower between v237 and v243" is not very useful.

**Comment by Shuangistan** [comment]
Yes, we are looking into it. Just wanted to know if somebody has already a hint for that.

**Comment by Shuangistan** [comment]
@keszybz Please close this, we found out that the root is in Yocto. Sorry for this.
