### ISSUE TITLE
The future of the `test/TEST-??-*` integration testsuite

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#13802]
As @keszybz pointed out in https://github.com/systemd/systemd/pull/13722#issuecomment-543766255, and @evverx did that several times throughout various reports, the situation with the `TEST-??-*` *integration* tests is getting slightly out of hand, as many of those tests have a runtime of < 1s, yet we keep building & spinning a separate VMs for them, which is pretty expensive, and definitely not scalable. Some CI's already take several hours to complete, and it's definitely not going to get better without any action.

As proposed in the @keszybz's comment, it would make sense to merge certain tests together to minimize the overhead. Also, from my point of view, there are a few other things which should be taken into consideration:

1) Can we execute the tests *after* the system is fully booted up?
Right now the test's output is interleaved with the boot log, which is pretty ugly, unreadable, and thus hard to debug. Executing the tests *after* the boot sequence is finished should give us a slightly more readable output

2) *Prettify* the test logs
Right now all tests are written in plain bash and run with `set -x` to see what's being executed, which is not ideal and is usually missing some meaningful comments/output. Using some *consistent* logging mechanisms (either homebrewed, or from some framework, like [Beakerlib](https://github.com/beakerlib/beakerlib)) might be worth considering. (cc @msekletar)

Anyway, everything said here is up to discussion, as we definitely need to do something with the growing collection of tests, the main question is *how* it's going to look like.

**Comment by msekletar** [comment]
We don't have clearly defined set goals that we want to achieve with our test suite. But so far we mostly stayed on the assurance side. IOW, does component/feature X work as intended if we throw at it some input?

Secondly, I think that we want to achieve the above goal with as little work as possible and we also want the test suite to be as reliable as possible. With that in mind...

0) In my opinion, it doesn't make sense to merge test cases together as that goes directly against the reliability of the test suite. More thing that can go wrong in a single test case means a higher probability of flakes due to side effects.

1) I think this should be easily achievable if we change how we execute those tests. Currently, they are executed during the boot transaction. I think we should have the possibility to drive the test execution from the outside of the test VM. That would probably mean that we would need to have working ssh inside the test VM.

2) We should rewrite some test case using beakerlib and submit it as a PR. Then we could have a look at output from both test cases and asses whether the result is worth the effort.

**Comment by evverx** [comment]
> We don't have clearly defined set goals that we want to achieve with our test suite

Just out of curiosity, I'm wondering what group you're referring to as "we"? I'm pretty sure I knew what I was doing (and why) when I, for example, helped to make it possible to run the testsuite on Debian/Ubuntu, added support for ASan/UBsan (which has been extended by @mrc0mmand since then) and so on and so forth.

Before I start going through my comments to remember what I was talking about in other threads regarding what to do about those tests (and before setting hypothetical goals that don't seem to be achievable for large projects like systemd with the machine resources available), I'm wondering whether testing here in general is going to be prioritized. My understanding is that currently @mrc0mmand (alone) is trying to at least cover the basics (introducing some tidbits like the stuff extracting coredumps (which I think is great!) along the way) getting around the issues like the ones discussed in https://github.com/systemd/systemd/pull/13087#issuecomment-512092962 that usually don't bother anyone to be honest if testing gets as much attention as it deserves in places where people talk in terms of setting clearly defined goals.

**Comment by evverx** [comment]
FWIW I'm against using Beakerlib or any other framework that isn't used widely. It's important to make it easier for external contributors to add tests and judging by the issue we're discussing here TEST-* seems to be good enough in that regard. Beakerlib on the other hand is foreign to most contributors I think and judging by that part of CentOS CI where the test were run with Beakerlib and that vanished into thin air it's far from ideal.

**Comment by msekletar** [comment]
> Just out of curiosity, I'm wondering what group you're referring to as "we"? I'm pretty sure I knew what I was doing (and why) when I, for example, helped to make it possible to run the testsuite on Debian/Ubuntu, added support for ASan/UBsan (which has been extended by @mrc0mmand since then) and so on and so forth.

By "we" I meant upstream developers. First, I didn't mean it negatively and I didn't want to devalue any previous work that has been done.

Each of us has some outcome in mind while working on code or tests but AFAICT we never agreed on any goals for the test suite specifically.  For example, we could have goals (or at least shared expectation) in terms of what type of tests we expect to land alongside the code changes (functional/performance/...), how long the test suite should run (what wallclock duration is still acceptable?). 

I am not advocating for beakerlib. I've just mentioned it because it is one of the options. The main advantage, in my opinion, is a consistency of output that you get when using bearkerlib. And on the contrary, this issue is proof that how we do TEST-* doesn't quite cut it.

**Comment by evverx** [comment]
@msekletar I didn't mean to say I thought you meant it negatively. It looks like it was a miscommunication on my part. Sorry about that.

While I agree all the issues @mrc0mmand brought up here are important and should be addressed to avoid duct tape and popsicle sticks like the ones in https://github.com/systemd/systemd/pull/13771#issuecomment-548072348 (where the CI was called insane :-) (and rightfully so)) used to debug those tests, I think since those tests are heavy (because they aren't unit tests) they aren't exactly suitable for PRs (however hard they are optimized). As far as I can remember, I suggested running them via a cron job once a day (which is a more or less standard way of dealing with this kind of tests) but for it to be useful we'd ideally have to build an infrastructure that would open bugs here on GitHub, mark them flaky, close them when they are fixed and so on (similarly to what OSS-Fuzz does) but I'm not sure whether anyone is ready to pour this kind of engineering into testing :-) It's also not clear how to integrate this approach into Ubuntu CI. At this point it can't seem to be used in the "light" and "heavy" modes.

**Comment by poettering** [comment]
So here's a summary what we just discussed inside of RH:

1. we should work on making tests parallel installable in the same image, i.e. test.sh for TEST-33 should be called test-33.sh or so and testsuite.service testsuite-33.service and so on

2. Then we should build a single image that contains all deps and all tests and needs to be rebuild only once. 

3. Then either run all tests in parallel or pick one via kernel cmdline to run

the current dracut image building would then become one way to build the image, but we could also build the image with mkosi (or similar tool) to make tests more isolated from the host they run on.
