### ISSUE TITLE
nspawn: Regression in stdin handling

### ISSUE THREAD

**Issue by teg** [systemd/systemd#13822]
It appears de40a3037af944f6803375f2f5269cffc4247f56 introduced a regression in the way stdin is handled by default. The old behaviour seems to be possible to be restored by passing `--pipe`, but changing the default breaks existing users. See https://github.com/osbuild/osbuild/issues/152.

**systemd version the issue has been seen with**
> 142

**Used distribution**
 > Fedora 31 - Beta

**Expected behaviour you didn't see**
 > stdin is forwarded as before the change in question without  additional command-line arguments.

**Unexpected behaviour you saw**
 > stdin is closed.

**Comment by keszybz** [comment]
da40a30 wasn't supposed to change behaviour. The old behaviour is now conditionalized as ` if (arg_console_mode != CONSOLE_PIPE) ` and similar, but since `--pipe` is not the default, things should be the same as before. Maybe there's some bug in the conditionals. I'd like to figure out what exactly changed first.

> args = json.load(sys.stdin)

This code is problematic. A pseudo-tty is not exactly a pipe. So you *should* be running this with `--pipe`.

**Comment by keszybz** [comment]
https://github.com/systemd/systemd/commit/de40a3037af944f6803375f2f5269cffc4247f56?diff=split#diff-db6b16c9ade7e951e3bb793bec110098R3130
— I think your issue starts here. The conditional would have to be `if (arg_console_mode == ARG_CONSOLE_INTERACTIVE)` to keep unchanged behaviour.

The code was heavily modified in 3acc84ebd9aebe8cf1771b42644ebbfbecdfaa37, but this aspect didn't change. Currently, we always allocate /dev/console when `--pipe` is not used, and set up either bidirecational or uni-directional forwarding. This seems correct, and the code before de40a3 seems iffy.

@fbuihuu, @poettering ?

**Comment by keszybz** [comment]
Yeah, previous behaviour was fucked. When stdin or stdout was redirected, systemd-nspawn would not set the console up properly, leaking caller's tty into the container. So this worked for you by accident, but we can't have that.
