### ISSUE TITLE
hostnamectl spams the journal on every invokation

### ISSUE THREAD

**Issue by lahwaacz** [systemd/systemd#13921]
AFAIK, `hostnamectl` is intended to replace the `hostname` utility from GNU inetutils. However, there is a major drawback when people use e.g. `hostnamectl --static` in scripts to query the hostname: the journal is spammed with several lines on _every_ invokation of `hostnamectl`. This is especially noticeable with scripts which run in a loop or cron or timer services:
```
dbus-daemon[594]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.14307' (uid=1000 pid=148166 comm="hostnamectl --static ")
systemd[1]: Starting Hostname Service...
dbus-daemon[594]: [system] Successfully activated service 'org.freedesktop.hostname1'
systemd[1]: Started Hostname Service.
```

Expected behaviour: command-line tools which are intended for scripting should not spam the journal _at all_, or at least only the first time they are invoked.

Related issue: https://github.com/chef/ohai/issues/962

**Comment by poettering** [comment]
hostnamectl does something different from the hostname utility, really. It changes /etc/hostname primarily, which the the hostname utility from GNU doesn't do (they overlap though admittedly). It does this in a way so that unprivileged clients can request a hostname change safely, after authentication via polkit. 

the tool doesn't spam anything. It talks to a small service that is auto-started and executes the actual operation. Starting services results in logging on systemd, and this is not going to change, sorry...

I am not sure why you bother with hostnamectl though, if all you want to know is the static hostname, if one is configured. just do `cat /etc/hostname`, it's equivalent, and doesn't involve service activation or anything.

Hence, I don' think we'll change this, and there's no need to use hostnamectl really, if you want to call it quickly and just for reading. hence, let's close this. I hope this makes some sense?
