### ISSUE TITLE
[xorg][systemd] Failed to start X: systemd-logind Operation not permitted 

### ISSUE THREAD

**Issue by telychko** [systemd/systemd#13943]
**systemd 243.78**

**Arch linux**

Bug appears randomly. Probability 50%.

X server bail out with the message:

```
(EE) systemd-logind: failed to take device /dev/dri/card0: Operation not permitted
...
Unable to retrieve master
(EE)
Fatal server error:
(EE) AddScreen/ScreenInit failed for driver 0
```

Steps to reproduce:
1. Run startx.

**After `systemctl restart systemd-logind.service` X server starts OK.**

[logs.zip](https://github.com/systemd/systemd/files/3807964/logs.zip)

**Comment by poettering** [comment]
what session do you start this from?

**Comment by poettering** [comment]
if you do "echo drm > /etc/modules-loadd/test.conf" and reboot, does the issue go away?

(my educated guess is that the `DeviceAllow=char-drm rw` line in logind.service doesn't work if the DRM subsystem is not loaded yet)

**Comment by n0amso1** [comment]
I'm experiencing this problem too. Though, much less than 50% (I tried rebooting my system 5 times and only once I encountered this issue). 
> what session do you start this from? (i.e. ssh? console?)

I run `startx` as part of my `.xinitrc` script, this runs automatically after logging in on `tty1`, I hope this answers your question.

> if you do "echo drm > /etc/modules-loadd/test.conf" and reboot, does the issue go away?
> 
> (my educated guess is that the `DeviceAllow=char-drm rw` line in logind.service doesn't work if the DRM subsystem is not loaded yet)

I have just tried this command, but because I had a hard time reproducing it, I can't be certain whether this fixes it. I will keep you posted anyway.

**Comment by loqs** [comment]
> if you do "echo drm > /etc/modules-loadd/test.conf" and reboot, does the issue go away?

[1] Reports that it did go away.  This is a user executing sway from the console.
From the same report removing all DeviceAllow entries from the service achieved the same result.
As the service file already has
```
ExecStartPre=-/sbin/modprobe -abq drm
```
why is that not enough?
[1]: https://bbs.archlinux.org/viewtopic.php?id=250684

**Comment by telychko** [comment]
> what session do you start this from? (i.e. ssh? console?)

I started X from console. Console device is tty7. The commands I started X: `exec startxfce4` . `startx` produces the same result.
Sorry for such delay of reply.

**Comment by telychko** [comment]
> if you do "echo drm > /etc/modules-loadd/test.conf" and reboot, does the issue go away?
> 
> (my educated guess is that the `DeviceAllow=char-drm rw` line in logind.service doesn't work if the DRM subsystem is not loaded yet)

I have workaround via early kernel mode setting: [Early KMS](https://wiki.archlinux.org/index.php/kernel_mode_setting#Early_KMS_start)
This way issue does not appear.

**Comment by nkr0** [comment]
Hi,

I'm using debian testing and I've the exact same issue with [243](https://packages.debian.org/bullseye/systemd).

> if you do "echo drm > /etc/modules-loadd/test.conf" and reboot, does the issue go away?

This is the only thing that works consistently. Early KMS was already set properly, I think. Different from arch wiki,
```
/etc/modprobe.d/i915-kms.conf
options i915 modeset=1
```
But that's probably just because it's Debian.

P.S. Not sure if this info is useful. But, booting into rescue mode is always successful.

**Comment by nkr0** [comment]
Actually, I've some more possibly useful information. Other than rescue mode, there are a couple more things that worked.
1) Replacing `gdm3` with `lightdm`. I spent too much time thinking the issue was with `gdm3` because of this.
2) Has the issue on a `haswell` machine, but no issues at all on a `skylake` machine. Both running nearly identical Debian installation.

**Comment by croyleje** [comment]
I am having the same error but have found if I reinstall dbus it will also start with out the error until the next time I reboot

**Comment by Oppen** [comment]
I can consistently reproduce both this and a related issue with iwd causing panics with >50% probability.
Early loading of relevant modules reliably fixes it.
Is there anything useful for me to do here?

**Comment by poettering** [comment]
#14504 should be fixing this properly.

**Comment by xosevp** [comment]
Quick hack to bypass the error.

Add to initram the X drivers via dracut:
In /etc/dracut.conf.d/drm-i915.conf put: add_drivers+="drm i915" 
dracut -f -v
init 6
