### ISSUE TITLE
systemd-udevd.service breaks unmounting etc on shutdown

### ISSUE THREAD

**Issue by Vogtinator** [systemd/systemd#13947]
**systemd version the issue has been seen with**
v243

**Used distribution**
openSUSE Tumbleweed

**Expected behaviour you didn't see**
```
[  OK  ] Unmounted /etc.
etc.mount: Succeeded.
```

**Unexpected behaviour you saw**
```
etc.mount: Mount process exited, code=exited, status=32/n/a
[FAILED] Failed unmounting /etc.
```

**Steps to reproduce the problem**
Have an entry for `/etc` in `/etc/fstab`.

openSUSE with read-only-root-fs has `/etc/` mounted as `overlayfs`, which fails to unmount reproducably on shutdown. `lsof` showed that `/etc/udev/hwdb.bin` was held open by `systemd-udevd` and indeed, adding `RequiresMountsFor` to `systemd-udevd.service` fixed shutdown reproducibly.

**Comment by poettering** [comment]
I am sorry, but making /etc a regular mount point that is unmounted at shutdown is not supported. /etc (much like /usr) must be available from the time the initrd transitions to the host till the very end when we transition back to the initrd. 

i.e. if they want to do this, they should set DefaultDependencies=no for etc.mount (either via drop-in or by just shipping a .mount unit rather than an fstab for it anyway), and they should set this up from the initrd and never touch it. 

Anyway, we are expressly not going to add deps on etc.mount or so, it's one of the dirs we expect to be there from start to end.

(that said, this suse thing appears to me this is a less careful reimplementation of what systemd.volatile=overlay already does?)

since this is misconfiguration in suse, and breaks our expectations on /etc's lifecycle let's close this.
