### ISSUE TITLE
machinectl shell always starts /bin/sh instead of the user's default shell

### ISSUE THREAD

**Issue by Celti** [systemd/systemd#1395]
e.g., even if root's default shell as listed in /etc/passwd is /bin/zsh or /bin/bash, /bin/sh is invoked. This causes assumptions regarding the operating environment (bashrc/zshrc/etc.) within machinectl shell to fail.

**Comment by julian-klode** [comment]
That one is very important. Debian uses dash for /bin/sh which is not really suitable for interactive use.

**Comment by poettering** [comment]
Implementing this is quite hard actually, as we need to pick the shell from the container, not the host. Now, one option might be to write this via ExecStart=$SHELL, and rely on en var expansion here... But we currently explicitly forbid such expansion for the first ExecStart= parameter, because we want to be able to read the selinux label of the binary of a service when socket activation is used, at the time of the creation of the socket to label it properly. And if the binary is not specified explicitly, but as env var (and env vars are only resolved at execution time, not before) , then we cannot read the selinux label off that. However, may it is time to lift this restriction for all cases where socket activation is not actually used, like in this case.

Hence, to fix this properly, here's what I propose as a proper fix:
1. allow env var expansion for the first ExecStart= argument
2. when starting a socket unit, refuse starting if its specific service uses an env var as first argument We thus make the check much tighter and instead of prohibiting env var expansion for the first arg of ExecStart= for all cases, just for the socket activation cases.
3. Then, change machined to actually use ExecStart=$SHELL instead of ExecStart=/bin/sh for the service it starts.

Now, to complicate this further: in order to avoid NSS checks for root (since NSS is problematic from PID 1) we currently hardcode /bin/sh as shell for root, and I figure we want to lift this hardcoding for this specific case, too, since most folks probably use "machinectl shell" for the root user...

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by GongT** [comment]
`machinectl shell fedora /bin/bash --login -i`:
* `echo $SHELL` = /bin/sh
* `cat /proc/$$/cmdline ` = /bin/bash

`machinectl shell --setenv=SHELL=/bin/bash DesktopEnvironment /bin/bash --login -i`
* `echo $SHELL` = /bin/bash
* `cat /proc/$$/cmdline ` = /bin/bash


why there is a SHELL env variable exists?

**Comment by mbiebl** [comment]
Since the perfect is the enemy of the good, I decided to prep a patch in #7682 which makes the default shell spawned by "machinectl shell" configurable on a distro/system wide basis. PTAL

**Comment by keszybz** [comment]
What about a yet another approach: add a helper binary that we'd invoke in the container, which would exec the shell for us? Something like `/usr/lib/systemd/systemd-start-shell UID`. I think the shell command already requires systemd inside of the container, so this wouldn't change much.

**Comment by bl33pbl0p** [comment]
Instead of changing the logic to support variable expansion in the first argument to ExecStart= for everything but socket activated units (which would be nice to have ofcourse), how about just using ExecStart=/usr/bin/env $SHELL until then?

**Comment by wsw70** [comment]
I found this entry when searching for exactly this problem. 

So what is the status of the resolution? I am not sure, reading the thread, what should be done to have the shell from `/etc/passwd` used by default?

**Comment by spectrum70** [comment]
Hi, if you want for a silly need, i would to be in zsh after systemd-nspawn as user. 
As far as i understand this is nothing that should be fixed/added.
My workaround has been to add a .profile with "/bin/zsh" inside and works perfect.
