### ISSUE TITLE
Thomas Krenn Awards 2020

### ISSUE THREAD

**Issue by Chaostheorie** [systemd/systemd#13979]
Next year Thomas Krenn will make an award for open source projects with hardware prices up to 10k €
Maybe systemd is as an open-source project qualified for this and could use some of the hardware. Just thought of systemd as the first project who should be rewarded with such an award. 

Would be nice if any of the the core members consider participating. Becuase systemd would be rewarded for the the hard work of the contributors and some new hardware for the project seems to be a nice idea.

Link: https://www.thomas-krenn.com/en/company/about-us/thomas-krenn-award.html

**Comment by poettering** [comment]
So, here's the thing, we actually received some substantial donations already, and we haven't been able to use them on much yet. As I understand the Thomas Krenn awares would be payed out in hardware, which is something we don't really need right now. I mean, hw for testing stuff or running build/test infrastructure is always great, but so far we are short on people, not on hw, so acquiring even more hw is probably not the most helpful to us since there's noone to actually use it for testing/building stuff.

Thank you for thinking about us for this, but I don't think it makes sense for us to submit a proposal here for now. Hope that makes sense?

@keszybz opinion?

**Comment by poettering** [comment]
Ok, let's close this now. Thank you anyway for point us to this, @Chaostheorie !
