### ISSUE TITLE
systemd-networkd.service and systemd-sysctl.service ordering

### ISSUE THREAD

**Issue by legrostdg** [systemd/systemd#14022]
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Debian sid

**Expected behaviour you didn't see**
> systemd-sysctl.service is restarted after systemd-networkd.service

**Unexpected behaviour you saw**
 > systemd-sysctl.service is retarted before systemd-networkd.service

**Steps to reproduce the problem**

 I'm trying to mitigate #13991 (I want to use an other DHCPv6 client than systemd-networkd, and accept RA with this client) I tried to set `net.ipv6.conf.wan0.accept_ra=2` in my sysctl.conf, and created a `/etc/systemd/system/systemd-sysctl.service.d/20-sysctl-restart-after-networkd.conf` with

    [Unit]
    PartOf=systemd-networkd.service

but systemd-sysctl.service appears to be restarted before systemd-networkd.service. I tried to add `After=systemd-networkd.service` to this file, but then I got an error message:

    Failed to restart systemd-networkd.service: Transaction order is cyclic. See system logs for details.

**Comment by poettering** [comment]
sorry, but this is not supported: either an interface is managed by networkd or it isn't. half managing it is not supported, and i don#t think we should make that work.

networkd is ordered after sysctl so that everything is initialized and then networkd just inherits from that.

Long story short: if you want to use something else than networkd for an iface, then do that, but make sure that networkd then doesn't manage it.
