### ISSUE TITLE
systemd-fstab-generator issue with glusterfs and overlayfs

### ISSUE THREAD

**Issue by gbaudot** [systemd/systemd#14067]
Hi.

Setting up a fstab with one glusterfs mount point and overlay(s) with upper_dir pointing to a sub dir of this gluster mount leads to possible wrong mount ordering (overlay mount point failing because glusterfs is not yet mounted, in other terms, systemd-fstab-generator ignores dependency).
Notes:
 - trying with net_dev option for overlay did not help
 - a simple workaround is to set noauto,x-systemd.automount options for overlay(s)
 - feel free to ask for more information if required

++
Gi)

**Comment by poettering** [comment]
First of all, always fill in the supplied form, we have it for a reason, for example, to get information about which version of systemd you are using.

We can't possibly determine the additional per-fs deps of all possible file systems in the world, otherwise we'd drown in a huge rules database.

Hence, for stuff like this, just use the x-systemd.after= mount option in fstab, which allows you to order things manually against additional units or mount points.

**Comment by gbaudot** [comment]
Hi
Thanks for the quick reply.
Regarding the supplied form... well, I did not really notice, I just submitted an issue, sorry.
Anyway, thanks for the x-systemd.after suggestion: I did not know about it and it looks much better to me than the noauto,x-systemd.automount combination (in other terms, yes, this is what I required... and missed).
Regards.

++
Gi)
