### ISSUE TITLE
Please reconsider priority of nss_myhostname in the documentation

### ISSUE THREAD

**Issue by patrakov** [systemd/systemd#14073]
The nss-myhostname currently says three important things:

1. Various software relies on an always-resolvable local hostname.
2. It is recommended to place "myhostname" last in the nsswitch.conf' "hosts:" line to make sure that this mapping is only used as fallback, and that any DNS or /etc/hosts based mapping takes precedence.
3. With nss-myhostname enabled, changing /etc/hosts is unnecessary, and on many systems, the file becomes entirely optional.

I.e., it recommends this line:

hosts:          files mymachines resolve [!UNAVAIL=return] dns myhostname

I would question the second recommendation on the following basis:

1. Various software relies on the local host name being resolvable immediately. Therefore, "fallback after DNS" is not what is wanted.
2. The nss-resolve manual page recommends placing the "resolve" module (which, according to the documentation, but not in reality, duplicates the functionality of nss-myhostname) before "dns", thus making the "DNS should override this" argument self-inconsistent.

**Describe the solution you'd like**

Recommend this line:

hosts:          files myhostname mymachines resolve [!UNAVAIL=return] dns

Well, re-reading my suggestion, I would even say that the documented placement of mymachines before myhostname may be a security issue: what if a machine is created with the same hostname as the host?

**Comment by refi64** [comment]
FWIW I believe Arch does something similar, and I've also taken to putting
myhostname before dns in my Debian containers to avoid having to manually
edit /etc/hosts.

**Comment by keszybz** [comment]
I agree. I always put myhostname first on my machines, because I want "localhost" to **always** resolve to my local machine, and I don't fully trust all possible dns servers I'll interact with. (Actually, I was once on a network with a bunch of Fedora machines all names "localhost" and the fancy proprietary dhcp server / local dns forwarder would happily register "localhost" as a name and then resolve it to one of the machines. Hilarity ensued.)

**Comment by poettering** [comment]
So, the only reason we put it at the end right now is that I expect people to be pissed if we put it first, since they won't see the name of their host not show up in `getent hosts $(hostname)` or `hostname --fqdn` anymore, and I expect people use that.

That said, I actually think in a perfect world we'd put it first.

Hence this is not so much a question I think about what is more correct and what is less correct, but more about "Are we willing to piss everyone off who expects that `hostname --fqdn` does anything reasonably sensible?"

I used to answer that question with "no". Have things changed on this?

**Comment by patrakov** [comment]
I'd say we should put it second, exactly because of folks who expect `hostname --fqdn` to return what they have configured in `/etc/hosts`. OTOH, I think that it is insane for `hostname --fqdn` to contact DNS, because of the delay.

**Comment by poettering** [comment]
it was always my assumption that "hostname --fqdn" was precisely about contacting DNS...

**Comment by SueHACK88** [comment]
Someone here who can help me please?
I'm (I was... Now I have to learn about it more than I need) a bloody dummy in android things, my device is spyed out from someone, how can I get that shit away from my fone?
![Screenshot_20200126_175054_com huawei android projectmenu](https://user-images.githubusercontent.com/60318386/73138929-554b5c00-4068-11ea-88c8-4103acac2fd9.jpg)

It's a Netflix ore Facebook partnersetup, frp bypass? Belongs Easteregg to this too? I think so. 

Please help me, Im nearly to suicide, a girl in my life (one of 2 possibilitys) spys my fone and I have this problem since years... 4 ore 5 y... I have bought more than 6 smartfones in this time changed the phone number two times and changed every password more than a 100times! 
So... All of my security access information like passwords and fingerprint and faceID are saved on a server, must be Huawei, Facebook ore GDrive. 
I don't know... 
And after that ( if someone can help me...) 
Please give me a tip, which smartfone do I have to bye that I'm save from this?

That works with every device if the person get some minutes alone with it to put a SD card in it ore scan a code, am I wrong?

**Comment by SueHACK88** [comment]
![Screenshot_20200126_185345_com android settings](https://user-images.githubusercontent.com/60318386/73139327-4e731800-406d-11ea-8948-94b07625418d.jpg)

This is what the system says about its hard and software. My safety patch is newer than the oldest official Huawei update and Huawei stopped support for my device a very short time after I got it, can't belive that, 350€... For some weeks support...
Can I get it safe myself with apps ore patches?

Thx for helping... 😢

**Comment by Cassandrameeleus** [comment]
I am a very proud 3rd degree solitary Wiccan for 19 years now and I am very devoted to my practice/craft! Pasiphaê (aka:Cassandra _my name) was the FIRST Crete moon Goddess followed by Selenɛ(№ ① вiтс) & Hekatɛ̀**_

**Comment by SueHACK88** [comment]
So... can you help me please?

**Comment by mbiebl** [comment]
For some reason, this issue was attracting off-topic comments, so locking it down.

**Comment by keszybz** [comment]
@mbiebl it's just spam. There's a "block user" thingy in the "..." menu. That also marks all the comments as spam and hides them by default.

**Comment by charlesferguson85** [comment]
Did u fix hack

ci

**Comment by PratJawn** [comment]
I recommend Pat's line 19

**Comment by poettering** [comment]
Fixed by ce266330fc3bd6767451ac3400336cd9acebe9c1 I guess.
