### ISSUE TITLE
After installing systemd-journal-remote.rpm, journal change its directory from /run/log/journal to /var/log/journal.

### ISSUE THREAD

**Issue by fayeinseu** [systemd/systemd#14124]
**systemd version the issue has been seen with**
> systemd 239
   fedora 29

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > …
the installation of systemd-journal-remote.rpm will not create the /var/log/journal directory 

**Unexpected behaviour you saw**
 > the directory /run/log/journal has been removed ,and  /var/log/journal is created

**Steps to reproduce the problem**
yum install systemd-journal-remote

**Comment by boucman** [comment]
That's a pretty old version of systemd, and this is not a bug... or at least not a but in systemd

When /var/log/journal exists, systemd will move it's logs there instead of the volatile /run directory. If you don't want to have your logs there, just remove the directory and journald will move things back at next boot

the fact that the directory is probably due to the RPM package, so please report that part to your upstream distro

**Comment by keszybz** [comment]
Yeah, that's a problem with the way systemd is packaged in Fedora. Please open a bug in bugzilla.
