### ISSUE TITLE
/root part of the base filesystem?

### ISSUE THREAD

**Issue by haraldh** [systemd/systemd#1414]
Why do we assume that "/root" is part of the base file system?

Apparently people give root another home in passwd.

https://github.com/systemd/systemd/blob/3a3701f03360f9a292dcab31fda1f6e0e0629c64/src/shared/base-filesystem.c#L42

**Comment by haraldh** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1266997

**Comment by johannbg** [comment]
@haraldh ? 

The home directory for the root should reside on the same partition as the operating system resides on so that you can still login as root without issues. 

Supporting anything else is idiotic.

**Comment by poettering** [comment]
While I would pick different words as @johannbg I do agree to some level. /root should be on the root file system, and we actually hardcode that all over the place, in order to avoid NSS lookups from PID 1. See this for example:

https://github.com/systemd/systemd/blob/master/src/basic/util.c#L3331

So, having the root file system anywhere but in /root, is explicitly not supported in systemd.

That said, I am open to adding a patch that makes failure to create /root, in the base-filesystem code non-fatal.

**Comment by poettering** [comment]
There's a fix now in #1418, please verify that it works, and merge.
