### ISSUE TITLE
Support multiple [Timer] sections in systemd.timer

### ISSUE THREAD

**Issue by cryobry** [systemd/systemd#14242]
I am attempting to run multiple rsnapshot backup services using a single systemd timer.

```
# /home/user/.config/systemd/user/rsnapshot@.service
[Unit]
Description=rsnapshot (%I) backup
After=run-media-bryan-usb\x2dhomebackup.mount
Requires=run-media-bryan-usb\x2dhomebackup.mount
ConditionACPower=true

[Service]
Type=oneshot
Nice=19
IOSchedulingClass=idle
PIDFile=%h/.config/systemd/user/rsnapshot.pid
ExecStart=/usr/bin/rsnapshot -c %h/.config/systemd/user/rsnapshot.conf %I
```

I have been using multiple systemd.timer unit files to call rsnapshot with the appropriate backup interval. Example:

```
$ systemctl --user cat rsnapshot-hourly.timer 
# /home/user/.config/systemd/user/rsnapshot-hourly.timer
[Unit]
Description=rsnapshot hourly backup

[Timer]
# Run hourly
OnCalendar=*-*-* *:00:00
Persistent=true
Unit=rsnapshot@hourly.service

[Install]
WantedBy=timers.target
$ systemctl --user cat rsnapshot-daily.timer 
# /home/user/.config/systemd/user/rsnapshot-daily.timer
[Unit]
Description=rsnapshot daily backup

[Timer]
# 05:30 is the clock time when to start it
OnCalendar=05:30
Persistent=true
Unit=rsnapshot@daily.service

[Install]
WantedBy=timers.target
```

I would like the ability to combine all of these timer unit files into a single timer file with multiple [Timer] sections:

```
[Unit]
Description=rsnapshot scheduled backups

[Timer]
# Run hourly
OnCalendar=*-*-* *:00:00
Persistent=true
Unit=rsnapshot@hourly.service

[Timer]
# Run daily
OnCalendar=02:30
Persistent=true
Unit=rsnapshot@daily.service

[Timer]
# Run weekly
OnCalendar=Monday  *-*-* 04:30:00
Persistent=true
Unit=rsnapshot@weekly.service

[Install]
WantedBy=timers.target
```

This functionality would make it possible to start and enable an entire backup schema within a single .timer file, which would simplify service installation and admin.

What would be nice is if systemd had an optional way to prevent OnCalendar= conflicts by preventing multiple [Timer] sections within a single .timer file from activating simultaneously. In other words, a way to prevent OnCalendar=hourly and OnCalendar=daily and OnCalendar=weekly from all starting at the same time (or on reboot with Persistent=true). 

In the case of rsnapshot this can be mitigated somewhat by a pid file, but I think it makes more sense to handle that logic at the service manager level so that we can see why some processes may be delayed using systemctl and to also support programs without pid files.

**Comment by poettering** [comment]
This has been requested before, but it means we the dependencies between units would not be normalized anymore. Suddenly we'd have a single unit that sometimes activates one unit and other times another unit, and so on. Right now it's very simpe: one unit activates one other units. It might do so for a number of conditions, but it will always activate the same unit. This makes ordering very clear, and looking at deps.

If you want to group stuff, use a target unit that's what they exist for. i.e. With "Wants=" from the target to the timers and "PartOf=" the other direction you can start the timer units in one step very easily and naturally.

So, I am very sure we shouldn't dissolve the clear relationships here. THere's nothing wrong with having multiple unit files and grouping them via target units. It tends to be more powerful, since that way you could even bind the activated service units to the target, and such.

Hope this makes sense?

**Comment by carterpeel** [comment]
> This has been requested before, but it means we the dependencies between units would not be normalized anymore. Suddenly we'd have a single unit that sometimes activates one unit and other times another unit, and so on. Right now it's very simpe: one unit activates one other units. It might do so for a number of conditions, but it will always activate the same unit. This makes ordering very clear, and looking at deps.
> 
> If you want to group stuff, use a target unit that's what they exist for. i.e. With "Wants=" from the target to the timers and "PartOf=" the other direction you can start the timer units in one step very easily and naturally.
> 
> So, I am very sure we shouldn't dissolve the clear relationships here. THere's nothing wrong with having multiple unit files and grouping them via target units. It tends to be more powerful, since that way you could even bind the activated service units to the target, and such.
> 
> Hope this makes sense?

Thanks for the clarification. I was researching this myself and now it makes sense why that would cause catastrophic problems in a lot of existing configurations.
