### ISSUE TITLE
nspawn does not add capabilities with --private-users=pick

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#14383]
When container as `/usr/bin/systemd-nspawn --private-users=pick --boot --machine=frkbturn` application cannot bind to privileged ports, e.g. `python3 -m http.server` fails with `Permission denied`.
If add capabilities with `--capability=CAP_NET_BIND_SERVICE --capability=CAP_NET_ADMIN` application still canNOT bind to privileged ports.
When running without `--private-users=pick` (`systemd-nspawn --boot --machine=frkbturn`), privileged ports are bindable, `python3 -m http.server` does not fail and works correctly.

Is it expected behaviour? Is it documented anywhere? 

```
# systemd --version
systemd 242 (242)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```
Ubuntu 19.10

**Comment by poettering** [comment]
We changed this quite a bit in more recent systemd versions. Please upgrade to 244 first.  If there's still an issue there, please reopen.

**Comment by marthellius** [comment]
I  can confirm that this issue is still present when running systemd 245:

`systemd 245 (245.5-2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
`

When launching a Debian container with ssh installed in it, the ssh daemon can't bind port 22. 

`systemd-nspawn --quiet --boot --link-journal=try-guest --private-users=pick --private-users-chown --settings=override --machine=buster --capability=CAP_NET_RAW,CAP_NET_ADMIN,CAP_NET_BIND_SERVICE `

`May 20 20:00:23 localhost systemd[1]: Starting OpenBSD Secure Shell server...
May 20 20:00:23 localhost sshd[85]: error: Bind to port 22 on 0.0.0.0 failed: Permission denied.
May 20 20:00:23 localhost sshd[85]: error: Bind to port 22 on :: failed: Permission denied.
May 20 20:00:23 localhost sshd[85]: fatal: Cannot bind any address.
May 20 20:00:23 localhost systemd[1]: ssh.service: Main process exited, code=exited, status=255/EXCEPTION`

Besides, it's not possible to ping any address from inside the container (even having explicitly added the CAP_NET_RAW capability):

`ping 127.0.0.1
ping: socket: Operation not permitted`

When using Private networking (VirtualEthernet=yes), everything works fine: daemons can bind to privileged ports, and you can ping any address. This behaviour is expected and the man page is quite clear about it: 
> If this option is specified, the CAP_NET_ADMIN capability will be added to the set of capabilities the container retains

However, when using Host networking (VirtualEthernet=no) and --private-users=pick, some network operations remain limited even when granting the required capabilities.
