### ISSUE TITLE
Setting to ensure only one instance of a template can be active at the same time.

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#14391]
**Is your feature request related to a problem? Please describe.**

I have a scenario where I want to run several instances of a template at boot but because of how the program works, only a single instance can be active at any one moment. Currently, booting up the system fails because systemd tries to start the instances of the template in parallel. 

**Describe the solution you'd like**

A way to automatically order all instances of a service template so only one of them is running at the same time. I don't care about the exact ordering, I just want to ensure only one instance is active at any one time. When starting another instance, it should be queued to start after all the previously started instances have finished.

**Describe alternatives you've considered**

I'm not sure if it's somehow already possible to implement this using existing features. The problem is that because the instances are dynamically enabled, I don't know which instances are enabled so I can't hard-code the ordering in the service file.

**Comment by poettering** [comment]
Not sure I follow? Templating/Instances are a mechanism to allow multiple parallel, concurrent executions of something. Now you say you don't want that. So why do you use templating/instances?

**Comment by DaanDeMeyer** [comment]
I might not be using templates as intended then. When running tests, I do some configuration on a container that has to be reapplied when the container reboots. Because the configuration always invokes a program with only different parameters, I use a systemd oneshot template service and use the template parameter to point to an environment file containing the parameters to pass to the program.

Simplified service (<program>@.service):

```
[Service]
Type=oneshot
EnvironmentFile=/etc/<program>/%i.env
ExecStart=/usr/bin/<program> -w ${ENV1} -s ${ENV2} ${ENV3}

[Install]
WantedBy=multi-user.target
```

I then enable multiple instances of this template to apply any required dynamic configuration when the container reboots. This seemed like a simple solution to allow me to reuse the service file while still allowing invoking the program with different parameters. The problem is that only one instance of the program can be active at any one time, which led me to make this issue as systemd starts all instances in parallel.

I guess I'm using templates more to reuse service file logic rather than explicitly running things concurrently. Generating separate services for each of the required invocations of the program doesn't seem like an ideal solution to me either.

I'm currently trying to get around the issue by having a single service which invokes a bash script that invokes the program multiple times with different parameters, but this won't have the same semantics when setting timeouts or similar in the service file as those would apply to the entire bash script with all invocations instead of to a single invocation when using a templated service.

I think `Conflicts=<program>@.service` (didn't actually test) comes close to what I need, except I don't want systemd to stop any running instances, but instead queue this instance to run after the other instances finished running.

**Comment by poettering** [comment]
Yeah, template units are not designed for this purpose.

**Comment by DaanDeMeyer** [comment]
Let's close this as it doesn't fit the template use case.
