### ISSUE TITLE
systemd won't start sysvinit jobs that were previously started and stopped by themselves

### ISSUE THREAD

**Issue by alkisg** [systemd/systemd#1445]
I'll explain it better with an example.
`# service nbd-server start`
=> the service is started
`# killall nbd-server`
=> the process is killed
`# service nbd-server start`
=> **wrong behavior**: systemd does no attempt to start the service
`# /etc/init.d/nbd-server start`
=> **correct behavior**: the service is started

If I put this inside the sysvinit service file:
`# pidfile: /var/run/nbd-server.pid`
...then the problem goes away.

Maybe RemainAfterExit shouldn't be set for sysvinit services, or systemd could improve its logic on detecting the pid file of processes?

**Comment by arvidjaar** [comment]
I am afraid I miss the actual problem description.

> systemd could improve its logic on detecting the pid file of processes

There is no detection logic I am aware of. Either unit definition specifies PID file or not. For leagcy scripts this translates to pidfile line or to drop-in.

**Comment by alkisg** [comment]
Sorry my markdown was completely messed up, I fixed it a bit.

systemd does see that there are no processes left in that cgroup, but it still considers the nbd-server service as active. I think that it should notice that it's dead and not list it as active...

**Comment by arvidjaar** [comment]
> systemd does see that there are no processes left in that cgroup, but it still considers the nbd-server service as active

sysvinit scripts were used for both one-time activity (similar to oneshot in systemd) as well as for starting long-running daemons. You have no practical way to know what it does. Current heuristic is that if pidfile is present, it should be daemon, otherwise it is oneshot (and so no processes need to be left after starting). To be able to execute stop action it needs to remain active in this case.

Can you suggest how systemd can improve detection what script does?

**Comment by poettering** [comment]
Yeah, this is a known issue: we cannot know whether a sysv script is supposed to be one where there's a process running after "start", and where the process exiting means the sysv service is gone, or whether it is one of the kind that just sets something up at boot, and then maybe resets it at shutdown again, but has nothing running in between. (example for the latter is stuff like alsa volume saving scripts and suchlike)

I updated the incompatibilities list on this now:

https://wiki.freedesktop.org/www/Software/systemd/Incompatibilities/

But I don't see anything we could do about this, SysV is simply not expressive enough to allow us to be smarter on this. Hence closing. Sorry.

**Comment by fbuihuu** [comment]
@poettering in the case of "proces running after start", I'm not sure: that should be the only case where the cgroup is not empty after the control PID has exited no ?

Also it is a bit strange that specifying the pidfile in the service helps because if I'm not mistaken systemd has some logics to guess the main PID of a service if pidfile has not been specified. And for nbd-server it should be pretty easy to make a guess since nbd-server seems to only use one process in the background.

**Comment by alkisg** [comment]
> Can you suggest how systemd can improve detection what script does?

I'm no expert in this, so while I can suggest a couple of things, feel free to ignore them if they're not suitable:
1. For sysvinit services, `systemctl start service` could always run the `/etc/init.d/service` script even if it the service is marked as active.
2. Or it could just use pidfile=/var/run/$service.pid as the default, at least in Debian/Ubuntu all the pid files are in that path. Also note that I don't see any sysvinit script with `# pidfile:`, they usually have PIDFILE=xxx right after the header comments. Maybe that could be used as well?
3. If none of the above are acceptable upstream, maybe distributions can work around the issue, e.g. Debian's start-stop-daemon could tell systemd that this is a service? ...so that they don't have to change all the other packages that still use sysvinit scripts. If this is an accepted solution from the systemd side, I could start by filing a bug in Debian for this.

Thank you.

**Comment by poettering** [comment]
> @poettering in the case of "proces running after start", I'm not sure: that should be the only case where the cgroup is not empty after the control PID has exited no ?

There are cases where a sysv script does something in the bg and then exits, and that's OK and should not be considered a service going down. And there are cases where something is in the bg, and exits, and it should be considered a service going down. I don't see how we could automtically distinguish these two cases...

> Also it is a bit strange that specifying the pidfile in the service helps because if I'm not mistaken systemd has some logics to guess the main PID of a service if pidfile has not been specified. And for nbd-server it should be pretty easy to make a guess since nbd-server seems to only use one process in the background.

The guessing only works if we know that there _will_ _be_ a main process of the daemon. i.e. it only works in systemd's own unit types where you configured with Type= and RemainAfterExit= what kind of service you have. But the guessing is not useful if we don't know what kind of service it is.

Or in other words. GuessPID=yes is useful only to figure _which_ process is the main process, it's not useful to determine if there's a "main" process in the first place.

**Comment by poettering** [comment]
> I'm no expert in this, so while I can suggest a couple of things, feel free to ignore them if they're not suitable:
> 1. For sysvinit services, systemctl start service could always run the /etc/init.d/service script even if it the service is marked as active.

Nah, I am pretty sure we should only allow starting of stopped services, and stopping of started services... This is particularly essential in order to guarantee automatic clean-up and correct shutdown.

> 1. Or it could just use pidfile=/var/run/$service.pid as the default, at least in Debian/Ubuntu all the pid files are in that path. Also note that I don't see any sysvinit script with # pidfile:, they usually have PIDFILE=xxx right after the header comments. Maybe that could be used as well?

I am pretty sure that most services don't actually put their pid in precisely /run/$service.pid, as many have their own subdirs in /run...

`# pidfile:` is a Red Hat thing, as mentioned. Debian unfortunately has no equivalent.

The PIDFILE= thing I am pretty sure is already too much of a heuristic I think.

> 1. If none of the above are acceptable upstream, maybe distributions can work around the issue, e.g. Debian's start-stop-daemon could tell systemd that this is a service? ...so that they don't have to change all the other packages that still use sysvinit scripts. If this is an accepted solution from the systemd side, I could start by filing a bug in Debian for this.

I think best would be to simply write a proper unit file for the services where this turns out to be a problem. In the long run everybody will be much happier with such a solution.
