### ISSUE TITLE
systemctl mask incorrectly handling non .service units

### ISSUE THREAD

**Issue by agowa** [systemd/systemd#14461]
**systemd version the issue has been seen with**
> systemd 244 (244.1-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > masking the 80-iwd.link unit.

**Unexpected behaviour you saw**
 > 80-iwd.link.service being masked (even though that service does not exist)

**Steps to reproduce the problem**
1. Install iwd
2. Run `systemctl mask 80-iwd.link`

(Same error can be observed using `systemctl cat`, `systemctl unmask` and `systemctl edit`)

**Comment by poettering** [comment]
That's a misunderstanding. systemd itself only manages *units*. systemd units have the types listed here:

https://www.freedesktop.org/software/systemd/man/systemd.html#Concepts

i.e. ".link" is not a unit type managed by systemd (and thus by systemctl), but something managed by systemd-udevd instead (and thus not my systemctl). See https://www.freedesktop.org/software/systemd/man/systemd.link.html

Since this is all already documented in detail, let's close.
