### ISSUE TITLE
journald presumably crashes system

### ISSUE THREAD

**Issue by adrium** [systemd/systemd#14478]
**systemd version the issue has been seen with**

```
$ systemd --version
systemd 242 (+suse.77.geaa7b8b148)
+PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

I believe journald is responsible for crashing my server repeatedly.
The system is upgraded more than twice a year. Even though the version is a bit older, please allow me to describe the problem.

I am running a server with a lot of services. Every once in a while it needs to be force powered off and restarted.
Yesterday, problems were noticed around 8 am, but I could not debug the problem.
Today around 2 pm, I checked the services:

* nginx, postfix, and dovecot did not print a banner or response anymore.
* sshd printed the banner (netcat to the server showed `SSH-2.0-OpenSSH_7.9`), but it was not possible to log in
* named still resolved queries

At 4 pm nothing worked anymore, so had to access the server (a laptop with tedious access). Login was not even possible anymore from any of the TTYs and it had to be force powered off and restarted. That is the scenario that repeats itself once in about 3 or 4 months.

Nothing suspicious was ever visible in the logs, so the scrollback buffer size is increased to be able to check what is happening on the screen. Below is a screenshot of the messages that repeat themselves and they started to occur when troubles with the services began.

My assumption is that all services are stuck in a log write operation to the journal.

What can I do to further debug the problem?
I implemented some measures to further debug the problem when it occurs again:

* `cat /dev/kmsg > file` because journald ignores its own entries which would be helpful in this case
* `netcat -e` equivalent

**output on screen**

```
systemd[1]: systemd-journald.service: State 'stop-watchdog' timed out. Terminating.
systemd[1]: systemd-journald.service: State 'stop-sigterm' timed out. Killing.
systemd[1]: systemd-journald.service: Killing process 416 (systemd-journal) with signal SIGKILL.
systemd[1]: systemd-journald.service: Processes still around after SIGKILL. Ignoring.
systemd[1]: systemd-journald.service: State 'stop-final-sigterm' timed out. Killing.
systemd[1]: systemd-journald.service: Killing process 416 (systemd-journal) with signal SIGKILL.
systemd[1]: systemd-journald.service: Processes still around after final SIGKILL. Entering failed mode.
systemd[1]: systemd-journald.service: Failed with result 'watchdog'.
systemd[1]: systemd-journald.service: Service has no hold-off time (RestartSec=0), scheduling restart.
systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 2.
systemd[1]: systemd-journal-flush.service: Succeeded.
systemd[1]: Stopped Flush Journal to Persistent Storage.
systemd[1]: Stopping Flush Journal to Persistent Storage...
systemd[1]: Stopped Journal Service.
systemd[1]: systemd-journald.service: Found left-over process 416 (systemd-journal) in control group while starting unit. Ignoring.
systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
systemd[1]: systemd-journald.service: Start operation timed out. Terminating.
systemd[1]: systemd-journald.service: State 'stop-sigterm' timed out. Killing.
systemd[1]: systemd-journald.service: Killing process 21066 (systemd-journal) with signal SIGKILL.
systemd[1]: systemd-journald.service: Killing process 416 (systemd-journal) with signal SIGKILL.
systemd[1]: systemd-journald.service: Processes still around after SIGKILL. Ignoring.
```

**original "screenshot"**

![systemd-journal-error](https://user-images.githubusercontent.com/23739584/71772145-62cc6500-2f46-11ea-9fae-c8c913992430.jpg)

Notable timestamps:

* 4583591.417309 = 30.12.2019 22:09:43 (last log entry in saved log, used to calculate timestamps)
* 4871476.214397 = 03.01.2020 06:07:47 (first problem with journal)
* 4935734.083247 = 03.01.2020 23:58:45 (last reported problem with journal, not visible on this screenshot)
* 4993379.576828 = 04.01.2020 15:59:31 (unplugging the ethernet cable interestingly printed a message, shortly before force power off, not visible on this screenshot)

**Comment by poettering** [comment]
Nah, this is misleading. Journald is most likely just victim, not cause. For some reason journald hangs (probably because of scheduling issues, IO issues such as access to HDD hanging). systemd notices that and restarts journald because of that. Which resolves the issue again.

Figure out why your IO hangs, i.e. which could be a hw issue that journald can't write stuff in sane speeds or could be a scheduling issue that the system is simply so overloaded.

What kind of fs in /var/log/journal? It appears not to support ACLs, hence looks like something fishy? all modern file systems support ACLs, so this is something strange? NFS?

**Comment by poettering** [comment]
BTW your screenshots show that journald couldn't be killed at all, the process was entirely frozen, and unkillable from userspace. That means it's definitely a kernel/IO issue, because if userspace code hangs you can always kill the process. However if kernel code called from userspace hangs then quite often you end up having the process remain in unkillable state.

Or in other words: something is off on that system, the storaga subsystem of your kernel has issues, and journald is running int this as it wants to write log data to disk. Of course, the log data likely contains information about what precisely is going wrong, but you can't really recover that since after all the log data can't be written to disk...

Your only chance is to have local access to the system, use something like netconsole or maybe crashdump to exfiltrate log data about the hang some other way...

**Comment by adrium** [comment]
Thanks for your quick answer.

The file system is ext4, but the noacl flag is set in fstab, because traditional permissions are sufficient. Is this a real problem for journald?
Has always complained, but always worked so far.

I do have physical access to the system, so netconsole should not be necessary.
The scrollback buffer works. Before force power it off, I removed the network cable. The "link down" message was still printed. Everything else was blocked (login, switching ttys). That is really odd...

Would it help to `ForwardToConsole=yes` to see the messages on the screen that can not be flushed to disk?

Any ideas what else could be monitored?

**Comment by vcaputo** [comment]
With console access, you can use magic-sysrq to dump potentially useful information about the state of the system.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/Documentation/admin-guide/sysrq.rst?h=v5.5-rc5

Some particularly relevant commands:
```
``w``	    Dumps tasks that are in uninterruptable (blocked) state.
``d``	    Shows all locks that are held.
``t``	    Will dump a list of current tasks and their information to your
            console.
```

**Comment by poettering** [comment]
> The file system is ext4, but the noacl flag is set in fstab, because traditional permissions are sufficient. Is this a real problem for journald?

You lose access to the journal from unpriv users, that's all.

That ACLs aren't supported just looked like a hint you used some weird fs...

**Comment by adrium** [comment]
Good idea with the Magic SysRq method! I will try that next time when it happens.
Thanks for your answers.
Closing the issue and see you in about three months :sweat_smile:

**Comment by mrjimenez** [comment]
Hi,

For the people that landed here as I did, I will leave my report.

I have made a recent kernel upgrade to my distribution, openSUSE Tumbleweed, and started to have exactly the same problem. The upgrage was motivated because I had to install kvm.

At first I thought it could be a memory or disk problem, because, you know, Linux usually only behaves like this with hardware problems. But `dmesg` gave me no clue.

So, in the sequence, I thought it could be related to the virtualization module. Removed it, but the problem persisted.

After a while I began to think it was related to journald, because the problem always started with it. I used `top` sorted by state in reverse, so I could see the `D` processes piling up. JBD2 was always the first process to enter `D` state, and from then on others would follow, until most of my processes were in `D`. That "bricked" state would typically remain for a random amount of time, something between 10 and 30 minutes, in rare cases a lot more. Then, suddenly all of the processes started to come alive again and the system would work again for a while until it all repetaed again.

Here is a typical dmesg output. Notice that even the emergency sync is blocked. I did it while in bricked state, but it only appears when the system comes alive again:

```log
[Sat Apr  2 22:07:05 2022] systemd-journald[11182]: File /var/log/journal/a0848146a8854c519ce698d28901e824/system.journal corrupted or uncleanly shut down, renaming and
[Sat Apr  2 22:07:08 2022] systemd[1]: Started Journal Service.
[Sat Apr  2 22:07:08 2022] systemd-journald[11182]: File /var/log/journal/a0848146a8854c519ce698d28901e824/user-1000.journal corrupted or uncleanly shut down, renaming a
[Sat Apr  2 23:26:21 2022] sysrq: Emergency Sync
[Sat Apr  2 23:30:13 2022] systemd[1]: systemd-journald.service: State 'stop-watchdog' timed out. Killing.
[Sat Apr  2 23:30:13 2022] systemd[1]: systemd-journald.service: Killing process 11182 (systemd-journal) with signal SIGKILL.
[Sat Apr  2 23:31:44 2022] systemd[1]: systemd-journald.service: Processes still around after SIGKILL. Ignoring.
[Sat Apr  2 23:33:14 2022] systemd[1]: systemd-journald.service: State 'final-sigterm' timed out. Killing.
[Sat Apr  2 23:33:14 2022] systemd[1]: systemd-journald.service: Killing process 11182 (systemd-journal) with signal SIGKILL.
[Sat Apr  2 23:34:44 2022] systemd[1]: systemd-journald.service: Processes still around after final SIGKILL. Entering failed mode.
[Sat Apr  2 23:34:44 2022] systemd[1]: systemd-journald.service: Failed with result 'watchdog'.
[Sat Apr  2 23:34:44 2022] systemd[1]: systemd-journald.service: Unit process 11182 (systemd-journal) remains running after unit stopped.
[Sat Apr  2 23:34:44 2022] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 3.
[Sat Apr  2 23:34:44 2022] systemd[1]: Stopped Journal Service.
[Sat Apr  2 23:34:44 2022] systemd[1]: systemd-journald.service: Found left-over process 11182 (systemd-journal) in control group while starting unit. Ignoring.
[Sat Apr  2 23:34:44 2022] systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
[Sat Apr  2 23:34:44 2022] systemd[1]: Starting Journal Service...
[Sat Apr  2 23:36:14 2022] systemd[1]: systemd-journald.service: start operation timed out. Terminating.
[Sat Apr  2 23:37:04 2022] systemd[1]: systemd-journald.service: Failed with result 'timeout'.
[Sat Apr  2 23:37:04 2022] systemd[1]: Failed to start Journal Service.
[Sat Apr  2 23:37:04 2022] systemd[1]: systemd-journald.service: Scheduled restart job, restart counter is at 4.
[Sat Apr  2 23:37:04 2022] systemd[1]: Stopped Journal Service.
[Sat Apr  2 23:37:04 2022] systemd[1]: Starting Journal Service...
[Sat Apr  2 23:37:05 2022] systemd-journald[12730]: File /var/log/journal/a0848146a8854c519ce698d28901e824/system.journal corrupted or uncleanly shut down, renaming and
[Sat Apr  2 23:37:14 2022] systemd[1]: Started Journal Service.
[Sat Apr  2 23:37:14 2022] systemd-journald[12730]: File /var/log/journal/a0848146a8854c519ce698d28901e824/user-1000.journal corrupted or uncleanly shut down, renaming a
[Sat Apr  2 23:37:32 2022] Emergency Sync complete
```

The argument that `jbd2` was actually a victim and not the culprit sounded reasonable, so I started to look for other things. I have noticed that there was also a zombie process from nvidia-settings, so I tried to change the video driver.

```log
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                             
10607 myuser    20   0       0      0      0 Z 0.000 0.000   0:00.09 [nvidia-settings] <defunct>                                                                         
    1 root      20   0  169204  10548   6792 S 0.000 0.032 260:08.18 /usr/lib/systemd/systemd showopts --switched-root --system --deserialize 32                         
    2 root      20   0       0      0      0 S 0.000 0.000   0:00.05 [kthreadd]                                                                                          
```

To make a long story short, I changed the video driver from Nvidia's G05 to G06 and the problem went away. All is working fine now.

The curious thing is that the zombie nvidia-settings persists. That process was not called by me, there is probably some initialization script doing that. So the problem should be unrelated to nvidia-settings, but there is a good chance it has something to do with the video drivers in my case.

Best regards,
Marcelo.

**Comment by mdPlusPlus** [comment]
It's probably not much of a help, but I've come here with similar errors in my `dmesg -Tw` output:

```
[Do,  9. Apr 2026, 13:27:28] systemd[1]: systemd 255.4-1ubuntu8.15 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
[Do,  9. Apr 2026, 13:27:28] systemd[1]: Detected architecture x86-64.
[Do,  9. Apr 2026, 13:27:29] systemd-journald[853]: Received SIGTERM from PID 1 (systemd).
[Do,  9. Apr 2026, 13:27:29] systemd[1]: Stopping systemd-journald.service - Journal Service...
[Do,  9. Apr 2026, 13:27:29] systemd[1]: systemd-journald.service: Deactivated successfully.
[Do,  9. Apr 2026, 13:27:29] systemd[1]: Stopped systemd-journald.service - Journal Service.
[Do,  9. Apr 2026, 13:27:29] systemd[1]: Starting systemd-journald.service - Journal Service...
[Do,  9. Apr 2026, 13:27:29] systemd-journald[27207]: Collecting audit messages is disabled.
[Do,  9. Apr 2026, 13:27:29] systemd[1]: Starting fwupd.service - Firmware update daemon...
[Do,  9. Apr 2026, 13:27:29] systemd[1]: Started systemd-journald.service - Journal Service.
```

```
$ systemd --version
systemd 255 (255.4-1ubuntu8.15)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

```
$ uname -r
6.8.0-107-generic
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.4 LTS
Release:        24.04
Codename:       noble
```

```
$ echo $XDG_SESSION_TYPE
x11
```

My system didn't crash though, it just froze for a solid 20 seconds or so and generated this output in dmesg. Nothing relevant in the log _before_ or _during_ the freeze, just _after_ (or I got my timing completely wrong).  
Might be related, might be something completely different, but this issue was the only one I could find that seemed like it could fit.
