### ISSUE TITLE
Change systemd.time format to comply with RFC 3339

### ISSUE THREAD

**Issue by ypid** [systemd/systemd#14515]
**Is your feature request related to a problem? Please describe.**

systemd sticks to a datetime format that "deliberately" differs from ISO 8601 (and RFC 3339), as defined in https://github.com/systemd/systemd/blob/master/man/systemd.time.xml. Although having a nicely human readable date format is appreciated, breaking standards is not. This bugs me a bit when working with systemd.

Follow up to #5194.

**Describe the solution you'd like**

It is possible to have human readable and comply to existing standards if we want to.

> I am not sure it's [ISO 8601] that sensible. We deliberately opted for a different native format we output and parse, since the "T" and "Z" stuff is hardly friendly for humans to read...

@poettering [RFC 3339](https://tools.ietf.org/html/rfc3339) comes to the rescue:

> NOTE: Per [ABNF] and ISO8601, the "T" and "Z" characters in this syntax may alternatively be lower case "t" or "z" respectively.
> NOTE: ISO 8601 defines date and time separated by "T". Applications using this syntax may choose, for the sake of readability, to specify a full-date and full-time separated by (say) a space character.

So `2019-12-22 12:13:23+01:00` or `2019-12-22 11:13:23z` is both valid according to RFC 3339. And I don’t think that is worse than the `2019-12-22 12:13:23 CET`.

The weekday at the beginning is useful and (with much good will) could be seen as outside of the RFC 3339 date string.

For testing, I wrote wrappers for `systemctl status` and `journalctl` which changes the date format to RFC 3339, ref: https://github.com/ypid/scripts/blob/master/sc, https://github.com/ypid/scripts/blob/master/rl

**Describe alternatives you've considered**

Open for discussion.

**Comment by poettering** [comment]
So, the journalctl output we cannot change since it's basically API, it mimics the data traditionally stored in /var/log/messages "pixel exact". You can switch to ISO times with --output=short-iso though if you want.

The date and time formatting are carefully documented here:

https://www.freedesktop.org/software/systemd/man/systemd.time.html

Hence changing that is also a bit of an API breakage. If I have the choice of breaking the ABI to ourselves or adopting some standard that isn#t really used in user-facing stuff anyway (do you know and user-facing app that presents times in ISO? I don't, they all use other syntaxes. ISO is used in some machine readable formats but that's something systemctl status isn't supposed to be so much).

hence I am not convinced. I think making our parser also accept ISO dates makes sense, which is what #5194 is about. And maybe it even makes sense to offer the option to option to display our dates in iso times, but changing everything over and breaking ABI all over the place? I don't think the case for that is even remotely strong enough...

I mean, if you can convince GNU coreutils to change their "date" implementation to default to ISO date output we could talk, but other than that I don't think this is change is advisable at all.

**Comment by steverweber** [comment]
Personally I would like to see an option in: `/etc/systemd/journald.conf` to change the default output format,

```
[Journal]
#OutputFormat=short
```

What would also be nice is output format(s) that respect `LC_TIME`
```
[Journal]
#OutputFormat=locale
#OutputFormat=locale-full
```

**Comment by C0rn3j** [comment]
As of 2023-09 it's at least parsed, thanks to https://github.com/systemd/systemd/pull/29049

**Comment by poettering** [comment]
So, let's close this. We parse RFC 3339 these days, and you can explicitly ask for ISO dates on output. 

I am pretty sure we should not change our default output format though, as it's widely established and inherits the syntax to some degree from syslog date formatting. Changing this right now would be a massive compat break, and I am still not convinced that the ISO format (even in the two suggested formats) is really that nice to read. 

Hence, closing.
