### ISSUE TITLE
Cannot login after adding an encrypted home partition to /etc/fstab

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#14543]
If I add to /etc/fstab an encrypted home partition that should be decrypted manually by the user, systemd will disallow the login to the system. Login on the console just timed out after a long waiting time, no error message. Login with ssh is blocked too, long waiting time and nothing happens. The root login was disabled on this system, so I had to use a recovery usb-stick to undo the changes in /etc/fstab before I was able to use the system again.

**systemd version the issue has been seen with**
244

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
Login to user account is possible

**Unexpected behaviour you saw**
Cannot login

**Steps to reproduce the problem**
1) Add an encrypted home partition to /etc/fstab (mount options used and tested: noauto,x-systemd.automount,nofail,_netdev)
2) Reboot and try to login

Note: I tried to add noauto to /etc/crypttab, but it didn't help either.

**Comment by poettering** [comment]
add noauto to both the fstab and the crypttab entry, and dont list x-systemd.automount and systemd should not activate the thing at boot, except if something has an explicit dependency on it.

What do you mean by "a home partition"? /home itself? that's required for log-ins, so is always triggers.

Whenver you submit a bug report please paste the full configuration lines you are using, otherwise it#s hard to understand what you are doing, i.e. both the full fstab and the crypttab line you are using.

**Comment by poettering** [comment]
Closing due to lack of response
