### ISSUE TITLE
store journald data on block device without filesystem layer

### ISSUE THREAD

**Issue by cypa** [systemd/systemd#14638]
**Is your feature request related to a problem? Please describe.**
I feel uncertain if storing log data on the same filesystem is reliable
I can see log data files size is multiple of 8Mb so why not put these chunks on plain block device?
In case of filesystem failure log data would be safe I guess.

**Describe the solution you'd like**
store journald log data on separate partition without filesystem

**Describe alternatives you've considered**
Can't see any good alternative

**Comment by vcaputo** [comment]
The filesystem is a significant component of the overall journald architecture.

If your concern is that filesystem activity unrelated to logging may result in corruption affecting the logs, you can already mitigate this by using a dedicated filesystem on either /var or /var/log/journal, and you can put that filesystem on dedicated underlying storage.

**Comment by cypa** [comment]
Could you please hint any docs/explanations on filesystem role in the overall journald architecture?
Also which filesystem would be best for separate /var/log/journal partition? I guess simplest and robust one.

**Comment by boucman** [comment]
@cypa : as a minimal idea, there are multiple journals
* one per user, using unix permissions to allow each user to read his logs
* compression when they go beyond a certain size...

With a direct-to-device approch, that would break all this logic

the direct-to-device approch to logs comes from the microcontroller world wher a FS is a very complex overhead compared to the overall capacity of your uC. When you use linux there isn't really a reason not to use proper filesystem. I'd be very interested to know of your use case, and if/why you need that approch...

**Comment by cypa** [comment]
- apply permission to chunks on the blockdev seems trivial

- special compression algorithm aware of log records structure would be better I guess

rock solid logging storage would be useful for any OS on any scale so why not? as I can see adoption to block dev would be trivial, many features are ready

ten years back /var/log filesystem fill was very annoying and frequent problem, I feel the pain until now

**Comment by cypa** [comment]
also there is KISS idea of unix, or isn't?

**Comment by boucman** [comment]
Well, it's more KISS to use a filesystem than to reinvent the whole layer. Everything else means writing some highly specific code in systemd instead of relying on what the kernel does for us. 

I don't know of any permission-aware feature of the kernel on chunks of a block device... do you mean implementing that in systemd ? that seems not trivial and a security nightmare. Same thing with using a specific compression algorithm instead of relying on existing libraries. 

Also I'm not sure what you mean by "rock solid storage" my experience is that the kernel's FS layer is rock solid and that most user-space solutions writing directly to a block device is usually way more fragile.

Moreover journald is very good at suppressing old logs (see man:journald.conf) so logs filling up /var is more or less a solved problem. I remember that time and I understand your trauma (TBH, your mention of it woke up the same trauma in me) but I havn't seen that problem for a very long time, thanks to journald. 

HTH
Jérémy

**Comment by cypa** [comment]
```
-rw-r-----+ 1 root systemd-journal 8,0M ноя 30 11:42 system@8ba5786349354b2f81efe01835370bc7-0000000000000001-0005986843b29576.journal
-rw-r-----+ 1 root systemd-journal  24M дек  8 21:07 system@8ba5786349354b2f81efe01835370bc7-000000000001612c-0005988aa668bec1.journal
-rw-r-----+ 1 root systemd-journal  16M дек 25 21:27 system@ac9de56d52c44194b91564953e658370-0000000000000001-00059a4b65c07a4f.journal
-rw-r-----+ 1 root systemd-journal  64M янв 24 15:23 system.journal
-rw-r-----+ 1 root systemd-journal 8,0M окт  7 11:37 user-1000@0005944c49f514af-8f7f799bb337deb5.journal~
-rw-r-----+ 1 root systemd-journal 8,0M окт  7 11:50 user-1000@0005944c74338b31-4ab3f1c4d093069f.journal~
-rw-r-----+ 1 root systemd-journal 8,0M окт 14 00:39 user-1000@000594cfe216020e-b946216307d3ee53.journal~
-rw-r-----+ 1 root systemd-journal 8,0M ноя  1 15:43 user-1000@00059646a205348d-e275adf0bfd0332f.journal~

```
I see we need a filesystem which 

- split the whole block dev in 8,0M simmetric chunks permanently
- permissions on every chunck
- ... what else?

**Comment by cypa** [comment]
possibly losetup with offset and size would be enough to manage chunks?

**Comment by cypa** [comment]
dear @boucman I understand your logic well, but there are many use cases of linux nowadays, many use cases, like embedded, would benefit I guess

**Comment by cypa** [comment]
in theory logs are streams of data - should we have "streamsystem" on disk instead of filesystem? modern filesystems is far more sophisticated, so why not add ring buffer which is rather simple thing?

**Comment by cypa** [comment]
oh ... maybe we need 8,0M block size filesystem?

**Comment by boucman** [comment]
I am also en embedded guy, and I assumed that was your use-case, but reimplementing a low-level ring buffer is way more complicated than using the highly tested FS layer. You are adding some unreliable feature instead of using reliable, existing ones.

Again, that approch makes sense for microcontrolers, but not for embedded linux.

You have some great, highly tested tools. We (my company) are currently looking at smart way to store high quantitiy of linear logs (more for data-sensors/IoT than logs) but even in that case, attacking the block device directly is not a good idea. FS provide high flexibility, reliable writing (journals, fsck) inline compression and are easily adapted if the use-case changes (adding encryption for example) for... no cost. It's here, it's reliable, it's simple to use. So I don't really see the point of attacking the block device directly

On modern hardware, block devices are complex things. If you attack them directly you need to deal with bad blocks, timings and various calls to deal directly with the hardiware. If you use a higher level tool like /dev/mtd, you need to deal with in-advance blanking, block rotation etc. It's hard. Very hard. It's way safer to use some tested code like ubi/ubifs or f2fs that deals with the hardware for you

Writing linearly on a block device is not a good idea. Leave that job to the kernel.

**Comment by cypa** [comment]
I'll try XFS with 64K blocksize for now on /var/log/journal filesystem

**Comment by poettering** [comment]
I am sorry, but I don#t think we should support such a mode in journald. file systems solve real problems, implement block allocation and release, data synchronization and what not. If we'd support writing natively to a block device we'd have to reinvent all that. I mean, sure it could be simpler than in a real fs, but it still would have to be there, as we need to implement rotation and vacuuming and similar.

File systems solve these issues for us, solving these issues is their very reason to exist and I think we should trust them enough to deliver on this.

Sorry!
