### ISSUE TITLE
statically enabled sshd.socket (symlink in sockets.target.wants) has status "disabled"

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#1464]
/usr/lib/systemd/system/sockets.target.wants/sshd.socket is present, yet systemctl list-unit-files sshd.socket says "disabled".

Is there a status calculation bug, w.r.t. things enabled for the sockets.target? I was expecting status "static".

**Comment by arvidjaar** [comment]
What is in `[Install]` section of sshd.socket?

**Comment by xnox** [comment]
```
[Unit]
Description=OpenSSH Server Socket
Conflicts=sshd.service

[Socket]
ListenStream=22
Accept=yes

[Install]
WantedBy=sockets.target
```

**Comment by heftig** [comment]
I think status `static` is simply shown for a missing `[Install]` section. Your section would control `/etc/systemd/system/sockets.target.wants/sshd.socket`, and I believe the system just checks this file instead of calculating actual dependencies. So…
- `[Install]` section missing => `static`
- `[Install]` section present, symlinks present => `enabled`
- `[Install]` section present, symlinks absent or (for `Alias=`) wrong targets => `disabled`

**Comment by heftig** [comment]
Hm, looking through the code I think it's actually scanning the entire `/etc/systemd/system` tree for symlinks, but doesn't look at `/usr/lib/systemd/system`. So, in order:

```
Masked (Linked to /dev/null) ··········· → masked
Symlinks present in /etc ··············· → enabled
Loading [Install] failed ··············· → invalid
Alias=, WantedBy= or RequiredBy= present → disabled
Also= present ·························· → indirect
else ··································· → static

```

**Comment by poettering** [comment]
@xnox "disabled" is the state (as @heftig correctly identified) when the data from [Install] is not applied in /etc. If you statically enable something via a symlink in /usr/lib, then also drop its [Install] section, so that this is correctly reported, and systemctl is never led to believe that the [install] section was something to apply.

The thing is really that "enabled" should imply that the user can "disable" it, and "disabled", that the user can "enable" it. [Install] should imply that the user can enable/disable it. This is relatively easy to grok I think...

I see nothing to fix here...
