### ISSUE TITLE
Automatic daemon-reload

### ISSUE THREAD

**Issue by TRPB** [systemd/systemd#14757]
**Is your feature request related to a problem? Please describe.**

Every time a service file is edited, I have to run `systemctl daemon-reload`.

However, if I first run `systemctl restart name.service` it tells me:

> Warning: The unit file, source configuration file or drop-ins of php-fpm.service changed on disk. Run 'systemctl daemon-reload' to reload units.

systemd already knows that the unit has changed on disk, is there a reason it cant automatically reload the file instead of giving me a notice and making me do it manually?

**Describe the solution you'd like**

systemd knows that the service file has changed, instead of displaying the warning, automatically reload the daemon and then start the service.

**Describe alternatives you've considered**

If there's a reason for this behaviour then it would be nice if can be toggled on/of with a configuration option.

**Comment by keszybz** [comment]
This is on purpose. We don't know when the right time to reload the configuration would be. We don't know if just one file is being edited or multiple ones, and doing any kind of automatic reload would be inherently racy. `systemctl edit` will do a daemon-reload at the end, because it knows that the editing operation is done. In general the answer is to do an explicit daemon-reload at a well defined point in time.
