### ISSUE TITLE
A stop job is running for Snappy daemon.

### ISSUE THREAD

**Issue by shuvidora** [systemd/systemd#14754]
**systemd version the issue has been seen with**
> 237

**Used distribution**
 > I play Ubuntu 18.04.3 amd64  server under Vmware Workstation and have UEFI boot my virtual machine.

**Expected behaviour you didn't see**
 > No snappy daemon waiting message blocks the shutdown process.

**Unexpected behaviour you saw**
 > If I type poweroff and enter to shut down Ubuntu, it always prompts 'A stop job is running for Snappy Daemon’  with a 90s temporal span. without a 90s waiting period for Snappy daemon. This happens to either root or ordinary user.

**Steps to reproduce the problem**
Run `poweroff` and look at the following black window lines.

**Comment by topimiettinen** [comment]
237 is way too old, can you replicate this with newer version?

There was a bug in kernel which was fixed in 5.2-rc5, and the fix was backported to 4.19.66 and 4.14.138, but there may be stable kernels without the fix. Also systemd since v243 has a workaround, so this shouldn't be a problem even with unfixed kernels.
