### ISSUE TITLE
networkd will using existing netlink socket which is not belonging to itself

### ISSUE THREAD

**Issue by medadyoung** [systemd/systemd#14760]
systemd 243

OpenBMC Linux 5.2

I noticed that networkd will try to using the existing netlink socket which is not creating by networkd in systemd_netlink_fd(), and once networkd terminates, the response messages from kernel will stay in the read queue which is not creating by networkd, so the next run of networkd may get the response messages which are not belonging to itself, and something may be wrong in some case.

**Comment by yuwata** [comment]
Could you give us an example?

**Comment by medadyoung** [comment]
In OpenBMC boot up flow, networkd will be launched twice.
sometimes the first run will terminate under some condition before reading all the response message from read queue, and leave three ACK messages in the read queue which is not belonging to itself, and then the if the second run of networkd still use the same socket as the first run, then the second run will read these three ACK messages which are belonging to the first run.

so the second run will meet some problem due to treat these three messages as the response of the command it sends out.

**Comment by yuwata** [comment]
Please elaborate more. What kind of ACK messages? What problem happens then? What is logged in that case?

**Comment by medadyoung** [comment]
I just check the type of the message is ACK, but I do not look into it.
Every message networkd sends out will have a serial number, and the issue happens when the response messages of the first run from serial number 7~9 are leaving in the read queue in kernel space, and when the second run starts, networkd will read the messages of serial number 7~9 into its read queue in user space.
now when the second run sends messages out with serial number 7~9, networkd will treat the response messages which are already existing in its read queue as its response according to the serial number.
but actually, these response messages are not belonging to second run, so networkd will treat it as something wrong.
as a result, network does not complete the enumeration of eth interface, so it does not bring up some eth.

**Comment by ningchia** [comment]
Let me try to elaborate it a bit more as I heard from Medad. Please Medad correct me if I misunderstand anything.

It happens in flow like the following :
1. In the 1st round, networkd enumerates network device info with several cmds, and each of them expects long response divided into several packets. The cmds and packets were tagged with a serial number so that networkd can match them up. Let's say them as 1,2, ..., 7,8,9.
2. Now when networkd is receiving response for his cmd with serial number 7, somehow networkd terminates, and leave some response residue in the read queue, also with serial number 7.
3. Now in the 2nd round networkd enumerates network device info again. It happens that the "new" cmd was tagged with serial number 7 again, and networkd will match it with the "partial, old" response it got from the read queue, and reports error here.

That's why Medad re-create the netlink socket in his patch so that to flush the residue.

Hope it helps.

**Comment by ssahani** [comment]
What happens if you restart the `.socket`. Does it fixes ?

**Comment by ssahani** [comment]
@yuwata I think this may be happening.  I propose two solutions

1. When restarting networkd  we also restart .socket unit too.
2. We introduce a small function which will drain the data in receive queue before requesting any new or we before networkd starts any netlink operations.

**Comment by medadyoung** [comment]
> .socket

Hi, what do you mean "restart .socket unit" ?

**Comment by ssahani** [comment]
systemd-networkd.socket

**Comment by medadyoung** [comment]
Hi
I add ExecReload=/bin/systemctl stop systemd-networkd.socket in /lib/system/system/system-networkd.service,
but the issue still happens
is the way I restart .socket correct?
thanks
