### ISSUE TITLE
An instantiated User= does not effect subsequent specifiers

### ISSUE THREAD

**Issue by Earnestly** [systemd/systemd#1476]
When using `User=%i` with a specifier, the result doesn't seem to propagate to other specifiers used within the unit such as `%h`.

For example `user@.service`

``` ini
...

[Service]
User=%i
Environment=XDG_CONFIG_HOME=%h/local/cfg
Environment=XDG_DATA_HOME=%h/local/data
Environment=XDG_CACHE_HOME=%h/local/var/cache
...
```

After this change inspecting (`systemctl show`) an instantiated unit such as `user@1000` reports the following environments:

```
...
Environment=XDG_CONFIG_HOME=/root/local/cfg XDG_DATA_HOME=/root/local/data XDG_CACHE_HOME=/root/local/var/cache
...
```

I would have expected the expanded `User=` to also correctly expand `%h` according to that user's home directory.

**Comment by poettering** [comment]
This is explicitly not supported, see systemd.unit(5). And we cannot change that, as that would mean we'd have to do an NSS lookup from PID 1, in order to get the home directory for the specified user, which we cannot do.

Sorry.

**Comment by Earnestly** [comment]
Is there a suitable workaround which would let one add an environment to the `user@` templates (or essentially the user sessions) without hardcoding the paths?  Currently this seems to indicate `systemctl --user` cannot realistically honour `XDG_CONFIG_HOME`.

**Comment by poettering** [comment]
You can set additional environment for the user instance in ~/.config/systemd/user.conf

**Comment by Earnestly** [comment]
Unfortunately using `HOME/.config` is precisely what I'm trying to avoid (ideally I would like to use the `XDG_*_HOME` environments to reduce the number of "dotfiles" on my system as they have caused lots of headaches in the past).

Another option which was suggested is to wrap the `ExecStart` in `user@.service` to essentially take `%i` as an argument and then do the necessary lookups via `getent`.

Conceptually:

``` sh
getent passwd "$1" | awk -v FS=: '{ print $6 }'
```

Then using the result to construct exports before calling `systemd --user`.

I realise this is a bit of a hack but I'm not really sure if there's a cleaner method than this.  I thought perhaps `pam_env` would help here but even `@{HOME}` doesn't appear to do what I thought it should.

_Edit: Is there any reason why systemd couldn't essentually do the equivalent `getent` if `User=` is configured?  I'm not sure what you mean by not being able to do the necessary lookup.  Would you mind explaining the issues for this for posterity if others may look here?_

**Comment by poettering** [comment]
I am pretty sure if you actually use XDG_CONFIG_HOME to move everything you are in a bigger headache than without....

You could set the env var via PAM use pam_env.

Specifiers are expanded during load-time of the unit, so that automatic dependencies can be generated from the settings they are included in. This means resolving %h from User= would mean to do a getpwnam() call from PID 1 while loading the units. However, getpwnam() is an NSS call, and it might go to another service to actually resolve the name. Now, PID 1 is the service manager of the system, it's managing all other services -- as such it should not be a client to those services it manages, becaause that might otherwise result in deadlocks, since requests to NSS might trigger activation, but those cannot happen because PID 1 is blocking in the NSS lookup.

Hence we have the policy: no NSS lookups from PID 1, ever.

**Comment by Earnestly** [comment]
Ah, thank you for the explaination.  It certainly makes sense now.
