### ISSUE TITLE
Timedated set_timezone sets kernel tz-offset but systemd initialize_clock does not

### ISSUE THREAD

**Issue by steene8472** [systemd/systemd#14875]
**systemd version the issue has been seen with**
> current master (v245-rc1)

**Used distribution**
 > None - looked at source in github repository

**Expected behaviour you didn't see**
 > Either never touch in kernel timezone offset (sys_tz.tz_minuteswest via settimeofday) OR update it on boot AND on timezone changes

**Unexpected behaviour you saw**
 > kernel timezone offset is updated when changing timezone via timedated BUT not on clock initialization in init

**Steps to reproduce the problem**
Boot system, call gettimeofday(NULL, &tz)
Change timezone and change it back to boottime timezone
Call gettimeofday(NULL, &tz)
Values are different. (First result is 0 while second represents actual offset)

As mentioned in other issues (https://github.com/systemd/systemd/issues/13305) the in-kernel offset value is used in some filesystem code (fat, udf, hpfs, hfs).
Using the alternate time_offset mount parameter would require changing this option actively on every timezone change.

Relevant code:
https://github.com/systemd/systemd/blob/master/src/shared/clock-util.c#L110
https://github.com/systemd/systemd/blob/master/src/core/main.c#L1497

**Comment by poettering** [comment]
Having a tz offset for the RTC is inherently broken, we only do the absolute minimum support, which is the boot-time support. we do not do any further management of it. it's a really poor concept and will be necessarily racy and fucked, since we'd have to update the offset whenever winter/summer time changes too, but we cannot do that without delay.

Basically, it's a minimal work windows compat thing, and we output a loud blurb about how broken it is if you run timedatectl with it enabled:

```c
        if (i->rtc_local)
                printf("\n%s"
                       "Warning: The system is configured to read the RTC time in the local time zone.\n"
                       "         This mode cannot be fully supported. It will create various problems\n"
                       "         with time zone changes and daylight saving time adjustments. The RTC\n"
                       "         time is never updated, it relies on external facilities to maintain it.\n"
                       "         If at all possible, use RTC in UTC by calling\n"
                       "         'timedatectl set-local-rtc 0'.%s\n", ansi_highlight(), ansi_normal());
```

Sorry, but this is nothing we can reasonably support. 

Also note that android nowadays assumes FAT timestamps are UTC, and everyone probably should do, since there's no metadata indicating anything else and fat, udf are all formats primarily used for data exchange between systems with different clocks.

Sorry, but we are not going to support anything more in this area. Just switch your RTC to UTC if you want this to work somewhat sanely.

**Comment by m-korber** [comment]
I think the request was not about supporting RTCs running in local time but about a possibly inconsistent behavior of systemd. 

Setting the kernel time(zone) offset during systemd startup has been introduced in 190 but later removed again in 216 with the following explanation: _systemd will no longer inform the kernel about the current timezone, as this is necessarily incorrect and racy as the kernel has no understanding of DST and similar concepts._

The question is: Why does systemd still change the kernels timezone offset via settimeofday() in clock_set_timezone() - when running e.g. "timedatectl set-timezone" - when it thinks it's a bad idea to do the same thing during startup?

Can someone please explain the reason behind that?
