### ISSUE TITLE
Systemd journal daemon doesn't honour MaxFileSec= option

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#14876]
**systemd version the issue has been seen with**
> 244.2

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Rotate journal and create new file after fixed period of time, e.g. MaxFileSec=1week. Journal files are expected to have the same time span.

**Unexpected behaviour you saw**
 > Rotating files before fixed period.

**Steps to reproduce the problem**
> Observe journal files time span for default 1month or change MaxFileSec= parameter to 1 week and so on.

**My current configuration /etc/systemd/journald.conf.d/custom.conf**
> [Journal]
Storage=persistent
SplitMode=none
MaxLevelStore=info
MaxFileSec=1week
MaxRetentionSec=1year

**Comment by anitazha** [comment]
Is it possible you are hitting the size limits for the journal? The documentation at https://www.freedesktop.org/software/systemd/man/journald.conf.html#SystemMaxUse= details the default size values.

**Comment by marcin-82** [comment]
No, my root partition is 50GB, here is space usage by journal (part from systemctl status systemd-journald):
`Runtime Journal (/run/log/journal/3ffac4148e1f46e8b4edb64ce7240245) is 8.0M, max 802.0M, 794.0M free.`
`System Journal (/var/log/journal/3ffac4148e1f46e8b4edb64ce7240245) is 80.0M, max 4.0G, 3.9G free.
`

**Comment by poettering** [comment]
i am sorry, but what is the problem? not that there are multiple reasons we rotate, for example abnormal exit (i.e. poweroff while journal file was dirty), disk size, time, user request and so on. What precisely is the problem here?

MaxFileSec= is setting a maximum, not a minimum...

with the little information you provided this is not actionable... have your turned on debug logging for journald itself (i.e. set Environment=SYSTEMD_LOG_LEVEL=debug for it)? it usually says why it rotates.

**Comment by poettering** [comment]
Let's close this, since this appears to be a misunderstand and there was no reply.
