### ISSUE TITLE
docs: Consider building the site with GFM instead of Kramdown

### ISSUE THREAD

**Issue by LynnKirby** [systemd/systemd#14897]
Rendered documentation is likely viewed mostly on GitHub. The docs are also used to build the systemd.io website. However, the current setup for Jekyll to build the site uses the Kramdown markdown processor. The Kramdown dialect is a bit different than GitHub Flavored Markdown which can lead to differences in rendered output (e.g. see [my comment](https://github.com/systemd/systemd/pull/14852#issuecomment-587178898) on #14852).

The two rendered outputs can be synchronized by using GFM for the site. This is easily changed: just set `markdown: GFM` in `_config.yml`.

I haven't actually checked but I would guess that Kramdown features aren't actually being used and the setting to Kramdown is only because it's the default.

**Comment by inanc665** [comment]
İnanç organizasyon ilahi sanatçısı https://inancorganizasyon.com/mustafa-ozcan-gunesdogdu-iletisim/   inceleyip yorum yaparsanız sevinirim

**Comment by Arpitkt** [comment]
#okkkkk

**Comment by keszybz** [comment]
Sure, why not. Can you submit this as PR?

**Comment by Rancho309** [comment]
![F85CA14B-9505-48B9-9650-FECCEBBCB565](https://user-images.githubusercontent.com/41242962/75487377-2e33c300-5963-11ea-9fee-b80f75e25721.jpeg)
![4779EBD8-6FC4-41F5-9DDF-D5FCAD0039AA](https://user-images.githubusercontent.com/41242962/75487394-33910d80-5963-11ea-9f42-2383e90b7e4b.jpeg)
![1B0CDC63-3E5E-4716-A9EF-7C72984FDE84](https://user-images.githubusercontent.com/41242962/75487395-3429a400-5963-11ea-860e-a9a1fc6cc1a1.jpeg)
![B22B4B54-8593-4B9F-B0EA-5ABF2D7A99C3](https://user-images.githubusercontent.com/41242962/75487409-38ee5800-5963-11ea-84c3-d237c60cc2ae.jpeg)
![D6B2FC0A-8BB0-4BA4-B7EB-B6E9B9273930](https://user-images.githubusercontent.com/41242962/75487419-3be94880-5963-11ea-880b-a835145be9d3.jpeg)
![Uploading E9F8A750-F103-4292-9865-FA715CA2545A.jpeg…]()

**Comment by Marcus197133** [comment]
Priscillacmpaixao

**Comment by Mehedi34** [comment]
where

**Comment by reportersocial** [comment]
a+aa

**Comment by Arpitkt** [comment]
What

**Comment by bnf** [comment]
Hey,

thanks for the heads up.
So this is basically `kramdown` parser in `input: GFM` mode (which is enabled by default in jekyll [1]) versus native (and proprietary?) `GFM` parser provided by GItHub.

That means this change is *not* about kramdown dialect vs github-markdown dialect, but mostly a parser/compliance decision. 
<details>
  <summary>Note that we already use the GFM dialect and also make use of its features.</summary>
  
This can easily be checked by explicitly activating the `input: Kramdown` dialect in `_config.yml`:

```
kramdown:
  input: Kramdown
```
Comparing the result of `jekyll build` leads to a large diff because with `input: Kramdown` would ignore language-flavored code-examples (that is GFM-dialect). So it's clear: We are using kramdown in GFM mode.
</details>

Now, while switching to the native GitHub markdown parser (GFM) would have the advantage that rendering would be 100% compatible with the rendering on the github-source-view and autolinking raw URLs would be supported, we'd loose the ability to simply compile/serve locally via `jekyll build` or `jekyll serve`, as installed via `dnf install jekyll`:

```
$ sed -i 's/kramdown/GFM/' _config.yml
$ jekyll build
Markdown processor: "GFM" is not a valid Markdown processor.
                    Available processors are: kramdown
```

I don't even find a source or an available jekyll plugin for the native GitHub GFM parser for local usage, so I guess the parser is properitary. That means we'd have to push to github and wait for the github-pages processing for every change that wants to be tested/previewed.

For that reason and as we actually already use GFM (just with another parser) I'd recommend to close this and avoid the switch. Also, for an open source project all build pipelines should be kept reproducible independently from any properitary compilers.

Fine with you?

[1] https://jekyllrb.com/docs/configuration/markdown/#kramdown-processor

**Comment by keszybz** [comment]
> For that reason and as we actually already use GFM (just with another parser) I'd recommend to close this and avoid the switch. Also, for an open source project all build pipelines should be kept reproducible independently from any proprietary compilers.

Yep.
