### ISSUE TITLE
logind SetBrightness is undocumented

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#14938]
Sorry if this is the wrong place, but I don't see SetBrightness documented in https://www.freedesktop.org/wiki/Software/systemd/logind/ .

It was added sometime back in v243 I think and it might see more usage if it was documented. I don't actually know where the freedesktop page gets it's content from, but it doesn't appear to be this repo, otherwise I'd submit an update myself.

**Comment by CorvetteCole** [comment]
I second this

**Comment by keszybz** [comment]
https://www.freedesktop.org/wiki/Software/systemd/ is a separate wiki.
We have been slowly moving content from there to systemd.io, which is generated based on contents of this repo (docs/ directory).

For the pages describing the dbus api, we should move the contents too, and then make any changes. It would be great if we could combine this move with some (partial) automation, so that we'd have a script that we could call to update the introspection data dump and tell us if new entries need documenting.

**Comment by poettering** [comment]
Documented since 7592871e26554fb67baf5e18fe4fd9b053224490. Closing.
