### ISSUE TITLE
Unlclear ExecStopPost semantics

### ISSUE THREAD

**Issue by helmutg** [systemd/systemd#15032]
The `systemd.service` manual page includes this paragraph in the explanation of `ExecStopPost`

>  As the service's processes have been terminated already when the commands specified with this setting are executed they should not attempt to communicate with them.

To me, it reads like `ExecStopPost` commands will only run after all service processes have been terminated. However that is not what happens on 244.3 and 241.

One can easily craft a service (even with `KillMode=control-group`) where the mainpid spawns a child that deliberately ignores `SIGTERM`. When terminating that service, systemd does send `SIGTERM` to both processes. Once the mainpid terminates, `ExecStopPost` is run. Any children are left running even after the service is fully stopped. Those children remain in the control group of the service even though it is now shown as inactive. Thus they can be cleaned up reliably using `systemctl kill --signal=9`.

It seems to me that the present behaviour is intentional although I think that having a mode where stopping the service reliably kills all processes would be good as well. As such I suggest updating the documentation to make it more explicit that some non-mainpid processes may be left running when `ExecStopPost` runs.

I would like to thank @boucman for helping diagnose the issue on irc.

Actionable aspects:
 * Improve the documentation to make it more clear that `ExecStopPost` may run with service processes present.
 * Optionally offer a mode where all processes are reliably killed.

**Comment by rlpowell** [comment]
I'm not sure if this really adds anything, but in case it's helpful here's the large writeup I did on this issue when it was causing production problems for me:

It turns out that it's possible (not even that hard) to construct a situation in which ExecStopPost runs while elements of the service are still running.

The expected behaviour here is "kill all the processes in the control group, wait until they're actually dead (with possible edge cases for various timeouts) and then proceed with ExecStopPost".  And, indeed, this works in the way you'd expect if the control process (the process actually started directly by systemd) ignores TERM.

However, the *actual* behaviour is "kill all the processes in the control group, wait until the control process is actually dead (with possible edge cases for various timeouts) and then proceed with ExecStopPost".  That is: systemd *does* wait for the control process (the process actually started directly by systemd) to stop before running ExecStopPost, but it does *not* wait for the rest of the control group processes.

This can, in particular, result in a cleanup script fighting with dangling child processes for control of files.  Ask me how I know.  -_-;

Repro example, not minimal but pretty close:

Service file:

```
[Unit]
Description=test daemon
After=network.service syslog.service

[Service]
TimeoutStartSec=0
EnvironmentFile=/etc/sysconfig/testd
ExecStart=/Users/rlpowell/scratch/systemd_test_1.sh
ExecStopPost=/Users/rlpowell/scratch/systemd_test_2.sh
Restart=on-failure
KillMode=control-group
KillSignal=SIGTERM
TimeoutStopSec=25

[Install]
WantedBy=multi-user.target
```

The scripts run by systemd, parent and child:

```
$ cat /Users/rlpowell/scratch/systemd_test_1.sh
#!/bin/bash

/Users/rlpowell/scratch/systemd_test_3.sh
```

```
$ cat /Users/rlpowell/scratch/systemd_test_3.sh
#!/bin/bash

trap "echo main script just got term $(date)" TERM

for num in $(seq 1 10000)
do
  date
  sleep 1
done
```

The ExecStopPost script:

```
$ cat /Users/rlpowell/scratch/systemd_test_2.sh
#!/bin/bash

echo "Running the post-stop script now."
```

Here's what things look like (mixture of journalctl and a script that's running ps afux) after starting the thing:

```
Oct 01 17:49:30 testhost.localdomain systemd[1]: Started The testd Daemon.
Oct 01 17:49:30 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:30 UTC 2021
Oct 01 17:49:31 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:31 UTC 2021
Oct 01 17:49:32 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:32 UTC 2021
Oct 01 17:49:33 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:33 UTC 2021

Fri Oct  1 17:49:31 UTC 2021
root      4908  0.0  0.0 116888  3124 ?        Ss   17:49   0:00 /bin/bash /Users/rlpowell/scratch/systemd_test_1.sh
root      4909  1.0  0.0 117812  3976 ?        S    17:49   0:00  \_ /bin/bash /Users/rlpowell/scratch/systemd_test_3.sh
Fri Oct  1 17:49:32 UTC 2021
root      4908  0.0  0.0 116888  3124 ?        Ss   17:49   0:00 /bin/bash /Users/rlpowell/scratch/systemd_test_1.sh
root      4909  0.5  0.0 117812  4072 ?        S    17:49   0:00  \_ /bin/bash /Users/rlpowell/scratch/systemd_test_3.sh
```

And here's what things look like after calling stop:

```
Oct 01 17:49:41 testhost.localdomain systemd[1]: Stopping The testd Daemon...
Oct 01 17:49:41 testhost.localdomain systemd_test_1.sh[4908]: Terminated
Oct 01 17:49:41 testhost.localdomain systemd_test_1.sh[4908]: main script just got term Fri Oct 1 17:49:30 UTC 2021
Oct 01 17:49:41 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:41 UTC 2021
Oct 01 17:49:41 testhost.localdomain systemd_test_2.sh[5048]: Running the post-stop script now.
^^ THAT'S THE BAD PART
Oct 01 17:49:41 testhost.localdomain systemd_test_1.sh[4908]: Terminated
Oct 01 17:49:41 testhost.localdomain systemd_test_1.sh[4908]: main script just got term Fri Oct 1 17:49:30 UTC 2021
Oct 01 17:49:41 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:41 UTC 2021
Oct 01 17:49:42 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:42 UTC 2021
Oct 01 17:49:43 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:43 UTC 2021
Oct 01 17:49:44 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:44 UTC 2021
Oct 01 17:49:45 testhost.localdomain systemd_test_1.sh[4908]: Fri Oct  1 17:49:45 UTC 2021

Fri Oct  1 17:49:40 UTC 2021
root      4908  0.0  0.0 116888  3124 ?        Ss   17:49   0:00 /bin/bash /Users/rlpowell/scratch/systemd_test_1.sh
root      4909  0.1  0.0 117812  4072 ?        S    17:49   0:00  \_ /bin/bash /Users/rlpowell/scratch/systemd_test_3.sh
Fri Oct  1 17:49:41 UTC 2021
root      4909  0.1  0.0 117820  4080 ?        S    17:49   0:00 /bin/bash /Users/rlpowell/scratch/systemd_test_3.sh
Fri Oct  1 17:49:42 UTC 2021
root      4909  0.1  0.0 117820  4080 ?        S    17:49   0:00 /bin/bash /Users/rlpowell/scratch/systemd_test_3.sh
Fri Oct  1 17:49:43 UTC 2021
root      4909  0.1  0.0 117820  4080 ?        S    17:49   0:00 /bin/bash /Users/rlpowell/scratch/systemd_test_3.sh
```

So.  The parent dies, the stop gets run, but the child is still running.  Eventually (TimeoutStop=25):

```
Oct 01 17:50:06 testhost.localdomain systemd[1]: test.service stop-final-sigterm timed out. Killing.
Oct 01 17:50:06 testhost.localdomain systemd[1]: Stopped The testd Daemon.
Oct 01 17:50:06 testhost.localdomain systemd[1]: Unit test.service entered failed state.
Oct 01 17:50:06 testhost.localdomain systemd[1]: test.service failed.
```

, and then all the processes are gone.
