### ISSUE TITLE
systemd-logind v245 reads /etc/shadow

### ISSUE THREAD

**Issue by cgzones** [systemd/systemd#15105]
**systemd version the issue has been seen with**
> systemd 245 (245-2)

**Used distribution**
 > Debian sid

**Unexpected behaviour you saw**
 > systemd-logind reads directly /etc/shadow at boot
```
type=PROCTITLE msg=audit(03/13/20 11:26:20.408:34) : proctitle=/lib/systemd/systemd-logind 
type=PATH msg=audit(03/13/20 11:26:20.408:34) : item=0 name=/etc/shadow inode=131425 dev=fe:01 mode=file,640 ouid=root ogid=shadow rdev=00:00 obj=system_u:object_r:shadow_t:s0 nametype=NORMAL cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(03/13/20 11:26:20.408:34) : cwd=/ 
type=SYSCALL msg=audit(03/13/20 11:26:20.408:34) : arch=x86_64 syscall=openat success=yes exit=19 a0=0xffffff9c a1=0x7f342cc5b176 a2=O_RDONLY|O_CLOEXEC a3=0x0 items=1 ppid=1 pid=531 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=systemd-logind exe=/usr/lib/systemd/systemd-logind subj=system_u:system_r:systemd_logind_t:s0 key=(null) 
type=AVC msg=audit(03/13/20 11:26:20.408:34) : avc:  denied  { open } for  pid=531 comm=systemd-logind path=/etc/shadow dev="vda1" ino=131425 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:object_r:shadow_t:s0 tclass=file permissive=1 
type=AVC msg=audit(03/13/20 11:26:20.408:34) : avc:  denied  { read } for  pid=531 comm=systemd-logind name=shadow dev="vda1" ino=131425 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:object_r:shadow_t:s0 tclass=file permissive=1 
----
type=PROCTITLE msg=audit(03/13/20 11:26:20.408:35) : proctitle=/lib/systemd/systemd-logind 
type=SYSCALL msg=audit(03/13/20 11:26:20.408:35) : arch=x86_64 syscall=fstat success=yes exit=0 a0=0x13 a1=0x7ffe30a64fe0 a2=0x7ffe30a64fe0 a3=0x0 items=0 ppid=1 pid=531 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=systemd-logind exe=/usr/lib/systemd/systemd-logind subj=system_u:system_r:systemd_logind_t:s0 key=(null) 
type=AVC msg=audit(03/13/20 11:26:20.408:35) : avc:  denied  { getattr } for  pid=531 comm=systemd-logind path=/etc/shadow dev="vda1" ino=131425 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:object_r:shadow_t:s0 tclass=file permissive=1
```

**Questions**
 > Is this expected?
>  If denied (e.g. by SELinux) are there any failures to expect?

**Steps to reproduce the problem**
> boot

**Comment by arvidjaar** [comment]
> Is this expected?

My understanding is that if `systemd-userdb.service` is not available, `systemd-logind` falls back to reading `/etc/shadow` directly. What `systemctl status systemd-userdb.service systemd-userdb.socket` says?

**Comment by mbiebl** [comment]
We don't enable userdb in Debian.

**Comment by mbiebl** [comment]
What information exactly does logind need from /etc/shadow (and why)?

**Comment by arvidjaar** [comment]
> What information exactly does logind need from /etc/shadow

I do no think it needs anything (at least for now). It comes as side effect of getting full `UserRecord`. that's all.

**Comment by poettering** [comment]
I tries to use getspnam() to get account info if possible, and falls back gracefully if it cannot. It's the code that synthesizes new-style records from NSS.

shadow contains a lot of info besides the password, such as account enable/disable state and so on. Its information we are generally interested in, and shouldn't be subject to additional access controls, like the password itself.

**Comment by arvidjaar** [comment]
> shadow contains a lot of info besides the password, such as account enable/disable state and so on.

And what exactly is required by `logind`?

**Comment by poettering** [comment]
Fix waiting in #15377

**Comment by poettering** [comment]
> > 
> 
> And what exactly is required by `logind`?

Nothing specific, but the existing code tried to get shadow info and gracefully degrades to make things simple. Of course, MACs naively think that any attempt to read a file like this is already a break-in attempt, even though it's just easier to gather the info together from the various sources at once and combining them instead of finely tweaking on each lookup what fields we need and what fields we do not need.

**Comment by poettering** [comment]
> We don't enable userdb in Debian.

Note that realistically it only makes sense to enable both userdb and homed together, or neither. Enabling one but not the other is mostly a theoretic excerise...

The purpose of systemd-userdb.service is to make NSS queries safer by running them out of process and to make userdb simpler for clients by not requiring client side support for merging userdb data or converting NSS. but all this only makes sense if you actually care about homed. if you don't care about homed there's currently no point in enabling userdb, since nothing else but lognd and homed use it....

Hence, either disable both, or enable both. Everything else is just a source of bugs with no real benefit.

**Comment by mbiebl** [comment]
The Debian package disables both (homed, userdb) for the time being.
