### ISSUE TITLE
Unable to start user session when logged in as active directory user on systemd 245

### ISSUE THREAD

**Issue by dtwood** [systemd/systemd#15149]
Unable to start user session when logged in as active directory user

```
$ systemctl --version
systemd 245 (v245~rc1-4.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

Used distribution:
```
$ head -n 7 /etc/os-release
NAME=Fedora
VERSION="32 (Thirty Two)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Thirty Two)"
```

Expected (Fedora 31)

```
$ loginctl show-user $(id -u)
UID=14017
GID=100
Name=$USER@$AD_DOMAIN
Timestamp=Tue 2020-03-17 19:24:11 GMT
TimestampMonotonic=83671999059
RuntimePath=/run/user/14017
Service=user@14017.service
Slice=user-14017.slice
Display=16
State=active
Sessions=16
IdleHint=no
IdleSinceHint=1584473648404559
IdleSinceHintMonotonic=84269064636
Linger=yes
$ loginctl show-session 16
Id=16
User=14017
Name=$USER@$AD_DOMAIN
Timestamp=Tue 2020-03-17 19:27:15 GMT
TimestampMonotonic=83855967683
VTNr=0
TTY=pts/4
Remote=yes
RemoteHost=172.18.18.113
Service=sshd
Scope=session-16.scope
Leader=42799
Audit=16
Type=tty
Class=user
Active=yes
State=active
IdleHint=no
IdleSinceHint=1584473656404559
IdleSinceHintMonotonic=84277064636
LockedHint=no
$ loginctl --version
systemd 243 (v243.7-1.fc31)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

Log output:
```
Mar 17 19:27:15 $MACHINE sshd[42799]: Accepted publickey for $EMAIL from 172.18.18.113 port 10659 ssh2: ED25519 SHA256:XeuQh0yMEWO8fHFI+ru9O+nNf/3iiopIjPnZncIkjFs
[...]
Mar 17 19:27:15 $MACHINE systemd-logind[745]: New session 16 of user $USER@$AD_DOMAIN.
Mar 17 19:27:15 $MACHINE systemd[1]: Started Session 16 of user $USER@$AD_DOMAIN.
Mar 17 19:27:15 $MACHINE sshd[42799]: pam_unix(sshd:session): session opened for user $EMAIL by (uid=0)
Mar 17 19:27:15 $MACHINE sshd[42799]: pam_lastlog(sshd:session): username too long, output might be inaccurate
[...]
Mar 17 19:36:09 $MACHINE systemd[1]: session-16.scope: Succeeded.
Mar 17 19:36:09 $MACHINE sshd[42801]: Disconnected from user $EMAIL 172.18.18.113 port 10659
Mar 17 19:36:09 $MACHINE systemd-logind[745]: Session 16 logged out. Waiting for processes to exit.
Mar 17 19:36:09 $MACHINE sshd[42799]: pam_unix(sshd:session): session closed for user $EMAIL
Mar 17 19:36:09 $MACHINE systemd-logind[745]: Removed session 16.
```

Actual:
```
$ loginctl show-user 14017
Failed to get user: User ID 14017 is not logged in or lingering
$ loginctl list-users
No users.
$ loginctl --version
systemd 245 (v245~rc1-4.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

Log output:
```
Mar 17 19:46:38 $MACHINE sshd[52687]: Accepted publickey for $EMAIL from 172.18.18.113 port 11101 ssh2: ED25519 SHA256:XeuQh0yMEWO8fHFI+ru9O+nNf/3iiopIjPnZncIkjFs
[...]
Mar 17 19:46:38 $MACHINE sshd[52687]: pam_systemd(sshd:session): Failed to get user record: Invalid argument
Mar 17 19:46:38 $MACHINE sshd[52687]: pam_unix(sshd:session): session opened for user $EMAIL by (uid=0)
Mar 17 19:46:38 $MACHINE sshd[52687]: pam_lastlog(sshd:session): username too long, output might be inaccurate
[...]
Mar 17 19:47:27 $MACHINE sshd[52689]: Received disconnect from 172.18.18.113 port 11101:11: disconnected by user
[...]
Mar 17 19:47:27 $MACHINE sshd[52689]: Disconnected from user $EMAIL 172.18.18.113 port 11101
Mar 17 19:47:27 $MACHINE sshd[52687]: pam_unix(sshd:session): session closed for user $EMAIL
```

This also leads to some more critical things being missing, for example `/run/user/14017` does not get created.

It looks like the EINVAL is coming from `acquire_user_record`/`userdb_by_name`/`valid_user_group_name_compat`/`valid_user_group_name_full`, although I'm not sure what it should be doing there.
POSIX disallows `@` in a username, but it's how all the AD usernames will be represented.

A few other bits of output:
```
$ sudo userdbctl user 14017
   User name: $USER@$AD_DOMAIN
 Disposition: regular
    Login OK: yes
 Password OK: yes
         UID: 14017
         GID: 100 (users)
 Aux. Groups: (can't acquire: Invalid argument)
   Real Name: David Wood
   Directory: /home/$USER
     Storage: classic
       Shell: /bin/csh
   Passwords: none

$ sudo userdbctl user $EMAIL
Failed to find user $EMAIL: Invalid argument

$ sudo userdbctl user $USER@$AD_DOMAIN
Failed to find user $USER@$AD_DOMAIN: Invalid argument

$ sudo userdbctl user $NB_DOMAIN\\$USER
Failed to find user $NB_DOMAIN\$USER: Invalid argument

$ sudo cat /etc/sssd/sssd.conf
sudo cat /etc/sssd/sssd.conf
[sssd]
domains = $AD_DOMAIN
config_file_version = 2
services = nss, pam

[domain/$AD_DOMAIN]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = $AD_DOMAIN
realmd_tags = manages-system joined-with-adcli
id_provider = ad
fallback_homedir = /home/%u@%d
ad_domain = $AD_DOMAIN
use_fully_qualified_names = True
ldap_id_mapping = False
access_provider = simple
simple_allow_users = $USER
simple_allow_groups = Linux-Admins
krb5_renew_interval = 3600
auth_provider = ad

[pam]
```

**Comment by yrro** [comment]
Re: the duplicate bug filed--I wanted to point out that the warning printed out by `valid_user_group_name_full` isn't useful. My systems have to consume what they've given by Active Directory, which has the following length limits:

 * Person's SAM-Account-Name: 20 characters
 * Group's SAM-Account-Name: 256 characters
 * Domain's DNS domain name: 255 characters

In the default configuration, FreeIPA/sssd with a cross-forest trust to AD constructs POSIX user/group names thus: `concat(SAM-Account-Name, '@', DNS domain name)`. So you can end up with user/group names of 276 and 512 characters! SAM-Account-Name can also contain spaces and other odd characters too...

**Comment by yrro** [comment]
FYI, I'm using this patch to make the username check less restrictive:

```diff
diff --git a/src/basic/user-util.c b/src/basic/user-util.c
index a491f55..7c416a3 100644
--- a/src/basic/user-util.c
+++ b/src/basic/user-util.c
@@ -723,21 +723,14 @@ bool valid_user_group_name_full(const char *u, bool strict) {
             u[0] != '_')
                 return false;
 
-        bool warned = false;
-
         for (i = u+1; *i; i++) {
                 if (((*i >= 'a' && *i <= 'z') ||
                      (*i >= 'A' && *i <= 'Z') ||
                      (*i >= '0' && *i <= '9') ||
-                     IN_SET(*i, '_', '-')))
+                     IN_SET(*i, '_', '-', '@', ' ')))
                         continue;
 
                 if (*i == '.' && !strict) {
-                        if (!warned) {
-                                log_warning("Bad user or group name \"%s\", accepting for compatibility.", u);
-                                warned = true;
-                        }
-
                         continue;
                 }
 
```

**Comment by dtwood** [comment]
A workaround I’ve found at https://bugzilla.redhat.com/show_bug.cgi?id=1815412 - edit /etc/sssd/sssd.conf and set `use_fully_qualified_names = False`.

Remember (as I didn’t) to change the username in /etc/groups after.

**Comment by poettering** [comment]
Is your UNIX user really called `$USER@$AD_DOMAIN`?

See POSIX:

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_437
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282

Neither `$` nor `@` are allowed in user names. It's very weird that AD asks for that, it's hardly surprising this blows up at various places, no? How do you expect MTAs to handle such usernames?

I am sorry, but in particular usernames with '$' look a lot like a break-in attempt to me, i.e. some attempt to somehow exploit variable expansion in some layer of the stack...

**Comment by yrro** [comment]
> Is your UNIX user really called $USER@$AD_DOMAIN?

Not literally; in my case it's `sam.morris@ad.domain.example`.

Background information: several AD domains can be federated into a 'forest', and a user object's SAM-Account-Name is only unique within a domain. Thus, `sssd` combines the SAM-Account-Name and the domain's DNS domain name to create a human-readable user name that is both unique across a forest, and that does not clash with any locally defined system accounts, or user accounts defined within a FreeIPA or other LDAP directory.

(For reference, @dtwood appears to be making use of the 'direct integration (with SSSD)' setup whereas I'm using the 'indirect integration (based on cross-forest trust with AD)' scenario. These scenarios are described here: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/planning_identity_management/planning-integration-with-ad_planning-dns-and-host-names)

> Neither $ nor @ are allowed in user names. It's very weird that AD asks for that, it's hardly surprising this blows up at various places, no?

AD itself isn't asking for that; it's an implementation detail of how SSSD projects a view of the users within an AD forest to the Linux systems that want to consume it.

Please note that SSSD's `use_fully_qualified_names` option is that user names will no longer be unique across a forest and between the forest and local users or users defined within a directory. In addition, making this change is hugely disruptive in an existing deployment. Finally, it still doesn't solve the problem of the SAM-Account-Name permitting other characters that are not within in the Portable Filename Character Set.

I don't know of any particular problems caused by `@` in a user name. `$` I can't speak of because I haven't run into such names in the wild. It's worth noting however that computer objects within AD end with `$`. This is probably not relevant here but it is useful to know this when trying to construct a Kerberos Service Principal Name as part of authenticating to a service on a particular host.

> How do you expect MTAs to handle such usernames?

I don't. Our email is managed by the Windows folks. ;)

**Comment by poettering** [comment]
So, they insert `@` into user names (the `$` I understand was just your way of hiding the actual domain/user name used in this github issue?). Still, very much outside of POSIX, and a very poor choice given that `@` is used typically with user names in other contexts already... I mean, email addresses use it, and yuck, my frickin bash prompt spells out "lennart@iota" already, so if my user name was "lennart@foobar" it would show "lennart@foobar@iota"? that's just confusing, broken, and prone to issues like this one. What were the sssd people thinking? it's not that hard to come up with a different way to separate an AD username from its domain, that is less likely to explode everywhere... i.e. double underscore "__" or so, and it would very well be in the realm of posix that way... @simo5, any chance sssd can be fixed?  does sssd enforce any limits on usernames at all? i.e. can i have umlauts and emojis in usernames in sssd? spaces, commas?

grmbl.

**Comment by simo5** [comment]
@poettering I do not think this default can be changed now, it has been used this way for 8 to 10 years, since I first created this notation. SSSD does make it configurable.
And it is not like this was done for fun, there were many, many things to consider and other separators were often already taken for other uses. I am pretty sure using '@' is much better than using '\' like Winbind does when using the FLATNAME\user form (which SSSD can use if the user wants to).

The reason @ was chosen is that kerberos principals already use it and often that is the same as the email address as well in Windows domains. so simo@AD.TEST would be my realm, and simo@ad.text would be my email, and it can be my login as well (SSSD also allows you to log in with your email for example, and then will feed the system whatever name is configured in sssd, which could be completely different).

The other reason is that there are very few characters that are not allowed as Windows names, where even spaces are allowed. And @ is one of them exactly because it is used as a separator in contexts like email. Although '@' was not perfect it was definitely much better than having to mangle names. For example using _ in names is pretty common in Windows deployments so definitely that was never an option on the table.
As for emojis... yes I believe Windows account name could have those, they are unicode strings after all. Of course if you use them ... well you get an 'interesting' experience.

**Comment by simo5** [comment]
@poettering note that also group names will be fully qualified if needed, and can also have spaces and emojis I guess.
Please do not step over characters that have been used forever in setups that cannot be changed now.

**Comment by poettering** [comment]
Fix waiting in  #15352.

That PR contains a longer document explaining the restrictions on user names we make. PTAL.

**Comment by yrro** [comment]
#15352 works for me - thanks

**Comment by abbra** [comment]
@poettering please note that fully qualified user names are the norm in integration with Active Directory for the last two decades. I added ability to use non-qualified user names via winbindd in Samba circa 2003 and it was one of most horrible design decisions I made: even though it was one of most requested by the users, the whole change produced so many bugs that we still keep dealing with them in both Samba and SSSD which adopted the fully-qualified approach from its inception.

The biggest dilemma you deal with is that you have to handle multiple Active Directory domains. Active Directory has a number of predefined users and groups that have the same name within each domain but would be mapped to totally different UID/GID (because they are different, even in Active Directory). Using fully-qualified version is the only way to differentiate them on Linux and other non-Windows environments.

If you want more details on the problem domain, feel free to contact me separately. Current comments in the code demonstrate that there is certain lack of understanding of the problem domain, sadly.
