### ISSUE TITLE
NetClass option doesn't mark packets

### ISSUE THREAD

**Issue by morfikov** [systemd/systemd#1522]
There's the following info concerning the 227 version of systemd:

```
    * Support for the "net_cls" cgroup controller has been added.
      It allows assigning a net class ID to each task in the
      cgroup, which can then be used in firewall rules and traffic
      shaping configurations. Note that the kernel netfilter net
      class code does not currently work reliably for ingress
      packets on unestablished sockets.

      This adds a new config directive called NetClass= to CGroup
      enabled units. Allowed values are positive numbers for fixed
      assignments and "auto" for picking a free value
      automatically.
```

That's really great, but I was unable to mark any packet using `NetClass=` option. I just wanted to know if I did everything right, or whether this feature doesn't work at all.

I have one service that already utilizes some cgroups attributes, and the service works as expected:

```
# systemctl status qbittorrent-nox.service
● qbittorrent-nox.service - qbittorrent-nox
   Loaded: loaded (/etc/systemd/system/qbittorrent-nox.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2015-10-10 00:54:24 CEST; 12h ago
     Docs: man:qbittorrent-nox
 Main PID: 1694 (qbittorrent-nox)
   Memory: 49.9M (limit: 50.0M)
      CPU: 2min 47.318s
   CGroup: /p2p.slice/qbittorrent-nox.service
           └─1694 /usr/bin/qbittorrent-nox

Oct 10 00:54:24 morfikownia systemd[1]: Started qbittorrent-nox.
```

There's a limit of memory set via the `MemoryLimit=50M` option in the service file as you can see. But when I add the `NetClass=5` option to the file, nothing happens. I mean when I issue the following commands:

```
# systemctl daemon-reload
# systemctl restart qbittorrent-nox.service
```

some directories are created under `/sys/fs/cgroup/net_cls,net_prio/` and there's one that matches the service: `/sys/fs/cgroup/net_cls,net_prio/p2p.slice/qbittorrent-nox.service/` . Pids were added to the `tasks` file:

```
# cat /sys/fs/cgroup/net_cls,net_prio/p2p.slice/qbittorrent-nox.service/tasks
84545
84555
84556
84557
```

But there's `0` set in the `net_cls.classid` file:

```
# cat /sys/fs/cgroup/net_cls,net_prio/p2p.slice/qbittorrent-nox.service/net_cls.classid
0
```

So it looks like the mark wasn't set at all:

```
# cat /proc/net/nf_conntrack | egrep "mark=5" |wc -l
0
```

**Comment by zonque** [comment]
Does it set the net_cls.classid value if you `stop` and `start` the service, instead of restarting it?

Note that the netfilter code to match against cgroup class IDs is currently buggy for ingress packets and doesn't work reliably. That's a known bug, and we're working on a (kernel-side) solution for that. For egress (outgoing), it should however work just fine. However, nf_conntrack is unrelated to that.

**Comment by morfikov** [comment]
No, it doesn't set marks in that way either, it's always 0.
I know that it doesn't work well for ingress traffic, but I really need it for egress traffic.

`NetClass=auto` also doesn't work.

**Comment by ghost** [comment]
Same for pids.max, also does not work

**Comment by poettering** [comment]
if you strace pid 1, and then use "systemctl set-property" to dynamically alter these settings, do you see the write access to the attributes in the strace output?

**Comment by ghost** [comment]
Yes for TasksMax that seems to work:

systemctl set-property sshd.service TasksMax=31337

open("/sys/fs/cgroup/pids/system.slice/sshd.service/pids.max", O_WRONLY|O_NOCTTY|O_CLOEXEC) = 16
fcntl(16, F_GETFL)                      = 0x8001 (flags O_WRONLY|O_LARGEFILE)
fstat(16, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(16, "31337\n", 6)                 = 6
close(16)                               = 0

cat /sys/fs/cgroup/pids/system.slice/sshd.service/pids.max
31337

For netclass though it returns:

systemctl set-property sshd.service NetClass=auto
Unknown assignment NetClass=auto

**Comment by ghost** [comment]
I suspect that TaskMax= might work, but not if you simply restart the service

i added TasksMax= to sshd.service and did a systemctl restart sshd.service and the whole /sys/fs/cgroup/pids/system.slice/sshd.service was no longer there...

Then i rebooted and there were no directories in /sys/fs/cgroup/pids/system.slice/ at all...

then i removed the TasksMax from sshd.service , rebooted again and /sys/fs/cgroup/pids/system.slice/ is still not populated with dirs ...

I think i corrupted this system because sys/fs/cgroup/pids and others are now no longer populated with dirs no matter what i do (just a few files in there)

**Comment by ghost** [comment]
Naw, TaskMax only works via systemctl set-property, it is not honored via service units

**Comment by morfikov** [comment]
I just get the following output:

```
# systemctl set-property qbittorrent-nox.service NetClass=5
Unknown assignment NetClass=5.
```

It works just fine with the `MemoryLimit=60M`

**Comment by poettering** [comment]
The TasksMax= thing should work now, with PR #1568 applied.

The NetClass= property was actually never intended to be dynamically writable, sorry for the confusion around that (i.e systemctl set-property is not supposed to work for it). 

Anyway, we still need to figure out why NetClass isn't actually applied to the cgroupfs. @morfikov when you do "systemctl show -p NetClass" on your service, what does it say?

**Comment by morfikov** [comment]
```
# systemctl show -p NetClass qbittorrent-nox.service
NetClass=0
```

Even though there's `NetClass=5` set in the service file.

**Comment by DSpeichert** [comment]
I've been fighting with the same issue until I found this report. Indeed NetClass is not set. Also, it's not clear whether it should be passed as decimal or hex or what is the translation when it's passed to net_cls.classid.

**Comment by zonque** [comment]
Did you stop and start the service again? On the kernel level interface, it doesn't matter whether you pass it as hex or dec. systemd does it in decimal.

However, note that with the unified architecture, this controller is likely going away, and netfilter rules are supposed to specify the full cgroup path. Even though the kernel code will fall back to compat mode if net_cls.classid is set, this is undesirable.

The code for this has already landed in the kernel during the merge window of 4.5, so systemd will be required to drop the NetClass= code again any time soon. This is unfortunate, because the idea was to pave the road towards per-unit netfilter rules with this, but it turns out merging the support on our side was premature.

**Comment by DSpeichert** [comment]
@zonque It was user-N.slice, so I rebooted to make sure. Not only is the setting ignored, if I set the net_cls.classid manually in /sys/fs/cgroup, then when I log in as the user in slice N (thus creating a session under it), the net_cls.classid is reset to 0. That is weird because the slice wasn't just creating, the same user had a lingering user@N.service running all the time.

**Comment by DSpeichert** [comment]
@zonque I noticed that:
a) if remove NetClass=... from slice config file, I can set net_cls.classid manually (in /sys/fs/cgroup/...) and systemd doesn't touch that
b) if I set NetClass=170 (or any other number) in slice config file, systemd sets net_cls.classid to 0 when user logs out and logs back in
c) If I later remove NetClass=170 and do `systemctl daemon-reload`, systemd keep setting net_cls.classid to 0 until reboot

**Comment by poettering** [comment]
Support for NetClass= has been removed from systemd again, see the NEWS file for v229. It has no future in the kernel, hence we shouldn's support this in systemd either. Closing this.

**Comment by Mic92** [comment]
@zonque can you give a pointer, which netfilter module supports to specify the full cgroup path? nftables `meta cgroup`  and iptables cgroup statement are still relying on netclass ids. So is this still on the todo list?
