### ISSUE TITLE
systemd-journald: excessive and hugely abnormal disk IO

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#15292]
I've recently discovered that systemd-journald writes extreme amounts of data to the disk even when there aren't that many events to speak of.

Consider this
```
# journalctl -b | wc -l
4049
# journalctl -b | wc -c
488143
# uptime 
 00:39:34 up 14:35,  0 users,  load average: 0.12, 0.26, 0.24
```
That gives us 4049 writes each about 120 bytes. You'd think that disk IO in this case even if each message is padded to 4096 bytes (which is already excessive) would be around 16MB. In reality systemd-journald writes **over 700MB of data** which is simply insane.

My system info:
Fedora 31 with all updates installed.
systemd-243.7-1.fc31.x86_64

This needs to be improved and fixed. I have an SSD drive which doesn't like to be abused and at the moment systemd-journald is the worst offender in terms of disk writes.

**Comment by vcaputo** [comment]
I don't understand how you're coming to such conclusions based on the number of lines and characters output by `journalctl -b`, could you please explain?

**Comment by birdie-github** [comment]
Conclusions are simple - I'm monitoring `systemd-journald` disk writes.

There are many ways to do that - that's beside the point.

**Comment by vcaputo** [comment]
I don't think you know what you're talking about.

**Comment by birdie-github** [comment]
I perfectly understand what I'm talking about and your comment reeks of elitism or something else which still does not belong to this bug tracker.

During the last 14 hours of uptime systemd-journald has generated over 700MB of disk writes, while its log is around 500KB. I would love systemd-journald disk writes to be optimized because this discrepancy is simply insane.

**Comment by vcaputo** [comment]
Please copy and paste what commands you're using to measure this, attach graphs, or whatever it is you're using to inform these conclusions.

In lieu of evidence backing your claims, I will continue to assume you do not know what you're talking about.  It's a baseless claim without proof.

Walking you through the process of properly measuring and characterizing journald's behavior in the event that you indeed do not know what you're talking about amounts to technical support.  This is not a support forum, try the systemd mailing list or your distribution vendor for that.

If you do know what you're talking about, you'll have zero difficulty facilitating better information properly characterizing the issue.  Thus far you have not, and you would know better if you did.

**Comment by birdie-github** [comment]
> This is not a support forum, try the systemd mailing list or your distribution vendor for that.

The f you're talking about? I use Fedora 31 whose developers are primarily contributing to systemd and which is using systemd pretty much as is without any additional patches or anything.

> If you do know what you're talking about, you'll have zero difficulty facilitating better information properly characterizing the issue. 

Run `iotop -ao` and see for yourself. God, this is effing embarrassing.

I'm **not** seeking support for f sake. I'm reporting a bug. I've reported over 400 bug reports in various Open Source projects to this date and this is the first time I'm treated this way. What the f?

**Comment by vcaputo** [comment]
You've done nothing to determine journald isn't actually being asked to log precisely what's being written.  If all you're looking at is the write load at the backing store, you're not even seeing the whole picture.

Please stop editing your comments while I'm responding to them, it makes the conversation completely disjointed.

**Comment by birdie-github** [comment]
> You've done nothing to determine journald isn't actually being asked to log precisely what's being written. If all you're looking at is the write load at the backing store, you're not even seeing the whole picture.

I've no idea how systemd-journald works - I'm just reporting what I see. I see 500KB of logs being translated to 700MB of disk writes.

I have the only difference vs. Fedora 31 defaults:
```
/etc/systemd/journald.conf.d/systemMaxUse.conf
[Journal]
SystemMaxUse=64M
```

That's it. No other options have been changed in any shape or form.

**Comment by birdie-github** [comment]
If you're interested, I can upload my entire log file for this session somewhere but it'll take quite some time because I'll have to strip it off any personally identifiable information (e.g. MAC addresses, UIDS, etc. etc. etc.)

**Comment by birdie-github** [comment]
```
# rpm -V systemd
.M.......  c /etc/machine-id
.M.......  g /var/log/btmp
.M....G..  g /var/log/journal
```

`/etc/systemd/journald.conf.d/systemMaxUse.conf` is the only extra file that I have in `/etc/systemd`.

**Comment by poettering** [comment]
This is not actionable. Please provide information how you measure this in detail, in a way that clearly matches this to the journal. Otherwise we'll have to close this.

**Comment by birdie-github** [comment]
Under root:

Terminal 1: `iotop -ao`
Terminal 2:`echo MESSAGE > /dev/kmsg`

`MESSAGE` translates maybe into 64 bytes at most (source, timestamp, etc).

iotop reports **12KB** written to the disk.

**Comment by birdie-github** [comment]
Another way to verify that.

```
# journalctl -b | wc -c
209518
# journalctl -b | wc -l
1955
# awk '/^write_bytes:/{print $2}' /proc/`pidof systemd-journald`/io
11161600
```

Compare 200KB in the journal and 11MB flushed to the disk.

**Comment by poettering** [comment]
well, iotop isn't a useful tool for this, we don't know what fs you have and what it does. a single byte of IO will necessarily explode into a lot more IO given that file systems need to update all kinds of accounting data too. I mean, just do your test with a simple "echo -n x > bar ; sync" and see how that explodes.

The /proc/$PID/io counter is not really suitable for this kind of testing, it's not clear what precisely it accounts. Moreover its a counter for all IO journald ever did, i.e. including the tmpfs flushing and stuff...

On top of that, "journalctl -b" gives you a condensed output. What is stored on disk is much more, i.e. all kinds of structered metadata. Use "journalctl -o verbose" to see the more complete data.

I am sorry, but the tools you are using are not suitable for determining journald's IO load. At least, use IOAccounting=yes in the journald unit file, but that too is misleading, since this includes fs overhead and stuff...

**Comment by birdie-github** [comment]
ext4, no journal. Reproducible under any VM under a minute. No one cares.

**Comment by ValdikSS** [comment]
Well, I tend to believe @poettering: what you see is most likely write amplification, not a real journald issue.

>I mean, just do your test with a simple "echo -n x > bar ; sync" and see how that explodes.

ext4 (with journal) has about 4-6x write amplification on small writes.

**Comment by vcaputo** [comment]
No one cares because it's expected that filesystems (and whatever other block layers like lvm/dmcrypt are in the mix) add overhead.

Nobody expects a write of 100 bytes into a file to be reflected as 100 bytes written at the backing store.

100 bytes get written, the kernel's page cache turns it into one or even two pages when straddling a page boundary, at a minimum.  Then the filesystem has its own preferred IO unit size, and add whatever bookkeeping and metadata overhead it adds.  I presume encryption like dmcrypt adds even more metadata overhead and maybe even further enlarges IO block size.

This issue is as @poettering said not actionable.  It amounts to shouting "the sky is falling!" without sufficient data to back the claim let alone attribute blame on a specific component like journald.

The machine I'm typing this on runs journald, has a disk activity light, and that light is dark.  The sky is not falling from where I'm sitting.

**Comment by ValdikSS** [comment]
Also remember that journald uses hash tables. Updating hash tables amplifies writes as well.

>1 hash table entry per 768 bytes of journal file
https://github.com/systemd/systemd/blob/199f75205b9c0625bf56e229b12b95a645ed7a6c/src/journal/journal-file.c#L1091

Compression, which is enabled by default, may also negatively affect small writes. Try to disable it (`Compress=no` in journald.conf).

journald uses mmap'ed files, so it's not possible to monitor what exactly does it write with tools like strace. However you can monitor page faults, which kind of allows to see what it writes with `$ sudo perf trace -F -p  $(pidof systemd-journald)`.

**Comment by vcaputo** [comment]
> Also remember that journald uses hash tables. Updating hash tables amplifies writes as well.

If anything it's the entry array objects, because every recurring unique data object gets indexed by its own chain of them.

The hash tables are allocated once up front as initialization, it's not an ongoing overhead besides the little linked list updates consisting of 8-byte offsets.

**Comment by vcaputo** [comment]
Another thing to consider is journald will immediately fsync() any time a critical/emergency message is logged, which will defeat the page cache's buffering of writes.

https://github.com/systemd/systemd/blob/v247/src/journal/journald-server.c#L1667

**Comment by sharma-gauri** [comment]
Hi There,

**Comment by poettering** [comment]
Actionable data, with a more appropriate tool than "iotop" was never provided. let's close this here.

If you can provide data that shows that journald's own file system writes are that terrible (and not the block IO the file system makes of it), please report back and we can reopen. iotop is not a suitable tool for this Also note that journald uses mmap() access to journal files, which means you can't just strace it either. You basically need to track file system backed pages that journald dirties, to get an accurate understanding of how much it actually writes.

Or to say this differently: write amplification by the fs is hardly under journald's control, and due to lazy allocation and stuff might vary wildly. In particular for smaller writes (like journald does them frequently) the noise added through that is massive. If you write more data the write amplification has less of an effect, and then iotop can be a useful tool again.

Anyway, let's close. Please come back with better data, if that still shows a problem!

(Note I am not denying that there's room for improvement here. I *know* there is. I am just saying that things aren't as bad as you make them to be, and that#s because the tooling you used is highly misleading for this case.)

**Comment by sehraf** [comment]
FWIW i have the same symptoms in a systemd-nspawn container running on btrfs, luks and mdadm. Journald causes GBs of writes based on iotop.
My fix was rather simple: configure journald.conf `Storage=volatile` (or none). I don't need the logs to be stored anyway.

**Comment by ChristopheBernard** [comment]
Thanks @sehraf. Good to know.

I tried this, only to see that the disk activity did not decrease and that now ext4lazyinit was flagged by iotop as a culprit.

So in my instance, ext4lazyinit might have been the main culprit, as suggested above.

**Comment by pablobass** [comment]
> I've recently discovered that systemd-journald writes extreme amounts of data to the disk even when there aren't that many events to speak of.
> 
> Consider this
> 
> ```
> # journalctl -b | wc -l
> 4049
> # journalctl -b | wc -c
> 488143
> # uptime 
>  00:39:34 up 14:35,  0 users,  load average: 0.12, 0.26, 0.24
> ```
> 
> That gives us 4049 writes each about 120 bytes. You'd think that disk IO in this case even if each message is padded to 4096 bytes (which is already excessive) would be around 16MB. In reality systemd-journald writes **over 700MB of data** which is simply insane.
> 
> My system info: Fedora 31 with all updates installed. systemd-243.7-1.fc31.x86_64
> 
> This needs to be improved and fixed. I have an SSD drive which doesn't like to be abused and at the moment systemd-journald is the worst offender in terms of disk writes.

Did you have any type of RAID configured using MDADM?

I notice same issue as you and realize it's when mdadm resync. Don't know why it's resyncing cause nothing obvious happend, but it is, and I only have to wait to finalize to get back to normal IO.

**Comment by kanehekili** [comment]
Same problem here. Herr Poettering is a narcissus. He doesn't make any mistakes. I still admire some of his code. But you can't criticize anything he does. Tim Pritlow made a pretty good podcast about [him](https://cre.fm/cre209-das-linux-system). Decide for yourself...

**Comment by birdie-github** [comment]
> Did you have any type of RAID configured using MDADM?

Nope, a normal GTP ext4 partition with journalling turned off.

> ...

@kanehekili 

Let's keep it friendly guys. You've got the source code - you can always study it, improve it and send patches.

**Comment by madhatter0** [comment]
Just as another datum, I, too, ran into this problem.  The full analysis and writeup can be found at https://www.teaparty.net/technotes/debian-slow.html but in short it was fixed by changing to `Storage=volatile` .

In passing, and in response to the comments deriding iotop's diagnostic utility, I note that although the point about FS write amplification is fair, it will either apply to all applications equally (in which case iotop is still a useful tool for comparing the write load of the various things running on the system), or there is something particular about systemd-journald that is particularly powerfully affected by FS write amplification (in which case this bug report is completely valid).

**Comment by ValdikSS** [comment]
https://github.com/systemd/systemd/issues/40262#issuecomment-5169482357
