### ISSUE TITLE
Can not set time before build time

### ISSUE THREAD

**Issue by blochl** [systemd/systemd#15320]
**systemd version the issue has been seen with**
> 244

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > System time synced with the hardware RTC clock, no matter what time it reports.

**Unexpected behaviour you saw**
 > System time set to build time, with a log message `System time before build time, advancing clock.`

**Steps to reproduce the problem**
> 1. Set the RTC to some time several months in the past.
> 2. Boot the system.

For some testing scenarios the system time needs to be set few months/years in the past _via_ the RTC. Systemd seems to not allow this. Is there a way to overcome it without changing the systemd code [here](https://github.com/systemd/systemd/blob/50f5e2e2817d3435a1d6c0ce0d434efe5dcc2748/src/shared/clock-util.c#L153)?

**Comment by poettering** [comment]
There's not, besides recompiling systemd with the TIME_EPOCH meson build variable set to something else.

I am not convinced we should lift this restriction upstrea though

**Comment by blochl** [comment]
Thanks for your answer, @poettering! Meanwhile I have found a way to circumvent this for my needs with a few tweaks in the kernel. Please feel free to close this, if you think it's not worth an upstream solution.

**Comment by keszybz** [comment]
Yeah, I think using some low-level tool to set the clock is better. We don't need to support this at the higher level that the tooling in systemd provides.

**Comment by alien999999999** [comment]
For some specific purposes, i'd like to have some system run in the past, and even though the rtc is set in the past, it gets skewed... it would be great if there was a kernel option to just not do this... systemd.advance_time=0 or something.

On another system that runs on nfs (without any rtc: an rpi4), the dhclient is started after the system time is advanced, but before ntpd, but the nfsroot lease is still from 1970, which means the dhclient gets confused, sticks with the faulty lease from a year ago and then 2h after boot, the lease runs out and due to nfsroot the system hangs... here too this kernel parameter would be great... because dhclient knows about epochtime and not about the build time of systemd...

**Comment by alien999999999** [comment]
btw: for this 2nd system, i'm trying to touch /usr/lib/clock-epoch at ntpd shutdown, so the advancing system clock would be more recent and have higher change of being close enough (time-wise), but that didn't seem to work? does this still work? there is not a lot of documentation on this...

**Comment by alien999999999** [comment]
I'm giving up, trying to boot the nfs and get it set as static ip, so the dhclient doesn't kill the network after a few hours...
Trying to get static ip using kernel arguments, but it doesn't work, the default and `ip=eth0:dhcp` work, but all the `ip=10.A.B.244::10.A.B.1:255.255.255.0:host.dom.tld:eth0:{dhcp,none,off} nameserver=10.A.B.1` just doesn't work...?

**Comment by alien999999999** [comment]
i guess i'll have to just increase lease time to more than 25h and reboot each night or something... man all this crap is one hack after another... why doesn't documented stuff work?

**Comment by alien999999999** [comment]
getting weirder: switched back to dhcp and now there is a:

inet 200.0.0.0/24 brd 200.0.0.255 scope global eth0 on this interface? before the dhcp one even? where does this even come from???

**Comment by mozo78** [comment]
Please allow us to set time before build time.
