### ISSUE TITLE
[systemd-nspawn] resolv-conf-setup fails with resolved guest in stub-mode

### ISSUE THREAD

**Issue by WolleTD** [systemd/systemd#15340]
I recently started moving my DNS confiurations to `stub-resolv.conf` and I am using `systemd-nspawn` in automatic image building. However, when symlinking `/etc/resolv.conf` to `/run/systemd/resolve/stub-resolv.conf` in the guest filesystem, copying or mounting anything fails as the `resolve` directory is non-existent and name resolution in the container fails.

**systemd version the issue has been seen with**
> 245.4

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > DNS resolving inside of the container works

**Unexpected behaviour you saw**
 > DNS resolving doesn't work and no resolv.conf is copied or mounted

**Steps to reproduce the problem**
1. Create guest filesystem and `ln -sf /run/systemd/resolve/stub-resolv.conf`
2. `systemd-nspawn -D $rootfs`
3. `ping www.google.de` or sth.
4. Result: `ping: www.google.de: Temporary failure in name resoluton`

Apparently, `setup_resolv_conf()` fails on `chase_symlinks()` with `Failed to copy /etc/resolv.conf to $rootfs/etc/resolv.conf, ignoring: Too many levels of symbolic links`, which seems odd.

**Comment by poettering** [comment]
Not sure I grok the problem?

Hmm, how exactly does /etc/resolv.conf look like in the image before you invoke nspawn on it?

How precisely to you invoke nspawn (cmdline, …)?

Is this something you can work around with --resolv-conf=?

Can you provide an "strace -s 500 -f -o log" excerpt of the nspawn invocation's boot phase, so that we can grok what is going on?

**Comment by WolleTD** [comment]
I got two cases:
```
$ readlink ${image}/etc/resolv.conf
/run/systemd/resolve/stub-resolv.conf
$ readlink -f ${image}/etc/resolv.conf
/run/systemd/resolve/stub-resolv.conf
```
This is the Ubuntu 18.04 default configuration, I just stumbled upon this half an hour ago:
```
$ readlink ${image}/etc/resolv.conf
../run/systemd/resolve/stub-resolv.conf
$ readlink -f ${image}/etc/resolv.conf
${image}/run/systemd/resolve/stub-resolv.conf
```

Both result in identical behaviour. I simply run `systemd-nspawn -D ${image}`.

--resolv-conf doesn't change anything either. While copy-host and copy-static fail silently (`/etc/resolv.conf` is still a symlink to a nonexistent file), bind-host and bind-static result in a mount error:
```
Failed to mount {/etc|/usr/lib/systemd}/resolv.conf (type n/a) on ${image}/run/systemd/resolve/stub-resolv.conf (MS_BIND ""): No such file or directory
```
delete works, but is pointless.

strace for both relative and absolute symlinks:
[strace-absolute.log](https://github.com/systemd/systemd/files/4444365/strace-absolute.log)
[strace-relative.log](https://github.com/systemd/systemd/files/4444334/strace-relative.log)

Running with `SYSTEMD_LOG_LEVEL=debug`:
[systemd-debug.log](https://github.com/systemd/systemd/files/4444389/systemd-debug.log)

```
$ grep /etc/resolv.conf *.log
strace-absolute.log:92804 openat(AT_FDCWD, "/mnt/etc/resolv.conf", O_WRONLY|O_CREAT|O_NOCTTY|O_TRUNC|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ELOOP (Too many levels of symbolic links)
strace-relative.log:91504 openat(AT_FDCWD, "/mnt/etc/resolv.conf", O_WRONLY|O_CREAT|O_NOCTTY|O_TRUNC|O_NOFOLLOW|O_CLOEXEC, 0644) = -1 ELOOP (Too many levels of symbolic links)
systemd-debug.log:Failed to copy /etc/resolv.conf to /mnt/etc/resolv.conf, ignoring: Too many levels of symbolic links
```

**Comment by WolleTD** [comment]
I guess, [`here`](https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn.c#L1895), directory creation is missing. Instead of `touch()`, there should probably be a direct call to `touch_file()` with partents set to true?

**Comment by poettering** [comment]
So if /etc/resolv.conf exists as symlink, nspawn assumes the thing is managed by something smart (such as resolved inside the container) and doesn't want to break things and hence doesn't replace the thing.

I am a bit conservative in wanting to change this behaviour. i.e. if we just blindly replace it with a regular file and then you next boot up the image in qemu or on a physical host, then resolved will be borked for good. Hence, for the automatic, implicit behaviour I think we should only replace the thing when it is a regular file (because that just means staying within the same type of setup, just with fresher data) and not when it is a symlink (because that would mean changing the type of setup).

Hence I think I'll add a new mode --resolv-conf=replace-stub which is like copy-stub but replaces whatever exists regardless what it is. 

A fix for that is waiting in #15516.

Hope that makes sense?

**Comment by yisonPylkita** [comment]
`--resolv-conf=replace-stub` didn't work for me on Ubuntu 20.04 so I ended up with `--resolv-conf=copy-host`

So now my container boot looks like this
```bash
systemd-nspawn -b -D ubuntu_bionic --bind=/dev/fuse --resolv-conf=copy-host
```

**Comment by bowling233** [comment]
For users on Debian 12 and newer, such as myself, `systemd-resolved` is not installed by default (see [Debian Bookworm Release Notes](https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.en.html#systemd-resolved)). As a result, using the `--resolv-conf=replace-stub` option may lead to errors like:

```text
Failed to copy /etc/resolv.conf to /pxe/rootfs/ubuntu/oracular.error/etc/resolv.conf, ignoring: No such file or directory
```

To resolve this, simply install `systemd-resolved` and restart the service. After doing so, the process should work as expected.
