### ISSUE TITLE
'systemctl status <service>' does not obey terminal color palette

### ISSUE THREAD

**Issue by iddinev** [systemd/systemd#15346]
**Is your feature request related to a problem? Please describe.**
When using colored output 'systemctl status <service>' colorizes some of the output (state, triggered by, log messages, etc.). All of the colorized output follows the 16 color terminal palette except for the final systemd status report of the service in case the service startup failed - the color used is hardcoded. 

**Describe the solution you'd like**
It makes sense for this output to also use the terminal palette, as otherwise it won't be clearly visible depending on the terminal background.

**Describe alternatives you've considered**
Not colorizing systemctl's output and changing terminal BGs.

On both attached screenshots the sampled yellow-ish color is from the status report line.
![Screenshot_2020-04-06_13-39-57](https://user-images.githubusercontent.com/11410938/78550674-1de9f000-780d-11ea-8dce-4646b806b5e2.png)
![Screenshot_2020-04-06_13-44-46](https://user-images.githubusercontent.com/11410938/78550680-20e4e080-780d-11ea-8829-f52829e6bb4e.png)

**Comment by poettering** [comment]
See discussion on #13561, #12482, d35305fe83686da819466b573fcdbb8bdaf80813 a9009769de43b7f29d05017f4219e18c1e42a273, bb40c12569d017f75774ff9f4b6fb0ac64f9eee0 and such.

I am not sure we have to reopen the discussion here now.

**Comment by iddinev** [comment]
I read the mentioned issues and I think I'm missing something - what was the purpose of hardcoding colors to fix #12482? You need more than the, usually, available 16 colors to differentiate all the things in the log outputs, or you are aiming for a particular colored look?  Right now some colors are hardcoded, and some are using the 16 color palette - this seems to be the worst of both worlds.
I'm not trying to reopen any discussion, but I am trying to understand where it ended last time.

**Comment by poettering** [comment]
We generally want to use the palette colors, i.e. the 16 ones. As it turns out this desire collides with reality though. It is essential to us that the colors we use are well visible on the most common terminal backgrounds, i.e. on black and on white. Some terminal emulators pick a very unfortunate default palette however where the color is not recognizable one both backgrounds. That sucks hard. So after some consideration we decided to use fixed colors for those cases, which are two types of grey and two types of yellow.

I mean, if individual people pick stupid palettes and things aren't readable for them we don't care to much, but I think we should make sure that the stuff we output should still be recognizable on the default palettes of the major terminal emulators...

So our general goal is sticking to palette colors, except where this doesn't work out IRL.

Hope this makes some sense?

**Comment by iddinev** [comment]
It makes more sense now, thanks for the explanation. 
I don't agree with the 'stupid palettes' part though - color usage is pretty subjective and user specific, I'd reckon that the default backgrounds you mentioned are the least used (or at least - not the most used) of all widely distributed terminal palettes.

In any case - if anybody counts (or cares) - I vote for no color hardcoding, otherwise such issues will probably continue to pop-up from time to time.

Keep up the good work though.

**Comment by poettering** [comment]
@iddinev let's turn this around, we can revert back to using only palette colors if those terminals are fixed. i.e. if you prep pacthes that fix the default palettes of rxvt, xterm, konsole, gnome-terminal and the linux console (where necessary) so that the two grays and two yellows are all recognizable on both black and on white then we can switch back to full palette...

The colors we use are not particularly exotic. it's primarily traffic light colors, i.e. red, green and yellow, to communicate health status. As well as two grays to make stuff like comments/debugs slightly less visible since it's auxiliary info that shouldn't needlessly obstruct the primary information shown. I'd argue that these colors and their meaning are well enough understood universally to warrant that the terminal palette's are carefully tuned to make them visible on both backgrounds. 

Or to say this differently: it's not the crazy exotic colors where the palette sucks, it's the common, important ones... If color is useful at all in terminal output it's for these colors.

**Comment by iddinev** [comment]
I do agree to some extent with this reasoning and see value in it, although I have my arguments to the contrary. 
For the sake of your initial comment on this issue and the fact that you guys probably have better stuff to do than to argue about colors - I won't pursue this discussion further. 
If at some point you decide to (or have the desire/need to) reopen the discussion, I'd be happy to join with a random end user's point of view.

**Comment by poettering** [comment]
My suggestion of fixing those terminal emulators with the sad palette choices is honest btw. I figure the set of patches necessary isn't even that big, and if that's fixed everybody wins and we can revert to palette colors here again.

**Comment by iddinev** [comment]
I will abstain from trying to patch 5 different mature projects, as the patches will definitely be seen as fixing a problem that doesn't exist and/or there will be questions about strange color dependencies between projects that should be independent from one another. Furthermore, even if the respective communities agree, I'll probably have to actively participate in at least one very subjective discussion about what colors should be the default ones.
In the end, as a user of a non stupid (mainly) dark palette, the hassle is not worth it.

**Comment by poettering** [comment]
Well, there's only one way to figure out if that's true. But I think there's a good case to be made here to say that the primary colors should be visible well on both primary backgrounds. Doesn't sound to me as if this was hard to agree with, for the maintainers of those projects.

**Comment by oliverpool** [comment]
Since https://github.com/systemd/systemd/pull/17702 has been merged (released in version 248), you can use set the `SYSTEMD_COLORS` environement variable to `16` to accommodate your palette.

> Various tools now accept SYSTEMD_COLORS=16|256 to configure what colours are used in output.

**Comment by RichardTMiles** [comment]
I just tried using
 `journalctl --all --utc -u  YOUR_SERVICE | ccze`
 
 I installed `ccze` from yum, and it worked better than expected.
