### ISSUE TITLE
resolved/dnssec defaults should be systemd's recommendation

### ISSUE THREAD

**Issue by BryanQuigley** [systemd/systemd#15435]
> 245
> Fedora

**Expected behaviour you didn't see**
 > I expect the systemd defaults to be what is recommended to use.

**Unexpected behaviour you saw**
 > The Fedora project has explicitly stated "Per recommendation from the systemd developers, we will change the default value of this setting in Fedora from the upstream default DNSSEC=allow-downgrade to DNSSEC=no by building systemd with the build option -Ddefault-dnssec=no"
https://fedoraproject.org/wiki/Changes/systemd-resolved#DNSSEC

Why not change the systemd defaults to DNSSEC=no if that is the recommendation?

**Comment by keszybz** [comment]
Systemd is generally not suitable for direct installation on an end-user machine from the upstream. Most users should install systemd from their distribution with the various tweaks and configuration choices made by the distribution to allow systemd to best fit that specific distribution. (For example, whether sysv compat should be provided, what dns servers to use as fallback, and various things like that. In addition, distributions often include workarounds which are not suitable for upstream but necessary because of some quirk in that distro.) Installation of systemd from the upstream is intended for developers and early adopters who are ready to make any tweaks necessary to their machine. The defaults in upstream are geared toward this kind of work. The default of DNSSEC=allow-downgrade is in line with this — to test the code, even though we know that it (and the network infrastructure it uses) is not ready for being enabled on a general-purpose distro.
