### ISSUE TITLE
documentation edit for Random_seeds

### ISSUE THREAD

**Issue by jaypatelani** [systemd/systemd#15434]
The first part (`it neither updates the random seed before using it')in documentation [ https://github.com/systemd/systemd/blob/master/docs/RANDOM_SEEDS.md ]  is no longer true in netbsd-9:

 <http://cvsweb.netbsd.org/bsdweb.cgi/src/sbin/rndctl/rndctl.c?rev=1.30.18.1&content-type=text/x-cvsweb-markup&only_with_tag=netbsd-9>.

**Comment by poettering** [comment]
hmm, the way i read it it's a command you call after boot, it is not capable of updating the random see during boot already, i.e. before it is used.

Updating the seed *after* use leaves you vulnerable, since it means if you can boot up multiple times with the same random seeds (which is a problem) simply by turning off the machine early enough , before that rndctl tool runs. Key really is to update the seed *before* using it, so that any subsequent boot will use a different seed.

hence, let's close this, unless i misread the change our current text is still correct.
