### ISSUE TITLE
RFE: provide DHCP server details

### ISSUE THREAD

**Issue by elmarco** [systemd/systemd#15462]
It would be useful to provide the per-link DHCP server details. I guess it should be introspected over dbus, and networkctl status could provide some basic informations.

fwiw, dnsmasq has a dbus interface
```
[root@boraha systemd]# busctl introspect uk.org.thekelleys.dnsmasq /uk/org/thekelleys/dnsmasq 
NAME                                TYPE      SIGNATURE RESULT/VALUE FLAGS
org.freedesktop.DBus.Introspectable interface -         -            -
.Introspect                         method    -         s            -
uk.org.thekelleys.dnsmasq           interface -         -            -
.AddDhcpLease                       method    ssayayuub -            -
.ClearCache                         method    -         -            -
.DeleteDhcpLease                    method    s         b            -
.GetLoopServers                     method    -         as           -
.GetMetrics                         method    -         a{su}        -
.GetVersion                         method    -         s            -
.SetBogusPrivOption                 method    b         -            -
.SetDomainServers                   method    as        -            -
.SetFilterWin2KOption               method    b         -            -
.SetServers                         method    av        -            -
.SetServersEx                       method    aas       -            -
.DhcpLeaseAdded                     signal    sss       -            -
.DhcpLeaseDeleted                   signal    sss       -            -
.DhcpLeaseUpdated                   signal    sss       -            -
```
https://github.com/imp/dnsmasq/blob/master/dbus/DBus-interface

Is it reasonable to add a new interface over the existing networkd link paths?
On `/org/freedesktop/network1/link/_36`, add `org.freedesktop.network1.DHCPServer` ?

It would have a `Leases` property, of type: `a(ayayayayt)`: array of
```
ay client_id
ay address
ay gateway
ay hwaddr
t expiration
```

**Comment by lperkov** [comment]
@elmarco thank you very much for this work. We were going to do exactly this after we get this one accepted:

https://github.com/systemd/systemd/pull/15556

We'll happily test your pull request :)

**Comment by borna-blazevic** [comment]
@elmarco, it seems to me that all that is missing so that the test could pass is a default case in this [file](https://github.com/sartura/systemd/commit/2238a490989a9cc05b3e81acdb24582a5119e893#diff-c280f76d5161e4a9cb63e0ecc5476cd3R177-R178). The review won't start until all of the tests are passing as per the [contribution guidelines](https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md). Could you please fix that so that the review process can start,

**Comment by elmarco** [comment]
@borna-blazevic actually, in most of my contribution so far, the CI is randomly failing. I don't really get it tbh.

**Comment by borna-blazevic** [comment]
@elmarco Yes, I had that happen, but if you resolve the build errors other errors seem to go away.

**Comment by borna-blazevic** [comment]
@elmarco I have taken a look at your issues with the CI tests. It seems to me that [this test](https://github.com/systemd/systemd/blob/master/test/test-network/systemd-networkd-tests.py) is failing because it is not properly configured for your additional features. To be exact [these lines](https://github.com/elmarco/systemd/blob/5a20b6cb431b4991d184b387d492da69e398b079/src/network/networkctl.c#L1140-L1146) are always failing in the tests. And because of that the [link_status_one](https://github.com/elmarco/systemd/blob/5a20b6cb431b4991d184b387d492da69e398b079/src/network/networkctl.c#L1338) never [ finishes correctly](https://github.com/elmarco/systemd/blob/5a20b6cb431b4991d184b387d492da69e398b079/src/network/networkctl.c#L1975-L1987).

The function fails with the message `Failed to query link DHCP leases: Unknown interface org.freedesktop.network1.DHCPServer or property Leases.`

So maybe adjust the [test](https://github.com/systemd/systemd/blob/master/test/test-network/systemd-networkd-tests.py) or make the dump_dhcp_leases function optional. Hope this helps.

**Comment by elmarco** [comment]
@borna-blazevic thanks for your analysis. I went about that far, and I was trying to run `mkosi --default=mkosi.default.networkd-test boot` to fix the pb, but I didn't manage yet... Any help appreciated!

**Comment by borna-blazevic** [comment]
@elmarco maybe try something like [this](https://github.com/sartura/systemd/blob/f6f30b9504ffac1e9a1ab2ca6496a14194611a62/src/network/networkctl.c#L1142-L1144)

**Comment by borna-blazevic** [comment]
@elmarco, Semaphore-CI seems to be passing with the changes I [sugested](https://github.com/sartura/systemd/blob/f6f30b9504ffac1e9a1ab2ca6496a14194611a62/src/network/networkctl.c#L1142-L1144). You can take a look [here](https://github.com/systemd/systemd/pull/15788).
