### ISSUE TITLE
Seeking advice on user unit to run before sleep.target

### ISSUE THREAD

**Issue by graysky2** [systemd/systemd#15468]
I'd like to have a **user** service to run under two conditions:
1) When a timer tells it to run
2) When the system is suspended

I have condition 1 working now, the service does not get triggered on condition 2 I believe due to the fact that sleep.target does not apply to user units.  Is what to do possible?
* [psd-resync.service](https://github.com/graysky2/profile-sync-daemon/blob/047574453033757db265bf8bb9538defb71a9a66/init/psd-resync.service)
* [psd-resync.timer](https://github.com/graysky2/profile-sync-daemon/blob/75363da43fe2767deec908861efd1f1ae1529f3f/init/psd-resync.timer)

**Comment by poettering** [comment]
This is not a support forum. And the bug submission form tries to make this clear in order to minimize frustration. Please contact the mailing list or so instead, as the submission form suggests, if you have questions like yours.

Please only file bug and feature requests here. For everything else there are other forums, such as the mailing list.

**Comment by graysky2** [comment]
@poettering - Thanks for clarification.  I opened https://github.com/systemd/systemd/issues/15477 thinking it.
