### ISSUE TITLE
systemd-resolved wrong parsing of multiple search domains

### ISSUE THREAD

**Issue by 0asys** [systemd/systemd#15474]
**systemd version the issue has been seen with**
> 244.4

**Used distribution**
 > Manjaro

**Expected behaviour you didn't see**
 Multiple entries in NetworkManager config `ipv4.dns-search` should configure systemd-resolved DNS-Domain correctly with multiple domain routes.

Like:
```
Link 2 (wlp0s20f3)
      Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: opportunistic
      DNSSEC setting: allow-downgrade
    DNSSEC supported: yes
  Current DNS Server: 192.168.1.53
         DNS Servers: 192.168.1.53
          DNS Domain: ~.
                      ~srv.local
                      ~lan.local
```
A single domain search entry leads to correct configuration of resolved domain routing.

**Unexpected behaviour you saw**
ipv4.dns-search in NetworkManager Connection setting leads to wrong parsing and characters.

Example: `ipv4.dns-search=lan.local srv.local;`
```
          DNS Domain: ~.
                      ~lan.local\032srv.local
```
Example: `ipv4.dns-search=lan.local,srv.local;`
```
          DNS Domain: ~.
                      ~lan.local\044srv.local
```

**Steps to reproduce the problem**
set NetworkManager connection setting ipv4.dns-search to `lan.local,srv.local` or `lan.local srv.local`.   
systemctl restart NetworkManager
resolvectl status

**Comment by poettering** [comment]
This is something NetworkManager parses, not systemd or resolved. This hence needs to be fixed in NM. @lkundrak @thom311, right?

**Comment by thom311** [comment]
> Example: ipv4.dns-search=lan.local srv.local;

This very much seems something from NetworkManager, but it's not clear what exactly.

In keyfile format (under `/etc/NetworkManager/system-connection`), there would be a separate section `[ipv4]`, and in `nmcli` command line syntax, you wouldn't use `=` to assign values.

It would be better to show full examples of what you did. 

Anyway, the space is not a delimiter for the string list in keyfile format. For nmcli, the exact syntax depends on which property you entered (for dns search property, whitespace is indeed a separator).

The keyfile format uses the format defined by glib's parser ([[1]](https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html#glib-Key-value-file-parser.description)), for which NM uses `;` as separator.

For nmcli, the syntax is like `nmcli connection modify "$PROFILE" ipv4.dns-search "$VALUE"`. In this case, nmcli accepts whitespace and `,` as delimiter.

You are welcome to edit keyfiles directly (followed by `nmcli connection reload`). But then use the correct syntax for the file format.

Also, when editing a profile in NetworkManager, it seems most interesting to first check what you configured there. Check that with `nmcli -g ipv4.dns-search connection show "$PROFILE"`. Checking what ends up in systemd-resolved, is two steps later.

> systemctl restart NetworkManager

Restarting NetworkManager is the wrong thing if you want to apply some configuration changes. That is because when NetworkManager stops, it tries to leave the network up and not change anything, so that you can restart the service without disconnecting yourself from the NetworkManager. That means, NM tries actively *not* to do any changes and restarting the daemon to perform changes is the wrong thing. Use `systemctl reload NetworkManager` or `nmcli connection reload|load` or `nmcli connection up "$PROFILE"`, depending on what you changed.

**Comment by bpereto** [comment]
You are right in many points.

The result in systemd resolved is the downstream value from NetworkManager.
Another view gives us `nmtui`. this is the result setting the ipv4.dns-search by tui:

![image](https://user-images.githubusercontent.com/1131885/79767866-3e946880-832a-11ea-97f0-01c10a68e4e3.png)

`/etc/NetworkManager/system-connections/PROFILE.nmconnection`
```
[ipv4]
dns-search=srv.local;lan.local;
```

When the correct format (separator `;`) in the keyfiles is used, with `nmcli connection modify "$PROFILE" ipv4.dns-search "lan.local;srv.local;"` or manually, the correct search domains are set in resolved.

NM let you set dns-search sepparated by space `nmcli connection modify "PROFILE" ipv4.dns-search "lan.local srv.local"`, the result is as described previously.

The keypoint for me here is that I used the wrong syntax, besides using `nmcli connection modify` and `systemctl restart`instead of connection reloading.

**Comment by thom311** [comment]
> When the correct format (separator ;) in the keyfiles is used, with `nmcli connection modify "$PROFILE" ipv4.dns-search "lan.local;srv.local;"` or manually, the correct search domains are set in resolved.

I guess you mean  `nmcli connection modify "$PROFILE" ipv4.dns-search "lan.local,srv.local"` because `;` isn't right for nmcli.

> NM let you set dns-search sepparated by space nmcli connection modify "PROFILE" ipv4.dns-search "lan.local srv.local"

I guess you mean "*nmcli* let you set ...". nmcli is just one possible client of NetworkManager, beside nmtui and nm-connection-editor any other tool that uses NetworkManager's API.

In nmtui the question doesn't arise, because the UI there is a list input field, not one text field where you would need to split the value with one delimiter or another. Also, on D-Bus API and in libnm, the dns-search is of type string list.

> The keypoint for me here is that I used the wrong syntax, besides using nmcli connection modify and systemctl restartinstead of connection reloading.

If you use `nmcli connection modify` or any other NM client that uses the D-Bus API (e.g. nmtui), then `nmcli connection reload|load` is not necessary. That is only necessary and useful, if you edit files on disk directly.

But I think now all is solved, isn't it?

**Comment by bpereto** [comment]
sorry for my copy paste errors,

yes, thank you for your clarifications. :+1:
