### ISSUE TITLE
Document OPTIONS+="db_persist" udev rule

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#1551]
Original bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1247210

**Comment by poettering** [comment]
Hmm, is this really something we want to document, and thus make API?

I mean, we do keep some things undocumented for the reason of not encouraging people to use it, this might be one of those cases. @kaysievers?

**Comment by johannbg** [comment]
What's the purpose of including something if it's not supposed to be documented and used? 

Does it exist for some backwards compatibility only and if so, should it's use not trigger a deprecation warning which includes the date it's going to be removed?

**Comment by poettering** [comment]
@johannbg some things we use for our own private stuff, but don't want to encourage anyone else to use it.

**Comment by johannbg** [comment]
@poettering  The "privates" need to be documented as "private" so people that look at the code and figure hey I can do this dont implement it.

**Comment by kaysievers** [comment]
I don't know. Does anybody really use it?
If not, it should be removed. If it's used by something that makes sense, we should probably add it to the man page.

**Comment by poettering** [comment]
@haraldh do you know anything about this?

otherwise might make sense to ask on the ML, and tell them that this is subject to removal

**Comment by prajnoha** [comment]
I've just noticed this report here by chance... Yes, the OPTIONS+="db_persist" is used for DM devices (and I MD devices too, I think) to keep udev database content when we're switching from initramfs to root fs. Usually, we cleanup the udev database when we do the switch due to a risk that different rules may be used in those two environments, but this does not apply to DM and MD devices - these can hand over the state and actually they rely on seeing the previous state correctly (even if it's coming from initramfs).

**Comment by haraldh** [comment]
Yes, it is used for the initramfs transition.

```$ git grep db_persist 
modules.d/90dm/11-dm.rules:OPTIONS+="db_persist"
modules.d/90mdraid/59-persistent-storage-md.rules:OPTIONS+="db_persist"
```

**Comment by haraldh** [comment]
```
        /*
         * set 'sticky' bit to indicate that we should not clean the
         * database when we transition from initramfs to the real root
         */
```
