### ISSUE TITLE
mknod not working inside nspawn cotainer

### ISSUE THREAD

**Issue by damianatorrpm** [systemd/systemd#15523]
**systemd version the issue has been seen with**
>systemd 245 (+suse.83.gc5aa158173)

**Used distribution**
>openSUSE Tumbleweed

**Expected behaviour you didn't see**
>mknod working inside nspawn cotainer

contents of /etc/systemd/nspawn/container_name.nspawn

```
[Exec]
Capability=all
SystemCallFilter=@clock @io-event @ipc @module @mount @network-io @obsolete @privileged @process @raw-io 
Boot=yes

#All the commented lines have been tried with various combinations
#Environment=SYSTEMD_NSPAWN_USE_CGNS=0
#Parameters=systemd.legacy_systemd_cgroup_controller=yes
#User=root
```
And the` /etc/systemd/system/systemd-nspawn@.service.d/override.conf`

```
[Service]
#various other variations have also been tried like DevicePolicy=closed
DevicePolicy=auto
DeviceAllow=/directory/on/host/to/container_name/home/dev/loop1 rwm
DeviceAllow=/home/dev/loop1 rwm
DeviceAllow=block-loop rwm
DeviceAllow=block-* rwm
DeviceAllow=/dev/loop-control rwm
DeviceAllow=/dev/loop1 rwm
```

The container is launched via `systemd-nspawn -D /directory/on/host/to/container_name/ -b --resolv-conf=bind-host --settings=yes`

and the settings file seems to be picked up correctly:
`Configuration file /etc/systemd/nspawn/container_name.nspawn is marked executable. Please remove executable permission bits. Proceeding anyway.`

inside the container
```
localhost:~ # mknod /home/dev/loop1 b 7 1
mknod: /home/dev/loop1: Operation not permitted
```

**Comment by poettering** [comment]
first of all, /etc/systemd/system/systemd-nspawn@.service.d/override.conf has no effect if you run the container from the cmdline instead of via the systemd-nspawn@.service service template.

If you run nspawn from the cmdline it will configure its own DeviceAllow= lines itself, directly. Use `systemd-nspawn --property=…` to set these properties when invoking the thing.

or in other words: if you run nspawn as system service, the DeviceAllow= lines must be in the .service unit file for it, or a drop-in extension of it. If you run nspawn from the command line instead, the DeviceAllow= lines must be listed on the command line, via `--property=`.

Anyway, this is more a support question, and this is a bug and feature tracker. Please contact a forum like the mailing list instead for any further questions. Thank you.
