### ISSUE TITLE
logind thinks my laptop is docked but it isn't

### ISSUE THREAD

**Issue by ewonchang** [systemd/systemd#15655]
Ubuntu 20.04 LTS
systemd version: 245.4-4ubuntu3

I'm trying to let my laptop suspend when the lid is closed. I set 
`HandleLidSwitch=suspend` and `HandleLidSwitchExternalPower=suspend`
in */etc/systemd/logind.conf* 

It is not working. I found out that systemd thinks my laptop is docked, but I'm not attaching any peripherals to my laptop other than the power cable (old school barrel cable, not USB-C)

```
ewon@Dell-Ubuntu:~$ sudo journalctl -b -u systemd-logind
-- Logs begin at Thu 2020-04-30 14:32:17 EDT, end at Thu 2020-04-30 14:41:02 EDT. --
Apr 30 14:40:30 Dell-Ubuntu systemd[1]: Starting Login Service...
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: New seat seat0.
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: Watching system buttons on /dev/input/event3 (Power Button)
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: Watching system buttons on /dev/input/event1 (Power Button)
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: Watching system buttons on /dev/input/event0 (Lid Switch)
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: Watching system buttons on /dev/input/event2 (Sleep Button)
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: Watching system buttons on /dev/input/event11 (Intel Virtual Button driver)
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: Watching system buttons on /dev/input/event8 (Intel HID events)
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: Watching system buttons on /dev/input/event4 (AT Translated Set 2 keyboard)
Apr 30 14:40:31 Dell-Ubuntu systemd[1]: Started Login Service.
Apr 30 14:40:31 Dell-Ubuntu systemd-logind[815]: New session 1 of user ewon.
Apr 30 14:40:32 Dell-Ubuntu systemd-logind[815]: System docked.
```

```
ewon@Dell-Ubuntu:~$ systemd-inhibit
WHO                          UID  USER PID  COMM            WHAT                                                     WHY                                                       MODE 
ModemManager                 0    root 934  ModemManager    sleep                                                    ModemManager needs to reset devices                       delay
NetworkManager               0    root 758  NetworkManager  sleep                                                    NetworkManager needs to turn off networks                 delay
UPower                       0    root 1386 upowerd         sleep                                                    Pause device polling                                      delay
Unattended Upgrades Shutdown 0    root 1229 unattended-upgr shutdown                                                 Stop ongoing upgrades or perform upgrades before shutdown delay
ewon                         1000 ewon 1529 gsd-media-keys  handle-power-key:handle-suspend-key:handle-hibernate-key GNOME handling keypresses                                 block
ewon                         1000 ewon 1529 gsd-media-keys  sleep                                                    GNOME handling keypresses                                 delay
ewon                         1000 ewon 1531 gsd-power       sleep                                                    GNOME needs to lock the screen                            delay
```

I found a similar issue on [Arch Forum](https://bbs.archlinux.org/viewtopic.php?id=176883). The workaround is to set `HandleLidSwitchDocked=suspend` in */etc/systemd/logind.conf* However it is not ideal. What causes systemd to think my laptop is docked? How to fix this? Thanks.

**Comment by poettering** [comment]
One of your input devices exposes a switch named `SW_DOCKED`, and it claims to be on. You have to figure out which one that is. This is most likely a driver problem.

Install the "evtest" tool (most distros package it), then run "evtest /dev/input/eventX" on your various input devices, and look for one that shows `SW_DOCKED` as supported switch (of course, there might be multiple such devices). It also tells you the current state of the switch, and it should show you the current state of the switch (which should be the incorrect, of course).

we rely on the drivers telling us things correctly. If they lie there's nothing much we can do. In that case, please report this to the driver authors, so that they fix it.

Let's close this here now, as logind just uses what the drivers report. If you find that the drivers report this correctly, but logind somehow misunderstands that, please report back and reopen.
