### ISSUE TITLE
stop tying sysvinit to creation of /run/lock?

### ISSUE THREAD

**Issue by geissonator** [systemd/systemd#15668]
**Is your feature request related to a problem? Please describe.**
Over in OpenBMC land we utilize /run/lock for synchronizing lock control for a few processes.  With the latest release of systemd, picked up via yocto, 245.5+, the incorporation of the file, tmpfiles.d/legacy.conf, and it's creation of /run/lock are tied to the new PACKAGECONFIG option, sysvinit.

**Describe the solution you'd like**
I don't believe the creation of /run/lock should be tied to the PACKAGECONFIG feature sysvinit.

**Describe alternatives you've considered**
Over in OpenBMC I just added sysvinit to our systemd.bbappend but it seems a little weird because we're obviously using systemd, not sysvinit.

**Comment by poettering** [comment]
/run/lock/ is a sysvinitism used for locking concurrent service operations.

There's really no need for any app to use it and it's a security problem, since it is a shared namespace. 

It is inherently legacy, and I can only advise your software to place the lock it needs in a more appropriate place, for example /run/$yoursoftware/ somewhere. These directories are typically generated via tmpfiles or RuntimeDirectory= and have the benefit that they are not a shared namespace, but a private one, and thus not prone to the security issues.

Sorry, but /run/lock/ really should die, there's zero benefit of using that dir over a proper, private runtime directory, like everyone else does.

Even on sysvinit systems there's no point in using /run/lock/ for your software, as there too you might just as well use your own private runtime dir.

Hence, let me ask, why would you want to use /run/lock/ over /run/$yoursoftware/ for your lock files?

**Comment by geissonator** [comment]
Thanks for the feedback @poettering. Not sure if it matters but it's mostly /var/lock usage which then is a link over to /run/lock. Our main issue seems to be in the u-boot scripts, fw_setenv, fw_printenv (although a grep of the code still shows a few uses of /var/lock in other areas). I'll just go with our workaround for now and follow up with the other communities still using it.

**Comment by buhtz** [comment]
Hello Lennart,

>I can only advise your software to place the lock it needs in a more appropriate place, for example /run/$yoursoftware/ 

What is the difference between `/run/lock/myapp.flock` and `/run/myapp/myapp.flock`? I really try to understand.

My application need a global flock usable by multiple user including root.
