### ISSUE TITLE
systemd does not shut down target after usb device has been unplugged

### ISSUE THREAD

**Issue by aruiz** [systemd/systemd#15676]
**systemd version the issue has been seen with**
```
systemd 245 (v245.4-1.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Used distribution**
 > Fedora 32

**Expected behaviour you didn't see**
I am trying to make the GNOME Settings Daemon gsd-smartcard.service to only be present when a smartcard is inserted. To get there I first had to create a hwdb file for supported devices to match the udev rule already present in 99-systemd.rules. See [20-usb-smartcard-readers.zip](https://github.com/systemd/systemd/files/4567972/20-usb-smartcard-readers.zip)

Once that was installed and the hwdb rebuilt, inerting a supported smartcard triggered smartcard.target both in system and user's systemd session as expected.

When I remove the USB device expect the target to stop itself.

**Unexpected behaviour you saw**
After removing USB device the target was still present

**Steps to reproduce the problem**
Install hwdb file attached, insert USB smartcard reader supported by CCID, plug a USB smartcard reader to a device with no built-in smartcard reader. Remove the USB device.

See the output in systemctl --user below, there you can see there are a number of devices still attached to WantedBy. Those devices are not present in the system anymore and udevadm info will not acknowledge them as present.

My gut feeling is that systemd is failing to remove the .device unit after removal for some reason or due to a bug.

```
Id=smartcard.target
Names=smartcard.target
WantedBy=sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d2.device sys-devices-pci0000:00-0000:00:1c.0-0000:01:00.0-0000:02:02.0-0000:39:00.0-usb3-3\x2d1-3\x2d1.1-3\x2d1.1.3.device sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d1.device sys-devices-pci0000:00-0000:00:1c.0-0000:01:00.0-0000:02:02.0-0000:39:00.0-usb3-3\x2d1-3\x2d1.1-3\x2d1.1.2-3\x2d1.1.2.1.device
Conflicts=shutdown.target
Before=shutdown.target
Documentation=man:systemd.special(7)
Description=Smart Card
LoadState=loaded
ActiveState=active
SubState=active
FragmentPath=/usr/lib/systemd/user/smartcard.target
UnitFileState=static
UnitFilePreset=disabled
StateChangeTimestamp=Sat 2020-05-02 17:09:13 CEST
StateChangeTimestampMonotonic=918299945780
InactiveExitTimestamp=Sat 2020-05-02 17:09:13 CEST
InactiveExitTimestampMonotonic=918299945780
ActiveEnterTimestamp=Sat 2020-05-02 17:09:13 CEST
ActiveEnterTimestampMonotonic=918299945780
ActiveExitTimestamp=Sat 2020-05-02 17:06:18 CEST
ActiveExitTimestampMonotonic=918125010846
InactiveEnterTimestamp=Sat 2020-05-02 17:06:18 CEST
InactiveEnterTimestampMonotonic=918125010846
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
StopWhenUnneeded=yes
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Sat 2020-05-02 17:09:13 CEST
ConditionTimestampMonotonic=918299945778
AssertTimestamp=Sat 2020-05-02 17:09:13 CEST
AssertTimestampMonotonic=918299945778
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
SuccessAction=none
InvocationID=e9de831b3b0e46118c1fb5bb8a72daa6
CollectMode=inactive

```

**Comment by poettering** [comment]
Well, this is not how this is supposed to work, the targets are really just additive: we start stuff for you, but we don't shut it down, expecting services to figure out when it's time to go themselves.

Generally, while it's safe to start stuff when things are plugged in, it's not clear when the right time is to shut things down, because from the outside we typically cannot see what your daemon does and if it really is idle now that all hw is gone. Hence the idea is: pull your service in when the hw shows up, but let the service figure out on its own when it's not needed anymore and not doing anything else. i.e. start based on external trigger, but stop on internal decision.

That said you can set StopWhenUneeded=yes in your service's unit file, in which case it will be stopped when nothing wants it anymore. smartcard.target is pulled in by the smartcard devices, and if you then hook your service into smartcard.target you should get the behaviour you want transitively, as smartcard.target sets StopWhenUnneeded=yes too.

Hmm, so I think we should try to set ID_SMARTCARD automatically if we detect a CCID device. I thought we did, but apparently we don't. If we did, then we wouldn't need the udev ruleset you posted. I'll have a look at that.

**Comment by poettering** [comment]
So I prepped #15857 which adds the usb interface class rule which should make that huge rule files you linked unnecessary.

**Comment by poettering** [comment]
With that in place, and when you use StopWhenUnneeded= then you have all you are looking for right? And we can close this?

**Comment by aruiz** [comment]
> So I prepped #15857 which adds the usb interface class rule which should make that huge rule files you linked unnecessary.

Oops, I was working on this: https://salsa.debian.org/rousseau/CCID/-/merge_requests/3#note_164722

Was that overkill?

**Comment by poettering** [comment]
Hmm, the the rule in #15857 automatically detects all USB CCID devices by their usb interface, and only sets a boolean.

Question is: your database dump, does that include smartcard readers that do not implement the USB CCID interface? If so that might be interesting to have.

Other than that: unlike my rule your database contains description strings for the devices. Are those from the usb database? or are they independently maintained? If the latter, then it might make sense to import them into our hwdb logic, as they might have prettier strings than the USB id hwdb we import. The fields should be named ID_MODEL_FROM_DATABASE then however, I guess.

**Comment by LudovicRousseau** [comment]
Yes, I am the upstream maintainer of a CCID driver and of the list @aruiz  is working on.
The list mostly contains information from the USB device. But some device have bogus information and my list provides a "better" version.
For example we have:
```
 idVendor: 0x0424
  iManufacturer: SMSC
 idProduct: 0x1202
  iProduct: SMSC USX101x Reader 
```
My [list](https://salsa.debian.org/rousseau/CCID/-/blob/master/readers/supported_readers.txt#L554) overwrite the iProduct to be "SEC1210" since that is the commercial name.

If you do not really care about the `iManufacturer` and `iProduct` values you can just identify CCID device using `bInterfaceClass: 0x0B`.


Before I integrate the list in my package I want to make it work and to start a sample script but I failed so far. See https://salsa.debian.org/rousseau/CCID/-/merge_requests/3#note_165243
I am not a systemd expert so maybe you can help @poettering ? :-)

I used this `foobar.service` as a user service:
```
[Unit]
Description=Smart Card Test
Wants=smartcard.target
After=smartcard.target

[Service]
Type=oneshot
ExecStart=/home/rousseau/bin/foobar.sh

[Install]
WantedBy=multi-user.target
```

**Comment by poettering** [comment]
So we import various external databases into our hwdb set regularly, i.e. the ACPI, PCI, USB, OUI databases, as well as ChromeOS suspend data and so on. I think it would make sense to regularly pull in your database, too, if it has nicer strings for the devices.

If you want a service that is automatically pulled in when a smartcard is plugged in, use:

```
[Unit]
Description=Smart Card Test
StopWhenUnneeded=yes

[Service]
ExecStart=/home/rousseau/bin/foobar.sh

[Install]
WantedBy=smartcard.target
```

then enable this with systemctl enable --user.

**Comment by LudovicRousseau** [comment]
Since systemd "regularly imports external database" maybe it is better to do just that?
i.e. what are the benefits of my CCID driver to provide its own `20-usb-smartcard-readers.hwdb` if the same database is also provided by systemd?
And the systemd database can be used even if my CCID driver is not installed.

Note that my driver does not support all USB smart card readers, not even all USB CCID smart card readers (for different reasons). So maybe you want to include the driver name in the `.hwdb` file. Or you will have to concatenate different files to get a more complete `20-usb-smartcard-readers.hwdb`.

**Comment by poettering** [comment]
so, if you have a database of readers keyed by vid/pid that have pretty names, that's generic stuff that would perfectly fit into the stuff we regularly import. OTOH stuff that is specific to the smartcard userspace code probably should be maintained as part of that, i.e. specific driver info or so.

**Comment by keszybz** [comment]
> the targets are really just additive: we start stuff for you, but we don't shut it down, expecting services to figure out when it's time to go themselves.

Let's close this issue then.

> so, if you have a database of readers keyed by vid/pid that have pretty names, that's generic stuff that would perfectly fit into the stuff we regularly import. OTOH stuff that is specific to the smartcard userspace code probably should be maintained as part of that, i.e. specific driver info or so.

It *would* be nice to have this database as part of systemd, so that anyone who install udev sees the corrected pretty names. In this regard, keeping the list in CCID has a slight disadvantage that installing CCID will suddenly change device descriptions. But "regular importing" of the database requires additional work and has a high chance to go wrong at some point. So I think it's better to keep things simple, and generate a hwdb list in CCID. @aruiz's PR looks like a good start, I'll comment some more there.

**Comment by LudovicRousseau** [comment]
@poettering I created my `foobar.service`  as suggested. The service has been executed **once** on the first smart card reader connection.

From `journalctl`
```
mai 22 14:00:48 node304 kernel: usb 1-1: new full-speed USB device number 11 using xhci_hcd
mai 22 14:00:48 node304 kernel: usb 1-1: New USB device found, idVendor=08e6, idProduct=3437, bcdDevice= 1.00
mai 22 14:00:48 node304 kernel: usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
mai 22 14:00:48 node304 kernel: usb 1-1: Product: USB SmartCard Reader
mai 22 14:00:48 node304 kernel: usb 1-1: Manufacturer: Gemplus
mai 22 14:00:48 node304 mtp-probe[6037]: checking bus 1, device 11: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
mai 22 14:00:48 node304 mtp-probe[6037]: bus: 1, device: 11 was not an MTP device
mai 22 14:00:48 node304 systemd[1530]: Started Smart Card Test.
mai 22 14:00:48 node304 systemd[1530]: Reached target Smart Card.
mai 22 14:00:48 node304 mtp-probe[6042]: checking bus 1, device 11: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1"
mai 22 14:00:48 node304 systemd[1530]: foobar.service: Succeeded.
```

Now the service do **not** start again if I remove and insert again the reader.
What did I missed?

I have systemd version 245.5-3 (Debian testing)
```
$ cat .config/systemd/user/foobar.service 
[Unit]
Description=Smart Card Test
StopWhenUnneeded=yes

[Service]
ExecStart=/home/rousseau/bin/foobar.sh

[Install]
WantedBy=smartcard.target
```
```
$ systemctl status --user foobar
● foobar.service - Smart Card Test
     Loaded: loaded (/home/rousseau/.config/systemd/user/foobar.service; enable>
     Active: inactive (dead)

mai 22 14:00:48 node304 systemd[1530]: Started Smart Card Test.
mai 22 14:00:48 node304 systemd[1530]: foobar.service: Succeeded.
```
I always get the `SYSTEMD_USER_WANTS=smartcard.target` reported by `udevadm monitor -p` on each USB reader connection.

I tried to disable and enable again the service but that does not help.

**Comment by wucke13** [comment]
To hook onto this:

I use the following udev rule:

```udev
SUBSYSTEM=="usb", ACTION=="add", ATTRS{idVendor}=="dead", ATTRS{idProduct}=="beef", TAG+="systemd", ENV{SYSTEMD_WANTS}+="$my-cool-device.service"
```
Now in `my-cool-device.service` is configured as following:

```ini
[Unit]
StopWhenNeeded=true

[Service]
ExecStartPre=/usr/bin/my/pre/hook.sh
ExecStop=/usr/bin/my/post/hook.sh
RemainAfterExit=true
Type=oneshot
```

So my expectations are:

1. [x] the service is started when device is plugged in
2. [x] the pre/hook.sh is started when the service is started
3. [ ] the service keeps running until when the devices is detached
4. [ ] the post hook is executed after the device goes offline

Reasoning: The `.device` unit wants `my-cool-device.service`, thus as long as the `.device` unit is active, `my-cool-device.service` should be active too. However, `my-cool-device.service` is finished immediately, calling the post hook immediately after calling the pre hook. This seems to indicate, that the device unit does not actually want `my-cool-device.service` -- which actually is the case, `my-cool-device.service` doesn't appear anywhere in the output of `systemctl show *.device`. Why is this the case?

For reference, the service is meant to enable usb redirection of the device to a VM. Can this be the culprit, e.g. that the device is considered offline by systemd once it was passed through to the VM? If so, how canthis be avoided?

**Comment by poettering** [comment]
@wucke13 please do not hijack bug reports. if you need help → systemd mailing list. As a one time exception I'll answer here though: you match `ACTION=="add"` thus the dep is only valid on `add`. However usb devices usually receive othr events (`bind` + `change`) later on, at which point the dep is dropped. In almost all cases you want to use `ACTION!="remove"` instead, as you want to keep the dep around for the entire time the device is around at all.

**Comment by wucke13** [comment]
@poettering thank your for the exception and the nice hint re `ACTION!="remove"` (TDIL!). Still, I think there is a bug. Essentially, I have the same behavior as https://github.com/systemd/systemd/issues/15676#issuecomment-632667537, I guess. 

Let's consider the following:

A systemd service, `udev--demo.service`, that is mean to perform an action (in this case just print the date) when a device is attached, and when the device is detached:
```ini
[Unit]
StopWhenUnneeded=true

[Service]
ExecStartPre=/bin/date
ExecStop=/bin/date
RemainAfterExit=true
Type=oneshot
```

Now lets consider the following `udev` rule:

```udev
SUBSYSTEM=="usb", ACTION!="remove", ATTRS{idVendor}=="dead", ATTRS{idProduct}=="beef", TAG+="systemd", ENV{SYSTEMD_WANTS}+="udev-demo.service"
```

When I plug in the device with the corresponding `idVendor` and `idProduct`, sure enough a `.device` unit becomes active:
```
○ sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d1-1\x2d1:1.0.device - /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0
     Loaded: loaded
     Active: inactive (dead) 
```

becomes 

```
● sys-devices-pci0000:00-0000:00:14.0-usb1-1\x2d1-1\x2d1:1.0.device - /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0
     Loaded: loaded
     Active: active (plugged) since Tue 2022-05-17 13:05:12 CEST; 8min ago
     Device: /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0
```

Sure enough, this device unit depends on `udev-demo.service`:

```console
 systemctl show sys-devices-pci0000:00-0000:00:14.0-usb1-1\\x2d1-1\\x2d1:1.0.device | grep Wants
Wants=udev-demo.service
```

Now on the first time plugging in the device, `udev-demo.service` is started, but it is never stopped, even after the device unit becomes `inactive (dead)`.

__Now, why do I consider this a bug__:

From `man systemd.unit`:

```
StopWhenUnneeded=
    Takes a boolean argument. If true, this unit will be stopped when
    it is no longer used. Note that, in order to minimize the work to
    be executed, systemd will not stop units by default unless they are
    conflicting with other units, or the user explicitly requested
    their shut down. If this option is set, a unit will be
    automatically cleaned up if no other active unit requires it.
    Defaults to false.
```

From this I understand, that if no unit requires `udev-demo.service`, it should be stopped. But, `systemctl list-dependencies udev-demo.service --reverse` (ran while device is __not attached__) only names `udev-demo.service` but no dependents. So, if there are no dependents, and `StopWhenUneeded=true`, why doesn't the service stop? If I did not overlook something here, then either the documentation or the implementation is wrong, as the one does not comply to the other.

**Comment by DaanDeMeyer** [comment]
@wucke13 Please open a new issue instead of hijacking the old bug report, it'll greatly increase the chance your issue will get looked at
