### ISSUE TITLE
Journald should be able to utilize multiple cpu cores.

### ISSUE THREAD

**Issue by CodyKochmann** [systemd/systemd#15677]
**Describe the problem:**
I'm frustrated that I cannot tell journald that it can use more than 1 cpu.

Back when systems did not have as many cores, this was not as much of an issue because core count was not nearly as high as it is today and nvme disks being able to keep up with high io demand. I commonly find myself in the following scenario:

I have some 32, 64, or 128 cpu core system and I am trying to get the most out of it to get my money's worth. If I decide that logs are important and journald does an excellent job organizing those logs, I am then limited to what journald is able to keep up with.

After extensive hours trying to tune it as much as I can and turning off every cpu intensive step I can find for journald, at the end of the day its still limited to the throughput of 1 cpu core. As time goes on, this becomes less and less of a fraction of the entire processing capacity.

**Describe what I would like:**
I would like to be able to have a `MaxProcesses=` or `MaxCPU=` or something along those lines option in `journald.conf` that allows users to tell journald that they _intend_ on letting journald spawn child processes to take up a significant amount of the system.

**Alternatives I've considered:**
- Having different execution models configurable for journald. like:
  - "single-core" would be the current setup
  - "per-service" or "service-forking" where it spawns a dedicated journald process for every systemd service
  - "multi-core" where it more adopts rsyslog's forking logic and only spawns children when the demand passes how many cores are currently being used
- Lowering journald to a more accessible level so users can run multiple journald services on the same system.
  - This would mean journald would need to tweak some of its assumptions that it is the only journald that will be running on the system. (this worked before by running multiple containerized journalds on the same system and _did_ prove that you can have significant multicore speedups but was more of a POC than a user friendly solution)
  - If there was anything tying journald to run at such a highly integrated into systemd's core spot, "systemd-journald" could be purely for the systemd level things and other systemd daemons can take care of the rest since journalctl doesn't seem to have a difficult time reading multiple journals at the same time.
- Tweaking journald so it can be executed at the user level as a normal user process just like you can with rsyslog, syslog-ng, sshd, and many other "system level" services.

**Comment by benjarobin** [comment]
I'm a little curious, what is the use case? What is the average log throughput in MB/s or even in GB/s?
Journald should be IO bound and not CPU bound

**Comment by poettering** [comment]
We guarantee global ordering of log messages written to disk. This makes it nasty to distribute work on multiple CPUs.

Why do you want this specifically, have done profiling that shows that something specifically is a performance issue that could be improved by doing stuff on multiple CPUs? Last time I looked we typically are IO bound, not CPU bound, and dong stuff on multiple CPUs is not going to do any good with that at all, but most liekly make things worse.

That all said, use JournalNamespace= in services to instantiate journald as many times as you like. It's basically a way to say "i don't care about global ordering, i am fine with local ordering within this group of services". If you do, then every set of services that use the same JournalNamespace= value get their own entirely independent journald instance, just for them.

Anyway, their are jobs that can be easily distributed to many CPUs and jobs where that's not easy. Processing streams with global ordering is one of the latter. Unless there's some profiling data available that clearly shows that the parallelizable sections of journald are clearly CPU bound and a big source of latency we can look into doing more work distributed onto multiple CPUs, but otherwise this smells a lot like premature optimization...

But anyway, doesn't JournalNamespace= do evrything you are looking for?

**Comment by CodyKochmann** [comment]
The cpu bottlenecking was real when you started introducing a large number of writers all streaming a lot of data at various rates. Its volatile mode kind of makes this a lot more observable. I'll save numbers for reproducible tests but it was definitely in the multi GB/sec range total.

I'll do some digging with JournalNamespace and report back if that doesn't work. Didn't know about the global guarantee and assumed it was a guarantee just per service so you definitely might be right about that being exactly what I need.

**Comment by CodyKochmann** [comment]
Yeah this is exactly what I was looking for.

Should I open a different ticket for making this more discoverable? I've spent days reading over these docs, have dragged multiple colleagues from NASA into wrestling with this and we all and missed the small mention that the JournalNamespaces increase performance.

The setting memory to volatile, sealing settings, disabling compression were easy suggestions to find in the docs. This piece of advice was well buried.

**Comment by poettering** [comment]
where would you make this more discoverable?

**Comment by poettering** [comment]
Anyway, given that journal namespaces exist, let's close this.
