### ISSUE TITLE
test_exec_dynamicuser takes 90s on Arch mkosi image

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#15748]
**systemd version the issue has been seen with**
> v245.5

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Tests are (almost) instant

**Unexpected behaviour you saw**
 > test_exec_dynamicuser takes 90s

**Steps to reproduce the problem**

`sudo mkosi --default .mkosi/mkosi.arch`

The problem seems to be `check_user_has_group_with_same_name` which calls `getpwnam` and `getgrgid`. This function takes 45s before it returns false twice in `test_exec_dynamicuser`. 

This only happens when running the tests via the mkosi image. Running the tests locally is almost instant (9s). I'm running the mkosi Arch image from a Arch Linux system. 

EDIT: I ran some more tests and `getpwnam("adm")` and `getpwnam("games")` are both taking exactly 45s to complete. And more interesting, 45s is the default varlink timeout so userdb seems to be the culprit in nss.

**Comment by DaanDeMeyer** [comment]
I'm not even sure if this is Arch specific anymore. I think the problem is caused by trying to resolve hostnames from the nss-systemd plugin via userdbd on a system that doesn't even have systemd running (mkosi's doesn't specify `--boot` for systemd-nspawn when running build scripts). However, even when mounting the journald socket into the container, I'm still not getting any debug logs from the plugin so I'm having a hard time figuring out what exactly is causing the varlink timeout. 

@poettering Since you wrote the userdb/varlink stuff, maybe you have an idea why it would timeout in a `systemd-nspawn --as-pid2`  container? setting `SYSTEMD_BYPASS_USERDB=1`  in mkosi.build before running the tests fixes it but that seems like a workaround rather than the actual solution.

Looking at the code, it seems like the `connect` tot the userdb varlink socket should just fail but for some reason it doesn't and the `sd_event` instance the varlink client is attached to never fires the EPOLLOUT event so eventually the 45s timeout expires. Either that or for some unknown reason the connect succeeds but there's nothing on the other end to respond which is followed by the timeout.

**Comment by DaanDeMeyer** [comment]
Ahah, I think I've got it. It's a circular dependency between test-execute and nss-systemd. test-execute starts a manager which creates the run/systemd/userdb directory and all varlink sockets in it. When it calls `getpwnam`, nss-systemd kicks in. One of the varlink services contacted by nss-systemd is io.systemd.DynamicUser which is implemented by the manager started by test-execute. So nss-systemd tries to connect to test-execute via a unix domain socket while test-execute is blocking on `getpwnam`. `getpwnam` can only finish when nss-systemd finishes and nss-systemd's connection to the varlink socket can only be handled by test-execute when `getpwnam` finishes. As a result, we get a deadlock which is only resolved when the connection attempt of nss-systemd to the io.systemd.DynamicUser varlink socket times out which results in the 90s required for `getpwnam` to complete.

**Comment by poettering** [comment]
my proposed fix is in #15793.
