### ISSUE TITLE
`systemd-udevd` should establish inotify watches before scanning block devices.

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#15837]
**Is your feature request related to a problem? Please describe.**
The root cause of #10179 is that `systemd-udevd` scans the block device before establishing a inotify watch.  If the inotify watch was established first, and devices were rescanned on queue overflow, there would be no race condition.

**Describe the solution you'd like**
`systemd-udevd` should establish inotify watches before scanning block devices.

**Describe alternatives you've considered**
Expect every program that alters block devices to adhere to the systemd locking protocol.  This requires changes to every such program, rather than solving the problem once and for all.

**Comment by poettering** [comment]
Changes to block devices are never atomic (and neither is identifying them), there's no way around locking things properly to fix these problems systematically. Everything else is just "trying and hoping". This is particularly important if you try to make more than a few changes.

We install inotify watches as effect of udev rules, i.e. as effect of probing. Thus we cannot reasonably install the watches beforehand, since we don't know whether to do so at all. Moreover, there's also a inotify event cycle then (as we generate those events we watch for with inotify ourselves)

We generally only open/watch stuff that we are told explicitly, since block devices are weird, and there are plenty block devices where we shouldn't even think of opening them automatically since they have special semantics, or hw that needs special setup or so and might hang. 

Hence, I don't think we should do this. It will break compat, not fix the problem, likely generate new problems. 

I hope this makes some sense?

Sorry!

**Comment by DemiMarie** [comment]
@poettering I agree that opening things we are not told to is a bad idea.  However, once we do open a block device, I don’t see a reason to not immediately establish an inotify watch before probing them.  Furthermore, as explained in <https://github.com/systemd/systemd/issues/10179#issuecomment-633272621>, I believe that even proper locking does not prevent the race condition.
