### ISSUE TITLE
Unable to execute service before systemd-fstab-generator

### ISSUE THREAD

**Issue by bdrung** [systemd/systemd#15890]
**systemd version the issue has been seen with**

232 and also 245

**Used distribution**

 Debian

**Expected behaviour you didn't see**

I have a live systems where I want to generate `/etc/fstab` at a very early stage of the boot (but not inside the initrd) using a systemd service. For that, this systemd service needs to be executed before `systemd-fstab-generator`. I expect the documentation to tell me how to do that.

**Unexpected behaviour you saw**

The man page of `systemd-fstab-generator` says:
> `systemd-fstab-generator` is a generator that translates `/etc/fstab` into native systemd units early at boot.

But it does not clarify at which state at all and if there is a target/service that it comes after.

**Comment by boucman** [comment]
This is an issue tracker. for support please ask on the mailing list.

That being said, generators are the very first thing systemd runs before any units and there is no way to run a unit before that.

what you can do instead :
* have a generator run before systemd-fstab-generator 
* mask the generator if you don't want it to run at all (see man:systemd.generators)
* replace it with a generator of your own
* mask/override the units the generator creates. These are just norma units (see man:systemd.units)
* simply remove the line you don't want from /etc/fstab

I can't tell you more without understanding why you are not happy with what the generator does, but that's something to discuss on the mailing list.

**Comment by poettering** [comment]
generators are a way to extend the unit tree with dynamically generated units. Because it synthesizes the tree, it's outside of the unit tree, and thus runs in very special circumstances. Specifically, generators run during earliest boot, before any services are run, as services are called as effect of the generators. They also run when PID 1 is reloaded, in order to generate new configuration for it.

generally, generators should convert external configuration into native unit files. You shouldn't really use them for anything else, including generating other, foreign configuration, since this is typically bound to a very different cycle. After all, the output generators generate is automatically removed on the next reload cycle, to not interfere with the new cycle of unit file generation.

Hence: generating fstab from generators doesn't really make sense. It's not what the concept is for. Either generate systemd mount unit files directly or don't generate them at all.

If you want to generate fstab at boot anyway, then you should do that from a regular service, and then issue a "systemctl daemon-reload" or equivalent call. But of course that's ugly and slow, as reloading configuration is not something that should happen in clean code paths during runtime. It's mostly something that should happen when new packages are installed or suchlike.

So my suggestion would be: generate mount units directly from a generator, and forget about fstab.

Anyway, this is really a support question. For those please contact the ML, do not use github for that. We try to make this very clear in the submission form to keep frustration low.
