### ISSUE TITLE
varlink interfaces should not contain upper-case letters

### ISSUE THREAD

**Issue by embe** [systemd/systemd#15952]
The varlink interface definition (https://varlink.org/Interface-Definition) only allows lower-case letters in interface names.

Most of the interfaces defined by systemd contain upper-case letters. For example: `io.systemd.UserDatabase`, `io.systemd.Journal`.

**Comment by poettering** [comment]
umm, why don't they allow that, that sounds like a poor choice. :-( 

not sure if we reasonably can change this now. the userdb varlink stuff is pretty much public by now...

**Comment by haraldh** [comment]
why? oh why?

**Comment by haraldh** [comment]
It was made to be able to quickly validate `org.example.test.GetInfo` ... interface name is all lower-case... method has to begin with upper-case... So it was all specced out since day one.

**Comment by poettering** [comment]
i take the blame, didn't read the specs well enough, back when I implemented this. but not sure i want to change this now, since our codebase is probably one of the most prominent places where varlink is deployed, and it's pretty much API.

I mean, I can see why enforcing lower-case makes sense if things were truly domain names (since domain names are case insensitive), but they are aren#t really just that, they also take the role of the "class" in traditional OO programming languages if you so will, and it's probably the first time I see a place where one couldn't use uppercase characters for that.

**Comment by haraldh** [comment]
corrected our go, python, C, rust libraries for it

**Comment by poettering** [comment]
@haraldh thanks a lot! I guess we can close this then!

much appreciated!
