### ISSUE TITLE
IPv6 forwarding

### ISSUE THREAD

**Issue by Kubuxu** [systemd/systemd#1597]
As for the [docs](http://www.tldp.org/HOWTO/Linux+IPv6-HOWTO/proc-sys-net-ipv6..html) IPv6 forwarding can be enabled and disabled only _globally_ and not as in case of IPv4 on per interface basis.

This means that the only option that matters is `net.ipv6.conf.all.forwarding` and rest in essence are useless as they do not affect anything.

This behaviour was reported ([redhat](https://bugzilla.redhat.com/show_bug.cgi?id=38533) and [netdev](http://oss.sgi.com/archives/netdev/2001-05/msg00149.html) examples) and accepted as correct in case of IPv6 forwarding.

This is quite a problem as `systemd-networkd` does not set `1` to `net.ipv6.conf.all.forwarding` and tries enabling IPv6 forwarding on per interface basis which doesn't work.

Even if forwarding on all interfaces were to be set to `1` the forwarding won't be enables unless the forwarding in `all` is set to `1`.

**Comment by poettering** [comment]
Is this really still that way? I read the current documentation from the kernel sources differently:

https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

**Comment by Kubuxu** [comment]
@poettering search for: `conf/all/forwarding - BOOLEAN` there is explanation.
The top is about ipv4 forwarding.

**Comment by Kubuxu** [comment]
So what should be correct behaviour in case of networkd.

Should enabling IPv6 forwarding on any interface enable it globally, if not then docs should be updated to reflect this problem.
I think more and more people will struggle with that.

**Comment by Kubuxu** [comment]
Resolved in 765afd5c4dbc71940d6dd6007ecc3eaa5a0b2aa1.

**Comment by bonktree** [comment]
Since kernel 6.17 (tagged September 2025) the situation has changed: while `conf/$iface/forwarding` and `conf/all/forwarding` still control totally different things, there has appeared (torvalds/linux@f24987ef6959a7efaf79bffd265522c3df18d431) a way to enable forwarding packets coming from a specific interface: `conf/$iface/force_forwarding`. This works just like IPv4 `conf/$iface/forwarding` as documented, even if `conf/all/forwarding` is set to 0.

**Comment by yuwata** [comment]
@bonktree Thanks. Filed as #40666.
