### ISSUE TITLE
systemd-shutdown seems not handling writeback cached lvm devices properly

### ISSUE THREAD

**Issue by CommDServ** [systemd/systemd#16068]
**systemd version the issue has been seen with**
> 245.5-3

**Used distribution**
 > debian unstable(2020-06)

**Background info**
> Found this problem when using lvm writeback caching and shutting down/rebooting with systemd.
> On writeback cached lvm changes are written directly into caching device(usually the fast one),and only when necessary these data are synced to the original disk(usually slower)
> I was using lvm writeback to speed up HDD using an SSD.

**Expected behaviour you didn't see**
 > HDD,SSD,every device properly shut down,without data loss or harm to device

**Unexpected behaviour you saw**
 > When shutting down/reboot systemd-shutdown shows like:
> Failed to finalize DM device /dev/(forgotten)/dm-[6-8]
> Failed to finalize DM devices,ignoring.
******And my HDD experiences power loss,since I can hear it.******

**Steps to reproduce the problem**
Build up a writeback-cached Logical Volume(better not root,or very troublesome),mount it,and shutdown/reboot on a systemd inited system.

**What I think about the issue**
I think the cause is systemd-shutdown's force shutdown policy,
or not well checked when unmounting dm devices,which is syncing from cache to original,
leading to unexpected power loss(and possibly data loss).
Plus,I'm pretty sure writethrough mode works fine.(which almost only caches reading)

**Comment by poettering** [comment]
Please report to the initrd you use.

systemd tries to detach various DM devices, but this is no comprehensive, and does not cover MD devices anyway. But that's OK. The idea is that initrds provide an entrypoint so that systemd can jump back in them and they detach the rest that systemd can't natively detach. For example, if you have storage backed by iscsi, the iscsi connections need to be torn down from that.

This is out of control of systemd though. It's documented here:

https://systemd.io/INITRD_INTERFACE/

your distro/initrd needs to implement that if they want to detach storage properly. 

Closing,

**Comment by Common-D-Service** [comment]
Problem resolved after I switched to the dracut initrd,which I think handles the detachment well for now.
Maybe recommending dracut to replace initramfs-tools can be a solution,when systemd shows "fail to finalize...|fail to detach..."
Sorry for bothering.And thx for letting me know more 'bout these.
