### ISSUE TITLE
SYSTEMD_LESS=-K ^C leaves terminal in reverse video mode

### ISSUE THREAD

**Issue by jidanni** [systemd/systemd#16084]
```
# journalctl --boot | wc
   1170   13768  105524 
# SYSTEMD_LESS=-iRXQMK journalctl --boot
^C
```
leaves terminal in reverse video mode.

**Comment by jidanni** [comment]
I couldn't reproduce it with

```
# journalctl > /tmp/j
# LESS=-iRXQMK less /tmp/j
^C
```

so I filed https://github.com/systemd/systemd/issues/16084 which shows it even happens with smaller --boot input.

**Comment by jidanni** [comment]
systemd 245 (245.5-3)

**Comment by poettering** [comment]
Hmm? what does this have to do with systemd? We don't propagate C-c. The tty passes it directly to less and journalctl

**Comment by poettering** [comment]
also, journalctl never sets reverse video. it must be less that does that? I really don't see what this has to do with systemd?

**Comment by jidanni** [comment]
> Hmm? what does this have to do with systemd?
```
$ dlocate /bin/journalctl
systemd: /bin/journalctl
```
Well all I know is with pure less, as you could see in https://github.com/gwsw/less/issues/68, I could not reproduce it.

**Comment by poettering** [comment]
Hmm, so this appears to be a bug in less, I figure. I am pretty sure it should not leave reverse video set if it receives SIGTERM. SIGTERM is the official friendly way to terminate processes after all, i.e. the clean way to say "exit please". They should handle that and exit cleanly.

It does such a clean-up when receiving SIGINT, but not with SIGTERM. It should just do the same in both cases.

systemd's auto-paging feature will fork off the pager as a child process, and set PRCTL_PDEATHSIG to SIGTERM. This means if our tool then dies suddenly the pager is killed with SIGTERM, i.e. friendly told to exit too. This is the right way to do it I am very sure.

We could of course also use PRCTL_PDEATHSIG with SIGINT, instead, which would make this work with current less. But that smells like a dirty work-around, since it hardcodes the expectation that less is the pager and handles SIGINT but not SIGTERM. Which smells a lot like a work-around for a bug,

Alternatively we could just reset the terminal ourselves from our signal handler, but this is kinda besides the point, after all the whole reason to do the PRCTL_PDEATHSIG thing was to make things work if we die suddenly (i.e. not cleanly) and clean up the pager in that case too.

Hence: I am pretty sure we should consider this a less bug, and the bugfix there would be easy: just handle SIGTERM similar to SIGINT, restore video and exit.

**Comment by jidanni** [comment]
Ah! A less bug after all! Closing.

**Comment by poettering** [comment]
So, given that we actually explicitly set "K" into `$LESS` which enables its SIGINT behaviour I think after all we actually should send SIGINT too here, instead of SIGTERM. Hence I prepped #16101 now. That said, I think less should fix this too and be happy on SIGTERM too.
