### ISSUE TITLE
journal files's permission in /var/log/journal  changes from "640  root root" to "-rw-r-----+ 1 root systemd-journal" after reboot？

### ISSUE THREAD

**Issue by fayeinseu** [systemd/systemd#16141]
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > permission of journal files won't change ,it should be "-rw-r-----+ 1 root systemd-journal" after created.

**Unexpected behaviour you saw**
 > it  changes.

**Steps to reproduce the problem**
1.useradd test -g systemd-journal
2.ls -l /var/log/journal/*
3.reboot
4.ls -l /var/log/journal/*

the problem seem to be related with tmpfiles.d .

**Comment by poettering** [comment]
The permissions and ownership are adjusted via /usr/lib/tmpfiles.d/systemd.conf.

We do it like that (instead of via journald natively) because resolving user/group names requires NSS calls, i.e. getpwnam() which might do local IPC to local services (think: sssd), but those local services might want to log to journald, so you get a deadlock. Hence journald just creates the files as root, and then tmpfiles fixes up ACLs and ownership. and tmpfiles can run later and thus safely block on NSS on local IPC.

**Comment by fayeinseu** [comment]
However , the user named test can't  open system.journal because the permission of 640 after /var/log/journal is created ,even that the user should have permission to open it .@poettering
![image](https://user-images.githubusercontent.com/26080826/84386480-028fcc80-ac24-11ea-9294-2769813cc8bc.png)

**Comment by fayeinseu** [comment]
So , you means that the better way is using "systemd-tmpfiles --create" to change journal file's permission after /var/log/journal is created.

**Comment by poettering** [comment]
it's run at boot automatically, to adjust everything
