### ISSUE TITLE
Alternatvies to Google NTP and DNS

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#16148]
Google has been incorporated in FOSS/OSS for too long, it is time we make a change and use privacy respecting services and services that care about their users.

For NTP I suggest using https://www.ntppool.org/

And for DNS, see https://dns.watch/ 

And for DoH there is https://dns-unfiltered.adguard.com/dns-query

**Comment by mbiebl** [comment]
Sigh

**Comment by poettering** [comment]
> For NTP I suggest using https://www.ntppool.org/

Last time I looked ntp pool explicitly doesn't allow us to use it unless we register as an organization. Thing is, we don't want that, since it's something downstreams should do, not us. i.e. systemd is not something you install yourself, it's something your distro packages for you. And it's the job for the distro to register with the NTP pool as an organization. And most distros do: Fedora for example does, and Ubuntu does too. And they then specify that when building systemd, so that those pools are used by default.

hence, we cannot default to the ntp pool, because it's against their rules to do it without being a registered organization. We don't want to be a registered organization, hence we cannot use it.

Google is much more lenient there. They say they only do that for their own devices, but they also don't care if you use it for something else. Which is fine by us.
