### ISSUE TITLE
systemd-homed -- how to update user UID and GID 

### ISSUE THREAD

**Issue by heywoodlh** [systemd/systemd#16164]
Hello all,

I have used the following command in an attempt to update my UID I'm more used to:

```
homectl update [username] --uid 1000
```

I see the updated UID in the `~/.identity` file in my user's home directory. However, when I run `id` against my user (after ending my current session, rebooting, etc.) it still shows my user's UID is 60063. 

How do I get my system to recognize the new UID for my user? And how do I change my group GID (which is the same as my UID)? 

Obviously, since I'm using `homed` I can't use the `usermod` command or other normal utilities to update my UID and GID so I'm at a loss as to how to approach this issue. I suppose I could delete my user and recreate it by specifying `--uid` but I would rather not lose my homed image.

Thanks in advance for any assistance. :)

**Comment by poettering** [comment]
This is not a support forum and the bug submission form should have made that really clear, in order to minimize frustration. Please, use the mailing list for support questions.

Anyway, here's the answer, but please, for follow-up questions → mailing list.

UID assignments are "sticky" in homed, to match how file ownerships on
UNIX are sticky: if a random user creates a random file in some random
dir, it's owned by that user, and if the user changes UID later, then
the file will still be owned by the original UID, which might then be
recycled for some other later added user who might then get access to
a file they should not get access to.

The UID you configure with "homectl update --uid=…" is the *suggested*
UID only. On each system the user logs in a so called "binding" is
generated which extends the user records and "binds" the user record
to the local machine. The actually used UID is stored as part of the
binding. On first log-in the suggested UID is attempted to be
used. If however the UID is already taken by some other UID a new
random, free one from a certain range is selected. The binding
remains stored on the host so that whenever the user returns to the
host they'll get the same UID again.

For details about user records and their bindings see this:

https://systemd.io/USER_RECORD

Now, if you want to change the UID in the binding, the best is to
simply remove the binding. On the lower level we have a command for
that "unregister", which however is currently not exposed in homectl
(we probably should add that though). However, you can trick homectl
to act in "unregister" mode. For that, simply move away the user's
home directory for a moment, after logging out of course. (e.g. mv
home/lennart.home /home/lennart.home-disabled), then issue "homectl
remove lennart". Since the home directory is not accessible then this
just removes the binding. (normally, "homectl remove" removes both
binding and the actual home directory too). Then, just move it back
in. It will then not be registered on the local system yet (i.e. has
no binding yet), and when you log in first, the binding will be
created, taking any newly configure suggested UID into account.

**Comment by heywoodlh** [comment]
Thank you for the detailed response (and all your work on systemd-homed, it is awesome).

Sorry about posting here and not the mailing list. 
I didn’t even know a mailing list existed! I will make sure to send an email there in the future. 

If it’s not too much of a bother, which mailing list would be best for this kind of question? Devel, commits and bugs are the lists I found via Google and none of those seem appropriate just going off the title.

**Comment by poettering** [comment]
The mailing list is linked from the man repo page, in the README blurb at the bottom. And in the CONTRIBUTING document that is linked from the issue submission form...

https://systemd.io/CONTRIBUTING/#filing-issues
