### ISSUE TITLE
systemd floods log when sysfs paths are too long

### ISSUE THREAD

**Issue by dougmill-ibm** [systemd/systemd#16161]
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > RHEL 7.7 (systemd-219-67.el7.ppc64le)

**Expected behaviour you didn't see**
 > Systems logs are quiet and do not fill rapidly

**Unexpected behaviour you saw**
 > Systems logs were noisy and filled rapidly

**Steps to reproduce the problem**
Behavior seen continuously on system with SAS disks in enclosures, resulting in long paths in sysfs for devices. This leads to long filenames created by systemd which can exceed 255 characters in length, resulting in OS errors when those filenames are used. Typical message:

systemd: Failed to set up device unit: Invalid argument

1132507 of these messages were seen in one /var/log/messages file, as an example. The system had multiple LSI9305 adapters and several Seagate 4U106 enclosures, so many disk drives and several paths to each drive. The resulting systemd filenames were over 260 characters in length. It appears that the exact platform hardware makes a difference, as another system with a different PCI bus layout showed systemd filenames that were ~240 characters long and thus never broke the OS filename limit.

A similar/related problem was fixed in issue #6867, but the fix was not broad enough to fix all cases where these long filenames are being created and used.

**Comment by poettering** [comment]
I guess we should do what 2c905207db37c691d4abef868165ad5ea2dd0f4f did for mount units for device units too, i.e. make logging more verbose, but ratelimit this specific cause.

**Comment by poettering** [comment]
(i general, sysfs synthesizes file names from device paths too, and udev synthesizes /dev/by-path/ symlinks for such device nodes. Because that is how it is I would really encourage people who maintain these drivers to not use such ridiculous long names. It's going to break here, and in udev and in the kernel too, sooner or later. And it's unlikely this will ever get fixed: from our systemd pov we'll instead just simply stop doing our thing for such long names, and people are left on their own with them. or to say this differently: we can tweak our logs of course, but the problem is that these names are just ridiculously long, and that's really what you should address.)

**Comment by DemiMarie** [comment]
Another option is to relax the length requirement.  We don’t actually need to generate a file for each unit we have, especially for mount and device units.  And there is absolutely nothing wrong (from a kernel perspective) with a very long mountpoint name.

If we need to create a file on disc, we can use a hash of the name instead of the name itself.

**Comment by DemiMarie** [comment]
Yet another option is to create a symlink to the mount point somewhere under `/run`, and manage that instead of the actual mount point.  The same can be done with device units.

**Comment by poettering** [comment]
Hmm, does anyone have a good idea how i can artificially create a device with an overly long sysfs path like this? I have a patch ready, but no nice way to test this...

**Comment by DemiMarie** [comment]
> Hmm, does anyone have a good idea how i can artificially create a device with an overly long sysfs path like this? I have a patch ready, but no nice way to test this...

Will the patch actually make the code work, or just stop the log spam?  The latter would still be an improvement, of course, but I would prefer the former as you might imagine.

**Comment by poettering** [comment]
I prepped #19801 now, which puts a ratelimit on the logs generated because of this. It does not allow systemd to manage such devices (we'll just briefly log and ignore them otherwise) but as I understand so far the systems that have such ridiculous long sysfs paths are not the kind where systemd should manage these devices really.

or to say this differently: as long as we can get away with gracefully handling such devices by logging briefly and ignoring them I'd really try to do that.

**Comment by DemiMarie** [comment]
> as I understand so far the systems that have such ridiculous long sysfs paths are not the kind where systemd should manage these devices really.

Would you mind explaining this?

> or to say this differently: as long as we can get away with gracefully handling such devices by logging briefly and ignoring them I'd really try to do that.

 Ignoring the problem works fine for device units, but it causes #17684 for mount units.  And an artificial limit on mountpoints is rather annoying.

**Comment by poettering** [comment]
> > as I understand so far the systems that have such ridiculous long sysfs paths are not the kind where systemd should manage these devices really.
> 
> Would you mind explaining this?

From discussions about the background of these issues I was told that the storage hw that results in these huge sysfs paths is usually large disk arrays, whose disks are not individually mounted by systemd anyway, and everyone was happy that these block devices would just show up in udev hence, but not in pid1.
 
> > or to say this differently: as long as we can get away with gracefully handling such devices by logging briefly and ignoring them I'd really try to do that.
> 
> Ignoring the problem works fine for device units, but it causes #17684 for mount units. And an artificial limit on mountpoints is rather annoying.

The limit isn't precisely artificial. It's the filename length. And that' because we generally want a 1:1 bijective mapping between unit names and the files on disks where their configuration data is stored in, and (if this applies) the primary id of the underlying kernel object they expose (which for devices is the sysfs path). And we want to be able to easily convert this primay id to the unit file names and back. So, for device units we want to trivially map between unit names, their files on disk and the sysfs path. This works really well as long as the kernel's sysfs path length fit into filenames, and didn't use to be a problem. This only started to become a problem once kernel starting to generate such huge sysfs path on specific types of hw, which I think is a bad idea (and probably unnecessary too, the paths are needlessly verbose).

**Comment by dougmill-ibm** [comment]
The issue here is that using a path-name as a file-name is fundamentally unworkable because the maximum allowed length of a path-name is much larger than that of a file-name. The sysfs paths are created based on the hierarchy of the device, and as more complex device hierarchies come into existence, the sysfs path-names become longer. Any scheme where the systemd device file-name length is directly proportional to the sysfs path-name will break under these circumstances.

Regarding whether such devices are mounted by systemd, I can only say that the customers that originally encountered this problem were not using these disks that way. However, there is nothing about these disks that would/should prevent a customer from having systemd mount them, or at least one/some of them.

**Comment by dougmill-ibm** [comment]
This patch is just delaying the real issue. I'm not convinced that this issue should be closed.

**Comment by keszybz** [comment]
I don't see this going anywhere unless someone who has access or knowledge about such hardware comes up with a good use case where systemd showing such devices would be needed. It is true that in principle this *could* be useful in some scenarios, but this is not enough. If we are to add a significant complication to the core systemd code and logic of naming units, there should be a practical reason, not just theoretical considerations without any examples.

**Comment by dougmill-ibm** [comment]
I misunderstood the implications of issue #17684: in that issue it is that the *mount point*, after being escaped, exceeds 256 bytes. While mount points are paths, and as such could easily exceed 256 bytes before escaping, this is another example of the same flawed scheme being used elsewhere in systemd (translating a pathname into a filename, which is not going to work in all situations - i.e. is not scalable).

If there is nothing preventing a customer from mounting, or otherwise using, disks that systemd is unable to create device objects for then I guess this can be closed. I suspect there will be more problems in the future related to the use of this scheme, but I understand how deeply this was designed into systemd and how difficult it will be to fix it. Hopefully, when the next replacement for systemd is designed, the lessons learned here will lead to a better design.

**Comment by poettering** [comment]
I think the story for mount units is different: there, the paths that systemd is supposed to manage are chosen by the admin or developer, in almost all cases. And admins/developers usually prefer paths they can actually type in and thus aren't really keen on ridiculously long names. I mean, to this point the only complaint we got about the limit was about the unicode thing, where the escaping reduces the effectively allowed maximum length quite a bit. (The other reports are only about log noise, not the fact that systemd won't manage such long mount paths)

For these sysfs paths things are different: these path are generated automatically, they cannot be chosen directly by the admin. And while some subsystems are pretty good at generating reasonably short paths, others are less so.

I am pretty sure keeping the paths reasonably short is generally a good idea, regardless if you care about systemd or not. Hence I'd always advise kernel subsystems maintainers to not go overboard with super long sysfs paths, noone is really helped with that.

In general: we can certainly revisit all this one day, once people *actively* report to us that they wanted to manage a device with systemd, but systemd couldn't because of the limit — and the cause is not artificial or caused by sloppy sysfs path design of the subsystem maintainers. We could certainly find a different way to map such overly long paths, but whatever we do, we ultimately always want to map them back to a filename, and if a sysfs path is excessively long that's never going to be nice, and always going to be cryptic. If we use hashing then the transformation from sysfs paths to unit names will not be reversible, which is ugly, but not a total disaster, given that the reversibility of the transformation is mostly used to make things convenient, since it allows unit names and sysfs paths to be usable entirely interchangeably, and allows people to translate the unit names to paths and back in their head without any special tools doing the transformation for them.

Anyway, as long as we can get away with it, I'd rather not go down this path though. It deteriorates usability. Long sysfs do that in any case. I'd really recommend subsystem devs to not go down this road, their userbase won't enjoy this either way.

**Comment by dougmill-ibm** [comment]
Yes, the main problem with mount points is for multi-byte characters. But there are systems that generate mount point paths internally, automatically, and so human typing is not involved. However, I know of none that would generate such a long path - but they could.

Our current customers are using udev rules to prevent systemd from trying to manage devices with long sysfs paths, and that may be the recommended configuration even with this patch, as these systems have hundreds of disks/paths and reducing the resources consumed by systemd for them is probably a good thing - although it is unclear just how much is gained.

**Comment by rogerwegmanneit** [comment]
Using microk8s (a snap) in combination with cephcsi will generate very long mount points:

/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/rbd.csi.ceph.com/d489af1c2bf3d99a146235ac05e9ec6c165a2366deacb4b25dcb08e1a34f2b15/globalmount/0001-0024-aa1322ff-d015-4b96-a375-9d0f542e3559-0000000000000003-aadb9ad5-d127-40b3-ab95-b8785a799e36
