### ISSUE TITLE
LogNamespace= for timers

### ISSUE THREAD

**Issue by bjoe2k4** [systemd/systemd#16272]
**Is your feature request related to a problem? Please describe.**
I am very happy about journal namespaces and was about to start to put all the timers that run every 5 minutes (which therefore clutter the default journal) into their own namespace. After adding the appropriate `LogNamespace=cron` directive to the `[Service]` section in the service files, all the `Starting bla`, `Started bla`, `Finished bla` and `bla: Succeeded` entries still appear in the default journal.

**Describe the solution you'd like**
Allow timers to accept a `LogNamespace=` *or* make timers inherit the lognamespace of the service they are activating.

**Describe alternatives you've considered**
Run a good old cron daemon.

**Comment by poettering** [comment]
LogNamespace= changes where the processes forked off on behalf of service units log to. It does not affect where PID 1 logs to about that service.

timer units have no forked off processes associated with them. Hence LogNamespace= doesn't apply to them, how could it?

PID 1 is one process and logs to a single journal instance. That relationship betweend PID1 and journald is complex enough, since PID 1 spawns it but also is a client to it, which means chances for dead locks are everywhere. I am very strongly against making this even more complex, by making PID 1 be client to a multitude of journald instances.

Anyway, sorry, but this is not going to happen. One service should log to one namespace, and for PID 1 that's the main journal namespace. Sorry.
