### ISSUE TITLE
Add GracePeriod= key to .path units

### ISSUE THREAD

**Issue by mathstuf** [systemd/systemd#1628]
When I update my dotfiles repo, my dotfiles are written to by git rapidly and triggers the rate limiting for restarting unit files. It would be nice to have the `.path` units which watch files (such as reloading XMonad when its configuration changes) to have a grace period so that rapid writes are grouped together.

**Comment by poettering** [comment]
How exactly do your .path units look like?

Note that it's a pretty bad idea to automatically reload services if their configuration files change, in particular if you have multiple files that are read together. This is because services that way might read half-written files, or files twice or not at all if they are renamed.

**Comment by mathstuf** [comment]
Here's one:

```
[Unit]
Description=XMobar Watcher

[Path]
PathChanged=/home/boeckb/.config/xmobar/xmobarrc
Unit=xmobar.target

[Install]
WantedBy=x11-standard.target
```

The `xmobar.target` Wants a set of `xmonad@.service` files, one for each monitor.

**Comment by dvdhrm** [comment]
You should never watch configuration files. This is just wrong. Once your editor does not use atomic file-replace, you're screwed.

Furthermore, if you hook into an event that happens too often, you should ratelimit your handler, not the event (or rethink your design, whether it really makes sense to watch high-frequency events). Last but not least, `path` units are really not designed for that. You should rather use your own inotify-based monitor, if you really want that feature.
