### ISSUE TITLE
shutdown -r now should display broadcast message

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#1631]
For compatibility reasons.

https://bugzilla.redhat.com/show_bug.cgi?id=624149#c36

"Which is useful if there are people logged in and you want them to know why they got disconnected."

**Comment by poettering** [comment]
We always did that. In old versions the message was generated from the shutdown binary, which meant it wouldn't work from unpriviliged invocations. Since 225 we generate it from logind instead, which means it always works. Either way I see nothing to fix here. Unless this bug is about the code in 225 being broken?

**Comment by jsynacek** [comment]
Yes, the message is logged, but not visible in the terminal like the original reporter suggested.
