### ISSUE TITLE
Allow determining which target is currently being attempted to reach

### ISSUE THREAD

**Issue by BrainStone** [systemd/systemd#16352]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to figure out what state of the boot cycle the machine is currently in. Meaning I'd like to know if it's booting, if it has finished booting or if it shuts down or reboots.

This *could* be fairly easily determined if the target systemd is currently trying to reach was accessible.  
For example if the target it is trying to reach is multi-user.target but that target is not active, the machine is booting. Once it is active, it has finished booting. And if it tries to reach shutdown.target it's shutting down.

**Describe the solution you'd like**
A simple command that outputs the current target systemd is trying to reach. Similar to ``systemctl get-default``. I'd propose ``systemctl get-target``.

**Describe alternatives you've considered**
I'm very aware that something similar can be achieved by adding services to systemd. But that is really not ideal when trying to use commands to query the state systemd is in.  
Another alternative would be systemd writing that status to a publically readable file.

**Comment by falconindy** [comment]
Are you aware of `systemctl is-system-running`? The manpage documents various states that are returned by this command, including `starting` and `stopping`.

**Comment by BrainStone** [comment]
No I was not. Thank you for pointing this command out to me.  
While that covers my use case I still think exposing the current targetted target might be worth exposing.

**Comment by poettering** [comment]
Thereq are typically multiple targets queued at boot. Targets are not runlevels, i.e. we activate any number of them, and combine their deps into a single transaction. In fact, it typically even happens that later during boot more targets are enqueued. hence what you are asking for isn't really something we can reasonably do, because any number of targets can be defined and enqueued.

You could do "systemctl list-jobs | grep target", but would that really help you much?

We could alternatively add "systemctl -t target list-jobs", to make this a tiny bit nicer, but the essence is always: it's a list of targets you'll get back, not a single one.

Given your usecase I think "systemctl is-system-running" is the way to go, hence I am tempted to just close this?

**Comment by BrainStone** [comment]
Thank you very much for your insight.  
Having ``systemctl -t target list-jobs`` would certainly be nice to have but of course it's not a priority.

Considering my usecase is covered with ``systemctl is-system-running`` I'm absolutely ok with closing this.
