### ISSUE TITLE
Systemd-boot and full disk encryption

### ISSUE THREAD

**Issue by Khomyak-sibiryak** [systemd/systemd#16434]
The grub2 bootloader recently started supporting luks 2 encryption, which allows for full disk encryption. Does systemd-boot support luks 2 encryption or other types of encryption? How can I achieve full disk encryption using systemd-boot?

**Comment by poettering** [comment]
Full Disk Encryption is something implemented on the OS level, i.e. for the OS file systems.

UEFI's boot protocol involves the EFI System Partition (ESP), which cannot be encrypted, the UEFI spec doesn't allow that. It needs to be unencrypted VFAT. EFI's SecureBoot logic then allows to lock down the binaries found there, and ensure that unsigned binaries cannot be run. There's no point in encrypting the ESP, as those binaries are signed, and given that in our case Open Source encrypting such binaries is pointless anyway, you can acquire/rebuild the unencrypted binaries anyway from data/code freely available on the Internet.

systemd-boot is a single EFI binary dropped into the ESP, and the kernels and initrds too. The idea is to sign them with signature keys enrolled in the firmware (SecureBoot). The kernels/initrd then boots up, and decrypts your root fs and other file systems, to implement full disk encryption. 

When Grub is used in UEFI mode, the initial process also relies in unencrypted files (it *has* to be that way, because – as mentioned — EFI doesn't allow the ESP to be encrypted). This is hence no difference.

What Grub can do, what sd-boot cannot is load the kernels/initrds from some other encrypted medium. However, was mentioned this is not how sd-boot works, we just expect the kernels/initrds to be signed themselves if you want a fully locked down system, so that everything becomes a lot simpler.

**Comment by z36r2850o** [comment]
@poettering What about computers that support UEFI boot but don't support SecureBoot? For them, kernels/initrds are left defenseless.

**Comment by dngray** [comment]
> @poettering What about computers that support UEFI boot but don't support SecureBoot? For them, kernels/initrds are left defenseless.

Authentication is not encryption. You could just replace the boot volume with something else. If they don't support UEFI they don't support SecureBoot either, so they are still defenceless.

Encryption provides no protection to predictable data if it is not authenticated.

**Comment by cyruseuros** [comment]
@poettering There is also the issue of booting into system snapshots (the way opensuse does). Even if you snapshot your root filesystem, you're probably left with a non-corresponding kernel in the boot partition leaving your system in an inconsistent state (if you keep old images around, you have to arrange for cleanup, mapping to snapshot IDs...). The only way to do this right is to have the boot partition be _in_ the filesystem snapshot. It would be nice if this was at least plugable functionality in systemd-boot - like https://efi.akeo.ie/

**Comment by arvidjaar** [comment]
> (if you keep old images around, you have to arrange for cleanup, mapping to snapshot IDs...)

That is exactly what SUSE does to integrate systemd-boot.

**Comment by cyruseuros** [comment]
@arvidjaar didn't know that! Their solution for anyone interested https://github.com/openSUSE/sdbootutil/blob/main/ARCHITECTURE.md
