### ISSUE TITLE
IdleActionUSec is undocumented property with systemd command

### ISSUE THREAD

**Issue by swestlake** [systemd/systemd#16448]
https://www.freedesktop.org/software/systemd/man/logind.conf.html
 does not define "IdleActionUSec" as a property, 

looking at 
https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html
^ IdleActionUSec is mentioned (and no mention of IdleActionSec)

using distribution- debian 10 x86_64-bit with systemd release 245.6-1.

'loginctl show-session --all' shows
"IdleAction=ignore
IdleActionUSec=30min"

was IdleActionSec renamed to IdleActionUSec ?

I don't see any mention about it so I am posting this as a bug..

-- unrelated:: for some reason "ssh" lingers after a user has logged out of his Desktop environment (disable-linger has already been applied to that user).

^ If this is NOT a bug, then supposedly this "IdleActionUSec" is for logind entries in,
/usr/lib/systemd/logind.conf.d/*.conf

I couldn't find any documentation on IdleActionUSec other than it is a property on the logind manpage, but the explanation for it -- to be found is for "IdleActionSec" and not for "IdleActionUSec".

Perhaps the documentation also needs to be corrected.

thanks

**Comment by poettering** [comment]
D-Bus properties expose low-level, normalized types. All time values are expressed as integers in microsecond units.

This is different from logind.conf where we expose more human friendly ways to express stuff, i.e. "5min 3s" strings. When times are specified without units we imply seconds. That's why the setting in the configuration file is named "Sec", and the one in the D-Bus property "USec".

They do refer to the same concept though, just have different default units.

The D-Bus property is documented in the new org.freedesktop.login1 man page that has been added in the upcoming v246 release, hence closing.
