### ISSUE TITLE
 Multiple different sessions support sharing the same cgroup

### ISSUE THREAD

**Issue by JackFangXN** [systemd/systemd#16499]
**Is your feature request related to a problem? Please describe.**
I miss a issue that start many sftp tasks to tranfer files in memory file system. one task create one session and one cgroup. The size of one cgroup maybe 0.5M, when start 20000 sftp tasks the memory may be use 10G.  

**Describe the solution you'd like**
I hope that many sessions can sharing the same cgroup by one configuration if i want.
**Describe alternatives you've considered**
Sorry, i don't know how to do, so i want to discuss that is it ok or not.

**Comment by poettering** [comment]
No, we use cgroups to manage sessions, and running multiple sessions in the same cgroup defeats the whole point. 

cgroups don't really take up memory (except for a tiny bit of accounting data), processes in them take up memory. Hence if you place multiple sessions in the same cgroup you only save a tiny bit of memory.

Note that all sessions of a user are placed within the same per-user slice, i.e. a common surrounding cgroup.

Sorry, but this is nothing we want to support, hence closing.

If the session management done by logind is to heavy, I'd suggest taking pam_logind out of your sftp PAM stack. But of course this means that logind won't know about these sessions anymore. But since logind's session management primarily means "management by cgroup" placing all of them in one cgroup really defeats the point of logind, and your best way out is to simply not use logind for those sessions.

Hope that makes some sense?
