### ISSUE TITLE
Add bsdtar(libarchive) support to machinectl/importd

### ISSUE THREAD

**Issue by tpgxyz** [systemd/systemd#16506]
**systemd version the issue has been seen with**
> 235

**Used distribution**
 > OpenMandriva LX cooker

**Expected behaviour you didn't see**
 > Works

**Unexpected behaviour you saw**
 > machinectl fails to import compressed images if bsdtar is default tar program

**Steps to reproduce the problem**
1. install libarchive
2. make sure bsdtar is default tar command in your system
3. machinectl import-tar foo.image.xz
4. observe error

```
[root@lazur TEST]# LC_ALL=C machinectl import-tar image.raw.xz OMV
Enqueued transfer job 1. Press C-c to continue download in background.
Importing '/home/tpg/OpenMandriva/TEST/image.raw.xz', saving as 'OMV'.
tar: Option --xattrs-include=* is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
Failed to decode and write: Przerwany potok
Exiting.
```

**Comment by poettering** [comment]
Hmm, what? /usr/bin/tar points to a command that is not command line compatible with GNU tar on some really basic features on OpenMandriva? That sounds like something to fix in OpenMandriva. We don't use crazy parameters here, xattrs are not that exotic...

**Comment by poettering** [comment]
under which name does openmandriva provide the gnu tar implementation? I figure we can call "gtar" or so before "tar" to cover cases like this.

**Comment by tpgxyz** [comment]
@poettering Yes we do provide a tar and cpio symlinks to bsd{tar,cpio}.
We renamed tar to gtar and it's not even in our main repo, as it is not well maintained compared to libarchive.
bsdtar does not support `--xattrs-include=*`, yet it supports `-p` to preserver file permissions while extracting.

We tries to fix things by checking tar implementation and then use one of two attributes list to match found tar or bsdtar.

For now i'm going to patch it downstream.

**Comment by poettering** [comment]
> @poettering Yes we do provide a tar and cpio symlinks to bsd{tar,cpio}.
> We renamed tar to gtar and it's not even in our main repo, as it is not well maintained compared to libarchive.

Yeah, but it's incompatible. You just create maintenance burdens with that. Unless the command lines are entirely interchangeable it's just a maintenance headache, since the "tar" command line effectively is API on Linux, used by a myriad of tools, and you just broke API.

Anyway, fix pending in #16533.

**Comment by poettering** [comment]
> Anyways does `--xattrs-include=*` makes any sense if by default `--xattrs` pulls all the attributes in ?

On Fedora it's necessary at least to get the whole bunch. I have not tested things elsewhere...

**Comment by tpgxyz** [comment]
> Yeah, but it's incompatible.

That's why we file issues for software that does rely on tar options which are not supported by libarchive's tar. Like we pushed changed to rpm, mock, dracut and even steam to help support libarchive.

Have you considered to check `tar --version` output and if it is bsdtar then use bsdtar compatabile  list of options ? Your PR #16533 solves this by adding `Requires: gtar` to systemd's rpm which leads to pulling another dependency.

Why not use:
```
                execvp("bsdtar", "-C", path, "-c", "--xattrs", ".", NULL);
                execvp("tar", "-C", path, "-c", "--xattrs", "--xattrs-include=*",
                       use_selinux ? "--selinux" : "--no-selinux", ".", NULL)
```

**Comment by poettering** [comment]
> That's why we file issues for software that does rely on GNU tar options which are not supported by libarchive's tar. Like we pushed changed to rpm, mock, dracut and even steam to help support libarchive.

Easier fix: just use gnu tar like everyone else? Or teach libarchive the options the established implementation everyone uses supports? i.e. why expect the many to adjust to the few here, instead of adusting the few to just make things work with the many?

**Comment by poettering** [comment]
or replace "tar" by a kludgy shell script that maps the env vars and calls your own tar version if needed. Not sure why we should do that in our code however.

I'd be willing to merge a patch that would allow overriding the tar binary to invoke. i.e. let's say we define $TAR as env var to honour if set, to call instead of "gtar" or "tar". Then you can maintain your own script that mangles the cmdline and passes things on to the tar implementation you care about. And you could ship that script in your RPM, along with a drop-in file for systemd-importd.service that uses Environment= to override $TAR. That way you could add in compat with any tar implementation you like, without patching systemd, and you'd pay the price for maintaining that...

**Comment by tpgxyz** [comment]
@poettering At the end of the day i'm fine with your PR, at least things got improved.
Speaking of adding compat options to libarchive it's quite complicated, as author keeps compatibility with POSIX.
I've explained that GNU tar is not well actievly maintained so we decided to switch to libarchive 5 years ago.
I may prepare PR for libarchive's tar to skip --xattrs-include option.
Thanks.

**Comment by poettering** [comment]
> Speaking of adding compat options to libarchive it's quite complicated, as author keeps compatibility with POSIX.

POSIX never standardized xattrs. There was a draft, Linux implemented it, but it was never finalized iirc. So that tar implementation of yours doesn't support that either? I am sorry, if that's the case, then your implementation is simply not suitable for our importd usecase here, and we shouldn't use it anyway here...

(If people see POSIX as a religion, and don't accept the real world — i.e. a world where GNU tar is the de-facto standard and xattrs exist — then I'd really stay away from such software. it's not help if the software if the software is better maintained than GNU tar, if it doesn't implement what is needed and is compatible with the real world. it appears the maintainer is more interested in religion then solving real-life problems. I don't really understand why you are making these problems your own though... That just creates churn)

**Comment by tpgxyz** [comment]
@poettering I just wrote that author of libarchive tries to keep things close to POSIX, and not always accepts what user needs and uses on daily basis. libarchive does support `--xattrs` but does not `--xattrs-{include,exclude}`

**Comment by berolinux** [comment]
The main reason for switching to libarchive tar was that it is, in very many ways, better. Among other things, being built around libarchive, it can open all sorts of different file formats, so you no longer need lots of tools that all do the same thing ("tar xf whatever.zip" is rather useful -- so is not needing any special tools to look into an iso file, "tar tf whatever.iso" is a lot simpler than loopback mounting it somewhere to look into it).

In the real world, there are multiple implementations of tar where GNU tar is most common on desktop and server Linux systems, but that changes as soon as you start taking embedded devices (where busybox and toybox are the most common implementations) or the BSD world (which has standardized on libarchive tar) into consideration.

All the common implementations are similar but diverge on a few options (typically busybox and toybox removing "bloated" things that aren't needed on a typical embedded device [sometimes including xattrs], and libarchive tar keeping its own flags for functionality that was added there before GNU tar added it in a somewhat different way).

I agree that it would be a good idea to patch libarchive tar for even better compatibility. But that doesn't address busybox/toybox/... (where such patches would be rejected as "bloat"). Of course machinectl is unlikely to be used on an embedded device - but if someone tries, the need to handle multiple tar implementations will resurface.

**Comment by poettering** [comment]
Well, we don't need support for zips really here. In fact we really don't want that, to not create needless incompatibilities. And a tar that doesn't do xattrs is not useful here either, we don't want to support such images. 

Anyway, if you want to support other tars, knock yourself out, but I think it's on you to carry the compat kludge then or get the compat support merged upstream in your tar. We will now automatically prefer gnu tar, to avoid this mess, and I'd be willing to add a patch that allows override which tar implementation is used via an env var (as mentioned above), but key really here is that I don't want to deal with maintaining compat with multiple tar implementations, but I want that the burden for that is either on the maintainers of those implementations or on the ones packaging and making them the default, but not us upstream here. Hope that makes some sense.

**Comment by tpgxyz** [comment]
@poettering I may have been misunderstood, due to my poor english language skills, and i really DO NOT want force you to support any other tar implementaions on this planet. I'm perfectly happy that you added support for gtar. Anyways i've filled a bugreport on libarchive https://github.com/libarchive/libarchive/issues/1416
