### ISSUE TITLE
The cgroup path of PID1 changes when systemctl daemon-reload

### ISSUE THREAD

**Issue by JackFangXN** [systemd/systemd#16549]
**systemd version the issue has been seen with**
> ...
systemd 243, 245

**Used distribution**
 > …
In systemd 243 version
![image](https://user-images.githubusercontent.com/53254947/88257618-bb036280-ccf0-11ea-9844-0773fd9cef72.png)

In systemd 239 version
![image](https://user-images.githubusercontent.com/53254947/88257893-67dddf80-ccf1-11ea-8891-ccd7832d5c81.png)

I want to know which commits cause this change?  if i want to change pid1 cgroup path and how should i do ?
**Expected behaviour you didn't see**
 > …
1、echo 1 > /sys/fs/cgoup/test/tasks
2、systemctl daemon-reload

PID1 stays in /sys/fs/cgoup/test/tasks

**Unexpected behaviour you saw**
 > …
1、echo 1 > /sys/fs/cgoup/test/tasks
2、systemctl daemon-reload

PID1 don't stays in /sys/fs/cgoup/test/tasks and recove in /
**Steps to reproduce the problem**
1、cat /proc/1/cgroup,  PID1 memory cgroup path is /
2、mkdir /sys/fs/cgroup/memory/test
3、echo 1 > /sys/fs/cgroup/memory/test/tasks
4、cat /proc/1/cgroup,  PID1 memory cgroup path is /test,  and PID1 stays in test/tasks.
5、systemctl daemon-reload
6、cat /proc/1/cgroup， PID1 memory cgroup path change / and PID don't stay in test/tasks.

**Comment by JackFangXN** [comment]
I want to know which commits cause this change? if i want to change pid1 cgroup path and how should i do ?

**Comment by poettering** [comment]
I am sorry, but this is simply not supported. You cannot move stuff around in the cgroup tree unless you do it in your own delegated subtree.

systemd when it first initializes runs in the root cgroup, because that's where the kernel puts it. it then moves itself down to `init.scope`. When it reexecs (due to systemctl daemon-reexec or systemctl switch-root) it already is in `init.scope` so it doesn't do anything in that case. It hence has code during early initialization where it checks if it already is at the right place, or needs to be moved there.

**Comment by JackFangXN** [comment]
tks, bu i still want to know which commits cause the change between systemd239 and systemd243. Because there are many old usage(echo pids > cgroup path) in my customer, maybe i want to revert in old products.

**Comment by JetXujing** [comment]
I found that in v249, the result for `cat /proc/1/cgroup` is as follows:
![image](https://user-images.githubusercontent.com/43668249/168775728-09bf6c76-ed5f-4991-8009-5e89252f4568.png)

I fount /sys/fs/cgroup/memory/init.scope is not created.
```
[root@localhost ~]# ls /sys/fs/cgroup/memory/init.scope
ls: cannot access '/sys/fs/cgroup/memory/init.scope': No such file or directory
```

What caused the change?
