### ISSUE TITLE
nspawn: container doesn't exit, when an X11 client inside the container exits

### ISSUE THREAD

**Issue by maxbrieiev** [systemd/systemd#16581]
**systemd version**
`systemd 245 (245.6-8-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid`

**Used distribution**
Arch Linux

**Issue**

I use `systemd-nspawn` to run a graphical app inside the container.
If I run the app inside current Xorg session, then all works fine (launch and exit is handled by nspawn gracefully).

If I run the application on a separate tty (starting new Xorg instance and the container through xinit), then the app is launched and works correctly, however, when the app exits, the container continues to run, and as a result the Xorg does not shutdown.

Here is the process tree.

```
root     11:blkio:/system.slice,9:de login -- maxim
maxim    11:blkio:/system.slice,9:de  \_ /bin/sh /usr/bin/startx /home/maxim/.xinitrc emacs
maxim    11:blkio:/system.slice,9:de      \_ xinit /home/maxim/.xinitrc emacs -- /etc/X11/xinit/xserverrc :2 vt3 -keeptty -auth /tmp/serverauth.yylLCmTyu6
maxim    11:blkio:/system.slice,9:de          \_ /usr/lib/Xorg -nolisten tcp :2 vt3 -keeptty -auth /tmp/serverauth.yylLCmTyu6
root     11:blkio:/system.slice,9:de          |   \_ xf86-video-intel-backlight-helper intel_backlight
root     11:blkio:/system.slice,9:de          \_ sudo systemd-nspawn --setenv=DISPLAY=:2 -aD /mnt/arch emacs
root     11:blkio:/system.slice,9:de              \_ systemd-nspawn --setenv=DISPLAY=:2 -aD /mnt/arch emacs
root     0::/machine.slice/machine-a                  \_ [(sd-stubinit)] <defunct>
```
As can be seen `emacs` process became defunct after exit, but for some reason it still sits there, systemd doesn't reap it even with `-a` flag.

**Steps to reproduce the problem**

Start `X11` server on some `tty`, then launch a graphical application inside the container (you may also need to run `xhost +local:` to allow xorg to accept requests from the container).

This can be achived, for example, by adding the following line to the end of your `.xinitrc` file.

```
xhost +local:
exec sudo systemd-nspawn --setenv=DISPLAY=:1 -aD /mnt/arch emacs
```

**Comment by poettering** [comment]
hmm, this does look like a bug... the stubinit appears to die but nspawn doesn't collect it...

Any chance you can "strace -s 500 -o log" the nspawn invocation and provide the logs this generates?

**Comment by maxbrieiev** [comment]
Strace log attached
[log.txt](https://github.com/systemd/systemd/files/5002223/log.txt)

And here is relevant `ps` output:

```
   3871 login -- maxim
   4256  \_ /bin/sh /usr/bin/startx /home/maxim/.xinitrc emacs
   4280      \_ xinit /home/maxim/.xinitrc emacs -- /etc/X11/xinit/xserverrc :1 vt3 -keeptty -auth /tmp/serverauth.0d2Ks7f4tY
   4281          \_ /usr/lib/Xorg -nolisten tcp :1 vt3 -keeptty -auth /tmp/serverauth.0d2Ks7f4tY
   4283          |   \_ xf86-video-intel-backlight-helper intel_backlight
   4290          \_ sudo strace -s 500 -f -o /tmp/log systemd-nspawn --setenv=DISPLAY=:1 -aD /mnt/arch emacs
   4299              \_ strace -s 500 -f -o /tmp/log systemd-nspawn --setenv=DISPLAY=:1 -aD /mnt/arch emacs
   4302                  \_ systemd-nspawn --setenv=DISPLAY=:1 -aD /mnt/arch emacs
   4304                      \_ [(sd-stubinit)] <defunct>

```

**Comment by poettering** [comment]
hmm, this is interesting. in line 2079 of that strace we see that pid 4302 gets a SIGTTOU and then is suspended and stays that way. that happens after pid 4305 issues setsid()...

**Comment by poettering** [comment]
4305 is what eventually becomes emacs btw...

**Comment by poettering** [comment]
hmm, how precisely do you invoke nspawn? from a shell script with `&`?

The SIGTTOU is sent by the kernel to a process, if it tries to write to or change params on a tty while not being in the foregorund process group. This typically happens when you create a bg process group with the shell's `&` construct. When SIGTTOU is received by a process it will suspend (equivalent to SIGSTOP), and that's what you seeing: nspawn is suspended while the container payload keeps running.

You invoke nspawn with an interactive tty, if you do that in the bg then job control means it is suspended until you put it in the foreground again.

Hence I think the behaviour is to be expect – of course if you invoke things with `&`. Do you?

One could argue that if nspawn itself is suspended due to SIGTTOU (or SIGSTOP or similar) that it should somehow suspend the container it manages, as well. Not entirely sure how to do this best. Probably needs to involve the cgroup freezer in some form.

You can work around this by using "-P", so that tty handling is not done.

**Comment by maxbrieiev** [comment]
I invoke it as `exec sudo systemd-nspawn --setenv=DISPLAY=$DISPLAY -aD /mnt/arch emacs` within my `.xinitrc` script.

I have this line in my bash profile:
```
[[ -z $DISPLAY && $XDG_VTNR -eq 3 ]] && exec startx $HOME/.xinitrc emacs
```

And here is my `.xinitrc` file:

```
#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xset r rate 175 50

session=${1:-xmonad}
xhost +local:
case $session in
    xmonad            ) exec xmonad;;
    awesome           ) exec awesome;;
    emacs             ) exec sudo strace -s 500 -f -o /tmp/log systemd-nspawn --setenv=DISPLAY=$DISPLAY -aD /mnt/arch emacs;;
    # No known session, try to run it as command
    *                 ) exec $1;;
esac
```

So basically when I login on `tty3` a fresh X server is started and emacs connects to it from a container.

**Comment by poettering** [comment]
so what's the controlling tty of that .xinitrc script? 

i.e. can your run `ps -eo pid,tty,pgrp,user,cmd f`

my guess is that the X server and your shell script are two process groups inside the same session and thus fight for tty ownership and thus when nspawn does its tty stuff it gets SIGTTOU'ed...

**Comment by maxbrieiev** [comment]
```    663 ?            663 root     login -- maxim
    671 tty3         671 maxim     \_ /bin/sh /usr/bin/startx /home/maxim/.xinitrc emacs
    695 tty3         671 maxim         \_ xinit /home/maxim/.xinitrc emacs -- /etc/X11/xinit/xserverrc :1 vt3 -keeptty -auth /tmp/serverauth.Oey499HqYP
    696 tty3         696 maxim             \_ /usr/lib/Xorg -nolisten tcp :1 vt3 -keeptty -auth /tmp/serverauth.Oey499HqYP
    698 tty3         696 root              |   \_ xf86-video-intel-backlight-helper intel_backlight
    705 tty3         705 root              \_ sudo strace -s 500 -f -o /tmp/log systemd-nspawn --setenv=DISPLAY=:1 -aD /mnt/arch emacs
    714 tty3         705 root                  \_ strace -s 500 -f -o /tmp/log systemd-nspawn --setenv=DISPLAY=:1 -aD /mnt/arch emacs
    717 tty3         705 root                      \_ systemd-nspawn --setenv=DISPLAY=:1 -aD /mnt/arch emacs
    719 ?            719 root                          \_ [(sd-stubinit)] <defunct>```

**Comment by maxbrieiev** [comment]
Here is log file
[log.txt](https://github.com/systemd/systemd/files/5037865/log.txt)

**Comment by poettering** [comment]
so yeah, there you go. All relevant processes have tty3 as controlling tty. and there are three process groups:

1. 671 is startx/xinit
2. 696 is your X server
3. 705 is nspawn

Since X is in the foreground, nspawn is in the bg, and if it then tries to do stuff with the tty it will be suspended by the kernel.

Hence everything is as I suggested and to be expected.

Your best way out is to use -P as suggested to turn off nspawn's tty logic.

Anyway, this is to be expected by job control on UNIX ttys, and has little to do with systemd. It's simply because you have a bg process group doing tty stuff while another proces sgroup is in the fg. and that's between your shell, your xinit/X11 script stuff and you.

You could disconnect from the tty when you do your stuff so that job control won't be bothering anymore. Use the /bin/setsid tool for that.

Either way, I'll add a TODO list item to our list, suggesting we freeze the container payload when nspawn gets SIGSTOP'ed or otherwise suspended. But this is not going to help you with your issue, it just makes things less confusing, since then you won't have this weird state where the container payload runs fine but the container supervisor hangs. You instead have both hang.

**Comment by poettering** [comment]
Closing, since it's not a systemd/nspawn issue, but job control.
