### ISSUE TITLE
System erroneously reported as docked for lid switch event since 226

### ISSUE THREAD

**Issue by LeifW** [systemd/systemd#1658]
Which breaks the default config of suspending for that event. The default action for "lid closed while dock" is ignore.
 This is the cause of #1273

**Comment by poettering** [comment]
I don't grok a word. Can you please elaborate?

What do you see that you don't expect? What don't you see that you do expect?

Which tools report which error precisely? What's the exact output generated? 

What makes you think there's something wrong in systemd? (and not in the kernel/drivers/apps/...)?

**Comment by LeifW** [comment]
It's the cause of the issue reported by myself and others on #1273.

After upgrading to systemd 226 or greater, the HandleLidSwitch action is not executed with the laptop is closed.
The HandleLidSwitchDocked action is executed, though. No docks are involved with this laptop, a/c cord is unplugged, there is only display reported connected in /sys/class/drm/*/status

Booting with the `debug` on the kernel command-line, you see in "journalctl -f" a "System is docked." right after the "Lid closed." action. You do not see this on systemd 225 and earlier.

Pretty sure this is a regression in systemd; this behavior is perfectly reproducible changing nothing on the system besides the installed systemd version.

**Comment by poettering** [comment]
Hmm, maybe you have a laptop that does something weird to the connectors when the lid is closed?

**Comment by poettering** [comment]
Is this still an issue even with current kernels and systemd?

logind considers the system docked (and prints the log message about it) as soon as the SW_DOCKED switch is reported by an input device. It's pretty straight-forward actually, and no black magic in there: as soon as one input device claims SW_DOCKED is set, then we deduce the system is docked.

Most likely one of your input devices reports that switch incorrectly. Consider using "evtest" to see if SW_DOCKED is reported on one of the devices (good candidates are the ACPI and laptop driver input devices). Most likely it's a matter of fixing SW_DOCKED in the specific driver then.

Closing this for now, given the bug is old and against an old version of systemd (at least at this point in time). Please reopen if this is still an issue though. Or comment here. Would be good to check the evtest stuff!
