### ISSUE TITLE
mmap() call in sigbus handler

### ISSUE THREAD

**Issue by rmaddali991** [systemd/systemd#16591]
I see the following sigbus_handler in systemd revision 230.  This handler is simply doing anonymous mapping of bad address.   Can someone please explain the purpose of mapping bad address and continue.  In case of bad address, isn't it better to get the core dump and analyze the reason for bad address ?

 We are observing random zero page corruptions on MIPS based platforms when we have the sigbus_handler installed. I see that we are calling mmap() as part of signal handler. https://man7.org/linux/man-pages/man7/signal-safety.7.html doesn't include mmap() as safe system call to make in signal handler. Can this cause random corruptions ?

```
static void sigbus_handler(int sn, siginfo_t *si, void *data) {
        unsigned long ul;
        void *aligned;
        assert(sn == SIGBUS);
        assert(si);
        if (si->si_code != BUS_ADRERR || !si->si_addr) {
                assert_se(sigaction(SIGBUS, &old_sigaction, NULL) == 0);
                raise(SIGBUS);
                return;
        }
        ul = (unsigned long) si->si_addr;
        ul = ul / page_size();
        ul = ul * page_size();
        aligned = (void*) ul;
        /* Let's remember which address failed */
        sigbus_push(aligned);
        /* Replace mapping with an anonymous page, so that the
         * execution can continue, however with a zeroed out page */
        assert_se(mmap(aligned, page_size(), PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED, -1, 0) == aligned);
}
```

**Comment by poettering** [comment]
We use this to catch I/O errors when doing mmap() access of journal files. I/O errors are not programming errors but runtime errors. Hence catching them and handling them makes sense. This is different from bad memory accesses due to programming errors where segfaulting/coredumping is the approach to take.

mmap() is a thin layer around a kernel syscall, and thus should be fine to call. even from a syscall. It's actually a pretty common technique...
