### ISSUE TITLE
Explain StartLimitIntervalSec= syntax, i.e. seconds as default unit plus reference to systemd.time

### ISSUE THREAD

**Issue by ygoe** [systemd/systemd#16644]
**systemd version the issue has been seen with**
> systemd 245 (245.4-4ubuntu3.1)

**Used distribution**
> Ubuntu 20.04

**Expected behaviour you didn't see**
> No error

**Unexpected behaviour you saw**
> Warning message: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.

**Steps to reproduce the problem**
1. Create a service file with this line: `StartLimitIntervalSec=400`
2. Start it

Documentation: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval

The option `StartLimitInterval` worked without this warning. It's entirely undocumented though. I just used that from an older server setup with Ubuntu 16.04. Now I've seen that this is wrong, according to the docs, so I changed it. Now the software really says it's wrong. Something isn't correct here.

**Comment by zdzichu** [comment]
The documentation is correct. `StartLimitIntervalSec` is a setting for `[Unit]` section, not `[Service]` (since v229, released 2016-02-11).
The name without *Sec is undocumented because it's a legacy compatibility. Rename to *Sec happened in https://github.com/systemd/systemd/commit/f0367da7d1a61ad698a55d17b5c28ddce0dc265a
With 16.04, you probably used a version without above changes.

**Comment by zdzichu** [comment]
Oh, I see where could the problem be. During movement and renaming, the parsing of legacy name and location was probably lost.

**Comment by ygoe** [comment]
This is a sample file:

```
[Service]
Type=exec
ExecStart=/var/www/aspnet/6
Restart=always
RestartSec=15
StartLimitInterval=400
StartLimitBurst=20
User=web001
Group=webusers
SyslogIdentifier=aspnet-6

[Install]
WantedBy=multi-user.target
```

There is no `[Unit]` in there. This file generates no error/warning but I haven't verified its functionality yet. Replacing `StartLimitInterval` with `StartLimitIntervalSec` in-place generates that warning.

Please advise how to correct or improve this. The documentation doesn't seem to help me.

What's the correct usage of `StartLimitIntervalSec` anyway? Does the name stand for "seconds" and I should provide an integer number? Or can I use other formats like "1min", then what does "Sec" mean?

**Comment by zdzichu** [comment]
If you want to use `StartLimitIntervalSec`, you need to add `[Unit]` section to your file and put `StartLimitIntervalSec=` there.
As with other time fields, plain numbers are treated as seconds (thus "Sec"), but you can put stuff like "1min" there, too. The renaming is explained in commit ID I've linked.

**Comment by poettering** [comment]
Please follow the documentation matching your systemd version.

There used to be StartLimitInterval= in [Service]. We generalized that and made it StartLimitIntervalSec= in [Unit]. The old name in the old section is still accepted though for compat.

The old name in the new group is not accepted because that never worked.

the sample file you supplied should work with both current versions and really old ones. You can verify that things are properly parsed by using:

```
systemctl show -p StartLimitIntervalUSec foo.service
```

Your unit file should be updated though, as the setting has moved, i.e. to something like this:

```
[Unit]
StartLimitIntervalSec=400
StartLimitBurst=20

[Service]
Type=exec
ExecStart=/var/www/aspnet/6
Restart=always
RestartSec=15
User=web001
Group=webusers
SyslogIdentifier=aspnet-6

[Install]
WantedBy=multi-user.target
```

This then only works with current systemd versions.

**Comment by poettering** [comment]
> Does the name stand for "seconds" and I should provide an integer number? Or can I use other formats like "1min", then what does "Sec" mean?

The "Sec" just indicates the default unit if you don#t specify a unit yourself. But you can specify units to override this default. i.e. the following three lines are equivalent:

```
StartLimitIntervalSec=400
StartLimitIntervalSec=400s
StartLimitIntervalSec=6min 40s
```

We probably should document this better here though. Will hence turn this into a documentation bug.
