### ISSUE TITLE
RFE: Option to use UUID instead of machine-id in bootctl, kernel-install

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#16658]
The machine-id isn't always guaranteed to be available when creating images in mkosi. Does anything prevent us from using the partition UUID instead? If not, maybe I can make a PR to add this. I'm not sure if this is public API which would influence whether we'd put this behind an option or not.

**Comment by poettering** [comment]
use it for what precisely? the top-level dir in ESP/XBOOTLDR? It can actually be any string, just machine-id is convenient. How would you make this configurable?

I have the suspicion though that for cases where one doesn't want to use the machine ID for that one probably also wants to use unified kernels (i.e. kernel + initrd in one)

**Comment by DaanDeMeyer** [comment]
I actually didn't know it could be anything. Currently, bootctl install and kernel-install fail if there's no machine-id available. (kernel-install doesn't crash but it becomes a noop). I'm fine if we can modify those tools to work without having a machine-id in the image. My idea was to replace the machine-id required for those two tools by the partition UUID but it can't be whatever, I don't particularly mind as long as its not the machine-id.

**Comment by poettering** [comment]
what about this: if we can't find the machine ID, use a fixed string `default` or `linux` or so, and log about it (at LOG_INFO/LOG_NOTICE level, i.e. it's neither error nor warning, just relevant info). Also, introduce an env var that can be used to override it.

i.e. let's not add a config file or so, since there's little reason to change the default string, except in exotic cases where an env var should be enough.

**Comment by DaanDeMeyer** [comment]
SGTM, I'll submit a PR.
