### ISSUE TITLE
crash_kexec_post_notifiers should not be always enabled

### ISSUE THREAD

**Issue by ryncsn** [systemd/systemd#16661]
**systemd version the issue has been seen with**
> v246

**Used distribution**
 > Fedora

**Expected behaviour you didn't see**
 > crash_kexec_post_notifiers should not be always enabled.

**Unexpected behaviour you saw**
 > crash_kexec_post_notifiers is always enabled

Always reproducible. On latest v246, commit f00c36641a253f4ea659ec3def5d87ba1336eb3b added a config file:
/usr/lib/tmpfiles.d/systemd-pstore.conf

it enables crash_kexec_post_notifiers for pstore service. In the file description we can see:
```
# To configure the kernel parameters, uncomment the appropriate
# line(s) below. The value written is either 'Y' to enable the
# kernel parameter, or 'N' to disable the kernel parameter.
```

However this line is not commented
```
w- /sys/module/kernel/parameters/crash_kexec_post_notifiers - - - - Y
```

So crash_kexec_post_notifiers is enabled even if pstore is not enabled. It's a known issue that crash_kexec_post_notifiers may lead to potential kdump failure, as the post notifier could make the panicked kernel more unstable. See below part from kernel doc:
```
	crash_kexec_post_notifiers
			Run kdump after running panic-notifiers and dumping
			kmsg. This only for the users who doubt kdump always
			succeeds in any situation.
			Note that this also increases risks of kdump failure,
			because some panic notifiers can make the crashed
			kernel more unstable.
```

It's better to leave it to user to enable it, and doc the issue to only enabled this when pstore is needed.

**Comment by poettering** [comment]
the tmpfiles.d snippet is installed when systemd-pstore is enabled at compile time. Fedora enables this.

Either pstore is something that is supposed to work or it's something that's is really broken. Normally, if something isn't entirely stable yet Fedora is the right place to enable it first, to see how things work out. So we enable it.

I am not sure why a failing crash_kexec_post_notifiers would make anything worse though: if the kernel is fucked it is fucked after all, and if the crash collection then works, that's just makes a fucked condition a bit better and that's all. But I don#t think many people would expect it to work in all cases, given that it runs in a situation where the system otherwise doesn't work either. i.e. if the kernel just showed that it isn't as robust as we wished it was, then who#s to expect that the crash collection it does would be guaranteed to work otherwise?

or to say this differently: without this enabled then a crash means besides rebooting there's nothing we can do. But with this enabled then this means some data is if all goes well collected, but if not, then the same outcome as before is seen: besides rebooting there's nothing we can do. Hence afaics nothing gets worse here, it only gets better, but not in really all cases...

**Comment by ryncsn** [comment]
Hi, maybe there are some misunderstand. I didn't imply that pstore will fail, think it might just works, and I'm not aware of any pstore failure yet.

But the thing is it might break kdump. (pstore runs in the crashed kernel, doing anything extra in the crashed kernel may crash it even more).

Even if pstore service is not enabled/available, the tmpfiles.d file enable crash_kexec_post_notifiers unconditionally, and that param could break kdump on some machines.

So for example, on a system where originally kdump is configured, tested, and works, and user updated to v246, kdump could be suddenly broken even if pstore service is not enabled/available, and now the situation is, both pstore and kdump won't work.

And if kdump is enabled, I think it can replace pstore in many use cases.
One useful case for pstore is the one I found in the following doc (https://www.freedesktop.org/software/systemd/man/systemd-pstore.service.html):
```
The pstore service is independent of the kdump service. In cloud environments specifically, host and guest filesystems are on remote filesystems (eg. iSCSI or NFS), thus kdump relies (implicitly and/or explicitly) upon proper operation of networking software *and* hardware *and* infrastructure. Thus it may not be possible to capture a kernel coredump to a file since writes over the network may not be possible.
```

But for such case, can we let user to enable that crash_kexec_post_notifiers param manually, or only enable it when systemd-pstore the service is enabled?

**Comment by daveyoung** [comment]
The kernel parameter was created only for user to enable manually if they are aware of what they are doing.  But enable it by distribution would mislead and cause breakage.   The reason why it is not recommended for kdump is we expect very minimum things to be done after panic then immediately jump to kernel kernel, the current panicked kernel is not stable, we do not trust any further actions in this context.   We get at least ppc64 and s390x report about kdump kernel hang. According to Philipp, the s390 maintainer, the s390 pstore is never expected to work.   Even for x86 I do not think pstore is a reliable and widely used.

**Comment by poettering** [comment]
If pstore doesn't work reliably, not even on x86 I am reconsidering why we should support it at all in systemd actually.

**Comment by daveyoung** [comment]
Let me summary about my points here,  I'd suggest to ask user to enable it if they want and also make them aware about the limitations:
- pstore panic kmsg saving could cause kdump failure, so somehow they are conflicted with each other, but people can use it if they are really sure about it (I means coexist with kdump setup, or just disable kdump and use pstore if they want). 
- pstore depends on special hardware, it is not common for most people.

**Comment by edevolder** [comment]
Fwiw, when I integrated this change to our internal systemd, I did not enable this option by default, for the reasons I cited in the discussion around that option.eric

    On Thursday, August 6, 2020, 10:57:17 AM CDT, Lennart Poettering <notifications@github.com> wrote:  
 
 


/cc @edevolder

**Comment by daveyoung** [comment]
ping :)

**Comment by edevolder** [comment]
>     * pstore panic kmsg saving could cause kdump failure, so somehow they are conflicted with each other, but people can use it if they are really sure about it (I means coexist with kdump setup, or just disable kdump and use pstore if they want).

yes, this is possible as I have witnessed certain BIOS related issues with the pstore backend writes to flash.
 
>     * pstore depends on special hardware, it is not common for most people.

The two most common pstore backends are ACPI ERST and EFI. There is not necessarily any special hardware, just support via ACPI (EFI uses variables, so nothing special). If ACPI doesn't support ERST, then pstore will not use it as a backend and it is effectively disabled.

The problems I've witnessed have been with BIOS writes/updates to flash (since both ERST and EFI eventually persistent the data in flash).

**Comment by daveyoung** [comment]
> > ```
> > * pstore depends on special hardware, it is not common for most people.
> > ```
> 
> The two most common pstore backends are ACPI ERST and EFI. There is not necessarily any special hardware, just support via ACPI (EFI uses variables, so nothing special). If ACPI doesn't support ERST, then pstore will not use it as a backend and it is effectively disabled.

EFI is popular nowadays,  but I still doubt it is good enough to use EFI formally as a pstore backend,  I personally still worries running out of space or some other weird bugs firmware related,  it sounds still risky.  But maybe I should not bring up this point at all,  if it is useful for some people then they can enable it if they want :)  Just we'd better not to enable the crash_kexec_post_notifiers by default.

> 
> The problems I've witnessed have been with BIOS writes/updates to flash (since both ERST and EFI eventually persistent the data in flash).

Thanks for that info!

**Comment by daveyoung** [comment]
@edevolder @poettering ,  do you agree to remove the default =y setting?

**Comment by edevolder** [comment]
I'm indifferent as to the default setting. I've outlined my concerns previously (https://github.com/systemd/systemd/pull/15272#issuecomment-614715006).
Internally I have set the default to disabled in our systemd rpm as we have machines with ERST BIOS bug, which is now nearly extinguished. Until then it was prudent to set default to off.
Also note that the "running out of space" is actually the exact purpose/mission in life of the pstore service, to keep space in the pstore available for future events.

**Comment by ryncsn** [comment]
> I'm indifferent as to the default setting. I've outlined my concerns previously ([#15272 (comment)](https://github.com/systemd/systemd/pull/15272#issuecomment-614715006)).
> Internally I have set the default to disabled in our systemd rpm as we have machines with ERST BIOS bug, which is now nearly extinguished. Until then it was prudent to set default to off.
> Also note that the "running out of space" is actually the exact purpose/mission in life of the pstore service, to keep space in the pstore available for future events.

I just read through the discussion in #15272, so I think the idea of setting it to on by default is that after kernel panic things can't get worse by enabling it, even if it didn't work.

But if user have enabled kdump, which usually captures more useful info than pstore, then enabling crash_kexec_post_notifiers could break kdump, and it will actually got worse.
And there are also few old cases that with pstore enabled, kernel panic could brick the EFI firmware.

Can we comment out that crash_kexec_post_notifiers by default?

**Comment by guilhermepiccoli** [comment]
> If pstore doesn't work reliably, not even on x86 I am reconsidering why we should support it at all in systemd actually.

Who told you that pstore is broken? Pstore seems OK for me, and this is not what is being discussed here.
The problem here is very simple: systemd is enabling, by default (at least in Fedora, it seems) an option ("crash_kexec_post_notifiers") that *breaks kdump* and that should be reverted. Such an option is available for fine-tuning purposes, for advanced user that *know* what they are doing; the init system shouldn't enable that by default.

**Comment by daveyoung** [comment]
Thanks for merging the commit!
