### ISSUE TITLE
beef up systemd-networkd-wait-online to wait for ipv4 or ipv6 or both addresses

### ISSUE THREAD

**Issue by LetzteInstanz** [systemd/systemd#16700]
Hello. The version 246 of systemd-networkd doesn't wait the routable IPv4 and IPv6 addresses assignment together to the network interface at startup on my VirtualBox machine with Arch Linux:
```
авг 09 17:03:12 arch systemd-networkd[386]: enp0s17: State changed: configuring -> configured
авг 09 17:03:12 arch systemd-networkd[386]: enp0s17: Discovering IPv6 routers
авг 09 17:03:12 arch systemd-networkd[386]: NDISC: Started IPv6 Router Solicitation client
авг 09 17:03:12 arch systemd-networkd[386]: enp0s17: Remembering route: dst: fe80::a00:27ff:fe7e:a5fc/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
авг 09 17:03:12 arch systemd[1]: Finished Wait for Network to be Configured.
авг 09 17:03:12 arch systemd[1]: Started OpenSSH Daemon.
авг 09 17:03:12 arch sshd[430]: error: Bind to port 22 on 2dc0:a17b:7415:0:a00:27ff:fe7e:a5fc failed: Cannot assign requested address.
```
`uname -a`:
`Linux arch 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux`

`cat /etc/systemd/network/10-enp0s17.network`:
```
[Match]
Name=enp0s17

[Network]
DHCP=ipv4
IPv6AcceptRA=true
```

`cat /etc/systemd/system/sshd.service.d/dependencies.conf`:
```
[Unit]
Wants=network-online.target
After=network-online.target
```

`systemctl is-enabled systemd-networkd-wait-online`:
`enabled`

Full debug log with `journalctl -b -u systemd-networkd -u sshd -u systemd-networkd-wait-online`:
[debug_output.txt](https://github.com/systemd/systemd/files/5048117/debug_output.txt)

This config worked for the version 245.

How can I set up it now?

**Comment by yuwata** [comment]
Hmm, `systemd-networkd` considered an interface 'configured' when at least one dynamic IP assigning protocol (like DHCP) finishes. So, it is not guaranteed that both IPv4 and IPv6 addresses are set when it is in configured state.

Maybe, we should add `--ipv4` and `--ipv6` options to `systemd-networkd-wait-online`, and if they are set, `s-n-wait-online` waits for the interface is in configured state _and_ at least one corresponding IP address is set.

Note that, your issue is caused by 3cd5924c850929b03bc8d4ba5db614d662edb49a.

**Comment by LetzteInstanz** [comment]
Can I implement this feature?

**Comment by ssahani** [comment]
Yes please thanks !
