### ISSUE TITLE
RFE: make hibernation more robust, and on-demand

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#16708]
I think we should give the hibernation logic a bit more love:

1. Support a mode where we activate swap files/partitions only immediately before hibernating, so that they are not used for swap, only for hibernation. For swap files even: create them on-demand.
2. Get rid of need to configure hibernation offsets in the boot loader config if swap files are used. instead mount file system at boot, and find the hibernation image directly by going via file system and using FIEMAP during boot. make this safe, by using BLKROSET before mounting the file system so that xfs and friends don't replay journals and fuck things up.

With this in place we should be able to be as robust as we can be while being a lot more dynamic: stuff gets created only when needed, and discovered automatically at boot.

**Comment by sftim** [comment]
> I think we should give the hibernation logic a bit more love:
> 
>     1. Support a mode where we activate swap files/partitions only immediately before hibernating, so that they are not used for swap, only for hibernation. For swap files even: create them on-demand.

On this: I'd expect to find hooks so that I can do things like first set up an encrypted volume for swap - used just for hibernation - and then have userland do things with the encryption key (asymmetric encryption? use the TPM? other ideas?)

Does that sound like a systemd generator, perhaps?

I can see how this also relates to initializing and using swap space for its usual purpose, paging. The same mechanism could work for that case too, and then let distributions or end users teach systemd about different dependencies to decide when to start the procedure.
A while back I used a daemon that added swap on-demand, by creating _n_ MiB swap files. Today, that could look like multiple instances of a systemd unit, and a service that autoscales the number of instances.

Some other examples for the swap-as-paging case:
- early boot, maybe even before the initrd hands over to boot from the final root filesystem
- multiuser
- after the first user logs in (pretty sure this is possible)
- at the moment hibernate is requested
- ten minutes after the system has finished booting
- when the userland memory monitor identifies that memory demand is high enough
- after the hardware security module is online
- after the hardware security module is unlocked

**Comment by pgoodall** [comment]
I love the idea, as I've been battling with hibernation myself on several different distros. Any chance this will go forward?

**Comment by sftim** [comment]
This issue is really several parts. AIUI the first part of a contribution here would be to split those out into their own issues and have each of those get triaged. We'd like them back to this issue, of course.

**Comment by YHNdnzj** [comment]
> Support a mode where we activate swap files/partitions only immediately before hibernating, so that they are not used for swap, only for hibernation. For swap files even: create them on-demand.

Is this still relevant after https://github.com/systemd/systemd/commit/6f1fe575f0d293fa801e8f02374988f7bbf69dca?

**Comment by poettering** [comment]
> 1. Support a mode where we activate swap files/partitions only immediately before hibernating, so that they are not used for swap, only for hibernation. For swap files even: create them on-demand.

frankly, I think this is a bad idea. swap is inherently a good thing, see oomd and stuff, hence using swap only around hibernation if it exists anyway is just a stupid idea.

So let's not to that.

**Comment by poettering** [comment]
> 2\. Get rid of need to configure hibernation offsets in the boot loader config if swap files are used. instead mount file system at boot, and find the hibernation image directly by going via file system and using FIEMAP during boot. make this safe, by using BLKROSET before mounting the file system so that xfs and friends don't replay journals and fuck things up.

And in light of #27330 this one is unnecessary too. storing the offset at the moment of hibernation in an EFI var removes any need to search for it at boot. Given the resume from the hibernation image is not going to work if the fs changed during the offline time it's entirely sufficient to determine the offset before hibernating and storing it in an EFI var.

Hence, with that in mind I think we can just close this issue.

**Comment by Nehctarg** [comment]
>  frankly, I nowadays think this is a bad idea. swap is inherently a good thing, see oomd and stuff, hence using swap only around hibernation if it exists anyway is just a stupid idea.
> So let's not to that.

How about hardware swap in combination with zram swap? If I want to hibernate I'd have to deactivate the zram swap and activate the hardware swapfile before the actually hibernation begins. The same process obviously needs to be reversed for resuming. Implementing this whole process though systemd services seems unnecessarily hard to me right now.

**Comment by polarathene** [comment]
> If I want to hibernate I'd have to deactivate the zram swap and activate the hardware swapfile before the actually hibernation begins.

Do you need to deactivate zram? Wouldn't the memory used for zram swap just be part of the hibernation image?

I haven't tried, but might be easy enough to check with a VM guest to see what happens. Otherwise if it is an issue, changing the swap device priority at this time for the on-demand hibernation swap should work?

---

> hence using swap only around hibernation if it exists anyway is just a stupid idea.

On-demand swap for hibernation specifically still seems worthwhile.

I can quite easily load up to 32GB RAM for the work I do, and if I have a swap device in memory or disk, that can sometimes get a fair amount allocated as well. I've had 8GB zram swap used with a 4x compression ratio or higher, but doesn't hibernation require enough swap space to support active memory allocated in RAM?

If that current swap is too small or already using a fair amount of the capacity and hibernation cannot reserve it, how much larger does the swap need to be made?

Whereas with a swap partition or file that's activated for hibernation I don't have to account for that concern. I know hibernation image can be compressed but I am not sure that'd always be reliably successful vs a larger swap only used for hibernation. With a 2TB NVMe SSD, 32GB or so for this is a small cost vs "I can't rely on hibernation working if my memory / swap usage is too high".

I'm not sure how reserving that space for hibernation translates to _"just makes the system worse overall."_?

**Comment by poettering** [comment]
> How about hardware swap in combination with zram swap? If I want to hibernate I'd have to deactivate the zram swap and activate the hardware swapfile before the actually hibernation begins. The same process obviously needs to be reversed for resuming. Implementing this whole process though systemd services seems unnecessarily hard to me right now.

You do not need to deactivate zram, since the hibernation logic in systemd ignores zram devices anyway when looking for a swap device to hibernate into.

if you have a swap file anyway, then just activate it always, but make sure to give it a lower priority than your zram device, so that zram is always preferred, and the swap file is only used if the system is under pressure enough that zram didn#t work. That will give you overall better behaviour.

Hence, no need deactivate zram, and no need to activate the swap files. just use swap priorities, which exist since forever.

**Comment by SkyREgit** [comment]
> > How about hardware swap in combination with zram swap? If I want to hibernate I'd have to deactivate the zram swap and activate the hardware swapfile before the actually hibernation begins. The same process obviously needs to be reversed for resuming. Implementing this whole process though systemd services seems unnecessarily hard to me right now.
> 
> You do not need to deactivate zram, since the hibernation logic in systemd ignores zram devices anyway when looking for a swap device to hibernate into.
> 
> if you have a swap file anyway, then just activate it always, but make sure to give it a lower priority than your zram device, so that zram is always preferred, and the swap file is only used if the system is under pressure enough that zram didn#t work. That will give you overall better behaviour.
> 
> Hence, no need deactivate zram, and no need to activate the swap files. just use swap priorities, which exist since forever.

Is this logic implemented already?

Ubuntu 24.04.1 LTS, systemd 255.4, zram has 100 priority vs swapfile -2 => "Cannot allocate memory" during hibernation.
With swapoff for /dev/zram0 (instruction from [here](https://gist.github.com/eloylp/b0d64d3c947dbfb23d13864e0c051c67)) - hibernates successfully.
[Here](https://ubuntuhandbook.org/index.php/2021/08/enable-hibernate-ubuntu-21-10/) (Note in Step 1) also confirmed that logic above not in place.

**Comment by ISSOtm** [comment]
I have a system with 8 GiB RAM and a swap partition of 8 GiB also, and I routinely get failures to hibernate due to inability to allocate enough memory. (E.g. `PM: hibernation: Normal pages needed: 1070440 + 1024, available pages: 844930`) This has gotten me to start looking into ways to get hibernation-specific swap (a `.swap` unit that gets pulled in by `hibernate.target`), but this has proven flaky so I eventually found this thread. Note that I have zswap on, and thus am not using zram, since AFAICT that would be counter-productive.

If dedicated swap for hibernation isn't a good solution, are there better recommendations?

I know I *could* make this extra swap constantly available, but I've previously run (gaming) workloads that saturated even that, and thus I would like to have a hibernation setup that remains robust even in such cases, without having to set aside even more of my disk space Just In Case. (I only have 67 GiB remaining on this drive, and it keeps shrinking.) I would rather applications get OOM-killed (I have successfully set up `systemd-oomd`) while I work, and have a reasonably-sized space for hibernation to be reliable.
