### ISSUE TITLE
How to mount cgruopfs rw into container?

### ISSUE THREAD

**Issue by HuJK** [systemd/systemd#16722]
**Is your feature request related to a problem? Please describe.**
I just want to run docker in systemd-nspawn.

**Describe the solution you'd like**
A flag that can mount cgroups rw instead ro in container

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
