### ISSUE TITLE
Growing solutions. 

### ISSUE THREAD

**Issue by rewolff** [systemd/systemd#16723]
**systemd version the issue has been seen with**

Whatever  Ubuntu 18.04 comes with. 

**Used distribution**
 
Ubuntu 18.04

**Expected behaviour you didn't see**

A booting system. 

**Unexpected behaviour you saw**
Systemd encounters a failing startup script and retries. 

**Steps to reproduce the problem**
I'n guessing adding "exit `1" to the start of the mdadm startup scritp should do the trick. 

Situation: 
I just upgaded from Ubuntu 16.04 intending to go to 20.04 in one go. 
I have installed mdadm because I want the manpage on this system. 

The boot process normally shows a purple screen and then the system boots and shows me my login. But when errors occus, no indication is given except that the screen remains purple. Not good. You might say that this is an ubuntu boot scripts issue, but systemd boot system should make it easy to do things right and allow showing of error messages once things start failing once or twice. 

So after five minutes of purple screen I rebooted into recovery mode. Then I was able to see "mdadm: No automatic arrays found and nothing in the config file". This is correct and intentional. I just want the manpage and the binary maybe to check syntax. I also get a message about fd0 error. Same rhythm as the mdadm error message so I'm guessing that mdadm is probing on the floppy. I don't have a floppy anymore. 

So you might say it's mdadm startup scritpt that is returning error. Right. But systemd infrastructure should give up trying after two or three attempts. I gave up waiting for the system to boot after ten minutes. I'll report back if there was a timeout or not tomorrow when I get back. In any case, my system won't grow a floppy disk in 16 hours when I get back. It won't grow in 10 minutes either. 

These "there is an error, lets retry" have already repeatedly cost me lots of useless time. Systemd should make it easy for distributions to confgiure a timeout and/or simply ask what to do. 

Linux is a multitasking OS. You can start a "ask the user what to do in case of a failure" process even before starting the first script. Then trigger: something like "mdadm startup is failing what should we do?" from that process. My suggestion to do it this way is because this allows the "retry" to continue, allowing unattended reboots to recover in the case the "wait and retry" DOES work eventually.

**Comment by TriMoon** [comment]
Systemd already has timeout settings for unit files, if some package does not make use of it the default timeout for units should have been used.
But if a package overrides it to be infinitely there is not much todo from systemd side...
Systemd even has watchdog functionality to monitor running processes....

You should check the unit files used for that package...

**Comment by poettering** [comment]
@TriMoon is right: we timeout everything by default, but my educated guess is that mdadm turns the time-out explicitly off.

What's "systemctl cat mdadm" output on your system?

Note that if you use a graphical bootsplash such as plymouth all our boot-time output is eaten up by plymouth. If you turn off plymouth systemd manages the output on its own, and then exposes two different behaviours: by default it will output full log output including information what it is currently doing. If "quiet" is passed on the kernel cmdline it stay quiet until the first service fails or a long delay is noticed, at which point boot-time console log output is turned on.

Hence, yes, boot time output is taken over by Ubuntu if you so will and there's little we can do to improve it hence.

Automatic restarting of services on failure is problematic, since it cannot be done in a blanket fashion, because you really don#t want that for certain operations that reset stuff and similar. Hence it's opt-in for services. 

Summarizing: I doubt there's little we can do about this, what you are seeing are deliberate choices of mdadm and Ubuntu. 

But anyway, please provide your mdadm service definition.

**Comment by rewolff** [comment]
So after 15 minutes I timed out and whent home. 
After about three hours my colleague was in the office and noticed my system had booted. So indeed it timed out. 

> What's "systemctl cat mdadm" output on your system?
You can tell me to run commands but the issue is that I need access to my system to be able to try and fix it. 

As expected you are blaming something else, while your infrastructure might provide all the bells and whistles, but the combination of people maintaining packages that have worked for decades and systemd is causing these kinds of problems. 

So my sytem booted I tried to configure mdadm to just "not run" I couldn't find how to do that. So I removed the whole package. I need it, for work, but I need my system up and running more. 

So then I told "recovery mode" to continue the boot, it told me things might not work, but it booted fine and gave me a login screen. 

Then I decided: But do I know that I fixed things? So I rebooted. Turns out that something with fd0 (I don't know what) is also running on a 12 second retry loop. So a quarter of an hour later, I now have my system booted again and I have no clue what I need to disable to be able to boot in less than a quarter of an hour. 
I checked in /etc: Mentions of fd happen in fstab: noauto,user In mtools config and in sysstatconfig. I don't think that's the problem. 

I've given up. I'm not fighting this anymore. I'm going to upgrade to 20.04 and hope things get better.

**Comment by poettering** [comment]
> As expected you are blaming something else, while your infrastructure might provide all the bells and whistles, but the combination of people maintaining packages that have worked for decades and systemd is causing these kinds of problems.

Please vent your frustration elsewhere. I understand you want to blame use no matter what, but we are not accepting that, sorry. 

Please work with your distribution to address this. They should help you with integration issues like this. We only provide one building block (a big one admittedly), but we cannot possibly take responsibility with every single breakage that happens on Linux systems. And this one is pretty clearly outside of our direct realm.

If there's indeed an issue in systemd here, then the distro people will escalate this back to us. But please follow the usual way to report integration issues: talk to your distro first, and leave it to them to escalate this to us.

Thank you for understanding.

**Comment by rewolff** [comment]
You provided infrastructure that causes issues.

It is so complex, that people don't know how to use it. 
There is no infrastructure for me to access my system and fix it. 
In the decades before systemd my system would always boot with: "services X Y and Z reported error, you may want to look into it." . 
Now I understand that some services (e.g. ones that might for instance provide the root filesystem) are essential and an attempt to keep going might not work. Still that would normally mean I have access to my system 2 minutes later by booting with init=bin/sh   or working with the bootloader. 

I have removed mdadm. I issued the command you asked: 

```
# /run/systemd/generator.late/mdadm.service
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/mdadm
Description=LSB: MD monitoring daemon
Before=multi-user.target
Before=multi-user.target
Before=multi-user.target
Before=graphical.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
SuccessExitStatus=5 6
ExecStart=/etc/init.d/mdadm start
ExecStop=/etc/init.d/mdadm stop
lines 1-23...skipping...
# /run/systemd/generator.late/mdadm.service
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/mdadm
Description=LSB: MD monitoring daemon
Before=multi-user.target
Before=multi-user.target
Before=multi-user.target
Before=graphical.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
SuccessExitStatus=5 6
ExecStart=/etc/init.d/mdadm start
ExecStop=/etc/init.d/mdadm stop
ExecReload=/etc/init.d/mdadm reload
lines 1-24...skipping...
# /run/systemd/generator.late/mdadm.service
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/mdadm
Description=LSB: MD monitoring daemon
Before=multi-user.target
Before=multi-user.target
Before=multi-user.target
Before=graphical.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
SuccessExitStatus=5 6
ExecStart=/etc/init.d/mdadm start
ExecStop=/etc/init.d/mdadm stop
ExecReload=/etc/init.d/mdadm reload

```

While in "recovery root shell" I tried finding the configuration file for the mdadm service. I found /lib/systemd/<something?>/mdadm.service .  that turned out to be a symlink to /dev/null. That's when I gave up and removed the whole thing. Why the "systemctl cat mdadm" still provides output I don't know.

**Comment by poettering** [comment]
You mdadm service is still a sysv script, the first line explains that. We generate a unit file for it dynamically at boot, to provide compat.

sysv scripts can take any time they want to initialize really and block boot. Please talk to your distro to maybe update that...

> You provided infrastructure that causes issues.

Nah, I don't maintain mdadm, sorry. And I don#t maintain your distro either. I just maintain one component of that distro, and it's the job of the mdadm maintainers to maintain admin, and of your distro maintainers to integrate things into their distro and maintain the result.

BTW, the bug submission form already makes clear that this is an issue tracker for upstream issues only, in the two most recent upstream versions only. You are using a 2 year old verson of this. 

PLEASE: talk to your distro, thank you. And stop the discussion here, it's pointless. You are just stealing our time.

**Comment by rewolff** [comment]
Turns out my old disk failed and I swapped it for an SSD. Now the swap partition was gone. 

I still maintain that systemd is responsible for having made this so difficult to diagnose.

**Comment by poettering** [comment]
Yeah of course, systemd is the cause for your failed disk. True.

**Comment by TriMoon** [comment]
> @rewolff 
> I still maintain that systemd is responsible for having made this so difficult to diagnose.

The first party that is _"responsible for having made this so difficult to diagnose"_ because of your lack of educating yourself with software that you run.
The second party would be the **mdadm** maintainer for not updating his package for use in **current** linux distributions which almost all use systemd nowerdays.
And last but not least your distribution for providing such package without customizing it to their setup...

Yes as you can notice i didn't list systemd in that list for obvious reasons...

We all are humans so we understand your frustration when something unexpected happens, but be human also and address things at the right parties instead of blaming a party that has no fault and infact makes the whole Linux community better...

**Comment by rewolff** [comment]
@poettering : You need to read better. I'm not blaming systemd for failing my disk. The disk failed, it happens. In the ensuing (forced) upgrade, the swap partition got changed/went missing. I'm blaming systemd for making it difficult to access my system when things don't run as planned. 

@TriMoon mdadm had nothing to do with this. Systemd made me thing it had something to do with it. It's all nice when things work, but when things fail, systemd has made it difficult for me to find the real cause and diagnose the problem. systemd is about creating infrastructure for a system to be built upon. The "retry to start mdadm" led me to believe it was related to mdadm , but it wasn't. 

Systemd could for example provide better status-updates: the following startup scripts are still running: ...

**Comment by poettering** [comment]
> @poettering : You need to read better. I'm not blaming systemd for failing my disk. The disk failed, it happens. In the ensuing (forced) upgrade, the swap partition got changed/went missing. I'm blaming systemd for making it difficult to access my system when things don't run as planned.

As mentioned before, your distro decided to put a boot splash up, so that systemds status display is hidden. If you turn off thta boot splash (plymouth) via some kernel cmdline option you should see the status output.

if you don#t like bootsplashes, then please contact your distro, it's a distro thing we cannot do anything about.

**Comment by TriMoon** [comment]
> @rewolff 
> Systemd could for example provide better status-updates: the following startup scripts are still running: ...

And there we go.... systemd **actually does** give you that info, it tells you about "jobs still running" instead of scripts because thats how things are done in systemd... (units, services, etc etc)
If you took **half the time** to educate yourself about how systemd works instead of the time to blame as you insist to do now, you would notice it isn't that hard to configure nor operate nor diagnose etc etc...
But yes true systemd does things **different** as you were used-to using SysV with "init-scripts", but trust me its WAY better...
And that's from me as a **user** of systemd, in that respect im on same side as you, im not involved in development of systemd either...
But i hate if people blame a software unfairly that's actually making the whole Linux community better., and i say that with only 45 years of experience with computers :wink: 
So lets just drop this finally ok?
/signout of discussion...

**Comment by rewolff** [comment]
It is clear you guys are ignoring the facts, maliciously focussing on irrelevant details etc etc in an attempt to be able to maintain your worldview of "there is nothing wrong with systemd, nothing to improve, it is always someone else's fault". 

You are correct that I don't like splash screens. My distribution provides a way to disable it. I used that and.... systemd and the configuration by my distribution conspired to make it difficult for me to diagnose the problem. 

From "floppy error" and "mdadm: no config" scrolling on my screen I'm supposed to deduce that something else is the problem? There is room for improvement IMHO.

**Comment by TriMoon** [comment]
> It is clear you guys are ignoring the facts, maliciously focussing on irrelevant details etc etc in an attempt to be able to maintain your worldview of "there is nothing wrong with systemd, nothing to improve, it is always someone else's fault".

One can only be that ignorant if you take into account that same person is reporting on the same system where issues and PR's are handled in public in real-time...
@rewolff please adjust that remark to read _"there is nothing wrong with me, nothing to improve, it is always someone else's fault"_ and you might be on right track...
/unsubscribed from pointless finger-pointing kid-like-talks...
