### ISSUE TITLE
Why is systemd-fsck referencing /usr/local/bin/fsck.xfs?

### ISSUE THREAD

**Issue by mabod** [systemd/systemd#16729]
**systemd version the issue has been seen with**
> systemd 246 (246.1-1-manjaro)

**Used distribution**
 > Manjaro

My root filesystem is on xfs. And I just realized today that since several weeks at every boot systemd-fsck says:

```
systemd[1]: Starting File System Check on /dev/disk/by-uuid/43f7f2c4-fd86-4693-bb5f-9f2fa4122ec6...
systemd-fsck[326]: /usr/local/bin/fsck.xfs: XFS file system.
systemd[1]: Finished File System Check on /dev/disk/by-uuid/43f7f2c4-fd86-4693-bb5f-9f2fa4122ec6.
```

This is the correct  UUID for my root filesystem. But where is this  `/usr/local/bin/fsck.xfs` coming from? It does not exist. I only have `/usr/bin/fsck.xfs` which is owned by `xfsprogs 5.6.0-2`. And I have exactly this in my initramfs: 
`BINARIES=(/usr/bin/fsck.xfs /usr/bin/fsck /usr/bin/fsck.zfs)`

**Comment by poettering** [comment]
We do not invoke fsck.xfs directly. We just invoke /sbin/fsck which then dispatches this to fsck.xfs. 

The script XFS places as fsck.xfs contains this line:

```
echo "$0: XFS file system."
```

which is what you apparently see. It hence appears /sbin/fsck sets argv[0] to that path you see. If that path doesn't look right, then it's between /sbin/fsck (i.e. util-linux) and your distro/initrd.

Neither of these packages are maintained by us. Hence, please contact your distro for further help.

My educated guess: your distro places a symlink from /usr/local to /usr in the initrd. Since typically /usr/local/bin appears in the search path before /usr/bin any binaries searched for via search path will thus be found in /usr/local.

But again, this appears to be a a distro/initrd integration issue (and maybe util-linux as package that contains the fsck binary). Hence please contact your distro community for help first. 

Thank you for understanding.
