### ISSUE TITLE
[question] is it possible with systemd-journalctl to change the location to save logs in other location?

### ISSUE THREAD

**Issue by ionutnechita** [systemd/systemd#16748]
Hi SystemD Team,

One question.

Is it possible with systemd-journalctl to change the location to save logs in other location?

My system is volatile (tmpfs) and I have another location available to keep certain logs.
1. /dev/root or / is tmpfs
2. /external-persistent0 is ext4 or xfs

I would like to save the logs here:
/external-persistent0/journal

Is it possible to do this?
In the current documentation for journalctl I have not seen anything about this.
Thank you and have a good day to the whole team.

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
