### ISSUE TITLE
Documentation mentions DefaultControllers= for avoiding cpu cgroup RT scheduling interference but that doesn't work

### ISSUE THREAD

**Issue by gleventhal** [systemd/systemd#16751]
**systemd version the issue has been seen with**
> latest

**Used distribution**
 > CentOS 7

**Expected behaviour you didn't see**
 > I'd like to use cgconfig and allow a single cpu cgroup for a specific purpose without breaking all real-time scheduling tasks

**Unexpected behaviour you saw**
 > EPERM on sched_setattr for RT prio
Setting DefaultControllers= in /etc/systemd/system.conf does nothing to help with this it seems.  The behavior is unchanged after setting and rebooting.

**Steps to reproduce the problem**
chrt -r 99 /usr/bin/true

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
