### ISSUE TITLE
MemoryMax of systemd not valid

### ISSUE THREAD

**Issue by DinoStray** [systemd/systemd#16769]
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

My systemd unit file:
```
[Unit]
Description = Increase Mem Service
After=network-online.target
Wants=network-online.target

[Service]
CPUQuota=90%
MemoryMax=20M
Type = simple
Restart = on-failure
RestartSec = 10s
User = root
Environment="TZ=UTC"
ExecStart = /work/increase_mem

[Install]
WantedBy = multi-user.target
```

The MemoryMax not valid.

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
