### ISSUE TITLE
Talos Security Advisory for Systemd DHCP (TALOS-2020-1142/CVE-2020-13529)

### ISSUE THREAD

**Issue by CiscoTalos** [systemd/systemd#16774]
Please review email issued to  systemd-security at redhat dot com regarding this issue

**Comment by klnSVM** [comment]
@yuwata are there any news regarding this vulnerability?
According to the Talos Advisory systemd maintainers told talos at the 4th of Dez 2020, that fixing the Issue is planned for the next release. Assuming form this point, it would have been v248.
Unfortunately I couldn't find any further information, if v248 fixed CVE-2020-13529 or not.
Could you please help me along?
Thanks!

**Comment by yuwata** [comment]
@klnSVM The issue is not fixed yet. If I remember correctly, we discussed and concluded that if we use DHCP protocol then such the vulnerability always exists. Also, we could not find any RFC to avoid or mitigate the issue... So, I think it is hard to fix the issue soon on systemd-networkd side. Please let me know if you know relevant RFCs.

In short, we concluded that the vulnerability is not a issue of systemd-networkd but of DHCP protocol.

@keszybz Do you have any follow-ups?

**Comment by yuwata** [comment]
Oh, I tried to find relevant RFCs, maybe https://tools.ietf.org/html/rfc6704 is related.

**Comment by yuwata** [comment]
I've not read RFC6704 in detail, but it should mitigate the issue. I will try to implement that.

**Comment by ret2libc** [comment]
@CiscoTalos Hi, it would be great if your report at https://talosintelligence.com/vulnerability_reports/TALOS-2020-1142 could reference a specific commit instead of just "master", otherwise it is hard to follow the code references because code changes quickly. Thanks!

**Comment by thom311** [comment]
Since the DHCP client doesn't implement rfc3118 (Authentication for DHCP Messages) nor rfc6704 (Forcerenew Nonce Authentication), wouldn't a simple fix be to ignore any FORCERENEW messages?

If I am not wrong, then ISC's dhclient also does not support rfc3203/FORCERENEW, so this seems an acceptable thing not to support. And neither does nettools' [n-dhcp4](https://github.com/nettools/n-dhcp4).

**Comment by StayPirate** [comment]
is there any update on that?

**Comment by yuwata** [comment]
@StayPirate Unfortunately, not yet.

**Comment by yuwata** [comment]
Fix is waiting in #20002.
