### ISSUE TITLE
Can't run systemd-tmpfiles on an overlayfs mounted root directory

### ISSUE THREAD

**Issue by olivier-singla** [systemd/systemd#16848]
On a Debian system where the root filesystem is an overlay filesystem, it is not possible to run systemd-tmpfiles:
SYSTEMD_LOG_TARGET=console SYSTEMD_LOG_LEVEL=debug systemd-tmpfiles --clean
will give:
Cleanup threshold for directory "/var/tmp" is Mon 2020-07-27 14:41:35.470310 UTC
Ignoring "/var/tmp/hello.txt": different filesystem.

**Comment by poettering** [comment]
So, overlayfs is a weird file system, it reports a different `.st_dev` field for each file. This is really somehing they overlayfs people have to fix.

That said, on kernel 5.8 we have a better way to detect mount points, via the new statx() STATX_ATTR_MOUNT_ROOT flag. If we use that, then we don't have to rely on `.st_dev` making any sense. I have prepped a patch I'll post shortly for now.

Either way, please complain to the overlayfs maintainers so that they export sensible `.st_dev` data in `stat()`. A multitude of tools rely on it to detect fs boundaries, including `find` and such, and not just tmpfiles and they really should fix that hence.

**Comment by olivier-singla** [comment]
Thanks Lennart for the patch and looking into this.

May I ask what is the rational of skipping purging temp files which are not the some mounted root fileystem?
Could we have a configuration option to not perform this test and just proceed?

Otherwise, is there a way to figure out if the file belongs to an overlay filesystem?
I noticed that the major/minor reported is a loop device (/ being mounted using overlayfs):
root@sonic:/home/admin# stat /vmlinuz
  File: /vmlinuz -> boot/vmlinuz-4.9.0-11-2-amd64
  Size: 29        	Blocks: 0          IO Block: 1024   symbolic link
Device: 700h/1792d	Inode: 43670       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-08-25 22:10:41.000000000 +0000
Modify: 2020-08-25 22:10:41.000000000 +0000
Change: 2020-08-25 22:10:41.000000000 +0000
 Birth: -
root@sonic:/home/admin# cat /sys/dev/block/7\:0/loop/backing_file 
/root/host/image-broadcom_sonic_3.x.0-091ee9b1f/fs.squashfs

**Comment by poettering** [comment]
We do not cross fs boundaries for safety reasons. People regularly use it to create a temporary directory they then mount something into. We should clean up the temp dir they overmounted eventually but certainly not the mount itself. People rely on this behaviour.

**Comment by poettering** [comment]
And instead of working around overlayfs' semantical probs in tmpfiles maybe just fix overlayfs to expose standard semantics.

**Comment by olivier-singla** [comment]
> We do not cross fs boundaries for safety reasons. People regularly use it to create a temporary directory they then mount something into. We should clean up the temp dir they overmounted eventually but certainly not the mount itself. People rely on this behaviour.

Does that mean that if we let systemd-tmpfiles creating the directory if it does not exist, it will still not able to clean-up this directory later?

If systemd-tmpfiles creates /var/tmp, /var being mounted over an overlayfs directory, the assumption is that it should later be able to perform a cleanup on it.

I understand overlayfs can present confusing information, but I really wish there would be a way for systemd-tmpfiles to still clean-up a directory mounted over overlayfs, using either a configuration option or some other method. If there is no such way, people will start using alternate method to clean-up temp directories (cron job or whatever).

**Comment by poettering** [comment]
> Does that mean that if we let systemd-tmpfiles creating the directory if it does not exist, it will still not able to clean-up this directory later?

iiuc overlayfs actually sets sensible dev_t data for all dirs, just not for the regular file nodes. This means that aging works for dirs, but not for the files instead.

#16877 will use better method for detecting mounts on kernels >= 5.8. I still think overlayfs should be fixed to return more sensible dev_t/ino_t info, but on 5.8 and newer this wouldn't matter for tmpfiles at least anymore.

Hence, please work with the overlayfs people so that they fix their logic. And/or upgrade to kernel 5.8, since we'll now switch to a better API for detecting mount boundaries there.
