### ISSUE TITLE
nss-resolve should fallback to nss-dns also if D-Bus cannot be connected to

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#1692]
Typical case, running just a shell with nspawn as a better chroot (`systemd-nspawn -D /home/containers/arch/`) with just `hosts: files resolve myhostname` in nsswitch.conf

**Comment by johannbg** [comment]
Hmm nss-resolve should already chain-load nss-dns if systemd-resolved.service is not running so former should already be working for you and you need to be a bit more clearer about what you mean by if "resolved doesn't answer" since there are legit user cases for the resolver not to answer. 

For example if there is no network connection or if it finds no nameservers resolv.conf should just be empty and the answer is legit right?

**Comment by gdamjan** [comment]
https://github.com/systemd/systemd/blob/master/src/nss-resolve/nss-resolve.c#L137-L157

there are several cases here when it doesn't fallback, the first one is would happen when the bus socket is not available for ex.

**Comment by poettering** [comment]
Yes, we already fall back and chainload nss-dns. Are you saying that you ran into a case where we don't chainload where we should better have?

**Comment by gdamjan** [comment]
if sd_bus_open_system fails

**Comment by poettering** [comment]
OK, i see.

**Comment by poettering** [comment]
Fix waiting in #2445

**Comment by gdamjan** [comment]
I confirm that it works now (as of b3042837397380b9a4d0900f5e00452f0f87a808)
