### ISSUE TITLE
resolved does not use search domains

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1697]
Looking for an unqualified name (e.g. `foobar`) immediately sends out LLMNR queries, and does not attempt DNS lookups within search domains found in `resolv.conf`.

**Comment by poettering** [comment]
Yeah, we currently don't do search domains in resolved, not sure we should...

**Comment by heftig** [comment]
IMO this is critical to have if you expect `nss-resolve` to be a drop-in replacement for `nss-dns`.

That is, I believe the behavior concerning DNS if `resolved` is running shouldn't be noticeably different from when it's not (and `nss-resolve` falls back to `nss-dns`). Right now, stopping `resolved` makes unqualified lookups work. Having `resolved` should affect performance and use additional lookup methods, of course.

(On another note, I think `resolved` is caching negatives a bit too aggressively and doesn't flush its cache when the network config changes, but that's different problem.)

**Comment by teg** [comment]
@heftig care to file a separate bug report about the too aggressive negative caching?

**Comment by poettering** [comment]
@heftig note that we maintain caches per network interface and protocol. Hence, there's no reason to explicitly flush caches when network configuration changes, because the whole cache for that specific interface goes away or is newly created. Or what do you mean by "network config changes"?

Anyway, please file a separate bug about that issue, and some hints how to reproduce it, if the issue still exists.
