### ISSUE TITLE
Possible support for child logind sessions running under a display server?

### ISSUE THREAD

**Issue by n3rdopolis** [systemd/systemd#17015]
Hi

I have been experimenting with making some sort of non-root kmscon alternate by combining wlroots based `cage` and `vte`
Two problems force me to run it as root.

(The first being the obvious escalation of `/bin/login` which might be possible to do with `systemd-run` and `pkexec` and a custom policy)

The second being that for polkit to work in the session XDG_SEAT and XDG_VTNR both need to be set. However if an existing session is using that XDG_VTNR the polkit session fails to start

For example, under a terminal running under a graphical session
```
system-run --setenv=XDG_SEAT=$XDG_SEAT --setenv=XDG_VTNR=$XDG_VTNR -t -- login -p
```
logging in, and then trying `pkexec ls` access is denied, because I guess that XDG_VTNR is already used, whereas `--setenv=XDG_VTNR=63` ,  but not feasible as it doesn't work quite right

So could something like where if XDG_SESSION_CLASS="guest" the session won't need a VTNr on `seat0` be acceptable? 
Or will there be problems with the fact that the session that the host display server is running will have to be the active one for the seat?

Thanks

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by n3rdopolis** [comment]
This _was_ intended as a feature request
