### ISSUE TITLE
Is it possible to change udev rules programmatically without modifying files on disk?

### ISSUE THREAD

**Issue by deliciouslytyped** [systemd/systemd#17098]
- or otherwise programmatically talk to udev?

Similar questions have been asked without any real answers:
https://stackoverflow.com/questions/23572467/how-to-make-udev-deamon-think-we-have-added-a-new-rule https://stackoverflow.com/questions/20411624/how-to-set-device-permissions-using-udev-programmatically https://stackoverflow.com/questions/11846594/how-can-i-programmatically-set-permissions-on-my-char-device

Is there some kind of dbus target or something?

I found https://insujang.github.io/2018-11-27/udev-device-manager-for-the-linux-kernel-in-userspace/ , but that seems to only be for receiving notifications.

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by deliciouslytyped** [comment]
FWIW I don't really use mailing lists, so if anyone wants to answer here anyway I'll check.
