### ISSUE TITLE
Timed out waiting for device dev-ttyPS0.device

### ISSUE THREAD

**Issue by zhoupeng** [systemd/systemd#17117]
**systemd version the issue has been seen with**
>udevadm --version
>237
>systemd-udev.riscv64                     237-1.0.riscv64.fc28

**Unexpected behaviour you saw**
We can see ttyPS0 boots ok in the kernel boot period:
[    0.180000] console [ttyPS0] enabledat MMIO 0xe0000000 (irq = 2, base_baud = 6250000) is a xuartps
[    0.180000] console [ttyPS0] enabled

But, when boot into systemd, it failed on dev ttyPS0:
[ TIME ] Timed out waiting for device dev-ttyPS0.device. // **here**
[DEPEND] Dependency failed for Serial Getty on ttyPS0. // **here**
[  OK  ] Started Rebuild Hardware Database.
         Starting Update is Completed...
         Starting udev Kernel Device Manager...
[  OK  ] Started Update is Completed.
[  OK  ] Started udev Kernel Device Manager.

I found there was a similar issue  https://github.com/systemd/systemd/issues/3446 which is on Ubuntu,  and @jeras reported it can be fixed by 'apt get install udev' on Ubuntu, But on Fedora 28 (Rawhide), I searched there is no udev package, there is only 
systemd-udev package, and the systemd-udev is installed. So  I didn't find a way to fix this issue.

**Steps to reproduce the problem**
Boot the Fedora 28 (Rawhide) using Linux  kernel version 4.18, with kernel bootargs as below
Kernel command line: console=ttyPS0,115200n8 root=/dev/mmcblk0p2 rootfstype=ext4 rw rootwait earlycon clk_ignore_unused

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

---

[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
