### ISSUE TITLE
systemd silently fails to start auto-generated units

### ISSUE THREAD

**Issue by Binarus** [systemd/systemd#17116]
I noticed the issue when I installed a new debian buster system (systemd-based, with systemd-sysv) where I needed fetchmail. I installed fetchmail, installed an appropriate configuration file, and tried `systemctl start fetchmail`. This returned immediately without any output and did not do anything; notably, it did not start `fetchmail`. Likewise, after having rebooted the system, fetchmail was not running.

Then I tried `/etc/init.d/fetchmail start`. This time, I got an output saying it started via systemd, but actually `fetchmail` still was not running. Well, that was expected somehow ...

Next, I copied the init script `/etc/init.d/fetchmail` to my (i.e. root's) home directory and started it directly. This worked - fetchmail was running and doing its thing afterwards.

I tried to analyze why systemd does not start fetchmail. This was somehow difficult because I actually have no clue regarding systemd. However, I have two results (please see attached files):

I ran `systemd-analyze dump` and have copied the relevant portion into the attachment; please let me know if you need the full output.

Plus, I have set the log level to debug and have tried to start fetchmail again via systemctl. This produced a lot of output in the logs; I have copied the relevant portion into the attachment. I believe that the lines

```
Sep 21 19:50:02 debian systemd[1]: fetchmail.service: Failed to send unit change signal for fetchmail.service: Connection reset by peer
Sep 21 20:04:26 debian systemd[1]: fetchmail.service: Changed dead -> exited

```

show the cause of the problem, but I don't have the slightest idea what they mean and what I could do about it.

Googling did not help: When searching for "systemd connection reset by peer" I got myriads of results, all of them referring to problems where systemd's administration utilities didn't work. But in my case, everything works as expected, except that systemd can't start auto-generated units (in the meantime, I have noticed that the same problem appears with saslauthd and all other auto-generated units). There is no problem with normal units.

[dump.txt](https://github.com/systemd/systemd/files/5259352/dump.txt)
[debug.txt](https://github.com/systemd/systemd/files/5259353/debug.txt)

Please let me know what I can do to solve the problem. I'll happily assist in analyzing it, but you would need to give me step-by-step instructions as soon as it comes to strace and friends. I am not experienced in this field.

**Comment by poettering** [comment]
[Canned reply follows] When submitting a GitHub issue, please fill in the submission form you find in the issue creation page, i.e. provide the requested details, such as distribution and systemd versions. We ask you these details to keep frustration at a minimum, both for us, and for you. If you don't provide this information it makes things needlessly difficult to help you.

Also, please keep in mind: this is a bug and feature request tracker only. If you have a support question, i.e. wonder how to use a feature, or can't figure out how to do something best, please use a different forum, such as the systemd mailing list. Also, do not file bug reports unless you can reproduce the issue with one of the two most recently released *upstream* version of systemd. For everything older, please contact your downstream distribution instead.

Thank you for understanding!

--
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

---

[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
