### ISSUE TITLE
logging in generators doesn't work anymore

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#17129]
Generators produce no more log output during boot.

Probably broken by commit bc694c06e60505efeb09e5278a7b22cdfa23975e.

**Comment by DaanDeMeyer** [comment]
No more log output as in no output on the screen or does the output not appear in journald either? I'm not super familiar with generators.

**Comment by fbuihuu** [comment]
It means that the output isn't sent to journald or kmsg, so it's basically lost.

During boot, generators are supposed to send theirs logs to kmsg because journald isn't available. Not sure about their stderr but I would assume they are redirected to /dev/null.

**Comment by boucman** [comment]
ideally I think generators stdout/stderr should be redirected to wherever systemd logs, according to SYSTEMD_LOGLEVEL and SYSTEMD_LOGTARGET

if generators could use the <#> convention for message gravity (like services) that would be awesome.

The current convention (generators write directly to /dev/kmsg) is quite annoying, because it's a rather complex thing to do, especially if you try to write simple generators (shell scripts)

**Comment by poettering** [comment]
> ideally I think generators stdout/stderr should be redirected to wherever systemd logs, according to SYSTEMD_LOGLEVEL and SYSTEMD_LOGTARGET

This has been requested in #15638 already
