### ISSUE TITLE
Expected path encoding and DBus property types

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#17125]
In https://gitlab.gnome.org/GNOME/glib/-/commit/91f43f39a376e0ab353d1bf62b0c9d024dc4c872#note_913832 Christian commented that paths there is a possible discrepancy between the path encoding and the fact that DBus expects UTF-8 for strings.

I am not sure what is expected here or whether this is a bug. If systemd just assumes that all paths on a system are utf-8, then it may be good as is. If that assumption does not hold, then there may be a problem. But a problem that isn't easily fixable (`StartTransientUnit`, etc. could also accept `ay`, but the existing properties can't really be changed from `s` to `ay`).

**Comment by poettering** [comment]
Uh, no. There are certain things we don't want to support: non-utf8 paths. We intend to refuse them wherever we get them. For example if you specify non-utf8 paths in options such as SourcePath= or so we refuse them too. 

Yes, the Linux kernel doesn't mandate any charset for filenames. And it's fine if people insist on using them, but I am pretty sure systemd is doing it right when it refuses such crap. I mean, knock yourself out, use non-utf8 paths as much as you want, but please don't expect systemd would process your stuff then.

Or in other words: this is intentional: we refuse non-UTF8 paths pretty much everywhere (and if we missed some place where we do not validate things correctly that'd be a bug) where we process data files we define, and this by side-effect means we shouldn't have any issue with the D-Bus insistence on UTF-8. In fact I think it's good it insists on that.

So, I think we can close this: if we'd accept non-UTF8 file names for stuff we process we'd consider that a bug, but otherwise we are fine.

Hope that makes sense?

**Comment by benzea** [comment]
Yup, that makes sense.
