### ISSUE TITLE
Delegation of properties controlling  creation of cgroup subhierarchies causing regressions in I/O benchmarks 

### ISSUE THREAD

**Issue by bitstreamout** [systemd/systemd#1715]
as the subject says and seen here:  The switch between two and more blkio controllers (e.g. between journald and dbench started in an other user session with a different blkio cgroup) requires 8ms.

IMHO there is no need to use different blkio cgroups.

Compare with the fixes/commits done for issue 317 ... that is commit a931ad47a8623163a29d898224d8a8c1177ffdaf which introduce the usage of the blkio property

**Comment by poettering** [comment]
I cannot parse this. What is "switch between two and more blkio controllers" supposed to even mean?

"two blkio controllers"? "blkio" is a controller, how can there be two of them? I don't grok a word...

**Comment by fbuihuu** [comment]
@poettering, I _think_ that the issue is the following: using cgroup controllers seems to put some overhead in different part of the kernel even if the default resource constraints are used.

And now with commit a931ad4, system and user proccesses have all controllers systemd manages enabled by default.

This leads to some performance regressions which are described here: https://bugzilla.suse.com/show_bug.cgi?id=953241.

**Comment by arvidjaar** [comment]
You are not authorized to access bug #953241.

**Comment by fbuihuu** [comment]
@arvidjaar: sorry this link is not public. Here is the public one:  http://bugzilla.suse.com/show_bug.cgi?id=954765

**Comment by gormanm** [comment]
I populated the bug with as much information as I had on the behavior of cgroup controller activation. My understanding was that it would only be activated for controllers but it appears to be activated for ssh sessions run by root. It's not clear if that was expected or not but it has a significant impact.

**Comment by gormanm** [comment]
s/activated for controllers/activated for containers/

**Comment by poettering** [comment]
Fix waiting in #7564
