### ISSUE TITLE
udev: document how to tweak udev trigger for specific embedded devices to cover only some subsystems

### ISSUE THREAD

**Issue by franksinankaya** [systemd/systemd#17264]
**Is your feature request related to a problem? Please describe.**
While systemd-tmpfiles-setup-dev.service has the concept of static boot devices with b! or c!, udev is not obeying this semantics and is registering to all subsystems and devices for uevents in systemd-udev-trigger.service.

On the poor little single core armv6 embedded system that I'm using, this operation takes 10 seconds and another 4 seconds to create dev-foo devices.

from systemd-analyze:
systemd-udev-trigger.service (10.346s)
systemd-udevd.service (1.053s)

Startup finished in 19.654s (userspace)

**Describe the solution you'd like**
I'd like to ask either to be able to limit the amount of devices we want to monitor in udev or have some instructions for how to use systemd without udev.

I see instructions here:
https://github.com/profusion/demystifying-systemd-for-embedded-systems/blob/b1c10727729d888c6429b90e181c2f26d55e9354/systemd-minimal-strip.sh#L143

It didn't work for me. For folks with embedded background, I'd like to see an officially supported statement about how to achieve this.

**Describe alternatives you've considered**
I was thinking of redirecting hotplug events to busybox and let systemd handle the rest of the execution as an example. This didn't quite work for me.

I'm very much used to using systemd for other projects. I'd hate to go to another project like busybox/sysvinit due to udev inefficiency.

**Comment by poettering** [comment]
udev doesn't "register" for all subsystems and devices. it subscribes to the netlink uevents multicast group, and there's only one for them, that receives nfo about all devices.

systemd-udev-trigger.service re-triggers all kernel devices during early boot. it will necessarily take some time if you have many devices, but on smaller devices you shouldn't have so many, 10s sounds like an awful lot of time, and this suggests some driver needs more time for triggering than it should.

For special purpose devices it might work not to trigger all subsystems. For that you can alter the trigger service and use "-s" to select specific subsystems to trigger. but you have to fine tune that to your device, what you need there.

using tmpfiles.d/ for creating device node is only useful for device drivers that do not implement the linux device model. For those which do the nodes are created anyway, and udev is not needed to create them (but is to adjust access modes/ownership/ACLs/… of them).

**Comment by franksinankaya** [comment]
How about the second piece?

4 seconds to create dev-foo devices.

![image](https://user-images.githubusercontent.com/41809318/95379409-5e592200-08b3-11eb-8d38-65e0ca904e8a.png)

**Comment by franksinankaya** [comment]
Would udev skip generating these devices if I were to create them at build time?

**Comment by poettering** [comment]
these devices are not "created". they show up then in systemd, that's all. which is without effect if there's nothing to wait on them.

You can hide them from systemd if you want, by dropping the "systemd" tag from them, if you are into that kind of tweaking.

i can't tell you why these device take so long to show up. Could be because the device probing in the driver is simply slow. Could be because you have awfully slow programs in your udev rules. Could be anything. The device showing up in systemd is pretty much the last step of the whole chain where it could be slow.

**Comment by boucman** [comment]
could it be that the kernel checks your MTD device for bad blocks ? I have seen mtd device take quite some time to appear because of the way that hardware works...

**Comment by franksinankaya** [comment]
I wasn't mounting those MTD devices TBH on this build. I just booted from ramdisk. I also don't have any custom udev rules.

FWIW, I can boot the system in 4 seconds with busybox. 

I'm not that convinced that those devices are cosmetic. Based on what I'm seeing on the graph, sysinit.target is gated on these devices showing up. There is 4 seconds of idleness here.

![image](https://user-images.githubusercontent.com/41809318/95486994-c1a18d80-0961-11eb-9a11-0df6bdd45c67.png)

**Comment by boucman** [comment]
I guess your busybox experiment doesn't include udev ? so you are not waiting for the devices to be ready...
moreover, bad blocks are a complex thing with MTD, they might be scanned even when not mounting the filesystem, i'm not sure (with things like UBI, they are not handled at the filesystem level at all...)

sysinit waits for "the base of the system" to be ready, and that includes waiting for udev to have settled. so sysinit waiting or your devices is normal. The real question is really why those devices take so long to be ready, not why we are waiting for them...

**Comment by franksinankaya** [comment]
Correct, I didn't use udev. It was busybox + mdev only.

All devices do show up in /dev directory though.
Maybe, those devices showed up as busybox continued to boot in parallel.

That's basically what I'm asking here.
Removing these devices from the hotpath and depend on systemd's Requires/After/Wants to serialize only the things that actually depend on them rather than gating the whole system from booting.

Based on what the udev diagram looks like, I also think there is some kind of a single threadedness going on somewhere.
All devices are created one device at a time. (even ttyS*)

**Comment by poettering** [comment]
> I wasn't mounting those MTD devices TBH on this build. I just booted from ramdisk. I also don't have any custom udev rules.

udev runs blkid on all block devices btw, and probes them, since it needs to figure out where to mount stuff from if mounts via /dev/disk/by-uuid/ and suchlike are used. udev will thus generate IO on block devices by default.

> FWIW, I can boot the system in 4 seconds with busybox.

Well, sure, but busybox doesn't do anything, does it?

> I'm not that convinced that those devices are cosmetic. Based on what I'm seeing on the graph, sysinit.target is gated on these devices showing up. There is 4 seconds of idleness here.

Well, "systemctl list-dependencies" shows you have sysinit.target depends on/is ordered after.

local-fs.target waits for all block devices listed in /etc/fstab to be mounted (and thus to have shown up, and probed by udev)

> sysinit waits for "the base of the system" to be ready, and that includes waiting for udev to have settled. so sysinit waiting or your devices is normal. The real question is really why those devices take so long to be ready, not why we are waiting for them...

Are you talking about systemd here? systemd does *not* wait for devices to be settled, if you are referring to the "udevadm settle" concept. Only legacy, broken software such as LVM requires that still, by pulling in systemd-udevadm-settle.service. If you encounter a system where that service is still pulled in, then it's basically unmaintained stuff from people who had their head in the sand for the last 10 years or so. systemd does not wait for devices to settle, some legacy software that needs urgent fixing might. systemd itself will only wait for devices to show up that it needs for what it is configured to. i.e. it waits for devices listed in /etc/fstab to show up, or waits for serial ports for which serial-getty@.service is pulled in, and so on. But it won't delay anything for devices that aren't actually used by anything.

> Based on what the udev diagram looks like, I also think there is some kind of a single threadedness going on somewhere.
> All devices are created one device at a time. (even ttyS*)

again, udev does not create devices. It just changes access modes/ownership/… on device nodes. The device nodes are created  by the Linux kernel in devtmpfs itself.

What distro is this btw? what kernel? what systemd?

note that udev will only run a number of device probes in parallel, and if those are all slow then of course udev takes a while to get through the queue. Use children_max= to increase this if you like.

**Comment by franksinankaya** [comment]
> What distro is this btw? what kernel? what systemd?
> 

This is yocto's thud baseline with 5.4 LTS kernel and systemd version 239.

**Comment by franksinankaya** [comment]
Could this wait be happening because system is waiting for ttyS4 (serial port) to show up to open a console and that happens to be the last one processed by the kernel because of slow mtd device problem?

Are there any other means to specify the serial port besides serial-getty service?

**Comment by franksinankaya** [comment]
I was wondering about the coupling between systemd and udev.

Which parts of systemd depend on udev? 
Is it possible to add with/with-out udev to systemd?

All embedded blogs I found suggests us to stay away from udev.
