### ISSUE TITLE
[systemd-udev-trigger] Coldplug devices rules parsed before kernel detects device

### ISSUE THREAD

**Issue by mkkot** [systemd/systemd#17373]
I have a USB scanner which needs udev rules to be applied so it can be accessed by users in 'scanner' group:

```
cat /usr/lib/udev/rules.d/49-sane.rules |grep -A1 '1200 TA'
# Mustek BearPaw 1200 CS | Mustek BearPaw 1200 TA
ATTRS{idVendor}=="055f", ATTRS{idProduct}=="021e", MODE="0664", GROUP="scanner", ENV{libsane_matched}="yes"
```

The scanner is permanently connected to the PC via USB port, so it's coldplugged. From udevadm documentation:

> udevadm trigger [options] [devpath|file|unit]
> 
> Request device events from the kernel. Primarily used to replay events at system coldplug time

This command is run by: 
`/usr/lib/systemd/system/systemd-udev-trigger.service`

```
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=udevadm trigger --type=subsystems --action=add
ExecStart=udevadm trigger --type=devices --action=add
```
**The problem is that it is run before the scanner is even detected by the kernel:**

```
[mk@linux ~]$ lsusb |grep Mustek
Bus 001 Device 007: ID 055f:021e Mustek Systems, Inc. BearPaw 1200 TA/CS
[mk@linux ~]$ journalctl -b |grep '021e'
Oct 17 09:52:51 linux kernel: usb 1-10.1: New USB device found, idVendor=055f, idProduct=021e, bcdDevice= 1.00
[mk@linux ~]$ journalctl -b |grep 'Coldplug'
Oct 17 09:52:50 linux systemd[1]: Starting Coldplug All udev Devices...
Oct 17 09:52:50 linux systemd[1]: Finished Coldplug All udev Devices.
```
Please mind the _**timestamps**_.

In the effect the device file doesn't get proper ACL:
```
[mk@linux ~]$ getfacl /dev/bus/usb/001/007 
getfacl: Removing leading '/' from absolute path names
# file: dev/bus/usb/001/007
# owner: root
# group: scanner
user::rw-
group::rw-
other::r--
```

After issuing:

```
[mk@linux ~]$ sudo systemctl restart systemd-udev-trigger.service 
[mk@linux ~]$ journalctl -b |grep 'Coldplug'
Oct 17 09:52:50 linux systemd[1]: Starting Coldplug All udev Devices...
Oct 17 09:52:50 linux systemd[1]: Finished Coldplug All udev Devices.
Oct 17 09:56:07 linux systemd[1]: Stopped Coldplug All udev Devices.
Oct 17 09:56:07 linux systemd[1]: Stopping Coldplug All udev Devices...
Oct 17 09:56:07 linux systemd[1]: Starting Coldplug All udev Devices...
Oct 17 09:56:08 linux systemd[1]: Finished Coldplug All udev Devices.
```

The appropriate sane rule from `/usr/lib/udev/rules.d/49-sane.rules` is applied and my user gets RW access in ACLs of the device file.

```
[mk@linux ~]$ getfacl /dev/bus/usb/001/007 
getfacl: Removing leading '/' from absolute path names
# file: dev/bus/usb/001/007
# owner: root
# group: scanner
user::rw-
user:mk:rw-   <<<<<<<< MY USER IS HERE 
group::rw-
mask::rw-
other::r--
```

Instead of restarting `systemd-udev-trigger.service` I can also physically unplug and plug again the USB plug of the scanner, so it gets hotplugged and the ACL of `/dev/bus/usb/001/007` is also altered.

My system:

> Archlinux
> systemd: 246.6-1
> linux: 5.8.14.arch1-1
> sane: 1.0.31-1
> libusb: 1.0.23-2
> Motherboard: Gibabyte B550M AORUS PRO (rev. 1.0)
> Scanner: Mustek BearPaw 1200 TA
> CPU: AMD Ryzen 3 PRO 4350G with Radeon Graphics

Downgrading systemd, kernel and sane few months back didn't help. I think this behaviour started when I upgraded my PC with new motherboard and CPU. 

[dmesg.txt](https://github.com/systemd/systemd/files/5395191/dmesg.txt)
[journal.txt](https://github.com/systemd/systemd/files/5395192/journal.txt)

**Comment by poettering** [comment]
This is a misunderstanding of how udev works. udev listens to all devices as they show up and runs udev rules for them. The `systemd-udev-trigger.service` exists only to close the gap for devices that have shown up before udev runs: for those devices udev missed the notifications of course, simply because they were generated before udev ran (possibly even before userspace ran at all). The `systemd-udev-trigger.service` just tells the kernel to please retrigger all devices again, i.e. synthesize new notifications for everything that already showed up, so that udev will run its rules for that too. The net effect is that udev will run its rules for all devices that ever have shown up, both those that showed up *before* udev ran, and those after.

Anyway, this looks like a misunderstanding how udev works, and probably is just an issue with the udev rule your supplied. Eitherway this is more of a help/support question then, and not a bug report. Hence please ask for help on a more appropriate forum, such as the systemd mailing list, please. This is a bug report and feature tracker, and afaics there's no bug here. 

Thank you for understanding!
