### ISSUE TITLE
Should systemd accept environment updates with values containing carriage return (CR, `\r`) characters?

### ISSUE THREAD

**Issue by ndim** [systemd/systemd#17378]
**systemd version the issue has been seen with**
 > systemd-246.6-3.fc33.x86_64

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > Linux infty 5.8.15-301.fc33.x86_64 #1 SMP Thu Oct 15 16:58:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Working gnome session upon logging in from gdm (yes, really, this does touch systemd).

**Unexpected behaviour you saw**
 > After gdm login, a black screen with a stationary mouse pointer.

**Steps to reproduce the problem**
 
  * Put something like the following lines into `/etc/profile.d/trigger-the-bug.sh` or some test user's `~/.bashrc` exporting environment variables which contain `\r` characters. E.g. (using vi's way of displaying the carriage return character as `^M`)

        CR="^M"
        export CR

        CRLF="^M
        "
        export CRLF

  * (For help with debugging, but not necessary to reproduce the issue:) As the test user in a virtual console, launch `busctl monitor --user > busctl-monitor--user.log`.

  * From gdm, log in as that user into a "Gnome" or "Gnome on Xorg" session.

  * Screen goes black, mouse pointer stops moving, and nothing happens any more.

As @benzea has diagnosed on my system, the following now happens:

  * `gdm` starts a login shell, which will pick up the environment variables containing `\r` characters

  * that login shell starts the `gnome-session` script

  * the `gnome-session` script starts `gnome-session-binary`

  * `gnome-session-binary` uploads the environment to the D-Bus bus name `org.freedesktop.systemd1` using `UnsetAndSetEnvironment`, containing information essential for launching the Gnome session

  * systemd detects `\r` characters somewhere in the new environment and therefore rejects the whole environment update, including those environment variables with essential information

  * now the `gnome-session-binary` process asks systemd to launch `gnome-session-binary --systemd-service --session=gnome`, which uses the environment which should have but does not have the environment variables with essential information

  * `gnome-session-binary --systemd-service --session=gnome` is now missing essential environment variables like `XDG_SESSION_TYPE`, so the `/usr/lib/systemd/user/org.gnome.Shell@wayland.service` and `/usr/lib/systemd/user/org.gnome.Shell@x11.service` checks for `XDG_SESSION_TYPE` being equal to `%I` fail

  * No service has been launched, nothing is done further, the screen stays black. The End.

The part where systemd could help here would be to allow environment variables containing `\r` characters alongside allowing those with `\t` and `\n` which it already allows. @benzea has located that check in https://github.com/systemd/systemd/blob/master/src/basic/env-util.c#L70.

**Comment by ndim** [comment]
For the record, the following issues are related:

  * https://github.com/systemd/systemd/issues/17378 (this issue)
  * https://gitlab.gnome.org/GNOME/gnome-session/-/issues/70
  * https://gitlab.gnome.org/GNOME/gnome-session/-/issues/71

**Comment by poettering** [comment]
Well, what's the rationale for doing this? Aren't you just asking for trouble by setting things up like that? 

`\r` is a great way to hide information by overprinting. I'd argue it's simply unsafe to allow systemd to be a conduit for such unsual and unsafe env vars.

We might want to handle this more graceful maybe: accept the rest of the data if there's more than one assignment, and just ignore (and log) the offending assignment.

systemd is a security boundary after all, in particulary PID 1, which accepts updates from unpriv clients (authenticated via polkit), I am thus very concerned about accepting any security-questionable rubbish as env var...

/cc @keszybz

**Comment by benzea** [comment]
Note that gnome-session already does some filtering. We can also ignore the assignment on that side already.

**Comment by ndim** [comment]
> Well, what's the rationale for doing this? Aren't you just asking for trouble by setting things up like that?

Probably.

From a user point of view, there used to be no problem having an environment variable CR containing a `\r` character for years. Now there is a problem, and the user visible feedback is "screen stays black" meaning "we suddenly have an issue with the value of an environment variable which used to be no problem for years to decades". That should be fixed "somewhere".

A first glance from a more technical point of view inside systemd, the `env_value_is_valid()` function does some checks on the value of an environment variable, where the criteria for "valid" appear to mean:

  * valid UTF-8
  * bash allows it
  * string is not too large (measured in bytes, not UTF-8 characters)

As the `\r` character is a valid part of bash variable's values, accepting `\r` could be considered reasonable for `env_value_is_valid()`. There might be other criteria to consider, though.

> `\r` is a great way to hide information by overprinting. I'd argue it's simply unsafe to allow systemd to be a conduit for such unsual and unsafe env vars.

Systemd also passes env variables containing substrings like "\e" (backslash e) which is often interpreted as an ESC character later, e.g. in PS1 prompts. Terminals parsing ESC characters can also be a source for a lot of confusing, obfuscating, and potentially exploiting of terminal behaviour. And systemd does not refuse that at all, does it? It would refuse a literal ESC character, of course.

However... why are those shell environment variables even passed around at all everywhere during Gnome session service startup?

Shells launched from somewhere inside a Gnome session will eventually read `~/.bashrc` and `/etc/profile.d/` and whatever anyway, so those variables need not be passed through the Gnome session startup for that purpose.

For passing a well-defined set of variables and values from one part of the Gnome session startup to other parts of the Gnome session startup, do you really need shell environment variables, do you? The D-Bus mechanisms for dealing with environment variables may be a convenient way to pass around a set of key value pairs inside the subtree of services dealing with a Gnome session, but do they need to be conflated with shell variables?

In this case, `gnome-session-binary` should pass a very short and strict positive list of variables in the first place, and the only thing systemd could help with here may be a more explicit error message returned to the D-Bus caller and/or logged, perhaps including the name of the first offending variable (env var names can be validated much more strictly in `env_name_is_valid()` than env var values can in `env_value_is_valid()`) and a reference to a description of what kinds of values systemd considers valid ("strictly safe and secure subset" sssss S5?).

> We might want to handle this more graceful maybe: accept the rest of the data if there's more than one assignment, and just ignore (and log) the offending assignment.

I would argue against partially succeeding operations, as that concept appears to open a whole new world of complexity in dealing with failures. If the call either succeeds or fails, the caller knows precisely where they are standing, and there are only two possibilities the caller code needs to deal.

Communicating back which parts were valid and which ones were not is also complex, as is handling that information on the caller's part. That kind of code complexity does not appear to be warranted here.

> systemd is a security boundary after all, in particulary PID 1, which accepts updates from unpriv clients (authenticated via polkit), I am thus very concerned about accepting any security-questionable rubbish as env var...

Good point.

If my above idea about Gnome not passing around shell variables at all holds any water, I would say this issue is outside of systemd's realm after all, with the possible exception of maybe the aformentioned improvements to error reporting.

**Comment by poettering** [comment]
> From a user point of view, there used to be no problem having an environment variable CR containing a `\r` character for years. Now there is a problem, and the user visible feedback is "screen stays black" meaning "we suddenly have an issue with the value of an environment variable which used to be no problem for years to decades". That should be fixed "somewhere".

Well again, we could change things to simply eat up/warn log those weird assignments. 

Previously there was no service manager env vars could be loaded into, hence it doesn't really matter what was before, this is a new concept. Of course showing a black screen is not the solution, but there are at least two choices that are different from the current failure of showing a black screen: accept questionnable env vars or ignore questionnable env vars. I am leaning towards the latter, since systemd is a security boundary.

> Systemd also passes env variables containing substrings like "\e" (backslash e) which is often interpreted as an ESC character later, e.g. in PS1 prompts. Terminals parsing ESC characters can also be a source for a lot of confusing, obfuscating, and potentially exploiting of terminal behaviour. And systemd does not refuse that at all, does it? It would refuse a literal ESC character, of course.

Well, I think systemd is the wrong place to totally and completely sanitize env vars to the most extreme knowing whatever weird variable means to whatever weird apps people use that could trip up on them. That's totally out of scope. But what is in scope is to ensure that the most obvious dangerous stuff doesn't end up in every single service we manage. Security is not a boolean thing. It's a gradual thing, and I think there's a lot of value of doing basic sanitizing — but avoid extreme sanitizing.

> I would argue against partially succeeding operations, as that concept appears to open a whole new world of complexity in dealing with failures. If the call either succeeds or fails, the caller knows precisely where they are standing, and there are only two possibilities the caller code needs to deal.

I disagree. This is not common stuff, these are corner cases. They simply don't matter enough to be worth causing failure. And as you correctly notice, it's actually bash internal stuff: if this doesn#t get inherited into all service this doesn#t matter, since bash_profile is going to set it again anyway.

I must say I totally understand why GNOME uploads everything: it's closest to what was done before in the status quo ante where all desktop apps + services where ultimately forked off the same gnome session process and thus also inherited the same set of env vars. And it's simple and generic: if you just upload everything then you do not need to maintain app-specific allow lists, and maintaining them sucks hard.

**Comment by poettering** [comment]
So I think I we should just drop the offending vars, and maybe log about them. There are two approaches to this actually:

1. Clean things up server side
2. Clean things up client side, before submitting this to the server.

Now, as it turns out "systemctl import" actually already implements the latter since a4ccce22d9552dc74b6916cc5ec57f2a0b686b4f (i.e. current git master). And I think that is kinda nice, since the method calls then do not hide stuff to the client.

Hence, @benzea you already suggested to do the filtering client side. Maybe we should do that, and then close this PR? Would that work for you?

Our validation functions are here for reference. 

https://github.com/systemd/systemd/blob/master/src/basic/env-util.c#L84

gnome would have to enforce similar validation and drop the fields client side then.

Sounds OK?

**Comment by ndim** [comment]
With the answer being "No".

**Comment by benzea** [comment]
> Hence, @benzea you already suggested to do the filtering client side. Maybe we should do that, and then close this PR? Would that work for you?

I already submitted the relevant gnome-session patches. Also adding log messages when we filter something and throwing a warning should systemd reject our request to update the environment.
 * https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/53
 * https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/54

It seems fine to me to leave it as is. Really, the main pain point was that gnome-session was not logging the error causing it to become almost invisible.

**Comment by poettering** [comment]
Excellent! Let's close then! Thanks!
