### ISSUE TITLE
Follow mode (-f) doesn't work when combining logs

### ISSUE THREAD

**Issue by kripper** [systemd/systemd#17398]
**systemd version the issue has been seen with**
 > systemd-219-73.el7_8.6.x86_64

**Used distribution**
 > CentOS 7

**Linux kernel version used** (`uname -a`)
 > kernel-3.10.0-327.el7.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Show only the most recent journal entries, and continuously print new entries as they are appended to the journal.

**Unexpected behaviour you saw**
 > "continuously print new entries as they are appended to the journal" is not working.

**Steps to reproduce the problem**
- /usr/bin/journalctl _SYSTEMD_UNIT=my_service.service + SYSLOG_IDENTIFIER=my_identifier -e
- Press F key to activate follow mode (-f)

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
