### ISSUE TITLE
[Match] Section for systemd.mount

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#17394]
Implement support in systemd.mount to do matching of .mount configuration files.
Similar to what is done in systemd.networkd (at least allowing matching hostname).

**Comment by poettering** [comment]
I am sorry, what?

.mount units define a mount point, i.e. the *synthesize* new mount points generally, and don't operate on *pre-existing* mount points. [Match] sections in .network file otoh operate on pre-existing interfaces and never synthesize interfaces.

hence i really don#t grok what you are looking for.

let's start from the beginning: please explain your usecase.

**Comment by boucman** [comment]
matching on hostname can be done with ConditionHost= in the [Unit] section, IIRC

**Comment by poettering** [comment]
oh, ah, if it's about conditionalizing things based on hostname or so, we have support for various ConditionXYZ= already:

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Conditions%20and%20Asserts

I guess we can close this then.

**Comment by boucman** [comment]
well, since .mount units must have fixed filenames... we can't really use them. 

That would be a problem even with a [Match] secction since no two units can describe the same mount point, even if the logically don't contradict each other..

**Comment by poettering** [comment]
use for what?

What#s the usecase here? I don't get it? is this not just about Conditionhostname=? what is this about?

**Comment by boucman** [comment]
I'm not the OP, so i'm speculating but I would guess he wants to mount different devices depending on the hostname...
i.e use /dev/sda1 on machine1 and /dev/mmcblk0p1 on another or something similar...

if you want to mount the relevant one on /home for example, you would need two .mount units with different ConditionHost, but you can't since they would both need to be named home.mount

Again, just speculating since I'm not the OP, I don't have a personal use-case for that.

**Comment by poettering** [comment]
sounds more like the job for a generator

@malikumaliku can you elaborate on your usecase, please?
