### ISSUE TITLE
move examples from man pages to /usr/share/systemd/examples

### ISSUE THREAD

**Issue by eszlari** [systemd/systemd#1743]
I would like to be able to just

```
cp /usr/share/systemd/examples/network/80-dhcp.network /etc/systemd/network/
```

to configure my network connection.

**Comment by poettering** [comment]
Why doesn't copy/pasting them from the man pages not work? It's not that the files are really that large...

**Comment by eszlari** [comment]
Yes, it's a minor thing, but it gets annoying when you have to do it multiple times (e.g. when installing multiple machines or testing different distributions).

**Comment by keszybz** [comment]
The examples are always tied to specific configuration. Even the one for dhcp limits to en*, which is often reasonable, but not always. If we moved it to examples and thus encouraged people to link to those files, we would be bound by the details, and couldn't change the examples as we see fit because somebody could be relying on the specific form. The example for dhcp is the only one which is generic enough to be widely used, but even that doesn't cover all common configurations. This just doesn't seem to be a good idea.
