### ISSUE TITLE
LUKS passphrase is not reused to decrypt GNOME keyring if multiple attempts are used to enter the LUKS passphrase

### ISSUE THREAD

**Issue by intelfx** [systemd/systemd#17565]
**systemd version the issue has been seen with**

> systemd 246 (246.6-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux able 5.8.14-arch0pf7-1 #2 SMP PREEMPT Thu, 01 Jan 1970 00:00:00 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 
After entering the password to decrypt LUKS2 root partition in initramfs, I expect the same password to be reused to decrypt GNOME login keyring.

**Unexpected behaviour you saw**
 
_If_ I do not enter the LUKS passphrase correctly on the first attempt, the subsequently entered passphrase is not used to decrypt GNOME login keyring and a keyring decryption prompt appears after autologin.

**Steps to reproduce the problem**
 
1. Configure LUKS encryption for the rootfs.
2. Configure initramfs to use systemd (and, therefore, systemd-cryptsetup).
3. Enable autologin in GDM.
4. Set your GNOME login keyring password to the LUKS passphrase.
5. Reboot and enter the LUKS password incorrectly on the first attempt.

**Comment by poettering** [comment]
uh oh, no idea what gnome keyring actually does to get the password.

Note that systemd-ask-password generally handles multiple passwords. Not sure wether the further components in the stack that deal with the pw can do that though. But that's outside of systemd's control.

@benzea do you happen to know how the PW ultimately makes it to gnome keyring? or you @halfline?

**Comment by benzea** [comment]
gnome-keyring has its own PAM module and it just uses the password from the pam session if it can get that. Really, I don't think that can work.

The only way for this to work is to try and use the LUKS password for the login, thought there was a mechanism to store it temporarily and then use it for the login. But not sure if/how that is supposed to work.

**Comment by poettering** [comment]
So, it's actually gdm that puts the password from LUKS into the PAM stack, see

https://gitlab.gnome.org/GNOME/gdm/-/blob/master/pam_gdm/pam_gdm.c#L35

The thing though is, there is a certain asymmetry here: the passwords the password querying logic in systemd acquires are all put in the kernel keyring, in a NUL separated list. GNOME only pulls out one though, see the code above.

the pw querying logic in systemd doesn't really know which passwords worked and which ones did not. It caches the input data, whatever that is.

PAM of course can't really deal with multiple passwords being passed into the stack, there can only be one. But it probably should take the last password in the cached list, not the first one. (the passwords stored in the cache are strictly in order)

Hence I figure we should move this over to gdm, this needs to be fixed in pam_gdm.

**Comment by poettering** [comment]
A filed a bug on gnome bugzilla now:

https://gitlab.gnome.org/GNOME/gdm/-/issues/657

I guess discussion should be continued there. Let's close this there.

**Comment by intelfx** [comment]
> The thing though is, there is a certain asymmetry here: the passwords the password querying logic in systemd acquires are all put in the kernel keyring, in a NUL separated list. GNOME only pulls out one though, see the code above.
>
> the pw querying logic in systemd doesn't really know which passwords worked and which ones did not. It caches the input data, whatever that is.
>
> PAM of course can't really deal with multiple passwords being passed into the stack, there can only be one. But it probably should take the last password in the cached list, not the first one. (the passwords stored in the cache are strictly in order)

Ah, I see the issue. I assumed that the password caching works on a different level. Thanks for the analysis @poettering!

**Comment by TastyPi** [comment]
FYI I've created a pull request to fix this in gdm, hopefully it will be accepted https://gitlab.gnome.org/GNOME/gdm/-/merge_requests/136
