### ISSUE TITLE
Make WakeSystem= available for user units

### ISSUE THREAD

**Issue by jsparber** [systemd/systemd#17564]
**Is your feature request related to a problem? Please describe.**
The main goal is to implement a background service for gnome-clocks that can wake the system when suspended.
It would be nice to implement the alarms for gnome-clocks via user `.timer` units, but an alarm needs also to go off when the system is suspended, which isn't possible right now since `WakeSystem=` needs privileges . https://gitlab.gnome.org/GNOME/gnome-clocks/-/issues/100

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
The problem is that a non privileged user isn't allowed to create a timer with `timerfd_create` that can wake up the system from suspend, because they don't have access to `CLOCK_BOOTTIME_ALARM` and `CLOCK_REALTIME_ALARM`.

**Describe the solution you'd like**
I would like the `WakeSystem=` to work the same as per system unit files and wake the system once the timer goes off.

**Describe alternatives you've considered**
I also considered extending the systemd-timedated to allow adding wake up timers, but this wouldn't fit well with the unit file of systemd.

**Comment by jsparber** [comment]
I would work on this but i don't know how this should be implemented.

**Comment by poettering** [comment]
Hmm, so this is about giving unpriv users access to CLOCK_REALTIME_ALARM, which currently needs CAP_WAKE_ALARM, as enforced by the kernel.

I am not entirely sure how this could look best.

Do you actually care that the `systemd --user` instances triggers things for you, i.e. invokes some binary for you? Or do you have code running anyway all the time? If the latter it would probably make sense to provide a tiny privileged service that hands out fully initialized timerfds to you, after some policykit authorization. Something like that might even live in logind, given logind already deals with authenticated, user-managed, system suspend, and I guess wakeup timers like this are just a way of system resume.

Another, simpler, option would be to simply pass CAP_WAKE_ALARM to all "regular" users (i.e. add it to all regular user's ambient set at login time), so that all regular users can have such timers without any special setup. But maybe this is a shortcut that's just too short, given that I understand gnome actually wants to lock down individual apps, and this way (unless gnome/flatpak would explicitly drop the cap on every single process it forks off again)

If you actually want to user .timer units (so that your code doesn't need to run all the time), then I guess we could implement things as suggested above, and make `systemd --user` talk to the systemd-logind via the same API to acquire its timer. but that's not totally trivial, since sd-event (the event loop systemd uses) is big on backing all timer events by a single timer fd per clock only, and then reprograms it all the time. But such reprogramming isn't going to be cheap if we go to dbus all the time.

**Comment by jsparber** [comment]
The idea is not to have code running all time and let systemd start the application when needed.

**Comment by jsparber** [comment]
would it be possible to give only `systemd --user` `CAP_WAKE_ALARM`?

**Comment by jsparber** [comment]
My first approach would be:
Logind:
- Add dbus API to logind to add timers that takes: `clock, time [usec], fd, accuracy, interactive`.
- The dbus method calls internally `sd_event_add_time()` to create a new timer. 
- Once the timer goes off logind closes `fd` to emit `EPOLLHUP` event.
- When the `fd` is closed by the caller the timer is removed, therefore we need to listen to io events via `sd_event_add_io()`

Systemd user mode:
- If systemd is in `user` mode and `WakeSystem=true` then we make a call to the dbus API instead of adding a new timer to the event loop via `sd_event_add_time()`. The required `fd` is created via `eventfd` then we can listen for the EPOLLHUP event via `sd_event_add_io()` to get notified that the timer went off (a.k.a the `fd` was closed).
- To remove the timer we can simply `close (fd)`which emits `EPOLLHUP`

I'm open to suggestions and corrections.

**Comment by poettering** [comment]
Quite frankly, I am coming back to this in my head over and over again, and I always end up thinking we should just give CAP_WAKE_ALARM to all human users by default (i.e. not to system users such as the http user or so). i see no reason why we'd ever want to interactively authenticate whether an app is allowed to install such a wake-up timer, and that would be the only benefit that going the logind way would give us. would you want to have a polkit auth dialog whenever somebody sets a timer like this? i doubt it.

Moreover, as we allow suspending without extra authentication generally, and resuming should be much less invasive than suspending I'd say.

Hence, I'd probably go this way:

1. Somebody should write a pam module, whose only purpose is to add arbitrary ambient caps configured on its pam module line to users logging in. This pam module should be placed in the PAM stacks of at least the per-user systemd instance, but probably every place where a PAM session can be allocated in the big distros, turning on CAP_WAKE_ALARM for them. (for users managed by systemd-homed I am gonna add a proper JSON property for this, making that module redundant. But the module I propose is needed for non-homed-users, i.e. traditional /etc/passwd ones)

2. any service or sandbox management tool should be carefully checked/updated to drop any ambient caps it might receive before invoking its payload, i.e. prohibit accidental propagation of ambient caps. Specifically this means: systemd --user should not pass ambient caps itself might have received via PAM on to its services, except if they are listed in the ambient caps setting in their service unit files too. Similar, things like flatpak should also mangle their ambient caps set, and drop anyhting from it. (maybe it actually does tha already, as side effect of the userns stuff it does?)

3. gnome-clocks should then simply request the CAP_WAKE_ALARM cap in its unit file, and thus should get it passed in because now the systemd --user instance posseses it.

I think ultimately this would be a much simpler, nicer solution, because noone would have to call any new fancy apis, but can just use regular kernel timerfd.

@alexlarsson what's your take on this? given your involvement in flatpak i figure you might have an opinion on this? does flatpak currently drop all ambient caps it might receive?

**Comment by poettering** [comment]
(btw, because the implications of just giving all human users that cap aren't entirely clearly to me, i asked twitter about it: https://twitter.com/pid_eins/status/1334253187176468483

**Comment by alexlarsson** [comment]
Flatpak currently strips all capabilities from the child so you would not be able to pass on CAP_WAKE_ALARM. This is mainly out of caution for the unknown though, and If we deep a particular cap to be safe we could change it to be passed through.

**Comment by pothos** [comment]
> 3. gnome-clocks should then simply request the CAP_WAKE_ALARM cap in its unit file, and thus should get it passed in because now the systemd --user instance posseses it.

When `systemd --user` already has the capability, then GNOME Clocks could use `WakeSystem=true` user timers and does not need the capability itself. Maybe it's possible to set the capability for the systemd binary only instead of dealing with PAM and ambient capabilities?

**Comment by poettering** [comment]
Not a fan of fscaps... i.e. caps should be passed down the tree, and not something we can acquire through suid/fscaps. if you ask me it's a hacky misdesign of unix that it introduced suid binaries, and fscaps are just an extension to that. To me it sounds much better to pass them down the tree right-away.

**Comment by poettering** [comment]
I posted this now: https://github.com/linux-pam/linux-pam/issues/317

maybe the PAM devs want to make us a belated christmas present, so I figured it might be worth to just ask for the feature from them ;-)

**Comment by spaetz** [comment]
So the blocking pam issue says this is already possible with ^cap_wake_alarm *. Their side seems ok, so what do we need on the systemd side to allow user timers using WakeSystem=True?

**Comment by karlkashofer** [comment]
Hi Lennart, Sebastian !
It seems the PAM issue was solved for real in August 2021, not exactly Christmas, but alas, is implementation of this feature now possible ? We'd really need in on Pinephone et. al. :)
Cheers,
KK

**Comment by pothos** [comment]
I installed (on Debian) libpam-cap, put `^cap_wake_alarm *` into `/etc/security/capability.conf` (the `none *` line commented out), and got this result (from a new `sudo -u $USER -i` shell):
```
$ capsh --print | grep wake
Current: cap_wake_alarm=i
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore
Current IAB: cap_wake_alarm
```

Not sure if this is will work yet for `/lib/systemd/systemd --user` because with a quick test of swapping out `CLOCK_REALTIME` for `CLOCK_REALTIME_ALARM` in the `man 2 timerfd_create` example I got `timerfd_create: Operation not permitted`.
Maybe the related fixes mentioned in the PAM ticket are still missing on my system.

**Comment by spaetz** [comment]
> installed (on Debian sid) libpam-cap, put `^cap_wake_alarm *` into `/etc/security/capability.conf` 

I tried the same thing previously and could not get it to work not sure what was missing, so no, no cigar yet....

**Comment by AndrewGMorgan** [comment]
What version of `libcap` and what version of `libpam` ? What is your `pam.d` config line that references [`pam_cap.so`](https://sites.google.com/site/fullycapable/pam_cap-so)?

**Comment by AndrewGMorgan** [comment]
I grep'd through the `systemd` sources for how it invokes `pam_end()`. I don't think it is following the [documentation for `pam_end()`](http://www.linux-pam.org/Linux-PAM-html/adg-interface-by-app-expected.html#adg-pam_end) (written sometime around the year 2000). That is: 
```
systemd $ git grep PAM_DATA_SILENT
systemd $
```
As such, I think that is likely the crux of the issue. You can see this omission is widespread, likely due to copy-pasta coding. The story of fixing it in the shadow and util-linux packages can be followed from here: https://github.com/shadow-maint/shadow/pull/408#issuecomment-919673098 .

**Comment by pothos** [comment]
Yes, should have written that, sorry: libcap 2.44-1, libpam 1.4.0-11

`auth	optional			pam_cap.so` is the last line of `/etc/pam.d/common-auth`

**Comment by pothos** [comment]
… and libpam-cap is also on 2.44-1 - thanks for the link to the home page which clearly says `From 2.58 on, compliant Linux-PAM applications should be able to support Ambient vector Capability inheritance.`. I need to get a newer version first.

**Comment by spaetz** [comment]
Just filed a spin-off issue with regard to pam_end, to keep this one focused on the WakeSystem progress.

**Comment by AndrewGMorgan** [comment]
To be clear, getting PAM to propagate Ambient values requires the following things to be true:

- `systemd` needs to correctly use `PAM_DATA_SILENT` in the `pam_end()` arguments **for the process that execs the child**
- use a modern enough version of `libcap` & `pam_cap.so` (version >= 2.58)
- include the `pam_cap.so` module arguments: `keepcaps` and `defer`.

**Comment by spaetz** [comment]
@AndrewGMorgan I apologize for drawing your attention to the above, but am I doing something fundamentally wrong?

**Comment by pothos** [comment]
> /etc/capabilities/security contains ^cap_wake_alarm *

I think you mean `/etc/security/capability.conf`, or?

As far as I understood there are changes needed in systemd (maybe how the caps get passed/dropped, maybe how the timer works in the user session?).

**Comment by spaetz** [comment]
> > /etc/capabilities/security contains ^cap_wake_alarm *
> 
> I think you mean `/etc/security/capability.conf`, or?

of course, fixed. Sorry and thanks.

**Comment by AndrewGMorgan** [comment]
Catching up after a bit of a vacation. It looks like you have verified that `su` to a user, configured with some Ambient capabilities enabled, works. This seems to demonstrate that the PAM and `libcap` things are set up correctly.

If you have [`captree`](https://sites.google.com/site/fullycapable/captree) installed, you might be able to figure out where the Ambient capabilities are added and/or taken away.

It looks to me (`captree systemd`), based on the single `(sd-pam)` process under the `systemd` child that looks to be invoking terminals etc on my system, that some sort of PAM setup is being invoked. However, I'm not familiar with `systemd` and can't find any indication of which PAM service name `systemd` is using for me. None of the `/etc/systemd/` files on my system make reference to `PAMName`.

**Comment by spaetz** [comment]
I'd say, that the ball is now in systemd's court. libcap allows want we need, the pam way works in granting ambient capabilities, including System wakeup. Now, all that remains to be done to start systemd --user in a way that it invokes the pam.d modules to get those capabilities itself.

**Comment by karlkashofer** [comment]
Any updates on this ?

Is Lennart still following systemd issues ?

**Comment by spaetz** [comment]
Just wanted to point to my summarizing notes at https://pad.uni-hamburg.de/s/VlSduMhxt# with a section on 'working theory what goes wrong' which explains how to reproduce and what changes `systemd --user` needs imho. (sorry no patches though)

**Comment by pothos** [comment]
Thank you for the PR, with adding `CAP_WAKE_ALARM` by default it shouldn't be needed anymore in `/etc/security/capability.conf`, right? Extending the `/etc/pam.d/common-auth` line `auth optional pam_cap.so` with `keepcaps defer` is still needed, though, or not?

**Comment by poettering** [comment]
@pothos nah, with #26548 this should not be necessary.
