### ISSUE TITLE
pid1: a Wants=foo@%n.service in a service foo@.service creates too many units

### ISSUE THREAD

**Issue by ckotte** [systemd/systemd#17602]
**systemd version the issue has been seen with**
 246.6

**Used distribution**
 Arch Linux

**Linux kernel version used** (`uname -a`)
 5.9.3-arch1-1

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
Only one additional (notify) service should be created for every unit on the system.

**Unexpected behaviour you saw**

1550 services are created from the template:

```
systemctl show systemd-notify@
zsh: do you wish to see all 1200 possibilities (1550 lines)? 
```
```
...
systemd-notify@systemd-notify@systemd-notify@systemd-journal-flush.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-logind.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-machined.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-machine-id-commit.service.service.service.service
systemd-notify@systemd-notify@systemd-notify@systemd-modules-load.service.service.service.service
...
```

"hundreds" of entries like this in the log:
```
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@updatedb.service.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-tmpfiles-clean.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@emergency.service.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
Nov 13 20:06:18 icarus systemd[1]: /etc/systemd/system/service.d/10-override.conf:3: Failed to add dependency on systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@systemd-notify@rescue.service.service.service.service.service.service.service.service.service.service.service.service, ignoring: Invalid argument
```

**Steps to reproduce the problem**

Create top-level drop-in with OnFailure override:
```
/etc/systemd/system/service.d/10-override.conf
[Unit]
OnFailure=systemd-notify@%n.service
```

Create template unit:
```
/etc/systemd/system/systemd-notify@.service
[Unit]
Description=Send desktop notification to user on unit failure

[Service]
Type=oneshot
ExecStart=su user -c "DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send --urgency=critical 'Systemd unit %i failed.' \
  'See \"systemctl status %i\" and \"journalctl -xe\" for details.'"
```

**Comment by poettering** [comment]
The current logic does make sense: if you drop in such a thing that will instantiate a new unit for it, which then will instantiate another unit following the same logic, and so on.

So yeah, the current logic does exactly what you wanted: it creates one additional service for every service, but that includes that additional unit that you create, hence this grows linearly. Think about as: the notification services that runs on failure also will get a notification service that runs on its failure and so on.

There's no need top involve drop-ins in this, it suffices to do this:

```
$ cat foo@.service 
[Unit]
OnFailure=foo@%n.service

[Service]
ExecStart=/bin/false
```

if you load the unit (with a simple "systemctl status foo@xyz.service") then it will load recursive failure units for that too.

I think behaviour on this is not tottally wrong after all the recursion is bounded. But we might want to lower the limit somehow. Not sure how we could do that though.

**Comment by ckotte** [comment]
@poettering How can I automatically add OnFailure to all services on my system with that approach? Do I have to load the units manually for every service?

I tested this with one service and here I have the same issue:

```
# systemctl show foo@
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service.service
foo@foo@foo@foo@foo@reflector.service.service.service.service.service.service
foo@foo@foo@foo@reflector.service.service.service.service.service
foo@foo@foo@reflector.service.service.service.service
foo@foo@reflector.service.service.service
foo@reflector.service.service
```

Also lots of errors in the journal.

This "loop" should be blocked and the unit created from a template unit should not be able to create a new unit. Is there any practical value in allowing this behavior?

**Comment by ppacher** [comment]
It's interesting that I found this issue now since I'm facing a similar one for a few days now (see [here](https://www.reddit.com/r/systemd/comments/js9d85/reset_onfailure_stanza_via_dropin_file/) for my question on r/systemd). I totally get that this is actually expected behavior. Though, I expected to be able to work around the recursion by overwritting the `OnFailure` stanza using a drop-in for the actual `OnFailure` handler service.

To be exact, I'd like to get mail notifications for all services that enter failure state by using a drop-in file in `service.d` with something like `OnFailure=systemd-email-user@%n.service`. This works as expected but if systemd-email-user fails itself for some reason it will enter an endless loop that stops at the recursion limit (with `Invalid argument`). To fix that, I added a drop-in file for the `systemd-email-user@.service` that sets `OnFailure` to empty. IMHO, this should reset the OnFailure list. `systemctl cat systemd-email-user@.service` also shows what I wanted to do (below) but once I do `systemctl daemon-reload` I end up with a bunch of error messages like @ckotte .

```
# /etc/systemd/system/systemd-email-user@.service
[Unit]
Description=Status email for %i to user

[Service]
Type=oneshot
ExecStart=-/usr/local/bin/systemd-email noc@domain.tld %i
User=root
Group=systemd-journal

# /etc/systemd/system/service.d/90-report-failure.conf
[Unit]
OnFailure=systemd-email-user@%n.service

# /etc/systemd/system/systemd-email-user@.service.d/99-failure-overwrite.conf
[Unit]
# Clear out any OnFailure setting.
OnFailure=
```

**Comment by ppacher** [comment]
@poettering IMHO the actual issue is that it's not possible to "reset" the `OnFailure` stanza using drop-in files. This way it's actually useless to even allow setting `OnFailure` using drop-ins.

**Comment by pdmorrow** [comment]
Hi,

I have the same requirement as @ppacher here, i.e. the want to add an instance OnFailure= dependency for all services except the one which handles the first failure. The use case is pretty much the same, I want to be able to run a tool which gathers some extra diagnostics when any service or mount unit fails.

I took a stab at fixing this via a few commits and confirmed it works via some new tests and also booting my system with these patches applied:

https://github.com/pdmorrow/systemd/commits/onfailure_dep_removal_master

One thing I also noticed is that even without any of my diffs applied, it seems like the when I boot a system (using v244 here) with the following unit files installed (for example):

```
/lib/systemd/system/failure-handler@.service:
    
[Unit]
Description=Failure handler for service "%I"
    
[Service]
Type=oneshot
ExecStart=/bin/myfailure-handler %i
```
    
```
/lib/systemd/system/service.d/20-all-services-on-failure.conf:
    
[Unit]
OnFailure=failure-handler@%N.service
```
    
```
/lib/systemd/system/failure-handler@.service.d/failure-handler.conf:
    
[Unit]
OnFailure=
```

systemd takes much longer to start up:

![image](https://user-images.githubusercontent.com/696127/101006803-2ab81280-3559-11eb-8e0e-0379c5e47dc9.png)


vs a system booted with none of the above unit files or drop-ins:

![image](https://user-images.githubusercontent.com/696127/101008478-a1eda680-3559-11eb-850c-a4354c4fe8a2.png)

I am assuming this is due to the huge number of units created (as the title of this issue suggests).

Thanks!

**Comment by anitazha** [comment]
Catching up on this issue. Correct me if I'm wrong but we need to tackle 2 problems:
- Lower the limit for dependencies recursively being added through templating
- "Clearing" properties with an empty setting (e.g. OnFailure=) are not working in top-level drop-ins

**Comment by pdmorrow** [comment]
Hi @anitazha 

I think that is accurate, though for clearing properties the issue isn't specific to top-level drop-ins. I have a few patches which allow clearing out OnFailure dependencies (only OnFailure, no other dependency types) which seems to work. I'm happy to send a PR for that part (https://github.com/pdmorrow/systemd/tree/onfailure_dep_removal_main).

**Comment by anitazha** [comment]
PR is most welcome @pdmorrow

**Comment by pdmorrow** [comment]
@anitazha I submitted https://github.com/systemd/systemd/pull/19771 for the dependency removal part.

**Comment by bluca** [comment]
@ckotte as mentioned by Lennart in #19771 you can block the top-level drop-in by symlinking it (same name) to /dev/null in the template unit drop-in directory.

ie, add:

```
/etc/systemd/system/systemd-notify@.service.d/10-override.conf -> /dev/null
```

and this will break the chain.

I think @anitazha's idea of limiting the recursion so that we don't DoS ourselves makes sense as well, as a separate and independent change.
