### ISSUE TITLE
Mount unit enters active (mounted) state when mount process exits with status=1/FAILURE

### ISSUE THREAD

**Issue by scruloose** [systemd/systemd#17617]
**systemd version the issue has been seen with**
 > Systemd 246

**Used distribution**
 > Debian Bullseye

**Linux kernel version used**
 > `5.8.0-2-amd64 #1 SMP Debian 5.8.10-1`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > When the mount process exits with a non-zero status, I would expect the mount unit to enter failed state accordingly. Interestingly, when an unmount fails (eg `target is busy` which returns `status=32/n/a`) it does register as failed: the next line in the log reads `"<unitname>.mount: Failed with result 'exit-code'.`, and the `OnFailure` dependency is triggered. I honestly don't know whether it's intended/expected that a failed attempt to unmount a filesystem that's not mounted causes the mount unit to enter a failed state, but I would certainly expect a failed *mount* process to do so.

**Unexpected behaviour you saw**
 > When the mount process returns  `status=1/FAILURE`, the mount unit enters state `active (mounted)` and the `OnFailure` dependency is not triggered (but the filesystem is of course not mounted). I found this particularly surprising given that the log shown by journalctl indicates the mount process exit status as "FAILURE".

**Steps to reproduce the problem**
 > In my case, it's an sshfs mount triggered by an automount unit. Making the ssh key inaccessible will cause the mount process to fail (`Connection reset by peer`), triggering the bug. I have not tested with other filesystems, or with other failure modes yielding different exit codes than the ones mentioned above.

**Comment by yuwata** [comment]
Could you provide debugging logs for the issue?

**Comment by yuwata** [comment]
Thanks, but unfortunately these are not debug log. Please enable debug mode by `sudo systemd-analyze log-level debug`, then start/stop the corresponding .mount or .automount unit, and provide the relevant journal log. Thank you.

**Comment by scruloose** [comment]
Oh, I see. Sorry about that.

Let's try this again:

[automount-debuglog.txt](https://github.com/systemd/systemd/files/5550108/automount-debuglog.txt)
[mount-debuglog.txt](https://github.com/systemd/systemd/files/5550110/mount-debuglog.txt)

**Comment by yuwata** [comment]
@scruloose Thanks!

**Comment by scruloose** [comment]
By the way:
* I have verified that moving the automount location out of `/media` makes the frequent polling events go away.
* Triggering the automount manually with `ls` *does* still result in the `status=1/FAILURE` → `Mounted` behaviour. (That is, with the ssh key unavailable in order to make the mount fail for testing purposes.)
* I can get you debug logs without all the noise of those polling events if you like.

**Comment by yuwata** [comment]
@scruloose I've created #17631, though I have not tested it. If it is possible and you want, please test the PR. Thank you.

**Comment by scruloose** [comment]
Thanks! That was quick!

In theory, I'm happy to test it. In practice, building and installing something as big and complex as systemd straight from the git repo is pushing the boundaries of my skills.

I may spin up a VM, make sure I can reproduce the bug, and take a stab at building and testing that PR at some point in the next few days. I'm not going to promise results, though.

**Comment by yuwata** [comment]
Thank you for your help!

**Comment by raven-au** [comment]
> @scruloose I've created #17631, though I have not tested it. If it is possible and you want, please test the PR. Thank you.

Hi, I built systemd with your patch and did some testing.
I'm using a Fedora rpm based in v245.

@scruloose made the ssh key unavailable to duplicate this, the target host key not being present in the root users known hosts file has the same effect and is what I used for testing.

I didn't reproduce the problem before testing with the patch because I have seen similar sshfs mount problems before.

I see that the patch does seem ensure the mount enters the correct state on failure, the journal reports the mount failure and the mount unit status shows "Active: failed (Result: exit-code)" while the automount unit shows "Active: active (waiting)" ready to try again.

**Comment by raven-au** [comment]
I also performed a simple test on what happens with mounts performed outside of systemd for which the proc mounts processing creates mount units.

I used a simple autofs indirect mount map and observed that an automounted mount ended up in the correct state on success:
[raven@localhost ~]$ systemctl status test-Public.mount
● test-Public.mount - /test/Public
     Loaded: loaded (/proc/self/mountinfo)
     Active: active (mounted) since Wed 2020-11-18 17:20:39 AWST; 1min 36s ago
      Where: /test/Public
       What: shadow:/Public

Attempting an automount for an autofs map key that didn't exist also worked correctly but that's because, in this case, no mount is even attempted. I also tried using an autofs map entry that would trigger an actual mount that would fail and again that worked fine with no mount unit created again because no mount actually succeeded so no mount was present in the proc mount table.

So the change here appears to work fine and looks to be robust.

**Comment by poettering** [comment]
So, did i get this right? the mount binary invocation failed, but the actual mount point is registered in the kernel (i.e. appears in /proc/self/mountinfo?)

If so, this is expected behaviour. We will track the process failing, and we'll log about it and track it. But key is: the mount is up, so we show it as active. And that's enough for us, and I think correct behaviour.

**Comment by raven-au** [comment]
> So, did i get this right? the mount binary invocation failed, but the actual mount point is registered in the kernel (i.e. appears in /proc/self/mountinfo?)

Almost, for these sshfs mounts, one way or another, sshfs is invoked.

sshfs performs the fuse mount and then raises an ssh connection to the target host in order to use the established socket to communicate between the host and the local fuse file system.

What has happened in a couple of issues is that the socket connection fails and the fuse mount is then umounted.
It appears this appearing and shortly after disappearing mount entry confuses systemd a bit leaving the unit in an unexpected state.

> 
> If so, this is expected behaviour. We will track the process failing, and we'll log about it and track it. But key is: the mount is up, so we show it as active. And that's enough for us, and I think correct behaviour.

I think that was the complaint, the mount isn't actually up, it failed but that isn't properly reflected in the unit state.

The other complaint (in another related issue) was about the lack of logging so the user knows what's going on but it seems to me that isn't a systemd problem as I'm pretty sure that systemd will log exec'ed mount command output and sshfs must be silent about these failures (haven't actually checked).

**Comment by poettering** [comment]
so if sshfs failed, why did it leave the fuse mount in place? it should just have torn it down again

**Comment by poettering** [comment]
i don't think this deserves the 247 milestone. I am not even sure we should really do anything in systemd about this at all.

**Comment by yuwata** [comment]
> so if sshfs failed, why did it leave the fuse mount in place? it should just have torn it down again

@poettering sshfs does so. Please read https://github.com/systemd/systemd/pull/17631#issuecomment-729489847.

**Comment by yuwata** [comment]
> i don't think this deserves the 247 milestone. I am not even sure we should really do anything in systemd about this at all.

@poettering Could you reconsider this issue and review #17631?
