### ISSUE TITLE
Automount : Set a ban time?

### ISSUE THREAD

**Issue by lebarde** [systemd/systemd#17779]
Hello,
I have a hard drive in a dock and I have set automount to mount it whenever I turn it on.

As described [here](https://stackoverflow.com/questions/65071593/autofs-how-to-set-a-ban-time), I have symlinks that make `ls` long to answer.

In a consequence, I would love to have a way to set a "ban time" for a specific mount, just like a fail2ban service. In that way, if the device has been banned, Systemd doesn't have to check for its availability.

Is that easily feasible? Or can I already do it?
Thanks a lot by advance!

**Comment by poettering** [comment]
I am not sure I get what the issue is supposed to be, and what "banning" is supposed to mean?

You have an automount unit defined which is backed by a non-existing device (i.e. one that is not plugged in), is that correct? And you want any accesses to it to fail instantly? If so, why do you set it up as automount at all?

It appears to me you want the automount to not be active while the device is not plugged in, right?

To me it appears you'd be better served by invoking `systemd-mount --automount=yes` from a udev rule for the matching device. See the example at the end of the man page of `systemd-mount`.

Or am I missing something?

**Comment by poettering** [comment]
Let's close this, due to lack of response, and this appears to be better solved otherwise.
