### ISSUE TITLE
Hardware watchdog does not work if kernel module was not loaded by the time systemd starts

### ISSUE THREAD

**Issue by mamarley** [systemd/systemd#17838]
**systemd version the issue has been seen with**
 > 247.1

**Used distribution**
 > Ubuntu

**Linux kernel version used** (`uname -a`)
 > 5.8, 5.10-rc6

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > systemd hardware watchdog support should begin to operate when kernel module is loaded

**Unexpected behaviour you saw**
 > systemd hardware watchdog support does not operate until running "systemctl daemon-reload" if kernel module for hardware watchdog was not loaded by the time systemd starts

**Steps to reproduce the problem**
 > 
1. Enable hardware watchdog support in systemd (set RuntimeWatchdogSec to some positive value in /etc/systemd/system.conf)  (On a system with a hardware watchdog, of course.  My system uses the iTCO_wdt driver.)
2. Reboot system
3. Execute "lsof /dev/watchdog" and note that no process has the file open
4. Execute "systemctl daemon-reload"
5. Execute "lsof /dev/watchdog" and note that systemd is now using the file

On Ubuntu (and perhaps other distros), the hardware watchdog modules are not loaded by default.  I configured my system to load the module during the boot process, but it loads too late for systemd to detect that the system has a hardware watchdog.  I have to also execute "systemctl daemon-reload" after loading the module during the boot process to actually get systemd to pick up the watchdog.

**Comment by poettering** [comment]
Hmm, so this used to work. We'd regularly retry to reopen the watchdog device. THis was probably broken in c5f8a179a2350717777bdd8ee2a5e04ab0afdbb3 or so.

That said, we probably should change this all so that we listen to udev and can actually make use of any watchdog device popping up that has some udev tag on it, the instant it becomes available.

**Comment by poettering** [comment]
See #17460

**Comment by mamarley** [comment]
Cool, thanks!

**Comment by mamarley** [comment]
I confirmed that the patch (with your suggested changes) fixes the issue, but it has been several months since the author last posted, so it seems the PR may have been abandoned.  Is there anything I can do to move this along?

**Comment by keszybz** [comment]
@mamarley if you fixed up the PR, maybe post your updated version as a new PR.

**Comment by mamarley** [comment]
After another look, it seems I missed the first comment (about getting the actual timeout back from the hardware).  I don't know how to do that, sorry. :(

**Comment by poettering** [comment]
watchdog_set_timeout() returns that in the second param. It's an input + output param: you specify the timeout you want, and it is updated to the timeout you got, which hopefully is close enough to what you asked for.

**Comment by mamarley** [comment]
I get that part, and it seems what the patch does is basically just makes manager_{set|override}_watchdog() pretend that starting the watchdog succeeded even if it didn't, causing the timeout to be set and watchdog_ping() to be called on the appropriate interval.  Since watchdog_ping() opens the watchdog if it isn't already open, that works around the problem.

What I'm not sure of would be the best way to fix it so the actual timeout was read back from the hardware on one of these delayed starts.  One idea I had was to call watchdog_set_timeout() on the normal watchdog interval instead of watchdog_ping() if the watchdog had never been successfully opened.  Is that acceptable?

**Comment by fbuihuu** [comment]
> What I'm not sure of would be the best way to fix it so the actual timeout was read back from the hardware on one of these delayed starts. 

Sorry for resurrecting this but I'm not sure to see why you would want to store the updated timeout (the one  from the HW) in `m->watchdog[]` and `m->overriden_watchdog[]`... especially since it is the case only for one type of watchdog (`WATCHDOG_RUNTIME`) and this is true only if a watchdog device has been opened.

The values stored in the manager object are supposed to be the ones from read from the config files or set via the DBus methods whereas the one from the HW is supposed to be stored in `watchdog_timeout` in src/shared/watchdog.c and this value and only this one is reused by the watchdog helpers (such as `watchdog_ping()`) in the watchdog module.

So the initial patch submitted via https://github.com/systemd/systemd/pull/17460 looks correct to me.

@poettering could you please clarify ?

**Comment by fbuihuu** [comment]
In case someone here is interested I submitted https://github.com/systemd/systemd/pull/20650, which includes a different fix for this issue.
