### ISSUE TITLE
Systemd caches the passphrase for crypted devices (dm-crypt)

### ISSUE THREAD

**Issue by tkn777** [systemd/systemd#17864]
**systemd version the issue has been seen with**
246.6-4

**Used distribution**
Debian bullseye (testing)

**Linux kernel version used** (`uname -a`)
Linux bender 5.9.0-4-amd64 #1 SMP Debian 5.9.11-1 (2020-11-27) x86_64 GNU/Linux

**CPU architecture issue was seen on**
amd64

**Unexpected behaviour you saw**
The passphrase to access a crypted device (dm-crypt) is cached by systemd - as plain text in memory - and there is no way to disable that cache.

=> From my point of view, this is a security problem.
=> At least there must be an option to disable the cache.

**Steps to reproduce the problem**
1. Create (at least) two dm-crypt devices
1. Add them to crypttab
1. Boot the system

**Comment by poettering** [comment]
They are cached in the kernel keyring actually, not by systemd. They are automatically destroyed after a few seconds.

The kernel has the volume keys for your dm-crypt device in memory anyway, otherwise it couldn't decrypt anything.

If you don#t trust the kernel to maintain security keys for you, I don't think Linux is the right OS for you... Anyway, let's close this, as there's nothing to "fix" here.
