### ISSUE TITLE
User automount fails with "Operation not permitted" even if corresponding mount unit works

### ISSUE THREAD

**Issue by scruloose** [systemd/systemd#17886]
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > Debian Bullseye

**Linux kernel version used** (`uname -a`)
 > 5.9.0-3

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > When I have a 'user' mount unit that successfully mounts a FUSE filesystem to a user-owned mountpoint, I expect a corresponding 'user' automount unit to start successfully, enter "waiting" state, and trigger the mount unit on demand, the same way it works in a 'system' mount/automount pair.

**Unexpected behaviour you saw**
 > The 'user' automount unit immediately fails. `journalctl` shows the following:

    <unit-name>.automount: Failed to initialize automounter: Operation not permitted
    <unit-name>.automount: Failed with result 'resources'.
    Failed to set up automount "<Unit Description>"

**Steps to reproduce the problem**
 > Create a 'user' mount unit and corresponding automount. In my case this is an sshfs mount. I have verified that starting the mount unit succeeds and does actually mount the filesystem as expected. After manually ensuring that the filesystem is unmounted and the mount unit is stopped (see issue #17788), start the automount unit. `systemctl --user start <unit-name>.automount` immediately returns "Job failed. See "journalctl -xe" for details." `journalctl` shows the errors given above.

**Comment by poettering** [comment]
Automount units are a privileged subsystem on Linux, unprivileged code cannot use them. That's a design limitation of the kernel APIs. systemd doesn#t add any artificial restrictions. If you want this to work, please work with the kernel community to open this up.

I don't think this is actionable for us. But certainly something to document, see #17916.

**Comment by raven-au** [comment]
As a follow up here's some explanation of why it's the way it is.

> Automount units are a privileged subsystem on Linux, unprivileged code cannot use them. That's a design limitation of the kernel APIs. systemd doesn#t add any artificial restrictions. If you want this to work, please work with the kernel community to open this up.

It's not even only allowing unprivileged mounts for both the autofs mount trigger and the subsequent mount that's triggered by it.

The user space autofs package needs to prevent processes other than the owner, meaning processes in the process group that mounted the direct mount trigger, from changing the directory topology because it requires the mount point directory tree not be altered by other processes in certain cases. And the process that listens for mounts being triggered needs to be a systemd process not a user process (from a common sense POV), so that introduces restrictions on what the owner process group can be.

So I think it would be quite difficult to do but I haven't thought about it enough to know for sure.

> I don't think this is actionable for us. But certainly something to document, see #17916.

Yes, I don't think systemd can be expected to be able to do this.

There may be an alternative approaches that involve using macros in some way but I think the of units for automounts in systemd doesn't lend itself too well to this.

**Comment by scruloose** [comment]
Thanks for the explanation.  I must admit that the underlying implementation details are a bit over my head, but I see that the reasons for this limitation run deeper than I anticipated.

Hopefully using a generator as suggested by @poettering in related issue #17789 will let me achieve the outcome I'm looking for in practice.

**Comment by Mannshoch** [comment]
Sorry if I'm not right here. Im new in working with systemd. 
I landed here while searching for a solution:

My case:
- Working with my Laptop
- mostly but no permanent Internet connection
- a needed sftp and smb directory

At moment every time I use an application which needs this directory I have to check if it is correctly mounted and may have to remount it first. That's also because of standby, a restart, missing internet or other cases.

While surfing the internet most automount solution require to mount as root. (worsest solution). Best solution would be something on user account. And I would prefer a solution with a cache feature like common file syncing tools have. 

But simply I search at moment a solution to allow users to auto mount and auto reconnect every time I have Internet.

**Comment by rektide** [comment]
This shoudl be reopened. This is hard to get right & do well & reasonably. But this is far from impossible to handle. Systemd should 100% absolutely try to make this good.

**Comment by rektide** [comment]
This should be reopened. This is hard to get right & do well & reasonably. But this is far from impossible to handle or do. Systemd should 100% absolutely try to make this good. This would be a colossal improvement for those who rely on user-sided systemd, would do so much to pave a gross annoying difficult cowpath that so many systems/operators/users end up treading over anyways.

**Comment by Mannshoch** [comment]
For the record: I still not have a working solution. Gnome and KDE solutions seems not working if no mount is there but an application request for a file on a shar.
The Problem on Gnome and KDE is also their ignorance of CLI users. 
I would like tho have an easy to use mount on user and not root level and an easy access for application if a mount is currently not there.
I would like haveing a solution with automount if credentials are somewhere stored (keyfile, keyring, keepassxc)
And I would prefer a solution where a User or an app can request for a permanetly sync. So it's fast accessible and accessible even I'm offline. 
Like soliutions like OneDrive and Dropbox serves.

Systemd has a mounting solution, Systemd has a solution wher you could work on userlevel. So it is normal to assume that SystemD solve basic automount on user level. And as in other cases, if you provide a good or better solution like kde and gnome has, there is a chance that your solution will be standard. And I would Prefer a solution from SystemD because you will not forget CLI user.

**Comment by dazoe** [comment]
I too think this is something systemd should handle. If there is an option to configure user mounts then automount should work as well.
