### ISSUE TITLE
Wipe LUKS Disk Encryption Key for Root Disk from RAM during Shutdown to defeat Cold Boot Attacks

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#17887]
**Is your feature request related to a problem? Please describe.**

* https://www.youtube.com/watch?v=JDaicPIgn9U
* https://en.wikipedia.org/wiki/Cold_boot_attack
* https://blog.f-secure.com/cold-boot-attacks/
* https://www.usenix.org/legacy/event/sec08/tech/full_papers/halderman/halderman.pdf

**Describe the solution you'd like**
Run `cryptsetup close` at end of shutdown procedure.

Quote `cryptsetup close` (previously `cryptsetup lukseClose`) man page (bold added):

> close
> Removes the existing mapping <name> and **wipes the key from kernel memory**.

Maybe `cryptsetup close` could be implemented in [`systemd-shutdown`](https://github.com/systemd/systemd/blob/master/src/shutdown/shutdown.c)? Or a script in folder `/lib/systemd/system-shutdown`?

This would not wipe all secrets from RAM to defeat a cold boot attack but at least remove one of the most important secrets, the root disk LUKS encryption key.

**Describe alternatives you've considered**
This issue can probably not be redirected at the Linux kernel. While a generic solution `Wipe RAM to defeat Cold Boot Attacks` (#17242) probably belongs into the kernel, this does not. For the kernel to be able to wipe the memory, encrypted LUKS devices need to be properly closed first. `cryptsetup close` does that.

`/lib/cryptsetup/cryptdisks-functions` does not run `cryptsetup close` on root device.

```
# Removes all mappings in crypttab, except the ones holding the root
# file system or /usr
do_stop() {
```

A related systemd feature request is "cryptsetup luksSuspend (wipes encryption key from kernel) on suspend" (#5794). This feature request is not a duplicate. The other ticket is for wiping the LUKS encryption key on suspend. This ticket is for wiping the LUKS encryption key on shutdown.

**Comment by poettering** [comment]
systemd-cryptsetup@.service instances when stopped detach the relevant volumes (which also erases the key material implicitly).

systemd-shutdown then detaches whatever might be remaining, and the initrd's shutdown hook might finally detach the root fs too and anything it backs. 

Or in other words, we already do what you are asking for.

Not sure what /lib/cryptsetup/cryptdisks-functions is, but that's not a systemd thing. Maybe your distro uses that? 

suspending of the root fs cannot work really easily, since the UI stack and everything  else resides on it. In order to implement something like that there would have to be some second OS around somewhere that takes over the UI, is not backed by encrypted storage, then resumes stuff and returns control to the old OS. But that's very far outside of the systemd scope, and doesn't really fit into how things are generally done.

I am personally not sold about doing things that way. Thing is, there is no need to encrypt the OS anyway, we are talking about Open Source software here after all. i.e. /usr should use dm-verity or dm-integrity, and for that suspending is pointless.

Anyway, the closing of the cryptsetup volumes we already do, twice. Closing hence.

**Comment by adrelanos** [comment]
Avoiding all sidelines, keeping this simple, for my understanding and for the record and please correct me if I am wrong... Summary:

`"cryptsetup close" of root device during shutdown` is already implemented.

**Comment by poettering** [comment]
> `"cryptsetup close" of root device during shutdown` is already implemented.

iff your initrd/distro of choice do so. For the root disk it doesn't matter what systemd does, it matters what the initrd/distro do. hence ping the maintainers of those.

**Comment by adrelanos** [comment]
Debian `cryptsetup`  feature request:
[Wipe LUKS Disk Encryption Key for Root Disk from RAM during Shutdown to defeat Cold Boot Attacks from Initial Ramdisk (initramfs-tools or dracut)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978642)

Debian `dracut`  feature request:
[Wipe LUKS Disk Encryption Key for Root Disk from RAM during Shutdown to defeat Cold Boot Attacks from Dracut Initramfs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978644)

`dracut` upstream feature request:
https://github.com/dracutdevs/dracut/issues/997
