### ISSUE TITLE
Keep killing systemd with SIGSEGV leads to kernel panic

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#17941]
**systemd version the issue has been seen with**
 > systemd-245

**Used distribution**
 > Fedora 32

**Linux kernel version used** (`uname -a`)
 > Linux localhost.localdomain 5.6.6-300.fc32.aarch64

**CPU architecture issue was seen on**
 > aarch64

**Expected behaviour you didn't see**
 > systemd freeze, but no kernel panic

**Unexpected behaviour you saw**
 > systemd freeze and kernel panic

**Steps to reproduce the problem**
 
```shell
for i in `seq 1 10000`; do
    kill -11 1;
    sleep 0.01; # this is necessary.
    echo $i;
done
```

**Comment by Geass-LL** [comment]
In my virtual machine, after running the loop for about 1600 times, the kernel will crash.

**Comment by Geass-LL** [comment]
```c
static void install_crash_handler(void) {
        static const struct sigaction sa = {
                .sa_handler = crash,
                .sa_flags = SA_NODEFER, /* So that we can raise the signal again from the signal handler */
        };
        int r;

        /* We ignore the return value here, since, we don't mind if we
         * cannot set up a crash handler */
        r = sigaction_many(&sa, SIGNALS_CRASH_HANDLER, -1);
        if (r < 0)
                log_debug_errno(r, "I had trouble setting up the crash handler, ignoring: %m");
}
```

Should we delete the `.sa_flags = SA_DODEFER` to block the triggered signal? In my situation, if someone keeps killing systemd with SIGSEGV, the call stack depth may increase to 5000+, which will cause kernel panic. Killing systemd shouldn't make kernel panic, should it?

**Comment by poettering** [comment]
Why does this matter? There are a million ways to crash your machine when you have privs. Why should we bother?

**Comment by Geass-LL** [comment]
I think killing systemd shouldn't make kernel panic. I don't know why `SA_NODEFER` is used here, because everytime PID1 got SIGSEGV (or other signals), it runs to freeze_or_exit_or_reboot() and freeze. There is no way for systemd to recover from these killing  signals,  why we must set `sa_flags` to `SA_NODEFER`?

**Comment by poettering** [comment]
Not handling double segfaults doesn't sound much better than overrunning the stack the stack in an artificial case.

Your case is entirely synthetic. If pid1 segfaults in real life because something is borked, and then segfaults again while handling that, it's entirely ok to handle that again. Either way we are fucked, we can only try to make the best of a fucked situation. But I'd rather do things so that a fucked up situation that has some limited relevance in reality is handled ok'ish rather than do things so that a completely and entirely artificially situation looks a bit prettier...

Anyway, I see nothing to fix here, doing something remotely rasonable on double segfaults is a lot more relevant than people shooting themselves repeatedly in the foot and wondering why you can't walk anymore if you do...

**Comment by Geass-LL** [comment]
Thanks for the explanation, handling double segfaults sounds more rasonable indeed.
