### ISSUE TITLE
systemd-coredump: Failed to get EXE, ignoring: No such process

### ISSUE THREAD

**Issue by abitrolly** [systemd/systemd#17965]
I've lost my GNOME on Wayland at tty2. Now switching to that session with Ctrl-Alt-F2 show a screen with a bunch of ^@^@^@ characters. Looking at `dmesg` I see this.
```
[552165.186438] rfkill: input handler enabled
[552165.608256] systemd-coredump[489753]: Failed to get EXE, ignoring: No such process
[552169.355427] rfkill: input handler disabled
[552177.230624] rfkill: input handler enabled
```
Huh?

Digging further into `journalctl -b` I see this.
```
systemd-coredump[489760]: Process 2833 (Xwayland) of user 1000 dumped core.

       Stack trace of thread 2833:
       #0  0x00007f29917e79d5 raise (libc.so.6 + 0x3d9d5)
       #1  0x00007f29917d08a4 abort (libc.so.6 + 0x268a4)
       #2  0x000056028a36603c n/a (/usr/bin/Xwayland (deleted) + 0x19f03c)
```

**systemd version the issue has been seen with**
```bash
$ sudo systemctl --version
systemd 246 (v246.6-3.fc33)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)
 > Linux blackred 5.9.11-200.fc33.x86_64 #1 SMP Tue Nov 24 18:18:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Restart Wayland after the crash maybe?

**Unexpected behaviour you saw**
 > Text session after switching to the window.

**Steps to reproduce the problem**
 > Don't know.

**Comment by poettering** [comment]
Seem you upgraded xwayland while running, and thus crash collection cannot  work, since the binary to analyze doesn't exist anymore. There's nothing much we can do about it, except logging.

I can't tell you why xwayland crashed, please contact the xwayland devs about htis. Might be related due to the inline upgrade, i.e. xwayland might have problem finding its own resources.

Either way, let's close this here. please raise this with xwayland devs. systemd is just the messenger here.
