### ISSUE TITLE
test-journal-flush randomly(?) fails in CentOS CI (CentOS 7)

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#17963]
```
=== Failed test log ===
--- test-journal-flush begin ---
journal_file_copy_entry failed: Bad message
Assertion 'r >= 0' failed at src/journal/test-journal-flush.c:52, function main(). Aborting.
--- test-journal-flush end ---
Spawning getter /root/systemd/build/journalctl -o export -D /var/tmp/systemd-test-TEST-02-UNITTESTS/root/var/log/journal/8ac58dc170454b6ba7398ed95ce4f40d...
Finishing after writing 61618 entries
Spawning getter /root/systemd/build/journalctl -o export -D /var/tmp/systemd-test-TEST-02-UNITTESTS/root/var/log/journal/remote...
Finishing after writing 0 entries
QEMU test failed
```
See https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-centos7/1272/ for more details.

**Comment by mrc0mmand** [comment]
Hmpf, this is indeed weird. We had the same issue in the Arch Linux jobs (see https://github.com/systemd/systemd/pull/13728#issuecomment-538544765), but I dismissed it as a (nested) KVM issue, so since then the test is being skipped in these runs (https://github.com/systemd/systemd-centos-ci/commit/a632f4f596530fbee7a71644cd98e5ba394fc21a).

It's however quite suspicious that this issue started happening in the CentOS 7 jobs just recently.

**Comment by ddstreet** [comment]
I believe this is the same problem that's been seen in the Ubuntu CI intermittently for a long time, and I spent a few hours over the holiday break looking into it; it looks to me like the cause of this is a corrupt journal file present in the test system. Once you have a journal file that's corrupted in a specific way, test-journal-flush will fail while trying to flush it.

For example in this artifacts tarball:
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-focal-ddstreet-lp1881947/focal/arm64/s/systemd/20210101_182242_ee811@/artifacts.tar.gz

contains a journal file:
artifacts/test-journal-enum-journal/journal/eaf3d39349aa4644a1d3a821e1b33c22/system@0005b7dac334f805-0021aca076ae5c5e.journal~

which is corrupted in such a way to cause test-journal-flush to fail.

For the Ubuntu CI, I'm fairly certain this is happening on the arm64 architecture intermittently because there is some issue that only affects that arch where the instances don't reboot successfully/correctly, so it seems to be intermittently corrupting system journal files (I'll note that I can observe and reproduce the reboot problem on our test/devel cloud arm64 instances, but I don't have direct access to the production cloud instances where the Ubuntu CI runs, so I'm assuming it also has the reboot problem).

**Comment by ddstreet** [comment]
I'm not sure if this really is a 'bug' in systemd, as I think it's behaving correctly when it encounters a corrupt journal file...possibly test-journal-flush should be pre-checking each of the system journal files to make sure they aren't corrupt, before attempting to flush them (and skipping any journal file fails verification)?
