### ISSUE TITLE
Allow disabling systemd-sysv-generator warnings about lack of native unit file

### ISSUE THREAD

**Issue by Simpleton350** [systemd/systemd#18014]
**Is your feature request related to a problem? Please describe.**
Systemd-sysv-generator gradually fills the kernel log with warnings like this:

> SysV service '/etc/init.d/deluged' lacks a native systemd unit file. Automatically generating a unit file for compatibility. Please update package to include a native systemd unit file, in order to make it more safe and robust.

While these warnings are useful, they are repeated after every package update, when presumably a daemon-reload is executed. Over time, the kernel log fills up with them and more important messages may be overlooked.

**Describe the solution you'd like**
There should be a way to disable these warnings completely or have them log only once per boot for each service lacking a unit file.

**Describe alternatives you've considered**
Systemd-analyze could gain a new command to show which services are affected.

**Comment by poettering** [comment]
Maybe just fix the service in question?

This warning exists for a reason: to annoy people enough to do something about it. And it appears to work somewhat, as you posted this issue here. However, please file a bug against the offending package instead, so that they ship a unit file. Such a fix would take an equal amount of work, simplify things, be more future proof, and have an alround better result.

I am sorry, but I am not convinced that adding a config knob for this is a good thing. I think more config knobs need to be carefully introduced since they come with a price. In particular new knobs for legacy features where the problem they shall deal with will go away sooner or later anyway. 

I am sorry, but please contact your package maintainers to ship a unit file instead.

I hope this makes some sense, even if it might be disappointing.

**Comment by corbolais** [comment]
Sorry, controversial attitude of yours. Should tag it `is-kinda-n-issue-of-ours`.

Seeing this for mcelog, pihole-FTL, munin, nbd-server, lsyncd and many more. I'm running out of life-time fixing or reporting this to every single upstream.

A "knob" like "msg repeated X times" looks like a compromise between completely suppressing the offending issues and cluttering logs to such an extend that debugging via dmesg/kernel log becomes infeasible and error-prone.  Instead of having to always `grep -v` it, this "knob" would come in handy.

**Comment by trentbuck** [comment]
Hi, I want to briefly document a related "gotcha" I ran into on Debian 11 bullseye, since (IMO) nothing can be done to improve matters.

1. ``apt install rsyslog``
2. ``apt remove rsyslog``
3. Now you get warnings, because ``/etc/init.d/rsyslog`` still exists, but ``/lib/systemd/service/rsyslog.service`` was removed.
4. To avoid these warnings, purge instead of remove, e.g. ``aptitude purge '~c'``.

**Comment by doggodanubus** [comment]
@Simpleton350 I see the attitude server of redhat hasn't changed. BTW redhat is an anagram for hatred. I'd recommend going with a distribution that does not have systemd and pulseaudio. There are great ones out there. All my Linux virtual servers run a hardened version of Gentoo without systemd. I'm only here because of one proprietary redhat system that the owner of it bought from some integrator cretin. This error is not just at reboot but about ever 15 minutes. It eventually kills the logging. I'm not sure what to tell the customer. They are stuck with this due to all the proprietary licensing they signed up for. Stuff I'd have gotten them for free but still with all the technical support they thought they were going to get. I'll just run a cron job to flush the logs and call it a day since the bug won't be fixed.
