### ISSUE TITLE
[Question] systemd-analyze time

### ISSUE THREAD

**Issue by torvic9** [systemd/systemd#18017]
Hello,
Just a simple question: does `systemd-analyze time` take into account the time needed to uncompress the initrd? Or does it only start measuring the time when it is already unpacked?

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
