### ISSUE TITLE
"optional" libidn2 in systemd-resolved breaks it entirely

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#18078]
**systemd version the issue has been seen with**
 > 247.2

**Used distribution**
 > NixOS unstable

**Linux kernel version used** (`uname -a`)
 > Linux pine 5.10.2 #1-NixOS SMP Mon Dec 21 12:30:08 UTC 2020 aarch64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64-linux, aarch64-linux

NixOS uses rpaths to reason about runtime dependencies. Contrary to other distros, there's no default path that's `dlopen()`'ed, as `/usr/lib` doesn't exist.

When switching to 247.2, we noticed a regression in systemd-resolved (https://github.com/NixOS/nixpkgs/pull/107067#issuecomment-748212367). Apparently we first confused it with https://github.com/systemd/systemd/issues/18025, but we managed to reproduce resolution failures without `DNSOverHTTPS`.

There were some reports about it [not being able to find `libidn2` (at runtime)](https://github.com/NixOS/nixpkgs/pull/107067#issuecomment-750778494), and together with me seeing the following logs while trying to reproduce it locally:

```
Dec 24 16:43:10 pine systemd-resolved[689]: Failed to escape hostname: Invalid argument
Dec 24 16:43:10 pine systemd-resolved[689]: Defaulting to hostname 'linux'.
```

… this did ring a bell.

Apparently, https://github.com/systemd/systemd/pull/17292 wasn't correct, and systemd-resolved always needs libidn2 to properly work. This PR should probably be reverted.

**Comment by poettering** [comment]
So you don't have neither libidn2 nor libidn installed, but you enabled it at build time, is that correct?

**Comment by flokli** [comment]
`systemd` was compiled with libidn available in the build closure, but `dlopen()` doesn't find it on the installed system.

In RPM/DEB speech, we didn't install the "recommended" libidn2 dependency.

**Comment by bluca** [comment]
No need to revert, the librari is meant to be optional. There's a small typo that I should have caught while reviewing, but I missed it. Sorry! Fix in https://github.com/systemd/systemd/pull/18093

(note that by default resolved links to libgnutls which links to libidn. Also common tools like apt link to it. We didn't see it before because it's quite uncommon to not have it on a system, as you need both a build of systemd without gnutls and no other system utilities that pull it in).
