### ISSUE TITLE
Unknown key name 'DBusActivatable'

### ISSUE THREAD

**Issue by ckujau** [systemd/systemd#18153]
**systemd version the issue has been seen with**
 > systemd-246.7-2.fc33.x86_64

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -r`)
 > 5.9.16-200.fc33.x86_64

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > --

**Unexpected behaviour you saw**
 > systemd-xdg-autostart-generator[35043]: /etc/xdg/autostart/org.freedesktop.problems.applet.desktop:92: Unknown key name 'DBusActivatable' in section 'Desktop Entry', igoring.

**Steps to reproduce the problem**
 > Boot system

This had been [reported for an entirely different project](https://github.com/phw/peek/issues/393 "DbusActivatable is not a valid key for a desktop file") but appears to be true for `systemd` itself. [conf-parser.c](https://github.com/systemd/systemd/blob/master/src/shared/conf-parser.c#L141) warns about unknown non-extension fields, but [the spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) lists `DBusActivatable` as a valid key. The `.desktop` file here is provided by [abrt](https://github.com/abrt/abrt/blob/master/src/applet/org.freedesktop.problems.applet.desktop.in) and hasn't changed since 2018, so I'm not entirely sure why I only see this warning now from `systemd-xdg-autostart-generator`, could this be related to commit  [ddeb3f5d4b](https://github.com/systemd/systemd/commit/ddeb3f5d4b7ce67c23fde0ad149fb06b29a92f2a "shared/conf-parser: allow sections to be silently ignored with new -Section syntax") ("shared/conf-parser: allow sections to be silently ignored with new -Section syntax")?

**Comment by ckujau** [comment]
Or, should `DBusActivatable` be added to [xdg-autostart-service.c](https://github.com/lqb/systemd/blob/master/src/xdg-autostart-generator/xdg-autostart-service.c#L321), similar to commit [ab2bd5e2d](https://github.com/lqb/systemd/commit/ab2bd5e2dd4ac1eb31993acc799417a25f740853 "xdg-autostart: Ignore more common XDG Desktop Entry fields") ("xdg-autostart: Ignore more common XDG Desktop Entry fields")?

**Comment by benzea** [comment]
Right, yeah, two possible solutions, both are pretty straight forward:
 1. Just ignore the key
 2. Generate an `ExecStart=` line that uses busctl to activate the service

**Comment by poettering** [comment]
Given that the XDG desktop spec talks about that if DBusActivatable=true is set Exec= still "should" be specified I figure Exec= is actually optional if the bool is set, which suggests not ignoring DBusActivatable.

My guess is that we should use Exec= if set (since systemd is the service manager after all, why hand this job over to anyone else). And if not set we should probably do the busctl thing. However busctl probably needs to be tweaked a bit, and probably gain a new command "activate" or so, which not only activates a service but also blocks until the service goes away again. Otherwise our service wouldn't track the service runtime properly anymore...

That said, maybe we can wait with patching "busctl" like this until we actually encounter some real-life .desktop file of relevance that does not set Exec= but does set DBusActivatable=true.

Hence, my suggestion: ignore the key, but maybe generate a brief log_debug() message explaining that we'll ignore the line and use Exec= because we are the service manager, ffs.

**Comment by benzea** [comment]
So, ignoring the key is trivial.

I actually looked into this earlier to day, and using busctl is completely feasible (no new command needed, we need to poke the application directly anyway). I would have submitted an MR already, but failed to get the test in line and decided that I really should add more tests to also check the output routine a bit.

**Comment by benzea** [comment]
Bus activation is more complicated, but it would be kind of nice if an application that provides its own .service will will actually start as that.

Though, then it might as well just also handle autostart using systemd …

**Comment by YHNdnzj** [comment]
Fixed by https://github.com/systemd/systemd/pull/18695.
