### ISSUE TITLE
Better notify user about full disk

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#18239]
Using Debian sid/unstable with *systemd* 247.2-4 and F2FS formatted root partition, the user downloaded pictures and movie archives, and extracted them filling the root directory (`/home` is *not* a separate partition). As a result, the system did not start GDM (and several other services like systemd-timesyncd), and it wasn’t clear, that it’s due to a full root partition. Switching to tty2 worked, and the user could log in there.

Is there a way to better notify the user about this condition?

**Comment by zdzichu** [comment]
Why do you think this is a systemd bug?

**Comment by paulmenzel** [comment]
Because systemd is the system manager.

**Comment by poettering** [comment]
well, i am sure the involved software all logged about it, no?

I mean it's the general problem that serious events are typically logged about, but not surfaced to the user in a nice way. systemd isn't a UI though. 

Might be something to report against gdm, so that they update their service to do OnFailure=… in their unit, spawning some tool that maybe brings a user friendly warning about this to screen via plymouth or so.

In the long run: we had discussions in the past, if systemd should maybe have a small component that is triggered whenever a log message at emergency level is generated by a privileged daemon. And when that happens, isolate to some special state where information about this is brought to screen, in a reasonably pretty way (maybe with a QR code next to it to scan off the issue from screen) and the system otherwise freezes (and maybe turns off or reboots after some time). i'd argue this is the right course of action in cases like this. I mean, it might sounds a bit drastic, becuase in this specific case thigns are recoverable by a knowledgeable person with admin privs, but if then again, it's a mistake by the admin to even allow this to happen, i.e. serve /var from the same pool as /home without quota or so... But quite frankly i wouldn't hold my breath on this.

(This reminds me of another feature request: that we should maybe freeze boot/turn off again with a friendly message when running from battery and very little remaining power, so that people plug in things before booting up fully)

**Comment by poettering** [comment]
any way, i fail to see why "disk full" was in any way special. The issue is that gdm failed to start, and that some fallback logic for that should be in place if that happens, that has a high chance of succeeding (i.e. doesn't require /var or so to work) and just brings a "you are fucked" dialog to screen. I'd consider this a gdm issue for now.

**Comment by paulmenzel** [comment]
Thank you. Filed as https://gitlab.gnome.org/GNOME/gdm/-/issues/669.

**Comment by mbiebl** [comment]
Btw, there is already https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/housekeeping/gsd-disk-space.c

**Comment by poettering** [comment]
@mbiebl that's good to have, but unfortunately too late, if one cannot even log in...

I do wonder though why gdm needs storage outside of volatile memory at all, i.e. it shouldn't need persistancy. In an ideal world it should just mount a tmpfs as home dir and then unmount it whenever it goes through a cycle.

**Comment by mbiebl** [comment]
I suspect it failed to start up because /tmp was full. I vaguely remember a similar problem like this in the past.

**Comment by poettering** [comment]
/tmp should be a tmpfs, really. It shouldn't be served from the same pool as /home or /var

**Comment by mbiebl** [comment]
That doesn't mean it can't run full. It actually makes it more likely to run full.

**Comment by poettering** [comment]
is that so

**Comment by mbiebl** [comment]
Given that typical SSD/hard disk sizes are still at least one order of magnitude larger then RAM size (half or RAM), I'd say so, yes.
Anyway, my main point was that /tmp-on-tmpfs does not really help here (it is interesting for other reasons, certainly).

**Comment by paulmenzel** [comment]
Wow, I assumed that `/tmp` was mounted as tmpfs the whole time, but it is not on two Debian systems I checked:

    $ findmnt /tmp
    $

Did Debian make a decision on deviating from that “upstream recommended” setting?

**Comment by paulmenzel** [comment]
> Anyway, my main point was that /tmp-on-tmpfs does not really help here (it is interesting for other reasons, certainly).

Sorry, can you elaborate. During boot up, even a 2 GB system should have enough space for a tmpfs, shouldn’t it? Sorry for being ignorant.

**Comment by mbiebl** [comment]
Whether you have /tmp-on-tmpfs or /tmp which is cleaned on boot makes no practical difference.

**Comment by poettering** [comment]
> Given that typical SSD/hard disk sizes are still at least one order of magnitude larger then RAM size (half or RAM), I'd say so, yes.

/tmp is for small stuff + /var/tmp for large stuff.

So it shouldn't really matter. Given that many distros default to /tmp as tmpfs most apps that get this wrong are fixed quickly.

> Anyway, my main point was that /tmp-on-tmpfs does not really help here (it is interesting for other reasons, certainly).

It doesn't? It means allocation is from a different pool than /home or /var, and thus if the those to run full /tmp does not.
