### ISSUE TITLE
Journald - Failed to iterate through journal: Bad message Failed to get realtime timestamp: Bad messag

### ISSUE THREAD

**Issue by rvnsource** [systemd/systemd#18253]
Hi,

Under heavy logs entering the systemd-journald, journalctl can exit with one of the following error messages:

Failed to iterate through journal: Bad message
Failed to get realtime timestamp: Bad message
Failed to get monotonic timestamp: Bad message

The systemd is at version 243

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.

**Comment by rvnsource** [comment]
Thanks for the answer.
Not able to get what is feature tracker of systemd.

I require commit ID of the fix in upstream. Thanks.

**Comment by rvnsource** [comment]
> [Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.
> 
> https://github.com/systemd/systemd/releases
> 
> For support for older versions please contact your distribution instead.
> 
> In order to keep frustration at a minimum the submission forum tried to make this all very clear.

What is the commit ID of this fix.
