### ISSUE TITLE
Assume --user when called by non-root

### ISSUE THREAD

**Issue by langdon** [systemd/systemd#18419]
**Is your feature request related to a problem? Please describe.**
typing "--user" when using systemctl for user services seems like a waste of keystrokes when systemctl already knows I am not root.

**Describe the solution you'd like**
I think it would be great if "--user" was assumed if a non-root user called it. I think you still have the flag if i want to run a "user service" as root (for some odd reason) or if I want to be explicit. However, there is no need for me to specify it. If you think people don't know about --user and think they are operating as root, you could add a warning about the assumption.

**Comment by floppym** [comment]
It's very common to run `systemctl status` as a non-root user, and people may expect that to display information about system services (not user services).

**Comment by floppym** [comment]
Also, if the polkit policy allows it, non-root users may perform other actions on system services.

**Comment by poettering** [comment]
I run "systemctl" all the time to inspect the system state. I'd be very annyoed if it suddenly would show me the per user list instead.

moreover as @floppym also said, there's all kinds of policykit hook-up which allows unpriv clients to issue privileged operation.

most importantly though: it's now how it is, and changing this would be massive compat breakage. Since OS developers try to push people to do their admin work unprivieleged and only issue privileged work when really required changing the defaults here would not only break all kinds of scripts, but also admin workflows.

Hence, sorry, but I don't think we can change that, nor do I even think changing it would be desirable. 

Hope this makes any sence?

Closing.

**Comment by langdon** [comment]
Understood, particularly the "it works this way now." Still don't agree on the other arguments though :)

**Comment by keszybz** [comment]
I had a related thought today: shouldn't `systemd` (not ctl), refuse to execute when called without `--user` argument? Right now it tries to launch itself as a user manager and fails on some cgroup permission stuff. `systemd --user` is run execlusively from `user@.service` and there we call it with `--user`. So calling plain `systemd` without any arguments as non-pid1 is almost always a mistake.
