### ISSUE TITLE
How to express "ip route add local 0.0.0.0/0 dev lo table 100" in systemd-networkd?

### ISSUE THREAD

**Issue by notcome** [systemd/systemd#18503]
My initial attempt is

```ini
[Match]
Name = lo

[Route]
Type = local
Destination = 0.0.0.0/0
Table = 100
```

but this route does not get added. In fact, `ip route show table 100` gives:

```
Error: ipv4: FIB table does not exist.
Dump terminated
```

I also tried to add a `Gateway = 127.0.0.1` but it didn't help.

Many thanks!

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
