### ISSUE TITLE
RFE: support upcoming libcryptsetup plug-in interface for our FIDO2/TPM2/PKCS#11 support

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#18510]
Let's support the upcoming libcryptsetup plug-in interface and provide our FIDO2/TPM2/PKCS#11 unlocking support directly in the main cryptsetup tool.

(As discussed elsewhere with @oniko + @mbroz)

**Comment by oniko** [comment]
I've hacked **highly experimental** plugin just for systemd-tpm2 luks2 token. It depends on yet unreleased cryptsetup 2.4.0 (current master snapshot works: https://gitlab.com/cryptsetup/cryptsetup/-/commit/78797ae078604f268e6b1f4af5ad2121f9dc0ae5). Just compile with additional **--enable-external-tokens** option.

The enrolled device may be unlocked either by systemd-cryptsetup or directly by cryptsetup tools. cryptsetup does not pass any pcr search mask or specific tpm2 device yet, so defaults only. systemd-cryptsetup works with search mask set or specific tpm2 device.

Basically I just moved and slightly modified code in src/cryptsetup/cryptsetup.c (and cryptsetup-tpm2.c).

What do you think about it? It's sort of chicken&egg deadlock. I'd like to hear if changes in libcryptsetup API are good enough for this to proceed and we don't want to make upstream cryptsetup 2.4.0 release unless we're sure this may proceed or not.

Few questions specific only to luks2 enrollments:
- It seemed to me that it should work without need to pass tpm2 key via files, right? aka unseal luks2 passphrase from tpm2 unlocked by tpm2 key stored in file (unlike other types: luks1, plain,bitlk...)?
- what is search_pcr_mask good for? Should not we just try based on what is stored in LUKS2 token?
- should we identify tpm2 device in LUKS2 token metadata? So that it's not required to pass specific tpm2 device when more than one is available?

TODO:
- waiting for tpm2 device to appear is currently broken (libcryptsetup returns -EAGAIN when plugin expects additional 'PIN' data and it's missing)

**Comment by oniko** [comment]
Hi,

I've fixed some issues in libcryptsetup (the systemd-tpm2 plugin still requires current master branch: https://gitlab.com/cryptsetup/cryptsetup build).

Most notably: event based waiting for tpm2 HW initialization now works properly with systemd-tpm2 plugin. Any thoughts on this approach?

**Comment by keszybz** [comment]
Implemented in #19059.

**Comment by oniko** [comment]
Hi @keszybz,

please, since you have closed this...Please also look at (merge or comment) on #19797. So that it does not deviate much from tpm2 plugin.

**Comment by oniko** [comment]
@keszybz  ah...ti has conflicts now...nvm, I'm going to fix it asap....
