### ISSUE TITLE
systemd name has become ambiguous

### ISSUE THREAD

**Issue by vcaputo** [systemd/systemd#1858]
Today the word _systemd_ tends to be used to refer to the systemd _project_ and _daemon_ interchangeably.  It's an unfortunate situation, but it seems like the systemd _daemon_ should be renamed for clarity and consistency sake.

There are already systemd-networkd, systemd-journald, systemd-resolved, then the oddball systemd.

I'd like to propose renaming the systemd daemon to systemd-daemon, (consistent with dbus-daemon), or systemd-managerd or systemd-initd.  This simple change would reduce confusion in discussions involving the systemd project and the systemd daemon.  I feel many people appear to criticize the systemd _daemon_ in public discussions when in reality they are taking issue with the systemd _project_, which should be more clearly distinguished, considering the scope of the project vs. the daemon.

**Comment by utezduyar** [comment]
I have seen usage of "PID 1" for what you are referring as systemd "daemon" quite a lot.

**Comment by alban** [comment]
I like the name `systemd-initd`. But it does not capture `systemd --user`, which does not start as pid 1.

**Comment by poettering** [comment]
Well, I see what you mean, but I am not a big fan of such games of bike-shedding I must say. Yes, it's confusing, but then again, the name is kind established already, it is somewhat user interface and it is after all the main and primary part of the project, hence I am not too keen to changing this now, nor do I think that it's really a misnomer.

Yes, it requires everybody to be more precise from time to time, and clarify "systemd - the project" vs. "systemd - the daemon" when they talk about it, but somehow I doubt this problem would really go away if we'd call the thing "systemd-daemon", since during normal conversation people would still suppress the suffix when talking and thus create the confusion again.

Also, "systemd-daemon" is a bit like talking about an "LCD display", which after all is redundant, since the "LCD" already contains "display" in the D... Hence, "systemd-daemon" would be the "system daemon daemon" ;-)

In my talk and in the sources, we usually refer to the main part of systemd as "PID 1", the "daemon", the "manager" or the "core".  All of these names are suboptimal I think, as "PID 1" is a misnomer, as it is also used for --user. "Daemon" is not accurate, as pretty much half of the binaries in systemd would qualify as "daemon". Similar is "manager". "core" might still be the best...

But either way, I doubt we really should rename this now, even though I acknowledge the issue you raise.

Sorry!
