### ISSUE TITLE
Man page has no description of required permissions to call/use systemd-inhibit

### ISSUE THREAD

**Issue by amarao** [systemd/systemd#18619]
If systemd-inhibit is called by non-root user it refuses with message:
```
systemd-inhibit /bin/bash
Failed to inhibit: Access denied
```

Man page for systemd-inhibit provides no information on required permissions to use it.

**Comment by poettering** [comment]
we don't duplicate the policies in the man pages, generally because people can reconfigure them any way they want, and we just provide defaults. They are documented in detail in the policy file itself though:

/usr/share/polkit-1/actions/org.freedesktop.login1.policy

Yupp, policykit XML is hard to grok, policykit has some tools to make things easier to grok, but htey aren't great:

```
pkaction -va org.freedesktop.login1.inhibit-block-shutdown
```

Improvements to those should really come from the PK project though, we are just consumers of their APIs on that.


Hope that makes some sense.

Hence, closing.

**Comment by amarao** [comment]
Can systemd be a little more verbose for who had rejected the request? From user perspective it's really hard to guess that this permission is controlled by policykit via dbus. (I understand that there is a 'developer guide', but for an operator, there is `systemd-inhibit` binary and it's man page, and that's all).
