### ISSUE TITLE
Add default udev rules and group for sgx_* dev nodes for new SGX support in kernel 5.11

### ISSUE THREAD

**Issue by haitaohuang** [systemd/systemd#18669]
**Is your feature request related to a problem? Please describe.**

Kernel 5.11 now exposes two sgx dev nodes: sgx_enclave and sgx_provision and only allow root user to access them by default.

Every process hosting SGX enclaves would need RW to sgx_enclave. Processes hosting specialized "provisioning" enclaves need RW access to sgx_provision additionally.

Please refer to [this specific kernel patch](https://patchwork.kernel.org/project/intel-sgx/patch/20201112220135.165028-16-jarkko@kernel.org/) for background on sgx_provision

This is to propose default settings with udev rules for both sgx dev nodes and a special group to limit access to sgx_provision

**Describe the solution you'd like**

Add a new "sgx_prv" group in "hardware access groups" in [basic.conf.in file under sysusers](https://github.com/systemd/systemd/blob/main/sysusers.d/basic.conf.in):

```
# Hardware access groups
...
sgx_prv   -     -            -
```
Add a rules file with following content in [default udev rules](https://github.com/systemd/systemd/tree/master/rules.d):

```
# 90-sgx.rules
SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
SUBSYSTEM=="misc",KERNEL=="sgx_provision",GROUP="sgx_prv",MODE="0660",SYMLINK+="sgx/provision"
```

**Describe alternatives you've considered**
An alternative and current practice is for SGX runtime packages to include and install the similar rules and create the user group. But different runtime package may choose different names of group and create redundant rules. That's not efficient and causes unnecessary confusion on user part.

**The systemd version you checked that didn't have the feature you are asking for**

All current versions of systemd do not have this feature as SGX support in kernel is new in 5.11

**Comment by yuwata** [comment]
Maybe related to #15593?

**Comment by poettering** [comment]
Is there going to be a package that is highly likely installed on all systems where userspace wants to use SGX? for AMD SEV there's apparently sevctl. If there's a matching package for SGX I think the rule should be shipped there, like in the AMD case

**Comment by haitaohuang** [comment]
There is no such package. Different runtime implementations can have their own wrapper of ioctl for the dev nodes and they can have different provisioning.

**Comment by npmccallum** [comment]
I suspect the architectural enclaves are the right place for this.

**Comment by haitaohuang** [comment]
For sgx_prv group and rules for sgx_provision, it may make sense we put them in a package with Intel signed PCEs. People only need them for provisioning and remote attestation. And they need PCE at least for those usages.

But sgx_enclave is needed for everyone. Currently Intel SGX PSW has abstraction package [libsgx-enclave-common](https://github.com/intel/linux-sgx/tree/master/psw/enclave_common). But other runtime may have different implementation and may not use it. So for apps developed using those runtime, they would need separate rules to set the permissions for sgx_enclave.

**Comment by woju** [comment]
Hi, on behalf of Graphene project (https://github.com/oscarlab/graphene, https://graphene.rtfd.io/):
- Graphene uses `/dev/sgx_enclave` directly.
- Currently Graphene doesn't touch `/dev/sgx_provision`. For some cases, when this device is needed (not always), we defer to `aesmd` daemon which depends on `libsgx-enclave-common` (this is so called "out-of-proc" attestation).
- In the future we might be forced to do "in-proc" attestation and `open("/dev/sgx_provision")` ourselves. In that case we'd probably use DCAP SDK and depend on `libsgx-enclave-common` directly.
- For the in-kernel driver (upstreamed since 5.11), which this bug concerns, we suggest in documentation that user adjusts permissions and/or udev rules, but don't install the file directly (https://graphene.readthedocs.io/en/latest/sgx-intro.html#linux-kernel-drivers). Our example includes a rule for `/dev/sgx_provision` for completeness, in case it would be needed in the future.
- We don't install udev rules automatically, because Graphene also supports two out-of-tree SGX drivers: so called "OOT" or SDK driver, and "DCAP" driver. Both of those non-upstream drivers don't need additional udev rules: OOT driver is by default 0666 (https://github.com/intel/linux-sgx-driver/blob/0373e2e8b96d9a261657b7657cb514f003f67094/sgx_main.c#L164-L169) and DCAP driver supplies it's own udev rules (https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/30fac05232e13eab72c425a7788fafa5a46b3247/driver/linux/10-sgx.rules).

So we would be grateful from upstream udev rules for `/dev/sgx_enclave` and wouldn't mind if rules for `/dev/sgx_provision` would be included, though we also woudn't mind if they weren't included.

For reference, our discussion: https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0

Cc: @dimakuv @mkow

**Comment by haitaohuang** [comment]
Thanks to all for the comments.

I discussed with Intel SGX SDK/PSW team and we will put the rules for sgx_provision and sgx_prv user group in libsgx-ae-pce, which is a package needed for any app requiring remote attestation (main usage for sgx_provision access).

All other 3rd party packages hosting apps that need access /dev/sgx_provision should declare dependency on libsgx-ae-pce, and ensure their apps run with an uid in sgx_prv. Alternatively in highly unlikely scenario that an enclave just need access the SGX provisioning bit (non-remote-attestation usage), the enclave hosting package can  setup the access rules itself (or still just declare dependency to libsgx-ae-pce anyway).
 
For sgx_enclave rules, each app/enclave package can setup on its own as commented above. Or they can declare dependency on libsgx-enclave-common

**Comment by jethrogb** [comment]
> For sgx_enclave rules, each app/enclave package can setup on its own as commented above. Or they can declare dependency on libsgx-enclave-common

“setup on its own as commented above” can you clarify this? I've read the thread multiple times but I don't see any discussion on this? Your proposal for prv seems fine but I think /dev/sgx_enclave should be available generally.

**Comment by haitaohuang** [comment]
I may have misinterpreted comments by @woju. My understanding is that packages needing access to /dev/sgx_enclave would just set the permission flags of /dev/sgx_enclave to 666 during installation done by an admin.  A default rule would be more consistent and convenient, but it would turn on those bits even without any user needing them.   Would like community feedback on this.

**Comment by woju** [comment]
> [...] packages needing access to /dev/sgx_enclave would just set the permission flags of /dev/sgx_enclave to 666 during installation done by an admin.

The problem is, `MODE="0666"` isn't a sane default for packagers, because admins might not want to allow running enclaves to all users (for various reasons). So packagers would most likely supply `MODE="0660",GROUP="app1"` rule, and admins would just add users to the group when they'd need to access the SGX device. This is a common approach to many different permissions, from `dialup` to `wireshark`. But then there will be a problem when more than one application that would install such rules, because those rules might not be compatible (e.g. `GROUP="app2"`). So I think it would be better to have one canonical group and rule supplied by systemd/udev upstream.

I don't know if this group might be the same as the group used for other TEEs.

**Comment by haitaohuang** [comment]
Just want to add that it's also possible to use setfacl to gain access.

**Comment by poettering** [comment]
Everyone here, could you please have a look at #18944 and review?
