### ISSUE TITLE
systemd-sleep trigger suspend after boot due to wrong LID initial status

### ISSUE THREAD

**Issue by aaronlu** [systemd/systemd#1874]
The LID initial status after boot on Surface 3 is close, which causes the system to enter system suspend at some random point after system is booted. Unfortunately, it's not easy, if not impossible, to fix this from kernel side, see here:
https://bugzilla.kernel.org/show_bug.cgi?id=106941

I wonder if it is possible to fix this in systemd? so that the system suspend is only triggered after systemd received an event and the LID status is close as suggested in the kernel bugzilla page, instead of just checking the LID status?

BTW, I'm not entirely sure the problem is due to systemd-sleep, I just added a debug print in kernel and found that the process that calls enter_state(which is the kernel entry point of the system suspend) is systemd-sleep. And if I set HandleLidSwitch to ignore, the problem is gone so I guess it is systemd-sleep that triggered the system suspend once it found out the LID status is close.

**Comment by poettering** [comment]
We explicitly made sure to immediatelly suspend whenever the lid is reported closed, so that we can deal nicely with devices that are booted up with the lid closed (which can happen easily with devices that have their power button on the outside of the devices, such as the Lenovo Yoga devices, that people put in their backpacks). In such a case we want to make sure the device suspends immediately and doesn't stay on forever, burning CPU.

In general: suspending in logind is generally level-triggered not edge-triggered, since we allow clients to take "suspend inhibitors" that might delay suspending if they wish, but we really want to act on the lid later on as soon as all inhibitors are released.

It's not uncommon that firmware is borked, but usually it's the kernel that works around it, and systemd is really not the right place for it. Specifically, it appears as if the kernel should add a quirk that will consider the lid opened until the first lid event arrives on Surface devices

**Comment by zetalog** [comment]
In the above bug link.

We can see there is only Notify() for the close event, for the "open" event, no Notification will be sent to the LID device:
            Method (_E4C, 0, Serialized)  // _Exx: Edge-Triggered GPE
            {
                If (LEqual (HELD, One))
                {
                    Store (One, ^^LID.LIDB)
                }
                Else
                {
                    Store (Zero, ^^LID.LIDB)
                    Notify (LID, 0x80)
                }

```
            Notify (^^PCI0.SPI1.NTRG, One)
        }
```

I don't know why the workaround should be put into the ACPI lid device driver.
It looks like that "ACPI LID" device only ensures:
1. When OSPM receives "LID status change" notification, the current status can be ensured by the _LID control method.
2. BIOS only may only trigger "LID close" event.

Thanks and best regards
-Lv

**Comment by zetalog** [comment]
This bug https://bugzilla.kernel.org/show_bug.cgi?id=89211 implies that:
When and only when "LID status change" event arrives, the result of _LID is expected to be correct.

The bug https://bugzilla.kernel.org/show_bug.cgi?id=106941 implies that:
BIOS may not generate "LID status change" event for the "LID open" cause.

We also noticed that after resuming from S3, there might not be any GPE/EC IRQs related to the LID.
BIOS simply jumps to the waking vector address and such IRQs may have already been handled by BIOS and thus won't be reported to the OS.

Thanks
-Lv
