### ISSUE TITLE
resolvectl query says DNS was used when it was actually using /etc/hosts

### ISSUE THREAD

**Issue by squarebracket** [systemd/systemd#18752]
**systemd version the issue has been seen with**
> systemd 246 (v246.7-2.fc33)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)

 > `Linux goliath.local 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
> A resolution message that referenced a "static" lookup from `/etc/hosts`

**Unexpected behaviour you saw**
> A resolution message that claimed the lookup was acquired via DNS

**Steps to reproduce the problem**
> 1. Add a hostname entry to `/etc/hosts`
> 2. Run `resolvectl query <hostname>`

**Additional program output to the terminal or log subsystem illustrating the issue**

```
myhost: 192.168.1.237

-- Information acquired via protocol DNS in 317us.
-- Data is authenticated: yes
```

This seems very strange to me. It's very much _not_ using DNS to look up that hostname, it is completely bypassing DNS servers. Perhaps an `/etc/hosts` protocol would make sense, if that is possible?

**Comment by poettering** [comment]
Well, so the idea, that synthesis is orthogonal to protocol choice. i.e. if we synthesize foo.local (because "foo" is the local hostname) then it's still an mDNS name, and thus reported to be mDNS. Similar for LLMNR.

I think this becomes a lot easier to grok with 5c1790d1cec785951f16addb257bbf13d594e02b which will show up in the coming release: with that we'll clearly say if a record is synhesized, or whether it came from the network or cached.

Hence, closing since 5c1790d1cec785951f16addb257bbf13d594e02b fixes this.

**Comment by squarebracket** [comment]
Ah, great, that's a reasonable way of approaching things. Thank you.
