### ISSUE TITLE
journald exist

### ISSUE THREAD

**Issue by rvnsource** [systemd/systemd#18787]
Hi,

Under heavy logs entering the systemd-journald, journalctl can exit with one of the following error messages:

Failed to iterate through journal: Bad message
Failed to get realtime timestamp: Bad message
Failed to get monotonic timestamp: Bad message

The systemd is at version 243

**Comment by poettering** [comment]
[Canned reply follows] When submitting a GitHub issue, please fill in the submission form you find in the issue creation page, i.e. provide the requested details, such as distribution and systemd versions. We ask you these details to keep frustration at a minimum, both for us, and for you. If you don't provide this information it makes things needlessly difficult to help you.

Also, please keep in mind: this is a bug and feature request tracker only. If you have a support question, i.e. wonder how to use a feature, or can't figure out how to do something best, please use a different forum, such as the systemd mailing list. Also, do not file bug reports unless you can reproduce the issue with one of the two most recently released *upstream* version of systemd. For everything older, please contact your downstream distribution instead.

Thank you for understanding!

[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
