### ISSUE TITLE
Automatic start of nspawn containers does not work with virtual bridges

### ISSUE THREAD

**Issue by resdigita** [systemd/systemd#18793]
**systemd version the issue has been seen with**
 > 2.46

**Used distribution**
 > Fedora 33

**Linux kernel version used** (`uname -a`)

 > `5.10.16`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 >  After booting, containers should automatically start. Containers are all "systemctl enable ..."ed 

**Unexpected behaviour you saw**
 > spawn container don't start after (re-)boot

Error message

```
 [... ~]# systemctl  status  systemd-nspawn@camena 
● systemd-nspawn@camena.service - Container camena
     Loaded: loaded (/usr/lib/systemd/system/systemd-nspawn@.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2021-02-25 08:12:32 CET; 1min 33s ago
       Docs: man:systemd-nspawn(1)
    Process: 771 ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=camena (code=exited, stat>
   Main PID: 771 (code=exited, status=1/FAILURE)
     Status: "Terminating..."
      Error: 19 (Kein passendes Gerät gefunden)
        CPU: 29ms

... systemd[1]: Starting Container camena...
... systemd-nspawn[771]: Failed to add interface vb-camena to bridge vbr6s0: No such device
... systemd-nspawn[784]: Parent died too early
... systemd[1]: systemd-nspawn@camena.service: Main process exited, code=exited, status=1/FAILURE
... systemd[1]: systemd-nspawn@camena.service: Failed with result 'exit-code'.
... systemd[1]: Failed to start Container camena.

```
Instead you have to manually start each container using systemctl start systemd-nspawn@<container> which works without issues.

**Steps to reproduce the problem**
 > 
Our servers use an internal virtual bridge for protected communication between 
spawn containers and with the host

1. Create a virtual bridge connected to an internal physical interface using NetworkManager
```
[...]# nmcli dev 
DEVICE  TYPE      STATE            CONNECTION 
enp4s0  ethernet  verbunden        enp4s0     
vbr6s0  bridge    verbunden        vbr6s0     
enp6s0  ethernet  verbunden        enp6s0
```   
2. Create container using the bridge as a second interface for internal use 
and "systemctl enable ..." the container
3. reboot

**Additional program output to the terminal or log subsystem illustrating the issue**

```
. 
…
```

**Comment by poettering** [comment]
looks like a bug in NM? they apparently don't create the bridges you configured before telling the service manager that their initialization is complete. i.e. systemd-nspawn@.service is ordered after network.target, and NetworkManager is ordered before that. So this should theoretically order things properly:

1. first NM sets up the bridge, tells systemd its ready
2. this means network.target is reached
3. which means nspawn can be started

but it appears NM is not actually delaying ready notification until the bridge device is created but already returns earlier than that.

@thom311 any chance NM can give the guarantee that synthetic network devices that do not require on any backing hw to be available before they can be created are created before NM tells the service manager it is ready?

**Comment by poettering** [comment]
I posed PR #18800 which extends the docs on network.target, hopefully making clear what NM should do there I think.

**Comment by thom311** [comment]
I am quite skeptical. My biggest concern is that this will delay boot for everybody and that it's still ill-defined.

For NetworkManager, `network.target` means that the well-known D-Bus name was acquired. That this point, almost nothing is done yet, it didn't even yet read the profiles from disk nor the rtnetlink information. At that point, the D-Bus API shows no devices and no profiles yet. They appear dynamically afterwards.

`network-online.target` means that `NetworkManager-wait-online.service` completed, which corresponds to the moment when NetworkManager logs "startup complete". That's the point when NetworkManager completed to configure everything that it is planning to. It's a very general (but useful) meaning of "it's ready".

Compared to `systemd-networkd-wait-online` command line tool, NetworkManager-wait-online.service is currently not intended to be configurable directly -- instead you configure in NetworkManager the profiles that should autoconnect and settings like `connection.wait-device-timeout` that controls what to wait for. For example, I would prefer a new (hypothetical) profile setting `connection.ignore-for-startup` over a `--ignore=INTERFACE` flag to `NetworkManager-wait-online.service`. If a user requires something more specific, they are encourage to have their own service. NetworkManager maybe can also get new features to help with certain specific use cases.

This is how `network.target` works since the beginning. Changing now the definition seems not right especially because it would delay boot of most systems (because many services are `After=network.target`, but few are `After=network-online.target`).

Also, is it useful to have the virtual device created, if nothing else is there yet? Likely there are no bridge ports attached, so the device has no carrier and no IP configuration. That may actually suffice for this issue, but it doesn't seem to be general enough to define it as part of `network.target`. There should be a more specific solution that better can express what to wait for.

If the user wants to wait for the software devices to be there, maybe they should order `After=network-online.target`? If that waits for too much, then we could introduce a new synchronization target which is specific to NetworkManager and has a very specific meaning.

How about a new service `nm-device@vbr6s0.service` that the user can enable? Or even a `NetworkManager-wait-any-synthetic-network-devices.service`?

**Comment by poettering** [comment]
> I am quite skeptical. My biggest concern is that this will delay boot for everybody and that it's still ill-defined.

Will it though? The idea is not to wait for configuration of such interfaces, but just the mere creation (i.e. only wait for allocation of the network interface device in kernel/sysfs). In fact, it should be entirely enough to enqueue the netlink requests to create the relevant synthetic interfaces that can be created without further resources to exist. There isn't even the need to wait to the requests to complete — under the assumption the kernel will process such netlink requests before (i.e. in order to ) any netlink requests that try to query them then coming in from later clients.

> How about a new service `nm-device@vbr6s0.service` that the user can enable? Or even a `NetworkManager-wait-any-synthetic-network-devices.service`?

We don't really need something like that. People can just add unit drop-ins then:

```
mkdir -p /etc/systemd/system/systemd-nspawn@foo.service.d
cat >  /etc/systemd/system/systemd-nspawn@foo.service.d/wait-for-net.conf <<EOF
[Unit]
Wants=sys-subsystem-net-devices-br0.device
After=sys-subsystem-net-devices-br0.device
EOF
```

But that of course requires manual tweaking which I'd like to avoid.

I think it would be nice to users if the stuff that can be done "quickly", i.e. that doesn't require protocols or so would be complete by the time network.target is reached. Of course it's up to the network management solution to figure out what "quick" is, but I'd personally draw the line at: at least enqueue the rtnetlink create messages for all virtual interfaces that have no deps on resources that need to show up first. i.e. signal "initialization complete" only at the moment you actually have to start blocking, waiting for events.

Anyway, I updated the network.target docs now, which suggest this is a good thing to do. If NM doesn't want to do that, then that's fine, the target is vaguely enough defined to allow either way. I think it would be really nice if NM would move towards this too, but if that's not in the cards, that's fine by me.

**Comment by thom311** [comment]
> Will it though? The idea is not to wait for configuration of such interfaces

It would require NM to signal started only after reading all profiles and starting to activate them. In theory, that should be blazing fast. In practice, it probably would increase the start time by a few hundred milliseconds. That should be improved, but it's not high priority at the moment.

I wasn't aware of device units. Nice, I am impressed.

> Anyway, I updated the network.target docs now, which suggest this is a good thing to do. If NM doesn't want to do that, then that's fine, the target is vaguely enough defined to allow either way. I think it would be really nice if NM would move towards this too, but if that's not in the cards, that's fine by me.

Makes sense. OK, it would be nice indeed. It would require some work to do, but the hardest part is to ensure that NetworkManager still starts fast (enough).

**Comment by poettering** [comment]
I prepped a patch in #18858 which documents the .device dependency stuff.

Once the PR is merged this issue is closed. I think everything here has been addressed with that documentation fix
