### ISSUE TITLE
systemd-networkd: symbol lookup error .. undefined symbol: _set_put_strdup_full, version SD_SHARED

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#18822]
```
symbol lookup error: /usr/lib/systemd/systemd-networkd: undefined symbol: _set_put_strdup_full, version SD_SHARED
```

**systemd version the issue has been seen with**
```[root@bp-devel ~]# systemctl --version
systemd 246 (v246.6-3.fc33)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Used distribution**
Fedora 33 systemd-nspawn container on fedora 33 host

**Linux kernel version used** (`uname -a`)
```
[root@bp-devel ~]# uname -a
Linux bp-devel 5.10.18-200.fc33.x86_64 #1 SMP Tue Feb 23 22:06:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
**Additional program output to the terminal or log subsystem illustrating the issue**
```
Feb 28 19:58:08 bp-devel systemd[1]: Starting Network Service...
Feb 28 19:58:09 bp-devel systemd-networkd[51]: /usr/lib/systemd/systemd-networkd: symbol lookup error: /usr/lib/systemd/systemd-networkd: undefined symbol: _set_put_strdup_full, version SD_SHARED
Feb 28 19:58:09 bp-devel systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=127/n/a
Feb 28 19:58:09 bp-devel systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Feb 28 19:58:09 bp-devel systemd[1]: Failed to start Network Service.
Feb 28 19:58:09 bp-devel systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 5.
Feb 28 19:58:09 bp-devel systemd[1]: Stopped Network Service.
Feb 28 19:58:09 bp-devel systemd[1]: systemd-networkd.service: Start request repeated too quickly.
Feb 28 19:58:09 bp-devel systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Feb 28 19:58:09 bp-devel systemd[1]: Failed to start Network Service.
```

**Steps to reproduce the problem**
First time I saw this today, after a container crashed with max memory usage.
As Google didn't bring up anything relevant, I thought this is some one-time issue, and reinstalled the container.
Then after updating the host, another container produced exactly the same error.

**Additional program output to the terminal or log subsystem illustrating the issue**
Starting from the shell drops instantly the same error:
```
[root@bp-devel ~]# /usr/lib/systemd/systemd-networkd
/usr/lib/systemd/systemd-networkd: symbol lookup error: /usr/lib/systemd/systemd-networkd: undefined symbol: _set_put_strdup_full, version SD_SHARED

```
The configuration was working well, and does work well on other containers, but I have no explanation why suddenly the second container is facing this issue. It might have to do something with stopping working containers? ....

**Comment by poettering** [comment]
hmm, is it possible the container was upgraded while running? i.e. systemd.rpm updated?

**Comment by LaKing** [comment]
Yes, it was. 

It didn't cause any trouble at the upgrade, and upgrading used to work, it just says that it fails to update the systemd package ...

Is updating the container os with `dnf -y update` not recommended?

**Comment by poettering** [comment]
my educated guess is that between RPM minor versions some stuff get backported that affected the libsystemd-shared-XYZ.so ABI. The idea is that the lib isn't abi stable, but gets a new name on every release. But that only works as long as the backports that leave the major version untouched don't break ABI. 

@keszybz i guess we should make the version number included in the .so name configurable at meson time, and then pass it in during the RPM build process, so that it is nevra? That way rpm can safely update everything, since every single minor rpm package version would pick a new .so name.

**Comment by keszybz** [comment]
There's a bug open in Fedora that looks similar. It should be fixed by the recent rework to restart services later. The issue was that we would restart things quite early. In general all systemd subpackages have strict requires on the main subpackage that provides libsystemd-shared.so. But since systemd-networkd is in a separate subpackage, it could happen that we installed systemd.rpm already, but had old systemd-networkd, or vice versa. With the recent rework, scriptlets have been moved to the end, and this should be fine.

But I think you have a different problem:
> First time I saw this today, after a container crashed with max memory usage.
> Starting from the shell drops instantly the same error:

It seems your rpm transaction crashed, and you ended up with incompatible versions of systemd and systemd-networkd installed. Please verify with `dnf list --installed 'systemd*'` and `rpm -V systemd systemd-networkd`. I'll close this here, since it doesn't seem to be an upstream issue in any way.

**Comment by poettering** [comment]
@keszybz but wouldn't it be safer to just update the .so filename with every minor RPM update too?

**Comment by keszybz** [comment]
> @keszybz but wouldn't it be safer to just update the .so filename with every minor RPM update too?

I guess we could do that. Though I think we should just do that upstream, i.e. change the current libsystemd-shared.so naming scheme to include the full version string.

See also https://bugzilla.redhat.com/show_bug.cgi?id=1906010.
