### ISSUE TITLE
systemd support for CLONE_INTO_CGROUP

### ISSUE THREAD

**Issue by giuseppe** [systemd/systemd#18843]
**Is your feature request related to a problem? Please describe.**

currently an existing pid is required to create a new systemd scope, this makes impossible the usage of the new CLONE_INTO_CGROUP[1] kernel feature where a process is cloned into a different cgroup at fork time.

**Describe the solution you'd like**

Have a way to create a scope without any PID inside of it (perhaps have a timeout mechanism to cleanup it up if no pid is moved there?).  Once a new process is moved there, then it is made the main pid for the scope.

**Describe alternatives you've considered**

Create a delegated subcgroup and CLONE_INTO_CGROUP there, but this doesn't really play nicely with systemd and requires an extra cgroup migration.

**The systemd version you checked that didn't have the feature you are asking for**

246

[1] https://www.man7.org/linux/man-pages/man2/clone.2.html

**Comment by keszybz** [comment]
Sounds like we need a new dbus method to create an empty scope. We should also create a start job which would finish as successful as soon as a pid has been moved into the scope and made main pid.

**Comment by poettering** [comment]
(also see #16706 — CLONE_INTO_CGROUP from C/glibc is currently not possible).

There's no "main pid" concept for scopes, And I am not sure there should be? Thing is we cannot collect exit codes from non-children of ours (pidfd doesn't change that)...

But yeah, we need a story so that processes can be spawned directly into scopes. We have nothing nice there.

Currently scopes only go from populated to unpopulated. If we allow them to be alive even when unpopulated we probably need to provide some scheme how clients can take a ref on a scope so that we can sanely track lifecycle.

**Comment by poettering** [comment]
> Currently scopes only go from populated to unpopulated. If we allow them to be alive even when unpopulated we probably need to provide some scheme how clients can take a ref on a scope so that we can sanely track lifecycle.

Maybe we could just say: scopes are active as long as either a process is in it, or the scope unit as a `Controller` bus peer that is still on the bus, that would probably suffice

**Comment by giuseppe** [comment]
@poettering @bluca thanks for working on this!

Can it only be used through `posix_spawn_wrapper`, meaning there's no way to create an empty cgroup and have another process manage the CLONE_INTO_CGROUP by itself?

**Comment by poettering** [comment]
@giuseppe no, we do not support this. At this time migration into units must go through our bus APIs, and that doesn't conceptually work with CLONE_INTO_CGROUP...

**Comment by poettering** [comment]
@giuseppe so i don't think we can implement what you are suggesting even if we decided we wanted to.

The thing is that cgroupvs2 allows migrations over delegation boundaries only to privileged processes. Thus, if you let's say run crun or so in an ssh session and want to migrate it into a per-user scope, then you cross a delegation boundary (since the former is part of a session scope, and the latter is part of user@.service of the user). To allow this to work anyway the per-user service manager actually falls back to a bus call of the per-system manager to do the actual migration.

But something like this is never going to work if we want to allow crun to use CLONE_INTO_CGROUP: if it doesn't have the perms it just doesn't have the perms...

hence, i don't see an avenue for this, sorry.
