### ISSUE TITLE
man page sd_listen_fds_with_names - guidance on service exit - close?

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#18872]
I'm looking at implementing a socket activation service and the current man page contains good information about getting the listening file descriptors.

**Describe the solution you'd like**

It lacks guidance as what to do with the file descriptors upon exit.

I suspect if you change socket options its current to the service process and won't be reflected on the restart but there's obviously some limitations on this regarding on filesystem unix socket permissions and other options. Some clarification of these items would be most welcome.

**Describe alternatives you've considered**

https://www.freedesktop.org/software/systemd/man/systemd.socket.html#RemoveOnStop= has the base of a guidance as to just leave them open, but is limited in scope to filesystem visible items.

**Comment by poettering** [comment]
You can close them or leave them open (in which case your process exiting will close them for you), up to you. They are yours. PID 1 basically keeps an dup()'ed copy of them around, and that's what it'll watch for POLLIN on on the next cycle. Hence, everytime your service gets reactivated again and again while the .socket unit for it remains running you'll basically get the same sockets passed in (well, except in Accept=yes mode). This also means that any setsockopt() you call will remain in effect on the next cycle (which can be used for good – and for evil).

And of course this means you should never call shutdown() on such a socket, because in that case you really shutdown the sockets, and PID1's dup()ed copies will be useuless too.

But yeah, we could certainly improve doc on this.
