### ISSUE TITLE
Getting Error  systemd[3990]: Failed to canonicalize path /home/abc/.config/systemd/user/exit.target.wants: Permission denied

### ISSUE THREAD

**Issue by baid86** [systemd/systemd#18947]
**Systemd Version**
`systemctl --version`
`systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid**`
 > …

**Used distribution**
 > Ubuntu 18.04.5 LTS

**Linux kernel version used** (`uname -a`)
 > `Linux cnmaestro-10-110-208-241 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 > While system was going to reboot I saw above errors on console. Is it something to be worried about OR can be ignored.
`systemd[3990]: Failed to canonicalize path /home/abc/.config/systemd/user/exit.target.wants: Permission denied`

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.

**Comment by tkalfaoglu** [comment]
Unfortunately it's not something that can be ignored -- I am getting 10 of these messages every second in the logs.. So, it's lots of useless I/O..
