### ISSUE TITLE
systemd-boot: allow to default to the last booted entry

### ISSUE THREAD

**Issue by patrakov** [systemd/systemd#18994]
I dual-boot between Windows 10 and Arch Linux. Sometimes Windows wants to reboot without asking after installing the updates. I would still like to be greeted by the Windows login screen after this, not Linux. On the other hand, after rebooting Linux, I would still like to get back into Linux by default.

It would be nice if I could configure systemd-boot (via loader.conf) so that it automatically remembers (without having to press "d") which entry was booted last, and boot into that by default.

E.g.:

default=last-booted-entry

Note: I am not asking to make this "remember the last booted entry" behavior the default. I am asking to make it possible.

Obviously there is some interaction with boot-blessing logic, but, as I don't use this logic, I can't think of a good design here. Maybe we'll also need some logic that prevents certain entries from being remembered, not sure here.

Systemd version that doesn't have this feature: 247

**Comment by poettering** [comment]
hmm, so far we refrained from doing automatic persistent efi variable changes in "regular" boot code paths, and instead only in case where the user explicitly reconfigures something, because the involved memory chips are typically low quality and the memory management implementations for persistent efi vars in firmware even worse, hence making changes on every single boot is a bit questionnable.

That said, I figure as an option we can certainly add that. And maybe quality of the firmware implementations and memory chips has increased today. And if you don't update your kernel that often/change what to boot into the write cycles don't grow thaaaat much.
