### ISSUE TITLE
service Unit file with Slice and KillMode cannot work after restart

### ISSUE THREAD

**Issue by zihan618** [systemd/systemd#19167]
**systemd version the issue has been seen with**
 > systemd 219

**Linux kernel version used** (`uname -a`)

 > `Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Expected behaviour you didn't see**
  the origin service unit file is like, and all processes are in subcgroup of `system.slice`
```
...
[Service]
...
ExecStop=/bin/kill -s TERM $MAINPID
KillMode=process
...
```
new service unit file is like, 
```
...
[Service]
...
ExecStop=/bin/kill -s TERM $MAINPID
KillMode=process
Slice=parent-child.slice
...
```
expect that all processes move to new slice `/parent.slice/parent-child.slice` after exec `systemctl daemon-reload & systemctl restart xxx.service` 
**Unexpected behaviour you saw**
 > cgroup changes if the service only has $MAINPID
cgroup doesn't change if service contains other PIDs except $MAINPID.   
The features of `KillMode=process`  and `Slice=` seem to conflict, is this feature or bug? 
And how to achieve the cgroup transition?

**Comment by poettering** [comment]
[Canned reply follows] This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission forum tried to make this all very clear.
