### ISSUE TITLE
Add ESP, XBOOTLDR and INITRD to systemd-path and systemd-path search

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#19176]
I think it would be a nice addition adding the relevant efi, xbootlrd and initrd paths to systemd-path along with their search- equivalents. 

I also think there should exist search- equivalent for all paths systemd-path but there must be reason why that was not done on the first place.

**Comment by poettering** [comment]
What is "initrd path" supposed to mean?

**Comment by johannbg** [comment]
Path to the initrd images on the system

**Comment by poettering** [comment]
they could be anywhere... the way kernel-install and the boot-loader spec typically is implemented they likely aren't placed in the same dir, and instead each kernel version gets its on dir where the initrd is placed in.

hence, there's no sane way to detect that, it's not a common directory, it's a bunch of dirs, all over the places.

what'd be the usecase for this?

**Comment by johannbg** [comment]
The general idea with systemd-path is to "List and query system and user path" which are the currently used paths on the system and this would just follow that convention and be used in same manner as systemd-path and search is being used for other listed paths.

With regards to the initrd/kernel paths being all over the place that´s a deficiency in the sd-fhs specification and should be addressed there. For example in a "rolling" release the paths and name would always be the same ( which I think Arch is doing ).

**Comment by poettering** [comment]
We have a spec which describes how kernels/initrds are to be discovered, but it doesn#t define a single dir to place initrds in, and quite frankly i don't see the reason why one would place them all in the same dir. 

I mean, ESP and XBOOTLDR are clearly defined as concept that are mounted somewhere and are per-system singletons, but initrds are really not just like that. initrds are often even embedded into unified kernel images...

**Comment by poettering** [comment]
So, sd-path mostly just exposes "static" data, i.e. compiled in defaults, some config files some env vars.

searching for the ESP/XBOOTLDR is an "active" operation however, it actually looks at file systems, probes them and so on. Hence I am pretty sure sd-path is not the right place for this.

However, bootctl I think fits, and in fact since a longer time we actually have commands for dumping the esp/xbootldr path there: 

```
bootctl -p
bootctl -x
```

I don't think the initrd thing is really something we could possibly provide, since initrds can come in any form, in any place, there's no standard. And I don't think there should be any.

Anywa, since the ESP/XBOOTLDR things has a nice answer these days, let's close this.
