### ISSUE TITLE
Support '+=' in environment file

### ISSUE THREAD

**Issue by julien-lecomte** [systemd/systemd#19194]
I'm frustrated that I have to create a very long line in environment file (eg: /etc/default/prometheus on debian), when I could and would rather be using '+=' to concat the env var.

'+=' is allowed by several tools to concat strings such as 
`foobar="hello"`
`foobar+=" world" `
is identical to
`foobar="hello world"`

systemd version 241 (241)

**Comment by poettering** [comment]
EnvironmentFile= employes a subset of bourne shell syntax. i.e. any file that parses as EnvironmentFile= should also parse fine as bourne shell script (though the reverse is not true and shouldn't be true, since that would mean we'd be another bourne hsall implementation).

To my knowledge posix bourne shell doesn't support any "+=" syntax (bash does support it though), hence I am very sure we shouldn't either.

Debian's /etc/default/* files in particular are supposed to be shell fragments, hence I am pretty sure this would even be against debian's guidelines if used.

Hence, closing, I am very sure we shouldn't do this. 

Or maybe to turn this around, if you can convinced posix to add this syntax in bourne shell scripts, we can look into this too.

Hope this makes some sense?
