### ISSUE TITLE
Surprising results with the DBus API

### ISSUE THREAD

**Issue by bochecha** [systemd/systemd#1929]
I'm trying to use the systemd DBus API, but the problem is easier to reproduce with `busctl`, and both exhibit the same surprising behaviour.

I'm running this on Fedora 23, with systemd-222-8.fc23.x86_64

```
$ busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager GetUnit s nginx.service
Unit nginx.service not loaded.
```

However, systemctl find it just fine:

```
$ systemctl status nginx.service
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```

However, after I enable `nginx.service`:

```
$ sudo systemctl enable nginx.service
Created symlink from /etc/systemd/system/multi-user.target.wants/nginx.service to /usr/lib/systemd/system/nginx.service.
$ busctl call org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager GetUnit s nginx.service
o "/org/freedesktop/systemd1/unit/nginx_2eservice"
```

So it seems that there is a problem with the DBus API, where it returns that it can't find the unit if the service is not enabled.

If this is expected, then it is very surprising, as I would expect the enablement of the unit to have no impact on its `LoadState`.

**Comment by poettering** [comment]
GetUnit is actually not a particularly useful call. Use LoadUnit instead. In fact we should really deprecate and hide that call really.

systemd GCs units agressively unloading them as soon as they are not referenced anymore. However it also implicitly loads units again when they are accessed, including when accessed via their bus path. The bus path is stable across such reloads.

An enabled unit is usually referenced from multi-user.target or so because its pulled in by that. That reference is enough to ensure the unit is never unloaded (or well, stays around as long as multi-user.target itself stays around). Hence yes, enabling a unit does have an effect on the load state.

Hope that makes sense? I dont see.anything to fix here, hence closing.

**Comment by bochecha** [comment]
@poettering Indeed, `LoadUnit` does exactly what I need, thanks! :+1: 

Thanks for the explanation as well. It does make sense now that I know how it works, but it has the potential to continue confusing newcomers (like I was before you explained), so much that you might have to answer this question over and over in the future.

Maybe deprecating `GetUnit` isn't necessary though, couldn't you just make it an alias for `LoadUnit`?

In any case, thanks for your answer, my problem is now solved. :smile:
