### ISSUE TITLE
journald:The 666 permission of dev-log

### ISSUE THREAD

**Issue by syyhao1994** [systemd/systemd#19341]
**systemd version the issue has been seen with**
 > All

**Used distribution**
 > fedora33 and all others

**Steps to reproduce the problem**
 > I noticed that the permision of /run/systemd/journal/dev-log is 666. I am wondering if there is a security risk as others's permission is also 6, this maybe introduced the log injection of dos problems. Should we do some things on this?

**Comment by poettering** [comment]
syslog access on UNIX is generally assumed to be world-writable. Always was (at least on linux). 

journald will pick of the sender's creds however, and attach them to the log records implicitlly, and that can't be faked because we get the data from the kernel directly. So unless people are able to fake the kernel's metadata (i.e. exploit the kernel) we should be safe.

It's typically our interest that people run their code with the least privileges possible. hence it's kinda important that we make logging easy from any kind of user, but then track which one was actually used.

Hope that makes sense?

Closing.
