### ISSUE TITLE
systemctl reboot get terminated by signal 15

### ISSUE THREAD

**Issue by PengpengSun** [systemd/systemd#19353]
Hi there,

Our program executes 'systemctl reboot' in a child process to reboot Linux right after its booted, Sometimes there is no error, but sometimes the child process terminated due to received uncaught signal 15, then no reboot happened.  WIFSIGNALED evaluated a non-zero value, WTERMSIG evaluated 15.  Don't understand why the uncaught signal 15 happened here, please shed light on this, Thanks.

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
