### ISSUE TITLE
Is there a way to know inside of systemd if it's in a reboot state?

### ISSUE THREAD

**Issue by jetm** [systemd/systemd#19358]
This is not a bug report. It's more like a question.

Is there a way to know inside of systemd if it's in a reboot state?

Something like the [Linux kernel does](https://elixir.bootlin.com/linux/v4.19.98/source/include/linux/kernel.h#L581), keeping the system state in a variable.

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
