### ISSUE TITLE
run non root user command as a service

### ISSUE THREAD

**Issue by bilalmalik777** [systemd/systemd#19399]
I have a command to create backup file for sql server

`sqlcmd -S localhost -U SA -P lhr_lon_tt258 -Q "BACKUP DATABASE [Core] TO DISK = N'/var/opt/mssql/data/corebackup/core.bak' WITH NOFORMAT, NOINIT, NAME = 'Core-full', SKIP, NOREWIND, NOUNLOAD, STATS = 10"`
. It creates a backup file. But now i want to run this command as a service, when i create a service and start that service it is not getting run successfully even I added **sudo -u username** in the start of the command but same error. Service code is also given below.

```
[Unit]
Description=start sqlbackup service

``
[Service]
Type=simple
ExecStart=/home/thingtrax/Downloads/DockerCompose_localserver/DockerCompose/Backup_script/sqlbackup.sh
Restart=on-failure
RestartSec=30s
StandardOutput=null

[Install]
WantedBy=multi-user.targe
```

**Comment by boucman** [comment]
see User= in [Service] (an please check the man page)

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
