### ISSUE TITLE
Don't do SELinux access checks when running in --user mode

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#1941]
Hi,

Shouldn't the systemd --user instance keep the audit_write capability?

I'm seeing things like that in syslog: 

```
nov 18 09:20:17 fornost systemd[2569]: Can't send to audit system: USER_AVC avc:  denied  { reload } for auid=n/a uid=1000 gid=1000 cmdline="/bin/systemctl --user set-environment DBUS_SESSION_BUS_ADDRESS=unix:pa
                                    exe="/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?
```

I know it's a bug in the SELinux policy, but this kind of things should be logged in audit

**Comment by poettering** [comment]
I am quite sure we probably should turn off all selinux checking from systemd when we run in `--user` mode.

**Comment by bigon** [comment]
Are you sure we don't want SELinux check for user sessions? Not all users are unconfined

**Comment by linux-modder** [comment]
I'm with @bigon on this, plus  setenforce=1  (permissive) does not seem to be  reporting to audit either

**Comment by rhatdan** [comment]
What context is systemd -user running under?  If it is running under a user context then it probably should not do any checking.  If it is not doing anything that raises privileges.

**Comment by ghost** [comment]
systemd --user is running with whatever context you tell it to run with via pam_selinux.

systemd --user needs various permissions that you may not want to associate with confined login user shells. For example: logging to audit, and journal, write access to cgroupfs, selinux compute create access vectors, compute create context, create user ptys, read systemd --system state, dgram send systemd --system, read systemd config and units, send generic signals to systemd --system etc.

 I think it is comparable to dbus, where you have a system and session bus. the dbus session bus currently enforces selinux access control just like the system bus does. The same currently applies to systemd --system versus systemd --user

**Comment by ghost** [comment]
The thing here is that we are deviating here. This issue is only losely related to the question whether to enforce selinux access control with systemd --user or not.

The issue here is that it is currently not permitted to send some messages to audit. dbus seemingly had similar issues for a long time. This was fixed in the dbus code without disabling the selinux access control enforcement in dbus --session. I am struggling to understand why this issue should be resolved by disabling selinux access control in systemd --user.

I will admit that i am struggling to find a compelling reason to enforce access control with systemd --user but chances are that i am overlooking things. I just do not see how this particular issue should result in disabling this functionality. no one ever considered disabling the selinux access control for dbus --session when it was unable to send some messages to audit....

**Comment by ghost** [comment]
@rhatdan I would like to be able to govern what can control what in the user session with systemd --user. this functionality allows me to do that. Currently no user applications use systemd --user as far as i am aware, but I can imagine/envision that once gnome for example starts using systemd --user that it will start using systemctl --user to control various components. I want to be able to contain that.

After thinking about this for a while, i came to believe that we should just really keep this functionality at least for now.

Just associate audit_write with systemd --user and get it over with.

either that or log to journal instead of audit if that is at all possible

**Comment by rhatdan** [comment]
Have you attempted to run systemd -user under a separate context?  What access did it need that your confined user did not have?  Is sytemd-user subdividing cgroups? Starting separate services on the users behalf?  

Dbus only enforces whether or not you can talk across the bus for all practical purposes.
