### ISSUE TITLE
test-siphash24 fails on mips, powerpc and s390x

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1946]
Version: 228

The rework of the siphash function seems to have caused regressions on various architectures:
https://buildd.debian.org/status/package.php?p=systemd

They all fail with the following error message:

```
==== test-siphash24.log ====
Assertion 'out == htole64(0xa129ca6149be45e5)' failed at ../src/test/test-siphash24.c:33, function do_test(). Aborting.
FAIL test-siphash24 (exit status: 134)
```

**Comment by fsateler** [comment]
Note that all 3 failing architectures are big endian. All that succeeded are little endian.

https://wiki.debian.org/ArchitectureSpecificsMemo

**Comment by filbranden** [comment]
I think just removing the `htole64` there would fix the problem. I just tested that that doesn't break x86-64 which is a good hint already :-)

It might be the other way around though... That out is missing the converse transformation. Not sure which of them is the correct one.

**Comment by martinpitt** [comment]
I'm looking at this ATM, thanks for filing this already. Indeed the whole siphash24 now uses only 8 bit ints, thus it should behave exactly the same on little and big endian. I'll verify that dropping the `htole64()` works.

**Comment by martinpitt** [comment]
> the whole siphash24 now uses only 8 bit ints

Ah, not quite -- the `v0..3` state fields are `uint64_t`, and the result is XORing them. However, conceptually the test should not have to do endianess conversion -- `siphash24_finalize()` returns an `uint64_t`, so that should be the same on all architectures and the test should assert that. 

Indeed dropping the conversion fixes the test on powerpc. Commit 
933f9caeeb2b3c1b951d330e04beb04226e5a890 converted the result into native endianess, so expectations now match reality. :-)
