### ISSUE TITLE
the blkio/ hierarchy changed of current login bash shell after I start a VM by virsh command

### ISSUE THREAD

**Issue by Xiaojun-zhao** [systemd/systemd#19479]
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.4)

**Used distribution**
 >root@ubuntu2004:~# lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Unexpected behaviour you saw**
 > Show the blkio controller hierarchy of current login bash
`cat /prco/$$/cgroup | grep blkio
root@ubuntu2004:~# cat /proc/$$/cgroup | grep blkio
3:blkio:/
`
And then I started a VM with virsh command.
`
virsh start ubuntu-test
`
I relogined and showed the blkio controller hierarchy of current login bash.
`
root@ubuntu2004:~# cat /proc/$$/cgroup | grep blkio
3:blkio:/user.slice
`
The blkio controller hierarchy was changed of current bash from **3:blkio:/** to **3:blkio:/user.slice**.
I tested it was not changed if I did not start a VM. Way it was changed from  **3:blkio:/** to  **3:blkio:/user.slice**? 

```text
…
```

**Comment by poettering** [comment]
[Canned reply follows]

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
