### ISSUE TITLE
systemd-resolved: Very high CPU usage when abruptly exiting tcpdump

### ISSUE THREAD

**Issue by ndren** [systemd/systemd#19492]
systemd version the issue has been seen with

    systemd 248 (248-5-arch)

Used distribution

    Arch

Linux kernel version used (uname -a)

    Linux arch 5.10.33-1-lts #1 SMP Wed, 28 Apr 2021 15:58:21 +0000 x86_64 GNU/Linux

CPU architecture issue was seen on

    x86_64

Configuration

    DNS=95.216.24.230#fi.dot.dns.snopyta.org 2a01:4f9:2a:1919::9301#fi.dot.dns.snopyta.org
    FallbackDNS=
    DNSOverTLS=yes

Steps to reproduce

    1. Run tcpdump as root.
    2. Run multiple network requests, e.g. visiting multiple heavy websites.
    3. Exit tcpdump in the middle of the network requests.

Results

systemd-resolved reaches 100% CPU usage until it is restarted/killed, or approximately 30 seconds, whichever comes first. This is not an issue with tcpdump as I cannot reproduce the issue with unbound (it exits gracefully, if maybe not immediately). I have come across the same issue with other operations, e.g. `curl` with a working router but no network connection, however this is the one I could most easily reproduce.

**Comment by poettering** [comment]
Hmm, wa?

Any chance you can run "strace -s 500 -y -p $PID" on resolved's PID when this happens, to see wat it might be spinning on?

This is seriously weird...

**Comment by btdmaster** [comment]
Odd. I could not reproduce this at first however after a reboot (and enabling it to start at startup) it happened again.
Result of `sudo strace -s 500 -y -p 290`:
```
epoll_wait(4<anon_inode:[eventpoll]>, [{events=EPOLLHUP, data={u32=972342720, u64=94906864682432}}], 40, -1) = 1
gettid()                                = 290
epoll_wait(4<anon_inode:[eventpoll]>, [{events=EPOLLHUP, data={u32=972342720, u64=94906864682432}}], 40, -1) = 1
gettid()                                = 290
epoll_wait(4<anon_inode:[eventpoll]>, [{events=EPOLLHUP, data={u32=972342720, u64=94906864682432}}], 40, -1) = 1
gettid()                                = 290
epoll_wait(4<anon_inode:[eventpoll]>, [{events=EPOLLHUP, data={u32=972342720, u64=94906864682432}}], 40, -1) = 1
gettid()                                = 290
```
and so on. It seems the issue triggers most easily (i.e. with only `curl cht.sh` and no other network requests) early on, while the system has just booted. I'm using plain IWD if that matters.

**Comment by poettering** [comment]
hmm, we see EPOLLHUP on one specific fd. That's quite interesting. Question is which one that is. any time you can gdb this?

somehow your issue triggers EPOLLHUP on some fd we don't expect EPOLLHUP on and thus don't handle properly

**Comment by btdmaster** [comment]
I don't know how to use gdb, let alone find the relevant fd. Any suggestions?

**Comment by mrc0mmand** [comment]
I gave it a try on Arch with the latest master (f8eb41003df1a4eab59ff9bec67b2787c9368dbd AToW) and the issue is indeed quite easily reproducible using the steps above, e.g.

`/etc/systemd/resolved.conf`
```ini
[Resolve]
DNS=95.216.24.230#fi.dot.dns.snopyta.org 2a01:4f9:2a:1919::9301#fi.dot.dns.snopyta.org
FallbackDNS=
DNSOverTLS=yes
```

In one terminal:
```
# systemctl restart systemd-resolved && tcpdump
```

In the second one:
```
$ curl cht.sh
```

and then ^C `tcpdump`. This causes resolved to spin up to 100% CPU for a while.

I attached `ltrace` to the resolved process during one of the occurrences, but I guess it won't help much: [resolved-ltrace.log](https://github.com/systemd/systemd/files/6429300/resolved-ltrace.log) (note: every `<...BIG SNIP...>` section is ~20k of lines containing the previous `SYS_epoll_wait() - SYS_gettid() - SYS_sendmsg()` combo).

**Comment by poettering** [comment]
Is this reproducible on non-Arch? fedora?

I tried to reproduce this exactly as @mrc0mmand suggested, but failed to reproduce this. the curl cmdline will fail because there's something wrong with the TLS certificates of those DNS servers, but that's just takes us a brief moment to figure out.

can anyone provide at least a debug output of resolved when this happens? i.e. issue `systemctl service-log-level systemd-resolved debug`, then reproduce the issue and check the log

**Comment by poettering** [comment]
ping?

**Comment by ndren** [comment]
It looks like this is "solved", that is the snopyta.org server is down and I can't reproduce on any other... I'll reopen with logs if I can reproduce again.

**Comment by rdnaskelz** [comment]
Just encountered this "bug", got the same output for `strace` as @ndren 
But my use case and DNS servers are different: I'm trying to run an Ansible "common" role on freshly installed Proxmox VM and using Quad9 DNS. Also got 100% on one of the cores.

Turns out my playbook was bug-prone and had configured iptables wrong (wrong interface name to be specific) so the host basically firewalled itself in mid-playbook which had been stopping `apt update` from working (it just hanged) and CPU usage on `/usr/lib/systemd/systemd-resolved` went to 100% on a single core but as soon as I flushed iptables, CPU usage went down.
