### ISSUE TITLE
Common cli integration of services

### ISSUE THREAD

**Issue by jackiesparks** [systemd/systemd#19586]
Raspbian buster 10

Upon copying template and im sure im doing this wrong.
I change the variables. 
Systemd doesnt use getpid <string> 

Assumes process is running and reports active by lock tmp file structure.

Also

Source built daemons added under differnt prefix than system packages has const variables and has to be manually edited 20+ times.

I assume make a C wrapper from the template. While also a vauge psuedo function shell instead of individual functions in one script.

**systemd version the issue has been seen with**
 > …

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
