### ISSUE TITLE
`bootctl systemd-efi-options` fails to read efi variable

### ISSUE THREAD

**Issue by tmuehlbacher** [systemd/systemd#19597]
I am using Debian with v247.3 and originally reported this here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=988450

```console
$ uname -a
Linux sol 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux
```

As discussed in the original but report, reading the `SystemdOptions` variable using `bootctl` fails, while setting it does work and the option is also applied after booting the system.

This appears to happen because the command only tries to read the cached variable from `/run/systemd/efivars` and doesn't fall back to reading it from `/sys/firmware/efi/efivars`.

I am using GRUB and have Secure Boot enabled. This particular `bootctl` subcommand doesn't seem to me like it would actually depend on using `systemd-boot`, but should work on any EFI system?

```console
# bootctl systemd-efi-options
Failed to query SystemdOptions EFI variable: No data available
# bootctl systemd-efi-options 'debug'
# bootctl systemd-efi-options
Failed to query SystemdOptions EFI variable: No data available
$ hd /sys/firmware/efi/efivars/SystemdOptions-8cf2644b-4b0b-428f-9387-6d876050dc67
00000000  07 00 00 00 64 00 65 00  62 00 75 00 67 00 00 00  |....d.e.b.u.g...|
00000010
```

As a solution I would suggest that this function should also fall back to reading from `/sys/firmware/efi/efivars` if the cache in `/run/systemd/efivars` is not available:
https://github.com/systemd/systemd/blob/v247/src/basic/efivars.c#L378

**Comment by poettering** [comment]
hmm, so the issue you are having that if you set it and read it back with "bootctl systemd-efi-options" you get different results?

I guess that's surprising indeed.


That said, my original thinking was that it would be a good idea to discern the current and the future string here, see here:

 https://github.com/systemd/systemd/pull/16139#issuecomment-643619000

But looking at this again, this is kinda confusing indeed. 

I mean, I am still pretty sure it's a good idea to not act on any settings on the current boot that weren#t in effect when the boot began. Thus if you change the string it should not be processed by our tools until the next reboot. Thus, the current implementation actually makes a lot of sense, but we really should update "bootctl systemd-efi-options" output, so that we display both the current string that is in effect, and the string that is going to be in effect on next boot if both differ.

**Comment by tmuehlbacher** [comment]
Sorry, my explanation may have been a bit convoluted. 😅

`bootctl systemd-efi-options` *always* fails to read the EFI var, because it *only* tries to read the var from `/run/systemd/efivars/SystemdOptions-8cf2644b-4b0b-428f-9387-6d876050dc67`.

That file (+ the parent dir) doesn't exist on my system, and apparently it shouldn't, according to this comment:
https://github.com/systemd/systemd/blob/v247/src/basic/efivars.c#L342

It's certainly not a critical problem as the *only* thing that doesn't work is reading the EFI var using `bootctl`, everything else works afaict.
