### ISSUE TITLE
tmpfiles: q/Q trigger mount request (which dead locks for remote mounts)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#1959]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805553
Version: 228

In v228, /usr/lib/tmpfiles.d/home.conf was changed to use Q for /home and q for /srv
It is not uncommon, that /home is shared via NFS. In the bug report above, the user has used automount for /home.
Running systemd-tmpfiles --create /usr/lib/tmpfiles.d/home.conf will trigger a mount request (which in turn requires network, which results in a dead-lock)

Previous versions of home.conf used type 'v'. This type doesn't trigger a mount request.

**Comment by mbiebl** [comment]
Thinking about it, I guess automounts for remote mounts should be setup _after_ network-online.target is up to avoid this kind of dead locks. That the mount request was triggered by systemd-tmpfiles is unfortunate (and a regression), but it's possible to trigger such automount requests easily from other components as well.

**Comment by fsateler** [comment]
It seems to me that tmpfiles.d, because it is ordered Before=sysinit.target, should not operate on anything that may be remote, since there is no guarantee that network is up by that time.

Therefore either tmpfiles should be documented to only work for local file systems, or its dependencies relaxed, or split into two runs (one for local-only and another for remote filesystems).

**Comment by lorenzhs** [comment]
The current behaviour was introduced in 822cd601357f6f45d0176ae38fe9f86077462f06 (PR #1641)

**Comment by poettering** [comment]
What is "automount" supposed to mean in this case? systemd's .automount unit logic? Or upstream autofs?

**Comment by lorenzhs** [comment]
The mount options in /etc/fstab are `defaults,x-systemd.automount,x-systemd.device-timeout=5,noatime,noauto`.

**Comment by mbiebl** [comment]
@poettering If you follow the linked bug report, there is a complete copy of /etc/fstab. It uses systemd's automount logic via the x-systemd.automount fstab parameter:

```
141.3.24.140:/home           /home           nfs             defaults,x-systemd.automount,x-systemd.device-timeout=5,noatime,noauto        0 0
141.3.24.140:/global_data    /global_data    nfs             defaults,x-systemd.automount,x-systemd.device-timeout=5,noatime,noauto        0 0
141.3.24.140:/software       /software       nfs             defaults,x-systemd.automount,x-systemd.device-timeout=5,noatime,noauto        0 0
i10pc149:/data01             /workspace      nfs             defaults,x-systemd.automount,x-systemd.device-timeout=5,noatime,noauto        0 0
```

**Comment by vlstill** [comment]
I still have this problem in archlinux and systemd 229. What is the status of this bug?

**Comment by lorenzhs** [comment]
@vlstill I use the workaround described in the first post (`v` instead of `Q` in `home.conf`)

**Comment by vlstill** [comment]
Yes, that works, but I find it unfortunate that systemd can't boot without this modification in a fairly common setup, especially since the mount is done by systemd automounter.

**Comment by prcastro** [comment]
This bug caused a crash of all computers on a computer lab after an upgrade to systemd 229. This setup is too common to be incompatible with systemd by default, I think.

**Comment by fsateler** [comment]
Is a reasonable fix to stop processing (ie, do not continue with the subvolume logic) if the path is a mount point? This should take care of not tampering with admin configuration, but maybe this is too coarse a fix.

**Comment by motp** [comment]
fsateler has made a good point.

We can verify this Bug on our current Debian Setup.
Unfortunately, there also seems to be a race condition when using Dualstack IPv4-dhcp and IPv6-Autoconfiguration on the Client are used: Sometimes the Client will be keept waiting at  systemd-tmpfiles-setup.service, sometimes it will just boot and set /home automount to failed state (see below).

Setup: 
- /home on nfs  (NFS v4.0 over IPv6)
- systemd.automount logic via fstab / x-systemd.automount

Problem: 
Using "Q /home 0755 - - -  " in /usr/lib/tmpfiles.d/home.conf triggers automount of /home, which in turn needs rpcbind, which depends on systemd-tmpfiles-setup.service. 

------------------ schnipp --------------
 Jun 30 08:52:47 kaki systemd[1]: home.automount: Got automount request for /home, triggered by 727 (systemd-tmpfile)
---------------- schnapp ----------

To be clear: This breaks all setups, where /home ist an systemd-automountpoint on NFS and this is our DEFAULT for all Desktop Clients since systemd has gained automount support.

As far as I understand SYSTEMD-TMPFILES(8), this automount request by systemd-tmpfile should never happen, since  /lib/systemd/system/systemd-tmpfiles-setup.service only uses "--create --remove --boot" and the manpage states:

---------------- schnipp --------------
 --create   If this option is passed, all files and directories marked with f, F, w, d, D, v, p, L, c, b, m in the configuration files are created or written to. Files and directories marked with z, Z, t, T, a, and A  have their ownership, access mode and security labels set.
--clean      If this option is passed, all files and directories with an age parameter configured will be cleaned up.
--boot       Also execute lines with an exclamation mark.
---------------- schnapp -------------

I don't see q or Q here. So no automount request should happen at all (just my 2¢). 
IF, however, automount is triggered, systemd-tmpfiles-setup.service should not wait 
for it, since this will cause a dependency loop. Maybe splitting systemd-tmpfiles-setup into an early-stage and network-stage would provide a solution to that?

Regarding the possible race-condition, mentioned above: Our Setup for the Clients is: 
- Client is Dualstack, NFS Server is IPv6-only
- DHCP for IPv4 (via ifupdown)
  iface ptxnet inet dhcp
- SLAAC for IPv6 (via ifupdown)
  iface ptxnet inet6 auto

Now, as soon as the system fires up, home.mount essentially waits for /lib/systemd/system/networking.service to succeed. Since SLAAC is done by the Kernel, there may be a small timeframe, where "ExecStart=/sbin/ifup -a --read-environment" succeeded, but actually no global IPv6 Address is configured yet. In this case, the mount-request will fail immediately afterwards.
This may be debian specific due to the ifupdown logic, though. 
If dhcp/slaac succeeds configuring the interface before the mount request, we see the abovementioned dead-lock.
I'll recheck that on another system as soon as possible.

**Comment by motp** [comment]
Update: This Bug also breaks my Fedora Installation after upgrading to Fedora24:

Jul 05 19:40:05 pizza systemd[1]: Starting Create Volatile Files and Directories...
Jul 05 19:40:05 pizza systemd[1]: home.automount: Got automount request for /home, triggered by 761 (systemd-tmpfile)

After that, the system waits for tmpfiles.d to complete (without timeout), blocking boot.
Temporary workaround as discussed above:

--- /usr/lib/tmpfiles.d/home.conf   2016-07-06 10:25:05.393925627 +0200
+++ /etc/tmpfiles.d/home.conf   2016-07-06 10:26:19.016005224 +0200
@@ -7,5 +7,6 @@

 # See tmpfiles.d(5) for details

-Q /home 0755 - - -
+# 20160706 disable quota check, breaks nfs
+# Q /home 0755 - - -
 q /srv 0755 - - -

**Comment by michaelolbrich** [comment]
Also note, that using type 'v' only works for non-btrfs rootfs: In this case btrfs_is_subvol("/") is false and tmpfiles.d doesn't try to create the subvolume. As a result the automount is not triggered.
A btrfs rootfs will trigger the same dead lock with 'v'.

And btw, home on NFS without automount isn't handled well either: tmpfiles.d will create a useless subvolume and the the actual filesystem is mounted on top of that.

**Comment by uzytkownik** [comment]
Is there at least some local workaround in /tmp? I have accidentally updated systemd on my semi-headless system today (yet again) and it is pain to get it fixed.

**Comment by prcastro** [comment]
Using version 231, the workaround of changing the trigger from `Q` to `v` still is the only way to get systemd to work on a system mounting a NFS `/home` partition

**Comment by mbiebl** [comment]
@poettering any idea how to fix this? This seems to be one of the more common issues our users run into.

**Comment by poettering** [comment]
hmm, i have no nice idea. I figure the mounts we permit to be mounted after basic.target should probably not be referenced in tmpfiles.d as they are right now. But the corollary, i,e. that we'd have to execute tmpfiles.d a second time with those is something I really don't like I must say...

**Comment by joshtriplett** [comment]
I'm wondering if Q and q should really be the domain of tmpfiles at all, rather than something event-driven. Then, if /home is managed by an automount, after it gets mounted it'll get quota'd.

**Comment by poettering** [comment]
> I'm wondering if Q and q should really be the domain of tmpfiles at all, rather than something event-driven. Then, if /home is managed by an automount, after it gets mounted it'll get quota'd.

well, we want it to happen synchronously before we let users log in, hence this should really be inside the dep tree, after the stuff got mounted, but before the logins are permitted..

**Comment by joshtriplett** [comment]
@poettering Absolutely agreed; I'm wondering if it should be hooked in at mount time, though. Rather than "do this right away, with an automount under it", it could be "mount this when needed, and when you mount it, do this before you consider the mount done". (Whether the mount unit triggers a tmpfiles invocation for paths under the mount point, or handles this internally, either way works.)

**Comment by poettering** [comment]
Closing as #6506 was merged.
