### ISSUE TITLE
Reliable sd_pid_notify_with_fds()

### ISSUE THREAD

**Issue by DemiMarie** [systemd/systemd#19646]
**Is your feature request related to a problem? Please describe.**
Some daemons need to store file descriptors in a location where they will never, ever be closed, even if the service is stopped.  Closing the file descriptors would result in a use after free of an important resources, such as a loop device or listening socket.  libxl and RPC port mappers are two services that could use this feature.

**Describe the solution you'd like**
A service configuration setting to *not* close file descriptors (stored with `sd_pid_notify_with_fds()`) when the service is stopped.  Furthermore, this setting would disable all automatic closing of the file descriptors by systemd.

**Describe alternatives you've considered**
A way to ensure that a process cannot be killed, even by OOM or SIGKILL.

**The systemd version you checked that didn't have the feature you are asking for**

**Comment by poettering** [comment]
I am a bit concerned of basically eternally pinning such resources. Every resource needs some kind of lifecycle definition, when it is cleaned up. For example, we try hard to introduce lifecycle definitions for stuff such as Sysv SHM/SEM stuff, via logind, so that they don't stay around forever with no mechinism to clean them up. Similar /tmp and and son...

What's your precise usecase? Why can't it be solved with a service that does RemainAfterExit=? That way you could upload your fds, and they'd stick around until the service itself is closed, but the service wouldn't go down when the service processes do.

why do you need to store an fd of a loop device? (and what is libxl?)

i.e. i think any new concept or tweaked concept we add needs to have clearly defined lifecycle semantics, and I don't think we should support a way to exclude things from any form of lifecycle management.

**Comment by DemiMarie** [comment]
> I am a bit concerned of basically eternally pinning such resources. Every resource needs some kind of lifecycle definition, when it is cleaned up. For example, we try hard to introduce lifecycle definitions for stuff such as Sysv SHM/SEM stuff, via logind, so that they don't stay around forever with no mechinism to clean them up. Similar /tmp and and son...

That is valid!  In this case, I do want to clean up the resources, but only the service can clean them up safely.

> What's your precise usecase? Why can't it be solved with a service that does RemainAfterExit=? That way you could upload your fds, and they'd stick around until the service itself is closed, but the service wouldn't go down when the service processes do.

I need to keep some file descriptors open between when the service is stopped and when it is subsequently started.  Failing to do so would result in leaked loop devices.

> why do you need to store an fd of a loop device?

I need to store the fd so that I can destroy the loop device when it is no longer in use.  If the file descriptor was closed, I would no longer be able to destroy the loop device without risking race conditions.  Therefore, I would have no choice but to leak it, which would be bad.  The loop devices are used to provide backing storage for Xen virtual machines, which (like the loop devices themselves) have kernel persistence.

> (and what is libxl?)

libxl, or libxenlight, is a common toolstack library for Xen.  Qubes OS uses Xen to provide isolation.

> i.e. i think any new concept or tweaked concept we add needs to have clearly defined lifecycle semantics, and I don't think we should support a way to exclude things from any form of lifecycle management.

The only safe time to close the file descriptors would be if `ExecStopPost=` has succeeded (not just run).

**Comment by poettering** [comment]
This is actually available these days, in the FileDescriptorStorePreserve=yes service setting.
