### ISSUE TITLE
user@.service and user's private units.

### ISSUE THREAD

**Issue by alxchk** [systemd/systemd#19644]
Recently I met a problem with my setup, which was initially quite hard to trace out, mostly because of misunderstanding of  a sequence of actions which happens during the boot and session logon.

The problem looks like this.
1. I have private units in ~/.config/systemd/user/ and default.target among them
2. Some units, which expected to run during user instance active, and which are not related to UI (like tmux) expected to start as dependencies for default.target. They are placed to ~/.config/systemd/user/default.target.wants
3. I have home directory encrypted
4. I expect that using system login pam_fscrypt will "decrypt" my home folder and pam_systemd will triggher user@.service launch [WRONG]
5. I expect that user@.service will call systemd --user, which will read ~/.config/systemd/user/.. launch default.target and it deps [WRONG]

So, it turns out, that user@.service is launched /before/ any actual login. As home directory is encrypted, obviously systemd reads default.target (which is empty). After login nothing happens, as systemd expected that default.target already reached. 

So.. There should be the way to handle this? It's pretty expected situation, when home directory is not fully available before login (encrypted or remote storage, whatever). I'm not sure that starting user@.service before any actual login is really valid way to do things, but even it is, there should be some way to trigger reload. At least from pam_systemd. Something like "reload configuration and if any updates handle them". Initially I tried to trigger reload from pam_script. Using SIGHUP it's possible to reload, using  SIGRTMIN+0 it's possible to isolate default.target. But as default.target is already reached (with default state), this doesn't help the situation. Starting systemctl from pam_script is also ugly idea, as it needs to communicate with user instance, so needs to change privileges, which will trigger pam, which may trigger loop.. So, ugly things. The best way to solve likely to add additional target, which will be triggered by pam_systemd. Or to change logic of starting user@.service. Or something like that.

**Comment by poettering** [comment]
fscrypt is weird, as it requires the access keys in the keyring of the process doing the accesses. Semantically it actually makes little sense to do that though. I don't know pam_fscrypt, but if it is not capable of pushing the decryption keys from the original PAM session into the background session that user@.service runs, then it is simply incompatible with systemd.

Note that systemd-homed also supports fscrypt, and it doesn#t suffer by this issue, it properly propagates the key to the necessary keyrings of all active PAM sessions.

Either way, this is something to bring up with the pam_fscrypt people. If they intend to be compatible with systemd they need to make sure the keys are properly propagated from the original PAM session to the user@.service one, like systemd-homed does it.

Hence, closing, since there's a clear approach how to handle this, except that pam_fscrypt might not do that, but that's not actionable to us.

**Comment by alxchk** [comment]
Well. Fscrypt doesn't plays a first role here. It may be pam_mount, or pam_whatever. The question is why user@.service started before actual session ever started? And, if it's supposed to work this way, how exactly this should deal with user units, which does not exist yet (because storage will be attached only after user logged in).
