### ISSUE TITLE
RFE: Support multiple ESPs for mirrored-disk configurations

### ISSUE THREAD

**Issue by gregory-lee-bartholomew** [systemd/systemd#19668]
**Is your feature request related to a problem? Please describe.**
Mirrored system drive configurations are popular for their redundancy and greater read performance. Software mirroring (btrfs, zfs, mdadm) can be used to mirror most system partitions, but they cannot mirror the ESP. This breaks the desired redundancy that one would otherwise get when mirroring their system drive on UEFI systems. Currently, if a drive fails on a software-mirrored UEFI system, the system will be unbootable if the drive that failed contained the ESP.

**Describe the solution you'd like**
Since normal software-mirroring does not work on ESPs, I'd like systemd's bootctl and kernel-install commands to handle updating multiple ESPs.

**Describe alternatives you've considered**
An obvious solution is to write a script that rsyncs a "primary" ESP to all the other known or detected ESPs on successful boot. I've attempted to implement such a script [here](https://github.com/gregory-lee-bartholomew/bootsync). But I ran afoul of changes that were subsequently made to systemd's 90-loaderentry.install script (the addition of the stat command broke things because my script required /boot to be a symlink to the "primary" ESP).

**The systemd version you checked that didn't have the feature you are asking for**
248.3 (on Fedora Linux 34). I've also searched for existing issues and pull requests and I found the following:

https://github.com/systemd/systemd/issues/12468
https://github.com/systemd/systemd/issues/17530
https://github.com/systemd/systemd/issues/17298

The above issues suggest that mirroring the ESP across multiple disks is not an uncommon desire.

**Comment by poettering** [comment]
Please see my comments here:
https://github.com/systemd/systemd/issues/12468#issuecomment-698782077

We can look into this, once EFI spec actually supports this concept. Otherwise it's just something that will constantly break, since writes can happen from any participant in the ESP, including boot loaders themselve (yes, both sd-boot and grub can write to the ESP, and do)
 
Sorry, but this is nothing we can safely support without explicit support from firmware + boot loaders. We are just one participant in the ESP.

**Comment by gregory-lee-bartholomew** [comment]
I guess I was thinking that everything on the ESP is just a file. If so, wouldn't rsyncing the contents of the ESP to one or more "backup" copies preserve everything, regardless of whether it was updated by the firmware or by systemd (or by any other OS on the system)? Is there a timing problem that I'm overlooking maybe (e.g. perhaps something like rsync would pickup a partially writen/updated file somehow if the firmware was writing to it after the Linux system had booted)? Otherwise, it seems like a system that essentially made a backup copy of the ESP after the system boots should work.

**Comment by poettering** [comment]
well, of course you can try to propagate changes made on the ESP from one copy to the other. but it's fragile to do so, because you never really know what the latest change is and what to do if you have conflicting changes on multiple ESPs.

sd-boot for example makes changes when boot assesment is used, i.e. when unsuccessful boots are counted for automatic fallback to older versions.

**Comment by poettering** [comment]
What precisely are you trying to solve? Usually people wo deploy RAID to this to increase reliability and data safety. Mirroring ESPs as you suggest or redefining ESPs in opposition to the specs i not going to do either.

**Comment by poettering** [comment]
> So is everything we need already implemented in the spec in a round-about way? If we label the backup ESP(s) as "Basic data partitions" (EBD0A0A2-B9E5-4433-87C0-68B6B72699C7) and set their read-only and shadow copy flags, would it then be a firmware/OS bug if something other than our backup software read from or wrote to them unexpectedly?

Firmware doesn't care about Windows partition types, and in particular not their flags. "Basic data partition" is a Windows thing, not an EFI thing.

But I still don't get what you are even trying to solve?

**Comment by arvidjaar** [comment]
> you never really know what the latest change is and what to do if you have conflicting changes on multiple ESPs

By this login you cannot install in ESP at all because you never know who will modify ESP.

If `bootctl --esp-path=/esp install` is valid invocation what exactly makes the second call `bootctl --esp-path=/esp1` invalid?

**Comment by gregory-lee-bartholomew** [comment]
There are designated namespaces/paths on a single ESP such that different programs know what their "territory" is. What is apparently missing is a way to designate a whole ESP for exclusive management (or at least read-only by all but the "backup" software).

What I really want is the ability to just swap in a replacement drive in the event of a failure and restore it "online" from the existing system. This used to work with BIOS, but doesn't with UEFI. I don't want to have to create an elaborate "rescue" disk with all the necessary drivers for my hardware and all the special software (e.g. zfs) that may be necessary to restore the mirroring. I should just be able to shutdown, swap out the bad drive, boot, and click a button to restore the replication. It isn't a high priority though. There are (more painful) ways to get such a system repaired.

**Comment by poettering** [comment]
> If `bootctl --esp-path=/esp install` is valid invocation what exactly makes the second call `bootctl --esp-path=/esp1` invalid?

THat's totally OK. But I don't think doing that is really considered "mirroring". Mirroring to means syncing one ESP to the other, i.e. migrating data from one ESP to the other. The two commands you suggested just update/install the boot loader to two ESPs, which is a very different concept.

**Comment by arvidjaar** [comment]
> The two commands you suggested just update/install the boot loader to two ESPs, which is a very different concept.

E-h-h ... did you actually try to read the original description before closing this issue?

>>**Since normal software-mirroring does not work on ESPs**, I'd like systemd's bootctl and kernel-install commands to **handle updating multiple ESPs**.

That is exactly what was requested - to transparently handle installation on several separate ESP.

**Comment by poettering** [comment]
hmm? but that's not what i'd call "mirroring"?

Running "booctl update --esp-path=" multiple times already exists, so what is missing then?

**Comment by gregory-lee-bartholomew** [comment]
I think kernel-install will only update one "/boot" directory on system update. Is there a way to get it to automatically maintain identical copies? For example, if I have two BLS type 1 partitions (ESP+XBOOTLDR) mounted to "/boot/0" and "/boot/1" what is the proper way to get the system to update both of them when the kernel is updated? My apologies if I'm overlooking something simple.

**Comment by kpfleming** [comment]
I realize this has been closed, but I'm in the same situation (and was heading in this direction due to the "You Got RAID" section of this blog post: https://0pointer.net/blog/linux-boot-partitions.html, which was published just a few weeks ago).

I have two systems that have only one operating system installed on them. That OS has complete control of the ESP contents. Each of them has dual drives holding the root filesystem, and there's a partition on each drive for the ESP too. The goal here is to enable the system to boot using the ESP on the second drive if the first drive fails. The ESP contents would thus be identical, or close to it (same machine-id, same kernels/initramfs, same loader entries), and the EFI variables would work against either ESP.

If bootctl and kernel-install (and any other relevant parts of systemd) supported a configuration file in /etc/systemd telling them not to do auto-discovery but to explicitly treat two (or more) paths as ESPs, and to duplicate the changes they make onto each of them, I'd be all set.

The result would be that systemd-boot-update.service would update both when a new version of sd-boot has been installed, and kernel-install would install/remove kernels/initramfs/UKIs on both.

If the community can agree on a design for this I'd be happy to do the implementation work. For now I'll need to use a boot-time rsync script as the OP indicated.
