### ISSUE TITLE
'org.freedesktop.systemd1' timed out still continues to happen (ubuntu 20.04). What was the resolution to the error below?

### ISSUE THREAD

**Issue by bagcheap** [systemd/systemd#19684]
**systemd version the issue has been seen with**
 > …

**Used distribution**
 > …

**Linux kernel version used** (`uname -a`)

 > `…`

**CPU architecture issue was seen on**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by bagcheap** [comment]
The issue is not resolved by **systemctl daemon-reload** or **systemctl daemon-reexec** or **kill 1**

It shows up every time I try to run sudo apt upgrade on my new install of Ubuntu 20.04. 

Not repeating a lot of the information already shared by earlier discussion of this issue.

Would appreciate any help I can get!

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
