### ISSUE TITLE
LUKS password prompt prints my actual password as I type instead of echoing asterisks!

### ISSUE THREAD

**Issue by barmadrid** [systemd/systemd#19696]
**systemd version the issue has been seen with**
 > systemd 248.3-2

**Used distribution**
 > Arch Linux

**Linux kernel version used**
 > linux 5.12.5.arch1-1

**Initrd**
 > Dracut

**CPU architecture issue was seen on**
 > AMD Ryzen 3400G (x86_64) 

**Expected behaviour you didn't see**
 > Echo asterisks as I type instead of my real password

**Unexpected behaviour you saw**
 > I see my password as I'm typing 

**Steps to reproduce the problem**
 > Power on (restart) your machine and try to type your LUKS passphrase at the prompt to unlock

**Comment by poettering** [comment]
are you sure that it is systemd that queries for the password? are you using plymouth or so?

I'd prefer if you'd contact the arch community about this first, as this feels very much like an integration issue to me. i.e. something between the kernel, console handling, loading DRM drivers, used boot splash, initrd. The code to query passwords is pretty simple in systemd, and we actually have no code to output the literal password. so there's nothing in our codebase that could accidentally be turned on, because such code does not exist.

My guess is that either plymouth is in the mix, or something turns on echo on the VT concurrently to us prompting on it with turned off echo. Your goal wouldbe to find out what triggers that, but that's really not something we cn help you much with.

hence, please ping the archlinux guys. if they determine there's an actual systemd bug somewhere, they'll propagate this to us again. But i doubt there is...

thank you dor understanding.
