### ISSUE TITLE
message catalog for "unit failed" references UNIT= journal field even for --user units, where it should reference USER_UNIT=

### ISSUE THREAD

**Issue by mineo** [systemd/systemd#1972]
I have the following user unit file in `~/.config/systemd/user`:

```
[Unit]
Description=Hallo Welt!

[Service]
Type=oneshot
ExecStart=/usr/bin/true
EnvironmentFile=/%h/.config/helloworldconfigfile

[Install]
WantedBy=default.target
```

The EnvironmentFile doesn't exist.

`systemctl --user start hello` logs

```
Nov 20 23:10:29 slartibartfass systemd[1624]: hello.service: Failed to load environment files: No such file or directory
Nov 20 23:10:29 slartibartfass systemd[1624]: hello.service: Failed to run 'start' task: No such file or directory
Nov 20 23:10:29 slartibartfass systemd[1624]: Failed to start Hallo Welt!.
-- Subject: Unit UNIT has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has failed.
-- 
-- The result is failed.
Nov 20 23:10:29 slartibartfass systemd[1624]: hello.service: Failed with result 'resources'.
```

Instead of the real unit name, `UNIT` is used in several places.

/edit: Using

```
systemd 227
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN
```

on Arch Linux.

**Comment by keszybz** [comment]
Yeah, we use the same MESSAGE_ID for --user and --system modes, but different meta-data fields. Most likely we should use a different MESSAGE_ID for user units.

**Comment by poettering** [comment]
@keszybz hmm, this would mean adding new secondary message ids for pretty much all unit events, and then pick them when we are in --user mode...

Note sure I like that, especially since this would also mean we'd have to duplicate all catalog entries...

 Another option would be to make the templating engine smarter... Maybe allow writing this:

```
@FOO:BAR:WALDO:QUUX@
```

This would mean: replace this expression by field FOO if it exists. If not, replace it by BAR if it exists, and so on...

Then, we could fix the catalogs to always use `@USER:USER_UNIT@` to and could stick to the same message ids and catalog entries as before. I think I much prefer this approach.

**Comment by keszybz** [comment]
+1

**Comment by keszybz** [comment]
Let's close this and continue in #3351. Funny how the same ideas resurface.
