### ISSUE TITLE
cryptsetup: add configurable timeout for waiting for security token insertion during boot

### ISSUE THREAD

**Issue by sza-1** [systemd/systemd#19739]
**Is your feature request related to a problem? Please describe.**
It seems that currently there is not simple way to unlock LUKS volume when pkcs11-uri=auto specified in /etc/crypttab for the volume.

It is a painful situation when you lost the security token and need to unlock the root volume on boot.

systemd-cryptsetup displays 'Security token XXX not present for unlocking volume test, please plug it in.' and wait for the token. At least I did not figure out the simple way to skip this request and fallback to the password or keyfile.

**Describe the solution you'd like**
Probably systemd-cryptsetup should silently fallback to the password or keyfile authentication method.

**Describe alternatives you've considered**
Optionally systemd-cryptsetup can fallback the password or keyfile authentication method only if token-timeout (or even just keyfile-timeout) specified.

**The systemd version you checked that didn't have the feature you are asking for**
systemd 248

**Comment by boudekerk** [comment]
I think it's the same for fido2-device=auto. Would also like a fallback or even a user choice from all available methods (that have been configured for a slot)

**Comment by poettering** [comment]
the problem is that during boot hardware pops up continously. i.e. disk drivers show up and we try to activate them, and concurrently hid devices show up. If we'd check for HID/FIDO2/PKCS11 devices only at the moment we try to activate a LUKS device, then this would be very unreliable, since there's a major chance the security device isn't probed yet, but will be instants later.

So, to fix this we actively have to wait for the device to show up.

Now, we certainly should add a timeout for this. I was thinking about adding support for asking for pw and security token insertion simultaneously. But that sucks a bit, since this might mean we might suddenly change the prompt from asking for pw to asking for PIN once the security token is detected.

**Comment by crazyh** [comment]
@poettering yeah, I believe that timeout would be enough.

Also there can be a simply solution: stop waiting for security token early if user pressed some key ('Q' etc).

As a quick fix a new bootloader option like 'rd.luks.options=UUID=pkcs11-uri=ignore' can be implemented. So user can temporary add this option to kernel cmdline and boot system without token.

**Comment by boudekerk** [comment]
> Now, we certainly should add a timeout for this. I was thinking about adding support for asking for pw and security token insertion simultaneously. But that sucks a bit, since this might mean we might suddenly change the prompt from asking for pw to asking for PIN once the security token is detected.

How about user choice, i.e. asking the user which (configured) slot they'd want to use?
 This would also "solve" / provide a workaround for: https://github.com/systemd/systemd/issues/19208

**Comment by boudekerk** [comment]
I think it's different enough from the original request here, so I've created a new ticket for my suggestion: #19764 

Of course feel free to close if you disagree with it warranting a separate ticket.
