### ISSUE TITLE
cgroup compatibility translation between legacy and unified hierarchy settings activated

### ISSUE THREAD

**Issue by celcan** [systemd/systemd#19748]
**systemd version the issue has been seen with**
 >systemd 247.4+

**Used distribution**
 > https://github.com/systemd/systemd-stable/releases/tag/v247.4

**Linux kernel version used** (`uname -a`)

 > `Linux 4.9.216`

**CPU architecture issue was seen on**
 > ARMv7

**Expected behaviour you didn't see**
 > No warning message related to cgroup compatibility

**Unexpected behaviour you saw**
 > [ WARNING ] systemd[1]: cgroup compatibility translation between legacy and unified hierarchy settings activated. See cgroup-compat debug messages for details.

**Steps to reproduce the problem**
 > At boot, after every reboot operation.

**Additional program output to the terminal or log subsystem illustrating the issue**

```
We have upgraded the systemd to v247.4 recently and seen this warning message.
We are not sure what the root cause is to get this message.
Do you have a chance to point out where and what we need to look at?
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by celcan** [comment]
Thanks
