### ISSUE TITLE
What is `systemd-analyze blame` algorithm

### ISSUE THREAD

**Issue by 4l1fe** [systemd/systemd#19745]
It seems Github to be not a proper place for such a question, but i didn't find a better place to ask if there is a specification of the subject?

I wanna try to collect my laptop bootload statistic and `system-analyze blame` gives all the information i need BUT for the latest bootload only. As far as i understand such information is extracting from _systemd journal logs_(start point is [`static int analyze_blame`](https://github.com/systemd/systemd/blob/2d8c8549abd306b19a99dc7735bcb4b252eab6d9/src/analyze/analyze.c#L1058))  and it's possible to _somehow_ extract all **blame reports** from very a journal beginning.

Here is my question about it on [unix.stackexchange.com](https://unix.stackexchange.com/questions/645584/how-to-list-systemd-analyze-blame-chronological-records).

Any advice is appreciable.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
