### ISSUE TITLE
what is the order in which systemd .device units are created ?

### ISSUE THREAD

**Issue by lakabd** [systemd/systemd#19778]
Maybe this is not the right place to ask my question, but frankly, even though I've browsed through a lot of resources I haven't found a satisfying answer. I've been trying to minimize the booting time in the user land on my embedded board, and when I run the classic `systemd-analyze plot > plot.svg` I see that there is a non-negligible slot of time in which systemd creates only device units (that were discovered via udev).

My problem is in the order in which these device units are created, specially for the block device that contains my rootfs. What i noticed is that when these device units are created, the one corresponding to my rootfs blockdev is always the last one created, causing the other services depending on it to wait much more than if it was created earlier. 

So, I would like to know if systemd follows a special order when creating these units, and if yes, what can I do so the device unit of my rootfs blockdev can be the first one created ?

(Btw if you know a better place to ask my question please just let me know in a comment so I could ask the question there and remove this one, in order to not mess too much).

Any help is greatly appreciated.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
