### ISSUE TITLE
strace systemd seems in infinit looping state

### ISSUE THREAD

**Issue by cmingxu** [systemd/systemd#19782]
Hi, All 

systemd process CPU usage upto 100% on single core, which probably make other **systemd_run** process stuck.  My systemd version is 239 and the following is strace result.

openat(AT_FDCWD, "/usr/lib/systemd/system/systemd-coredump@.service", O_RDONLY|O_NOCTTY|O_NOFOLLOW|O_CLOEXEC) = 16
fcntl(16, F_GETFL)                      = 0x28000 (flags O_RDONLY|O_LARGEFILE|O_NOFOLLOW)
fstat(16, {st_mode=S_IFREG|0644, st_size=1104, ...}) = 0
fstat(16, {st_mode=S_IFREG|0644, st_size=1104, ...}) = 0
fstat(16, {st_mode=S_IFREG|0644, st_size=1104, ...}) = 0
read(16, "#  SPDX-License-Identifier: LGPL"..., 4096) = 1104
getrandom("\x4a\x5d\x50\xdb\x2c\x0e\xcc\x5d\x86\x55\x2b\x53\x3b\xa5\x28\xab", 16, GRND_NONBLOCK) = 16
getrandom("\x81\xb0\x2e\x65\xd3\x5e\x80\xc4\x3e\xa7\x9a\x88\x33\xb3\xa9\x96", 16, GRND_NONBLOCK) = 16
getrandom("\x64\x7b\x28\x44\x74\x08\xfe\x23\x30\xd9\x59\xf5\xa7\x0b\xd4\xf3", 16, GRND_NONBLOCK) = 16
getrandom("\xc8\x16\x96\x4f\x4a\x63\x32\x1e\xc8\x84\xbe\xd8\x96\x04\x05\xfc", 16, GRND_NONBLOCK) = 16
getrandom("\xe0\xc7\xc5\x34\x79\x0a\x85\xda\xd4\x37\x4d\xa0\x37\x1c\x85\xa9", 16, GRND_NONBLOCK) = 16
getrandom("\x84\x67\x53\xd6\xdf\xd4\x25\x15\x19\x3a\x54\xbc\x5b\x7c\xd7\xbd", 16, GRND_NONBLOCK) = 16
read(16, "", 4096)                      = 0
close(16)

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
