### ISSUE TITLE
systemd-shutdown[1]: Failed to finalize MD devices, ignoring.

### ISSUE THREAD

**Issue by Gooberpatrol66** [systemd/systemd#19812]
**systemd version the issue has been seen with**
 > systemd-247.2

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)

 > `Linux gentooserver 5.10.27-gentoo-x86_64 #2 SMP PREEMPT Sun May 2 12:54:53 CDT 2021 x86_64 Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz GenuineIntel GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Systemd stops mdadm devices on shutdown

**Unexpected behaviour you saw**
 > Systemd fails to stop mdadm devices on shutdown

**Steps to reproduce the problem**
 > …

**Additional program output to the terminal or log subsystem illustrating the issue**

```
systemd-shutdown[1]: Could not stop MD /dev/md127: Device or resource busy
systemd-shutdown[1]: Failed to finalize MD devices, ignoring.
…
```

**Comment by poettering** [comment]
What is that MD device used for? Is your root fs mounted from that? If so, it's not surprising it remains busy till the end.

The general approach to allow disassembly of storage that is backing the root fs is to provide the right hooks in the initrd so that systemd can return into the initrd on shutdown, and the initrd then disassembles what it initially set up.

Either way, this is no a systemd problems. It's a matter how your distro, in particular your initrd is set up. Please contact your distro for help.
