### ISSUE TITLE
networkd v228 running DHCPv6 when it shouldn't

### ISSUE THREAD

**Issue by esmil** [systemd/systemd#1982]
```
root@rodent~# cat /etc/systemd/network/enp.network 
[Match]
Name=enp*

[Network]
DHCP=ipv4
LinkLocalAddressing=true
root@rodent~# journalctl -u systemd-networkd
-- Logs begin at Sun 2015-11-22 12:24:23 UTC, end at Sun 2015-11-22 12:39:23 UTC. --
Nov 22 12:24:27 rodent systemd[1]: Starting Network Service...
Nov 22 12:24:27 rodent systemd-networkd[356]: Enumeration completed
Nov 22 12:24:27 rodent systemd[1]: Started Network Service.
Nov 22 12:24:27 rodent systemd-networkd[356]: enp0s18: Gained carrier
Nov 22 12:24:27 rodent systemd-networkd[356]: enp0s18: DHCPv4 address 192.168.7.16/24 via 192.168.7.2
Nov 22 12:24:28 rodent systemd-networkd[356]: enp0s18: Could not set hostname: Permission denied
Nov 22 12:24:29 rodent systemd-networkd[356]: enp0s18: Gained IPv6LL
Nov 22 12:24:41 rodent systemd-networkd[356]: enp0s18: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
Nov 22 12:24:41 rodent systemd-networkd[356]: enp0s18: Configured
```

Notice the "Starting DHCPv6 client after NDisc timeout failed: Invalid argument" message.

**Comment by sitsofe** [comment]
@esmil: Are you sure this isn't handled by the caveat in the [systemd.network man page](http://www.freedesktop.org/software/systemd/man/systemd.network.html#[Network] Section Options)?

**Comment by esmil** [comment]
@sitsofe Ah yeah. I think you're right. That's new in 228.

In that case there really ought to be some way to disable DHCPv6 completely - or at least an option to tell networkd to "GTFO" (as the source says) and let the kernel do it's work as it used to.

**Comment by sitsofe** [comment]
@esmil From the link above does setting `IPv6AcceptRouterAdvertisements` help?

**Comment by esmil** [comment]
IPv6AcceptRouterAdvertisements=false seems to prevent it doing DHCPv6, but it also sets net.ipv6.conf.enp0s18.accept_ra = 0, which prevents to kernel from accepting RAs.

**Comment by poettering** [comment]
Most likely you are on a network when RA declares that clients have to use DHCPv6 to get configuration data. I think in that case we actually do what it says and enable DHCPv6. But @teg knows more...

**Comment by thx1111** [comment]
The "IPForward=kernel" option appears to have been removed, and man 5 systemd.network also has:
DHCP=
... Note that DHCPv6 will by default be triggered by Router Advertisment, if that is enabled, regardless of this parameter.  ...
IPv6AcceptRouterAdvertisements=
... When router advertisements are accepted, they will trigger the start of the DHCPv6 client if the relevant flags are passed, or if no routers are found on the link.  ...

The networkd DHCPv6 client is still unable to configure a working "Managed" IPv6 address, and does not provide Prefix Delegation.  The only way to properly configure network interfaces for IPv6 is with a traditional working DHCPv6 client, such as WIDE-dhcp6c or dibbler, or even "dhclient -6" or dhcpcd.

With the most recent changes to networkd, because the  networkd DHCPv6 client interferes with IPv6 routes, with the log message "kernel: ICMPv6: RA: ndisc_router_discovery failed to add default route" and interferes with any other DHCPv6 client providing Prefix Delegation, and because it cannot be disabled while accept_ra != 0, then the only option is to disable systemd-networkd completely, such that the networkd IPv4 DHCP client also cannot be used.  Thus, systemd-networkd is entirely unusable now.

It seems to me that systemd-networkd is trying to solve the wrong problem.  There is no need to "re-invent the wheel" here.  DHCP and DHCPv6 clients already exist.  Rather, the practical problem, and the more interesting problem, for networkd to solve is the ability re-configure network interfaces for devices encountering a changing network environment.  The most obvious network challenge is disappearing and reappearing wireless and ethernet interface carriers.  More subtle network changes involve changing IPv6 Router Advertisements, for instance, involving changes in the M[anaged] or A[utonomous] flags.  Generally, networkd should be able to properly configure interfaces as a computer system moves between networks.  That would be worthwhile.  That is the kind of thing that systemd is otherwise very good at doing.

**Comment by j16sdiz** [comment]
Can I have `IPv6AcceptRouterAdvertisements` _without_ `DHCPv6`?
It is cause me lots of delay on system boot.

In my network, the router expect me send a DHCPv6 with a custom `DUID-LL`, the ra is correct.
Since systemd does not currently support custom clientidentifier (see systemd#394 ), the DHCP request fails after much timeout.

Would be nice if I can config `accept_ra` and `dhcp` independently.

**Comment by tomty89** [comment]
Experiencing similar issue here:

(DHCP=yes)
[tom@localhost ~]$ journalctl -b --unit systemd-networkd
-- Logs begin at Sat 2015-12-19 00:59:44 HKT, end at Sat 2015-12-19 03:25:24 HKT. --
Dec 19 03:24:54 localhost systemd[1]: Starting Network Service...
Dec 19 03:24:54 localhost systemd-networkd[206]: Enumeration completed
Dec 19 03:24:54 localhost systemd[1]: Started Network Service.
Dec 19 03:24:54 localhost systemd-networkd[206]: enp3s0: Renamed to eth0
Dec 19 03:24:54 localhost systemd-networkd[206]: eth0: Renamed to enp3s0
Dec 19 03:24:57 localhost systemd-networkd[206]: enp3s0: Gained carrier
Dec 19 03:24:57 localhost systemd-networkd[206]: enp3s0: DHCPv4 address 192.168.11.2/24 via 192.168.11.1
Dec 19 03:24:58 localhost systemd-networkd[206]: enp3s0: Gained IPv6LL
Dec 19 03:25:11 localhost systemd-networkd[206]: enp3s0: Configured

(DHCP=ipv4 / DHCP=v4)
[tom@localhost ~]$ journalctl -b -1 --unit systemd-networkd
-- Logs begin at Sat 2015-12-19 00:59:44 HKT, end at Sat 2015-12-19 03:25:24 HKT. --
Dec 19 03:22:51 localhost systemd[1]: Starting Network Service...
Dec 19 03:22:51 localhost systemd-networkd[197]: Enumeration completed
Dec 19 03:22:51 localhost systemd[1]: Started Network Service.
Dec 19 03:22:51 localhost systemd-networkd[197]: eth0: Renamed to enp3s0
Dec 19 03:22:54 localhost systemd-networkd[197]: enp3s0: Gained carrier
Dec 19 03:22:54 localhost systemd-networkd[197]: enp3s0: DHCPv4 address 192.168.11.2/24 via 192.168.11.1
Dec 19 03:22:55 localhost systemd-networkd[197]: enp3s0: Gained IPv6LL
Dec 19 03:23:08 localhost systemd-networkd[197]: enp3s0: Starting DHCPv6 client after NDisc timeout failed: Invalid argument
Dec 19 03:23:08 localhost systemd-networkd[197]: enp3s0: Configured
Dec 19 03:24:41 localhost systemd[1]: Stopping Network Service...
Dec 19 03:24:41 localhost systemd[1]: Stopped Network Service.

I believe my router has no support on IPv6 at all.

**Comment by ravenexp** [comment]
There should be a way to avoid "Starting DHCPv6 client after NDisc timeout failed: Invalid argument" message for every interface that goes online. Not many people use IPv6 on LANs.

**Comment by pengshao** [comment]
Luckily enough for me networkd was not able to parse RA sent from my ISP (while dhcpcd seemed to be able to do that just fine), so networkd will crash after a while and it won't effect the already-working ipv6 configuration set up by dhcpcd. I really have no idea what will happen if it actually worked: will it compete with dhcpcd to set up ipv6 and cause a total chaos?...

Please, consider `adding an option` to disable this built-in dhcpv6 function and let other dhcpv6 clients do their job. Or if it can work nicely like dhcpcd, wide or even dhclient then it should justify such enforcement as well and I will happily use it. But right now, for people using a Linux computer running systemd as an ipv6 home router obtaining pd from their ISP, this change from 227 to 228 is causing more trouble than merits...

Thanks.

**Comment by jonathanio** [comment]
I've started noticing some major issues with the DHCPv6 client in 228. Specifically:
- The DHCPv6 client doesn't seem to honour the `IPv6PrivacyExtensions` setting: Any address that is added to an interface is not added with the `mngtmpaddr` flag and as such privacy addresses are not created from it; and
- IPv6 addresses are not being added within virtual machines (libvirtd/qemu). `tcpdump` shows RA's being received by the system, and the default route is added to the IPv6 routing table, but no dynamic address is added to any interface and as such requests via IPv6 fail (_Destination unreachable: Beyond scope of source address_)

I still have an older host running 227 and IPv6 is working as expected there. I also have a VM guest on the same host machine running 208 (CentOS7) and that is having no issues either. These are all specific to 228.

IPv6 is now utterly broken for all my main use cases as a result of this change. DHCPv6 _must_ be disabled unless _specifically_ set until these issues are resolved when so many failings are apparent.

**Comment by tomty89** [comment]
@poettering:

> Most likely you are on a network when RA declares that clients have to use DHCPv6 to get configuration data. I think in that case we actually do what it says and enable DHCPv6. But @teg knows more...

I think "Starting DHCPv6 client after NDisc timeout failed" happens only when networkd failed to get any RA successfully, otherwise it would be "Starting DHCPv6 client on NDisc request failed" instead. The former apparently will only be triggered once, while the latter seems to keep going periodically. See #3256.

The two bugs may however be of the same nature:
https://github.com/systemd/systemd/blob/95adafc428b5b4be0ddd4d43a7b96658390388bc/src/network/networkd-ndisc.c#L142
https://github.com/systemd/systemd/blob/95adafc428b5b4be0ddd4d43a7b96658390388bc/src/network/networkd-ndisc.c#L192

I don't think the problem was ever "networkd running DHCPv6 when it shouldn't", but actually "networkd fails to start DHCPv6 whenever it is not enabled explicitly". This is even more obvious while `DHCP=ipv6` or `DHCP=yes` can prevent both cases.

`systemd.network(5)`:

> Note that DHCPv6 will by default be triggered by Router Advertisement, if that is enabled, regardless of this parameter. By enabling DHCPv6 support explicitly, the DHCPv6 client will be started regardless of the presence of routers on the link, or what flags the routers pass. See "IPv6AcceptRouterAdvertisements=".

**Comment by yuwata** [comment]
Version 246 has `DHCPv6Client=` setting in `[IPv6AcceptRA]` section to control whether DHCPv6 client should start or not. Moreover, no DHCPv6 response should not delay booting anymore if DHCPv4 or NDisc provides IP addresses. Closing.
