### ISSUE TITLE
systemd-growfs: please add check from resize2fs regarding sparse_super2

### ISSUE THREAD

**Issue by joshtriplett** [systemd/systemd#19830]
**systemd version the issue has been seen with**
 > latest git

**Linux kernel version used** (`uname -a`)
 > `Linux localhost 5.12.8 #1 SMP Tue Jun 1 19:00:47 PDT 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Steps to reproduce the problem**
Use `mkfs.ext4` with the `-O sparse_super2` option to make a small ext4 filesystem (e.g. 64M). Resize the containing device/file to be much larger (e.g. 30G). Use systemd-growfs to resize it.

The `resize2fs` tool has a check to see if the kernel supports resizing ext4 filesystems with the `sparse_super2` option enabled; it checks `/sys/fs/ext4/features/sparse_super2` first. `systemd-growfs` doesn't have that check; it just calls the `ioctl`. In current kernels, that ioctl will fail with EINVAL and only partially resize the filesystem. In that case, dmesg will show some errors, but those errors will not in any way point towards the `sparse_super2` filesystem feature.

Please consider either adding a check similar to the one in resize2fs, or alternatively, improving the kernel error messages to better identify the problem to aid in debugging.

**Comment by poettering** [comment]
not sure I follow?  `sparse_super2` appears to be around since kernel 3.16 times, not sure we should add checks for such old features to systemd still? Your kernel is 5.12 yet you are lacking that feature?

isn't this a kernel bug? i.e. allowing the ioctl to incorrectly resize the file system is a bug no?

**Comment by joshtriplett** [comment]
`sparse_super2` has been around for a long time, but while the kernel supports mounting such a filesystem, no version of the kernel supports resizing it.

**Comment by poettering** [comment]
But isn't it a kernel bug if the kernel tries anyway? sholdn't it just say EOPNOTSUPP or so?

**Comment by joshtriplett** [comment]
@poettering The kernel does give an error code (EINVAL) and doesn't complete the resize, but the kernel gives no clear indication of *why* it failed. I absolutely agree that the kernel *should* give a better error message. I'm just suggesting that it might be worth checking if the filesystem has `sparse_super2` and `/sys/fs/ext4/features/sparse_super2` doesn't exist, and giving a helpful error message from systemd-growfs in that case.

If you'd prefer to leave this entirely to the kernel, and just report the error code and suggest that the user go look at dmesg, that's fine. I wanted to report this here because it's a helpful check that resize2fs does and systemd-growfs doesn't; the error message from the former was how I ultimately diagnosed this issue.

**Comment by poettering** [comment]
Ah, so nothing bad actually happens at all, this is simply about improving logging?

Note that we cannot really test for the superblock flags, unless we implement explicit support for reading and parsing the superblock ourselves. Not sure how much I like that. So far we didn't access the block device itself, the ioctls operate on the fs level after all, not the block level.

Adding such a warning kinda sucks though since once the kernel gains support for resizing fs with this flags we'll generate a misleading error message, no?

**Comment by poettering** [comment]
Did I get this right: `/sys/fs/ext4/features/sparse_super2` doesn't indicate whether the kernel supports *mounting* sparse_super2 enabled file systems, but indicates whether it supports *resizing* them? That's so weird, i.e. not having the "resizing" in the feature name.

Moreover, if I grok this right, the file doesn't actually exist at all because no existing kernel actually implements the feature? So the flag file is about a "future feature" that might or might not exist one day, and the flag file is very poorly named? kinda makes me want to stay away from it...

**Comment by joshtriplett** [comment]
> Ah, so nothing bad actually happens at all, this is simply about improving logging?

As far as I can tell, the attempted resize appears to cause minor filesystem corruption according to e2fsck. (e2fsck doesn't seem to have any trouble fixing the filesystem, though.)

> Note that we cannot really test for the superblock flags, unless we implement explicit support for reading and parsing the superblock ourselves.

Yeah, that's fair. Having to manually read and parse the superblock doesn't really seem like something systemd-growfs should have to do. Please feel free to close this.

I've submitted a kernel patch to detect this case and give a better error message and error code.

**Comment by poettering** [comment]
> As far as I can tell, the attempted resize appears to cause minor filesystem corruption according to e2fsck. (e2fsck doesn't seem to have any trouble fixing the filesystem, though.)

Yikes! So the kernel accepts the resize request and then breaks stuff? That's bad, even if the corruption can be fixed easily in userspace. Sounds like a real kernel bug.

> Yeah, that's fair. Having to manually read and parse the superblock doesn't really seem like something systemd-growfs should have to do. Please feel free to close this.

OK, let's close.

> I've submitted a kernel patch to detect this case and give a better error message and error code.

Excelent! Thanks!
