### ISSUE TITLE
journalctl doesn't inform about a damaged journal

### ISSUE THREAD

**Issue by tobwen** [systemd/systemd#19875]
**systemd version the issue has been seen with**
 > systemd 247 (247.3-5)

**Used distribution**
 > Debian Bullseye RC1

**Linux kernel version used** (`uname -a`)
 > `Linux debian 5.12.6-051206-generic #202105221033 SMP Sat May 22 11:04:48 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > AMD64

**Expected behaviour you didn't see**
 > any kind of error message that the current journal has an issue

**Unexpected behaviour you saw**
 > no error message, error code is zero...

**Steps to reproduce the problem**
 > 1. edit an existing journal file with your favorite editor (just mess around somewhere in the middle)
 > 2. `journalctl --file=broken.journal -o export >/dev/null`
> 3. `echo $?` is 0

**Additional program output to the terminal or log subsystem illustrating the issue**
```sh
# journalctl --file=broken.journal --verify
390c30: Invalid hash (8cdec34d38af4c0d vs. 8cdec34d38af4c0a
390c30: Invalid object contents: Bad message
File corruption detected at broken.journal:390c30 (of 8388609 bytes, 44%).
FAIL: broken.journal (Bad message)
```

**Comment by tobwen** [comment]
Wow, this issue is ages old... https://bugzilla.redhat.com/show_bug.cgi?id=1157350

**Comment by poettering** [comment]
Log files can get corrupted if the system is shutdown abnormally, but we handle that gracefully: on next boot we move the files away and read them to the point they are still good, and only write to fresh new files. These corruptions are hence not really an issue, and don't really need fixing: the journal parser is supposed to handle them as well as possible, implicitly. Only if you really ask for it (i.e. use "--verify") we'll tell you these corruptions. 

Compare with the situation for traditional text log files: like journal files they are typically not explicitly synced to disk hence might be corrupted too/incompletely written if the system shuts down abnormally. The difference between those and our journal files is that we can detect many of the corruptions and then only consider the "good part" of the files, while for text log files there's no such logic and if you look at corrupted files you'll see the corruptions as they are.

or to say this differently: incompletely synced log files haven#t been considered an issue before (in text logging era), and we try to follow that same logic, since there are plenty systems where abnormal shutdowns are the norm and we must make the best of it. If we'd start immediately complaining about every single half synced log file people would seriously be upset, because it's such a frequent thing to happen.

Note that journald actually does fsync() after writing high-priority log messages. i.e. while we gracefully accept corruptions we still try to minimize them when it really matters, as an attempt of finding a compromise between data integrity needs, performance and reliability.

Anyway, this has come up before, but I am still pretty sure we shouldn't generate unnecessary warnings for something that simply is a very very common case.
