### ISSUE TITLE
Remove specific journal file filter

### ISSUE THREAD

**Issue by mihirbhat** [systemd/systemd#19953]
Hi Team,

I am using sd_journal_add_match() API to add filter into journal files. Is there any way to remove/modify existing filter rather than remove all using sd_journal_flush_matches().

For example :

Current method:

To remove F_3 : 
sd_journal_add_match( j , "F_1" , 4);  
sd_journal_add_match( j , "F_2" , 4);  
sd_journal_add_match( j , "F_3" , 4);   
sd_journal_add_match( j , "F_4" , 4);
.....

sd_journal_flush_matches().

sd_journal_add_match( j , "F_1" , 4);  
sd_journal_add_match( j , "F_2" , 4); 
sd_journal_add_match( j , "F_4" , 4);
.... N Filters

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
