### ISSUE TITLE
Typo in systemd.timer manpage

### ISSUE THREAD

**Issue by Yvan-Masson** [systemd/systemd#19994]
Hi,

I think there are two similar typos in the current `systemd.timer` manpage. It looks like a wrong copy/paste but I am not an English native so please apologize if I am wrong:

```
<row>
    <entry><varname>OnUnitActiveSec=</varname></entry>
    <entry>Defines a timer relative to when the unit the timer unit is activating was last activated.</entry>
</row>
<row>
    <entry><varname>OnUnitInactiveSec=</varname></entry>
    <entry>Defines a timer relative to when the unit the timer unit is activating was last deactivated.</entry>
</row>
```

Regards,
Yvan

**Comment by mbiebl** [comment]
which typo/word exactly do you mean?

**Comment by mbiebl** [comment]
I admit the sentence might be a bit hard to grasp, but I don't see a typo. Can you elaborate?

**Comment by Yvan-Masson** [comment]
Hi @mbiebl,
The same construction is repeated in the two sentences:
```
Defines a timer relative to when the unit the timer unit is activating was last activated.
```
If I understand properly the intended meaning (this is why I read the manpage :-D), I would have simply written something like:
```
Defines a timer relative to when the unit was last activated.
```

**Comment by keszybz** [comment]
There are two units here: the timer unit and the unit the timer unit is activating. We have to be clear which of the two is meant. Your shorter sentence would probably be interpreted as "unit" referring to the timer. The sentence is indeed not easy to grasp, but it is correct and necessary. If you find a better wording that retains the meaning, please suggest a patch. I'll close the issue, since there's no bug.

**Comment by Yvan-Masson** [comment]
OK, sorry for the noise.
Regards,
Yvan
