### ISSUE TITLE
cgroup v2 doesn't delegate controllers

### ISSUE THREAD

**Issue by globin** [systemd/systemd#20026]
**systemd version the issue has been seen with**
 > systemd 248.3
 > systemd 247.6

**Used distribution**
 > 248.3 on fedora 34
 > 247 on NixOS master

**Linux kernel version used** (`uname -a`)
 > 5.12.11
 > 5.10.45

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `cpu` written to `/sys/fs/cgroup/system.slice/delegate-test.service/cgroup.subtree_control`

**Unexpected behaviour you saw**
 > `/sys/fs/cgroup/system.slice/delegate-test.service/cgroup.subtree_control` is empty

**Steps to reproduce the problem**
 > sudo systemd-run -u delegate-test -p Delegate=cpu sleep 1200000000

Same issue with
 > sudo systemd-run -u delegate-test -p Delegate=yes sleep 1200000000

**Additional program output to the terminal or log subsystem illustrating the issue**
No relevant output found

**Comment by poettering** [comment]
that's not how this works. If you turn delegation on this means two things:

1. we make sure the requested controller is enabled for your cgroup (i.e. shows up in you cgroup's `cgroup.controllers`).
2. and we ensure your service's user gets write access to delegate the controller further down (i.e. `cgroup.subtree_controller` is owned by your user.)

i.e. no changes on the contents for cgroup.subtree_controller are made if delegation is truned on, because that's for you to control yourself. i.e. you get the rights to make the changes yourself this way, but we won#t make them for you.

Anyway, this is a not a support forum. if you have further questions about using cgroupsv2 with systemd, please direct them to the systemd mailing list or so.

**Comment by hxysayhi** [comment]
If I modify the value of subtree_control, then when I restart the service, systemd will try to overwrite the value of subtree_control. For example, if I add a `cpu` controller to subtree_control, systemd will remove it from subtree_control when the service is restarted. If I create a subdirectory at this time, and there are still processes in the subgroup when restarting, the startup will fail. The error is as follows:   
```
Control process exited, code=exited, status=219/CGROUP
...
Unit process 543222  (xxx) remains running after unit stoped.
....
```
Which seems to be a failure when rewriting the subtree_control. 

I want to manage subtree_control by myself when delegation is turned on, I hope systemd doesn't modify it.

Is there any way to solve this problem, please?
