### ISSUE TITLE
Autostart not working in KDE with systemd boot after changing my $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by kumikooumae** [systemd/systemd#20049]
**systemd version the issue has been seen with**
 > 248.3

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `Linux fedora 5.12.12-300.fc34.x86_64 #1 SMP Fri Jun 18 14:30:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > In KDE Plasma, after enabling systemd boot, desktop files in $XDG_CONFIG_HOME/autostart should autostart even after $XDG_CONFIG_HOME is changed in environment variable.

**Unexpected behaviour you saw**
 > I changed my $XDG_CONFIG_HOME to another path, and placed desktop file in $XDG_CONFIG_HOME/autostart. The program won't autostart in KDE. However if I manually create ~/.config/autostart and put desktop file in it, the program can autostart with KDE. If I disable systemd boot by running "kwriteconfig5 --file startkderc --group General --key systemdBoot false", desktop files in $XDG_CONFIG_HOME/autostart can autostart.

**Steps to reproduce the problem**
 > Change $XDG_CONFIG_HOME in your profile and placed desktop file in $XDG_CONFIG_HOME/autostart, then reboot

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
I did not see any useful information about autostart in log
```

**Comment by poettering** [comment]
how did you change XDG_CONFIG_HOME precisely? what do you mean by "profile"? the `~/.profile` file? that's a file only bourne shells read, but systemd is not a bourne shell and not a child of one either.

if you want to set an env var for the systemd per-user service manager, so that it honours that you could set that via pam_env or similar. Or you could add a dropin `/etc/systemd/system/user@.service.d/local.conf` or so.

But key really is: it's not sufficient to set an env var for your bourne shell if you want it to apply to systemd per-user service manager, because that doesn't interpret shell. 

Let's close this. The only way we could possible support honouring shell variales if we'd wrap systemd --user in a shell script that sources in ~/.profile, but I am pretty sure we shouldn't do that, as it defeats most of what systemd is about: be more than a shell script.

Hope that makes some sense even if disappointing?
