### ISSUE TITLE
v218: journald default for Storage= causes strange behavior when /var/log/journal/ missing

### ISSUE THREAD

**Issue by mpictor** [systemd/systemd#2009]
Running Gentoo's systemd version 218.

My journald.conf has nothing uncommented, so it's using the defaults. I assume the default is `Storage=auto`:

> ... "auto" is similar to "persistent" but the directory /var/log/journal is not created if needed, so that its existence controls where log data goes.
> -- _man journald.conf_

I noticed strange behavior with various services; most noticeable was that systemd-networkd would _usually_ not bring up any interfaces.

I suspected a race condition, as it
a) did work at some boots, and
b) reliably worked if I ran `systemctl restart systemd-networkd` after logging in.

Enabling debug output for systemd as a whole, or for systemd-networkd itself, provided me with no hints.

Finally I noticed that `journalctl --list-boot` only showed the most recent boot. `/var/log/journal` didn't exist, so I created it. After rebooting, networkd worked. Repeated boots with and without `/var/log/journal` indicate that the absence of that directory seems to cause the behavior.

If a race condition is indeed involved, perhaps journald stops processing input until all filesystems have been mounted if it doesn't see /var/log/journal? If so, that could cause other services to hang because they couldn't write to stderr/stdout.

**Comment by poettering** [comment]
the journal will log to /run/log as long as /var/log is not available. It will not block then.

I have no good explanation for your issue. But please note that we only track bugs in the two most recent systemd versions upstream. Given that 218 was even old when the issue was filed I will close this now. (Sorry for not reacting for such a long time though!)

if this is still an error with one of the two most recent systemd versions please file a new bug! Thanks!
