### ISSUE TITLE
/run/nologin not removed after "systemctl restart systemd-logind"

### ISSUE THREAD

**Issue by divkoro** [systemd/systemd#20129]
**systemd version the issue has been seen with**
 > systemd-234-lp152.31.25.1.x86_64 

**Used distribution**
 > opensuse 15.3

**Linux kernel version used** (`uname -a`)
 > `5.3.18`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > shutdown -c removes /run/nologin

**Unexpected behaviour you saw**
 > shutdown -r +5 ; wait a short while ... ; systemctl restart systemd-logind; shutdown -c ; /run/nologin is not removed; login is not possible; after time of planned shutdown is exceeded, even root access per ssh (if configured) is not possible anymore!

**Steps to reproduce the problem**
 > 
 >  leap1:~ # shutdown -r +5 ;
Shutdown scheduled for Sun 2021-07-04 18:36:59 CEST, use 'shutdown -c' to cancel.
 > leap1:~ # ls -l /run/nologin
-rw-r--r-- 1 root root 22 Jul  4 18:32 /run/nologin
 > leap1:~ # systemctl restart systemd-logind ;
 > leap1:~ # shutdown -c ;
 > leap1:~ #  ls -l /run/nologin
-rw-r--r-- 1 root root 22 Jul  4 18:32 /run/nologin
 > leap1:~ # more /run/nologin
System is going down.
**Additional program output to the terminal or log subsystem illustrating the issue**

```Result: no login possible
…
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by divkoro** [comment]
Just a short question
is this topic known and known already being solved for current path.
It’s easy to reproduce.

Gruß 
Robert Divko

Von meinem iPad gesendet
