### ISSUE TITLE
sd_bus_get_description() wrongly return -ENXIO when user doesn't specifically set description

### ISSUE THREAD

**Issue by stream009** [systemd/systemd#20133]
**systemd version the issue has been seen with**
 > 248.3

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.12.13`

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 > return NULL to the out parameter `description` or return default name if bus is system bus or user bus

**Unexpected behaviour you saw**
 > return -ENXIO and out parameter unchanged

**Steps to reproduce the problem**
 > just call the function with bus that isn't set description

**Comment by bluca** [comment]
This has been the case for a long time, since: https://github.com/systemd/systemd/commit/f4b2933ee7890e5d414ab266d8586f19027a2bd9

I guess the right thing to do is to update the documentation here? It says:

>  sd_bus_get_description() returns a description string in description. This string may have been previously
>  set with sd_bus_set_description() or sd_bus_open_with_description(3) or similar. If not set this way, a
>  default string like "system" or "user" will be returned for the system or user buses, and NULL otherwise.


which is clearly wrong, as it does not return NULL, but `-ENXIO`.

https://github.com/systemd/systemd/blob/main/man/sd_bus_set_description.xml#L112
