### ISSUE TITLE
Concurrent login / daemon-reload produces abandoned sessions

### ISSUE THREAD

**Issue by nicolasbock** [systemd/systemd#20136]
Using `systemd-248.3-1ubuntu1` on Ubuntu Impish the following script produces multiple abandoned sessions:

```bash
$ for i in {1..100}; do sleep 0.2; ssh localhost sudo systemctl daemon-reload & ssh localhost sleep 1 & done
$ sleep 2
$ jobs -p | xargs --verbose --no-run-if-empty kill -KILL
$ systemctl | grep abandoned
  session-174.scope                    loaded active     abandoned Session 174 of user ubuntu
  session-175.scope                    loaded active     abandoned Session 175 of user ubuntu
  session-176.scope                    loaded active     abandoned Session 176 of user ubuntu
  session-25.scope                     loaded active     abandoned Session 25 of user ubuntu
```

I would like to debug this behavior further and understand why this is happening but don't know where to look next. Is there any information in particular I should look at?

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
