### ISSUE TITLE
how to detect abnormal restarted service

### ISSUE THREAD

**Issue by Ivlyth** [systemd/systemd#20162]
**Is your feature request related to a problem? Please describe.**

how to detect a service is restarted without `systemctl restart OR systemctl stop / systemctl start` 
with `Restart=always` property set. 

i want to monitor my service for abnormal auto restart (eg. service crash, OOM, killed by user etc)

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
