### ISSUE TITLE
RFE: allow nspawn 228 to work with machined 227

### ISSUE THREAD

**Issue by alban** [systemd/systemd#2016]
systemd-v227 introduced a new property "TasksMax" in https://github.com/systemd/systemd/commit/03a7b521e3ffb7f5d153d90480ba5d4bc29d1e8f and systemd-nspawn-v228 starts to use it for machine registration in https://github.com/systemd/systemd/commit/541ec33075f9f2461b5286592312d2b50295ad32.

So systemd-nspawn-v228 cannot register a container to machined if systemd-pid1 < v227 is running on the host. This can cause rkt to fail because rkt imbed systemd-nspawn in rkt's stage1. This was first reported in https://github.com/coreos/rkt/issues/1782. At the moment, rkt uses systemd-nspawn-v222 but we want to switch to v228 to get the following fixes: #1318 (aka "container exits with non-zero code"), #1619 (aka "Failed to mount sysfs to /sys/full").

The error is:

```
Failed to register machine: Cannot set property TasksMax, or unknown property.
```

What's the best way to solve this? Could systemd-nspawn check if TasksMax is supported before using it? Or fallback without TasksMax if an error is reported? Or alternatively, is there a way to ask systemd-pid1 to ignore properties that it does not understand?

Also, if other container managers want to register containers to machined, how are they supposed to know which properties are accepted or not? Is there a GetSupportedProperties() D-Bus method call?

**Comment by poettering** [comment]
Note that we don't officially support such mixing&matching of nspawn and the host version.

That said, I'd be willing to take a patch that moves setting the default for TasksMax= from nspawn itself into machined. It's probably better placed there anyway, so that it applies to all container managers alike. Make sure to set the prop when machined creates the scope object before it adds the client's props on top, so that the client's setting of this prop if it sets it override the builtin default in machined.

We currently have no way to check which setting are supported, except for trying and retrying... There's a TODO list item, to make this a bit ncier though, by adding a proper error code for this case. would be happy to take a patch for that too.

**Comment by alban** [comment]
I started to look at this, but I am not sure I understand how the scope_properties "a(sv)" is passed from the "CreateMachineWithNetwork" D-Bus message to the "StartTransientUnit" D-Bus message via sd_bus_message_copy(). I wrote my question in the comments of the following commit:

https://github.com/alban/systemd/commit/2892cf1870cdc2c211fb09fc3921128c5e8e6b9f

/cc @iaguis

**Comment by poettering** [comment]
commented there too.
