### ISSUE TITLE
Start units whose Requisite becomes available

### ISSUE THREAD

**Issue by aerusso** [systemd/systemd#20296]
**Is your feature request related to a problem? Please describe.**

I have three units on my system: A B C

1. A Wants=B
2. B After=C, and Requisite=C

(A and C are WantedBy=multi-user.target)

On startup, this does exactly what I want: 
 1. A and C start up
 2. After C is up, B starts.

Sometimes, I need to turn off C, which brings B down as well, which is perfect. (I actually use BindsTo= on startup, but my testing suggests this should not affect things.)

However, when I turn C back on, B stays off (obviously---C does not Want=B).

If I `systemctl start A`, B starts back up (as one expects).  Is there a nice way to express this dependency?  The idea that B should be started, if something else Wants= it? 

**Describe the solution you'd like**

Spitballing: something like `StopWhenUnneeded`, but `StartWhenWanted` that tries to start something whose `Requisite` has just become available.

**Describe alternatives you've considered**
We could also do something like `PartOf=` or `ConsistsOf=`, like `Enhances=`, maybe?

**The systemd version you checked that didn't have the feature you are asking for**
This is 247, in Debian bullseye.

**Comment by poettering** [comment]
You could Wants= from the dependency units to B, so that the dependencies start B whenever they themselves start. Then add Requisite= the other direction, so that these Wants= have no effect unless both deps are actually fullfilled.

Anyway, this is more a support question, and this is a bug tracker. Please continue discussion on systemd-devel or so. Thank you.
