### ISSUE TITLE
nss-systemd: conflict with recent pam_unix

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#20299]
**systemd version the issue has been seen with**
 
v249.1

**Used distribution**
Gentoo

Since https://github.com/linux-pam/linux-pam/commit/f220cace205332a3dc34e7b37a85e7627e097e7d, pam_unix expects getspnam to set errno to EACCES if /etc/shadow is not readable by the current user. In this case, it invokes a helper binary with `CAP_DAC_OVERRIDE` to allow the current user to validate their own password.

On my test system, nss-systemd is configured in nsswitch.conf per the documentation:
```
shadow: files systemd
```
If the current user exists in /etc/shadow, and has not been confgured via userdb dropin snipets, libnss_files will return no result and sets errno to EACCES. However, libnss_systemd does not attempt to access /etc/shadow; it returns no result and sets errno to 0 when it cannot find the user via userdb.

This breaks the expectations of pam_unix, and causes unprivileged processes to be unable to validate the password of the current user. A prime example of this is the lock screen provided by common X11 desktop environments.

According to PAM maintainer @ldv-alt, this behavior is incorrect and "violates the contract" specified in getspnam(3).

https://github.com/linux-pam/linux-pam/issues/379

It seems like at least one PAM maintainer is unwilling to change the behavior of pam_unix, so I guess systemd needs to work around this?

A possible workaround in nsswitch.conf:
```
shadow: files [UNAVAIL=return] systemd
```
This causes getspnam to return immediately if libnss_files fails to open /etc/shadow.

Downstream bug: https://bugs.gentoo.org/803050

**Comment by ldv-alt** [comment]
On Sun, Jul 25, 2021 at 04:45:29PM -0700, Mike Gilbert wrote:
> According to PAM maintainer @ldv-alt, this behavior is incorrect and "violates the contract" specified in getspnam(3).
> 
> https://github.com/linux-pam/linux-pam/issues/379

This issue is not just about pam_unix, my concern here is that all
getspnam(3)/getspnam_r(3) users relying on the error code specification
are potentially broken.

> It seems like at least one PAM maintainer is unwilling to change the behavior of pam_unix, so I guess systemd needs to work around this?

The problem is that you will have to patch every user of
getspnam(3)/getspnam_r(3) to stop checking error code.

**Comment by doverride** [comment]
The patch description mentions the CAP_DAC_OVERRIDE requirement but that, i believe, is wrong. CAP_DAC_READ_SEARCH should be enough, CAP_AUDIT_WRITE would be needed when audit is enabled (for example SELinux enabled systems)

It would help if systemd would adhere to the PAM rules when it is built with PAM. We rely on unix_chkpwd and unix_update as the single point of access to /etc/shadow for read and write respectively.

**Comment by floppym** [comment]
I see a few possible solutions for libnss_systemd:

1. Change the documentation to suggest `[UNAVAIL=return]` after compat or files in nsswitch.conf.
2. In `_nss_systemd_getspnam_r`, save/restore errno if userdb_getspnam returns `NSS_STATUS_NOTFOUND`.
3. Call `access("/etc/shadow", R_OK)` and set errno to `EACCES` on failure.

**Comment by floppym** [comment]
@ldv-alt Thanks for replying.

I do understand that the change in behavior for getspnam is not ideal. However, it seems like that manual page was written without any regard for NSS modules that provide alternate database backends. Trying to maintain the EACCES behavior for modules that don't even look at /etc/shadow is a bit weird.

Also, I think the number of programs that read/write the shadow password database is quite limited.

**Comment by jbowler** [comment]
I think it's worth pointing out that the bug as reported is, I believe, about the re-entrant API getspnam_r, not the stateful non-re-entrant APIs.  The stateful APIs still set EACCES when setspent is called (I verified that).  The stateless API however offers no easy work round for the API change that @floppym is suggesting.

These are the relevant parts (from https://man7.org/linux/man-pages/man3/getspnam.3.html):

`RETURN VALUE
        * * *
       The reentrant functions return zero on success.  In case of
       error, an error number is returned.`

The change causes the getspnam_r function to return 0, previously it returned EACCES.  

`DESCRIPTION 
   * * *
   Reentrant versions
        * * *  A pointer to the result (in case of success)
       or NULL (in case no entry was found or an error occurred) is
       stored in *spbufp.`

So the API as documented allows the case of "no matching user name" to be distinguished from a privilege violation by the return code - 0 in the first case, EACCES in the second.  (Also a programming error - ERANGE is returned if the buffer is too small.)

The API change @floppym is apparently suggesting requires an app programmer to do unspecified extra work to distinguish the two conditions.  Calling setspent and checking errno is not viable in an MT program, even if the current behavior were documented...

In any case, there are other consequences to the change beyond the altered API.  This file contains a program with, I hope, easily understandable output which allows quite a lot of the problems to be shown by editing /etc/nsswitch.conf:

[tso2.c.txt](https://github.com/systemd/systemd/files/6881104/tso2.c.txt)

Compile with:

`gcc -o tso2 -Wall -Wextra -std=gnu89 -x c tso2.c.txt`

"gnu89" is necessary because getspnam_r is a glibc extension.

Here is the output with `shadow: files` in nsswitch.conf, I believe this is the original behavior, first as root, output has the form:

`return-code(errno-value) name(*sp_namp) epw(*sp_pwdp) (description-of-spwd-result: description-of-return-code`

`# ./tso2 root bin foobar jbowler
getspnam_r(root) -> 0[0] name(root) epw($6$q..YDB.) (entry found: success)
getspnam_r(bin) -> 0[0] name(bin) epw(*) (entry found: success)
getspnam_r(foobar) -> 0[0] name(?) epw(?) (no entry: success)
getspnam_r(jbowler) -> 0[0] name(jbowler) epw($6$0..wsO/) (entry found: success)`

/etc/shadow only has two entries with passwords (root and jbowler).  "bin" has a *'ed out password, foobar does not exist.  Now with only user (jbowler) privilege:

`$ ./tso2 root bin foobar jbowler
getspnam_r(root) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(bin) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(foobar) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(jbowler) -> 13[13] name(?) epw(?) (ERROR: not permitted)`

Now the current nsswitch.conf with `shadow: files systemd`, just the jbowler version this time (the superuser output does not change):

`$ ./tso2 root bin foobar jbowler
getspnam_r(root) -> 0[0] name(root) epw(!*) (entry found: success)
getspnam_r(bin) -> 0[0] name(?) epw(?) (no entry: success)
getspnam_r(foobar) -> 0[0] name(?) epw(?) (no entry: success)
getspnam_r(jbowler) -> 0[0] name(?) epw(?) (no entry: success)`

Notice that the 'foobar' entry is now the same as the original superuser result for 'foobar' and that 'root' is now found and an encoded password is returned; apparently the change returns the encoded root password to an unprivileged user!  It's the wrong password of course, but that is definitely new behavior.  (The returned strings in this case are actually not inside the allocated buffer.)

Finally with the '[UNAVAIL=return]' change the API reverts to the original definition:

`$ ./tso2 root bin foobar jbowler
getspnam_r(root) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(bin) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(foobar) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(jbowler) -> 13[13] name(?) epw(?) (ERROR: not permitted)`

@floppym:
> I see a few possible solutions for libnss_systemd:
> 
> 1. Change the documentation to suggest `[UNAVAIL=return]` after compat or files in nsswitch.conf.

**Require**, not suggest; otherwise, unless the API is formally changed, a suggestion does not fix the problem.

> 2. In `_nss_systemd_getspnam_r`, save/restore errno if userdb_getspnam returns `NSS_STATUS_NOTFOUND`.
> 3. In `_nss_systemd_getspnam_r`, attempt to open /etc/shadow just to satisfy the behavior specified in the getspnam(3) man page.

Take note of the the baseline POSIX 1003.1 specification.  POSIX 1003.1 has this to say (original emphasis _removed_, my emphasis added):

`2.5 Error Numbers.  Most functions provide an error number in the external variable errno, which is defined as:

   extern int errno;

  **The value of this variable shall be defined only after a call to a function for which it is explicitly stated to be set**, ...`

The documentation of getspnam_r _**does not explicitly state**_ that errno is set.  So the value of errno after a call to (in fact) any of the re-entrant functions is _undefined_, in the strict POSIX sense (section 2.1).  Application programmers are constrained (in the absence of an API change) to use the return code from the function, not the value of errno.

**Comment by floppym** [comment]
I was really just glossing over the differences between getspnam and getspnam_r (errno versus return value). Don't read too much into that.

**Comment by floppym** [comment]
> In _nss_systemd_getspnam_r, save/restore errno if userdb_getspnam returns NSS_STATUS_NOTFOUND.

I think this isn't actually an option; my intent here was to maintain the error number that the equivalent function in libnss_files generated, but I don't think the nss API actually provides that.

**Comment by jbowler** [comment]
This almost works:

> shadow: systemd files
> gshadow: systemd files

The results, superuser and jbowler, are thus (using a slightly modified tso2 which checks whether the buffer was used for the name/pwd):

```
# ./tso2 root bin foobar jbowler
  'root', 0x7f742826b1b7: string outside buffer ('', 0x55a7bc0802a0)
  '!*', 0x7f742826b1cb: string outside buffer ('', 0x55a7bc0802a0)
getspnam_r(root) -> 0[0] name(root) epw(!*) (entry found: success)
getspnam_r(bin) -> 0[0] name(bin) epw(*) (entry found: success)
getspnam_r(foobar) -> 0[0] name(?) epw(?) (no entry: success)
getspnam_r(jbowler) -> 0[0] name(jbowler) epw($6$0..wsO/) (entry found: success)

$ ./tso2 root bin foobar jbowler
  'root', 0x7f36e4c111b7: string outside buffer ('', 0x55dda60112a0)
  '!*', 0x7f36e4c111cb: string outside buffer ('', 0x55dda60112a0)
getspnam_r(root) -> 0[0] name(root) epw(!*) (entry found: success)
getspnam_r(bin) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(foobar) -> 13[13] name(?) epw(?) (ERROR: not permitted)
getspnam_r(jbowler) -> 13[13] name(?) epw(?) (ERROR: not permitted)
```

So, unfortunately, systemd is providing a bogus result for the password of root, which looks dangerous, but it has the desired semantic apart from that.  With the changed order systemd can add records or even change the passwords on existing records (is that what is happening with root?)  However if the systemd NSS service does not have an entry, or does not have sufficient privilege to reveal it, it will be checked with files (or compat, I guess, or db).

The underlying problem is that NSS is not distinguishing "service not available" from "insufficient privilege to ask that question"; when the files service sets EACCES (in *errnop) and returns NSS_STATUS_UNAVAIL it means the latter, for "entry not found (but you have enough privilege)" I believe it returns NSS_STATUS_NOTFOUND and sets  ENOENT in (*errnop).  However UNAVAIL would also be returned if /etc/shadow were deleted (I assume, I don't dare test that ;-)  and in that case ENOENT would be set in *errnop.

I don't quite understand why the systemd service sets errno to 0; the [gnu.org documentation](https://www.gnu.org/software/libc/manual/html_node/NSS-Modules-Interface.html) is quite explicit:

>An NSS module should never set *errnop to zero.

I don't see any reason to put systemd at the end if the root passwd behavior is fixed (it certainly prevents a root login on a console), but without that change the systemd service is going to get called with *errnop == EACCES and it could simply return NSS_STATUS_UNAVAIL at that point.

**Comment by jbowler** [comment]
FWIW with appropriate breakpoints and using `gcc -o tso2 -g -pthread -fPIC -Wall -Wextra -std=gnu89 -x c tso2.c`:

```
Breakpoint 1, _nss_files_getspnam_r (name=0x7fffffffde47 "jbowler", 
    result=0x7fffffffd8d0, buffer=0x5555555592a0 "", buflen=1024, 
    errnop=0x7ffff7dcb6c8) at nss_files/files-XXX.c:78
(gdb) print *errnop
$1 = 0
```
Then:
```
Breakpoint 2, _nss_systemd_getspnam_r (name=0x7fffffffde47 "jbowler", 
    spwd=0x7fffffffd8d0, buffer=0x5555555592a0 "", buflen=1024, 
    errnop=0x7ffff7dcb6c8)
    at ../systemd-stable-249.1/src/nss-systemd/nss-systemd.c:244
(gdb) print *errnop
$2 = 13
```
Note that errnop is not changed and seems to point somewhere on the main() thread stack.  The value 13 is EACCES, so the systemd implementation of getspnam_r has the expected value.  This value is preserved across the _nss_systemd_gethostbyname_r call:

```
(gdb) up
#1  0x00007ffff7eca8e3 in __getspnam_r (name=<optimized out>, 
    resbuf=<optimized out>, buffer=<optimized out>, buflen=1024, 
    result=<optimized out>) at ../nss/getXXbyYY_r.c:274
274     ../nss/getXXbyYY_r.c: No such file or directory.
(gdb) break
Breakpoint 4 at 0x7ffff7eca8e3: file ../nss/getXXbyYY_r.c, line 274.
(gdb) c
Continuing.

Breakpoint 4, 0x00007ffff7eca8e3 in __getspnam_r (name=<optimized out>, 
    resbuf=<optimized out>, buffer=<optimized out>, buflen=1024, 
    result=<optimized out>) at ../nss/getXXbyYY_r.c:274
274     in ../nss/getXXbyYY_r.c
(gdb) print *(int*)0x7ffff7dcb6c8
$3 = 13
```

But then:

```
(gdb) c
Continuing.
getspnam_r(jbowler) -> 0[0] name(?) epw(?) (no entry: success)
[Inferior 1 (process 8548) exited normally]
```
So that is slightly weird.  I suspect _nss_systemd_gethostbyname_r is returning NSS_STATUS_NOTFOUND and the problem lies in getspnam_r itself; "not found" trumps the earlier (files) "not available" because NSS doesn't provide "denied" and getspnam_r doesn't implement shadow specific handling to deal with the EACCES result.

Because errnop is auto (on the stack) _nss_systemd_getspnam_r can rely on it having been initialized to 0 at the start (it's not like errno).  So a one line fix is for that function to return NSS_STATUS_UNAVAIL if:

1) It finds no matching entry (this will mean the "root" problem isn't fixed).
2) *errnop == EACCES.

Better (and what I would; I do like to completely rewrite things) is for NSS to have a "permanent failure" option; blocking further attempts to resolve a query.

**Comment by floppym** [comment]
> I don't quite understand why the systemd service sets errno to 0

I think this is a side-effect of the errno save/restore logic in _nss_systemd_getspnam_r (see the PROTECT_ERRNO macro). Maybe _nss_systemd_getspnam_r should be updated to call UNPROTECT_ERRNO and set *errnop to ENOENT when returning NSS_STATUS_NOTFOUND.

**Comment by jbowler** [comment]
The base commit in question is this one:

https://github.com/systemd/systemd/commit/06202b9e659e5cc72aeecc5200155b7c012fccbc

That doesn't seem to add the macro to getspnam_r but it seems to be the origin of the whole thing.  The discussion is here:

https://sourceware.org/bugzilla/show_bug.cgi?id=23410

It's a different version of the same issue; the systemd service changing an established API (in that case getpwent).  It is worth reading the sourceware.org discussion all the way through otherwise all of it will just get repeated here (not that I'm saying the discussion is correct, just that it is plausible enough to be stated again.)

I don't think this can be what sets *errnop to 0; I traced through the call and *errnop was 13 both before and after the call (see above).  My assumption is that getspnam_r itself resets *errnop to 0 as a result of the NOTFOUND return value; this is mentioned in the discussion above (for getpwent), see comment #2.

My one line fix could be made in getspnam_r; the implication of the discussion is that there was some feeling that the broad outlines in the manual, see comment #5.

I think the bottom line is that if the systemd service fails to find an entry then it should not invalidate the results of a previous service (files in this case); it doesn't have any more information so it should not mess up the information already returned.  A fix in the calling function, getspnam_r, would clearly be safer but getting fixes in glibc is likely to be a major undertaking (based on my experience with gcc.)

**Comment by jbowler** [comment]
Having found the code I now know that _all_ of the **_r** re-entrant NSS APIs do not initialize the ***errnop** parameter at all and, to complicate things, the parameter is actually a pointer to the thread-local **errno** variable.  The nss_files_getspnam_r implementation (which seems to be part of glibc) does not change errno when it returns NSS_STATUS_NOTFOUND, so if it were set to EACCES before the original call to getspnam_r it will still be set that way for a user name that is not in /etc/shadow.  This means my one-line-fix won't work.

**Comment by jbowler** [comment]
> > I don't quite understand why the systemd service sets errno to 0
> 
> I think this is a side-effect of the errno save/restore logic in _nss_systemd_getspnam_r (see the PROTECT_ERRNO macro). Maybe _nss_systemd_getspnam_r should be updated to call UNPROTECT_ERRNO and set *errnop to ENOENT when returning NSS_STATUS_NOTFOUND.

I was wrong about where errno was set to 0; nss_systemd_getspnam_r leaves it set to EACCES (from the preceding call to nss_files_getspnam_r, however it returns NSS_STATUS_NOTFOUND and this causes getspnam_r itself to set errno to 0.  It has to return NSS_STATUS_NOTFOUND and, since it is the last service in the chain, that will always lead getspnam_r to set errno to 0.

Suggestion 3:

3. In _nss_systemd_getspnam_r, attempt to open /etc/shadow just to satisfy the behavior specified in the getspnam(3) man page.

A system with no /etc/shadow, no 'files' support (for example a system using 'db' instead - see the comments in nsswitch.conf itself) will then fail incorrectly.

So far as I can see code changes to systemd _cannot_ fix this!  Code changes are required to glibc; the simplest change is number (1) from above to nsswitch.conf:

gshadow: files [unavail=return] systemd
shadow: files [unavail=return] systemd

Similar changes are probably required if 'db' or 'compat' or some other service that can fail to return a shadow password is used before systemd.

**Comment by poettering** [comment]
So this is a long discussion and I am not sure I follow fully, but is the gist that if you have a stack of "shadow" modules now, then a module is supposed to return EACCES/NSS_STATUS_UNAVAIL if /etc/shadow is not accessible which the next module will then mangle and the info gets lost?

We can cetrainly document that `[unavail=return]` is inserted before the `systemd` specification. But doesn't do that too much? In what other cases is UNAVAIL returned by nss-files/nss-compat? If we insert this for shadow/gshadow shouldn't we also do this for passwd/group?

Is any of this properly documented somewhere?

Shouldn't there be NSS_STATUS_PERMISSION or so? (i figure hard to add, due to compat, admittedly)

**Comment by floppym** [comment]
> So this is a long discussion and I am not sure I follow fully, but is the gist that if you have a stack of "shadow" modules now, then a module is supposed to return EACCES/NSS_STATUS_UNAVAIL if /etc/shadow is not accessible which the next module will then mangle and the info gets lost?

That's the gist of it.

I am probably not the best person to answer the other questions you have posed. I think they need to be worked out between you, the PAM maintainers, and the glibc maintainers.

**Comment by floppym** [comment]
> In what other cases is UNAVAIL returned by nss-files/nss-compat?

It looks like UNAVAIL is returned if the file cannot be opened, or if any unexpected error occurs when reading a line from the file.

**Comment by jbowler** [comment]
Pretty much all the discussion is about how to fix the bug; the actual bug is that the getspnam(3) APIs, the /etc/shadow access utilities, are documented to return NULL and set errno to EACCES if:

> The caller does not have permission to access the  shadow  password file.

This does not happen with the setting 'shadow: files systemd' in /etc/nsswitch.conf

Apart from buffer overflow (which already has special handling in getspnam_r) there are no other documented errors; implicitly everything else is treated as "no more entries [being] available."

getpwnam(3) is documented to behave as at present; EACCES is handled in "..." here:

>0 or ENOENT or ESRCH or EBADF or EPERM or ...
>              The given name or uid was not found.

**Comment by cgzones** [comment]
This behavior also affects SELinux enabled systems, where `/etc/shadow` is not read-able by pam processes and the helper unix_chkpwd(8) must be used.

With a *nsswitch.conf* setting of `shadow files systemd` getspnam(3) returns `$*` as root password, which prevent root logins (via local_login, ssh). For other users, like rtkit, getspnam(3) returns NULL with `errno` set to `0` (such that pam retries via the helper).

**Comment by bauen1** [comment]
> Is there a reason libnss-systemd synthesizes skeleton entries for root and nobody, or was it just copied from the passwd code?

@poettering I would like to know this too, from my (user) perspective, there seems to be no reason I can think of why systemd-nss should synthesize root/nobody shadow entries when there exist legitimate entries.

From what I understand about NSS and the behavior of PAM, it seems to me, that the best way to fix this would be to simply not synthesize root/nobody shadow entries at all, or at least not if there exist legitimate entries.
However I know very little of how NSS works and how the API is specified.

**Comment by poettering** [comment]
> @poettering Is there a reason libnss-systemd synthesizes skeleton entries for root and nobody, or was it just copied from the passwd code?

The shadow record contains more than just the password, i.e. info about the account state, i.e. whether it is locked, whether a pw is set. We want to provide a complete fallback record, that marks the root account as locked when no proper record is otherwise provided, hence the skeleton.

I have no idea what the right fix here is. But I am pretty sure that we should be able to provide a fallback shadow record somehow. "fixing" this by avoiding that would be chickening out and a work-around, not more.

Anyway, open to suggestions. We can certainly tweak the errors we return, np, but not sure how that would help...

**Comment by jbowler** [comment]
> The shadow record contains more than just the password, i.e. info about the account state, i.e. whether it is locked, whether a pw is set. We want to provide a complete fallback record, that marks the root account as locked when no proper record is otherwise provided, hence the skeleton.

/etc/shadow is not readable by regular users (users with a UserID other than 0) and it is the intention that access to all information in /etc/shadow is privileged.  So if (say) getpwent is called by a regular user this returns only the non-privileged information and if something like setspent is called it returns NULL and sets errno to EACCES.

Any program which relies on some other behavior is either buggy or non-portable.  In particular even if the nss APIs provide extra information a portable user program can't rely on NSS being present and, anyway, it would be a significant security problem if a non-privileged API could reveal that the root, or indeed any, password has been set.

For certain an entry should not be returned (synthesized or not) if it exists in /etc/passwd and that is consulted first or it exists in /etc/passwd and does not exist in NSS (which may be a more useful scenario, where NSS is adding logins).

**Comment by ldv-alt** [comment]
Looks like the only viable solution for _all_ getspnam(3) users that have privileged fallback helpers is to use their helpers as the primary method, not as a fallback.
Following this route, I'm going to resolve this issue from pam_unix perspective with https://github.com/linux-pam/linux-pam/pull/686.

**Comment by poettering** [comment]
Let's close this was addressed in https://github.com/linux-pam/linux-pam/pull/686
