### ISSUE TITLE
[system-networkd]: Not able to disable layer3 configuration for specific interface link

### ISSUE THREAD

**Issue by chetuneve** [systemd/systemd#20313]
**systemd version the issue has been seen with**
 > systemd 241 (241)

**Used distribution**
 > Debian 10 (buster)

**Linux kernel version used** (`uname -a`)
> Linux DEB-NUC8i3BE-G6BE01300RG2 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
> Linux RP4-2711-c03112-1xb0e6f3b8 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux

**CPU architecture issue was seen on**
 > x86_64 and arm32v7

I would like to know, Is there any way in systemd-networkd to disable a specific interface through configuration file?
I am aware of "**IP flush** and **ip link set dev <ifname> down**". I don't want to use these both methods.
But I need some configuration which will disable an interface only and should not affect on layer2 configuration.

Any help would be appreciated.
Thank you so much in advance !

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
