### ISSUE TITLE
Please create a gathered entropy service

### ISSUE THREAD

**Issue by sitsofe** [systemd/systemd#2032]
Description of the problem:
Certain services really shouldn't be started until the system has gathered a minimum amount of entropy.

It would be good if there was a well known service which would block until minimum entropy had been gather so that other services (such as making server certificates for http or ssh) could be made to depend on them until such a point they are converted over to the [`getrandom` syscall](http://man7.org/linux/man-pages/man2/getrandom.2.html).

If the seeding happens thanks to pre-saved entropy that would essentially mean there was no blocking but if that wasn't available for whatever reason it would not take long before a minimum amount of entropy was accumulated. I guess a timeout could also be instigated just in case there are systems that can't gather entropy at all...

**Comment by poettering** [comment]
I am not convinced this is really worth it. There are APIs to do the right thing (albeit crappy ones, such as getrandom() -- blocking syscalls are so 1990s...), and people should just use that. I am pretty sure if the SSH/SSL folks care about security they have started using those anyway already instead of waiting for systemd, to hide the issue for them...

Sorry, but please file bugs against SSH and the SSL certificate generators instead.

**Comment by crrodriguez** [comment]
You are preaching to the wrong choir here.. please refer your complains to LKML on this subject as it is the kernel that should handle all of this. userspace ought not to be involved in any way.
