### ISSUE TITLE
RFE: search for hibernation swap partitions from gpt-auto-generator logic in the initrd

### ISSUE THREAD

**Issue by WhyNotHugo** [systemd/systemd#20355]
**systemd version the issue has been seen with**

Current master:

```
$ systemctl --version
systemd 249 (249.rc1.r113.g409ca5fff1-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**

ArchLinux

**Linux kernel version used** (`uname -a`)

    Linux victory 5.12.14-arch1-1 #1 SMP PREEMPT Thu, 01 Jul 2021 07:26:06 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**

amd64

**Expected behaviour you didn't see**

When using `resume=/dev/mapper/swap` and the Discoverable Partitions Specification, the system hangs waiting for this partition to be unlocked:

    A start job is running or /dev/mapper/swap (1min 6s / no limit)

This hangs indefinitely and blocks startup completely.

**Unexpected behaviour you saw**

The partition should be unlocked normally when trying to `resume`.

**Steps to reproduce the problem**

- Empty fstab.
- Swap partition is LUKS encrypted.
- Swap partition has the right PARTTYPE.

**Additional program output to the terminal or log subsystem illustrating the issue**

Booting the system without `resume=...` works fine, and systemd unlocks `/dev/mapper/swap` properly.

I'm not sure how to generate further logs; the system will hang indefinitely at this stage and won't finish booting

**Comment by poettering** [comment]
are you sure your distro's initrd supports that even? please ping them first.

**Comment by WhyNotHugo** [comment]
I'm using dracut. I'm assuming you usually guys use the same thing, right?

**Comment by poettering** [comment]
so, hmm, i see now you are relying on the GPT auto logic? that doesn't really work for the hibernate swap partition stuff right now. The current logic is to identify root/usr from initrd via GPT logic, then transition to that out of the initrd, and then look for auxiliary partitions from there, activating swap and things like that. But in your case doing so can't work, since after all you want to resume from the hibernation image and *not* transition to the root fs first. 

We'd have to beef up the gpt discovery logic in the initrd first, so that we support looking for swaps from within the initrd.

**Comment by WhyNotHugo** [comment]
I guess the way around this is to do the swap discovery early (e.g.: when doing the `/` and `/usr` discovery), right?

**Comment by YHNdnzj** [comment]
I've just put together the mandatory building blocks for this in https://github.com/systemd/systemd/issues/27247#issuecomment-2526037748, and several implementation details. I'd close this one here, and consolidate discussion there.
