### ISSUE TITLE
[hostnamed] Why the service will automatically exit after 30 seconds

### ISSUE THREAD

**Issue by Zeno-sole** [systemd/systemd#20446]
How to configure this service so that it will not automatically exit

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
