### ISSUE TITLE
systemd-timesyncd fails to sync time from NTP server with IPv6 address

### ISSUE THREAD

**Issue by leiyu-bytedance** [systemd/systemd#20482]
**systemd version the issue has been seen with**
systemd v249 and main branch

**Used distribution**
 > OpenBMC

**Linux kernel version used** (`uname -a`)

 > `5.10.53`

**CPU architecture issue was seen on**
 > ARM

**Expected behaviour you didn't see**
 > systemd-timesyncd should be able to sync time from NTP server with IPv6 address

**Unexpected behaviour you saw**
 > It fails to sync time and get error message as below.

**Steps to reproduce the problem**
- Config the NTP server with IPv6 address
- Start systemd-timesyncd

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
systemd-timesyncd[534]: Error receiving message, disconnecting: Exchange full
```

**Comment by leiyu-bytedance** [comment]
The issue occurs after 3691bcf3c5eebdcca5b4f1c51c745441c57a6cd1
I tried to revert the related change in `src/timesync/timesyncd-manager.c` and the issue could be fixed.
See patch attached.
[0001-timesyncd-Use-recvmsg-instead-of-recvmsg_safe.txt](https://github.com/systemd/systemd/files/7014072/0001-timesyncd-Use-recvmsg-instead-of-recvmsg_safe.txt)

**Comment by yuwata** [comment]
Could you test #20488?

**Comment by leiyu-bytedance** [comment]
> Could you test #20488?

Tested with the patch, and the issue remains.

**Comment by yuwata** [comment]
Could you show the last two line of the result `test-sizeof`?

**Comment by leiyu-bytedance** [comment]
> Could you show the last two line of the result `test-sizeof`?

```
timeval: 8
timespec: 8
```
It's on arm32.

**Comment by yuwata** [comment]
Could you test #20567?

**Comment by leiyu-bytedance** [comment]
Tested with https://github.com/systemd/systemd/pull/20567 and it works fine. Thanks!

**Comment by UZver24** [comment]
I am experiencing the same issue on **Ubuntu 24.04** (`systemd` versions `255.4-1ubuntu8.6` and `255.4-1ubuntu8.10`, **ARM architecture**).

- The error message is identical:
  ```
  systemd-timesyncd[PID]: Error receiving message, disconnecting: Exchange full
  ```
- The problem persists even after updating to the latest available `systemd` versions in Ubuntu 24.04 (`255.4-1ubuntu8.6` and `255.4-1ubuntu8.10`).
- The issue occurs with both IPv4 and IPv6 NTP servers.
- All network connectivity is fine, and other NTP clients (like `ntpdate` and `chrony`) work as expected.
- I have checked and manually set the required capabilities (`CAP_SYS_TIME`, `CAP_NET_RAW`, `CAP_NET_BIND_SERVICE`) for the `systemd-timesyncd` process, but the error still occurs. It seems that even with the correct capabilities, the service cannot synchronize time.
- The problem is reproducible on ARM/embedded devices.

**Summary:**
- The bug is not fixed in the latest `systemd` versions for Ubuntu 24.04.
- The issue may be related to missing capabilities or internal `timesyncd` networking logic.
- As a workaround, I am using `chrony`, but would prefer to use the built-in `systemd-timesyncd` if possible.

Please let me know if I can provide any additional logs or help with debugging.

**Comment by UZver24** [comment]
After reassembling from source (version "systemd 258 (258~devel)"), I observe: `Error receiving message, disconnecting: got truncated control data`

**Comment by williamspatrick** [comment]
@UZver24 - considering this issue has been closed as fixed for a few years, I would suggest you create a new issue report rather than trying to revive this one. Your issue sounds different anyhow even though it might have similar symptoms.

**Comment by UZver24** [comment]
I agree, I've moved the error description here: https://github.com/systemd/systemd/issues/38222
