### ISSUE TITLE
use hwclock to write rtc after systemd-timesyncd in rtc-in-local mode

### ISSUE THREAD

**Issue by caoxia2008cxx** [systemd/systemd#20545]
If we set rtc-in-local,the 11 minute mode will not enable because of DST.so the system time will never sync to RTC.
Can we use hwclock  to write rtc after systemd-timesyncd,it's always right in any timezone.
But I don't know what's the suitable period to write rtc.
the kernel write rtc every 11 minute in 11 minute mode ，but I don't know why is 11 minute

**Comment by poettering** [comment]
1. don't use rtc-in-local, it's a mess.

2. if you do, this means that some other OS manages your RTC (i.e. windows), and that means you shouldn't set it ever. in rtc-in-local mode there can only be one "owner" of the RTC, i.e. the OS that does DST switches and such, and keeps track whether it switched already. If you have multiple OSes writing to the RTC in that mode, i.e. two "owners" of the RTC, then the DST change one applies will be duplicated by the other and confusion ensues.

Because of that the kernel and timesyncd will never sync to RTC in RTC-in-local mode. You can only lose that way, it's a nonsensical setup: if Linux would "own" (i.e. manage) the RTC then it should do so in RTC-in-UTC mode, and if it doesn't "own" the RTC then it should never make changes to it, and leave that to Windows.

If you want to kludge this togther yourself, then by all means, go ahead, but timesync is not going to help you with that. Pick any interval you like. kernel picked 11min. I see no reason to pick a different value, it's really up to you though. 

Also, this sounds like more a support question then a bug report or feature request (which this tracker is about). And for support questions please use the systemd mailing list or so, not this tracker, to keep noise levels at a minimum.

(If you meant this as a feature request/RFE, i.e that we add RTC sync to timesyncd in rtc-in-local-mode, then I'd say: no way, it's a bad idea, sorry)
