### ISSUE TITLE
Recover from freezing execution 

### ISSUE THREAD

**Issue by jiayi0118** [systemd/systemd#20647]
Absolutely systemd will crash when catching 6 kind of signals, such as SIGSEGV, SIGILL and so on. After frozen, the only way to unfreeze systemd is to reboot the computer compulsively.
However, it is a high cost to reboot in some enterprise scenarios, thus I am wondering whether systemd can support optional reexecution feature to give more emergency space to system maintainer. Or why systemd does not support this feature?

**Comment by poettering** [comment]
You can reexec systemd alread, but only if we are in a clean state, as reexec means serializing state and deserializing it after reexec. 

If we hit a segfault, then the state is not clean, serialization is very likely not going to work or will be generated in corrupted fashion only. The only way you could address that if you#d continously update state in the filesystem, so that whenever PID 1 dies you can restore from the latest state on disk, however that would be quite inefficient .

Sending the relevant signals explicitly to PID 1 is something we really don't have to protect against, since that is a privileged op, and this is not going to happen by accident or by untrusted users. So besides the segault case no case is interesting.

To our kowledge PID 1 is seldomly an issue though, the kernel is much more likely to oops than PID 1 is in the general case, thus I am not convinced trying to address this is really resources spent well...

Hence, this has been suggested before. if you prep a really convincing patch that implements this logic and that actually works, great, please submit a PR, otherwise I see not much point in this tbh. Let's close hence.
