### ISSUE TITLE
modules-load.d not ordered after usr-local.mount

### ISSUE THREAD

**Issue by lnussel** [systemd/systemd#20727]
**systemd version the issue has been seen with**
 > 249.4

**Used distribution**
 > openSUSE Tumbleweed

**Linux kernel version used** (`uname -a`)

 > `Linux tw-systemd 5.14.3-2-default #1 SMP Mon Sep 13 13:34:40 UTC 2021 (39fb041) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > modules listed in /usr/local/lib/binfmt.d/*.conf loaded at boot

**Steps to reproduce the problem**
 > have /usr/local on a separate volume and add a file to /usr/local/lib/binfmt.d/ to load a kernel module at boot. Reboot and see it's not loaded.

FWIW I have no actual use case for this, just noticed SELinux denied messages due to /usr/local that are not reproducible later. Reason is that on openSUSE /usr/local is on a separate btrfs subvolume by default. Due to a missing dependency on `usr-local.mount`, `systemd-modules-load.service` accesses the unlabeled original directory. Even if SElinux allowed that, there would be no content at that point in time of course :-) So the issue is generic.
For the same reason SElinux also complains about `systemd-sysctl.service`.

Adding `After=usr-local.mount` fixes the issue.

**Comment by poettering** [comment]
nah, we don't know what /usr/local/ needs to work. People do weird shit with /usr/local. It's a really weird concept, some people mount it from NFS, but that means we can't access it in early boot. But others mount it from local fs, and then want to drop early-boot stuff/kmods/… in it, including binfmt.d/modules-load.d stuff and so on.

I think /usr/local is a really strange beast and we should only support it to the bare minimum, i.e. look in those dirs if they exist and are accessible and ignore them otherwise. That way people can decide on their own, whether they want to put early boot stuff there (in which case they can't put it on NFS) or if not (in which case they can put it on NFS).

Or in other words: people should decide themselves how they schedule this. If they want to delay modules-load.d stuff until /usr/local is around, all power to them, they can just add a drop-in to the relevant unit themselves adding the ordering. But if they don't, then we should not wait for it.

I mean, it could be that the modules-load.d/sysctl.d/binfmt.d is necessary to to access /usr/local, or it could be that it should be configured from what it contains. We can't know which one of the two cases it is, hence we should step away and leave that in territory for the user to configure.

Hope that makes some sense?

**Comment by lnussel** [comment]
Sure. Thx!
