### ISSUE TITLE
cryptenroll: use Argon or higher PBKDF2 iteration count

### ISSUE THREAD

**Issue by Algebro7** [systemd/systemd#20735]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is a security issue in the context of cryptenroll, but I noticed when enrolling a device with `systemd-cryptenroll`, the [minimum PBKDF2 iteration count 1000 is used](https://github.com/systemd/systemd/blob/main/src/cryptenroll/cryptenroll-fido2.c#L58), which was recommended circa 2000 but is well below the current recommended minimum iteration count. For example, when creating a key directly with `cryptsetup`, the count is far higher:

```  2: luks2
        Key:        256 bits
        Priority:   normal
        Cipher:     aes-xts-plain64
        Cipher key: 256 bits
        PBKDF:      pbkdf2
        Hash:       sha256
        Iterations: 3591012
```
Modern versions of `cryptsetup` now default to `argon2id`, which in theory should be even more secure.

**Describe the solution you'd like**
At the very least, `systemd-cryptenroll` should protect the key with a much higher PBKDF2 iteration account (10,000 was the bare minimum as of a couple years ago). Ideally it could support the newer argon method.

**Describe alternatives you've considered**
N/A

**The systemd version you checked that didn't have the feature you are asking for**
Current master

**Comment by poettering** [comment]
In the FIDO2 case the key is generated from the host RNG, it has already highest entropy. You want large number of KDF iterations when your key has low entropy, i.e. is a password picked by a human, but this is precisely what FIDO2 doesn't do: it uses high-entropy, binary keys already, hence no need to magically increase entropy in something that already has entropy plenty.

If you look closely we use the default argon2id KDF when passwords are enrolled, we turn it off only for TPM2, FIDO2, PKCS#11 keys, because each time the key material is already high quality enough, and using a needlessly high KDF only slows things down for no benefit.

**Comment by Algebro7** [comment]
Sounds good, appreciate the explanation!
