### ISSUE TITLE
Assign address from ISP prefix-delegation on receiving interface (WAN/uplink)

### ISSUE THREAD

**Issue by iam-TJ** [systemd/systemd#20808]
**Is your feature request related to a problem? Please describe.**
Router uplink interface able to automatically assign and use an address from a prefix delegated from the upstream router.

Scenario: where ISP does IPv6 prefix delegation. systemd-networkd on customer gateway/router. Delegated prefix can currently only be assigned automatically on the LAN side. Customer wishes to automatically assign an address from the delegated prefix on the uplink interface so that all traffic originating from their network uses the same prefix. Some ISPs may enforce using the delegated prefix in their ingress filtering.

Earlier commits added the ability to do this on the LAN-side interfaces when that interface is announcing the delegated prefix.

**Describe the solution you'd like**
Ability to use something like  `Assign=` and `Token=` but probably in an `[Address]` section. Using existing semantics maybe something like this:
```
[Address]
# this address is a placeholder and is ignored when AddDelegatedPrefixAddress=yes
Address=2001:db8::1
# default is no
AddDelegatedPrefixAddress=yes
# required when AddDelegatedPrefixAddress=yes
DelegatedPrefixIPv6Token=2001:db8::1/48
```
Given the upstream router delegating `2000:2000:2000::/48` then this would result in `2000:2000:2000::1` being assigned. Chosen key names to be familiar but not confused with other usages of e.g. `Token`.  `AddPrefixRoute=` already exists in this section so `AddDelegatedPrefixAddress=` is in the same style.

`DelegatedPrefixIPv6Token=` would not need a `mode` option as in other `*Token=` usage. Given prefix would be discarded and replaced with the delegated prefix.

**Describe alternatives you've considered**
Using a static `[Address]` section but this will break when the delegated prefix changes.

**The systemd version you checked that didn't have the feature you are asking for**
v249

**Comment by eyJhb** [comment]
Confirming that this issues affects me, and my ISP. Have tried to find a solution together with @iam-TJ, but to no avail (for a clean solution at least). 

Would really like to see such a feature get merged into systemd :)

Also, thank you @iam-TJ for writing this up, and making a clear case for this feature. Highly appreciated!

**Comment by yuwata** [comment]
Could you test #20808?

**Comment by yuwata** [comment]
The PR makes upstream link accept `DHCPv6PrefixDelegation=yes` and `[DHCPv6PrefixDelegation]`, and assign an address within each delegated prefix: if we receive e.g. `2000:2000:2000::/48`, then assign e.g. `2000:2000:2000:SUBNETID:aabb:ccdd:eeff:0011:2233:4455/64` (the address depends on `Token=` in `[DHCPv6PrefixDelegation]`). If it is not desired, then please feel free to request to reopen this page.

**Comment by yuwata** [comment]
@iam-TJ 
> The prefixlen of the assigned address should match that of (each of the) prefix(es) being delegated.

You mean, if we receive `2000:2000:2000::/48`, then we should assign an address with `/48`? How does it work with its temporary address? Also, how should we avoid the conflict with the addresses assigned to the downstream links?

Anyway, though the PR is already merged, if the PR does not work for you, please let me know (if it is possible, please report before v250 is released). Thank you.

**Comment by tokred** [comment]
I might be hitting a bug with this implementation using v250, please let me know if you'd prefer a dedicated issue:

I configured my WAN interface as described, and based on the example in https://github.com/systemd/systemd/blob/f370708084bf0d81e43360db103a44cbd2ed4aad/man/systemd.network.xml#L4443

**Issue:** Upon successful ISP-delegation of a /56 prefix on WAN, subsequent /64 subnets are properly assigned to LAN interfaces but on WAN, an address of the "full" /56 is assigned. `SubnetId` is ignored (0x00 seems to be used instead), and an additional /56 route is installed on WAN (which is overlapping with the unreachable route of the delegated prefix):

```
[Match]
Name=wan

[Network]
DHCP=yes
IPv6AcceptRA=yes
IPv6SendRA=no
# we want a delegated prefix also on WAN interface
DHCPPrefixDelegation=yes

[DHCPv6]
UseDelegatedPrefix=yes
PrefixDelegationHint=::/56
WithoutRA=solicit

[DHCPPrefixDelegation]
UplinkInterface=:self
SubnetId=0xf
Announce=no
```

Delegated prefix is _2001:db8:205:e900::/56_

Interfaces: The first v6 is the wrongly assigned /56 WAN IP (instead of /64), and ignoring the `SubnetId=0xf`. The second v6 is the IA_NA assigned IP (not relevant, could be removed with `UseAddress=no`)
```
$ ip -br a s dev wan
wan0  UP  x.y.220.189/30 2001:db8:205:e900:225:90ff:fef2:c636/56 metric 256 2001:db8:0:97:24e2:418:61c8:2433/128 fe80::225:90ff:fef2:c636/64 
```

For comparison, the properly assigned /64 subnet on LAN-side, with `SubnetId=0x0a` taken into account:
```
$ ip -br a s dev vlan10
vlan10  UP  192.168.1.1/24 2001:db8:205:e90a::1/64 metric 256 fe80::b8c5:82ff:fe11:fab5/64
```
using this config (`Assign` primarily for visibility):
```
[Match]
Name=vlan10

[Network]
IPv6AcceptRA=no
IPv6SendRA=yes
DHCPPrefixDelegation=yes

[DHCPPrefixDelegation]
SubnetId=0x0a
Announce=yes
Assign=yes
Token=::1
```

Resulting route table:
```
$ ip -6 route
2a02:8106:205:e90a::/64 dev vlan10 proto kernel metric 256 expires 5382sec pref medium
2a02:8106:205:e900::/56 dev wan proto kernel metric 256 expires 5382sec pref medium
unreachable 2a02:8106:205:e900::/56 dev lo proto dhcp metric 1024 pref medium
```

Is this a misconfiguration on my side, or a misbehaviour of the special case when assigning a PD address on WAN? I would expect a /64 assigned to WAN exactly the same way as LAN interfaces, no?

Thanks and regards

**Comment by yuwata** [comment]
@tokred Could you open a new issue?

**Comment by tokred** [comment]
created separate issue https://github.com/systemd/systemd/issues/22559
