### ISSUE TITLE
Ability to bind units to firewalld services

### ISSUE THREAD

**Issue by Jamstah** [systemd/systemd#20917]
**Is your feature request related to a problem? Please describe.**
Managing services that have firewall requirements

**Describe the solution you'd like**
Add a `FirewallService=` (or similar) option to unit files that will add the firewall service on unit start, and remove it on unit stop.

**Describe alternatives you've considered**
Doing it manually... Leaving the ports opens... Using an ExecStart and ExecStop to run firewall-cmd...

The idea here is to make it declarative and something that packages can install as default behaviour on systems with both systemd and firewalld.

**The systemd version you checked that didn't have the feature you are asking for**
249

**Comment by poettering** [comment]
This is something firewalld can provide on its own. It can implement a service template `firewall@.service` if they want, and that you can then pull in from your service of choice via `Wants=` + `After=`. If that firewalld template service then uses "StopWhenUnused=1" in its definition that service will be pulled in whenever the consuming service needs it and then exit whenever it isn't needed anymore. That template service can then talk to firewalld to allow some ports or not.

Let's close, because firewalld can do this easily on its own if it wants to, all the necessary hooks and knobs in systemd already exist.

**Comment by Jamstah** [comment]
Neat approach. Have suggested it here: https://github.com/firewalld/firewalld/issues/862
