### ISSUE TITLE
document that "systemctl disable" does not support unit file paths, but only unit file names

### ISSUE THREAD

**Issue by mmstick** [systemd/systemd#2098]
I've noticed that in recent versions of systemd (228) on Arch Linux, the dbus interface isn't accepting pathnames, like `/usr/lib/systemd/system/sshd.service`, for DisableUnitFiles(). However, it still works for EnableUnitFiles(). I'm currently working around this by just passing the filename, `sshd.service`, rather than the pathname.

On my Gentoo install, which uses an older version of systemd (218), it does accept pathnames so sometime between there and 228, DisableUnitFiles stopped working with pathnames.

**Comment by poettering** [comment]
This is actually on purpose. While "systemctl enable" accepts both unit files by name and by path, "systemctl disable" only takes unit names by path. This is simply because the operation behind "systemctl disable" is supposed to unlink a unit fully from the system, and it doesn't really care by which path it is referenced.

But this is seriously underdocumented in systemctl(1), and we should fix that. Will convert the bug now into a documentation bug to get this fixed.

**Comment by keszybz** [comment]
Obsoleted by 1d3c86c06fca8311923fcf81af0ab0bbb66e1edd.
