### ISSUE TITLE
homed direct-io for [at least] btrfs luks images

### ISSUE THREAD

**Issue by DomingoMontoya** [systemd/systemd#21003]
Mounting of home volumes is currently done without direct-io loopback support. Maybe there's a reason for this, but it's extremely slow on my btrfs on luks on btrfs on luks configuration.

Copying/moving from my homed $HOME to a folder outside of $HOME yields about 150-250MBps on an NVMe.

Using losetup to switch the loopback device for my home folder to direct-io yields much faster speeds - over 1GBps.

If there's a reason that mounting the image file is done the current way, could we at least have a settable option for each user [homectl] and system default so it doesn't have to be changed after mounting/login every time?

**Comment by poettering** [comment]
The main reason is that documentation on this is so sparse... Do you have any hints where this is documented further?

Would there be any reason *not* to enable this? i.e. why doesn't `losetup` default to it?

But maybe we can steal tweaks like this from here:

https://android.googlesource.com/platform/system/apex/+/refs/heads/master/apexd/apexd_loop.cpp

**Comment by poettering** [comment]
Note to self: that android apexd code forcible sets the IO elevator for block devices to "noop". Current development kernels default to that anyway, hence I figure we should not copy that part of what apexd doess.

**Comment by poettering** [comment]
apexd also does the following:

1. Set the IO elevator queue depth of loopback devices to 2x the one of the underlying device
2. It sets the read-ahead to 128, which however is the default anyway afaics.
3. Invokes BLKFLSBUF ioctl after LOOP_SET_STATUS64 to work around some kernel bug (which might have been fixed by now?)
4. Sets the block size of the loopback device to 4096K unconditionally
