### ISSUE TITLE
Systemd frequently remounts filesystem for some reason (???)

### ISSUE THREAD

**Issue by plomari** [systemd/systemd#21010]
**systemd version the issue has been seen with**
 > 249.5-1 (debian unstable package version)

**Used distribution**
 > debian unstable, up-to-date as of now

**Linux kernel version used** (`uname -a`)

 > `5.10.68` (vanilla, custom kernel config)

**CPU architecture issue was seen on**
 > AMD x86_64

**Expected behaviour you didn't see**
 > systemd shouldn't frequently bind mind stuff on `/run/systemd/unit-root/etc`

**Unexpected behaviour you saw**
 > systemd remounts something on `/run/systemd/unit-root/etc` every time I open or save a file with firefox (HOW????)

**Steps to reproduce the problem**
 > I don't know, open firefox, open a website, and save it by using ctrl+s?

**Additional program output to the terminal or log subsystem illustrating the issue**

I get this on dmesg:

> [  +0.001562] xfs filesystem being remounted at /run/systemd/unit-root/etc supports timestamps until 2038 (0x7fffffff)

There are a lot of these, every dozens of minutes. One observed trigger is saving or opening a file in firefox (go to a random website and hit ctrl+s). It's up to you to figure out why.

This could be my root filesystem. It's the only xfs formatted partition I know about in the system. It's probably my root filesystem. The warning appears early in the boot process too (before the upgrade to the current debian unstable systemd version, and where it did not flood the kernel log with these remount messages).

Is it really systemd? It was notable that this happened after `apt dist-upgrade`, that systemd was updated, and that the remount path seems to have to do with systemd.

Yes, the xfs filesystem will probably fail in unexpected ways in 2038. That is not the problem. The problem is that systemd seems to trigger these remounts, and the message just happens to highlight this fact. (Also, I hope it's just a bind remount, and that systemd isn't corrupting my root file system right now.)

Please tell me how to stop systemd from doing this.

**Comment by floppym** [comment]
Isolating systemd from dbus is not feasible. They are interdependent on one another.

**Comment by floppym** [comment]
This is a bug/issue tracker, and I don't think this is really a bug.

Your question(s) about how/why systemd works would be better directed to the systemd-devel mailing list.

**Comment by floppym** [comment]
systemd-hostnamed.service has ReadWritePaths=/etc. That probably causes the mount calls you are seeing. You can read more about this in the manual.

https://www.freedesktop.org/software/systemd/man/systemd.exec.html

Based on the description, I believe if / was mounted read-only, this setting would not cause it to be remounted read/write.

**Comment by mbiebl** [comment]
Let me add here, that we got downstream bug reports about this in Debian as well.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996876

It appears to be a result of #20023

I suspect, since Fedora/Redhat do enable SELinux by default, you haven't seen any users run into this yet on those distros.
I notice, that this feature has been discussed controversially.
Given that it is basically disabled for half of the Linux population (Fedora/Redhat) anyway and causes this issue on XFS and the security benefits are minimal, could we re-evaluate whether to revert this commit again?
@topimiettinen ^

**Comment by mbiebl** [comment]
Just curious: Is XFS still the default for Redhat?

**Comment by mbiebl** [comment]
right, Linus proposed a different approach.

**Comment by topimiettinen** [comment]
There are similar messages also for ext4:
```
Oct 20 20:56:43 kernel: ext4 filesystem being mounted at /run/systemd/unit-root/var/lib/systemd/timesync supports timestamps until 2038 (0x7fffffff)
Oct 20 20:56:44 kernel: ext4 filesystem being mounted at /run/systemd/unit-root/var/lib/iwd supports timestamps until 2038 (0x7fffffff)
Oct 20 20:56:45 kernel: ext4 filesystem being mounted at /run/systemd/unit-root/var/lib/smartmontools supports timestamps until 2038 (0x7fffffff)
Oct 20 20:57:26 kernel: ext4 filesystem being mounted at /run/systemd/unit-root/var/lib/upower supports timestamps until 2038 (0x7fffffff)
```
I think Linus' approach is most reasonable.

Though since 2038 is several years beyond, perhaps it would not be unreasonable to remove the message entirely. Is there anything the system administrator could do about file system timestamps, like enable 64 bit timestamps and run `fsck`? If not, the message just wastes resources.

I don't think there's anything wrong with systemd doing lots of mounting and remounting. It's part of it's job because services enable various options and using mount namespaces (one of the key sandboxing technologies) requires lots of mounts.

**Comment by poettering** [comment]
> I maintain that unprivileged user processes should not be able to cause mount hierarchy changes with default settings.

Yeah, but this was always possible. Via autofs, udisks, and so on. As long as the rules which mounts to establish on demand are controlled by privileged code, it doesn't matter whether they are established at boot or lazily when requested by possibly unprivileged code. An unprivileged trigger is fine — if the unprivileged code could directly influence what to mount where, that'd be a problem, but it cannot do this.

There's nothing actionable. Yes, the kmsg line about it is confusing, but that's really just a cosmetic issue, and something to address within kernel territory. If anyone wants to see this addressed please work with kernel devs.

**Comment by socketpair** [comment]
So, what's the status in upstream kernel ? Fedora 36: still seeing this annoying message.
