### ISSUE TITLE
RFE: systemd-socket-proxyd does not wait for socket to be ready

### ISSUE THREAD

**Issue by ticpu** [systemd/systemd#2105]
When using a service that does not notify systemd when ready, for example; VLC, socket-proxyd will refuse the first connection then accept the next one.

There should be a way to make it wait for the socket to be listening (and time-out if needed) when first started up.

After making a script using netcat to check for a listening socket, I found out I was not alone in doing so.

https://developer.atlassian.com/blog/2015/03/docker-systemd-socket-activation/

The ultimate way to fix this is to make the underlying service systemd aware, but for compatibility, this should be an option.

**Comment by ticpu** [comment]
I was wondering, is there any better way to know if the socket is open than to repeatedly trying to connect or looking up /proc/net/tcp{,6} at an interval?

**Comment by poettering** [comment]
This really sounds as if the service in question should be fixed to properly notify systemd about when it has finished initialization. We cannot guess that from the outside really. Sorry.

Checking /proc/net/tcp in a loop is not really an option, we don't want to do such hacks. And even if the kernel would provide a proper notification interface for this, it'd be really error prone, as the configuration in the unit file could easily get out of sync with what the service is actually listening on.

Instead of adding a hack to systemd here, it's really the better idea to just fix the service in question to notify systemd about being ready with sd_notify() or by taking a name on the bus.

Sorry, but I don't see anything we could do here. Closing hence.
