### ISSUE TITLE
StandardOutput documentation does not mention inherit default when StandardInput is set

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#2114]
It appears that when setting `StandardInput=socket`, `StandardOutput` changes default from `journal` to `inherit`. The [guide for administrators](http://0pointer.de/blog/projects/inetd.html) also mentions this property.

This is not documented in `systemd.exec`. There should be documentation on when this default is changed, and how it interacts with `DefaultStandardOutput` in `systemd.conf`

**Comment by dkg** [comment]
I just ran into this myself.  It was pretty confusing!

to be clear:

```
0 dkg@alice:~$ systemctl --user cat test-stdin.service test-normal.service
# /home/dkg/.config/systemd/user/test-stdin.service
[Unit]
Descriptor=test service file: on stdin

[Service]
ExecStart=/usr/bin/yes hello
StandardInput=file:/tmp/foo

# /home/dkg/.config/systemd/user/test-normal.service
[Unit]
Descriptor=test service no stdin

[Service]
ExecStart=/usr/bin/yes hello
0 dkg@alice:~$ systemctl --user show --property='StandardInput,StandardOutput' test-stdin.service
StandardInput=file
StandardOutput=inherit
0 dkg@alice:~$ systemctl --user show --property='StandardInput,StandardOutput' test-normal.service
StandardInput=null
StandardOutput=journal
0 dkg@alice:~$ 
```

and `systemd.exec(5)` says:
```
StandardInput=
[…]
           This setting defaults to null.
[…]
StandardOutput=
[…]
           This setting defaults to the value set with DefaultStandardOutput=
           in systemd-system.conf(5), which defaults to journal.
```

but:

```
0 dkg@alice:~$ grep DefaultStandard /etc/systemd/system.conf 
#DefaultStandardOutput=journal
#DefaultStandardError=inherit
0 dkg@alice:~$ 
```

Whereas [part XI (converting Inetd services)](http://0pointer.de/blog/projects/inetd.html) says:

> Note that we do not need to explicitly configure `StandardOutput=` here, since by default the setting from `StandardInput=` is inherited if nothing else is configured.

The documentation in the manual is clear and understandable, but does not correspond to reality when `StandardInput=` is set.  The documentation in part XI is clearly wrong in the general case, since it is *not* the case that `StandardOutput=` is set to `inherit` when `StandardInput=` is unset (or when it is explicitly set to `null`).  But i don't know what to expect from an unset `StandardOutput=` in the general case.  Is the logic supposed to be something like this:

 * if `StandardInput=` is set to some non-null value, then `StandardOutput=` defaults to `inherit`
 * otherwise, `StandardOutput=` defaults to `inherit`

Or is there more nuance/subtlety to it?

To make matters even more confusing, `user.conf` states a different commented-out value for `
DefaultStandardOutput=` than `system.conf.in` states.

Please align the documentation with the behavior, or vice versa!

**Comment by keszybz** [comment]
I tried to figure out what exactly is happening in the code, but it's such a twisted maze of little passages that I gave up. 
@poettering, maybe you could try give this a go? This is one of our oldest documentation bugs.

**Comment by poettering** [comment]
We should rework the code, so that the internal variables work the same way as enums usually work in our code: i.e. instead of using `STANDARD_INPUT_NULL`/`STANDARD_OUTPUT_NULL` as the magic default value, do it properly, and use `_EXEC_INPUT_INVALID` and `_EXEC_OUTPUT_INVALID`...

i.e. the reason i never bothered to fix the docs to match the code was because I thought the code should be fixed to work sanely... because right now it's kinda stupid to handle the null input/output so special. But i never came around to fix the code...

(and when we fix that, also address https://bugzilla.freedesktop.org/show_bug.cgi?id=43872)

**Comment by neosimsim** [comment]
Ran into this too.

**Comment by neosimsim** [comment]
Is there a way to set StandardOutput to the value of DefaultStandardOutput again or would the workaround be to set StandardOutput to journal for my unit?
