### ISSUE TITLE
Improve Suspend-Then-Hibernate functionality on Linux

### ISSUE THREAD

**Issue by axet** [systemd/systemd#21165]
**Is your feature request related to a problem? Please describe.**

suspend-then-resume is very noisy. Between suspend and hibernate it wake-up machine, starts display with few flickering, starts background music (if currently playing) and hibernate with few screen flickering.

**Describe the solution you'd like**

- [ ] ~~Create a new top-level cgroup and move everything below it, so that it can be frozen to avoid wasting power/resuming tasks, without affecting the wakeup handler which would be in a separate hierarchy - eg, /sys/fs/cgroup/root gets frozen and /sys/fs/cgroup/s2h keeps running with the handler~~
- [ ] ~~Hide the new top-level /sys/fs/cgroup/root/ so that existing hard-coded assumptions are not broken by creating a cgroup namespace early at boot where to move PID1 into, mounting /sys/fs/cgroup/s2h under /run/systemd/ so that it can be accessed~~
- [x] Estimate battery consumption and set up timed wakeup to assess again
- [x] Handle when to wake up for the first check (no previous data to do an estimation)
- [x] Record estimates/consumption on machine-specific (keyed by /etc/machine-id) storage location for reuse on future reboots
- [x] Add support for ACPI _BTP so that the bios/hw will trigger a wakeup when battery is low
- [x] Freeze/thaw `user.slice` on suspend/resume
- [ ] ~~Add qemu-based automated tests exercising as much of this feature as possible. Qemu/KVM support suspend/hibernate.~~

**Describe alternatives you've considered**

I guess, before suspend, machine should be prepared and moved in special state with blackscreen and no background sounds (suspended user apps), then after resume screen will be blank and hiberate process will continue in silince. Then after resume from hibernate it should restore black screen into normal screen and background sounds.

**The systemd version you checked that didn't have the feature you are asking for**

systemd-247.3-6

**Comment by khansaUmatullah** [comment]
> We have funding for an Outreachy internship to work on exactly this issue. Looking for candidates at the moment: #20928 These are the high-level tasks: https://github.com/systemd/systemd/projects/2

@bluca I wanna work on this project. I'm working on repeatable tasks

**Comment by poettering** [comment]
Hmm, I wonder if a simple approach might be to simply freeze `user.slice` (and only that) before going into s2h, but leaving everything else running. This means all user code/apps will freeze and not come back and run when we change from suspend to hibernate, but all system code will resume for that moment. I think for most things that would be entirely sufficient and would simplify the problem quite a bit since we wouldn't have to rearrange the cgroup tree in major ways, and we wouldn't have to write our suspend code in a way it would never ever use any other services's apis.

Thus, we'd simply issue FreezeUnit(user.slice) before going into s2h, and then ThawUnit(user.slice) after coming back fully.

**Comment by bluca** [comment]
Given the Outreachy project is not going ahead this semester, here's the tasks converted:

- [ ] Create a new top-level cgroup and move everything below it, so that it can be frozen to avoid wasting power/resuming tasks, without affecting the wakeup handler which would be in a separate hierarchy - eg, /sys/fs/cgroup/root gets frozen and /sys/fs/cgroup/s2h keeps running with the handler
- [ ] Hide the new top-level /sys/fs/cgroup/root/ so that existing hard-coded assumptions are not broken by creating a cgroup namespace early at boot where to move PID1 into, mounting /sys/fs/cgroup/s2h under /run/systemd/ so that it can be accessed
- [ ] Estimate battery consumption and set up timed wakeup to assess again
- [ ] Handle when to wake up for the first check (no previous data to do an estimation)
- [ ] Record estimates/consumption on machine-specific (keyed by /etc/machine-id) storage location for reuse on future reboots
- [ ] Add support for ACPI _BTP so that the bios/hw will trigger a wakeup when battery is low
- [ ] Add qemu-based automated tests exercising as much of this feature as possible. Qemu/KVM support suspend/hibernate.

**Comment by JeWe37** [comment]
Imma just cut in here briefly: One issue that I've been having with suspend-then-hibernate has been that it can only sleep for a set amount of time rather than being able to wake up at a specified time. This would be useful if say once 9pm has past, you're pretty sure you won't be getting back to your PC again for the day if it's currently in sleep mode. I've thought up how I can hack together this functionality using WakeUp=true timers already but it would definitely be nice to have a more "proper" solution for this. Perhaps that's also something to consider whilst doing this.

I've looked at the code and as it stands it's really rather simple to work with, so I would look into it myself perhaps if I find the time, but I don't want to interfere with this other project and I have little to no idea how a proper configuration interface to this functionality would look.

**Comment by JeWe37** [comment]
Perhaps this could be combined with #16052 ? The interface proposed there seems suboptimal, since as I think that waking up at a set time is pretty much the only practical alternative use, but perhaps an additional timer OnCalendar-esque parameter in the configuration files would work? 

I might look into this myself, the code looks fairly manageable in its current state, but I believe I have a solution for how to hack this together with timers for my use case and I don't really wanna interfere with the outreachy project or anything.
