### ISSUE TITLE
varlink client example

### ISSUE THREAD

**Issue by vishwanathchandapur** [systemd/systemd#21182]
Hi
Do you have any client test application to test varlink resolveHostname and resolveAddress API.
Thanks

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
