### ISSUE TITLE
systemctl preset-all fails completely on any error

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#21224]
If one of the services is a broken symlink, `systemdctl preset-all` does not go further:

```
[root@rt ~]# file /etc/systemd/system/syslog.service
/etc/systemd/system/syslog.service: broken symbolic link to /lib/systemd/system/rsyslog.service
[root@rt ~]# systemctl preset-all
Failed to preset all units: File syslog.service: Link has been severed
[root@rt ~]# echo $?
1
[root@rt ~]# rm -fv /etc/systemd/system/syslog.service
удалён '/etc/systemd/system/syslog.service'
[root@rt ~]# systemctl preset-all
Failed to preset all units: File dbus-org.freedesktop.oom1.service: Link has been severed
```

Similar to https://github.com/systemd/systemd/issues/19407 , but an other error.

systemd-249-1.gitfab79a.1.x86_64

**Comment by AdamWill** [comment]
so ultimately the problem is [here in unit_file_preset_all](https://github.com/systemd/systemd/blob/d840783db5208219c78d73b9b46ef5daae9fea0a/src/shared/install.c#L3685), where if we encounter an error outside of the ones we ignore entirely, we don't just propagate it, we propagate it *immediately* and drop out of the loop, not attempting to apply any later presets. I guess that loop should instead always complete, but store up errors as it goes and return them all at the end.

**Comment by AdamWill** [comment]
note as discussed [here downstream](https://bodhi.fedoraproject.org/updates/FEDORA-2024-02ed8700f4#comment-3508294), this breaks Fedora installs (using the traditional installer) with systemd 256, because anaconda bind mounts `/run` into the install target directory. The installer environment's `/run` contains a generated `sshd-vsock@` service, but the first time we hit this preset-all logic during the package install process, sshd isn't installed yet, so it bails out.
