### ISSUE TITLE
"systemd-run --user" accepts properties it probably should not

### ISSUE THREAD

**Issue by ondrejv2** [systemd/systemd#21247]
systemd-249

cgroups v2, Fedora 34

Unexpected behaviour:

$ systemd-run --user -p MemoryMax=10G ....

is happily accepted although ignored. I guess an ordinary user has no rights to change property like MemoryMax, so systemd-run should probably exit with error

**Comment by poettering** [comment]
First of all: configuring settings is one thing, applying another. We generally want our unit files (and thus also our systemd-run cmdlines) to be roughly portable, hence we parse for general validity, not for specific validity: i.e. accept anything that could apply in theory, even if it locally doesn't make sense. example: we happily parse a CPU affinity consisting of 256 CPUs even if the local machine has only a single one.

We also apply many settings gracefully, i.e. proceed even if we can't apply them, for the same reason. This is particular true for resource mgmt settings, as they are about tweaking resources generally, and not a requirement to make something work. In the logs you'll find details about this (but much of it only at debug level, since things becomes too noisy otherways in many cases).

Finally, MemoryMax= actually works fine in user mode, as long as you enable cgroupsv2 mode. These settings are per unit, and recursive, i.e. each user can put any limits it wants, but things are always restricted by the limits further up the tree too.

With other words: the behaviour you describe is intended, it's good that way.
