### ISSUE TITLE
evdev hwdb entry for Toshiba Satellite Pro C665

### ISSUE THREAD

**Issue by ig3** [systemd/systemd#21284]
**Is your feature request related to a problem? Please describe.**
I ran `libinput measure touchpad-size` and it reported:

```
Using "SynPS/2 Synaptics TouchPad": /dev/input/event5
Kernel specified touchpad size: 63.9x32.1mm
User specified touchpad size:   82.0x42.0mm

Kernel axis range:   x [1472..5692], y [1408..4680]
Detected axis range: x [1122..5863], y [ 951..5118]
```
And advised to add a hwdb entry:

```
Suggested hwdb entry:
Note: the dmi modalias match is a guess based on your machine's modalias:
  dmi:bvnINSYDE:bvr1.00:bd04/01/2011:br1.0:efr1.0:svnTOSHIBA:pnSatelliteProC665:pvrPSC2FA-002002:rvnTOSHIBA:rnPortablePC:rvrBaseBoardVersion:cvnOEMChassisManufacturer:ct10:cvrOEMChassisVersion:
Please verify that this is the most sensible match and adjust if necessary.
-8<--------------------------
# Laptop model description (e.g. Lenovo X1 Carbon 5th)
evdev:name:SynPS/2 Synaptics TouchPad:dmi:*svnTOSHIBA:*pnSatelliteProC665**
 EVDEV_ABS_00=1122:5863:58
 EVDEV_ABS_01=951:5118:99
 EVDEV_ABS_35=1122:5863:58
 EVDEV_ABS_36=951:5118:99
-8<--------------------------
Instructions on what to do with this snippet are in /usr/lib/udev/hwdb.d/60-evdev.hwdb
``` 

**Describe the solution you'd like**
Add the following entry to 60-evdev.hwdb:

```
# Toshiba Sattelite Pro C665 
evdev:name:SynPS/2 Synaptics TouchPad:dmi:*svnTOSHIBA:*pnSatelliteProC665** 
 EVDEV_ABS_00=1122:5863:58 
 EVDEV_ABS_01=951:5118:99 
 EVDEV_ABS_35=1122:5863:58 
 EVDEV_ABS_36=951:5118:99
```
**Describe alternatives you've considered**
I have added the same entry to /etc/udev/hwdb.d/61-evdev.hwdb, per the comments in 60-evdev.hwdb, and it seems to work. This is sufficient for me but in case you consider that this entry might be more generally applicable, I thought I would send it along, per the comments.

**The systemd version you checked that didn't have the feature you are asking for**

Current master at https://github.com/systemd/systemd

**Comment by ig3** [comment]
After adding the entry to /etc/udev/hwdb.d/61-evdev.hwdb:
```
$ udevadm info /sys/class/input/event5
P: /devices/platform/i8042/serio1/input/input5/event5
N: input/event5
L: 0
S: input/by-path/platform-i8042-serio-1-event-mouse
E: DEVPATH=/devices/platform/i8042/serio1/input/input5/event5
E: DEVNAME=/dev/input/event5
E: MAJOR=13
E: MINOR=69
E: SUBSYSTEM=input
E: USEC_INITIALIZED=5845571
E: EVDEV_ABS_00=1122:5863:58
E: EVDEV_ABS_01=951:5118:99
E: EVDEV_ABS_35=1122:5863:58
E: EVDEV_ABS_36=951:5118:99
E: ID_INPUT=1
E: ID_INPUT_TOUCHPAD=1
E: ID_INPUT_WIDTH_MM=81
E: ID_INPUT_HEIGHT_MM=42
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-1
E: ID_PATH_TAG=platform-i8042-serio-1
E: ID_INPUT_TOUCHPAD_INTEGRATION=internal
E: LIBINPUT_DEVICE_GROUP=11/2/7:isa0060/serio1
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-1-event-mouse
```

**Comment by poettering** [comment]
*[Canned reply follows]*

We detected you posted a patch in a GitHub *Issue*. Please submit the patch as a GitHub *Pull* *Request* ("PR") instead. That way we can directly merge your work into our tree, with proper attribution, automatic CI testing, maintainer reviews and similar.

Like most Open Source maintainers we have a lot of work to do, thus it would be of great help for us if patches like yours are submitted through the proper channels (i.e. as PR as suggested above), to minimize our workload, and take benefit of the automatic build and test pipeline that is attached to the PR concept.

In case you posted this issue because you were unsure whether it would be a patch we'd consider for merging: please still submit patches as PRs either way, the decision whether to merge it or not is orthogonal to the form of submission. — Don't ask whether it is OK to submit a patch, please always just submit the patch instead right-away, if you already have it anyway.

Thank you for understanding!
