### ISSUE TITLE
nfs mount delays system shutdown

### ISSUE THREAD

**Issue by JonathanKang** [systemd/systemd#21303]
**systemd version the issue has been seen with**
 > 249.4(openSUSE Tumbleweed) and 249.6(Fedora 35)

**Used distribution**
 > Answered above

**Linux kernel version used** (`uname -a`)

 > `Linux jonathan-x1 5.14.16-301.fc35.x86_64 #1 SMP Wed Nov 3 13:55:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Expected behaviour you didn't see**
 > nfs mount doesn't delay system shutdown

**Unexpected behaviour you saw**
 > With a nfs mount(this is achieved in /etc/fstab), and wireless connection enabled. when shutting down the system, the process is delayed about 1 to 2 minutes, and systemd complains: `Unmounting timed out. Terminating.`

**Steps to reproduce the problem**
 > 1. A system with only wireless connection. And set this connection only available to current user.
 > 2. Add a nfs mount using /etc/fstab: `host:/path/to/mount    /mnt/mount-point    nfs    defaults    0 0`
 > 3. Shutdown the system and observe long shutdown time.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
https://gist.github.com/JonathanKang/b6ce9f9aaad2b22dff72380c725e671b
```

The wireless connection is only available to the current user. So when shutting down the system, the wireless connection goes down at a quite early stage, which makes the nfs server unreachable. Thus systemd is unable to successfully unmount it.

The logs provided are from openSUSE Tumbleweed. There exists an NetworkManager dispatcher script named `nfs`, which tries to mount/unmount nfs file system when the network goes up/down. But it failed to do so. This is because dbus said it was about to shutdown and refused the activation. However, in Fedora, there is no such a script. So just ignore this.

Maybe we need a target indicating that the whole system is offline? And nfs unmounts should happen before this target. I'd love to hear your thoughts on this.

Thanks.

**Comment by marcosfrm** [comment]
> > 1. A system with only wireless connection. And set this connection only available to current user.

This NetworkManager behaviour also affects SMB shares:

https://bugzilla.gnome.org/show_bug.cgi?id=788253
https://github.com/systemd/systemd/issues/1435#issuecomment-332795236

I think the fix is... make the connection global in NetworkManager...

**Comment by poettering** [comment]
So you have a system owned resource (i.e. the NFS share mounted via /etc/fstab) that is dependent on a user owned/managed resource (i.e. the user-controlled network link)?

System resources that depend on user resources is always a mess, security-wise and in context of robustness. My answer would always be: don't do this. It's OK if user stuff depends on system stuff or other user stuff. It's also OK if system stuf depends on other system stuff. But system stuff that relies on user stuff? Nope, bad idea. Having unprivileged stuff be in control of something privilege stuff needs is not a good idea.

Hence my response here would be:

1. Make the NFS share a user managed thing too, so that the user is responsible for both
2. Make the network connection a system owned thing.

In the latter case everything should just work: if things like remote-fs-pre.target are properly used by your distro, then systemd will take down NFS before taking down the network.

**Comment by JonathanKang** [comment]
> Hence my response here would be:
> 1. Make the NFS share a user managed thing too, so that the user is responsible for both
> 2. Make the network connection a system owned thing.

@poettering Thanks for the explanation. That is a fair point. I'm closing this.
