### ISSUE TITLE
hwdb update for Plantronics Savi headsets

### ISSUE THREAD

**Issue by sherbang** [systemd/systemd#21381]
**systemd version the issue has been seen with**
 > systemd 247 (247.3-3ubuntu3.6pop0~1631829388~21.04~08ab711)

**Used distribution**
 > Pop!_OS 21.04

**Linux kernel version used** (`uname -a`)

 > `5.13.0-7614-generic #14~1631647151~21.04~930e87c-Ubuntu SMP`

**CPU architecture issue was seen on**
 > x86_64

**Unexpected behaviour you saw**
 > Plantronics D200 USB headset adapter paired with a Savi 8200 headset repeatedly sends volume-down keypresses.

**Steps to reproduce the problem**
 > Plug in the D200, make sure a headset is paired.  Problem persists until device is unplugged

**Additional program output to the terminal or log subsystem illustrating the issue**

evtest output when the problem is occuring
```text
# sudo evtest /dev/input/event8
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x47f product 0xab04 version 0x111
Input device name: "Plantronics Plantronics Savi 8200 UC Series"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 163 (KEY_NEXTSONG)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1637016760.753702, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00ea
Event: time 1637016760.753702, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 1
Event: time 1637016760.753702, -------------- SYN_REPORT ------------
Event: time 1637016760.754686, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00ea
Event: time 1637016760.754686, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 0
Event: time 1637016760.754686, -------------- SYN_REPORT ------------
Event: time 1637016762.653681, type 4 (EV_MSC), code 4 (MSC_SCAN), value c00ea
Event: time 1637016762.653681, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 1
Event: time 1637016762.653681, -------------- SYN_REPORT ------------
```
`udevadm info` output
```text
P: /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2.2/1-8.2.2:1.0/0003:047F:AB04.0168/input/input299/event20
N: input/event20
L: 0
S: input/by-path/pci-0000:00:14.0-usb-0:8.2.2:1.0-event
S: input/by-id/usb-Plantronics_Plantronics_Savi_8200_UC_Series_96586D8886C0415E9608615DC040C0A2-event-if00
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.2/1-8.2.2/1-8.2.2:1.0/0003:047F:AB04.0168/input/input299/event20
E: DEVNAME=/dev/input/event20
E: MAJOR=13
E: MINOR=84
E: SUBSYSTEM=input
E: USEC_INITIALIZED=2429267742619
E: KEYBOARD_KEY_c00ea=reserved
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_VENDOR=Plantronics
E: ID_VENDOR_ENC=Plantronics
E: ID_VENDOR_ID=047f
E: ID_MODEL=Plantronics_Savi_8200_UC_Series
E: ID_MODEL_ENC=Plantronics\x20Savi\x208200\x20UC\x20Series
E: ID_MODEL_ID=ab04
E: ID_REVISION=3846
E: ID_SERIAL=Plantronics_Plantronics_Savi_8200_UC_Series_96586D8886C0415E9608615DC040C0A2
E: ID_SERIAL_SHORT=96586D8886C0415E9608615DC040C0A2
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030000:010100:010200:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:8.2.2:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_8_2_2_1_0
E: XKBLAYOUT=us
E: BACKSPACE=guess
E: XKBMODEL=pc105
E: LIBINPUT_DEVICE_GROUP=3/47f/ab04:usb-0000:00:14.0-8.2
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:8.2.2:1.0-event /dev/input/by-id/usb-Plantronics_Plantronics_Savi_8200_UC_Series_96586D8886C0415E9608615DC040C0A2-event-if00
E: TAGS=:power-switch:
E: CURRENT_TAGS=:power-switch:
```
# hwdb entry that solves the problem:
```text
# Disable weird volume-down keypresses from Plantronics SAVI D200
evdev:input:b0003v047FpAB04*
    KEYBOARD_KEY_c00ea=reserved
```

**Comment by poettering** [comment]
*[Canned reply follows]*

We detected you posted a patch in a GitHub *Issue*. Please submit the patch as a GitHub *Pull* *Request* ("PR") instead. That way we can directly merge your work into our tree, with proper attribution, automatic CI testing, maintainer reviews and similar.

Like most Open Source maintainers we have a lot of work to do, thus it would be of great help to us if patches like yours are submitted through the proper channels (i.e. as PR as suggested above), to minimize our workload, and to take benefit of the automatic build and test pipeline that is attached to the PR concept.

In case you posted this issue because you were unsure whether it would be a patch we'd consider for merging: please still submit patches as PRs either way, the decision whether to merge it or not is orthogonal to the form of submission. — Don't ask whether it is OK to submit a patch, please always just submit the patch instead right-away, if you already have it anyway.

Thank you for understanding!

**Comment by AsciiWolf** [comment]
It looks like that this was still not added.

**Comment by poettering** [comment]
if this is interesting to you, submit a PR, not an issue.
