### ISSUE TITLE
sd_bus_query_sender_privilege() capability argument has no effect, and should be removed (left-over kdbus stuff)

### ISSUE THREAD

**Issue by DannyPlusPlus** [systemd/systemd#21586]
1.The dbus monitor capture the message:
method call time=1637784128.987913 sender=:1.21 -> destination=org.freedesktop.timedate1 serial=56 path=/org/freedesktop/timedate1; interface=org.freedesktop.timedate1; member=SetTimezone
   string "Africa/Abidjan"
   boolean false
method call time=1637784128.988227 sender=:1.32 -> destination=org.freedesktop.DBus serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetConnectionUnixUser
   string ":1.21"
method return time=1637784128.988278 sender=org.freedesktop.DBus -> destination=:1.32 serial=5 reply_serial=6
   uint32 1000
error time=1637784128.988473 sender=:1.32 -> destination=:1.21 error_name=org.freedesktop.DBus.Error.AccessDenied reply_serial=56

2.the 1.21 process user id is 1000, it has CAP_SYS_TIME,but can't SetTimezone

3.  in sd_bus_query_sender_privilege,the code （ r = sd_bus_query_sender_creds(call, SD_BUS_CREDS_UID|SD_BUS_CREDS_EUID|SD_BUS_CREDS_AUGMENT|SD_BUS_CREDS_EFFECTIVE_CAPS, &creds);）may have a bug that SD_BUS_CREDS_EFFECTIVE_CAPS has no effect.

**Comment by poettering** [comment]
The client cap is without effect, we can't check that safely on AF_UNIX. The fact we still write it down is a kdbus remnant (where we could do that safely).

Ideally AF_UNIX would support SCM_CAPS or so, so that we could implement this safely...

But given this hasn't happened so far, i guess we can remove any mention of the cap in sd-bus code for priv checks.
