### ISSUE TITLE
systemd-growfs requires that udev ran first to work (because /dev/block/ symlinks must exist)

### ISSUE THREAD

**Issue by tewarid** [systemd/systemd#21592]
**systemd version the issue has been seen with**

v249.7

**Used distribution**
**Linux kernel version used** (`uname -a`)
**CPU architecture issue was seen on**

```text
sh-5.1# uname -a
Linux raspberrypi0-wifi 5.10.81 #1 Mon Nov 22 14:00:03 UTC 2021 armv6l
```

**Expected behaviour you didn't see**

root fs does not get resized.

The following works from shell

```
sh-5.1# /lib/systemd/systemd-growfs /
Successfully resized "/" to 348.3M bytes.
```

However, root fs does not get resized to fill all space available on sd card (e.g. 7.5GB of 7.9GB remains available).

**Unexpected behaviour you saw**

```text
sh-5.1# systemctl status -l systemd-growfs@-
x systemd-growfs@-.service - Grow File System on /
     Loaded: loaded (/run/systemd/generator/systemd-growfs@-.service; generated)
     Active: failed (Result: exit-code) since Fri 2021-11-19 17:19:34 UTC; 31s ago
       Docs: man:systemd-growfs@.service(8)
    Process: 111 ExecStart=/lib/systemd/systemd-growfs / (code=exited, status=1/FAILURE)
   Main PID: 111 (code=exited, status=1/FAILURE)

Nov 19 17:19:34 raspberrypi0-wifi systemd[1]: Starting Grow File System on /...
Nov 19 17:19:34 raspberrypi0-wifi systemd-growfs[111]: Failed to open "/dev/block/179:2": No such file or directory
Nov 19 17:19:34 raspberrypi0-wifi systemd[1]: systemd-growfs@-.service: Main process exited, code=exited, status=1/FAILURE
Nov 19 17:19:34 raspberrypi0-wifi systemd[1]: systemd-growfs@-.service: Failed with result 'exit-code'.
Nov 19 17:19:34 raspberrypi0-wifi systemd[1]: Failed to start Grow File System on /.
```

**Steps to reproduce the problem**

/etc/fstab is setup to grow root fs

```
/dev/root            /                    auto       defaults,x-systemd.growfs              1  1
```

**Comment by poettering** [comment]
Note that systemd's growfs logic will only grow the file system itself, not the partition it is contained in. Use systemd-repart for that (or some other tool).

Is this a boot with an initrd? It appears /dev/block/179:2 doesn't actually work for accessing the backing block device of your fs. That's a symlink typically created by udev. And usually that should exist if the initrd managed to transition into the host, and thus ran udev already far enough.

But if your boot is initrd-less then it might be that the symlink doesn't exist yet because growfs runs before udev gets so far...

**Comment by tewarid** [comment]
Thanks for clarifying the need for systemd-repart, I'll try it out.

udev is handled by systemd-udevd, `udevadm info /dev/block/179:2` after boot, logs

<details>
<summary>Log</summary>

```log
sh-5.1# udevadm info /dev/block/179\:2 
P: /devices/platform/soc/20202000.mmc/mmc_host/mmc0/mmc0:a7b6/block/mmcblk0/mmcblk0p2
N: mmcblk0p2
L: 0
S: disk/by-partuuid/b6538010-02
S: disk/by-uuid/d494bdf3-773c-447a-abfc-0f168abd7bea
S: disk/by-label/root
S: disk/by-id/mmc-SD08G_0xc02f13a8-part2
S: disk/by-path/platform-20202000.mmc-part2
E: DEVPATH=/devices/platform/soc/20202000.mmc/mmc_host/mmc0/mmc0:a7b6/block/mmcblk0/mmcblk0p2
E: DEVNAME=/dev/mmcblk0p2
E: DEVTYPE=partition
E: PARTN=2
E: MAJOR=179
E: MINOR=2
E: SUBSYSTEM=block
E: USEC_INITIALIZED=14415451
E: ID_SERIAL=0xc02f13a8
E: ID_NAME=SD08G
E: ID_PATH=platform-20202000.mmc
E: ID_PATH_TAG=platform-20202000_mmc
E: ID_PART_TABLE_UUID=b6538010
E: ID_PART_TABLE_TYPE=dos
E: ID_FS_LABEL=root
E: ID_FS_LABEL_ENC=root
E: ID_FS_UUID=d494bdf3-773c-447a-abfc-0f168abd7bea
E: ID_FS_UUID_ENC=d494bdf3-773c-447a-abfc-0f168abd7bea
E: ID_FS_VERSION=1.0
E: ID_FS_TYPE=ext4
E: ID_FS_USAGE=filesystem
E: ID_PART_ENTRY_SCHEME=dos
E: ID_PART_ENTRY_UUID=b6538010-02
E: ID_PART_ENTRY_TYPE=0x83
E: ID_PART_ENTRY_NUMBER=2
E: ID_PART_ENTRY_OFFSET=114688
E: ID_PART_ENTRY_SIZE=724172
E: ID_PART_ENTRY_DISK=179:0
E: DEVLINKS=/dev/disk/by-partuuid/b6538010-02 /dev/disk/by-uuid/d494bdf3-773c-447a-abfc-0f168abd7bea /dev/disk/by-label/root /dev/disk/by-id/mmc-SD08G_0xc02f13a8-part2 /dev/disk/by-path/platform-20202000.mmc-part2
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```
</details>

init is handled by systemd / telinit.

Still trying to figure out why /dev/block/179:2 is not available when systemd-growfs runs.

**Comment by poettering** [comment]
But again, is this a boot with an initrd (and in that question: which initrd generator?)? or is this without an initrd, i.e. the kernel directly mounting the rootfs itself?

**Comment by tewarid** [comment]
Right, the kernel is configured to mount the rootfs from /dev/mmcblk0p2.

**Comment by poettering** [comment]
So, are you saying that *no* initrd is involved?

**Comment by tewarid** [comment]
Right, initrd is not involved - bootloader loads kernel image that sets up root file system on disk.

**Comment by poettering** [comment]
OK, so best would probably be to find a to find the device node to open for a major/minor pair without relying on udev's /dev/block/* symlinks. If we did that we should be able to open the device node before udev is up.

Not sure how to do that best though...

Most likely we have to open /sys/dev/block/$major:$minor/uevent and then look for DEVNAME there... kinda sucks though

**Comment by marcan** [comment]
I'm also seeing this on Asahi Linux (Arch Linux ARM derivative). I don't think it always happens, since I'm pretty sure this used to work at some point, but at least it happens some of the time. This is obviously broken if that unit does not have a dependency on udev right now.

As a workaround, I'm considering calling systemd-growfs in our first-boot script only (where I already know the name of the root partition) and skipping the fstab flag.

**Comment by poettering** [comment]
> I'm also seeing this on Asahi Linux (Arch Linux ARM derivative). I don't think it always happens, since I'm pretty sure this used to work at some point, but at least it happens some of the time. This is obviously broken if that unit does not have a dependency on udev right now.

It doesn't need a dep on udev. It's sufficient that it has a dep on the .device unit, since that will only pop up once udev probed the device.

But the issue of the original reporter is that we don't support systemd-less initrds with the growfs stuff at all. If PID 1 is not systemd in the initrd, then nothing of this stuff works.

It might make sense to support systems without udev/PID1 in the initrd, as I outlined, but that'd be more a "new feature" and less of a "bugfix"-

**Comment by marcan** [comment]
Sounds like this feature doesn't work for us then (Arch does not use systemd as PID 1 in the initrd, though it *does* use udev but does not carry over the devtmpfs into the new root as far as I can tell).

**Comment by tewarid** [comment]
> But the issue of the original reporter is that we don't support systemd-less initrds with the growfs stuff at all. If PID 1 is not systemd in the initrd, then nothing of this stuff works.

To clarify, the system I'm working on is built using yocto project and its meta-raspberrypi recipe and runs on a raspberry pi. 

PID1 is systemd init

```log
sh-5.1# ps -l | head
S   UID   PID  PPID   VSZ   RSS TTY   STIME TIME     CMD
S     0     1     0 12480  7664 0:0   09:09 00:00:07 {systemd} /sbin/init
```

I've got two issues

- the system uses MBR partition scheme which systemd-repart doesn't support.

- systemd-growfs fails due to reason root caused by @poettering.

For now, I can do what I need using a one-shot service and tools like parted and resize2fs.

**Comment by DaanDeMeyer** [comment]
> Sounds like this feature doesn't work for us then (Arch does not use systemd as PID 1 in the initrd, though it does use udev but does not carry over the devtmpfs into the new root as far as I can tell).

Note that mkinitcpio supportS building initrdS that use systemd, but that requires a config change (see https://wiki.archlinux.org/title/mkinitcpio#HOOKS). The other option is to use dracut instead of mkinitcpio, but that's a bit more involved as you have to start updating pacman auto update hooks and the like.

**Comment by poettering** [comment]
So I am pretty sure avoiding systemd in the initrd is a really pointless excercise, once you have slightly complex storage a shell script isn't going to cut it, since you need to wait for stuff sanely and have userspace services backing complex storage around. 

But anyway, if anyone wants to prep a sane patch that determines the devnode to open given a major/minor without relying on the device node symlinks udev creates, I'd be willing to merge that. (add some helper src/basic/devnum-util.c similar to 
device_path_make_major_minor() that probably does something like readlink_malloc(/sys/dev/block/$MAJOR:$MINOR) and then path_extract_filename() of the result, and the prepend /dev. plus probably a verification via stat() to see if this resulted in the right device node.)

**Comment by tewarid** [comment]
Submitted #24418.
