### ISSUE TITLE
systemd-run --scope -p LimitAS=xxxxx does not work

### ISSUE THREAD

**Issue by ondrejv2** [systemd/systemd#21643]
I am unable to set the LimitAS property for scope transient units:
**systemd version the issue has been seen with**
 > systemd-249 (Fedora 34)
# systemd-run --scope -p LimitAS=100000000 /bin/bash
Unknown assignment: LimitAS=100000000

but works fine as a service:
# systemd-run -t --wait -p LimitAS=100000000 /bin/bash
Running as unit: run-u4813277.service

**Comment by mrc0mmand** [comment]
That's expected, `LimitXXX=` directives set the per-process rlimit (as described in `setrlimit(2)`), so they can't be applied to a scope. For scopes, you should use directives from `systemd.resource-control(5)` (which are preferred anyway, since they apply to the whole service, not a single process).

**Comment by ondrejv2** [comment]
True, but:
- Forking services are the same (i.e. multi process units), but yet LimitAS works there fine
- cgroup limits does not work the same way (i.e. crossing cgroup limit yield into kernel OOM whereas limits set by setrlimit() can be caught by the process)
I mean cgroup limits are not 100% replacement for setrlimit() hence it would be good if the above still works. If you decide it will not work by design, then it should not work for forking services as well.

**Comment by poettering** [comment]
@mrc0mmand is right, LimitAS= is a process setting, and since in --scope mode systemd isn#t forking off any processes it simply doesn't exist there. In --scope mode the process to place in the unit is forked off from your own invocation (which is the whole point of it), hence you can set it on your own process yourself, for example via the ulimit shell command.

Either way, this is expected, hence closing.
