### ISSUE TITLE
systemd-sysusers broken in initramfs

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#21665]
resolved has a dependency on sysusers and consumers of networkd and resolved, preferably want to keep it working in the initramfs.
This [PR](https://github.com/systemd/systemd/commit/294eace024b0e6c34cb64e3bb4f8958bb98ee00b) broke it.

**Comment by yuwata** [comment]
Hm, the PR itself looks good to me. I think, in general, updating files in initrd is not a good way. Why not to add systemd-network or systemd-resolve user when creating the initrd? Or, if you really want to generate them dynamically, a workaround for the issue is adding `ConditionPathExists=|/etc/initrd-release`.

**Comment by yuwata** [comment]
cc @keszybz.

**Comment by johannbg** [comment]
@yuwata systemd-sysusers creates system users and groups in addition to updating them so the `ConditionNeedsUpdate=/etc` in the type unit file for sysusers is arguably wrong ( You cant make the assumption that /etc exist or is not read only ). The current workaround that is implemented is `ConditionNeedsUpdate=`

**Comment by johannbg** [comment]
Worth mentioning is that resolved has an after dependency on sysusers which arguably is correct, which means that there should be after dependency in other type units for the services that have users for them ( coredump, networkd,journal etc ) which obviously means that PR would have broken all of them or will break them in the initramfs if the ( missing ) after dependency on sysusers get's added to them.

**Comment by keszybz** [comment]
The initrd is not supposed to be a generic environment, it should be considered immutable during boot. If a user or group is needed in the initramfs, it should just be pre-created. It doesn't really make sense to create users or do other "permanent" changes in the initramfs, because they would need to be repeated on each and every boot, since the initrd is immutable. Also, this would slow boot down a bit, and would also bring in additional code into the initrd, which we don't want, since everything needs to be unpacked into memory. That unpacking is actually a noticeable part of the runtime of the initrd.

So yeah, this change was done on purpose.

**Comment by yuwata** [comment]
> The current workaround that is implemented is `ConditionNeedsUpdate=`.

yeah, that's simpler :+1
