### ISSUE TITLE
System unbootable with btrfs compression level in fstab

### ISSUE THREAD

**Issue by bkdwt** [systemd/systemd#21668]
Like #18114, I get into in the same problem. This is the first time this happens with my system.

**systemd version the issue has been seen with**
 > 249

**Used distribution**
 > OpenSUSE Tumbleweed

**Linux kernel version used** (`uname -a`)
 > `Linux localhost.localdomain 5.15.6-1-default #1 SMP Wed Dec 1 08:32:12 UTC 2021 (c2ce213) x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 >  System boots and mount options are set correctly.

**Unexpected behaviour you saw**
 >  Much of my system breaks as soon as I write the problematic change to fstab, and doesn't boot after a reset.

**Steps to reproduce the problem**
 > Have a btrfs entry in fstab (mounted on / with the subvolumes), my mount options are compress-force=zstd,noatime,discard=async,space_cache=v1. If you uses zstd compression without a level, works as expected, but if you set the level you can't boot into the system anymore.

I have reported the same problem with EndeavourOS, here: https://www.reddit.com/r/EndeavourOS/comments/rb2x0h/system_breaks_after_the_first_reboot/

When I try to install OpenSUSE, I can't install if I set the compression level. Look the image bellow. 

![1638897749852](https://user-images.githubusercontent.com/51302074/145091810-d19c034c-251e-4d89-8cc9-62dc85e5cdf5.jpg)

**Comment by yuwata** [comment]
Please provide relevant journal logs. Otherwise, there is almost nothing we can do.

**Comment by poettering** [comment]
are you sure that zstd:xyz syntax even exists?

The screenshot you appended is from yast, i.e. has nothing to do with systemd. If the mount command yast invokes doesn't work this smells as if the option string you use simply doesn't work at all, and systemd has nothing to do with that.

Please contact the opensuse community for help about this, as this doesn't appear to be an issue caused by systemd, but be some issue with the used btrfs option string.
