### ISSUE TITLE
virt: detection for Hyper-V VMs

### ISSUE THREAD

**Issue by namiltd** [systemd/systemd#21816]
Pull request https://github.com/systemd/systemd/commit/76eec0649936d9ae2f9087769f463feaf0cf5cb4#diff-d5b6c9503f12e3cfcc77bbdc2e1184b772ccedbaa2826605a5a3dae0dbd9149f

I think a better solution would be to look in:
"/sys/class/dmi/id/product_name",
"/sys/class/dmi/id/sys_vendor",
"/sys/class/dmi/id/board_vendor" + "/sys/class/dmi/id/product_name" ,
"/sys/class/dmi/id/bios_vendor"
to find 'Microsoft Corporation Virtual Machine'

**Comment by yuwata** [comment]
Could you provide the value of each files?

**Comment by namiltd** [comment]
/sys/class/dmi/id/board_vendor -> 'Microsoft Corporation'
/sys/class/dmi/id/product_name -> 'Virtual Machine'

**Comment by bluca** [comment]
Why would that be better?

**Comment by namiltd** [comment]
After patch #76eec06 it is only tested "Hyper-V" in /sys/class/dmi/id/product_version. For example, testing on Debian 9 on Windows Server 2012 R2 "/sys/class/dmi/id/product_version" is "7.0" and not "Hyper-V" so detection doesn't work. Testing is ok for sum of contents /sys/class/dmi/id/board_vendor and /sys/class/dmi/id/product_name

**Comment by bluca** [comment]
> After patch #76eec06 it is only tested "Hyper-V" in /sys/class/dmi/id/product_version. For example, testing on Debian 9 on Windows Server 2012 R2 "/sys/class/dmi/id/product_version" is "7.0" and not "Hyper-V" so detection doesn't work. Testing is ok for sum of contents /sys/class/dmi/id/board_vendor and /sys/class/dmi/id/product_name

@fbq could you please double check and confirm the above?

**Comment by namiltd** [comment]
Debian 9
cat /sys/class/dmi/id/product_name: Virtual Machine
cat /sys/class/dmi/id/sys_vendor: Microsoft Corporation
cat /sys/class/dmi/id/board_vendor: Microsoft Corporation
cat /sys/class/dmi/id/bios_vendor: American Megatrends Inc.
cat  /sys/class/dmi/id/product_version: 7.0

'cat "/sys/class/dmi/id/board_vendor"' + " " +'cat "/sys/class/dmi/id/product_name"': 'Microsoft Corporation Virtual Machine

**Comment by fbq** [comment]
> > After patch #76eec06 it is only tested "Hyper-V" in /sys/class/dmi/id/product_version. For example, testing on Debian 9 on Windows Server 2012 R2 "/sys/class/dmi/id/product_version" is "7.0" and not "Hyper-V" so detection doesn't work. Testing is ok for sum of contents /sys/class/dmi/id/board_vendor and /sys/class/dmi/id/product_name
> 
> @fbq could you please double check and confirm the above?

I don't have a Windows Server 2012 R2 at hand, so I will need to find one for testing, but @namiltd please note that the detection using dmi is only necessary for ARM64, because on x86 we also have `detect_vm_cpuid()` to detect Hyper-V guests. I'm not sure whether Windows Server 2012 R2 supports ARM64 or not.

Anyway, thank @namiltd for spotting this, I will go check the Windows Server 2012 R2 part.

**Comment by namiltd** [comment]
The same values on Windows Server 2019.

**Comment by fbq** [comment]
> The same values on Windows Server 2019.

I don't think Windows Server supports ARM64 yet, so there is no real issue about the current detection. As I said previously, on x86, `detect_vm_cpuid()` is used for virtualization detection. You can verify that by running the latest `systemd-detect-virt` in your guests on Windows Server 2019 since you currently have one. And it should report "microsoft". Are you suggesting that we should unify the detection for x86 and ARM64?

**Comment by namiltd** [comment]
I suggest that detecting virtualization in the first step is more optimal.

**Comment by namiltd** [comment]
I'm closing due to lack of response.
