### ISSUE TITLE
Does systemd also mount sysfs, procfs?

### ISSUE THREAD

**Issue by mountainlion0523** [systemd/systemd#2182]
During early mount in mount_setup_early(), systemd tries to mount sysfs and procfs.
But as I printed systemd log, systemd failed to mount sush pseudo-file system bacause name_to_handle_at() function returns errno EOPNOTSUPP.

Does systemd really mount sysfs and procfs? does it success on mount_setup_early()?

**Comment by grawity** [comment]
Well, you pretty much answered that yourself. It _[tries to](https://github.com/systemd/systemd/blob/master/src/core/mount-setup.c#L74)_ mount them – but it has troubles because your kernel is compiled without CONFIG_FHANDLE=y.

(That option isn't strictly required for mounting itself, but _apparently_ it's required for certain checks that systemd does before every mount.)

**Comment by mountainlion0523** [comment]
If so, then who mounts sysfs and procfs?. It seems systemd doesn't do that.
I only guess udevd.... is it right?

**Comment by mountainlion0523** [comment]
Let assume name_to_handle_at with path char *p returns -1(with errno: EOPNOTSUPP), but it's parent path returns success, how should I understand this? path p is already mounted? or not mounted and wait to be mounted?

**Comment by poettering** [comment]
@mountainlion0523 this is not a support forum, but a bug tracker. Please ask questions like yours on the systemd ML or so, but not here.

(If name_to_handle_at() returns EOPNOTSUPP for a dir, but works for a parent, then this indicates that the file systems for the dir and its parents are differently featured, and one supports the call and the other does not. Which means it's a mount point already.)
