### ISSUE TITLE
systemd error log

### ISSUE THREAD

**Issue by robson-66** [systemd/systemd#21921]
`Dec 27 14:08:02 pc dbus-daemon[513]: writing oom_score_adj error: Permission denied`

**Comment by mrc0mmand** [comment]
This is completely unactionable. Please use the Bug Report template and fill in all necessary information (along with a larger snippet of the journal).

**Comment by luebking** [comment]
https://github.com/systemd/systemd/commit/ce7de0ba8ef355c5119e7dffc46e075b257dc90d#diff-c981a30c0e7b420b0ba50ce7d1d4174a511fdf20567b852ab02c774cb9a3591e tries to set the score adjustment to 100 but it would seem that OOMScoreAdjust actually stacks values instead of controlling them so you end up w/ 200 on the session bus and that seems inherited by dbus activated services in some privileged manner and subsequent efforts to change the value to anything lower fail w/ the reported error.

Reverting the commit therefore prevents the error.

The warning for OOMScoreAdjust seems ok in general (to inform the author of the unit of the failure) but the general behavior is off and it would seem that this also only exposes an underlying bug about the behavior of OOMScoreAdjust

I'll update this week and take a closer look locally just for curiosity if you don't figure it yourself.

---

Also a sincerely kind advice about the attitude to deal with such issues:
User bug reports are often not of stellar quality. As a matter of fact, most are initially useless and it is very frustrating to get anywhere from there. I do understand that.

But:
Whenever you merely stumble over the situation where after your changes a process can unexpectedly not be controlled by the owning UID, THAT'S A MASSIVE RED FLAG, because the alternative cause - the one that does not rely so much on slapstick as in this case - is that the process is running w/ elevated capabilities it's not expected to have.

So regardless of what you may think of your users, you better swallow it and immediately look at the situation and actively extract as much information from the user until you can explain it.
This is *your* bug and the symptoms indicate a potentially critical situation.
It is therefore not a good time for "notabugifidontlookthere" at all, but to act professionally w/ the exclusive focus on the integrity of your product.

**Comment by mrc0mmand** [comment]
> Also a sincerely kind advice about the attitude to deal with such issues:
> User bug reports are often not of stellar quality. As a matter of fact, most are initially useless and it is very frustrating to get anywhere from there. I do understand that.

I agree, and that's why we have an issue template with all the info we might need for it to be a useful report. So if there's indeed an issue, please open a new bug report with the requested info, so we have something actionable on our hands.

**Comment by Finoderi** [comment]
>that's why we have an issue template with all the info we might need for it to be a useful report
Fill it up yourself then. And fix the obvious bug.
Nobody asked for this systemd-oom-fuck-upper in the first place. And now it creates security holes out of thin air and you can't pull your head out of your ass.

**Comment by luebking** [comment]
For clarification: there's no (known) security issue attached to this! You can "getpcap" verify it yourself.
(If there was an actual issue I wouldn't have put it on the backburner but posted a patch asap)

It's just clumsy and probably exposes unexpected code behavior.
But the symptoms very much *suggest* that there *might* be a massive security issue - which is why one would immediately look there to identify the cause, regardless of whether the user provides an exhaustive problem description.
Because the problem is not your user complaining, but your code possibly compromising the whole linux landscape - one doesn't rely on users explaining why that's not an acceptable condition.

**Comment by bluca** [comment]
A general reminder aimed at nobody in particular that adhering to https://github.com/systemd/systemd/blob/main/docs/CODE_OF_CONDUCT.md is required for participants in issues and PRs on this org, and unhelpful messages will be removed without notice
