### ISSUE TITLE
systemd.confirm_spawn broken due to eye of cylon output

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#2194]
When you boot with systemd.confirm_spawn=true, the eye of cylon animation kicks in pretty quickly so you don't have any chance to answer the questions which services to start.
This basically breaks the confirm_spawn functionality completely.

To reproduce the problem, add systemd.confirm_spawn=true to the kernel command line, then wait for 30 secs. After that it's impossible to interact with systemd.

@keszybz that's maybe for you

**Comment by fbuihuu** [comment]
Resurrecting this as some users of Suse distros are also complaining that this goodie pretty hard to use.

Maybe I'm missing something but why not simply disabling the cylon animation when systemd.confirm_spawn=true is passed ?

While looking at it, I was wondering if it wouldn't make it easier to use if we could specify a different console to use for the confirmation messages so those messages are separated from the other messages (kernel ones, status one, etc...).

I'm going to make a PR in order to have some material to discuss...
