### ISSUE TITLE
can't run an ssh command on power events from a unit file

### ISSUE THREAD

**Issue by danielkrajnik** [systemd/systemd#21953]
You can't use a user's ssh-agent from a system unit file.
You can't use sleep.target from a user unit file.
systemd ignores /etc/pm/sleep.d scripts.

This means that if you want to run a command remotely via ssh on a power event 
you just can't.

https://unix.stackexchange.com/questions/149959/how-to-run-systemd-user-service-to-trigger-on-sleep-aka-suspend-hibernate

**Comment by danielkrajnik** [comment]
Maybe a workaround is to find SSH_AUTH_SOCK in /tmp 
https://github.com/wwalker/ssh-find-agent/blob/master/ssh-find-agent.sh#L37
and setting it up manually via a file
https://unix.stackexchange.com/questions/511797/creating-os-environment-variables-using-execstartpre-on-systemd

**Comment by danielkrajnik** [comment]
EDIT: it worked

suspend-system.service:
[Unit]
Before=sleep.target

[Service]
EnvironmentFile=/home/username/.config/systemd/user/ssh-agent-socket-location
ExecStartPre=/bin/bash -c 'echo SSH_AUTH_SOCK=$(find /tmp -maxdepth 2 -type s -name agent.\* 2> /dev/null | grep '/ssh-.*/agent.*' | head -n 1) > /home/username/.config/systemd/user/ssh-agent-socket-location'
ExecStart=ssh machinename sudo systemctl suspend 
User=username
Group=username

[Install]
WantedBy=sleep.target

why systemd blocks SSH_AUTH_SOCK? Is this solution insecure?

**Comment by danielkrajnik** [comment]
EDIT2 without EnvironmentFile:
[Unit]
Before=sleep.target

[Service]
ExecStart=/bin/bash -c 'SSH_AUTH_SOCK=$(find /tmp -maxdepth 2 -type s -name agent.\\* 2> /dev/null | grep '/ssh-.*/agent.*' | head -n 1) ssh machinename sudo systemctl suspend'
User=username
Group=username

[Install]
WantedBy=sleep.target

**Comment by poettering** [comment]
I am not sure I follow, but you want to use a running user SSH agent from a system service that also runs something udner that UID? You probably want to use PAMName, so that your code actually runs under the user's session instead of a real system service...

But this isn't really a feature request or bug report, but a support question. Those do not belong here. Please use the mailing list or so instead. The submission form should have made that clear to keep frustration at a minimum.
