### ISSUE TITLE
systemd-250 fails to boot with root-on-NFS

### ISSUE THREAD

**Issue by Malvineous** [systemd/systemd#21967]
**systemd version the issue has been seen with**
 > systemd 250 (250-4-arch)

**Used distribution**
 > Arch Linux ARM

**Linux kernel version used** (`uname -a`)
> `Linux 5.10.89-1-rpi-legacy-ARCH #1 SMP Sun Jan 2 13:38:35 AEST 2022 armv7l GNU/Linux`

**CPU architecture issue was seen on**
 > ARMv7h 32-bit, Raspberry Pi

**Expected behaviour you didn't see**
 > I expected the system to boot normally as it did with systemd-249.5 and earlier.

**Unexpected behaviour you saw**
 > System froze during boot, with kernel messages saying the NFS server providing the root filesystem is not responding.  The system stops responding to pings at this point as well, suggesting the network interface used for the root filesystem was brought down but not brought back up again.

**Steps to reproduce the problem**
 > Boot a machine with its root filesystem on NFS.  Observe it works perfectly with systemd 249.5 and earlier, but it does not finish booting with systemd 250.  Observe that the machine responds to pings during the boot process until the freeze, at which point it stops responding to pings.

**Additional program output to the terminal or log subsystem illustrating the issue**

Reverting to systemd 249.5 resolves the problem.

I am still working on getting useful output from the debug logs.  Sometimes the kernel complains that the `systemd-udevd` process blocked for more than 120 seconds.  If I enable debugging output via a serial console, the last lines of output I get are:
```text
[  136.362428] systemd-udevd[221]: kprobe: Device processed (SEQNUM=1139, ACTION=add)
[  136.362855] systemd-udevd[223]: armv7_cortex_a7: sd-device-monitor: Passed 158 byte to netlink monitor
[  136.363271] systemd-udevd[221]: kprobe: sd-device-monitor: Passed 149 byte to netlink monitor
[  136.363685] systemd-udevd[219]: cam1_regulator: Device ready for processing (SEQNUM=1145, ACTION=add)
[  136.364166] systemd-udevd[222]: arm-pmu: /usr/lib/udev/rules.d/50-udev-default.rules:14 Importing properties from results of builtin command 'hwdb --subsyst'
[     *] (2 of 3) A start job is running for...e Configured (1min 58s / no limit)
```
I am booting with the command line parameters `systemd.log_level=debug systemd.log_target=console systemd.journald.forward_to_console=1 console=ttyAMA0,115200`.

If there is a way to narrow down the output to only udev or only systemd-networkd let me know, as I am suspecting this is where the issue is.  It seems like systemd is trying to reconfigure the network interface being used for the root filesystem, and while the interface is down, it is trying to access the root filesystem.  Since NFS blocks the process until the server can be contacted again, it would appear this results in a deadlock (NFS is waiting for the network, and systemd is waiting for NFS before restoring the network).

**Comment by Malvineous** [comment]
Found this in the logs:
```
systemd-networkd[277]: eth0: Removing foreign address (configured,marked): 192.168.0.5/24 (valid forever, preferred forever), flags: permanent, scope: global
```
Not long after is when everything stops.  It looks like networkd removes the addresses added by the kernel, then attempts to access the now unavailable root filesystem, before starting the DHCP process to add the addresses back again, causing the deadlock.

I seem to recall there was something in place to prevent systemd from messing around too much with an interface that had already been autoconfigured by the kernel?  Has that stopped working in systemd-250?

**Comment by yuwata** [comment]
Could you provide the relevant .network files?

**Comment by yuwata** [comment]
> It looks like networkd removes the addresses added by the kernel,

Which DHCP client do you use to assign the address?

**Comment by Malvineous** [comment]
Thanks for your fast response!  The IP address is assigned via the kernel command line parameter `ip=dhcp`.
```
$ cat /etc/systemd/network/eth0.network 
[Match]
Name=eth0

[Network]
DHCP=yes
DNSSEC=no
IPv6AcceptRA=true
```
This is the only `.network` file in the folder.

I don't have any other DHCP client installed, it's just whatever systemd uses by default as far as I'm aware.

**Comment by yuwata** [comment]
Hm, could you try to add `KeepConfiguration=dhcp` or `KeepConfiguration=yes` in the [Network] section?

**Comment by poettering** [comment]
@Malvineous you are using the in-kernel IP auto-configure logic, or an initrd with some network management service to boot from NFS?

**Comment by coagentpai** [comment]
I have a very similar setup (RPi, root on NFS, systemd-250 on Arch) and I am seeing the same failed boot. I have tried both KeepConfiguration=dhcp and KeepConfiguration=yes separately and still have the issue. 

As far whether the configuration happens in the kernel or in initrd I am not quite sure. I have ip=dhcp on the kernel command line.  

Let me know what other information would be helpful.

**Comment by yuwata** [comment]
@coagentpai Could you generate debugging log of networkd by creating the following drop-in config?
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
Then please provide the log of networkd (`journalctl --no-hostname -b -u systemd-networkd.service`).

You may need to change /etc/systemd/journald.conf to not save journals through NFS (`Storage=volatile`).

Also, please provide the relevant .network file.

**Comment by coagentpai** [comment]
@yuwata 
I think I may have a lead on what I am doing wrong here. When `systemd-network-generator.service` is enabled boot fails. When it's not enabled boot works fine. For some reason I had overlooked it earlier. I don't quite understand all the details but I suspect because `ip=dhcp` is in the kernel command line it must be creating a configuration that is later releasing the IP interrupting root NFS access.  When boot fails after some time the hung task is systemd-udevd.  I have tried to get the logs with the generator enabled but I can't seem to find a way to get far enough in the boot so I can run anything (over serial or network: no getty). 

I thought that if I added a file `/etc/systemd/network/default.conf` with
 ```
[Network]
KeepConfiguration=yes
```
that might fix the issue but it did not. I might be completely wrong here. I attached the logs as requested (generator is not enabled). Is disabling the `systemd-network-generator.service` the right move here?

See the attached files for logs and other data:
journal logs:
[journal-data-clean.txt](https://github.com/systemd/systemd/files/7991204/journal-data-clean.txt)
eth0.network:
[eth0.network.txt](https://github.com/systemd/systemd/files/7991200/eth0.network.txt)
networkd-config-service:
[networkd-config.txt](https://github.com/systemd/systemd/files/7991210/networkd-config.txt)
Kernel command line:
```
root=/dev/nfs ip=dhcp nfsroot=10.8.0.10:/srv/nfs/romeo-t1 rw rootwait console=serial0,115200 console=tty1 selinux=0 plymouth.enable=0 smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 kgdboc=serial0,115200 cgroup_enable=memory cgroup_memory=1
```

Thanks in advance for any insight you might have.

**Comment by yuwata** [comment]
Thanks. But, the journal seems to be truncated. It does not contains early stage of starting the service.

**Comment by coagentpai** [comment]
Sorry I had removed the earlier lines:
[journal-data-clean.txt](https://github.com/systemd/systemd/files/7991441/journal-data-clean.txt)

**Comment by yuwata** [comment]
Thank you!

I hope #22383 should fix your issue even if systemd-network-generator.service is enabled.

In your log, I found the following:
```
eth0: found matching network '/etc/systemd/network/eth0.network'
```
It seems you do not use number-prefixed .network files. It easily causes issues. As, networkd searches a matching .network file in alpha-numerical order. And network-generator.service generates .network files prefixed "90-" or "91-". So, you also need to prefix the file e.g. 50-eth0.network. Otherwise, the generated .network file will be used.
