### ISSUE TITLE
bootctl install: option not to install duplicate loader in \EFI\BOOT

### ISSUE THREAD

**Issue by rhendric** [systemd/systemd#22056]
**Is your feature request related to a problem? Please describe.**

Some UEFI implementations might only look in `\EFI\BOOT` for boot loaders, but for the ones that pay even a little attention to the relevant EFI variables (which, in 2022, dare I hope is a lot of them?), installing an identical copy of systemd-boot in that location is pure clutter. It's less than 100K of clutter, but it's the principle of the thing; plus, it's one more file for me to think about verifying/securing when my system boots.

**Describe the solution you'd like**

I'd like there to be a command-line flag or an environment variable that stops `bootctl install` from putting an extra copy of systemd-boot in `\EFI\BOOT`.

**Describe alternatives you've considered**

Ensuring that `\EFI\BOOT\` doesn't exist and using the `--graceful` flag is my current workaround, but `--graceful` is too permissive; I'd like to be aware if something else goes awry with the `install` operation.

**The systemd version you checked that didn't have the feature you are asking for**

249, but I can see from the code that there's nothing that would do this in the master branch either.

**Comment by medhefgo** [comment]
Nope. Not going to happen. `\EFI\BOOT` is there for a reason. Firmware tends to forget about EFI variables when they get updated or simply because their configuration was reset. That includes boot variables, which would render the system unbootable without the fallback loader being present. On the other hand, boot loaders are supposed to install themselves into their own folders so they don't step on each other's toes like in the bad old MBR days, so we cannot just install to one location.

If you want to be that picky about boot loader bloat you're on your own. Just don't use bootctl and copy the files by hand.

**Comment by sharpjs** [comment]
I'm late to the party, but one workaround is to ensure that some other boot loader owns the file in `\EFI\BOOT`.  Then you get output like this:

```
$ sudo bootctl update 
Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Skipping "/boot/EFI/BOOT/BOOTX64.EFI", it's owned by another boot loader (no version info found).
```

I'm too lazy at the moment to go read how `bootctl` decides who owns that file, but it might work just to place some dummy file there.
