### ISSUE TITLE
New "include" keyword in sd-boot entries files

### ISSUE THREAD

**Issue by iamGavinJ** [systemd/systemd#22213]
**Is your feature request related to a problem? Please describe.**
I have a number of sd-boot entry files which share many common `options`.  These options are duplicated across all entry files.

**Describe the solution you'd like**
Ideally, [src/boot/efi/boot.c](https://github.com/systemd/systemd/blob/df4ec48f45f518b6926e02ef4d77c8ed1a8b4e2c/src/boot/efi/boot.c#L1373) would provide an `include` keyword which sources another file.

**Describe alternatives you've considered**
I have written a basic script which parses all entries, looks for a specific comment line, truncates everything below it and appends my common options.

**The systemd version you checked that didn't have the feature you are asking for**
250++

**Comment by poettering** [comment]
No. Let's not do that. sd-boot entries are supposed to be simple, parsable with simple tools, reimplementable trivially. include concepts turn them into a templating language of sorts, and that is explicitly what these snippets should not be. Doing so would create all kinds of problems, i.e. we'd have to add an include cycle detector and similar. Complexity raises dramatically in non-obvious ways once you add that.

We removed the include logic from systemd unit files for a reason, and we shouldn't add this here either.

If you want a templating logic, then go ahead, but please plug it in front of the snippets, so that the snippets are generated by some script or so. But natively in the snippets, so that each and every implementor of the snippet spec has to implement them? No, definitely not.

Sorry, if that's disappointing.

**Comment by iamGavinJ** [comment]
@poettering that's fair.  I wasn't aware that `include` statements previously existed in `[Unit]` files, so the consistency and justification is understandable.  Thanks for explaining.
