### ISSUE TITLE
Mount/Automount unit should detect and report CIFS mount status when network connection is lost

### ISSUE THREAD

**Issue by sven** [systemd/systemd#22241]
**Is your feature request related to a problem? Please describe.**
I'm using systemd 250 on Manjaro and created a mount + automount unit file for a CIFS share. The intention is that I can use systemd via the D-Bus API as a reliable way to check whether the mountpoint is available or not. A simple test reveals that the mount unit still reports `active (mounted)` as ActiveState/SubState when the following happens:
* pull the network cable
* access the share via `ls`
* dmesg reports `[...] CIFS: VFS: \\server has not responded in 30 seconds. Reconnecting...`
* `ls` times out with `ls: cannot access '/home/me/share': Host is down`

**Describe the solution you'd like**
If the system detects the timeout it would be nice the mount status would change to `inactive (timeout)` or something that signals that the share is currently not available. Additionally, if possible, the information `Host is down` should be given as a reason.

**Describe alternatives you've considered**
An alternative would be polling the directory myself, but I'm a big fan of the systemd API as this makes it easy to port the code to other Linux distributions as well.

**The systemd version you checked that didn't have the feature you are asking for**
Currently I'm using version 250 from Manjaro.

Thank you!

**Comment by poettering** [comment]
I am sorry, but this is something the SMB/CIFS and kernel people of to figure out and systemd would then just follow. i.e. I think adding a "state" to mounts makes a lot of sense, but not glued onto the top layers, guessing the current state of the lowest layers of the stack. If this is a good thing (and I think it might be) then this has to come from the lowest layers and be propagated up in some way, so that we can pick it up generically. But that work needs to come from the SMB/CIFS people and kernel VFS people, not us.

Hence, please ask the SMBC/CIFS people for this, but glueing a local hack/workaround for this into systemd only is not the way to go.
