### ISSUE TITLE
systemd-network can't handle symlinkd network units

### ISSUE THREAD

**Issue by colemickens** [systemd/systemd#2227]
I have a very basic network unit:

```
[Match]
Name=enp3s0
Host=chimera

[Network]
Address=10.0.0.2/24
Gateway=10.0.0.1
```

This works perfectly when dropped in `/etc/systemd/network/` and `systemd-networkd.service` is running.

Unfortunately, when I move the file back to my stow directory, and then execute stow to have it create the symlink, systemd-network stops starting up at all. Instead, when it starts, I simply get:

```
Could not load configuration files: Permission denied.
```

I even created the drop in and bumped set SYSTEMD_LOG_LEVEL to debug. That gave me a few extra dbus messages, but nothing relevant.
1. Should systemd-networkd completely fail on one bad unit? What if there are many others?
2. Why does systemd-network error on a symlinked network unit file.

I tried to skim the code while working backward from the error string, but the fopens I saw were in "re" mode which should be fine (tested with a short C program).

**Comment by colemickens** [comment]
Another user possibly seems to indicate that this was working in the past and is a regression: https://bbs.archlinux.org/viewtopic.php?id=184065

**Comment by arvidjaar** [comment]
systemd-networkd runs as user systemd-network. Please check if this user has access to symlinked directory/file.

**Comment by colemickens** [comment]
I checked, the file was accessible by that user. I checked with this as well: http://unix.stackexchange.com/a/82349

The network unit is readable to everyone.

**Comment by poettering** [comment]
@colemickens there's not concept as a "network unit". "Units" are a concept of PID1 itself, and refer to "service", "socket", "target", "mount", .. units, but the stuff managed by systemd-networkd is completely independent of that, and we don't call the stuff it manages "units".

If you get EACESS the way you do then that's an indication that your file or any symlink in the chain of symlinks to that file is not accessible, either because the UNIX access rights say so or because some form of MAC such as AppArmor or SELinux prohibit access. Either way, access management is not a systemd-networkd problem but usually a distro or admin problem. Make sure the "systemd-network" user has access to the file and all symlinks in its chain. Consider turning off AppArmor/SELinux to see if that's at fault.

If you are interested which access precisely is causing the issue, consider strace'ing the networkd process (by prefixing the `ExecStart=` command line with `strace -f -o /tmp/strace.log -s500 -D` or suchlike). 

Anyway, closing as this is almost certainly not a systemd problem.

**Comment by colemickens** [comment]
Thank you for the detailed reply @poettering. I've made further attempts to understand what is wrong with my symlink.

All that I can say definitively is that when `chimera-wired.network` exists at `/chimera-wired.network` and `/home/chimera-wired.network`,  and `/etc/systemd/network/chimera-wired.network` is a symlink to them, then everything works fine.

As soon as I move the file to /home/cole/chimera-wired.network and recreate the symlink, `systemd-networkd` starts throwing the access error.

I'm at a loss. My home directory is world readable and world executable. Is there another concept at play that I'm ignorant of when it comes to determining systemd-network's access to files?

```
$ ls -al /home/cole
drwxr-xr-x 20 cole cole 4096 Dec 29 14:53 .
[trimmed]

$ ls -al /home/cole/chimera-wired.network
-rwxr-xr-x 20 cole cole 81 Dec 29 14:36 .
```

Further confusion:

```
$ sudo -u systemd-network cat /etc/systemd/network/chimera-wired.network

    [prints out the network configuration file]

$ sudo -u systemd-network ls -al /etc/systemd/network/chimera-wired.network

lrwxrwxrwx 1 root root 99 Dec 29 13:43 /etc/systemd/network/chimera-wired.network -> /home/cole/chimera-wired.network

$ sudo -u systemd-network cat /home/cole/chimera-wired.network

    [prints network config file]
```

All parent directories of the file in question are world readable and executable.

I tried the `strace` suggestion, changing Exec line:

`Exec=/usr/bin/strace -v -o/tmp/strace.log -e trace=file -s500 -D /usr/lib/systemd/systemd-networkd`

which got me this, but it doesn't include the filename of the config file that failed:

https://gist.github.com/anonymous/51bfabc80b5309167274

I'm currently trying to find out if I can coax `strace` into giving me the filename.

Last week, I actually wrote a C program that open() with 're' mode just like systemd-network does. Ran it `sudo -u systemd-network ./a.out` and it was able to open the symlinked file.

**Comment by colemickens** [comment]
Here's the ltrace: https://gist.github.com/anonymous/834226dd3ace6bdc947b

[Line 1814](https://gist.github.com/anonymous/834226dd3ace6bdc947b#file-strace-log-L1814): `7463 fopen("/etc/systemd/network/chimera-wired.network", "re") = 0`

**Comment by colemickens** [comment]
webczat was very helpful in #systemd and informed me that `systemd-networkd.service` has `ProtectHome=true` which is the cause for this behavior.

**Comment by wyongjian** [comment]
> webczat was very helpful in #systemd and informed me that `systemd-networkd.service` has `ProtectHome=true` which is the cause for this behavior.

Thanks your share help me solved my problem。
