### ISSUE TITLE
systemd does not invoke pam_end properly

### ISSUE THREAD

**Issue by spaetz** [systemd/systemd#22318]
This is a spinoff of https://github.com/systemd/systemd/issues/17564#issuecomment-1025252833 which is about enabling WakeSystem= for user units.

libcap and (previous) PAM author AndrewGMorgan comments that systemd likely does not use the pam API correctly with regard to pam_end(). I cannot claim to understand half of it, but the linked comment contains more pointers to likely code culprits. It would be great if somebody familiar with the systemd code base could look if that is a problem, in order to unblock the WakeSystem progress.

Specifically, the lack of the PAM_DATA_SILENT flag in pam_end (https://github.com/systemd/systemd/blob/673a18170259b3d31189c76f75c7f1278e4f04c8/src/core/execute.c#L1346) seems to be wrong.

Thanks for systemd!

**Comment by spaetz** [comment]
Digging deeper, I am a bit puzzled, systemd does invoke pam_end, it just does not add the FLAG PAM_DATA_SILENT, which looking at the documentation does not seem too critical, but then I don't really know PAM...

**Comment by AndrewGMorgan** [comment]
The `PAM_DATA_SILENT` flag is the way that `pam_end()` communicates to the module stack that this invocation of `pam_end()` is not the final one, but in the process that is going to directly exec the child. Without this flag, all of the modules assume that PAM is fully shutting down and they should fully delete and cleanup all credentials etc.

**Comment by poettering** [comment]
@AndrewGMorgan so in a better world the flag would be named PAM_CALLING_IN_CHILD or so? or maybe PAM_NOT_CALLING_IN_PARENT?

**Comment by AndrewGMorgan** [comment]
Possibly, but it has been named this way since around (I suspect before) the year 2000.

I seem to recall there were some use cases wanting to have a hook in the PAM stack that executed a callback **after** the application called `setuid()` but before it invoked `exec*()`. There was a desire to drop/wipe references to some kernel objects at this stage etc. but not all of them---the session closing still needed them around in some form.

However, it was normally the case that the terminating (full end) `pam_close_session()` ... `pam_end()` for the application was invoked in a process that had never called `setuid()`. The decision at that time was to use this flag to support a mini-end protocol.

**Comment by AdrianVovk** [comment]
I suspect this is still broken.

As far as I can tell, the way this is supposed to work in PAM is:
- You start the session
- You fork
- One process `setuid()`s, and then `exec()`s the session leader
- The other process sits and waits for the first to go away, at which point the session is over and `pam_end()` is invoked to clean up all resources
- The process that ultimately `exec()`s the session leader should first call `pam_end()` with `PAM_DATA_SILENT` to notify PAM modules that it's about to `exec()`. This gives the modules the opportunity to clean up in-memory state but won't touch external state that's to be cleaned up by the second process.

Before #22341 systemd implemented this logic except for the `pam_end(PAM_DATA_SILENT)` call in the process that's about to `exec()`. Instead of adding that call, the pull request instead _replaced_ the non-`exec()`ing process's `pam_end()` call with a call to `pam_end(PAM_DATA_SILENT)`. This means two things:

1. This bug isn't fixed. The process that is about to `exec()` still doesn't call `pam_end(PAM_DATA_SILENT)`
2. We've introduced a new bug. `pam_end()` is now never called (without `PAM_DATA_SILENT`) when the session ends, which means PAM modules are not given the opportunity to clean up external state

I suspect this happened due to confusion from the way systemd inverts the usual PAM relationship: GDM, login, and so on `setuid()` and `exec()` in the child process while the parent sits and waits. systemd does the opposite: it waits in the child while the parent goes on to `setuid()` and `exec()`. You can see this in Lennart's suggestion to call the flag `CALLING_IN_CHILD`. PAM cares less about the parent/child relationship and more about which process ultimately `exec()`s.

What's not documented in the PAM man page is that the `pam_end(PAM_DATA_SILENT)` call must happen after `setuid()`. This is a convention followed by other users of PAM (i.e. util-linux), and I know that `pam_cap.so` relies on this for its `defer` option to work, but that's about it. It would be easy if systemd didn't wait for the setuid. Perhaps if it's important to the correct functionality of `PAM_DATA_SILENT`, there should be a note in the man page.

**Comment by AndrewGMorgan** [comment]
Your analysis is correct. The `PAM_DATA_SILENT` is supposed to be called in the half of the `fork()` that has already changed UID. The half that doesn't change UID and persists until the session ends is where the full `pam_end()` is called.
