### ISSUE TITLE
KERNEL_INSTALL_MACHINE_ID in /etc/machine-info should be revisited

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#22376]
I am not too happy with  #21757 and how it played out.

Three points:

1. I would like to understand why /etc/machine-info is ever written to by the script. Consuming might be acceptable, but writing it?
2. I don't think /etc/machine-info is the right place for this, it's not really machine info, it's kernel-install specific configuration. Hence, can we please move this to /etc/kernel/image-prefix-dir or so? (see my comments on the original PR)
3. I don't think the concept should be called "machine-id", because apparently it's *not* the machine ID, and the string can actually be anyhing, i.e. an arbitrary prefix dir.

**Comment by poettering** [comment]
(I'd be fine with still honouring KERNEL_INSTALL_MACHINE_ID if it is set, but I am pretty sure we should move this elsewhere, and I think probably never auto-write this, but maybe I don't understand what this is about...)

**Comment by DaanDeMeyer** [comment]
Writing a separate file in /etc/kernel was my initial idea but @keszybz suggested we use /etc/machine-info. I don't mind switching back to a separate file in /etc/kernel but @keszybz might want to pitch in here as well.

**Comment by poettering** [comment]
@DaanDeMeyer what was the rationale for writing that file automatically though?

(writing to env var files sucks btw, since you basically need an editor. if you we use a file like /etc/kernel/image-prefix-dir or so that just containst the prefix dir string that is much either since if you want to change it you jst rewrite the file as a whole)

Also, /etc/kernel/install.conf exists now too. So one more file even.

This is just a mess, so much configuration options and I doubt we actually want any of this configurable tbh...

**Comment by DaanDeMeyer** [comment]
@poettering The reason for writing a file (either machine-info or a new one in /etc/kernel) automatically is because we need some kind of identifier to identify the directory to use in the boot directory that isn't the machine ID because it's not guaranteed to be available. Like you already said, it doesn't matter what it actually is, so we decided to just generate a UUID and use that. Of course we need to persist the generated UUID somewhere. My initial PR stored it in /etc/kernel/boot-id, but after review I changed it to be stored in /etc/machine-info as requested.

**Comment by DaanDeMeyer** [comment]
See also #22224 which brings up valid points, especially around factory resets of /etc.

Although if we can't touch the host filesystem I'm all out of ideas for how to make this work properly. AFAIK, there's nothing to uniquely identify an image before the machine ID gets generated. And generating our own identifier and persisting it brings its own set of issues. 

I tried looking at the type 2 stuff generated by mkosi and those are named linux-<kernel-version> so those aren't unique either.

Should we write a file to /var instead of /etc? Although I assume /var can be stripped whenever as well in case of factory reset so I don't think that'd work either.

**Comment by poettering** [comment]
> @poettering The reason for writing a file (either machine-info or a new one in /etc/kernel) automatically is because we need some kind of identifier to identify the directory to use in the boot directory that isn't the machine ID because it's not guaranteed to be available. Like you already said, it doesn't matter what it actually is, so we decided to just generate a UUID and use that. Of course we need to persist the generated UUID somewhere. My initial PR stored it in /etc/kernel/boot-id, but after review I changed it to be stored in /etc/machine-info as requested.

My thinking was always that there are two kinds of setups:

1. The "personalized" (aka "pet") approach. Here you use a traditional likely interactive installer tool, booted from an USB medium. That installer unpacks some binary packages on a freshly formatted file system on some HDD, then "personalizes" it with stuff the user on the console chose, installs a boot loader, asks the user to remove the USB medium and reboots.

2. The "automated" (aka "cattle") approach. Here somehow the preprepared image ends up on the HDD, no personalization takes place by any installer, but everything happens automatically or possibly on first boot.

These two usecases have some different requirements I think. Specifically, I think for the first case it's essential we not only allow parallel installation of multiple different OSes (i.e. allow "multi-boot"), but also of multiple instances of the very same OS/version. This works fine here, sine the machine ID identifies the installation, and hence the various versions won't interfere with each other. In the second case this doesn't matter I think. Yes, it makes sense to allow parallel installation of different OSes, but different installations of te very same OS/version? I doubt that is that important.

In the first usecase the idea was that an installer shows some user dialogs and then basically can do something like: systemd-repart, then systemd-machine-id-setup --root=, systemd-firstboot --root=, bootctl install --root=, `systemctl reboot`. Here the installer adds a machine ID to the installation, and bootctl can pick it up and all is good.

In the second usecase the idea was that the image is installed via dd or something, and that's it, and then during first install everything not set up yet gets set up, including the machine ID. In this case of course the machine ID cannot be used to name the kernel dirs in the ESP, but that's fine, since as mentioned parallel installation of multiple instances of the same OS is not that relevant I think. So what dir name should be used in the ESP? My recommendation: use the $IMAGE_ID field as defined in os-release. i.e. for my hypotetical os QuuxOS this would "quuxos" or so. That's a good string, becuase it still allows me to install other OSes in parallel (i.e. "waldoos"), but it won't allow parallel installation of another instance of "quuxos", since they'd fight over the "quuxos" dir then. But as mentioned, I think that'd be OK.

Now, this was never made automatic, since IMAGE_ID hasn#t existed for that long, and before I figure out it should be IMAGE_ID I was actually advertising to name it just "DEfault" (which is OKish, but means you can only install a single OS in the ESP, not even quuxos and waldoos in parallel).

Does this make sense?

**Comment by poettering** [comment]
Hence me proposal for cleaning this all up.

1. replace the --make-machine-id-directory= switch to bootctl so that you can choose between:
    1. use machine ID (example: /boot/913bb3d6754349b395586aa4199fe457/)
    2. use IMAGE_ID from /etc/os-release (example: /boot/quuxos/)
    3. (maybe the fixed string "Default")
    4. use arbitrary supplied string
    5. automatic discovery (i.e. look for machine ID or IMAGE_ID, or "Default" paths and use them if found)
2. maybe add a file /etc/kernel/image-directory or so that just contains the string to use, and that is used if the switch above is not used, this is where the admin would configure it if they want to change it to arbitrary stuff that cannot be auto-detected.
3. change kernel-install to search for the dir automatically, i.e. look for /boot/$MACHINE_ID, /boot/IMAGE_ID, /boot/Default, or if configured use whatever is in /etc/kernel/image-directory.
4. change mkosi to always use the IMAGE_ID mode if an image id is specified, otherwise the fixed string "Default". After all its a tool for the second usecase described above.

**Comment by DaanDeMeyer** [comment]
I'm a bit confused why we should extend the --make-machine-id-directory switch of bootctl. I had the impression that the only reason we added that switch was to keep backwards compatibility after I changed bootctl to not create the machine ID directory in https://github.com/systemd/systemd/commit/31e57550b552e113bd3d44355b237c41e42beb58 because that broke backwards compatibility because there were tools relying on bootctl creating the machine ID directory in $BOOT.

Instead, why not have kernel-install create the relevant directories and only keep the minimum in bootctl to keep backwards compat intact (which is what --make-machine-id-directory does now)? We don't enforce that bootctl install should be executed before kernel-install so kernel-install will have to have support for creating the necessary directories regardless so it seems pointless to add the same functionality to bootctl unless it's required to keep backwards compat intact.

It should be easy enough to extend kernel-install to check for IMAGE_ID in /etc/os-release and use that if the machine ID isn't available. We already have a fallback to "Default" in kernel-install if nothing else is available to use, although I'm a bit sad now that I added that, I think it'd be much better to fail if we can't find an IMAGE_ID in /etc/os-release because it seems extremely easy to end up with conflicting installs to the same directory if we silently default to "Default". 

Also, what do we do with KERNEL_INSTALL_MACHINE_ID? Unfortunately that ended up in 250. Do we break compat and remove it again? If so, we'll likely end up breaking Anaconda again. But it might be better to do a mea culpa here and break compat now before this ends up in a public Fedora/centos release.

There's also the factory reset usecase that is brought up in #22224. If /etc is removed, we can't find the relevant directory in /efi anymore. This would happen with both IMAGE_ID in /etc/os-release and machine ID in /etc/machine-id. I'm not sure there's a way around aside from embedding the information in a directory that doesn't get removed on factory reset. Or we assume that on factory reset the bootloader stuff gets removed before the reset and installed again after the reset.

**Comment by poettering** [comment]
> I'm a bit confused why we should extend the --make-machine-id-directory switch of bootctl. 

Not really "extend". Probably more "replace by something else", i.e. --kernel-image-directory-name= or so. I mean, if you have an entirely empty ESP (which is likely before you run "bootctl install" for the first time) you need to pick whether to use the machine ID or the image ID for the naming or something else, we cannot possibly guess which of the two usecase you have if nothing was written yet. 

Once the dir exists we can likely auto-detect it for the future.

**Comment by poettering** [comment]
> Instead, why not have kernel-install create the relevant directories and only keep the minimum in bootctl to keep backwards compat intact (which is what --make-machine-id-directory does now)? We don't enforce that bootctl install should be executed before kernel-install so kernel-install will have to have support for creating the necessary directories regardless so it seems pointless to add the same functionality to bootctl unless it's required to keep backwards compat intact.

The problem with that is that kernel-install runs in the bg, i.e. it can only operate based on auto-detection or configuration on disk. bootctl has the benefit that it runs on explicit request, possibly even interactively, so it's easy to make a choice there, create the dir and then know for sure that kernel-install will then pick up what it did.

**Comment by poettering** [comment]
> Also, what do we do with KERNEL_INSTALL_MACHINE_ID? Unfortunately that ended up in 250. Do we break compat and remove it again? If so, we'll likely end up breaking Anaconda again. But it might be better to do a mea culpa here and break compat now before this ends up in a public Fedora/centos release.

So, I'd probably drop it from the docs, but still honour it if it is set.

**Comment by poettering** [comment]
> There's also the factory reset usecase that is brought up in #22224. If /etc is removed, we can't find the relevant directory in /efi anymore. 

I would say factory reset mechanisms are something primarily relevant for scheme 2, as described above. That said, if people want factory reset to work for scheme 1, i.e. the ability to *reset* an *instance* of an OS, instead of removing all instances and creating a new once from scratch, then they could make this possible: we support the `systemd.machine_id=` kernel cmdline option since a while that may be used to specify the machine ID to use when coming up from scratch (i.e. it has no effect if /etc/machine-id is already initialized. Thus, if the boot loader spec snippets would include that in the kernel cmdline they generate you can actually flush out /etc, and reboot and we'd then reinitialize everything, but *reuse* the old machine ID, and thus also reuse the dir in $BOOT again. Actually, our kernel-install scripts should generate the snippets with that automatically!

**Comment by DaanDeMeyer** [comment]
> I would say factory reset mechanisms are something primarily relevant for scheme 2, as described above. That said, if people want factory reset to work for scheme 1, i.e. the ability to reset an instance of an OS, instead of removing all instances and creating a new once from scratch, then they could make this possible: we support the systemd.machine_id= kernel cmdline option since a while that may be used to specify the machine ID to use when coming up from scratch (i.e. it has no effect if /etc/machine-id is already initialized. Thus, if the boot loader spec snippets would include that in the kernel cmdline they generate you can actually flush out /etc, and reboot and we'd then reinitialize everything, but reuse the old machine ID, and thus also reuse the dir in $BOOT again. Actually, our kernel-install scripts should generate the snippets with that automatically!

This works if we're using the machine ID as the directory in $BOOT, but not if we end up using the image ID from /etc/os-release. But shouldn't the IMAGE_ID  be protected from a factory reset of /etc? It seems like something that shouldn't be in /etc because we'd want to keep it intact even if a factory reset is done. Does it really belong in /etc? Then again, it doesn't come from the distro so we can't put it in /usr.

**Comment by johannbg** [comment]
> Then again, it doesn't come from the distro so it can't be put it in /usr.

Hmm upstream can be in the role of the vendor so upstream can place files in /usr then other vendors ( like downstream distribution ) will simply have to override that.

**Comment by poettering** [comment]
> This works if we're using the machine ID as the directory in $BOOT, but not if we end up using the image ID from /etc/os-release. But shouldn't the IMAGE_ID be protected from a factory reset of /etc? 

IMAGE_ID is a vendor-chosen string, see my example above: "quuxos" for a hypothetical QuuxOS operating system. i.e. the machine id binds the dir to *instances* of an OS, but the image id only to the supplier of the OS, not any instance, and thus only allows for a single instance of the OS per system.

Note that /etc/os-release is not really a personalized file, it's actual name is /usr/lib/os-release, and /etc/os-release is just a symlink to it. (The only reason why people shouldn't go directly to /usr/lib/os-release, because at RH people wanted a "flavour" of the OS that can theoretically be switched via RPM package installs. In that case /etc/os-release is a file that is an "extended version" of /usr/lib/os-release. Anyway, key take away is that IMAGE_ID is a field chosen by the *vendor* of the image, and hence the same for *all* installations (aka "instances") of an OS.

> It seems like something that shouldn't be in /etc because we'd want to keep it intact even if a factory reset is done. Does it really belong in /etc? Then again, it doesn't come from the distro so it can't be put it in /usr.

**Comment by DaanDeMeyer** [comment]
> Note that /etc/os-release is not really a personalized file, it's actual name is /usr/lib/os-release, and /etc/os-release is just a symlink to it. (The only reason why people shouldn't go directly to /usr/lib/os-release, because at RH people wanted a "flavour" of the OS that can theoretically be switched via RPM package installs. In that case /etc/os-release is a file that is an "extended version" of /usr/lib/os-release. Anyway, key take away is that IMAGE_ID is a field chosen by the vendor of the image, and hence the same for all installations (aka "instances") of an OS.

So the idea is to ship the IMAGE_ID as part the rpm that provides /usr/lib/os-release? I'm trying to understand how this would work for image builders. Unless I missed something, when building mkosi images, we don't persist the image ID in os-release at all except when building Debian where we append it to /etc/os-release as part of the build process. So simply modifying kernel-install to use the IMAGE_ID from os-release wouldn't work for mkosi because the IMAGE_ID isn't persisted in os-release.

We could modify os-release and append the image ID but that would mean modifying a file in /usr which is bad or copying it to /etc/ which means it would get wiped on factory reset, which is also bad.

Technically, we could build an install a "mkosi" rpm as part of the build process that would include the IMAGE_ID in a modified os-release file but that would conflict with the existing file so then we'd need something like os-release.d/ so we can add extra snippets of key/value pairs such as IMAGE_ID which would also be rather involved.

**Comment by poettering** [comment]
> So the idea is to ship the IMAGE_ID as part the rpm that provides /usr/lib/os-release? I'm trying to understand how this would work for image builders. Unless I missed something, when building mkosi images, we don't persist the image ID in os-release at all except when building Debian where we append it to /etc/os-release as part of the build process. So simply modifying kernel-install to use the IMAGE_ID from os-release wouldn't work for mkosi because the IMAGE_ID isn't persisted in os-release.

Yeah, mkosi should propagate its idea of "IMAGE_ID" into os-release automatically, when set. Currently you have to do that manually from mkosi.build.

> We could modify os-release and append the image ID but that would mean modifying a file in /usr which is bad or copying it to /etc/ which means it would get wiped on factory reset, which is also bad.

The assumption was to do that in /usr/, after rpm/deb did its thing. I mean, that's how I thought mkosi to be used: you build an image with rpm/deb, and then make modifications to it, before you ship it and those modifications *can* be in /usr/ too if you build an image that is updated with other tools than rpm/deb. For example, if you build the mkosi definition in the systemd tree it will install the freshly built systemd all over /usr, mixing the RPM/deb stupplied files with the freshly locally built systemd tree.

**Comment by DaanDeMeyer** [comment]
> The assumption was to do that in /usr/, after rpm/deb did its thing. I mean, that's how I thought mkosi to be used: you build an image with rpm/deb, and then make modifications to it, before you ship it and those modifications can be in /usr/ too if you build an image that is updated with other tools than rpm/deb. For example, if you build the mkosi definition in the systemd tree it will install the freshly built systemd all over /usr, mixing the RPM/deb stupplied files with the freshly locally built systemd tree.

For the development images use case, I agree that's a good way to do things. Is it the way to go though if we're building production ready "golden" images? I guess if you're going for a "golden" image with read-only /usr, it might not be that bad to manually modify stuff in /usr after all the packages have been installed.

**Comment by poettering** [comment]
One more thought: maybe as a fallback for IMAGE_ID we should use just ID. This means, that if my Fedora-based image doesn't have the IMAGE_ID field set, because I am lazy, then I'll get the dir named "fedora" which is pretty good too. It means you cannot install multiple fedora images this way in parallel, but at least you can install an ubuntu one in parallel with fedora... And given that ID was defined for /etc/os-release since time began it should be universally supported.

**Comment by poettering** [comment]
> For the development images use case, I agree that's a good way to do things. Is it the way to go though if we're building production ready "golden" images? I guess if you're going for a "golden" image with read-only /usr, it might not be that bad to manually modify stuff in /usr after all the packages have been installed.

Touching /usr/ after rpm/dnf/dpkg/apt did their things should generally OK – unless people intend to update the images later with rpm/dnf/dpkg/apt instead of some other tool (i.e. do not intend to use A/B images or so). In that case things are more complicated, but if so they have to package *everything* in proper RPMs anyway, and my assumption is that the distro will provide them with an OK way to install an alternative RPM that provides /usr/lib/os-release in that case, it's not what we have to provide.

**Comment by poettering** [comment]
#22463 should now be ready, and address all issues I raised here in one way or another. PTAL

**Comment by poettering** [comment]
Btw, I kept --make-machine-id-directory= now in place, but renamed it --make-entry-directory=, i.e. drop the reference to the machine ID, given it can be any kind of string.

And I made the string configurable via --entry-token=, and it's persisted. Hence depending on your usecase you can use the machine ID (which continues to be the default), or use ID=/IMAGE_ID= from os-release or even some completely unrelated string if your choosing. THe choice is then persisted in /etc/kernel/entry-token.

This should keep the door for all usecases open
