### ISSUE TITLE
networkd: Is NTP a system level configuration or interface level

### ISSUE THREAD

**Issue by sunharis** [systemd/systemd#22384]
I have a system with two ethernet interfaces, eth0 and eth1. Per networkd, the NTP servers are property at interface level.
But NTP is for the time management and it does not matter if the time comes down to the system via eth0 or eth1. Single time should be given to the system.
Does it makes more sense to move NTP servers as a system level configuration ? 

Same question holds good for the NameServers as well.

**Comment by sunharis** [comment]
@poettering @ratagupt

**Comment by yuwata** [comment]
If you want to configure system wide NTP servers, then please create the following:
```
# /etc/systemd/timesyncd.conf.d/your-ntp-servers.conf
[Time]
NTP=address_or_name_of_NTP_server
```
For DNS servers, similarly you can configure /etc/systemd/resolved.conf.d/foo.conf.

About the question why NTP or DNS servers assigned by networkd is per-link config. Because each network interface may be connected to different network. For example, if the host is a router, then one interface is connected to upstream (WAN), and another is to downstream (LAN). In such case, the NTP or DNS provided through WAN interface cannot be connected through the LAN interface, and vice versa. And if the WAN interface becomes down, then timesyncd or resolved should and can handle that the DNS or NTP servers assigned to the WAN interface cannot be accessed if these settings are per-link. If these servers are assigned globally, these daemons cannot do like that.

Anyway, this is the design of timesyncd, resolved, and networkd. And we cannot change that. And I do not think there is no good reason to change that. Closing.

**Comment by sunharis** [comment]
Thank you @yuwata

**Comment by sunharis** [comment]
@yuwata What is the way to differentiate between the Static NTP servers and DHCP provided NTP servers ?

**Comment by yuwata** [comment]
Sorry, could you elaborate more? You can configure NTP servers in many ways.
```
[Match]
Name=eth0

[Network]
NTP=ntp1.example.com

[DHCPv4]
UseNTP=yes|no

[DHCPv6]
UseNTP=yes|no

[IPv6AcceptRA]
UseNTP=yes|no
```
You can also configure DNS servers in the similar ways.

Also, you can change NTP servers `timedatectl ntp-servers eth0 ntp2.example.com ntp3.example.com`. But the settings take effect only in a runtime, that is, the specified servers are reset when networkd is restarted.

**Comment by sunharis** [comment]
I will be storing the NTP IP addresses at the interface file . Then what is the way to mark which IP is assigned by DHCP and which IP is assigned statically by a user setting ? When a user looks at the interface settings, i wanted a way to list them separately.

**Comment by yuwata** [comment]
If you use v250 or newer, then you can find detailed information by using `networkctl --json pretty status eth0`. E.g.
```json
        "DNS" : [
                {
                        "Family" : 2,
                        "Address" : [
                                192,
                                168,
                                86,
                                1
                        ],
                        "ConfigSource" : "DHCPv4",
                        "ConfigProvider" : [
                                192,
                                168,
                                86,
                                1
                        ]
                },
```
Then, the DNS server address 192.168.86.1 is provided by DHCPv4 server 192.168.86.1.
Unfortunately, user friendly way, that is, `networkctl status` without `--json` option, does not show the detailed information, at least currently. But, that is in my TODO list.
