### ISSUE TITLE
Support NDOF devices

### ISSUE THREAD

**Issue by albfan** [systemd/systemd#22503]
**Is your feature request related to a problem? Please describe.**

Is it possible to support natively this type of devices:

![3d mouse](https://gitlab.freedesktop.org/libinput/libinput/uploads/a09a80816d466c832d1c6cefdd828b9b/image.png)

It is just 6 axis + 2 buttons

Here an analysis from libinput perspective: https://gitlab.freedesktop.org/libinput/libinput/-/issues/736

Basically add ID_INPUT_NDOF and define how their axis should be mapped

**Describe the solution you'd like**

Define and support this devices (that describe itself in a report) so we can use them generically mapping it to any action)

**Describe alternatives you've considered**

Userspace drivers:

https://github.com/FreeSpacenav/spacenavd

This works out of the box in blender or freecad

**The systemd version you checked that didn't have the feature you are asking for**

    $ systemctl --version
    systemd 249 (v249.9-1.fc35)

**Comment by whot** [comment]
We discussed this in the linked libinput issue, step one for these devices is the addition of a new `ID_INPUT_NDOF` and I guess the updates to the hwdb to tag the ... 10? devices out there that match that description. It still won't be supported any more than it is now (anyone who already handles these will have that database already) and how libinput supports it is unclear still.

My general thought is: yes, that's fine, but until we have proper userspace support [1] we shouldn't add that property to systemd yet. Otherwise it's just yet another property we have to maintain when there's no user for it.

[1] doesn't need to be libinput, but at least *something* that matters

**Comment by albfan** [comment]
I'm fine with that. If at some point this needs to be implemented this is the way.

Let's close by now
