### ISSUE TITLE
RFE: Add % specifier that resolves to /run/credentials

### ISSUE THREAD

**Issue by flokli** [systemd/systemd#22549]
**Is your feature request related to a problem? Please describe.**

Most processes can be configured to read credentials from from a path described in an environment variable, but there's no way right now to assemble these paths from systemd, without wrapper scripts.

This means, if you want to run an application with SOME_SECRET_LOCATION= env var, which makes use of systemd service credentials, you need an intermediate wrapper script doing the interpolation and then invoking the real service.

**Describe the solution you'd like**

It'd be very convenient if systemd would support substituting `$CREDENTIALS_DIRECTORY` in `Environment=` directives.

The canonical way to do this seems to be Specifiers (from `systemd.unit(5)`), as we don't do variable interpolation there.

With this, something like the following would be possible without any wrapper scripts:

```ini
[Unit]
…
[Service]
ExecStart=/path/to/binary
LoadCredential=google_application_credentials:/run/secrets/google_application_credentials
Environment="GOOGLE_APPLICATION_CREDENTIALS=%c/google_application_credentials"
```

**Describe alternatives you've considered**

Sticking with the wrapper scripts

**The systemd version you checked that didn't have the feature you are asking for**
230

**Comment by flokli** [comment]
I realized we already do interpolate `$CREDENTIALS_DIRECTORY` in `ExecStart=` - so restricted this proposal to environment variables only.

**Comment by poettering** [comment]
We do not resolve env vars in env vars, sorry. We are not a shell. If you want a shell, use a shell.

The only thing we do is resolve them in a very minimalist way in Exec*=, at the moment of invocation. And I must say I kinda regret having added that too.

We really want Unit files to be simple, so that not just our tools can parse them. i.e. not a complex pattern resolution language, but just simple linear assignments. Doing variable expansion inside of variables (and thus requiring ordering, or dealing with recursions) is something we really don't want to do, as it turns units into a form of shell scripts, and that's a bad idea, you can then just use shell scripts in the first place.

**Comment by flokli** [comment]
Nope, I'm not asking to resolve env vars in env vars.

This is about having a specifier for the credentials directory (`%c`) also holding the contents of `$CREDENTIALS_DIRECTORY`.

Similar to how we already have `%S` for `$STATE_DIRECTORY`, `%t` for`$RUNTIME_DIRECTORY`, `%C` for `$CACHE_DIRECTORY` and `%L` for `$LOGS_DIRECTORY`.
