### ISSUE TITLE
Anonymous auth incompatible with dbus implementation

### ISSUE THREAD

**Issue by anthonybrandon** [systemd/systemd#22560]
I've noticed that since commit 1ed4723d38cd0d1423c8fe650f90fa86007ddf55 the dbus anonymous auth method seems incompatible with with other dbus implementations (specifically https://gitlab.freedesktop.org/dbus/dbus/)
Is this intentional?

The problem comes from two places: the unexpected DATA in sasl_auth_anonymous
And the server never sending the expected DATA back.

How to reproduce:
Try to connect to a remote https://gitlab.freedesktop.org/dbus/dbus/ server using anonymous auth and call some dbus method.

**Comment by leiflm** [comment]
https://github.com/altdesktop/python-dbus-next/pull/121 might be helpful to others.

**Comment by anthonybrandon** [comment]
@leiflm so am I interpreting that comment correctly that the sdbus implementation is correct and it's the other library that should be changed?

**Comment by dvdhrm** [comment]
Honestly, what dbus-daemon does looks wrong. It seems to require an inline argument to `AUTH <mech>` while the spec does not mandate this. `dbus/dbus-auth.c:handle_auth()` is what I am looking at. It calls `process_data()` unconditionally on any AUTH line, even though data is not mandatory in AUTH-lines. But not sure what exactly fails. Can you elaborate what the issue exactly is?

**Comment by leiflm** [comment]
> Honestly, what dbus-daemon does looks wrong. 

I'm looking at `systemd-stdio-bridge`.

> It seems to require an inline argument to `AUTH <mech>` while the spec does not mandate this. `dbus/dbus-auth.c:handle_auth()` is what I am looking at.

The [relevant statement](https://github.com/systemd/systemd/blob/3a2a0806f5520dc1a979f6f3faebfd5c6f10301b/src/libsystemd/sd-bus/bus-socket.c#L419) within the server context boils down to the question of whether the server should answer `OK` or `DATA`, if the client sends `AUTH ANONYMOUS`?

I'd argue the server should reply `OK` right away, as the client actually confirms that it is done sending credentials by sending `BEGIN` as reply to an `OK`. But I am not familiar with SASL. @dvdhrm do you know whether SASL mandates this?

So - IMO - what _should_ happen is:
```
...
C: AUTH ANONYMOUS
S: OK
C: DATA mytraceinfo
S: OK
C: BEGIN
```

> It calls `process_data()` unconditionally on any AUTH line, even though data is not mandatory in AUTH-lines. But not sure what exactly fails. Can you elaborate what the issue exactly is?

I assume you are referring something different (client code?) than I am. Anyway, the server [seems](https://github.com/systemd/systemd/blob/3a2a0806f5520dc1a979f6f3faebfd5c6f10301b/src/libsystemd/sd-bus/bus-socket.c#L474) to discard the trace info.

**Comment by anthonybrandon** [comment]
This is what I am seeing (note the client is sdbus, server is dbus):

```
C: AUTH ANONYMOUS
C: DATA 616e6f6e796d6f7573
C: BEGIN
S: OK <bunch of hex>
S: ERROR "Sent DATA while expecting BEGIN"
```

The "working" version looks like this (where I reverted commit 1ed4723d38cd0d1423c8fe650f90fa86007ddf55):

```
C: AUTH ANONYMOUS  616e6f6e796d6f7573
C: BEGIN
S: OK <bunch of hex>
```

If instead of reverting that commit I just modify the AUTH line to match what the server expects I get:

```
C: AUTH ANONYMOUS 616e6f6e796d6f7573
C: BEGIN
S: OK <bunch of hex>
# Client forever waiting for DATA that never comes
```

**Comment by dvdhrm** [comment]
Btw., it does correctly initiate it in case of EXTERNAL. Only for ANONYMOUS it does not.

**Comment by leiflm** [comment]
> `If an AUTH command specifies a mechanism, and the server supports said mechanism, the server should begin exchanging SASL challenge-response data with the client using DATA commands. `

So is it supposed to exchange data and thus `NOP`, if there is none (i.e. `AUTH ANONYMOUS` _without_ trace information)? Or should it query the client for nothing anyway?

**Comment by dvdhrm** [comment]
> > This is what I am seeing (note the client is sdbus, server is dbus):
> > ```
> > C: AUTH ANONYMOUS  616e6f6e796d6f7573
> > C: BEGIN
> > S: OK <bunch of hex>
> > ```
> 
> I am a bit confused by either of these communication sequences. As far as I understand [the `BEGIN` command as specified in the DBus specification](https://dbus.freedesktop.org/doc/dbus-specification.html#auth-command-begin), should only send by the client, after it received an `OK` from the server:

Yeah, the order is wrongly displayed because clients use pipelined implementations. This means they predict what the server answers will be and just assemble all responses ahead of time so they can send it in a single roundtrip, rather than having one roundtrip for each request.

Obviously, this only works if you can predict the messages that end up being sent. And this also means you get weird logs when one side mispredicted the comm but still sent its messages as pre-assembled.

> > `If an AUTH command specifies a mechanism, and the server supports said mechanism, the server should begin exchanging SASL challenge-response data with the client using DATA commands. `
> 
> So is it supposed to exchange data and thus `NOP`, if there is none (i.e. `AUTH ANONYMOUS` _without_ trace information)? Or should it query the client for nothing anyway?

I read it that the server should send `DATA` and the client should respond with `DATA <trace>` (where an empty trace would be allowed). But the `should` is a bit vague, so maybe it is fine if the server does not do this. Problem is, in that case the piplined / pre-assembled messages are incorrect.

**Comment by dvdhrm** [comment]
> > I read it that the server should send `DATA` and the client should respond with `DATA <trace>` (where an empty trace would be allowed). But the `should` is a bit vague, so maybe it is fine if the server does not do this. Problem is, in that case the piplined / pre-assembled messages are incorrect.
> 
> Could you point to the SASL RFC where this "should" originates from? It would be a useful reference comment within the code.

This is from the dbus-spec.

> Reading the [`AUTH` protocol's documentation of the D-Bus specification](https://dbus.freedesktop.org/doc/dbus-specification.html#auth-protocol) again, it could be read in a similar, contradictory way:
> 
> > The AUTH command is sent by the client to the server. The server replies with DATA, OK or REJECTED.
> 
> This reads like: "Either answer `DATA`, `OK` or `REJECTED`.
> 
> However, a subsequent statement (further down) appears to contradict this:
> 
> > If authentication succeeds after exchanging DATA commands, an OK command must be sent to the client.
> 
> It is not entirely clear to me, whether the _"after"_ is mandatory or to be read as _"in case"_. I assume the missing `,` implies that it refers to "in case of"?

I think we can avoid all this by inlining the trace-string in the anonymous case and then *NOT* send `DATA`. But this would require adjusting `bus_socket_auth_verify_client()` to expect just one reply in the anonymous case. I don't think anyone really cares enough to fix the anonymous case, though. What is the advantage of using it, anyway?

**Comment by leiflm** [comment]
> > > I read it that the server should send `DATA` and the client should respond with `DATA <trace>` (where an empty trace would be allowed). But the `should` is a bit vague, so maybe it is fine if the server does not do this. Problem is, in that case the piplined / pre-assembled messages are incorrect.
> > 
> > 
> > Could you point to the SASL RFC where this "should" originates from? It would be a useful reference comment within the code.
> 
> This is from the dbus-spec.

Does the dbus-auth protocol deviate from the SASL protocol spec here?

> > Reading the [`AUTH` protocol's documentation of the D-Bus specification](https://dbus.freedesktop.org/doc/dbus-specification.html#auth-protocol) again, it could be read in a similar, contradictory way:
> > > The AUTH command is sent by the client to the server. The server replies with DATA, OK or REJECTED.
> > 
> > 
> > This reads like: "Either answer `DATA`, `OK` or `REJECTED`.
> > However, a subsequent statement (further down) appears to contradict this:
> > > If authentication succeeds after exchanging DATA commands, an OK command must be sent to the client.
> > 
> > 
> > It is not entirely clear to me, whether the _"after"_ is mandatory or to be read as _"in case"_. I assume the missing `,` implies that it refers to "in case of"?
> 
> I think we can avoid all this by inlining the trace-string in the anonymous case and then _NOT_ send `DATA`. But this would require adjusting `bus_socket_auth_verify_client()` to expect just one reply in the anonymous case.

Your suggestion would be that client send `AUTH ANONYMOUS ` (note the ` `/"empty" trace info)? As far as I understood the SASL Anonymous specification that's entirely optional?

> I don't think anyone really cares enough to fix the anonymous case, though. What is the advantage of using it, anyway?

It's useful for [Windows machines to authenticate in debug/development environments](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2682#note_1463067).

**Comment by leiflm** [comment]
So to fix this particular issue instance, you simply send a constant as trace-string along?

But this kind of avoids the discussion of how SASL profiles should behave if there are no further credentials to exchange? Maybe the `SASL` project would be the right place to discuss this though.

**Comment by dvdhrm** [comment]
> So to fix this particular issue instance, you simply send a constant as trace-string along?

We always send a constant trace-string. This patch just changes the line it is sent in.

> But this kind of avoids the discussion of how SASL profiles should behave if there are no further credentials to exchange? Maybe the `SASL` project would be the right place to discuss this though.

The dbus reference implementation does not trigger a DATA challenge if no inline trace string was sent. We need to adjust to that. I don't see the point in discussing whether it is actually correct. This would be the job of the D-Bus reference implementation authors. It does not affect our code, as we need to be compatible to older dbus-daemon versions, anyway.

**Comment by smcv** [comment]
I would warn D-Bus implementors that `AUTH ANONYMOUS` is a security disaster (it gives clients ambient authority to whatever they happen to be able to access), and was part of the reason for [the 2015 recall of 1.4M vehicles](https://www.theguardian.com/business/2015/jul/24/fiat-chrysler-recall-jeep-hacking). The D-Bus spec calls it out as something that should not be accepted by message buses (in other words, nobody should configure dbus-daemon with `<allow_anonymous/>`, and I've been very tempted to remove that feature entirely).

`EXTERNAL` is much, much better. The major problem with `EXTERNAL` is that it doesn't work on Windows (but neither does systemd).

If you're doing remote-debugging against a message bus on an embedded device or something, the approach involving `systemd-stdio-bridge` as used by `busctl --host=...` should be strongly preferred over `ANONYMOUS`.

> Yeah, the order is wrongly displayed because clients use pipelined implementations

I don't think the D-Bus specification was intended to allow for pipelined implementations of the SASL handshake, so pipelining messages (in other words, making an assumption about what the next message will be, and blindly replying to it before it has been received) is always going to be rather unstable and involve relying on some implementation details.

> So is it supposed to exchange data and thus NOP, if there is none (i.e. AUTH ANONYMOUS without trace information)? Or should it query the client for nothing anyway?

It's a long time since I read all of RFC 4422, but I *think* the intention is that at a conceptual level, during the mechanism-specific part of the handshake, the server speaks first (the challenge, in D-Bus this is DATA) and the client responds (the response, in D-Bus this is also DATA), and there is always at least one challenge from server to client, with exactly one response from client to server per challenge; *but* as an optimization, for mechanisms like ANONYMOUS, EXTERNAL and PLAIN where the server's first challenge is known to be always empty, the client can optimize away the round-trip by sending its initial response to the empty challenge as an extra argument to the protocol's equivalent of D-Bus AUTH. However, in D-Bus at least, that optimization is only valid if the initial response is *also* non-empty, because D-Bus doesn't have a representation for an initial response of length 0 bytes (I don't remember whether that's a D-Bus protocol limitation, or a RFC 4422 SASL limitation).

So if dbus-daemon gets `AUTH ANONYMOUS`, the reply should be `DATA` (because `AUTH ANONYMOUS` specifies a method but no initial response, therefore the dbus-daemon needs to send its initial challenge, to which the client should reply with an empty or non-empty response). The reply should not be `OK`, and @dvdhrm seems to be correct to say that the server-side of libdbus is getting this wrong? Merge requests welcome.

If all known D-Bus server-side implementations are happy with a non-empty initial response (which I suspect they are, because they tend to have been implemented by people who didn't actually read the SASL RFC and assumed that inlining the initial response is mandatory, as we've seen in the past with EXTERNAL), then having the client-side send a non-empty initial response inlined into the `AUTH` command seems like a good way to work around the server-side bug.

**Comment by leiflm** [comment]
>  there is always at least one challenge from server to client, with exactly one response from client to server per challenge

Thank you for clarifying this.

> If you're doing remote-debugging against a message bus on an embedded device or something, the approach involving `systemd-stdio-bridge` as used by `busctl --host=...` should be strongly preferred over `ANONYMOUS`.

I assume that you're refering to [`unixexec`](https://github.com/systemd/systemd/blob/3a2a0806f5520dc1a979f6f3faebfd5c6f10301b/src/libsystemd/sd-bus/sd-bus.c#L1476) address specification. I believe I've [tried that](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2682) on Windows to no avail. But I'm not certain about that.

**Comment by zeenix** [comment]
> `EXTERNAL` is much, much better. The major problem with `EXTERNAL` is that it doesn't work on Windows (but neither does systemd).

@smcv I also have another use case where `EXTERNAL` wouldn't work (`COOKIE` might but with some hacks): connecting to a bus running on a host from a VM through AF_VSOCK socket. I'm well aware that this is the major reason for your reluctance to [add AF_VSOCK support in the dbus reference implementation](https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/200) but I'm using Firecracker, which [bridges the AF_VSOCK as/to a AF_UNIX socket on the host side](https://github.com/firecracker-microvm/firecracker/blob/main/docs/vsock.md#guest-initiated-connections) so I can use dbus-daemon on the host w/o explicit AF_VSOCK support. However client from inside the VM can't do an  `EXTERNAL` auth as it only has access to an AF_VSOCK socket.

So unless and until I can make COOKIE auth somehow work, I've no choice but to use ANONYMOUS auth.

> I would warn D-Bus implementors that `AUTH ANONYMOUS` is a security disaster (it gives clients ambient authority to whatever they happen to be able to access), and was part of the reason for [the 2015 recall of 1.4M vehicles](https://www.theguardian.com/business/2015/jul/24/fiat-chrysler-recall-jeep-hacking).

While that is a good example of how easily you can design a massive security hole in a super safety-critical system, I think:

1. `AUTH ANONYMOUS` was only one part of the problem.
2. Not everyone needs to use dbus in safety critical systems and hence no need for top-notch security.
3. It's not the fault of dbus if people enable a security hole in their setup, as long as they're warned about it (which they are).

So I would strongly advise not to remove ANONYMOUS auth from the reference implementation.
