### ISSUE TITLE
Confusing man page systemd.network / upper case DHCPv4

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#22623]
Originally filed as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006414

It turns out,  that
```
  <refsect1>
    <title>[DHCPv4] Section Options</title>
```
in systemd.network.xml is ultimately turned into
```
[DHCPV4] SECTION OPTIONS
```
in `man systemd.network`

As a result, the user tried to put the config into a `[DHCPV4]` section which systemd-networkd failed to read.

Now, we could blame the user for not reading the man page carefully enough and that  `DHCPV4` is actually ` `DHCPv4`.

But maybe we can do something better?

That everything is turned into uppercase letters is probably something of the man/xml toolchain?

Is there a way to avoid that?

If not, should we make the parser more forgiving and treat DHCPV4 and DHCPv4 as the same?

Other ideas?

**Comment by keszybz** [comment]
Yeah, it's a long-standing issue caused by the baroque-yet-underperforming docbook toolchain. The first sentence in that section (as in any other section describing a configuration section) starts with "The [DHCPv4] section…", so we describe the section name correctly; sometimes you have to read past the title. I think we can't do anything about this right now.
