### ISSUE TITLE
journal files have an odd x-bit set

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#22729]
Looking at the journal file created on a system running v250:
```
$ getfacl system.journal 
# file: system.journal
# owner: root
# group: systemd-journal
user::rw-
group::r-x			#effective:r--
group:adm:r--
mask::r--
other::---
```
There is this odd, even if in-effective, x-bit set for the group

It get's more interesting looking at a user journal file:
```
$ getfacl user-1000.journal 
# file: user-1000.journal
# owner: root
# group: systemd-journal
user::rw-
user:michael:r--
group::r-x			#effective:r--
group:adm:r-x			#effective:r--
mask::r--
other::---
```
Here the x-bit is set for both group and group:adm.

Looking at a system running an older version, i.e. v245, I also see:

```
$ getfacl system.journal 
# file: system.journal
# owner: root
# group: systemd-journal
user::rw-
group::r-x			#effective:r--
group:adm:r-x			#effective:r--
mask::r--
other::---
```

Can anyone explain those inconsistencies? Could we get rid of the x-bit somehow? It's a minor, cosmetic issue for sure but it has confused users , see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934284

It's especially confusing if one still uses a non-persisent journal, as then journald will create a log file during boot without that x-bit apparently and systemd-tmpfiles will later fix up the ACLs so after a rotation new log files will have the x-bit set.

**Comment by mbiebl** [comment]
I would agree it's not an important issue, but I'd say it is not a non-issue.
It at least is a cosmetic issue in the sense that it's confusing.
Apparently it also trips up intrusion detection systems like https://aide.github.io/ which seemingly monitor if the permissions of files change and log about that.

**Comment by mbiebl** [comment]
I also don't see the inconsistencies explained between user and system journals?

**Comment by poettering** [comment]
> I would agree it's not an important issue, but I'd say it is not a non-issue.

What is the issue precisely? i don't get it? the mask ACL field will mask the x bit away, and it does that. Are you saying that's not working?

The ACLs we set do make sense if you take them together. if you naively look at a single entry of the ACL and ignore the mask they don't, but why would you do that? you are holding it the wrong way if you do...

> Apparently it also trips up intrusion detection systems like https://aide.github.io/ which seemingly monitor if the permissions of files change and log about that.

file a bug against it. It *must* take the ACL mask into account. The ACL entries alone are not relevant. The entries in combination with the mask are.

A major reason why the mask exists and is useful is precisely to allow default ACLs to be set on a dir that make sense on both files and dirs created within them, and that recursively. Because there's only one default ACL per dir, but the modes that dirs and files typically should have created within them is different, because dirs should get x and files typically not. The mask ACL field allows this to be handled nicely, by masking it what is not desired of the default ACLs.

Or in other words, if you have issues with POSIX ACL design, complain to the POSIX people. But we are using it exactly the way it was designed. If you disagree with the usefulness of the mask concept of POSIX ACLs, then that's not something to complain to systemd about though, but to the people who designed POSIX ACLs.

> I also don't see the inconsistencies explained between user and system journals?

The ACL entry that gives users read access on their own journal files we create ourselves, from the numeric UID of the client that sent us the log message. We can do this safely, because it's already a numeric UID, i.e we don#t have to resolve it.

Thus: the ACLs user entries you see are genreated by us in code from nmeric UID info. The ACL group entries you see are generated indirectly via tmpfiles.d/ default ACLs on the enclosing dirs, because for them we need to explicitly resolve "adm" and "wheel", which would block if we'd do it in journald, and hence we cannot.
