### ISSUE TITLE
runtime/dbus interface to timesyncd

### ISSUE THREAD

**Issue by sielicki** [systemd/systemd#22742]
**Is your feature request related to a problem? Please describe.**
org.freedesktop.timedate1 provides the ability to stop/start timesyncd, but timesyncd lacks a dbus interface that allows configuration of key ntp settings: servers and polling rates.

On a stateless systemd embedded device you might want to enable an end user to select a particular ntp server on their local network for the device at runtime.

**Describe the solution you'd like**

Either a full dbus interface to timesyncd or some hack that exposes timesyncd options within timedated.

**Describe alternatives you've considered**

Currently, vendors can ship static ntp servers in a file, or possibly dynamically generate a drop in config file from some persistent settings and reload, but neither of these is ideal for stateless systems. It's also worth mentioning that the man page for timedated does not currently list volatile paths that it reads for drop in, if it does at all (haven't checked), which would complicate this workaround. 

**The systemd version you checked that didn't have the feature you are asking for**
249

**Comment by sielicki** [comment]
I just realized there's a PR open for this already.

**Comment by sielicki** [comment]
https://github.com/systemd/systemd/pull/22614

@zonque Please close this with PR.

**Comment by zonque** [comment]
What kind of source do you envision for information about NTP servers in your network? I'm asking because in our case we would most likely opt for mDNS, and my PR would then be just half of the story because there's need for some glue logic that bridges a mDNS monitor to timesyncd's new D-Bus property.

An alternative approach would be to make timesyncd speak to resolved directly in order to track mDNS services itself. #22532 would need to be merged for that, but then the implementation would be pretty straight forward.

**Comment by sielicki** [comment]
I work somewhere that makes IP cameras and, depending on local IT policies, installers might want to provision the devices to use a local NTP server to avoid external traffic.

In an ideal world, if their network was setup correctly, they could automatically determine that from someone else on the network. But more realistically, it would get saved off as a preference in a json file on a rw partition and my middleware would just send the correct dbus messages to configure the server on boot.
