### ISSUE TITLE
With systemd.unified_cgroup_hierarchy=1, shutdown gives "cgroup: remount is not allowed"

### ISSUE THREAD

**Issue by jamespharvey20** [systemd/systemd#2275]
Using systemd   228 (-3 Arch).  Just upgraded to linux 4.3.3 (-2 Arch), and started using the kernel parameter systemd.unified_cgroup_hierarchy=1

On shutdown/reboot, I see a message I haven't seen before (it's the "cgroup: remount is not allowed" line, gave a few extra lines a context.)  Maybe an ignorable / irrelevant message, but I really don't know, so passing it along.

[  OK  ] Reached target shutdown
[ time ] watchdog watchdog0: watchdog did not stop!
[ time ] watchdog watchdog0: watchdog did not stop!
[ time ] cgroup: remount is not allowed
[ time ] shutdown1: Failed to finalize  DM devices, ignoring

In case it matters, I do have a weird mounting setup.  Three identical drives, each with a 100MB and a 4.6TB partition.  md1 is a raid1 of the 100MB sd[.]1 partitions, for /boot.  LVM has the 4.6TB sd[.]2 partitions.  / and some others are btrfs lzo-compressed raid1 volumes on thinly provision LVM volumes.

**Comment by poettering** [comment]
This is purely cosmetic, but should certainly be fixed anyway.

**Comment by thx1111** [comment]
Arch
systemd 228-3
linux 4.4-3

Upgrading from linux 4.3 to 4.4, and booting with
 systemd.unified_cgroup_hierarchy=1
shutdown fails completely with

[...] systemd[1]:  segfault at 0 ip        (null)  sp ... error 14 in systemd[...]
Broadcast message from systemd-journald@<hostname> (<date>):
systemd[1]: Caught <SEGV>, dumped core as pid 395.
Broadcast message from systemd-journald@<hostname> (<date>):
systemd[1]: Freezing execution.
[...] systemd-journald[191]: Failed to send stream file descriptor to service manager: Connection refused
[...] systemd-journald[191]: Failed to send WATCHDOG=1 notification message: Transport endpoint not connected
<last message repeats>

Seen on both a Toshiba Satellite and an HP Pavilion.
Removing "systemd.unified_cgroup_hierarchy=1" from the linux command line is a work-around.
Is this seg fault a systemd issue or a linux kernel issue?

I cannot tell what program is pid 395.  It is something that runs after running "shutdown", but then the process table is no longer accessible.

**Comment by poettering** [comment]
The unified cgroup API exposed by the kernel isn't stable yet, maybe they changed it in some way systemd doesn't like. I haven't updated to kernel 4.4 yet, so what's going on with it yet. Anyway, incompatibility with the new kernel 4.4 of the unified hierarchy isn't really something to track in this bug, or probably at all, since the unified stuff is kinda a preview anyway, as the underlying API is still in flux.

We'll consider this stable starting as soon as we kernel 4.5 is out and we made sure systemd works fine with the unified support in that kernel release, as that's when the unified hierarchy support in the kernel is supposed to be stable.

**Comment by keszybz** [comment]
I hope this is fixed now. The kernel code changed, and our code changed in #2903.
