### ISSUE TITLE
Return value of sd_bus_error_copy() should only reflect whether the copy was successful.

### ISSUE THREAD

**Issue by jgruenm** [systemd/systemd#22816]
**systemd version the issue has been seen with**
 > Noted in v250 and before.

**Used distribution**
 > Irrelevant.  The problem can be seen in the **main** branch of the git repo.

**Linux kernel version used** (`uname -a`)
 > Irrelevant (see above).

**CPU architecture issue was seen on**
 > Irrelevant (see above)

**Expected behaviour you didn't see**
 > `sd_bus_error_copy()` should return a nonzero value only if the copy operation, _itself_ failed.

**Unexpected behaviour you saw**
 > `sd_bus_error_copy()` returns a nonzero error code, even if the copy was successful, simply because the source argument contains a value representing an error.  This is not what callers expect or generally want.

> The current manpage `man/sd_bus_error.xml` certainly doesn't suggest this behavior.  It indicates the return code is `-errno`-style, but says nothing about the return code reflecting the value contained in the source argument, even if the copy is successful.

> What makes this behavior _truly_ problematic is that one cannot reliably use the return code even as the corresponding errno value of the argument, since that could potentially mask a failure encountered during the copy operation, which some paths of the function also return.

**Steps to reproduce the problem**
 > Simply look at the code for `sd_bus_error_copy()`, in `src/libsystemd/sd-bus/bus-error.c`, and you can see for yourself.  It's a short function.

**Comment by poettering** [comment]
let me ask back: what did you actually intend to do with sd_bus_error_copy()?

the function is designed to guarantee that it always does something reasonable. i.e. even if it cannot copy the structure due to OOM it will return an initialized error struct, but in that case initialized by static data indicating the OOM.

so, this really is by design: a function that never can fail and thus is suitable for use in error paths (where handling errors is usually pointless, you are already *in* an error path).   now this means you cannot really distinguish the case where it returns failures that it was told to copy/pass along from failures that happened while copying, but given the intended use in error paths this is not a problem, but acceptable.

**Comment by poettering** [comment]
not that this structure is actually open coded, i.e. if you want a deep copy and handle errors caused by copying (though I wonder what the usecase for tht would be?) you can easily do that yourself, just strdup() the two fields in it, if non-NULL, and catch the results. No need to use sd_bus_error_copy() for that.
