### ISSUE TITLE
Fix time zone name form 'Kiev' to 'Kyiv' 

### ISSUE THREAD

**Issue by olegios** [systemd/systemd#22827]
According to the Ukraine local and international law, the correct name of **"Kiev"** is Kyiv.
Reference material:

1. Local: [Resolution No 55 of 27.01.2010 of the Cabinet of Ministers of Ukraine "On regulation of transliteration of Ukrainian alphabet by means of Latin alphabet "](https://zakon.rada.gov.ua/laws/show/55-2010-%D0%BF?lang=en#Text).
2. Global: [https://unstats.un.org/UNSD/geoinfo/UNGEGN/docs/10th-uncsgn-docs/econf/E_CONF.101_85_Standardization%20of%20Geographical%20Names%20_eng.pdf](https://unstats.un.org/UNSD/geoinfo/UNGEGN/docs/10th-uncsgn-docs/econf/E_CONF.101_85_Standardization%20of%20Geographical%20Names%20_eng.pdf)

`$ timedatectl list-timezones | grep Europe`

**AS-IS:**
`Europe/Kiev`

**TO-BE:**
`Europe/Kyiv`

**Comment by yuwata** [comment]
The timezone name is obtained from /usr/share/zoneinfo/tzdata.zi, which is managed by IANA (https://www.iana.org/time-zones).
Here is not a right place to report. Closing.

**Comment by keszybz** [comment]
Yeah, we're just parsing and printing the list provided by tzdata. We shouldn't change this here, because that'd just lead to chaos.

tzdata 2022a was just released a few days ago with updates for Ukraine, but it was some historical stuff. I guess the decision to use native transliteration happened to late. I hope that it can be done in the next update.
