### ISSUE TITLE
systemd-homed: --umask not honored

### ISSUE THREAD

**Issue by Nemris** [systemd/systemd#23007]
**systemd version the issue has been seen with**
 > systemd 250 (250.4-2-arch)

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux master 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > The umask set with the `--umask` parameter of `homectl` should take precedence over the system default stored in `/etc/profile`.

**Unexpected behaviour you saw**
 > The umask set with the `--umask` parameter of `homectl` is ignored, and the system default is used instead.

**Steps to reproduce the problem**
 > Create a fresh user with e.g. `homectl create --umask=0007 john`. Login as said user and run `homectl inspect`, noticing the line `UMask: 0007`. Finally, issue `umask` and observe that the value mentioned is the system's default (e.g. `0022`).
>
> Optionally, `touch` a file and confirm the permissions are not influenced by the umask set via `homectl`.

**Comment by poettering** [comment]
if `/etc/profile` also sets the umask it will override whatever homed/pam_systemd/pam_systemd_home set, simply because it runs later.

We can't do much about that, you need to fix your profile script...

Or am I misunderstanding what you are saying?

**Comment by Nemris** [comment]
I get what you mean, yes. I was under the impression that, given the fact that `~/.identity` is personal to a user, its config would take precedence over the systemwide one in the same fashion a `.bashrc`- or `.profile`-written `umask 0007` would. Is that a misunderstanding on my side?

**Comment by poettering** [comment]
well, .bashrc/.profile just do `source /etc/profile` iirc on most distros, so the system wide is simply sourced into your private one...

if you ask me, distros should drop resetting umask in /etc/profile so that pam_systemd/pam_systemd_home can set the umask and it counts. And even outside of the systemd world, by overriding the umask in /etc/profile by default they break pam_umask and similar modules.

On Fedora, /etc/bashrc sets umask, and it is loaded from /etc/profile. But id does that only on non-login shells. Which makes this somewhat OK i guess, as those mean PAM is not involved anyway.

Appears to me to get your distro to address this, and maybe do what Fedora does on this.

**Comment by Nemris** [comment]
The (possibly) interesting thing is that my `.bashrc` doesn't source `/etc/profile` - and my `.profile` didn't exist at the time of the report.

While LightDM might be the culprit in my case, as it has an `/etc/lightdm/Xsession` that apparently sources `/etc/profile` (among others), it looks like the issue appeared even on a simple TTY login. Any way to determine what sourced `/etc/profile` in that case?

**Comment by poettering** [comment]
you could modify /etc/profile and log from thre or so? and maybe sleep so that you can look at the process tree with some time?

Anyway, I think we can close this here, as we can#t fix that, and your distro simply shouldn#t override the umask, because that way neither pam_systemd nor any other PAM module that intends to set the umask can work, such as pam_umask.
