### ISSUE TITLE
systemd-udev does not use newer values from networkd drop-in link configuration

### ISSUE THREAD

**Issue by gogsbread** [systemd/systemd#23128]
**systemd version the issue has been seen with**
 > 249, 250, master

**Used distribution**
 > CentOS 8

**Linux kernel version used** (`uname -a`)
 > `Linux 5.6.13`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Expected that after changing a configuration value for a `.link` drop-in and triggering with `udevadm trigger --action add <sys/path/to/interface>`, the newer configuration value should take effect

**Unexpected behaviour you saw**
 > The drop-in `.link` configuration value wasn't effective unless there was a change in the main `.link` configuration

**Steps to reproduce the problem**
Assume a system has the following configuration
*/etc/systemd/network/foo.link*
``` 
[Link]
RxBufferSize = 2000

[Match]
OriginalName = eth0
```
*/etc/systemd/network/foo.link.d/1.conf*
``` 
[Link]
RxBufferSize = 3000

[Match]
OriginalName = eth0
```
and `ethtool -g eth0` correctly shows the Rx buffer to be `3000`(overridden).

Now change the value in drop-in for `RxBufferSize` to, say `5000` and trigger with `udevadm trigger --class add /sys/class/net/eth0`. You'd expect udevd to load the new configuration value and `ethtool -g eth0` to show `5000`, however it does not. Now if you change some random value in the main, `foo.link`, link configuration and `udevadm trigger` then the expect Rx buffer value shows up.

This problem is obvious when browsing the source code as it [reloads configuration](https://github.com/systemd/systemd/blob/da13d2ca0731b413841663052f2cc6832a855334/src/udev/net/link-config.c#L335) by using the timestamp of the base directory alone, `/etc/systemd/network`, and not the drop-ins.

This look like an undesired behavior and I can work on a patch if there is consensus that this should be fixed.

**Comment by g0tar** [comment]
Directory timestamp, seriously?! What makes anyone think that directory has anything to do with files inside... Any sane program should be consistent at configuration handling: either it is being kept in memory and reloaded on demand (command, signal), so the admin can keep on working on the files without worrying of anything to trigger the reload unexpectedly, or it should be revalidated each time it's needed. Pick one and do it properly.

What kind of shortcut is directory timestamp checking? Mail user agent app?

I've lost several hours on #23036 fighting against `udev` to fetch new files from overlayfs mounts... (`udevadm control -R; systemctl restart systemd-networkd; networkctl reload` etc.) finally doing the `reboot` a few times.

Oh, and BTW - since these `udev` files were put (by unknown reasoning) in `/etc/systemd/network` directory and intermixed with `networkd` files, the `networkctl reload` should force the `udev` to refetch these unconditionally. The same goes for `udevadm control -R` as it apparently also cuts corners.

**Comment by poettering** [comment]
> Directory timestamp, seriously?!

It's how this works on Linux. Creating/removing a file in a dir will propgate to the dir's timestamp. what did you think the timestamp of a dir was about.

> I've lost several hours on #23036 fighting against `udev` to fetch new files from overlayfs mounts...

Well, overlayfs is a bit icky. You should blame overlayfs here, not the quite reasonable UNIX semantics of dir timestamps.

**Comment by g0tar** [comment]
But modifying a file doesn't propagate to the dir containing it...

```
/etc/systemd/network#  sed 's/AlternativeName=testX/AlternativeName=testY/' 92-cluster-dev2.link > 91-cluster-dev2.link; sleep 1; udevadm trigger -c add /sys/class/net/eth3; sleep 1; ip l sh dev eth3
6: eth3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond10 state UP mode DEFAULT group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff permaddr 90:e2:ba:16:d6:f6
    altname testX
    altname testY
[altname testY added, but testX not removed]

/etc/systemd/network#  sed 's/AlternativeName=testX/AlternativeName=testZ/' 92-cluster-dev2.link >! 91-cluster-dev2.link; sleep 1; udevadm trigger -c add /sys/class/net/eth3; sleep 1; ip l sh dev eth3
6: eth3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond10 state UP mode DEFAULT group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff permaddr 90:e2:ba:16:d6:f6
    altname testX
    altname testY
[1st altname not removed - `92-cluster-dev2.link` providing it is no longer first in lexical order]
[2nd altname not changed - `91-cluster-dev2.link` updates ignored]

/etc/systemd/network#  ls -latr | tail -n2
drwxr-xr-x 1 root root   60 Apr 28 00:19 .
-rw-r--r-- 1 root root  554 Apr 28 00:23 91-cluster-dev2.link
[the directory timestamp is behind the actual file mtime]

/etc/systemd/network#  sed 's/AlternativeName=testX/AlternativeName=testZ/' 92-cluster-dev2.link > 90-cluster-dev2.link; sleep 1; udevadm trigger -c add /sys/class/net/eth3; sleep 1; ip l sh dev eth3
6: eth3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond10 state UP mode DEFAULT group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff permaddr 90:e2:ba:16:d6:f6
    altname testX
    altname testY
    altname testZ
[and so on]

/etc/systemd/network#  sed 's/AlternativeName=testX/AlternativeName=testV/' 92-cluster-dev2.link >! 90-cluster-dev2.link; touch .; sleep 1; udevadm trigger -c add /sys/class/net/eth3; sleep 1; ip l sh dev eth3
6: eth3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond10 state UP mode DEFAULT group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff permaddr 90:e2:ba:16:d6:f6
    altname testX
    altname testY
    altname testZ
    altname testV
[...until triggered by touch on directory]
```

[Note the descending prefixes vs updating the same file.]

While superfluous altname might be another issue[*] being actual (functional) alias of the device (not the descriptive `IFLA_IFALIAS` which doesn't even work: https://github.com/systemd/systemd/issues/23036#issuecomment-1102483423), not updating the file contents by it's own timestamp is simply a bug ...or misfortune design.

If it is assumed, that "existing-file update"=="reconfiguration" that requires manual triggering (`udevadm control -R`) while "new files might be fetched when needed (dir timestamp)", this is at best misleading and confusing. First of all, as already mentioned, this might catch not finished files, therefore is unreliable and every sane admin must reload manually anyway. For the second, it's not consistent with both `udev` and `systemd` general rule of "explicit config reloads". Therefore I strongly suggest to remove this "directory monitoring" feature as harmful. Just think about `ActivationPolicy=always-down` directive caught in some transient state of a `.network` file without finished `[Match]` section.


[*] such properties CAN be removed, whether they should when outdated (until `reconfigured`) is different question, with answer depending and varying on the source of such outdated setting - obsoleted/removed config file vs manual setting, i.e. if the previous altname was set by udev itself; but there are certainly some settings that cannot be reset to defaults when unset, like `ethtool` values. In this case the `networkctl` also misbehaves:

```
# networkctl reconfigure eth3; sleep 1; ip l sh dev eth3 
6: eth3: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc mq master bond10 state DOWN mode DEFAULT group default qlen 1000
    link/ether 90:e2:ba:16:d6:f4 brd ff:ff:ff:ff:ff:ff permaddr 90:e2:ba:16:d6:f6
    altname testX
    altname testY
    altname testZ
    altname testV
    altname testW
```
and doesn't remove the obsoleted altnames despite the link being actually reconfigured:
```
[ +32.665925] ixgbe 0000:04:00.1: removed PHC on eth3
[  +0.075062] bond10: (slave eth3): link status definitely down, disabling slave
[  +0.102608] ixgbe 0000:04:00.1: registered PHC device on eth3
[  +0.117284] 8021q: adding VLAN 0 to HW filter on device eth3
[  +0.078088] ixgbe 0000:04:00.1 eth3: detected SFP+: 6
[  +0.025039] bond10: (slave eth3): link status definitely down, disabling slave
[  +1.265688] ixgbe 0000:04:00.1 eth3: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[  +0.095304] bond10: (slave eth3): link status definitely up, 10000 Mbps full duplex
[Apr28 01:07] ixgbe 0000:04:00.1: removed PHC on eth3
[  +0.074791] bond10: (slave eth3): link status definitely down, disabling slave
[  +6.530662] ixgbe 0000:04:00.1: registered PHC device on eth3
[  +0.118271] 8021q: adding VLAN 0 to HW filter on device eth3
[  +0.015072] bond10: (slave eth3): link status definitely down, disabling slave
[  +0.070980] ixgbe 0000:04:00.1 eth3: detected SFP+: 6
[  +0.630446] ixgbe 0000:04:00.1 eth3: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[  +0.034583] bond10: (slave eth3): link status definitely up, 10000 Mbps full duplex
```

Since there is no "link remove/readd" at all (well, the virtual devices can be deleted, but not readded afterwards without full restart of `networkd`, see #23022) this effectively means one has to do all the housekeeping manually... (or remove and readd device using some brunt method, like `rmmod & modprobe` or `remove & rescan on PCI in /sys`).

**Comment by g0tar** [comment]
And before anyone asks - network setting are special in certain ways. Particullary, it's often required to change them gradually, interleaving the system with network equipment changes, just to keep connection to the (remote) system alive. Consider moving management VLAN between interfaces while adding LACP. During such transition restarting the `networkd` is not an option.

Of course noone has to use `networkctl` for such tasks, but what would be the point of implementing all the advanced features then?

@poettering - as for the overlayfs, I would expect the `systemd.volatile=overlay` cmdline wouldn't harm `systemd` logic. However I'm not sure, again, if that's even overlay related, just too many things happen here and at least a few seem to need some polishing before going deeper. I'm trying to use `networkd` for a few weeks and it bites... there's a monster hiding after many corners and paragraphs of documentation... Since I'm running out of time till my deadline I'll probably end up with another bunch of `sh` plumbing of deficiencies (#14915!). And this is getting hard and tricky due to the `systemd` constraints (#2741). Honestly I'm not even sure if this is convergent into `systemd`+`networkd` or if it eventually would throw such network setups out of the scope to the "good old times of s-**hell**".

**Comment by g0tar** [comment]
Oh, and just for the record, something that should be obvious: regardless the reload principle choosen, `touch /etc/systemd/network` shouldn't be the action trigger.

Either the files should be picked up from the disk when needed, and configuration applied based solely on their invocation-time content (what kind of requirement would be to "update directory mtime"? You could keep each file timestamp, but ...get over it, simply read them), or they should not be reloaded until explicitly requested.
