### ISSUE TITLE
Reference variables for nice level

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#23189]
We'd like to reference a variable for the nice levels:

```
[Service]
LimitNICE=${APP_MAX_PRIORITY}
Nice=${APP_PRIORITY}
```

Where `APP_MAX_PRIORITY` and `APP_PRIORITY` are both defined as `-20`, such as:

```
APP_MAX_PRIORITY=-20
APP_PRIORITY=-20
```

It appears that when interpreting configuration values that are expected to be numeric, variables are not parsed.

Our application can be launched from a service as well as from the command-line during development. We've been bitten in the past because our development shell scripts and service scripts were out-of-sync with respect to the application's nice level. Introducing a variable would ensure that the nice level is set at a single location in the system regardless of how the application is launched.

As a work-around, we've updated the systemd service file to use:

``` bash
[Service]
LimitNICE=-20
bash -c "nice -n ${APP_PRIORITY} ..."
```

However, this still leaves the `LimitNICE` value hard-coded and isn't immediately obvious why the `Nice` configuration option isn't set using a variable.

**Comment by poettering** [comment]
env vars are only expanding in ExecStart= and similar command lines.

I am very sure we should not turn unit files into a generic template language. we kind already do too much magic expansion than too little.

That said I'd be fine with adding a special value Nice=best or so, which will set the nice level to the best value possible according to the RLIMIT_NICE value configured for the unit. That would suffice, no?

**Comment by poettering** [comment]
Sorry, but we are not going to turn systemd units into a yet another templating language. We want that code can parse the unit files reasonably, without implementing m4 again.

In particular I think the indirection via an external file is certainly not helping simplicity, since you have to look at multiple places then in order to figure out what actually will happen.

If you want to use an external source to auto-configure stuff in units, then that's OK, we have the generator concept for that:

https://www.freedesktop.org/software/systemd/man/systemd.generator.html

You could easily write a generator that reads whatever source file you want to read and then generates abc.d/xyz.conf drop-ins that contain the Nice=/LimitNice= settings for your set of units. i.e. if you want a shell, use a shell, and plug it in via the generator interface. 

But we definitely shouldn' turn systemd into another shell or another templating language.

**Comment by DaveJarvis** [comment]
Using the generator looks like it may work, thank you.
