### ISSUE TITLE
resolve variables in place of the command in ExecStart/ExecStop statements 

### ISSUE THREAD

**Issue by twojstaryzdomu** [systemd/systemd#23235]
**systemd version the issue has been seen with**
 > 250.4

**Used distribution**
 > Debian

**Expected behaviour you didn't see**
 > Resolving variables in place of the command in Exec* constructs does not work. This precludes overriding the binary only via an environment variable in an environment file, rather than the entire Exec* entry in a drop-in, without over-the-top constructs with a shell involved.

**Unexpected behaviour you saw**
> Failure to start such a process, resulting with errors: "Failed at step EXEC spawning ${<VARIABLE_NAME>}: No such file or directory" or "code=exited, status=203/EXEC".

**Steps to reproduce the problem**
```
sudo tee /etc/systemd/system/test.service << EOF
[Service]
Environment=APP=/bin/true
ExecStart=\${APP}
EOF
cat /etc/systemd/system/test.service
sudo systemctl daemon-reload
sudo systemctl start test
sudo systemctl status test
ls -la /bin/true
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```
[Service]
Environment=APP=/bin/true
ExecStart=${APP}
× test.service
     Loaded: loaded (/etc/systemd/system/test.service; static)
     Active: failed (Result: exit-code) since Sat 1970-01-01 00:00:01 GMT; 591ms ago
    Process: 1000 ExecStart=${APP} (code=exited, status=203/EXEC)
   Main PID: 17955 (code=exited, status=203/EXEC)
        CPU: 10ms

Jan 1 00:00:01 hostname systemd[1000]: test.service: Failed at step EXEC spawning ${APP}: No such file or directory
Jan 1 00:00:01 hostname systemd[1]: Started test.service.
Jan 1 00:00:01 hostname systemd[1]: test.service: Main process exited, code=exited, status=203/EXEC
Jan 1 00:00:01 hostname systemd[1]: test.service: Failed with result 'exit-code'.
-rwxr-xr-x 1 root root 65536 Jan 1 1970 /bin/true
```

**Comment by g0tar** [comment]
This is not a templating engine, see #23189.

**Comment by g0tar** [comment]
Elaborating this a little bit, why I'm against such features. Imagine this is implemented - at first, you'll be happy using it. And then some mindless corpo devops guys will start providing units named `super-stuff@.service` containing everything possible via `%I`-based environment files. Such trend, when picked by various upstream projects, could trash every distro and end system very fast. Therefore no - just stop being lazy and do this the right way.

**Comment by twojstaryzdomu** [comment]
> This is not a templating engine, see #23189.

Variables are already allowed in ExecStart to some degree.

To quote one reply from the issue: "env vars are only expanding in ExecStart= and similar command lines."

Not quite. And worse still, this works:

sudo tee /etc/systemd/system/test.service << EOF
[Service]
Environment=APP=/bin/true
ExecStart=echo \${APP}
EOF

This design is terribly inconsistent, allowing allow variables anywhere but the binary name in the Exec* statements.

There is nothing really to justify WHY a variable cannot be used in place of the binary in the statement when the variables are permitted elsewhere.

Is there company politics behind locking users out from selecting the binary in Exec* statements via an environment variable?

**Comment by twojstaryzdomu** [comment]
> And then some mindless corpo devops guys will start providing units named `super-stuff@.service` containing everything possible via `%I`-based environment files.

Then why allow these variables in ExecStart altogether? What makes you think YOU yourself know better than the users?

And isn't this the exact opposite - a corpo resistance not to introduce a sensible idea?

> Therefore no - just stop being lazy and do this the right way.

Do you call everyone that does not subscribe to your idea behind an inconsistent design lazy? I call out this design on its stark inconsistency in its treatment of variables (binary = a no no, parameters = good) and going against sensible expectations when variables are introduced.

**Comment by g0tar** [comment]
Variables in `ExecStart=` were (*probably*) introduced to support old-style SysV habit to include configuration **parameters** from sourced `/etc/sysconfig/service` files for daemons that don't handle config files. This might seem inconsistent, but the keyword would be "compromise". I'd be glad seeing this removed entirely and all the software to support configuration files and directories (includes, drop-ins etc.) but this is not going to happen anytime soon.

And yes, I call lazy everyone who insist on not doing something properly. Instead of all the paragraphs you've written you should have simply read `man systemd.generator`.

If you even thing about doing some crazy shell wrappers to be executed instead... well, smells much Comarch-like; introducing poor solutions for badly addressed problems thus creating more and more bloat on each iteration.

PS. I'm not systemd sponsor or developer, so still there's a hope you'll convince someone in charge.

**Comment by twojstaryzdomu** [comment]
Speaking of compromise, calling someone's approach lazy is a sign of not allowing any other ways.

This thinking and design is a based on a false premise systemd's developers and sponsors know what is best for the user. How politically driven this is by corporate sponsors I can only speculate.

And exactly how widespread is the use of generators? 
Forcing a facility onto frustrated users when a simple problem could be done with a better design is not the way to promote the use of that facility.

Please do not call out company names, it's immature. There are plenty of projects and companies where shell execution will be put to use to work around these false "compromises". Bodges from systemd's standpoint are a fact of life. They're are inevitable due to the restrictions that severely limit users freedom and the most obvious ways of going about a problem. Listen to your users, rather than settle on false compromises and offer over-the-top solutions. I'm saying this from a production business (not Debian based this time) standpoint and on behalf of other users in a commercial Linux distro.
Your view about doing away with variables is likely a minority one among the actual users of the product. A developer does not always know best.

**Comment by g0tar** [comment]
You shouldn't be talking about mature attitude with such nickname, don't you think?

And it's not about what the users **want** (i.e. **how** they intend to approach), but what's the **problem** they encounter. Because, you know - users usually come with wrong solution; they lack the knowledge, they are lazy; when the only tool you know is a hammer (ENV)...

And the proper solution is the one you can provide without sacrificing or violating integrity, transparency, accordance with best practice or compliance with standards. Bloating units with too much environments breaks most of these rules, making units obscure and tedious to analyze and jeopardizing system security (sooner or later someone *would* invent "user units" by including `~someuser/my_super_service.env`).

Of cource you can easily prove me wrong - show the other tickets requesting similar feature, show the snippets of the generator-based approach and compare it with the code required to safely and reliably handle this in core or simply show the scenario that currently cannot be handled sanely.

**Comment by twojstaryzdomu** [comment]
> You shouldn't be talking about mature attitude with such nickname, don't you think?
Please refrain from making low 'ad personam' comments. Defaming or disclosing how companies go about their business can get you in trouble, I suppose you ought to know better as a developer right?

> Because, you know - users usually come with wrong solution; they lack the knowledge, they are lazy; when the only tool you know is a hammer (ENV)...

That is exactly the prevailing condescending attitude towards the user base that I'm against. 
Users in their infinite wisdom (by sheer numbers) will expect a more logical way but sadly be hampered by an arrogant design some developer came up with to satisfy his or his corporate sponsor's roadmap. I gave you an example of a common use case.

> Bloating units with too much environments breaks most of these rules [integrity, transparency, accordance with best practice or compliance with standards]

And what party decides what practices are best? You? Or rather the users?

Variables aren't bloat. I don't think you can arbitrarily (unless you look down upon users) decide which variables are bloat and which ones aren't. If a user needs variables for a particular use case, I don't see any reason why disallow variables for argument #1 but allow for #n > 1. 
Note I'm specifically focusing on Exec* statements, where variables are already partially available, not globally to set internal parameters, like #23189.

>  making units obscure and tedious to analyze and jeopardizing system security

Only UNIX illiterate users could fall for such arguments, knowing that variables are already partially permitted. 
Who decides what is obscure and what isn't? Exactly how tedious would it be to track one variable? And why a variable used to set the command (in gcc parlance argc = 0) renders a units obscure and tedious to analyse yet a variable in the same Exec* statement used as a parameter (argc > 0) does not? That isn't making any sense... Variables used to set both the command and its parameters that do not magically make anything obscure nor jeopardise anything.

It isn't a security problem. Security isn't managed by systemd but POSIX write privileges and file ownership. Unless there are plans to reinvent the wheel here again.

There are far more obscure things in systemd than variables.

**Comment by poettering** [comment]
Duplicate of #1274

**Comment by twojstaryzdomu** [comment]
#1274 has been pending for the last 7 years (since Sep 15, 2015). Apparently there are no incentives to address it, or this request is running against a corporate policy of a sponsor.
