### ISSUE TITLE
restructure services for utmp and wtmp update

### ISSUE THREAD

**Issue by jurekb** [systemd/systemd#2325]
I am a bit confused about this UTMP reference here (utmp and wtmp are different and located in different places):

```
$ cat /usr/lib/systemd/system/systemd-update-utmp.service
Description=Update UTMP about System Boot/Shutdown
...
RequiresMountsFor=/var/log/wtmp
...
```

There are actually two confusingly named services and their unit files defined for one log file only:

```
/usr/lib/systemd/system/systemd-update-utmp-runlevel.service
/usr/lib/systemd/system/systemd-update-utmp.service
```

There shoud be:

```
/usr/lib/systemd/system/systemd-update-wtmp-runlevel.service
/usr/lib/systemd/system/systemd-update-wtmp.service
```

with dedicated executable

```
/usr/lib/systemd/systemd-update-wtmp
```

and

```
/usr/lib/systemd/system/systemd-update-utmp.service
```

with dedicated executable

```
/usr/lib/systemd/systemd-update-utmp
```

The current (and future wtmp) unit file contains

```
RequiresMountsFor=/var/log/wtmp
```

which is described in systemd.unit(5) as

```
RequiresMountsFor=
```

Takes a space-separated list of absolute paths. Automatically adds
dependencies of type Requires= and After= for all mount units
required to access the specified path.

I am just wondering if similar in particular should apply to the new (future utmp) unit file as well

```
RequiresMountsFor=/var/run/utmp
```

because the type is configured as

```
$ cat /usr/lib/tmpfiles.d/systemd.conf
...
F! /run/utmp 0664 root utmp -
...
```

and described in tmpfiles.d(5) as
If the exclamation mark is used, this line is only safe of execute
during boot, and can break a running system. (...)
and

```
$ mount
...
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
...
```

and

```
$ ls -al /var/run
lrwxrwxrwx 1 root root 6 Sep 30 21:17 /var/run -> ../run
```

**Comment by poettering** [comment]
utmp and wtmp are closely related, they are always updated in sync, with the exact same data (except that one file is more a "log", and the other a UID-indexed database) It makes no sense to update them in separate, asynchronous programs.

utmp is generally how the concept is called, and this is reflected for example in the fact that the man page for it is called utmp(5), and only mentions wtmp briefly in one paragraph. Generally, either both wtmp and utmp are used, or none, or utmp without wtmp, but never wtmp alone. As such we call the concept "utmp", as the wtmp stuff is pretty much auxiliary to it.

Also, we never reference files in /var/run, as that's just a legacy name for /run. On systemd systems /run is considered an "API fs", i.e. is mounted implicitly during earliest boot, and is such not subject to the usual mount unit logic, it's just "always there". That's why we have no explicit dependencies on that path.

Hence, I am pretty sure things are pretty much exactly already the way they should be. Closing.
