### ISSUE TITLE
boot: Require password for certain menu entries

### ISSUE THREAD

**Issue by benthetechguy** [systemd/systemd#23280]
**Is your feature request related to a problem? Please describe.**
I have a modified version of the Arch Linux ISO on my EFI system partition to have a good environment ready to boot to in case I need to fix something. It has proved very useful. However, this conflicts with my system's security.
I have secured my system with Secure Boot and FDE so that the computer will boot no operating system without my consent (sbsigned unified kernel image + encryption password). Having the archiso available compromises that, providing an operating system with root access, so I would like to require a password to boot that entry.

**Describe the solution you'd like**
Simply add an entry config option to require a password to boot that entry. It would be similar to the functionality SYSLINUX has, where you can add to an entry `MENU PASSWD` with either a plaintext or hashed password. There's also the global `MENU MASTER PASSWD`, which is required to edit menu entries. This could be implemented as an analogous option in loader.conf.

**Describe alternatives you've considered**
There are not any other solutions I could think of, other than just removing the archiso entirely.

**The systemd version you checked that didn't have the feature you are asking for**
Yes

**Comment by medhefgo** [comment]
I fail to see how that improves security. Either your data is safe thanks to full disk encryption or not. And with secure boot enabled, the rescue environment should not be able to temper with the integrity of the regular boot path without it breaking the signature of it.

Or are you saying the encryption password is stored *inside* the unified image? Then you've already tossed security out of the window.

You would also have to design this so that an attack cannot just remove the password requirement, which requires even more work for questionable gain. So I am loath to the idea of a password feature.

You're better off baking this requirement into the booted entry itself (as part of the initrd).

**Comment by poettering** [comment]
I would agree with @medhefgo. When implementing a password prompt, it automatically raises the question where to store the password in a temperproof way. i.e. storing it in hashed or plaintext in the ESP is useless, because attackers can just override it there, and poof your protection is gone.

I think there are only two other ways: make the fde password the important one: i.e. encrypt your data with a key derived from the password, so tha the data definitely isn't accessible without the password. Or alternatively, bind it to the TPM2 somehow, ensuring boot cannot complete if password and state of TPM don't match up. 

But both of these cases mean sd-boot is not the place to implement it, but the initrd, because TPM communication from sd-boot kinda sucks (we currently have no infra for that, besides the UEFI TPM apis themselves, which can't really do anything besides measurement)

In your specific case it appears to me, you should modify your archlinux ISO to also be encrypted with a key derived from the entered pw.

But other than that, I am pretty sure we should not add fake security concepts, that are easily overriden by an attacker...
