### ISSUE TITLE
journalctl: make output of hostname optional

### ISSUE THREAD

**Issue by chkr-private** [systemd/systemd#2342]
Currently, when using either the default or any other "-o" option for a human-readable output, there is no way to suppress the output of the hostname/FQDN:

<pre>...
Jan 17 10:44:43 myhost.mylocalnetwork.example systemd[1411]: Reached target Basic System.
Jan 17 10:44:43 myhost.mylocalnetwork.example systemd[1411]: Starting Basic System
...</pre>

The full output of the complete hostname make the lines unnecessarily long and doesn't provide any useful additional information (for a purely local setup).

Having an option to turn off the display of the FQDN would be helpful for increasing the readability of the output.

Looking at the current command line options I'm unsure what would be the best way to achieve that:
- just adding a new "short-nohost" output modifier
- allowing multiple modifiers for "--output"
- adding a new option

Please let me know if there would be any preference and I'll try to implement it.

**Comment by poettering** [comment]
Hmm, I can see the usecase, but I wonder if we shouldn't find a different way to expose this, rather than adding even more output modes. Maybe we could add a logic of allowing the caller to override the hostname via an env var, including overriding it to the empty string.

One option could be to say that if "$HOSTNAME" is set, then this will override the hostname field of all log lines that have the hostname set to the current value of gethostname()... Then, to suppress the hostname output you could invoke `HOSTNAME= journalctl` or so...

**Comment by chkr-private** [comment]
Yes, that would certainly be an option which could be easily implemented. But I see the following disadvantages:
- assuming I'd like to have this behaviour as default, then I could either set HOSTNAME in my .bash_profile with unpredictable side-effects to other processes or I would have to create an alias
- the concept is not very intuitive, even with a description like "$HOSTENV: Overrides the hostname in the output if the entry's hostname is the current hostname."

What about the using a different environment variable?
`JOURNALCTL_OVR_HOST= journalctl`

This would have the advantage of having zero risk when setting the variable globally and at least solve the first issue.

Personally, I would probably follow a completely different approach by making the most common use case the default:
- show only local logs and omit the hostname
- show only the logs from the last boot

Most people I know are using journalctl always with "-b" and checking only the local logs. ;-)

If any of the described options would be acceptable, please let me know.

**Comment by poettering** [comment]
Well, it's unlikely we are going to alter the default output. We try hard to make sure the log lines look exactly how they did in old syslog days. /var/log/messages on syslog does contain the hostname.

**Comment by keszybz** [comment]
Why not add a switch to `journactl`? One can always define a shell alias.
An environment variable is too much magic, and it appear to be at the wrong level (can leak into scripts, etc).

**Comment by johannbg** [comment]
Yup a switch ( -m )  to journal that only outputs the MESSAGE=  field should handle the usescase where time/date and hostname are irrelevant to the administrator

**Comment by poettering** [comment]
@keszybz I am a bit conservative on inflating the journalctl interface with even more switches, in particular if they are rather exotic, which I think this one is...

**Comment by johannbg** [comment]
@poettering having an switch that output just the message field is nothing exotic and quite useful in many ( administrator ) cases  however dropping either the timestamp or the hostname field arguably are rather exotic/weird use case.

**Comment by poettering** [comment]
@johannbg there already is -o cat if you only want to see the message. But this not about that really

**Comment by keszybz** [comment]
I don't think this is particularly exotic. It's has come up a few times before... And there's a good reason: for single-host journal logs, i.e. for a great majority of users, the hostname is constant ant completely boring. If you happen to have a long name, then it's noticable.

Part of the problem is people using the fqdn as hostname...

**Comment by poettering** [comment]
OK, then let's add a cmdline option --suppress-hostname that suppresses the hostname in the output if the machine id of an entry matches the local machine id.

**Comment by mleise** [comment]
I just found this old issue after posting a screenshot of a custom service output. Just wanted to let you know that I was looking for the exact same switch (that's still missing from zsh-completion) have more narrow and relevant (to others) information. So thanks for adding it 3 years ago.

**Comment by andreyvit** [comment]
I know this is a very old ticket, and you'll probably lock it due to spam after this, but OH MY GOD THANK YOU. Was so fed up with hostnames, and no combination of -o and --output-fields was helping. Somehow, ChatGPT does not know about this option either. So stoked  to discover it by accident! (Of course, it's right there in the man page, but somehow it never occurred to me to look for a separate flag.)
