### ISSUE TITLE
Systemd journal daemon doesn't honour MaxRetentionSec option

### ISSUE THREAD

**Issue by plomari** [systemd/systemd#23461]
**systemd version the issue has been seen with**
 > 250.4-1

**Used distribution**
 > Debian

**Linux kernel version used** (`uname -a`)

 > `5.10`

**CPU architecture issue was seen on**
 > x86

**Expected behaviour you didn't see**
 > journalctl doesn't show entries older than MaxRetentionSec in /etc/systemd/journald.conf after "systemctl restart systemd-journald", I tried "MaxRetentionSec=6day" in the "[Journal]" section

**Unexpected behaviour you saw**
 > journalctl shows entries that are at least a week before the date MaxRetentionSec before

**Steps to reproduce the problem**
 > see above

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by poettering** [comment]
Are they removed once you request rotation? `i.e. journalctl --rotate`?

The thing is: journal files are removed due to retention only when archived. Thus if you keep them open all the time, the retention stuff doesn't get active.

We should probably document that. And maybe close files once we notice that the oldest entries they contain are before the retention cutoff.

**Comment by plomari** [comment]
I think this works now, currently I'm on 252. I don't know exactly what caused the change.
