### ISSUE TITLE
fuzz: also run fuzzers on 32bit arch

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#23532]
To detect issues like that found in #23486 and #23526.

From https://github.com/systemd/systemd/pull/23526#issuecomment-1139167655
> FWIW OSS-Fuzz supports "i386" with `-m32` and 32-bit packages: https://google.github.io/oss-fuzz/getting-started/new-project-guide/#architectures but for that to work the systemd dependencies would have to be linked statically (because the runtime environment is still 64 bit and doesn't include the packages available in the build environment).

cc @evverx and @mrc0mmand.

**Comment by evverx** [comment]
I think I was told many times that `systemd` wouldn't support static dependencies because it would make the "dlopen" stuff complicated so I don't even try anymore :-) It was about issues like https://github.com/systemd/systemd/issues/11018 and MSan though as far as I can remember. Maybe fuzzing on i386 would be more successful in terms of bringing static dependencies :-)
