### ISSUE TITLE
 BTRFS_IOC_QUOTA_RESCAN_WAIT

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#2374]
With PR #1641  BTRFS_IOC_QUOTA_RESCAN_WAIT was introduced to the code. 

```
 +int btrfs_quota_scan_wait(int fd) {
-        return qgroup_create_or_destroy(fd, true, level, id);
+        assert(fd >= 0);
+
+        if (ioctl(fd, BTRFS_IOC_QUOTA_RESCAN_WAIT) < 0)   <-- o_O 
+                return -errno;
+
+        return 0;
```

AFAIK BTRFS_IOC_QUOTA_RESCAN_WAIT is unsupported BTRFS feature hence I have to ask any particular reason for that and should it not be dropped until it gets officially supported?

**Comment by johannbg** [comment]
Should be just a simple matter of removing that if statement with that unsupported btrfs stuff and reduce it to this ( unless of course there's some spectacular reason that this is in there in the first place )

```
int btrfs_quota_scan_wait(int fd) {
         assert(fd >= 0);
         return 0;
 }
```

**Comment by poettering** [comment]
What makes you think that this btrfs ioctl was supported worse than any other btrfs ioctl?

The thing is, quota operations fail while a quota scan is ongoing, with EBUSY. When we see that we hence try to wait for any ongoing quota scan to finish with the ioctl. We do this at max 10 times though, which is when we give up, and we do ignore he return code of the ioctl anyway.

Hence I think we are doing the right thing, and even if the ioctl disappears one day, we should be fine, since it will return ENOSYS then, which we ignore, and all is good. And the wait loop is bounded, hence we'll not hang forever. 

By all I can see we are doing the right thing here...

**Comment by johannbg** [comment]
What makes me think this btrfs ioctl was supported worse than any other btrfs ioctl is because I have seen pattern forming where wide variety of embedded distribution carrying systemd patches removing this spesific part amongst other things all qouting "unsupported" and upstream btrfs seems to prefer just polling the RESCAN_STATUS value since the key information is provided and accessible.

**Comment by johannbg** [comment]
Here's an example from one of the more popular one. ( there are arguably two other patches there that should be fixed here ) 
1. https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/sysutils/systemd/patches/systemd-09_dont_support_btrfs.patch

**Comment by poettering** [comment]
Well, that patch carries no explanation, and I am not sure what brings him to the idea that this specifically is not supposed to be used...

**Comment by johannbg** [comment]
If you have it on good ( btrfs ) authority that you are doing it right then those embedded distro's will just keep carrying that patch for whatever reason or ( mis)belief they do but if not then this should be fixed where it belong which would be here.

**Comment by stefansaraev** [comment]
this patch was a quick hack to make systemd compile on one of OpenELEC supported projects (wetek), that uses old kernel (3.10 from amlogic). BTRFS_IOC_QUOTA_RESCAN_WAIT is missing in that "ancient" kernel. and no, upgrading it is not an option

we never cared about btrfs, and we will probably never do.

I could add it to missing.h and send a PR if you'd like me to.
