### ISSUE TITLE
Strange behaviour in systemd-nspawn container

### ISSUE THREAD

**Issue by jam3st** [systemd/systemd#23758]
For over a year with systemd 240+

Basically this is about a possible race condition described in https://bugs.gentoo.org/850901 

It appears that a file isn't visible on an ext4 or tmpfs filesystem immediately after it is created in the container. This happens when "emerging" glibc usually. Running strace on this isn't really practical.

**Comment by yuwata** [comment]
Could you provide minimum reproducer?

**Comment by jam3st** [comment]
Can you provide a minimum systemd?

**Comment by yuwata** [comment]
Huh? Is it a joke?

You use several --bind and --tmpfs. Which affects the issue? If you think it is caused by nspawn, then please try to spawn a container with single --bind or --tmpfs, and try to create several files and check the existences of them.

Also, please provide the mount options of backed filesystem, e.g. `cat /proc/1/mountinfo` on the host (not in the container).
