### ISSUE TITLE
RFE: nspawn: add native options to create extra devices

### ISSUE THREAD

**Issue by srd424** [systemd/systemd#23831]
### Component

systemd-nspawn

### Is your feature request related to a problem? Please describe

It seems to be getting much harder to add extra device nodes into a container (https://github.com/systemd/systemd/issues/21987), definitely not helped by the user namespace code change in the kernel that diallowed mknod regardless of capabilities and cgroups settings (see links from https://github.com/systemd/systemd/pull/9483#issuecomment-449602341)

### Describe the solution you'd like

When looking through the code I notice we now already have support for adding configurable extra nodes to the container:
https://github.com/systemd/systemd/blob/05ab439a62de8bb47e4137d2a8a473a307ccfb33/src/nspawn/nspawn.c#L2299
This seems to be to support the OCI compatibility stuff - it would be great if it could be plumbed in to a `.nspawn` file option as well?

In the bigger picture, making sure the native nspawn settings mechanisms support a superset of OCI options might allow at least some of the OCI support code to be implemented as a translator/generator that emitted a native configuration (or the other way around, but I'm not personally a huge JSON fan..)

### Describe alternatives you've considered

My latest hack is to programmatically generate a directory outside the container with the extra device nodes I want, bind mount it to `/.dev` in the container, and then run a service in early boot which does `find /.dev -type b,c -print0 | xargs  -0 ln -v -f -s -t /dev`, but it all seems rather ugly!

### The systemd version you checked that didn't have the feature you are asking for

250 (also checked latest git nspawn source)

**Comment by poettering** [comment]
device nodes are not virtualized by the Linux kernel. Blanket supporting passing them through is not really a good idea, since /dev/ and /sys/ need to match up, and there's no support for that in the kernel.

So what are you actually trying to do here?

**Comment by srd424** [comment]
Well, for one example, I use a binary-only tool which talks to a USB zigbee adapter (simple serial interface.) Partly because it has some weird dependencies, and partly because I don't like running binary-only code on the host system, I have it containerized. It's quite happy with just the device node being available.

I appreciate there are various pitfalls, but presumably they apply to OCI containers too? It just seems a shame given the plumbing seems to be already there not to expose it. The man page could document the problems with actually using the option..

**Comment by poettering** [comment]
Why doesn't --bind= mounting the device node work? If the tool is so minimal that it only wants one specific device node (and no matching sysfs stuff), then --bind= should suffice, no?

**Comment by poettering** [comment]
OCI is terrible model, they just expose 1:1 kernel behaviour regardless if it actually makes sense or not. We only support this for compat, not because it was a good idea.

**Comment by kpfleming** [comment]
As noted in #21987, bind-mounting the existing device nodes doesn't work if the container is making use of any `PrivateUsers` mode, because the owner/group on the existing device node aren't in the container's user namespace. This results in the device nodes inside the container being owned by 'nobody:nogroup'. I had been using bind-mounting (in my case for /dev/sr0 and /dev/sg5 for an optical disk drive) without any issues, until I fixed my configuration to make use of PrivateUsers.

If the container was running udev it would probably be possible to inject a synthetic event to cause udev to create the device node, but at least in my case udev is not in use (Debian Bullseye in the container).

As a hack on my system, since I know which UID/GID range the container is using and it's stable, I will create a couple of device nodes on the host, setting their owner/group appropriately, and then bind-mount those into the container's /dev. I think that will work.
