### ISSUE TITLE
sd_bool should be added back

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#23908]
### systemd version the issue has been seen with

git main

### Used distribution

Fedora 36

### Linux kernel version used

-

### Expected behaviour you didn't see

sd_bool exists

### Unexpected behaviour you saw

sd_bool is gone

### Steps to reproduce the problem

We should revert 6b852d22b621ef37ef67a3b24ca1f075e0b78698

The thing is that UEFI's `BOOLEAN` type is defined as `unsigned char`, i.e. takes up one byte in memory, and distinguishes 256 values. But C99 `bool` is quite different, it takes up 4 bytes on gnu/x86-64 and knows just 0/false and 1/true. 

THis has effects all over the place. i.e.

1. stuff will be laid out in memory quite differently, which matters for structs and such.

2. `bool x = 5, y = 4; assert(x == y);` must hold, but doesn't if we use UEFI `BOOLEAN` instead.

3. `void *p = NULL; bool x = p;` is not a type problem on C99 bool, but is if UEFI `BOOLEAN` is used.

and so on.

The reason sd_bool existed is to make clear to the programmer that what they are dealing with here is weird, and certainly conceptually a boolean, but might be defined quite differently depending on the context. 

/cc @medhefgo

**Comment by medhefgo** [comment]
> The thing is that UEFI's `BOOLEAN` type is defined as `unsigned char`, i.e. takes up one byte in memory, and distinguishes 256 values. But C99 `bool` is quite different, it takes up 4 bytes on gnu/x86-64 and knows just 0/false and 1/true.

Actually, it doesn't. The UEFI spec literally makes anything other than 0/1 undefined behavior. Also, compiler explorer tells me that `sizeof(_Bool) == sizeof(unsigned char)` (for the EFI arches at least?).

The idea is that we use bool internally and BOOLEAN when interfacing with EFI APIs. sd_bool in particular was only used internally and we can therefore use whatever type we wanted (like, a custom enum even). There is really nothing inherently special about uses of sd_bool here that warrants this complexity.

The idea is/will be that I still intend to use BOOLEAN when redefining the EFI APIs and structs to be on the safe side. But really, even that isn't really necessary.

> * stuff will be laid out in memory quite differently, which matters for structs and such.

Since sizeof(bool) is 1, it doesn't?

> * `bool x = 5, y = 4; assert(x == y);` must hold, but doesn't if we use UEFI `BOOLEAN` instead.

If you use BOOLEAN you invoke undefined behavior according to the UEFI spec.

> * `void *p = NULL; bool x = p;` is not a type problem on C99 bool, but is if UEFI `BOOLEAN` is used.

Again, technically, undefined behavior according to UEFI spec.

> The reason sd_bool existed is to make clear to the programmer that what they are dealing with here is weird, and certainly conceptually a boolean, but might be defined quite differently depending on the context.

But we want to use bool for these and we don't want to map these to BOOLEAN when we can just use bool. Doing that is/was a silly idea in the first place as the standard C types are perfectly fine to use in UEFI code. It only ever matters when *interfacing* with EFI APIs (and sd_bool wasn't used for that). But there, bool gets nicely cast to BOOLEAN without any problems for copy-by-value or you should be using BOOLEAN when passing a pointer to bool. Same for functions that return BOOLEAN: they get cast to bool transparently on assign without any issue.

**Comment by keszybz** [comment]
Yeah. I'm not sure what problem is `sd_bool` was trying to solve. If we use `bool` internally, things should "just work". 
Based on the examples posted in the report, it seems as introducing BOOLEAN (i.e. `sd_bool`) could actually create new bugs, not solve them.

> > * stuff will be laid out in memory quite differently, which matters for structs and such.
> 
> Since sizeof(bool) is 1, it doesn't?

We don't rely on layout of structures, at least not structures with `bool` and other types which could have implementation-defined widths. So the compiler can make it 1 byte, or 4 bytes, or whatever, and it's all fine.

**Comment by medhefgo** [comment]
> We don't rely on layout of structures, at least not structures with `bool` and other types which could have implementation-defined widths. So the compiler can make it 1 byte, or 4 bytes, or whatever, and it's all fine.

Well, right now we don't have any cases where we rely on this anyways. And I intend to use a properly defined BOOLEAN for efi.h too.

**Comment by poettering** [comment]
ok, i guess it is fine to use bool internally, and BOOLEAN for the stuff facing outside then.
