### ISSUE TITLE
hostnamectl should be independent of running systemd as init system (PID 1)

### ISSUE THREAD

**Issue by empjustine** [systemd/systemd#23917]
### Component

hostnamectl, systemd-hostnamed

### Is your feature request related to a problem? Please describe

Systemd is supposed to be a comprehensive composition of independent modules. Said modules are often distributed in environments where running systemd as PID 1 is neither possible or desirable.

`hostnamectl` seems to depend on `systemd-hostnamed` and on the dbus binding `org.freedesktop.hostname1`, but the error message `System has not been booted with systemd as init system (PID 1). Can't operate.` implies that it depends on `org.freedesktop.systemd1` or `/usr/lib/systemd/systemd`, and that should not be strictly true, or prevent everything from working.

### Describe the solution you'd like

Being able to use `hostnamectl` (and other command line interface commands) without systemd as PID 1.

A message with possible alternatives to run `hostnamectl` and `systemd-hostnamed` without systemd as PID 1.

### Describe alternatives you've considered

Write a more descriptive error message, with the actual interfaces required, instead of a generic "can't work, won't try" message.

Stop compiling and distributing `hostnamectl`, `systemd-hostnamed` and `/usr/lib/systemd/systemd` as a separate binaries if they can't work without each other at all; Bundling everything as a multi-call binary, like busybox/toybox, to enforce the actual monolithic nature of the solution, and to prevent said modules from being split.

### The systemd version you checked that didn't have the feature you are asking for

250

**Comment by bluca** [comment]
@empjustine note that the check is failing simply because there's no `/run/systemd/system/`, nothing else. So if you want to hack it you know what to do... of course it's an unsupported setup, and the existence of that directory is the canonical check to see if a system was booted by systemd, and if you hack around that you get to keep the pieces if it falls apart.

**Comment by empjustine** [comment]
> I am sorry, but why?
> 
> You can use /usr/bin/hostname if you want the set the hostname without systemd.

Aren't `hostnamectl` and `systemd-hostnamed` the supposed ways to manage `/etc/machine-info`? hostname doesn't handle that because it's supposed to be systemd-specific.

> We build systemd, and the burden to maintain things for niche service managements that do not provide the same level of execution context management is just too much.

So you should rename `hostnamectl` to `systemd-hostnamectl`, as it is useless without systemd?

**Comment by poettering** [comment]
> @poettering that said, maybe we could relax the check in `bus_connect_transport()` down to a warning? We need a hard error for `bus_connect_transport_systemd()` of course, as that expects to connect to actually pid1, but the former just wants to talk to something on D-Bus.

Note necessarily. The latter you can use when you *only* want to talk to systemd, the former works if you want to talk to more than just systemd, i.e. polkit, logind and so on. 

The various tools we have typically want to talk to systemd, so i think the check should stay. It creates more confusion than helps anyone, since if you drop it you'll just get some cryptic warning about "org.freedesktop.systemd1" not being on the bus. i'd rather have a helpful error message that explains what is going on clearly, than support frankenstein systems that want to use something we explicitly do not support.

This is free software, so people can take it and turn it into whatever they want, but I am not convinced we need to support tha tupstream. If @empjustine doesn't want to use some other init system with our stuff, good, but then they should patch this out locally.

> Aren't `hostnamectl` and `systemd-hostnamed` the supposed ways to manage `/etc/machine-info`? hostname doesn't handle that because it's supposed to be systemd-specific.

/etc/machine-info is a systemd thing. Not sure why you'd bother with that elsewhere.

> So you should rename `hostnamectl` to `systemd-hostnamectl`, as it is useless without systemd?

This is not what the `systemd-` prefix is about.
