### ISSUE TITLE
nss-resolve returns an IPv6 address even when IPv6 is disabled

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#23951]
### systemd version the issue has been seen with

251

### Used distribution

Fedora 36

### Expected behaviour you didn't see

nss-resolve should return an IPv4 address when `net.ipv6.conf.all.disable_ipv6=1`.

### Unexpected behaviour you saw

nss-resolve return an IPv6 address with `net.ipv6.conf.all.disable_ipv6=1`

### Steps to reproduce the problem

```
# cat /etc/hosts
10.0.0.1               ns1.unsigned.test
fd00:dead:beef:cafe::1 ns1.unsigned.test
# sysctl -w net.ipv6.conf.all.disable_ipv6=0
net.ipv6.conf.all.disable_ipv6 = 0
# getent -s resolve hosts ns1.unsigned.test
fd00:dead:beef:cafe::1 ns1.unsigned.test

# sysctl -w net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6 = 1
# getent -s resolve hosts ns1.unsigned.test
fd00:dead:beef:cafe::1 ns1.unsigned.test
```

**Comment by pemensik** [comment]
I think resolved should still deliver IPv6 address if requested explicitly by ``-t AAAA``. It might just not start AAAA queries when requested by *getaddrinfo* call with *AF_UNSPEC*.

**Comment by flokli** [comment]
This works as intended - see https://github.com/systemd/systemd/pull/14125 for the rationale.

It's up to clients (implementing RFC6724) to determine how to reach a given destination, whether to consider the v6 records returned or not. The resolver trying to be smart about it is almost always wrong.

**Comment by flokli** [comment]
You have a point. I'd still err on the side of caution.

resolved can speak UDP on port 53, and DNS lookups popping up there might come from systems with IPv6 enabled in the kernel (think about local (firecracker) VMs, which bring their own kernel).

Sure, it's highly unlikely that such a VM then has v6 connectivity over a L2, while IPv6 is explicitly disabled in the host kernel, but still…

--

It feels like adding this complexity in resolved doesn't gain us a lot, except saving some DNS requests that are usually cached anyways.

I'd rather have some `SkipAAAAOnAFUnspec=` config knob in `resolved.conf` that sysadmins can set to `yes` if they really care. I'd argue most browsers etc. doing happy eyeballs do explicit requests anyways.

Disabling IPv4 kernel-wide is not really a thing anyways unfortunately, so we don't really need a knob for that.

**Comment by pemensik** [comment]
Yes, but what RR type was queried on port 53, that type should be asked on forwarder. There is no AF_UNSPEC equivalent  on unicast DNS. QType *ANY* does not have well-defined behaviour on unicast DNS, unlike MDNS. It cannot be used to obtain both A and AAAA request reliably. systemd-resolved is failing to be good recursive cache in several way, but this is already implemented well and *must not* be modified. If I do ``dig -t AAAA example.net``, then I must receive IPv6 answer if there is any.

Depends if we speak about VM, which has a kernel of its own. Then it has own setting of IPv6 disablement and should act appropriately. Containers sharing kernel with the host should have this setting shared with host I think. Sure, this autodetection may save few CPU bytes and network traffic. I would say it has low severity and is only nice to have feature.

``SkipAAAAOnAFUnspec`` may help even on hosts just missing IPv6 route, but otherwise having local IPv6 connectivity working. If that is implemented, I think it still should default to yes if ``net.ipv6.conf.all.disable_ipv6=1``. I would prefer ``ResolveIPv6OnUnspec=no`` variable name instead. If that is implemented, I think ``ResolveIPv4OnUnspec`` should be provided too.

**Comment by fuzzy7k** [comment]
I agree with pemensik, I have been searching for a way to turn off IPv6 responses to clients and gather that there is currently no way to do that. 

See NM bug,  https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1098
A couple of relevant issues here, in the case that the wwan connection provides no data, or metered data and resolved returns a AAAA record first, but the wlan connection only has routing for IPv4. 
a) No Data, the client app tries to connect to the resource and routing is "successful", only it routes to a bit bucket.
b) Metered Data, since route metrics are not shared between IPv4/6, if the IPv6 address is tried first, it will be used no matter how much of a penalty the metered connection may have. 

My hope was to patch NM to configure resolved correctly, in such a case that IPv6 is disabled in the manager. However, I would expect to be able to do that via resolvectl first.  

As far as whether or not to initiate a AAAA query if IPv6 is disabled is a legitimate question. According to bug https://github.com/systemd/systemd/issues/19003, it matters if resolved is being used as a caching server that is serving clients with access to other networks. However, not all use cases are created equal and if we are on a mobile, saving CPU cycles and metered bandwidth from an extra query count. 

It would be nice to have these features tunable so that a connection manager can set  this up correctly depending on the use case or network configuration.

**Comment by pemensik** [comment]
There is a new not-yet documented option no-aaaa for resolv.conf, available since recent glibc. It seems to be backported even to RHEL 9. Check [rhbz#2096191](https://bugzilla.redhat.com/show_bug.cgi?id=2096191). I have requested something similar in [rhbz#2182745](https://bugzilla.redhat.com/show_bug.cgi?id=2182745), which should have something similar for IPv4 too. Implementing something similar on side of systemd-resolved would make sense too. As a daemon it can monitor availability of IPv6 connectivity much better than common userspace application.

**Comment by pemensik** [comment]
I think the correct expectation would be to query AAAA records only if there were *at least one* not link-local route on *whole* system, excluding always present loopback addresses. Not related just to interface the server is received from, but on any other addresses. DNS server over IPv4 only VPN can provide me address to limited IPv6 connection on another interface. Similarly there is no reason to query A records on ipv6-only networks, if I have only 127.0.0.0/8 ipv4 route.

**Comment by yuwata** [comment]
See https://github.com/systemd/systemd/pull/28136#issuecomment-1607234163.
