### ISSUE TITLE
Out of memory error from systemd-sysv-generator

### ISSUE THREAD

**Issue by donagrejja** [systemd/systemd#23976]
When I do "systemctl daemon-reload" I get these lines in my logs:
systemd[1]: Reloading.
systemd-sysv-generator[]: Out of memory.
systemd-sysv-generator[]: Out of memory.

But I can't really figure out where it's coming from or why.
This issue has been with me on several of my Debian servers since I upgraded from 10 to 11.
But it's not there on a fresh install.

Is there any way that I can debug/trace what's happening when these errors appear to get a more detailed log output on what's actually failing ?

I doubt this is a bug. It's just a help request.

Thanks =)

-- systemd --version
systemd 247 (247.3-7)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

-- uname -a
Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

-- lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

-- free -h
               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       566Mi       124Mi       155Mi       3.2Gi       2.9Gi
Swap:          2.0Gi        73Mi       1.9Gi

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
