### ISSUE TITLE
systemd-sysusers seems to leak its /etc/.pwd.lock lockfile

### ISSUE THREAD

**Issue by lucab** [systemd/systemd#23977]
### systemd version the issue has been seen with

systemd-250.7-1.fc36.aarch64

### Used distribution

Fedora 36

### Linux kernel version used

5.18.7-200.fc36.aarch64

### CPU architectures issue was seen on

aarch64

### Component

systemd-sysusers

### Unexpected behaviour you saw

systemd-sysusers seems to be leaving behind a `/etc/.pwd.lock` file, which is used for locking the users/groups databases.

### Steps to reproduce the problem

Simple reproducer:
```
$ mkdir -p etc/sysusers.d
$ echo 'u testuser -' > etc/sysusers.d/testuser.conf
$ systemd-sysusers --root .
Creating group 'testuser' with GID 999.
Creating user 'testuser' (n/a) with UID 999 and GID 999.
$ ls -la etc/.pwd.lock 
-rw-------. 1 core core 0 Jul 11 14:12 etc/.pwd.lock
```

### Additional program output to the terminal or log subsystem illustrating the issue

I'm unsure if this is a bug or if the missing unlocking step is somehow on purpose.

I can see the code here that does the `/etc/.pwd.lock` locking dance, but beyond that there is no trace/intent of unlocking:
https://github.com/systemd/systemd/blob/d5548eb618d426a3952746eb3a0e7d95d186ea7e/src/sysusers/sysusers.c#L2119

It looks like the locking logic was already that way in @poettering's original `sysusers` commit at https://github.com/systemd/systemd/commit/1b99214789101976d6bbf75c351279584b071998.

**Comment by poettering** [comment]
this is the lock file that libc's lckpwdf() function uses. And if you look at glibc's implementation of ulckpwdf() then you'll see they don't remove the file either after use.

The simple fact is that lock files cannot safely be removed because there is not concept of an atomic "unlink if noone uses it" on Unix. That means, if you remove it after unlocking, then someone else might already have opened the inode, waits to acquire the lock only to then end up with a lock on a lock file that has already been removed...

We never unlock the file explicitly, because we take a per-fd lock, hence closing the fd will automatically unlock the fd.

Anyway, this all works the way it should, and the interface is not defined by us anyway, we just reimplement it slightly different from glibc (in ways that don't matter here, i.e. we do not allow use of alarm() in our codebase, and we want a per-fd instead of per-process lock).

hence closing.

**Comment by lucab** [comment]
> he simple fact is that lock files cannot safely be removed because there is not concept of an atomic "unlink if noone uses it" on Unix.

Ah that was the conceptual bit I was missing, thanks for the explanation and sorry for the noise.
