### ISSUE TITLE
nspawn: kernel: overlayfs UID shifts

### ISSUE THREAD

**Issue by tixxdz** [systemd/systemd#2404]
Hi,

cc @zonque @poettering @dvdhrm @dongsupark @alban 
### Overview

This is just a PoC about UID shifting at the kernel level, before going further I'm posting here to see what you think. Thank you for your comments.

To sum it up we want processes inside and outside containers to have their own "struct user" of the kernel. This will avoid cases where they share the same resources and the same capabilities and so on...

A solution would be to use user namespaces. However at the current state user namespaces at the filesystem level do not work well, inodes will likely end up with the wrong mapping of `UIDs` and `GIDs`.

A solution would be to do a recursive chown() for all files, a better one will be to do it automatically at the kernel level each time inodes are accessed as noted by @dvdhrm here: https://github.com/coreos/rkt/issues/1057

The presented solution here uses overlayfs. With overlayfs we have two layers, the lower one which will always be read-only and the upper one.

The solution only takes into account cases where the shifting is set by a real privileged user. So the shift has to be specified outside the user namespace which seems the best way since overlayfs can't be mounted inside user namespaces for security reasons.

Overlayfs mount point will take the `"shift_uids"` and `"shift_gids"` flags and will use the user namespace rules of the containing mount namespace. This part is basically inside VFS so the shift functions are part of the VFS in case something pops up later, overlayfs just uses them.

Using the user namespace of the containing mount namespace makes sure that we follow the rules of the current mount namespace and that only a process with the same privileges or an ancestor can change the mappings of the user namespace.

When we do a first read operation it will be fetched from the lower layer, at that time we check if the returned `UIDs` and `GIDs` to userspace of inodes should be shifted or not. So for read operations on the lower layer `inode->{i_uid|i_gid}` will never change we just do our mapping afterwards in order to present to userspace.

For writing, inodes are first copied up to the upper layer, we do the shifting at that time. During each copy up operation we check if the `UID` and `GID` of the inode should be shifted if so then the `inode->{i_uid|i_gid}` are remapped according to user namespace rules of the containing mount namespace. In other words, for every copy up operation we remap the `UID` and `GID` that are presented to userspace, we make new global `kuid` and `kgid` from these `UID` and `GID` according to the mappings of the user namespace and use them to write inodes on disk. The upper layer should always contain the global `kuid` and `kgid`. An example:

Make sure that the appropriate overlayfs directories are there, start the overlayfs-uidshift-mount-test program:

`$ sudo /home/tixxdz/code/systemd/linux/tools/testing/selftests/mount/overlayfs-uidshift-mount-test -u 100000 --lowerdir=/home/tixxdz/fedora-tree --upperdir=/home/tixxdz/overlay/overlay-container-1/upper --workdir=/home/tixxdz/overlay/overlay-container-1/work --mountdir=/home/tixxdz/overlay/overlay-container-1/mount`

Inside the container:
`-sh-4.3# stat -c "%u:%g" /etc/passwd`
`0:0`

Outside the container:
`$ stat -c "%u:%g" /home/tixxdz/fedora-tree/etc/passwd`
`0:0`

So previously without the UID shifting inside the container the result was:
`# stat -c "%u:%g" /etc/passwd` 
`65534:65534`

Now a write operation inside the container:
`-sh-4.3# chown 99.99 /etc/passwd`

Outside the container, the result fetched from the upper directory:
`$ stat -c "%u:%g" /home/tixxdz/overlay/overlay-container-1/upper/etc/passwd`
`100099:100099`

`UID` and `GID` written on disk in the upper layer where where shifted 100000+99, but currently inside the container due to cache they will continue to show up with the previous `UID` and `GID`, this will be fixed later. Stopping and restarting the container will show the correct values.

Inside the container again:
`-sh-4.3# stat -c "%u:%g" /etc/passwd`
`99:99`

Other virtual file systems that can be mounted inside user namespaces could implement UID shifting on their own and use the same user namespace of the containing mount namespace.
#### kernel

To test, first fetch a kernel from here:
https://github.com/endocode/linux/tree/tixxdz/overlayfs-uidshift-v2
or
https://github.com/systemd/linux/tree/overlayfs-uidshift-v2
##### systemd-nspawn

Then with `systemd-nspawn` apply this patch:
https://gist.github.com/tixxdz/e79cc5440a15bb465a51

An example of `systemd-nspawn` command, just make sure that the overlay directories are there.
`$ sudo systemd-nspawn -D ~/fedora-tree/ --private-users=1000 --overlay=/home/tixxdz/fedora-tree:/mnt/container`

Inside `nspawn`
root directory:
`-bash-4.3# stat -c "%u:%g" /etc/passwd`
`65534:65534`

overlayfs mount directory:
`-bash-4.3# stat -c "%u:%g" /mnt/container/etc/passwd`
`0:0`
##### Included overlayfs-uidshift-mount-test program

Use the included overlayfs-uidshift-mount-test program, you will find it under `testing/selftests/mount/overlayfs-uidshift-mount-test`

`$ sudo /home/tixxdz/code/systemd/linux/tools/testing/selftests/mount/overlayfs-uidshift-mount-test -u 100000 --lowerdir=/home/tixxdz/fedora-tree --upperdir=/home/tixxdz/overlay/overlay-container-1/upper --workdir=/home/tixxdz/overlay/overlay-container-1/work --mountdir=/home/tixxdz/overlay/overlay-container-1/mount`

Current limitations and next goals:
- Not all operations are supported.
- Inodes are written to disk with the correct UID and GID when you do a chown() call inside the container, they will we have the global values. However inside the container they may still show up with the previous UID and GID due to the cache. This will be fixed later.
- Currently we did not consider the mount being inherited or cloned into another mount namespace and what happens with the shifts and should we restrict other mount flags, NO_SUID, etc.
- We should rework the permission checks.
- More testing.

As noted in the beginning this is just an earlier experiment.

Thanks!

**Comment by alban** [comment]
Cool work!

With this solution, a container should always be started with the same uid shift though. We cannot start `systemd-nspawn --private-users=1000`, stop it, and start it again with `systemd-nspawn --private-users=2000` because the files in the upper directory would have the wrong ownership in the second run.

**Comment by vbatts** [comment]
two questions:
- overlayfs is just the first to trial this logic on, right?
- (naive question) how is vfs or overlayfs asserting permissions that uid +10000 can read from directories owned and readable by uid 0?

**Comment by alban** [comment]
After a OOB discussion, we were wondering if this overlay fs patch can be used to mount volumes (rather than rootfs) in the container.

One idea was to mount the overlay fs with only one layer. But overlay fs does not allow that: it needs at least one lower directory and exactly one upper directory. This could be worked around with an empty directory serving as a lower directory and using the directory with the data as an upper directory.

Another question is whether it would be possible to use the same volume in two different containers, with two overlay fs mounts (one in each container). But unfortunately, the [overlay fs documentation](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt) specifies that:

> Changes to the underlying filesystems while part of a mounted overlay filesystem are not allowed.  If the underlying filesystem is changed, the behavior of the overlay is undefined

I think that the first overlay mount changing its upper directory would be considered as changing the underlying filesystem from the point of view of the second overlay mount.

**Comment by poettering** [comment]
One key feature I want is that we never persist "high UIDs" to disk, so that we don't have to keep track persistently which container needs which UID range. I want something where disk images are portable, and always use "low UIDs", and then at runtime are mapped to "high UIDs" to use in conjunction with userns. But as soon as the container terminated the "high UIDs" are fully released again, and since the only UIDs that hit the disk are the "low UIDs", the next time we run the same container we can pick a completely different "high UID" range, and everything will be fine.

Building this into overlayfs appears fine to me, but I'd really like to have a way how we can run this mapping stuff with a single layer only. The existing overlayfs requires exactly 1 upper layer plus n lower layers, where n >= 1. I'd prefer if we could use it in a setup where n = 0 lower layers are OK too. After all, when we donwload some random image of the inet, and want to shift its UIDs during runtime, then we often don#t want the ability of writing to the image at all, and don't need to merge any file systems.... 

(Of course, this opens the question whether maybe doing this in a new virtual mappings fs might also be an option, for example a "shiftfs" or so, that simply takes an existing FS, maps all uids around and makes them available under a new mount point.)

**Comment by HackToday** [comment]
hi @tixxdz  Some questions,

```
1. https://github.com/endocode/linux/tree/tixxdz/overlayfs-uidshift-v2
For you mentioned, do you means I need to compile  the linux kernel ?

2. Does 1 is general enough to be applied to other container technology, like docker etc ?
Which I can play with ? 

```

Thanks

**Comment by HackToday** [comment]
@tixxdz Could you help above question ?  Thanks

**Comment by dongsupark** [comment]
@HackToday Hi, @tixxdz looks busy these days. So I'll try to answer.
1. Yes, you need to compile the kernel. At the moment there's no installable package for this feature.
2. As this patchset is based on overlayfs, I wouldn't say it's completely for "general-purpose". In these days, however, most container runtimes including docker support overlayfs. So I could say it might be one of the realistic approaches.

I suppose @tixxdz is going to update more on it in several days.

**Comment by HackToday** [comment]
Thanks @dongsupark  for you info.

1> One point not clear to me. It seems

```
Then with systemd-nspawn apply this patch:
https://gist.github.com/tixxdz/e79cc5440a15bb465a51

An example of systemd-nspawn command, just make sure that the overlay directories are there.
$ sudo systemd-nspawn -D ~/fedora-tree/ --private-users=1000 --overlay=/home/tixxdz/fedora-tree:/mnt/container
```

Does it mean I need to find ways to change docker code to apply that ? Because above if for systemd-nspawn.

2>  For linux kernel, I just pull that branch, `https://github.com/endocode/linux/tree/tixxdz/overlayfs-uidshift-v2`,  and then compiler this kernel,  Right ?

**Comment by dongsupark** [comment]
@HackToday
1. I'm not sure I follow your question. The example above describes only how to apply the patch for the systemd tree. That has nothing to do with docker.
2. Yes right.

Can you please send me emails or messages for further questions about this setup, not to distract other people? I'll try to help you as much as I can.

**Comment by poettering** [comment]
@tixxdz heya, so I hacked up #3093 now, as a way to deal with the whole situation without having a way in the kernel to remap the uids. I think it's quite workable, but of course, I'd really prefer if the kernel would solve that for us natively, to make this cheap.

**Comment by tixxdz** [comment]
Sorry for not updating this issue, was busy with other unrelated stuff, and didn't have time at all to look into this again.

@vbatts 

> two questions:
> overlayfs is just the first to trial this logic on, right?

I tested that with overlayfs, and it seems it can work but there is now a new RFC based on VFS, please check this link:
https://lkml.org/lkml/2016/5/4/411

Simple tests were run against ext4, btrfs and overlayfs, nothing sure, just discussing it.

> (naive question) how is vfs or overlayfs asserting permissions that uid +10000 can read from directories owned and readable by uid 0?

With the new VFS solution, I just grabe inode->i_uid value and shift to the virtual view based on the user namespace mapping, if it matches uid +10000, then access granted, and the inode uid is not changed...

**Comment by tixxdz** [comment]
@HackToday sorry I was out of context at all. Any way as with every kernel interface it should be generic and not tied to any user space implementation. I'm not a docker user, but if the support is in the kernel then it should work with it.

Please note that this issue was just some early discussion and experimenting that's it! A new version is here: https://lkml.org/lkml/2016/5/4/411

**Comment by poettering** [comment]
Let's close this here. The discussion around "shiftfs" is well underway on LKML, I figure we don't need this forum here. Let's revisit this again when shiftfs got merged, at which point we can add support to in systemd right-away.
