### ISSUE TITLE
journalctl shouldn't use a pager by default

### ISSUE THREAD

**Issue by wfaulk** [systemd/systemd#24148]
### Component

journalctl

### Is your feature request related to a problem? Please describe

If I'm a non-elevated user and I want to view logs, I can run (for example) `sudo journalctl -u network.service`. But if I don't quite know what I'm looking for and just want to visually scan through the logs, the pager that is going to be invoked in the vast majority of cases, `less`, truncates lines by default, making that visual scan difficult.

### Describe the solution you'd like

Don't use a pager by default. Add `--pager` to use one. Also add a short option for it.

Alternatively, at least provide a short option for `--no-pager`.

Or at least include the word "wrap" in the man page to make it easier to search for the problem, even though `journalctl` is not the one preventing the line wraps.

### Describe alternatives you've considered

* Use the `--no-pager` option to `journalctl`
* Piping `journalctl` to `cat` (or otherwise blocking the pty from the process)
    * This has the side-effect of also disabling coloring
* Setting `$SYSTEMD_PAGER` to nothing (or `cat`)
    * This also probably necessitates telling `sudo` to pass that envvar along, making this wonderful command line:
        `SYSTEMD_PAGER='' sudo --preserve-env=SYSTEMD_PAGER journalctl -u network.service`
* Setting `$SYSTEMD_PAGER` to a pager command that won't truncate lines
    * See above
* Interactively change settings on the pager to wrap lines
    * This would be the interactive command `-S` for `less`

But I shouldn't have to tell it not to do something extra. If I want it to be passed through a pager, I can do that myself. It's a very common Unix pattern.

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by poettering** [comment]
Discussion was had before. And sorry, no. Let's not reopen this can of worms.

Auto-paging is useful to many, including me personally. It's not something we invented, but git came up first, and we just copied the concept. If you disagree with the fact that it is opt-out rather than opt-in then that's something we both have to live with.

Sorry, but this is not something we are going to change. 

Please just turn off auto-paging if you like, there is plenty documentation around how to do that.

Anyway, closing, since this is simply nothing that we'll change.
