### ISSUE TITLE
What will happen to manually create the scope directory in the cgroup directory？

### ISSUE THREAD

**Issue by 1ikejun** [systemd/systemd#24197]
In the systemd official website, it is recommended not to manually create your own cgroup in the cgroup directory, there will be some problems, but I manually create a cgroup for testing and there is no problem. I don't know what the specific problem will be?

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
