### ISSUE TITLE
boot loader spec is confused about $BOOT

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#24247]
the boot loader spec now defines $BOOT in a way that is different than before, and totally different from what is implemented in bootctl.

Previously $BOOT refers to XBOOTLDR if it exists, and ESP otherwise. 

Now it always points to the ESP?

But bootctl doesn't implement it that way.

I think the spec change should really be reverted, i.e.  #23504

**Comment by keszybz** [comment]
I noticed the issue with bootctl too, but didn't have time to submit a patch.
Actually bootctl mostly works fine internally, but just displays things in a confused way. In particular, it doesn't handle entries existing in both places very well, even though the EFI code handles that fine.

I don't think we should revert changes to the spec: I know that meaning of $BOOT was changed, but the old definition was internally inconsistent. And more importantly, it didn't describe what the EFI code was doing. So there isn't much point in trying to "rescue" the old inconsistent meaning of "$BOOT". I think we can either a) redefine it to be useful and consistent, b) invent a new term.

**Comment by poettering** [comment]
> I don't think we should revert changes to the spec: I know that meaning of $BOOT was changed, but the old definition was internally inconsistent.

how so?

at least I am terribly confused now. I don't know what $BOOT is supposed to be now?

**Comment by poettering** [comment]
> And more importantly, it didn't describe what the EFI code was doing.

It wasn't?

**Comment by poettering** [comment]
Text now says:

> An OS installer picks the right place for $BOOT as defined above (possibly creating a partition and file system for it) and creates the /loader/entries/ directory in it. It then installs an appropriate boot loader that can read these snippets. Finally, it installs one or more kernel packages.

So what is $BOOT? In the original definition it was where to put stuff, so either XBOOTLDR or ESP, but I think it's no longer that, but just the ESP? but why bother with that, if noone puts stuff there? The spec *now* appears to be inconsistent?

**Comment by keszybz** [comment]
From the commit messages:

**[docs/BLS: rework the description of directory layout](https://github.com/systemd/systemd/pull/23504/commits/0f5a416c81917fb85ed6d8043041660c310cc8d9)**

We said "`$BOOT/loader/` is the directory containing all files needed
for Type https://github.com/keszybz/systemd/pull/1 entries" which is blatantly wrong. And also saying that we
define two directories, /loader and /loader/entries, but only ever defining
the second one was not very consistent.

Instead, let's say that /loader/ is for "boot loader configuration", and
/loader/entries has the snippets. A new section about /<entry-token>/<version>/
is added. This is described as the "recommended layout for additional files".

Also, we said that ID= should be used in the file name, but in fact it
wasn't in the example that was given, and afaik, nobody ever did that. So
this part is reduced to say "kernel version (as returned by `uname -r`,
including the OS identifier)". AFAIK, all distros include some form of
OS identifier in the version, so this should be good enough.

Since we now don't depend on autodetection (e.g. with entry-token and layout
configured), the installed doesn't need to always create /loader/entries and
things will still work. So don't say that the installer needs to create it.

Part of the discussion is moved to the Discussion section.

Overall, this brings the specification more in line with actual practice.

**[docs/BLS: clear up the confusion about what $BOOT means](https://github.com/systemd/systemd/pull/23504/commits/53c26db4dac0f5b79ca2a57364ee7df78a14bbfd)**

The text used was originally written for everything being on the ESP. It was
later generalized for support XBOOTLDR, and "$BOOT" was introduced to mean
something like "XBOOTLDR if present, the ESP otherwise", and most of the text
was changed to talk about $BOOT. Sadly, this doesn't work, because the two
partitions are not interchangeable. sd-boot loads entries from both partitions,
and its configuration, random-seed, etc. only from the ESP.

The terms are redefined: $BOOT now means either the ESP or the "boot partition"
playing the same role on MBR systems, and $XBOOTLDR is XBOOTLDR.

Like various previous commits, this makes the specification describe our
current implementation.

~~Also, the let's just accept the common practice of using /boot and /boot/efi.
Since both partitions need to be read to gather configuration, it isn't a
problem that one is mounted underneath the other one. I think having /boot and
/efi is OK, but not better in any measureable way, so let's stop trying to push
people towards this setup.~~
[EDIT: that part is partially wrong, because automounts are a good reason to avoid /boot/efi, at least with the current implementation.]

A note that XBOOTLDR must be on the same disk as ESP is added.

**Comment by poettering** [comment]
> We said "`$BOOT/loader/` is the directory containing all files needed
> for Type [keszybz#1](https://github.com/keszybz/systemd/pull/1) entries" which is blatantly wrong.

I really don't follow here? why do you say "blatantly" wrong?

**Comment by poettering** [comment]
> Sadly, this doesn't work, because the two
> partitions are not interchangeable. sd-boot loads entries from both partitions,
> and its configuration, random-seed, etc. only from the ESP.

It's configuration, random seed are *not* part of the boot loader spec, and should not be.

The fact that sd-boot reads boot loader spec entries from the ESP even if XBOOTLDR exists is mostly to make it more robust, if multiple parties disagree on esp/xbootldr, which is quite likely given that XBOOTLDR was added much later.

But the fact it does that is an implementation detail. The spec otoh was supposed to give clear indication where to put stuff. But the new version suggests to always put stuff in the ESP as I see it but that really misses the point of the existance of XBOOTLDR?

We shouldn't write the spec from our perspective of sd-boot maintainers, but with a focus on what other projects might do with it. And for them the primary question is "where should i put my stuff". And that's XBOOTLDR, and not the ESP, and that is *key*. But with this new spec version you basically tell them to never put something in XBOOTLDR, but just read from it. Which is really the opposite of how it should be...

**Comment by cmurf** [comment]
[18 days ago](https://github.com/systemd/systemd/issues/24247#issuecomment-1208387110)

    We said "$BOOT/loader/ is the directory containing all files needed
    for Type https://github.com/keszybz/systemd/pull/1 entries" which is blatantly wrong.

>I really don't follow here? why do you say "blatantly" wrong?

Because either or both $ESP/loader/ and $XBOOTLDR/loader could contain files, and have to be merged. Maybe it's a nuance but I consider $BOOT as being more of a concept than a literal device or partition. It's the merged $ESP and $XBOOTLDR. $ESP can only contain the bootloaders (shim, sd-boot, grub, etc), we can't put those on $XBOOTLDR because we can't be assured the firmware will read them there. It probably will if there's an entry for them in NVRAM that points to $XBOOTLDR but it's not guaranteed.

**Comment by poettering** [comment]
→ #24521

**Comment by poettering** [comment]
> Because either or both $ESP/loader/ and $XBOOTLDR/loader could contain files, and have to be merged. Maybe it's a nuance but I consider $BOOT as being more of a concept than a literal device or partition.

Yeah, but that's not how the spec was intended and implemented. The spec is a lot more practical: $BOOT is the thing you mount to /boot/, and which "kernel-install" installs to. It's what "bootctl -x" tells you the path of.

For practical implementation we need concepts that are well-defined and unique, i.e. that we can mount and have paths of. If things are "conceptually" backed by two partitions all that goes down the toilet...
