### ISSUE TITLE
systemd timer triggers service; combination spamming logs

### ISSUE THREAD

**Issue by garberw** [systemd/systemd#24275]
### Component

journalctl, systemd

### Is your feature request related to a problem? Please describe

A frequently run timer triggers a service.  This generates a small message in journalctl.  Since this is frequently run over a long time it not only makes journalctl hard to read, it may make the log file way too big.  It is run on a raspberry pi with limited space.   Bug/feaure also on fedora 36.

### Describe the solution you'd like

"LogLevelMax=notice" is supposed to eliminate these messages (in timer and/or service file?).  It does not seem to be working.
`
root@weatherb### systemd --version
=systemd 247 (247.3-7+rpi1)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
root@weatherb### 
`

### Describe alternatives you've considered

the only alternative I can think of is to use cron.  
For annoyed people see:

[bugzilla same problem](https://bugzilla.redhat.com/show_bug.cgi?id=911766)

### The systemd version you checked that didn't have the feature you are asking for

247

**Comment by garberw** [comment]
[bugzilla same problem](https://bugzilla.redhat.com/show_bug.cgi?id=911766)

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
