### ISSUE TITLE
Simple log analyzer for systemd-journald with triggers for running arbitrary commands

### ISSUE THREAD

**Issue by robert-scheck** [systemd/systemd#2432]
It would be great to have a simple log analyzer for systemd-journald with triggers for running arbitrary commands on the system.

A daily usage scenario would be that e.g. failed SSH logins could lead to an iptables command to drop this source IP address. The idea is not to replace existing tools like fail2ban which are likely much more powerful, however fail2ban is written in Python and gets slow (and/or causes high load) with zillions of log lines.

On the other hand, systemd-journald already knows the log lines (if systemd-journald is used rather another syslog implementation) and applying a regular expression parser with a counter depending on occurrence amount in a specific time frame in C is hopefully much less resource consuming rather fail2ban; aside of that journalctl already features some of these options (`--since`, `--until`).

**Comment by johannbg** [comment]
Oh you mean something like tallow?

https://github.com/sofar/tallow

**Comment by johannbg** [comment]
I should mention that tallow uses iptables ( which systemd did at the time of it's writing ) while systemd has now switched to use nftables. These things will conflict.

**Comment by poettering** [comment]
This would certainly be useful, but appears to be something that can easily be implemented outside of systemd, and needs no additional support in systemd itself.

**Comment by johannbg** [comment]
@poettering dont be too quick to dismiss this you might actually want to leave this RFE open since things have changed quite a bit in those three years Auke wrote that stuff and systemd is already going down the path of firewall support so leaving type units out makes little to no sense.

You could add options to type service files something along the lines of 
FirewallAction=
FirewallThreshold=
FirewallExpiration=
FirewallWhitelist=
along with having each type service file residing in it's own nft chain if this has been enabled.

**Comment by johannbg** [comment]
@poettering I'm unsure how you have planned on implementing the nftable support in grand scheme of things but at this point in time I suggest you seriously consider introducing a new type unit of type .rules which stores all those firewall rules and potentially additional actions ( like additional actions, threshold,experations,whitelist etc ) since you need to be able to enable/disable/change those rules on the fly without having to start,stop,restart the interface or the service,scope,container whatever but at the same time you want to "bind" those rules to existing type units and interfaces so when they start the rules are implemented and when they stop the rules are removed
