### ISSUE TITLE
Invalid assumption that `get_option('optimization')` in Meson is a valid argument to `-O` 

### ISSUE THREAD

**Issue by tristan957** [systemd/systemd#24323]
### systemd version the issue has been seen with

master

### Used distribution

n/a

### Linux kernel version used

n/a

### Component

systemd-boot

### Expected behaviour you didn't see

A successful build.

### Unexpected behaviour you saw

https://github.com/systemd/systemd/blob/e228d48b9ebff665e8b1dd1572c53217075c1a5a/src/boot/efi/meson.build#L224

You can see that here systemd takes the output of get_option('optimization') and passes it as a `-O` argument.

This is going to become a problem very soon with impending merge of https://github.com/mesonbuild/meson/pull/10593.

### Steps to reproduce the problem

Pull the branch specified in https://github.com/mesonbuild/meson/pull/10593 and try to build systemd.

**Comment by tristan957** [comment]
Easiest solution would be to use the option as a key into a dict. I am happy to submit a PR unless someone else wants to fix it.

**Comment by medhefgo** [comment]
Let's wait for that PR to go in first…

**Comment by eworm-de** [comment]
Meson merged, so please consider this now.

**Comment by eli-schwartz** [comment]
> Let's wait for that PR to go in first…

The fix has landed in systemd, but I guess there wasn't enough time to cherry-pick it into systemd-stable 251.7 (it's in the 251 branch at least...)

**Comment by bluca** [comment]
if it's in the v251-stable branch it will be in the next point release

**Comment by eli-schwartz** [comment]
@bluca sorry for the confusion, I probably wasn't clear enough.

The reason I mentioned this at all was because there's already been a bug report to Gentoo about it.

And Meson is imminently going to release the new version of Meson that breaks this, which is why it would have been nice if this actually worked rather than "okay granted it errors out now, but don't worry, for the next point release, systemd will actually compile".

I cannot help but feel that waiting 2 months for unclear reasons before fixing it was less than fully optimal, if it had been fixed immediately then it would have already been released in a previous point release.

As it is, despite us giving 3 months of advance warning, I'm getting worried that Meson 0.64.0 is going to start circulating and people are going to start complaining that we broke things.

So yes, my research into the systemd stable branch and conclusion that the fix is still pending and will be delayed until the *next* point release, as opposed to the one that is available to people today, was actually leading to a specific conclusion. And that conclusion is:

It would be fantastic if that could in fact be released soon. :)
