### ISSUE TITLE
Race condition on system shutdown / reboot

### ISSUE THREAD

**Issue by robret77** [systemd/systemd#24416]
### systemd version the issue has been seen with

249.11-0ubuntu3.4

### Used distribution

Ubuntu 22.04

### Linux kernel version used

5.17.0-1015-oem

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

A dirty shutdown after a configurable fixed amount of time.

### Unexpected behaviour you saw

No shutdown at all with even increasing wait time.

### Steps to reproduce the problem

Unfortunately this is a race condition which happens seldom. But it will happen sooner or later.

### Additional program output to the terminal or log subsystem illustrating the issue

After triggering a shutdown, the desktop manager exited and the shutdown was initiated. I took some photos, but as it is not too much text, I'll just type the console output here by hand just because this bug is a bigger problem in my eye:

1) Shutdown initiated

```
Stopped Permit User Sessions.
Stopped target Network.
Stopped target User and Group Name Lookups.
Stopped target Remote File Systems.
Stopped target Preparation for Remote File Systems.
Stopping Network Manager...
Stopping System Security Services Daemon...
Stopping Network Name Resolution...
Stopping WPA supplicant...
Stopped Network Name Resolution.
Stopping Network Name Configuration...
Stopped Network Name Configuration.
Stopped System Security Services Daemon.
Started Show Plymouth Reboot Screen.
Starting Tell Plymouth To Jump To initramfs...
Finished Tell Plymouth To Jump To initramfs.
(1 of 2) A stop job is running for Network Manager (1min / 1min 50s)
```

--> Not good to wait so long for my laptop's network, but OK, I had not been in a hurry

2) First upgrade of the wait time

```
(1 of 2) A stop job is running for Network Manager (2min 18s / 3min 20s)
```

--> My worries started

3) I lost confidence now

```
(1 of 2) A stop job is running for WPA supplicant (3min 32s / 4min 50s)
```

--> Some not good feeling developed already

4) The wish not to use systemd increased to it's maximum and I shutdown my laptop physically

```
(1 of 2) A stop job is running for Network Manager (5min 24s / 6min 20s)
```

--> Hope had been gone completely to have a shutdown

This behavior happens with guarantee sooner or later. I also experianced it on Arch Linux with it's normally extremely fast systemd configuration. With the network service or with others. When this problem could be fixed, the acceptance for systemd will directly increase exponentially in my eye. What is the alternative, to wait forever? I have always unrelaxed worries on Ubuntu to reboot or shutdown my device. In a server room it could be even more troublesome to initiate a physical reboot. 

Anyhow, even if this bug would not exist, I really wish for a configurable fixed max wait, after that this command should be executed: 'halt -fp'. Just to guarantee a shutdown VS don't shutdown at all or waiting for a great amount of time for nothing good.
```

**Comment by vcaputo** [comment]
How is this proven to be a race condition in systemd by the provided information?

IME whenever I have a spuriously stalled shutdown resembling what you've posted, it's because `dhcpcd` has for some reason mishandled its graceful shutdown SIGTERM without actually exiting.  Then systemd's "kill with extreme prejudice" timeout on the service must expire for the shutdown to continue.

It might be helpful to add journal output from these delayed shutdowns you're experiencing.  The `-b-N` relative boot journalctl flag can be useful here.  If you know the previous boot's shutdown was FUBAR use `-b-1`, two boots back `-b-2` etc.

I'd love for this to be a bug in systemd we can fix, but every time I've dug into these it's been the service's shutdown implementation at fault.  Which sucks, because there's an infinite number of daemons out there systemd will potentially have to wait for on shutdown, that then need to be identified and fixed upstream.

**Comment by reitzrobert77** [comment]
Of course there exist an infinite amount of services, but there also exist an infinite amount of distributions with infinite services which would need infinitive fixes of the same upstream fix infinite times.

It simply doesn't feel right to create such field of problem for no good reasons on the shutdown, except of course you concatenate a shutdown directly to a startup without reboot, then you really need such feature for cleanness, but be aware of kernel problems with dirty unmounts of network shares or graphic card problems, KMS maybe?

That's the point why I opened the bug report here and not on the Ubuntu bug tracker. To search for complete eays. I love systemd for all other parts.

This problem isn't any new, even if it might look so today. In the old days, misbehaving services have already been well studied and treated well by a fixed total time limit (e.g. 5 seconds on laptops) in such all polite services at once may shutdown gracefully. After this fixed total amount of time, all unpolite services had been treated by the SIGTERN at once.

Is there is any similar option to configure such limit for all of my services at once? I would be very thankful.
I'm and not very thankful to hear that I otherwise have to debug all misbehaving services myself. Remember, there is an infinite amount of services which would suck too much energy.

--> Redirecting the responsibility for the shutdown to anyone else (the distributions) is probably not very kind in the eyes of the user itself who has this disadvantage. Like an empty laptop battery when he shut down the machine and put it in his bag for later use, just because he trusted systemd to do the most simple operation of all, the shutdown. And isn't trust all that matters?

**Comment by vcaputo** [comment]
So... not a race condition then?  This is now sounding like more of an RFE for a less cooperative shutdown.

If there's a race condition in systemd we'd like to characterize and fix it.  If there's no actual evidence of that, please close this issue.

As far as what you're wanting, are you aware of the `CtrlAltDelBurstAction=` setting in system.conf?

When you're at the console you already have the option of compelling a brute-force shutdown style of your choosing.  See the `systemd-system.conf(5)` man page for more information.

**Comment by reitzrobert77** [comment]
Unfortunately Ctrl+Alt+Del is no option, as it involves user interaction.

**Comment by reitzrobert77** [comment]
I would be good to convert the issue to a feature request for a optionally enforcing cooperative shutdown.

**Comment by vcaputo** [comment]
Please open a new RFE issue *clearly* and *succinctly* characterizing the feature you actually want added.  You can always link to this closed issue if necessary.

What's here right now only muddies the waters IMNSHO.

**Comment by poettering** [comment]
249 is too old to be tracked here (only 251 and 250 issues are tracked here, as the bug submission form shoul dhave made clear). And this smells like an integration issue anyway, hence, please contact your distro first, and let them elevate this here.

**Comment by robret77** [comment]
Nice to get personally offended by professionals. IMNSHO it takes a bit more then to pull a graph algorithm from a gum machine.
