### ISSUE TITLE
Unexpected behavior with notify service

### ISSUE THREAD

**Issue by chandrasekhar1996** [systemd/systemd#24498]
### systemd version the issue has been seen with

219

### Used distribution

CentOS Linux 7

### Linux kernel version used

3.10.0-1160.71.1.el7.x86_64

### Component

systemd

### Expected behaviour you didn't see

I have a service A of type `notify`. Service A will restart every 2 minutes on failure. I have another Service B which has `After=serviceA` in its service unit file. Service B also has a timer with OnCalendar set for it to run every 5 minutes.

I expect to service B to not start when service A has entered an error state and exited with code 1. I use sd_notify (https://github.com/coreos/go-systemd/blob/main/daemon/sdnotify.go) to send ERRNO=2

### Unexpected behaviour you saw

The service B doesn't run and initially and as soon as service A enters the failed state, service B starts running. After that service B on its next run (after 5 minutes) again runs when service A enters failed state.

### Steps to reproduce the problem

serviceA: 

```
[Unit]
Description=Service A
After=sshd.service

[Service]
Type=notify
NotifyAccess=main
ExecStart=/usr/sbin/serviceA
Restart=always
RestartSec=120

[Install]
WantedBy=multi-user.target
```

serviceB.service: 

```
[Unit]
Description=Service B
After=serviceA.service
Wants=serviceA.service
Wants=serviceA.timer

[Service]
Type=simple
ExecStart=/usr/sbin/serviceB

[Install]
WantedBy=multi-user.target
```

serviceB.timer

```
[Unit]
Description=Service B timer
Requires=serviceB.service

[Timer]
Unit=serviceB.service
OnCalendar=*:0/5
OnBootSec=0min

[Install]
WantedBy=timers.target
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
05:39:23 systemd[1]: serviceA.service: main process exited, code=exited, status=1/FAILURE

05:39:23 systemd[1]: Started ServiceB
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
