### ISSUE TITLE
please consider making credential handling optional

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#24508]
### Component

systemd

### Is your feature request related to a problem? Please describe

[aide](https://github.com/aide/aide) is a tool that takes file lists and checksums of files on the system and compares them to a baseline database to be able to identify changes to the file system, which might be an attacker trying to hide their files in the system.

When running aide from a systemd unit with protections in place (for example, "ProtectControlGroupos=yes"), /run/credentials gets a temporary mount which hides files that might be stored in /run/credentials of the "real" system. This is kind of documented in man systemd.exec (although I cannot find the place right now).

However, I'd like to have my aide process see /run/ as seen by the "real" system while still being able to use things like ProtectSystem, ProtectHome and ReadWritePaths.

### Describe the solution you'd like

Please consider implementing a configuration setting that undoes the automatic enabling of "overmounting" /run/credentials by setting certain protection options.

### Describe alternatives you've considered

I considered running aide without proections or staying with the shell script called from classic cron, but that would be a pity because I would not be able to make use of systemd's nifty features. Of course living with the risk of somebody using /run/credentials to hide things from aide is also an option, but with this issue being open for everybody to read, it's public information now which chould seriously reduce aide's impact.

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by poettering** [comment]
Which mount precisely? You talk of /run/credentials and /proc/credentials?

Can you mention the precise line from /bin/mount point you are concerned about?

What's the 'aide' tool unit file?

If you want it to see the host view of the full fs, then you cannot enable any sandboxing option that involves mount namespaces, such as ProtectControlGroups=, since that after all makes subhierarchies unavailable to the invoked service, and if that shouldn't happen, then don't use the option?

/run/credentials is used as backing store for passing service credentials (i.e. this stuff: https://systemd.io/CREDENTIALS/) into services. If fs namespacing is enabled for a service, we will hide the full credentials hierarchy from the service. If you don#t want that, don#t enable any sandboxing for the service.

Anyway, i don't get what the issue is, and pleas provide the unit file in question.

**Comment by Zugschlus** [comment]
> Which mount precisely? You talk of /run/credentials and /proc/credentials?

I mean /run/credentials, I am sorry for the typo. I have edited the original report for clarity.

> Can you mention the precise line from /bin/mount point you are concerned about?

tmpfs on /run/credentials type tmpfs (ro,nosuid,nodev,noexec,relatime,size=36448k,mode=755,inode64)

> What's the 'aide' tool unit file?

```
[Unit]
Description=dailyaide check
StartLimitIntervalSec=7200
StartLimitBurst=1

[Service]
Type=oneshot
User=root
Group=root
ProtectSystem=strict
ProtectClock=yes
ProtectKernelModules=no
ProtectKernelLogs=yes
ProtectControlGroups=yes
PrivateDevices=no
ProtectKernelTunables=yes
ProtectControlGroups=yes
ProtectHome=read-only
ReadWritePaths=/run/aide /var/lib/aide /var/log/aide /var/spool/exim4 /var/log/exim4 /var/tmp /tmp
RestrictRealtime=yes
RestrictSUIDSGID=yes
PrivateTmp=no
ExecStart=/usr/local/sbin/dailyaidecheck --systemdservice
```
> If you want it to see the host view of the full fs, then you cannot enable any sandboxing option that involves mount namespaces, such as ProtectControlGroups=, since that after all makes subhierarchies unavailable to the invoked service, and if that shouldn't happen, then don't use the option?

One can debate the usage of ProtectControlGroups for sure, I have not yet fully gasped the results of these options, but it should be obvious that ProtectSystem=strict paired with strategically placed ReadWritePaths will improve the processes' security because it cannot write to most of the file system.

> /run/credentials is used as backing store for passing service credentials (i.e. this stuff: https://systemd.io/CREDENTIALS/) into services. If fs namespacing is enabled for a service, we will hide the full credentials hierarchy from the service. If you don#t want that, don#t enable any sandboxing for the service.

This service is not using systemd-credentials and it is unlikely that it ever will. However, it gets the feature, undesired and reducing system security one way or the other. What I am kindly asking for is the opportunity to disable this feature that the service doesn't use.

I hope that I was able to answer your questions and will of course continue to do so.

Best regards, Marc

**Comment by poettering** [comment]
You can't really have it both ways: enable sandboxing and have your service see the whole host fs. Pick one.

**Comment by Zugschlus** [comment]
> You can't really have it both ways: enable sandboxing and have your service see the whole host fs. Pick one.

For the protocol, I disagree. Just make those extra mounts configurable and we're all fine.

**Comment by poettering** [comment]
I don't follow: you want to hide some dirs, but also you categorically don't want to hide some dirs? How does that computer?

sandboxing options in systemd are to a large part about overmounting host dirs in a per-service namespace, obstructing access to it. You said you don't want overmounting, so then disable those sandboxing options.

So, let me ask you then: are you OK with overmounting for the purpose of obstructing access? if yes, the issue makes no sense to me and we can close it? if no, then disable the sandboxing options and we can close this issue too?

Or what am I not grokking?

**Comment by Zugschlus** [comment]
Thanks for staying in the discussion, I really appreciate that.

I want to make some dirs read-only. In fact, I'd like to have most of the system read-only with the exception of a small single-digit number of dirs that I need read/write such as the place where I write my results. I currently cannot have this without having /run/credentials being hidden away.

If running on a fully read/write system is the only way to not lose access to the original /run/credentials then I'm going to go that way, but it's full of grief to not be able to make use of a good feature because it only comes bundled with another feature that is bad for the use case.

**Comment by waldiTM** [comment]
But that you can do much easier with retaining `CAP_DAC_READ_SEARCH` and don't run that stuff as `root`.

**Comment by poettering** [comment]
Ah, so you are interested in read-only but not in hiding stuff, got it now.

Do note that if a service enables both sandboxing and credentials, then we'll mount a private ramfs into that service namespace that noone else is seeing. This is kinda the goal of credentials: that they are private to services as much as we can do it. If the service that consumes the creds itself uses sandboxing then that's easy. If some service uses sandboxing but doesn't consume creds then we can hide everyone else creds too. The only time where two services could possibly see each other creds if both disable sandboxing, because then simply there is no way.

so the question what is more important:

1. the desire to hide credentials from everyone else as much as we can and keeping them private to the consuming service

2. the desire for your specific aide tool to see "everything".

I am pretty sure goal 1 trumps goal 2: credentials are assumed to be secrets by their definition we should really try hard to hide them as good as we can.

**Comment by Zugschlus** [comment]
So, which is the option in my service unit that (accidentally, I surely didnt want that) enables credentials, and how do I disable credentials for my service?

**Comment by poettering** [comment]
Nope, that's not what i was suggesting. Your service is not using creds, it has no LoadCredential= or SetCredential= line.

But your service uses sandboxing/mount namespacing. Whenver a service does that we'll mask our the creds dir for it. Why? Because *other* services might use credentials but not sandboxing and we should hide those creds of other services, because they after all are supposed to be be private and secret per service.

i.e. the thinking is: if we can't lock the secrets into the service that actually uses them because it doesn't use sandboxing, then the next best thing is hide it for every other service that does use sandboxing.

**Comment by poettering** [comment]
Anyway, I'd advise you to simply turn off sandboxing for your service. Note that enabling sandboxing also disables propagation of mount events (since we want to deviate from other processes' mount table after all). But if you intend to analyze the host fs in full you probably want those propagation events.

So as suggsted before: if you want to see the host fs in full, disable all sandboxing for your service. i.e. make all these go away:

```
ProtectSystem=strict
ProtectClock=yes
ProtectKernelModules=no
ProtectKernelLogs=yes
ProtectControlGroups=yes
PrivateDevices=no
ProtectKernelTunables=yes
ProtectControlGroups=yes
ProtectHome=read-only
ReadWritePaths=/run/aide /var/lib/aide /var/log/aide /var/spool/exim4 /var/log/exim4 /var/tmp /tmp
```

**Comment by Zugschlus** [comment]
> Nope, that's not what i was suggesting. Your service is not using creds, it has no LoadCredential= or SetCredential= line.
> 
> But your service uses sandboxing/mount namespacing. Whenver a service does that we'll mask our the creds dir for it. Why? Because _other_ services might use credentials but not sandboxing and we should hide those creds of other services, because they after all are supposed to be be private and secret per service.

That's something I understand. But why would those other services use credentials but not sandboxing? If they want their credentials to be safe they should be sandboxed.

> i.e. the thinking is: if we can't lock the secrets into the service that actually uses them because it doesn't use sandboxing, then the next best thing is hide it for every other service that does use sandboxing.

Would it not be possible to hide those even from othre services that dont use sandboxing?

Anyway, I think I have understood.
