### ISSUE TITLE
RFE: systemd.confirm_spawn=1 should wait forever

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#2452]
Originally reported in https://bugzilla.redhat.com/show_bug.cgi?id=1084401:

> systemd.confirm_spawn=1 should ask for confirmation when spawning processes but it has a built-in timeout after which a positive response is assumed. This causes issues when an administrator boots up a system with systemd.confirm_spawn=1 and the administrator is interrupted by something while the system is booting, the bootup continues slowly behind his/hers back although the intention was to confirm each step.
> 
> systemd.confirm_spawn=1 should not expect a positive response no matter how long it takes to provide a response to a question.
> 
> In the worst case, this seems to cause system boot to fail altogether. To reproduce, boot with systemd.confirm_spawn=1, go have a long lunch, and then see time out errors for devices and services on the screen and question should dracut-emergency be executed.

**Comment by mbiebl** [comment]
Related to that: I see the eye-of-cylon animation kicking in when I use systemd.confirm_spawn=1, which is pretty much not what you want in this case

**Comment by johannbg** [comment]
@poettering  should have closed this one back in twenty fourteen <sigh>

**Comment by poettering** [comment]
Sorry, but this cannot work. We apply timeouts to everything. This means if one service is currently initializing and talks to another service which isn't started yet, and we thus begin starting, and that one hangs forever, then the first one will timeout and die. 

As long as there are timeouts everywhere (and there should be), we have to continue booting, otherwise they all will hit eventually. 

The only option to make this workable would be if we could pause all timeouts on the system temporarily. But that's not realistic, as there are so many different places where timeouts are applied: in the kernel, in dbus, in various places in systemd, and so on and so on.

So no, this is nothing we can support. Sorry.

**Comment by mbiebl** [comment]
Wouldn't it be better to remove the confirm_spawn feature completely then? Shipping a known broken feature, which you say is unfixable, only leads to confusion once people use it.

**Comment by poettering** [comment]
@mbiebl why is it broken? I mean, sure the eye-of-ceylon conflict isn't nice, and we should fix that (#2194). However, as long as the user reacts quicker than the timeout all should be good. Of course, it would be nicer if we'd actually show a countdown or so, but all that is cosmetics, not more.

What really matters is that the timeout for the question is chosen shorter than the usual other timeouts on the system.

**Comment by mbiebl** [comment]
Last time I tried the confirm_spawn feature, it was barely usable. If you have multiple jobs running at the same time, you don't see which one will be started next etc.

It basically was a complete failure when I used it.
