### ISSUE TITLE
log if a condition prevents starting a unit

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#2468]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775459

If a service/unit fails to start due to a failed condition, this is not logged. It can only be seen in the status output. In the aforementioned bug report, the user requests that systemd should log such a failure to start a unit and why i.e. which condition was not met.

**Comment by fsateler** [comment]
This seems to be logged, but only at debug level: https://github.com/systemd/systemd/blob/v228/src/core/unit.c#L1314

Maybe the level should be raised?

**Comment by keszybz** [comment]
So there are two bugs...
1. Failing Condition on the service unit triggered by a socket connection are not treated as a failure. Best option would be to treat them exactly the same as normal failures, and give up after a few tries. If that is hard, we could give up after the first time Condition fail.
2. We only log "Starting...", but not that Conditions were not met. I think it's a good idea to upgrade the level to log_info.

**Comment by keszybz** [comment]
A successful condition should still be logged at debug level. log_info only for failing.

**Comment by mbiebl** [comment]
2016-01-29 2:12 GMT+01:00 Zbigniew Jędrzejewski-Szmek <
notifications@github.com>:

> So there are two bugs...
> 1. Failing Condition on the service unit triggered by a socket connection
> are not treated as a failure. Best option would be to treat them exactly
> the same as normal failures, and give up after a few tries. If that is
> hard, we could give up after the first time Condition fail.
> 
> I've filed https://github.com/systemd/systemd/issues/2467 for that, at
> least I think we do mean the same thing here.
> 1. We only log "Starting...", but not that Conditions were not met. I
>    think it's a good idea to upgrade the level to log_info.

I think this bug report should be about 2.

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by poettering** [comment]
So, here's the thing: ConditionXYZ= exists precisely to skip a unit _without_ logging loudly about it. For example we mark many units with this that shall be skipped without this being considered an error if some optional kernel feature or subsystem is missing, or if we boot with a read-only file system or in a container. Example: the getty service is conditioned on there actually being a VC subsystem, so that it becomes a NOP automatically when there's no VC to show any prompt on. Similar, udev is conditioned on /sys being writable, because if it is read-only there are no devices to manage (which means the right thing happens in a container). If you start a container without VC and with /sys mounted read-only then we should log tons of stuff about things we _don't_ do, we only should log about stuff that we _do_.

The fact that conditions are used and have an effect isn't hidden. You can see them in "systemctl status" (i.e. explicitly query them) and you see them if you turn on debug logging. But that's pretty much the way it should be.

Note that there's also the concept of "assertions" that are much like condition, but instead of silently skipping a unit, result in loudly failing it. To me it appears as if your user really should have been using an assertion instead of a condition instead. 

I will prep a patch that extends on the docs about this and clarifies that ConditionXYZ= is "silent skipping" while AssertXYZ= is "loud complaining", so that people use the right option at the right place.

I hope this makes sense.
