### ISSUE TITLE
repart should support a global version of CopyFiles=

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#24786]
### Is your feature request related to a problem? Please describe

Let's say I have a directory tree that I want to move to a disk image with a root partition and a home partition. If I try to use the following config files, I will run into issues:

```
[Partition]
Type=root
CopyFiles=/
````

```
[Partition]
Type=home
CopyFiles=/home
```

Since the files from /home will end up in both the root partition and the home partition.

### Describe the solution you'd like

Instead of copying files per partition, I want to copy them all at once. What I figure we should do is format all the partitions with filesystems, mount them all at their canonical mount point, and then copy all files at once from a directory tree. This makes sure that all files end up in the right partition.

I'd probably go about this by adding a --copy-files switch that takes a directory. If --copy-files is configured, after formatting the filesystems, repart would mount them all and copy the files from the --copy-files directory (target == "/").

Now, you could end up in a scenario where no root partition is configured, so I figure we should do all the mounts in a temporary directory, and create upper level directories as needed if there is no partition for them. That way, if only a usr partition is configured, all the files outside of the usr partition would simply end up being thrown away when the temporary directory is deleted. The only annoying thing is that this isn't super efficient, since we might be copying files unnecessarily, but it's not impossible to optimize later (e.g. only copy files that are prefixed with one of the partition mount point directories or such).

### Describe alternatives you've considered

We could add an ExcludeFiles= switch to repart to not copy anything under the configured excludes, but that requires a lot of manual configuration from the user to figure out the required excludes based on the other partitions that are configured, which would lead to a lot of manual hassle. The proposed solution requires zero extra configuration from the user, just configure a set of partitions, and repart will automatically make sure that every directory from the directory tree ends up in the right partition.

### The systemd version you checked that didn't have the feature you are asking for

main

**Comment by poettering** [comment]
Isn't that something to just do with `systemd-dissect --copy-to`? I mean that does exactly what you are asking for here, no?

**Comment by DaanDeMeyer** [comment]
Yes, but that means I can't use the verity support I just added to repart anymore

**Comment by poettering** [comment]
I see.

What about just adding ExcludeCopy= or so? so that in the root fs you say CopyFiles=/ and then ExcludeCopy=/home?

**Comment by DaanDeMeyer** [comment]
Yes but configuring all of the manually from mkosi is not great, I think we should do this by default in repart. If a home partition is configured, it probably does not make sense to copy files from /home into the root partition.

**Comment by poettering** [comment]
so, wouldn't it make sense to call repart twice? i.e. first to create the basic structure. then you'd do `systemd-tmpfiles --image=` and `systemd-dissect --copy-to` and then you would call `systemd-repart` again, to add in verity?

**Comment by DaanDeMeyer** [comment]
Hmm, that would actually work I think, and just not use CopyFiles= at all.

But with that approach, I'd like to be able to tell repart what partitions to create in each run, since I want the user to be able to supply all partition definitions in the same directory, but that could include verity, so we'd need a CLI switch to tell repart whether to apply the verity stuff or not.

**Comment by poettering** [comment]
i mean, sooner or later people might want to run the whole series:

1. systemd-repart --image= (for basic partitions)
2. systemd-tmpfiles --image= (for basic hierarchy)
3. systemd-dissect --copy-to (to populate hierarchy)
4. systemd-sysusers --image= to create users
5. systemd-firstboot --image= (to provision basic settings)
6. bootctl --image= (to install boot loader)
7. systemd-repart (to finalize verity)

**Comment by poettering** [comment]
It probably would make sense to teach systemd-firstboot and systemd-dissect some additional tricks to make this comprehensive.

i.e. systemd-dissect should probably gain a tool "--reset-timestamp" or so, for resetting all times back to zero, and systemd-firstboot should probably gain "--generalize" or something like that which removes machine-id/random seeds and stuff.

**Comment by poettering** [comment]
> But with that approach, I'd like to be able to tell repart what partitions to create in each run, since I want the user to be able to supply all partition definitions in the same directory, but that could include verity, so we'd need a CLI switch to tell repart whether to apply the verity stuff or not.

Sounds reasonable. Maybe add --filter-partitions= or so, where you can list part type uuids, either as allowlist or as denylist or so, and we'd not operate on what is listed.

**Comment by DaanDeMeyer** [comment]
I was thinking of just adding a --verity switch really. This seems pretty specific to the verity use case, not sure if we should make it more generic than that.

**Comment by DaanDeMeyer** [comment]
Also for completeness, while this approach will work for almost all our usecases, it won't work for squashfs or other read-only filesystems, since that has to be done with CopyFiles=.

I wonder if we should stick with the current approach (at least for final images) in mkosi after all, if gpt is requested, run repart once beforehand, mount everything with systemd-dissect, run all the other installation steps, unmount, and run repart again to format any verity partitions if needed.

read-only filesystems are still really weird though. Ideally they'd support some kind of staging area, so that you can write to them as like any other filesystem, and then have a finalize command after which it becomes compressed and read-only. Without that, maybe we need some kind of hybrid approach. e.g. tell repart not to format squashfs partitions immediately, just like the verity ones, and simply write to directories on the host filesystem during the host install phase, and then copy to the squashfs when running repart a second time. The issue with that is that you run into the CopyFiles= limitation I'm reporting here again. So you'd still need some kind of automatic exclude so that files don't end up duplicated across squashfs partitions. 

There's also minimized images. Those probably need explicit support from repart as well. The way it happens in mkosi is we generate a filesystem, minimize it, and then use the minimized size to accurately size the partition. I suppose for mkosi that would mean doing the same as with read-only filesystems, write to directories on the host system, and then when repart is executed a second time, format and populate the partition's filesystem outside of the disk image, minimize it, and use that size to accurately size the partition, and then use the minimized filesystem as a CopyBlocks= source to populate the partition. But again here, when populating the minimized filesystem, we'll run into the same CopyFiles= issue I mentioned here again. So we'll probably need some special handling for root partitions in repart to exclude files that already have a dedicated partition.

The question is whether it should be configured by the user via e.g. CopyExclude= or whether repart should try to figure it out itself.

**Comment by DaanDeMeyer** [comment]
Another idea would be to have two separate "stages" in repart, "staging" and "finalize". "finalize" would be enabled with --finalize, and "staging" would be enabled with --staging.

In "staging" mode, we would not format verity, replace any read-only filesystems with ext4 instead, and calculate sizes for partitions without taking into account whether they're supposed to be minimized. This staging image can then be mounted with systemd-dissect and populated as usual. Then, when we call repart a second time in "finalize" mode, any partitions that are configured to be minimized are minimized, other partitions are moved around to accommodate the new minimized partitions, the ext4 filesystems are mounted and used as root for the actual read-only filesystem and verity partitions are formatted.

This approach would mean that regardless of whether read-only or minimized partitions are used, the logic to populate the partitions with systemd-dissect and systemd-tmpfiles is the same and we don't need to use CopyFiles= for read-only or minimized partitions to make things work. Using ext4 as a staging area for the read-only filesystems shouldn't be a problem as these can't be populated in place anyway so the original source tree is always going to come from another filesystem regardless, whether's it's an ext4 filesystem generated by repart or the host filesystem.

**Comment by DaanDeMeyer** [comment]
So the replace squashfs with ext4 idea isn't exactly trivial, since you can't just convert the ext4 to squashfs in place, you'd have to generate the squashfs outside of the disk image and then copy it back in over the ext4 staging filesystem, which seems rather inefficient and ugly, but it's the best I can come up with that still allows us to keep a unified interface to populate a disk image regardless of what options are used for the partitions.

So staging mode would mean:
- Ignore to be implemented `Minimize=` setting on partitions
- Replace read-only filesystems with ext4 to be used as a staging area
- Don't generate verity hash/sig partitions

And finalize mode would mean:
- Minimize existing partitions with `Minimize=` setting enabled. For ext2, ext3 and ext4, `resize2fs` should work in place, for btrfs, we'll have to use a temporary loop device to recreate the btrfs filesystem and pass the --shrink option to mkfs.btrfs. Other filesystems we'd just not support minimization.
- Compact partitions after minimization (reduce size of minimized partitions, and move offsets of following partitions forward to take up the space freed by minimization, but make sure padding is still respected)
- For partitions with read-only filesystems configured, mount the existing partition, create a new loop device with same size as the existing partition, format that new loop device with the read-only filesystem using the existing mounted partition root as the source tree, and afterwards replace the existing partition with the contents of the loop device.
- Generate verity hash/sig partitions

I'd probably make the finalize mode a completely separate codepath just after we've loaded the partition table so that in finalize mode we only do the mentioned things and absolutely nothing else.

This approach wouldn't be the most efficient one, but it seems like it would be easy to use:

- run repart once with mode = "staging", 
- populate the staging image using all the other tools with the --image switch
- run repart again with mode = "finalize" on the staging image

**Comment by poettering** [comment]
note that homed already contains offline calls to resize2fs. we could generalize, add similar support for btrfs offline resize and then implement a "Minimize=" option in repart with it. Might be kinda nice, since it could be a "smart" minimize, i.e. a bisection loop that takes SizeMin= and SizeMax= into account.

so, let me sort stuff we really need to cover:

a. create partitions
b. create directories
c. create subvolumes
d. copy in OS files (depends on c)
e. minimize fs (depends on b, c, d)
f. encrypt fs (depends on e)
g. calculate verity fs (depends on e)
h. sign verity (depends on g)
i. write verity root hash to partition uuids (depends on e)
j. run tmpfiles on it (depends on d)
k. run sysusers on it (depends on d)
l. run bootctl on it (depends on a)
m. run firstboot on it (depends on d)
n. generate UKI with root hash (depends on e)
o. copy UKI in (depends on a)

which is quiet a complex dependency tree...

and it's not even complete, since I guess populating and sealing of root fs via verity must be done before we write UKI into ESP.

I am currently leaning towards this:

1. try to prepare as much as we can in a staging tree, and let repart package it up.
2. since we cannot create btrfs subvolumes in a staging tree most likely (given it can be backed by a non-btrfs fs), this probably then means we should add MakeSubvolume= to repart files after all, to complement MakeDirectory=. And maybe do that in a syntax of `<name>:<flags>`. i.e. `MakeSubvolume=/foobar:ro`. This would need to implemented carefully in repart: i.e. create the subvolume before copying in files, mark it read only afterwards.
3. add a MinimizeFileSystem= natively to repart, for creating minimal file systems. Question is how to implement that best. One idea is via bisection of making/populating the fs. Other idea is via bisection of offline shrinking. 

With that we could first arrange everything in a staging dir, even run tmpfiles/sysusers/firsboot on it. The we'd glue it all together with repart, minimized. And then finally install kernel/boot laoder into a fixed size ESP.

**Comment by poettering** [comment]
so here's another idea I just had, which I think I kinda like.

what about introducing a set of xattrs that copy_tree() optionall honours, that tweak its behaviour. something like this:

```
metacopy.subvol=1
metacopy.rosubvol=1
metacopy.chattr=0x4711
metacopy.stop=1
```

Under the assumption that all relevant file systems support xattrs these days but they differ on support of subvol/rosubvol/chattr these xattrs could carry additional info that we'd honour when copying such a tree onto a file system that supports these special concepts.

Specifically, when encountering `metacopy.subvol=1` or `metacopy.rosubvol=1` on a directory inode, CopyFiles= (and similar calls in tmpfiles) will try to create the dir as a subvolume, and use a dir as fallback. When encountering `metacopy.rosubvol=1` it would mark the subvolume as read-only after use. When encountering `metacopy.chattr=…` it would set chattr flags on the copied inode. And then, `metacopy.stop=1` would tell the copy logic to exclude the inode this is set on from copying unless it is the root of what shall be copied.

This would tne allow us prepare everything in the staging tree: create the whole hierarchy in a staging tree, set some special values, and then have repart just glue it all together, with the right concepts.

What do you think?

**Comment by poettering** [comment]
interpretaion of these concepts would be guarded by new flags in `CopyFlags`. i.e. `COPY_HONOUR_XATTR_METACOPY_SUBVOL`, `COPY_HONOUR_XATTR_METACOPY_CHATTR` and `COPY_HONOUR_XATTR_METACOPY_STOP`. And then we would set all three for CopyFiles= in repart and `C` lines of tmpfiles.d at least.

And there probably should be COPY_HONOUR_XATTR_METACOPY_STRIP or so as another flag: when set we'd drop all xattrs starting with `metacopy` when copying xattrs

**Comment by DaanDeMeyer** [comment]
That still means mkosi has to figure out where it should set `metacopy.stop` on depending on which partitions are configured in repart. I would very much prefer if mkosi didn't have to concern itself with all that logic. Same with subvolumes really, the user should just be able to supply a tmpfiles snippet with the subvolume stuff in it and the only thing mkosi should have to do is pass that file to systemd-tmpfiles when it executes it. The only thing mkosi I want mkosi to be doing ideally is to just run the tools in the right order with the right configuration and leave everything else to the systemd tooling.

That's why I like the staging idea so much, mkosi just has to run systemd-repart in staging mode, mount the resulting image with systemd-dissect, and it has a ready-to-go root mount that it can start populating (run package manager, tmpfiles, firstboot, ...). All the files will automatically end up in the right partitions without any involvement required from mkosi's side.

The only tradeoff is that we need a "staging" concept in repart, because partitions can't always be minimized in place, and read-only filesystems need a staging area so they can be populated, so we have to put another filesystem in there temporarily to allow populating the read-only filesystem and then use that as the source for the actual read-only filesystem later.

**Comment by poettering** [comment]
what i dislike about the idea of staging-on-disk-image as opposed to staging-on-host-fs is the sizing question. It means you have to pick a size first.

**Comment by poettering** [comment]
so, i started out with the staging-on-disk-image model with mkosi, and as we kept adding stuff such as minimization and squashfs and tarball output and such i figured its kinda broken to try to hard to stick to it, and instead we should really go for the staging-on-host-fs concept everywhere, to make things systematic again, and unify codepaths again.

**Comment by poettering** [comment]
so if you don't like the `metacopy.stop=1` idea. what about this idea: make the copy logic in repart smarter. automatically stop descending further into recursive copy once we hit one of inodes that we already would copy otherwise.

implementation would be like this: before copying anything, do stat() on all inodes directly pointed to by CopyFiles=, and collect their st_dev/st_ino into a `Set` object. Then, pass that to copy_tree() as a denylist: whenever we descent the tree and reach an inode matching an entry in the `Set` we'll skip it.

that should nicely cover it, no?

**Comment by DaanDeMeyer** [comment]
Yeah, that's similar to what I was thinking to solve that problem without doing staging (I was going to use paths, but the inode stuff is way more interesting). 

Still, I'd very much like to avoid reinventing tmpfiles with xattrs. What about running tmpfiles as a library before populating the filesystems (except for read-only filesystems) in repart?

**Comment by DaanDeMeyer** [comment]
What about adding something to tmpfiles that lets it set the xattrs based on what's in the the tmpfiles snippets? So that we can run it on the staging area to just have it set xattrs. And then the copy logic can pick up on the xattrs.

**Comment by DaanDeMeyer** [comment]
Yes, but for the stuff it can't apply, wouldn't it be great if it could set the `metacopy` xattrs instead? So that it can be picked up later by repart?

**Comment by poettering** [comment]
sure, i guess we could teach tmpfiles.d to generate these metacopy xattrs indeed. but probably should be optional

**Comment by DaanDeMeyer** [comment]
One thing I'm worried about is that incremental mode is going to slow down quite a bit in mkosi when building disk images, since we have to copy the full staging tree to the disk image every time if we do staging outside of the disk image itself.

I first thought about doing shenanigans with btrfs subvolumes and btrfs send/receive, but that's awfully filesystem specific. So I figured, what if we added casync support to sysupdate and used sysupdate when in incremental mode to update an existing disk image?

So we'd populate the new staging area of the final image, optionally based on a cached version of the staging tree. And then if we're building a disk image and one already exists, instead of building it from scratch with repart, we update a casync store based on the staging tree, and then use sysupdate to deploy the update to the disk image, copying only what's necessary instead of the full contents.
