### ISSUE TITLE
systemd-user-session.service ordered after remote-fs.target

### ISSUE THREAD

**Issue by fmore-xyz** [systemd/systemd#24792]
### systemd version the issue has been seen with

251

### Used distribution

openSUSE TW

### Linux kernel version used

Not relevant

### Component

systemd

### Expected behaviour you didn't see

Being able to log in even if the network fs are not setup yet.

### Unexpected behaviour you saw

I can't log in until remote-fs.target is started which can take time before network is online.

I think it is due to systemd-user-session.service that has `After=remote-fs.target` and `remote-fs.target` is ordered after `iscsi.service` which has in its turn `After=network-online.target`, see https://github.com/open-iscsi/open-iscsi/blob/master/etc/systemd/iscsi.service.template.

I don't understand why systemd-user-session.service must wait for remote filesystems.

**Comment by poettering** [comment]
remote-fs's only purpose is to be able to delay things like logins until remote fs is up. Don't use it if you don#t want this. i.e. drop "nofail" from your fstab entry

**Comment by poettering** [comment]
ah, iscsi is broken. They shouldn't pull in network-online.target. That's really an iscsi packaging bug.

**Comment by fmoreau** [comment]
thank you, I'll open a bug at  https://github.com/open-iscsi/open-iscsi.

Do you have a link to the similar issue on Fedora ?

**Comment by fmoreau** [comment]
After thinking about what you wrote, I'm still wondering why users need to wait for remote-fs.target. The only path that is a concern for users is /home. Therefore I still don't understand why users would need to wait for all other configure remote fs on the system.

**Comment by poettering** [comment]
Well, the idea of remote-fs.target is that stuff that should be available after boot completed is added to it. Question is how to define "after boot completed". At the most basic we figured to say "once we open the floodgates to allow regular users to login" is a good thing. And that's really what systemd-user-session.service does.

If you don#t want to synchronize things like that on remote-fs.target the whole concept serves no purpose.

**Comment by poettering** [comment]
> Do you have a link to the similar issue on Fedora ?

See this thread:

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/HACVEJ3FMOIM2TOENOVH5CPOUNR7NCMS/#BNWBPMKNG7VZI4XREEKZKPBYZ6JMPCYQ

**Comment by fmoreau** [comment]
This concept is strange especially since systemd aims at parallelize services during boot.

I agree with you that the definition of "after boot completed" is subjective.

In regard of a simple daemon (with no need to access to the network), local-fs.target could be the target meaning "after boot completed" (in fact even local-fs.target is strange because if the service only need to access to /var for example var.mount would be the right definition).

For a daemon accessing the network, remote-fs.target is the definition but again for finer granularity it could specify the real paths it needs instead.

But for users, only /home should be needed. If /home is on a network fs then After=home.mount should automatically takes care of the right ordering (against the network stuff), no ?

**Comment by fmoreau** [comment]
In fact automount units for mount units are what socket units are for service unit. To increase parallelization, /etc/fstab could be used to generated automount units insteand of mount units.

**Comment by poettering** [comment]
> In regard of a simple daemon (with no need to access to the network), local-fs.target could be the target meaning "after boot completed" (in fact even local-fs.target is strange because if the service only need to access to /var for example var.mount would be the right definition).

Regular services wait for basic.target, which is ordered after local-fs.target, but not after remote-fs.target.

System services have to explicitly order themselves after remote-fs.target if they want, but are implicitly (transiently) ordered after local-fs.target.

systemd-users-sessions.service is explicitly ordered after remote-fs.target

**Comment by poettering** [comment]
> In fact automount units for mount units are what socket units are for service unit. To increase parallelization, /etc/fstab could be used to generated automount units insteand of mount units.

You can request that, via x-systemd.automount. But we don#t do that by default, because this cannot work for nested stuff, and can create deadlocks, if stuff needed to etsablish automounts ends up accessing the stuff on it.

**Comment by poettering** [comment]
> In regard of a simple daemon (with no need to access to the network), local-fs.target could be the target meaning "after boot completed" (in fact even local-fs.target is strange because if the service only need to access to /var for example var.mount would be the right definition).

You can define services that only require /var/, if you like. Set DefaultDependencies=no in that case and you lose the implicit dep on basic.target/local-fs.target. But if you do this you really should know what you are doing, because it means you cannot just rely on other services to be around, i.e. that /run is initialized or /tmp is mounted (i.e. you cannot even use various shell constructs that are backed by temporary files!). 

Allowing services to run in a seriously limited environment is doable, but requires careful programming, and declaration of minimum deps. Because that's hard we provide DefaultDependencies=yes (which is the default), which basically gives you a good set of functionality you don't have to think about, i.e. stuff is generally already mounted, logging works, /run is set up, /tmp works and so on.

And this is similar for regular user stuff. People generally expect that various things just work when user code runs. We provide remote-fs.target as a barrier that people can put some of the stuff in front.

Anyway, I think the discussion here is pointless. If you don#t want to sue remote-fs.target then just don't. mask it or whatever. But this is not a discussion forum here. It's a bug tracker, and as indicated the bug here is in iscsi, not systemd.

**Comment by fmoreau** [comment]
> systemd-users-sessions.service is explicitly ordered after remote-fs.target

Again there's no such needs. For users, "boot completed" meaning is  "I can access to my $HOME". They don't care about waiting for all other fs on the system. Can't this be achivied with `RequiresMountFor=/home` ?

**Comment by fmoreau** [comment]
> Anyway, I think the discussion here is pointless. If you don#t want to sue remote-fs.target then just don't. mask it or whatever. But this is not a discussion forum here. It's a bug tracker, and as indicated the bug here is in iscsi, not systemd.

ok

**Comment by poettering** [comment]
> Again there's no such needs. For users, "boot completed" meaning is "I can access to my $HOME". They don't care about waiting for all other fs on the system. Can't this be achivied with `RequiresMountFor=/home` ?

That might be the case for you, but in general it is not. Poeple might want to access some shared dir /shared/ or so, or might have their home dir outside of /home for some reason. Hence it's not correct to assume /home/ alone would suffice. You cannot know this. Hence we have `remote-fs.target` as a generic hook point where all these things can be plugged before. if you don't like it, then don't use it.

**Comment by fbuihuu** [comment]
disabling it is not a solution because I still want the remote fs to be set up at boot but most of the times users don't need to access them right after logging. And if there's no network access during boot, the boot process is stuck until a timeout expires, which is not good. Maybe I should switch to automount instead but the remote-fs.target concept seems strange to me.

Now I'm wondering how things work if /var is a remote fs. I chose /var because it's likely to be used by a lot of services that are scheduled after local-fs.target but not after remote-fs.target by default. If /var is migrated to a network fs should admin manually change the ordering of the services ?

If home dir is outside of /home, then `After=home.mount` contained in systemd-user-sessions.service is incorrect.
