### ISSUE TITLE
How to disable systemd-logind from automatically opening /dev/dri/Card0

### ISSUE THREAD

**Issue by zhijie-zhang** [systemd/systemd#25034]
### Describe the solution you'd like

disable systemd-logind from automatically opening /dev/dri/Card0

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
