### ISSUE TITLE
journal catalog: no way to provide a downstream Support: link

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#2516]
The catalog files shipped by systemd list in the Support: [1] field http://lists.freedesktop.org/mailman/listinfo/systemd-devel as contact address.

This is apparently confusing for users of downstream distros, as e.g. shown in [2]
Shouldn't downstreams be able to customize that field and e.g. point at their own bug tracker?
Maybe in addition to the upstream fdo mailing list.
Can Support: be specified twice?

[1] http://www.freedesktop.org/wiki/Software/systemd/catalog/
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769187

**Comment by johannbg** [comment]
Multiple defined same type entry's are bad and would just confuse the end user more since the end users would never be able to tell which one he should use.

Distribution already can ( and do ) define this in os-release 
HOME_URL=
SUPPORT_URL=
BUG_REPORT_URL=
which should be used for this, distribution should not have to define this information in multiple location in systemd.

The real underlying bug here is that those entry's aren't being sourced ( if set ) and used where they should. 

Unfortunately distributions ( or at least one of them ) seem to be already misusing and mutilating the os release file with undocumented entry's like this to confuse end users, potentially turning a messy situation even messier when they start requesting that those entry's will be added in addition to the documented ones stated above as well . 
REDHAT_BUGZILLA_PRODUCT=
REDHAT_BUGZILLA_PRODUCT_VERSION=
REDHAT_SUPPORT_PRODUCT=
REDHAT_SUPPORT_PRODUCT_VERSION=

**Comment by poettering** [comment]
Would be happy to take a patch that would override the support field on the configure command line. And if not specified the value should probably not default to systemd-devel, but to whatever is defined on the build machine's /etc/os-release SUPPORT_URL. And if that doesn't exist HOME_URL or so...

(And yes, Support: can appear twice or more times, but I wouldn't bother really)

**Comment by johannbg** [comment]
@poettering can you explain what purpose these lines are supposed to serve 
Subject:
Support:
I mean the message associated with the message ID clearly explains what the problem is so why would you a) provide a Subject Line and b) want users to contact upstream in the first place? 

Perhaps it's just better to drop those lines here upstream but retain the Defined-By line since you actually need that to trace back who this messages belongs to and or is owned by.

**Comment by poettering** [comment]
Consider reading the docs:

https://wiki.freedesktop.org/www/Software/systemd/catalog/

**Comment by johannbg** [comment]
Had already read the docs did not see any practical value or logic for the Subject and Support lines  or use case hence the question for further explanation. 

To me the subject line serves no purpose since a) the administrator reads the message text which is followed by in depth message from the catalog if he does not understand it and b) the support line is unnecessary since the entire message being provided should be self explanatory and accommodated by a hint ( if nessary ) to solve the configure error in the system of the administrators part and if he does not understand it, he should be directed at a documentation not support since he would not be able to understand any of the response he would get from "support" since he did not understand the message itself in the first place right. 

On top of that the fact is the entire purpose of the in depth explanation of the message is to reduce load on the community ( support,developers, qa etc ) right  so sorry for my ignorance of what I am missing so what practical purpose and problems are those catalog references supposed to solve?

**Comment by poettering** [comment]
Well, Johann. If people don't grok our docs then that possibly says as much about the quality of our docs as about the intelligence of the people reading them. Thus, it's just nice to provide them with a support hotline/forum/... where they can ask their questions...

Note that these catalog messages are supposed to be exposed in graphical tools, such as Cockpit, where having a bit of structure in them goes a long way to make this auxiliary information pretty to look at in a web browser... Hence the Subject line...

**Comment by johannbg** [comment]
If the intent is gather feedback to improve documentation ( or for that matter gather submission and or requests for translation which you left out there ) in the catalog files then the conclusion must be that the support entry cannot be multiplied whether it's another support entry and or an new type support entry ( distribution support, vendor support etc ) overwritten on a global scale but always must be delivered to the upstream responsible for maintaining the catalog file(s) in question ( who are expecting to receive that feedback ) otherwise you loose that feedback and with application like cockpit using this, supporting multiple definition of the same line ( Subject, Support etc ) will undoubtedly break those applications and or cause confusion with end users ( as they would as well without them using such application but the journal output directly ) as an result of that logic dictates out of the four possible ways to handle this you should leave things as they currently are...

**Comment by poettering** [comment]
Fix waiting in #3597.
