### ISSUE TITLE
do we have any alternatives for /etc/crypttab keyscript option?

### ISSUE THREAD

**Issue by JustPlay** [systemd/systemd#25219]
https://github.com/systemd/systemd/blob/e8dc52766e1fdb4f8c09c3ab654d1270e1090c8d/src/cryptsetup/cryptsetup.c#L129

i need run a program to get the rootfs unlock passwd in the initramfs

thanks

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
