### ISSUE TITLE
mounting swap partitions using nofail

### ISSUE THREAD

**Issue by MischaBaars** [systemd/systemd#25220]
### systemd version the issue has been seen with

250.8

### Used distribution

Fedora 36

### Linux kernel version used

5.19.16-200.fc36.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

Hello,

According to swapon(8), the /etc/fstab nofail mount option is supposed to be supported for swap partitions:

-e, --ifexists
           Silently skip devices that do not exist. The /etc/fstab mount option nofail may also be used to skip non-existing device.

However, with a /etc/fstab like this:

UUID=1eb7f4d4-93a5-4450-a031-4b24124f6c8b       /                                               ext4    defaults,nofail                                 1 1
UUID=b066a192-3aa0-4daf-b5cc-39d6fe4466aa      none                                            swap    defaults,nofail                                 0 0     UUID=2c35e1f8-c4ea-49d0-bdf8-ef1383b1798e      none                                            swap    defaults,nofail                                 0 0     

where the second UUID denotes a partition on one computer and the third UUID denotes a partition on a second computer, booting results in a timeout for the non-existent UUID on both computers. For the first UUID, the root partition's UUID, the nofail option does seem to be accepted, and booting without it results in errors on the network booted computer.

Best regards,
Mischa Baars.

### Unexpected behaviour you saw

Nov 01 11:36:28 tp07 systemd[1]: dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.device: Job dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.device/start timed out.
Nov 01 11:36:28 tp07 systemd[1]: Timed out waiting for device dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.device - /dev/disk/by-uuid/b066a192-3aa0-4daf-b5cc-39d6fe4466aa.
Nov 01 11:36:28 tp07 systemd[1]: Dependency failed for dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.swap - /dev/disk/by-uuid/b066a192-3aa0-4daf-b5cc-39d6fe4466aa.
Nov 01 11:36:28 tp07 systemd[1]: dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.swap: Job dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.swap/start failed with result 'dependency'.
Nov 01 11:36:28 tp07 systemd[1]: dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.device: Job dev-disk-by\x2duuid-b066a192\x2d3aa0\x2d4daf\x2db5cc\x2d39d6fe4466aa.device/start failed with result 'timeout'.

**Comment by MischaBaars** [comment]
On closer inspection:

Perhaps it would be possible to have a x-systemd.conditionhost directive implemented from the ConditionHost directive in an upcoming systemd release, such that ConditionHost can be used from /etc/fstab. This would solve the problem.

Best regards,
Mischa Baars.

**Comment by poettering** [comment]
sorry, but this would be racy. devices can take any time to pop up and initialize they want. Thus depending on how early we run the suggested existance test the swap devices might not be there yet or they might. Given we do swap stuff really early it's probably going to be more often the case that the device does not exist than that it does.

or in other words: if you define a swap device then it tells systemd to *wait* for the device to pop up and then mount it. Hence it's necessarily racy if you'd skip the waiting, and just run such a check right-away.

Hence, this isn#t really implementable in a race-free fashion. The swapon switch comes from a simpler time I guess, where the whole system knew a "settled" state where all devices possibly connected have been known to have shown up. But since decades we live in a plug and play world where basically everything can pop up any time, and thus you need to know exactly what to wait for.

hence, closing. hope that makes sense

**Comment by Kerrnel** [comment]
The whole purpose of nofail would be to move on if not present. Hanging, waiting, racing ... they all ignore the fact that I said - do not do that via nofail. Does not make sense.
