### ISSUE TITLE
[Question] `/run/user/public/${UID}`

### ISSUE THREAD

**Issue by jb2170** [systemd/systemd#25245]
### Component

systemd

### Is your feature request related to a problem? Please describe

Hey I think this is the right place / project to ask?

The `/run` folder is great, permissions managed by the system, and `/run/user/${UID}` is a good place to put private user AF_UNIX sockets, with permissions `700` by default. 

I was wondering if there's an equivalent folder with permissions `755` (umask `022`) say to put files / sockets that a user wants to be publicly available on the system, eg unix sockets for a server being run by a user. `/tmp` seems a bit chaotic, and it is easy for one user to DOS another user's server by creating a file where they the first user wants to bind a socket. A well-permissioned folder akin to `/run/user`, say `/run/user/public`, managed by systemd could be nice.

Does such a folder already exist?

### Describe the solution you'd like

However `/run/user/${UID}` is created, do that also for `/run/user/public/${UID}` but with permissions `755` instead of `700`.

### Describe alternatives you've considered

`/tmp` is a bit chaotic. Using `mktemp` / systemd-tmpfiles creates a different filepath each time: a consistent filepath / hierarchy like `/run/user` would be nice

### The systemd version you checked that didn't have the feature you are asking for

251 (251.7-1-arch)

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by poettering** [comment]
(But no, this does not exist. User services typically do not provide services to other users, hence there never was any need or desire to add that.)
