### ISSUE TITLE
suspend-then-hibernate: add option to force early hibernate

### ISSUE THREAD

**Issue by junocomp** [systemd/systemd#25269]
### systemd version the issue has been seen with

252-2

### Used distribution

Debian Bookworm

### Linux kernel version used

6.0.0-2-amd64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Since 252 I can no longer suspend-then-hibernate using `systemctl suspend-then-hibernate.`

If I execute the commands to `suspend` only it does work, same for `hibernate`. But not in combination

UPDATE: I tested on `Manjaro` which is using `systemd 251.7` and is working fine.

**Comment by bluca** [comment]
What does "not work" mean? Describe the problem in details, and pastebin verbose logs

**Comment by junocomp** [comment]
@bluca As I mentioned on my main post.

When executing `suspend-then-hibernate` it will go into Suspend mode but it will not follow into Hibernate after. This is what my login.conf and sleep.conf look like.

```
[Login]
HandleLidSwitch=suspend-then-hibernate
```

```
[Sleep]
HibernateDelaySec=300s
```
I checked dmesg but it doesn't show any errors. If you have any other way of tracking it, then I can paste it here.

**Comment by bluca** [comment]
That's expected, see the manpage. Hibernate will happen when low on battery.

**Comment by junocomp** [comment]
@bluca I think you are miss understanding my issue. I did have it working before systemd 252.

**Comment by bluca** [comment]
https://www.freedesktop.org/software/systemd/man/systemd-sleep.conf.html#suspend-then-hibernate

**Comment by junocomp** [comment]
I set mine to go into suspend-then-hibernate by default.

```
rm /usr/lib/systemd/system/systemd-suspend.service
ln -s /usr/lib/systemd/system/systemd-suspend-then-hibernate.service /usr/lib/systemd/system/systemd-suspend.service
```

Either way, if I execute the systemd command or wait until it gets to 5%, hibernate is never followed after suspend.

**Comment by TriMoon** [comment]
> @junocomp,
> I set mine to go into suspend-then-hibernate by default.
> 
> ```
> rm /usr/lib/systemd/system/systemd-suspend.service
> ln -s /usr/lib/systemd/system/systemd-suspend-then-hibernate.service /usr/lib/systemd/system/systemd-suspend.service
> ```
> 
> Either way, if I execute the systemd command or wait until it gets to 5%, hibernate is never followed after suspend.

Looks like you are messing manually with your systemd there :thinking: 
I wouldn't suggest messing like that before you absolutely know what your're doing...

Why didn't you choose the documented way to configure stuff?

On my current Manjaro, See:
```
#> man systemd-suspend-then-hibernate.service`
#> man systemd-sleep.conf`
#> cat /etc/systemd/sleep.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation; either version 2.1 of the License, or (at your option)
#  any later version.
#
# Entries in this file show the compile time defaults. Local configuration
# should be created by either modifying this file, or by creating "drop-ins" in
# the sleep.conf.d/ subdirectory. The latter is generally recommended.
# Defaults can be restored by simply deleting this file and all drop-ins.
#
# See systemd-sleep.conf(5) for details.

[Sleep]
#AllowSuspend=yes
#AllowHibernation=yes
#AllowSuspendThenHibernate=yes
#AllowHybridSleep=yes
#SuspendMode=
#SuspendState=mem standby freeze
#HibernateMode=platform shutdown
#HibernateState=disk
#HybridSleepMode=suspend platform shutdown
#HybridSleepState=disk
#HibernateDelaySec=120min
```

Anyhow i don't use this stuff at moment on my desktop, but you might try these pointers :wink: 

Here is the current original contents of `/usr/lib/systemd/system/systemd-suspend.service` on my Manjaro, for you to be able to restore it:
```
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=System Suspend
Documentation=man:systemd-suspend.service(8)
DefaultDependencies=no
Requires=sleep.target
After=sleep.target

[Service]
Type=oneshot
ExecStart=/usr/lib/systemd/systemd-sleep suspend
```

**Comment by n-peugnet** [comment]
@bluca:
> https://www.freedesktop.org/software/systemd/man/systemd-sleep.conf.html#suspend-then-hibernate

Well this is a little bit easy to refer to the latest docs which [changed since v252](https://github.com/systemd/systemd/commit/91ea7ebcdfac18137a1f3d1e89d99917ad66d87f).

On v251 the manual entry for this option was:

     suspend-then-hibernate
           A low power state where the system is initially suspended (the state is stored in RAM).
           If not interrupted within the delay specified by HibernateDelaySec=, the system will be
           woken using an RTC alarm and hibernated (the state is then stored on disk).

Why did this change instead of creating another power saving mode. And how to use the previous behaviour. I dont want my computer to stay in S3 state when it is >5% battery. I want it to go to S4 state after `HibernateDelaySec` of S3 state.

**Comment by bluca** [comment]
That is not supported anymore, as it was half-broken and made very little sense, it was just a workaround for missing functionality that is now implemented. If you want to hibernate it immediately, then just do that.

**Comment by n-peugnet** [comment]
> If you want to hibernate it immediately, then just do that.

I don't want to hibernate. Resume from hibernation is around 45s on my system while resume from suspend is instantaneous.

I want to always suspend, then after 30m hibernate. If I need to quickly reuse my computer after I suspended it, it resumes instantaneously. And if I need to use it later, then I can probably wait 45s, so I want it to hibernate to save power.

**Comment by bluca** [comment]
Why 30 minutes and not, say, 4 hours?

**Comment by n-peugnet** [comment]
> Why 30 minutes and not, say, 4 hours?

Why is it important? This is my setup, which was previously configurable with `HibernateDelaySec`. I happen to like the value of 30m (in fact I just checked and I used 45m, but I don't see the point of this question).

-------

I also have this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023483 which is a little bit different, and forced me to rollback to v251. Should I open a new issue here for this ?

It might be related to https://github.com/systemd/systemd/pull/24336/

**Comment by junocomp** [comment]
@n-peugnet I also had to downgrade

**Comment by yuwata** [comment]
Tentatively reopen this to make more users can easily find this 'issue' and join the discussion. Though, I am not sure the current behavior is expected or not.

**Comment by bluca** [comment]
The current behaviour is fully expected and documented

**Comment by yuwata** [comment]
Hmm, but as reported, v252 changes the behavior. That's true regardless of it is expected or not.

How about to honor the setting if specified instead of using ACPI_BTP or calculated discharging rate?
And/or, introduce another knob(s) to control the interval for calculating discharging rate?

Anyway, please do not close this page so quickly.

**Comment by bluca** [comment]
> Hmm, but as reported, v252 changes the behavior. That's true regardless of it is expected or not.

Yes, and it was a 6-months long project, widely advertised and listed in the changelog as expected. The purpose of this functionality is to avoid power getting cut and data loss, so the previous implementation was just a bandaid, and a bad one at that, and it is not something we want to support because there's just no way to guarantee that there will be no data loss or worse.

The use case of "I happen to like the value of 30m" is not sensible and definitely not something to support.

**Comment by n-peugnet** [comment]
> The purpose of this functionality is to avoid power getting cut and data loss

Once again, this is the purpose _now_ and I think it is clear to everyone that _you prefer_ it over the previous one.

> so the previous implementation was just a bandaid, and a bad one at that, and it is not something we want to support because there's just no way to guarantee that there will be no data loss or worse.

The previous purpose of this feature was to go into hibernation after a period of time. Which can be used to save _power_ and _battery life_. The current behavior does not allow that so it is not _just better_.

> The use case of "I happen to like the value of 30m" is not sensible and definitely not something to support.

At least accept that this is a matter of preference, as _you prefer_ to have your battery drawn untils it's 5% before it goes to hibernation. Whereas _I prefer_ my computer to go into hybernation pode after a period of time to _save battery_.

First I have never experienced a lows of data as 30min is enough for the battery to survive in suspend mode even at 5%. But most importantly, I don't see why it would not be possible to have **both**. I.e. have the computer to go into hibernation after a period of time **and** if it goes below 5%.

**Comment by bluca** [comment]
> The previous purpose of this feature was to go into hibernation after a period of time.

No. The purpose was to attempt to provide a way to suspend for a safe amount of time and then hibernate to avoid power loss. It obviously did not work reliably, and required manual configuration changes each time depending on device, current battery status, wear rate, and so on - in other words, it was unreliable and mostly broken for all intents and purposes. This is about safety, not preferences. Supporting dangerous configurations is out of the question, sorry.

Besides, you can still hack it to ignore actual battery status, which means only the configured time will be used - with the understanding that doing so means you might incur in data loss or device damage, and it's entirely on you if it happens. You simply have to add a drop-in for the suspend-then-hibernate service to make the battery status inaccessible, eg `InaccessiblePaths=/var/lib/systemd/sleep/ /sys/firmware/dmi/entries/ /sys/class/power_supply/`

**Comment by DaanDeMeyer** [comment]
As @bluca says, we should always go to sleep if low on battery to avoid data loss.

That said, If users want their laptop to hibernate earlier after some fixed amount of time spent suspended, I don't see why we couldn't support that. Low battery notification should always override the user provided value though. I'm not sure if messing around with the current option anymore is a good idea, so we should probably add a new setting `HibernateDelayMaxSeconds` or so that specifies the **maximum** amount of time we'll spend in the suspend state.

**Comment by yuwata** [comment]
I agree with @DaanDeMeyer's idea. But, in stead of introducing `HibernateDelayMaxSeconds=`, I think it is better to make `HibernateDelaySeconds=` specify the maximum amount of suspend time to keep backward compatibility.
And introduce e.g. `DefaultLowBatteryDetectionInterval=` or `DefaultIntervalForMeasuringBatteryDischargingRate=` to control the interval for measuring battery discharging rate.
Since v252, the meaning of `HibernateDelaySeconds=` is hijacked and now it does not mean delay, but just an initial interval to measuring discharging rate, IIRC the PRs. That breaks backward compat and confuses users.

**Comment by bluca** [comment]
Nah, supporting setups that can lead to data loss is a bad idea. As said above, this can be achieved just the same with InaccessiblePaths, at one own's risk.

**Comment by DaanDeMeyer** [comment]
> Nah, supporting setups that can lead to data loss is a bad idea. As said above, this can be achieved just the same with InaccessiblePaths, at one own's risk.

This wouldn't lead to data loss though. Again, the property set the **maximum** possible suspend time. If we get woken up earlier because of low battery, we go into hibernation earlier to avoid data loss. The only scenario where this property would take effect is when the system still hasn't gone into hibernation time by the time the specified interval expires. If the battery becomes almost drained before the specified interval expires, we go into hibernation earlier to avoid data loss. Only when there's ample battery and we don't need to go into hibernation because of low battery would this take effect. There's no chance of data loss with this behavior because low battery will always take priority.

**Comment by bluca** [comment]
Ah you mean as an additional property, got it - that's a weird use case but fine I guess, feel free to send a PR. I'll rename accordingly.

**Comment by n-peugnet** [comment]
@bluca:
> Nah, supporting setups that can lead to data loss is a bad idea.

Then you might also consider removing the `suspend` only mode.

**Comment by yuwata** [comment]
> > Nah, supporting setups that can lead to data loss is a bad idea.
> 
> Then you might also consider removing the `suspend` only mode.

Hahaha, that makes some sense. But please do not burn the thread.

**Comment by feluxe** [comment]
> I think it is better to make HibernateDelaySeconds= specify the maximum amount of suspend time to keep backward compatibility.

Yes, please. This breaking change cost me countless hours and pain over the last few days, because I was debugging a dead end: https://bbs.archlinux.org/viewtopic.php?id=281373

I also miss the old behaviour of HibernateDelaySeconds...

**Comment by OJFord** [comment]
> Why 30 minutes and not, say, 4 hours?

> The use case of "I happen to like the value of 30m" is not sensible and definitely not something to support.

Where's this '30m' coming from @bluca? Mine was set to 2h and working nicely as _I_ intended it to.

>  If you want to hibernate it immediately, then just do that.

I don't want to hibernate immediately - consider using a laptop in an office for example, you close it to take it to a meeting room, re-open it a few minutes later, you don't want to wait for resume from hibernation.

But if plans change and it ends up suspended for hours, I want to save the battery and probably don't mind the start-up delay so much coming back to it after a longer period.

(That's just for illustration - my usual use case is actually at home with a personal laptop, using and closing, not knowing if I'll use it again or not that evening, but if I do it's probably for something quick and won't be bothered if it takes too long. But if I don't, I don't want it suspended all night.)

**Comment by ezhukov** [comment]
> @bluca:
> 
> > Nah, supporting setups that can lead to data loss is a bad idea.
> 
> Then you might also consider removing the `suspend` only mode.

Indeed, the default `suspend` setup can easily lead to a battery loss. Charge goes to zero, the battery gets permanently damaged and won't charge anymore. Happened to me once, using `suspend-then-hibernate` ever since.

**Comment by jojoob** [comment]
I'm a bit late to the party but want to put my two cents anyway:

I think the fact that this was a breaking change for the "HibernateDelaySec" option for that, at least, I didn't found a reference in the release notes should be argument enough to restore the previous functionality. Don't get me wrong, I appreciate the new feature for guarantee hibernation on low battery. But if it had been possible to maintain backward compatibility this should be considered as a regression.

> that's a weird use case but fine I guess

One use case is to safe battery as @n-peugnet described. My use case is to combine fast resume within the configured delay (comfort) and automatically secure the system after that delay with hibernation (suspend to disk) with full disk encryption (security).

**Comment by DianaNites** [comment]
This is a serious security regression, as anyone who was relying on systemd to do what it said it would until version 252 is now potentially vulnerable. I *need* my (fully encrypted, verified boot) system to hibernate when I tell it to for security reasons, and until recently it did. And now it doesnt.

This is an extremely serious vulnerability and its baffling theres been a month of "debate" on whether a silent, backwards incompatible change, to an existing feature and option, that causes real world security issues is a problem or not.

Before anyone gets into it: Your threat model is not my threat model. This is within mine, and i'm sure also within plenty of organizations.

Not to mention the basic usability issues, I for one like to come back to my laptop and resume where I left off with my battery where I left it, not empty or at 5%.

**Comment by jojoob** [comment]
@DianaNites I would not name it a *serious security regression*. You can still just hibernate your system to secure the sleep state with full disk encryption. And I wouldn't rely too much on the interrupt for hibernate after a delay when your security concerns are strong. ;)

Meanwhile, anyone who can't wait for the feature to return and isn't able to downgrade can work around the regression by using a custom suspend-then-hibernate script. [I once wrote one](https://unix.stackexchange.com/questions/491482/how-to-use-uswsusp-for-suspend-then-hibernate-with-systemd/492956#492956) for the purpose of using uswsusp with systemd but it can be adopted easily.

---

> I also have this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023483 which is a little bit different, and forced me to rollback to v251. Should I open a new issue here for this ?

@n-peugnet you did you not open an issue for that, or did you? I have a very similar problem on Arch since updating from v252.1 to v252.2. Maybe you could check if v252.1 works for you as well.

**Comment by n-peugnet** [comment]
@jojoob:
> > I also have this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023483 which is a little bit different, and forced me to rollback to v251. Should I open a new issue here for this ?
> 
> @n-peugnet you did you not open an issue for that, or did you? I have a very similar problem on Arch since updating from v252.1 to v252.2. Maybe you could check if v252.1 works for you as well.

This issue is tracked there: https://github.com/systemd/systemd/issues/25356

**Comment by DianaNites** [comment]
Just because it can be worked around doesn't mean it isnt a regression. The behavior worked and was secure, and an update made it not. Thats called a security regression.

Now if everyone who was using it wants that same security, they have to first know about this issue somehow(CVE?), and then manually work around it until the proper fix comes out.

**Comment by bluca** [comment]
Given trolling has started, time to lock
