### ISSUE TITLE
behaviour of `sd_journal_next()` has been changed

### ISSUE THREAD

**Issue by pobrn** [systemd/systemd#25369]
The behaviour of `sd_journal_next()` appears to have been changed in 977ad21b5b8f6323515297bd8995dcaaca0905df (#23909) and this seems to have caused two sd-journal related pipewire tests to fail. I think the reason for the failure is that the test code assumed that `sd_journal_seek_tail()` seeks to the *current* tail and then new entries can be consumed with `sd_journal_next()`, but that no longer seems to be the case.

Pipewire issue: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2823#note_1637715
Pipewire test code: https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/ea4e5cf364d5925b992c5cb16abd2ff8872f8762/test/test-logger.c#L488

There is a change in the pipewire issue tracker that appears to fix the tests, but I would like some advice on what the proper fix is.

**Comment by ChenQi1989** [comment]
@DaanDeMeyer  @pobrn  I think the fix in https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2823#note_1637715 does make sense. Why are we reverting the original patch? 
The issue's description says "the test code assumed that sd_journal_seek_tail() seeks to the current tail ", but looking at the manual, it clearly says:
"""
Note that these calls do not actually make any entry the new current entry, this needs to be done in a separate step with a subsequent sd_journal_next(3) invocation (or a similar call).
"""
So sd_journal_seek_tail does not seek to 'current' tail, it only means seeks to the 'logical' end of the journal. 
What it does is: .type = LOCATION_TAIL
You can see it's just setting a value, it's not seeking to any 'current' entry.
I do think this is correct, because if sd_journal_seek_tail means seeking to 'current' end, then users really do not have a reliable to get the latest entry, unless its implementation is changed to including doing some sd_journal_next operation.

Also, a sd_journal_next call immediately after sd_journal_seek_tail is undeterministic, it may point to a newly added entry, but it may also point to some old entry.

My suggestion: instead of reverting the original patch, change the manual to clearly tell users to do sd_journal_previous after sd_journal_seek_tail, and similarly do sd_journal_next after sd_journal_seek_head.

**Comment by ChenQi1989** [comment]
@DaanDeMeyer ping
Please re-visit this issue, I think you've reverted a correct patch.

**Comment by yuwata** [comment]
@ChenQi1989 Could you open a new issue or re-submit the reverted commit? Otherwise, we easily forget your comment in this already closed issue page.
