### ISSUE TITLE
User-<id>.journal retaining forever

### ISSUE THREAD

**Issue by PrajwalAdsul** [systemd/systemd#25455]
### systemd version the issue has been seen with

219

### Used distribution

RHEL7

### Linux kernel version used

3.10.0-1160.76.1.el7.x86_64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

`/var/log/journal/<uuid>/user-<id>.journal` logs don't get deleted even it `MaxRetentionSec=30day` is set.

It would seem to me that it is because of length of file name of this being small looking at https://github.com/systemd/systemd/blob/f2acaf39c1f680d526df6cda8052cbf2f7f75ba0/src/libsystemd/sd-journal/journal-vacuum.c#L163-L199.

Can we fix this ?

### Steps to reproduce the problem

With normal journald.conf you can see this problem too, I would guess.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://github.com/systemd/systemd/blob/f2acaf39c1f680d526df6cda8052cbf2f7f75ba0/src/libsystemd/sd-journal/journal-vacuum.c#L163-L199
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
