### ISSUE TITLE
systemd-tmpfiles: Failed to adjust quota for subvolume "/var/lib/machines": Bad file descriptor

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#25468]
### systemd version the issue has been seen with

252

### Used distribution

openSUSE TW

### Linux kernel version used

Not relevant

### Expected behaviour you didn't see

Commit 8f6fb95cd069884f4ce0a24eb20efc821ae3bc5e introduced this regression. Basically ioctl(2), among other syscalls, doesn't work if the fd was obtained with O_PATH.

I don't see what kind of race this commit was fixing, at least in `create_directory_or_subvolume()`, so I would tempted to revert this part at least.

### Steps to reproduce the problem

On openSUSE TW with the default BTFS layout:

```
# btrfs subvolume delete  /var/lib/machines
# systemd-tmpfiles --create /usr/lib/tmpfiles.d/systemd-nspawn.conf
Failed to adjust quota for subvolume "/var/lib/machines": Bad file descriptor
```

**Comment by fbuihuu** [comment]
Cc @poettering

**Comment by poettering** [comment]
Hmm, 2e6e6168874 doesn't work for you?

**Comment by poettering** [comment]
ah, it's just the quota ioctls? i guess we need to make the same change there, and convert O_PATH to a regular fd locally if needed.

**Comment by fbuihuu** [comment]
Yes probably but as written previously I don't see which type of race the use of O_PATH in `create_directory_or_subvolume()` is supposed to fix in the first place.

**Comment by Vogtinator** [comment]
I agree, what's the reason to use `O_PATH` there instead of just opening the created directory?

**Comment by poettering** [comment]
> Yes probably but as written previously I don't see which type of race the use of O_PATH in `create_directory_or_subvolume()` is supposed to fix in the first place.

create_directory_or_subvolume() uses path_open_parent_safe() to pin the directory it operates below. Which in turn uses chase_symlinks() (which is important to implement --root= and to deal with untrusted symlink chains) which returns an O_PATH fd.

mkdirat() is happy with an O_PATH fd, already on the kernel level. hence it makes sense to model btrfs_subvol_make_fd() similar to it, and also make sure it can deal with O_PATH.

**Comment by poettering** [comment]
oh, you wonder why after creating the dir/subvol we pin it via O_PATH rather than just a regular O_DIRECTORY? well, for starters, O_PATH works on inodes we cannot open. We can still pin them. That's extremely useful when adjust access modes to them. tmpfiles is after all also run in user context where the ownership/access mode of existing inodes matters, and we must be able open up inodes that are closed down access-wise. If we'd always open the dir without O_PATH then this would possibly fail with EACCESS quite likely early on.

**Comment by Vogtinator** [comment]
> That's extremely useful when adjust access modes to them. tmpfiles is after all also run in user context where the ownership/access mode of existing inodes matters, and we must be able open up inodes that are closed down access-wise.

FWICT the only case where this can be relevant for `create_directory_or_subvolume` is if the directory/subvolume is created without `S_IRUSR`. That is actually broken with the approach of using `fd_reopen` as well, it just delays `EACCESS` to the time the reopen is attempted.

What would work is to create the subvolume with `S_IRUSR`, do $stuff with the FD and later on `fd_set_perms` will assign the attributes.

**Comment by fbuihuu** [comment]
> the dir might be pre-existing with some bad access mode. tmpfiles is not just a tool to create stuff, but also a tool to adjust modes and stuff of what is already existing.

I can see how O_PATH can help in this case but the justification of 8f6fb95cd069884f4ce0a24eb20efc821ae3bc5e is to make the code less racy. This is the part which is confusing.

**Comment by poettering** [comment]
think about this scenario: we are tmpfiles, and are supposed to create a dir or subvol if missing at some place, and adjust ownership/access mode of it. Some rogue code racing against us might watch us create the dir/subvol and then immediately replace the inode by something else, such as a regular file. if we don't ping the inode via O_PATH and validate its actually a dir as we created it then this might be a big problem, for example because the setuid flag for a file and for a dir mean very different things.

This vulnerability arises whenver privileged tmpfiles operates in dirs that are also writable to some unpriv code. To ensure we fix this we always need to create an inode then immediately pin it via O_PATH, verify it is what we asume it is, and then operate exclusively on the fd.

**Comment by polarina** [comment]
Could this fix be backported to v252-stable, please?
