### ISSUE TITLE
More visibility into systemd-networkd sysctls

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#25492]
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

systemd-networkd writes to certain sysctls but there is not a lot of visibility as a user as to what values it is writing.

This came up due to a separate (but maybe related) issue: we had a config under /etc/sysctl.d/ that was setting `net.ipv6.conf.eth0.accept_ra=2`. This was (accidentally) reapplied when someone called `systemd-sysctl`, after systemd-networkd was already started and had already configured eth0 with `IPv6AcceptRA=yes` (sysctl accept_ra=0). Since systemd-networkd doesn't reapply the sysctl value, we were getting spammed with messages from the kernel related to RA.

### Describe the solution you'd like

@chantra had an idea that I thought was simple and could cover both of these issues: what if we had systemd-networkd write its sysctl settings to `/run/sysctl.d/999-systemd-networkd.conf` when it sets the sysctls? This would provide visibility and also prevent some accidental overrides.

It's not foolproof and doesn't fix people just calling `sysctl` to change things at runtime. But it's something.

### Describe alternatives you've considered

None right now, but alternatives are appreciated

### The systemd version you checked that didn't have the feature you are asking for

251

**Comment by poettering** [comment]
Hmm, this is a bit racy though...

**Comment by anitazha** [comment]
Yea it's not ideal. That's why I'm open to better ideas :D
There was another idea to use BPF to monitor when certain sysctl changes. Maybe with BPF_PROG_TYPE_CGROUP_SYSCTL?

**Comment by poettering** [comment]
so what about this idea: let's make networkd take a lock on all sysctls it wants to manage. Specifically, take a F_OFD_SETLK/F_WRLCK file lock (i.e. an "unposix" lock for "write"), which should give us the semantics we want. systemd-sysctl could take the same locks when it does its thing, and whenever it gets EBUSY on that could print a friendly message "hey, this sysctl is apparently managed by somebody else". (or even friendlier: "this is a network interface sysctl, so I figure your network management subsystem manages this").

It must be F_OFD_SETLK/F_WRLCK and nothing else:

1. It can't be BSD flock() locks since you can take any kind of BSD lock on all fds you can open at all. This would be a vulnerability here, since sysctls are typically readable by unprivileged code, and thus any code could take the flock() and thus break systemd-sysctl.

2. POSIX locks are a horrible mess (i.e. are per-process, not per-fd and automatically released when a process closes any fd for the inode, regardless if that#s the first or last fd to it).

3. "unposix" F_OFD_SETLK/F_RDLOCK locks are also available to any kind of unpriv code

→ hence "unposix" F_OFDSETLK/F_WRLCK are the way to go: strictly per-process, and only available to code that can write to the sysctl.

@anitazha @yuwata what do you think?

**Comment by yuwata** [comment]
Sounds nice. Interesting.

**Comment by teknoraver** [comment]
I have a proof of concept implementation of this change.
Missing part is in systemd-sysctl to just check for the lock existence
