### ISSUE TITLE
systemd-gpt-auto-generator[PID]: Failed to dissect: Permission denied

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#25494]
### systemd version the issue has been seen with

systemd-251.8-586.fc37.x86_64

### Used distribution

Fedora 37

### Linux kernel version used

6.0.8-300.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Unexpected behaviour you saw

On each boot:
```
Nov 23 06:41:08 hp systemd-gpt-auto-generator[613]: Failed to dissect: Permission denied
Nov 23 06:41:08 hp systemd[606]: /usr/lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
Nov 23 06:41:08 hp audit[613]: SYSCALL arch=c000003e syscall=16 success=no exit=-13 a0=4 a1=1269 a2=7ffddab53210 a3=96000 items=0 ppid=606 pid=613 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-gpt-aut" exe="/usr/lib/systemd/system-generators/systemd-gpt-auto-generator" subj=system_u:system_r:systemd_gpt_generator_t:s0 key=(null)
```

### Steps to reproduce the problem

None. It just spews an error after upgrading from F36.

**Comment by poettering** [comment]
given the audit message this is almost certainly an selinux issue. Please contact your distro's selinux policy maintainers about this, or turn off selinux. Either way, not something actionable for us here upstream.

**Comment by QuintinHill** [comment]
Actually this seems to be a duplicate of https://github.com/systemd/systemd/issues/24431.  This was fixed in v252 in https://github.com/systemd/systemd/pull/24530 but apparently the commit responsible was https://github.com/systemd/systemd/commit/75d7e04eb4662a814c26010d447eed8a862f5ec1 which is only in v252 as well.  https://github.com/fedora-selinux/selinux-policy/pull/1468 and https://bugzilla.redhat.com/show_bug.cgi?id=2141998 look to address this at the distro level but there is push back there at adding sys_admin.

**Comment by QuintinHill** [comment]
I think the relevant commit is actually https://github.com/systemd/systemd/commit/1b010ae7c96d953f11a9925d4c5aef29befc86d1 which introduces use of the BLKPG_ADD_PARTITION ioctl which requires SYS_ADMIN.  So this should be fixed in the SELinux policy.
