### ISSUE TITLE
systemd-gpt-auto-generator shouldn't cause creations of partitions

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#25528]
### systemd version the issue has been seen with

252

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.1.0-0.rc6.46.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Expected behaviour you didn't see

systemd-gpt-auto-generator should only scan the root block device and create respective mount units based on the content of GPT parition table.

### Unexpected behaviour you saw

It seems that generator causes scan of the partition table by the kernel and creation of respective partition devices. This is done in `block_device_add_partition()` and requires `sys_admin` capability which is not granted by the SELinux on Fedora. AVC is message is logged and error is ignored on the generator side. My main issue is that rescan of the partition table needs to happen anyway at later point because systemd-udevd is not running when the generator is executed during boot and probing partitions at such early time seems wasteful and unnecessary.

### Steps to reproduce the problem

```strace -e ioctl /usr/lib/systemd/system-generators/systemd-gpt-auto-generator /tmp /tmp /tmp 2>&1 | grep BLKPG_ADD_PARTITION```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
ioctl(4, BLKPG, {op=BLKPG_ADD_PARTITION, flags=0, datalen=152, data={start=1048576, length=1048576, pno=1, devname="/dev/vda1", volname=""}}) = -1 EBUSY (Device or resource busy)
ioctl(4, BLKPG, {op=BLKPG_ADD_PARTITION, flags=0, datalen=152, data={start=2097152, length=21472722432, pno=2, devname="/dev/vda2", volname=""}}) = -1 EBUSY (Device or resource busy)
```

**Comment by qhill** [comment]
@msekletar this affects 251 too see https://github.com/systemd/systemd/issues/25494.

**Comment by keszybz** [comment]
We discussed this with @msekletar yesterday. The conclusion was that this is OK and expected. https://github.com/systemd/systemd/commit/1b010ae7c96d953f11a9925d4c5aef29befc86d1 added a call to BLKPG_ADD_PARTITION to work around a problem with the kernel asynchronously and unpredictably detecting partitions on its own. Instead of waiting for the kernel to read the partition table and create device notices for the partitions, we tell the kernel to "add" a partition. The partition already exists on disk, so the only change is in the volatile state in the kernel. There are no plans to change this, because this approach is more robust than the other approaches that were tried previously and suffered from various race conditions.

**Comment by poettering** [comment]
@keszybz hmm, but the gpt generator should not trigger these ioctls. this was conditioned out, i.e. via the DISSECT_IMAGE_MANAGE_PARTITION_DEVICES flag: we only set it when we set up the block device ourselves (i.e. when loopback devices are used), and do not set the flag otherwise. 

gpt-auto-generator should not set that flag and afaics it really does not. So something is buggy there if this happens nonetheless.

@yuwata any idea?

**Comment by poettering** [comment]
@msekletar can you check if #25580 fixes the issue for you?

**Comment by seVenVo1d** [comment]
Is this bug related to this one -> https://bugzilla.redhat.com/show_bug.cgi?id=2083900

**Comment by msekletar** [comment]
@poettering JFYI, the original SELinux issue is gone. Thanks!
