### ISSUE TITLE
user-${UID}.slice is not templatable

### ISSUE THREAD

**Issue by KellerFuchs** [systemd/systemd#2556]
The `user-${UID}.slice` units are not templatable, and use a naming scheme that is inconsistent with the rest of `systemd`.
I particular, this makes it impossible to set _per-user_ ressources limits: @poettering suggested in https://github.com/systemd/systemd/issues/2305 to set those in `user.slice`, but this would set a limit on all users collectively (i.e. “users can use at most 500MiB of RAM in total” vs. “any given user can use at most 500MiB of RAM”).

I understand this is a difficult-to-handle bug report, since simply changing to `user@.slice` is compatibility-breaking, and [some code](https://github.com/systemd/systemd/blob/bcbd1d0cd5a1e6ff068f251c99ed7905223fed67/src/basic/cgroup-util.c#L1548-L1571) has `user-${UID}.slice` hardcoded-in.
However, it should be doable to make this configurable - for instance by honoring the `Slice` parameter in `user@.service` if it is present - in order to support templating and not break backwards compatibility.

Should this be an acceptable solution, I would happily try to contribute patches for this. Otherwise, please suggest a possible solution, so that we can move towards resolving this issue.

Note: This is a rehash of https://github.com/systemd/systemd/issues/2305, which was closed because it contained a non-helpful description and has a problematic suggested solution.
I opened a new issue since none of the comments in it were addressed after it was closed, and I was unable to get it reopened.

**Comment by omahn** [comment]
We have a remote desktop service here and would like to use resource limits as described by @KellerFuchs above. If the solution suggested is acceptable then we would also be more than happy to help in the development and/or testing to move this forward.

**Comment by KellerFuchs** [comment]
@poettering Any thought on that?

**Comment by poettering** [comment]
Hmpf, so I see the usecase for this, but I have no idea how to implement this I must admit. The thing is that slice units encode their full path in the unit name, in a fully defined syntax. That syntax does not allow for @ characters and templating though. And I am not sure it would be a good idea to depart from that syntax...

THe same issue came up before for mount units, where people wanted the concept of mount unit templates.

I figure to fix this we'd need to make a pretty major change to the logic of PID 1. For example, it might be an option to say that each unit foo@bar.suffix implicitly also gets a name foo-bar.suffix, i.e. that there's an implicitly alias added for each instance with the @ replaced by an underscore. With that concept both the .mount and the .slice could be implemented, as we'd still follow the rule that the unit name maps to the file system path, but we'd still allow instantiation at one level.

But this still opens up a lot of questions. i.e. foo-quux@bar.suffix and foo@quux-bar.suffix would create a naming conflict, because they'd both get aliases of foo-quux-bar.suffix...

Hence, I am really not sure how we can resolve this without having to give up the basic concept that .mount and slice units have a bijective mapping between their names and their paths...

**Comment by KellerFuchs** [comment]
OK, I see the issue.
@poettering Thanks for the toughtful reply, I will look whether I can think of something.

**Comment by daurnimator** [comment]
> That syntax does not allow for @ characters and templating though. And I am not sure it would be a good idea to depart from that syntax...

Why is this such a difficult change?

> it might be an option to say that each unit foo@bar.suffix implicitly also gets a name foo-bar.suffix, i.e. that there's an implicitly alias added for each instance with the @ replaced by an underscore.
> 
> But this still opens up a lot of questions. i.e. foo-quux@bar.suffix and foo@quux-bar.suffix would create a naming conflict, because they'd both get aliases of foo-quux-bar.suffix...

This seems like a lot of ugly work to get around the above "bad idea".

> Hence, I am really not sure how we can resolve this without having to give up the basic concept that .mount and slice units have a bijective mapping between their names and their paths...

Can that not be kept if you just have `user@${UID}.slice`? it seems trivial to map back/forth.

**Comment by KellerFuchs** [comment]
> Can that not be kept if you just have user@${UID}.slice? it seems trivial to map back/forth.

The main issue, as far as I understand, is that this would break backwards compatibility.

**Comment by KellerFuchs** [comment]
@daurnimator  I didn't find any doc saying that the naming `user-${UID}.slice` can be relied upon.

@poettering Would it be acceptable to fix all the systemd code that relies on the `user-${UID}.slice` convention, and make it use `user@${UID}.slice` instead?
The encoding problem can be solved by encoding the `user@123.slice` instance name as `user--123.slice` in the path name.

**Comment by stevehorsfield** [comment]
Why not introduce a completely new type of unit, '.template'. This could address a range of templating needs:
- Dynamically create units at install time: slice, path, mount, device, automount, etc.
- Support more complex cases where the template parameter is decomposed into multiple parts (one example is for mounts where it would be nice to separate the device from the mount path)

I agree the current design makes this hard, but it still feels  to me that this is something that shouldn't just be rejected because it's hard, without any real workaround.

**Comment by stevehorsfield** [comment]
To give an example, I currently have `service` units performing mounts because I can't template a mount and a mount creates a dependency on a device I also can't template!

**Comment by poettering** [comment]
@stevehorsfield if you want to dynamically create unit files from foreign configuration, please use "generators" for this, not templates.

See https://www.freedesktop.org/software/systemd/man/systemd.generator.html for details.

**Comment by stevehorsfield** [comment]
Thanks @poettering.

It isn't really "foreign configuration", but I hadn't seen `systemd.generator`, so thanks for the link. That may be useful. It does seem a fairly arbitrary decision to say use "generators", not "templates". What's the rationale?

**Comment by poettering** [comment]
@stevehorsfield this isn't really the place to discuss this: but a template is a passive file that is instantiated multiple times with minimal variable expansion applied. A generator is an executable binary that writes out unit files (it "generates" them) of any content, usually based on foreign configuration. For further questions → check out the linked man page, thank you.

**Comment by daurnimator** [comment]
Has anyone looked at this recently?

@poettering would you accept a PR that changes slices from user-$UID to user@$UID? + a compat alias to make old code/config still work?

**Comment by poettering** [comment]
@daurnimator it's not that easy... instances apply to all aliases, hence you cannot have a unit named both user-$UID.service and user@$UID.service, as a unit cannot be both both a template instance and a regular unit at the same time.

That said, for other purposes (such as templatable mount units) it has been requested to change this, so that all template instances automatically gain non-instance aliases where the `@` is replaced by a "-". I'd be happy to take a patch for that as first step.

**Comment by traylenator** [comment]
Another approach to this, currently pam_systemd creates the slice. 
What about enabling pam_sytemd to support a configuration for the generated user slices.

**Comment by Saford91** [comment]
> Another approach to this, currently pam_systemd creates the slice.
> What about enabling pam_sytemd to support a configuration for the generated user slices.

@traylenator I'm not sure if pam_systemd ultimately creates the slices, but I agree that a different method of templating could avoid the issues already discussed.

@poettering What if the /etc/systemd/user.conf file allowed for a [Slice] section and all parameters in that section were applied to each new user slice?

**Comment by Saford91** [comment]
@KellerFuchs Since there'es no native support for this, are you using another method to set per-user limits?

**Comment by daurnimator** [comment]
> @KellerFuchs Since there'es no native support for this, are you using another method to set per-user limits?

Yes. We are using pam_exec to run a little snippet that sets limits on the slice.
https://github.com/hashbang/shell-etc/pull/183

**Comment by jsbillings** [comment]
The place where the pam_exec solution fails is if you're using SELinux and confined user accounts.  The SELinux user_u (and anything based on it) can't modify it's own systemd slices, at least on RHEL7.  I've given up and just run a cron job every 15 minutes to adjust logged in users.

**Comment by KellerFuchs** [comment]
@jsbillings Right, you need `pam_selinux` to run before `pam_systemd`, so the `pam_exec` thing cannot run unconfined.
