### ISSUE TITLE
 systemd-vconsole-setup/setfont fails on VM with no VGA

### ISSUE THREAD

**Issue by haraldh** [systemd/systemd#2560]
If I don't have a VGA device attached to a VM then systemd-vconsole-setup.service always fails on startup.

putfont: PIO_FONT trying ...
/usr/bin/setfont failed with error code 71.

results in:
https://bugzilla.redhat.com/show_bug.cgi?id=1272686
https://bugzilla.redhat.com/show_bug.cgi?id=1272684

**Comment by poettering** [comment]
We have a `ConditionPathExists=/dev/tty0` check in the unit file. /dev/tty0 is how we detect whether the VT subsystem is available. Are you saying your VM claims to have a VT but setfont fails on it then?

**Comment by johannbg** [comment]
These errors are due to a missing font which are either the kernel built-in/provided one or user defined one
systemd-vconsole-setup: setfont: putfont: 512,8x16:  failed: -1 
systemd-vconsole-setup: putfont: PIO_FONT: Invalid argument
systemd-vconsole-setup: /usr/bin/setfont failed with error code 71.
Anyway this is not a systemd problem since all systemd does, is calling setfont which is failing here. You should be able to duplicate this by running the exact same command from the command line on the affected host.

**Comment by haraldh** [comment]
Well, it seems like tty0 is a serial console and the VM does not have a VGA attached.

**Comment by poettering** [comment]
Nah. /dev/tty0 is strictly a VC thing. It maps to the foreground VC. It doesn't exist if VCs are not compiled in. (/dev/console is different: it might map to a serial terminal)

**Comment by poettering** [comment]
OK, closing now, since there appears nothing wrong with systemd, and we explicitly check for VC-less systems via the /dev/tty0 check. If that check doesn't work, please reopen and provide details!

**Comment by poettering** [comment]
(Specifically, please provide details what a system with "no VGA" specifically means, i.e. which display devices precisely exist and which don't, and so on, i.e. whether the whole VC is compiled out, and whether /dev/tty1, /dev/tty0 and so on exist, and what the correct way would be to detect such systems)
