### ISSUE TITLE
Long waiting for initrd-root-fs.target On boot

### ISSUE THREAD

**Issue by muellerjoel** [systemd/systemd#25623]
Doesn’t mount properly crypted LVM device since systemd 252.2-1 with systemd 252.1.-2 it’s works

Here the discussion 
https://bbs.archlinux.org/viewtopic.php?pid=2071614#p2071614

**Comment by poettering** [comment]
not a useful bug report.

Also, please contact your downstream distro first.

And yeah, once LVM is in the mix, the likelyhood of us behing able to help you is severly reduced.

**Comment by Joel-Muller** [comment]
I contacted first ArchLinux forum. They can’t help.  Which information is needed? Have you read the thread?

**Comment by Joel-Muller** [comment]
systemd252.3-1 still not fix as info

**Comment by Joel-Muller** [comment]
systemd version the issue has been seen with

252.2-1 till 252.3-1
Used distribution

Arch Linux Mainline
Linux kernel version used

Intel Xeon
CPU architectures issue was seen on

x86_64
Component

systemd-cryptsetup
Expected behaviour you didn't see
Mount LVM cryptsetup /dev/vg_main/{data,home,swap}
Error initrd-root-fs.target failed


Unexpected behaviour you saw
Emergency Console and downgrade systemd to systemd252.1-2 to boot properly


Additional program output to the terminal or log subsystem illustrating the issue

The full thread on ArchLinux forum
https://bbs.archlinux.org/viewtopic.php?pid=2071614

**Comment by poettering** [comment]
Again, please report to archlinux bug tracking system first. If they find an actual error in systemd, they'll escalate this back to us, but LVM stuff is really not our area of expertise, and integration issues with LVM and systemd should really be first analyzed on a distro level.

Not saying there wasn't a bug here in systemd somewhere, but this is too vague on one side and too specific an issue on the other for us to deal with here for now.

hence, please contact your distro bug tracker first, and once they determiend there is no issue in their initrd, their LVM integration work, please let them escalate back to us

thank you for understanding.

(no, a forum posting is not a bug report)

**Comment by Joel-Muller** [comment]
git bisect bad

```
3ec3ae68d2cea32461d779645a737d57160631bf is the first bad commit
commit 3ec3ae68d2cea32461d779645a737d57160631bf
Author: Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>
Date:   Thu May 19 09:50:48 2022 +0200

    basic/strv: add optimizable version of strv_push/consume/extend
    
    This will be helpful in cases where we are repeatedly adding entries
    to a long strv and want to skip the iteration over old entries leading
    to quadratic behaviour.
    
    Note that we don't want to calculate the length if not necessary, so
    the calculation is delayed until after we've checked that value is not
    NULL.

 src/basic/strv.c     | 30 ++++++++++++++++++------------
 src/basic/strv.h     | 24 +++++++++++++++++++++---
 src/test/test-strv.c | 43 +++++++++++++++++++++++++++++++++++++++++++
 3 files changed, 82 insertions(+), 15 deletions(-)
```
