### ISSUE TITLE
Can systemd-resolved be extended with plugins or hooks?

### ISSUE THREAD

**Issue by KiranVKumar** [systemd/systemd#25624]
Can **systemd-resolved** be extended with plugins or hooks? If so, please share the right docs for writing the plugin or hooks.
I am planning to write a plugin that should be called by **systemd-resolved** whenever it receives a DNS query response, and can be used to perform custom actions.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
