### ISSUE TITLE
suspend-then-hibernate only suspends

### ISSUE THREAD

**Issue by hissssst** [systemd/systemd#25709]
### systemd version the issue has been seen with

"v252.1"

### Used distribution

NixOS 23.05 (Stoat)

### Linux kernel version used

5.15.82

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-boot

### Expected behaviour you didn't see

suspend-then-hibernate suspends and then hibernates my laptop

### Unexpected behaviour you saw

suspend-then-hibernate only suspends

### Steps to reproduce the problem

1. Call `systemctl suspend-then-hibernate`
2. See that no `hibernate` happens

**Comment by hissssst** [comment]
Nothing interesting in `dmesg` and `journalctl`

**Comment by Proximus888** [comment]
@hissssst This is the new expected behaviour. 

suspend-then-hibernate now only hibernates if your battery reaches 5%. It doesn't follow HibernateDelaySec anymore. If your system doesn't hibernate if your battery reaches 5% then yes something is wrong.

See #25269  and #25374

**Comment by hissssst** [comment]
@Proximus888 could you help me please, is there any way to achieve the previous behavior in recent version?

My laptop supports only S0 sleep which drains battery and reduces it's lifetime, therefore I use suspend-then-hibernate most of the time.

**Comment by hissssst** [comment]
Yeah, seems that it is duplicate, I'll continue on in #25269

**Comment by joint007** [comment]
Yeah, continue in locked thread.. Thanks..

Now, we know, bluca is type of programmer, who simple doesnt thing about user-experience.. How this people can be paid for this bad work????

Imagine, when you are forced to use systemd with your system.. And after some time, after i got used of it, one developer thinks for the user instead of asking them.

So, for many years, i have set HibernateDelaySec to 2 hours.. And for many years, everything works like expected, when i use suspend-then-hibernate.. My computer is fast-resumed, when i need to work in 2 hours after i close it, and after this time, it has been hibernated.. 
So, my battery-life will be extended to huge-time, after i simply close notebook. Now, my notebook battery is drain to 5%!!! 

<irony>So, thanks to all devs, who thinks for the user.. </irony>
