### ISSUE TITLE
add CRIU integration

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#258]
With handy integration between machined, nspawn etc throughout the stack the next useful addition would be integration with CRIU: http://www.criu.org/Main_Page

Would be really handy is I could call:
systemctl freeze myservice
systemctl move -H myhost.com myservice
or
systemctl move -M mycontainer myservice

To freeze the service on local host and than move it to other host. The same applies to nspawn containers - ability to free on one host and unfreeze on another would be perfect for live migrations.

**Comment by poettering** [comment]
This has been discussed before, but I am not convinced that CRIU is something we want to support natively in nspawn. It makes a promise that is pretty much impossible to keep. Yes, it works in some cases, but it's impossible to guarantee that it works in all cases, and that's just something I have no interest to support.

Sorry.

**Comment by rektide** [comment]
Leaving "some caveats may apply" (applying the halting problem) as a sole reason for not allowing feature work is bunk Lennart. :-1:

Would love to see this incredible range of capabilities enrich the Linux world. If people do adopt it, it's much more likely to get the support it deserves. Getting some systemd integration seems key to that work.

**Comment by filbranden** [comment]
To be fair, CRIU is fairly good at detecting when a checkpoint will fail and it can abort the operation leaving the original processes in place, so it's probably "safer" than you think.

Though I think what might make more sense for systemd is to create a somewhat standard framework around checkpoint/restore/migration and make it extensible such that multiple implementations can be used.

I would actually probably hook it to machinectl since then we could implement these operations over both virtual machines (using e.g. qemu-kvm savevm/loadvm/migrate or native commands from other hypervisors) or containers (using CRIU or p.haul which will support live migration.)

Making it pluggable/extensible is also nice because it can be used to hook applications that implement native checkpointing, for example video transcoding, you could tell ffmpeg to dump its internal state (which frame it's in, which offset on the input file and output file, etc.) so that you could migrate a large transcoding job to another machine if you need to reboot the system it's running on. (Only thing about this one case is that machinectl is possibly not the best fit CLI since it's a task and not really a virtual machine or container.)

**Comment by poettering** [comment]
Well, if you write software to solve a problem, and give it to people, then they want to rely on the fact that it solves the problem. Modulo some bugs that's the deal. However, CRIU makes a promise to people, that is impossible to keep. Sure, it might be good at saying "I cannot support this case", but what kind of a promise is that? Telling people "hey, look at this shiny thing for you, use it, it will solve this problem you care about for you, but only sometimes", what kind of a weird deal is that?

Also, I think the concept misses half the point of what containers are about: containers are decidedly more light-weight. You can spin them up quickly, you can shut them down quickly. You can socket activate them, and you can run tons of instances. The mode of operation with them is really that they live only a short-time, and in many instances. Hence the need to migrate them live is much smaller: instead of running a single instance you keep migrating live, you should run many, start them dynamically, stop them dynamically, and if not bother with actually moving one specific running instance of it somwhere else.

Doing C/R on VM images makes a ton more sense to me. Both technically how things are implemented, and on the conceptual level. But for containers? Nah, I am not convinced the technical design nor the conceptual need for it make a lot of sense.

Sorry.

**Comment by xemul** [comment]
Not trying to change your mind, just want to point out things you're misleading people.

First, containers are lightweight, yes, but not the software that runs inside. If you compare the start time versus the restore time for some apps (regardless of where it runs -- in our out of container) the difference can come up to several times. This makes sense for some scenarios and, btw, socket activation doesn't solve it.

Second, the promise C/R makes to people is not "I can make it sometimes" but "I can make it for all but several kernel APIs". This is huge difference though some "but" APIs can be quite common already. If some new API will appear in the kernel CRIU will probably notice it and surely fail to dump it, but till we really meet a software that uses the API we'll have enough time to support one (provided the API is done right).

Third, C/R != live migration. It's the basis for it, but not only, there are other use cases for C/R other than migration.

**Comment by rektide** [comment]
_Third, C/R != live migration. It's the basis for it, but not only, there are other use cases for C/R other than migration._

I'll cite snappy-start's [other stated advantages](https://github.com/google/snappy-start/blob/master/README.md#snappy-start-tool-for-process-startup-snapshots); it's a different C/R implementation but the advantages apply for any C/R system:
- Faster startup, if the program does a non-trivial amount of computation during startup.
- Saving memory, because memory pages that the program writes to during startup will be shared between the instances.

Edit: @zabbal's original post is chiefly around migration which quickly set the tone for this topic. Checkpoint/Restore can accomplish much more than this one use case CRIU can also be used for HA processes (checkpoints can be incrementally or continuously streamed remotely), startup-less/pre-warmed launch, saving memory, ... and probably more.

**Comment by ludovic-gasc** [comment]
Hi,

Two years later after this discussion, is it still a no-go ?
Some usages listed at the end of this issue seems interesting.

Regards.

**Comment by balsoft** [comment]
It's pretty sad that ideas like this one get rejected outright. This integration would be perfect for implementing "low-power" mode on non-Android Linux. Attempt to freeze most of the stateful services (and if it can't be frozen, stop it), stop all of the stateless services. Keep services from a certain allow-list running, so that the system can still do some tasks, e.g. music could continue playing on the desktop via mpd, or a smart home device could wait for something to happen while having most services shut off. Obviously, also do some other things like turn off the screen, shut off unused wireless, cap the CPU frequency at lowest possible, turn off the dedicated GPU, etc.

**Comment by acuteaura** [comment]
@balsoft I think what you're looking for is 'socket activation'.

I'd be interested to see if anything substantially changed to make CRIU more feasible, considering it deemed stable/reliable enough by [podman](https://www.redhat.com/en/blog/podman-checkpoint-restore-and-sql-server-2019) for a first-party implementation. Maybe that's an alternative for some of the services you run?

**Comment by balsoft** [comment]
Socket activation doesn't solve the issue for services designed to run continuously. Those services have runtime state which takes some time to initialize. Freezing and starting with CRIU would often be a lot faster.

**Comment by Sporesirius** [comment]
Hallo @poettering,
Wouldn't the feature that CRIU offers make it possible to update the kernel while old processes continue running on the new one? This could lead to zero downtime or at least very minimal downtime. I think systemd, as the init system, would be the best place to handle this kind of thing, no?
