### ISSUE TITLE
Unable to reboot or power the system down when systemd is not the init process

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#25854]
### systemd version the issue has been seen with

any

### Used distribution

any

### Linux kernel version used

any

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Boot with `init=/bin/bash`, try to `reboot`/`poweroff` - both will fail.

I've had this issue for as long as I remember but never bothered to file a formal bug report. Looks like I'm not alone.

Please fix.

**Comment by smod** [comment]
Since the manager is not running there is no way you can get a controlled shutdown in this scenario.

However `reboot -f` and `poweroff -f` will do what you expect: killing everything and umounting all filesytems so that no data is lost.

This is documented here: https://www.freedesktop.org/software/systemd/man/systemctl.html#reboot

**Comment by birdie-github** [comment]
I never thought about the `-f` flag/option. It actually works. Thanks a ton and sorry for the noise!
