### ISSUE TITLE
Smart mount fallback

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#25881]
### Component

systemctl, systemd-gpt-auto-generator, other

### Is your feature request related to a problem? Please describe

Device fallback has always been a pretty manual process, usually involving creating initrd scripts or services yourself to your needs, but, having a built-in file/format for defining how systemd should fallback when devices fail to mount would be a huge help.

### Describe the solution you'd like

This is a rough proposal meant to communicate what such a fallback mechanism could look like, definitely needs a lot of work to get it to a state flexible and robust enough, so take everything you see below with a heap of salt.

```
[Fallback]
What=/dev/disk/by-uuid/"root-uuid"
Where=/
Type=btrfs
Options=subvol=/@

[Fallback]
What=/dev/disk/by-label/root
Where=/
Type=btrfs
Options=subvol=/@-fallback

[Fallback]
What=tmpfs
Where=/
Type=tmpfs
Options=
```

- Each mount unit would have a `*.mount.d/name.fallback.conf` file in `/etc/systemd/system` (is `.fallback.conf` the best choice?).
- A `systemd-fstab-generator`-like service would process the file to populate the missing [Unit] section, mainly to cut down on the amount of content needed from users (or perhaps a different format should be used?).
- `[Fallback]` sections are attempted in the order they're defined in, unless overridden by `Order=...` or something, from top to bottom.
- Fallback options should override devices defined on the kernel cmdline, which is complicated when considering how it'd interact with Secure Boot.

Additionally, having a way of pairing fallbacks together, so a specific `/home` fallback is used for certain `/` fallbacks, would likely be useful as well, but I have no clue how you'd nicely format that.

### Describe alternatives you've considered

Instead of `*.mount.d` overrides with special handling on `.fallback.conf`, a new file like `/etc/falltab` might be a better fit, or perhaps something completely different?

The ability to define fallbacks in the kernel cmdline is also something to consider, I only know of `rootfallback` as used by Dracut (see `man dracut.cmdline`), but, a compact layout for defining fallbacks is tricky.

Instead of a dedicated file for defining fallbacks, perhaps more robust automated fallbacks, with overrides for their behaviour where applicable, would be a better place to start (e.g. https://github.com/systemd/systemd/issues/24539 with fallback cmdlines, https://github.com/systemd/systemd/pull/25608 for preventing fallbacks to invalid devices, etc).

(Couldn't find anything related in the TODO file)

### The systemd version you checked that didn't have the feature you are asking for

252.4-2

**Comment by poettering** [comment]
This is much harder to implement than one might thing.

First of all, when precisely do you intend to fall back? The most common problem with mounting something is that the specified device simply never shows up. Which hence suggests that we'd need to implement a time-out on the dependencies here. But then, if you then switch to another device you'd need to wait for an entirely different device. So you need another time-out then, and so on. That's just a mess.

Your example suggests that your specific usecase is about the root fs, but if it's about that I think  boot counting/assessment is probably the better choice, i.e. instead of specifically doing fallbacks on root fs (i.e. one possible error source among many) cover the whole boot process, and revert to an older version of it if we never manage to reach the final boot goal.

But automatic boot assessment/fallbcak we already have in place, see https://systemd.io/AUTOMATIC_BOOT_ASSESSMENT/

Hence, I am not convinced the proposal really is desirable, nor even implementatble reasonably.

**Comment by Winterhuman** [comment]
Can't disagree with that, I did mention using multiple cmdlines in the "more robust automated fallbacks" part, so it seems we're in agreement there. I guess https://github.com/systemd/systemd/issues/24539 is the best solution then, it doesn't reinvent anything, and it's already underway.

Closing issue, I can always open new issues if more control through the cmdline is needed for specific use-cases

**Comment by L3P3** [comment]
I need this for nfs and sshfs fallback. And I did not get why this would be hard to implement when I could hack a shell script in less than 5 minutes to do that. Greetings. :upside_down_face:
