### ISSUE TITLE
systemd-mount fails on boot

### ISSUE THREAD

**Issue by muellerjoel** [systemd/systemd#25893]
Hi 

My LVM Crypt root device doesn't mount properly.

I did

git clone https://aur.archlinux.org/systemd-git.git
cd systemd-git

git clone https://github.com/systemd/systemd.git
cd systemd
git bisect start
git bisect good b622e95  #v251
git bisect bad 9ca1efb   #v252.rc2
cd ..
makepkg -efsi

The first tow build are ok but after two git bisect bad couldn't build anymore

I got following meson log and there is the error is It's can't build the package nor compile systend-mount

https://0x0.st/o5E2.txt

Here the log.

The ArchLinux Community couldn't help me anymore so my last call. Plz fix it.

**Comment by TriMoon** [comment]
> I got following meson log and there is the error is It's can't build the package nor compile systend-mount

You can't expect people to delve into a `9.10 MB` log file to find what you mean....
Mention the exact error part...

Plus in relation to the topic title:
> My LVM Crypt root device doesn't mount properly.

- Post relevant config files including full paths and contents.

> The ArchLinux Community couldn't help me anymore so my last call. Plz fix it.

Post a link to where and what was discussed so far...

---
Without exact info, all you get is what you have now a computer response saying "I can't do this" without any human explanation.

---
Next time post in your original language and quote a google translation of it.
Because now the text you posted is not understandable, at least not for me.
_(I'm not native english also)_

All we (I) understood so far is:
- "It doesn't work..."
- "It doesn't compile, fix it"

Help us to help you, if not have fun....

**Comment by Joel-Muller** [comment]
https://bbs.archlinux.org/viewtopic.php?id=281732&p=3

Here the link with all relevant information

**Comment by poettering** [comment]
Sorry, but LVM issues have to be dealt with with downstream distros, that's an integration issue. LVM is outside of our area of expertise.

Please contact yout distro developers for help, if there's actually something to fix in systemd upstream let *them* escalate this back to us.
