### ISSUE TITLE
alloc-util.h change macros to inline functions

### ISSUE THREAD

**Issue by jonnygrant** [systemd/systemd#25907]
### Component

systemd

### Is your feature request related to a problem? Please describe

alloc-util.h has lots of macros, and some inline functions. May I offer to prepare a patch that changes them to regular functions, which have the benefit that they will be compiled (rather than macro replacements) and so the compiler can give better compiler output if any typos etc, and check types too.

For example

````
#define alloca0(n)                                      \
        ({                                              \
                char *_new_;                            \
                size_t _len_ = n;                       \
                _new_ = alloca_safe(_len_);             \
                memset(_new_, 0, _len_);                \
        })
````

The compiler is free to inline this if it is places in alloca-util.h

````
void * alloca0(const size_t __len__) {void * __new__ = alloca_safe(__len__); memset(__new__, 0, __len__); return __new__;}
````

This function of course assumes alloca_safe never returns NULL, but that shouldn't happen.. and if it does a core dump might be useful. I'd probably add an assert in the middle though.
````
void * alloca0(const size_t __len__) {void * __new__ = alloca_safe(__len__); assert(__new__); memset(__new__, 0, __len__); return __new__;}
````

### Describe the solution you'd like

````
void * alloca0(const size_t __len__) {void * __new__ = alloca_safe(__len__); assert(__new__); memset(__new__, 0, __len__); return __new__;}
````

**Comment by vcaputo** [comment]
alloca allocates on the local stack frame via `alloca(3)`, which means it's freed upon return from the function.

Hence the macro.

There are other reasons to use macros for allocation helpers as well, even when they don't use alloca(3).  One being you can make the helper determine the size of what to allocate automagically via sizeof() because the macro can access the type of the passed-in object.  Whereas when it's a function you have to pass in the size.  e.g.  
```
alloc_helper(res_ptr) { *res_ptr = malloc(sizeof(*(res_ptr))); assert(*res_ptr); }
```

Allocation helpers in particular tend to be resistant to macro->static-inline-function conversions as a result.

The systemd code tends to already favor the function form where applicable...

**Comment by jonnygrant** [comment]
Maybe I'm missing something.. alloca0() doesn't use the operator sizeof, I'll go into more detail below.

Thank you for your quick reply. I did look at your example, I had a look at your example alloc_helper() it doesn't seem related to my alloca0 proposal, as it contains a sizeof() operator. I believe you may be mistaken mentioning that example, as it's not related to alloca0. (This is not a criticism of you personally ). I only picked one obvious macro to convert to a function that could be compiled directly. I appreciate that some other macros may not be suitable to convert though.

You're completely right that [alloca(3)](https://man7.org/linux/man-pages/man3/alloca.3.html) allocates in the local stack-frame, saves needing clean up when function returns. alloca takes a bytesize parameter. If you look at the assembler output by the compiler, or use objdump to look at the resulting ELF file it shows the what the resulting machine code is when disassembled. I compared both, its the same 36 lines. godbolt.org is a great site to compare things like this.

I couldn't find your alloc_helper() in the code base. My reply was only about the alloca0() macro on line systemd/src/basic/alloc-util.h:3

Given that alloc0() takes a bytesize, not a type, there is no sizeof() inside it, it seems ideal to be a function - wouldn't you agree?

bpf-firewall.c:374 is a good example of where alloca0() macro is used at present.

Sharing my example, I used explicit_bzero() to ensure it wasn't optimised out.
https://godbolt.org/z/fKd9bGEah

**Comment by vcaputo** [comment]
You're conflating two things.

Your alloca0() function conversion proposal is inappropriate purely because alloca() allocates on the local stack frame, as I already stated.  If you turn that into a function, the allocation's pointer should not be returned from the function - it's technically a UAF bug, regardless of what the compiler happens to generate.

My ad-hoc example was just to highlight another reason why macro-based allocation helpers tend to resist conversion to functions; such type visibility is unique to macros.  There are multiple of those in alloc-util.h which you would see if you actually studied the code there.  (new0(), GREEDY_REALLOC(), et al)

> Given that alloc0() takes a bytesize, not a type, there is no sizeof() inside it, it seems ideal to be a function - wouldn't you agree?

There is no alloc0().  If you're talking about alloca0(), that shouldn't be a function again because of the alloca(3) usage.

malloc0() does look like it could be an inline function though...

It's unclear to me at this point what the purpose of this effort is.  This is an upstream issue tracker, not a discussion forum.  Please use systemd-devel mailing list for such conversations.

**Comment by jonnygrant** [comment]
@vcaputo My brain must have gone wrong, you're completely right that changing to a function would mean the stack allocation by alloca() would be a use after free bug so I shouldn't have suggested it. Thank you for your time replying.
