### ISSUE TITLE
user.slice,system.slice,init.scope are created on some machines, but not on others.

### ISSUE THREAD

**Issue by xiacunshun** [systemd/systemd#25939]
### systemd version the issue has been seen with

239

### Used distribution

tencentos 3.1

### Linux kernel version used

5.4.119-19

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

user.slice,system.slice,init.scope are automatically created under /sys/fs/cgroup/cpu.

### Unexpected behaviour you saw

There are some machines don't have user.slice/system.slice/init.scope under /sys/fs/cgroup/cpu while some do.
Is there any configuration or option can control this behaviour?
![企业微信截图_16729244205994](https://user-images.githubusercontent.com/7437321/210788268-763582bf-8d88-4409-a12e-cd4be9fa43da.png)
![企业微信截图_16729244783397](https://user-images.githubusercontent.com/7437321/210788418-8f87468f-b300-4127-95fb-e841c5ef1e56.png)

### Steps to reproduce the problem

none

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by poettering** [comment]
(and also: the cpu controller is only enable for unit cgroups if cpu accounting or cpu weights are configured for it. cpu controller will also be enabled for all parents and siblings of a unit once enabled, i.e. propagates up and sideways)

**Comment by xiacunshun** [comment]
> (and also: the cpu controller is only enable for unit cgroups if cpu accounting or cpu weights are configured for it. cpu controller will also be enabled for all parents and siblings of a unit once enabled, i.e. propagates up and sideways)

Very thanks. Eventually I found that, sshd.service was configured with 'Deletegate=yes' and this makes the processes under it not controlled by manager conf.
