### ISSUE TITLE
journalctl does not output user units in the right order

### ISSUE THREAD

**Issue by jelly** [systemd/systemd#25932]
### systemd version the issue has been seen with

252

### Used distribution

Debian testing

### Linux kernel version used

6.0.0-6-cloud-amd64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

In Cockpit we have a services page which shows journalctl logs, we "shell" out to journalctl -f --output=json to display these logs in our web ui.

One of our tests creates test.service, which echo's output in a bash script, in our test we verify that it shows up in the webui. This does not show the "START" line but starts with "Started test service" as can be seen below.

### Unexpected behaviour you saw

START is shown before "Started X Service".

```
$ journalctl -f
Jan 04 21:02:30 debian systemd[2288]: Reloading.
Jan 04 21:02:30 debian sh[2382]: START
Jan 04 21:02:30 debian systemd[2288]: Started Test Service.
Jan 04 21:02:35 debian sh[2382]: WORKING
Jan 04 21:02:40 debian sh[2382]: WORKING
```

### Steps to reproduce the problem

Our test creates the following script in `/usr/local/bin/test-service`
```
#! /bin/sh

trap "echo STOP" 0

echo START
while true; do
  sleep 5
  echo WORKING
done
```

Creates a system service in `/etc/systemd/system/test.service`
```
[Unit]
Description=Test Service

[Service]
ExecStart=/bin/sh /usr/local/bin/test-service
ExecReload=/bin/sh true

[Install]
WantedBy=default.target
```

Then start the service:
```
systemctl --user start test.service
```

```
journalctl _SYSTEMD_USER_UNIT=test.service '+' USER_UNIT=test.service
```

Outputs:

```
-- Journal begins at Wed 2023-01-04 20:29:58 UTC, ends at Wed 2023-01-04 20:51:52 UTC. --
Jan 04 20:30:07 debian sh[4051]: START
Jan 04 20:30:07 debian systemd[1017]: Started Test Service.
Jan 04 20:30:12 debian sh[4051]: WORKING
Jan 04 20:30:17 debian sh[4051]: WORKING
```

As we also test other systemd versions in our CI we found out this does not occur in Fedora-37 but only with systemd 252. (As Fedora 37 is `systemd 251 (251.10-588.fc37)`)

**Comment by poettering** [comment]
There's no global ordering guarantee with stdout/stderr written log messages (as you do here). Each stdout/stderr stream is a separate socket with a separate socket buffer, and journald will process the streams as quickly as it can, but if they are all filled at the same time then there's no ordering known.

note that syslog messages are strictly ordered among themselves and so are journal native messages among themselves (but not syslog against journal native messages, as those again are delivered via separate sockets).

but even if we had total global ordering between all log transports here, even then you'd see the messages done in basically undefined order. That's because you picked Type=simple (i.e. you didn't specify a service type. That means PID1 just forks off the process and immediately goes on doing the next thing. The next thing is going to be to write the "Started …" message, indicating it just forked this off. But of course, this code will run in parallel with the child that was just forked off, and which side gets to run first is up the process scheduler and might end either way.

You can actually make this strictly ordered if you want. For that, use Type=notify. If you do that systemd won't consider the service started until an sd_notify() message has been received from it. You can send that message via the `systemd-notify` tool, specifically the `--ready` switch. You can then also use `journalctl --sync` to ensure anything logged so far has hit the disk.

Hence, if you change your script to:

```
#!/bin/sh
echo START
journalctl --sync
systemd-notify --ready
while true; do
  sleep 5
  echo WORKING
done
```

And the service unit file to:

```
[Service]
ExecStart=/usr/local/bin/test-service
Type=notify
```

Then you should see the START in the logs strictly before the "Started…"

Anyway, closing, since this is basically expected.
