### ISSUE TITLE
localectl list-keymaps fails on overlayfs

### ISSUE THREAD

**Issue by djgera** [systemd/systemd#2602]
Due usage of nftw(3) with FTW_MOUNT flag localectl list-keysmaps is unable to show available locales on system running with overlayfs as root.

systemd-229 (and previous versions)

**Comment by poettering** [comment]
Well, those are the broken semantics of overlayfs really, they currently break `nftw()`, `find` and pretty much any other tool that checks dev_t to determine where mount "cuts" are located. It's how this has been done on UNIX since a long long time.

This is really something the overlayfs folks have to fix, sorry.

**Comment by poettering** [comment]
Note that POSIX explicitly says that comparing dev_t is how do detect mount "cuts":

http://pubs.opengroup.org/onlinepubs/009695399/utilities/find.html

If overlayfs claims to be a POSIX file system it really shouldn't break at one of the most basic, documented file system behaviours.

**Comment by djgera** [comment]
Sure I understand the issue, and I will report to overlayfs team.
But is really needed such flag at that point in the code? How bad can be without it?

Thanks.

**Comment by poettering** [comment]
well, it's kinda necessary to be robust against recursive bind mounts. We have quite a few invocations of nftw() in our sources, and every single one of them use FTW_MOUNT, for the same safety reason. Also we have some unrelated directory traversal code in place and it uses equivalent logic (tmpfiles for example, where it really matters because the directory may be user specified). I am very sure we shouldn't patch this out all, just to accomodate for a file system that so clearly violates how UNIX file systems are supposed to work.

This is something for overlayfs to deal with, not something for userspace to work around. Sorry.

**Comment by djgera** [comment]
Okey, thanks for your time.

**Comment by djgera** [comment]
Upstream bug https://bugzilla.kernel.org/show_bug.cgi?id=114951

**Comment by NicoHood** [comment]
I came from this thread: https://bugs.archlinux.org/task/46725
The bug is marked as fixed on the kernel bugtracker, but is still not functional in the archlinux iso of december which has kernel 4.13.12 Any ideas why? Is this an archlinux bug now?

**Comment by djgera** [comment]
Because the patch was never applied.

**Comment by NicoHood** [comment]
djgera, any idea why? Should we bump the issue once again?

**Comment by Keensyst** [comment]
I don't know what to do help please

**Comment by Keensyst** [comment]
Help
On Jan 4, 2018 7:20 PM, shawnkeeney1973@gmail.com wrote:

I don't know what to do help please
On Jan 4, 2018 3:10 PM, "Nico" <notifications@github.com> wrote:

djgera, any idea why? Should we bump the issue once again?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/systemd/systemd/issues/2602#issuecomment-355399439>,
or mute
the thread

**Comment by Keensyst** [comment]
On Jan 4, 2018 7:20 PM, shawnkeeney1973@gmail.com wrote:

I don't know what to do help please
On Jan 4, 2018 3:10 PM, "Nico" <notifications@github.com> wrote:

djgera, any idea why? Should we bump the issue once again?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/systemd/systemd/issues/2602#issuecomment-355399439>,
or mute
the thread

**Comment by djgera** [comment]
No, ask upstream. I reopened the ticket.
