### ISSUE TITLE
`systemctl mock`?

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#2606]
Idea from https://bugzilla.redhat.com/show_bug.cgi?id=1139148:

provide a way to display the environment and commands executed by a service.
Something like this:

```
$ systemctl --mock start apache.service
LANG=C
OPTIONS=-DFOO
/usr/sbin/httpd -DFOO -DFOREGROUND
```

Environment variables would shown, specifiers expanded, etc.

I know that this would be useful at least sometimes, but maybe it's too hard too implement?

**Comment by johannbg** [comment]
@poettering has already rejected this in that bug report ( what purpose is it supposed to opening a bug report upstream that has already been rejected by upstream, downstream? ).

If this is going to be implemented and useful to people you not only need show the complete run time environment block ( as Lennart mentioned ) since application environment setups belong in /etc/profile.d/ ( not in type units ) , you also need to distinguishes where those entries came from so administrator can adjust the _correct_ entry at the correct place for those application environment setups, that means those application environment correctly placed in .profile, profiles.d/scripts, and those that are incorrectly placed in type units which may be in "Environment=" entry, an file that resides in "EnviromentFile=" entry or in a script being executed in Exec*= lines.

Tool that displays all of this does not belong in systemd, it belongs in util-linux or something since you cannot rely only on the environment being set in type units since it's neither the correct place to set it. nor the only place to set but if you insist on implement this just as an environment used type units ( which serves no purpose since that output cannot be relied upon, since it's not the full runtime environment ) as an extension to systemctl you still would need to show from where that's being picked up, from an "Environment=" entry, an file that resides in "EnviromentFile=" entry or from an script being executed in Exec*= lines and if you are only going to be showing what's in those type unit files it's should be a unit properties of show or the existing systemctl cat could be used for that.

**Comment by praiskup** [comment]
+1. The `--mock` idea sounds fine.  From the OP's perspective, `.profile` issue orthogonal
issue.  Our services' environment is reasonably clean, usually unaffected by shell startup
files.

**Comment by johannbg** [comment]
You are the same red hat employee that requested this and had it rejected downstream ofcourse it's fine for you o_O

**Comment by praiskup** [comment]
Random ideas:

With variables, there is problem with escaping (newlines, (double)quotes, ..), but
it would be nice to have the output easily parseable.  This itself is not trivial.
Would it be OK to have `--mock CMD` (argument)?  While the CMD could be
`/usr/bin/env` (or equivalent hand crafted script)?

Also, if the output should contain the 'Exec*=' line, I would vote to have it
on the first line (which would make it easier to parse in one run).

**Comment by poettering** [comment]
I am sorry, but I really don't think this is realistic to add. The env block for a service is determined at the moment we execute it. It includes information about the precise invocation ($LISTEN_PID, $MAINPID, $WATCHDOG_PID), and about stuff that is derived from dependencies pulled in by the service being activated ($LISTEN_FDS, $LISTEN_FDNAMES, $REMOTE_ADDR, $REMOTE_PORT). Stuff such as EnvironmentFiles= is read at activation time, too, might be dynamic and is not cached (which people use by referencing files in /run). 

Pretty much the only env vars that are somewhat "fixed" and do not require actual activation or actual deps to be pulled in are the ones set with Environment= but those we already expose with "systemctl show -p Environment foobar.service". And we don't really need a new command for that I think.

Sorry, but I think this really isn't realistic to add. If we'd add this, but avoid the actual activation or the actual deps stuff, then we'd synthesize something that is very far from the actual truth a forked off process would get passed – so far that I'd claim it's useless and or at best misleading to have.

If people want to see what the actual environment is that was passed to an activated service, then I also think this has no place in systemd, because the env block is subject to changes by the service and strictly per-process, not per-service. Hence, a tool for process investigation (i.e. something in  procps) would really be the better place than systemd...

This has been requested before (though under different names), and I always said the same thing: this is unrealistic to add, sorry!

**Comment by praiskup** [comment]
As this has been requested before, it sounds like it is needed.  Could we interlink
the RFEs here to see the similarities?

If time permits, I'll hack together the script serving the stuff which is unrealistic to add
directly into systemd.

**Comment by poettering** [comment]
was requested on the ML or so, don't remember the details, also, consult fdo bz.

Just because people want it, it doesn't mean we can or should provide this, if it's not implementable correctly. Sorry.

**Comment by praiskup** [comment]
> was requested on the ML or so, don't remember the details, also, consult fdo bz.

If anybody was able post here concrete links, it would be fine.

> Just because people want it, it doesn't mean we can or should
> provide this, if it's not implementable correctly. Sorry.

The info I need is definitely not implementable correctly outside from systemd,
that is why I reported this directly against systemd.  But it is needed, so .. we 
need to go the ugly way and parse by script.  That way we are unfortunately
unable to expand specifiers everywhere.

No need to say sorry :) (that many times) the important thing is that the RFE was understood
correctly (and I believe it was) because I was **not** asking for something like "deterministic"
output.

**Comment by keszybz** [comment]
Related:
https://bugzilla.redhat.com/show_bug.cgi?id=978955
https://github.com/systemd/systemd/issues/1287

I have to sadly agree with what @poettering said, this is hard to implement. I guess that the only way forward would be to figure out a not-too-intrusive implementation and restart the discussion with a concrete proposal.
