### ISSUE TITLE
systemd-cryptenroll FIDO2 hash and cipher choose during the process of adding a new key slot to unlock LUKS2 encrypted device

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#26067]
### Is your feature request related to a problem? Please describe

**systemd version the issue has been seen with**

systemd 251 (251.3-1~bpo11+1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Used distribution**

Debian 11

**Linux kernel version used**

#1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

**CPU architectures issue was seen on**

x86_64

**Component**

systemd-cryptsetup, systemd-cryptenroll

**I'have tried to use FIDO2 systemd-cryptenroll implementation with a full-disk encryption Hard-drive (without LVM) with LUKS2.**

**Here is the steps i go across to set it up:**

**sudo cryptsetup --type luks2 --cipher aes-xts-plain64 --hash sha3-512 --iter-time 9042 --key-size 512 --pbkdf argon2id --use-random --verify-passphrase luksFormat /dev/sda**
![image](https://user-images.githubusercontent.com/122745664/212561162-203aee50-1b15-44a9-ba0a-8c2294978d79.png)

**Dump of LUKS2 configuration /dev/sda:**
![image](https://user-images.githubusercontent.com/122745664/212561286-765a5f09-9271-403d-9b5a-39d6304edb6f.png)

**Then i add the FIDO2 authentification in the first keyslot avaible wich is 1, with algo eddsa:**
**systemd-cryptenroll --fido2-device=auto --fido2-credential-algorithm=eddsa /dev/sda**
![image](https://user-images.githubusercontent.com/122745664/212562253-0683593f-b38d-4a48-be23-f9eeff303545.png)

**Actually u can only choose between this algo wich are implemented in fido2 devices (if i'm not wrong)**
![image](https://user-images.githubusercontent.com/122745664/212561673-9cc86d4e-23d2-43a4-8652-a800bdc52136.png)

**Dump of new LUKS2 configuration of /dev/sda:**
![image](https://user-images.githubusercontent.com/122745664/212561587-94a9f5c5-d45e-471f-b680-5ed6c9f840a8.png)

**As u can see (difficult to not do...) i circled in red the parameter id'like to be able to change:

 - pfkdf2                     -->     OK, or argon2id
 - sha2-215                -->     sha3-512, argond2id, BLAKE3, etc...
 - Iteration = 1000      -->     A way to manually change this value if used by hash algo (not argond2id for exemple) ?**
 
**Is there any way to do it or add this functionality to symsted-cryptenroll ?
Is this a good idea ?
dos it strength in any way the LUKS2 configuration or is the actual implementation of FIDO2 using pbkdf2 with sha-512 and 1000 iteration strong enough ? (guess i like a little bit of explanation if the answer is yes)**

**So i tried with cryptsetup, but as it's doesn't support FIDO2 i wasn't surprise i cannot did it**
![image](https://user-images.githubusercontent.com/122745664/212561769-79b6e60f-5dc2-4322-9ce4-cae62032375b.png)

**I'm not a crypto specialiste in any way i'm just traying to learn and explor this field. but i do have some basis after ready that make me have this questions.**

 

### Describe the solution you'd like

**A way to select optionnal hash and cipher when configuring the FIDO2 systemd-cryptenroll:

 - pfkdf2                     -->     OK, or argon2id
 - sha2-215                -->     sha3-512, argond2id, BLAKE3, etc...
 - Iteration = 1000      -->     A way to manually change this value if used by hash algo (not argond2id for exemple) ?**

### Describe alternatives you've considered

Don't implement this functions cause there are useless ? dunno actually ..

**Comment by AidanGG** [comment]
Not necessary since the key output by the FIDO2 token follows the HMAC Secret CTAP2 extension (https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#sctn-hmac-secret-extension), so we can assume that it's already high entropy and not in need of long pbkdf, hence the minimal default pbkdf parameters you showed.

Some tokens such as the YubiKey 5 will also enforce a maximum number of incorrect UV PINs.

**Comment by poettering** [comment]
Yes, @AidanGG is right, we set the KDF to the most minimal parameters we can, because we simply don't need any KDF here, since our key is highest entropy anyway, and KDFs are slow (which is the point of them).

A KDF is generally used if you have a crappy key (let's say a password picked by a human), and want to make it "better". But in the FIDO2 key we operate with a high-quality computer generated random key, and we let the FIDO2 device HMAC it with its own high-quality key, hence the result should be highest quality too. Hence, the KDF is just a nuisance, and doesn't make anything better.
