### ISSUE TITLE
journal contains entries where MESSAGE is an array, not a string

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#26175]
### systemd version the issue has been seen with

252.2

### Used distribution

archlinux

### Linux kernel version used

6.0.10-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

According to [the specs](https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html) the MESSAGE field of a journal entry is supposed to be a string. However, ever since PowerDNS [introduced](https://github.com/PowerDNS/pdns/blob/18381787bccce187a3ea8e6ebd313e342b15ac7c/pdns/recursordist/rec-main.cc#L894) structured logging to systemd, there are messages appearing in my journal that are an array of strings instead

### Unexpected behaviour you saw

`journalctl -o json-pretty` shows the problem:
```
{
        "STATUS" : "3",
        "QUERY" : "recursor-4.8.0.security-status.secpoll.powerdns.com",
        "_SYSTEMD_SLICE" : "system.slice",
        "_SYSTEMD_CGROUP" : "/system.slice/pdns-recursor.service",
        "SUBSYSTEM" : "housekeeping",
        "MESSAGE" : [
                "PowerDNS Security Update Mandatory",
                "Upgrade now, see https://doc.powerdns.com/recursor/security-advisories/powerdns-advisory-2023-01.html" 
        ],
        "_COMM" : "pdns_recursor",
```

regardless of how this entry gets inserted, it's my understanding that `MESSAGE` is supposed to be a string, so this is a bug, right?

### Steps to reproduce the problem

run powerdns (recursor) with `--structured-logging-backend=systemd-journal`

**Comment by poettering** [comment]
journal fields can be specified more than once per log entries, that is fully support. THis is used in _UDEV_DEVLINK= for example, where a log entry will come with *all* udev symlinks listed.

powernds really shouldn't use that for MESSAGE= though. That sounds like a poor choice. It appears to me they should just use \n instead to separate their multi-line message. 

While technically we allow MESSAGE= to be defined multiple times per entry it really should not be done that way, because nothing can deal with that.

please file a bug against powerdns.

I will make the language stronger in systemd.journal-fields(7) man page, to emphasize that none of the fields should be set more than once except for the once where this is noted othewise.

**Comment by SjonHortensius** [comment]
thanks for your explanation, I did just notice this in the specs:

> In some cases, fields may appear more than once per entry

But I understand and agree with your reasoning; I'll file a bug with PowerDNS

**Comment by poettering** [comment]
→ #26181
