### ISSUE TITLE
systemd-creds: wrong file permission

### ISSUE THREAD

**Issue by quentin9696** [systemd/systemd#26259]
### systemd version the issue has been seen with

251.10-588.fc37

### Used distribution

Fedora 37

### Linux kernel version used

6.0.15-300.fc37.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

When we run `systemd-creds encrypt`, the stored file is set with the default filesystem permission (in my case `0644`). 

When I run `systemd-creds cat`, I see a warning message that tell me the permission or owner is not correctly set. If I change the permission to `0600`, I the message is not display anymore. 

### Unexpected behaviour you saw

The warning I have: 

```
password.cred has 0644 mode that is too permissive, please adjust the ownership and access mode.
```

### Steps to reproduce the problem

1. `mkdir -p /run/credstore.encrypted`
2. `echo -n "super secret" | systemd-creds encrypt --with-key=auto - /run/credstore.encrypted/password.cred`
3. `export CREDENTIALS_DIRECTORY=/run/credstore.encrypted`
4. `systemd-creds cat password.cred`

To remove the warning, I have to `chmod 600 /run/credstore.encrypted/password.cred`

**Comment by poettering** [comment]
btw, this is pretty bogus.

$CREDENTIALS_DIRECTORY is the place for plaintext creds, not for encrypted creds. The access mode check matters for plaintext creds, not for encrypted creds.

Note that systemd will pass credentials unencrypted to services, hence for services there is no $ENCRYPTED_CREDENTIALS_DIRECTORY env var that would match $CREDENTIALS_DIRECTORY (for service managers there is however).

"systemd-creds cat" operates from the PoV of a services, hence only looks into $CREDENTIALS_DIRECTOY and only deals with plaintext/decrypted creds.

Closing since this is a misuse.

**Comment by quentin9696** [comment]
Hi, 

Thanks the clarification
