### ISSUE TITLE
Encrypted LUKS root drive fails to remount with kernel parameter debug

### ISSUE THREAD

**Issue by pvdk** [systemd/systemd#26345]
### systemd version the issue has been seen with

252

### Used distribution

Manjaro

### Linux kernel version used

6.1.1-1-MANJARO 

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot, systemd-cryptsetup

### Expected behaviour you didn't see

Encrypted LUKS root partition won't get remounted when kernel parameter 'debug' is present. A message appears:

Waiting for /dev/disk/by-uuid/2833b74a-f17d-4b90-93f0-04aace0bfb84

This UUID corresponds to /dev/dm-0 which should be the encrypted LUKS root partition.

### Unexpected behaviour you saw

Waiting for /dev/disk/by-uuid/2833b74a-f17d-4b90-93f0-04aace0bfb84

### Steps to reproduce the problem

Does not work: 

`BOOT_IMAGE=/boot/vmlinuz-6.1-x86_64 root=UUID=2833b74a-f17d-4b90-93f0-04aace0bfb84 rw rd.luks.name=97eb312e-876a-4529-a3e7-81ee27073218=cryptroot debug nosplash udev.log_priority=3`

Works:

`BOOT_IMAGE=/boot/vmlinuz-6.1-x86_64 root=UUID=2833b74a-f17d-4b90-93f0-04aace0bfb84 rw rd.luks.name=97eb312e-876a-4529-a3e7-81ee27073218=cryptroot quiet nosplash udev.log_priority=3`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Please advice on which logs to include.
```

**Comment by poettering** [comment]
what do you mean be "remounted"? i.e. the `*re-*` part? what's that supposed to mean?

What the "Waiting for …" line you pasted suggests is that your LUKS device is never set up. Maybe you didn't provide your pw? did you talk to your distro about this? maybe they forgot to include systemed-ask-password-agent in their initrd?

other than that, provide debug logs of the boot. otherwise this is not actionable for us. 

https://freedesktop.org/wiki/Software/systemd/Debugging/#diagnosingbootproblems

**Comment by poettering** [comment]
Let's close this, as this is not actionable like this and none of the requested information was provided.
