### ISSUE TITLE
RLIMIT_CORE unlimited leaves core files on the filesystem

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#2643]
Original bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1309172

```
I'm on rawhide with abrt 2.8.0-2 and every time when a program crashes a file called
core.PID (where PID is the pid of the crashed program) is created in the PWD of the
crashed program. This usually means the home directory but it is also affecting system
daemons such as gdm. This machine for example has several core.PID files in /var/lib/gdm.

I've checked if it is abrt that is handling those crashes using this command:
$ cat /proc/sys/kernel/core_pattern
|/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t %P %I

Here are the journal entries from one such crash:
Feb 16 12:23:54 t420 audit[770]: ANOM_ABEND auid=4294967295 uid=1000 gid=1000 ses=4294967295 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=770 comm="nautilus" exe="/usr/bin/nautilus" sig=11
Feb 16 12:23:54 t420 kernel: traps: nautilus[770] general protection ip:7fd286898355 sp:7fd2637fd9f8 error:0 in libglib-2.0.so.0.4705.0[7fd28680a000+10d000]
Feb 16 12:23:55 t420 abrt-hook-ccpp[1463]: Process 739 (nautilus) of user 1000 killed by SIGSEGV - dumping core
Feb 16 12:23:57 t420 abrt-hook-ccpp[1463]: Failed to create core_backtrace: waitpid failed: No child processes
Feb 16 12:24:13 t420 abrt-server[1464]: Deleting problem directory ccpp-2016-02-16-12:23:55-739 (dup of ccpp-2016-02-15-08:09:19-15481)
Feb 16 12:24:14 t420 dbus[687]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)
Feb 16 12:24:14 t420 dbus[687]: [system] Successfully activated service 'org.freedesktop.problems'
```

**Comment by poettering** [comment]
Humm. No. abrt should not write core dumps everywhere, and instead honour RLIMIT_CORE like systemd-coredump does.

users and apps should have a way to disable coredumps via RLIMIT_CORE, and abrt should respect that. Also, if the core_pattern says not to store anything in the working directory, then abrt shouldn't do it anyway..

This appears to be really broken behaviour in abrt.

**Comment by jfilak** [comment]
All the time before systemd-229 RTLIMIT_CORE was 0 by default - i.e. users and apps had a way to enable coredumps via RTLIMIT_CORE (ulimit -c)  (coredumps were disabled by default).

Starting with system-229 RTLIMIT_CORE is 'unlimited'  (18446744073709551615 on my box), so everyone has coredumps enabled by default.

Please excuse my ignorance but I do not understand your point  about ABRT not respecting RTLIMIT_CORE because RTLIMIT_CORE is 'unlimited' and that means that coredump should be created.

**Comment by poettering** [comment]
Well, there are apparently two interpretation of RLIMIT_CORE:
1. abrt's: coredumps are always collected and processed, RLIMIT_CORE defaults to 0, but if RLIMIT_CORE is is != 0 they are also dumped in the process' working directory. Thus RLIMIT_CORE is only an opt-out of the process' working directory dumping, but not an opt-out for the whole collection and processing of coredumps.
2. systemd's: coredumps are collected by default, RLIMIT_CORE defaults to infinity, and RLIMIT_CORE is applied to all coredump collection and processing.

I am pretty sure that 2. makes a thousand times more sense, because it actually allows processes to fully opt-out of coredump collection and processing. It also doesn't result in littering the working directory of crashing processes with coredumps (which is a really bad idea anyway).

People kept complaining that they cannot opt-out of coredump generation before, and now they can (well, except if they install abrt)...

Anyway, I am pretty sure interpretation 1. is a bad choice, and I'd suggest abrt adopts interpretation 2. too. However, it really doesn't have to. It can just ship a file /usr/lib/systemd/system.conf.d/50-abrt.conf in its RPM containing DefaultLimitCORE=0 and get the old behaviour back.

But if I'd were you I'd ask myself two questions first:
- does dropping coredumps in process working directory every make sense? (I am pretty sure it does not)
- isn't an opt-out of the whole coredump collection/processing via RLIMIT_CORE a lot more useful than just an opt-out of the dropping-coredumps-in-process-working-directoriess.

**Comment by fsateler** [comment]
> It can just ship a file /usr/lib/systemd/system.conf.d/50-abrt.conf in its RPM containing DefaultLimitCORE=0 and get the old behaviour back.

This is very user-unfriendly due to #2121

**Comment by jfilak** [comment]
Thank you very much for your reply! I understand your points and your idea make sense to me but I believe RTLIMIT_CORE should not be used to opt-out coredumpig because Linux offers a much better way to do so via PR_SET_DUMPABLE or am I wrong?

> does dropping coredumps in process working directory every make sense? (I am pretty sure it does not)

I think it does because ABRT users want it as it pretend the well-known behavior that they are used to.

> isn't an opt-out of the whole coredump collection/processing via RLIMIT_CORE a lot more useful than just an opt-out of the dropping-coredumps-in-process-working-directoriess.

True but why not use PR_SET_DUMPABLE?

**Comment by poettering** [comment]
@jfilak RLIMIT_CORE is exposed in the shell, and people know about it. Many many daemons make it configurable. PR_SET_DUMPABLE however is something generally not exposed, and which pretty much currently only is settable from within C code.

PR_SET_DUMPABLE is strictly a security feature, and also has effects such as disabling ptracing and stuff. (also, are you sure it's inherited across execv(), which would make it a very different beast?)

OTOH RLIMIT_CORE is really a resource limit as the name suggests, and it can take a lot of other values besides 0 and infinity. Thus people may use it to reduce the load and disk/memory space a coredump takes by using it. As such, coredump pattern hooks really should honour it, to its full extend.

And yes, I know that traditionally on Linux coredumps are dropped in the working directory. But that's a pretty bad idea and always really has been, and core_pattern was initially created to redirect this to some other place precisely to avoid these weird semantics.

Yes, sometimes it's a good idea to give up on bad ideas, and dropping coredumps in the working directory is really one of those. It has a long history of security vulnerabilities and is really opaque to the user (how should he know which process currently has which working directory?). It's also unworkable in many cases due to perms problems (because the working directory is really nothing where one could write to in many cases).

So yeah, I understand your interest in exposing the Linux behaviour of 1994 with this, but you really should ask yourself if that feature is really such a great idea in the first place, and whether you really want to support that forever as default, because it really is a crappy default.

**Comment by martinpitt** [comment]
We earned a release-critical bug in Debian too about this (https://bugs.debian.org/815020). I must say I don't like this change either, as it changes the interpretation of `RLIMIT_CORE` quite substantially. This has always meant to "place an upper limit on the size of the core dump file that will  be produced", i. e. only the core _file_, which is unrelated to when using a pipe/program in `core_pattern` (that's why the rlimit is ignored for pipes). See man core(5).

@poettering, you yourself are always the first to say that systemd/userspace should not work around the kernel, but if kernel behaviour is wrong it should be changed _in_ the kernel. So changing the definition of ulimits that way is doing exactly that.. It's not systemd's place to redefine kernel behaviour IMHO.

But more importantly, what happens now is that without systemd-coredump, every crash generates a core stream which is sent to /bin/false, which is both wasting CPU time and resources, and also breaks the semantics of classic core files.

I suppose to fix this I'll have to revert the second hunk of https://github.com/systemd/systemd/commit/15a900327a, so that without having systemd-coredump/apport/abrt installed things are back to normal. Any programmatic core dump handler like apport/abort will set the core pattern to a pipe and to things by themselves, so they don't need this changed behaviour either.

**Comment by martinpitt** [comment]
Would you accept a patch which moves these settings out of the pid 1 code into a `system.conf.d/` snippet (`DefaultLimitCORE=`) and e. g. tmpfiles.d snippet for setting `core_pattern`? This is much easier to package by distros and tweak by admins.

We have to split out systemd-coredump into a separate package, as it conflicts with Apport, ABRT, and similar projects.

**Comment by martinpitt** [comment]
> and e. g. tmpfiles.d snippet for setting core_pattern?

err, of course not that, as systemd-coredump already sets it by itself.

> into a system.conf.d/ snippet (DefaultLimitCORE=)

Ah, that doesn't work as this only applies to units, not to scopes apparently (i. e. not the user sessions).

**Comment by johannbg** [comment]
@martinpitt if you have to split out systemd-coredump into separated (sub) package it just means you are doing it wrong since those other components should be implementing their own configuration files and settings which take precedence over the systemd shipped one.

**Comment by martinpitt** [comment]
I'm not a fan of these "but I have the last word" wars in packages, as this quickly leads into contradicting situations. It's also confusing if you look at a particular setting and wonder why it's not being applied; correspondingly, installing a package and wondering why it does not work. I'm not going to pour lots of "systemctl disable systemd-coredump.service" over alternative implementations.

It's much clearer if the admin explicitly chooses which implementation she wants, and all implementations conflict to each other.

**Comment by johannbg** [comment]
All of those other solutions would need to a) conflict with each other on packaging level ( which I assume they already do ) and at the same time take precedence over systemd configuration. 

The alternative to that is to convince them to use systemd implementation ( instead of their own ) to handle those coredumps  or change the upstream default to leave this completely disabled but again you should not have to split systemd-coredump into separated component then something is broken on either side. ( from my pov )

Personally I dont know anyone ( administrator or packager ) that likes the steps required to disable systemd-coredump completely so I feel your pain with regards systemctl disable systemd-coredump.service and linking to /dev/null and what not and at $dayjob we have issues with 3rd party coredump handller and systemd-coredump rendering desktop for end users completely unusable but it's seems to be something Lennart has decided should be handled this way.

**Comment by utezduyar** [comment]
Overriding core_pattern... But then they would loose the PID 1's control on the forked off tasks. Wouldn't it be nicer to forward the core to a configurable socket so systemd starts the core dump service accordingly. systemd-coredump@.service or ABRT@.service or..

**Comment by jfilak** [comment]
@poettering Yes, PR_SET_DUMPABLE is inherited acros execv()

``` bash
$ cat main.c
```

``` C
#if 0                                                                            
BINARY=${0/%.c/}                                                                 
gcc -Wall -Wextra -std=c11 -pedantic -o $BINARY $0 || exit 1                     
./$BINARY                                                                        
exit                                                                             
#endif                                                                           

#include <sys/prctl.h>                                                           
#include <sys/types.h>                                                           
#include <sys/wait.h>                                                            
#include <unistd.h>                                                              
#include <stdlib.h>                                                              
#include <stdio.h>                                                               
#include <string.h>                                                              
#include <errno.h>                                                               
#include <err.h>                                                                 

void print_dumpable(void)                                                        
{                                                                                
    int r = prctl(PR_GET_DUMPABLE, 0, 0, 0, 0);                                  
    if (r < 0) {                                                                 
        fprintf(stderr, "Cannot get PR_GET_DUMPABLE: %s\n", strerror(errno));    
        return;                                                                  
    }                                                                            

    printf("%d: PR_GET_DUMPABLE: %d\n", getpid(), r);                            
}                                                                                

int main(void)                                                                   
{                                                                                
    print_dumpable();                                                            

    int r = prctl(PR_SET_DUMPABLE, 0, 0, 0, 0);                                  
    if (r < 0) {                                                                 
        err(EXIT_FAILURE, "prctl(PR_SET_DUMPABLE, 0, 0, 0, 0)");                 
    }                                                                            

    pid_t child = fork();                                                        
    if (child < 0) {                                                             
        err(EXIT_FAILURE, "fork");                                               
    }                                                                            

    print_dumpable();                                                            

    if (child != 0) {                                                            
        waitpid(child, NULL, 0);                                                 
    }                                                                            

    return EXIT_SUCCESS;                                                         
}
```

``` bash
$ ./main.c
3855: PR_GET_DUMPABLE: 1
3855: PR_GET_DUMPABLE: 0
3856: PR_GET_DUMPABLE: 0
$ uname -r
4.6.0-0.rc4.git0.1.fc25.x86_64
```

**Comment by jfilak** [comment]
Yay, I forgot `exec`. It turned out that PR_GET_DUMPABLE returns 1 after `exec`. So, no, it does not survive fork+exec. Sorry for misleading you in the previous comment.

However, I found out that if RLIMIT_CORE is 1 then kernel does not write coredump at all. That is because: 
 1) RLIMIT_CORE=1 is a special value for pipes that tells kernel to abort dumping [1]
 2) this limit is hardly greater than the minimal supported size of coredump file by any binary format [2]

Hence, we don't need to set RLIMIT_CORE to RLIM_INFINITY just to allow processes that don't want to be dumped to reset it 0. Those processes can set their RLIMIT_CORE to 1.

1: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/coredump.c#n602
2: https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/fs/coredump.c#n660
