### ISSUE TITLE
How to disable systemd create cgroup paths in containner?

### ISSUE THREAD

**Issue by luodw** [systemd/systemd#26457]
### Component

systemd

### Is your feature request related to a problem? Please describe

Hi, I use systemd as the first process in container, but in cgroupv2, systemd will create many cgroup sub levels, I want to know how can I disable systemd create cgroup sub levels in container? thanks

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by poettering** [comment]
(and also, no you cannot do this, systemd uses cgroups to manage its services. you cannot turn this off)

**Comment by luodw** [comment]
@poettering Thanks
