### ISSUE TITLE
Boot failure regression 253 (Bisected) (lvm at fault)

### ISSUE THREAD

**Issue by Toolybird** [systemd/systemd#26488]
### systemd version the issue has been seen with

253

### Used distribution

Arch

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Boot success.

### Unexpected behaviour you saw

Boot failure.

### Steps to reproduce the problem

- install systemd-253 on a system with LVM volume as root
- regenerate initrd with dracut
- reboot

My server on Arch no longer boots after upgrading to systemd-253-1

- lvm2 2.03.18-5
- dracut 056-1

Bisected to
ca6ce62d2a437432082b5c6e5d4275d56055510f

#26474 looks related. Thanks.

**Comment by yuwata** [comment]
The system is running on a container? If so, this is a duplicate of #26474. If not, please check that the installed generators on the system write only on /run or /tmp.

**Comment by Toolybird** [comment]
No container involved. This is the initrd that is failing. How do I check installed generators inside an initrd?

**Comment by yuwata** [comment]
Please try to unpack the initrd with `cpio`.

**Comment by Toolybird** [comment]
It's just standard dracut. AFAICT these are the files involved:

https://github.com/dracutdevs/dracut/blob/master/modules.d/98dracut-systemd/dracut-cmdline.sh
https://github.com/dracutdevs/dracut/blob/master/modules.d/98dracut-systemd/rootfs-generator.sh

The Arch version of dracut is slightly behind (dracut 056-1). I hope that is not a factor.

**Comment by ljrk0** [comment]
> Please try to unpack the initrd with `cpio`.

I seem to be hitting the same issue.  In my case, `dmsetup` is not reporting any devices and no `/dev/dm-*` exist (neither `/dev/mapper/*`).  This results in `lvm_scan` not even being run.  Creating those nodes seems to at least partially be `udev`'s job through LVM's configuration files.  I didn't get around bisecting myself, but if @Toolybird could confirm that in their emergency shell these files don't exist as well, it would be a step forward I guess.

FWIW, here are two initramfs generated through dracut 059 with systemd 253 (not working) and 252 (working) as well as the failing systems `journalctl` output and `/run/initramfs/rdsosreport.txt`:

 * [253-initramfs.tar.gz](https://github.com/systemd/systemd/files/10777535/253-initramfs.tar.gz)
 * [252.5-initramfs.tar.gz](https://github.com/systemd/systemd/files/10777534/252.5-initramfs.tar.gz)
 * [253-journalctl.txt](https://github.com/systemd/systemd/files/10777539/253-journalctl.txt)
 * [253-rdsosreport.txt](https://github.com/systemd/systemd/files/10777538/253-rdsosreport.txt)

**Comment by yuwata** [comment]
@Toolybird and @ljrk0 Could you test #26494 if possible?

**Comment by Toolybird** [comment]
Thank you @yuwata. #26494 fixes the problem for me.

**Comment by yuwata** [comment]
@Toolybird Thank you for testing the PR so quickly!

**Comment by poettering** [comment]
so what's the issue? the lvm scripts of your initrd fail if the generators don't allow writing to arbitrary places? sounds like a bug in those lvm scripts. generators were expressly documented to not do that, ever.

See:

https://www.freedesktop.org/software/systemd/man/systemd.generator.html#Output%20directories

To quote:

> Note: generators *must* *not* write to other locations or otherwise make changes to system state. Generator output is supposed to last only until the next daemon-reload or daemon-reexec; if the generator is replaced or masked, its effects should vanish.

I am not sure how we could make this language any stronger.

**Comment by keszybz** [comment]
https://github.com/dracutdevs/dracut/blob/master/modules.d/98dracut-systemd/rootfs-generator.sh
writes to `"$hookdir/initqueue/finished/devexists-${_name}.sh"` and `"$hookdir/emergency/80-${_name}.sh"`. Strangely, it also writes to `/run/systemd/generator/systemd-fsck@"${_name}".service.d/after-pre-mount.conf` (i.e. hardcodes the output directory instead of using the one given in the commandline argument), which could create a nasty surprise if somebody is doing a test run.

I think this generator should just be fixed to not do this. Why create scripts dynamically at runtime based on some conditions when you can just create them statically and put those condition checks in the script? This makes things more complex than they need to be. And this ties the state of the dracut initqueue to daemon-reload cycle. In particular, if daemon-reload is executed, those files are rewritten in place, so if you time things just right, dracut will try to execute an empty or partially written initqueue job. I don't think we should add workarounds in systemd to support such setups.

**Comment by yuwata** [comment]
Yeah, actually the rootfs-generator.sh does something spurious. Dropped 'bug' tag.

**Comment by keszybz** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2164404

We discussed this with @lnykryn and Pavel Valena and they'll look into making a patch for dracut.
In Fedora, I'll temporarily apply @yuwata's patch from #26494. I think we can close this.
