### ISSUE TITLE
Allow CREDENTIALS_DIRECTORY to be configurable

### ISSUE THREAD

**Issue by LaserEyess** [systemd/systemd#26485]
### Is your feature request related to a problem? Please describe

For services/daemons that have a configuration file that does not do environment parsing, `${CREDENTIALS_DIRECTORY}/my_cred` is not really an option. You would have to do some weird stuff like adding an `ExecPreStart=/usr/bin/bash script_to_generate_config` or some other crazy things to get `$CREDENTIALS_DIRECTORY` working with such services.

Admittedly, I started thinking about this when thinking about encrypting my sshd host key, and there is already a solution for that:
```
ExecStart=sshd -D -oHostKey=${CREDENTIALS_DIRECTORY}/sshd_key
```
But there are services where this isn't possible, or these isn't an easy solution such as sshd. 

### Describe the solution you'd like

Something like `CredentialsDirectory=/some/user/path` that is automatically mounted in the service. So then instead of `${CREDENTIALS_DIRECTORY}/my_cred` one could do `/some/user/path/my_cred`.

### Describe alternatives you've considered

```
BindReadOnlyPaths=${CREDENTIALS_DIRECTORY}:/some/user/path
```
Honestly if this works it's probably good enough, but I think an explicit feature for this would be nice. 

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by LaserEyess** [comment]
`systemd-creds` was not an option in the components dropdown btw

**Comment by poettering** [comment]
I am not convinced this is desirable. We want uniformity, and ideally daemons should just honour $CREDENTIALS_DIRECTORY natively. It's doomed to wrangle systemd into generating just the right directory hierarchy for some crappy daemon.

$CREDENTIALS_DIRECTORY as the name suggests will set up a whole directory of things with very special semantics. Even if we wanted to it would be really hard to make this something you can "merge" into a pre-existing dir that otherwise is already populated.

You can always ExecStartPre= with "ln -s"

or you can use BindPaths= with the `%d` specifier. 

Anyway, I am very cool about this idea, sorry.

**Comment by LaserEyess** [comment]
That makes sense, but would e.g. `BindPaths=%d:/some/path` be supported for this? By that I mean is there any downside to doing this that could cause incompatibilities and make it unusable in the future. 

It just surprises me that the usecase hasn't shown up before. For example I don't know how one would manage this for tls keys with nginx without doing some sort of path manipulation in the unit file or `ExecStartPre=`. I would have expected some docs explaining this but I guess perhaps it's just obvious (??).

**Comment by poettering** [comment]
> That makes sense, but would e.g. `BindPaths=%d:/some/path` be supported for this? By that I mean is there any downside to doing this that could cause incompatibilities and make it unusable in the future.

well, this forces your service into a mount namespace, thus if your service establishes new mounts they wouldn't appear on the host.

otherwise shuld be fine.
