### ISSUE TITLE
Mount ESP to /efi when root=tmpfs on gpt-auto-generator

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#26489]
### Component

systemd-gpt-auto-generator

### Is your feature request related to a problem? Please describe

I'm trying to boot a system with `root=tmpfs usrhash=<dm-verity-hash>`. In this setup, by the time systemd switches-root, /sysroot contains neither /boot nor /efi. After the pivot, systemd executes `gpt-auto-generator`, which detects that /efi is missing and thus decides to mount the ESP to /boot. The `boot.automount` unit created by the generator eventually creates the /boot directory and mounts the ESP there.

This might be an issue simply because it introduces a little bit of complexity in finding the ESP. Depending on whether an XBOOTLDR partition was necessary at install time, the ESP will either be located at /boot or at /efi (and something else will be at /boot). If I were using a root partition, I'd fix this by just creating an empty /efi directory to make sure the ESP is always in the same place. However, with `root=tmpfs`, `gpt-auto-generator` won't behave in this way

### Describe the solution you'd like

`gpt-auto-generator` detects that /boot doesn't exist either, concludes that the system is booting with a volatile rootfs, and creates units that mount the ESP to /efi rather than /boot. Thus, /boot only exists if there is an XBOOTLDR partition

### Describe alternatives you've considered

- A unit to run in the initrd right before switch root that does `mkdir /sysroot/efi`
- Getting systemd-tmpfiles to run in the initrd before switch root, and then configure an entry to make /efi within /sysroot

### The systemd version you checked that didn't have the feature you are asking for

252.5

**Comment by AdrianVovk** [comment]
If you think my solution is acceptable I can implement it

**Comment by poettering** [comment]
I am not sure what your goal is? You want that the esp is mounted to /efi/ no matter what? So far our thinking was that /boot/ is where kernels shall be placed, i.e. xbootdlr if it exists and esp otherwise. Why would we depart from that rule?

wouldn't adding a symlink or bind mount from /efi to /boot better to achieve what you want?

or what am i missing?

(We generally recommend using "bootctl -x" and "bootctl -p" to find the relevant paths.)

**Comment by AdrianVovk** [comment]
My impression was that you'd prefer to mount the ESP to /efi (and leave /boot for a potential XBOOTLDR partition), but on systems that don't have an /efi mount point you mount the ESP to /boot just as a fallback. Perhaps I'm wrong about this preference?

The bug is that when root=tmpfs, you never get to execute on that preference because /efi doesn't exist (but neither does /boot!)

By no means is this a major issue. Just a small consistency nit I noticed while trying to figure out what gets mounted where and how when root=tmpfs.

**Comment by poettering** [comment]
uh, so i got confused for a moment. The current logic goes like this:

1. mount xbootldr to /boot always (creating it if needed)
2. mount ESP to /efi if exists
3. mount ESP to /boot if that exists and /efi does not
4. mount ESP to /efi otherwise (creating it) 

So yeah, we actually do prefer /efi/ as mount point for the ESP, we only use /boot/ for it if /efi does not exist, but /boot does.

**Comment by poettering** [comment]
so what i don#t grok is why you say in your case gpt-auto decides to mount the ESP to /boot. it shouldn't do that unless you have /boot in your tmpfs already?

**Comment by AdrianVovk** [comment]
I don't think there is a check for whether or not /boot exists.

https://github.com/systemd/systemd/blob/main/src/gpt-auto-generator/gpt-auto-generator.c#L515-L530

Looks like the logic is:

1. mount XBOOTLDR to /boot always (creating it if needed)
2. Mount ESP to /efi if it exists
3. Mount ESP to /boot if there is no xbootldr partition, creating /boot if needed
4. Mount ESP to /efi, creating it if needed
