### ISSUE TITLE
Poweroff/reboot actions logging

### ISSUE THREAD

**Issue by pboguslawski** [systemd/systemd#26519]
### Component

systemctl

### Is your feature request related to a problem? Please describe

When admin executes `reboot` or `poweroff`, systemd starts operation without logging this fact in journal/syslog.

### Describe the solution you'd like

Reboots/poweroffs/halts are important events and should be logged; i.e. `user ... initiated system reboot|shutdown|halt`.

### Describe alternatives you've considered

Auditd but logging such events in system log should be implemented independently IHMO.

### The systemd version you checked that didn't have the feature you are asking for

247

**Comment by poettering** [comment]
we log them. and you can even search for them by message id:

journalctl MESSAGE_ID=98268866d1d54a499c4e98921d93bc40

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
