### ISSUE TITLE
Running cron tasks under the user account

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#26598]
### systemd version the issue has been seen with

252

### Used distribution

Fedora 37

### Linux kernel version used

6.1

### CPU architectures issue was seen on

other

### Component

systemd

### Expected behaviour you didn't see

This is not a bug report per se, this is a question but I've no idea who I can ask it, so that's it.

User session management in Linux has become quite complicated nowadays, so not only we have the old `DISPLAY=:0.0` environment variable for Xorg users + `XAUTHORITY`, we now have Wayland and PipeWire.

Imagine I want to create a cron task which runs an app which uses my graphics output **and** audio.

**What's the most efficient way to do that for a certain user which is known to be logged in?**

If you simply do this:

01 12 * * * username /home/username/bin/script.sh

It will fail. No running graphics app, no audio for it, all the right variables are not set.

So, how can I enable/populate/fetch all the needed variables for
1) Graphics output
2) Audio output?

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
