### ISSUE TITLE
EVM + SE-Linux no_label errors for setting up udevd temples

### ISSUE THREAD

**Issue by mtayyabm** [systemd/systemd#26614]
I am running systemd 247.3-7 and Kernel 5.15.92 on raspberry pi-4 (64bit)
* Enabled SELinux standalone, it works good
* Enabled EVM (cert based). Verified the public key is loaded in the .evm ring. In the evm=fixed mode and in evm=enforced mode at kernel . Without selinux enabled, system works fine.
* IMA is enabled but no policy at all (for this test case), it ensures that ima is not interfering.
* EVM and SELinux simultaneous: Simultaneously enabling EVM and SELinux results in a lot of audit logs with "op_appraise" by integrity subsystem due to "no_label" error. Mainly, udev, logind spits out these issues. 
whenever a file is created with selinux enabled, it gets an xattr, when anything tries to change the mode/owner/group of the file, EVM prevents from changing that. 
How to solve this issue?

**Comment by poettering** [comment]
talk to the EVM/selinux people, this is the systemd project.

Also:

*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
