### ISSUE TITLE
SystemCallFilter and the landlock LSM

### ISSUE THREAD

**Issue by rfc1036** [systemd/systemd#26913]
### systemd version the issue has been seen with

252

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

A Debian package that I maintain (OpenBSD's rpki-client) started using the Landlock LSM to provide hardening features similar to OpenBSD's `unveil(2)`, but it fails when started with `SystemCallFilter=@system-service` because the Landlock system calls are not permitted by the filter.

Should the Landlock system calls be included in `@system-service`? In some other group? Or not at all and each daemon using them should list them explicitly?

### Unexpected behaviour you saw

The landlock calls fail with EPERM and the daemon terminates.

**Comment by bluca** [comment]
I think it makes sense to have shortcuts for LSMs - maybe one per type, or one for all LSMs

**Comment by poettering** [comment]
I am not convinced this should be subsumed into @system-services. Probably get its own group or so. or something like `@sandbox` together with seccomp or so

**Comment by poettering** [comment]
So with #26960 you can add `@sandbox` to your filter list, and get all landlock syscalls allowlisted (plus seccomp)

**Comment by poettering** [comment]
syscall filters means reduction of attack surface. and security frameworks add complexity and hence attack surface. It's not always clear if the enforcement capabilities they bring to the table clearly outweighs the complexity and attack surface they themselves bring along. To give an example, user namespaces are a security technology, as they isolate user resources from each other. But the concept single-handledly is responsible for the majority of CVEs of the Linux kernel for the first years it was added to the kernel... Because of that history there's even now an LSM hook specifically protecting that. I am just trying to be defensive here. I mean, it#s super-easy to enable, just add the `@sandbox` thing too and you are done.

Moreover, things like seccomp can actually be used for evil means too, i.e. trigger error conditions where normally there aren't. To lock this down a bit people came up with PR_NO_NEW_PRIVS (so that artificial error conditions cannot be triggered with that in higher privileged code). But the power of things like seccomp, and in particular seccomp can be a dangerous concept.

Hope that makes some sense?

**Comment by l0kod** [comment]
> syscall filters means reduction of attack surface. and security frameworks add complexity and hence attack surface. It's not always clear if the enforcement capabilities they bring to the table clearly outweighs the complexity and attack surface they themselves bring along. To give an example, user namespaces are a security technology, as they isolate user resources from each other. But the concept single-handledly is responsible for the majority of CVEs of the Linux kernel for the first years it was added to the kernel... Because of that history there's even now an LSM hook specifically protecting that. I am just trying to be defensive here. I mean, it#s super-easy to enable, just add the `@sandbox` thing too and you are done.

I agree that we should control syscalls, especially those managing namespaces, which were not designed for security.

However, seccomp and Landlock are designed with security in mind, to improve the security of the entire system and reduce the attack surface. They are designed to be safely used by unprivileged processes, and overall, they can greatly improve the security of such processes.

> 
> Moreover, things like seccomp can actually be used for evil means too, i.e. trigger error conditions where normally there aren't. To lock this down a bit people came up with PR_NO_NEW_PRIVS (so that artificial error conditions cannot be triggered with that in higher privileged code). But the power of things like seccomp, and in particular seccomp can be a dangerous concept.

seccomp can cause bugs (e.g. by changing the behavior of syscalls), but seccomp cannot cause security issues more than what is inherently possible by controlling execution of the current thread. Not be able to use seccomp could also cause bugs because on a "normal" system, seccomp should be available.

Anyway, my point is that these syscalls should always be available to any processes for them to be able to limit the impact of exploited vulnerabilities in their code. I think that the use of systemd to manage services should not degrade the security of (already sandboxed) services. I agree that `@sandbox` is easy to use, but it is much easier to forget, see #34552
