### ISSUE TITLE
systemd-user-sessions deletes /etc/nologin

### ISSUE THREAD

**Issue by sjquinney** [systemd/systemd#26965]
### systemd version the issue has been seen with

252

### Used distribution

Debian

### CPU architectures issue was seen on

None

### Component

systemd

### Unexpected behaviour you saw

We use pam_nologin to deny user access to systems whilst we work on them. Recently, whilst doing maintenance on a server, I put a helpful message into /etc/nologin. After a reboot, I was surprised to discover that this file had been deleted by something which led to users gaining access before we were ready.

Using the Linux auditd I tracked down the file deletion to systemd-user-sessions.service. Reading the man page for that service, it only mentions using the /run/nologin file.  Checking the source code for src/user-sessions/user-sessions.c though I see in the start method:

                r = unlink_or_warn("/run/nologin");
                k = unlink_or_warn("/etc/nologin");

There doesn't seem to be any good reason given for this service to also delete the file in /etc.  This leaves me with no easy way to set my own nologin file that will be preserved over a reboot. I realise that I could just remove the service completely but this doesn't seem like appropriate behaviour, I'm sure it will surprise other sysadmins who expect to be able to rely on pam_nologin to keep systems secure.

**Comment by keszybz** [comment]
The code was like this since its introduction in e92787416c691c3f34f47349e5eae3fa68eae856. pam_nologin looks for both files.

I think it would be reasonable to adjust the code to match the docs. We should only delete the file that we create ourselves. I don't think there's a good reason to touch `/etc`, this is admin territory.

**Comment by poettering** [comment]
/run/nologin was our invention, we asked for the file to be moved from /etc/ to /run/ and it was. Long ago. We still manage both files because we wanted compat with the old PAM. Before dropping the old file we should verifiy support for /run/nologin is well enough supported elsewhere and for long enough, and maybe document the minimal version of PAM (and login?) that we then require to work correctly.

/etc/nologin was never an admin thing on sysv but a system thing. We can turn it into an admin thing now though I guess, but this is a change of semantics.

**Comment by poettering** [comment]
man-pages package still only mentions /etc/nologin, and no /run/nologin. Needs further investigation whether we really can drop this.

**Comment by poettering** [comment]
So util-linux `nologin` tool actually shows `/etc/nologin.txt`, and neither `/etc/nologin` nor `/run/nologin`...

This seems quite confusing.

**Comment by poettering** [comment]
PAM added support for `/var/run/nologin` in e9e593f6ddeaf975b7fe8446d184e6bc387d450b btw, which is from 2010.

I think it probably would make sense to ask them to update this to actually reference `/run/nologin` since `/var/run/` is a symlink to `/run/` anyway, and the indirection just means the file can be accessed during late boot only.

**Comment by poettering** [comment]
hey @karelzak what's the story with util-linux reading `/etc/nologin.txt`? why different from pam_nologin?

hey, @ldv-alt can we change pam_nologin to check `/run/nologin` instead of `/var/run/nologin`?

i.e. can we maybe agree that every tool checks `/etc/nologin` first, and then `/run/nologin` as fallback? 

And then systemd would only bother with `/run/nologin`, and nothing else anymore.

**Comment by keszybz** [comment]
> So util-linux `nologin` tool actually shows `/etc/nologin.txt`, and neither `/etc/nologin` nor `/run/nologin`...

`nologin` is a per-user mechanism, generally unrelated to `pam_nologin`. It is reasonable that they use the different files for the message, though the naming could be a bit clearer.

**Comment by poettering** [comment]
hmm, indeed /etc/nologin.txt and /etc/nologin are indeed different things. I wished the man pages would clear this up. Man this is confusing.

**Comment by sjquinney** [comment]
The man page for pam_nologin (at least on Debian and Ubuntu) is fairly
clear:

      pam_nologin is a PAM module that prevents users from logging into the
       system when /var/run/nologin or /etc/nologin exists. The contents of
       the file are displayed to the user.

I think that's ideal behaviour, it allows for systemd stuff to happen with
/var/run/nologin and for the admin to also express a preference with the
file in /etc/nologin.

**Comment by karelzak** [comment]
nologin(1) from util-linux replaces shell in /etc/passwd. It always refuses login to the system, and the optional file /etc/nologin.txt is just a message for users, nothing else.

PAM uses  /var/run/nologin or /etc/nologin to control the module behavior.  See man nologin(1), NOTES section.

It means the purpose of the files is completely different.  

(Maybe /etc/nologin.mesg would be a better name for the file, but it's probably too late to change it.)
