### ISSUE TITLE
systemd-fstab-generator generates a dangling symlink under specific conditions

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#27156]
### systemd version the issue has been seen with

latest main

### Used distribution

Fedora Rawhide

### CPU architectures issue was seen on

None

### Component

other

### Unexpected behaviour you saw

While writing tests for systemd-fstab-generator I came across a very specific corner case, in which fstab-generator generates questionable results:

```
# mkdir out
# SYSTEMD_LOG_LEVEL=debug SYSTEMD_PROC_CMDLINE="" SYSTEMD_IN_INITRD=1 SYSTEMD_FSTAB=/dev/null SYSTEMD_SYSROOT_FSTAB=/dev/null /usr/lib/systemd/system-generators/systemd-fstab-generator out
Could not find a root= entry on the kernel command line.
Parsing /dev/null...
Parsing /dev/null...
# echo $?
0
# ls -lR out/
out/:
total 4
drwxr-xr-x. 2 root root 4096 Apr  5 14:42 initrd-usr-fs.target.requires

out/initrd-usr-fs.target.requires:
total 0
lrwxrwxrwx. 1 root root 16 Apr  5 14:42 sysroot.mount -> ../sysroot.mount
```

in other words - there's a dangling symlink to `sysroot.mount`. However, as stated above, this is a very specific corner case probably nobody will run into, but maybe it should be handled slightly better.

**Comment by keszybz** [comment]
This symlink is generated when the generator has **not** created a `sysroot.mount` or `sysusr.mount`.

The symlink being dangling is fine: pid1 doesn't care about this, as long as the symlink points into one of the unit directories. It would be nicer to link to some real file, to avoid user confusion, but `sysroot.mount` has no static fragment file, so we can't do that easily.

There's also a question of what happens with `initrd-usr-fs.target` and units that depend on it. The target will now fail to start because `sysroot.mount` cannot be found. But units that order themselves `After=initrd-usr-fs.target` would be fine. I guess that the target failing is appropriate in this case.

@poettering PTAL too.
