### ISSUE TITLE
systemd-creds rootless or notify rootless?

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#27192]
### Component

other

### Is your feature request related to a problem? Please describe

Hi 👋 

I’m facing this issue related to the use of podman in systemd units: https://github.com/containers/podman/issues/12778.

According to [this answer](https://github.com/containers/podman/issues/12778#issuecomment-1008945410), this is a known limitation of systemd and using `--user` is the good practice.

However, we are using systemd-creds, which - to my knowledge - cannot be used rootless. I don't think realistically that systemd-creds could ever be used rootless (unless perhaps with subkeys…), so I'm a bit stuck.

### Describe the solution you'd like

Allow the user in `User` to notify?

Or any viable solution to the problem I'm mentioning? For me, this is a deal breaker for systemd-creds… If I have the choice between rootless containers and sane secret management: I'm gonna go with the juicy cleartext secrets.

The question I'm asking myself - and pardon my lack of knowledge - is preventing notify for rootless user a bigger security risk compared to both rootful containers and bad secret management?

I’d be happy to clarify if needed. Thanks a lot!

### Describe alternatives you've considered

- Forking and PID are not an option either, because of the famous "this pid does not belong to the user or root" when using cgroupv2.

- using cgroupv1 with forking. Does not work anymore because of a bug in network namespacing. Broke our production.

- Other `Type`, but not working with podman.

### The systemd version you checked that didn't have the feature you are asking for

253.2

**Comment by poettering** [comment]
hmm? what do you mean by systemd-creds specifically? The ability to encrypt and bind to the tpm or what? not sure i grok what the issue here precisely is.

The general credentials concept should work unpriv too.

**Comment by poettering** [comment]
> Allow the user in `User` to notify?

what is that supposed to mean?

i am not really understanding a word you are saying. I am not at home with podman. Not sure what podman is doing with systemd-creds? it's news to me it is doing anything with it?

**Comment by gui-don** [comment]
> Not sure what podman is doing with systemd-creds? it's news to me it is doing anything with it?

Podman itself do not use systemd-creds. **_I_** would like to use systemd-creds and pass credentials to a container manager, that happens to be podman in my case.

I'm refering to [this comment](https://github.com/containers/podman/issues/12778#issuecomment-1008945410) stating:
> This is a limitation on the systemd side. They will only accept notifications, or PID files, that are created by or sent by root, for security reasons - even if the User and Group of the unit file are explicitly set to start the process as a non-root user. 

But maybe this comment is incorrect.

---

> The general credentials concept should work unpriv too.

Do you really mean _should_ or _already does_? To my knowledge, I cannot use systemd-creds unpriv because:
> A secret key stored in the /var/lib/systemd/credential.secret file which is only accessible to the root user.

Maybe it is possible to use systemd-creds without root with TPM, but I'm hitting an issue that I opened a while back (AWS VMs not having virtual TPM2): https://github.com/systemd/systemd/issues/23566

Here is a summary of the problem:

- podman has [this problem I mentionned](https://github.com/containers/podman/issues/12778) - they claim they can’t properly sd_notify because of permission issues.
- And:  the general recommendation for unprivileged systemd units seems to be to run them _as_ the intended user and avoid root + `User=`.
- But: because I use systemd-creds (without TPM), the unit needs to run as root (with `User=` to avoid running containers as root).
- And: podman members seems to direct part of their permission difficulties with sd_notify to systemd. They claim they cannot sd_notify in a unit started as root with `User=` (as far as I understand the problem).

But after more tests, it seems it is indeed possible to notify in these conditions. So I guess I'm gonna ask on their side for clarifications.
Thanks.

**Comment by Nairou** [comment]
Came here with the same question. I want to use credentials in user services, but am unable to generate a rootless `credential.secret` to use in encrypting/decrypting files for the user.

I don't want to rely on the system `/var/lib/systemd/credential.secret` file, as that could change, breaking the user service.

**Comment by hseg** [comment]
> Came here with the same question. I want to use credentials in user services, but am unable to generate a rootless `credential.secret` to use in encrypting/decrypting files for the user.

Same here - though my usecase is perhaps abusing the system: oauth key management services need someplace to store refresh and auth tokens, which need to be secured at rest. Many guides suggest keeping these in gpg-encrypted files, and using gpg-agent to make sure the service is able to read/write to them.
Which is fine, and can be made to work, but I was hoping systemd would provide something more idiomatic -- `systemd-creds` seemed to fit the bill.

**Comment by poettering** [comment]
> * podman has [this problem I mentionned](https://github.com/containers/podman/issues/12778) - they claim they can’t properly sd_notify because of permission issues.

Sorry I cannot parse this. THis might be digestable for people who are podmanheads, but I am not, I don't follow, this is way too long. If you want me to understand this, you need to break it down with general words, not some podman gobbledegook

**Comment by gui-don** [comment]
Hey @poettering, you’re not alone being confused.

Let me summarize what I know:

- It’s not possible to create a systemd service with the combination of `User=…` and `Exec=podman run …` and `Type=notify`.
- Podman people claims it’s a systemd issue - without much justification (that’s why I created this ticket)
- However, after tests by the community and myself, it seems the comination `User=…` + `Type=notify` + `Exec=anything but podman` actually works, pointing toward a podman issue, more than a systemd issue.

**Comment by poettering** [comment]
> * It’s not possible to create a systemd service with the combination of `User=…` and `Exec=podman run …` and `Type=notify`.

User= and Type=notify should work fine together. I have no idea what Exec=podman would do to that. Can you explain this to me without and podmanisms?

Also what does Type=notify have to do with credentials?

This is really not the forum to ask podman questions though.

**Comment by poettering** [comment]
I mean, I sense from this that you want encrypted credentials you can use in per-user services (i.e. those that run inside a systemd --user service manager). We do not have that right now, but we could add that.

But I am a bit lost here, I don#t really grok what this issue is supposed to be about

**Comment by gui-don** [comment]
> I mean, I sense from this that you want encrypted credentials you can use in per-user services (i.e. those that run inside a systemd --user service manager). We do not have that right now, but we could add that.

Oh, that would be awesome yes.

My context:

- We want to use `systemd-creds`;
- We don’t have any TPM2 chip (AWS limitation), so we use the "host" password feature of systemd-creds.
- This does not work with fully rootless units (`--user`)

There we can stop. That’s my problem with systemd.

---

Then, it lead to the additional **podman** issue:
- Because we can’t use `--user`, we use `User=`
- And: it’s not possible to create a systemd service with the combination of User=… and Exec=podman run … and Type=notify…
- etc.

**Comment by gui-don** [comment]
I'm closing in favor of https://github.com/systemd/systemd/issues/30191.
