### ISSUE TITLE
systemctl edit: remove empty dir after abandoned edit

### ISSUE THREAD

**Issue by ackalker** [systemd/systemd#2734]
### Submission type

[ ] Bug report

[X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch Linux latest
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> …

After abandoning a `systemctl edit NAME` for a unit with no existing drop-in files, there remains an empty directory `.../systemd/.../NAME.d`. It would be nice if systemctl removed this directory, similar to how `systemctl disable` removes directories which have become empty as a result of its actions.

**Comment by johannbg** [comment]
Is there some tool that is reporting to upstream like this or is it being done as from another bug tracker?

**Comment by ackalker** [comment]
@johannbg I don't know what you mean. If you mean the formatting of the report, it appears to be a template generated by Github. I was not aware of such a feature, but there.

**Comment by ackalker** [comment]
@johannbg Perhaps like this: [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by johannbg** [comment]
@ackalker yeah meant the formatting of the report which suggested some tool and or workflow in downstream tracker. 

bi-direction communication can be achieved quite easily between upstream and downstream using proper bug tracker but it is only applicable to downstream using latest ( same thing goes with any upstream reporting tool ) which pretty much limits it to arch. 

Was not aware of nor did not expect this to be an feature of github which indicates someone turn it on when it should stay off.

**Comment by zonque** [comment]
> Was not aware of nor did not expect this to be an feature of github which indicates someone turn it on when it should stay off.

It was deliberately switched on in #2686

**Comment by johannbg** [comment]
Github issue tracking is crap and template that clutter bug reports wont fix that. 
Reporters wont fill out fields since they cannot be made required, you cannot differentiation an feature from a bug (which you normally do with different issue types hence those check box in the template ) you still need to manually assess and tag those reports,do unnecessary bidirectional communication with reports, basically your not doing anyone a favour by enabling this nor offloading any work of yourself and just end up cluttering reports with fields that never will get filled.  

If and then when you guys finally reach the conclusion that a proper bug tracker is the thing to go I can resurrect the work I had already put in creating one for the community and provide you with something that actually is useful and takes the load off your back and grants you that time for another round of beer ;)
