### ISSUE TITLE
With NIS domain, systemctl restart redis hangs and  a new process (s-server)  eats memory  quicky to 50G, and be killed by OS

### ISSUE THREAD

**Issue by hejiwen** [systemd/systemd#27366]
### systemd version the issue has been seen with

243

### Used distribution

fedora31

### Linux kernel version used

4.19.90

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

systemctl restart redis  return quickly and systemctl status redis shows redis is running 

### Unexpected behaviour you saw

the redis service isn't running , a new process (s-server) eats memory quicky, about one minute later, it will be killed by os.

### Steps to reproduce the problem

1. config yp.conf
2. systemctl start ypbind
3. config nsswitch.conf： add nis keyword to group line
4. systemctl restart redis

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
