### ISSUE TITLE
RFE: Add systemctl --user=otheruser

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#2736]
To manage another user's systemd user instance, you currently need something like:

```
sudo -u otheruser env XDG_RUNTIME_DIR=/run/user/$(id -u otheruser) systemctl --user
```

Could we have `systemctl --user=otheruser`?
Similarly `journalctl --user=otheruser` would be useful.

**Comment by poettering** [comment]
Hrmpf. I really don't like this. Higher priviliged code should never call (and in particularly not synchronously) into lower privileged code. It should instead be the lower privileged code that reacts to notifications from the higher priviliged code (and that asynchronously).

This has been requested before in other ways: i.e. a way to connec to a user's bus or systemd instance from system code. But each time we turned this down really, because it's an invitation to stack the system the wrong way round...

Also, and most importantly: as you showed above you can already do that without native, direct support in systemctl. Hence I'd prefer to leave it at that: it works already, and is not an invitation to cross privilige seperations the wrong way round...

I hope that makes some sense! Sorry!
