### ISSUE TITLE
journalctl behaves in unexpected ways if there are logs the future

### ISSUE THREAD

**Issue by LukeShu** [systemd/systemd#2738]
### Submission type

[x] Bug report

[ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

229
### Used distribution

Parabola GNU/Linux-libre (derivative of Arch Linux)
### In case of bug report: Expected behaviour you didn't see

I expected `journalctl --follow --since='1 min ago'` to print things that happened in the last minute, then start showing new things as they happen.
### In case of bug report: Unexpected behaviour you saw

I did not expect (when run on February 24) to see lines beginning with "Jan" and no year at the top of the output when running `journalctl --follow --since='1 min ago'`
### In case of bug report: Steps to reproduce the problem

Set the time to some time in January, 2099 (as happens on some ThinkPads if you pull the BIOS battery out), boot, and let some events hit the journal.  Then, let NTP (timesyncd) set the time correctly. Proceed to be confused by the output of journalctl for a month before you take the time to figure out what happened.

I had no idea that there were journal events from 2099 (timesyncd fixed it before I noticed).  Since January 2099 is indeed after '1 minute ago', 2016, it printed.  Confusingly, it printed without a year (I assume because it checks something like `event->year < now->year`). I believe that at the very least, it should print a warning about journal dates in the future.

**Comment by ohsix** [comment]
times are smelly, what is the 'future' depends on your clock, as you've noticed, so you have the same problems looking at journals that are from 'now' on machines with clocks that are behind (arbitrarily behind, could be as far back as the 1970s)

there are monotonic timestamps in the journal, so if you log something with the clock at say, 2016, then set the clock to 1980, then 2016 again; they'll all be sequenced correctly by something like '--follow'

the problem arises when you use the wall clock to decide what to view, what is in the future is only relevant to the wall clock and your concept of time, and is introduced by 'since'

something could probably be done but i don't think introducing another message about 'the future' (introducing wall time again) can be one of them, there are systems without clocks entirely that will have and will work with journal files, the messages will be meaningless to anyone aware of what's going on with their clock and only forestalls surprise of someone who doesn't

**Comment by LukeShu** [comment]
Yeah, time is gross.

There's definitely at least a bug though in the default format with the date being formatted without a year for years in the future.

I just tried to replicate again, and it seems there's a bit more to get the weirdness I was seeing.  Perhaps something with reboots?

I'd fixed my issue (`rm` the offending journal files, identified with `--header`), then it occurred to me that I should file a bug, since it had me scratching my head for so long ("why is it showing me entries from a month ago?").  Maybe I was just getting confused because of the date formatting, but I _think_ that there was a delay, then it showed me the actual recent stuff.  

I guess this just stopped being a useful bug report, huh?

**Comment by LukeShu** [comment]
Yeah, I've tried a couple of things now, and I can't get it to show me the future events every time I type `--follow` anymore.  Now I really wish I didn't delete that file.

I guess feel free to close this since I have no proof or testcases.

**Comment by poettering** [comment]
--since= and --until= operate purely on calendar time, and the relative specifications are hence subject to invalid system time. We should clarify that in the man page though.

Given that this is not reproducible, I will now turn this into a documentation bug so that we clarify the above.

**Comment by keszybz** [comment]
This should be improved with #4362, and journalctl should not get confused anymore. Nevertheless, the docs should probably be still updated.

**Comment by qouoq** [comment]
I've had for the past 6 months a few screens worth of journal entries from 2080. As in the case initially reported by @LukeShu, that's due to a CMOS reset followed by an eccentric clock initialization.

These entries made journalctl -f unusable, and journalctl -e inconvenient (had to scroll up a lot to get to the actual last messages).
The solution mentioned above was the perfect one for my case (getting rid of the future entries without touching the rest of the journal), that is: `journalctl -e --header` to identify the journal files, then remove the files identified.

It could be that the problem I had is known and documented, but then its solution is not very discoverable. Since this GitHub issue is still open, I report here with the hope it may be useful, to systemd team or to users looking for a solution.

(systemd 241-7, Arch linux)
