### ISSUE TITLE
Setting DefaultCPUAccounting=yes not enabling cpu for cgroups

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#27538]
### systemd version the issue has been seen with

systemd 250 (250-12.el9_1.3)

### Used distribution

almalinux 9.1

### Linux kernel version used

5.14.0-162.23.1.el9_1.x86_64

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

```
[root@host~]# cat /sys/fs/cgroup/aa/cgroup.controllers
io memory pids
[root@host~]# ls /sys/fs/cgroup/aa/
cgroup.controllers  cgroup.max.descendants  cgroup.type    io.max          memory.events.local  memory.numa_stat     memory.swap.events  pids.max
cgroup.events       cgroup.procs            cpu.pressure   io.pressure     memory.high          memory.oom.group     memory.swap.high
cgroup.freeze       cgroup.stat             cpu.stat       io.stat         memory.low           memory.pressure      memory.swap.max
cgroup.kill         cgroup.subtree_control  io.bfq.weight  memory.current  memory.max           memory.stat          pids.current
cgroup.max.depth    cgroup.threads          io.latency     memory.events   memory.min           memory.swap.current  pids.events
```
After setting DefaultCPUAccounting=yes, cpu should be enabled for cgroups. The cgroup.controllers file should show cpu along with io, memory and pids. Also, cpu.max file should not be missing inside the cgroup directory. Setting DefaultIOAccounting=yes worked well as you can see from the above output. The controller file shows io and the cgroup has io.max file.

### Steps to reproduce the problem

Add DefaultCPUAccounting=yes in /etc/systemd/system.conf.
Create cgroup named aa using mkdir /sys/fs/cgroup/aa.
Check if cpu is enabled by executing cat /sys/fs/cgroup/aa/cgroup.controllers.
Executing ls /sys/fs/cgroup/aa will show 2 cpu files but cpu.max file will be missing.

**Comment by Werkov** [comment]
CPU accounting on the unified hierarchy is part of the cgroup core, cpu(acct) controller isn't necessary for CPU accounting.
As shown in your listing `cpu.stat` file is present in the `aa` cgroup. (`CPUAccounting=yes` is almost virtually nop on the unified hiearchy.)

If you want to modify limits, use `CPUQuota=` (generally systemd directives) on units or delegate the given controller `Delegate=cpu` so that you can build and configure cgroups in a nested hiearchy below the unit.

I hope that clarifies and justifies closing this.
