### ISSUE TITLE
Support querying ${IMAGE_ID}.SHA256SUMS with systemd-sysupdate

### ISSUE THREAD

**Issue by mcassaniti** [systemd/systemd#27537]
### Is your feature request related to a problem? Please describe

Currently when `systemd-sysupdate` queries a URL for the files it should update with, the list of files is pulled from `Path=` + `SHA256SUMS`. It would be nice to also query `PATH=` + `$IMAGE_ID` + `.SHA256SUMS`.

For example, if in  /etc/os-release we have `IMAGE_ID=YALD-workstation` and if one of the sysupdate.d files contains `Path=https://cdn.yald.io/images/`, the following two URLs would be tried in order:

  1. https://cdn.yald.io/images/YALD-workstation.SHA256SUMS
  2. https://cdn.yald.io/images/SHA256SUMS

These URLs are fictitious but that shouldn't matter.

### The systemd version you checked that didn't have the feature you are asking for

main

**Comment by pothos** [comment]
The idea of a global file is that it may contain different parts, e.g., the kernel and the partition separately, and the update config pick the one it uses with `MatchPattern=` to write the kernel to the EFI partition and the OS partition to the wanted slot. It can even be that more files are needed, e.g., an initrd extension that is also put to the EFI partition or something like that. Instead of having multiple SUMS files a unified file is enough.

That said, I don't like fallback logic because it makes things unpredictable.

**Comment by mcassaniti** [comment]
@DaanDeMeyer can you comment on this one?

**Comment by mcassaniti** [comment]
@DaanDeMeyer Any updates for this one? If not I'm closing it out.

**Comment by DaanDeMeyer** [comment]
> @DaanDeMeyer Any updates for this one? If not I'm closing it out.

Why close it? It's a valid request. We just haven't gotten to it yet.

**Comment by septatrix** [comment]
What prevents you from using the current way or simply appending the image id to the url as a subdirectory?

**Comment by mcassaniti** [comment]
The issue is how mkosi is generating the name for the file checksum. By default it is now called ${IMAGE_ID}.SHA256SUMS which does make sense for the tool when you consider one invocation can generate multiple named images (i.e.: multiple IMAGE_ID values).

The tools mkosi, systemd-repart and systemd-sysupdate are supposed to somewhat work together with each other. Sometimes there's a design change in one, and here we are compensating for that design change.

**Comment by NekkoDroid** [comment]
Part of the problem for just looking at a `${IMAGE_ID}.SHA256SUMS` file is that to my understanding sysupdate uses the contents of the `SHA256SUMS` to figure out which version it can even update to. It needs *some* file that somehow lists all the available versions, which currently is that `SHA256SUMS` file.

**Comment by septatrix** [comment]
> The issue is how mkosi is generating the name for the file checksum. By default it is now called ${IMAGE_ID}.SHA256SUMS which does make sense for the tool when you consider one invocation can generate multiple named images (i.e.: multiple IMAGE_ID values).

I never noticed that change in mkosi as I have switched to manually generating that file since a while ago. I need both the compressed and uncompressed version of partitions, and also do not need the initrd etc to be part of the SHA256SUMS file so I just do it manually. Also not quite sure why mkosi even does it that way. Looking at the git history I see that you changed it at one point to simply output to SHA256SUMS but that commit got reverted later on.

In general it should be fine to put the hashes of all artifacts in a single file as they have different names unless you force their output names to have duplicates (which would already cause problems as you would have filename conflicts in the output directory then). When updating the clients would also automatically select the correct file as long as one defines a reasonable `MatchPattern=` is provided.

> The tools mkosi, systemd-repart and systemd-sysupdate are supposed to somewhat work together with each other. Sometimes there's a design change in one, and here we are compensating for that design change.

While that is true they do not necessarily provide perfect defaults (e.g. `UnifiedKernelImageFormat=` should usually be adjusted when using sysupdate). And unless you build the images on the same host which later serves the artifacts you have to create a small script to call something like `curl` or `aws s3` anyhow. Adjusting the filename, putting it in a subdirectory, or merging them all into one file should only be 1-2 lines extra.

**Comment by mcassaniti** [comment]
@NekkoDroid I'm only suggesting having the image ID be part of the checksum file lookup. The file would still contain file name patterns that have versions in them.

@septatrix You're right that a bit of work but not too much is required to make a set of mkosi generated artifacts available to machines. I too have generated my own checksums instead of using what mkosi generates.

@DaanDeMeyer Should we expect users to take what mkosi generates and rework the output (renaming the checksum file and putting files in sub-directories) for use with systemd-sysupdate? If so then this issue can get closed. I personally wasn't keen on it to begin with.

For the record, https://github.com/systemd/mkosi/pull/1538 is the PR that introduced this change, and [here](https://github.com/systemd/mkosi/pull/1538#issuecomment-1535923549) is the actual request in the PR comments.

**Comment by NekkoDroid** [comment]
> @NekkoDroid I'm only suggesting having the image ID be part of the checksum file lookup. The file would still contain file name patterns that have versions in them.

I did understand that, but if you use version with `mkosi`, it is going to include the version in the name of the sha file (`<IMAGE_ID>_<IMAGE_VERSION>.SHA256SUMS`), so just looking for the image version as well isn't going to cut it to make them work well together.

**Comment by mcassaniti** [comment]
I really think @NekkoDroid is right and this should be closed. If this truly is ongoing then please open a separate issue.
