### ISSUE TITLE
Confidential computing: revise trusting smbios and other hypervisor-driven payloads

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#27604]
In the confidential computing case the hypervisor is untrusted, so we need to establish a way to detect that case, and stop trusting smbios oem strings and unsigned payloads in the ESP by default.

https://github.com/systemd/systemd/pull/27358#issuecomment-1542129454
https://github.com/systemd/systemd/pull/27358#issuecomment-1542144948
https://github.com/systemd/systemd/pull/27358#issuecomment-1542223091

A suggestion on how to do so is to check MSRs, see "15.34.10 SEV_STATUS MSR" in https://www.amd.com/system/files/TechDocs/24593.pdf

In terms of what needs changing, smbios kernel command line extensions, as they are passed directory by the hypervisor, and unsigned extensions/credentials in the ESP are at the top of the list, as the ESP is not encrypted and the hypervisor can drop payloads there, and they are used before ExitBootServices.

For the userspace stuff (eg: credentials), perhaps we could make them disabled-by-default, but allow opt-in? Userspace code and configuration is signed or encrypted, and thus should be fine to trust to make that decision (with a you-keep-the-pieces warning).

**Comment by berrange** [comment]
> A suggestion on how to do so is to check MSRs, see "15.34.10 SEV_STATUS MSR" in https://www.amd.com/system/files/TechDocs/24593.pdf

It wasn't quite this simple, because Azure runs guests with a hardware compatibility layer which means they aren't aware that they're under SNP and this HCL blocks the key CPUID leaf.

As a reference, I've written a GPLv2+ tool to detect confidential virtualization:

http://git.annexia.org/?p=virt-what.git;a=blob;f=virt-what-cvm.c;h=407efb49269f49d9c03cc573a4af674775777e32;hb=HEAD

For KVM with SEV/SEV-ES/SEV-SNP, a combination of CPUID and MSR checks detect correctly

For Azure with SEV-SNP, we have to probe a TPM NV index data blob

For TDX (whether Azure or KVM) checking the guest CPUID is sufficient

Also bear in mind the security im0plications of taking actions (or not) based on the checks - see 'IMPORTANT NOTE'

  http://git.annexia.org/?p=virt-what.git;a=blob;f=virt-what-cvm.pod;h=12cfc6a96d434d2d95a899f23c0b40396632e889;hb=HEAD

I wonder if there should be a 'ConditionConfidentialVM', to complement 'ConditionVirtualization'

**Comment by poettering** [comment]
Here's a bigger problem btw: the SystemOptions efi var. which frankly we should cnsider removing altogether.

**Comment by berrange** [comment]
> Here's a bigger problem btw: the SystemdOptions efi var. which frankly we should cnsider removing altogether.

IIUC, the systemd code reports EPERM if this EFI variable is set and  SecureBoot is enabled. This is likely sufficient for confidential VMs, because SecureBoot=on is a pre-requisite for every confidential VM deployment.

**Comment by bluca** [comment]
@berrange would you be able to send a PR to do this? We are a bit short on time, and need to get the release out of the door

**Comment by berrange** [comment]
> @berrange would you be able to send a PR to do this? We are a bit short on time, and need to get the release out of the door

I'm trying to spend a bit of time to wire up checks / conditions for confidential virtualization

**Comment by bluca** [comment]
ok, we might not hold RC1 for this, but it should be fine to merge later

**Comment by poettering** [comment]
when this code exists, we should probably hook it up via `ConditionSecurity=cvm`

**Comment by berrange** [comment]
> when this code exists, we should probably hook it up as `ConditionSecurity=cvm` too

Work in progress code to detect confidential VMs is here:

  https://github.com/systemd/systemd/commit/5dc7f49275fad095c4ad06c599088989a76592d3

I had tried a straight clone of `ConditionVirtualization`/`systemd-detect-virt`, as `ConditionConfidentialVirtualization`/`systemd-detect-confidential-virt` in some further patches:

  https://github.com/systemd/systemd/compare/main...berrange:systemd:cond-cvm

I'm not really wedded to that idea, so if you think `ConditionSecurity=cvm` is a better bet, i follow take that approach instead. Depends if we think the fine grained per-technology reporting/condition is needd or not ?

Many people don't tend to consider `sev`/`sev-es` to be credible as confidential VM technologies due to a number of design limitations and flaws. They're obsoleted since Zen 3 architecture added `sev-snp` anyway, so the earlier generations won't have much long term future regardless.

**Comment by bluca** [comment]
I don't think we need to go as far as per-cpu-technology for this, but provide a decent heuristic confidential computing yes/no. Also no need for a new command line tool I think, a new switch for systemd-detect-virt should be enough.

**Comment by bluca** [comment]
rc-blocking part is merged, but reopening as we need more work for 254

**Comment by bluca** [comment]
@berrange thanks for taking care of those issues - what's left to do? Right now we will still for example boot type 1 configs, where the configuration is plain text on the ESP, should we forbid that too? Anything else that you can think of?

**Comment by berrange** [comment]
> @berrange thanks for taking care of those issues - what's left to do? Right now we will still for example boot type 1 configs, where the configuration is plain text on the ESP, should we forbid that too? Anything else that you can think of?

The main issue with type 1 configs is that while the kernel binary will be verified for SecureBoot, the corresponding initrd, device-tree, cmdline blobs are non-verified. Secondarily since the ESP config files aren't verified, even if the binary bits were verified, the config file could be change to boot a different combination of kernel+initrd than the intended one.

In terms of mitigation, even if sd-boot stopped loading type 1 configs in a CVM, a malicious user could swap out sd-boot for grub which the vendor is highly likely to have signed previously, and get the same end result. The only way to address this is to be very specific about sealing data to a broad set of TPM PCRs, to lock-in expected measurements of every piece, which comes with the big burden of re-sealing frequently.

On the RHEL/Fedora side we've moved to the view point that we have to consider all existing (non-UKI) vmlinuz binaries as untrusted. To move forward means a clean break with the past by signing UKI binaries with a different sub-key than the non-UKI binaries. This new sub-key must be *exclusively* used for UKIs, and probably each distinct "flavour" of UKIs for different products, ought to have a different signing key. This makes it practical merely seal to PCR 7 thus locking in the choice of signing keys, and thus re-sealing is a rare thing (mostly only if SBAT or DBX updates). 

I think this general problem is the same for both confidential VMs, and non-confidential VMs wanting "Trusted Boot", so perhaps doesn't make sense to limit 'type 1' config usage under CVMs as its only a partial solution.

**Comment by mythi** [comment]
> @berrange thanks for taking care of those issues - what's left to do?

@bluca just an observation on what might be left: #28301 seems to skip the SMBIOS values but does not provide an alternative way to pass them (e.g. via UKI). I'm testing some Intel TDX stuff using systemd `mkosi qemu` (by setting some local `Qemu*` configs) and that flow fails. I guess that would belong to`mkosi` side though.

**Comment by DaanDeMeyer** [comment]
@mythi You can pass them via UKI, that's what the .cmdline section is for. Just change `KernelCommandLineExtra=` to `KernelCommandLine=` in the mkosi config and they'll be included in the UKI instead of smbios.

**Comment by mythi** [comment]
@DaanDeMeyer thanks! that was an easy change. It does not seem to cover *all* of the cmdline parts (e.g., `console=`) seems missing but with that added manually I'm able to boot at least.

**Comment by Vogtinator** [comment]
> > Here's a bigger problem btw: the SystemdOptions efi var. which frankly we should cnsider removing altogether.
> 
> IIUC, the systemd code reports EPERM if this EFI variable is set and SecureBoot is enabled. This is likely sufficient for confidential VMs, because SecureBoot=on is a pre-requisite for every confidential VM deployment.

This absolutely must not be relied upon. This needs to be covered by measured boot just as well.
