### ISSUE TITLE
Could systemd-cryptenroll support an "unattended update" on an existing LUKS slot?

### ISSUE THREAD

**Issue by flixman** [systemd/systemd#27828]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

Maybe this is something already supported by systemd-cryptenroll, but is not clear in the documentation. When creating a LUKS slot tied to the TPM state, via ```systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+1+7+9 <device>``` introduces a challenge: whenever the kernel / initramfs get updated one needs to boot with a rescue password and then enroll the new PCR state, by executing ```systemd-cryptenroll --wipe-slot=tpm2 --tpm2-device=auto --tpm2-pcrs=0+1+7+9 <device>```. In this case, you are expected to introduce the rescue password again (and these passwords tend to be long and expected to be used in case of a real rescue operation).

### Describe the solution you'd like

It would be nice if there was an option ```systemd-cryptenroll --update --tpm2-device=auto --tpm2-pcrs=0+1+7+9 <device>``` that would generate a new the LUKS key using the given PCRs and wipe the previous one that used the same registers, without having to introduce the rescue key.

### Describe alternatives you've considered

I do not know if, after doing the current boot decryption, something else is added to the PCRs. If not, this means that the TPM can still be used to retrieve the "old" key, I guess? If so, such key could be stored temporarily on the ESP so that at the next boot could be detected by sd-crypt, unlock the volume, enroll the new PCR state, wipe the old key and remove the temporary file?

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by poettering** [comment]
there's a TODO list item for this, but to add it to cryptsetup, i.e. the idea was that when unlokcing a device at boot doesn't work because PCRs are not matching we'll ask for the recovery key and immediately replace the bad tpm slot with an updated version. but noone hacked that up yet. patches welcome.

**Comment by flixman** [comment]
@poettering: Is there any way/plans to integrate a USB key on this workflow? After setting up LUKS with the usual recommendation is to generate a text based recovery key, but is usually tedious to type back (long, random... properly generated, I mean). Having a file on a USB drive that gets used if present would simplify this.

**Comment by Winterhuman** [comment]
@flixman Here: https://github.com/systemd/systemd/blob/main/TODO

**Comment by flixman** [comment]
@Winterhuman lol. Really? Thank you and sorry for your time then, I did not think in the most obvious possibility, I guess :-D

**Comment by AdrianVovk** [comment]
> there's a TODO list item for this, but to add it to cryptsetup, i.e. the idea was that when unlokcing a device at boot doesn't work because PCRs are not matching we'll ask for the recovery key and immediately replace the bad tpm slot with an updated version. but noone hacked that up yet. patches welcome.

Are you envisioning Plymouth's existing password entry screen, or would Plymouth have a new mode (kinda like the Bitlocker recovery screen). An alternative would be to spin up a special target (`tpm2-recovery.target`) to let the OS present some UI and then the OS can re-enroll the key itself if it so chooses

**Comment by poettering** [comment]
So I think pcrlock is the way to go for things like this, i.e. #28891 which got merged recently.

It allows enrolling a disk against a policy stored in an NV index, and then allows to update that NV index.

**Comment by sylveon** [comment]
Pardon the necro, but this is relevant to my problem. My current distro doesn't ship systemd-pcrlock, and it appears to still be experimental anyways. It also doesn't quite implement UKIs yet (UKIs on Fedora Atomic is a WIP), I use `SYSTEMD_FORCE_MEASUREMENT` to use `tpm-measure-pcr`, so I'm not sure pcrlock would work yet.

I have a two drive setup, where unlocking one drive depends on PCR15 being empty and unlocking the second depends on PCR15 being the value measured from unlocking the first (this should reasonably defend against evil OS attacks, as once the bad drive is unlocked, it would set PCR 15 and prevent extracting the key).

Anyways, since Fedora Atomic have very frequent updates, and my binding set includes kernel cmdline + initramfs, I have to use the rescue password to boot and then manually re-enroll the PCR quite frequently, so I made a little script until pcrlock works for me.

```sh
#!/bin/sh
set -e

SYSTEM_DRIVE=/dev/disk/by-uuid/855236c4-159d-4d01-801e-5da22a3c14fc
DATA_DRIVE=/dev/disk/by-uuid/43095f3b-76ce-4f0e-9bda-ae6976c241b2

# Unenroll previous protector
systemd-cryptenroll --wipe-slot=tpm2 "$SYSTEM_DRIVE"
systemd-cryptenroll --wipe-slot=tpm2 "$DATA_DRIVE"

# Read password
IFS= read -r -s -p "Password: " PASSWORD
echo

# Enroll new protector
systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=4+7+8+9+15:sha256=0000000000000000000000000000000000000000000000000000000000000000 "$SYSTEM_DRIVE" <<<"$PASSWORD"
systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=4+7+8+9+15:sha256=6ccda659ed4f9ca4cc5f4231c81db7a4474db69c7301e0136b767116ee9d15ba "$DATA_DRIVE" <<<"$PASSWORD"
```

Unfortunately it seems I can't feed the password via stdin, as I'd rather not enter it twice. The script hangs like this:
```
Wiped slot 1.
Wiped slot 1.
Password: 

Broadcast message from root@Daring-Duck (Mon 2026-06-22 10:38:42 EDT):

Password entry required for 'Please enter current passphrase for disk /dev/disk/by-uuid/855236c4-159d-4d01-801e-5da22a3c14fc:' (PID 15783).
Please enter password with the systemd-tty-ask-password-agent tool.


Broadcast message from root@Daring-Duck (Mon 2026-06-22 10:38:42 EDT):

Password entry required for 'Please enter current passphrase for disk /dev/disk/by-uuid/855236c4-159d-4d01-801e-5da22a3c14fc:' (PID 15783).
Please enter password with the systemd-tty-ask-password-agent tool.
```

Is there a way to feed the password from stdin to `systemd-cryptenroll`, or otherwise avoid entering the password twice (consider it is the same for both drives)?
