### ISSUE TITLE
Testsuite fails on beaglebone_balck

### ISSUE THREAD

**Issue by Sangeetha-E** [systemd/systemd#27850]
Hi,

While running the built-in tests, the following tests were failed.

```
FAIL: test-user-util
FAIL: test-execute
FAIL: test-netlink
SKIP: test-bpf-lsm
```

Kindly give me suggestions about this failures.

Here I've attached the full test logs. 
[testlogs.txt](https://github.com/systemd/systemd/files/11600320/testlogs.txt)

systemd: 253
Linux kernel: 5.10.100

Thank you.

**Comment by poettering** [comment]
Seems your group 5 is not tty or vice versa. Which indicates a bad build that doesn't match your local system. 

the tty group is essential for us, and we need to know the numeric id for it at build time, since it's included in the devpts mount options which we need to establish. 

See `tty-gid` meson build time option.

Anyway, this is a build environment problem, please contact your distro for help

**Comment by Sangeetha-E** [comment]
Thank you for response.

All the above issues are due to `tty` group?
