### ISSUE TITLE
Add [Timer] section to .service files?

### ISSUE THREAD

**Issue by danielkrajnik** [systemd/systemd#27899]
### Component

systemd

### Describe the solution you'd like

I'm wondering if it would make sense to add [Timer] section to .service files instead of having to create a separate .timer file each time. For simpler scripts I think that it would be easier to maintain? 

There is a hack suggested here, but it has downsides (too much logging): https://unix.stackexchange.com/questions/198444/run-script-every-30-min-with-systemd 

### The systemd version you checked that didn't have the feature you are asking for

253.4-1-arch

**Comment by poettering** [comment]
This has been proposed before. But no, let's not do that.

We need the ability to schedule when timers are turned on the same way as the services that shall be activated by them. (i.e. we want to turn on timers only at a very specific milestone at boot, not already in the beginning, and only under very specific conditions, which separate units allow us to configure nicely, because service and timer unit can have different sets of ordering deps). 

Moreover, we provide functionality such as "systemctl list-timers" or "journalctl -U foobar.timer" that are all modelled around the fact that timers are units like any others. breaking this up is bad, not good. Also, we allow multiple timers per unit, i.e. not 1:1 relationships. and that wouldnt work if the two unit types are not properly distinguished.

Also, redundant interfaces really suck. Two ways to do the same are not great. Might be OK in some cases, but the bar is really high, and I doubt this comes even close.

hence, sorry, i am still not convinced.

**Comment by danielkrajnik** [comment]
No worries, thanks for explaining it. I was about to suggest having this as a redundant interface, but I see that you thought about it already as well.
