### ISSUE TITLE
Softreboot: automatically update /run/host/ pointers to new rootfs

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#28023]
Softreboot allows to configure services that survive the reboot, but they might have references to the old rootfs. For example all portable services automatically gain a reference to the host's os-release. This needs to be updated to reference the new rootfs on softreboot.

**Comment by poettering** [comment]
four strategies:

1. just copy the file instead of bind mounting it. would mean the file reflects the state of the original host, not of the current host OS image. I think this might actually be OK. (would probably mean adding a CopyFile= setting to service files, which sounds generally useful)
2. provide a knob to simply turn this concept off, which we suggest people use if they don't want the original root fs tree pinned.
3. figure out a way to update where this points via mount propagation. would probably mean making the os-release file a symlink into some dir in /run/host where we enable mount propagation for. Messy as fuck. but certainly doable.
4. go through all running services and enter their namespace and fix it manually. super messy as fuck.

i hate 3 and 4 more than 1 or 2.

**Comment by bluca** [comment]
I am pretty sure that to make this work and be useful we'll need a variation of 4: for every bind mount that we do, if the source is on the old rootfs, swap them (using the new mount beneath feature probably)

**Comment by poettering** [comment]
why? this is nice meta info, not more. And is we see now it might not have been the greatest idea to use a static fs-based interface for it, if we now suddenly want it dynamic...

I don't really think option 4 can work in real-life, because mount namespace trees might become arbitrarily deep and we couldn't possible track down all descendents of the namespace we once created (becuase people forked off children they moved to new scope units or so).

I am not convinced at all that we should make the interface work, no matter what.

**Comment by bluca** [comment]
It's an interface that is supported and even documented, and there's even other container managers implementing it. It doesn't need to track anything complex, I'm not talking about arbitrary mounts, but exclusively BindPaths and BindReadOnlyPaths - we know what the source and dest are, because they are defined explicitly.

**Comment by poettering** [comment]
there's one more option:

5. copy /etc/os-release to /run/systemd/os-release, and use that as bind mount source. Then during softreboot replace contents of that inode. Sucks a bit because not atomic.

**Comment by bluca** [comment]
> > It's an interface that is supported and even documented, and there's even other container managers implementing it.
> 
> there is? which one?

flatpak

> > It doesn't need to track anything complex, I'm not talking about arbitrary mounts, but exclusively BindPaths and BindReadOnlyPaths - we know what the source and dest are, because they are defined explicitly.
> 
> still you don't get access to all namespaces that are descendend of the one we spawn, it's simply not realistic to do what you are trying to do. You could iterate through /proc/ for all pids you find there, but this is racy as fuck and bad anyway since mount namespaces might exist without any processes around in them.
> 
> I am sorry, but this simply doesn't work afaics. it's not as easy as you make it out to be.

There's no need to bother with any of that. If users take the things set up programmatically by systemd and do weird things with them, it won't work - though stuff, they'll have to deal with it. But in the vast, vast majority of cases it's just a normal bind mount that is configured declaratively and that's it, and that should be perfectly feasible to support.

**Comment by poettering** [comment]
> There's no need to bother with any of that. If users take the things set up programmatically by systemd and do weird things with them, it won't work - though stuff, they'll have to deal with it. But in the vast, vast majority of cases it's just a normal bind mount that is configured declaratively and that's it, and that should be perfectly feasible to support.

i don't see how without this being terribly ugly.

**Comment by bluca** [comment]
Foreach BindPath, if source is on rootfs, take FD to same source on new rootfs or /dev/null if not found, go in target namespace, mount beneath, lazy umount. Not the nicest, but also not a million miles away from the current dynamic mount_bind and mount_image we can already do from systemctl, no?

**Comment by bluca** [comment]
For now I'm implementing a copy of os-release into /run/host/os-release to solve the immediate problem of portable services getting an implicit bind mount from the host's os-release, pinning the filesystem. This way we can get a working solution for v254. But I think we should revise more broadly in the future.
