### ISSUE TITLE
systemd-resolved: Labels with trailing dots are treated as single-label names, requiring ResolveUnicastSingleLabel=yes even to resolve FQDNs with internal TLDs

### ISSUE THREAD

**Issue by beningodfrey4** [systemd/systemd#28054]
### systemd version the issue has been seen with

253

### Used distribution

Arch Linux

### Linux kernel version used

6.3.7-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

_systemd-resolved_ should treat TLDs with a trailing dot as FQDNs and handle it via unicast DNS. If not, even normal FQDN resolution fails if their TLDs have A records and are pointed to be other CNAMEs.

Unicast forwarding should at least be the behavior when CNAMEs redirect to TLDs with A records, let alone explicit queries of the form `resolvectl query mytld.`

Arguments for:
1. Technically, the trailing dot is a zero-length label for the root zone, making `mytld.` essentially 2 labels. ([RFC 1034 ](https://www.ietf.org/rfc/rfc1034.txt)Sec. 3.1)
2. The trailing dot should already imply that no search domain-appending shenanigans would take place, further reducing the rationale of not forwarding as usual.
3. Though not recommended by ICANN, there still are a handful of Internet TLDs with A records, for ex `ai.`.

### Unexpected behaviour you saw

When `ResolveUnicastSingleLabel=no` _systemd-resolved_  fails without even sending out the query

1. **CNAME redirecting to TLD on internal DNS:**
```
$ resolvectl example.mytld
example.mytld: resolve call failed: No appropriate name servers or networks for name found

$ dig example.mytld
; <<>> DiG 9.18.15 <<>> example.mytld
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41110
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;example.mytld.			IN	A

;; ANSWER SECTION:
example.mytld.		1614	IN	CNAME	mytld.
mytld.			1614	IN	A	1.2.3.4

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Thu Jun 15 20:27:12 EDT 2023
;; MSG SIZE  rcvd: 72
```

2. **Vanilla query to Internet DNS:**
```
$ resolvectl query ai.
ai.: resolve call failed: No appropriate name servers or networks for name found

$ dig ai.
; <<>> DiG 9.18.15 <<>> ai.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6063
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;ai.				IN	A

;; ANSWER SECTION:
ai.			3600	IN	A	209.59.119.34

;; Query time: 124 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Thu Jun 15 20:26:02 EDT 2023
;; MSG SIZE  rcvd: 47
```

Starts working as intended if `ResolveUnicastSingleLabel=yes` but that opens the floodgates for dotless domains entirely for all links on the host.

### Steps to reproduce the problem

Stock config of _systemd-resolved_ with no DNSSEC, no search or routing domains pointing to some internal DNS with 1 CNAME record pointing to `mytld.` and an A record for `mytld.`

`resolvectl query` will fail even though question is a proper FQDN, while `dig` works (see above).

```
$ resolvectl example.mytld
example.mytld: resolve call failed: No appropriate name servers or networks for name found
```

This issue was brought up after closure in #11391 and pretty poorly in #18409.

**Comment by poettering** [comment]
This is well documented. See here:

https://www.freedesktop.org/software/systemd/man/resolved.conf.html#ResolveUnicastSingleLabel=
https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Compatibility%20with%20the%20traditional%20glibc%20stub%20resolver

A trailing dot turns of search domain processing, it has nothing to do with how queries are routed. in resolved we generally don't round single-label names to the internet, since that is a security issue (as single-label names typically have a local context, see llmnr, and we shouldn't leak those onto the public internet). Yes, there are some tlds with A/AAAA RRs, but that's agaist IAB recommendations:

https://www.iab.org/documents/correspondence-reports-documents/2013-2/iab-statement-dotless-domains-considered-harmful/

if you insist on having these looked up on the internet, then set ResolveUnicastSingleLabel= to true. But generally we try to provide secure defaults.

the trailing do is also a client-side construct only. clients talking to the local port 53 stub to resolved for example cannot communicate the dot anyway.

This has been discussed amply before. Let's not reopen this please.
