### ISSUE TITLE
Timer restart immediately a service after it normally finished

### ISSUE THREAD

**Issue by leonleeann** [systemd/systemd#28203]
### systemd version the issue has been seen with

245.4-4ubuntu3.20

### Used distribution

Ubuntu 20.04

### Linux kernel version used

Linux shd 5.4.0-131-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

A timer should only start the service at the specified time points.
A oneshot service controled by a timer, should keep dead after it finished normally.

### Unexpected behaviour you saw

A oneshot service controled by a timer, is restarted immediately by the timer after it finished normally, while in the config file of the timer, the service should be started a time everyday.

### Steps to reproduce the problem

my-service.timer:
```
[Unit]
Description=Timer of My Service
[Timer]
OnBootSec=25s
OnCalendar=Mon-Fri *-*-* 08:00:00
[Install]
WantedBy=timers.target
```

my-service.service
```
[Unit]
Description=My Service
Requires=postgresql.service
After=postgresql.service
[Service]
Type=simple
ExecStart=/usr/local/bin/xxx
ExecReload=/bin/kill -HUP $MAINPID
User=leon
Group=leon
OOMScoreAdjust=-1000
TimeoutSec=0
LimitNICE=-10
Nice=-10
[Install]
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
I'm running a custom service in two Ubuntu Server, the one is Ubuntu-20.04.3 LTS, and the other is Ubuntu-20.04.5 LTS.

The version of systemd in both servers are all of  245 (245.4-4ubuntu3.20), i.e. installed by `apt install` from the official repository of Ubuntu.
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
