### ISSUE TITLE
vconsole locking regime is broken?

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#28721]
### systemd version the issue has been seen with

253

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

I think the locking regime vconsole-setup + the per-service TTY logic used for firstboot use is broken,since they lock different inodes. systemd-firstboot locks /dev/console, but vconsole-setup typically locks /dev/tty1, thus being entirely orthogonal.

https://github.com/systemd/systemd/pull/27867#pullrequestreview-1567161854

**Comment by keszybz** [comment]
> systemd-firstboot locks /dev/console

I'm looking at the code, and I don't see any explicit lock. Where exactly is this happening?

**Comment by keszybz** [comment]
> PID 1 does that because systemd-firstboot has StandardOutput=tty, no?

`systemd-firstboot.service` doesn't have `TTYVHangup=yes`, and the default is "no".

But maybe this doesn't matter, if we change the lock to /dev/console as proposed in https://github.com/systemd/systemd/pull/27867#discussion_r1287088013.

**Comment by oscarpax** [comment]
FWIW, I've been getting the following error msgs since 254.0, in addition to console font not loading, and more annoyingly on a desktop, the console resolution being wrong resulting to huge font in console. 

`Aug 10 10:56:47 archlinux systemd-vconsole-setup[270]: /usr/bin/setfont failed with exit status 71.`
`Aug 10 10:56:47 archlinux systemd-vconsole-setup[270]: /usr/bin/loadkeys failed with exit status 1.`
`Aug 10 10:56:47 archlinux systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.`
`Aug 10 10:56:47 archlinux systemd[1]: Failed to start Virtual Console Setup.`
`Aug 10 10:56:47 archlinux systemd-vconsole-setup[276]: /usr/bin/loadkeys failed with exit status 1.`
`Aug 10 10:56:47 archlinux systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.`
`Aug 10 10:56:47 archlinux systemd[1]: Failed to start Virtual Console Setup.`

My apologies if this a wrong place to gripe about this.

**Comment by mrc0mmand** [comment]
> FWIW, I've been getting the following error msgs since 254.0, in addition to console font not loading, and more annoyingly on a desktop, the console resolution being wrong resulting to huge font in console.
> 
> `Aug 10 10:56:47 archlinux systemd-vconsole-setup[270]: /usr/bin/setfont failed with exit status 71.` `Aug 10 10:56:47 archlinux systemd-vconsole-setup[270]: /usr/bin/loadkeys failed with exit status 1.` `Aug 10 10:56:47 archlinux systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.` `Aug 10 10:56:47 archlinux systemd[1]: Failed to start Virtual Console Setup.` `Aug 10 10:56:47 archlinux systemd-vconsole-setup[276]: /usr/bin/loadkeys failed with exit status 1.` `Aug 10 10:56:47 archlinux systemd[1]: systemd-vconsole-setup.service: Failed with result 'exit-code'.` `Aug 10 10:56:47 archlinux systemd[1]: Failed to start Virtual Console Setup.`
> 
> My apologies if this a wrong place to gripe about this.

Could you open a new issue about this? And if possible, please attach output of `localectl` and `cat /etc/vconsole.conf` to the report as well.
