### ISSUE TITLE
Core dumps are written to the disk despite the setting asking not to do so

### ISSUE THREAD

**Issue by birdie-github** [systemd/systemd#28740]
### systemd version the issue has been seen with

systemd-253.7-1.fc38.x86_64

### Used distribution

Fedora 38

### Linux kernel version used

Doesn't matter

### CPU architectures issue was seen on

x86_64

### Component

coredumpctl, systemd-coredump

### Expected behaviour you didn't see

No disk activity.

### Unexpected behaviour you saw

Core dumps are **actually saved** to `/var/lib/systemd/coredump/` and **then deleted**.

### Steps to reproduce the problem

```
cat /etc/systemd/coredump.conf.d/disable.conf
[Coredump]
Storage=none
```

1. Run `fatrace --timestamp --filter='WD<>' 2>&1 | grep /var/lib`
2. Make an app crash.
3. Observe core dumps being saved to `/var/lib/systemd/coredump/` and then deleted.

**Comment by poettering** [comment]
Yeah, if we shall log about them, we need to analyze them to extract a stack trace. for that we need to put them somewhere, hence we write them to an anonymous inode in that dir.

Storage= just controls whether we keep the coredump around as a file, or not. That's all, not whether we temporarily write it to the dir in order to analyze it.

There's currently no knob in coredump.conf to disable analysis, and thus suppressing any attempt to write the coredump to disk.

**Comment by poettering** [comment]
Ah, wait, there actually is, and that's even documented:

ProcessSizeMax=0

Hence closing.

**Comment by poettering** [comment]
I extended the docs a bit on this → #28760
