### ISSUE TITLE
os-release namespace propagation needs reworking

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#28794]
### systemd version the issue has been seen with

git main

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

https://github.com/systemd/systemd/pull/28445#pullrequestreview-1573433283

This needs to be reworked: it's broken, any consumer of the file will not see an atomic version of the os-release but likely something half-written.

Also, otherwise semantics are bad, the bind mount generation should be in portabled (ideally even in the profiles, not in portabled itself), but not be enabled in all services.

**Comment by bluca** [comment]
> This needs to be reworked: it's broken, any consumer of the file will not see an atomic version of the os-release but likely something half-written.

What do you mean, specifically? CI is working fine, real-life usage also says it's fine - CI specifically is testing a field appended at the end of the file, so if it was half-written it would fail?

> Also, otherwise semantics are bad, the bind mount generation should be in portabled (ideally even in the profiles, not in portabled itself), but not be enabled in all services.

I need this in RootImage=/RootDirectory= cases too. It's part of the container interface we documented a long time ago: https://systemd.io/CONTAINER_INTERFACE/#:~:text=The%20/run/host/os%2Drelease and the purpose is the same across all usages - being able to know what you are running on, when in a container-like environment (separate rootfs)

**Comment by poettering** [comment]
> What do you mean, specifically? CI is working fine, real-life usage also says it's fine - CI specifically is testing a field appended at the end of the file, so if it was half-written it would fail?

it's a race. the file is not atomically updated.

and btw, if the test case would shorten rathern then length the

> I need this in RootImage=/RootDirectory= cases too. It's part of the container interface we documented a long time ago: https://systemd.io/CONTAINER_INTERFACE/#:~:text=The%20/run/host/os%2Drelease and the purpose is the same across all usages - being able to know what you are running on, when in a container-like environment (separate rootfs)

Sure, then add the bind mount for those case.

But i am strictly against implying this in all sandboxing cases. that's just wrong.

**Comment by bluca** [comment]
> > > What do you mean, specifically? CI is working fine, real-life usage also says it's fine - CI specifically is testing a field appended at the end of the file, so if it was half-written it would fail?
> > 
> > 
> > it's a race. the file is not atomically updated. so if you read from it at the wrong time with a short buffer (let's say 256chars at a time) you might start with one version of the file, and then read the next 256 bytes of the other version of the file. and no way to notice.
> > it's a short race, but it's a race.
> > and btw, if the test case would shorten rathern then enlarge the file the fact that the os-release file is never truncated would trip off the CI case.
> 
> Ah I saw the other comment now - thanks for spotting that, I missed it. I always get mixed up with the flags for those helpers. I'll send a fix. I suspect in the general case it's unlikely that os-release would radically change in size - version going up or down or so, and that's why I haven't seen an issue. But better to fix it for sure.

Indeed changing the test to truncate it shows the problem --> https://github.com/systemd/systemd/pull/28799

**Comment by poettering** [comment]
> > 
> 
> it's a race. the file is not atomically updated. so if you read from it at the wrong time with a short buffer (let's say 256chars at a time) you might start with one version of the file, and then read the next 256 bytes of the other version of the file. and no way to notice.
> 
> it's a short race, but it's a race.

btw, it's probably even a race that will be triggered in real life where you don#t want it. i.e. you have some service that keeps running during soft-reboot. It gets some async notification (could be as simple as a TCP or AF_UNIX connection disconnecting to some other component of the OS that is being shutdown) about the soft reboot, and then goes to check what new version of the OS is now running under it. And this is now racy: it might read in the middle of the file being overwritten. i think in such a case it would be ok if it read the old or if it read the new file, but an half-old-half-new file is not acceptable.

**Comment by bluca** [comment]
> > > 
> > 
> > 
> > it's a race. the file is not atomically updated. so if you read from it at the wrong time with a short buffer (let's say 256chars at a time) you might start with one version of the file, and then read the next 256 bytes of the other version of the file. and no way to notice.
> > it's a short race, but it's a race.
> 
> btw, it's probably even a race that will be triggered in real life where you don#t want it. i.e. you have some service that keeps running during soft-reboot. It gets some async notification (could be as simple as a TCP or AF_UNIX connection disconnecting to some other component of the OS that is being shutdown) about the soft reboot, and then goes to check what new version of the OS is now running under it. And this is now racy: it might read in the middle of the file being overwritten. i think in such a case it would be ok if it read the old or if it read the new file, but an half-old-half-new file is not acceptable.

Yes I agree it's better to fix that too, will implement a solution for that as suggested, but will take some more time so I started with the simple stuff in https://github.com/systemd/systemd/pull/28799

**Comment by bluca** [comment]
> > Nobody is forced to use it though, it's just a file sitting there, available in a hierarchy that is owned by the service manager. If somebody wants to do something different, or ignore it, they absolutely can. But I am very much convinced this interface should be provided as the documentation says, because it costs nothing to do so, and it's a documented interface used in other places too - it is definitely not just a portable thing, for example Flatpak uses it too.
> > It is very nice to provide value with allowing `source /run/host/os-release || source /etc/os-release` to always work, and always do the right thing. Batteries included and all that.
> 
> it's fine to define batteries included for portabled and nspawn, i.e for the combination of pieces fitting together. but doing so for the individual parts is wrong, i.e. RootImage= and RootDIrectory= should not implicitly mean host os-release is leaked to payload

First of all, let's be clear with terminology: there's no 'leak', static OS vendor data is available in other more convoluted ways, and it was intended to make it available in a straightforward way by the specification, as a certain Poettering Lennart said once upon a time, you might know him :-) https://github.com/systemd/systemd/pull/15891#issuecomment-634781431

Secondly, we make available several things to services that are taken from internal implementation details as the source. For example, the notify socket, a bunch of environment variables, etc. You do not have to set those manually in services, because doing so would inevitably mean having to leak internal implementation details of systemd as stable interface.

This about it this way: I picked the path that made most sense to me to store the copy (the copy strategy was your idea too btw :-) ). You want me to change it to a different location - that is fine, and the only reason we can do that without breaking anything is _because_ the source did not leak as an interface that users have to explicitly mention in a BindPath, but it is a hidden, internal implementation detail. If I had gone with what you suggest here, `/run/systemd/propagate/os-release` would have been forever cemented as a public interface that we can never change. But because the source is actually an implementation detail, we can change it as we like, just like with the notify socket and a bunch of other things.

Hence overall, all things considered, the current approach (bar the location, which I will fix as you requested) seems to me to provide the best result. The cost of maintaining it is extremely low, it allows users to just rely on the right thing to always work (`source /run/host/os-release || source /usr/lib/os-release`), and we can change the internal implementation detail when and however we feel like, as only the final path is a public interface, its source is an implementation detail that doesn't leak into user-supplied configuration.

**Comment by bluca** [comment]
I forgot, there's another advantage: the old approach of `BindPaths=/etc/os-release:/run/host/os-release` means that, if base-files is updated with a new os-release file on the host, running services will always see the old, stale version of it, given the update creates a new file and removes the old one, but the bind mount is pinned to the old inode.

But now with this approach, if we want to, we can simply set a notify event in the manager, and update the copy when /usr/lib/os-release is updated. This should be trivial to do, and ensure that no stale version is shown even to running services.
