### ISSUE TITLE
Go to end is slow in journalctl pager

### ISSUE THREAD

**Issue by ZettaScript** [systemd/systemd#28845]
### Component

journalctl

### Is your feature request related to a problem? Please describe

When viewing a large log using the command `journalctl -u <service>`, hit the End key. It can take a while to complete.

Sometimes during the operation an intermediate page is displayed, so I guess it processes all the file instead of seeking the end directly.

### Describe the solution you'd like

This can be made faster, proof is the `-e` option which is fast. Less also has this optimization for the "go to end" key.

### The systemd version you checked that didn't have the feature you are asking for

247

**Comment by mrc0mmand** [comment]
> Sometimes during the operation an intermediate page is displayed, so I guess it processes all the file instead of seeking the end directly.

I mean yeah, that's how it works - `journalctl -u unit` will show you everything from the oldest entries to the newest ones, which can be slow if you have quite a lot of journals, as `less` has to wait for `journalctl` to process everything. If you're interested only in the latest entries you can use `-e/--pager-end`, which does exactly what you want without the performance penalty. I don't think there's much we can do here otherwise.

**Comment by ZettaScript** [comment]
Ok I did not get that journalctl spawns less, I thought it used its own pager.
