### ISSUE TITLE
Unable to login with /home marked as nofail

### ISSUE THREAD

**Issue by fuzzy7k** [systemd/systemd#28890]
### Component

other

### Is your feature request related to a problem? Please describe

I have a mobile phone with /home on an encrypted sdcard.
I am trying to make sure that the phone will boot into a usable state regardless of whether /home is mounted or not.
Reasons that it might not be mounted include some type of sdcard failure/corruption, or the user removing the card while powered off.

The underlying / has a /home populated with a default user as a fallback in case /home is not mounted.
I have nofail options in /etc/crypttab and /etc/fstab.
With nofail set, this should work, however I am unable to log in with the card removed.

In the journal, I see the following repeated over and over.
```
Aug 16 08:06:19 pureos systemd-logind[656]: New session 2 of user x.
Aug 16 08:06:19 pureos systemd[1]: Starting partprobe after cryptsetup...
Aug 16 08:06:19 pureos partprobe[1368]: Error: Could not stat device /dev/mapper/home - No such file or directory.
Aug 16 08:06:19 pureos systemd[1]: partprobe.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 08:06:19 pureos systemd[1]: partprobe.service: Failed with result 'exit-code'.
Aug 16 08:06:19 pureos systemd[1]: Failed to start partprobe after cryptsetup.
Aug 16 08:06:19 pureos systemd[1]: Dependency failed for /home.
Aug 16 08:06:19 pureos systemd[1]: Dependency failed for Session 2 of user x.
Aug 16 08:06:19 pureos systemd[1]: session-2.scope: Job session-2.scope/start failed with result 'dependency'.
Aug 16 08:06:19 pureos systemd[1]: home.mount: Job home.mount/start failed with result 'dependency'.
Aug 16 08:06:19 pureos systemd[1]: Unnecessary job for /dev/mapper/home was removed.
Aug 16 08:06:19 pureos systemd[1363]: pam_systemd(login:session): Failed to create session: Job 2550 for unit 'session-2.scope' failed wit>
Aug 16 08:06:19 pureos systemd[1]: Finished User Runtime Directory /run/user/1000.
Aug 16 08:06:19 pureos systemd[1]: Starting User Manager for UID 1000...
Aug 16 08:06:19 pureos systemd-logind[656]: Session 2 logged out. Waiting for processes to exit.
Aug 16 08:06:19 pureos systemd-logind[656]: Removed session 2.
Aug 16 08:06:19 pureos systemd[1370]: pam_unix(systemd-user:session): session opened for user x(uid=1000) by (uid=0)
Aug 16 08:06:19 pureos phoc[1363]: [libseat] [libseat/backend/seatd.c:78] Could not connect to socket 
/run/seatd.sock: No such file or dir>
Aug 16 08:06:19 pureos phoc[1363]: [libseat] [libseat/backend/seatd.c:588] Built-in seatd instance requires root 
privileges
Aug 16 08:06:19 pureos phoc[1363]: [libseat] [libseat/libseat.c:73] No backend was able to open a seat
Aug 16 08:06:19 pureos phoc[1363]: [backend/session/session.c:84] Unable to create seat: Function not implemented
Aug 16 08:06:19 pureos phoc[1363]: [backend/session/session.c:249] Failed to load session backend
Aug 16 08:06:19 pureos phoc[1363]: [backend/backend.c:86] Failed to start a session
Aug 16 08:06:19 pureos phoc[1363]: [backend/backend.c:263] failed to start a session
Aug 16 08:06:19 pureos phoc[1363]: [backend/backend.c:311] failed to add backend 'drm'
Aug 16 08:06:19 pureos phoc[1363]: Failed to create server: Could not create backend
Aug 16 08:06:19 pureos systemd[1]: phosh.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 08:06:19 pureos systemd[1]: phosh.service: Failed with result 'exit-code'.
```

The problem appears to stem from a dependency link between systemd-user-sessions.service and home.mount, as each lists the other in Before/After clauses.

It seems that the nofail option was giving systemd the impression that home.mount was available, since it was not in a failed state, and therefore was a required dependency of systemd-user-sessions, even though it is not in 'Requires='.
If I don't add the nofail option, then the system will not boot.

### Describe the solution you'd like

The nofail option should not introduce other problems down the line. Maybe there should be a way for systemd to remember that a unit is not available.

### Describe alternatives you've considered

Maybe there is some .mount option that could be used to signal that this is not going to work, proceed without me.

I tried adding /etc/systemd/system/home.mount.d/override.conf:
```
[Unit]
ConditionPathExists=/dev/mapper/home
```
That one there does not wok.

I added /etc/systemd/system/systemd-user-sessions.service:
```
[Unit]
Description=Permit User Sessions
Documentation=man:systemd-user-sessions.service(8)
After=

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/lib/systemd/systemd-user-sessions start
ExecStop=/lib/systemd/systemd-user-sessions stop
```
That removes the Before/After deps that I was seeing when running systemctl show on home.mount and systemd-user-sessions. But mysteriously, it does not fix the problem. session.scope is still trying to pull in home.mount. 

I am able to log in by commenting out the /home mount from /etc/fstab:
`
#/dev/mapper/home /home         btrfs   noatime,nofail,compress=lzo,ssd_spread,x-systemd.requires=cryptsetup.target,x-systemd.mount-timeout=1s  0 0

### The systemd version you checked that didn't have the feature you are asking for

247

**Comment by fuzzy7k** [comment]
Sorry, but this should be marked as a bug. It was once possible, but no longer is. 
I initially sent an email to the mailing list because I was on an old release. I was also pretty sure that it was not fixed in a new release. The email was blocked because I was not subscribed. When I saw the notice that it was blocked I thought I had a working solution so resolved to making this feature request.  Unfortunatley, I do not.

I gather that the home directory is an implicit dependency for session-.scope, as I am unable to override it.

I should also point out that `systemctl --edit session-.scope` requested that I use `systemctl edit --force --full session-.scope`. Doing that created an /etc/systemd/system/session-.scope, which was not picked up systemctl daemon-reload. After moving the file into `/etc/systemd/system/session-.scope.d/override.conf` it was picked up. A minor paper cut.

I confirmed both the the failure of the nofail option and the `--edit .scope` quirk in systemd 252.12

**Comment by poettering** [comment]
"nofail" only controls the deps on your mount from `local-fs.target`. If "nofail" is used it will use Wants= without ordering, it it isn't used it will use Requires= with After= ordering.

But key here is that it only has an effect on `local-fs.target`, nothing else. What other units do is entirely orthogonal.

Generally the assumption is that /home/ must be around for users to log in, and thus we need to schedule things at boot and at shutdown so that /run/nologin exists exactly as long as this directory is not mounted.

It appears your desired logic wants to depart from that, which is fine, but in that case override the systemd-user-sessions.service, as you already did.

But of course, a user login session will still pull in the home dir of that user. Which is enforce programmatically in logind. But it's really the only thing that makes sense. Allowing the user to log in without their home dir is a very weird idea I'd argue. I cannot see how that would ever make sense?

if you want to hack something up like that, I'd suggest you write a script that early at boot makes the decision whether /home is available or not, and if not just synthesizes a "fake" mount onto /home. That will fulfill the dependencies and allow you to continue boot with all deps fulfilled. That fake mount could be a bind mount on itself, or a tmpfs or so. Up to you.

Note that whatever you are doing there, is neessarily racy: there's no point in time where on modern systems a device has to have popped up, hardware can take any time to initialize, in particular on USB (where possibly inetractivity can be required even for devices to show up). Hence making a decision between "home is there, will use it" and "home is not there, won't use it" cannot safely be made, your only choice is a time-out really.

But anyway. I don't really see anything to fix in systemd here. This discussion is material for systemd-devel, i.e. a support question, not a bug report.
