### ISSUE TITLE
Please provide a way to set timeout for device units.

### ISSUE THREAD

**Issue by kawing-chiu** [systemd/systemd#2891]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> arch

My situation: I've been using a linux usb stick across multiple machines. On one machine, there is a wireless card `wlp1s0`, and I enabled `wpa_supplicant@wlp1s0.service` so that when I use the stick on that machine, the wifi is automatically connected. The problem is that, when the system is used on other machines, `wlp1s0` is not present, so `sys-subsystem-net-devices-wlp1s0.device` is always timed out in as long as 1min 30s. So the `network.target` will not be reached within 1min 30s, even if other network interfaces are ready, which causes the system to boot up very slowly since many services, e.g. libvirtd, depends on `network.target`. Currently, I couldn't find a way in systemd to configure the timeout of a device unit. Maybe I'm missing something or this is a missing feature?

**Comment by arvidjaar** [comment]
It's not device timeout, but some other unit that requires this device waits for 90 seconds. You need to set timeout for this unit, not on device.

**Comment by kawing-chiu** [comment]
@arvidjaar However the log shows:

```
Mar 24 09:17:12 xbase_sd systemd[1]: sys-subsystem-net-devices-wlp1s0.device: Job sys-subsystem-net-devices-wlp1s0.device/start timed out.
Mar 24 09:17:12 xbase_sd systemd[1]: Timed out waiting for device sys-subsystem-net-devices-wlp1s0.device.
-- Subject: Unit sys-subsystem-net-devices-wlp1s0.device has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit sys-subsystem-net-devices-wlp1s0.device has failed.
--
-- The result is timeout.
```

From the log it seems that it is the device unit that times out?

Note that the goal I want to achieve is not
- ask `wpa_supplicant@wlp1s0` to always time out within a short time (like 5 secs)

but 
- if the device `wlp1s0` is not present within 5 sec, `sys-subsystem-net-devices-wlp1s0.device` and thus `wpa_supplicant@wlp1s0` should fail immediately so `network.target` would not be blocked up
- if the device `wlp1s0` is present, it is ok for `wpa_supplicant@wlp1s0` to time out after 1min 30s

**Comment by poettering** [comment]
It sounds as if you want to pull in wpa_supplicant from the .device unit, instead of pulling it in at boot unconditionally. Specifically, write a udev rule that uses SYSTEMD_WANTS= to pull in wpa_supplicant@xyz.service, see the systemd.device(5) man page.

Also, there's already JobTimeoutSec= to define such timeouts.

Either way, I see nothing to fix here, as this should be covered fine already. Please contact the systemd mailing list for further questions, as this issue tracker should be used for RFEs and bug reports only, and support requests should be redirected to the ML instead. Thanks.

**Comment by kawing-chiu** [comment]
@poettering Thank you very much for helping and sorry for the disturbance. However I still couldn't make it to work yet. I  added `/etc/udev/rules.d/20-wifi.rules`:

```
ACTION=="add", SUBSYSTEM=="net", KERNEL=="umx_wifi0", ENV{SYSTEMD_WANTS}+="wpa_supplicant@umx_wifi0.service"
```

but the service is not activated as expected. Am I missing something? The `umx_wifi0` device is created by a `link` unit in `/etc/systemd/network`.

**Comment by kawing-chiu** [comment]
@Liam-KO No, I didn't. I don't use systemd to manage my network anymore and instead going back to use networkmanager...

**Comment by anonymous683854643863** [comment]
@kawing-chiu @Liam-KO I decided to do some debugging, because I ran into the same issue and this unresolved thread was the only relevant thing that came up after a web search.

It turns out that the correct udev action to look for is **"move"** rather than "add"--because devices still get _initialised_ with the legacy names (eth0, etc.), and are then subsequently _renamed_ according to the "predictable" names (such as enp0s3, or your wlp1s0), which triggers a "move" event. If one were to look for events related to eth* devices, that's where the "add" would be found.

So, the udev rule posted above is one word away from being the solution.
`ACTION=="move", SUBSYSTEM=="net", KERNEL=="umx_wifi0", ENV{SYSTEMD_WANTS}+="wpa_supplicant@umx_wifi0.service"`

I hope this helps someone stumbling upon this in the future!
