### ISSUE TITLE
systemd-boot: Boot entries in reverse order

### ISSUE THREAD

**Issue by hunger** [systemd/systemd#28912]
### systemd version the issue has been seen with

254

### Used distribution

Arch Linux

### Linux kernel version used

6.4.11-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

I have several UKI-kernels installed in /efi/EFI/Linux. There is no configuration file whatsoever in /efi.

This is the output of `bootctl list`:

```
         type: Boot Loader Specification Type #2 (.efi)
        title: Cleanroom (20230815.1356) (default)
           id: arch_20230815.1356.efi
       source: /efi//EFI/Linux/arch_20230815.1356.efi
     sort-key: 20230815.1356
      version: 20230815.1356
        linux: /efi//EFI/Linux/arch_20230815.1356.efi
      options: i915.fastboot=1 intel_iommu=igfx_off mem_sleep_default=deep rd.luks.uuid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa rd.luks.opt>

         type: Boot Loader Specification Type #2 (.efi)
        title: Cleanroom (20230821.1859) (selected)
           id: arch_20230821.1859.efi
       source: /efi//EFI/Linux/arch_20230821.1859.efi
     sort-key: 20230821.1859
      version: 20230821.1859
        linux: /efi//EFI/Linux/arch_20230821.1859.efi
      options: i915.fastboot=1 intel_iommu=igfx_off mem_sleep_default=deep rd.luks.uuid=bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb rd.luks.opt>

         type: Automatic
        title: Reboot Into Firmware Interface
           id: auto-reboot-to-firmware-setup
       source: /sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
```

I expect the latest kernel (20230821.1859) to boot.

### Unexpected behaviour you saw

The oldest kernel boots (20230815.1356).

### Steps to reproduce the problem

Install several UKI-kernels, check boot order in bootctl.

**Comment by medhefgo** [comment]
Try `bootctl set-default ''`.

**Comment by medhefgo** [comment]
The issue is that the generated sort-key for the UKIs is too specific, forcing a specific sort order. The sort key is not supposed to be *that* unique as to allow ordering by (kernel) version.

 Please provide the output of `objcopy --dump-section .osrel=/dev/stdout /efi/EFI/Linux/arch_20230815.1356.efi`

**Comment by medhefgo** [comment]
We use `IMAGE_ID` or `ID` when picking a sort-key. And reading `man os-release` I would argue that you're using the fields not as intended (but I could be wrong). As I see it, `IMAGE_ID` should not contain version identification (except for things like `debian-11` vs `debian-12`).

> To summarize: if the image updates are built and shipped as comprehensive units, IMAGE_ID+IMAGE_VERSION is the best fit. Otherwise, if updates eventually completely replace previously installed contents, as in a typical binary distribution, VERSION_ID should be used to identify major releases of the operating system. BUILD_ID may be used instead or in addition to VERSION_ID when the original system image version is important.

@poettering Your thoughts.

**Comment by medhefgo** [comment]
Well, the sorting has become complicated because a certain someone prefers silly sorting based on file names, so that people can do silly things like `00-Zubuntu first.conf`. And that basically forces them to be sorted in reverse order so that if they have (kernel) versions in them the expected order happens (`zubuntu.conf`<`debian_4.6.conf`<`debian_4.5.conf`). In fact, this is the only way to sort these, as other things are not looked at.

Now to make this really funny, setting a sort-key will change the algorithm to this: `sort-key<machine-id<version<filename` (in ascending order, the version descending). UKIs have a sort-key picked based on `IMAGE_ID<ID` and version based on `IMAGE_VERSION<VERSION<VERSION_ID<BUILD_ID`.

(If it were up to me, we'd use the sort-key algorithm for `.conf` entries too to keep things consistent).

Note that the kernel uname has no bearing in all of this if it's not put in any of the picked version fields of the UKI. So you have to do that, if that's what you require.

So your suggested new osrel should do the trick, though I think `IMAGE_ID=clrm-arch` or so would be more appropriate, no?
