### ISSUE TITLE
homectl update with --uid updates .identity but doesn't take effect

### ISSUE THREAD

**Issue by niklas88** [systemd/systemd#28982]
### systemd version the issue has been seen with

254

### Used distribution

Arch Linux

### Linux kernel version used

6.4.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

homectl

### Expected behaviour you didn't see

I'm using `systemd-homedir` with btrfs subvolumes and previously used homectl create with no explicit UID but now needed to match my UID accross other systems (for my home server/NAS NFSv4 authenticated via wireguard). 
I tried `homectl update niks --uid 1000` with the user deactivated.  

### Unexpected behaviour you saw

The `homectl update niks --uid 1000` gave me an invalid value error. though only when done as logged in root!? I then checked `/home/niks.homedir/.identity` and that contained UID 1000 however `homectl` still showed the large default UID both when active and inactive.
To make sure there is no conflict somewhere else I checked `/etc/passwd` and created a new user/homedir with UID 1000 without issue. I then tried with a large UID in the typical systemd-homed range but got the same behavior.

*Manual fixup*:
I  succeeded in manually "fixing" things up by taking a btrfs snapshot of my homedir, removing the old user, recreating with UID 1000, removing the new empty homedir while saving the `.identity` and creating a snapshot of the old homedir in its place with the new `.identity` copied in. This all worked so again no fundamental issue with having a user
with that name and UID combination.

### Steps to reproduce the problem

See additional program output for exact steps note creating with `--uid 1001` does work.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
niks@io ~ % sudo homectl create tester
🔐 Please enter new password for user tester: ******
🔐 Please enter new password for user tester (repeat): ******
niks@io ~ % sudo homectl
NAME   UID   GID   STATE    REALNAME        HOME         SHELL
niks   1000  1000  active   Niklas Schnelle /home/niks   /usr/bin/zsh
tester 60253 60253 inactive tester          /home/tester /bin/bash

2 home areas listed.
niks@io ~ % sudo homectl update tester --uid 1001
🔐 Please enter password for user tester: ******
niks@io ~ % sudo homectl
NAME   UID   GID   STATE    REALNAME        HOME         SHELL
niks   1000  1000  active   Niklas Schnelle /home/niks   /usr/bin/zsh
tester 60253 60253 inactive tester          /home/tester /bin/bash

2 home areas listed.
niks@io ~ % sudo cat /home/tester.homedir/.identity
{
        "disposition" : "regular",
        "lastChangeUSec" : 1693129942930444,
        "lastPasswordChangeUSec" : 1693129900717382,
        "privileged" : {
                "hashedPassword" : [
                        "XXcensoredXX"
                ]
        },
        "signature" : [
                {
                        "data" : "JpgGblT5U2FBMqyYfh6XKR5XCmPPanLLROEQ2vXowZdoiAO+ud4qjf431RopIfjOH2z3pNwH/ogZLZOozp8LDw==",
                        "key" : "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEACgPM3K+7y/fYkk+KVbH6wJnZ6uQCgN+wmjO9CvmbEfc=\n-----END PUBLIC KEY-----\n"
                }
        ],
        "uid" : 1001,
        "userName" : "tester"
}
```

**Comment by poettering** [comment]
"--uid=" controls only the *preferred* UID, as per fcos. It's used only if no UID is used locally yet, and the UID is free. Changing that on an account you already have been using locally has no immediatey effect.

The UID assigned to an account locally is part of the account's local "binding". That binding is stored in `/var/lib/systemd/home/*.identity`, and dictates how locally the account and resources belong together. 

homed creates bindings automatically on first use, to ensure that all resources assigned to the user locally match up. You can delete a binding (simply by deleting the mentioned file for you account), the binding will then be recreated on next login, and the UID will be chosen. However this might not be sufficient to make the UID you configured via --uid= take effect: if you already have a populated $HOME and it is owned by a valid UID already we'll prefer using that if otherwise not use, to avoid rechowning. 

Hence, if you actually want to change the local UID assignment of your account you could removing the binding, and chown the files in your home manually, and then login, in which case logind should create a binding matching your intentions.

We might consider adding "homectl unbind" some day, to remove the binding via a command.

And on kernels with overlayfs the chowning is not necessary. So the issue goes away eventually.

**Comment by niklas88** [comment]
It seems that on my system with a btrfs subvolume home the mount of the homedir uses Christian Brauner's idmapped mounts as part of the btrfs subsystem mount
```
# mount
…
/dev/nvme1n1p2 on /home/niks type btrfs (rw,nosuid,nodev,relatime,idmapped,compress=zstd:3,ssd,discard=async,space_cache=v2,subvolid=299,subvol=/arch_root/home/niks.homedir)
```
This also matches that with the home deactivated I see everything owned by `nobody` in the homedir. I think this also means in this setup there is no need for overlayfs and idmapped mounts is probably less overhead. So I'd think that removing `/var/lib/system/home/*.identity` would have worked and thanks for that hint, maybe people can even discover it via this issue. I think if this works for more setups a `homctl unbind` command does make sense. Until then maybe it would be good to mention in the man/help text of `homectl update` that not all changes take effect even on a new activate.
