### ISSUE TITLE
System.Error.EXFULL: Exchange full error 

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#29025]
### systemd version the issue has been seen with

253

### Used distribution

GNU/Linux

### Linux kernel version used

6.1.12-f20a505

### CPU architectures issue was seen on

arm

### Component

systemd

### Expected behaviour you didn't see

Noticed systems exception ` sd_bus_process discard: System.Error.EXFULL: Exchange full`

### Unexpected behaviour you saw

Unexpected exception noticed ` sd_bus_process discard: System.Error.EXFULL: Exchange full`

### Steps to reproduce the problem

this exceptions causes crash of web server app which uses D-bus call

**Comment by raviteja-b** [comment]
Can someone please help explain when does this Exception occurs?

**Comment by poettering** [comment]
systemd is not written in any programming language that knows "exceptions". Please contact the maintainers of the software at hand.

Also, this is not a support forum but a bug and feature tracker.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by raviteja-b** [comment]
I meant EXFULL error, I see systemd returns this error here 
I am trying to understand when does system hit this error  https://github.com/systemd/systemd/blob/c27465d72d22e23be3ad0a6bdd139d8ed1aeb80e/src/basic/socket-util.c#L1444

**Comment by poettering** [comment]
it means too much control data was attached to a message on the dbus wire. i.e. too many fds or so sent along.
