### ISSUE TITLE
systemd-networkd removes zebra nexthops

### ISSUE THREAD

**Issue by akunszt** [systemd/systemd#29034]
### systemd version the issue has been seen with

252

### Used distribution

Flatcar Container Linux by Kinvolk stable 3510.2.6 for Amazon EC2

### Linux kernel version used

5.15.122-flatcar

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

When adding a new interface the nexthop entries added by zebra (FRRouting) should be kept.

### Unexpected behaviour you saw

Foreign nexthops are removed. Not all of them though. Based on the logs only the ones which doesn't have a device. For example this was removed:
```
id 64 group 60/65 proto zebra
```
While the "childs" weren't touched by systemd-networkd.
```
id 60 via 169.254.135.81 dev euw2-ipv4-2 scope link proto zebra
id 65 via 169.254.227.249 dev euw2-ipv4-1 scope link proto zebra
```

### Steps to reproduce the problem

Configure FRRrouting and establish BGP peering with ECMP or just pretend it by adding nexthop entries manually which is way more easier. Change the IP addresses, nexthop ID and interfaces accordingly if needed.
(Please note that this assumes that you have `11 zebra` set in `/etc/iproute2/rt_protos`.)
```
ip nexthop add id 101 via 172.16.8.1 dev eth0 proto zebra
ip nexthop add id 102 via 172.16.8.2 dev eth0 proto zebra
ip nexthop add id 100 group 101/102 proto zebra
```
Check if the entries are added.
```
ip nexthop list
```
You should see something like this:
```
id 100 group 101/102 proto zebra 
id 101 via 172.16.8.1 dev eth0 scope link proto zebra 
id 102 via 172.16.8.2 dev eth0 scope link proto zebra
```
Add a dummy interface.
```
ip link add name dummy10 up type dummy
```
Check the nexthop list again, notice that the nexthop id 100 is gone, but we still have 101 and 102.
```
ip nexthop list
```
If you enabled debug logging in systemd-networkd you can see that it removed the nexthop id 100.
```
Sep 01 13:40:32 ip-172-16-8-93 systemd-networkd[1743]: Removing foreign nexthop (configured,marked): id: 100, gw: (null), blackhole: no, group: 101:1,102:1, flags: n/a
```
Based on the source code at:
https://github.com/systemd/systemd/blob/904b8bb5a8da4aa0257f7730e4fbaa7ba7c67742/src/network/networkd-nexthop.c#L704
systemd-networkd removes every foreign nexthops on the interface (dummy10 in this case) and everything else which are not added by the kernel even if they don't have anything to do with the interface systemd-networkd configures.
I think systemd-networkd should ignore every nexthop instantiated by dynamic routing. The best would be if we can configure which protocols we would like to exclude as there are other implementations not just zebra by FRRouting.

**Comment by poettering** [comment]
networkd manages an interface fully or not at all. if you don't want the interface managed by networkd, then do not define a matching .network interface file.

**Comment by akunszt** [comment]
I configured systemd-networkd to not manage the interface at all.
This is from the "live" system:
```
id 57 group 58/59 proto zebra 
id 58 via 169.254.123.177 dev euw2-ipv4-1 scope link proto zebra 
id 59 via 169.254.193.217 dev euw2-ipv4-2 scope link proto zebra 
```
And
```
IDX LINK        TYPE     OPERATIONAL SETUP     
  1 lo          loopback carrier     unmanaged
  2 eth0        ether    routable    configured
  3 gre0        ipgre    off         unmanaged
  4 gretap0     ether    off         unmanaged
  5 erspan0     ether    off         unmanaged
  6 ip6tnl0     tunnel6  off         unmanaged
  7 ip6gre0     ip6gre   off         unmanaged
  8 docker0     bridge   no-carrier  unmanaged
 49 euc1        ip6gre   routable    unmanaged
 70 ip_vti0     tunnel   off         unmanaged
 71 euw2-ipv4-2 tunnel   routable    unmanaged
 72 euw2-ipv6-1 tunnel   routable    unmanaged
 73 euw2-ipv4-1 tunnel   routable    unmanaged
 74 euw2-ipv6-2 tunnel   routable    unmanaged

14 links listed.
```
When I am adding a dummy interface systemd-networkd removed the nexthop id 57.

**Comment by yuwata** [comment]
Yeah, we should add e.g. KeepForeignNexthops= or so, similar to KeepConfiguration= or ManageForeignRoutes=.

**Comment by ssahani** [comment]
@yuwata How we are getting here  https://github.com/systemd/systemd/blob/main/src/network/networkd-link.c#L967  if `KeepConfiguration= yes`

**Comment by arpad42** [comment]
I am not an expert - I am very far from it in this field - but I think because the link (interface) is a different one, what the systemd-networkd wants to manage. In the example above I had 3 nexthops. One on `euw-ipv4-1`, another on `euw-ipv4-2`, none of those interfaces were managed. The third one was just a grouping without any interface set, that is the one which got removed.
The code iterates through all the nexthops - an empyt set in this case - belongs to the `dummy10` at: https://github.com/systemd/systemd/blob/d8f281abcef80024045358d1f4420a17acacc69e/src/network/networkd-nexthop.c#L713
But it then calls `manager_mark_nexthops` at: https://github.com/systemd/systemd/blob/d8f281abcef80024045358d1f4420a17acacc69e/src/network/networkd-nexthop.c#L745
That iterates through a different set: https://github.com/systemd/systemd/blob/d8f281abcef80024045358d1f4420a17acacc69e/src/network/networkd-nexthop.c#L655
And as it is a foreign nexthop and has `proto zebra`, not `proto kernel` then it gets marked at: https://github.com/systemd/systemd/blob/d8f281abcef80024045358d1f4420a17acacc69e/src/network/networkd-nexthop.c#L668
I am not sure this is what actually happens, just my theory at the moment.

**Comment by sysoleg** [comment]
@akunszt I have not been able to reproduce the problem as you describe it on any version of systemd I have tried. But I was able to reproduce it with a slightly different scenario in 9d67fb0e33, but not in a0e99a377a and the current master. At the moment I don't understand how "unmanaged" interface creation can lead to the situation you describe. Here is the setup sufficient to reproduce the problem (I'm using Debian sid as a test environment, but it probably doesn't matter as I'm compiling systemd-networkd from source):
```
# cat /etc/systemd/network/10-dummy0.netdev 
[NetDev]
Name=dummy0
Kind=dummy

# cat /etc/systemd/network/10-dummy0.network 
[Match]
Name=dummy0
[Network]
Address=192.168.32.1/24
```
The nexthop configuration is the same as yours. I just added the blackhole nexthop because, like the two-nexthop group, it is "interface-less" and will be removed by systemd-networkd:
```
ip nexthop add id 101 via 172.17.8.1 dev eth0 proto zebra
ip nexthop add id 102 via 172.17.8.2 dev eth0 proto zebra
ip nexthop add id 100 group 101/102 proto zebra
ip nexthop add id 200 blackhole
```

Everything is OK
```
# networkctl 
IDX LINK   TYPE     OPERATIONAL SETUP     
  1 lo     loopback carrier     unmanaged
  2 dummy0 ether    routable    configured    <-- link flapping interface must be configured!
179 eth0   ether    routable    unmanaged

3 links listed.

# ip next ls
id 100 group 101/102 proto zebra 
id 101 via 172.17.8.1 dev eth0 scope link proto zebra 
id 102 via 172.17.8.2 dev eth0 scope link proto zebra 
id 200 blackhole 
```

Now try setting a link down for dummy0:
```
ip link set down dev dummy0
```
or, if you prefer to emulate the physical link "cable disconnected" scenario:
```
echo "0" > /sys/class/net/dummy0/carrier
```
Whichever method you use, the result is the same:
```
# ip next
id 101 via 172.17.8.1 dev eth0 scope link proto zebra 
id 102 via 172.17.8.2 dev eth0 scope link proto zebra 
```
... dummy0 unrelated nexthops with ID 100 and 200 are gone permanently.

But as I mentioned before, the issue not reproduced since a0e99a377a.

**Comment by sysoleg** [comment]
@akunszt, I was able to reproduce your scenario in the current master. I just had to make dummy0 managed, like this:
```
# cat /etc/systemd/network/10-dummy.network 
[Match]
Name=dummy0

[Network]
```
Probably you have a `.network` file in `/run` or `/usr/lib` that catch your dummy link with a `Name=` or `Kind=` match, since you have this in `networkctl` output:
```
...
  7 dummy0 ether    degraded    configuring
...
```

Anyway such behaviour seems wrong.

Currently I don't understand the logic when `manager_mark_nexthops()` is called with `foreign = true` and `except = NULL` here: https://github.com/systemd/systemd/blob/4ae703b2b50861556f444dff5f3c07b05fcaae39/src/network/networkd-nexthop.c#L745

Nexthops without interface (`RTA_OIF`) (such as blackhole or nexthop groups) are stored in `struct Manager`. Foreign nexthops are marked in first `SET_FOREACH()` and then unmarked in `HASHMAP_FOREACH()`: 
https://github.com/systemd/systemd/blob/4ae703b2b50861556f444dff5f3c07b05fcaae39/src/network/networkd-nexthop.c#L655
https://github.com/systemd/systemd/blob/4ae703b2b50861556f444dff5f3c07b05fcaae39/src/network/networkd-nexthop.c#L672
There is no connection between interfaces (links) and manager-stored ("OIF-less") nexthops. Therefore, marked nexthops have no chance of being unmarked in this case.

Yes, problem on carrier down (as in my scenario) is not reproduced after [this](https://github.com/systemd/systemd/commit/a0e99a377a2f22c0ba460d3e7228214008714c14#diff-c1517a1a0d368baff1790c92ad58671e577bcbf24aa12e058a7f6284c77d7fdaR616) change: in such event `manager_mark_nexthops()` is not called with `foreign = true` therefore external nexthops have no chance to be marked at all.

@akunszt, FYI, as a workaround, if you don't use nexthops in FRR explicitly, you can prevent zebra from storing nexthops separately with `no zebra nexthop kernel enable`.

**Comment by yuwata** [comment]
Fix is waiting in #30433.

**Comment by gjherbiet** [comment]
If you are stuck with rather old versions of FRRouting and `systemd` (e.g. resp. `8.4.4` and `252` under Debian 12), the following might help:

Add the following to, e.g. `/etc/systemd/system/frr.service.d/systemd-networkd.conf`:
```systemd
[Unit]
PartOf=systemd-networkd.service
```
And execute `systemctl daemon-reload`.

Now each time `systemd-networkd.service` will be restarted, `frr.service` will be restarted as well.

**Comment by tirupatihemanth** [comment]
@sysoleg I think the concern you raise isn't fixed by the https://github.com/systemd/systemd/pull/30433
I can still this issue in systemd v257.9 in Debian 13. 

I see that foreign nexthops are not deleted after adding the ManageForeignNextHops=no configuration as expected. But the foreign nexthop groups (managed by zebra) are still deleted.

Nexthop groups have ifindex = 0 because they are not bound to any specific device and they are marked for deletion again
https://github.com/systemd/systemd/blob/70b5d110be7702afc4dbce012f60d49506d513da/src/network/networkd-nexthop.c#L926
```
/* Ignore nexthops bound to other links. */
if (nexthop->ifindex > 0 && nexthop->ifindex != link->ifindex)
        continue;
``` 

@yuwata Please take a look. Thanks :)
