### ISSUE TITLE
Allow a service to depend on an interface or IP address

### ISSUE THREAD

**Issue by minfrin** [systemd/systemd#29260]
### Component

systemd

### Is your feature request related to a problem? Please describe

Is is currently not possible to make a service wait until an interface is up, or an IP address is available to bind to.

The closest approximation is the "network" is up, which is undefined. This leads to bugs like this: https://github.com/systemd/systemd/issues/2037

### Describe the solution you'd like

We would like a service to depend on an interface, or an IP address.

Until the interface or IP address is available / bound, the service must wait.

When the interface or IP address is unavailable, the service should stop.

**Comment by poettering** [comment]
There's `systemd-networkd-wait-online@.service` which can be instantiated for any interface you like.

Generally it's recommended to use IP_FREEBIND to counter issues like this.

Anyway, since we already provide functionality for this, I think we can close this.

If you use a different network management tool then please contact them for a similar helper tool. This is something that they must implement, since only they know when an interface is sufficiently far set up.
