### ISSUE TITLE
systemd-resolved doesn't apply search string to PQDNs containing a dot.

### ISSUE THREAD

**Issue by schornstephan** [systemd/systemd#29306]
### systemd version the issue has been seen with

252.17-1~deb12u1 amd64

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-12-amd64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Search Domain: `contoso.lan`
FQDN: `host.department.contoso.lan`

I expect `systemd-resolved` to resolve the PQDN `host.department` to its FQDN `host.department.contoso.lan`

`ping host.department` --> Does ping.

`systemd-resolved` did do this at least until version 247.

### Unexpected behaviour you saw

`host.department` cannot be found anymore.

`ping host.department` --> `ping: host.department: Name or service not known.`

### Steps to reproduce the problem

Take a freshly installed Debian 12 without `systemd-resolved`.
Write a simple `/etc/resolv.conf` containing only a nameserver and a search string.
`ping host.department`. It will ping the Host.
Install `systemd-resolved`.
Link `/etc/resolv.conf` to `/run/systemd/resolve/stub-resolv.conf`
`ping host.department`. It won't ping the host because it can't find its IP anymore.

**Comment by poettering** [comment]
This is explicitly documented:

See https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Compatibility%20with%20the%20traditional%20glibc%20stub%20resolver

It's a conscious decision not to qualify multi-label names with search domains, since it would create ambiguity, as a domain such as "microsoft.com" would then both be conisder subject to search domain expansion (which is controllable via DHCP lease info after all), and that's certainly a security issue.

Hence, closing.
