### ISSUE TITLE
Oneshot services start multiple times with `DefaultDependencies=no` on early boot targets

### ISSUE THREAD

**Issue by HanabishiRecca** [systemd/systemd#29367]
### systemd version the issue has been seen with

systemd 254.5-1

### Used distribution

Arch Linux

### Linux kernel version used

6.5.5-arch1-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Oneshot service should start only once.

### Unexpected behaviour you saw

Oneshot service starts multiple times.

### Steps to reproduce the problem

Create a oneshot service with `DefaultDependencies=no` and wanted by some early boot target (I not tested all existing targets, but e.g. `sysinit.target` and `local-fs.target` works).

For example:
```ini
[Unit]
Description=Test service
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=sh -c 'echo test'

[Install]
WantedBy=sysinit.target
```

Then enable it (`systemctl enable test.service`) and reboot.
Look into the journal and observe that the service was run multiple times:

```
$ journalctl --unit=test.service
Sep 28 21:30:20 pc sh[231]: test
Sep 28 21:30:20 pc sh[428]: test
Sep 28 21:30:20 pc sh[444]: test
Sep 28 21:30:20 pc systemd[1]: Starting Test service...
Sep 28 21:30:20 pc systemd[1]: test.service: Deactivated successfully.
Sep 28 21:30:20 pc systemd[1]: Finished Test service.
Sep 28 21:30:20 pc systemd[1]: Starting Test service...
Sep 28 21:30:20 pc systemd[1]: test.service: Deactivated successfully.
Sep 28 21:30:20 pc systemd[1]: Finished Test service.
Sep 28 21:30:20 pc systemd[1]: Starting Test service...
Sep 28 21:30:20 pc sh[547]: test
Sep 28 21:30:20 pc systemd[1]: test.service: Deactivated successfully.
Sep 28 21:30:20 pc systemd[1]: Finished Test service.
```

---

Observation: performing soft-reboot (`systemctl soft-reboot`) **does not** trigger this behavior, the service starts only once as intended. Only the real reboot causes it.

---

`RemainAfterExit=yes` may be considered as a workaround, the service will not be started multiple times because it will count as already running. But this approach has its own drawbacks, e.g. such services do not run after soft-reboot at all.

**Comment by poettering** [comment]
oneshot services without RemainAfterExit=yes start and finish and then are flushed out and will be started again if something else pulls it in again. the mechanism to address that is to set RemainAfterExit=yes to ensure the service is only started once and then is considered up until it is stopped again.

If you want to ensure that service is stopped again during shutdown add `Conflicts=shutdown.target` + `Before=shutdown.target`. As shutdown.target is started on all forms of shutdown this will cause your service to be terminated first, so that it then can be started again after soft reboot.

Anyway, this looks more like a support question, not a bug report or feature request. If you have further questions like this please contact the systemd mailing list:
https://lists.freedesktop.org/mailman/listinfo/systemd-devel
