### ISSUE TITLE
systemd.timer behaves in an unexpected way

### ISSUE THREAD

**Issue by mvo5** [systemd/systemd#2956]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229-3ubuntu2
### Used distribution

> Ubuntu 16.04 (xenial)
### In case of bug report: Expected behaviour you didn't see

I created a systemd timer that should do system tasks two times a day at a random time.
It looks like the following:

```
$ cat /lib/systemd/system/apt-daily.timer 
[Unit]
Description=Daily apt activities

[Timer]
OnCalendar=*-*-* 6:00,18:00
RandomizedDelaySec=12h
AccuracySec=1h
Persistent=true

[Install]
WantedBy=timers.target
```

My understanding from reading `systemd.time` is that this means the job runs every day at 6:00 and 18:00 with a random delay of 12h i.e. between [6:00,18:00) and [18:00,06:00).
### In case of bug report: Unexpected behaviour you saw

With the timer running I see this when starting my machine:

```
$ systemctl list-timers|grep apt
Tue 2016-04-05 13:27:46 CEST  1 day 3h left Mon 2016-04-04 07:37:16 CEST  2h 29min ago  apt-daily.timer  
```

This tells me that the timer ran for my [6:00,18:00) slot which is expected. However the next scheduled execution is in >24h, this means that the [18:00,06:00) slot appears to be skipped?

Maybe this is expected and just a documentation problem, i.e. maybe the `*-*-*` in front of the 06:00, 18:00 are wrong. If this is the case I'm happy to contribute a patch to the manpage.
### In case of bug report: Steps to reproduce the problem
1. Install the above timer to your system
2. Shut it down over night
3. Start the system and run `systemctl list-timers`

If there is anything I can do to help shed light on this, I'm happy to do so. I know that developers are super busy so brief reply with a pointer to code or tests is fine.

Thanks for your time,
 Michael

**Comment by benjarobin** [comment]
I may be wrong, but I think you should write it this way :

```
OnCalendar=*-*-* 6,18:00
```

**Comment by julian-klode** [comment]
I'm not sure 6,18:00 is better than 6:00,18:00, it just keeps delaying things...

$ systemctl status apt-daily.timer 
● apt-daily.timer - Daily apt activities
   Loaded: loaded (/usr/lib/systemd/system/apt-daily.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Tue 2016-04-12 14:35:49 CEST; 1 day 19h ago

Apr 12 14:35:49 jak-x230 systemd[1]: Started Daily apt activities.
Apr 12 20:27:05 jak-x230 systemd[1]: apt-daily.timer: Adding 8h 44min 54.490030s random time.
Apr 12 20:27:05 jak-x230 systemd[1]: apt-daily.timer: Adding 17min 28.542259s random time.
Apr 13 12:55:05 jak-x230 systemd[1]: apt-daily.timer: Adding 41min 54.712048s random time.
Apr 13 12:55:05 jak-x230 systemd[1]: apt-daily.timer: Adding 4h 26min 28.794729s random time.
Apr 13 13:51:23 jak-x230 systemd[1]: apt-daily.timer: Adding 2h 2min 32.080349s random time.
Apr 13 14:56:36 jak-x230 systemd[1]: apt-daily.timer: Adding 8h 21min 46.752410s random time.
Apr 13 16:07:09 jak-x230 systemd[1]: apt-daily.timer: Adding 11h 57min 55.081166s random time.
Apr 14 05:58:03 jak-x230 systemd[1]: apt-daily.timer: Adding 1h 10min 19.983549s random time.
Apr 14 05:58:03 jak-x230 systemd[1]: apt-daily.timer: Adding 4h 46min 45.125722s random time.

**Comment by julian-klode** [comment]
Further input: 13:51:23, 14:56:36, 16:07 are times where my machine resumed from sleep.

**Comment by julian-klode** [comment]
OK, so it actually ran if I look at apt-daily.service instead (or list-timers), but that's not really obvious from the apt-dailyer.timer status output :(

**Comment by poettering** [comment]
"6:00,18:00" means "Minutes 0 and 18 after 6 o'clock". I think you want to write "6,18:00:00" instead?

Or in other words: the "," binds first, the ":" second...

Does this explain your issue?

**Comment by keszybz** [comment]
Closing because of lack of feedback.
