### ISSUE TITLE
Failed to fork off sandboxing environment

### ISSUE THREAD

**Issue by arief-ametek** [systemd/systemd#29621]
### systemd version the issue has been seen with

253-stable

### Used distribution

 NXP i.MX Release Distro 6.1-mickledore 

### Linux kernel version used

Linux version 6.1.36

### CPU architectures issue was seen on

arm

### Component

systemd

### Unexpected behaviour you saw

Hardware : IMX8MP evl board
Linux : version 6.1.36
Distribution:  NXP i.MX Release Distro 6.1-mickledore.
Image loading from Sdcard.

Sandbox booting error as below,  

[    3.229915] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    3.238808] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    3.245447] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    3.254077] platform regulatory.0: Falling back to sysfs fallback for: regulatory.db
[    3.269685] ALSA device list:
[    3.272667]   No soundcards found.
[    3.276367] Waiting for root device /dev/mmcblk1p2...
[    3.354709] mmc1: host does not support reading read-only switch, assuming write-enable
[    3.387377] mmc1: new ultra high speed SDR104 SDHC card at address aaaa
[    3.394419] mmcblk1: mmc1:aaaa SC16G 14.8 GiB 
[    3.403478]  mmcblk1: p1 p2 p3 p4
[    3.527748] EXT4-fs (mmcblk1p2): mounted filesystem with ordered data mode. Quota mode: none.
[    3.536363] VFS: Mounted root (ext4 filesystem) on device 179:98.
[    3.545027] devtmpfs: mounted
[    3.548616] Freeing unused kernel memory: 3328K
[    3.553423] Run /sbin/init as init process
[    3.776225] systemd[1]: System time before build time, advancing clock.
[    3.817771] systemd[1]: systemd 253.1^ running in system mode (+PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -)
[    3.849538] systemd[1]: Detected architecture arm64.

 

Welcome to NXP i.MX Release Distro 6.1-mickledore (mickledore)!

[    3.930857] systemd[1]: Hostname set to <imx8mp-mcde-motec>.
[    3.944808] systemd[1]: Initializing machine ID from random generator.
[    4.000027] systemd[1]: Failed to fork off sandboxing environment for executing generators: Protocol error
[!!!!!!] Failed to start up manager.
[    4.033649] systemd[1]: Freezing execution.
[   13.284685] platform 30830000.spi: deferred probe pending
[   13.290126] platform sound-bt-sco: deferred probe pending

Please support to fix this issue.

**Comment by mrc0mmand** [comment]
Could you try to boot the system with debug logging? Adding `systemd.log_level=debug systemd.default_standard_output=journal+console` to the kernel cmdline should do the trick.

**Comment by arief-ametek** [comment]
I tried to add those parameters in bootargs as uboot parameters and unfortunately, no additional log was found. can you please suggest a way to add the parameters in the right place ?

**Comment by arief-ametek** [comment]
My trial was as below to add log levels in uboot

u-boot=> print bootcmd

bootcmd=run sr_ir_v2_cmd;run distro_bootcmd;run bsp_bootcmd

u-boot=> print sr_ir_v2_cmd

sr_ir_v2_cmd=cp.b ${fdtcontroladdr} ${fdt_addr_r} 0x10000;fdt addr ${fdt_addr_r};fdt set /soc@0/usb@32f10100/usb@38100000 compatible snps,dwc3;fdt set /soc@0/usb@32f10108/usb@38200000 compatible snps,dw 

u-boot=> print distro_bootcmd

distro_bootcmd=for target in ${boot_targets}; do run bootcmd_${target}; done

u-boot=> print bsp_bootcmd

bsp_bootcmd=echo Running BSP bootcmd ...; mmc dev ${mmcdev}; if mmc rescan; then if run loadbootscript; then run bootscript; else if run loadimage; then run mmcboot; else run netboot; fi; fi; fi;

u-boot=> print mmcboot

mmcboot=echo Booting from mmc ...; run mmcargs; if test ${boot_fit} = yes || test ${boot_fit} = try; then bootm ${loadaddr}; else if run loadfdt; then booti ${loadaddr} - ${fdt_addr_r}; else echo WARN: ;

u-boot=> print mmcargs

mmcargs=setenv bootargs ${jh_clk} ${mcore_clk} console=${console} root=${mmcroot}

u-boot=> editenv mmcargs

edit: setenv bootargs ${jh_clk} ${mcore_clk} console=${console} root=${mmcroot} systemd.log_level=debug systemd.default_standard_output=journal+console

u-boot=> saveenv
u-boot=>run bootcmd

 
I see the same log - no additional logs present

 

Welcome to NXP [i.MX](https://i.mx/) Release Distro 6.1-mickledore (mickledore)!

 

[   3.962388] systemd[1]: Hostname set to <imx8mp-mcde-motec>.

[   3.999987] systemd[1]: Failed to fork off sandboxing environment for executing generators: Protocol error

[!!!!!!] Failed to start up manager.

[   4.033765] systemd[1]: Freezing execution.

[  13.280788] platform 30830000.spi: deferred probe pending

[  13.286228] platform sound-bt-sco: deferred probe pending

[ 111.714018] random: crng init done

**Comment by arief-ametek** [comment]
Hi,
Removing the /tmp soft link from the file system and creating a /tmp directory with full R/W permission is the fix for the problem.

**Comment by anatoly-romanov** [comment]
Hi! I've also ran into this issue, also on Yocto Mickledore 6.1-mickledore with i.MX 8M Mini based board, when building a read-only rootfs. I managed to turn /tmp into a directory instead of a symlink (as @arief-ametek did) during the build, by creating a initscripts_%.bbappend in my layer with the following contents:

```
do_install:append() {
    sed -i 's/.*\/tmp \/var\/tmp.*/d root root 1777 \/tmp none/' \
        ${D}${sysconfdir}/default/volatiles/00_core
}
```

The process of me figuring it out:
- Check the do_rootfs.log of my image to see messages related to creating /tmp. See a "Creating link ... /rootfs/tmp-." message
- grep for "Creating link", find out it's in poky/meta/recipes-core/initscripts/initscripts-1.0/populate-volatile.sh
- See that it prints from a function apply_cfgfile, and that the list of directories/links to be created is read from a file, whose name is the first parameter
- Look for apply_cfgfile call site, see that the first argument is "${CFGDIR}/${COREDEF}", and it see that it expands into /etc/default/volatiles/00_core by looking where CFGDIR and COREDEF are assigned
- Find out that /etc/default/volatiles/00_core is installed with the `initscripts` package by executing `oe-pkgdata-util find-path /etc/default/volatiles/00_core`

I would still like to know why systemd fails to boot with /tmp being a link to /var/tmp, and whether it's an issue with systemd or this specific Yocto build

**Comment by linas** [comment]
This also hits containers; see https://discuss.linuxcontainers.org/t/failed-to-fork-off-sandboxing-environment-for-executing-generators-protocol-error/19521/2

In my case, I can look at the rootfs directly, and `container/rootfs/tmp` is a directory, not a symlink, so above doesn't fix it for me.  Also, for a container, there is no boot command line (since the kernel is lready running) so I don't know how to turn on additional systemd debugging. In my case, `lxc-unpriv-start -n debian-testing -F -l DEBUG` only prints additional LXC debugging and not systemd debugging.

For now, I'm stumped.

**Comment by Hi-Angel** [comment]
In my case I found it was caused by `--cap-add=SYS_ADMIN` Podman parameter *(AFAIR it's required for debugging to work)*. I'm not sure though, why it usually works, but not in the current case.
