### ISSUE TITLE
systemctl: unrecognized option '--kill-whom=main'

### ISSUE THREAD

**Issue by Crpepeyo** [systemd/systemd#29793]
### systemd version the issue has been seen with

247

### Used distribution

Debian 11

### Linux kernel version used

5.15.71-g93dec5e561dd

### CPU architectures issue was seen on

aarch64

### Component

systemctl

### Expected behaviour you didn't see

I created my own service and I need to send a signal to kill only the main process, in the documentation i found that the command to do that is --kill-whom=main

In my configuration of the service i have 
[Unit]
Description=name
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart=/usr/libexec/script.sh
StandardOutput=inherit
KillMode=process
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

### Unexpected behaviour you saw

When i send a signal with --kill-whom=main i got a message of unrecognized option 
![image](https://github.com/systemd/systemd/assets/35903102/6a255edc-36de-415a-bfaa-ddca429f90ba)

### Steps to reproduce the problem

systemctl kill --signal=SIGUSR1 --kill-whom=main "name.service"

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by poettering** [comment]
(the option was named --kill-who= in old versions)

**Comment by ice909** [comment]
@poettering May I ask in which version this option was renamed？

**Comment by ice909** [comment]
> Since [4ccde41](https://github.com/systemd/systemd/commit/4ccde410a3fc141c9ddf285f24a22dfea99e0287) (v252).

Thank you very much.
