### ISSUE TITLE
RFE: gpt-auto-generator: honour rd.luks.options= kernel cmdline 

### ISSUE THREAD

**Issue by jinliu** [systemd/systemd#29828]
### Component

systemd-gpt-auto-generator

### Is your feature request related to a problem? Please describe

Rationale is the same as https://github.com/systemd/systemd/pull/25816

### The systemd version you checked that didn't have the feature you are asking for

254.5

**Comment by jinliu** [comment]
1. Maybe also rd.luks.key= ?
2. Maybe also luks.options= and luks.key= ?
3. cryptsetup-generator allows `<UUID>=value` in these parameters, but since gpt-auto-generator is about not specifying part-uuid, maybe we shouldn't allow this, and then maybe we should use different parameter names.

**Comment by jinliu** [comment]
Or maybe instead of adding more to the kernel cmdline (e.g. what about homeflags and usrflags?), we can have gpt-auto.conf, where instead of partition ids, we can specify root.flags=, usr.luks.options=, etc.

**Comment by YHNdnzj** [comment]
Let's turn this around: instead of making gpt-auto-generator do all the heavy lifting, we should expose the DPS-conforming partitions in /dev/disk/. So if you want both discovery _and_ automatic mounting, use gpt-auto-generator. If you only want auto discovery of the partitions and then configure the luks/mount options yourself, use fstab/mount.extra with the gpt-auto device symlinks.

**Comment by YHNdnzj** [comment]
Please check https://github.com/systemd/systemd/pull/28894

**Comment by jinliu** [comment]
That totally makes sense. Thanks!
