### ISSUE TITLE
How to Install Systemd in the Centos6 Series

### ISSUE THREAD

**Issue by 1392273211** [systemd/systemd#29868]
### Is your feature request related to a problem? Please describe

How to Install Systemd in the Centos6 Series

**Comment by YHNdnzj** [comment]
Sorry, this is the upstream bug tracker for systemd rather than a support forum. For that, please goto our [mailing list](https://lists.freedesktop.org/mailman/listinfo/systemd-devel) instead.

And CentOS 6 is too ancient wrt kernel and everything. I believe this is simply not supported by any means.

**Comment by mrc0mmand** [comment]
Given that even CentOS 7 doesn't meet the minimum requirements for the latest systemd anymore, running it on CentOS 6 is _really_ out of the question (not to mention that CentOS 6 is EOL since 2020).
