### ISSUE TITLE
Interface renaming not working

### ISSUE THREAD

**Issue by DigiAngel** [systemd/systemd#29886]
### systemd version the issue has been seen with

249.11-0ubuntu3.10

### Used distribution

Ubuntu 22

### Linux kernel version used

kernel-5.15.0-87

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

Rename the interface from eno1 to management0

### Unexpected behaviour you saw

No change

### Steps to reproduce the problem

Boot system

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
/etc/systemd/network/00-management0.link:
[Match]
MACAddress=<mac address>

[Link]
Name=management0
```

**Comment by poettering** [comment]
Version too old. Also a support question. Please contact systemd-devel ML. No logs supplied either. Not actionable to us.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
