### ISSUE TITLE
systemd and nfsroot

### ISSUE THREAD

**Issue by michal-staniszewski** [systemd/systemd#300]
While starting system from nfsroot is ok (not quite but works), reboot/shutdown hangs the system.
System: OpenSUS 13.1 x86_64
The problem is that systemd shuts down network interfaces after unmounting remote file systems and it breaks root nfs filesystem communication with nfs server which in turn hangs the server.
Is there any workaround to enable proper working with nfsroot?
Regards,
Michal

**Comment by crrodriguez** [comment]
On Fri, Jun 19, 2015 at 4:56 PM, michal-staniszewski <
notifications@github.com> wrote:

> While starting system from nfsroot is ok (not quite but works),
> reboot/shutdown hangs the system.
> System: OpenSUS 13.1 x86_64

Too old, too much has changed since that time.. please update to 13.2 or
better to tumbleweed..

> The problem is that systemd shuts down network interfaces after unmounting
> remote file systems and it breaks root nfs filesystem communication with
> nfs server which in turn hangs the server.
> Is there any workaround to enable proper working with nfsroot?
> Regards,
> Michal
> 
> is the dracut nfs module included in your setup ?

**Comment by michal-staniszewski** [comment]
Actually I can't update because of other dependencies.
I don't use dracut but mkinitrd -f nfs
Michal

**Comment by crrodriguez** [comment]
On Fri, Jun 19, 2015 at 6:03 PM, michal-staniszewski <
notifications@github.com> wrote:

> Actually I can't update because of other dependencies.
> I don't use dracut but mkinitrd -f nfs
> Michal

Well..  mkinitrd is nowadays just a wrapper around dracut..unfortunately
13.1 does use the old mkinitrd which is no longer under development.

Anyway, this is not a systemd issue, it is either a bug in the openSUSE NFS
units or a bug in the old mkinitrd, please file a bug report at the
openSUSE bugtracker . Since this is a long.term support release, it might
have a chance of being fixed.. but I wouldn't hold my breath.

**Comment by poettering** [comment]
Yeah, @crrodriguez is right, this is not something to discuss at systemd upstream. We neither have specific nfsroot support (needs to be added by downstream distros), nor is this about any recent systemd version (please only report bugs in very recent systemd versions upstream). 

Please file a bug against OpenSUSE instead! Thanks!
