### ISSUE TITLE
Allow change status of systemd from deactivating. 

### ISSUE THREAD

**Issue by sophallee** [systemd/systemd#30175]
### Is your feature request related to a problem? Please describe

I had an incident where I stopped MySQL via the systemctl command. However, the MySQL process was in a zombie meaning systemctl was stuck in deactivating. If I was to restart the server in this state, AlmaLinux would be stuck for 30 mins as this is the default timeout to wait for stopping services. 

I have had issues when creating a systemd services for a software in my test environment. There were conditions that resulted in the state being stuck in deactivating.

### Describe the solution you'd like

I know there is a way to set the timeout on AlmaLinux to a shortened timeout. However, being able to change the state of a systemd service to stopped would be useful in a scenario where a systemd process becomes a zombie. 

Furthermore, when setting up the systemd process in my test environment, being able to change the deactivating condition to stopped would be very useful. At this stage, when my stop script fails, it's stuck in deactivating and I have to reboot the server each time this happens.

**Comment by poettering** [comment]
systemd will immediately rip all zombies that are children of PID 1. Thus, if you have a mysql as a zombie then i presume that wasn#t an immediate child of PID but some intermediary process in between, and that one was stuck? If so, you can just kill it hard, i.e. use `systemctl kill mysql.service -sKILL`.

If you do that, then all remaining processes will be killed, and their children (which might be zombies) are reparented to PID 1, which will then reap them and all is good.

Hence closing, since what you are asking for already exists.
