### ISSUE TITLE
Bluetooth disabled state not restored when resuming from disk

### ISSUE THREAD

**Issue by jconte** [systemd/systemd#3026]
# Overview

I'm running systemd 229 and GNOME 3.20.0 via Fedora 24 alpha on a Lenovo T420 Thinkpad which has one integrated Bluetooth adapter.

If I disable Bluetooth via the GNOME Control Center, suspend the laptop to disk, then resume from disk, Bluetooth is enabled upon resuming from disk. My expectation is that the disabled state should be retained upon resuming from disk the same way it is when rebooting or resuming from RAM.
# Additional Information

This behavior is present after a fresh installation with default packages. I do have to add `resume=/dev/fedora/swap` to the kernel parameters otherwise resume from disk fails to work with Fedora.

The bug only seems to occur after resuming from disk. If I disable Bluetooth then suspend to RAM and resume, Bluetooth is still disabled. If I disable Bluetooth and reboot, it is still disabled. So it seems that the Bluetooth state is not being saved before the suspend to disk takes place or the saved state is not being applied when resuming from disk.

Perhaps it's worth noting that GNOME Control Center seems to toggle different Bluetooth disable states depending on whether one disables Bluetooth from the GNOME Control Center Bluetooth panel or from the GNOME Control Center Power panel.

I originally reported this bug in the GNOME Bug tracker ([#758682](https://bugzilla.gnome.org/show_bug.cgi?id=758682)) where I was informed that this bug is related to the `systemd-rfkill@.service`.
# Steps to Reproduce
## Bluetooth completely enabled

GNOME Control Center -> Bluetooth: _ON_
GNOME Control Center -> Power -> Bluetooth: _ON_

```
$ rfkill list bluetooth
0: tpacpi_bluetooth_sw: Bluetooth
        Soft blocked: no
        Hard blocked: no
6: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no
```
## Bluetooth partially disabled

GNOME Control Center -> Bluetooth: _OFF_
GNOME Control Center -> Power -> Bluetooth: _ON_

```
$ rfkill list bluetooth
0: tpacpi_bluetooth_sw: Bluetooth
        Soft blocked: no
        Hard blocked: no
8: hci0: Bluetooth
        Soft blocked: yes
        Hard blocked: no
```
## Bluetooth completely disabled

GNOME Control Center -> Bluetooth: _OFF_
GNOME Control Center -> Power -> Bluetooth: _OFF_

```
$ rfkill list bluetooth
0: tpacpi_bluetooth_sw: Bluetooth
        Soft blocked: yes
        Hard blocked: no
```
## Bug manifests

```
$ systemctl hibernate
```

**Boot System**

```
$ rfkill list bluetooth
0: tpacpi_bluetooth_sw: Bluetooth
        Soft blocked: no
        Hard blocked: no
9: hci0: Bluetooth
        Soft blocked: yes
        Hard blocked: no
```

**Comment by poettering** [comment]
Please turn on debug logging in systemd-rfkill.service (add a drop-in via systemctl edit and add Environment=SYSTEMD_LOG_LEVEL=debug, then restart the service...) and please check what kind of output it generates during the hibernation.

**Comment by jconte** [comment]
Thanks for the tip about the drop-in. I added this for systemd-rfkill.service:

```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

But I don't see much difference. journalctl -u systemd-rfkill.service just gives me a lot of this:

```
systemd[1]: Starting Load/Save RF Kill Switch Status...
systemd[1]: Started Load/Save RF Kill Switch Status.
```

After doing a bit more digging, I've determined that the Bluetooth toggle on the Bluetooth panel of GNOME Control Center flips `/var/lib/systemd/rfkill/pci-0000:00:1a.0-usb-0:1.4:1.0:bluetooth` and the Bluetooth toggle on the Power panel of GNOME Control Center flips `/var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth`. It is the state of the latter (`platform-thinkpad_acpi:bluetooth`) which is not maintained after resuming from hibernate. It is always set to 0 on the boot following hibernate.

**Comment by poettering** [comment]
OK, my guess is that this is actually a driver problem. Specifically, that the thinkpad ACPI driver isn#t handling hibernation properly. systemd-rfkill will only restore the state of rfkill devices that come and go via hotplug. As USB devices are disconnected on hibernation, systemd-rfkill will nicely persist them. This is different for the thinkpad ACPI driver: it sticks around all the time, and systemd-rfkill doesn't get active on it.

Or in other words: persisting the state of the APCI thinkpad driver's rfkill device during hibernation is out of focus for systemd-rfkill, since systemd-rfkill only persists the state of devices when hotplugged/hotunplugged.

Or in even other words: it appears you ACPI kernel driver doesn't properly serialize its rfkill state to disk when hibernation takes places, because it's the really the job of the kernel/driver to do that, not systemd's. Please file a bug against the kernel, on kernel bugzilla, to get this fixed.

**Comment by jconte** [comment]
Thank you for the explanation. I will forward this issue to the upstream kernel as you have suggested.

> systemd-rfkill will only restore the state of rfkill devices that come and go via hotplug.

Does that mean it would be considered a bug that systemd-rkill tracks the state of a device it is not capable of restoring? (i.e. `/var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth`)

**Comment by poettering** [comment]
> Does that mean it would be considered a bug that systemd-rkill tracks the state of a device it is not capable of restoring? (i.e. /var/lib/systemd/rfkill/platform-thinkpad_acpi:bluetooth)

No, it wouldn't. So, in contrast to what I wrote above: on Linux these days pretty much every device is hotplugged, and that includes the platform thinkpad ACPI driver, which is hotplugged exactly once at boot. However, what I wanted to say is that from that point on it really just stays, it never goes away. And with systemd-rfkill.service we'll cover the initial hotplug just fine, and will track the runtime state for that, so that for this rfkill device the state is persistet across reboots. 

To explain this in different words: systemd-rfkill.service WRITES to a device's rfkill state only when a device is hotplugged (regardless if that is the initial boot-time "hotplug" – which sometimes is called "coldplug" – or actual runtime hotplug), but it SAVES a device's rfkill state each time it changes. Because of this, during hibernation it will only restore a device's rfkill state if it's one of those rfkill devices that are actually "hotunplugged" during hibernation, and are "hotplugged" again after hibernation ends. But for those devices which stay around during hibernation, it won't do a thing, because if a device stays around it really should be able to maintain its state, and if it does not, then that's a kernel driver bug, and should be fixed in the kernel driver.

You have two rfkill devices, and one is of the kind that stays around (the ACPI platform one), and one is of the other kind (the USB one). Thus we cover the latter nicely, and the former is provided by a buggy driver.

Does this make sense?

**Comment by jconte** [comment]
> Does this make sense?

Yes. Thanks again for taking the time to explain this.

**Comment by mxl** [comment]
Here is [kernel bug report](https://bugzilla.kernel.org/show_bug.cgi?id=60697).
For me adding kernel parameter `acpi_osi='!Windows 2012'` works.
