### ISSUE TITLE
Can systemd-journald be config-able to surpress some log level(such as surpress debug level output)?

### ISSUE THREAD

**Issue by yangsongx** [systemd/systemd#30320]
### Component

systemd-journald

### Is your feature request related to a problem? Please describe

I don't want the debug level output be found in journalctl, can we do this by config some configuration file?

**Comment by ragazenta** [comment]
You could set `LogLevelMax` in your service unit file or `MaxLevelStore` in journald.conf

Note: This question should be asked at systemd mailing list.

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
