### ISSUE TITLE
introduce "--job-mode=triggering" for "systemctl stop" that also stops triggering socket units and suchlike

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#3043]
When stopping unit, `systemctl` will check if the given unit has any triggering units and if yes, then  following warning is displayed to the user, e.g.

```
Warning: Stopping systemd-udevd.service, but it can still be activated by:
   systemd-udevd-control.socket
   systemd-udevd-kernel.socket
```

It would be nice to have the possibility for the user to say something like, 

```
systemctl --also-triggers stop <unit>
```

`systemctl` would then stop all triggering units first and then the unit for which stop action was explicitly requested.

**Comment by poettering** [comment]
In the TODO list we already have an RFE for this, but the suggested concept would be to extend the --job-mode= enum for that. i.e.:

```
systemctl stop --job-mode=triggering foobar.service
```

And I think the fix for that would be pretty easy actually, as we already track TriggeredBy depdenencies, hence all that's necessary is to also follow those deps when putting together the transaction. My guess is that it's a < 10 line patch for the actual code changes.

Would be happy to take a PR for that.

**Comment by msekletar** [comment]
Hmm...Concept itself is not generic enough to justify addition on new job mode, imho. But if you strictly insist I don't care much either.

**Comment by poettering** [comment]
Well, I think doing this as job mode is a much more minimal addition to the API than adding a completely new switch to systemctl, plus a new set of method calls on the bus that can transport it.

It's also conceptually the right place I'd claim, since the job mode is used so far to configure how the request is propagated to other jobs and unit, and this new addition defines exactly that: a new way how to propagate operations between units.

**Comment by msekletar** [comment]
What I had in mind originally was something radically simpler. From systemctl I'd query set of triggering units, I'd stop those first (enqueue jobs and wait for them to complete)  and then proceed to stop the main unit.

I am aware of the TOCTOU nature of operation if done in two steps as proposed but triggering units are configured once and don't change often, so I think that will not be a problem in practice.

**Comment by msekletar** [comment]
Thinking about this once more, you are probably right that adding new job mode will be less code then implementing some additional logic on `systemctl` side.
