### ISSUE TITLE
Bug 87799 - RFE: OnFailure version which is used when StartLimitBurst= or StartLimitInterval= are hit

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#305]
Wanna to duplicate here the bug-report from bugs.freedesktop.org: https://bugs.freedesktop.org/show_bug.cgi?id=87799 , because bugs.freedesktop.org seems to be in limbo.

Does the defined in Bug 87799 problem still actual or already fixed?

**Comment by poettering** [comment]
The fdo bugzilla is still open for discussion, but will not accept new bugs to be filed. We decided to not migrate bugs though, and we still work on the ones in fdo bz. Hence let's please continue to track this on fdo bz, I will hence close this bug here now. And no, the issue has not been worked on or fixed, and hence the fdo bz bug should stay open.

**Comment by MikhailKasimov** [comment]
Hello!

Due to comment on https://bugs.freedesktop.org/show_bug.cgi?id=87799#c11 , please, reopen this report. Thanks!
