### ISSUE TITLE
identification of ttyUSB*

### ISSUE THREAD

**Issue by alexanderzhirov** [systemd/systemd#30574]
### Is your feature request related to a problem? Please describe

To use USB devices, the serial port must be identified. When connecting multiple devices, these ports have different indexes. The problem is the constant reconfiguration to the required ports.

I understand that there is a `/dev/serial/by-*`, but this is not exactly the mechanism that I would like. At a minimum, if I connect 2 identical devices, they are identified in the same way in `*/by-id`, even if I swap them.

Or - is there a way in the `udev` library to identify `ttyUSB` as the path to `/dev/ttyUSB*`? I found only a crutch - to search for this name in the directory of the connected interface - `DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3.4/2-3.4:1.0`. Maybe should make a separate attribute that will store this name too?

**Comment by poettering** [comment]
> I understand that there is a `/dev/serial/by-*`, but this is not exactly the mechanism that I would like. At a minimum, if I connect 2 identical devices, they are identified in the same way in `*/by-id`, even if I swap them.

Sure, if you have two identical devices then they will have the same id, no surprise there?

If the identifiers cannot distinguish the devices, then use some other identifier, for example /dev/serial/by-path/ symlinks? the will give the devices stable names based on the USB port they are connected to.

But I am not sure I grok what the question is even supposed to be here, can't make sense what you are actually asking here.

**Comment by AlexanderZhirov** [comment]
For example, when connecting a USB modem, it is impossible to identify by name which port a particular modem was connected to. The only way to do this is to make an AT request to the serial port. But to use the udev library, this cannot be done, since the path to the serial port is determined by the kernel, and the link to the device itself cannot be determined through the udev library.

**Comment by poettering** [comment]
> If the udev library made it possible to get the path to this serial port as the serial port connection parameter, then it would be possible to make a request to this port. But alas, this path is not in the parameters. There is only the serial port numbering, but not the port path itself.

i don't understand what you mean by "port"? and i don't understand what oyu mean by "path is not in the parameters? what is "parameters" supposed to mean here?

not grokking at all what the issue is supposed to be?

don't the /dev/serial/by-path/ symlinks suffice to reference a specific modem via its device path?

**Comment by poettering** [comment]
Closing due to lack of response.
