### ISSUE TITLE
udevd needs persistent link holder for i.e. filesystem uuid

### ISSUE THREAD

**Issue by zkabelac** [systemd/systemd#3066]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd-udev-229-9.fc25.x86_64
### Used distribution

Fedora Rawhide
### In case of bug report: Expected behaviour you didn't see

Persistent setting of symbolic links in /dev/disk/by-uuid/
As even better way - we would like to see in lvm2 a method how to select which device can actually create such uuid link - so user can select if activation of  diskB is supposed to make filesystem available to the system  (i.e. if could be unrelated device for a guest activated on a host)

There is likely more such links where the 'first' link creater should be holding this link as long as it is alive - so disk duplicates will not cause run systemd service activations...
### In case of bug report: Unexpected behaviour you saw

When having 2 same disks (i.e. after dd if=A of=B, or using lvm2 thin snapshots)
the links for  filesystem are rather 'randomly' jumping around devices according
to the fact who was the last device to run 'watch' rule.
i.e. udevadm  info -q all -n  diskA   diskB
shows both having:  S: disk/by-uuid/cbce1387-c648-4df9-ab46-84025ab9a11d

This issue is closely related to this commit:

https://github.com/systemd/systemd/commit/071e0b8b3a698e73bcaecba09ffccab5553d2365

where likely a real system bug is getting hidden - user should be concerned as he has 2 devices
in the system both claiming ownership of a single link in /dev  filesystem and udev/systemd is getting confused. So better logic is needed..
### In case of bug report: Steps to reproduce the problem

> mkfs diskA
> dd if=diskA of=diskB

observe how the uuid link jumps from pointing to existing diskA to diskB, then invoke watch rule on them and see he it's getting relinked. After zeroing either of disks, the links goes to remaining one.

**Comment by poettering** [comment]
well, what do you propose? if two devices identify with the same data, then how would you discern them? I mean, that's kinda the key here: they use the same id data, thus cannot be discerned...

Really, if you use identical uuids for two volumes, and think that's an OK thing to do, then don't use that to identify the volumes, because by definition they are not unique. Use something else then, such as the device path or even the kernel names. But the key to the issue is: if you use UUIDs to identify your devices, then it's up to you to keep them suitable for that, and not assign them multiple times.

**Comment by zkabelac** [comment]
Yep that's the whole point of this RFE to figure out the solution.

It's ATM nontrivial to resolve the logic inside udev rules file - as there is needed some support to check there is already 'existing' UUID link - and we do not want to acquire link then to avoid fight for it.

We may possibly cook something quite complicated inside lvm2 udev rules to detect whether there is an existing filesystem with matching UUID (may need some forking I guess), but solving this directly on udev side is way easier as it knows about all devices, while in  rule file we know only about a single device so recognize there is an existing conflict is way harder - and  moreover - it will apply only to dm device - leaving other generic devices with same problem.

IMHO as a user I'd expect first 'holder' keeps the link until it's gone. Do you have a better proposal
how to handle this - i.e. how to avoid multiple assigns with existing udevd support ?

**Comment by poettering** [comment]
@zkabelac in udev the first device popping up will win. But as this is hardware, it may pop up in any order, and you never know if there will be more popping up.

**Comment by zkabelac** [comment]
It's a sure thing we don't know the order - but the problem is flipping between devices.

So whoever wins the link - is the link keeper - so there is no way to reference non-deterministically a device via uuid - you always get via link to the same device.

As a bonus feature would be then a mechanism to control who may get the link and which device is rather to be 'ignored'  - we do have some mechanism in lvm2 for old snapshot to use the link priority - however with thin-volumes it's way more complicated and resolvable only at runtime udev rule file.

**Comment by arvidjaar** [comment]
@zkabelac 

> So whoever wins the link - is the link keeper

This implies there is some other unique identification for link keeper. So use device alias based on this unique identification.

And at least in case of btrfs it is _required_ that link is flipped, otherwise multi-device btrfs support won't work (as implemented currently).

**Comment by zkabelac** [comment]
@arvidjaar  unsure what for would be this useful in  Btrfs - but when I get uuid of mounted filesystem and I'd use   fcsk /dev/disk/by-uuid  after unmount - I'd expect I'm addressing still the same disk no matter how many disk copies I've create in my system with i.e.  'dd' command.

The simple naive implementation in udev could be like - automatic counter uses some 'priority' counter/number when device with same UUID gets in - the later one gets the lower priority for a given symlink. So the device with highest priority is the link holder and when it's gone (REMOVE event) the next one in the list gets the link.

With Btrfs it should not matter which device is used for mounting - all devices for a single filesystem should be usable aren't they?  So if the UUID would be pointing to the first discovered device instead of the last one - it should still work very weil ?

**Comment by poettering** [comment]
@zkabelac i am sorry, but if you have multiple file systems with the same UUID, then that's completely OK, but then _don't_ _use_ _the_ _UUID_ _for_ _identification_ of the device... It's really that simple.

**Comment by zkabelac** [comment]
@poettering   I think you still  miss the point - the udev  cannot randomly non deterministically change resource link used by multiple devices - there should  be rules - i.e. first come first served.  udev database can't get into chaotic state when there is pretty simple deterministic solution - it's really that simple.  

Why then bother with links /dev/disk/by-uuid if it is plain useless ??

How even the  systemd unit service can be based on something which could be very easily confused by just 'dd' of disk header elsewhere?  Not sure why you are refusing this RFE which is needed in complex storage environments.

**Comment by poettering** [comment]
/dev/disk/by-uuid/ links are indeed useless if you have multiple file systems with the same UUID. That's by definition.

Use /dev/disk/by-uuid/ if your UUIDs are actually unique. if they aren't then /dev/disk/by-uuid is useless.

Note that the acronym "UUID" already includes the hint that they should be "unique". If they aren't then all bets are off, and what you get is necessarily not going to be reliable and stable. That's a pretty obvious deal.

And which device wins is never going to be deterministic, since device probing isn't. Devices can pop up at any time in any order. You never know what comes first, what comes second, and you never know whether something comes second at all. Hence you cannot resolve this, and first-come-first-serve (which udev actually implements) isn't going to provide you with a stable definition either.

If you have multiple file systems with the same UUID, then you have two options: a) don't use /dev/disk/by-uuid links, they are useless by definition in this case. or b) fix your file systems, and make the UUIDs actually unique.

**Comment by zkabelac** [comment]
The lvm2 deals with duplicated disk in sophisticated way - it needs to be detected and exposed to the user  and lvm2 tries to recognize which devices are the correct one - it's actually quite a some portion of lvm code..

When you have 'exact' same duplicates of disk - you will simply need to deal with them - they are not distinguishable by any blkid scan  and only the USER knows  what  /dev/sda   and /dev/sdb  is.

But this cannot lead to random flip of udev database base on the fact which device has been closed last  for write access - and udev database pretends all is OK.

That's why your  log error was a better message then debug - instead of hiding error with debug you should think how to handle the actual error.

It is deterministic to the point it will not change during lifetime of device in the system.
Doing disk duplicates by  'dd' command is pretty common command - so not sure why are you objecting against better solution then the current existing 'random' one - where usage of udev is giving 'random' results event through there were no physical 'disk' manipulations.

I should note - it's not needed for lvm2 - we deal with device tree validation differently - but all applications & services becomes fragile  with plan  'dd' copy of user's  root disk....

**Comment by poettering** [comment]
@zkabelac well, udev is totally happy with multiple disks with the same UUID. If you use its API it will allow you to enumerat the disks, it will tell you about both. But the /dev/by-disks/uuid/ links are symlinks, and symlinks on UNIX can only point to one place. If you want to cover cases where the same UUID is assigned to two file systems, then simply don#t use those symlinks at all. Instead, use libudev and enumerate the devices, and use whatever you find.

Again, /dev/disks/by-uuid/ are an offer, for those cases where the UUIDs actually honour their name and are really unique. For all other cases they are useless. Use something else, enumerate the devices via the libudev API, but don't pretend we could shoehorn support for borked UUIDs into the symlinks, it's not for that, and it simply cannot cover this.

**Comment by zkabelac** [comment]
@poettering  ok - then I'm confused why  systemd  ever bothers to check for it and even report it and return  EEXIST error code  -  why it is validating   borked UUID paths ?

**Comment by poettering** [comment]
@zkabelac systemd exposes block devices under a similar selection of names as udev does via its symlinks. In fact, since we want systemd device unit names to map 1:1 to symlinks on disk, there's actually a bijective mapping in place (modulo the cases where there's ambiguity regarding the symlinks). This is necessary since we process /etc/fstab after all, where people often use UUIDs to identify file systems to mount.

note that we downgraded the log message to DEBUG recently when we hit such a conflict. This is simply because a couple of the /dev/disks/by-xyz links are pretty likely to conflict. Specifically, Microsoft creates all its partitions with a GPT partition label of "Microsoft Data Partition", and hence the /dev/disk/by-partlabel/ links more often conflict than they are not, and that's not really an error. After all, if you label all your partitions the same way, then it's on you, and a bad idea to use them for referencing the partition but still perfectly valid...

**Comment by zkabelac** [comment]
So then I think you still should report error if there is ANY user for such  ambiguous UUID
when there is service for it.
And on the other hand there should be no check & no report if there is no user.

So when I do a 'dd' copy of device with a filesystem it will not lead to log error nor log debug as long as you there is no service (lazy-eval)

But I'm still unsure why defending  udev to randomly change links is -  change of links is 'expected' when I'm adding/removing drives holding them - but looks seriously broken to get same reaction when device is closed....
