### ISSUE TITLE
kdbus breaks session switching

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#308]
On a system using kdbus, rootless X (as used by Gnome 3.16) doesn't get the logind signals it needs to handle session switching properly.

While initialization works properly ("took control of session /org/freedesktop/login1/session/c2" et cetera), X seems to receive neither the pause signals ("got pause for X:X") nor the resume signals ("got resume for X:X") that should get emitted by logind when VT-switching.

As a result, when switching to an active X session, the seat freezes completely.

When using dbus-daemon, things work properly.

systemd 221
xorg-server 1.17.2

**Comment by kaysievers** [comment]
I see the same issue.
(I also can trigger a similar behavior just by using sudo, which starts systemd --user for root)

It does not seem to be related to #307, as it happens when kdbus is running and booted.

**Comment by dvdhrm** [comment]
Indeed, Xorg never gets the ResumeDevice signal, and as such cannot handle key-presses anymore (which prevents session switching).

I suspect this is because ResumeDevice and PauseDevice are directed signals (so unicasts, not broadcasts). This might confuse the bus-proxy..

**Comment by dvdhrm** [comment]
Meh.. so the signal is delivered just fine and even routed through bus-proxyd. Our own handlers work fine, gdm-session-wayland works fine, it's just the xserver which somehow doesn't get the signals.

I'll have to dig deeper..

**Comment by dvdhrm** [comment]
Ok, this is nasty.. CC'ing @smcv and @jwrdegoede for comments.

DBus has this nice feature that you can send signals as unicasts. We use this for systemd-logind as the PauseDevice and ResumeDevice signals should only be directed at the session controller. So far, my knowledge was that all signals are handled the same by dbus-daemon, regardless whether they're unicasts or broadcasts. This is also what we implement in kdbus: if a message is marked as signal, the _receiver_ needs to have a MATCH installed _and_ the _receiver_ must be able to talk to the sender (which matches exactly our policy for broadcasts, which must be marked as signals, otherwise they're rejected).

Now this is actually not what dbus-daemon implements. Instead, dbus-daemon handles unicast-signals just like any other unicast. Only real broadcasts need MATCH rules installed. Furthermore, the default policy of dbus-daemon is to route _all_ signals regardless of the sender and receiver. And this is where it gets nasty: Xorg relies on this hole and never installs matches for PauseDevice and ResumeDevice from logind. Instead, they just rely on those signals to be always routed to them. This works fine with the default system-policy of dbus-daemon, but breaks as soon as this policy changes, or if you use kdbus. With kdbus you really need a MATCH rule installed.

How to fix this: Well, there're 2 issues at hand:

1) Xorg _really_ should install a MATCH rule (and I think the current behavior was just an oversight, Hans?). Relying on the default policy to route all messages is really nasty. Furthermore, Xorg right now does _not_ look at the 'sender' field of the logind messages. Therefore, any dbus client right now can just fake those messages. Given that ResumeDevice includes a file-descriptor in its payload, this is _very_ nasty and allows other local clients to feed arbitrary FDs to Xorg.

2) Even though I think routing all signals by default is nasty, it's how dbus-daemon works. Question is, whether we need to support this in bus-proxy for legacy clients? If we want to support it, we need kdbus to support MATCH rules on destination names. This way, bus-proxy could just install a MATCH for all signals routed to it. However, I'm really not sure this is something we want to support. Maybe we should rather use this inconsistency to find those "misbehaving" clients and fix them. Or am I missing something?

I'll prepare a fix for Xorg and send it to xorg-devel.

Comments welcome!

**Comment by smcv** [comment]
There are two reasons you might not get a message on D-Bus:
- because it isn't directed to you and you aren't matching it
- because the security policy says you shouldn't

They are orthogonal.

Signals are not special for the first reason. The only distinction is between unicast messages to you (you get them), unicast messages to others (you don't get them unless you eavesdrop), and broadcast messages (conceptually, you get them, but as an optimization, they aren't delivered unless you have added a match rule).

Signals _are_ special for the second reason. In principle sending permissions should be based on broadcast/not-broadcast, but unfortunately dbus-daemon's security policy language doesn't have a way to say "is a broadcast", so sending permissions are based on non-signal/signal instead.

> So far, my knowledge was that all signals are handled the same by dbus-daemon, regardless whether they're unicasts or broadcasts.

This is not true; and it has never been true, so I think changing it would be a compat break.

> Only real broadcasts need MATCH rules installed.

Yes.

> 1) Xorg really should install a MATCH rule (and I think the current behavior was just an oversight, Hans?). Relying on the default policy to route all messages is really nasty.

Xorg is not required to add a match rule for unicast signals directed to Xorg's unique or well-known name. dbus-daemon delivers those anyway, just like unicast method calls, and so should kdbus.

> Furthermore, Xorg right now does not look at the 'sender' field of the logind messages.

This, on the other hand, is a bug...

> Therefore, any dbus client right now can just fake those messages.

... because of that. It's vaguely similar to https://security-tracker.debian.org/tracker/CVE-2013-0292 (which is a dbus-glib bug because pam_fprintd was relying on dbus-glib objects to have their documented semantics).

**Comment by dvdhrm** [comment]
@smcv But how is a client supposed to verify the sender of a message? dbus-daemon just passes the unique-name, but this might change due to activation. So to be safe, the client has to subscribe to `NameOwnerChanged` _and_ to the signal _without_ a `sender` match. It cannot match on `sender` as it would be racy, otherwise.

Btw., I think gdbus is still susceptible to spoofing. In the proxy, this is probably needed:

```
- if (proxy->priv->name_owner != NULL && g_strcmp0 (sender_name, proxy->priv->name_owner) != 0)
+ if ((proxy->priv->name && !proxy->priv->name_owner) || (proxy->priv->name_owner != NULL && g_strcmp0 (sender_name, proxy->priv->name_owner) != 0))
```

Otherwise, you can spoof signals if the tracked name does not exist.

Anyway, I looked at a lot of libdbus1 clients now, and nearly all of them are susceptible to spoofing. Also in sd-bus we are (on !kdbus). I really wonder whether we should allow such behavior. I believe you have a better overview here, so I'd appreciate if you could point out how this should be implemented?

I mean, it really sounds problematic to me that you _have_ to watch `NameOwnerChanged` whenever you want to reliably match on signals. This really sounds broken to me.

**Comment by smcv** [comment]
> So to be safe, the client has to subscribe to NameOwnerChanged and to the signal without a sender match.

Yes.

**Comment by smcv** [comment]
Note that I did not design D-Bus, I'm only relating how it has always worked, as far as I understand it as a current maintainer. Several things in D-Bus might be different if we had a time machine and could go back and argue with Havoc a decade ago.

The conceptual model is that match rules are only ever an optimization. Conceptually, a broadcast is received by every process on the bus; but that would be really bad from a performance/scheduling point of view (a "thundering herd" of processes being scheduled to run, deciding they don't actually care anyway and going back to sleep), so as an optimization, there's a filtering/subscription mechanism in dbus-daemon.

/etc/dbus-1/system.conf (soon to be /usr/share/dbus-1/system.conf) says:

```
 <policy context="default">
...
    <allow send_type="signal"/>
```

instead of `<allow send_broadcast="true">`, because there is no syntax for the latter. If someone wants to propose a dbus-daemon patch to add selection by broadcast vs. unicast, I'd be delighted to review it; or if someone can commit to reviewing it in a finite time, I might even write one.

This is also the property that allows kdbus to implement match rules as bloom filters, rather than implementing the (equivalent of the) full match-rule syntax in the kernel: if a process gets slightly more broadcasts than it really wanted, that's a missed opportunity for optimization, not a security flaw.

So, yes, if you want to receive signals from a particular sender, you need to keep track of who (if anyone) is currently that sender.

In practice, many D-Bus services require the signal recipient to track the owner _anyway_, because they have some sort of transient state that goes away with a NameOwnerChanged - for instance, if you have Connections or Transactions or Jobs or something, on seeing NameOwnerChanged("com.example.MyService", ":1.23", anything) you should emit "it went away" notifications for all your client-side proxy objects, because they are not going to be usable any more. Similarly, if objects' object-paths are not guaranteed to be stable between invocations of the service within the same boot (i.e. not a reversible transformation of something that persists between invocations), then client-side code needs to throw away any references to those object paths when the service dies or is atomically replaced.

> Btw., I think gdbus is still susceptible to spoofing

If so, please report a GLib bug.

**Comment by dvdhrm** [comment]
@smcv I'd be willing to review send_broadcast= extensions to send and recv. I looked at the code briefly, but wasn't sure whether this needs to be a tri-state for backwards compat. I mean, we cannot suddenly make the default "false" and no longer match on broadcasts? Ideas? So we'd need something like "send_broadcast=any" or so.

I'm looking into it right now, but if you can come up with an implementation, I'd be more than happy to review it!

**Comment by dvdhrm** [comment]
Hans kindly picked up my xorg patch and sent a pull-request (including some more fixes) to Keith. This should show up in the next xorg-release, and will probably also be backported. Distributions might want to pick these fixes up themselves, if interested.

http://lists.x.org/archives/xorg-devel/2015-June/046718.html

Closing now, as the kdbus issue is fixed.
