### ISSUE TITLE
AI: ramp up cgroup v1 deprecation

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#30852]
We should make it hard to boot in cgroupv1 mode, i.e. refuse booting unless some magic option is specified to get it anyway.

**Comment by ohnoov** [comment]
Breaking boot completely when the warning delay alone would have been more than enough to raise the issue is an asshole move. There are many classes of devices where recovery is not easy, because you can't easilly edit boot arguments after system fails to boot, or because they are remote.

**Comment by razaqq** [comment]
thanks for making me spent hours trying to debug this, really enjoyed it

**Comment by ohnoov** [comment]
> thanks for making me spent hours trying to debug this, really enjoyed it

Yeah, that's another aspect. Boot failure was completely silent in my case. Nothing in the console. After removing "quiet" kernel command line option, only extra message was message from systemd that boot was halted, no reason given. I had to add debug flags to kernel command line to see some actual symptoms being reported. And the final cause of the issue was systemd itself mounting cgroup-v1 (from initramfs) and then complaining it's not supporting it (when running from rootfs).

That's something to be improved, too, if this change is meant to inform users to change something, instead of just to piss them off.

**Comment by YHNdnzj** [comment]
> Breaking boot completely when the warning delay alone would have been more than enough to raise the issue is an asshole move. There are many classes of devices where recovery is not easy, because you can't easilly edit boot arguments after system fails to boot, or because they are remote.

Well, interestingly enough, https://github.com/systemd/systemd/issues/32998 has a completely different idea. Sorry, but we're deprecating a functionality here, and in such cases there's simply no way to please everyone. And the reason why we took this approach is exactly that it's noticeable by everyone yet the functionality is preserved for a while longer, giving people time to switch to cgroup v2.

We declared the deprecation initially in v253, and the NEWS file is very clear at it. It seems none of that actually helped to remind you to upgrade your setup, hence a choice must be made. If the recovery is not easy, I'd really suggest not upgrading those devices deliberately without going through changelog first.

**Comment by ohnoov** [comment]
Normal OS users don't read release notes for all SW before running pacman -Syu. Actually, I think nobody does that.

**Comment by poettering** [comment]
Normal OS users do not manually force the system into cgroupv1 mode either!

Please understand that support for cgroupv1 is going to go away entirely very very soon now. I think you should see the good in our slow ramp up of warnings here: we didn't completely break this for you right-away, but give you some time where we finally got you to notice that this is coming, so that you can for the moment set the kernel cmdline option, and then take your time to fix this properly by switching to cgroupv2 now.

**Comment by ohnoov** [comment]
I did not do any forcing.

**Comment by ohnoov** [comment]
It's a situation of old systemd running from initramfs using it's default config, and newer systemd from rootfs crashing the system when it stopped liking the old systemd defaults. Simple as that. The user here doesn't care about cgroups at all, let alone their versions. There were no prior warnings, because both systemds were running with default configuration, and message *along* with an intentional crasher was added only in this change in the latest systemd version and both at once. No grace period.

Edge case, I guess.

**Comment by Californian** [comment]
FYI I've already seen others in a similar, "we don't pay attention to cgroups/systemd release notes, just use the defaults" situation just add the `...FORCE` flag to bypass this. They will then obviously run into the problem again when cgroups v1 are removed completely; I think it would be useful to also mention here in more detail how to actually resolve the underlying issue (e.g. the commands to update initramfs via live media). I would do so myself, but I'm closer to that group of users than the ones commenting here so I wouldn't want to mislead with commands that are going to impact others' systems negatively.

**Comment by ayunami2000** [comment]
I JUST installed ArchLinuxARM on my Acer Chromebook R13. It worked until I ran `pacman -Syu` and rebooted. Now it does not boot due to this. How the hell do I add this kernel parameter on a _Chromebook_?!

**Comment by ohnoov** [comment]
> @ohnoov It's unfortunate that you hit this. That's not how the warning meant to be (i.e. old PID1 setting up v1 and new one breaking).
> 
> > Edge case of not updating initramfs often enough, I guess.
> 
> It seems that [pacman doesn't automate that](https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/blob/master/libalpm/hooks/90-mkinitcpio-install.hook?ref_type=heads#L15). I'd suggest adding a hook there to keep systemd binaries in sync. (Also, what was the version within the initrd? [This](https://gitlab.archlinux.org/archlinux/packaging/packages/systemd/-/commit/d0f176adf66205e864e85bf34cdccb3329d308ab#9b9baac1eb9b72790eef5540a1685306fc43fd6c_122_120) suggests it must have been <=v247.)

It was quite old. Probably ~3 years old. I don't think I regenerated it ever since I set up full disk encryption on my notebook. I use kernel build without modules, so I don't normally need to update initramfs pretty much ever. (except this time :)) and prefer it that way due to stability/reliability.

**Comment by ohnoov** [comment]
> I JUST installed ArchLinuxARM on my Acer Chromebook R13. It worked until I ran `pacman -Syu` and rebooted. Now it does not boot due to this. How the hell do I add this kernel parameter on a _Chromebook_?!

ArchLinuxARM-oak-latest.tar.gz is from [01-Mar-2023](http://fl.us.mirror.archlinuxarm.org/os/) so that suggests just a year old systemd in initramfs will result in this behavior.

**Comment by YHNdnzj** [comment]
> > I JUST installed ArchLinuxARM on my Acer Chromebook R13. It worked until I ran `pacman -Syu` and rebooted. Now it does not boot due to this. How the hell do I add this kernel parameter on a _Chromebook_?!
> 
> ArchLinuxARM-oak-latest.tar.gz is from [01-Mar-2023](http://fl.us.mirror.archlinuxarm.org/os/) so that suggests just a year old systemd in initramfs will result in this behavior.

Arch Linux switched the default to v2 long before that. With mkinitcpio I seriously doubt that systemd actually runs in the initramfs. Arch defaults to busybox-based init after all.

Please provide your `/etc/mkinitcpio.conf` and `/proc/cmdline`.

**Comment by catalinsanda** [comment]
@YHNdnzj  - Have same issue with Arch Linux ARM on an Odroid XU4 installed some time ago, but kept up to date.
The boot messages just mentioned "systemd[1]: Freezing execution.", which is very generic and didn't provide any clue to the underlying issue. Running out of options I've hooked the serial console and there I saw this: "[!!!!!!] Refusing to run under cgroup v1, SY… specified on kernel command line." which lead me to this page.

**Comment by catalinsanda** [comment]
Okey, leaving this here for those interested on how to fix this on an Arch Linux, probably not the best place, but it ranks pretty up on Google, so here it goes:

I had `systemd.unified_cgroup_hierarchy=0` added to the kernel params in boot.txt. This was done 3 or so years ago, and if I remember correctly, I've done it to make docker run.

Anyway, the fix is to edit `boot.txt`, remove the `systemd.unified_cgroup_hierarchy=0`, run a `./mkscr` to make `boot.scr` and then reinstall the kernel with a `pacman -S linux` which will rebuild the initial ramdisk.

Interestingly enough, now docker runs without the cgroup option.

**Comment by archisman-panigrahi** [comment]
> > 
> 
> ArchLinuxARM-oak-latest.tar.gz is from [01-Mar-2023](http://fl.us.mirror.archlinuxarm.org/os/) so that suggests just a year old systemd in initramfs will result in this behavior.

@ohnoov I ran into the same issue with the same chromebook image (I installed the image, updated, and rebooted, and ran into the issue). Is there a way to fix it now?

**Comment by martin-ueding** [comment]
I've just upgraded to Fedora 41 and hit this issue. Since it was released this Monday, more people might be coming in with the same issue.

The option `systemd.unified_cgroup_hierarchy=0` must have been set via NVIDIA Docker. Solving it is quite straightforward:

1. Press `e` in GRUB to edit the command line, remove the `systemd.unified_cgroup_hierarchy=0` option and boot the system.
2. Edit `/etc/default/grub` and remove `systemd.unified_cgroup_hierarchy=0` from the line with `GRUB_CMDLINE_LINUX`.
3. Run `sudo grub2-mkconfig -o /boot/grub2/grub.cfg` to generate a new config.

**Comment by archisman-panigrahi** [comment]
> vbutil_kernel --repack

@ayunami2000 Can you please share more details? Since the system refuses to open at all, how do you run this command? And how/what file do you flash to the boot partition?

**Comment by ayunami2000** [comment]
> > vbutil_kernel --repack
> 
> @ayunami2000 Can you please share more details? Since the system refuses to open at all, how do you run this command? And how/what file do you flash to the boot partition?

It was a while ago, but as far as I can remember, I could still boot to chrome os and used the terminal there to run that command and flash. I was booting off of an external flash drive. I do not remember the other details except that chrome os requires fancy shenanigans to boot stuff like this, and so that's why this was even possible to patch.

**Comment by archisman-panigrahi** [comment]
@ayunami2000 What are the arguments of `vbutil_kernel --repack`?

**Comment by ayunami2000** [comment]
> @ayunami2000 What are the arguments of `vbutil_kernel --repack`?

I don't remember but I think you should be able to Google it, hopefully.

**Comment by nroach44** [comment]
Can this be amended to either kill/exit systemd and trigger a panic (allowing CONFIG_PANIC_TIMEOUT= to take us back to the bootloader), or reboot the system after a timeout?

I'm doing "dumb shit" on a device with an old (4.2) vendor kernel, and while I've worked around this, I had to manually remove power to the system physically to recover.

**Comment by Werkov** [comment]
What version are you one?
Doesn't d0ab0e5fa5434cac67e51dbeb1d873c6ac6f20cd fix that?

**Comment by nroach44** [comment]
Ah, yes it does. I've got 256.4 currently because my buildroot tree is 2024.08.2, but it's been bumped to .7 recently and I haven't updated it, thanks!
