### ISSUE TITLE
Only sync rtc time when device appears

### ISSUE THREAD

**Issue by hadess** [systemd/systemd#3091]
The troll at:
http://www.hackable.fr/?p=752
mentions that, when using systemd on a Raspberry Pi, which doesn't have a builtin rtc, it's possible that systemd will try to reload the time from the RTC device before the external RTC module is available.

Instead of syncing the rtc on startup, systemd should wait until rtc0 becomes available.

Let me know if you need information from there above and beyond what a Google Translate of the page would offer. Happy to get a Raspberry Pi and RTC module to a developer that's interested in fixing that.

**Comment by poettering** [comment]
systemd doesn't load the time from the RTC at all. That's the kernel's job, and it's really the right place, so that the clock is properly initialized before the first userspace code runs, so that logs can be properly attributed from the first moment on, and userspace programs don't have to deal with jumping clocks.

In general, i am pretty sure RTC drivers should be compiled into the kernel, so that the kernel can do this. Involving userspace here sounds quite wrong to me. Or if people really want their RTC as a kernel module, then they should add the hwclock invocation manually, but systemd is really not the place for this glue...

Sorry, but I think this is out of focus for systemd. People are welcome to do this manual stuff, but then they should do it in full, and carry the hwclock invocations themselves. We have no RTC writing code in systemd (outside of the timedated mechanism that is), and I am pretty sure that should stay that way.

Sorry if that's disappointing.

**Comment by sdgathman** [comment]
So what are you supposed to do when there is no rtc at all?  The kernel can't do it in that case.  Well it could.  Using a timestamp from the rootfs superblock might be good.  Set the system time from rootfs when system time is a very small value.

Meanwhile, the earliest I've been able to hook setting system time (from rootfs) is just after switchroot.

**Comment by poettering** [comment]
@sdgathman we already touch a file in /var each time we get a ntp fix and during early boot we use it to bump the time back to that time, if we notice the time is not initialized yet. We also touch that file at shutdown, so that time stays monotonic.

**Comment by sdgathman** [comment]
That's perfect.  That doesn't seem to happen in Fedora 23 (systemd-222: Pignus on the rasp pi 0, for instance), so maybe it is a recent addition.

**Comment by poettering** [comment]
well, that logic is implemented with timesyncd. If you use Fedora that's not the default NTP implementation you are using.

**Comment by poettering** [comment]
well, that logic is implemented with timesyncd. If you use Fedora that's not the default NTP implementation you are using.

**Comment by trixymoon** [comment]
I like the tag "not-our-bug"... well, nevertheless, the problem is still there..

So, here a workaround to this problem:

<pre>
nano /etc/udev/hwclock-set
</pre>

put a "#" before the lines:

<pre>
#if [ -e /run/systemd/system ] ; then
#    exit 0
#fi
</pre>

The RTC kernel module is loaded by the file <code>/boot/config.txt</code> in my case the rtc is a maxim ds1307, so for completeness of information, this is my configuration

<pre>
# RTC Maxim ds1307 on I2C bus
dtparam=i2c_arm=on
dtoverlay=i2c-rtc,ds1307
</pre>

remember to purge fake-hwclock
<code>apt-get remove --purge fake-hwclock</code>

Tested on raspian Jessy

**Comment by sdgathman** [comment]
I will note that even on a PC system that *does* have a hwclock, there is occasionally a situation where the battery is dead, and having system time not monotonic when booting with a dead battery can cause nasty problems.  If this is truly a Fedora bug, I'll see if I can get it fixed.
