### ISSUE TITLE
[RFE] Direct numa support outside of numactl package

### ISSUE THREAD

**Issue by CrackerJackMack** [systemd/systemd#3097]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 229
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
### Proposal

Replicate or integrate [numactl ](http://oss.sgi.com/projects/libnuma/) functionality into systemd service directives.  Cgroups have similar options but not direct numa equivalents which are [specific kernel calls](https://www.kernel.org/doc/Documentation/vm/numa).
### Current behavior
- numactl (or equivalent package) has to be install
- invoked daemon is executed via /usr/sbin/numactl 
### Desired behavior
- Set numa directives in systemd service file

**Comment by poettering** [comment]
We already expose sched_setaffinity() via CPUAffinity=. What else do you need specifically?

**Comment by CrackerJackMack** [comment]
CPUAffinity only sets a portion of the numa bindings.  Numa is meant to compliment `cpu_setaffinity()` with memory policies and CPU policies. 

### NUMA recoures
- [libnuma intro](http://developer.amd.com/wordpress/media/2012/10/LibNUMA-WP-fv1.pdf) [WARNING:pdf] by AMD that isn't a horrible read.
- A [intro to NUMA pdf](https://www.dcl.hpi.uni-potsdam.de/teaching/numasem/slides/NUMASem_Kernel_APIs.pdf) slide deck as well.
-  Installing numalib-dev will give all the man pages necessary (`man -k numa`)

### More specifically requested features:
- `set_mempolicy()` equivalent 
- `mbind()`

These aren't very easy to use (or require a lot of NUMA knowledge) whereas numalib has a convenience method known as `numa_run_on_node()`.

I think it might be apropos to implement the `set_mempolicy` and `mbind()` syscalls to complement the already existing CPUAffinity directive.

**Comment by poettering** [comment]
OK, sounds like an OK thing to add. Note though given that none of the core developers are NUMA people nor own NUMA hardware (at least to my knowledge) this is most likely a feature we need a contributed patch for.

**Comment by CrackerJackMack** [comment]
Understood.  Thank you for approving feature.

**Comment by gmarkey** [comment]
Posted $250 [bounty](https://www.bountysource.com/issues/33246470-rfe-direct-numa-support-outside-of-numactl-package) for this

**Comment by berrange** [comment]
@poettering FYI KVM can emulate NUMA hardware so you can provision a guest with multiple NUMA nodes and expose arbitrary amounts of memory & CPUs in each virtual NUMA node in your guest, so there's no need for real hardware to be able to test this.

**Comment by bobrik** [comment]
Linux itself can emulate NUMA: http://cateee.net/lkddb/web-lkddb/NUMA_EMU.html

**Comment by grooverdan** [comment]
`CPUAffinity=` and a NUMA node list would be easier that an a CPU list and I suspect a `node:{num}` as part of this list would be a good first start.

`mbind` isn't useful as it applies to specific memory areas which can't be done the service manage as it doesn't allocate on behalf of the service however `set_mempolicy` is inherited by spawned processes so encapsulating its features seems the plausible way.

From `set_mempolicy` the MPOL_BIND, MPOL_INTERLEAVE are obviously different to the MPOL_DEFAULT, MPOL_PREFERRED and MPOL_LOCAL which all read remarkably similar in the man page.

What good cases are there for nodes different to CPUAffinity?

For those subscribed here which features are you likely to use?

https://lwn.net/Articles/717797/ seems to describe some shortcomings, mostly around changing CPU affinity however in the systemd context, its almost implicit your doing these settings because the service doesn't.

**Comment by msekletar** [comment]
@CrackerJackMack I think we can close this issue since we now have NUMAPolicy option.

**Comment by grooverdan** [comment]
Thanks for adding [NUMAPolicy](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#NUMAPolicy=) and [NUMAMask](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#NUMAMask=).

A `CPUAffinity=NUMA` would be a useful extension to align `CPUAffinity` to the same node as memory.

**Comment by CrackerJackMack** [comment]
For the requested feature, it does appear to be fixed via #12764

@grooverdan request is valid, but I think would be best addressed in another RFE as I can't speak to the complexities of implementing it as I am not a systemd developer.
