### ISSUE TITLE
sd_bus_error_set_errno doesn't return 0 on success

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#310]
`sd_bus_error_set_errno` currently returns it's argument.
There is no way to know if it failed.

This also applies to the other `sd_bus_error` `errno` functions

**Comment by zonque** [comment]
That's intentional and similar to what `log_full_errno()` does. The function itself cannot fail, and the way it is implemented allows the call site to return from a function and set the bus error at the same time. See `src/machine/machined-dbus.c` for examples.

**Comment by poettering** [comment]
@daurnimator you invoke sd_bus_error_set_errno() in order to propagate an error to a caller. Now, if that fails, what options do you have? You need to return an error, but you cannot, since the call you wanted to use to return it was the one that failed.

hence, sd_bus_error_set_errno() will never fail: if it can it will return the converted error you passed in, and if it can't (only reason that could make this fail is OOM...) it will return a canned OOM response instead, so that it actually _can_ always do something, and return an error that actually happened, even though it might not be the one you asked for in the worst case...

As @zonque said, it will also always return the error you pass in, which is useful for writing it in a "return" line, to keep the sources brief.

**Comment by daurnimator** [comment]
> @daurnimator you invoke sd_bus_error_set_errno() in order to propagate an error to a caller. Now, if that fails, what options do you have? You need to return an error, but you cannot, since the call you wanted to use to return it was the one that failed.
- depending on the error, e.g. `ENOMEM` I can run a garbage collection and try again
- not send the error (sending program has to assume the worst; e.g. they always need to consider that your program segfaulted)

But there are other errors. e.g. https://github.com/systemd/systemd/blob/02e55363f17065375823cc71f73799d0ceb6764c/src/libsystemd/sd-bus/bus-error.c#L446
You can't distinguish if you've accidentally reused an error object (without freeing) if you wanted to set it to `EINVAL`...

> As @zonque said, it will also always return the error you pass in, which is useful for writing it in a "return" line, to keep the sources brief.

I'm binding this for non-C... this doesn't matter for my use case.

**Comment by poettering** [comment]
> But there are other errors. e.g. https://github.com/systemd/systemd/blob/02e55363f17065375823cc71f73799d0ceb6764c/src/libsystemd/sd-bus/bus-error.c#L446
> You can't distinguish if you've accidentally reused an error object (without freeing) if you wanted to set it to EINVAL...

Well, but that's a programming error, not a runtime error. We generally check for programming errors with assert_return(), so that they are logged loudly. It's really nothing I'd care too much about, because assert_return() errors should never happen when the library is used properly.

The focus in sd-bus is on making things nice to use from C, but only secondarily to make things wrappable (under the assumptions, that the hacker who wraps things is more knowledgeable than the general user of the library), hence I'd really like to leave the current API the way it is. My recommendation would hence be when wrapping things for cases like yours, to first check if the error is ENOMEM. If so, then what sd_bus_error_set_errno() returns is always right. Otherwise, if the error is org.freedesktop.DBus.Error.NoMemory afterwards then the translation failed. The only reason the function can fail is OOM after all (ignoring the programming error thing mentioned above). We should probably document this behaviour and recommendation so that it becomes official API, so that you can rely on it.

**Comment by daurnimator** [comment]
> Well, but that's a programming error, not a runtime error. We generally check for programming errors with assert_return(), so that they are logged loudly. It's really nothing I'd care too much about, because assert_return() errors should never happen when the library is used properly.

It still means that improper use can't be detected...

> first check if the error is ENOMEM. If so, then what sd_bus_error_set_errno() returns is always right. Otherwise, if the error is org.freedesktop.DBus.Error.NoMemory afterwards then the translation failed. The only reason the function can fail is OOM after all (ignoring the programming error thing mentioned above). We should probably document this behaviour and recommendation so that it becomes official API, so that you can rely on it.

Indeed, that would be good to document; that would solve the issue short term.

---

I don't love the solution though. Why couldn't you stick with the nice general policy in the rest of libsystemd that everything returns < 0 on failure?
The "nice to use from C" could easily be implemented as a higher level function/macro on top.

**Comment by poettering** [comment]
> It still means that improper use can't be detected...

Well, it can, it's logged.

> Indeed, that would be good to document; that would solve the issue short term.

I added documentation for this behaviour in #348.

> I don't love the solution though. Why couldn't you stick with the nice general policy in the rest of libsystemd that everything returns < 0 on failure?

Well, we try to stay uniform for calls that generate errors, but these are calls that process errors, and special rules hence apply.

I can see that this isn't nice, but I still sure that easy-of-use should sometimes trump uniformity...
