### ISSUE TITLE
Can not monitor, if a non-readable disk is inserted in CD/DVD device

### ISSUE THREAD

**Issue by poidi** [systemd/systemd#31010]
### systemd version the issue has been seen with

239

### Used distribution

Alma Linux 8.9

### Linux kernel version used

4.18.0-513.9.1.el8_9.x86_64

### CPU architectures issue was seen on

x86_64

### Component

udevadm

### Expected behaviour you didn't see

As of CentOs 6.9 the udev was reacting to every little "move" in the CD/DVD Tray - that is, if it was opened, closed, if the CD was starting spinning,... 

Everything was found in the udev-events (watchable via "udev monitor" - and executeable via rules)

But now in AlmaLinux 8.9 i only get udev events, if a medium with an readable filesystem is ready to mount.

Our headless appliance is now in the situation that if you insert a CD upside-down or a heavily scratched or an empty (pristince writeable DVD) into the slot-in - there is no way that i can react on that event - so the user has to eject it manually.

### Steps to reproduce the problem

Install AlmaLinux 8.9.

Insert a CD/DVD with no filesystem, or a heavily scrachted one into the device

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by poettering** [comment]
(and frnakly, this is almost certainly a kernel issue, not a systemd one)

**Comment by poidi** [comment]
thanks for the elaboration! sorry, if i got the wrong channel
