### ISSUE TITLE
System startup hung in dracutpre-pivot and cleanup hook

### ISSUE THREAD

**Issue by linzhanglong** [systemd/systemd#31132]
### systemd version the issue has been seen with

systemd 243

### Used distribution

centos

### Linux kernel version used

4.18.0-372.19.1.49.po1.x86_64

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

System startup hung in dracutpre-pivot and cleanup hook。

[OK] Started File System Check on /dev/disk/by-label/vtproot
[OK] Mounting /sysroot ...
[OK] Mounted /sysroot .
[OK] Reached target Initrd Root File System.
         Starting Reload Configuration from the Real Root...
_**[OK] Stopped Reload Configuration from the Real Root.**_
[OK] Reached target Initrd File Systems.
[OK] Stopped target Initrd Root File System.
[OK] Reached target Initrd Default Target.
        Unmounting /sysroot ...
[OK] Unmounted /sysroot.
         Starting dracut pre-pivot and cleanup hook...
[OK] Stoppped File System Check on /dev/disk/by-label/vtproot.
**[OK] Started dracut pre-pivot and cleanup hook.**

### Unexpected behaviour you saw

System startup hung in dracutpre-pivot and cleanup hook，but i think because of :
Stopped Reload Configuration from the Real Root

### Steps to reproduce the problem

At that time, it was simulating an IO failure, but the failure was recovered, yet it still got stuck.

**Comment by poettering** [comment]
/
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
