### ISSUE TITLE
Error when trying to build for i386

### ISSUE THREAD

**Issue by stigl-cc** [systemd/systemd#31169]
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu(newest) and Debian

### Linux kernel version used

newest(on github codespace and on docker container)

### CPU architectures issue was seen on

aarch64

### Expected behaviour you didn't see

So, I was trying to build systemd for i386 on the x86_64 architecture.

Expected it to build just fine, without hopefully any errors.

### Unexpected behaviour you saw

I have installed i386 gcc, and then when I tried to configure it using
`./configure ARCH=i386`
it did a very weird error like this:

```
$ ./configure ARCH=i386
+ exec meson setup build ARCH=i386
ERROR: Neither directory contains a build file meson.build.
```

### Steps to reproduce the problem

`sudo dpkg --add-architecture i386`
`apt update`
` sudo apt install gcc:i386`
Clone the repo...
`./configure ARCH=i386`
Reproduced!

**Comment by mrc0mmand** [comment]
We don't use autotools (since ages ago), the `configure` script is a _very_ thin convenience wrapper around `meson setup` (as you can see from the script's output). If you want to build for a different architecture, you'll have to do it the *meson* way, i.e. https://mesonbuild.com/Cross-compilation.html
