### ISSUE TITLE
`Firmware Age:*.` doesn't adhere to ISO 8601 duration format, despite `timedatectl`  formatting timestamps as such.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [systemd/systemd#31167]
### Component

`hostnamectl`

### Is your feature request related to a problem? Please describe

If I set my locale to `om_ET.UTF-8`, which uses ISO 8601 for both dates (YYYY-MM-DD) and times (HH:mm:ss) the duration value returned by `hostnamectl status`:

> Firmware Age: 9month 1w

...doesn't adhere to that format — see undermentioned. Yet, all other commands return correctly formatted date and time values, albeit missing the time delimiter (T).

### Describe the solution you'd like

It should <q>PM9W1</q>, per https://en.wikipedia.org/wiki/ISO_8601#Durations.

### Describe alternatives you've considered

I haven't been able to think of any.

### The systemd version you checked that didn't have the feature you are asking for

https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/systemd-254.8-3.1.x86_64.rpm

**Comment by poettering** [comment]
systemd systematically uses the syntax described in systemd.time(5) to denote times and timespans. And this is explicitly chosen to be locale independent. We want that our time spans can be written into unit files and passed around and do not lose their meaning. 

Hence, sorry, but I don't think for basic system components we should deviate from that, but strictly generate a format that we can also parse again.

(There's also the basic fact that ISO durations are simply illegible to anyone who might not be a iso-time-nerd. It's just a bad standard at that).

Sorry if that's disappointing.

I think more high-level UI tools should show time durations in the local locale, but the low-level systemd tools should really stick to the time format we universally use.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/systemd/systemd/issues/31167#issuecomment-1921792764

@poettering, if consistent programmatic consumption of output is the primary concern (ignoring that dbus seems to me a better choice for that) all date-affected values which `timedatectl status` returns are affected by the locale, like:

> ```.txt
> PS /home/RokeJulianLockhart> timedatectl status
>                Local time: Thu 2024-02-01 17:07:35 GMT
>            Universal time: Thu 2024-02-01 17:07:35 UTC
>                  RTC time: Thu 2024-02-01 17:07:36
> ```

**Comment by poettering** [comment]
Our formatting of timestamps might be a profile of ISO 8601 by convenient accident, but it for example doesn't use the "T" and "Z" stuff that RFC 3339 defines for example for a reason: to make this somewhat reasonably readable for regular folks.

I am sorry, but I think the ISO spec is simply not a very good spec, because it results in unreadable strings. For example, if I give a string such as "PM9W1" to my mom, and ask her what it means, shell be just confused. If I give her a string such as "9month 1week" she'll immediately know what this means, without having to read (or buy) any spec. I mean, for ffs *I* don't even know what PM9W1 means...

And sorry, but yes, concerncs about uniformity and readability trump almost everything here.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/systemd/systemd/issues/31167#issuecomment-1921830961

I don't quite understand, but I'm thankful for the responses, @poettering.
