### ISSUE TITLE
Build Error with gcc below-8

### ISSUE THREAD

**Issue by Sangeetha-E** [systemd/systemd#31191]
### systemd version the issue has been seen with

255

### Linux kernel version used

5.10.100

### CPU architectures issue was seen on

None

### Additional program output to the terminal or log subsystem illustrating the issue

Encountered a build issue while using gcc below version 8. Below are the error logs:

Error logs:
```
../src/shared/varlink-idl.h:117:52: error: expected expression before ',' token
                 .fields = { __VA_ARGS__ __VA_OPT__(,) {}}, \
```

It seems that the __VA_OPT__ option is causing the problem, which was introduced in gcc-8.0.0 according to the GCC C++ Status.

Ref:

https://gcc.gnu.org/projects/cxx-status.html#cxx20                     
                                                                                                        
https://github.com/systemd/systemd/commit/e50b2a93d66eff9b41999d38b8ed5eb647e2d74c
```

**Comment by mrc0mmand** [comment]
I think we should just bump the [current](https://github.com/systemd/systemd/blob/660be5c5af54ccbe8c7fd74d92b4c8fe04e8adfd/README#L220C13-L220C15) gcc baseline 4.7 to 8.1, since we use `__VA_OPT__` in multiple places, and getting around it would be really painful. Anything below 8.1 is just way too old.
