### ISSUE TITLE
cryptenroll: document $NEWPIN env var

### ISSUE THREAD

**Issue by flixman** [systemd/systemd#31196]
### systemd version the issue has been seen with

255

### Used distribution

Arch

### Linux kernel version used

6.7.3-arch1-1

### CPU architectures issue was seen on

None

### Component

systemd

### Expected behaviour you didn't see

Following the documentation: in case there is a wish to use PCRs + PIN to unlock LUKS, the flag to be used is ```--tpm2-with-pin=yes``` and then a pin will be asked. However, this is not handy when generating UKI automatically. Checking the source code for systemd-cryptenroll I have noticed that there is the possibility to use an environment variable NEWPIN to provide the pin, thus enabling automated enrolls... but there is no mention to this variable in the documentation.

Is this env variable expected to go away soon, and thus is not mentioned on the documentation (so, should not be used), or is the documentation outdated? If so, I will prepare a PR to get it fixed.

**Comment by poettering** [comment]
NEWPIN was mostly added for debugging purposes, it's used in our test cases to automate testing. Passing around secrets via env vars is a terrible idea, since they are propagated down the process tree by default, they are trivially resolved in shell scripts and so on, and all that makes them really bad for propagating secrets. Hence we don't document that right now.

you can pass in the pw already via systemd credential, via kernel keyring, and via the pw query api. we  probably should document that better though

**Comment by flixman** [comment]
@poettering, As this is the first time I am using systemd-creds I have gone through the code on ```cryptenroll/cryptenroll-tpm2.c```, enroll-tpm2 function, that uses ```get_pin`` (in that same file), that finally executes ```getenv_steal_erase("NEWPIN", &pin_str);```, which does not take the contents of ```$CREDENTIALS_DIRECTORY/NEWPIN``` or similar (but instead the one of ```NEWPIN``` as it comes).

Does mean I need to load into ```NEWPIN``` the contents of the file I get through ```$CREDENTIALS_DIRECTORY/NEWPIN```? Should I create a PR in ```get_pin``` to check if ```$CREDENTIALS_DIRECTORY/NEWPIN``` exists and, if so, load it from there preferably?

**Comment by poettering** [comment]
So #31400 documents the various cryptenroll creds. It doesn't document NEWPIN, but I am still not convinced we should.

hence let's close this.
