### ISSUE TITLE
Systemd - networkd/resolved failed to start when root (/) permission set to rwx--x--x

### ISSUE THREAD

**Issue by zepala** [systemd/systemd#31378]
### systemd version the issue has been seen with

252

### Used distribution

Debian Bookworm

### Linux kernel version used

Debian 6.1.76-1 (2024-02-01)

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd, systemd-resolved, systemd-timesyncd

### Expected behaviour you didn't see

Protect the root filesystem by setting permissions to 711 (rwx--x--x) on /

### Unexpected behaviour you saw

Network and Resolve failed to start

### Steps to reproduce the problem

chmod 711 /
then reboot

### Additional program output to the terminal or log subsystem illustrating the issue

systemd-networkd[528]: Failed to connect to bus: Permission denied
systemd-networkd[528]: Could not set up manager: Permission denied
systemd[1]: Failed to start Network Configuration.
systemd[1]: Failed to start Network Configuration.
systemd-timesyncd[537]: Failed to connect to bus: Permission denied
systemd-timesyncd[537]: Could not connect to bus: Permission denied
systemd-resolved[536]: Failed to connect to system bus: Permission denied
systemd-resolved[536]: Could not create manager: Permission denied

Tested on an up to date archlinux too, same behavior

_No response_

**Comment by yuwata** [comment]
Sorry, such configuration is not supported, as you can see in the log message you provided, these services need bus connection.

**Comment by zepala** [comment]
The bug happens when setting root mode to 711, then systemd can't connect to DBus (Which is started anyway). If i put back / to 755, the problem disapear.

**Comment by daniel-leong** [comment]
> The bug happens when setting root mode to 711, then systemd can't connect to DBus (Which is started anyway). If i put back / to 755, the problem disapear.

may i know how did you solve your case? 
i have no idea how to optimize root permissions...

`ls -ld /
drwxr-xr-x 27 root root 4096 Feb  7 06:57 /`


may i know if your error messages are same as mine? : 
`Feb 07 08:27:31 instance-20250119-1907 systemd[1]: Starting systemd-networkd.service - Network Configuration...
Feb 07 08:27:32 instance-20250119-1907 systemd-networkd[2726115]: Failed to connect to bus: Permission denied
Feb 07 08:27:32 instance-20250119-1907 systemd-networkd[2726115]: Could not set up manager: Permission denied
Feb 07 08:27:32 instance-20250119-1907 systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=1/FAILURE
Feb 07 08:27:32 instance-20250119-1907 systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Feb 07 08:27:32 instance-20250119-1907 systemd[1]: Failed to start systemd-networkd.service - Network Configuration.
Feb 07 08:27:32 instance-20250119-1907 systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 5.
Feb 07 08:27:32 instance-20250119-1907 systemd[1]: systemd-networkd.service: Start request repeated too quickly.
Feb 07 08:27:32 instance-20250119-1907 systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
Feb 07 08:27:32 instance-20250119-1907 systemd[1]: Failed to start systemd-networkd.service - Network Configuration.`

now i dont dare to restart server, 
in my thought, since the networkd service unable to be started, 
it might not able to get online by itself after restart.
therefore i worry i will lost this VPS because...

hope somebody can share self-help solution.
