### ISSUE TITLE
Why can't systemd-nspawn just use `nsenter` for non-systemd inferiors?

### ISSUE THREAD

**Issue by o11c** [systemd/systemd#3144]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian

---

I'm using `systemd-nspawn -b` to test my software with various distros, including some that predate systemd. For those systems, it is documented that login access cannot be provided if the container's init is not systemd. However, running the following command appears to be equivalent to what systemd-nspawn provides:

`nsenter -t ${pid of container init} -r -w -i -m -p -u login`

and the PID is the direct child of systemd-nspawn so it knows it sooner than I can look it up.

If there is some disadvantages to the `nsenter` method, it would be reasonable to keep it behind some flag.

**Comment by poettering** [comment]
Well, there are a variety of reasons that an "nsenter" login is problematic. First of all, the protocol "login" uses is more complex than just invoking it. It expects an entry in utmp/wtmp it will then update. It's normally the init system that creates that entry (in systemd, this is exposed by UtmpId= in the service unit file), but if you don't run it from one it will be missing. Then, the process that joins the container's namespace is really weird: it has a PPID of 0, something that normally only PID 1 has... As such it better shouldn't stay around for good in the container. Then, the process you created that way due to this lives entirely outside of any life-cycle tracking of the init system in the container, i.e. is not cgroup'ified or anything like that. It will inherit the process attributes from outside the container, and not have the ones from inside the container applied (process attributes means a lot: rlimits, various prctl bits, selinux creds, env vars, ... pretty much anything that is stored or referenced from a struct task_struct in the kernel).

Now, this doesn't mean that in many cases the nsenter stuff can work fine, in particular if you are careful that you invoke it from a sanitized environment, but this is still nothing I want to support in nspawn natively, because it is necessarily hackish and "alien" to the system inside of the container.

That shouldn't stop you from using nsenter likes this if it works for you, it's just one thing using something hackish like that locally, and supporting this officially. 

The supported ways for login in nspawn/machined don't have these problems generally (i.e. machinectl shell, machinectl login, and the login prompt shown on the container console in nspawn by default by systemd) don't suffer by these problems because the login process for them is always forked off PID 1 in the container, managed by the init system, and thus managed and controlled by the container itself.

Note that on sysvinit based systems you can manually assign a login prompt to the container console too. Simply edit inittab and duplicate the usually getty lines for "tty1", "tty2", "tty3" for "console" and comment the former. That pretty much exactly the same effect as what happens if systemd is run in the payload, except that systemd does this automatically, and doesn't require explicit configuration.

Closing this now, since I am very convinced that this has no place in nspawn. Sorry, but I hope this makes some sense.

**Comment by o11c** [comment]
Thanks for the great writeup and workaround. At least now it's documented _somewhere_.

Note that on upstart-based systems, I had to instead edit `/etc/init/console.conf` to remove the second half of `start on stopped rc RUNLEVEL=[2345] and container CONTAINER=lxc`.
