### ISSUE TITLE
Put time limit on systemd-tmpfiles-setup by default

### ISSUE THREAD

**Issue by marekrost** [systemd/systemd#31641]
### Component

systemd-tmpfiles

### Is your feature request related to a problem? Please describe

I have just waited 20 minutes for my computer to boot.

### Describe the solution you'd like

There should be a limit on how long the job can run during boot.
- Let's say 3 minutes.
- It will manage to clean something,
- It will bring attention to the fact there is more to be done,
- It doesn't block the user for undetermined amount of time. The same way Microsoft Windows used to when it decided to install updates...

### Describe alternatives you've considered

I have considered overriding it just myself locally, but I believe this would be better solution as a whole.

**Comment by poettering** [comment]
Ahum. Why would that take 3mins? please provide logs.

**Comment by marekrost** [comment]
I think I've identified what behavior causes the long startup of systemd-tmpfiles-setup.service, I'll get the logs.

**Comment by marekrost** [comment]
The long boot time seems to be caused by large volume of files inside /tmp on my system. Specifically, these files originate from: https://github.com/wkeeling/selenium-wire/issues/408

Attached boot log from 2 days ago shows that system boot got stuck cleaning up these temporary files for nearly 8 minutes straight.

[2024-04-08_boot.log](https://github.com/systemd/systemd/files/14921375/2024-04-08_boot.log)

I suppose the question is - is this correct and expected behavior on the side of systemd-tmpfiles-setup? Or no-one just expected huge amount of files in /tmp?

**Comment by poettering** [comment]
/tmp/ should be a tmpfs generally. If you distro still is using a traditional fs there, please file a bug. It's 2024.

If it's tmpfs then clean-up is entirely automatic, because it's backed by swap (i.e. can just get lost during boot), rather than a traditional fs (where stuff *must* be synced to disk), which requires unnecessary write cycles at both shutdown and startup.

Generally, we have to run tmpfiles.d/ stuff during boot, to guarantee that the system is in order (ie. /tmp/ must be rleatively clean so that the system can operate correctly). It's simply not OK to leave stuff half set up.

This seems to be a local misconfiguration mostly the way I see it.
