### ISSUE TITLE
How to install libudev from source?

### ISSUE THREAD

**Issue by VInbv** [systemd/systemd#31667]
I am struggling to install libudev from source (with Ubuntu), what is the correct way to do this?

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.

**Comment by v-fox** [comment]
Better question is: why the hell systemd hard-depends on system version of libudev during its compilation instead of using its own source?

This prevents bootstrap install and forces to use binary prebuild before fresh-installing systemd. In Gentoo this prevents openrc-to-system transition unless network is used to download binary package first, hoping that it will be ABI-compatible and nothing messed up (like emerge making a fuss about package signatures or system freezing or half-crashing due to kernel's OOM still being trash that kills system instead of the runaway process), otherwise system will be left in unbootable state. Which is also [undocumented](https://wiki.gentoo.org/wiki/Systemd#Dependency_problems), so [that's "great"](https://github.com/systemd/systemd/blob/v257-stable/README).

**Comment by poettering** [comment]
> Better question is: why the hell systemd hard-depends on system version of libudev during its compilation instead of using its own source?

I am not sure what you are talking of. udev/libudev is part of the systemd tree, and any systemd component using udev will use the contained code, not system code for htis.
