### ISSUE TITLE
At shutdown: Shells loosing history and group based services killed immediately

### ISSUE THREAD

**Issue by bitstreamout** [systemd/systemd#317]
Several users report a similar behaviour.  That is at shutdown it happens very often that the used shell looses its history and sometimes the full history get lost. An other problem which seems also caused by killing immediately are group based services with e service section like

[Service]
Type=simple
User=java
Group=users
ExecStart=/usr/bin/java_app

after debugging the commit 743970d2ea6d08aa7c7bff8220f6b7702f2b1db7 has been identified as the cause of this behaviour.  After searching it looks like this problem is well known:

  https://bugzilla.redhat.com/show_bug.cgi?id=1141137
  https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?h=experimental&id=6068e872da

What is the problem with
 "... for nspawn we actually can't wait for cgroups running empty since systemd will get exactly zero notifications about it .."
and can this be solved in an other way instead immediately killing shell and group based services?

**Comment by michich** [comment]
Correct RH BZ link: https://bugzilla.redhat.com/show_bug.cgi?id=1141137

**Comment by bitstreamout** [comment]
Thanks for spotting!

**Comment by poettering** [comment]
@bitstreamout hmm, there's some confusion here. Commit 743970d is only relevant for units for which no main/control PID is known. That's only scope units, and service units that use Type=forking without PIDFile= and without GuessMainPID=, or where guessing the main PID fails. In your example service snippet this hence does _not_ apply, because it uses Type=simple where the main PID is always known.

Yes, the issue applies to login sessions (which are exposed as scopes), but for them only at final shutdown, where the PAM session is not cleanly ended. For sessions that close during normal runtime the SIGKILL will not happen, because session scopes actually are left around by default until their last process ended.

The right fix for the whole mess is to port systemd to the unified cgroup logic, since we'll have proper notifications there for the first time, and can even wait for foreign processes going away nicely.

**Comment by bitstreamout** [comment]
I do not have the customers service unit here. I know that this java which is started by a bash wrapper script has its own sub processes. Maybe here pam drops in. Nevertheless the customer reports that reverting the specific commit 743970d2ea6d08aa7c7bff8220f6b7702f2b1db7 does solve his problem. The problem of loosing the shell history I see my self every now and then on all systems at reboot.

**Comment by jamespharvey20** [comment]
Should 743970d be reverted until it can come back simultaneously with the "right fix" porting systemd to the unified cgroup logic?

Debian did so at http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=00aaecd71
Ubuntu did so at https://lists.ubuntu.com/archives/vivid-changes/2015-May/008558.html
Looks like RedHat may be doing so soon, at https://bugzilla.redhat.com/show_bug.cgi?id=1170765 and https://bugzilla.redhat.com/show_bug.cgi?id=1141137

Just filed a pull request to revert it.

**Comment by poettering** [comment]
@bitstreamout PAM has no place in starting services, that should really be fixed. The PAM session logic should be used for user sessions, but not for running arbitrary system processes.

**Comment by bitstreamout** [comment]
I'm aware but this is a foreign bash wrapper script I've never seen and AFAIK it is not documented that command like su/sudo or any other pam based tools should be avoided.  On the other hand old SysVinit boot scripts had used su/sudo to switch user and group and if a third party vendor ports his complex scripts to systemd it might be that such a script becomes a wrapper script.

**Comment by bitstreamout** [comment]
Btw: How difficult it would become to detect in login/pam_systemd.c that it is within the chain of a service unit for boot  instead of systemd login manager? For compatibility with SysV ;^)

**Comment by arvidjaar** [comment]
> How difficult it would become to detect in login/pam_systemd.c that it is within the chain of a service > unit for boot instead of systemd login manager?

I suggested something similar as part of bnc#906900 (https://bugzilla.novell.com/show_bug.cgi?id=906900#c55) but nobody seemed to be interested (bug was "fixed" by rewriting sysvinit script). See https://build.opensuse.org/package/view_file/home:arvidjaar:bnc:906900/systemd/session-class-service.patch?expand=0

**Comment by bitstreamout** [comment]
In the menawhile a message from the customer had reached me that they could not wait any longer and they found workaround for this. Now they are using ExecStartPre= to read all options from /etc/sysconfig/ for their application and then they are writing this to /var/run/aem_author/env. This file is read by systemd as EnvironmentFile=. Later in ExecStart= they are just calling /usr/bin/java with EnvironmentFile as the variable parameter.  In such configuration java is the main process and everything is working as should. Also he had found some ungracious about systemd! 

@ arvidjaar : I had missed that patch, sorry about.
@ poettering : What do you think about this patch? This would allow to port complex SysVinit boot 
              scripts without workarounds.  IMHO this would increase the acceptance for systemd a lot
              if such ports would work without trouble.

Beside this the problem with loosing history data of the shells remains even with this patch.

**Comment by arvidjaar** [comment]
> I had missed that patch, sorry about.

Second complementary patch is https://build.opensuse.org/package/view_file/home:arvidjaar:bnc:906900/systemd/set-session-class-service-for-sysv.patch?expand=0
Of course it is outdated and should be ported to generator but this is the idea.

**Comment by shaneforsythe** [comment]
There are currently 2 open TTS tickets for Fedora regarding this issue
  https://bugzilla.redhat.com/show_bug.cgi?id=1141137
  https://bugzilla.redhat.com/show_bug.cgi?id=1170765

And one here for Centos7.2
   https://bugzilla.redhat.com/show_bug.cgi?id=1199644

(also see: https://bugs.launchpad.net/ubuntu/+source/mosh/+bug/1446982 )

Ubuntu,Debian, and Centos7.2 have now all reverted the commit in question to to data-integrity/data-loss.  

Fedora is stuck because they rely on systemd as both upstream provider and maintainer, and from what I understand will not specifically "back port" for Fedora as they use the main upstream repo as well.

Reverting this commit may re-introduce another bug, but as I understand it that bug is a fairly specific edge-case and does not effect everyone, nor does it cause data loss.

This current bug effects everyone.

**Comment by bitstreamout** [comment]
@ poettering : is there any solution from upstream to avoid the method of jumping from the frying pan into the fire (aka `den Teufel mit dem Beelzebub austreiben')?  Most customers/users do not like  data loss.

**Comment by bitstreamout** [comment]
When will this issue become fixed?  We have several customers and users which insists that this bug has to be fixed.

**Comment by jamespharvey20** [comment]
@bitstreamout which distribution do you run?

**Comment by jamespharvey20** [comment]
@bitstreamout : after a quick google, I'm guessing you're on SuSE.  Is custom-building (even a release version) with git commit 743970d reverted an option for you?  It does create a race condition which can cause a ~30 sec delay on shutdown, but it gets rid of the data loss.  Ubuntu, Debian, Centos 7.2, and me on Arch are running great with this.  Not sure if RedHat has gone this way, or if they're still debating it.  I know it's not the optimal solution, but ...

**Comment by arvidjaar** [comment]
If every distribution reverts this patch, what is rationale for keeping it upstream?

**Comment by bitstreamout** [comment]
Good question.  AFAICS from the comment at git commit https://github.com/systemd/systemd/commit/743970d2ea6d08aa7c7bff8220f6b7702f2b1db7 the container logic using cgroups is not foolproof and therefore it looks like that this ``fix'' causing this trouble since Feb 7, 2014  seems to be acceptable for upstream or why do they play dead here?

**Comment by shaneforsythe** [comment]
Fedora 22 has not reverted this patch. 

As they rely on systemd directly as an upstream sources this is very unfortunate for them.

**Comment by AdamWill** [comment]
I'm not really sure what you mean when you keep saying Fedora 'rely on systemd directly as an upstream sources', implying that it's somehow different from any other distro. All distros use systemd as the upstream source for systemd, it couldn't really be any other way.

We certainly can patch systemd downstream in Fedora, it's happened before and will likely happen again. There's nothing magic about systemd or how it's packaged in Fedora which makes that impossible. If this isn't addressed upstream before the release of Fedora 23 I was already planning to ensure it was addressed downstream.

**Comment by shaneforsythe** [comment]
So then the entire release of Fedora 22 will have a data integrity issue that is known to the maintainers?  Reading the TTS tickets it appears bug is as far back as Fedora21.  I see you've commented on several Fedora TTS , but no where have you mentioned this plan to patch in Fedora 23, most people watching those tickets believe it is being completely ignored.

https://bugzilla.redhat.com/show_bug.cgi?id=1170765
https://bugzilla.redhat.com/show_bug.cgi?id=1183194
https://bugzilla.redhat.com/show_bug.cgi?id=1141137

You responded to me directly on the last ticket when I asked what the process was to have this bug addressed, your response
"The Fedora package has several maintainers, including Lennart, Zbigniew Jędrzejewski-Szmek and Jan Synáček."

Michael Chapman responded , "As with many other critical Fedora packages, the Fedora maintainers are also upstream maintainers and they typically only backport patches to Fedora that have already applied upstream, so the best place to start would be to get this fixed upstream: https://github.com/systemd/systemd"

So forgive me for my confusion, when I'm being told the direct opposite.

Every other maintainer for systemd for other distros has reverted this commit in CURRENT distros.  What is the rational for waiting another 3 months before addressing a data integrity bug?

**Comment by AdamWill** [comment]
The rationale is making sure it's the right thing to do. Software is complex, and it's not generally a good idea to run around whacking on buttons that superficially look like they do the right thing.

Calling this a 'data integrity issue' is technically correct but kind of overselling it, to my mind. The only case of 'data loss' we actually know of is bash history. That isn't the end of the world.

**Comment by martinpitt** [comment]
It also breaks things like mosh (https://launchpad.net/bugs/1446982). But most importantly, it doesn't give programs in your session (like LibreOffice or vim) any time to save their documents (e. g. in https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1448259/comments/17), so this _is_ a data loss issue.

I haven't yet seen any convincing argument or bug report why we need commit 743970d; AFAICS reverting this commit the right thing to do for downstream distros, as losing data is infinitely worse than a rare 90 s hang on shutdown.

**Comment by johannbg** [comment]
@poettering  Perhaps an status update of the porting systemd to the unified cgroup logic is in order here ( is it being worked on, is there something blocking it etc ).

Cant systemd sleep for X ( like 5 ) seconds  before sending sigkill which is ( if I'm not mistaken ) what sysvinit and upstart did?

It wont fix the underlying problem but it would make systemd on par with making it equally likely to happen as it is with the other init systems.

**Comment by shaneforsythe** [comment]
>Software is complex, and it's not generally a good idea to run around whacking on buttons that superficially look like they do the right thing.

You mean like just commenting out :
                        wait_for_exit = true;

Can we at least implement @johannbg suggestion?

**Comment by mcatanzaro** [comment]
This issue will be discussed at the Fedora Workstation Working Group meeting beginning at 14:00 UTC (10:00 EDT) on Wednesday, September 2, in #fedora-meeting on freenode, as it was requested that we revert 743970d2ea6d08aa7c7bff8220f6b7702f2b1db7 in Fedora, as many other distros have already done. systemd maintainers and developers are invited to attend and provide input. Our understanding is that reverting 743970d2ea6d08aa7c7bff8220f6b7702f2b1db7 will avoid many cases of data loss.

**Comment by mcatanzaro** [comment]
To be clear, we don't need anyone to attend and tell us that data loss is bad. We would probably need to hear a _very_ convincing argument in favor of not reverting, hence the invite is specifically addressed to systemd developers, whom presumably would be opposed to this as the change has not been made upstream.

**Comment by johannbg** [comment]
@mcatanzaro here's a convincing argument why aren't you going to be blocking the components that are the actual root cause for this issue so they finally get fixed "properly" . Why are you expecting that systemd should be playing whack-a-mole game and be providing "workarounds" for the underlying root causes not related to itself?  The "delay" workaround in sys V and upstart did not prevent this issue it just made it less likely to be encountered.

@keszybz and the rest that has finger in the downstream maintainance of systemd in Fedora, I suggest you just let the working groups maintain their own version of systemd downstream and or take over the maintainership downstream since they are showing up with direct threats on overwriting your maintainership   "We would probably need to hear a very convincing argument in favor of not reverting" in an illusion game of pressuring you to fix what cant be fixed here.

**Comment by mcatanzaro** [comment]
@johannbg Could you explain more fully what your plan is (what are the "components that are the actual root cause of this issue", how to fix them "properly")? Since this is a data loss issue, the highest priority is to find a way to avoid the data loss as quickly as possible. Our understanding is that reverting one commit in systemd will accomplish that.

**Comment by martinpitt** [comment]
"why aren't you going to be blocking the components that are the actual root cause for this issue" → as far as I understand, systemd _is_ the component for all of this -- it sets up and tears down units, scopes, sessions, etc. We can't possibly start requiring that bash, mosh, LibO and what not start registering with systemd in order to do cleanup actions on shutdown?

**Comment by AdamWill** [comment]
@johannbg I'm sorry, but it's absurd to say that a system where the init daemon signals processes to shutdown cleanly then waits some time for it to happen is a 'workaround'. A system where the init daemon signals processes to shutdown cleanly then immediately kills them dirtily is 'broken'.

**Comment by johannbg** [comment]
@mcatanzaro see both the issue label the cgroup comment as well as the commit message in what you want reverted, this might be mitigated by changing the killmode in affected type units.

@AdamWill so you dont think those processes notify the init system once they have shutdown ( which is what is broken here ) .

With regards to this suddenly becoming a release blocker ( cough not a release blocker in *F21 and not a release blocker in F22 ) based on what you seem to be suddenly judging this by ( data loss ) last time I checked the last bash closed session ( think multiple shells )  takes precedence in writing the bash history so based on your new founded blocker logic does not that cause "data loss"  hence it should be a blocker as well or are you going to argue somehow it's not?

**Comment by AdamWill** [comment]
@johannbg as things stand the processes get no chance to shutdown cleanly and then notify the init system. they get `SIGKILL` _one tic_ after they get `SIGTERM`.

We can discuss the ideal system until we're blue in the face, but the bottom line is that it's _not acceptable_ to have the init daemon for all the world's distros unconditionally `SIGKILL`ing user processes. You can't both be the init daemon that all the world uses _and_ hold users hostage to your desires for spherical cow perfect behaviour. If it's not possible to implement the spherical cow behaviour _right now_, then you have to implement behaviour that works reasonably well, i.e. not causing unclean shutdown of all running user applications every time they shut down the system. I don't honestly see how you can reasonably defend that behaviour. If it can't be fixed in the 'ideal' way right now, that's just too bad: fix it in the _not_ ideal way now and fix it in the ideal way later.

This wasn't a release blocker in 21/22 because it wasn't proposed as one at a time when its impact was fully understood; at the time all we knew is that it was causing some annoying behaviour with bash history. It should have blocked both of those releases, and if we had had a full understanding of the issue when we were evaluating it, it would have been.

This isn't a Fedora release blocker because it can damage people's bash history, it's a Fedora release blocker because it could cause people to lose data in _any process they have running in a scope_.

**Comment by johannbg** [comment]
@AdamWill, @mcatanzaro and the rest how do you expect this being implemented in better manner than is already outlined here [1]? 
1. http://lists.freedesktop.org/archives/systemd-devel/2014-November/025734.html

**Comment by johannbg** [comment]
And now the question that everybody should be asking... 
@poettering again simple question is someone working on replacing the old and outdated notify_on_release with the new and improved unified hierarchy cgroup.populated so this inconvenienced for downstream distribution and their users be ( soon or not so soon ) put to rest?

**Comment by AdamWill** [comment]
@johannbg The issue is not the best way to implement it, the issue is how long it's _taking_ to implement it. If it gets implemented the way that's outlined there tomorrow, that would be fine. But it seems like every time this gets escalated to upstream, the response is 'oh, we have this awesome plan for fixing this in a really good way, so please wait for that', and then it _doesn't happen_. This bug has been sitting around being an active danger on probably hundreds of thousands of users' systems for over a year. That's not acceptable for such a core component of the operating system.

If it can't be implemented in the desired way in a very short timeframe - and that implementation safely backported to stable releases - then it should be done a different way for the short term, because it just is not OK to leave this bug sitting around until the 'perfect fix' is ready.

**Comment by dvdhrm** [comment]
@johannbg, yes, unified cgroups are being _actively_ worked on.

**Comment by johannbg** [comment]
@dvdhrm im looking forward to see what inotify watch voodoo pony you have up your sleeve to implement this race free in systemd.  That's going to be one beautiful pony 

Do you have any roadmap for that pony or better yet if that pony wont be arriving in the near future cant you do the downstream distributions a favour and revert commit 743970d here upstream to throw people some bone before the bigger political issue that's going to be associated with that pony arrives ;)

**Comment by dvdhrm** [comment]
@johannbg, I'm cultivating different ponies.. can't tell you any details. But see the recent cleanups merged by @poettering which mention that it's in preparation for the unified cgroup. I'll leave it up to him to decide whether to revert the commit.

**Comment by mcatanzaro** [comment]
FYI: I am not going to put this on the agenda for the Workstation WG meeting after all, since it's come to my attention that the Fedora QA team has already accepted [bug #1170765](https://bugzilla.redhat.com/show_bug.cgi?id=1170765) as a release blocker.

**Comment by jamespharvey20** [comment]
@johannbg (and @poettering), I think the simple question is a bit different.  We've been left waiting for a long time because people are working on it, but have been given no idea of the magnitude of the wait.  Are the developers working on this area thinking it could be right around the corner, or something probably 6 months - a year off?  Something we could still be scratching our heads on 2 years from now?  And, the biggest question to me is why there's been no official comment or reassurance on this since Jun 24,  when there's been about 33 comments since then...

**Comment by johannbg** [comment]
@jamespharvey20 well Tejun Heo just recently re-factored the unified cgroups upstream and those changes are targeted to be included in kernel 4.3 so you can assume that any code written with previous implementation in mind now more or less needs to be re-written so rough expectation of the implementation for this to appear in systemd ( assuming the new implementation is "race free" ) is I would say 4 - 6 months. 

That means first sign of that implementation appearing in distribution which get released around mid next summer ( with the exception of arch which might introduce it sooner ) that's excluding any priorities developers they themselves might have so for example I think you can safely assume that if @dvdhrm here is the owner of these changes, that time increase to 6 - 8 months due to his involvement with kdbus ( that is if it ever gets accepted upstream ). 

Needless to say it's not happening anytime soon which is why @poettering  should revert that commit ( and or communicate with the "community" why he's so reluctant to do that since he is forcing everybody to carry downstream patches ) and re-introduce that commit when the implementation for the unified cgroups is actually in the horizon.

**Comment by poettering** [comment]
Please see my comment on https://github.com/systemd/systemd/pull/350#issuecomment-137005614 regarding the whole issue and the status quo.

**Comment by bitstreamout** [comment]
This issue seems to be fixed AFAICS ... but ... nevertheless, the new Delegate feature now causes a regresssion in I/O benchmarks.  I'll open a new issue for that!
