### ISSUE TITLE
gpt-auto-generator not finding esp on other devices

### ISSUE THREAD

**Issue by hsitter** [systemd/systemd#31763]
### systemd version the issue has been seen with

255

### Used distribution

Arch

### Linux kernel version used

6.7.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Expected behaviour you didn't see

No /efi auto mount. Specifically `enumerate_partitions(devno)` only appears called for the device the rootfs is on.

### Unexpected behaviour you saw

> Mar 13 15:19:07 archlinux systemd-gpt-auto-generator[358]: LoaderDevicePartUUID points to neither ESP nor XBOOTLDR, ignoring.

### Steps to reproduce the problem

- Have two drives
- Drive one sports the ESP and some random data partitions
- Drive two sports the SD_GPT_ROOT_X86_64
- boot without fstab but `root=PARTLABEL=OS` where OS is the label of SD_GPT_ROOT_X86_64
- /efi doesn't get auto mounted

### Additional program output to the terminal or log subsystem illustrating the issue

partial generator snippet
```sh
Mar 13 15:19:07 archlinux systemd-gpt-auto-generator[358]: Probed fstype 'btrfs' on partition /dev/disk/by-diskseq/4-part1.
Mar 13 15:19:07 archlinux systemd-gpt-auto-generator[358]: Probed fstype 'swap' on partition /dev/disk/by-diskseq/4-part2.
Mar 13 15:19:07 archlinux systemd-gpt-auto-generator[358]: Adding swap: /dev/disk/by-diskseq/4-part2
Mar 13 15:19:07 archlinux systemd-gpt-auto-generator[358]: Reading EFI variable /sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f.
Mar 13 15:19:07 archlinux systemd-gpt-auto-generator[358]: LoaderDevicePartUUID points to neither ESP nor XBOOTLDR, ignoring.
```

drive lineup
```
lsblk -o NAME,FSTYPE,PARTTYPENAME 
NAME        FSTYPE  PARTTYPENAME            
sda                 
`-sda1      ntfs    Microsoft basic data
sdb                 
`-sdb1      btrfs   Linux filesystem
nvme0n1             
|-nvme0n1p1 vfat    EFI System
|-nvme0n1p2         Microsoft reserved
|-nvme0n1p3 ntfs    Microsoft basic data
`-nvme0n1p4 btrfs   Linux filesystem
nvme1n1             
|-nvme1n1p1 btrfs   Linux root (x86-64)
`-nvme1n1p2 swap    Linux swap
```

LoaderDevicePartUUID is set and contains the correct UUID.

**Comment by poettering** [comment]
gpt-auto is not supposed to cover complex storage with multiple disks. For security reasons it strictly only looks at the root disk the EFI firmware picked, and nothing else (so that you cannot trick the system into booting into arbitrrary stuff just by sticking in an USB stick at the wrong time). 

If you have multiple disks that's entirely fine, but in that case please configure them in /etc/fstab, that's really what it is for.

Sorry, but your case simply is not the case that the gpt-auto stuff is designed for. 

And this all is documented very explicitly in the man page even!
