### ISSUE TITLE
runlevel utility does not report correct runlevel during boot

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#3177]
### Submission type
- Bug report
### systemd version the issue has been seen with

> 229
### Used distribution

> Debian
### In case of bug report: Unexpected behaviour you saw

When booting, `runlevel` reports 'unknown' until it reaches multi-user.target (or at least, somewhere comparably late). Similarly, on shutdown it reports "N 5" until some point at which it becomes "N N".
### In case of bug report: Steps to reproduce the problem

```
$ systemctl cat rltest.service 
# /etc/systemd/system/rltest.service
[Unit]
Description=Run runlevel

[Service]
# adjust sleep time if your machine boots too fast
ExecStart=/bin/sh -c 'while true ; do runlevel; /bin/sleep 0.1s ; done'

[Install]
WantedBy=multi-user.target
```

And then reboot.

I guess a single systemd-update-utmp service is not enough.

**Comment by martinpitt** [comment]
This is because `systemd-update-utmp-runlevel.service` has

```
After=runlevel1.target runlevel2.target runlevel3.target runlevel4.target runlevel5.target
```

I. e. it will only switch the runlevel from "unknown" to e. g. "5" after graphical.target is active.

I already had a go at this, but it's not that easy. `src/update-utmp/update-utmp.c` determines which runlevel to report in `get_current_runlevel()` using this table:

```
    static const struct {
            const int runlevel;
            const char *special;
    } table[] = {
            /* The first target of this list that is active or has
             * a job scheduled wins. We prefer runlevels 5 and 3
             * here over the others, since these are the main
             * runlevels used on Fedora. It might make sense to
             * change the order on some distributions. */
            { '5', SPECIAL_GRAPHICAL_TARGET },
            { '3', SPECIAL_MULTI_USER_TARGET },
            { '1', SPECIAL_RESCUE_TARGET },
```

But targets only have states "dead" and "active", unlike units there is no "activating". So we cannot use this approach to see if multi-user.target _will_ be active (or not) at some point in the future if we just made it past basic.target. So fixing this in systemd itself will require larger architectural changes: for example, adding a state "activating" to targets, or switching the above heuristics to determine the target unit in some other way than checking if that target is active.

**Comment by martinpitt** [comment]
@fsateler: Your unit in the reproducer is not correct: During early boot (before sysinit.target, or `rcS` in SysV terms) the runlevel _should_ be "unknown" (it also is in SysV). The bug is that `runlevel` is still "unknown" after `sysinit.target` and before `multi-user.target`. I'll adjust your test accordingly.

**Comment by poettering** [comment]
So, what is the behaviour you expected? We do not transition to any intermediary "runlevels" after all, we run everything in a single transaction...

**Comment by martinpitt** [comment]
The corresponding SysV behaviour is that *after* reaching sysinit.target runlevel reports something else ('S' or '2', I forgot) rather than "unknown" and succeeds.

However, this has been like that for so long now, and presumably all distros somehow got along with that. I figure Debian is the most difficult one in that regard as it still supports SysV init too, and we taught our `service` and `invoke-rc.d` scripts to not rely on `runlevel` any more under systemd.

Honestly I think we should just bury this now and "wontfix". @fsateler, WDYT?

**Comment by poettering** [comment]
I'd like this "solution" very much of course ;-)

**Comment by fsateler** [comment]
I think ideally systemd would treat runlevel S as equivalent to reaching sysinit.target or basic.target. However, since this appears to have hit very few people in practice (judging by the reports here, our tools were the only problematic ones, and they were taught to talk to systemd directly), I'm fine to close this if nobody is going to dedicate time to fix it.
