### ISSUE TITLE
systemd-integritysetup-generator doesn't support xxhash64 integrity

### ISSUE THREAD

**Issue by geovex** [systemd/systemd#31824]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

Despite being supported by `integritysetup`, `/etc/integritytab` can't use `integrity-algorithm=xxhash64`

### Describe the solution you'd like

`systemd-integritysetup-generator` should support `xxhassh64`

### The systemd version you checked that didn't have the feature you are asking for

255.4-2-arch

**Comment by Unique-Usman** [comment]
@geovex thanks for the report, I am beginner contributor in systemd, I have been able to locate the necessary files where the integrity-algorithm is located. Please, kindly help provide necessary information to replicate this issue, also if there is any error also associated with this, kindly help with it. Thank you. 

@bluca, if there is any other thing that might help, kindly help with it. Thank you very much.

**Comment by Unique-Usman** [comment]
@bluca I have gone through the code, I noticed there is no support for xxhassh64, https://github.com/systemd/systemd/blob/main/src/integritysetup/integritysetup.c#L77 
https://github.com/systemd/systemd/blob/main/src/integritysetup/integrity-util.c#L11
but, does not support xxhassh64 at the moment. It is also not included in the man page https://www.freedesktop.org/software/systemd/man/latest/integritytab.html#integrity-algorithm=%5Bcrc32c%7Ccrc32%7Csha1%7Csha256%7Chmac-sha256%5D

For support xxhassh64, are we just adding the name as specify as done in https://github.com/systemd/systemd/blob/main/src/integritysetup/integritysetup.c#L86. 

Something like this

```
static const char *integrity_algorithm_select(const void *key_file_buf) {
    if (arg_integrity_algorithm) {
        if (streq("hmac-sha256", arg_integrity_algorithm))
            return DM_HMAC_256;
        else if (streq("xxhash64", arg_integrity_algorithm))
            return "xxhash64";
        return arg_integrity_algorithm;
    } else if (key_file_buf)
        return DM_HMAC_256;
    return "crc32c";
}
```

and also 

```
static int supported_integrity_algorithm(char *user_supplied) {
        if (!STR_IN_SET(user_supplied, "crc32", "crc32c", "sha1", "sha256", "hmac-sha256", "xxhash64"))
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Unsupported integrity algorithm (%s)", user_supplied);
        return 0;
}
```

**Comment by KJ7LNW** [comment]
+1.  Found this on Oracle Linux 9, would be nice for native support:

[Apr13 15:44] systemd-integritysetup-generator[545637]: Unsupported integrity algorithm (xxhash64)

**Comment by ddawson** [comment]
> ```
>         else if (streq("xxhash64", arg_integrity_algorithm))
>             return "xxhash64";
> ```

I don't believe that's necessary. The `integrity_algorithm_select()` function exists simply to give an appropriate string based on a couple of things, one being if the string `hmac-sha256` is used, which it substitutes with `hmac(sha256)` (see [integrity-util.h](https://github.com/systemd/systemd/blob/main/src/integritysetup/integrity-util.h) for the macro used; incidentally, why is there a macro only for that one?), and the other being whether a key file is specified, in which case it defaults to that same algorithm. If nothing is specified, it defaults to `crc32c`.

The important thing here is that if any other string is given, such as, say, `xxhash64`, the function returns it as-is. So, it effectively doesn't change it. Adding explicit code for xxhash64 would change nothing. The change we actually need is this one:

> ```
> static int supported_integrity_algorithm(char *user_supplied) {
>         if (!STR_IN_SET(user_supplied, "crc32", "crc32c", "sha1", "sha256", "hmac-sha256", "xxhash64"))
>                 return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Unsupported integrity algorithm (%s)", user_supplied);
>         return 0;
> }
> ```

I tested, and it has the desired effect. (This is easy enough to test, since if the wrong algorithm is used, you will get only I/O errors when trying to read from the device.)

I went ahead and submitted PR #34567 for this.

**Comment by ddawson** [comment]
> Maybe parse /proc/crypto for type=shash?

Maybe. Then again, the kernel will check it anyway, so going this far probably isn't needed.

But I don't feel comfortable proposing such a change without input from authoritative devs, since I don't fully understand why systemd restricts the value like this.

**Comment by KJ7LNW** [comment]
> > Maybe parse /proc/crypto for type=shash?
> 
> Maybe. Then again, the kernel will check it anyway, so going this far probably isn't needed.

My concern is not the case where the kernel will fail; it is totally fine if someone chooses a hash that the kernel does _not_ support because the kernel _and_ systemd will give a proper error for the system administrator.  

Rather, I am much more concerned with avoiding another xxhash64 issue (like this #31824) where the kernel supports something but systemd does not.  As far as I can tell the only reason for this `supported_integrity_algorithm` list is that someone decided to hard-code the list of hashes that were supported by the kernel _at that specific Linux version_. Unfortunately that is a poor programming practice because it duplicates the check for support (which in this case is the duty of the kernel) and prevents future usability. 

Unless there is a really good technical reason for limiting hashes used by `systemd-integritysetup-generator` (and I do not just mean "these were tested as usable"), it would be best if systemd could be flexible and yield to whatever the kernel supports. If `@someone_authoritative` prefers warnings (as would be best practice) then something like _"warning: the hash %s has not been tested by systemd, YMMV."_ might be appropriate, but failing with `EINVAL` seems excessive.

> But I don't feel comfortable proposing such a change without input from authoritative devs, since I don't fully understand why systemd restricts the value like this.

Understood. Can you bring `@someone_authoritative` into this ticket to comment?

**Comment by ddawson** [comment]
> Rather, I am much more concerned with avoiding a future "xxhash64 issue" (like this #31824) where the kernel supports something but systemd does not. As far as I can tell the only reason for this `supported_integrity_algorithm` list is that someone decided to hard-code the list of hashes that were supported by the kernel _at that specific Linux version_. Unfortunately that is a poor programming practice because it duplicates the check for support, which in this case is the duty of the kernel, and prevents the use of future kernel features for (what appears to be) administrative reasons.

Yes, I understand. You're probably right. It's just, there could be something like a policy reason for doing this sort of check. Or maybe not. But I'm not very familiar with systemd's coding standards, and not at all familiar with how development is governed, so I think it's a good idea to talk to someone who understands it first.

> Understood. Can you bring `@someone_authoritative` into this ticket to comment?

I don't have any more authority here than you do. I'm just someone who also wants to use xxhash64 with this, but also decided I could do something. That said, you can see [from the blame](https://github.com/systemd/systemd/blame/6fd58537e5b01e4cbb0f0447ceb3791f0f8f53f5/src/integritysetup/integrity-util.c#L11) who wrote the code in question. I suppose @tasleson is a reasonable person to ask about it, but I have no idea whether he or anyone else will enter this conversation.

**Comment by KJ7LNW** [comment]
Thank you, I appreciate it!

**Comment by tasleson** [comment]
> I don't have any more authority here than you do. I'm just someone who also wants to use xxhash64 with this, but also decided I could do something. That said, you can see [from the blame](https://github.com/systemd/systemd/blame/6fd58537e5b01e4cbb0f0447ceb3791f0f8f53f5/src/integritysetup/integrity-util.c#L11) who wrote the code in question. I suppose @tasleson is a reasonable person to ask about it, but I have no idea whether he or anyone else will enter this conversation.

Please don't assume that the person that wrote the code has anymore authority than anyone else :smiley: .  If you look at the original PR: https://github.com/systemd/systemd/pull/20902 there was a lot of modifications made to get the support added.  As for why something is missing I have no idea.  My only guess is that whatever is missing wasn't present 3 years ago or it was omitted for some other technical reason.  The systemd folks that have "authority" have reasons for their design decisions which not all may agree with (see this [comment](https://github.com/systemd/systemd/pull/20902#discussion_r720679522) for more background on design).

My suggestion is to submit a PR to add the missing support, including improved unit tests. As part of that process, you can have a discussion on the limitations and the reasons behind what is or isn’t supported—things that will likely evolve over time.
