### ISSUE TITLE
Share `cryptsetup` passphrase with other volume encryption software

### ISSUE THREAD

**Issue by jze2** [systemd/systemd#32064]
### Component

systemd-cryptsetup

### Is your feature request related to a problem? Please describe

I have LUKS-encrypted SWAP and ZFS-encrypted root with the same password. While systemd-cryptsetup can reuse the passphrase for other LUKS volumes, ZFS cannot because the cryptsetup key(ring) has by default 0x3f010000 permissions so I get Permission denied when trying to read the key in initrd during boot.

I'd like to enter the password only once.

### Describe the solution you'd like

Alter the key(ring) default permissions by adding READ UID permission.

Either this or rewrite the whole systemd mounting ecosystem to ask for password first, create readable key and then enable all mounting software to accept the key name as an optional parameter.

### The systemd version you checked that didn't have the feature you are asking for

255.4-2

**Comment by poettering** [comment]
Hmm? Not sure I fully grok what you are saying, but if your code runs as root it should be able to access the key just like systemd-cryptsetup. I mean, what kind of privs does the zfs userspace lack that systemd-cryptsetup has? not following?

We even provide a PAM module in pam_systemd_loadkeys in the upcoming v256 that reads a cached disk encryption password and allows funnelling it into the PAM stack. Hence, this definitely works.

Mabye your forgot to set KeyringMode=inherit in the service that shall receive the keys? because by default we give private keyrings to each service, and the cryptsetup keys are hence not readable that easily.

**Comment by jze2** [comment]
OMG! Yes, that was the culprit.

I added `KeyringMode=inherit` to the `[Service]` section of `/usr/lib/dracut/modules.d/98dracut-systemd/dracut-pre-mount.service` and then added
```
***************
*** 31,40 ****
--- 31,43 ----
      [ "$(zfs get -Ho value keystatus "${ENCRYPTIONROOT}")" = "unavailable" ] || return 0
  
      KEYLOCATION="$(zfs get -Ho value keylocation "${ENCRYPTIONROOT}")"
      case "${KEYLOCATION%%://*}" in
          prompt)
+             # Try to use cryptsetup key first.
+             keyctl pipe `keyctl search @u user cryptsetup` | zfs load-key "${ENCRYPTIONROOT}" && return
+             # If the key does not match ZFS key, ask for it.
              for _ in 1 2 3; do
                  systemd-ask-password --timeout=0 --no-tty "Encrypted ZFS password for ${dataset}" | zfs load-key "${ENCRYPTIONROOT}" && break
              done
              ;;
          http*)
```
to `/usr/lib/dracut/modules.d/90zfs/zfs-load-key.sh` and now I have to enter password only for swap.

THANK YOU :-)
