### ISSUE TITLE
machined should allow dynamic allocation of transient UID ranges for userns support in container managers such as nspawn

### ISSUE THREAD

**Issue by tixxdz** [systemd/systemd#321]
This issue is to discuss how UIDs and ranges should be handled in machined.
## Problem

Our primary use case is related to rkt container and the "Investigating user namespaces" issue https://github.com/coreos/rkt/issues/986 . In rkt container we need:
- A way to get usable UIDs and ranges for the user namespace
- A locking mechanism to make sure that the UIDs will not overlap within multiple containers.
## Machined to handle UIDs and ranges

Enters machined, as discussed previously in a systemd meetup machined could provide this functionality. This allow us to not worry about all the locking, UIDs ranges, etc. The work will be done in machined. Programs and containers then could query machined for a usable UID and a range for their user namespaces and machined will provide that unique UID [base:range]. We believe that other programs that do not have a central daemon to handle UIDs within the global range will also find this functionality useful.

There is also the the subordinate uid file /etc/subuid [1] that can be used to handle UIDs and ranges in a static way, but with machined it would be possible to handle UIDs dynamically.
#### 1) Format of the UIDs and ranges

"It is recommended to assign as least 65536 UIDs to each container, so that the usable UID range in the container covers 16bit. For best security do not assign overlapping UID ranges to multiple containers. It is hence a good idea to use the upper 16bit of the host 32bit UIDs as container identifier, while the lower 16bit encode the container UID used."

```
    User or login name : First Host UID : Host UIDs range

   a) user or login name : UID                  : UIDs range

   b) user or login name : UID                  : 65536 (default value if omitted)

   c) user or login name : X   (omitted)        : 65536
       X is : owner of the root directory of the container
       X is : the uid of the remote peer in the host using D-Bus peer credentials.
```

The upper 16bit of the host 32bit UIDs will be managed on its own since we have cases where multiple containers running under the same user or login name will run simultaneously. So if a user did not request a specific UID then machined will generate multiple unique UIDs and handle them automatically for that user.
##### 2.1) How to expose things on the bus:

Interface org.freedesktop.machine1.Manager

```
GetUserNSuids(in s name,
              in u UID,
              in u UIDs range,
              in b overlap,
              out u UID_to_use,
              out u UIDs_range_to_use);

ListUserNSuids(out ...  )
```

Pass the [User:UID:UIDs range] tuple that was obtained from GetUserNSuids() method to machined D-Bus with `RegisterMachine(), CreateMachine(), CreateMachineWithNetwork() and RegisterMachineWithNetwork()` methodes. Or create a new D-Bus method:

```
 `RegisterUserNSuids(in s name, in u UID, in U UIDS range,...)` ?
```

Questions:
-  Two interfaces for UID and GID since perhaps there are cases where the GID range is not identical to the UID one ?

Then add the user namespaces UIDs and ranges to the org.freedesktop.machine1.Machine
interface.
#### 4) How is this related to NSS ?

To be completed, thank you for your feedback!

[1] http://manpages.ubuntu.com/manpages/trusty/man5/subuid.5.html

**Comment by alban** [comment]
Thanks. Just posting some thoughts and questions:

What happens if machined is restarted? Does it need to serialise the current state into a file and unserialise it on start?

What if the container manager (nspawn) crashed or is killed? Should machined monitor nspawn's D-Bus  name and release the UID allocation when the D-Bus name disappears?

> GetUserNSuids(in s name,
>               in u UID,
>              in u UIDs range,
>              in b overlap,
>              out u UID_to_use,
>              out u UIDs_range_to_use);

Is `name` an arbitrary token chosen by the caller or the name of the machine?

I'm not sure why we have 4 parameters UID, UIDs+range, UID_to_use and UIDs_range_to_use. I would use two parameters:
- in u uid_count: specify how many UID do you want (nspawn could use the constant 65536)
- out u uid: machined replying to nspawn "use that uid"

For example, if nspawn calls the method with uid_count=65536 and machined replies uid=131072, nspawn would apply the following mapping:
- 0 in the container -> 131072 outside
- 1 in the container -> 131073 outside
- ...
- 65535 in the container -> 196607 outside

machined does not need to know the exact mapping, does it?

And since there can be only one machined process running on the system, there will be no need to use a locking mechanism on some lock files. Instead, machined can just keep track of the uid allocations. As long as it serialises them on restart, it should be fine.

> Or create a new D-Bus method
> RegisterUserNSuids(in s name, in u UID, in U UIDS range,...)

It could be two new methods `{Create|Register}MachineWithNetworkAndUIDRange` with the additional parameters?

> Two interfaces for UID and GID since perhaps there are cases where the GID range is not identical to the UID one ?

At the moment, nspawn always applies the same mapping for UIDs and GIDs and I think it is better to keep it that way.

**Comment by poettering** [comment]
I am not entirely sure I grok fully what is being proposed here. But: I am strongly against persisting UID allocations with machined. If you want to persist the uids, then do that externally, but I am pretty sure machined should consider all allocations made through it fully dynamic and transient (i.e. non-persistant),

I am also very sure we should try to avoid explicitly registering allocations with machined. Instead, we should read the mappings implicitly from /proc/$PID/uid_map, where $PID is the leader process of a registered container. We can either to this on each lookup request, or cache this either on first access or at the time the container is registered with RegisterMachine() or CreateMachine() (caching should be OK,  uid_maps that change over time is nothing we should bother with I think). (I think doing this on RegisterMachine() or CreateMachine() is probably the best idea, so that we can maintain a complete database of mappings in /run somewhere, which is accessible from our NSS modules.)

I am fine with adding an API for allocating dynamic UID ranges to machined, but only for fully dynamic, non-persistent allocations. I doubt you want those for rkt right now though, as that effectively implies we need to have a way to apply non-persistent uid-shifts via mount switches or so.

If we do dynamic UID range allocation in machined, then this should be bound to an fd we return to the client, so that the uid range stays allocated as long as the fd is open, so that we have lifecycle tracking of the client. This is similar to how logind manages inhibitor locks for example.

**Comment by poettering** [comment]
To say this explicitly: if you want to deliver uid namespacing with rkt now, then this means you cannot use fully dynamic, non-persistant uid range allocations, since you need to uid-shift the container tree on disk, and cannot apply this via some special bind mount. And that means machined is not the place to allocate the uids with. Instead, just declare some high uid range as private property of rkt, and then allocate things from that range within rkt, by keeping a rkt-private database of valid allocations.

This all would happen entirely outside of machined hence. However, to make this all behave nicely I'll probably soon add some bits to machined that read uid_map from the leader process at time of RegisterMachine(), to hook that up with NSS. But that would be entirely generic and mostly about cosmetics, and would work with _any_ container manager that uses RegisterMachine() and at that time has user namespacing set up.

And doing dynamic UID range allocations in machined is probably something we shouldn't do before the kernel learns a per-bind-mount option to apply uid-shifts on access time. Because before that it makes little sense...

**Comment by alban** [comment]
> Instead, just declare some high uid range as private property of rkt, and then allocate things from that range within rkt, by keeping a rkt-private database of valid allocations.

@poettering That's less interaction between components. It can make this simpler in the end! So I am ok with that :) But I thought that was your idea to allocate uids in machined?

Ok, let's see if the following looks ok as well:

Let's say rkt gives 65536 uids for each container. And rkt allows up to 8192 simultaneously running containers (made up number for the example).

So that's 65536*8192 = 536870912 uids declared as private property of rkt. That's not even 0.1% of the complete 32 bit range, so that seems reasonable.  

rkt does not have a central daemon to keep a rkt-private database of valid allocations. But the allocation for each rkt container could be managed internally with locks files in /run/lock/rkt/uid/ (or some other rkt-specific directory). For example, the container using range [119603200, 119603200+65536] would lock the file /run/lock/rkt/uid/119603200. To decide the next allocation, rkt could just pick a range randomly within its high uid range. As long as rkt zeros the 16 least significant bits (because the container range is 65536), this locking scheme would successfully not allow overlapping ranges. 

But we still need to make sure no other software than rkt use rkt's high uid range. As far as I understand `/etc/subuid` can do that. If we have a system-user `rkt`, then `/etc/subuid` can contain one line (created at rkt's installation time) such as:

```
rkt:119603200:536870912
```

LXC uses `/etc/subuid` by default not to go outside of its territory (unless the user specifies a fixed mapping manually). And adduser(8) should take care of respecting `/etc/subuid` when allocating other ranges.

`/etc/subuid` might not have been designed for that, but it seems to me that it suits us. I am suggesting to use `/etc/subuid` for rkt's high uid range, not for individual rkt container uids allocation! Because the former can be static, and the latter will be dynamic. Does this look ok?

**Comment by filbranden** [comment]
> So that's 65536*8192 = 536870912 uids declared as private property of rkt. That's not even 0.1% of the complete 32 bit range, so that seems reasonable.

It's actually 12.5% of the 32-bit range (65536 \* 8192 / 4294967296 [2^32] = 0.125), but that still sounds reasonable to me (it's not like you'll have more than 7 container managers reserving more than that range of uids each.)

**Comment by poettering** [comment]
@alban yes, i want dynamic uid allocation in machined, but only for non-persistent allocation. persistent allocation i think is out-of-focus.

I really wouldn't bother /etc/subuid. It's  Debian-specific thing. I mean, the first column is "login name"... what's that even supposed to mean in the context of a uid-range? This is just weird...

I'd much rather make sure that NSS always reports the UIDs you want to own to be owned by you. Specifically: with the nss module I plan to add to systemd the UIDs of all running containers will have entries in getpwuid(). If I were you then I'd add another NSS module specifically for rkt, and then make it return something useful for the UID range you took possession of (for the full range really). Then, it's just a matter of always checking with NSS if a range is already taken: before anything takes posession of a UID range, it should verify with getpwuid() that there's nothing on the starting and end range... (of course, this is racy, but I think that's ok, this is just a safety net anyway. Also, this is of course incomplete, since it's innefficient to check the full range with NSS, hence check the first and the last one, and leave it at at that, which should be good enough, assuming that noone allocates less than 65536 UIDs per container).

**Comment by poettering** [comment]
Or to say this clearly: when i add dynamic uid allocation stuff to machined (for the non-persistent case, which I'll only do after the kernel learnt per-bind-mount uid-shifting options), then i will certainly not touch /etc/subuid, and not check it either. Instead, I'll just do NSS lookups and make sure the allocated uids show up in NSS.

**Comment by poettering** [comment]
With PR #537 all userns ids of containers registered via machined will now appear in NSS.

**Comment by poettering** [comment]
I guess the only thing I think machined should now implement is the dynamic transient UID range allocation of, but that can only happen when the kernel learns this new kind of uid mapping for mounts.

Renaming this issue accordingly.

**Comment by poettering** [comment]
Closing, as #3093 is merged since a while back.
