### ISSUE TITLE
Under devices group is systemd control but is not way to disable.

### ISSUE THREAD

**Issue by marian1000** [systemd/systemd#3214]
### Submission type
- [X ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> $ systemd --version
> systemd 229
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
> …

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16
### In case of bug report: Expected behaviour you didn't see

> Under group devices not want to see anithing because not have variable to se or unset.
### In case of bug report: Unexpected behaviour you saw

> $ ls -all /sys/fs/cgroup/devices
> total 0
> dr-xr-xr-x  5 root root   0 mai  7 08:58 .
> drwxr-xr-x 13 root root 340 mai  7 08:24 ..
> -rw-r--r--  1 root root   0 mai  7 08:26 cgroup.clone_children
> -rw-r--r--  1 root root   0 mai  7 08:26 cgroup.procs
> -r--r--r--  1 root root   0 mai  7 08:26 cgroup.sane_behavior
> --w-------  1 root root   0 mai  7 08:26 devices.allow
> --w-------  1 root root   0 mai  7 08:26 devices.deny
> -r--r--r--  1 root root   0 mai  7 08:26 devices.list
> drwxr-xr-x  2 root root   0 mai  7 08:24 init.scope
> -rw-r--r--  1 root root   0 mai  7 08:26 notify_on_release
> -rw-r--r--  1 root root   0 mai  7 08:26 release_agent
> drwxr-xr-x 67 root root   0 mai  7 08:24 system.slice
> -rw-r--r--  1 root root   0 mai  7 08:26 tasks
> drwxr-xr-x  2 root root   0 mai  7 08:24 user.slice
### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
I am sorry, but I don't understand a word. Can you please explain again what you are trying to say?

**Comment by marian1000** [comment]
On /sys/fs/cgroup/devices/ exists *.slice , init.scope subdirectory, but is enabled by default?

**Comment by keszybz** [comment]
This is still incomprehensible.

**Comment by poettering** [comment]
So, I still don't understand what you are trying to say, hence I am guessing: are you asking why the "devices" cgroup hierarchy isn't empty for you, even though you do not have it enabled for any unit?

If that's your question: cgroup membership always propagates up the tree, and sideways. that means, if you have a cgroup tree consisting of cgroups /a/b/c, /a/b/d and /a/e/f, and you make /a/b/c member of a specific cgroup hierarchy, then /a/b and /a are also made member of it, as well as /a/e, but not /a/e/f. This is because membership is propagated to all parents and all siblings.

Hence, if you find one or more units in the "devices" cgroups hierarchy then this is indication that one of it has a child that is a member. Try "tree -d" on /sys/fs/cgroup/devices/ to figure out which one that might be.

As one example, nspawn containers make use of the "devices" cgroup tree.

Does this answer your question?

**Comment by marian1000** [comment]
Not have any containers but i expect  under  /sys/fs/cgroup/devices/ to bee free by init.scope, user.slice, system.slice and to have variable to set like DefaultCPUAccounting and so.

**Comment by poettering** [comment]
Still don't understand a word. Closing.
