### ISSUE TITLE
Udev detects an Asrock LED controller as a joystick

### ISSUE THREAD

**Issue by KayJay7** [systemd/systemd#32773]
### systemd version the issue has been seen with

255

### Used distribution

Fedora 40

### Linux kernel version used

kernel-6.8.8-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

The LED controller is not detected as a Joystick.

### Unexpected behaviour you saw

Udev creates the `/dev/input/js0` file for the LED controller, and [builtin-input_id](https://github.com/systemd/systemd/blob/main/src/udev/udev-builtin-input_id.c) assigns it the `ID_INPUT_JOYSTICK=1` properties, which causes problem for other applications that use joysticks. The controller in question has usb id `26ce:01a2` but I cannot guarantee there aren't others with the same behavior.

This is a known issue with this device and there are workarounds available, but a proper solution would be preferred. [Here](https://github.com/foresto/joystickwake/pull/14) is the process of how we (me and @foresto) discovered the cause of the issue. In the end, we discovered that the LED controller reports having 6 joystick buttons and 11 axis, and because of that it looks like the builtin `input_id` function treats it as a joystick.

I have attached the output of `evemu_describe` for the device, as I have seen done in other issues, so the controller can possibly be added to some list of well known devices or dealt with in some way. I can provide more info and logs if needed.

### Steps to reproduce the problem

Not steps, the only requirements for the issue to arise are:
* Have an Asrock motherboard with an LED controller
* Use udev

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# EVEMU 1.3
# Kernel: 6.8.8-300.fc40.x86_64
# DMI: dmi:bvnAmericanMegatrendsInternational,LLC.:bvr2.02:bd11/17/2023:br5.32:svnASRock:pnB650ILightningWiFi:pvrDefaultstring:rvnASRock:rnB650ILightningWiFi:rvrDefaultstring:cvnDefaultstring:ct3:cvrDefaultstring:skuDefaultstring:
# Input device name: "ASRock LED Controller"
# Input device ID: bus 0x03 vendor 0x26ce product 0x1a2 version 0x110
# Supported events:
#   Event type 0 (EV_SYN)
#     Event code 0 (SYN_REPORT)
#     Event code 1 (SYN_CONFIG)
#     Event code 2 (SYN_MT_REPORT)
#     Event code 3 (SYN_DROPPED)
#     Event code 4 ((null))
#     Event code 5 ((null))
#     Event code 6 ((null))
#     Event code 7 ((null))
#     Event code 8 ((null))
#     Event code 9 ((null))
#     Event code 10 ((null))
#     Event code 11 ((null))
#     Event code 12 ((null))
#     Event code 13 ((null))
#     Event code 14 ((null))
#     Event code 15 (SYN_MAX)
#   Event type 1 (EV_KEY)
#     Event code 103 (KEY_UP)
#     Event code 105 (KEY_LEFT)
#     Event code 106 (KEY_RIGHT)
#     Event code 108 (KEY_DOWN)
#     Event code 116 (KEY_POWER)
#     Event code 138 (KEY_HELP)
#     Event code 139 (KEY_MENU)
#     Event code 142 (KEY_SLEEP)
#     Event code 143 (KEY_WAKEUP)
#     Event code 148 (KEY_PROG1)
#     Event code 174 (KEY_EXIT)
#     Event code 227 (KEY_SWITCHVIDEOMODE)
#     Event code 248 (KEY_MICMUTE)
#     Event code 314 (BTN_SELECT)
#     Event code 315 (BTN_START)
#     Event code 353 (KEY_SELECT)
#     Event code 356 (KEY_POWER2)
#     Event code 408 (KEY_RESTART)
#     Event code 438 (KEY_CONTEXT_MENU)
#   Event type 3 (EV_ABS)
#     Event code 0 (ABS_X)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 1 (ABS_Y)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 2 (ABS_Z)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 3 (ABS_RX)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 4 (ABS_RY)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 5 (ABS_RZ)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 6 (ABS_THROTTLE)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 7 (ABS_RUDDER)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 8 (ABS_WHEEL)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 16 (ABS_HAT0X)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#     Event code 40 (ABS_MISC)
#       Value        0
#       Min          0
#       Max        255
#       Fuzz         0
#       Flat         0
#       Resolution   0
#   Event type 4 (EV_MSC)
#     Event code 4 (MSC_SCAN)
# Properties:
N: ASRock LED Controller
I: 0003 26ce 01a2 0110
P: 00 00 00 00 00 00 00 00
B: 00 0b 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 80 16 10 00
B: 01 00 cc 10 00 00 40 00 00
B: 01 00 00 00 00 08 00 00 01
B: 01 00 00 00 00 00 00 00 0c
B: 01 00 00 00 00 12 00 00 00
B: 01 00 00 00 01 00 00 40 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 01 00 00 00 00 00 00 00 00
B: 02 00 00 00 00 00 00 00 00
B: 03 ff 01 01 00 00 01 00 00
B: 04 10 00 00 00 00 00 00 00
B: 05 00 00 00 00 00 00 00 00
B: 11 00 00 00 00 00 00 00 00
B: 12 00 00 00 00 00 00 00 00
B: 14 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
B: 15 00 00 00 00 00 00 00 00
A: 00 0 255 0 0 0
A: 01 0 255 0 0 0
A: 02 0 255 0 0 0
A: 03 0 255 0 0 0
A: 04 0 255 0 0 0
A: 05 0 255 0 0 0
A: 06 0 255 0 0 0
A: 07 0 255 0 0 0
A: 08 0 255 0 0 0
A: 10 0 255 0 0 0
A: 28 0 255 0 0 0
```

**Comment by yuwata** [comment]
BTW, 51-these-are-not-joysticks-rm.rules seems to be terrible workaround...

**Comment by KayJay7** [comment]
> BTW, 51-these-are-not-joysticks-rm.rules seems to be terrible workaround...

Yes, @foresto has already opened an issue suggesting better solutions on the repository that maintains the blacklist: https://github.com/denilsonsa/udev-joystick-blacklist/issues/58

**Comment by yuwata** [comment]
And the better way to workaround such misdetection is updating hwdb.d/60-input-id.hwdb.
Could you submit a patch?

**Comment by yuwata** [comment]
Should be something like that:
```diff
diff --git a/hwdb.d/60-input-id.hwdb b/hwdb.d/60-input-id.hwdb
index eff160cd31..37db06c9d8 100644
--- a/hwdb.d/60-input-id.hwdb
+++ b/hwdb.d/60-input-id.hwdb
@@ -79,3 +79,7 @@ id-input:modalias:input:b0003v068Ep00F2*
 # TEX Shinobi Trackpoint
 id-input:modalias:input:b0003v04D9p0407e0111-e0,1,2,4*
  ID_INPUT_POINTINGSTICK=1
+
+# ASRock LED Controller
+id-input:modalias:input:b0003v26CEp01A2*
+ ID_INPUT_JOYSTICK=0
```

**Comment by KayJay7** [comment]
Sure, I can

**Comment by yuwata** [comment]
> It occurs to me that software looking for ID_INPUT_JOYSTICK without additional logic to interpret its value might treat a 0 value the same as a 1.

Could you report the issue to an bug tracker of the software?

> To avoid that problem, perhaps it would make sense to have this rule set it to an empty value instead?

Yes, an empty string should be supported. Feel free to use `ID_INPUT_JOYSTICK=` (without value).

**Comment by yuwata** [comment]
> I notice that the `well_known_keyboard_keys` array in udev-builtin-input_id.c seems to be a more general approach to solving problems like this. I wonder under what circumstances it would make sense to include some of this device's "keys" (as found by evemu_describe) in that array, rather than making individual device-specific hwdb entries, given that there are dozens of such devices.
> 
> I suppose expanding the general approach would have the risk of matching devices that it shouldn't. Does the udev project have a policy for deciding which approach to use?

Yeah, maybe. But I am not familiar with what kind of keys should be added there...

**Comment by KayJay7** [comment]
> Yes, an empty string should be supported. Feel free to use `ID_INPUT_JOYSTICK=` (without value).

Even leaving it blank sets the property to 0. Though, among the programs I have tested, only `jstest-gtk` (which seems to look for `/dev/input/js*`) and the dolphin emulator (which probably look for the property but not it's value) have mistaken it for a controller.

**Comment by KayJay7** [comment]
It persisted after rebooting. And I have updated it with `systemd-hwdb update` and `udevadm trigger`. Maybe the rules in hwdb.d work differently from the ones in rules.d, after all if I run `udevadm verify` in hwdb.d it shows errors everywhere

**Comment by KayJay7** [comment]
Wait, I made an error. It does not set it to `0`. But it sets it to empty

**Comment by KayJay7** [comment]
Now with `udevadm test` i get

```
DEVPATH=/devices/pci0000:00/0000:00:08.3/0000:10:00.0/usb7/7-1/7-1:1.0/0003:26CE:01A2.0001/input/input2/js0
DEVNAME=/dev/input/js0
MAJOR=13
MINOR=0
SUBSYSTEM=input
ACTION=add
TAGS=:ASRock_Polychrome_USB:seat:uaccess:
ID_INPUT=
ID_INPUT_JOYSTICK=
ID_INPUT_KEY=
CURRENT_TAGS=:ASRock_Polychrome_USB:seat:uaccess:
ID_BUS=usb
ID_MODEL=LED_Controller
ID_MODEL_ENC=LED\x20Controller
ID_MODEL_ID=01a2
ID_SERIAL=ASRock_LED_Controller_A02019100900
ID_SERIAL_SHORT=A02019100900
ID_VENDOR=ASRock
ID_VENDOR_ENC=ASRock
ID_VENDOR_ID=26ce
ID_REVISION=0000
ID_TYPE=hid
ID_USB_MODEL=LED_Controller
ID_USB_MODEL_ENC=LED\x20Controller
ID_USB_MODEL_ID=01a2
ID_USB_SERIAL=ASRock_LED_Controller_A02019100900
ID_USB_SERIAL_SHORT=A02019100900
ID_USB_VENDOR=ASRock
ID_USB_VENDOR_ENC=ASRock
ID_USB_VENDOR_ID=26ce
ID_USB_REVISION=0000
ID_USB_TYPE=hid
ID_USB_INTERFACES=:030000:
ID_USB_INTERFACE_NUM=00
ID_USB_DRIVER=usbhid
ID_PATH_WITH_USB_REVISION=pci-0000:10:00.0-usbv2-0:1:1.0
ID_PATH=pci-0000:10:00.0-usb-0:1:1.0
ID_PATH_TAG=pci-0000_10_00_0-usb-0_1_1_0
ID_FOR_SEAT=input-pci-0000_10_00_0-usb-0_1_1_0
run: 'uaccess'
```

And dolphin still detects it

**Comment by yuwata** [comment]
> And dolphin still detects it.

Even after `udevadm trigger` or reboot the machine?

**Comment by KayJay7** [comment]
Yes, it lists it as `evdev/0/Asrock LED Controller`

**Comment by yuwata** [comment]
You mean, that's expected?

**Comment by KayJay7** [comment]
It's how it detected it before. But it means it still detects it

**Comment by KayJay7** [comment]
I have opened the PR [here](https://github.com/systemd/systemd/pull/32775)

**Comment by poettering** [comment]
> Udev creates the `/dev/input/js0` file for the LED controller,

Note that this is wrong/misleading. udev does not create device nodes, the kernel does this entirely on its own, udev then just changes access modes/ACLs and maintains metadata for it.

In this case this means that whatever we do in userspace: the kernel apparently thinks this is a joystick and thus created /dev/input/js0 for it. So to me it appears that this probably should be dealt with in the kernel properly too, since you don't want such a device to show up if the thing is not actually a joystick.

@whot what's the correct way to deal with such devices, so that the kernel doesn't create a JS device for them?

**Comment by scaronni** [comment]
Just hijacking, the ASRock LED Controller issue spins up from this: https://github.com/denilsonsa/udev-joystick-blacklist

Which I included in the Fedora Steam package long time ago to solve users' issues. This of course would be better as an hwdb with quirks and even better fixed properly in the kernel.

Since this has never been fixed in the kernel and the udev rules just touch the device files without changing what udev sees I think I will switch it all to a custom hwdb, at least short term.

**Comment by whot** [comment]
@KayJay7: I'm wondering: is this a HID device? Check with [`hid-recorder` from hidtools](https://gitlab.freedesktop.org/libevdev/hid-tools/) - if so we might be able to fix it with [udev-hid-bpf](https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/).

fwiw, please use `libinput record` instead of `evemu` because it would've answered that for us :) evemu is effectively unmaintained, `libinput record` still sees useful features added.

> Just hijacking, the ASRock LED Controller issue spins up from this: https://github.com/denilsonsa/udev-joystick-blacklist

@scaronni: fwiw, [libwacom](https://github.com/linuxwacom/libwacom) also ships a hwdb to explicitly mark every known tablet as `ID_INPUT_TABLET` and remove `ID_INPUT_JOYSTICK`. See `65-libwacom.hwdb` on your local machine, it's probably there.

and btw, I'd be nice if you could update `generate_rules.py` to also print a comment with the device name, makes debugging a bit easier than just staring at a bunch of hex numbers :)

Also, if those are objectively wrong defaults it'd be great to add the overrides to `60-input-id.hwdb` so we don't need a separate repo for those.


> @whot what's the correct way to deal with such devices, so that the kernel doesn't create a JS device for them?

`drivers/input/joydev.c` seems to have its own detection system including a blacklist so I guess it'd have to be added to that. From a quick check this device falls "afoul" of the `ABS_THROTTLE` check - because of that it's handled as joystick device. That check is incredibly simple but then again it's understandable - it's easier to create a `/dev/js` file and have userspace ignore it than make userspace handle a device that's not exposed at all.

>  This comment in Dolphin's evdev.cpp makes me wonder if the author was unaware of properties like ID_INPUT_JOYSTICK:

Or an even simpler approach, esp. if you don't want to trust the properties:

```c
sysname = udev_device_get_sysname(device);
if (strncmp("event", sysname, 5)) { ... }
```
unfortunately issues are disabled in the dolphin repo.

**Comment by KayJay7** [comment]
> @KayJay7: I'm wondering: is this a HID device? Check with [`hid-recorder` from hidtools](https://gitlab.freedesktop.org/libevdev/hid-tools/) - if so we might be able to fix it with [udev-hid-bpf](https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/).

With `hid-recorder` I get this: [hid-record.log](https://github.com/systemd/systemd/files/15319695/hid-record.log)
Those events are triggered when I change settings in OpenRGB.

> fwiw, please use `libinput record` instead of `evemu` because it would've answered that for us :) evemu is effectively unmaintained, `libinput record` still sees useful features added.

With `libinput record` I get this: [libinput-record.log](https://github.com/systemd/systemd/files/15319736/libinput-record.log)
Here it doesn't show any event when I change settings, I don't know if it means something.

**Comment by KayJay7** [comment]
@whot : For comparison, this is what the other LED controller (the corsair one, which doesn't pretend to be a joystick) looks like in `hid-record`: [hid-record-corsair.log](https://github.com/systemd/systemd/files/15319896/hid-record-corsair.log). Those events are also triggered when I change settings, much like the other controller. And it doesn't show up in `libinput record` which I guess makes sense since it's not an input device.

**Comment by whot** [comment]
> With hid-recorder I get this: [hid-record.log](https://github.com/systemd/systemd/files/15319695/hid-record.log)

Quick explanation of this report descriptor: this device basically declares every usage from 0 to 255 in the Generic Desktop usage page. That would translate into pretty much every axis and a few random buttons, one of which will be the wheel usage which translates into `ABS_THROTTLE` in evdev and that causes the device to be picked up as joystick. The events are a bit... confusing, each event is an array of 64 1-byte values (report count * report size) but the values make no sense as they are.

It looks very much like they're treated like a byte array with whatever data. So my suspicion is simply that the manufacturer *should* have used a vendor usage page but didn't for whatever reason and since it probably works with their driver under windows, it passed QA.
There are some feature reports (i.e. configuration) but unless you know the magic to send back to the device... *shrug*.

OTOH the corsair one declares a vendor specific page (i.e. "magic sauce") and unless there's a specific driver for it the hid-generic code won't map it to anything in evdev.


Changes are you could write a BPF in [udev-hid-bpf](https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/) to fix the report descriptor - change the first two bytes (Usage Page) from `0x05, 0x01` to the three bytes `0x06, 0x00, 0xff` (vendor page 1) and this problem should go away, and chances are the device will keep working because I doubt any vendor driver for this device would even look at the descriptor.
