### ISSUE TITLE
systemd-nspawn --network-veth broken in v256-rc3

### ISSUE THREAD

**Issue by 4nd3r** [systemd/systemd#33004]
### systemd version the issue has been seen with

v256-rc3 (installed from distro repo)

### Used distribution

Debian Sid

### Linux kernel version used

6.8.9-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

with v255 packets flow
```
root@test:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=57 time=9.09 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=57 time=8.48 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=57 time=14.9 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 8.481/10.830/14.917/2.900 ms
```

### Unexpected behaviour you saw

with v256-rc3 they do not
```
root@test:~# ip r
default via 192.168.175.241 dev host0 proto dhcp src 192.168.175.253 metric 1024 
172.16.1.1 via 192.168.175.241 dev host0 proto dhcp src 192.168.175.253 metric 1024 
192.168.175.240/28 dev host0 proto kernel scope link src 192.168.175.253 metric 1024 
192.168.175.241 dev host0 proto dhcp scope link src 192.168.175.253 metric 1024 
root@test:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2030ms
```

### Steps to reproduce the problem

something like...
```
mkosi -o test -t tar --compress-output=no -p systemd-container -p iputils-ping -p iproute2
machinectl import-tar test.tar
machinectl start test
machinectl shell test
```
...and `ping` something

`--network-veth` is in `systemd-nspawn@.service` and that's why I think this is broken.

```
$ systemctl cat systemd-nspawn@.service | grep Exec
ExecStart=systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=%i
```

### Additional program output to the terminal or log subsystem illustrating the issue
nft rules with v256-rc3
```
# nft list ruleset
table ip io.systemd.nat {
        set masq_saddr {
                type ipv4_addr
                flags interval
                elements = { 192.168.175.240/28 }
        }

        map map_port_ipport {
                type inet_proto . inet_service : ipv4_addr . inet_service
        }

        chain prerouting {
                type nat hook prerouting priority dstnat + 1; policy accept;
                fib daddr type local dnat ip to meta l4proto . th dport map @map_port_ipport
        }

        chain output {
                type nat hook output priority dstnat + 1; policy accept;
                ip daddr != 127.0.0.0/8 oif "lo" dnat ip to meta l4proto . th dport map @map_port_ipport
        }

        chain postrouting {
                type nat hook postrouting priority srcnat + 1; policy accept;
                ip saddr @masq_saddr masquerade
        }
}
```

tcpdump with v256-rc3
```
# tcpdump -i any -n icmp
15:18:38.498929 ve-test In  IP 192.168.175.253 > 8.8.8.8: ICMP echo request, id 62, seq 1, length 64
15:18:38.498986 wlan0 Out IP 172.16.1.23 > 8.8.8.8: ICMP echo request, id 62, seq 1, length 64
15:18:38.511402 wlan0 In  IP 8.8.8.8 > 172.16.1.23: ICMP echo reply, id 62, seq 1, length 64
```
reply comes back to host (`172.16.1.23`), but is not delivered to container (`192.168.175.253`).

**Comment by yuwata** [comment]
Please set the following in your upstream interface:
```
# /etc/systemd/network/eth0.network
[Network]
IPv4Forwarding=yes
IPv6Forwarding=yes
```
Or, please set the following in networkd.conf:
```
# /etc/systemd/networkd.conf.d/10-enable-ip-forwarding.conf
[Network]
IPv4Forwarding=yes
IPv6Forwarding=yes
```

Background: since v256, `IPForward=` is deprecated and replaced with the per-link settings. Previously, `IPMasquerade=` implies the global `IPForward=` setting, but now it implies per-link settings.
The change actually breaks backward compatibility. But, I have no idea how to make it work with new per-link settings.

**Comment by sfan5** [comment]
Turns out what I noted here https://github.com/systemd/systemd/issues/33414#issuecomment-2227348049 is actually this issue.

I am a bit puzzled by the solution here being "just document it".
systemd goes to a bunch of effort to provide an out-of-the box configuration for networking inside/outside nspawn containers, complete with automatically configured NAT rules. And now it's okay that users are left with a setup that looks like it should work but doesn't?
Not to mention that the UX of this is awful. It takes some careful investigation of the relevant `.network` file as well as reading `systemd.network(5)` to discover the intended fix.

Unfortunately I can't think of a good solution either, but a few thoughts:
* `systemd-nspawn(1)` does not mention that `--network-veth` is broken by default and requires further configuration
* maybe remove `IPMasquerade` from `80-container-ve.network` to make it obvious that manual configuration is required?

**Comment by 4nd3r** [comment]
@sfan5 I agree. 

But closed issues most probably go unnoticed. Maybe new issue works better in terms of visibility?

**Comment by sfan5** [comment]
perhaps @yuwata could chime in, but a new issue also sounds like a good idea
