### ISSUE TITLE
An extra argument '+4' is always passed to editors invoked with 'systemctl edit'

### ISSUE THREAD

**Issue by seinolab** [systemd/systemd#33023]
### systemd version the issue has been seen with

255

### Used distribution

Fedora 40

### Linux kernel version used

6.8.10-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

(case 1)
tee /etc/systemd/system/foo.service.d/.#override.confc277508c0a33bd17

(case 2)
vim /etc/systemd/system/foo.service.d/.#override.confc277508c0a33bd17

### Unexpected behaviour you saw

(case 1)
tee +4 /etc/systemd/system/foo.service.d/.#override.confc277508c0a33bd17

(case 2)
vim +4 /etc/systemd/system/foo.service.d/.#override.confc277508c0a33bd17

### Steps to reproduce the problem

(case 1)
SYSTEMD_EDITOR=tee systemctl edit foo.service
(on another terminal)
ps aux | grep tee

(case 2)
systemctl edit foo.service
(on another terminal)
ps aux | grep vim

**Comment by YHNdnzj** [comment]
This is intentional: https://github.com/systemd/systemd/blob/bf7d672f5db3e55f2edd7426ed4c1fab454a56df/src/shared/edit-util.c#L258-L263

All major editors should support this format?

Also note that `tee` is not a valid interactive editor. `systemctl` and other tools use `on_tty()` to detect if `edit` is being invoked with tty attached and refuse the case where they aren't. With systemd v256 there would be native support for non-interactive edits with the new `--stdin` option.

**Comment by seinolab** [comment]
Thank you for your response.
I got it.  I need the use of a non-interactive editor for automatic setup.
I'm looking forward to systemd v256.

**Comment by fellerts** [comment]
@YHNdnzj 
> All major editors should support this format?
I don't believe BusyBox vi, commonly used as $EDITOR on embedded targets, supports this at all.

**Comment by poettering** [comment]
well, busybox, what can you say. We don't really work with that anyway, we require util-linux mount + libmount anyway.

Seems to me this is a bug in busybox. Please report it to busybox.

**Comment by nero** [comment]
@poettering What does "what can you say" mean? Is busybox explicitly not supported, like musl?

**Comment by poettering** [comment]
@nero we depend on libmount from the util-linux, unconditionally. See README.

You cannot build systemd without util-linux, hence why bother with busybox? In particular as busybox, let's say, has certain code quality challenges...

I mean, sure, if you want to waste resources, you can always add busybox in addition to util-linux, but that just means duplication?

If you think that busybox reimplementation of vi is your editor of choice, by all means use it, but maybe fix it so that implements the same cmdline interface as literally *any* other editor.

**Comment by poettering** [comment]
Also, I mean, if a project has a Link "Life without systemd" on its website right at the top, which links to a file "kill_it_with_fire.txt" then maybe there are better projects to combine with systemd, and to work with? busybox is probably as toxic as a software project can be, no?

**Comment by fellerts** [comment]
Fair point. In pursuit of diplomacy I've submitted a [patch](http://lists.busybox.net/pipermail/busybox/2024-June/090778.html).

**Comment by poettering** [comment]
> Fair point. In pursuit of diplomacy I've submitted a [patch](http://lists.busybox.net/pipermail/busybox/2024-June/090778.html) to BusyBox.

That patch paints this as a systemd thing. It's not. This has been standard among UNIX editors since a *looooong* time, long before systemd came to be. Busybox is the outlier here really, and it's not systemd's fault that it is that.

Hence, I doubt this was very "diplomatic", it puts blame on systemd, where there really isn't any.

**Comment by poettering** [comment]
I mean, even fuckin "ed" supports that syntax (https://manpages.debian.org/testing/ed/editor.1.en.html). I am sorry busybox hasn't caught up with an editor that basically is still at a feature level from 1969.

**Comment by mooreye** [comment]
I depend on the `SYSTEMD_EDITOR=tee` trick in some of my scripts. I was losing my mind wondering why a `+4` named file always appeared in working directory after editing like this:

```
SYSTEMD_EDITOR=tee systemctl edit foo << EOF
[Unit]
ExecStartPRe=...
EOF
```

Now I know. Is there a better way then to non-interactively edit systemd units, or at least avoid the creation of `+4` file?

**Comment by YHNdnzj** [comment]
> I depend on the `SYSTEMD_EDITOR=tee` trick in some of my scripts. I was losing my mind wondering why a `+4` named file always appeared in working directory after editing like this:
> 
> ```
> SYSTEMD_EDITOR=tee systemctl edit foo << EOF
> [Unit]
> ExecStartPre=...
> EOF
> ```
> 
> Now I know. Is there a better way then to non-interactively edit systemd units, or at least avoid the creation of `+4` file, with current systemd version?

systemctl/networkctl supports `--stdin` option which implements exactly that.

**Comment by YHNdnzj** [comment]
(assuming "current" being v256/v257, that is)
