### ISSUE TITLE
[RFE] Forward machine IP resolution to host

### ISSUE THREAD

**Issue by Sufflope** [systemd/systemd#3308]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 222
### Used distribution

> Fedora 23

Hello,

on a host running Fedora 23, with systemd 222, I set up two containers (Fedora 23 too) in /var/lib/machines with "dnf --installroot ..." ; the host and both containers have systemd-networkd and systemd-resolved enabled and started. Containers are started with "machinectl start name".

Container one gets 10.0.0.2 address with 10.0.0.1 gateway on ve-one interface on host ; container two gets 10.0.0.18 with 10.0.0.17 gateway.

I can ping the internet, wget web pages... from both containers ; from host I can "ping one" or "ping two" and nss-mymachines resolution (I guess) does its magic and it pings. From container one I can "ping one" and it pings itself.

However, if I "ping two" from container one, I get "unknown host two". It is not a network problem because I can "ping 10.0.0.18" (two's IP) from inside one and it works (it even works with a "nc -l 2626" on two and "nc 10.0.0.18 2626" on one, I can netcat-talk between them).

Could we have nss-mymachines (or whoever) resolve other containers' names from inside a container ?

**Comment by poettering** [comment]
nss-myhostname needs to have privileged access into a container to do what it does. Entering a container from the host is a safe operation, since the host is more privileged than the container. However, the opposite direction wozuldn't be safe: allowing the containe to exit its own environment to determine the configuration of the host, and then from there enter the execution domain of any other container is a security problem.

I think the much better fix for this problem is to place both containers on the same virtual broadcast domain (or in other words: on the same virtual ethernet network). This way name resolution between the two containers and the host will work in all directions, just like that. As it turns out, the upcoming v230 release (see PR #3209) makes a setup like this very easy: simply place two .nspawn files named after the two containers in /etc/systemd/nspawn, and write into it:

```
[Network]
Zone=foobar
```

This will create virtual broadcast domain, named "foobar", and both containers will be placed on it, using only a single IP subnet, and direct connectivity.

On older versions of systemd/nspawn you can implement something similar, by using the Bridge= logic, and explicitly creating a bridge in networkd for the devices, via .netdev files. This would implement pretty much the same thing, except that it is a lot less automatic.

Anyway, closing this RFE bug now, as I think with the zones logic is the better approach to solving this and is already implemented now.

**Comment by Sufflope** [comment]
I was not thinking about "escaping" container, but maybe having eg.

> hosts:      files mymachines resolve myhostname

in container's /etc/nsswitch.conf, and then when container's files and mymachines fail (because they only look into container's data), try with systemd-resolved which would somehow have a secure channel to ask host's systemd-resolved (I think container's systemd knows it is contained, or am I mistaken?), which would itself find the machine's IP and inform container's systemd-resolved?

With the new network zone feature, will containers only be pingable from each other (which is already the case with my setup, the problem is they are not resolvable by name) or will their names be resolvable thanks to avahi (or any other local network shenanigan)?

**Comment by poettering** [comment]
well, I am not convinced such a "secure channel" between resolveds would be a good idea. I mean, the network is already a much better channel, and I'd actually see it as a benefit that the admin can choose easily which containers are located on the same broadcast link and which ones aren't, and thus which ones can see each other, and which ones can't.

The network zone stuff will create your own private ethernet link between the selected containers and the host. Thus, if you have containers A and B, running on a host H, then there will be a little Ethernet network, with all three, A + B + H on it, and all can see each other. The LLMNR naming logic implemented in resolved between them will just work, so that you can ping the host and all containers under their respective names from each other.

Or in other words: each network "zone" introduced this way creates a new host name "namespace", that is shared between the participating containers and the host, and is private to the three, and not accessible, or corruptible by any containers not in the same "zone".

And yes, LLMNR is pretty much equivalent to MulticastDNS when it comes to name resolution, and hence yes, Avahi will do the right thing that you are asking for in such setups too. However, given that LLMNR is simpler for this purpose (as it is implemented in resolved directly, and does not require suffixing everything with .local) I'd really go with that.
