### ISSUE TITLE
Race condition in repart cleanup of luks device

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#33129]
### systemd version the issue has been seen with

main

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

In repart we allow setting up encrypted partitions. To set up an encrypted partition, we use libcryptsetup to activate the luks device and then open a file descriptor to it which we then BSD lock to avoid udev from messing with it while we're operating on it. However, when we want to clean up the device, we have to close the file descriptor before deactivating the device with libcryptsetup, which leaves open a window for udev to start messing with the luks device, causing the deactivation to fail with EBUSY.

Ideally we would keep the lock intact while we deactivate the luks device so that there is no window where we don't have the lock while deactivating the lock but I'm not sure if libcryptsetup supports such a scenario.

@oniko Any suggestions on how we can handle this race condition?

**Comment by mbroz** [comment]
Device mapper cannot deactivate device if there is nonzero open count for device. But it you use libcryptsetup (not CLI cryptsetup wrapper), you can try to use CRYPT_ACTIVATE_PRIVATE activation flag, this should set the device-mapper udev rules  skips some device scanning. But this also means that you cannot depend on various symlinks as blkid is not run on the device (this will confuse many installers etc).

I have no idea why you need to activate the crypt device in the first place, so use it with care, perhaps you cannot use the private flag.

TBH I am not sure if private flag  also disables close-on-write scan for the dm-device (it should) what is perhaps the problem you see.

You can also use CRYPT_DEACTIVATE_DEFERRED in libcryptsetup deactivation call - this will setup kernel to remove device once the last user disappears (so deactivate call will not erro with EBUSY). But it perhaps means you need to wait until this happens.

But anyone can add own rules reacting to various events, there will be always some "race" possible.

@oniko could add more details

**Comment by poettering** [comment]
some ideas:

1. we could ensure that repart names the DM devices it creates some specific way (e.g. repart-temp-XYZ), and then have an udev rule match against that (e.g. repart-temp-*) and turn off the close-on-write rescan logic in that case
2. we could make repart first destroy the device with CRYPT_DEACTIVATE_DEFERRED first, and then maybe have an udev rule that tells udev to not do the rescan thing when that flag is found to be set on a device (assuming we can read that flag from sysfs somewhere). Problem: we want synchronous destruction, so we should immediately make repart destroy the device without CRYPT_DEACTIVATE_DEFERRED so that we can synchronously wait for it (though I wonder if this would actually work, maybe DM would just return EBUSY on this second destroy, and not allow us to wait for the destruction to complete?)

**Comment by DaanDeMeyer** [comment]
Haven't seen this in a while
