### ISSUE TITLE
tmpfiles: preserve open files

### ISSUE THREAD

**Issue by barak** [systemd/systemd#33158]
### Component

systemd-tmpfiles

### Is your feature request related to a problem? Please describe

Cleaning up temporary files is important, but it is also important to avoid inappropriate deletion. In particular, if a file is open (e.g., as a log file to which lines are appended) it should not be eligible for deletion, regardless of how long it's been since a read or write has occurred.

### Describe the solution you'd like

The `statx(2)` system call can be used to tell if a file is open, as done by `fuser(1)`, and I'd suggest its use here.

**Comment by arvidjaar** [comment]
> The `statx(2)` system call can be used to tell if a file is open

Which field in `statx` returns this information?

**Comment by bluca** [comment]
This is already implemented: https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html#:~:text=Note%20that%20while%20the%20aging%20algorithm

**Comment by barak** [comment]
I'm sorry, it's not statx; it looks like fuser grovels around in /proc/PID/fd/ to look for the file in question.

But @bluca, I don't understand what you're saying is already implemented. Applications need to take an flock on a file in order to keep it from consideration. This doesn't happen from just opening a file for write without locking it, as would be the case for a shell script with output redirected to a file, say. Or did I miss something?

**Comment by poettering** [comment]
We do not implement anything like this currently, hence dropping the label.

The thing though is that Linux has no reasonably API for implementing this. And even if it had something like an API to query "is this file open right now?" tying automatic deletion to it would necessarily be racy, since between the time we decide the file is unused and we remove it some app might reopen it again.

I think it is highly unlikely that kernel folks are going to add anything like this for us though, given that we actually delete dentries, not inodes here, and hence an api for checking if an inode is open would even be the wrong thing to have, and dentries you cannot really have open anyway.

Moreover, automatic clean-up has been a thing we have been doing in /tmp since basically its inception, hence I am pretty sure apps must be ready for the mess that /tmp is.

Or in other words, if you want a place with different cleanup semantics, then usr /run/<myapp> ro $XDG_RUNTIME_DIR/<myapps> or so, but /tmp/ i am pretty sure we should leave as fucked as it is.

we document in detail how to use /tmp correctly btw:

https://systemd.io/TEMPORARY_DIRECTORIES/

**Comment by barak** [comment]
Yeah, it's annoying that the kernel *knows* a file is open, but doesn't have an API to tell you. I don't think there's an efficient way to implement this, plus even if it was, there are issues with it being not-quite-what-you-want due to race conditions and such.
