### ISSUE TITLE
Enabling systemd-homed-firstboot.service by default has a medium-high chance of causing breakage

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#33249]
Both mkosi and Fedora Cloud's images got stuck during boot in CI testing because of the prompt from systemd-homed-firstboot.service. We might want to consider not enabling this by default and instead simply requiring users that want it in their images to enable it themselves.

**Comment by poettering** [comment]
What does fedora do with systemd-firstboot, i.e. the other tool that prompts questions like this?

**Comment by keszybz** [comment]
Fedora did disable `systemd-homed-firstboot.service`, exactly because of the issue that Daan described. https://pagure.io/fedora-kiwi-descriptions/pull-request/56, but there was also more discussion in on of the Bodhi updates, but I can't find it now.

So I think this is the right thing to do. `systemd-homed-firstboot.service` would only be used in very special circumstances. If somebody builds an image where they want the image to invoke the "first boot" paths, but actually create a live user, they can easily also enable the service.
