### ISSUE TITLE
RFE: Environment variable to stop systemd-run from setting a window title

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#33301]
### Component

systemd-run

### Is your feature request related to a problem? Please describe

When `systemd-run --pty` is active, it overwrites the previously-set terminal title with a copy of the command being run (plus a colourful dot for whatever reason). This is 1) hideous but also 2) makes the title actually useless in situations when something else than an interactive shell is run – my backup tool uses `systemd-run --pty borg` as part of the process, so while it would previously show what job was being run, now it only shows a mile-long borg command line.

### Describe the solution you'd like

Would like either a systemd-run option or an environment variable to disable both the background-setting and the title-setting.

### Describe alternatives you've considered

I was considering switching my backup tool back to using `sudo` or `doas` (as it already had the fallback code from back when systemd-run was still new).

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by poettering** [comment]
> (plus a colourful dot for whatever reason). This is 1) hideous but also 2) makes the title actually useless in situations when something else than an interactive shell is run – my backup tool uses `systemd-run --pty borg` as part of the process, so while it would previously show what job was being run, now it only shows a mile-long borg command line.

i don't grok this? what did it previously show precisely? what does "previously showed job" mean? what is "job"?

if the cmdline is too long for display and the WM doesn't sensible shorten it, we maybe should just ellipsize it ourselves, we have easy calls for that.

the colorful dot tells you about raised privs: if it's red. Or if you enetered a container or a VM.

**Comment by poettering** [comment]
anyway, please explain more precisely what the problem is, i.e.:

1. you don't like the dot?
2. we don't ellipsize the title?
3. …?

**Comment by AdrianVovk** [comment]
To rephrase OP's issue:

Lots of things set the terminal title, but `systemd-run` (or `run0`) will ask the terminal to change the title and the terminal will happily do that. So if you've configured your terminal to have an informational title of some kind, `systemd-run` will trample all over that.

In this case, it sounds like the user has some sort of orchestration infrastructure that sets the terminal title to something meaningful and then runs some tool with privileges. For example, maybe they have a script that looks something like this:

```bash
#!/usr/bin/bash

[...]

for location in /path/a /path/b /path/c /path/d; do
   set_terminal_title "Backup: $location"
   systemd-run --pty borg --lots --of --args $location
done
```

The script should change the terminal title to indicate the status of the script. So let's say the title should say "Backup: /path/c". Instead, it will say "🔴 borg --lots --of --args /path/c", which makes the output a lot less useful

> if the cmdline is too long for display and the WM doesn't sensible shorten it, we maybe should just ellipsize it ourselves, we have easy calls for that.

IMO, strong NACK. Truncating the title of the tab belongs to the UI, not to command line tools. The UI knows how much text will fit in the tab title, `systemd-run` does not.

> the colorful dot tells you about raised privs: if it's red. Or if you enetered a container or a VM.

IMO, I'm not the biggest fan of this (and the background changing) either.

The background changing can be just straight-up buggy when faced with ncurses applications, especially if those applications crash. Terminal emulators can't handle full-screen background color changes very well whenever they have to scroll, or resize:

![Screenshot from 2024-06-18 17-02-31](https://github.com/systemd/systemd/assets/11251606/aed426cd-2e13-42b0-a0ca-912136bb960f)

It is also entirely unaware of the color scheme of the terminal, and so it has the nice side-effect of making text in the terminal hard-to-read due to lack of contrast.

Essentially, this should really be the job of the terminal emulator, at least for interactive tasks. Modern GNOME terminal emulators will indicate when you're running something as root, or in a container, by recoloring the appropriate parts of a window red / purple / whatever, and changing the terminal color scheme appropriately. For instance:

![Screenshot from 2024-06-18 17-08-48](https://github.com/systemd/systemd/assets/11251606/50832c49-873e-4176-9d0c-09d1ccca92c9)

The red dot is entirely redundant here, and actually counter-productive in some cases because this specific terminal emulator will actually show the icon of the container manager if it detects that you're inside of a container.

I understand it's for situations like the VT where there's no terminal emulator to save you. Maybe we should just detect `TERM=Linux` and turn it on then. Maybe we turn off the recoloring when you're in an interactive terminal? IDK the solution here but this pretty printing logic makes it feel buggy...

Still not daily driving this on Fedora w/ v256 (Don't have v256 yet), so maybe this was all fixed between my last build of it & release. But I suspect not, most of these bugs are caused by the terminal emulator.

**Comment by heldderarbeit** [comment]
> the colorful dot tells you about raised privs: if it's red. Or if you enetered a container or a VM.

Just my 2 cents: The red dot emoji reminds me of a record button (conditioned by usage in camera apps), so when i see this icon, i expect it is indicating that the screen is recorded.

Maybe there is a better way to indicate raised privileges, but i doubt i can be done with an emoji. I can't think of a fitting emoji for this use case.

**Comment by poettering** [comment]
> IMO, strong NACK. Truncating the title of the tab belongs to the UI, not to command line tools. The UI knows how much text will fit in the tab title, `systemd-run` does not.

Well, not sure I agree. Right now we'd happily send a 1MB title to the terminal, which doesn't really make much sense. We should ellipsize overly long stuff. What's up for discussion though is just where to place the cutoff, i.e. already after 100ch or so, or more at 16K or so?

**Comment by poettering** [comment]
> Terminal emulators can't handle full-screen background color changes very well whenever they have to scroll, or resize:

Yeah, they really should take the bg color of the last character of a visible line into account when rebreaking things and inserting new whitespace.

**Comment by poettering** [comment]
> It is also entirely unaware of the color scheme of the terminal, and so it has the nice side-effect of making text in the terminal hard-to-read due to lack of contrast.

That's not actually true. We read the bg color from the terminal, and then shift it into a red hue. Maybe the algorithm for shifting the hue could be tweaked, but it's not true that we are "entirely unaware" of the color scheme. We are very much aware.

**Comment by poettering** [comment]
> Essentially, this should really be the job of the terminal emulator, at least for interactive tasks. Modern GNOME terminal emulators will indicate when you're running something as root, or in a container, by recoloring the appropriate parts of a window red / purple / whatever, and changing the terminal color scheme appropriately.

So I have seen the feature, and I really dislike the implementation of it, because it just keeps a list of command names it binds this too. That's just awfully hackish. I wish they'd come up with a proper ANSI OSC sequence instead so that we can tell them about this. But more importantly: this doesn't know the character cell where the priv change is placed, hence they tint the window title or something else that is "global", instead of telling me exactly in the output which part was privileged and which was not. I think this is really important to visualize actually, and they cannot do that, we however can.

I'd be happy to report such transitions to terminals via new OSC sequences, we can just make some new sequences up. But not sure there's interest in that, they seem to love hackish command name matches... Also, we'd need to find a way to detect this feature, i.e. some OSC sequence where we get a reply or so.

**Comment by poettering** [comment]
> The red dot is entirely redundant here, and actually counter-productive in some cases because this specific terminal emulator will actually show the icon of the container manager if it detects that you're inside of a container.

These are all hacks specific to the docker/podman ecosystem, hence wouldn't work for us.

**Comment by AdrianVovk** [comment]
> Right now we'd happily send a 1MB title to the terminal, which doesn't really make much sense

Ah well sure truncating so we don't send insane amounts of data into the terminal makes sense, of course. The terminal emulator layer probably does it for us, but I don't see any harm of doing it ourselves too.

As long as we're not truncating in the "visual" range of number of characters. It's perfectly feasible for the UI to show a couple hundred characters worth of title, and potentially more on an ultrawide monitor, so we should probably truncate at the ~2k char mark

> That's not actually true. We read the bg color from the terminal, and then shift it into a red hue. Maybe the algorithm for shifting the hue could be tweaked, but it's not true that we are "entirely unaware" of the color scheme. We are very much aware

Alright didn't know that, sorry about the misinformation then. In my testing, it seems that if my system is in dark mode I get the same shade of red no matter what the background color of the terminal is, giving my the false impression that run0 didn't take it into account. But switching into light mode does pick a different shade of red.

Of course, the terminal color scheme can also change at runtime, and in modern systems will do so relatively regularly depending on use-case. Here's what happens if I switch color schemes (which I do relatively often, i.e. if I take my laptop outside) while run0 is running:

![Screenshot from 2024-06-20 20-49-09](https://github.com/systemd/systemd/assets/11251606/e74b4d8f-b35f-443d-ad57-1e7ef08497ea)

![Screenshot from 2024-06-20 20-39-17](https://github.com/systemd/systemd/assets/11251606/ded30baa-8296-450c-af25-3848ede8cc5c)

So ulimately I don't think this is properly solvable from within a terminal client. We cannot control for nearly as many variables from within the limited API of the terminal as we could from the terminal emulator itself.

For instance: what if one of the numbered colors is red with the terminal's color scheme? Depending on the color scheme, it might end up being hard to read:

![Screenshot from 2024-06-20 20-47-33](https://github.com/systemd/systemd/assets/11251606/c336788a-d3ca-4f6f-8e38-7fff82564430)

> I  wish they'd come up with a proper ANSI OSC sequence instead so that we can tell them about this

Agreed.

Looks like Ptyxis, GNOME's state-of-the art containerized terminal app, already has some OSC codes in use for this. And `toolbx`, Fedora's podman wrapper, emits them. See: https://gitlab.gnome.org/chergert/ptyxis/#container-support

> this doesn't know the character cell where the priv change is placed

I'm really not sure about the limitations that terminals impose here. What's just not implemented versus what's impossible to implement.

CC @chergert for input on this specifically and the whole topic in general.

(Also, CC @allanday, @smwh because I think this is ultimately a design question)

> Also, we'd need to find a way to detect this feature, i.e. some OSC sequence where we get a reply or so.

Why? Seems more complicated than it's worth. Presumably the terminal app will either do something fancy with the information we give it, in which case great; or not, in which case oh well and maybe the user should just use the terminal app that does.

> they seem to love hackish command name matches
> [...]
> These are all hacks specific to the docker/podman ecosystem, hence wouldn't work for us

I presume that this has more to do with the current behavior of tools and less with them loving command name matching.

As mentioned above, in Ptyxis this isn't exclusive to docker/podman. There might not be an icon in the app for nspawn/systemd-run/etc, but that could be added quite easily. The actual end-goal mechanism here seems to be OSC sequences.

---

Also, unsure if this is a systemd bug or a terminal emulator bug. But run0 doesn't actually fill the whole line red:

![Screenshot from 2024-06-20 20-58-59](https://github.com/systemd/systemd/assets/11251606/3e492acf-ed1e-456f-83ab-20f7ab346b92)

**Comment by poettering** [comment]
> Looks like Ptyxis, GNOME's state-of-the art containerized terminal app, already has some OSC codes in use for this. And `toolbx`, Fedora's podman wrapper, emits them. See: https://gitlab.gnome.org/chergert/ptyxis/#container-support

Are those OSC codes documented somewhere?

**Comment by poettering** [comment]
> Also, unsure if this is a systemd bug or a terminal emulator bug. But run0 doesn't actually fill the whole line red:

hmm, the pytfwd code we have actually inserts an "erase-to-eol" sequence before each \n to ensure we erase things to the end line.

**Comment by chergert** [comment]
> Are those OSC codes documented somewhere?

They come from the Fedora patches in GNOME Terminal for the last 6-7 years.

However, we very much want to get away from them upstream in VTE and so GNOME 47 will introduce a concept called "termprops" which is a much better solution for PTY children to get/set variables coordinated with the terminal emulator. It will also serve as a better solution for notifications than what the Fedora patches do. 

The goal here is to patch podman/jhbuild/toolbox/distrobox/etc to emit these. Additionally, it will allow for bash/etc profiles to set a specific style scheme in the apps if they choose.

There is some effort to push the termprops up into the terminal working group on freedesktop, as the design is quite nice.

**Comment by AdrianVovk** [comment]
@chergert Looked @ termprops, look neat! One missing question though... is VTE able to "remember" ranges of cells/lines/whatever where a termprop is set and where it isn't?

Basically we want to be able to mark certain lines as being privileged output. Any of run0's output should have some special style, even as you scroll through the scrollback, resize the terminal, etc. With termprops, it looks like the best we can do is tell the terminal "hey, right this second we're running in a root shell!" and then later "done!". What we need to be able to do is say "hey, starting from right now all lines emitted are output from a root shell" and have VTE remember that until those lines are deleted from the scrollback. We don't just want the header-bar to go red while we're running a rootful command and then go back to grey when that's done; we also want the output of that rootful command to be recolored red

Another thing that seems wrong is that all termprops are reset when the terminal is reset. What happens if you have an interactive shell running in a container, then run `reset`? It clears out all the termprops, and the terminal emulator forgets that it's in a container?

**Comment by chergert** [comment]
> Another thing that seems wrong is that all termprops are reset when the terminal is reset. What happens if you have an interactive shell running in a container, then run reset? It clears out all the termprops, and the terminal emulator forgets that it's in a container?

If you're looking for anything bulletproof and a PTY is involved, you'll probably be churning for the rest of your career.

But I will extremely caution about using anything related to the color palette and PTY in some automated fashion. Because in my experience, terminal color schemes are broken in so many flawed and unfixable ways other than "just pick one that works for your use case".

When I saw the run0 stuff doing colorization my first thought was "oh shit they don't know what they just bit off" if I'm to be a bit glib.

**Comment by poettering** [comment]
Where is that "termprop" stuff specified?

**Comment by chergert** [comment]
https://gitlab.gnome.org/GNOME/vte/-/blob/b4481add89c8f4c0d357997a275826cdca55422e/src/vtegtk.cc#L3032

**Comment by septatrix** [comment]
Also see #35845. While it is possible to suppress the implicit background changes there is currently no way to do the same if a background color is explicitly given as a flag.
