### ISSUE TITLE
Automounts do not reset properly after TimeoutIdleSec automatic unmounts

### ISSUE THREAD

**Issue by Wibjarm** [systemd/systemd#3332]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> As of 230, automount units whose associated mount units have been auto-unmounted with TimeoutIdleSec do not trigger the associated mount unit when the automount path is accessed again until the automount unit is completely restarted.  This causing the accessing process to hang indefinitely.
### In case of bug report: Steps to reproduce the problem

> Trigger any automount unit with TimeoutIdleSec= set, wait for the idle time to occur and unmount the associated mount unit, then try to access the automount location again.

**Comment by StefanHamminga** [comment]
I can confirm the problem. Also Arch Linux (x86_64) and systemd 230 (Arch package version 230-2). This happens (at least) with SSHFS mounts (regular ssh connections confirmed working) and with a Btrfs microSD card (the card is not removed at any stage).

**Comment by AlexanderKurtz** [comment]
I'm also seeing this here on Debian Testing (systemd 230) affecting the EFI System Partition (which gets automounted to /boot by systemd-gpt-auto-generator):

If /boot gets automounted once, then unmounted after the timeout of 120 seconds, subsequent accesses to /boot hang indefinitely. As mentioned by  @Wibjarm, `systemctl restart boot.automount` fixes this, but only until the timeout is hit again.

I'm using the following as a workaround for the time being, as a surprising number of programs break/hang because of this (e.g. df, puppet, sftp):

```
root@shepard:~# cat /etc/systemd/system/boot.automount 
[Automount]
Where=/boot
root@shepard:~# 
```

**Comment by yshui** [comment]
I can confirm this problem exists on Archlinux for the automounted /boot

**Comment by kakra** [comment]
I do see this or something similar also in v229... Commands hang until I restart the automounter. At the same time (automounter restarts) I'm seeing something like this in dmesg:

```
[17951.683862] JBD2: recovery failed
[17951.683866] EXT4-fs (sde1): error loading journal
```

Is this the same error? Then it existed already in v229.

**Comment by michaelolbrich** [comment]
No, that must be a different issue. Your messages indicate that mounting the actual filesystem is attempted but fails for some reason. With the original issue systemd didn't even attempt to mount the filesystem.
