### ISSUE TITLE
where is the log "Started Load Kernel Modules" code location? i try to find the "Started Load Kernel Modules" log code location, but search nothing. Who know?

### ISSUE THREAD

**Issue by V0idk** [systemd/systemd#33340]
### systemd version the issue has been seen with

255

### Used distribution

suse

### Linux kernel version used

4.12.14-122.173.1.26798.1.PTF.1214453-default

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

i try to find the "Started Load Kernel Modules" log code location, but search nothing. Who know?

**Comment by poettering** [comment]
*[Canned reply follows]*

This is a bug and feature request tracker, and not a support forum. In order to keep frustration at a minimum the submission form should have made this very clear.

If you have questions about systemd use or how to do or make use of certain things, please contact a more appropriate forum, for example the systemd mailing list:

https://lists.freedesktop.org/mailman/listinfo/systemd-devel

Thank you for understanding.
