### ISSUE TITLE
Implement optional transfers in systemd-sysupdate

### ISSUE THREAD

**Issue by abderrahim** [systemd/systemd#33343]
### Is your feature request related to a problem? Please describe

Currently all transfers defined in `sysupdate.d` are taken into account and downloaded. This means we can't have optional transfers.

### Describe the solution you'd like

We want to have optional components of an OS that can be enabled/disabled by the user and acted upon by systemd-sysupdate.

The proposal is as follows:
* Have 2 directories considered by systemd-sysupdate: `sysupdate.d` and `sysregistry.d`
* Files in both directories are considered for ownership of currently installed stuff
    * that is `vacuum` will consider them when deleting old updates
* Files in `sysupdated.d` are downloaded when update is requested
* Files in `sysregistry.d` are not downloaded by default
    * These files can be symlinked into `sysupdate.d` to be considered for download
    * `vacuum` will delete things that are defined in `sysregistry.d` but not in `sysupdate.d` for the current version
    * 
* `systemd-sysupdate` and/or `updatectl` can get new verbs to enable/disable transfers by symlinking them from `sysregistry.d` to `sysupdate.d` / deleting the symlinks
    * Non-symlink files that are in `sysupdate.d` cannot be disabled (they aren't optional)

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by AdrianVovk** [comment]
OK as this is going in, we're hitting some design constraints of the `sysregistry.d/` proposal we agreed upon in our meeting. So here's some reasoning and an alternative design proposal.

## Initial solution

As a reminder on the design we initially settled on. We defined a new `sysregistry.d/` directory, that's read alongside `sysupdate.d/`. Files in the registry are only considered during a vacuum operation. They can be symlinked into `sysupdate.d/` to "enable" them, and sysupdate will start considering them for updates.

## Limitations

`sysregistry.d/` is the optimal solution for a situation where sysupdate transfers are all enabled/disabled individually. This is not our situation. In reality, many transfers aren't particularly useful on their own and should be enabled alongside others.

The NVIDIA GPU driver requires at least a regular sysext and an initrd sysext to function. These would be two separate transfers, placing two different resources into two different locations. However, individually these won't be particularly useful. I'll call these sets of transfers that work together to do one thing as a whole "optional features".

Of course we could leave this to be the responsibility of the user. The user would have to make sure that all the needed transfers are enabled for the optional feature to function. However, that gives the opportunity for broken systems. We will not be testing configurations where a feature is partially-enabled - who knows what the consequences of such a configuration may be

## Attempt at solving

The first solution we came up with was rather simple. We added a `[Transfer] Alias=` option to the transfer definition files. When set, this alias is used to group transfers into optional features. Then `updatectl`, the intended way to manipulate these files, would allow you to enable/disable these features, and it would symlink each member transfer into `/etc/sysupdate.d` individually.

For example, in the NVIDIA driver case, you'd set `Alias=nvidia-driver` in all transfers necessary for the driver to function. Then you could `updatectl enable nvidia-driver --now --reboot` to enable and download the driver, then reboot. Enabling would just symlink all of the transfers belonging to the NVIDIA driver individually into `/etc/sysupdate.d`

However, this has a problem. The distribution may want to, over time, change which transfers are necessary for a given feature. Maybe the NVIDIA driver stops needing a custom kernel module and only the userspace portion remains proprietary - then we could drop the initrd transfer. Or maybe the opposite situation occurs, and some feature starts requiring more transfers to be added. Either way, this isn't possible with this solution: the exact set of transfers is locked-in at the time the user runs `updatectl enable`. This system has no concept of what features are enabled and instead operates on the level of transfers. It also doesn't really have any way to interact with features outside of `updatectl`, so it doesn't give much of an opportunity to write UIs for managing these features if we ever want that.

## Proposed solution

Instead of containing transfer definitions only, `sysregistry.d/` would contain "feature definition" files too. I would also like to rename it to `sysfeatures.d/` to better represent what this directory defines, and instead of just `.conf` files there would be `.feature` and `.transfer` files.

A feature definition file would look something like this:

```ini
# /usr/lib/sysfeatures.d/nvidia-driver.feature
[Feature]
Title=NVIDIA Proprietary Driver
Documentation=https://os.example.com/docs/nvidia
AppStream=https://dl.example.com/metainfo/nvidia.xml
Transfers=50-nvidia-initrd.transfer, 50-nvidia-userspace.transfer
Enabled=false
```

This defines a transfer, called `nvidia-driver`, that when enabled makes sysupdate use `/usr/lib/sysfeatures.d/50-nvidia-{initrd,userspace}.transfer` as if they were part of `/usr/lib/sysupdate.d`. To enable a feature like this, you'd just need to  generate a drop-in file:

```ini
# /etc/sysfeatures.d/nvidia-driver.feature.d/enable.conf
[Feature]
Enabled=true
```

**Comment by chunyi-wu** [comment]
What's the benefits to use `enable.conf` to override the `Enabled`, instead of copying the whole `nvidia-driver.feature` to `/etc/sysfeatures.d`?

**Comment by AdrianVovk** [comment]
we generally try to avoid copying over whole config files when we could get away with using drop-ins. Otherwise they'll drift over time. In other words, if you copy the whole .feature file into /etc you're redefining the whole file, if you use a drop-in you're changing just one setting

Also see #33344
