### ISSUE TITLE
systemd sets incorrect terminal type for serial terminals

### ISSUE THREAD

**Issue by siteshwar** [systemd/systemd#3342]
### Submission type
- [ ] Bug report

systemd sets terminal type to `vt220` for serial terminals. bash expects `vt220` terminals to support line wrapping, however serial terminals do not support automatic line wrapping. This causes bash to misbehave when command entered on bash prompt is longer than one line. If `serial` terminal type is used instead of `vt220` bash behaves as expected.

Related code in upstream: https://github.com/systemd/systemd/blob/master/src/basic/terminal-util.c#L788

Related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1149651
### systemd version the issue has been seen with

> systemd-219 (and it should be reproducible with latest versions too)
### Used distribution

> Red Hat Enterprise Linux 7
### In case of bug report: Expected behaviour you didn't see

> Line wrapping in bash should work correctly.
### In case of bug report: Unexpected behaviour you saw

> Line wrapping in bash does not work correctly.
### In case of bug report: Steps to reproduce the problem

> Connect to RHEL7 machine over serial terminal and enter command longer than one line.

**Comment by floppym** [comment]
TERM=serial isn't a valid terminal type, according to the terminfo database provided by ncurses-6.0.

You would get the same result by setting TERM=dumb.

**Comment by poettering** [comment]
well, the original 1983 vt220 terminal hardware comes with an rs232 port. so: vt220 definitely qualifies as a serial terminal.

Now, it appears that your specific serial terminal does not support vt220 though. which terminal emulator are you using for this?

Note that we pick vt220 just because we need something that makes a good default. We picked vt220 here, because in our perspective it kinda is vt110 plus working pageup/pagedown/arrow keys. 

Now, of course, using this as default may very well be wrong, as not all terminals are compatible with vt220, and yours apparently isn't. But most terminal emulators in reality _are_ compatible with it. And as it is with defaults we pick something that works for a large part of the people, and for everybody else we offer the option to change things. Yours is one of those case: simply copy /usr/lib/systemd/system/serial-getty@.service to /etc/systemd/system, edit it there and add the `Environment=TERM=dumb` line to its `[Service]` section. This will override systemd's default and give you only the most basic of terminal support, compatible with your setup.

Of course, it would be great if we could auto-detect the right TERM= value, but this is not supported for serial terminals, and hence the only option we really have is pick something that has a good chance to work and is reasonably fully featured, and then make those folks whose terminal is incompatible with that change the config to something that's more appropriate for them.

And no, `TERM=serial` is not defined, that doesn't exist.

Anyway, this since auto-configuration is not possible and we have to pick a default that will work for some folks but not for others, this is nothing we can fix for you. Sorry. Closing.

**Comment by seebs** [comment]
The description of how to override this seems to be outdated; there's no /usr/lib/systemd/system on any machine I currently have access to.

vt220 seems an unusual choice, given that I have seen at least a dozen terminal programs which emulated xterm or vt100, and I am not sure I've ever seen a terminal program claim to have full vt220 support.

**Comment by poettering** [comment]
@seebs maybe your distribution is still using split /usr? if so, the path for unit files is /lib/systemd/system...

xterm is a superset of vt220. See the xterm wikipedia page for example: "…It emulates the VT220 and Tektronix 4010, and has experimental support for ReGIS.…"

**Comment by seebs** [comment]
That would make sense. (Of course, now I'm even more confused that a system without a split /usr would have a /usr at all, but computers are weird.)

And to think, for all these years, I've been assuming xterm was "probably just a vt100".

**Comment by bam80** [comment]
> Of course, it would be great if we could auto-detect the right TERM= value, but this is not supported for serial terminals

It's supported by serial terminals already, so need just add the support for systemd:
#36994
