### ISSUE TITLE
No DHCPv6 addresses are requested.

### ISSUE THREAD

**Issue by Thomas18893** [systemd/systemd#33550]
### systemd version the issue has been seen with

252

### Used distribution

Self build with buildroot

### Linux kernel version used

27003319

### CPU architectures issue was seen on

aarch64

### Component

networkctl

### Expected behaviour you didn't see

Request an IPv6 address via DHCPv6.

### Unexpected behaviour you saw

Nothing happened. No DHCPv6 messages were send. Only IPv4 addresses where requested correctly.

### Steps to reproduce the problem

Fill a .network file with this:

```
[Match]
Name=eth0

[Network]
DHCP=yes
LinkLocalAddressing=ipv6

```

And then enter `systemctl restart systemd-networkd` or reboot.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ systemctl --version
systemd 252 (252)
-PAM -AUDIT -SELINUX -APPARMOR -IMA -SMACK -SECCOMP -GCRYPT -GNUTLS +OPENSSL -ACL +BLKID +CURL -ELFUTILS -FIDO2 -IDN2 -IDN +IPTC +KMOD -LIBCRYPTSETUP -LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -TPM2 +BZIP2 -LZ4 -XZ +ZLIB -ZSTD -BPF_FRAMEWORK -XKBCOMMON -UTMP -SYSVINIT default-hierarchy=unified
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
