### ISSUE TITLE
Issues with XDG_RUNTIME_DIR when working in HPC environments

### ISSUE THREAD

**Issue by eburgueno** [systemd/systemd#3355]
### Submission type
- [] Bug report
- [X ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 219

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> RedHat/CentOS 7

When working in an HPC environment, it is common to use a job scheduler to submit jobs from a login host to other servers. Jobs are run in potentially different hosts than the one the user has logged in, so the entire user environment is sent to the execution node (I believe all job schedulers behave this way).

When a job is executed in a remote node, the user is not actually login in. This means `pam-systemd` is never triggered, so `XDG_RUNTIME_DIR` directories are not created. According to [the documentation](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Unprivileged%20Write%20Access), the only ways to trigger their creation is at boot time or at service startup, none of which are the case for job schedulers nor the jobs that they run, as they are not system processes.

This causes issues like the one described [here](https://github.com/jupyter/notebook/issues/1411) and [here](https://groups.google.com/forum/#!topic/openlava-users/CFaD5pGMfw0): An application that honours the XDG Base Directory specification checks for the existence of `XDG_*` variables, but then fails when attempting to use them if the user has never logged in, therefore never triggering the creation of said directories.

As far as I can see, there is nothing in the specification that mandates that applications relying on XDG directories should make sure that a login session actually exists before using them. Only that they should attempt to create them (which by design would fail for unprivileged processes).
- Would you suggest that job schedulers ignore XDG variables when submitting jobs to remote nodes where they will not trigger a login?
- Should the application verify the existence of both a) an XDG variable, and b) a current login session, before attempting to use XDG directories?
- Should the XDG spec be amended to clarify the above?

Thanks

**Comment by poettering** [comment]
XDG_RUNTIME_DIR is only defined for user programs. And user programs on Linux (at least on the Linux flavours systemd supports) are defined by running below a PAM session. Hence, if your daemon wants to run user code, then it really should involve PAM with that and open a PAM session. And if it doesn't want to do that, then it shouldn't be considered user code, and thus should not look for XDG_RUNTIME_DIR at all.

Other command schedulers, such as cron for example, that are capable of scheduling user code do all this properly, and go through the PAM stack, and thus will get XDG_RUNTIME_DIR correctly set up. Your scheduler really should do the same, or not claim to be able to run user code...

All of this is not just a systemd limitation btw. It's a general rule: user code should run only within PAM sessions, everything else is unsafe, because you don't get the security bits set up properly, no selinux, no keyring, no audit, no resource limits, no systemd, no cgroups, … It's all hooked in the same way via PAM.

To clarify this: PAM sessions are not just for interactive sessions, it's for all user code that runs, and that includes non-interactive command schedule type code, but also stuff such as ftp clients or so, wherer the actual upload/download process is forked off as user process and also lives in a PAM session.

Closing this one, since this appears to be a bug in your command scheduler software and needs to be fixed there.
