### ISSUE TITLE
When Group= is used, supplementary groups are not initialized from user's default group list

### ISSUE THREAD

**Issue by sirg** [systemd/systemd#33654]
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04

### Linux kernel version used

6.5.0-27-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Supplementary groups are initialized from user's default group list

### Unexpected behaviour you saw

Only the group specified with Group= appears in supplementary groups list

### Steps to reproduce the problem

- create user _testuser_, group _testgroup_ and add _testuser_ to group _testgroup_
- create simple service, that runs _/usr/bin/id_ and appends output to a file; specify **User = testuser**
- install/start the service
- modify the service to add **Group = testgroup**
- reload, start the service

Observe that supplementary group lists in the output file differ:
```
uid=1001(testuser) gid=1001(testuser) groups=1001(testuser),1002(testgroup)
uid=1001(testuser) gid=1002(testgroup) groups=1002(testgroup)
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
