### ISSUE TITLE
Audit multicast check is invalid

### ISSUE THREAD

**Issue by albe19029** [systemd/systemd#33730]
### systemd version the issue has been seen with

219

### Used distribution

Centos 7

### Linux kernel version used

3.10.0-1160.71.1.el7.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Expected behaviour you didn't see

bind return 0 on kernels <= 3.16 for audit socket

### Unexpected behaviour you saw

While testing on centos 7, I have found that this check
https://github.com/systemd/systemd/blob/main/src/journal/journald-audit.c#L522

is not working for kernel 3.10.

The problem is that in linux af_netlink.c netlink_bind is calling, and there is a check in code

if (nlk->netlink_bind && groups)

And if this check fails - there are no result about unsupporting of this bind method for this netlink audit socket. So the correct way to check is not by bind result, but by kernel version.

### Steps to reproduce the problem

run on kernel < 3.16

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by albe19029** [comment]
Very strange. If I run upstream systemd on linux kernel <= 3.16 this will still reproducible. Don't know why you closed this.
