### ISSUE TITLE
timesyncd: drop-in precedence in reverse order for NTP servers

### ISSUE THREAD

**Issue by fanuware** [systemd/systemd#33765]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12 (bookworm)

### Linux kernel version used

6.1.0-21-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-timesync

### Expected behaviour you didn't see

The collected `SystemNTPServers` should appear according to the precedence as described in the docs. The ones with higher precedence should be used first.

### Unexpected behaviour you saw

The collected `SystemNTPServers` appear in reverse order. The one with the lowest priority is used first. NTPs configured in the "main" configuration are active before any drop-ins.

### Steps to reproduce the problem

Consider the following drop-ins in `/etc/systemd/timesyncd.conf.d`

10-low-priority.conf
```sh
[Time]
NTP=1.debian.pool.ntp.org
RootDistanceMaxSec=10
```

20-high-priority.conf
```sh
[Time]
NTP=2.debian.pool.ntp.org
RootDistanceMaxSec=20
```

As a result we can discover that `RootDistanceMaxSec` appears according to the specified precedence. The order of `SystemNTPServers` is in reverse.

```sh
$ timedatectl show-timesync \
    --property=SystemNTPServers \
    --property=ServerName \
    --property=RootDistanceMaxUSec
SystemNTPServers=1.debian.pool.ntp.org 2.debian.pool.ntp.org
ServerName=1.debian.pool.ntp.org
RootDistanceMaxUSec=20s
```

**Comment by poettering** [comment]
I think this is a misunderstanding.

RootDistanceMaxSec= is a global singleton setting. If you specify it twice, the last assignment wins. OTOH NTP= is a list setting. If you specify it twice, then all assignments are combined. If you want to reset the list, assing an empty list once.

Hence, the NTP= lines in your two drop-ins are combined, but the RootDistanceMaxSec= setting of the first drop-in is ignored, because it is overriden by the 2nd drop-in.

Or in other words: we have no per-server setting for RootDistanceMaxSec=. And I am not convinced it makes too much sense to have that?

Anyway, closing, since this appears to be a misunderstanding.

**Comment by poettering** [comment]
hmm? no?

the drop-ins are processed in alphabetical order. hence because "10-low-priority.conf" orders before "20-high-priority.conf" it also means the order of the configured NTP servers in the list is "1.debian.pool.ntp.org 2.debian.pool.ntp.org". Hence everything works just as it should?

(also, don't overstimate the meaning of the ordering. timesyncd switches to a different NTP server whenever one stops responding properly, and then sticks with that, until that stops responding properly, and so on, in a round robin fashion. i.e. the order doesn't matter much, it just controls what's the first NTP server contacted at boot, but due to UDP datagram loss if your system has been running you'll almost certainly have switched to a different NTP server by then, or maybe back.)

**Comment by fanuware** [comment]
Referring to the official documentation:

- [*drop-ins have higher precedence and override the main configuration file*](https://github.com/systemd/systemd/blob/4cf7a676af9a79ff418227d8ff488dfca6f243ab/man/standard-conf.xml#L70)
- [*the entry in the file sorted last takes precedence*](https://github.com/systemd/systemd/blob/4cf7a676af9a79ff418227d8ff488dfca6f243ab/man/standard-conf.xml#L74)

> To me it seems that both statements do not currently apply to NTP=

In my use case the precedence is quite important as I need granular control over which NTP is used and in what order.

**Comment by poettering** [comment]
> To me it seems that both statements do not currently apply to NTP=

Well, this could proably be expressed more clearly, the "override" wording refers for single value options where each assignment overrides the previous one. For list options each assignment extends the previous one, unless an empty string is assigned which resets the list.

> In my use case the precedence is quite important as I need granular control over which NTP is used and in what order.

timesyncd does not give you guarantees over that. we'll round robin through defined NTP servers based only on whether we can reach them, and then stick to them, taking nothing else into account.
