### ISSUE TITLE
Add TCB support to sysusers

### ISSUE THREAD

**Issue by shaba** [systemd/systemd#33787]
### Component

systemd-sysusers

### Is your feature request related to a problem? Please describe

systemd-sysusers use /etc/shadow as constant file *shadow_path, but for OS with TCB /etc/shadow is empty, all shadows in /etc/tcb/$user/shadow.
See https://www.openwall.com/tcb.

### Describe the solution you'd like

ALTLinux use TCB for store passwords.
shadow package build --with-tcb.
```
grep TCB /etc/login.defs
USE_TCB			yes
TCB_AUTH_GROUP		yes
TCB_SYMLINKS		no
```
```
grep -E "shadow|passwd" /etc/nsswitch.conf
#	tcb			Use local tcb shadow files, see tcb(5)
passwd:      files systemd
shadow:     tcb files
```
For example, shadow file for user root is /etc/tcb/root/shadow
sysusers should use pam and nss stack, see /etc/nsswitch.conf and|or /etc/login.defs and select true way for add user.

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by shaba** [comment]
@ldv-alt please, add comment.

**Comment by AdrianVovk** [comment]
Ultimately something I want to do is make systemd-sysusers export users directly via userdbd and call it a day (if the distribution opts-in, of course). This would mean sysusers have no entry in /etc/passwd or /etc/shadow at all, and on image-based distributions using homed it means that those files simply won't exist.

That should hopefully handle your issue too, no?

**Comment by poettering** [comment]
Sorry, I am not convinced supporting this makes sense. First of all, system users generally don't have passwords anyway, they are not something you generally log into, hence this seems like completely unnecessary effort. The only user account < 1000 that would need this is root, and you can just create that without sysusers and use your tcb stuff for that then.

Let me stress this: sysusers does *not* support setting passwords via sysusers.d, that's outside of its scope, hence tcb is outside of its scope too, since that only matters for storing passwords.

but also, i am really not onboard with adding special casing for some niche distro, for something no other distro is even considering.

Hence, sorry, but no.
