### ISSUE TITLE
systemd-run --user --scope ... doesn't work with unified cgroup hierarchy

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#3388]
### Submission type
- [ x ] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

`230 and 230+84 commits`
### Used distribution

`Arch Linux (testing)`
### In case of bug report: Expected behaviour you didn't see

`systemd-run --user --scope bash -c "sleep 100"` should start a new scope and service in the user systemd instance.
### In case of bug report: Unexpected behaviour you saw

systemd-run fails and the journal has `run-r9c9b0f8d4fd14753bd9d4446b7a4c1ef.scope: Failed to add PIDs to scope's control group: Permission denied`

The system was booted with `systemd.unified_cgroup_hierarchy=1`. Removing that option (and rebooting) makes systemd-run --scope work again.

**Comment by evverx** [comment]
``` sh
-bash-4.3# cat /proc/cmdline
root=/dev/sda1 raid=noautodetect loglevel=2 init=/usr/lib/systemd/systemd ro console=ttyS0 selinux=0 systemd.log_level=debug systemd.unit=multi-user.target systemd.unified_cgroup_hierarchy=1

-bash-4.3# grep cgroup /proc/self/mounts
cgroup /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0

-bash-4.3# systemctl --version
systemd 230
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

-bash-4.3# systemd-run --user --scope bash -c 'sleep 10'
Running scope as unit: run-rc42d127d342b4eb6ab73acdb4143cccf.scope

-bash-4.3# journalctl --sync

-bash-4.3# journalctl -b --no-hostname | grep run-rc42d127d342b4eb6ab73acdb4143cccf
May 31 04:35:48 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope: Trying to enqueue job run-rc42d127d342b4eb6ab73acdb4143cccf.scope/start/fail
May 31 04:35:48 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope: Installed new job run-rc42d127d342b4eb6ab73acdb4143cccf.scope/start as 13
May 31 04:35:48 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope: Enqueued job run-rc42d127d342b4eb6ab73acdb4143cccf.scope/start as 13
May 31 04:35:48 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope changed dead -> running
May 31 04:35:48 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope: Job run-rc42d127d342b4eb6ab73acdb4143cccf.scope/start finished, result=done
May 31 04:35:58 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope: cgroup is empty
May 31 04:35:58 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope changed running -> dead
May 31 04:35:58 systemd[153]: run-rc42d127d342b4eb6ab73acdb4143cccf.scope: Collecting.
```

Maybe, https://github.com/systemd/systemd/blob/master/NEWS#L66

>  Therefore it
>           is necessary to also update systemd in the initramfs if using the
>           unified hierarchy. An updated SELinux policy is also required.

**Comment by evverx** [comment]
Well, I've tried as non-root:

``` sh
-bash-4.3$ id
uid=1002(hola) gid=1002(hola) groups=1002(hola)

-bash-4.3$ systemd-run --user --scope bash -c 'sleep 10'
Job for run-rd5b069a420f54cc592fbe1ebe2d90c90.scope failed.
See "systemctl status run-rd5b069a420f54cc592fbe1ebe2d90c90.scope" and "journalctl -xe" for details.
-bash-4.3$ journalctl -b | grep run-rd5b069a420f54cc592fbe1ebe2d90c90.
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: Failed to load configuration: No such file or directory
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: Trying to enqueue job run-rd5b069a420f54cc592fbe1ebe2d90c90.scope/start/fail
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: Installed new job run-rd5b069a420f54cc592fbe1ebe2d90c90.scope/start as 7
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: Enqueued job run-rd5b069a420f54cc592fbe1ebe2d90c90.scope/start as 7
May 31 05:26:54 systemd-testsuite systemd[156]: Failed to set pids.max on /user.slice/user-1002.slice/user@1002.service/run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: No such file or directory
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: Failed to add PIDs to scope's control group: Permission denied
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope changed dead -> failed
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: Job run-rd5b069a420f54cc592fbe1ebe2d90c90.scope/start finished, result=failed
May 31 05:26:54 systemd-testsuite systemd[156]: run-rd5b069a420f54cc592fbe1ebe2d90c90.scope: Unit entered failed state.
```

**Comment by evverx** [comment]
For the record:
- `systemd-run --user --scope` runs a process `PID` inside the cgroup `/user.slice/user-M.slice/session-N.scope`
- `systemd --user` runs `mkdir /sys/fs/cgroup/user.slice/user-M.slice/user@M.service/run-PID.scope`
- `systemd --user` tries to write `PID` to `/sys/fs/cgroup/user.slice/user-M.slice/user@M.service/run-PID.scope/cgroup.procs`

This fails

> The writer must have write access to the "cgroup.procs" file of the
>   common ancestor of the source and destination cgroups.

https://github.com/torvalds/linux/blob/5518f66b5a64b76fd602a7baf60590cd838a2ca0/Documentation/cgroup-v2.txt#L331

(`systemd --user` doesn't have write access to the `/sys/fs/cgroup/user.slice/user-M.slice/cgroup.procs`)

**Comment by htejun** [comment]
Hmm.. so the restriction is there to prevent !priv processes from jumping across isolation points. Is it problematic to give write access of /sys/fs/cgroup/user.slice/user-M.slice/cgroup.procs to the user?

**Comment by peterhoeg** [comment]
fwiw, manually setting the permissions makes it work.

**Comment by evverx** [comment]
@htejun , sorry for the delay.

> Is it problematic to give write access of /sys/fs/cgroup/user.slice/user-M.slice/cgroup.procs to the user?

Well, there is a complex interaction between `pam_systemd`, `systemd`, `systemd --user` and `systemd-logind`. I'm not sure which part of the `systemd` should `chown/chmod` the `cgroup.procs`.

Another question: what does [`Delegate=`](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#Delegate=) really mean?

> For unprivileged services (i.e. those using the User= setting), this allows processes to create a subhierarchy beneath its control group path.

```
└── user-1001.slice
    ├── session-4.scope
    └── user@1001.service <-- Delegate=yes
        ├── dbus.socket
         ...
        ├── init.scope <-- systemd --user here
        ├── run-pid.scope
        ├── -.mount
        ├── run-user-1001.mount
        ...
```

Why does `systemd --user` try to move process from `session-4.scope` to `user@1001.service/run-pid.scope` ? Should `Delegate` allow this?

**Comment by floppym** [comment]
This bug now effects anyone running systemd >= 232 with a recent kernel, since the new cgroup fstype is now used for /sys/fs/cgroup/systemd by default.

**Comment by evverx** [comment]
@floppym , right. Marked as "regression"

**Comment by peterhoeg** [comment]
This bug has been around for as long as the new hierarchy has been available. 

My workaround is this script:

``` sh
#!/usr/bin/env bash

set -euo pipefail

file=/sys/fs/cgroup/user.slice/user-$(id -u).slice/cgroup.procs

sudo chown $(whoami):root $file
sudo chmod g+w            $file
```

**Comment by floppym** [comment]
Should this not block the v233 release? Or will v233 have unified cgroup support diasbled out of the box?

**Comment by evverx** [comment]
@floppym , I'm not sure what to do about it.

According to f98220a22ff0c48805a
> It is expected that general-purpose distributions might want to override this.

I think all distros will use `./configure ... --with-default-hierarchy=legacy`

**Comment by floppym** [comment]
@evverx @keszybz It just seems awfully strange to have a default configuration that breaks one of systemd's own provided tools.

**Comment by poettering** [comment]
So, I am not sure what the right fix is here. I am not convinced that we should grant access to the slice's cgroup.procs file to the user, as that's a cgroup PID 1 manages, and I am very sure unprivileged users should not be able to muck with stuff PID 1 manages. It's fine to muck with stuff where PID 1 explicitly gave up control (through Delegate=yes), but the .slice units are not of that type.

I mean, if we could somehow mark the cgroup as an something where the user is permitted to jump acrosswithout actually giving him access to the file itself? I mean right now giving the +w bit on the file does two things: the user could move PIDs into the cgroup itself, and jump across all its children. I am only interested in permitting the latter, not the former.

note that this is only an issue when using "systemd-run --scope" from a process that is not invoked by "systemd --user" itself. One could claim that that's even a feature. In my normal GNOME session I cannot reproduce this issue, due to this, as my gnome-terminals are run as children of "systemd --user". If I ssh into the local machine with my own user name I can reproduce the issue however, as then it's not permitted to do this.

I am not sure this really deserves to be a block for v233, and I will drop this milestone now. We should find a solution for this though.

@htejun any ideas?

**Comment by floppym** [comment]
Using `systemd-run --user --scope screen` is suggested by `logind.conf(5)` and `systemd-run(1)` as a workaround to make tools like screen and tmux work when `KillUserProcesses` is enabled in logind.

It would be really nice if that suggestion actually worked. ;-)

**Comment by poettering** [comment]
so after chatting with @htejun we can make this work like this:

When we create the user slice, we should:
1. create the slice's cgroup
2. enable at least one controller in cgroups.subtree_control (e.g. "pids")
3. chown the slice's cgroups.proc file to the user

This would be sufficient to make things work. Enabling the controller means that the cgroup can't accept PIDs anymore, it becomes an inner node even if it is located at a leaf. That way, as soon as we chown the slice's cgroups.proc file to the user this will only enable the cross-movement of PIDs below this slice, but it won't permit the user to directly add PIDs to the slice cgroup, as the kernel will refuse this for inner nodes. And since the cgroups.subtree_control file is not chowned to the user he can't change the inner node state on his own, hence we should be safe.

Now, all that sounds pretty straightforward... There's just one problem with it: so far we have no concept of user-ownership for a slice. Slices are just slices with noone owning them. We'd have to introduce that, and that's quite hard, as it means we'd have to have a User= setting in the slice, and that means we'd have to fork off a process to resolve it (since NSS in PID 1 is not OK), and that's yuck...

**Comment by evverx** [comment]
> enable at least one controller in cgroups.subtree_control (e.g. "pids")

`README` says
> Kernel Config Options:
> CONFIG_CGROUPS (it is OK to disable all controllers)
 
We can't enable at least one controller if all controllers are disabled. Am I missing something?

**Comment by evverx** [comment]
Hm, what about a hybrid hierarchy?
```sh
-bash-4.3$ grep cgroup /proc/self/mountinfo
24 18 0:21 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:7 - tmpfs tmpfs ro,mode=755
25 24 0:22 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:8 - cgroup2 cgroup rw
26 24 0:23 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:9 - cgroup cgroup rw,xattr,name=systemd
28 24 0:25 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,net_cls,net_prio
29 24 0:26 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,memory
30 24 0:27 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,cpu,cpuacct
31 24 0:28 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,devices
32 24 0:29 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,hugetlb
33 24 0:30 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,cpuset
34 24 0:31 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,freezer
35 24 0:32 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,blkio
36 24 0:33 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,pids
37 24 0:34 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,perf_event

-bash-4.3$ cat /sys/fs/cgroup/unified/cgroup.controllers # prints nothing
```

**Comment by keszybz** [comment]
> We can't enable at least one controller if all controllers are disabled. 

It's enough of a corner case to ignore. You need both cgroups-v2 *and* disabled controllers *and* be running not as a user@.service child.

> There's just one problem with it: so far we have no concept of user-ownership for a slice. Slices are just slices with noone owning them. We'd have to introduce that, and that's quite hard, as it means we'd have to have a User= setting in the slice

Wouldn't it be better to avoid generic support for this (at least right now), and just reach out from user@.service when starting it, and chown  slice's cgroups.proc? This could be done as a ExecStartPre=+ thing. As long as systemd-user@.service is inactive, transfering PIDs out of the slice would not be possible, but I think that's actually OK.

**Comment by evverx** [comment]
> It's enough of a corner case to ignore

Indeed.

But we can't enable at least one controller if the hybrid hierarchy is used. Is the hybrid hierarchy usage a corner case too?

**Comment by poettering** [comment]
Yes, the proposed scheme is incompatible with hybrid mode. WHich is a bummer...

**Comment by poettering** [comment]
> Wouldn't it be better to avoid generic support for this (at least right now), and just reach out from user@.service when starting it, and chown slice's cgroups.proc?

Well, our model is the single-writer model: each part of the cgroup tree is managed by exactly one process, and cut points are only those units where Delegate=yes is set... Hence I'd prefer we'd not carry a hack that chowns the slice cgroup from logind/user@.service, because it means two components will play games in the same cgroup tree parts, and we might undo eventually what the chmod did there as a side effect on some unrelated operation...

We tried to come up with other schemes. For example, one idea was to add anew method call for service and scope units. MigrateMe() or so, which will migrate the calling process into another unit, but PID 1 would do that, and hence have privileges. We'd then use that first to move the process into the user@.service cgroup, and then talk to systemd --user to move it to the right place below that tree where it really should go. Alas, this doesn't work: we can't move processes into delegated subtrees from PID 1, simply because the top-level node in the delegated subtree is generally an inner node, and hence can#t accept processes. Thus PID 1 would have to first create a subgroup in the subtree that --user is supposed to manage, and at that point we are clearly in the territory where two managers start interefering with the same subtree and that's really not what we want...

**Comment by poettering** [comment]
So, here's another idea. Let's add the following:

* Let's add a concept of "process migration" to units proper:
  * Add a new per-unit boolean setting AcceptMigration= or so, which enables a unit to become a recipient for process migration
  * Add a new bus call MigrateMe() or so for units. The calling process will be moved by PID into the unit, if that's permitted
  * Internally, AcceptMigration= would have the effect that a root-owned "recv" subcgroup is created in the unit's cgroup, while the cgroup itself is chowned to the delegated user. With this scheme "recv" is basically retained under the control of PID 1, but it is inside the subtree of the destination service.
  * We'd then set the sticky chmod bit on the main unit cgroup, so that the owner of the unit cgroup can't remove "recv"
* Then, we'd change systemd-run to first invokes PID1's MigrateMe() so that the child it forks becomes a member of user@.service, and then it creates a scope unit out of it by talking to systemd --user...

Why this complexity? Well, we try to follow the rule that there's exactly one manager for each cgroup, and that there are "cut points" (marked by units with Delegate=yes) where there's a boundary between these managers. We need privileges to migrate the process between two subtrees owned by the same user, hence PID 1 needs to do that, but then again we can't permit PID 1 to move the process to the right place in one step, since that would conflict with the rule that there is only one manager for each cgroup (and thus cgroup subtree).

**Comment by poettering** [comment]
After another round of discussions with Tejun, here's what we think might make sense, a simplification of the above:

* Introduce the "recv" subcgroup, but let's call it "dropzone". Create it at the first time we start something in the service/scope, chowned to the service's user, but only when migration is enabled for the unit via a new per-unit AcceptMigration bool. This subcrgoup wouldn't actually be that different from the "control" subcgroup we already creat for control processes: a special subcgroup managed by PID 1, even in delegated units, but nominally owned by the service's own user.
* Add a per-unit MigrateMe() bus call as before, and when called, move the calling PID to the dropzone of the destination unit.

In this scheme we wouldn't bother with ownership of the cgroup anymore, it would be normally owned by the user itself. That should be safe, as the operations the user could do to interfere with us is pretty limited. Usually it's dangerous to make privileged code write/create stuff in dirs owned by unprivileged code, due to symlink attack scenarios and the fact that this enables unpriv users to rename priv-owned objects. But that's not a problem in this specific case as cgroupsfs doesn't permit symlinks nor renames (and won#t in future either, says @htejun, ever). The user could of course still remove the drop-zone, but this would only result in not being able to recv processes anymore, little else. 

I kinda like the "dropzone" concept I must say, it has a good feel, as it permits migration nicely without interfering directly with the actual delegated subtree. In fact, a cgroup manager that we delegate to could even listen to "cgroups.populated" events in the dropzone to get notifications when a process is dropped in...

We probably should be careful with naming the dropzone subcgroup though, to minimize naming conflicts with potential cgroups owned by the delegated subtree manager itself (and in fact the "control" subcgroup should probably be renamed due to this too). My first candidates would be to prefix the names with somethin magic, such as `_` or `@` but both we already use for other purposes in cgroup names (`_` is used for escaping, and `@` for templated unit names). hence, maybe ".dropzone" and ".control" or so... dunno.

Does this make sense?

**Comment by evverx** [comment]
What is the migrations's rules? Should a process calling `MigrateMe` has the same `UID` as an `AcceptMigration`-unit?

I don't understand the last step:
> Then, we'd change systemd-run to first invokes PID1's MigrateMe() so that the child it forks becomes a member of user@.service, and then it creates a scope unit out of it by talking to systemd --user...

How does `systemd --user` create a scope?

**Comment by poettering** [comment]
> What is the migrations's rules? Should a process calling MigrateMe has the same UID as an AcceptMigration-unit?

yes, I think that'd be sufficient. In combination with the fact that the client was able to connect to the system bus that should be sufficient of a check.

> How does systemd --user create a scope?

just like systemd --system does it. The difference is only in the location: systemd --system manages the cgroup root, and systemd-user only its own subtree, and that's where it places the scope.

**Comment by evverx** [comment]
Will it be possible to migrate processes between two user services via `systemd --user` only (without `PID1`)?

**Comment by poettering** [comment]
> Will it be possible to migrate processes between two user services via systemd --user only (without PID1)?

yes, that's already possible. If the process originates in cgroup that is below systemd --user's cgroup subgroup then migrations are permitted anyway.

Again, this bug is about "systemd --scope --user" being run *outside* of the cgroup subtree systemd --user manages.

In my proposal, if you call MigrateMe() on some unit you already are a member of, then we'd generate a recognizable error, which the client can then ignore, and would not move it into the dropzone.

**Comment by evverx** [comment]
> yes, that's already possible.

I know.

> Again, this bug is about "systemd --scope --user" being run outside of the cgroup subtree systemd --user manages

I know.

Sorry, the question is: will it be possible to use `AllowMigration`, `MigrateMe` and so on for user systemd? I'm asking because some settings/functions don't work for user systemd (for example https://github.com/systemd/systemd/issues/3944)

**Comment by poettering** [comment]
> Sorry, the question is: will it be possible to use AllowMigration, MigrateMe and so on? I'm asking because some settings/functions doesn't work for user systemd (for example #3944)

oh, you mean whether AllowMigration/MigrateMe would also be available within the --user instance of systemd?

Yes, I think that would make a ton of sense. Or to say this differently: I see no reason why we would prohibit it, and perms from the kernel would allow it.

**Comment by evverx** [comment]
Hm, `systemd-run --user --scope` doesn't place processes to the scope's controllers hierarchies:
```sh
# v231, legacy hierarchy

$ systemd-run --user --scope /bin/sleep 10000 &
[2] 15328

$ cat /proc/15328/cgroup
...
10:pids:/user.slice/user-1001.slice/session-4.scope
...
1:name=systemd:/user.slice/user-1001.slice/user@1001.service/run-r6eda5738f3bb4866a16dea4b0e3de91e.scope
```
Is there a plan to change this with `MigrateMe`?

**Comment by evverx** [comment]
I mean. How does `MigrateMe` affect the legacy/hybrid-controllers?

**Comment by poettering** [comment]
it doesn't.

On cgroupsv2 delegation of controllers to unprivileged clients is safe. We are not exposing that yet however, but we really should.

Delegation of controllers isn't complete yet in other ways either. For example, I figure we need to make configurable which controllers precisely are delegated. My current idea is that the current Delegate= boolean would become overloaded as a setting you can specify a set of controllers with, so that:

* Delegate=yes → delegate everything
* Delegate=io → delegate only the io controller hierarchies
* Delegate=pids cpu → delegate only pids and cpu controller hierarchies
* Delegate=~io cpu → delegate all hierarchies with the exception of cpu and io
* Delegate=minimal → delegate no controllers
* Delegate=no → delegate nothing

Just blindly delegating all controllers to unprivileged is problematic, as some controllers already have an effect if you don#t configure them but enable them for a controller, and we probably shouldn't do that by default if for all users if we enable controller delegation for `user@.service`, if you follow what I mean.

But anyway, migration and controller delegation are not directly connected I'd say. We should permit controller delegation and process migration, even in combination if people like.

**Comment by keszybz** [comment]
That's disappointing, but I don't think we'll get this fixed any time soon.

**Comment by wavexx** [comment]
Debian unstable is using hybrid as the default mode, which breaks --user + --scope.
Is it really expected that distributions request the legacy controller manually, or there's a reasonable fix pending?

As running processes in a transient scope was the expected migration away from KillUserProcesses=yes, it's a bit sad that the whole setup is broken.

**Comment by poettering** [comment]
Hmm, so I tested this again in hybrid, on kernel 4.11. It appears to just work now here. Is this still an issue? Did the kernel change recently on this?

**Comment by lilydjwg** [comment]
I don't know what hybrid mode is, but I still have the issue with Arch Linux, kernel 4.12.4, systemd 234.11.

**Comment by gdamjan** [comment]
On Arch, with kernel 4.13.1 and systemd 234.11-9 the systemd-run (from the original bug report) doesn't work in neither hybrid nor unified mode.

The error is:
```
Sep 12 14:30:09 arch-uefi-test systemd[276]: run-r072f0086eca04eb9900cd0002d92c2b6.scope: Failed to add PIDs to scope's control group: Permission denied
```

unified mode was enabled with `systemd.unified_cgroup_hierarchy=1`, without it, systemd defaulted to hybrid mode.

**Comment by sourcejedi** [comment]
+1.  I'm getting this message with systemd v234-424-gc13ee7cc8 installed from source.  No options to ./configure, no options on kernel cmdline.  System is Fedora 26 in a VM.  Kernel 4.12.9-300.fc26.x86_64 and 4.11.11-300.fc26.x86_64, both show this result.  Selinux is in permissive mode.

There doesn't seem to be a problem with the packaged systemd-233-6.fc26.x86_64, which is what I have on the physical host.  I don't know why that would be.

**Comment by poettering** [comment]
Hmm, after looking into this: I figure little has changed regarding this on the kernel side, I figure for now the only thing we can do is to move this to v236...

**Comment by akors** [comment]
So what is the currently accepted way to keep a `screen` session running after login?

**Comment by keszybz** [comment]
Don't use unified hierarchy yet.

**Comment by gasinvein** [comment]
So is there any workaround without disabling unified hierarchy?

**Comment by onilton** [comment]
> This bug has been around for as long as the new hierarchy has been available.
> 
> My workaround is this script:
> 
> ```shell
> #!/usr/bin/env bash
> 
> set -euo pipefail
> 
> file=/sys/fs/cgroup/user.slice/user-$(id -u).slice/cgroup.procs
> 
> sudo chown $(whoami):root $file
> sudo chmod g+w            $file
> ```

For those arriving late and using ubuntu:

file=/sys/fs/cgroup/unified/user.slice/user-$(id -u).slice/cgroup.procs

**Comment by lemmy04** [comment]
> > This bug has been around for as long as the new hierarchy has been available.
> > My workaround is this script:
> > ```shell
> > #!/usr/bin/env bash
> > 
> > set -euo pipefail
> > 
> > file=/sys/fs/cgroup/user.slice/user-$(id -u).slice/cgroup.procs
> > 
> > sudo chown $(whoami):root $file
> > sudo chmod g+w            $file
> > ```
> 
> For those arriving late and using ubuntu, the path may be slightly different:
> 
> ```shell
> #!/usr/bin/env bash
>  
> set -euo pipefail
>  
> file=/sys/fs/cgroup/unified/user.slice/user-$(id -u).slice/cgroup.procs
>  
> sudo chown $(whoami):root $file
> sudo chmod g+w            $file
> ```

where would I put that script? Somewhere where it gets executed on login? Then it needs to be somewhere where regular users can't edit it - /etc/profile.d comes to mind.

and the user logging in needs to be allowed to use sudo?

TBH, that **sucks**, security-wise.

**Comment by keszybz** [comment]
@lemmy04 the bug has was fixed back in 2018. Please update!

**Comment by lemmy04** [comment]
I'm running the latest openSUSE Leap 15.2, not **my** decision to still have systemd 234 in there o.0

**Comment by zasdfgbnm** [comment]
So what is the recommended way to allow unprivileged users to move his/her processes from somewhere like `/sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope/` to a different cgroup? Currently  `session-2.scope` are still owned by root. 

I am writing a tool that lets users use cgroups to manage resource usage. For example, a user might want to create two cgroups `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/manually_managed.slice/task1` and  `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/manually_managed.slice/task2`, and move tasks from `session-2.scope` to these cgroups, and control CPU and RAM usage of `task1` and `task2`. Is there any option somewhere to pass to systemd to allow this use case?

**Comment by danielecr** [comment]
> @lemmy04 the bug has was fixed back in 2018. Please update!

ok but what? is it enough to update some package? maybe snap? maybe I miss to run some -reconfigure, but still I have the same problem. Then I run the script. What is the security concern there?

**Comment by gdamjan** [comment]
> > @lemmy04 the bug has was fixed back in 2018. Please update!
> 
> ok but what? is it enough to update some package? maybe snap? maybe I miss to run some -reconfigure, but still I have the same problem. Then I run the script. What is the security concern there?

please ask this question in a proper support channel. either #systemd channel on Libera chat (https://web.libera.chat/) or your distro support channel.

**Comment by danielecr** [comment]
> 
> please ask this question in a proper support channel. either #systemd channel on Libera chat (https://web.libera.chat/) or your distro support channel.

@gdamjan Thank you.  I found https://lists.ubuntu.com/archives/ubuntu-devel/2021-August/041598.html I will ask on ubuntu, snapd's changelog say it was merged/fixed on October, 5th, 2021

**Comment by mikkorantalainen** [comment]
My understanding is that Ubuntu will support `systemd-run --user --scope` from version 22.04 LTS forward.
