### ISSUE TITLE
Zstd compressed /ztmp

### ISSUE THREAD

**Issue by eMPee584** [systemd/systemd#33926]
### Component

systemd

### Is your feature request related to a problem? Please describe

Excessive flash write strain should be prevented when long-term using live usb distros like our [schulstick](https://github.com/fsfw-dresden/usb-live-linux).

### Describe the solution you'd like

A compressed ramdisk is very practical as an ephemeral working space.
We are using `systemd-zram-generator` and a `/etc/systemd/zram-generator.conf` file as in:

```
# normal zram swap
[zram0]
zram-size = ram * 0.7
compression-algorithm = lz4

# compressed mount point as ephemeral work space
[zram1]
zram-size = ram * 0.3
compression-algorithm = lz4
mount-point = /ztmp
```

I think it would even make more sense to compress /tmp by default but the [feature request on the kernel bugzilla](https://bugzilla.kernel.org/show_bug.cgi?id=213197) has been ignored as of yet 😂

**Comment by bluca** [comment]
I'm not sure what the request is about? You can already use systemd-zram-generator?

**Comment by eMPee584** [comment]
Ah sorry, that wasn't clear; I wanted to spark a discussion whether a `/ztmp` would make sense as default.

**Comment by YHNdnzj** [comment]
> Ah sorry, that wasn't clear; I wanted to spark a discussion whether a `/ztmp` would make sense as default.

I doubt it. First of all, more distros have been adopting zswap/zram-backed swap by default. It's more sensible to let kernel decide when to swap out cold tmpfs data. Secondly, what semantics of `/ztmp/` do you specifically expect? Let's not expose such implementation details to the users of `/tmp/`, which would most likely create more churn rather than actually improving performance.

Sorry, but I'm not convinced. It's always possible to customize your own system with zram-generator and `$TMPDIR`, but doesn't seem useful both in the long run and wrt semantics.
