### ISSUE TITLE
sysv-generator not adding Wants=rpcbind.target

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#3395]
Hi,

In debian, a LSB initscript with the following header doesn't result in a .service that pulls rpcbind.target, the generator only adds an After=rpcbind.target:

```
# Required-Start:    $portmap $time
# Required-Stop:     $time
# Default-Start:     S
# Default-Stop:      0 1 6
```

Shouldn't a Wants=rpcbind.target also be added by the sysv-generator for initscript that requires portmap?

**Comment by fsateler** [comment]
Given that rpcbind.target is passive, it should be probably be treated like network-online.target: https://github.com/systemd/systemd/blob/v230/src/sysv-generator/sysv-generator.c#L433

**Comment by bigon** [comment]
To add a bit more context, in debian we have at least one service (nis) that is not using a .service and that is not using the unix socket to connect to rpcbind. The LSB script declares a dependency against $portmap facility.

A proper fix for this is to add a .service file I guess but in the mean time the idea was:

Add a WantedBy=rpcbind.target (in addition to Wants/Before=rpcbind.target) in the rpcbind.service and then make the sysv-generator add an additional Wants=rpcbind.target for the LSB scripts declaring a dependencies against portmap.

That would mean:
- If the .service is started, the target is also started (as written in the manpage)
- If the .target is started, the service would also be started

**Comment by poettering** [comment]
so, in systemd, requirement dependencies are processed during execution of a service, not while they are being enabled. This is different from LSB, where the requirement dependencies have no effect when a service is executed, but only an effect when they are being enabled. In order to come close to the original LSB behaviour sysv-generator won't translate the LSB requirement deps into native requirement deps, but uses them only for getting the right order into place. Processing of the requirement is left to chkconfig/update-rc.d which has the job of enabled/disabling the service in question.

Hence, not generated requirement dependencies is really by design here, as we don't want to override the enablement status of a service here. Or to say this differently: on traditional SysV if you have an LSB service A which declares a `Required-Start:` dep on a service B, and you invoke A via `/etc/init.d/A start` then this will no start B. However if you run `chkconfig A on`, then B will also be enabled. OTOH on systemd if a you have native service X which declares a `Requires=` on a service Y and you invoke X via `systemctl start X` then this will start Y, too. However, if you run `systemctl enable X`, then this has no immediate effect on Y. And in order to respect that difference we won't translate `Required-Start:` into `Requires=`.

Hope this makes sense.
