### ISSUE TITLE
Naming conflict when booting with multiple virtio-net NICs

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#34082]
### systemd version the issue has been seen with

256

### Used distribution

CentOS Stream 10

### Linux kernel version used

6.10.0-rc4

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

Multiple virtio-net NICs should use udev's stable network interface names and no naming conflicts should occur.

### Unexpected behaviour you saw

However, as soon as I add second virtio-net NIC I am running into naming conflict (because both interfaces try to claim ens0 name) and one interface ends up with eth0 name. This is most likely caused by recent change https://github.com/systemd/systemd/commit/0a4ecc54cb9f2d3418b970c51bfadb69c34ae9eb. 

### Steps to reproduce the problem

1. Boot latest CentOS Stream 10 with systemd-256-12
2. Verify that single virtio NIC has ens0 interface name
3. Shutdown the VM
4. Add another virtio-net NIC
5. Boot

**Comment by msekletar** [comment]
Btw, this is probably a kernel bug, but before it is dealt with, we may need to disable `NAMING_FIRMWARE_NODE_SUN` for the time being.

**Comment by poettering** [comment]
Hmm, might be good if the kernel would iterate throught the ACPI definitions and if sees non-unique _SUN entries it should suppress the whole _SUN info. Something that carries "unique" in the name but is not, should simply be suppressed.

**Comment by champtar** [comment]
I went with ACPI _SUN because it seemed pretty safe: https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/06_Device_Configuration/Device_Configuration.html#sun-slot-user-number
`_SUN is an object that evaluates to the slot-unique ID number for a slot`

@msekletar have you opened a ticket on qemu side ? (I assume qemu is responsible for generating the ACPI tables)

I would prefer @poettering suggestion instead of a revert as https://github.com/systemd/systemd/commit/0a4ecc54cb9f2d3418b970c51bfadb69c34ae9eb actually fixes slot naming on real hardware

On systemd side maybe we need a `net.naming_mask` to be able to enable / disable each flags individually

**Comment by msekletar** [comment]
I didn't open any other ticket yet.

**Comment by champtar** [comment]
Just opened a qemu ticket: https://gitlab.com/qemu-project/qemu/-/issues/2530

@msekletar @poettering what do you think about just ignoring _SUN == 0 ?

Also @msekletar what is your host OS ? I can reproduce it with Fedora 40, but with Alma 8.10 as host `firmware_node` is missing, haven't tried EL 9 as host

**Comment by champtar** [comment]
In previous implementation we were ignoring slot == 0
https://github.com/systemd/systemd/blob/0035597a30d120f70df2dd7da3d6128fb8ba6051/src/udev/udev-builtin-net_id.c#L139

**Comment by champtar** [comment]
PR to ignore firmware_node/sun == 0: https://github.com/systemd/systemd/pull/34099
