### ISSUE TITLE
journalctl does not respect --all with json output

### ISSUE THREAD

**Issue by bobrik** [systemd/systemd#3416]
Debian Jessie, stock or testing systemd:

```
# journalctl --version
systemd 230
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```

Related Docker issue: https://github.com/docker/docker/issues/15722

Somewhat related systemd issue: https://github.com/systemd/systemd/pull/1460

Stock journalctl outputs:

``` json
{
    "__CURSOR" : "s=5d26294b5919405f962545870aae8d16;i=be3105;b=b959b49e885b4c10b502ffaf4e46c96b;m=296eeec21a8;t=53438668c4bae;x=eeef85e9c70c25f9",
    "__REALTIME_TIMESTAMP" : "1464791726836654",
    "__MONOTONIC_TIMESTAMP" : "2847276802472",
    "_BOOT_ID" : "b959b49e885b4c10b502ffaf4e46c96b",
    "_TRANSPORT" : "journal",
    "_PID" : "18509",
    "_UID" : "0",
    "_GID" : "0",
    "_COMM" : "docker",
    "_EXE" : "/usr/bin/docker",
    "_CMDLINE" : "/usr/bin/docker daemon -H fd:// --storage-driver overlay --exec-opt native.cgroupdriver=systemd --log-driver journald",
    "_CAP_EFFECTIVE" : "3fffffffff",
    "_SYSTEMD_CGROUP" : "/system.slice/docker.service",
    "_SYSTEMD_UNIT" : "docker.service",
    "_SYSTEMD_SLICE" : "system.slice",
    "_MACHINE_ID" : "327881646f66435f8402208ed69def74",
    "_HOSTNAME" : "myhost",
    "PRIORITY" : "6",
    "CONTAINER_ID" : "17fb289f439b",
    "CONTAINER_ID_FULL" : "17fb289f439b3a5bb5dc04bad06dc23d12b096f98ca6d70ebff001a22a3d6f1e",
    "CONTAINER_NAME" : "backstabbing_davinci",
    "CONTAINER_TAG" : "wtf",
    "MESSAGE" : [ 87, 101, 100, 32, 74, 117, 110, 32, 32, 49, 32, 49, 52, 58, 51, 53, 58, 50, 54, 32, 85, 84, 67, 32, 50, 48, 49, 54, 13 ],
    "_SOURCE_REALTIME_TIMESTAMP" : "1464791726836197"
}
```

With a little patch (expected behavior):

``` json
{
    "__CURSOR" : "s=5d26294b5919405f962545870aae8d16;i=be3105;b=b959b49e885b4c10b502ffaf4e46c96b;m=296eeec21a8;t=53438668c4bae;x=eeef85e9c70c25f9",
    "__REALTIME_TIMESTAMP" : "1464791726836654",
    "__MONOTONIC_TIMESTAMP" : "2847276802472",
    "_BOOT_ID" : "b959b49e885b4c10b502ffaf4e46c96b",
    "_TRANSPORT" : "journal",
    "_PID" : "18509",
    "_UID" : "0",
    "_GID" : "0",
    "_COMM" : "docker",
    "_EXE" : "/usr/bin/docker",
    "_CMDLINE" : "/usr/bin/docker daemon -H fd:// --storage-driver overlay --exec-opt native.cgroupdriver=systemd --log-driver journald",
    "_CAP_EFFECTIVE" : "3fffffffff",
    "_SYSTEMD_CGROUP" : "/system.slice/docker.service",
    "_SYSTEMD_UNIT" : "docker.service",
    "_SYSTEMD_SLICE" : "system.slice",
    "_MACHINE_ID" : "327881646f66435f8402208ed69def74",
    "_HOSTNAME" : "36com79",
    "PRIORITY" : "6",
    "CONTAINER_ID" : "17fb289f439b",
    "CONTAINER_ID_FULL" : "17fb289f439b3a5bb5dc04bad06dc23d12b096f98ca6d70ebff001a22a3d6f1e",
    "CONTAINER_NAME" : "backstabbing_davinci",
    "CONTAINER_TAG" : "wtf",
    "MESSAGE" : "Wed Jun  1 14:35:26 UTC 2016\u000d",
    "_SOURCE_REALTIME_TIMESTAMP" : "1464791726836197"
}
```

Little patch mentioned earlier:

``` diff
diff --git a/src/shared/logs-show.c b/src/shared/logs-show.c
index 9351b85..6b4c957 100644
--- a/src/shared/logs-show.c
+++ b/src/shared/logs-show.c
@@ -607,7 +607,7 @@ void json_escape(
         if (!(flags & OUTPUT_SHOW_ALL) && l >= JSON_THRESHOLD)
                 fputs("null", f);

-        else if (!utf8_is_printable(p, l)) {
+        else if (!utf8_is_printable(p, l) && !(flags & OUTPUT_SHOW_ALL)) {
                 bool not_first = false;

                 fputs("[ ", f)
```

`\r` looks perfectly printable unicode character to me:

```
# ./journalctl -a -n1 -o json-pretty CONTAINER_TAG=wtf | jq .MESSAGE
"Wed Jun  1 14:35:26 UTC 2016\r"
# ./journalctl -a -n1 -o json-pretty CONTAINER_TAG=wtf | jq -r .MESSAGE
Wed Jun  1 14:35:26 UTC 2016
```

I've seen the issue happening with docker containers running without `tty` (no `\r` at the end), but I can't find an example right now.

It seems that:
- Whitespace-ish `\r` is not stripped, while it should be.
- Printable `\r` is considered unprintable.
- `--all` is not respected for json.

My patch only addresses the latter. Should I make a PR?

cc @dqminh, @evverx

**Comment by evverx** [comment]
> I've seen the issue happening with docker containers running without tty (no \r at the end), but I can't find an example right now.

Hm, seems like https://github.com/systemd/systemd/pull/2755#issuecomment-189761322

``` sh
-bash-4.3# printf "hola\n\rbro\n\r" | systemd-cat -t HOLA-BRO-SLASH-R

-bash-4.3# journalctl --sync

-bash-4.3# journalctl -b -t HOLA-BRO-SLASH-R --no-pager --no-hostname
-- Logs begin at Wed 2016-06-01 15:56:57 UTC, end at Wed 2016-06-01 16:05:26 UTC. --
Jun 01 16:04:57 HOLA-BRO-SLASH-R[52]: hola
Jun 01 16:04:57 HOLA-BRO-SLASH-R[52]: [4B blob data]
Jun 01 16:04:57 HOLA-BRO-SLASH-R[52]: [1B blob data]
```

**Comment by evverx** [comment]
> Whitespace-ish \r is not stripped, while it should be.

We strip trailing "\r"s:

``` sh
-bash-4.3# printf "ab\r" | systemd-cat -t TRAILING-R
-bash-4.3# journalctl --sync
-bash-4.3# journalctl -o verbose -t TRAILING-R | grep MESSAGE
    MESSAGE=ab
```

We don't strip leading "\r":

``` sh
-bash-4.3# printf "\rab" | systemd-cat -t LEADING-R
-bash-4.3# journalctl --sync
-bash-4.3# journalctl -t LEADING-R -o verbose | grep MESSAGE
    MESSAGE=[3B blob data]
```

See https://github.com/systemd/systemd/pull/1460#issuecomment-145784543

> We actually had this discussion before. I don't think we should guarantee bit-exact storing away of log messages when using stdout or stderr. Making sure leading whitespace is retained is important, so that indenting stays around, but trailing whitespace and empty lines I think we should suppress in order to keep logs minimal

.

> Printable \r is considered unprintable.
> --all is not respected for json.

Indeed. Seems like a bugs to me.

**Comment by evverx** [comment]
> We strip trailing "\r"s

Well, we don't strip trailing "\r"s sometimes:

``` sh
printf "SYSLOG_IDENTIFIER=native-slash-r\nMESSAGE=hola\r" | logger --journald

journalctl -t native-slash-r -o verbose | grep MESSAGE
    MESSAGE=[5B blob data]
```

**Comment by evverx** [comment]
BTW:
seems like Docker uses native logging [some](https://github.com/coreos/go-systemd/blob/master/journal/journal.go) [how](https://github.com/docker/docker/blob/master/daemon/logger/journald/read.go#L218). so, maybe, Docker/~~journald.go~~ should handle `SIGBUS`: https://github.com/systemd/systemd/issues/2323

**Comment by dqminh** [comment]
@evverx interesting.Do you have a note somewhere on how should SIGBUS be handled ?

**Comment by evverx** [comment]
@dqminh , there are no docs (or I can't find)
See
fa6ac76083b8ffc13
2cf4172a71860c
https://github.com/systemd/systemd/blob/master/src/basic/sigbus.c

**Comment by poettering** [comment]
Yeah, we really should strip trailing \r.

(There's currently no nice API for clients to catch SIGBUS properly. But that matters only for read acess to the journal anyway. As long as you only log to the journal you don't need to bother anyway as no mmap() is involed.)

**Comment by poettering** [comment]
So, we do strip trailing \r when using the stderr/stdout stream logic of journald, or when using traditional syslog() based logging. We do not strip it when the native protocol is used though (i.e. when the journal gets a series of binary field blobs), and I am pretty sure we shouldn't in that case either, it's up to the client to strip it then, I think. After all, in the stderr/stdout stream case, and in the syslog case we get human readable log messages, that are very unstructured and pretty free-form, and journald then cleans then up and structures them. In the native protocol case however, journald already gets the fully structured data, enhanced with all kinds of metadata, in binary form, and hence I think we shouldn't alter it anymore, but expect that the client already cleaned things up when it converted some human readable log message into this structured, binary form.

it appears that docker speaks the journal protocol natively. Now I am wondering how it does that. It either does that either through our sd-journal library, which provides a friendly interface to the native protocol. In that code we actually don't strip trailing whitespace yet (but we should, and I will prep a patch for that). My guess however is that that they do not user our library but use the naked protocol directly, passing binary, structured journal records data. In that case I am pretty sure it's docker's job to remove the trailing whitespace really, when they format the strings and before they pack them into binary blobs.

"\r" is pretty uncommon on UNIX, and it's a great way to play games with users, because it allows reprinting things on the same line, potentially hiding stuff in files. It's like ^H, which allows similar hackery like that. I am pretty sure that when checking if some record is binary we should continue to consider stuff that contains \r or ^H binary and not show it by default as text string, since that's nasty on terminals.

That said, I do agree that --all should output the \r stuff anyway. I'll hence prep to patches now:

a) one that makes --all work as suggested,

b) one that makes sure sd-journal strips trailing whitespace when formatting format-string based log messages, before turning them into binary journal records that are sent to journald.

Hope that makes sense.

**Comment by poettering** [comment]
the promised changes are now waiting in PR #3636.

**Comment by poettering** [comment]
@evverx btw, the reason why we don't strip \r in your last example command line is precisely because in that case the native protocol is used and it is the duty of the client side to drop the trailing whitespace, which "logger" doesn't do however sofar, but should with PR #3636 in place, given that logger appears to use sd-journal, and the fix in PR #3636 should fix fhis for sd-journal.

**Comment by evverx** [comment]
@poettering , thanks for the detailed explanation!

> it is the duty of the client side to drop the trailing whitespace, which "logger" doesn't do however sofar, but should with PR #3636 in place

`logger` [calls](https://github.com/karelzak/util-linux/blob/1c7227598824b1d9140298e9fe5742cae4131130/misc-utils/logger.c#L363) `sd_journal_sendv`.  So #3636 will not change something.

**Comment by poettering** [comment]
@evverx ah, good to know. @karelzak, logger is part of util-linux, any chance you can change it so that it removes trailing whitespace (including \r) from the end of log lines before passing them off to journald?
