### ISSUE TITLE
domain-limited DNS servers should not appear as global nameservers in resolved's resolv.conf

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#3420]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian unstable, git master build
### In case of bug report: Steps to reproduce the problem

In networkd, configure a `.network` device to have a DNS server which only applies to particular domains, e. g.

```
[Network]
DNS=1.1.1.1
Domains= ~company
```

Ensure `systemd-resolved` is  enabled. There should also be a global nameserver from your regular wifi/ethernet, let's call it 2.2.2.2.
### In case of bug report: Expected behaviour you didn't see

The generated `/run/systemd/resolved/resolv.conf` should have `nameserver 2.2.2.2`, but _not_ the domain specific 1.1.1.1 server.
### In case of bug report: Unexpected behaviour you saw

The generated `/run/systemd/resolved/resolv.conf` has both  `nameserver 2.2.2.2` and `nameserver 1.1.1.1`. This leads to queries like `google.com` going to the DNS specific `*.company` nameserver, which in the harmless case does not work, but it might also lead  to lookup loops and is also kind of a privacy violation.

It is justified to add this as a global name server _only_ if `Domains=` contains `~.`.

With this description this applies to the generated `resolv.conf` only, and thus to programs not using nss-resolve/`nsswitch.conf` (such as `host` or `dig`). However, the same issue is present with resolved, it uses domain specific name servers for requests that don't match the domains. However, I'm going to file a separate issue for this as these don't necessarily have the same fix.

**Comment by martinpitt** [comment]
I created a test case for `test/networkd-test.py` which reproduces/illustrates this issue: https://gist.github.com/martinpitt/b99823d1af105ffe79585de62e2d6da1

**Comment by martinpitt** [comment]
To clarify: `resolv.conf` simply does not provide any syntax for domain specific DNS servers, so we can't provide this to legacy software which does not use libnss-resolve. I. e. if you use domain specific DNS servers with networkd, you also have to use resolved, which I think is a fair requirement.

**Comment by poettering** [comment]
Hmm, but how is this a bug? We cannot map the concept of DNS servers with domains attached to resolv.conf...

Also, I think there's a misunderstanding here. The domains you configure are used for routing, but I think not in the way you assume. Specifically: if a lookup X appears in some interface's domain list, we mount the lookup to that interface/DNS server. Since multiple interfaces may declare the same domain this means the lookup might be routed to multiple interfaces. Now, for every lookup Y that appears in no interface's domain list we send it to all interfaces at the same time.

**Comment by poettering** [comment]
(I will probably add a minimal local DNS server listening on 127.0.0.53:53 soon, that you can place in /etc/resolv.conf and allows routing DNS server queries with resolved, even if they are done with legacy DNS clients. However this will necessariuly be incomplete, as link-local name resolution cannot be exposed that way since it generally requires inclusion of the ifindex in the response and DNS can of course not carry that. Hence: programs _really_ should use NSS (with nss-resolve as backend) or resolved's native bus APIs, but not talk DNS themselves.)

**Comment by martinpitt** [comment]
> We cannot map the concept of DNS servers with domains attached to resolv.conf...

Exactly, hence these shouldn't appear in there at all IMHO, as there is no way to make them specific to the configured domains only. As I said above, if you have that configuration you then must use resolved as well, and let that DTRT.

> Now, for every lookup Y that appears in no interface's domain list we send it to all interfaces at the same time.

Right, and I think that's wrong. If the config says "use this DNS server only for these domains" and you throw other requests at them, that seems like a direct contradiction; plus the privacy issue, and spamming that nameserver with requests it cannot/does not want to handle.

**Comment by poettering** [comment]
The config says "route these lookups to this interface/DNS server". It does not say "don't route anything else to this interface/DNS server".

I mean, I can understand that you want such limitation, but that's now how this is designed right now, and it's not a bug, it's by design. I mean, I am open to adding something like a boolean flag "Don't Route Anything Else Here, Please!" per interface, that should do what you say, but that's a new RFE.

**Comment by martinpitt** [comment]
> I mean, I am open to adding something like a boolean flag

We already  have that, it's `~.`. That says "route anything else here too". Right now this doesn't seem to make any difference, as even if you don't specify it, other requests are routed there regardless.

**Comment by martinpitt** [comment]
> I mean, I can understand that you want such limitation, but that's now how this is designed right now, and it's not a bug, it's by design. 

I honestly can't understand this. What's the utility of introducing a `Domains= ~foo` if that does not really change the behaviour at all? And `~.` is a complete no-op then. What is the current behaviour of the syntax above useful for that you don't already get with global nameservers? (I'm honestly interested, as I'm utterly confused how this could not be considered a bug). Thanks!

**Comment by piotr-dobrogost** [comment]
Could someone please clarify what exactly does *domain-limited DNS server* mean here? Is this only when there are routing domain(s) specified or does it apply also for non-routing domain(s) specified in `Domains=` directive? What if there are both routing and non-routing domains specified?

**Comment by timriker** [comment]
In my case, I want to use my internal DNS servers over my vpn connection to lookup internal services. This is partly because some internal servers are NOT published externally, and partly because using the internal address on some services gives me more functionality. I do NOT want to lookup external addresses using the internal dns over vpn as those may needlessly redirect me to the internal proxy and slow down those requests. ie:

vpn connection for 10.0.0.0/24
ns1.example.com and ns2.example.com delivered with 10.*.*.* address over vpn for use with example.com, example.net and example.org
external dns on wlan0 set to 8.8.8.8

how do I setup systemd-resolved to always use only the 10.*.*.* dns servers for the listed domains and always use only the 8.8.8.8 for any other domain?
