### ISSUE TITLE
SELinux prevents `systemd-sysctl` from reading `/etc/sysctl.d/10-congestion-control.conf`

### ISSUE THREAD

**Issue by nisbet-hubbard** [systemd/systemd#34246]
### systemd version the issue has been seen with

systemd-252-32.el9_4.6

### Used distribution

RHEL 9

### Linux kernel version used

5.14.0-427.31.1.el9_4.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysctl

### Expected behaviour you didn't see

`systemd-sysctl.service` exits with success.

### Unexpected behaviour you saw

`SELinux is preventing /usr/lib/systemd/systemd-sysctl from read access on the file /
etc/sysctl.d/10-congestion-control.conf`

### Steps to reproduce the problem

`reboot`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-sysctl[331409]: Failed to open file '/etc/sysctl.d/10-congestion-control.conf', ignoring: Permission denied.
```

**Comment by yuwata** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
