### ISSUE TITLE
Using fstab in nspawn

### ISSUE THREAD

**Issue by fxzxmicah** [systemd/systemd#34344]
### systemd version the issue has been seen with

255

### Used distribution

Fedora 40

### Linux kernel version used

6.9.10-200.fc40.x86_64

### CPU architectures issue was seen on

None

### Component

systemd-nspawn

### Expected behaviour you didn't see

Automatically mount partitions in fstab.

### Unexpected behaviour you saw

There is no automatic mounting of partitions in fstab.

### Steps to reproduce the problem

In `.nspawn` file:
```
Bind=/dev/sda2
Bind=/dev/disk
```
In `systemd-nspawn@.service.d` config file:
```
DeviceAllow=block-blkext rw
DeviceAllow=block-sd rw
```
`fstab` file in container:
```
/dev/sda2 /mnt ext4 defaults 0 0
```

**Comment by poettering** [comment]
devices are not virtualized for containers on linux. i.e there's only the host sysfs tree. And thus only one udev, and since systemd tracks the state of devices via udev/sysfs this also means that device mgmt via systemd is not available inside containers. And that means we cannot interpret fstab. if we did all listed mounts would just fail because their devices would never show up.

Sorry, but this needs addressing in the linux kernel: they'd need to virtualize device management for containers. Once they add that we can certainly support that too (in fact it would start to just work). But until then, sorry, no can do.

Good luck.

**Comment by fxzxmicah** [comment]
Then all I can do now is write a service file and execute `mount -a` in it?

**Comment by fxzxmicah** [comment]
```
[Unit]
Description=Mount all filesystems from /etc/fstab

[Service]
Type=oneshot
ExecStart=/bin/mount -a
RemainAfterExit=yes

[Install]
WantedBy=local-fs.target
```
