### ISSUE TITLE
case insensitive matching in udev rules files

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#34359]
### systemd version the issue has been seen with

v255.5-1.3.hs+fb.el9

### Used distribution

CentOS Stream 9

### Linux kernel version used

6.9.0-0_fbk0_hardened_rc21_1078_g8787f6ea9f10

### CPU architectures issue was seen on

x86_64

### Component

udev rule files

### Expected behaviour you didn't see

MAC address should be case insensitive in udev rules (since it's case insensitive in .link and .network files).

### Unexpected behaviour you saw

Udev rule didn't run when MAC address was upper case. I'm surprised we didn't hit this sooner.

### Steps to reproduce the problem

Example rule file:
```
/etc/udev/rules.d]$ cat 1-helloworld.rules
ACTION=="add", SUBSYSTEM=="net", ATTR{addr_assign_type}=="0", ATTR{address}=="b0:26:28:4e:7e:b6", PROGRAM="/bin/sh -c 'echo lowercasetest >> /tmp/usb.log'"
ACTION=="add", SUBSYSTEM=="net", ATTR{addr_assign_type}=="0", ATTR{address}=="B0:26:28:4E:7E:B6", PROGRAM="/bin/sh -c 'echo uppercasetest >> /tmp/usb.log'"
```

Ran `sudo /bin/udevadm trigger --action=add /sys/class/net/eth0`

Contents:
```
$ cat /tmp/usb.log 
lowercasetest
```

**Comment by DaanDeMeyer** [comment]
So ideally we'd automatically do case insensitive matching for mac addresses, but I would guess we need to check if something looks like a mac address to make that work.

Another option is to add a case insensitive match operator, e.g. `=~` or so.

**Comment by arvidjaar** [comment]
> Another option is to add a case insensitive match operator, e.g. `=~` or so.

`udev` already supports string modifier to enable escape sequences, what about `==i"xxx"` for "case-insensitive"? Both `e` and `i` could even be combined.

**Comment by poettering** [comment]
I am pretty sure we should not try to detect sysfs attrs that look like mac addresses, that can only fail.

having an explicit case insensitive string comparison operation mit be ok

**Comment by ryantimwilson** [comment]
Here is the PR for the fix using @arvidjaar's suggested solution: https://github.com/systemd/systemd/pull/34412

However, I'm not positive this is the right way since `i` is an operator on the value, not the comparison operation. For example, if Linux one day decided to return B0:26:28:4e:7e:b6 for the MAC address (aka a mix of lowercase and uppercase chars), the comparison would still fail with `i`. The more robust comparison operator like ATTR{address}~="B0:26:28:4E:7E:B6" to indicate case insensitive matching but looking at the code, this will be a deeper change.

Happy to hear suggestions one way or the other

**Comment by yuwata** [comment]
-> #34425.
