### ISSUE TITLE
systemd-cryptsetup isn't unlocking my /home partition automatically using TPM2

### ISSUE THREAD

**Issue by Ttfgggf** [systemd/systemd#34530]
### systemd version the issue has been seen with

 256.5 

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

6.10.11-1-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

For the /home partition and / to automatically unlock without any errors and asking for an encryption passphrase for /home before unlocking the system.

### Unexpected behaviour you saw

/ unlocks automatically using the TPM2 but /home doesn't automatically unlock. Leading to me having to enter the passphrase for /home.

### Steps to reproduce the problem

1. Install openSUSE Tumbleweed.
2. During the installing of the OS, When selecting the disk to install it on, click on the option to have a separate home partition and then select the Full Disk Encryption Option. (As far as I know the openSUSE Installer encrypts all the partitons in relation to this stage with the same key)
3. Go through the rest of the installation as normal
4. Once installation is done and system is rebooted as normal. Install tpm2.0-tools package.
5. Enroll both the / and /home partitions to the TPM2 using either sdbootutil (built by openSUSE which I believe uses either systemd-cryptenroll or systemd-cryptsetup under the hood) or systemd-cryptenroll.
6. If done via sdbootutil, no need to regenerate the initramfs or update the /etc/crypttab (as I believe it does it as part of running the commands) but if done via systemd-cryptenroll update the /etc/crypttab and regenerate the initramfs.
7. Reboot and then find that it is asking for encryption password for /home.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
https://paste.opensuse.org/pastes/89f65d2a83f5 - Here is the logs from my system collected before.

I also put this post up with my linux distributions forums https://forums.opensuse.org/t/set-up-encryption-on-root-home-paritions-on-a-system-using-systemd-boot/178766/15 to try to get some assistance but I was advised to raise this issue here.
```

**Comment by gdonval** [comment]
Relevant part:

```
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Trying to load /usr/lib64/cryptsetup/libcryptsetup-token-systemd-tpm2.so.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_open@CRYPTSETUP_TOKEN_1.0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_buffer_free@CRYPTSETUP_TOKEN_1.0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_validate@CRYPTSETUP_TOKEN_1.0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_dump@CRYPTSETUP_TOKEN_1.0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_open_pin@CRYPTSETUP_TOKEN_1.0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_version@CRYPTSETUP_TOKEN_1.0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token handler systemd-tpm2-1.0 systemd-v256.5 (256.5+suse.7.gbef0958f4d) loaded successfully.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Requesting JSON for token 0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loaded 'libtss2-esys.so.0' via dlopen()
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loaded 'libtss2-rc.so.0' via dlopen()
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loaded 'libtss2-mu.so.0' via dlopen()
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Failed to find TPM2 pcrlock policy file 'pcrlock.json': No such file or directory
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: No encrypted system credentials passed.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Couldn't find pcrlock policy for volume.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: systemd-tpm2 open failed: Object is remote.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token 0 (systemd-tpm2) open failed with -66.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token activation unsuccessful for device /dev/disk/by-uuid/e557c87e-9a6e-4a29-8ce4-57691403002f: Object is remote
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Beginning attempt 0 to unlock.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/e557c87e-9a6e-4a29-8ce4-57691403002f.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Activating volume cr_home [keyslot -1] using token.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: dm versions   [ opencount flush ]   [16384] (*1)
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: dm status cr_home  [ opencount noflush ]   [16384] (*1)
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token 0 unusable for segment 0 with desired keyslot priority 2.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Requesting JSON for token 0.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Failed to find TPM2 pcrlock policy file 'pcrlock.json': No such file or directory
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: No encrypted system credentials passed.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Couldn't find pcrlock policy for volume.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: systemd-tpm2 open failed: Object is remote.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token 0 (systemd-tpm2) open failed with -66.
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: TPM2 operation failed, falling back to traditional unlocking: Object is remote
```

Very likely not a bug but configuration problem. You've not said how you used `systemd-cryptenroll` or what PCR you bound your keys to.

**Comment by Ttfgggf** [comment]
> Relevant part:
> 
> ```
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Trying to load /usr/lib64/cryptsetup/libcryptsetup-token-systemd-tpm2.so.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_open@CRYPTSETUP_TOKEN_1.0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_buffer_free@CRYPTSETUP_TOKEN_1.0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_validate@CRYPTSETUP_TOKEN_1.0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_dump@CRYPTSETUP_TOKEN_1.0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_open_pin@CRYPTSETUP_TOKEN_1.0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loading symbol cryptsetup_token_version@CRYPTSETUP_TOKEN_1.0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token handler systemd-tpm2-1.0 systemd-v256.5 (256.5+suse.7.gbef0958f4d) loaded successfully.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Requesting JSON for token 0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loaded 'libtss2-esys.so.0' via dlopen()
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loaded 'libtss2-rc.so.0' via dlopen()
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Loaded 'libtss2-mu.so.0' via dlopen()
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Failed to find TPM2 pcrlock policy file 'pcrlock.json': No such file or directory
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: No encrypted system credentials passed.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Couldn't find pcrlock policy for volume.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: systemd-tpm2 open failed: Object is remote.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token 0 (systemd-tpm2) open failed with -66.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token activation unsuccessful for device /dev/disk/by-uuid/e557c87e-9a6e-4a29-8ce4-57691403002f: Object is remote
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Beginning attempt 0 to unlock.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/e557c87e-9a6e-4a29-8ce4-57691403002f.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Activating volume cr_home [keyslot -1] using token.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: dm versions   [ opencount flush ]   [16384] (*1)
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: dm status cr_home  [ opencount noflush ]   [16384] (*1)
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token 0 unusable for segment 0 with desired keyslot priority 2.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Requesting JSON for token 0.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Failed to find TPM2 pcrlock policy file 'pcrlock.json': No such file or directory
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: No encrypted system credentials passed.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Couldn't find pcrlock policy for volume.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: systemd-tpm2 open failed: Object is remote.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Token 0 (systemd-tpm2) open failed with -66.
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: TPM2 operation failed, falling back to traditional unlocking: Object is remote
> ```
> 
> Very likely not a bug but configuration problem. You've not said how you used `systemd-cryptenroll` or what PCR you bound your keys to.

PCRS Used are: 0,2,4,7,9 (used with sdbootutil)

Systemd-cryptenroll was used via openSUSE sdbootutil via the command sdbootutil enroll --method tpm2. I also did try systemd-cryptenroll --tpm2-device auto /dev/nvme0n1p3 (/home drive)  --tpm2-pcrs "7" at a time after I realised sdbootutil wasn't working and the same thing happened. With a similar command for /dev/nvme0n1p2 (/)

**Comment by gdonval** [comment]
> PCRS Used are: 0,2,4,7,9 (used with sdbootutil)

PCR4 will forever fail any time the boot manager or the partition table is changed. PCR9 will forever fail from the first time you update your initramfs and/or your kernel command line options (both will be changed after a kernel update). PCR2 contains option ROM and I'm not sure how it's calculated and how consistent the result would be.

All those things will happen and given how little context we were given, I can only assume it worked the first couple times and started to fail after any of these changed.

---

> systemd-cryptenroll --tpm2-device auto /dev/nvme0n1p3 (/home drive) --tpm2-pcrs "7"

Are you sure this registered a slot and that when you did it, secure boot passed and that when you booted, secure boot passed?

**Comment by Ttfgggf** [comment]
Yes. I am sure that I registered a slot. See here. 
Secure boot passed.

https://paste.opensuse.org/pastes/46cb6d6c6def

You may see x-initrd.attach in the crypttab as well tpm2-pcrs=7. Just to reiterate , I have tried with and without those options in the crypttab and the same results has happened.

**Comment by arvidjaar** [comment]
@Ttfgggf 
> Relevant part:

The relevant parts are
```
Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Failed to find TPM2 pcrlock policy file 'pcrlock.json': No such file or directory
...
Sep 22 12:04:11 localhost systemd[1]: Mounting /var...
```
`systemd-pcrlock` stores `pcrlock.json` in `/var`. On openSUSE `/var` by default is the separate subvolume and gets mounted after `cryptsetup.target`.

The problem is due to `/var` being a separate mount point. May be, the default location for `pcrlock.json` needs to be on root.

**Comment by Ttfgggf** [comment]
> @gdonval
> 
> > Relevant part:
> 
> The relevant parts are
> 
> ```
> Sep 22 12:04:10 localhost systemd-cryptsetup[961]: Failed to find TPM2 pcrlock policy file 'pcrlock.json': No such file or directory
> ...
> Sep 22 12:04:11 localhost systemd[1]: Mounting /var...
> ```
> 
> `systemd-pcrlock` stores `pcrlock.json` in `/var`. On openSUSE `/var` by default is the separate subvolume and gets mounted after `cryptsetup.target`.
> 
> The problem is due to `/var` being a separate mount point. May be, the default location for `pcrlock.json` needs to be on root.

I really appreciate your assistance here, you're lifesaver.

**Comment by Ttfgggf** [comment]
openSUSE Bugzilla Bug Number is https://bugzilla.opensuse.org/show_bug.cgi?id=1230909

**Comment by gdonval** [comment]
It looks like openSUSE got it wrong somehow. Parsing crypttab and acting on it should not involve any explicit mount dependency. Said otherwise, the action of unlocking luks volumes and mounting partitions should be independent.

That being said, the following doc and equivalent option of cryptenroll say that missing prclock.json should be gracefully ignored:

https://www.freedesktop.org/software/systemd/man/latest/crypttab.html#tpm2-pcrlock=

So the question is, have you a pcrlock registered in your luks headers?

As a workaround for this, you can set the option to an empty string to force it disabled.

**Comment by Ttfgggf** [comment]
> It looks like openSUSE got it wrong somehow. Parsing crypttab and acting on it should not involve any explicit mount dependency. Said otherwise, the action of unlocking luks volumes and mounting partitions should be independent (and systemd manages mount dependencies very well).
> 
> 
> 
> That being said, the following doc and equivalent option of cryptenroll say that missing prclock.json should be gracefully ignored:
> 
> 
> 
> https://www.freedesktop.org/software/systemd/man/latest/crypttab.html#tpm2-pcrlock=
> 
> 
> 
> So the question is, have you a pcrlock registered in your luks headers?
> 
> 
> 
> As a workaround for this, you can set the option to an empty string to force it disabled.
> 
> 

tpm2-pcrs is the only thing I have in my /etc/crypttab other than tpm2-device=auto

No pcrlock option is registered in the luks headers as far as I know. 
Is there any way for me to check other than /etc/crypttab?

**Comment by arvidjaar** [comment]
> missing prclock.json should be gracefully ignored

It **is** gracefully ignored and user is asked for passphrase. 

>It looks like openSUSE got it wrong somehow

Care to explain "somehow"?

> Parsing crypttab and acting on it should not involve any explicit mount dependency.

The problem is not related to *parsing* crypttab. The problem is related to actually unlocking the device.

> the action of unlocking luks volumes and mounting partitions should be independent

Please explain how `systemd-cryptsetup` is expected to use `pcrlock.json` file that is located on a filesystem that is not yet mounted during unlocking. 

> have you a pcrlock registered in your luks headers?

yes, he has it.

https://forums.opensuse.org/t/set-up-encryption-on-root-home-paritions-on-a-system-using-systemd-boot/178766/10

**Comment by gdonval** [comment]
> It is gracefully ignored and user is asked for passphrase.

That's not what I nor the doc meant. If `pcrlock` has not been set to `true`, `systemd` will have a look at `pcrlock.json` policies if they exist anyway but won't fail at decrypting anything using TPM if the file is not present.

> Care to explain "somehow"?

A person commented in the openSUSE bug report:
     
> The `pcrlock.json` is in `/var/lib/systemd/pcrlock.json`. So, it is basically incompatible with separate `/var`.

It seems somehow wrong to say something is "incompatible" when the problem lies with a missing mount dependency and the use of non-default option without making sure it's properly configured. By that I mean, the manual says you can write and read `pcrlock.json` files from arbitrary locations. Also, using LUKS with separated `/var` (or, using the same train of thought, encrypted `/`) is common enough out there that, yeah, someone got it wrong somehow. And that's even before considering the then-popular use of network shares to unlock local partitions. That was at a time before `pcrlock` and even TPM were a thing but it used to work well.  

> The problem is related to actually unlocking the device.

No, the problem is that `/var`, which is not even encrypted, is not mounted before the unlocks are processed. There is a missing mount dependency here. That much is fine. I know decryption happens at the trickiest moment in the boot process with the system's filesystem not being fully initialized so it's never easy. What I don't find fine is for this kind of use case being *dismissed* as "incompatible". 

> Please explain ... on a filesystem that is not yet mounted during unlocking.

You change you dependencies so that it's mounted beforehand? You also read the manual and discover there are options to locate the file elsewhere if needed? Or you read the manual and figure `v256` got you sorted?

> Starting with v256, a copy of the /var/lib/systemd/pcrlock.json policy file is encoded in a credential (see [systemd-creds(1)](https://www.freedesktop.org/software/systemd/man/latest/systemd-creds.html#) for details) and written to the EFI System Partition or XBOOTLDR partition

I hope it is clear that it's not the fact openSUSE does not handle that use case gracefully that is a problem, it's being dismissive about it that is.

> yes, he has it.

Then he needs to use the full extent of the options offered to him or change to a system that won't find it acceptable that `/home` starts to be processed even before the base system is properly mounted.

**Comment by aplanas** [comment]
There is a lot of misunderstanding here. Most pbly the issue is somewhere in how it was installed or a bug in sdbootutil, so lets move to the discussion downstream in the openSUSE bug report :)

But let me give the chance to clarify some of the misunderstanding, in case google index the wrong ideas!

> gdonval:
> PCR4 will forever fail any time the boot manager or the partition table is changed. PCR9 will forever fail from the first time you update your initramfs and/or your kernel command line options (both will be changed after a kernel update). PCR2 contains option ROM and I'm not sure how it's calculated and how consistent the result would be.

Sure, but there is a tool that will put the predictions in place after the update.

> arvidjaar:
> systemd-pcrlock stores pcrlock.json in /var. On openSUSE /var by default is the separate subvolume and gets mounted after cryptsetup.target.

Right, but the prediction (well, the file that contains the NVIndex) is also store in the ESP, so there is the chance for the dracut-pcr-signature to inject it in the running initrd before cryptsetup generator.

Because openSUSE is not using UKIs (but type#1 BLS entries), systemd-creds cannot be used to inject credentials into the running initrd. Is this dracut service the one that do the jobs here.

**Comment by poettering** [comment]
The systemd-pcrlock policy JSON file is stored at two places since v256: 

1. In /var/
2. In the ESP, as a credential for pick-up by systemd-stub, passed to the initrd.

The former is the "official" place, the latter exists so that the rootfs, /var itself and other OS-level file systems can be unlocked via pcrlock. (because we need the file to unlock pcrlock)

It appears your distribution hasn't set that up properly (maybe is not using systemd-stub? Or not using sytsemd in the initrd properly, so that it makes sure the pcrlock policy is retained below /run?)

Either way, I agree this is something that should be continued on the OpenSUSE bug tracker I guess.

**Comment by poettering** [comment]
> Because openSUSE is not using UKIs (but type#1 BLS entries), systemd-creds cannot be used to inject credentials into the running initrd. Is this dracut service the one that do the jobs here.

It should be safe to have type#1 entries that reference ukis (i.e. type#2), so that you get a hybrid of both schemes.

(that said, type #2 only is really the way to go)
