### ISSUE TITLE
Symlink /run/user/self to /run/user/$UID

### ISSUE THREAD

**Issue by killermoehre** [systemd/systemd#34609]
### Component

pam_systemd, systemd-logind

### Describe the solution you'd like

`$XDG_RUNTIME_DIR` is the goto variable for applications to write runtime configuration, but only if the application knows how to use environment variables.

I propose that `/run/user/self` is a bind mount to `/run/user/$UID` propagated to `user@.service` and in `user-%i.slice`.

Example would be to move [Firefox's cache to `/run` without the need to specify a user ID](https://wiki.archlinux.org/title/Firefox/Tweaks#Move_disk_cache_to_RAM).

### The systemd version you checked that didn't have the feature you are asking for

256

**Comment by YHNdnzj** [comment]
Hmm? How do you envision a viable implementation of this? It would involve either FUSE or user-specific mount namespacing, at which point it's much easier and saner to teach whatever application you have in mind to honor `XDG_RUNTIME_DIR`?

**Comment by poettering** [comment]
> I propose that `/run/user/self` is a bind mount to `/run/user/$UID` propagated to `user@.service` and in `user-%i.slice`.

That would imply setting up a private namespace for each user, and each session because the bind mount would point to different places for each user. But that is cumbersome and comes with major problems (as it would interfere with mount propagation and such).

> Example would be to move [Firefox's cache to `/run` without the need to specify a user ID](https://wiki.archlinux.org/title/Firefox/Tweaks#Move_disk_cache_to_RAM).

The right way to reference /run/user/$UID/ is via the $XDG_RUNTIME_DIR env var, and that's widely documented in https://specifications.freedesktop.org/basedir-spec/latest/#basics for example.

Sorry, but I am not convinced this request really is a good idea, the namespace thing is just not an option, and using $XDG_RUNTIME_DIR should be fine for all cases.
