### ISSUE TITLE
/etc/machine-info is not created automatically in new vms, despite that the chassis-name, icon-name are defined

### ISSUE THREAD

**Issue by MalloZup** [systemd/systemd#3496]
### Submission type
- [x ] Bug report
### Used distribution

> OpenSUSE, FEDORA

Name: systemd  [openSUSE ]
Version: 210-83.2

Fedora: 222.14fc23
### In case of bug report: Expected behaviour you didn't see

 Looking at the documentation about machine-info:
https://www.freedesktop.org/software/systemd/man/machine-info.html#

1) i would expect:

when i type hostnamectl,  ( in a fresh vm-machine)

```
icon name: computer-vm
Chassis: vm
```

so this 2 values are well defined, but the file /etc/machine-info doesn't exist.

When i modify like `hostnamectl set-icon-name "foo"` the /etc/machine-info file then appear.

This is not really what i could call an expected behavior.
 Since  this metadata exists, then the machine-info file should also exist.
Because in this fresh machine, the chassis and icon-name are defined as an example:
`Chassis: vm`

2) I see no description, or INFO in the DOC  that  define when this file should created.
### In case of bug report: Steps to reproduce the problem

Fresh installed System. 

```
ls /etc/machine-info
ls: cannot access /etc/machine-info: No such file or directory

hostnamectl       
...
 Icon name: computer-vm
           Chassis: vm
...

 hostnamectl set-icon-name "foo"
systemd-sut:~ # cat /etc/machine-info 
ICON_NAME=foo


```

**Comment by poettering** [comment]
yeah, this is actually by design. Basically /etc/machine-info is the primary source of data returned by hostnamed, and if it exists and contains data it's what takes precedence before everything else. However, hostnamed will try to come up with somewhat useful fallback data if the file does not exist, but it will not write it to /etc/machine-info. And its good that way, so that hostnamed tracks the right default values for whatever setup it runs in if it has not be configured for anything explicitly.

But yeah, this behaviour could use much better documentation.
