### ISSUE TITLE
`systemd-analyze security` is missing `PrivatePIDs=` (and others?)

### ISSUE THREAD

**Issue by Winterhuman** [systemd/systemd#35054]
### systemd version the issue has been seen with

257-rc1

### Used distribution

Arch Linux

### Linux kernel version used

6.11.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-analyze

### Expected behaviour you didn't see

`PrivatePIDs=` is listed by `systemd-analyze security example.service` alongside the other hardening options.

### Unexpected behaviour you saw

`PrivatePIDs=` is missing from `systemd-analyze security`.

Other options, or new values for existing options like `PrivateTmp=disconnected`, may need updating in `systemd-analyze security` as well.

Side note: Some of systemd's default services may want to have `PrivatePIDs=yes` too, where now possible.

### Steps to reproduce the problem

1. Run `systemd-analyze security` on any random service.
2. See that `PrivatePIDs=` isn't listed.

**Comment by poettering** [comment]
Uh, PrivatePID= is not just a security concept (i.e it doesn't just make stuff inaccessible or hide it), it creates an entire new world of things, it renumbers all processes after all. It also changes semantics of the main process quite a bit, since they'll now receive child processes that need to be reparented. Moreover, if the main process of a service dies this will zap all auxiliary processes away entirely, in a very unfriendly way.

Hence, we should probably *not* communicate this as a security option like any other. It's primarily about creating a new world, and that as side-effect might have some security benefits, but it's *not* primarily a security option.

hence, not sure this should be suggested by "systemd-analyze security", because it's not something you just turn on, your process must be ready for it.

**Comment by Winterhuman** [comment]
Hmm, that's a very good point. Perhaps the documentation should call this out explicitly? I can imagine a lot of people seeing `Private...` and assuming it's like all the other similarly named options

**Comment by Winterhuman** [comment]
That still leaves `PrivateTmp=disconnected` though. I guess it's not much "harder" than `PrivateTmp=yes` in function, and can be given the same exposure level?

**Comment by Winterhuman** [comment]
Closing issue since `PrivatePIDs=` is too different from the other options to include in terms of potential issues. I'll open a separate issue for including a notice in the docs mentioning that `PrivatePIDs=` requires special consideration.

(`PrivateTmp=disconnected` is probably fine too given it isn't much different in practice to `PrivateTmp=yes`)
