### ISSUE TITLE
ssh-generator logs to the console

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#35071]
ssh-generator uses log_info(), which for generators running under pid1 effectively means kmsg. This means we generate a log on the tty upon every manager reload:

![Screenshot_fedora-rawhide_2024-11-07_15:20:36](https://github.com/user-attachments/assets/d860fc0d-8e15-41a0-b17c-ce4140d88ec2)

OTOH, it's quite useful to have the address shown. But OTOH, this doesn't look great. I think we need to downgrade the log to debug and figure out a different way to convey this information to users. (`/etc/issue`?)

There's the additional issue that `→` is used without the utf-8 translation layer and it's apparently not rendered correctly.

/cc @poettering

**Comment by poettering** [comment]
yeah, i can see people might be annoyed by this. And yes, this information is interesting, that's why this is logged.

The issue idea is interesting. I guess we could:

1. teach ssh-generator to generate a drop-in for systemd-tmpfiles-setup.service that sets a service credential via SetCredential= with the message to add to issue
2. Add one line to our tmpfiles.d/ snippets somewhere that copy the credential to a file /run/issue.d/ via a `f^` line type, like we already write /etc/issue.d/50-provision.conf

**Comment by keszybz** [comment]
Hmm, so maybe we should allow generators to write to `/run`  and just create `/run/issue.d/something`? 

Oh, this won't work because agetty implements a logic where it won't even look at `/run/issue.d` if `/etc/issue` exists. I expected this to work like systemd dropins, i.e. I create `/run/issue.d/sshd.issue` and put some text there and it is printed after the default text from `/etc/issue`. But this does not happen unless I remove `/etc/issue`. This makes the scheme essentially useless… @karelzak can we change the logic to allow dropins from `/run` to be read even if `/etc/issue` is present?

**Comment by poettering** [comment]
so, that console actually looks like it's in iso8859-1 mode, unless i am mistaken, i.e. the fact the arrow became three high 8bit chars suggests that.

I think this is simply misconfiguration, i.e. the system is run in utf8 mode, but the console is in iso8859-1 mode. 

Now, one could argue that it isn't clear which charset the kernel log buffer should be in, but i think there could be a strong case made that it definitely shouldn't be iso8859-1 but utf8.
