### ISSUE TITLE
logind fails to open seat in nspawn

### ISSUE THREAD

**Issue by fxzxmic** [systemd/systemd#35114]
### systemd version the issue has been seen with

256.7+suse.9.gc7671762b3

### Used distribution

OpenSUSE Slowroll 11.03

### Linux kernel version used

6.11.6-300.fc41.x86_64

### CPU architectures issue was seen on

None

### Component

systemd-logind

### Expected behaviour you didn't see

logind can open seat in nspawn.

### Unexpected behaviour you saw

I want to use hyprland in nspawn, but logind fails to open the seat in nspawn.

### Steps to reproduce the problem

Host: fedora 41
Nspawn: OpenSUSE Slowroll
1. Install hyprland in nspawn, then start hyprland.
2. Startup failed.
3. But if you switch to use seatd, you can start it successfully.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[LOG] [AQ] [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[LOG] [AQ] [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[LOG] [AQ] [libseat] [libseat/libseat.c:76] Backend 'logind' failed to open seat, skipping
[ERR] [AQ] [libseat] [libseat/libseat.c:79] No backend was able to open a seat
[ERR] [AQ] libseat: failed to open a seat
```

**Comment by poettering** [comment]
nspawn does not provide a graphical seat. This is simply not supported. Sorry. It has no graphics device, it just has virtual TTYs and little else.

**Comment by fxzxmic** [comment]
> nspawn does not provide a graphical seat. This is simply not supported. Sorry. It has no graphics device, it just has virtual TTYs and little else.

No, it can have a graphics device as well as a graphical interface. Otherwise, how do you explain that seatd works?

**Comment by fxzxmic** [comment]
Maybe I need to reissue this as a feature request.

**Comment by poettering** [comment]
> No, it can have a graphics device as well as a graphical interface. Otherwise, how do you explain that seatd works?

i have no idea what "seatd" is. 

And I know nspawn quite well, I wrote the largest part of it. And the Linux device model is not virtualized for containers, hence we cannot really support it even if we wanted to.

**Comment by fxzxmic** [comment]
> i have no idea what "seatd" is.

https://github.com/kennylevinsen/seatd

All I know in contrast is that seatd can open the seat in nspawn, while logind cannot.
So you're saying that a non-systemd project knows more about nspawn than systemd itself?

**Comment by poettering** [comment]
I have no idea what "opening a seat" means in "seatd", and what that entails. I doubt it is comparable.

**Comment by fxzxmic** [comment]
I don't know either, as a regular user I don't have the ability to get the full technical details. You can check out the seatd code or talk to its developers. I'm just reporting that there is such a software that does a better job than systemd in one way or another.

**Comment by fxzxmic** [comment]
https://todo.sr.ht/~kennylevinsen/seatd/27

**Comment by kennylevinsen** [comment]
> You can check out the seatd code or talk to its developers. I'm just reporting that there is such a software that does a better job than systemd in one way or another.

"Other stuff works better" isn't an actionable bug report for systemd, and asking devs to just go read foreign codebases is unreasonable.

---

Your bug report lacks detail of what you want to achieve and what you have done so far. Do you want the container to have exclusive control your physical devices, running your main display server from within? Have you already plumbed `/dev/dri` and `/dev/input` through somehow? Those details would be helpful.

If you have plumbed through all your physical devices to the container, and can start  local session with seatd, then I imagine what is lacking is a way to let logind treat the session as graphical. The main difference between seatd and logind is that seatd doesn't do session tracking of any kind: Exclusive seat accesst is first-come, first-serve to users in the right group at any time.

If you don't want control over your physical devices but expected e.g. a VM console-esque window to pop up, then neither seatd nor logind is relevant - what you'd want plumbed through would be the Wayland display socket and render device of the "host", so that a nested display server session can be started.

**Comment by fxzxmic** [comment]
> "Other stuff works better" isn't an actionable bug report for systemd, and asking devs to just go read foreign codebases is unreasonable.

So this might be better suited as a feature request. As for letting him read external code, because that's one of the ways. You can't make me read it either, I don't exactly understand it.

> If you have plumbed through all your physical devices to the container, and can start local session with seatd

Absolutely correct.

> If you don't want control over your physical devices but expected e.g. a VM console-esque window to pop up, then neither seatd nor logind is relevant

Not this, I am using hyprland in nspawn as I had mentioned.

**Comment by fxzxmic** [comment]
As for your comment that I didn't provide the necessary information, I honestly had no idea that opening a seat had anything to do with exposing the device to nspawn until I received a reply from the developer. So naturally, I didn't know it needed to be provided.

As a user, I've only observed that logind and seatd behave differently for the same opening a seat operation. So it's natural to think it's a bug.

**Comment by kennylevinsen** [comment]
So what you need is probably a way to create a user-session tied to seat0 with VT 0, or a session on seat1 with all devices moved to that through an ID_SEAT udev rule.

Not sure what the most user-friendly way to do this would be. If run as a service setting `PAMName=` properly (see various services for running sway and weston as a system service), you might be able to make it work by setting `XDG_SEAT=seat0` and `XDG_VTNR=0` in the service. Otherwise, maybe `pam_env.so` in the PAM stack would work to flip the right flags.

Once things are set right, `loginctl` should show a session that has a seat association.

**Comment by fxzxmic** [comment]
@poettering Now do you have an idea? Do you want me to open another feature request?
