### ISSUE TITLE
Login prompt doesn't get sent to QEMU console on raspi4b / debian bookworm 

### ISSUE THREAD

**Issue by retpolanne** [systemd/systemd#35269]
### systemd version the issue has been seen with

252

### Used distribution

Debian 12 (bookworm)

### Linux kernel version used

6.6.51-v8+

### CPU architectures issue was seen on

aarch64

### Component

systemd-logind

### Expected behaviour you didn't see

Login prompt should show up on QEMUs terminal. 

### Unexpected behaviour you saw

Login prompt show up on tty1 (display) instead.

### Steps to reproduce the problem

1. Clone `git clone https://salsa.debian.org/raspi-team/image-specs.git`
2. `sudo make raspi_4_bookworm.img`
3. `qemu-img resize ./raspi_4_bookworm.img 4G`
4. 
```sh
curl -L https://github.com/raspberrypi/firmware/raw/refs/heads/stable/boot/bcm2711-rpi-4-b.dtb -o bcm2711.dtb
curl -L https://github.com/raspberrypi/firmware/raw/refs/heads/stable/boot/kernel8.img -o kernel8.img
```
5. 
```sh
qemu-system-aarch64 \
    -M raspi4b \
    -m 2G \
    -cpu host,accel=vhf \
    -serial mon:stdio \
    -dtb bcm2711.dtb \
    -kernel kernel8.img \
    -sd raspi_4_bookworm.img \
    -append "earlycon=pl011,mmio32,0xfe201000 root=/dev/mmcblk1p2 rootdelay=1 console=ttyAMA1"
```

If you find a way to log onto the machine (I couldn't), enabling `serial-getty@ttyAMA1` yields a message on the logs – it seems that serial-getty for ttyAMA1 doesn't even gets enabled automatically:

```
Job dev-ttyAMA1.device/start running
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
n/a
```

**Comment by poettering** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.
