### ISSUE TITLE
[systemd-resolve] dnssec: "Data Authenticated: yes" is wrong

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#3561]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 230
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

> Arch Linux

Hello,
I am just wondering about the output of `systemd-resolve`. `Data Authenticated` should show me if the server supports dnssec or not, right?
Why do I get for my server `nullday.de` `yes` as reply?

```
 # systemd-resolve nullday.de                                                                                                       :(
nullday.de: 37.120.168.88

-- Information acquired via protocol DNS in 965us.
-- Data is authenticated: yes
```

I am pretty sure that my server doesn't support DNSSEC.

**Comment by poettering** [comment]
hmm, this is really strange, and for me this actually results in "Data is authenticated: no". Weird....

Or is the local hostname (as reported by /proc/sys/kernel/hostname) of your system "nullday.de"? In that case: resolved will resolve the local hostname to the local IP addresses, and since the hostname configuration is privileged will report that the data is authenticated. It also does this for /etc/hosts entries btw, maybe the entry is listed there?

If that's the case, it might be worth temporarily changing the hostname/changing /etc/fstab, and retest. If neither is the case:

Any chance you turn on debug logging in systemd-resolved, rerun this query and provide the full output this resulted in here?

to enable debug logging either do this:

``` sh
mkdir -p /etc/systemd/system/systemd-resolved.service.d
echo -e "[Service]\nEnvironment=SYSTEMD_LOG_LEVEL=debug" > /etc/systemd/system/systemd-resolved.service.d/log-level.conf
systemctl daemon-reload
systemctl restart systemd-resolved.service
systemd-resolve nullday.de
```

And then use "journalctl -u systemd-resolved" to find the logs this created and attach them here.

**Comment by poettering** [comment]
My educated guess is that the the name appears in /etc/hosts, hence we should better document what "Data Authenticated" actually means. I hence filed PR #3571 to improve the situation.

**Comment by shibumi** [comment]
I can confirm. I had my server in the `/etc/hosts` thats the reason why I got a `yes` there. I've tested it again. With host in the hosts file I get `yes` without I get `no`. So everything looks fine.

```
root@motoko ~ # systemd-resolve nullday
nullday: 37.120.168.88

-- Information acquired via protocol DNS in 537.3ms.
-- Data is authenticated: yes
root@motoko ~ # systemd-resolve nullday.de
nullday.de: 37.120.168.88

-- Information acquired via protocol DNS in 1.4ms.
-- Data is authenticated: no
```

I will close this issue.
