### ISSUE TITLE
Automount is trying to unmount storage when used

### ISSUE THREAD

**Issue by EdiDD** [systemd/systemd#35617]
### systemd version the issue has been seen with

systemd 252 (252.31-1~deb12u1)

### Used distribution

bookworm 

### Linux kernel version used

6.1

### CPU architectures issue was seen on

aarch64

### Component

systemd

### Expected behaviour you didn't see

Try unmounting storage only if no other process is using it.

### Unexpected behaviour you saw

```
[Automount]    
Where=/mnt/disk1
TimeoutIdleSec=10m
```

```
[Mount]
What=/dev/disk/by-uuid/...
Where=/mnt/disk1
```

When stream data are read by some process like watching movie from disk1 errors like below appears in log every 10m:
```
Failed unmounting mnt-disk1.mount
Failed to expire automount, ignoring: No such device
```
Why this is happening? Did i miss something in conf files ?

**Comment by yuwata** [comment]
*[Canned reply follows]*

This is the upstream bug and feature request tracker of systemd. Please use this only for issues in the two most current upstream systemd versions. See this link for the list of current releases.

https://github.com/systemd/systemd/releases

For support for older versions please contact your distribution instead.

In order to keep frustration at a minimum the submission form tried to make this all very clear.

**Comment by yuwata** [comment]
Or, please reproduce the issue with a recent release with systemd.log_level=debug kernel command line option, and provide relevant debugging logs.
