### ISSUE TITLE
Changes in /etc/fstab are ignored

### ISSUE THREAD

**Issue by jkufner** [systemd/systemd#3568]
### Submission type
- Bug report
### systemd version the issue has been seen with

```
$ systemd --version
systemd 230
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```
### Used distribution

Debian
### The Bug

My hard drive failed so i bought a new one and copied data. After the copy was finished, I changed /etc/fstab to mount new hard drive to old mount point, then unmounted old drive, mounted the new one and disconnected the broken hard drive to let it rest for a minute. Then I reconnected the old broken drive. Instantly, systemd unmounted the new drive and mounted the old broken drive, not respecting changes in /etc/fstab. I was lucky noone has been using the server and badblocks has a check to not run on mounted drives, otherwise a lot of bad things would happen.

Before mounting anything, systemd MUST check /etc/fstab for changes. It is not acceptable to cache obsolete data and use the wrong data to do wrong things automatically.

This systemd's behavior may result in significant data loss.

**Comment by evverx** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.generator.html#Examples

> After editing /etc/fstab, the user should invoke systemctl daemon-reload. This will re-run all generators and cause systemd to reload units from disk. To actually mount new directories added to fstab, systemctl start /path/to/mountpoint or systemctl start local-fs.target may be used.

Did you run `systemctl daemon-reload`?

**Comment by jkufner** [comment]
Of course not... Well... I did run that after I realized what happened.

The point is, that systemd must check /etc/fstab for changes before it mounts anything. Otherwise it can lead to dangerous situations and possible data loss.

**Comment by arvidjaar** [comment]
> Did you run systemctl daemon-reload?

And what about all other generators that may be installed on your system by arbitrary other package? Do you imply that administrators today must know this and run daemon-reload when any file used by any of them changed?

**Comment by evverx** [comment]
> Do you imply that administrators today must know this

No, I don't.

> And what about all other generators that may be installed on your system by arbitrary other package?

So, `/etc/fstab`-checking doesn't really make sense. Right?

**Comment by jkufner** [comment]
@evverx No. The opposite. Other generators shoud perform similar checks too.

**Comment by poettering** [comment]
This is by really by design: configuration stays in effect until systemd's configuration is explicitly reloaded, so that incomplete changes are not read at the wrong time. THis is indeed different from classic SysV where changes made to init scripts or /etc/fstab had an immediate effect on subsequent operations on that script or mount point. 

I have documented this on https://www.freedesktop.org/wiki/Software/systemd/Incompatibilities now, given that this indeed might be something to stumble over, but I am very sure systemd's behaviour in this regards is the more correct one.

**Comment by jkufner** [comment]
So after every change in /etc we have to run `systemctl daemon-reload`, because there is no way of knowing whether there is a part of systemd using a changed file. And there are no safety checks to detect changed configuration and inhibit potentially dangerous automatic actions.

@poettering Btw, that Incompatibilities page is completely unreadable and very poorly structured. Some headings would help a lot.

**Comment by arvidjaar** [comment]
> So after every change in /etc we have to run systemctl daemon-reload

after _every_ change (dropping /etc), exactly

> because there is no way of knowing whether there is a part of systemd using a changed file.

**Comment by reusch** [comment]
Nice to know that systemd unmounts your intentionally mounted drives.

And also interesting: Removing logical volumes and creating them in a different volume group, changing the fstab and running mount on this mountpoint leads to the situation that nothing is mounted because systemd unmounts the new one and the old one has gone and cannot bei mounted.

SysV did not read fstab all the time to mount all volumes exactly as defined in fstab. Systemd does this partly and may leave a half-complete system state by doing this (from my perspective).

Sorry for waking up sleeping dogs, though...

**Comment by wdoekes** [comment]
> Nice to know that systemd unmounts your intentionally mounted drives.

It also mounted my intentionally unmounted drive that I was supposed to be doing e2fs stuff on.

**Comment by skupkosk** [comment]
Just experienced the same after migration of LVM backed local FS to NFS share, modification of /etc/fstab and manual remount.
After initialization of logrotate.timer at night the systemd unmounted the used NFS.

From the point of the sysadmin would expect the systemd will reload itself if required.

**Comment by boucman** [comment]
systemd can't guess at what point /etc/fstab is in a consistent stage, only the admin can tell it. 

In classical sysV, you wouldn't call "mount" while another admin is editing /etc/fstab. (usually using the "this will never happen anyway" locking mechanism) If systemd monitors /etc/fstab for changes, it will be warned at the very milisecond you change something, so we can't rely on that

Moreover, it can be made worse by other daemons (and thus their configuration) needing to be consistant. Think of a FUSE type daemon for example

Overall, systemd can't guess at what point it should reload fstab, so it does the only thing that makes sense... it waits for you to tell it when things are ready.

**Comment by reusch** [comment]
It does wait for you to daemon-reload, yes, I can understand that.
It also unmounts volumes you mounted by hand - why?

**Comment by keszybz** [comment]
> It also unmounts volumes you mounted by hand - why?

There were various issues like this in the past, but they should all be fixed now, i.e. systemd should not unmount anything unless asked too. If you can reproduce the issue with recent systemd (242+ at this point in time), please open a new bug.

**Comment by jkufner** [comment]
> In classical sysV, you wouldn't call "mount" while another admin is editing /etc/fstab.

Exactly. And that is the moment when Systemd can (relatively) safely reload fstab. So, when a filesystem is mounted and fstab is modified, then reload fstab.

**Comment by boucman** [comment]
when is that ? when nobody is editing /etc/fstab ?
I'm not sure that can be determined safely, and even if it is, that's not enough on modern systems. There might be other daemons/configurations involved in the mounting that systemd might not be aware of (FUSE daemons, NFS daemons, or simply that the corresponding cryptsetup hasn't been done yet because the admin is doing that next)

No, this is not really safe enough to attempt it. there is a real risk of putting important stuff into failed state.

**Comment by jkufner** [comment]
Well, current behavior also puts important stuff into failed state. Not loading /etc/fstab is as bad as loading it at a wrong moment.

Various tools don't make much difference here. Let's try it this way:

When a file system gets mounted and this particular file system is specified in /etc/fstab file (not the cached version in systemd), then it should be safe to reload /etc/fstab, because the user invoked an action based on the content of /etc/fstab.

**Comment by mbiebl** [comment]
The handling of /etc/fstab is indeed one of the most commonly raised complaints I see.
I wonder if we could make systemd smarter in that regard. E.g. whenever it triggers (auto)mount related actions it could check the timestamp of /etc/fstab and reload if it notices that it has stale data.

**Comment by keszybz** [comment]
Already implemented ;)

```console
$ sudo touch /etc/fstab
$ systemctl status  /boot/efi
Warning: The unit file, source configuration file or drop-ins of boot-efi.mount changed on disk. Run 'systemc>
● boot-efi.mount - /boot/efi
   Loaded: loaded (/etc/fstab; generated)
...
$ sudo systemctl start /boot/efi 
Warning: The unit file, source configuration file or drop-ins of boot-efi.mount changed on disk. Run 'systemctl daemon-reload' to reload units.
```

**Comment by boucman** [comment]
Out of curiosity, this is linked to SourcePath= ?

**Comment by keszybz** [comment]
Yep.

**Comment by boucman** [comment]
Awesome, I didn't know about that, thx

**Comment by jkufner** [comment]
... However, that is only a part of the fix.

**Comment by reusch** [comment]
Maybe we still have the problem because of the older systemd version in SLES at work.

Still one question remains: Why does systemd mount or unmount a filesystem at all? Just reload and do nothing until the next reboot? Just an idea.

In my(!) opinion, systemd should only ensure mounts at boot time, everything else may be only changed by explicit actions. Also, personally I do not use systemd operations to mount or unmount filesystems.

**Comment by keszybz** [comment]
@reusch There is no "during boot" and "after boot" — systemd is an event-driven program, and we have hotplug, and machines can be booted into different systemd targets, etc. It just isn't possible to say, "oh, the boot finished, now we do things differently", because that's an ill-defined concept.

Also, please don't do bug necromancy like this with vague comments. If you find something that violates **expected and documented behaviour** in **recent version**, please open a new bug.
