### ISSUE TITLE
RFE: systemd-run journal identifier

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [systemd/systemd#3693]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

230

currently, `systemd-run` will:
https://www.freedesktop.org/software/systemd/man/systemd-run.html
1) use only stripped executable name for journal identifier
2) not provide any option to control the identifier

suggested correction:
1) use `--unit=` name for journal identifier (not executable), when present
2) support new `--identifier=STRING` option, to override other identifier sources

**Comment by poettering** [comment]
Use "systemd-run -p SyslogIdentifier=foobar".

**Comment by poettering** [comment]
note that if programs log with syslog() it's up to them to pick the identifier. SyslogIdentifier= only has effect on stdout/stderr logging.

**Comment by poettering** [comment]
SyslogIdentifier= defualts to the executable name, and that's documented since a long time in systemd.exec(5), and I am not convinced there's enough reason to change that, as there's no clear rule that service names are a ton more suitable for this than executable names. Moreover syslog() defaults to the executable name too, hence I think we should follow suit here...

**Comment by Andrei-Pozolotin** [comment]
got it, agreed, thank you.
