### ISSUE TITLE
[nspawn] fails with unclear error message if /dev is mounted in the target directory

### ISSUE THREAD

**Issue by safinaskar** [systemd/systemd#3695]
- [x] Bug report
### systemd version the issue has been seen with

> 230
### Used distribution

> Debian sid

Steps to reproduce: create chroot environment (for example, in `/b`), then:

```
mount --bind /dev /b/dev
systemd-nspawn -D /b
```

nspawn will not run chroot environment and will say instead:

```
Spawning conainer b on /b
Press ^] three times within 1s to kill container.
Failed to create directory /b/sys/fs/selinux: Read-only file system
Failed to create directory /b/sys/fs/selinux: Read-only file system
mknod(/b/dev/null) failed: File exists
```

(I already reported that "Read-only file system" here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830693 , this bug report is not about it).
Expected behavior is to run the container.

Okey, why this is so important? Well, I often create some chroot environment, then mount some file systems (/proc, /dev, etc) and enter to them using typical chroot. Sometimes I use systemd-nspawn. Sometimes I mount some file systems, forget about them and then try to use systemd-nspawn. And it fails with very unclear error message (on systemd 215 on debian stable jessie error message is even more weird: just "container failed with code 1"). And this is very difficult to understand why.

So, please, support entering into any systems with some kernel file systems mounted (/proc, /sys, /dev, etc). Or at least print some helpful error message, for example: "/dev is mounted, unmount it and try again"

**Comment by tixxdz** [comment]
@safinaskar @poettering fix for this is here https://github.com/systemd/systemd/pull/4226 however I'm not sure if any third party software may fail due to this change... cc @lucab @alban @jonboulle in any case if a shared mount point is backed by a kernel fs doing userns chown is wrong.

@safinaskar now it will print:
`Failed to mount '/mnt/code/containers/fedora-tree-24/dev' already a mount point.`

Thanks

**Comment by tixxdz** [comment]
Ok updated in the appropriate PR, and for now we just warn the user, if someone wants to support pre-mounted kernel filesystems feel free...

Thanks!

**Comment by safinaskar** [comment]
@tixxdz, so, /dev is required to be empty now? This is very strange. Environments created by debootstrap have non-empty /dev by default

**Comment by tixxdz** [comment]
@safinaskar AFAIK with nspawn this has always been the case "/dev/" was always populated/cleaned by nspawn, the code didn't change due to this PR.

Now quoting your message: 

> So, please, support entering into any systems with some kernel file systems mounted (/proc, /sys, /dev, etc). Or at least print some helpful error message, for example: "/dev is mounted, unmount it and try again"

I was lazy and don't have time right now, so I just did go with the second approach that you proposed for 2 reasons: 1) knowing that to support pre-mounted /proc, /sys, /dev we have to change nspawn to ignore completely user namespaces in that case and test it. 2) We are planning for a v232 release soon and the logic of the code didn't change.

So I took what you proposed ;-) now please open a new PR, feature request or issue to support pre-populated /dev nodes, reference this one, and let others comment on it.

Thank you!

**Comment by safinaskar** [comment]
@tixxdz .

At first I thought new code will print ".../dev/ should be an empty directory" in all cases when /dev is non-empty. And this worried me. Because I know debootstrap creates non-empty static /dev.

But now I performed some tests with fixed version (232) and everything is clear now for me. I see that non-empty /dev (as created by debootstrap) is OK if /dev is static (i. e. not mounted). But if /dev is non-empty AND mounted, then systemd (232) fails with error.

So, all is okey now.

But I think you should fix error message. Non-empty /dev is OK if it is static.
So, change this:

".../dev/ should be an empty directory"

to something like this:

"error: ../dev/ is mounted and it is not empty"
