### ISSUE TITLE
Multi-line EnvironmentFile entries

### ISSUE THREAD

**Issue by mfowlewebs** [systemd/systemd#3729]
We expect some means to pass standard multi-line pem keys into our apps as environmental variables from an EnvironmentFile= file.

Systemd has no means to allow multi-line environment values in EnvironmentFile.

In #systemd irc it was mentioned that we ought pass in these values as files, but that would not be compliant with our 12-factor app design. We rely on being able to run our apps entirely via environmental variables. In particular, we pass a lot of public private keys (in standard PEM format), and there's really no option except new-line delimited environmental variables for these values. We really don't want to mangle our standard PEM files, and bundling secure information inside our containers is a non-starter. Please support passing keys to apps via environmental variables, by allowing some way to create multi-line environmental variables.

I haven't played around with it nearly as much, but this problem seems to affect Environment= as well.
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Ubuntu 16.04

**Comment by mfowlewebs** [comment]
Other users have experienced this limitation as well:  http://stackoverflow.com/questions/35909874/systemd-multiline-variable-in-environmentfile-where-new-line-is-significant

**Comment by arvidjaar** [comment]
Actually this looks like a bug, not RFE. Multiline assignments are correctly parsed, but then rejected in `exec_context_load_environment` because they contain newline. Code that does it is in `env_value_is_valid`:

```
        /* bash allows tabs in environment variables, and so should
         * we */
        if (string_has_cc(e, "\t"))
                return false;
```

But bash also allows newlines so by the same logic we should as well.

**Comment by poettering** [comment]
Humpf. Passing bulk data through env vars appears tobe quite strange to me I must say, smells a bit like a misuse, no?

**Comment by mfowlewebs** [comment]
This practice is set-forth by the Config section of the widely-regarded [fairly-popular](https://www.google.com/trends/explore#q=systemd%2C 12 factor) _12 Factor_ practice of app development. In their words:

> An app’s config is everything that is likely to vary between deploys (staging, production, developer environments, etc).

and,

> The twelve-factor app stores config in environment variables (often shortened to env vars or env). Env vars are easy to change between deploys without changing any code; unlike config files, there is little chance of them being checked into the code repo accidentally; and unlike custom config files, or other config mechanisms such as Java System Properties, they are a language- and OS-agnostic standard.

Coming from a place where we had per-deploy builds, this practice has been a major relief.

These PEMs are by far the bulkiest thing we have to pass in, and yes, I agree it is quite strange. But leaving the 12-factor path for this one multi-line entity, or going in and mangling our PEMs specifically for systemd both seem far more deviant. I feel this RFE/bug/whatever is on solid grounds, although I ack that it also could permit others slope to slip on.

I hacked up a branch on one of our apps to try a workaround, demangling the PEMs as they were read in, but didn't feel comfortable putting that work in a codebase where only some users are systemd based, and so I didn't commit this workaround to our app codebase. Instead I've been writing wrapper scripts, at the price of having to author the script and set SyslogIdentifier= to keep journaling usable, which I hadn't had to do previously. Would love to see multi-line added in, & h/t to @arvidjaar for pointing out that some bash interop was once a design intent: I think a lot more users will be happier having closer bash parity here too, will port those bash usability expectations into their systemd usage.

**Comment by smcv** [comment]
The restrictions that systemd applies to environment variables' values are apparently now a practical problem for gnome-session startup: it can't use the obvious `dbus-update-activation-environment` or `systemctl --user import-environment`, because a single environment variable whose value systemd doesn't like makes the whole batch fail. (See https://bugzilla.gnome.org/show_bug.cgi?id=736660#c74 and subsequent comments)

Environment variables are not really a shell thing anyway: they're lower-level than that, going down to the level of the C library (with some help from the kernel where they pass between processes). Environment variable names can contain anything except `\0` and `=`, and their values can contain anything except `\0`:

```
$ env - $'\x02\x0d\x0a=\x01' env | xxd
00000000: 020d 0a3d 010a                           ...=..
```

In Bourne-style shells, the fact that environment variables are treated as a special case of shell "parameters" means they get restricted to C-style identifiers, but the values are still unrestricted:

```
$ env - bash -c "export foo=\$'\\x02\\x0d\\x0a'; env" | xxd
00000000: 5057 443d 2f0a 666f 6f3d 020d 0a0a 5348  PWD=/.foo=....SH
00000010: 4c56 4c3d 310a 5f3d 2f75 7372 2f62 696e  LVL=1._=/usr/bin
00000020: 2f65 6e76 0a                             /env.
```

The D-Bus API to get environment variables into systemd is further restricted to UTF-8 (because it uses D-Bus strings, not byte-arrays). dbus-daemon's equivalent has the same restriction.

Beyond that, systemd currently restricts environment variable names to C identifiers (like bash) and restricts environment variable values to not contain control characters `\x01`-`\x1f` (other than tab) or `\x7f`.

If systemd is going to continue to apply such restrictions, then I think it should document them; and something needs to be filtering the environment, and ignoring any names or values that don't meet systemd's specification. Otherwise, we have an all-or-nothing situation where a single "bad" environment variable means none of them propagate at all, and that seems counterproductive.

**Comment by davidgubler** [comment]
Please fix this issue. We could not find a way to make systemd create multi-line environment variables. E.g. "\n\\" or similar at end of line doesn't work, hence we can't supply certificates and private keys via environment variables without another layer of encoding. In the web application world it is considered good practice to supply all configuration data via environment variables.

**Comment by jeffbyrnes** [comment]
@davidgubler, have you tried passing them in as single-line strings, enclosed w/ double-quotes so the shell expands them? E.g., `CERT="line1\nline2\nline3\n"`

I’ve not had to do this myself using SystemD, but I have to do something similar for JSON configs used by Chef (e.g., data bag items), which cannot be literally multi-line.

**Comment by hhyyrylainen** [comment]
I tried having `\n` line changes in an environment variable (defined like this: `VAR="My\nstring\ndata"`) but they turned into just the letter `n`, not a line change. So I had to make them be `\\n` and in the script that reads the environment variables replace `\n` in the text with actual line changes.

Like this: `MESSAGE = os.environ['WELCOME_MESSAGE'].replace("\\n", "\n")`

**Comment by davidgubler** [comment]
@jeffbyrnes Yes, we tried several variants of this, but none did what we needed. There's no shell to interpret the `\n`s, the environment is directly used by a Java app. We ended up with an evil workaround very similar to @hhyyrylainen's.

**Comment by mishak87** [comment]
FYI If you are generating EnvironmentFile content you could generate drop-in instead
`/etc/systemd/systemd/myservice.d/env.conf`
```unit
[Service]
Environment="ABC=some
line
content
"
```

**Comment by rarguelloF** [comment]
Does anyone know a workaround for this issue? Having same problem here.

**Comment by e-lisa** [comment]
@rarguelloF / Anyone having issues with this in an EnviromentFile. Lines should end with '\n\' -- as follows:

EXAMPLE='line one\n\
line two\n\
line three'

Hope that helps. This worked using:
$ systemd --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

Hope that helps with any confusion around newlines and env files

**Comment by noctuid** [comment]
Is there some way to tell which environment variable is causing import to fail?
