### ISSUE TITLE
IFNAMSIZ limit is hit for USB based network interfaces when configuring interfaces aliases

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#3756]
Trying to add an interfaces alias for say enx001e06303327, like 
enx001e06303327.20, will hit the IFNAMSIZ limit.

While a newer mechanism via iproute exists, the old/legacy scheme seems is still used [1] as a recent bug report in Debian [2] shows.

[1] https://wiki.debian.org/NetworkConfiguration#Multiple_IP_addresses_on_one_Interface
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824491#5

**Comment by poettering** [comment]
well, and what do you suggest we do about this?

The predictable names feature is a best-effort thing anyway: we do our best, based on your policy choices, but even if you do not use alias interfaces this might alreday hit the IFNAMSIZ limit, in which case we fall back to the next best naming scheme according to the configured policy.

If you then also throw legacy alias interfaces in the mix, and use the traditional naming for them, then yes, you are likely to hit the limit, but there's hardly anything we can do about it. My recommendation: don't use the legacy tools, assign a proper name, use a different naming policy...

I mean, I don't see anything we could reasonably do about it. And even if we could, I am not convinced we somehow could compress the names even further, it sounds strange to me to do this just magically guessing that the use rmight want to attach 3 more characters to the end of the name and hence leave them free...

Or do you have any specific suggestion?

**Comment by mbiebl** [comment]
what are we doing if the name generated based on the topology exceeds IFNAMSIZ. How do we ensure we stay within the limit and are still unique?

**Comment by poettering** [comment]
we don't ensure that. We try to build a unique name, but if it doesn't work, then we don't, and fall back to the next best optoin as defined by the policy. Specifically, if you set "NamePolicy=onboard mac" and the network device doesn't carry onboard information or the resulting name would be longer than IFNAMSIZ, then we use the next config option, which is "mac". And if that doesn't work either, because the device has no valid mac, then we fall back even further, and use the kernel name...

It's pretty simple: we try a couple of different ways to generate a nice name, but if we can't due to missing or unsuitable data, then we got to the next item in the configured list.

**Comment by mbiebl** [comment]
Tbh, I'm not sure what to do about this. Just wanted to make you aware that there is an issue, especially with MAC based names, which take up all of IFNAMSIZ.

Maybe someone else has a clever idea.

**Comment by poettering** [comment]
OK, closing this now, as I don't see anything we could improve here. if you come up with a striking new idea, please reopen, thanks!
