### ISSUE TITLE
coredump: faster compression

### ISSUE THREAD

**Issue by wavexx** [systemd/systemd#3768]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230

I'm on a development machine, and coredump is something I'd like to keep around to debug problems not strictly related to my programs. However with compression turned on, coredump is just too slow. It would be nice to have a low-overhead compression method such as lz4.

**Comment by poettering** [comment]
lz4 is the default compression algorithm already since v229.

**Comment by wavexx** [comment]
On Thu, Jul 21 2016, Lennart Poettering notifications@github.com wrote:

> lz4 is the default compression algorithm already since v229.

When both LZ4 and XZ are available, can I choose to compress the journal
with XZ but still use LZ4 for cores?

**Comment by poettering** [comment]
Runtime configuration of the algorithm used for compressions is not available right now. Sorry.

**Comment by wonderfly** [comment]
@poettering Is this a deliberate decision (to not allow configuration) or it's just not implemented yet?

**Comment by keszybz** [comment]
It's deliberate. It doesn't seem useful to allow XZ compression for small snippets (which are most common in the journal), because it doesn't get that much more compression to matter. And for really large snippets you cannot use it, because it is too slow and introduces unacceptable latency. All in all, it's generally too slow and uses too much memory for journald uses.
