### ISSUE TITLE
we need to document that "systemctl enable" does not work on "systemctl link"-ed unit files, and people should just use "systemctl enable" directly

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#3832]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 230, 229
### Used distribution

> arch linux, centos7
### In case of bug report: Expected behaviour you didn't see

After `systemctl link $unit_file`, `systemctl enable $svc` should enable the linked unit to run at system startup.
### In case of bug report: Unexpected behaviour you saw

```
# sudo systemctl link /root/blah.timer
Created symlink /etc/systemd/system/blah.timer → /root/blah.timer.
# systemctl enable blah.timer
Failed to enable unit: Too many levels of symbolic links
```
### In case of bug report: Steps to reproduce the problem
- Create a `.service` or `.timer` unit file outside of `SYSTEMD_UNIT_PATH`
- Link using `systemctl link $file`
- Try to enable using `systemctl enable $svc`

[My setup](https://gist.github.com/zfjagann/fb935ccedec9fbdc98c8407d270ab214) didn't work for either the timer or the service.

**Comment by leefr** [comment]
I see the similar things from my latest update in Debian Jesse 
(ii  systemd                        215-17+deb8u4               amd64        system and service manager):

```
# systemctl link /opt/addr_info/addr_info.socket
Created symlink from /etc/systemd/system/addr_info.socket to /opt/addr_info/addr_info.socket.
# systemctl enable addr_info.socket
Failed to execute operation: No such file or directory
```

This was working before applying that update.

**Comment by poettering** [comment]
"systemctl link" creates symlinks in /etc for stuff outside of it to make it available in the search path.

"systemctl enable" creates what is denoted in [install], and if the unit is outside of the search path it also links it into it. 

systemctl enable purely uses /etc as a place to create symlinks but not read them there. That's because symlinks in /etc are supposed to be what it manipulates, not what it reads to figure out what to manipulate. This is intended that way really.

Or in other words: just invoke `systemctl enable /some/where/strange.service` right away, without involving `systemctl link` as first step, and all should be good.

Of course, this should be documented explicitly, hence turning this into a documentation bug.

**Comment by keszybz** [comment]
This got changed in f777b4345e8c57e739bda746f78757d0fb136ac7, we now allow systemctl enable on a systemctl-linked file.
