### ISSUE TITLE
logind doesn't support UserTasksMax=infinity

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#3833]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> CentOS 7
### In case of bug report: Expected behaviour you didn't see

> No task max is applied and pids.max is set to "max"
### In case of bug report: Unexpected behaviour you saw

> systemd-logind[1537197]: [/etc/systemd/logind.conf:5] Failed to parse tasks maximum, ignoring: infinity
> 
> $ cat /sys/fs/cgroup/pids/user.slice/user-4967.slice/pids.max 
> 12288
### In case of bug report: Steps to reproduce the problem

> Set UserTasksMax=infinity in /etc/systemd/logind.conf and restart systemd-logind

**Comment by davide125** [comment]
Related, `UserTasksMax=100%` also fails to parse correctly.

**Comment by poettering** [comment]
Fixed by f50582649f8eee73f59aff95fadd9a963ed4ffea. Closing.

**Comment by flound1129** [comment]
Why is systemd managing this parameter at all?  Why are the Linux builtins insufficient for managing the thread cap?  I just spent several days with an unstable system due to this artificial process limit and it took me several hours to even find out that this setting existed.

Why have you removed this parameter from the official documentation at https://www.freedesktop.org/software/systemd/man/logind.conf.html ?
