### ISSUE TITLE
CPUQuota= values > 100% are invalid since v231

### ISSUE THREAD

**Issue by djgera** [systemd/systemd#3851]
### Submission type
- [X ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

v231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Arch Linux (x86_64)
### In case of bug report: Expected behaviour you didn't see

$ sudo systemctl --runtime set-property ghb@:1.service CPUQuota=200%
$
### In case of bug report: Unexpected behaviour you saw

$ sudo systemctl --runtime set-property ghb@:1.service CPUQuota=200%
CPU quota '200%' invalid.
### In case of bug report: Steps to reproduce the problem

$ sudo systemctl --runtime set-property ghb@:1.service CPUQuota=200%

**Comment by philips** [comment]
@vcaputo could you take a look at this? Related to https://github.com/coreos/coreos-overlay/pull/2106

**Comment by ajeddeloh** [comment]
Looks like it was introduced in https://github.com/systemd/systemd/commit/9184ca48ea43e009cd6f379f319926109a30926c since parse_percent checks the value is in the range [0,100]. Looking through the man pages, it appears the CPUQuota is the only place where values >100% are used. Not sure if a "parse_percent_unbounded" should be introduced or just revert the change in that one spot.

**Comment by dm0-** [comment]
I've tested using a `parse_percent_unbounded` function, which seems to work for me.  The PR is #3886.

**Comment by vcaputo** [comment]
Huh, I only get notified on my personal email for this project, didn't see my mention til now.  I believe dm0 is working on this.
