### ISSUE TITLE
RFE: Support for scheduling end of the month days on timers

### ISSUE THREAD

**Issue by harishanand95** [systemd/systemd#3861]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 222

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Fedora 23
### Feature Request

Currently if a user wants to schedule a timer that repeats on the end of every month, it is difficult to achieve that. 
Cases:
1. Setting a monthly timer on 31st will skip months like Feb, Apr, Jun, Sept and Nov. (`OnCalendar=*-*-31 00:00:00` )
2. Setting a monthly timer on 30th will skip months like Jan, Mar, May, Jul, Aug, Oct and Dec. (`OnCalendar=*-*-30 00:00:00`)
3. Setting a monthly timer on 28th/29th will run on all months but still it wont be the end of the month. ( `OnCalendar=*-*-29 00:00:00` ). Now on February, this becomes more complicated.
Having a feature that looks into this case would be great!
#### Discussion about this issue:

https://github.com/cockpit-project/cockpit/pull/4645#issuecomment-236855464

**Comment by poettering** [comment]
Definitely makes sense to add. Question is what a good syntax for this would be. First idea would be to use negative numbers for specifications relative to the end of the month, but that conflicts with the fact that we use "-" already as separator here. Maybe "^" could work, i.e. that `OnCalendar=*-*-^2` means every second to last day of the month or so? Suggestions?

**Comment by miaofengwei** [comment]
Maybe "32" means the end of the month?

**Comment by dmedri** [comment]
A new case for OnCalendar...

OnCalendar=endMonth # last day of current month

**Comment by johannbg** [comment]
These suggestions are far from being userfriendly so how about just calling it StartOfMonth, EndOfMonth and add as well StartOfWeek, EndOfWeek,StartOfDay, EndOfDay which leads to user friendliness of OnCalendar=StartOfMonth etc.

You could then add +/- days/hours/minutes to that because the next thing that will be requested will be I want to run x job on the seventh of every month (  OnCalendar=StartOfMonth +7d 00:00:00 ) or two days from the end of month ( OnCalendar=EndOfMonth -2d 00:00:00 ) etc. and if end users would want to express for example the first at the start of the day of the first sunday of the month they could do...

OnCalendar=StartOfDay StartOfWeek StartOfMonth then could fine tune it with -/+ days hours minute

**Comment by dmedri** [comment]
@johannbg OnCalendar has already many cases for the first day of a period.

**Comment by johannbg** [comment]
@dmedri then this should be implemented in the same fashion for the last day of a period as well as what I suggested above if that's wanted. StartOf<$FOO> EndOf<$FOO> is much more userfriendly than ~ ^ or "32" etc

**Comment by poettering** [comment]
@dmedri I think we should cover cases like "3 days before the end of the month" too. Consider a case where people want to send out paychecks early enough so that they arrive by the end of the month... Hence, "EndOfMonth" is not sufficient...

**Comment by dmedri** [comment]
Apart this issue, a new problem happen with many concurent .timers: "how to schedule".

**Comment by miaofengwei** [comment]
n1 means negative one,the end of the month?

**Comment by johannbg** [comment]
With StartOf<$FOO> EndOf<$FOO> it could also be implemented as an extension to the journal cli syntax as in journalctl --since StarfOfWeek --until EndOfMonth or journalctl --since StarfOfDay --until EndOfWeek or all in lowercase journalctl --since startofday --until endofweek,  journalctl  --since startofweek --until endofmonth etc.

**Comment by miaofengwei** [comment]
"n" represents negative sign, i.e. OnCalendar=*-*-n2

**Comment by poettering** [comment]
So, here's another idea. We currently support "+5days" and "-7h" already as alternative syntax to say "5 days from now" and "7 hours ago". Maybe we should allow mixing this syntax with the calendar based syntax. Examples: 

```
*-*-01       → as before, means first of the month
-1day        → as before, means one day subtracted from the current time
*-*-01 -1day → new: means one day before the first of the month, 
               i.e. the last day of the previous month
```

I think this would ultimately be a much more powerful syntax, as it generically allows combining absolute calendar-based times with relative times. For example you could express "15 days after the each Monday that is a first day of the month" with `Mon *-*-1 +15d` and other rules.

**Comment by dmedri** [comment]
@poettering, I'm not sure about the "3 days before the end of the month" case. If you move billions in paychecks, you can spend 10 minute for a well defined .timer with a date. Or even no scheduled action. We're talking about the "month" case here, but how many other cases will benefit from this syntax?

minutely-1 # 1 second before every minute?
hourly-1 # 1 minute before any hour?
daily+1 # 1 hour after every new day?
monthly-1 # 1 day before the new month?
...and so on with weekly, yearly, quarterly, semiannually.

IMHO the complexity of a general solution is more than benefits.

**Comment by poettering** [comment]
@dmedri what you are suggesting is pretty similar to what I am proposing. After all, `monthly` is just a friendly alias for `*-*-1`, and hence with my proposal above, you could also write `monthly -1day` to indicate the last of the month. And I'd claim that requiring specification of the unit (i.e. `monthly -1day` instead of `month-1`) is certainly helpful for legibility and to make things obvious.

**Comment by johannbg** [comment]
@dmedri the use case Lennart propose is more common than you think. 

The -/+ day,week,month,year idea would probably need to support days,weeks,months,years syntax since users probably would do typos if they write more than one in each cases as in -1day,-2days.

I personally would prefer startofday, endofday, startofweek, endofweek, startofmonth, endofmonth, startofyear, endofyear with -/+ since it would fit nicely with journal but I guess that's nothing that prevents having friendly aliases with that as well.

**Comment by miaofengwei** [comment]
it is ok to use negative numbers for specifications relative to the end of the month, such as `*-*--1`
