### ISSUE TITLE
set LidSwitchIgnoreInhibited to no by default

### ISSUE THREAD

**Issue by wengxt** [systemd/systemd#3897]
`###` Submission type
- [] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

231

Modern DE usually wants to handle the lid close action by themselves and configurable from the desktop. If they don't want to handle it, they don't need to add the inhibition in the first place. There's no point set any *IgnoreInhibited to yes by default in logind.conf .

See https://bugs.kde.org/show_bug.cgi?id=366402 as a reference.

**Comment by grawity** [comment]
Modern DE can use the special `handle-lid-switch` inhibitor, which should not be affected by this setting; I'm pretty sure that's what KDE already does. LidSwitchIgnoreInhibited= should only affect `sleep` inhibitors. 

If `handle-lid-switch` no longer works as intended after 8121f4d209eca85dcb11830800483cdfafbef9b7, then _that_ is a bug.

**Comment by keszybz** [comment]
I think your analysis is correct. For me the problem with inhibitors stems from the insufficient documentation, in the man pages. http://www.freedesktop.org/wiki/Software/systemd/inhibit is much better. "PowerKeyIgnoreInhibited=, SuspendKeyIgnoreInhibited=, HibernateKeyIgnoreInhibited=, LidSwitchIgnoreInhibited= 
      Controls whether actions triggered by the power and sleep keys and the lid switch are subject to inhibitor locks.
"
This man page text matches _current_ behaviour. With your patch (i.e. the _old_ behaviour), we should say "are subject to high-level inhibitor locks ("shutdown", "sleep", "idle"). Low level inhibitor locks ("handle-*-key"), are always honoured, irrespective of this setting."

**Comment by wengxt** [comment]
Personally I think current behavior make sense. If an enable IgnoreInhibited option is ignored, what's the point of having such an option in the first place? If that's the case, *IgnoreInhibited options should be set to no by default. I don't see there is any point that LidSwitch is so special that LidSwitchIgnoreInhibited need to be set to yes by default.

**Comment by grawity** [comment]
Well, that's why there are two levels of inhibitors... ones which inhibit just the action (i.e. going to sleep or shutting down), and ones which inhibit logind's event handling entirely.

The "IgnoreInhibited" option exists to control logind's behavior when it's managing the lid event _itself_ – that is, when there is no DE running, or when the DE decides to let logind set the policy.

The handle-\* inhibitors were added later, to let a DE say "the lid switch is my business now", under the assumption that the DE itself will have similar configuration to logind's. (For example, KDE does that.)

**Comment by arvidjaar** [comment]
@grawity 

> The "IgnoreInhibited" option exists to control logind's behavior when it's managing the lid event itself

But according to KDE bug report mentioned earlier, DE _does_ handle LID event:

> ```
> - qdbus --system --literal org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.ListInhibitors
> Argument: a(ssssuu) {[Argument: (ssssuu) "handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch", "PowerDevil", "KDE handles power events", "block", 1000, 27058], [Argument: (ssssuu) "sleep", "NetworkManager", "NetworkManager needs to turn off networks", "delay", 0, 410], [Argument: (ssssuu) "sleep", "Écran de verrouillage", "S'assure que l'écran est verrouillé avant la mise en veille", "delay", 1000, 24816]}]
> ```

May be KDE bug was closed too eagerly.

**Comment by NicoHood** [comment]
I have no idea about the internal implementation, but I just want to describe what bug I have:
I set the lid close options in the Xfce settings to "turn of screen" but when i close my laptops lid it will go into sleep after a few seconds. I am sure that this bug was not there before. I mentioned this in the archlinux chat and grawity pointed me here. I might be wrong, but this doesnt sound like a KDE bug only then, to me.

**Comment by grawity** [comment]
@arvidjaar: No, it's (probably) not a KDE problem. Read the whole thread – 8121f4d209eca85dcb11830800483cdfafbef9b7 broke the handling of those inhibitors in systemd-logind. (As the very nice people in KDE bugtracker have politely pointed out.)

@NicoHood: It's _probably_ the same as above – check whether Xfce shows up in `systemd-inhibit --mode=block`?

**Comment by NicoHood** [comment]
```
     Who: xfce4-power-manager (UID 1000/arch, PID 911/xfce4-power-man)
    What: handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch
     Why: xfce4-power-manager handles these events
    Mode: block

1 inhibitors listed.
```
