### ISSUE TITLE
sd_bus_default doesn't work without kdbus

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#390]
`sd_bus_default` doesn't seem to work: it's returning ENOENT

``` C
#include <systemd/sd-bus.h>
#include <stdio.h>
#include <string.h>

int main() {
    sd_bus *bus;
    int err = sd_bus_default(&bus);
    if (err < 0) {
        printf("%s\n", strerror(-err));
        return 1;
    }
    return 0;
}
```

```
$ gcc bus_test.c -lsystemd && sudo ./a.out
No such file or directory
```

strace output: http://sprunge.us/IfcS of note is that it fails straight after (and with the same error code as):

```
open("/sys/fs/kdbus/0-user/bus", O_RDWR|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by kaysievers** [comment]
This works just fine without sudo. On non-kdbus systems, as you run sudo, there is no user bus for root. This seems all fine and expected.

**Comment by daurnimator** [comment]
okay; I was expecting it would default to a system bus if it's run as root?
otherwise what's the point over `sd_bus_default_user`

**Comment by kaysievers** [comment]
On my box, sudo starts a user bus for root and this is returned. But I see your point, that this is not really predictable and behaves differently on dbus-1 and kdbus.

**Comment by dvdhrm** [comment]
`sd_bus_default()` returns the user-bus if you run in a cgroup. It returns the system bus, if you don't. Whether root has a user-bus or not does _not_ depend on whether you use kdbus or dbus1. It might be a side-effect, but it's not the root cause.

Now, given that every process should run in a cgroup, except for kernel spawned processes, I cannot see the point of `sd_bus_default()`. To be honest, I'd just drop it entirely. I cannot imagine why someone doesn't know the bus-type to connect to.

Anyhow, leaving this for @poettering to comment on. I don't see any code-issues with the current implementation. It behaves the same on kdbus and dbus1 and follows its description. However, I'd like to hear why we do have it at all.

**Comment by poettering** [comment]
@dvdhrm sd_bus_default() is for things like the bus proxy that run in any context, and don't really care which one it is. It's like the old "starter bus" logic of dbus1 in some ways, but more generic. In fact, it's a strict superset of the starter bus logic, since it checks dbus1' $DBUS_STARTER_BUS_TYPE and $DBUS_STARTER_ADDRESS environment variables when deciding where to connect first.

If neither $DBUS_STARTER_BUS_TYPE not $DBUS_STARTER_ADDRESS then it will check whether it belongs to the user (by checking if it is within a user's slice unit), and if so connect to the user bus, otherwise the system bus.

Note that this doesn't care which UID your process has, it simply checks whether you belong to a user slice or not, regardless if you are suid temporarily or not. There's one weirdness here though: we decide whether to connect to the user or system bus via the user slice, but we then calculate the user kdbus node via getuid(). Maybe we should actually change that, and also use the slice UID for that. Is that what this bug is about?

(Not sure I grok what the real issue is supposed to be now)
