### ISSUE TITLE
Add documentation and warning about PrivateTmp not working for user systemd

### ISSUE THREAD

**Issue by bnil** [systemd/systemd#3944]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229, but same behaviour in newest as I understand

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

>  Ubuntu 16.04
### In case of bug report: Expected behaviour you didn't see

> N/A
### In case of bug report: Unexpected behaviour you saw

> N/A
### In case of bug report: Steps to reproduce the problem

> N(A

PrivateTmp doesn't work when running on user systemd, e.g 
`
systemctl --user start privatetmpdir.service`

creates files in /tmp that are visible to everyone. When running against system systemd, it works as expected.

As I understand it, this is caused by user systemd not having the necessary privileges for setting up a private /tmp.

An error or at least a warning would have been nice when attempting to start a unit on a user systemd when it contains options that can't be used, instead of just ignoring them as it seems to work now.

It would also be nice if the documentation mentioned this, at least for me it wasn't obvious and could had caused me to store sensitive information in global /tmp

[privatetmpdir.service](https://github.com/systemd/systemd/files/413929/privatetmpdir.service)

**Comment by poettering** [comment]
I figure quite a few other settings don't apply to --user either, and we should document that for all.

**Comment by yuvipanda** [comment]
MemoryLimit nor MemoryAccounting seem to work either (as I found out after a lot of digging). Would highly appreciate this being documented :)

**Comment by WhyNotHugo** [comment]
`InaccessiblePaths`, `ReadOnlyPaths`, `ReadWritePaths` also don't work and should be documented (just mentioning this so it's not missed).

**Comment by AlexDaniel** [comment]
Uh, not sure if this can be resolved with just documentation. Why can't it error out when this happens? Or at least a warning would be nice.

**Comment by poettering** [comment]
fix waiting in #11989

**Comment by AlexDaniel** [comment]
Looking at that commit, it wasn't fixed. PrivateTmp and other options are still no-ops and will silently do nothing.

**Comment by johnl** [comment]
I agree with you @AlexDaniel that silently failing here is bad, but the title of this issue is about documentation. I suppose we should open a new ticket about this silently failing.

**Comment by poettering** [comment]
PrivateTmp= is skipped if we can't implement it on purpose. It's documented too:

>            Note that the implementation of this setting might be impossible (for example if mount
>           namespaces are not available), and the unit should be written in a way that does not
 >          solely rely on this setting for security.

And I am very sure we shouldn't start warning about that. it's OK if we run in an environment where namespaces aren't available (regardless if that's because it's disabled in the kernel, we run in a contianer that turned it off, or we run on behalf of a user as --user instance), and we shouldn't warn nor fail in that case.

**Comment by johnl** [comment]
It's worth noting that SELinuxContext= and AppArmorProfile= work a bit like this: if they're not enabled in the kernel, they're ignored.

However, if it is enabled but there is an error applying them, that is reported (and optionally disabled with a - prefix)

Isn't it arguable that PrivateTmp= should work in a similar same way? So ignored if not implemented, but an error or warning if it's for other reasons (such as privileges), unless prefixed with -

**Comment by poettering** [comment]
> Isn't it arguable that PrivateTmp= should work in a similar same way? So ignored if not implemented, but an error or warning if it's for other reasons (such as privileges), unless prefixed with -

I am very strongly of the opinion that we should not warn in this case. We want that people turn on PrivateTmp= in their units, and if this would throw lots of errors in environments (such as containers) where we lack the privs to actually implement it then people might be deterred to turn this on. Hence, we carefully made sure that the security settings that cannot be implemented due to lack of privileges and that are just about access are silently and gracefully skipped. OTOH settings that change the execution environment in more than just access restrictions will result in failure. For example, ReadOnlyPaths= will silently be skipped if we lack the privs, but BindPaths= will not. And this behaviour is documented and has been like this since time began. I am very sure we shouldn't change that.
