### ISSUE TITLE
systemd-user-sessions.service After=network.target causes 90s boot delay

### ISSUE THREAD

**Issue by networkimprov** [systemd/systemd#4010]
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

> 230+
### Used distribution

> Arch Linux
### In case of bug report: Unexpected behaviour you saw

> Startup has 90s delay
### In case of bug report: Steps to reproduce the problem

> https://bbs.archlinux.org/viewtopic.php?pid=1632295#p1632295
> This commit is the cause: https://github.com/systemd/systemd/commit/8c856804780681e135d98ca94d08afe247557770

**Comment by mbiebl** [comment]
I don't think this is a bug in systemd but in your network configuration (tool).
It shouldn't attempt a network connection (and timing out) if not network cable is plugged in.

**Comment by networkimprov** [comment]
It's not attempting a network connection. In my case (which I didn't post on the Arch BBS) it's waiting for the usb0 interface, which only appears if the user starts a usb-gadget for ethernet after boot. Prior to r230 the network configuration became active when/if the interface appeared.

**Comment by poettering** [comment]
your network management solution isn't really using network.target properly. It should not block on such external events. Or if it does then it should order itself before network-online.target, not network.target.

See https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget for more information about this.

Closing.

**Comment by networkimprov** [comment]
netctl@.service has been working for a long time:

```
[Unit]
Description=Networking for netctl profile %I
Documentation=man:netctl.profile(5)
After=network-pre.target
Before=network.target netctl.service
Wants=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/lib/network/network start %I
ExecStop=/usr/lib/network/network stop %I
```

**Comment by joukewitteveen** [comment]
I cannot really see the proper way for `netctl` to order itself. The current status of ordering before `network.target` is the result of much testing and investigation, including the page linked by @poettering.
As a network manager, `netctl` has to place itself before `network.target` in order to make sure it will not bring down the network too early on shut down.

For the usb gadget, I fail to see why you would want to enable a profile when the presence of the device is not certain at boot time. Maybe you are better off with a udev rule that runs `netctl start <profile>` whenever the device is plugged in.

**Comment by networkimprov** [comment]
@joukewitteveen, you may need to open a new issue to have your perspective considered. I can't re-open this one.
