### ISSUE TITLE
systemd-networkd: ifname_valid too strict (at least for use in config_parse_label)

### ISSUE THREAD

**Issue by dardok** [systemd/systemd#4057]
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> > = 230

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Gentoo
### In case of bug report: Expected behaviour you didn't see

> Address labels are useful to allow explicit association of names with additional IP addresses on a network device.  A name such as "eth0:alias" (i.e. a colon separator with the actual device name first and the alias after) is _required_ in order to allow tools like ifconfig (or, specifically for us, Lustre's lnet_ipaddr_enumerate()) to identify these as valid, distinct devices.  config_parse_label should not be rejecting names with a colon, I believe.  Perhaps ifname_valid can be stricter in other cases, but not for address labels (kernel's dev_valid_name does reject the colon, so must not be in the path for alias assignment). 
### In case of bug report: Unexpected behaviour you saw

> A systemd.network [ADDRESS] section should allow a "Label=" entry to contain colons.
### In case of bug report: Steps to reproduce the problem

> Assign a name with a colon to a network interface via systemd.network specification.  Start systemd-networkd and observe the error message, e.g.: "Interface label is not valid or too long, ignoring assignment: ethX:label".  Alternatively, assign a label without a colon (i.e. something that would pass ifname_valid), and try enumerating interfaces with ifconfig.  The expected additional "alias" device will not correctly display, instead erroring with "error fetching interface information: Device not found" (at least with net-tools 1.60)

**Comment by peoro** [comment]
Any progress on this bug? I need to use alias interfaces, with a colon in their name, and would like to do it with systemd-network.

According to the sources of net-tools it looks like `ifconfig` accepts as alias anything that has one (or more) `:` in the interface name, (see [ifconfig.c:151](https://github.com/giftnuss/net-tools/blob/4e848d6/ifconfig.c#L151)), so changing [src/basic/socket-util.c:890](https://github.com/systemd/systemd/blob/84e6712f/src/basic/socket-util.c#L890) should be enough.

I'm not sure why systemd is currently forbiding `:`. The check is there since the very first version of `ifname_valid` (https://github.com/systemd/systemd/commit/ef76dff225a00008fe0edd1f528c9096f1a91179) and a test explicitly makes sure that `x:y` is invalid. `ifconfig` lets me create an interface with a similar name though (as long as an interface named `x` is present).

I can provide a pull request to change this behavior and update the tests. I can't see any reason why this change could break existing systems (although it couldn't introduce new bugs, I guess - I'm not an expert on this topic).

**Comment by keszybz** [comment]
Fixed by https://github.com/systemd/systemd/commit/a341dfe563bf3be791107a0c98d47f74366c637d.
