### ISSUE TITLE
small BUS_WQUEUE_MAX

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#4068]
We have a user with more than 30 000 device units (really big storage setup). If you try to run systemctl daemon-reload on that machine, you will get "Failed to execute operation: No buffer space available"

It is easily reproducible on regular machines, you can create a lot of dummy network devices and you will get to the same situation.

```
# modprobe dummy
# for i in $(seq 1 1 30000); do (ip li add dummy$i type dummy &); echo $i; done
```

Just for curiosity, I have removed that check and on my machine bus->wqueue_size got to ~66000

**Comment by lnykryn** [comment]
related: https://github.com/systemd/systemd/commit/7a4a2105

**Comment by poettering** [comment]
I figure we can bump the limit again... maybe to 128K or so

**Comment by poettering** [comment]
Fix waiting in #4071.

**Comment by lnykryn** [comment]
To be honest I don't like this approach much. It won't take much time until someone comes with a bigger setup. On the other hand, it is super easy to backport to our version of systemd :-) Thanks.

**Comment by gleventhal** [comment]
@poettering We see this issue play out with autofs/NFS which is even more troublesome, because it's very easy to have an arbitrary number of logical devices which quickly can fill the bus when someone simply runs a find command that descends into the NFS tree.

Any suggests for how to deal with this?
