### ISSUE TITLE
Mentioning the default pager in the manpage

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4143]
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

On making a look at the manpage it seems not to be mentioned what the default pager is. I see just the option --no-pager to disable passing the output to a pager and $SYSTEMD_PAGER which says that no pager is used too in case the variable is empty or set to "cat".

But it seems not to be mentioned which pager is used if the variable is not set just that $SYSTEMD_PAGER overrides $PAGER. Is the default pager maybe "less" or the mysterious variable $PAGER? Maybe this part can be enhanced a bit.

**Comment by lucaswerkmeister** [comment]
I agree, it would probably be better to document this like `$SYSTEMD_EDITOR` in `systemctl(1)`, since there’s a similar fallback chain: `$SYSTEMD_PAGER`, `$PAGER`, `pager`, `less`, `more`, and finally an internal fallback that just copies stdin to stdout.

(Looking at `src/shared/pager.c`, I also noticed that systemd respects a `SYSTEMD_LESSCHARSET` variable that isn’t documented anywhere…)

**Comment by poettering** [comment]
fix waiting in #4348
