### ISSUE TITLE
Adding inotify listeners for systemd.unit

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4159]
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

systemd.unit provides several methods of conditional file checking like ConditionPathExists and the same again to trigger a failure like AssertPathExists instead of skipping. Experimenting now for several days with systemd I think it is useful to have the same again just as an inotify-listener like WaitPathExists. Instead of skipping/failing it is waited until the condition is true similar to the blocking behavior of RequiresMountsFor if a mountpoint is being registered but does not exist yet.

**Comment by abdulkareemnalband** [comment]
@Sworddragon 
You are requesting for path activation which is already supported by path units
https://www.freedesktop.org/software/systemd/man/systemd.path.html

**Comment by Sworddragon** [comment]
Thanks for the information. On making a look at it and experimenting a bit I'm noticing some things:
- If a .service depends on a .path which checks for file existence and the file does not exist at the time the service gets started its ExecStart gets executed immediately (maybe a bug?) and then every time the file gets created.
- The path is still being watched after the inotify event fires. Maybe Type=oneshot support in [Path] would be useful.
- Since .path needs an unit file to be activated it could make sense to allow direct use of [Path] in such unit files.
- The conditional file checking in systemd.unit has better support than [Path]. Maybe anything there that would be possible in [Path] should be made available there too (like checking if the file type is a symlink).

**Comment by gdamjan** [comment]
> The path is still being watched after the inotify event fires. Maybe Type=oneshot support in [Path] would be useful.

`Type=oneshot` and `RemainAfterExit=yes` in the .service would be enough

**Comment by poettering** [comment]
I don't think duplicating inotify support in .service units would be a good idea. Please just use .path for this kind of activation, it should work. I mean, I can undestand that you want something simpler that you can directly configure in your service file, but I am not convinced the usecase is strong enough for this (as this has never come up before so far).

An alternative way to implement this is by having some script that watches your file in ExecStartPre= that delays start-up of the service as necessary.

> If a .service depends on a .path which checks for file existence and the file does not exist at the time the service gets started its ExecStart gets executed immediately (maybe a bug?) and then every time the file gets created.

Well, a ".path" unit is a triggering unit. All it does is activating some other unit when the path it is supposed to watch enters the state it shall trigger on. That's really all it does. Using such an activator doesn't imply that it is the _only_ way to activate the unit it is supposed to activate. Or in other words: if you invoke your service of choice directly (instead of the path unit), then yes, then that's what is going to happen.

I am not convinced that adding the requested concept directly to service files has a sufficiently convincing case, and we already support an option to make what is needed work, hence I think I will close the bug. I hope this makes sense.

**Comment by Sworddragon** [comment]
What about:

> The conditional file checking in systemd.unit has better support than [Path]. Maybe anything there that would be possible in [Path] should be made available there too (like checking if the file type is a symlink).

Is this useful to implement? Should I create a new ticket for it?
