### ISSUE TITLE
"systemctl --all --state=failed" does not list all failed jobs

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4198]
### Submission type
- [ x ] Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev
### In case of bug report: Steps to reproduce the problem

> Execute "systemctl mask systemd-journald.service systemd-journald.socket", reboot the system and execute "systemctl --all --state=failed".
### In case of bug report: Unexpected behaviour you saw

> Jobs with "[ FAIL ]" appear on booting but "systemctl --all --state=failed" does not list them.
### In case of bug report: Expected behaviour you didn't see

> "systemctl --all --state=failed" should list all failed jobs that appeared on booting.

**Comment by davidstrauss** [comment]
What do they show up as in the full unit listing? It's possible that it's recovered since bootup. `--state=failed` only filters for currently failed, not failed since the start of bootup.

**Comment by Sworddragon** [comment]
The problem is that the booting process is too fast to see which units failed (I'm noticing them just because of the red FAIL).

**Comment by poettering** [comment]
uh, oh, this is more complicated. "systemctl list-units" actually shows you info about _units_, not of _jobs_. Units are a concept that encapsulates the objects systemd manages, and units can be active or inactive, or "failed". Jobs OTOH are operations enqueued for specific units, and they also can fail, but they are not the same concept. For example if you enqueue a "start" job for a unit that pulls in something else and requires it, and that other unit then for some reason cannot be started (for example, because it does not exist in the first place), then the "start" job for the unit you tried to start will fail and this is reported to you, but the unit you tried to start won't change state, because systemd never got that far: that unit was never attempted to be changed, because some of its pre-requisites already couldn#t be met.

Yes, this is a bit non-obvious. The short answer is: if you want to see information about jobs (i.e. requested operations on units) then look into "journalctl -b" or so after boot, that's where that's stored. If you are looking for the state of units (i.e. the state of the units themselves), then use "systemctl list-units" or even "systemctl status".

Jobs are generally short-living, and go away quickly when they did their deed. OTOH units are much more "sticky". Most of them stay around during the entire runtime of the system. That's why the result data for "jobs" are found in the journal, while runtime state info for units is exposed with runtime tools such as "systemctl status" in addition to the journal.

I hope this makes sense.

Closing because I don't think there's anything to fix here, "journalctl -b" is really the best way to see what operations precisely failed during boot.

**Comment by Sworddragon** [comment]
> Closing because I don't think there's anything to fix here, "journalctl -b" is really the best way to see what operations precisely failed during boot.

Tricky if systemd-journald is not running. But maybe #4309 can solve this issue.
