### ISSUE TITLE
systemctl isolate shell auto-completion should only show actually isolatable units

### ISSUE THREAD

**Issue by ht990332** [systemd/systemd#4222]
systemctl isolate m....(autocomplete) looks for nonexistent units.
locate plymouth returns nothing. locate auditd returns nothing.
To work around it, I masked the non existent units.
/etc/systemd/system/auditd.service  /etc/systemd/system/plymouth-quit.service /etc/systemd  system/plymouth-quit-wait.service /etc/systemd/system/plymouth-start.service /etc/systemd system/rc-local.service /etc/systemd/system/syslog.service point to /dev/null

This started in 231 and is still an issue in git master.

**Comment by poettering** [comment]
all untis referenced on the system are shown in this list. Most likely some other unit references audit or plymouth (because it wants to be ordered against them in case they are installed), and that's enough to make the unit name being known by systemd, and that's good that way.

Given that many unit operations do make sense on units that have no unit file at the moment, I think the current behaviour is actually OK.

That said, we could probably improve the shell completion for "systemctl isolate" to only show units that are actually isolatable, which are only very few, and units without unit file are not among them. Will convert this into an RFE for that.

**Comment by mrc0mmand** [comment]
This should be fixed by f28255e2d5695b0d060558ff8cbb2b526fc94cc0 and #12403.
