### ISSUE TITLE
Automatic storage does not log into /var/log/journal

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4277]
### Submission type
- [ x ] Bug report
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev
### In case of bug report: Steps to reproduce the problem

> From the configuration files only /etc/systemd/journald.conf exists with the only non-empty and uncommented line "[Journal]" and /var/log/journal exists as a directory.
### In case of bug report: Unexpected behaviour you saw

> On booting/rebooting the system /var/log/journal is still empty.
### In case of bug report: Expected behaviour you didn't see

> /var/log/journal should contain the logs.

**Comment by Sworddragon** [comment]
I have now added the line "Storage=persistent" to /etc/systemd/journald.conf in the "[Journal]" section but after a reboot /var/log/journal is still empty so the problem seems to be that nothing gets logged at all.

**Comment by poettering** [comment]
do you see journal files in /run/log/journal?

Not that the journal will write to /var/log/journal only after being told so via SIGUSR1 that it is writable. This may be triggered via "journalctl --flush". During normal boots that's what "systemd-journal-flush.service" is responsible for doing, after /var becomes available for writing. Is that service properly called on your system?

**Comment by Sworddragon** [comment]
On testing this and setting the storage to persistent again I noticed that the journal did successfully got written into /var/log/journal. Switching back to auto resulted in a success too but on experimenting with both variants I noticed that sometimes a boot still doesn't got logged. In such a case /run/log/journal was not empty and on checking systemd-journal-flush.service I saw that it was masked. Unmasking it and making a reboot did not cause "systemctl --list-boots" to list an additional entry but the next 5 reboots got successfully logged. I'm not sure if this is a race condition or if the masked systemd-journal-flush.service was the fault. On the latter I'm wondering why the journal got sometimes written into /var/log/journal and sometimes not while systemd-journal-flush.service seems to have been always masked during that time.

**Comment by poettering** [comment]
"auto" means use /var/log/journal if it is accessible and writable, and /run/log/journal otherwise. This exposes a race: if remounting /var read-writable is quicker than journald wanting to write stuff then /var will be writable, and data goes to /var/log/journal. However, if journald is quicker, then data will go to /run instead, because journald can't write to /var/log. Normally, this race doesn't matter, as later on systemd-journal-flush will correct this and flush anything written to /run to /var. However, in your case you masked that service hence you got exposed to this race.

We removed "auto" from very recent systemd versions btw, because this race is not only hard to grok, but triggers problems in other contexts as well.

If logs are stored in /run they are lost on reboot (as /run is a tmpfs). 

Hence: since you masked that service you got the behaviour you described. Don't mask that service.
