### ISSUE TITLE
Drop fedora-specific PAM config, document instead what PAM modules systemd --user requires

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#4284]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231
### Used distribution

> Debian
### In case of bug report: Expected behaviour you didn't see

Upstream ships generic configuration, and where it can't, it documents the things it needs/wants
### In case of bug report: Unexpected behaviour you saw

The upstream provided pam config uses fedora-specific files.

Debian patched the config file to be useful on debian, but really this should just be documented and downstream distros should provide the relevant configuration/scripts.

**Comment by fsateler** [comment]
`xorg/50-systemd-user.sh` seems to also be Fedora-specific, so it should be dropped as well. In debian an equivalent is shipped by the dbus package.

**Comment by poettering** [comment]
Hmm, well, any chance we can come up with a basic PAM file that works on both distros? (i.e. something that is good enough to boot on both systems, but that the downstream distros might still have to patch)?

Debian has a similar directory as the Fedora one we place 50-systemd-user.sh in, no? I am pretty sure this code should be unified between the two distros, and doesn't belong in the dbus package really...

I'd rather ship a file here that is "good enough" for both distros, but that enables people who build independent distros to have a good starting point, rather than leave things out completely.

**Comment by mbiebl** [comment]
@poettering I guess it will be hard to unify the pam configs. For that distros are just too different in that regard from my experience.

As for 50-systemd-user.sh: it's installed in /etc/X11/xinit/xinitrc.d/. This directory seems to be Fedora/Redhat specific. Under Debian/Ubuntu and derivates, there is no such directory.
We have /etc/X11/Xsession.d/, which serves a similar function as /etc/X11/xinit/xinitrc.d/ but is used a bit differently.

**Comment by poettering** [comment]
@mbiebl well, I am pretty sure that the set of PAM modules called is not totally different, and that the major difference is maybe in the scope and the use of include files, no?

use the script a bit differently? in which way?

If they are similar enough, we should really add --with-x11-session-dir= or so for "configure", so that distros can choose what they need.

**Comment by mbiebl** [comment]
@poettering 
The scripts in /etc/X11/xinit/xinitrc.d/ seem to be stand alone scripts which I suspect are executed one after the other.
The scripts in /etc/X11/Xsession.d/ are sourced and not executed.

**Comment by martinpitt** [comment]
We could ship a PAM config without any includes, i. e. expand out Debian's `common-account` and `common-session-noninteractive`, and Fedora's `{account,session} include system-auth`:

```
# common account modules
account [success=1 new_authtok_reqd=done default=ignore] pam_unix.so
account requisite pam_deny.so
account required pam_permit.so

session required pam_selinux.so close
session required pam_selinux.so nottys open
session required pam_loginuid.so

# common session modules
session optional pam_keyinit.so revoke
session required pam_limits.so
session [default=1] pam_permit.so
session requisite pam_deny.so
session required pam_permit.so
session [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid

session optional pam_umask.so
session required pam_unix.so
-session optional pam_systemd.so
```

(Haven't actually tested this)

However, this would then be ugly/too static everywhere, as both Debian's common-session and Fedora's system-auth are autogenerated by `pam-auth-update`/`authconfig` and need to be adjusted to packages that you install/remove (e. g. `pam_ecryptfs`). So maybe the common account and session modules could be specified as `./configure` arguments to avoid expanding them in the source.

**Comment by poettering** [comment]
> The scripts in /etc/X11/xinit/xinitrc.d/ seem to be stand alone scripts which I suspect are executed one after the other.

Nope, on Fedora they are sourced by /etc/X11/xinit/xinitrc-common. The concepts are really pretty much the same. The distros just deviate on the paths...

**Comment by poettering** [comment]
@martinpitt well, i want to ship a basic PAm config at least that is sufficient to make things work if you build your own distro from scratch. Ideally this should be a config that works well enough on both of Debian and Fedora-derived distros. But that doesn't mean that distros packaging systemd would leave it as is.

So, I see two possibilities here:

a) Ship a generic version with "expanded" includes, that does the same thing on Fedora/Debian and everything else, and that downstreams then minimally modify kicking out the lines they have in their includes, and adding an include stanza instead.

b) Maybe it is sufficient to just make the name of the include file configurable during build time, via a new configure option. If so, we'd use some generic name, and downstreams would just specify what they need there, but the default would work everywhere...

(Not sure if b) is possible, but if it isn't a) is an OK choice in my eyes, too). 

Does that make sense?

**Comment by mbiebl** [comment]
I'm including here the pam configs from Debian

```
@include common-account

session  required pam_selinux.so close
session  required pam_selinux.so nottys open
session  required pam_loginuid.so
session  required pam_limits.so
@include common-session-noninteractive
session optional pam_systemd.so
```

and Fedora

```
account  include system-auth

session  required pam_selinux.so close
session  required pam_selinux.so nottys open
session  required pam_loginuid.so
session  include system-auth
```

We explicitly had to include the pam_limits.so module here, because that is not included in common-session-noninteractive in Debian. See the related Debian bug report [1] which actually was the reason why Felipe filed this upstream bug report in the first place. Even if we make the includes configurable, we don't know if the included snippets actually provide everything needed. So a generic, expanded pam config seems like the more useful approach to me.
That the include mechanism is used differently between distros doesn't really help either.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838191

**Comment by johannbg** [comment]
Is there any hard dependency between pam and systemd? I

if not it makes no sense for shipping files associated with pam and that the integration of that entirely left to those downstream that use it. 

I would not be surprise if there existed Debian based variants that do not ship pam and are or would like to ship systemd so they end up having to patch those generics out anyway so you can just as well drop it unless there is hard requirement on it. 

+It's much more likely that an mutual  agreeable result for good generic upstream defaults can be achieved and used by downstream if and then when pam2 or the pam replacement emerges.

**Comment by poettering** [comment]
> Is there any hard dependency between pam and systemd? I

Well, semi-hard. PAMName= requires PAM, and user@.service makes use of it.

I am pretty sure that if a compile-time option is enabled we should install everything needed to make the thing work, without requiring distros to add more stuff in.

**Comment by poettering** [comment]
So my suggestin would be to include a PAM snippet like this in systemd:

```
session required pam_selinux.so close
session required pam_selinux.so nottys open
session required pam_loginuid.so
session optional pam_systemd.so
```

This appears to be the common core both distros use, and actually encodes valuable information (as the audit creds pam_loginuid sets up are actually used by pam_systemd, and hence needs to be ordered as above). 

The downstream distros would then just add in their specific include lines. (or, if they want to replace it entirely, that's OK too, but at least this way they can use this as an example to start from).

Does this make sense?

**Comment by martinpitt** [comment]
We can ship a minimal one as well of course; however, the main effect will just be that every package has to patch it differently. We certainly don't need things like `ecryptfs` or `keyinit` in there, but I'm fairly sure that we should at least add `limits` and `umask`. The one I put into https://github.com/systemd/systemd/issues/4284#issuecomment-251587434 is a merge of Debian's and Fedora's expanded file which in pretty much all cases will do too much. Question is if it's better to do too little.

FWIW, I consider the PAM part an issue which can be bikeshedded about for hours and which probably will never have a perfect upstream solution anyway, so TBH I wouldn't waste too much effort on it.

**Comment by poettering** [comment]
yeah, it's a bikeshedding topic... The snippet I posted tries to be more minimal, and is limited to the modules we actually care about (or actually: their order). Maybe adding pam_unix into this would be an option, but given that pam_limits and pam_umask are nothing we should really care about I'd probably leave it out, after all not using them breaks nothing, AFAICS...

What about this: we ship a minimal version, but add some comments in there, that tells downstreams about the missing bits, and where they should place their include invocations.

**Comment by johannbg** [comment]
That approach sounds like the most logical one as in ship only the one that is required to make systemd work out of the box since user@.service makes use of it and document/leave the rest to downstream distributions and apply the same logic to everything else as well to keep the per distribution/deviation/inclusion at absolute minimum.

**Comment by martinpitt** [comment]
> we ship a minimal version, but add some comments in there

Sounds good to me!

**Comment by fsateler** [comment]
> pam_limits and pam_umask are nothing we should really care about I'd probably leave it out, after all not using them breaks nothing, AFAICS...

pam_limits is required if you want to raise or restrict `Limit*` for the user units.

**Comment by poettering** [comment]
> pam_limits is required if you want to raise or restrict Limit\* for the user units.

Can you elaborate, what precisely do mean by this?

**Comment by poettering** [comment]
> we ship a minimal version, but add some comments in there
> 
> Sounds good to me!

Very good! Happy to accept a patch! ;-)

**Comment by johannbg** [comment]
He's probably referring to Limit\* entries in type units 
( which afaik has nothing to do with pam_limits and btw does not work in practice as it has been implemented for type user units sessions and friends )

**Comment by fsateler** [comment]
> > pam_limits is required if you want to raise or restrict Limit\* for the user units.
> 
> Can you elaborate, what precisely do mean by this?

`LimitMEMLOCK`, `LimitRTPRIO`, etc, cannot be raised by `systemd --user` (as that is a privileged operation).  Therefore, these settings only allow to lower each setting. If the admin allows a user a higher setting via `/etc/security/limits.conf`, this setting is not applied to `systemd --user`, and thus to any user services.

**Comment by poettering** [comment]
@fsateler sure, but why would there be the need to raise the limits here? I mean, if you build a complete OS, yes, the limits should probably be raised from the defaults. But to get your self-built distro off the ground it shouldn't really matter if you use systemd's system-wide default limits (which are mostly identical to the kernel's limits) or the default limits configured in /etc/security/limits.conf...

**Comment by fsateler** [comment]
@poettering I'm not sure I grok your objection. What I mean is that a reasonable admin would expect the limits set in limits.conf to apply to the systemd user services as well to the user shell. So that if an admin lowers any setting, the restriction cannot be trivially bypassed via `systemd-run --user $HOME/my-command`, or conversely systemd user units cannot be used to execute commands with the higher limits set.

I note that fedora includes pam_limits in system-auth currently.

**Comment by johannbg** [comment]
@poettering  For the first this does not change the hard limits, secondly users run immediately into issue with limits that affect desktop environment terminals in which they run applications like jack audio and the likes etc. and at that point as to how this has been implemented they immediately run into administrative hell trying to figure out where to raise the limits. Is it limits on the user is it the limits on the session manager, is it the limits on login manager, is the defaults in systemd ( system or user ) or is it /etc/security/limits.conf. 

In practice this is an utter and total mess how this has been implemented and either it needs to be rethought or an tool written that assist users trying to figure out where to raise the limits.

**Comment by poettering** [comment]
all i am saying is that limits are really just limits, and user@.service doesn't require any particular limits to be set, it should just work with pretty much any reasonable default set of limits. Yes, it probably makes sense to use pam_limits in most setups, but from the systemd perspective we really don't need that. It's one of the things the downstream distros should add in (and I'd guess pretty much all of them will).

**Comment by fsateler** [comment]
ack. I figure a comment is sufficient.

**Comment by poettering** [comment]
I figure we settled on an approach here then, anyone cares to prep a patch? ;-)

**Comment by johannbg** [comment]
@poettering  I'm not so sure it actually makes sense to use pam_limits in most setups and despite what you think that user@.service will not need particular limits to be set it will need tweaking by administrators or end users ( in some cases I) in which they will then raise it for all users via user@.service or particular users via user@<uid>.service.d snippet or ~/.config/systemd/user depending on where the administrators intends to raising of the limits or end up having a frustrating experience chasing it downs where they actually need to tweak these settings.

At least distribution should take into consideration that by mixing these things together they could arguably be complicating things since doing so takes away that one clear disquisitions point administrator and end users have in distinguishing between the "traditional" /etc/security/limits.conf and the limit handling in systemd in which they could be asking themselves. Is what I'm using,using systemd ( In which they would know they should raise those limits somewhere in systemd ) or is it not ( and then they know they should configure this in the "traditional" /etc/security/limits.conf file )

It turned out to be quite the surprise for Gnome users that are used to tweak these settings when the workstation group in F24 failed to mentioned they had switched to take advantage of the systemd implementation and users where no longer capable of raising the limits via the traditional means of using etc/security/limits.conf for the desktop environment ( or more accurately they partially have to raise it the as in the hard limit still needs to be done there  ) so this is one of those issues that are ticking time bomb for downstream if implemented incorrectly and or under documented or not properly announced by the distribution and or those components that have made the switch.  
And as usual systemd will get blamed for the pigs mess that will result from that.
