### ISSUE TITLE
/run/systemd/private does not appear to be accepting notifications

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#4289]
### Submission type
- [ X ] Bug report
### systemd version the issue has been seen with

Ubuntu 231-9git1

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Ubuntu 16.10 (development)
### In case of bug report: Expected behaviour you didn't see

system boots
### In case of bug report: Unexpected behaviour you saw

systemd-modules-load.service exit notification is missed with

Sep 22 13:15:45 s2lp4 systemd[1]: systemd-modules-load.service: Failed to send unit change signal for systemd-modules-load.service: Transport endpoint is not connected
### In case of bug report: Steps to reproduce the problem

automated QA, triggers reboots on s390x LPAR generating this behaviour every few reboots
### More details

Original bug report is at https://bugs.launchpad.net/ubuntu/+source/udev/+bug/1623383 and is a bit long winded. However the gist of the problem is that systemd-modules-load.service causes system to fail to boot to a usable state (e.g. multi-user.target).

The events tracked so far are as follows:
- system starts up
- systemd-modules-load.service is activated
- systemd-modules-load runs and the process exits
- upon exit unit change signal is attempted to be send to the /run/systemd/private
- that attempt returns -ENOTCONN
- message is not send
- systemd-modules-load unit does not transition to activate state, blocking the rest of the boot from happening

To me it is very peculiar how sending messages to /run/systemd/private that early in the boot (when systemd-modules-load exits), and how that can prevent the system from booting further. Even after the timeout is reached. The unit in question is DefaultDependencies=no, Before=sysinit.target, Type=oneshot, RemainAfterExit=yes, TimeoutSec=90s.

This is mostly a placeholder bug report so far. I hope to add more debug statements next, to track the bus status of /run/systemd/private to figure out why it's not ready yet when systemd-modules-load is already exiting.

**Comment by poettering** [comment]
This doesn't look right.

This message doesn't mean much actually. it happens if we got a connection via the private bus socket, and the client quickly disconnects. The connection is still in our list then, and we'd like to notify the client about state changes but we can't since the client is already gone. This is completely clean, and nothing to worry about.

You should normally see this only if you turn on debug logging however. Did you do that?

Failures to send out notification bus messages generally are ignored by PID 1 actually, beyond the log message you saw. One misbehaving client not accepting bus messages should never have an effect on any unit's state.

Can you provide the "systemctl status" output of the unit in question at the moment the unit hangs like this?

**Comment by xnox** [comment]
Thank you for hints. The message implies that pid1 fails to change unit state.

At that point it's not yet possible to login into the system. I guess I should be able to add a timer unit that will do systemctl status every minute.

**Comment by xnox** [comment]
[zvmguest-failedboot-journal.txt](https://github.com/systemd/systemd/files/513800/zvmguest-failedboot-journal.txt)
[zvmguest-goodboot-journal.txt](https://github.com/systemd/systemd/files/513799/zvmguest-goodboot-journal.txt)

**Comment by poettering** [comment]
what are those logs supposed to show?

All I can see is that a couple of things fail: some multipath stuff in udev rules, "networking.service", "setvtrgb.service", "serial-getty@ttysclp0.service", "serial-getty@hvc0.service", "serial-getty@ttyS0.service".

The latter fail probably because the matching devices never show up. Can't tell you why those devices never show up, you'd have to figure that out by yourself. But I can't see anything to do with sd-bus issues here?

**Comment by xnox** [comment]
setvtrgb.service is a red herring, and is in progress to be fixed. Missing consoles is also fine, those are generated, but because they are not connected fail to start. However, we do believe that udev gets stuck somewhere, because it does not online the expected CCW devices - specifically qeth. The multipath bits is kind of bad, because zfcp drives (and lvm on those) do not come up right. Will dig things further, certainly not having red-herring failing jobs should reduce distraction levels.

**Comment by xnox** [comment]
Note good boot has 

```
Sep 20 06:09:14 kernel02 systemd[1]: Child 526 (systemd-modules) died (code=exited, status=0/SUCCESS)
Sep 20 06:09:14 kernel02 systemd[1]: systemd-modules-load.service: Child 526 belongs to systemd-modules-load.service
Sep 20 06:09:14 kernel02 systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=0/SUCCESS
Sep 20 06:09:14 kernel02 systemd[1]: systemd-modules-load.service: Changed start -> exited
Sep 20 06:09:14 kernel02 systemd[1]: systemd-modules-load.service: Job systemd-modules-load.service/start finished, result=done
Sep 20 06:09:14 kernel02 systemd[1]: Started Load Kernel Modules.
Sep 20 06:09:14 kernel02 systemd[1]: systemd-modules-load.service: cgroup is empty
```

And bad boots don't.

**Comment by poettering** [comment]
well, do you see systemd-modules-load.service ever timing out in the bad boots? I couldn't find that in the logs.

Usually if s-m-l.s hangs during boot, then that's indication that one of the kmods listed for loading is broken and just hangs during initialization, and s-m-l.s just hangs waiting for it to return... Consider dropping all statically configured modules and see if things hang no longer then.

**Comment by poettering** [comment]
Closing due to lack of response
