### ISSUE TITLE
Resource control settings for processes

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#4317]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.04
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> …

MemoryLimit is a limit for the memory usage combined of all processes created by a service unit. I think options like MemoryLimitChild or MemoryLimitTask would be more than useful for a better fine-grained control. Of course, other resources could be also managed in a per process style too, not only in a per unit manner.

**Comment by poettering** [comment]
Sorry, but the kernel has no facility for this. We can only specify resource limits such as MemoryLimit= for whole cgroups, and we cannot precreate them and magically make child processes be part of them without the parent processes also being part of them.

Sorry, but I see little we can do here, without explicit kernel support, after all the resource control concepts are implemented by the kernel and we just expose them, they are not concepts we implement ourselves. Closing hence. Sorry, and I hope this makes sense.

(Prepared daemons can register a "scope" with systemd which allows them to run one or more processes in a separate systemd units, so that they can take benefit of split out logging and resource control. But this really means the daemon in question must be prepared for that and call into systemd's APIs for creating and managing these scope units.)
