### ISSUE TITLE
RFE: permit configuration of TFTP boot dhcp settings in networkd

### ISSUE THREAD

**Issue by q2dg** [systemd/systemd#4403]
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

Hello. As systemd-networkd already implements a Dhcp server, why not complete it with a Tftp server to get a basic PXE server all-in-one? This could be useful to get rid of dnsmasq, for instance. Sorry if I'm saying a stupid thing. Thanks!

**Comment by shibumi** [comment]
What has TFTP to do with networking? I think a PXE-Server is something additional and shouldn't be included in systemd-networkd. Otherwise there would be also no reason against a webserver or a ftp-server or a ssh-server.. and so on..

I don't think that TFTP is important for nspawn containers nor the host either.

**Comment by poettering** [comment]
Hm, sorry, but I am not convinced that a TFTP server really belongs in networkd. When it comes to addressing or discovery-related protocols, that are used in a huge part of the usecases sure, but TFTP doesn't strike me as one of those... Sorry.

**Comment by q2dg** [comment]
Ok! 2nd attempt, though...

Why not include as directives of systemd-netword's Dhcp server the hability of defining an external TFTP server and a corresponding boot file, "à la _next-server_ and _filename_ directives of ISC Dhcpd, then?

If you read RFC2131 (https://www.ietf.org/rfc/rfc2131.txt), which defines DHCP protocol, there are two standard fields for this purpose in dhcp messages : field "siaddr" and field "file" (they are briefly explained at pages 8, 9 and 27).

In any case, it will be fine if you consider this suggestion a nonsense idea: that's all right.

**Comment by poettering** [comment]
adding options for next-server and filename would be OK to add, indeed.

**Comment by b1tninja** [comment]
I would like to see IPXE capabilities in networkd as well.

One thing other dhcp servers do is allow you to customize the PXE/BOOTP/DHCP response based on the dhcp request. I think we can do better than dnsmasq's --tftp-unique-root. I will try and put together a PR this week for this feature, including a TFTP server-- the reason being the tftp server would need a network interface configured separately from [Match] making some scenarios unreasonably difficult to configure, as the TFTP server ideally would be aware of the files for that .network/DHCPServer, the netdev, and the appropriate broadcast address(es) to listen on.

The alternative would be duplicating static configs in some sort of tftpd service template... maybe it could not be built-in by default?

Is it scope or maybe security concerns that make you unsure?

**Comment by poettering** [comment]
Note that there's some support for this these days in SendOption= in the [DHCPServer] section. Adding explicit high-level support might still make sense though.

**Comment by mizvekov** [comment]
There are some other things missing from systemd-networkd dhcp server to make this be really useful though.
Having different configurations per the client's vendor-class-identifier for example. So you can give different filenames in different circumstances.
For example you can do this in dhcpd:
```
    if substring (option vendor-class-identifier, 0, 10) = "AM335x ROM" {
        filename "/u-boot-spl.bin";
    } elsif substring (option vendor-class-identifier, 0, 17) = "AM335x U-Boot SPL" {
        filename "/u-boot.img";
    } else {
        filename "/fitImage";
    }
```

**Comment by abraithwaite** [comment]
> Note that there's some support for this these days in SendOption= in the [DHCPServer] section. Adding explicit high-level support might still make sense though.

I've been trying to setup systemd-networkd for use in a pxeboot environment using a separate tftp server, but after reading a bit of code and doing a bit of head banging on keyboard, it appears that many pxe client implementations (at least from what I can tell reading [ipxe](https://github.com/ipxe/ipxe/blob/1192edf394aaebde666c6aafda1c8b782b08a845/src/core/settings.c#L2380-L2386) and [gpxe](https://github.com/etherboot/gpxe/blob/c23508d796325f8af724ad497c99ffb5a49abea0/src/net/udp/tftp.c#L1259-L1265) source code) depend on `siaddr` (next-server) being set in the DHCP reply in order to use them as tftp targets to connect to.  As far as I can tell, they don't allow for overriding that value with DHCP Option 66 or others for that matter.

I realize this may not be a priority for systemd-networkd, but I would very much appreciate the `next-server` and `filename` options added to the internal DHCP server, as the popular ipxe client doesn't seem smart enough to pull the other options.
