### ISSUE TITLE
Journald doesn't receive the FDSTOREd file descriptor back after a crash

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#4408]
### Submission type
- Bug report

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 225 & 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Own Distro & Debian Testing
### In case of bug report: Expected behaviour you didn't see

> I have terminated systemd-journald with kill -9. I was expecting to receive the sockets that had been sent to systemd back.
> 1) Journald is up, has a STREAM socket for another service ABC..
> 2) Same socket is sent to PID 1 and stored by PID 1 via FDSTORE=
> 3) Journald is killed with kill -9. 
> 4) Journald comes up again but without the FDSTOREd file descriptors.

I have tracked it down that PID 1 calls service_release_resources() for the dead service which terminates the only copy of the stored fds. 

The bad part is, service ABCs stdout still points to a socket. Write on the socket doesn't yield anything since journal is not aware of it. My guess is eventually the socket buffer will fill up and all prints to stdout will halt.

Am I missing something here?
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
hmm, journald uses Restart= and the stored fds should really stick around in that case. Basically, they are supposed to stick around as long as the service is around or there's a job queued for it. The moment that a service is stopped and no job is queued anymore for it they are closed.

Given your described behaviour this suggests the logic is borked somehow and not implemented correctly...

**Comment by utezduyar** [comment]
Thanks for looking in to this and fixing it @keszybz. I am confused though, maybe I misunderstood @poettering's comment but I thought some kind of simple line has been deleted or something like that. Seems like you have done a full-blown implementation. Was this functionality ever working?

**Comment by keszybz** [comment]
It's certainly possible I missed some simpler solution. I hope @poettering
can review this, he wrote the code and is probably the only person who
has the whole graph in his head. Nevertheless, the actual fix is quite
simple: add a flag, and set it one place, unset it in another.
I also considered adding another state SERVICE_DEAD_BUT_WILL_RESTART,
but that's require touching quite a lot of code and make the state graph
even more complicated.

**Comment by utezduyar** [comment]
I have tested this on one of our product which has systemd 208 on it and it is same problem there.

**Comment by utezduyar** [comment]
@poettering @keszybz I don't understand why the client side of the journald-server connections didn't get notified of the closure of the server side of the socket. If we had a way to enable that we would have caught this bug long time ago. Care to explain?

**Comment by poettering** [comment]
@utezduyar so, the stream socket from the daemons to journald are only open for writing, not for reading. When they are closed on the server side, then writing to them will normally raise a SIGPIPE. However, in systemd we decided to mask SIGPIPE by default for all system services, as such behaviour only makes sense in shell pipelines really. If SIGPIPE is turned off writing to the socket will result in an EPIPE error, which is good. However, pretty much nobody actually checks the error code when logging with `fprintf(stderr, "…");` or something similar, hence you'll never see any error raised by this. And it's actually the right thing to ignore any errors then, because what could you do in this case: log another error? then you'd enter an endless loop: you want to log that logging didn't work, which won't work either, so you log about it which won't work, so you log about it which won't work, so you log about it which won't work, ad infinitum.
