### ISSUE TITLE
ConditionFirstBoot is not power failure safe

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#4511]
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_

231

> …

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_

Own

> …

ConditionFirstBoot is not power failure safe. If before a service gets to execute, a power loss in system will eat up the first boot. Next time the system starts, it is no longer first boot and a service that is dependent on ConditionFirstBoot might produce faulty results.

> …
### In case of bug report: Unexpected behaviour you saw

> …
### In case of bug report: Steps to reproduce the problem

> …

**Comment by keszybz** [comment]
Yeah... It's hard to make this reliable with current design. Maybe instead we should have a firstboot.target which pull in a "firstboot-done.service" which would touch a flag file... or something, dunno.

**Comment by poettering** [comment]
Here's an idea, maybe on the first boot we should not write a new uuid to /etc/, but instead just an empty file, and then overmount that with a symlink to /run/machine-id, like we already do if /etc is not writable and the file is exists and is empty. Then, rely on systemd-machine-id-commit.service to write it to disk in later boot. Then, let's consider all cases where /etc/machine-id exists but is empty a first case boot oot. This should be a relatively easy change, and would mean until systemd-machine-id-commit.service has once been reached all boots are considered first boot.

**Comment by jlebon** [comment]
> Then, let's consider all cases where /etc/machine-id exists but is empty a first case boot oot.

Hmm, doesn't this break the use cases that were brought up when this was suggested in https://github.com/systemd/systemd/issues/8268 ?

**Comment by Rahix** [comment]
@jlebon, in the implementation (PR #16939) it was decided to use a sentinel value instead of "empty file" for exactly this reason.

**Comment by jlebon** [comment]
This topic came up in discussions in CoreOS-land about how safe it is to reboot from a `ConditionFirstBoot` unit (see e.g. [here](https://github.com/coreos/fedora-coreos-docs/issues/88#issuecomment-652009154)). I think the new `first-boot-complete.target` helps here, but not entirely. If we want to use `ConditionFirstBoot=`, we'd have to use `After=first-boot-complete.target` to make sure we don't get stuck in a reboot loop. But if we do that, we're then susceptible to power failures again causing the unit to not run.

Hmm, I guess what we'd have to do here is use `After=first-boot-complete.target` and avoid `ConditionFirstBoot=` in favour of our own stamp file? That works, but is counter-intuitive.

Maybe a cleaner approach is for systemd to inhibit reboots until `first-boot-complete.target` is reached? That way even units which want to reboot the system can safely use `ConditionFirstBoot=`.

**Comment by poettering** [comment]
@jlebon hmm, can you elaborate what you are still missing? with #16939 we should have a clear milestone: abnormal poweroff before the milestone means next reboot is considered a first boot still, abnormal after the milestone means next reboot is no longer a first boot. Whatever you order before the milestone thus will be invoked again and again and again until one boot manages to reach the milestone. Whatever you order after the milestone doesn't get that guarantee.

So what precisely do you still need semantically beyond thta?

**Comment by jlebon** [comment]
> So what precisely do you still need semantically beyond thta?

What happens if a unit wants to runs `systemctl reboot` from a `ConditionFirstBoot=true` unit ordered before the milestone? Does systemd still try to reach the target first, or does it immediately isolate to `reboot.target`? If the latter then we enter a reboot loop, right? My suggestion in https://github.com/systemd/systemd/issues/4511#issuecomment-709376660 was to use an inhibitor to cover this case.

**Comment by Rahix** [comment]
@jlebon, reboot needs to be delayed even beyond `first-boot-complete.target`, up until `systemd-machine-id-commit.service` completes.  I guess your first-boot service could enqueue a new unit for rebooting that is ordered after `s-m-i-c.service`?

**Comment by poettering** [comment]
> What happens if a unit wants to runs `systemctl reboot` from a `ConditionFirstBoot=true` unit ordered before the milestone? Does systemd still try to reach the target first, or does it immediately isolate to `reboot.target`? If the latter then we enter a reboot loop, right? My suggestion in [#4511 (comment)](https://github.com/systemd/systemd/issues/4511#issuecomment-709376660) was to use an inhibitor to cover this case.

The last request generally wins. So the reboot would take precedence. Yes, an inhibitor could help, but they currently have effect only on unprivileged clients since they can be acquired by unprivileged clients.

But not sure I grok this? Why would you issue "systemctl reboot" on every single boot? I mean, don't do that if you don't want a reboot loop. I don't get the scenario why you'd do that?

**Comment by jlebon** [comment]
> But not sure I grok this? Why would you issue "systemctl reboot" on every single boot?

That wouldn't be the intention of course. :) Let's say e.g. you want to install a package on the first boot of a cloud instance/freshly imaged machine and then reboot (e.g. via a systemd unit specified in Ignition/cloud-init). What I'm describing above is that you can't reliably use `ConditionFirstBoot=true` for this.

If you use `Before=first-boot-complete.target`, the next boot will also be considered a first boot (and if your service unit isn't designed to be idempotent, you'd get a reboot loop). If you use `After=systemd-machine-id-commit.service`, then any power failure/reset that happens between that and your service means your service will never run. (Unless I'm misunderstanding the semantics added in #16939).

Am I correct in that case you'd be better off using `After=systemd-machine-id-commit.service` and your own stamp file instead of `ConditionFirstBoot=true`?

>  I guess your first-boot service could enqueue a new unit for rebooting that is ordered after s-m-i-c.service?

I think that would work but having to write two units for something seemingly simple isn't a great UX (at least compared to just using your own stamp file). I guess we could ship that second unit in CoreOS which keys off of e.g. `/run/reboot-requested`? Meh... stamp files seem cleaner.

My original point though is that it's not obvious that using `systemctl reboot` from `ConditionFirstBoot=true` is probably not what you want to do.

**Comment by Rahix** [comment]
@jlebon, I wouldn't write an actual second unit but instanciate a transient one e.g. via

```bash
systemd-run \
    --unit="ignition-reboot.service" \
    --description="Reboot after Ignition set up the system for the first time" \
    --service-type="oneshot" \
    --property="After=systemd-machine-id-commit.service" \
    --no-block \
    /bin/systemctl reboot
```

(Not tested ...)

**Comment by poettering** [comment]
I'd go the route @Rahix suggested, too. If you want to reboot after the first boot is complete, that's totally OK, but I'd just enqueue a job that requests that. Either enqueue that with a dynamical transient unit, like the one @Rahix proposed. Or add a regular unit into /usr/lib/systemd/system/, that does the same and that you just enqueue whenever you want the system to reboot with "systemctl start --no-block".  i.e. enqueue a job that runs a program that enqueues a job that reboots. This way both jobs can be scheduled exactly at the right times via After=, and will not reverse what's already queued.

**Comment by poettering** [comment]
(I'd probably go the regular unit way, since it means mutiple different pieces of code that run during boot can all enqueue it, and it will just be enqueued once (since that's how systemd works if multiple clients all enqueue the same unit) which is a nice property. i.e. provide `fedora-coreos-firstbooot-reboot.service` in one of your base OS packages, that has `ExecStart=systemctl --no-block reboot` + `Type=oneshot` + `After=systemd-machine-id-commit.service`. And then every component of the boot process that wants to reboot after boot up completed can just do `systemctl --no-block start fedora-coreos-firstboot-reboot.service` to request a reboot after everything is done. You get the idea
