### ISSUE TITLE
RFE: timestamp/date specifier

### ISSUE THREAD

**Issue by mskarbek** [systemd/systemd#4519]
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### Description/justification

Assume daemon which takes file name as an option to write some output but does not support appending to this file so it will overwrite data each time it will be restarted. In that case timestamp or date specifier could prevent this behavior by providing new name for the file each time we are starting/restarting service.

**Comment by lucaswerkmeister** [comment]
Possible syntax, from Bash’s `printf`:

> `%(fmt)T` output the date-time string resulting from using FMT as a format string for `strftime(3)`

Otherwise, `%T` is still free, but that wouldn’t allow any date format specification. In that case the best choice would probably Unix time (not sure in which precision).

**Comment by poettering** [comment]
Hmm, so specifiers are expanded at the time we read configuration, and I am not sure we should change that. They have pretty clear semantics the way they are, and only expose settings that are basically constant during runtime, so that the precise time of evalution doesn't matter.

Moreover, I don't think systemd should be a place to work around other people's code. If the daemon in question cannot use O_APPEND, then I think it would be best to teach it that, and much more useful for everybody in the long run.

I am also afraid of turning the specifiers into more of a programming language they already are. They should be macros at best, but with a temporal concept added to them they'd suddenly become a lot more than a state-free macro language...

Sorry, but I am really not convinced this would be a good thing to add.

Sorry!
