### ISSUE TITLE
[RFE] Way of running something everytime a service state changes.

### ISSUE THREAD

**Issue by sean797** [systemd/systemd#4553]
### Submission type

  -   [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 231

### Used distribution

> Fedora 

### RFE
I would be great if we can have a way to run something everytime a service state changes.

The [Katello Project](http://katello.org) provides a repo server for client and after every yum/dnf transaction we use a yum-plugin and [Tracer](https://github.com/FrostyX/tracer) to upload a report to the server for what services need to be restarted (yum/dnf runs this script automatically). Currently if a user restarts/start/stops a service they need to then run the Tracer upload manually, it would be great if we could do this automatically.

**Comment by grawity** [comment]
You could write your own event-handler daemon for Tracer – systemd already provides such events in the form of D-Bus signals, so there already are facilities to do this in your own code. (See the `Subscribe()` method at first.)

**Comment by poettering** [comment]
we send notifications for all unit state changes as PropertiesChanged bus messages across the bus (you can see them via `busctl monitor org.freedesktop.systemd1`).

It's relatively easily to script something like what you need with language like python. But I am not convinced we should provide such a generic tool in systemd though.

Hope this makes sense.

Sorry!

**Comment by sean797** [comment]
>  But I am not convinced we should provide such a generic tool in systemd though.

Why? Other projects do this for example yum & dnf have plugins.

I want to avoid a daemon running and listening for events, although it would work, it seems like massive overkill to me & would use unnecessary resources however small it may use.

**Comment by poettering** [comment]
@sean797 just think about this for a moment. when systemd forks off a process it does so inside of a concept called "services". now you want us to call your tool whenever we start a service. Thus we'd start a service each time we start a service. Which would result in an explosion of services.

I don't think the semantics make much sense, sorry, and I am not really convinced by your usecase either (i mean, it's impossible to properly figure out what to restart after an rpm update: many deps are never visible to the outside, due to loadable modules and so on).

I simply don't think that systemd should be in the business of running arbitrary things depending on arbitrary conditions.

**Comment by sean797** [comment]
@poettering Okay that make sense :+1: Thanks!
