### ISSUE TITLE
RFE - remove requirement .mount files must match the where setting.

### ISSUE THREAD

**Issue by james-lawrence** [systemd/systemd#4661]
version: systemd 231
distro: arch linux

I've always found it odd that .mount files require the name match the Where= setting. Is this some weird security thing? Otherwise can we please remove that restriction its annoying and non-sensical.

**Comment by poettering** [comment]
This is by design and ensures that mappings between mounts and units always are 1:1. So that anything we enumerate via /proc/self/mountinfo has exactly one matching unit, and vice versa.

In contrast to many other unit types we synthesize mount units automatically depending on external objects, and thus sticking to a fixed naming scheme ensures we always know exactly which unit maps to which underlying mount point and vice versa.

Sorry, but this is not going to change.
