### ISSUE TITLE
RFE - multiseat with systemd-nspawn containers?

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#4662]
- [x] Request for enhancement (RFE)

I was wondering if it would be difficult to get a multiseat configuration running where each seat is using a container. I'm not a distro engineer, so I don't see how this could be done, but I feel it would make sense.
Multiseat is broken in fedora 24, and in fedora25 beta, due to bugs in the software layers somewhere above systemd. If it would be simple to set up, maybe some of these bugs could be isolated with containerization, and that could be a workaround. But also, maybe one seat wants to use a set of packages and the other another set, maybe even a different desktop environment. ...

Would it be possible to attach a seat to an nspawn container?

**Comment by poettering** [comment]
multiseat is a concept of grouping various hardware devices to form one logical workplace for a user. Containers (at least the ones systemd natively supports, in form of nspawn) are a form of virtualization that moves software from runnineg directly on the OS that runs on the bare metal and thus has device access onto containers that run in their own virtualized environment lacking direct hardware access. Among other things this means that containers generally lack the "udev" device manager, as the device nodes they have in /dev generally consist of little more than /dev/null, /dev/zero, /dev/random and similar pseudo-devices. "udev" is essential for managing seats however.

Due to this the concepts are pretty much incompatible: one is a technology to group hardware, the other to abstract the access to hardware.

Sorry, but this is not going to happen.
