### ISSUE TITLE
nspawn Support for audio autoconfig and/or manual soundcard assignment like networkd

### ISSUE THREAD

**Issue by fpqc** [systemd/systemd#4702]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch

Systemd-nspawn works very nicely with networkd and resolved for very nice automatic configuration of networking for containers. However, on the other hand, the solutions for audio (and arguably graphics) in containers are a mix of undocumented/poorly documented tricks together with some pretty ugly hacks (running pulseaudio as a system daemon on the nspawn host, either in tcp mode or by binding /run/pulse to the containers and passing environment variables).  

Pulse is written, like Network Manager, for desktop linux with one user taking command of audio at any given time, and not particularly with things like containers in mind.

It would be really cool if nspawn and systemd generally could provide a container-aware and service-aware platform for audio (and maybe something similar for graphics?) that also has sane automatic defaults like networkd.

**Comment by poettering** [comment]
First of all, the Linux audio stack is not virtualized. The only type of device that is fully virtualized are network devices really. That's why we don't provide block device, or audio device or any other kind of virtualization: we can only expose what the kernel supports natively.

Then, conceptually, nspawn is supposed to be two things: 

1) a tool for doing full-OS virtualization. Kinda like a KVM, that i implemented with container technology rather than hw virtualization. Key is that it is has a proper init system running as PID 1.
2) a generic building block that other projects can build anything from they like, the way rkt is doing it for example

Now, if these are the two concepts we try to follow: in neither does it fit to do anything specific for audio... I mean, full OS virtualization relies on using networking as the transport for anything in and out of it, and as PA has networking support you can already do that. And if you think of npsawn as building block for other projects, then it appears that audio hookup should happen on top and outside of nspawn, but not in the basic building block that nspawn is...

Moreover I am pretty sure that --setenv= + --bind= should already make most available of what you need. It's not automatic though, but I am not convinced it should be.

I hope this makes sense. Sorry!

**Comment by fpqc** [comment]
@poettering Lennart I was just wondering this, then: With the X.org team moving away from X and toward Wayland, we're seeing, to an extent, a move away from network transparency for graphics.  Do you guys at systemd have any idea on how you're going to handle this with something like nspawn if the remote rendering of X clients is already deprecated (some proceedings from an X.org conference I read referred to wanting to "kill it with fire")?  Without remote rendering in Wayland, graphical applications in containers will have to fall back to software rendering where they can now at least now use remote indirect GLX (set LIBGL_ALWAYS_INDIRECT=1 inside of the container and connect to DISPLAY=$HOST:0 in the container)?  This is sort of a more interesting question than audio, maybe, where the pulseaudio team (also the Jack2 team fwiw) seems to be committed to maintaining network transparency for the moment.

**Comment by poettering** [comment]
On Tue, 22.11.16 00:20, fpqc (notifications@github.com) wrote:

> @poettering Lennart I was just wondering this, then: With the X.org
> team moving away from X and toward Wayland, we're seeing, to an
> extent, a move away from network transparency for graphics.  Do you
> guys at systemd have any idea on how you're going to handle this
> with something like nspawn if the remote rendering of X clients is
> already deprecated?  Without remote rendering in Wayland, graphical
> applications in containers will have to fall back to software
> rendering where they can now at least now use remote indirect GLX?

Well, I am not a wayland hacker. But do note that Kristian early on
hacked up some network-aware wayland thingy. Wayland follows a
separate networking model, but it's not incompatible with networking.

But this is really something to ask the Wayland folks, not us.

**Comment by fpqc** [comment]
@poettering I haven't asked a Wayland hacker in person, but the "network transparency" of Wayland only amounts at best to VNC.  Someone named Alex Larsson was able to get Wayland to work for containers by exposing the host's DRI to the container for rendering but using Wayland in network mode for actual display. 

The trouble isn't Wayland as a display/input protocol,  the problem is that there is no way to proxy rendering out to the machine without directly exposing DRI through namespace hackery.  Maybe what is needed is a DRI proxy?  

The reason why I ask is that you guys at Systemd seem pretty enthusiastic about nspawn being both a platform for containerized services as well as for full OS virtualization, and the latter seems like a case where you could really make use of remote rendering, or at least access to the host's DRI, so I'm just wondering how much thought you've put into it.
