### ISSUE TITLE
No predictable interface names without networkd

### ISSUE THREAD

**Issue by mmazur** [systemd/systemd#479]
(I'm running 219, can't check 221 for whether this got fixed. I don't see anything in the changelog indicating that it has.)

rules/80-net-setup-link.rules assumes ID_NET_NAME is set to rename all interfaces to PNIN. However that var is not set without networkd running.

So with a simple 208 -> 219 upgrade of systemd I've gotten a rather serious regression.

(Old udev rules just checked all ID_NET_NAME_xyz vars in succession.)

**Comment by grawity** [comment]
Hmm, this has nothing to do with networkd; the mechanism has been slightly expanded but remains completely within udev. You should have an 80-\* rules file that calls the net_setup_link built-in, which then determines the possible names on its own, looks for *.link files, and renames interfaces accordingly.

**Comment by poettering** [comment]
Note sure I understand what the issue is supposed to be. @grawity is right, the renaming is applied by udev, by reading the .link configuration files. Specifically /usr/lib/systemd/network/99-default.link carries the default policy. Maybe your distro removed that file or packaged it along with networkd rather than udev?

Which distro is this anyway?

What is "PNIN" supposed to mean?

**Comment by mmazur** [comment]
Right, it was in fact a distro packaging error, the 99-default.link file was in a separate subpackage instead of the main systemd package. I've notified distro upstream and am closing this case.

**Comment by poettering** [comment]
(Which distro was this, out of curiosity?)

**Comment by mmazur** [comment]
[PLD](http://pld-linux.org)

Packager wrongly assumed that everything that resides under /lib/systemd/network is only relevant to networkd.
