### ISSUE TITLE
coredumpctl: do something sensible with coredumps from containers

### ISSUE THREAD

**Issue by MikhailKasimov** [systemd/systemd#4791]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 228 and others

### Used distribution

> openSUSE Leap 42.2

### RFE Description

Again, due to phrase ```coredumpctl is basically just a frontend for the journal```, ```journalctl``` has the possibility to work on local container (-M, --machine key). The same functionality should be also acceptable for ```coredumpctl``` -- e.g. ```coredumctl - M <containter>``` to have possibility to work with coredumps on local container(-s).

**Comment by poettering** [comment]
Well, coredump processing always happens on the host, the kernel enforces that. That means if a process in a container coredumps, this is collected by the host, not the coredump tools in the container.

Hence I doubt it makes much sense to provide coredumpctl -M, because there should normally not be much to process...

**Comment by MikhailKasimov** [comment]
```this is collected by the host, not the coredump tools in the container.``` -- ok, no problem, but here is the one question for it: how can user|admin see the source of defined coredump (was it from my host machine or was it from a local container(-s)) in ```coredumpctl list``` command output?

If all of them are in one single pile in ```coredumpctl list``` command output without any marks (e.g. $(hostname), $(container-name)), this seems not to be good.

**Comment by keszybz** [comment]
I'm not sure how best to handle this, but we should do *something*. We have a bunch of relevant info already:

    COREDUMP_UNIT=machine-rawhidex.scope
    COREDUMP_UID=1499201536
    COREDUMP_GID=1499201536
    COREDUMP_SLICE=machine.slice
    COREDUMP_CWD=/root
    COREDUMP_ROOT=/
    COREDUMP_CONTAINER_CMDLINE=systemd-nspawn --link-journal=try-guest --network-zone=zone1 -U -M rawhidex -b --bind=/home
    COREDUMP_CGROUP=/machine.slice/machine-rawhidex.scope/user.slice/user-0.slice/session-4.scope
    ...

**Comment by poettering** [comment]
@keszybz i figure we could use cg_path_get_machine_name() easily, and attache COREDUMP_MACHINE= as well, and then make -M just filter for that.

**Comment by keszybz** [comment]
And what about doing something crazy: feed the coredump back into the the container, and let it be processed internally there? It'd probably be more useful from the POV of the container, if the container is used like a separate system.

**Comment by martinpitt** [comment]
Agreed that handling core dumps in the container and just forwarding it there is structurally easier to understand and also more robust. In Apport I got bitten by a [privilege escalation](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-1318) vulnerability the other  day when it tried to handle container crashes in the host. So either way this needs to be designed carefully.

**Comment by poettering** [comment]
@keszybz yeah, i though about that too, but it wasn't obvious to me how to do that best. I mean, it would be great if we could emulate core_pattern inside a container properly, but I doubt we could really emulate things properly (i mean, it already starts with how to make a core_pattern file writable with sane semantics).

So if we can't do that we have two other options, both accepting that compat with generic core_patterns is not possible, but we'd only do systemd-specific support: systemd-coredump on the host would look for systemd-coredump in the container, and only support that.

1. from the host's core_pattern hook, directly invoke systemd-coredump in the container, with parameters compatible with what the kernel would pass. Doing this in a future-proof way isn't trivial though and requires special care: should the kernel gain a new specifier we'd like to make use of (e.g. cgroup path), and we cannot just go and change the core_pattern in the sysctl.d snippet we ship and be done with it, since some foreign coredump helper might still call our helper with the old parameter set, and we'd have to cover for that. one way to achieve that would be to change the core_pattern from `systemd-coredump %P %u %g %s %t %c %e` to `systemd-coredump _SYSTEMD_COREDUMP_PID=%P _SYSTEMD_COREDUMP_UID=%u _SYSTEMD_COREDUMP_GID=%g…` and so on, which would make this nicely extensible.

2. from the host's coredump_pattern hook, join the container and connect to the systemd-coredump.socket socket directly, i.e. skip the extra hook, avoid having to fork off a foreign process inside the container, and just connect to the AF_UNIX socket of systemd-coredump@.service directly.

In both cases we'd have to take particular care not to leak the host's view on PID, users and so on into the container, and translate them as necessary. I figure that'd be much easier to control in option 1 above, as in that case most metadata collection would happen inside the container anyway, and we would only have to translate what's specified directly on the core_pattern command line, but nothing else.

Both options have their pros and cons, but I figure the the UID/PID/GID translation issue makes option 1 look like the much better option...

But yeah, I think doing this would make sense. It's not entirely trivial though, due to the translation issues, but I figure that's managable.

**Comment by martinpitt** [comment]
For the record, this is [how apport currently does that](http://bazaar.launchpad.net/~apport-hackers/apport/trunk/view/head:/data/apport#L306): We use systemd's socket activation. On the container side, if `$LISTEN_FDS` is set we replace fd 0 (stdin, which is where the kernel  normally dumps the core when the kernel calls `core_pattern`) with the passed fd. The host apport instance (which gets the real core dump fed into stdin) then checks whether the pid belongs into a container, and if so sends its fd 0 to the container's `apport.socket`. This is reasonably simple and elegant, should avoid any privilege leaks and is as close as "container behaves like using `core_pattern` as possible.

**Comment by poettering** [comment]
@martinpitt and how do you pass any metadata you got from the kernel via the core_pattern command line? or don't you use that?

**Comment by martinpitt** [comment]
@poettering: apport does use that (I'd think it'd be quite hard to do without). It takes its own argv and `sendmsg()` that [on the host side](http://bazaar.launchpad.net/%7Eapport-hackers/apport/trunk/view/head:/data/apport#L372) and `recvmsg()`s it [in the container](http://bazaar.launchpad.net/%7Eapport-hackers/apport/trunk/view/head:/data/apport#L327), replacing `sys.argv` with it so that the following code remains unaltered. This works more nicely in Python of course, but the general approach should work in C as well.

**Comment by poettering** [comment]
ah, so you pass the translated PID in already, the way the kernel provides it to you. And you don't bother with the UID or any other data like that which might need translation and instead read it from /proc. Did I get that right?

**Comment by martinpitt** [comment]
Correct. Apport reads as much information as possible (like `/proc/pid/maps` or UIDs) from within the container, as every translation outside is prone to forgetting some translation and thus prone to privilege escalations. `core_pattern` uses `%p %s %c %P` only, and the `%P` does not get passed to the container (only the first three).

**Comment by keszybz** [comment]
> `_SYSTEMD_COREDUMP_PID=%P _SYSTEMD_COREDUMP_UID=%u _SYSTEMD_COREDUMP_GID=%g…` and so on

I'd make this
> `Pug…e: %P %u %g … %e`

That's shorter and should be just as extensible.  (We don't need support for arbitrary sequences here, we'd only change this on our own when we'd need to add more fields. Anyway, the code could just iterate over the first argument if necessary.)

**Comment by jfilak** [comment]
My two cents: You don't need to push coredumps to the source container. If there is a program which takes care of coredumps in a container, the container can be started in the way that the program can get coredumps from journald. The only problem here is that the program needs to be able to identify coredumps originating from its container. That's how I suppose ABRT will work in containers.

**Comment by mrc0mmand** [comment]
This should be addressed by https://github.com/systemd/systemd/pull/29272, which allows forwarding coredumps to the respective containers.
