### ISSUE TITLE
99-systemd.rules - please add ppdev rule

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4796]
- [ ] Request for enhancement (RFE)

> systemd 232-4

> Arch

In order to allow some kind of communication between the kernel's parport_pc module and systemd, please add the following rule to `/usr/lib/udev/rules.d/99-systemd.rules`:

SUBSYSTEM=="ppdev", TAG+="systemd", ENV{SYSTEMD_ALIAS}+="/sys/subsystem/ppdev/devices/$name"

This will allow some "pretense" of hot plug support on boot and also with any removable parallel port adapter, with the following service unit file, which operates in conjunction with the typical existing cupsd service unit file:

`org.cups.cupsd@.service`

---

[Unit]
Description=CUPS Scheduler
Documentation=man:cupsd(8)
After=network.target
BindsTo=sys-subsystem-ppdev-devices-%i.device

[Service]
ExecStart= /usr/bin/sh -c ' \\
 /usr/bin/grep -q "CLASS:PRINTER" /proc/sys/dev/parport/%I/autoprobe && \\
 /usr/bin/systemctl start printer.target'

[Install]
DefaultInstance=parport0
WantedBy=sys-subsystem-ppdev-devices-%i.device

---

This is particularly useful with a parallel port attached printer on a machine acting as a networked print server, to ensure that cupsd is started on boot, so that IPP broadcasts are sent, and the printer is "seen" by and available to remote hosts.

**Comment by poettering** [comment]
Hmpf, the parport stuff isn#t really hotpluggable anyway. This is something that needs to be fixed in the kernel, they need to adopt the device model. But I figure nobody is having the hw for tha anymore...

Either way I am not convinced we should carry such a rule upstream. It probably should be part of some "parport-tools" package or so, but I am not sure this should go upstream. sorry
