### ISSUE TITLE
Weird libsystemd behavior with private connections

### ISSUE THREAD

**Issue by nico-meetprizm** [systemd/systemd#4846]
### Submission type
  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with
> 231

### Used distribution
> Fedora 25

### Steps to reproduce the problem
Using libsystemd to make dbus calls
I deliberately use a private bus connection & not the sd_bus_default_xxx

I have the following test code in a c++ application (here without error checking):
> sd_bus_open_system(&bus);
> sd_bus_get_property(&bus, "my.bus", "my.path", "my.iface", "prop", NULL, &reply, "sig");
> /* I read the content of reply here */
> sd_bus_message_unref(reply);
> sd_bus_unref(bus);

### Expected behaviour you didn't see

I expected that when I `sd_bus_unref` the bus object in the previous code, the actual connection to the bus was closed & all ressources regarding the connection were dropped.

### Unexpected behaviour you saw

What I saw is:
- After `sd_bus_open_system` call the internal Refcount of the objec is 2 while I was expecting 1
- After `sd_bus_unref` the bus RefCount is 1 & the program still holds an open fd to the underlying /var/run/dbus/system_bus_socket socket

Am I missing something on the usage of the sd-bus API ?

I feel like the only way to really drop the connection would be for me to call `sd_bus_flush_close_unref` but that feels awkward. 
What would be the point of having such a reference counting mechanic if the caller would have to know that he holds the last reference to the object and thus should call a different 'unref' function.

**Comment by poettering** [comment]
The thing is that there might be messages being queued or half-read at time of unreffing, and the current logic is to stay around if so, so that they can be written out to the connection. If you don't want this then yes, you need to actively need to call sd_bus_flush_close_unref() so that they are actively flushed and the connection is terminated.

This follows the logic that code can ref a connection, drop a message into it, unref it, and still be sure that the message hits the wire eventually. If we'd immediately destroy the connection when the user unreffed it, then this would not be possible. Now of course, if the bus object isn't attached to an event loop then there's no chance it actually really be written out, but we chose to keep the logic similar for the mode where the bus is connected to an event loop, and where it isn't...

But yes, this is far from obvious, we really need to document this better.

**Comment by poettering** [comment]
Or to say this differently: a bus connection stays around as long as either the user has a ref to it, or as long as there's a message queued for input or output.

**Comment by nico-meetprizm** [comment]
Thanks for the info.
That behavior is quite understandable for the default system/user connections as (at least that's as i understood it) were made for calls like this (ref, call, unref, it will be sent/read later).
But I was hopping something different for the non-shared connections as once I drop all references to the bus with `sd_bus_unref` I won't be able to get a hold on that same bus object ever again.

Does that mean that if I :
1. open a bus `sd_bus_open_system`
2. do synchronous calls with `sd_bus_get_property` (only synchronous, so no async thus no unread messages)
3. unref both the bus & the property response message
Will the connection be closed ?

Or must I do a simple loop that loops on `sd_bus_process` as long as it returns me a value > 0 to be sure that all data is processed on the bus before I unref the bus ?
Or even that won't be enough to assure me the connection will be closed when I unref.

**Comment by poettering** [comment]
You need no simple loop, just use sd_bus_flush_close_unref() which will write out all unwritten messages, and close the connection dropping all unprocessed incoming messages. Internally, sd_bus_flush_close_unref() does the loop you need.

**Comment by poettering** [comment]
Actually this behaviour is already documented:

https://www.freedesktop.org/software/systemd/man/sd_bus_default.html#Reference%20ownership

Closing hence.
