### ISSUE TITLE
Unable to resolve DNS for a few seconds every now and then

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#4866]
Hi,

Running debian unstable with systemd 232-7 (compiled with "Default DNSSEC mode: allow-downgrade")

My resolver is set to my ISP box (this is different from my last DNS/DNSSEC issues with resolved) that doesn't seems to support DNSSEC.

From time to time, DNS resolution fails completely for a few seconds.

When the problem occurs I'm seeing the following messages:

> déc 11 19:58:51 fornost systemd-resolved[1190]: Switching to system DNS server 192.168.1.1.
> déc 11 19:58:51 fornost systemd-resolved[1190]: Grace period over, resuming full feature set (UDP+EDNS0+DO+LARGE) for DNS server 192.168.1.1.
> déc 11 19:58:51 fornost systemd-resolved[1190]: DNSSEC validation failed for question org IN DNSKEY: no-signature
> déc 11 19:58:51 fornost systemd-resolved[1190]: DNSSEC validation failed for question org IN SOA: no-signature
> déc 11 19:58:51 fornost systemd-resolved[1190]: DNSSEC validation failed for question debian.org IN DS: no-signature
> déc 11 19:58:51 fornost systemd-resolved[1190]: DNSSEC validation failed for question debian.org IN DNSKEY: no-signature
> déc 11 19:58:51 fornost systemd-resolved[1190]: DNSSEC validation failed for question nl.debian.org IN DS: no-signature
> déc 11 19:58:51 fornost systemd-resolved[1190]: DNSSEC validation failed for question nl.debian.org IN SOA: no-signature
> [...]
> déc 11 19:59:29 fornost systemd-resolved[1190]: Switching to system DNS server fe80::9e97:26ff:fe92:c82%2.
> déc 11 19:59:29 fornost systemd-resolved[1190]: Switching to system DNS server 192.168.1.1.
> déc 11 19:59:29 fornost systemd-resolved[1190]: Using degraded feature set (UDP+EDNS0) for DNS server 192.168.1.1.

I see the messages about "no-signature" at all time (even when there is no issues)

```
$ grep -e ^hosts /etc/nsswitch.conf 
hosts:          files myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns mdns4 mymachines
```

**Comment by poettering** [comment]
So, your DNS server appears not to support DNSSEC. Which we properly detect and downgrade. Now, there's logic in place that from time to time we try to upgrade again to the proper DNSSEC mode, in the hope that maybe something changed. If nothing changed we should downgrade again, going back to the old state.

This upgrade is what the "Grace period over, resuming full feature set (UDP+EDNS0+DO+LARGE) for DNS server 192.168.1.1." line indicates.

Normally all this shouldn't be noticable, except that the lookup takes a bit longer, since we have to go through all the downgrade steps again, figuring out what the server actaully groks, and what it doesn't.

The question is what precisely is wrong here. I have the suspicion that the reason for your issue is that we don't flush our local RR caches when this happens, which means we might mix up unauthenticated and authenticated data for the new lookups which is where things go wrong. The mix up might happen simply because your DNS server can do DNSSEC properly for some domains but not for others.

I'll prep a fix that flushes the caches in such a case, not sure if it helps though.

**Comment by poettering** [comment]
This might be fixed by #5347. Would be great to verify that.

**Comment by andrewdunndev** [comment]
I'll attempt to turn it on for some of my systems. We by and large had to disable and go back to using the standard `/etc/resolv.conf`, would be nice to use both networkd/resolved together.

**Comment by dreua** [comment]
Has this fix been verified? I'm running into a similar problem but with a slightly unusual configuration: I created a dummy interface in order to resolve DNS for specific domains through a different DNS Server. Which works fine except for the 20s timeout at the first query to this DNS Server and whenever the grace period has elapsed.

Reproducible after each reboot or `systemctl restart systemd-resolved.service` 

```
[dar@fedora systemd]$ sudo systemctl restart systemd-resolved.service 
[dar@fedora systemd]$ date && time resolvectl query [redacted host] && date
Di 17. Mai 18:15:30 CEST 2022
[redacted host]: [redacted ip]                   -- link: dummy-[redacted]

-- Information acquired via protocol DNS in 21.0583s.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: network

real	0m21.066s
user	0m0.004s
sys	0m0.004s
Di 17. Mai 18:15:51 CEST 2022
```
```
Mai 17 18:15:41 fedora systemd-resolved[59965]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server [...].
Mai 17 18:15:51 fedora systemd-resolved[59965]: Using degraded feature set TCP instead of UDP for DNS server [...].
```

**Comment by rpodgorny** [comment]
@dreua please be sure to link the new issue ticket. thanks!

**Comment by dreua** [comment]
Sorry that took so long, the issue template asked me to report only bugs to the last two major versions therefore I wanted to upgrade my Fedora first.
Bug is still the same and now reported as https://github.com/systemd/systemd/issues/24000
