### ISSUE TITLE
Frequent "Starting../Started.." status messages for frequent timer units

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#4919]
### Submission type

  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 231

If the system has a frequent .timer unit, the system log is filled with "systemd[1]: Starting ....." logs. What can be done for this?
- Maybe have an option on .timer units to completely silent systemd on "Starting.." / "Started.." messages.

**Comment by poettering** [comment]
I am pretty sure we should log about events happening on the system... Not sure we should do anything about it...

**Comment by utezduyar** [comment]
I agree that we should log about things. 
- What about having the option of lowering the log severity to debug for timer units?
- It would be pretty complex but what about having a configuration to merge multiple "Starting../Started.." messages?

**Comment by DocMAX** [comment]
I agree, please add option to silent start/stop messages on timers!

**Comment by aldem** [comment]
> I am pretty sure we should log about events happening on the system...

... unless someone explicitly _wants_ it otherwise. Policies and preferences are different in different sites/hosts, thus choice/option is important.

There are tons of start/stop events logged which are sometimes (often?) useless, especially timers firing every few seconds, or services which are monitored somehow anyway (outside of systemd). Sure, for long running services/timers you may want to know why/when it was started or stopped, but if this happens every few seconds, and for tens of services (or more)... it would rather make sense to log when it does not start/stop for a while.

The main problem is that frequent (few per minute or even second) noise-like messages are cluttering log and significantly increase disk space/usage (especially important for flash devices), while in most cases it is really totally unimportant to log starts/stops and similar noise. Additionally, lots of noise is "covering" more important messages, it is relatively easy to miss something.

**Comment by DocMAX** [comment]
Lots of tools have --quiet switch... so it seems to make sense to the people...

**Comment by adrianp-ro** [comment]
For those who may accept a workaround until this obvious issue is solved. I use it in a limited-resources device.
- Keep journal in (a limited) volatile memory (tmpfs - no /var/log/journal)
- Use rsyslogd to catch journal output
- Filter messages in /etc/rsyslog.d then save to /var/log/??? (may be on a different storage device!)
I use ReinerScript like "if ($app-name == '...' ) then stop"
or  "if ($msg contains '...') then ..."
I have a fair amount of details in journal and relevant info in saved log files.
For example one can prevent "...service: Succeeded" messages to pollute the 'real' log files.

N.B. I vote with two hands for an elegant and permanent resolution of this issue but until then...

**Comment by alexat** [comment]
I have socket-activated health check running on the machine contacted by 40 other machines around to do health checks (haproxy cluster). Pretty easy to guess, this causes 40 'Succeeded.' messages per second to appear in logs, a totally unnecessary clutter.

**Comment by alexat** [comment]
> For those who may accept a workaround until this obvious issue is solved. I use it in a limited-resources device.
> * Use rsyslogd to catch journal output
> * Filter messages in /etc/rsyslog.d then save to /var/log/??? (may be on a different storage device!)

Yeah, i.e. I filter it like that currently... but it still clutters the journal itself.

`
if ($programname == 'systemd') then {
  if ($msg startswith 'Started MySQL health check service') then {
    stop
  }
  if (re_match($msg,'^mysql_health\\@.+\\:\\s+Succeeded\\.$')) then {
    stop
  }
}
`

**Comment by krutztq** [comment]
+1 here, giving my vote for ability to suppress such messages.

I wanted to use a small service with a timer on an embedded device. It has a small small flash size and I have to keep an eye on wear leveling. I just want to suppress the start/stop messages of this special service to log only error messages of it.

For now I have to work around.

**Comment by rakafo** [comment]
I've recently started using systemd timers instead of cron, however in case where there are timers running in very frequent intervals, it inventively causes the log to fill up to default allocation limit and important information being dropped (in my case I get half a days worth of info, when the boot time is days).
It seems there's no official way to suppress it, a workaround being suggested is to just sleep inside the script which the .service calls, and while that would work, it also stops using .timer alltogether, which is akin to throwing the baby with the bathwater.

Would be great if there was a way to tweak this.

**Comment by gene1wood** [comment]
This feature was added in #19050 and is present in [systemd v249](https://github.com/systemd/systemd/releases/tag/v249) (see [changelog](https://github.com/systemd/systemd/blob/790096852738b4961ffd8b10664a67b3f075d612/NEWS#L2563-L2567)) available in, for example, [Ubuntu Jammy 22.04 LTS](https://packages.ubuntu.com/jammy/systemd)

> The LogLevelMax= setting of unit files now applies not only to log messages generated *by* the service, but also to log messages generated *about* the service by PID 1. To suppress logs concerning a specific service comprehensively, set this option to a high log level.

To use it to, for example, suppress the log lines from a frequently timer like this

> systemd[1]: Starting Clean php session files...
> systemd[1]: phpsessionclean.service: Succeeded.
> systemd[1]: Finished Clean php session files.

create a systemd override file, for example `/etc/systemd/system/phpsessionclean.service.d/override.conf` with contents like

```
[Service]
LogLevelMax=warning
```
