### ISSUE TITLE
libcap-dev needs to be a dependency

### ISSUE THREAD

**Issue by ecarew** [systemd/systemd#4931]
### Submission type

  - [x ] Bug report

### systemd version the issue has been seen with
commit 72d17ce680a22b958b4c074f62d9fa44bc1f54e0 

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution
Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see
Build failure due to missing dependency. In the READMD, libcap is mentioned as a dependency, but not libcap-dev.

### In case of bug report: Unexpected behaviour you saw

This caused the following error in configure:
configure: error: *** POSIX caps headers not found
makefile not built.

> …

### In case of bug report: Steps to reproduce the problem
run the recommended config command
> …

**Comment by poettering** [comment]
well, "libcap-dev" is how Debian names the development part of the upstream "libcap" package. Since we are agnostic to distributions (in fact, are fine even with systems where no distro is involved at all, but everything build from upstream), we do not make any reference to the distro-specific names or subpackages in our README, and I am pretty sure we shouldn't.

Sorry!
