### ISSUE TITLE
systemd: systemctl --list-unit-files failed with connection timeout

### ISSUE THREAD

**Issue by houstar** [systemd/systemd#4985]
### Submission type

  - [ *] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 219 or above

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> RHEL7.2

### In case of bug report: Expected behaviour you didn't see

> list all unit files

### In case of bug report: Unexpected behaviour you saw

> failed to list unit files: Connections

### In case of bug report: Steps to reproduce the problem

> 1. use virsh to create more than 1000 guests on RHEL7.2 hypervisor
   2. use systemctl --list-unit-files
    Failed to list unit files: Connection timeout

**Comment by poettering** [comment]
We do not track issues in such old systemd versions upstream. We only track issues within the two most recently released versions upstream

Moreover this is almost definitely https://bugs.freedesktop.org/show_bug.cgi?id=95263 again. Which is a D-Bus issue anyway, and not a systemd issue.

Closing.

**Comment by pauldraper** [comment]
> version-too-ancient

> the two most recently released versions

A hard requirement; means upgrading the init system every 2-3 months. 

In any case, still happens ten versions later (229).

```
$ sudo systemctl
Failed to list units: Connection timed out
$ sudo shutdown
Failed to set wall message, ignoring: Connection timed out
Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Connection timed out
```

**Comment by spacelama** [comment]
Indeed, a pointless and very systemd requirement.  Surprise surprise, the bug still exists 8 years later, because the bug is that systemd and/or dbus impose a hardcoded 25 second timeout that can't be changed, regardless of how slow your rapsberry pi is, and regardless of which particular systemd operation you're performing, and whether or not you care how long the process takes:

    > sudo time systemctl list-unit-files | head
    Failed to list unit files: Connection timed out
    
    real    0m25.073s
    user    0m0.011s
    sys     0m0.023s
    
    > sudo time systemctl list-unit-files | head
    Failed to list unit files: Connection timed out
    
    real    0m25.073s
    user    0m0.011s
    sys     0m0.023s
    
    > sudo time systemctl list-unit-files | head
    UNIT FILE                              STATE           PRESET
    proc-sys-fs-binfmt_misc.automount      static          -
    boot-firmware.mount                    generated       -
    dev-hugepages.mount                    static          -
    dev-mqueue.mount                       static          -
    proc-fs-nfsd.mount                     static          -
    proc-sys-fs-binfmt_misc.mount          disabled        disabled
    run-rpc_pipefs.mount                   generated       -
    sys-fs-fuse-connections.mount          static          -
    sys-kernel-config.mount                static          -
    
    real    0m22.364s
    user    0m0.038s
    sys     0m0.012s

**Comment by creaktive** [comment]
Thanks, @spacelama, your comment helped me to finally solve the issue that was nagging me for months! Turns out, there is another pitfall on Raspberry Pi devices: suppose you configured `RuntimeWatchdogSec=15s` (15s is the maximum on RPi4) in `/etc/systemd/system.conf`. However, running `systemctl list-unit-files` will block systemd for up to 25s, preventing it from pinging the watchdog device. So, instead of graciously timing out, you got BOOM! a forced reboot. And, to add insult to injury, `systemctl list-unit-files` is executed when stopping certain services. Therefore, instead of bringing down a stuck service, the whole system restarts (happened to me). Well, at least, it brings the system back to a usable state, even although awkwardly :)
