### ISSUE TITLE
Contributing Catalan translation

### ISSUE THREAD

**Issue by wagafo** [systemd/systemd#4998]
### Submission type

 - [ ] Request for enhancement (RFE)

[ca.zip](https://github.com/systemd/systemd/files/676784/ca.zip)
### systemd version the issue has been seen with

> systemd master

**Comment by poettering** [comment]
Unfortunately, we do not accept code contributions via zip files attached to github issues. Please file a proper GitHub Pull Request ("PR"), so that your submission gets automatically verified and tested before we review it and merge it.

Here's some documentation prepared by GitHub that explains how to do this:

https://help.github.com/articles/creating-a-pull-request/

Thank you very much for understanding!
