### ISSUE TITLE
60-evdev.hwdb Macbook5,1 match string not specific enough for MacbookPro7,1

### ISSUE THREAD

**Issue by varingst** [systemd/systemd#5079]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version / distribution

I use OpenRC on Gentoo. The package [sys-apps/hwids](https://github.com/gentoo/hwids#bug-reports) gets its hwdb files from systemd. The version on my system is old (telling me to report to bugs.freedesktop), but the section in question is the [same in master](https://github.com/systemd/systemd/blob/master/hwdb/60-evdev.hwdb#L53).

### Unexpected behaviour you saw

dmesg errors, `event9` is the builtin keyboard:
```
udevd[5226]: Unable to EVIOCGABS device "/dev/input/event9"
udevd[5226]: Unable to EVIOCGABS device "/dev/input/event9"
udevd[5226]: Unable to EVIOCGABS device "/dev/input/event9"
udevd[5226]: Unable to EVIOCGABS device "/dev/input/event9"
```

It tries to apply trackpad-specific properties to the keyboard, because the match string matches both:

In 60-evdev.hwdb:
```
# Macbook5,1 (unibody), aka wellspring3
evdev:input:b0003v05ACp0236*
evdev:input:b0003v05ACp0237*
evdev:input:b0003v05ACp0238*
 EVDEV_ABS_00=::92
 EVDEV_ABS_01=::90
 EVDEV_ABS_35=::92
 EVDEV_ABS_36=::90
```
On my MacbookPro7,1 (with a Norwegian "105"-key layout):
```
# keyboard
$ cat /sys$(udevadm info -q path /dev/input/event9)/../modalias
input:b0003v05ACp0237e0111-e0,.....
# trackpad
$ cat /sys$(udevadm info -q path /dev/input/event10)/../modalias
input:b0003v05ACp0237e0001-e0,.....
```

I fixed it to match the trackpad specifically on my own machine, but have no idea what other models this may apply to.

**Comment by poettering** [comment]
@whot ?

**Comment by whot** [comment]
yay, re-using USB product-IDs... couple of options, neither of them are great:

1. silence the warning or at least reduce it to something more obvious
1. change all the matches to include the version
1. make the hwdb use a touchpad: match instead of the plain input modalias

number 2  will  likely break things for existing users, I don't have access to all devices to do this reliably. number 3 introduces a dependency on ID_INPUT_TOUCHPAD, which given issue #5020 is not filling me with joy either. Number 1 is easy, you're still left with an error message but at least we can make it sound less bad ;)
