### ISSUE TITLE
TakeDevice method fails with 'Invalid argument' on seat1

### ISSUE THREAD

**Issue by muktupavels** [systemd/systemd#5095]
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

232-8

### Used distribution

Ubuntu 17.04

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

TakeDevice method fails with 'Invalid argument'.

### In case of bug report: Steps to reproduce the problem

I have pc with two nvidia cards:
seat0: /dev/dri/card0, major - 226, minor - 0
seat1: /dev/dri/card1, major - 226, minor - 1

gnome-shell starts on seat0, but fails to start on seat1. Full error message from mutter:
Can't initialize KMS backend: Could not open DRM device: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: Invalid argument

**Comment by poettering** [comment]
do you see anything in the logs of logind?

if you strace logind at the instant this bus call is done, do you see any syscall failing with EINVAL?

otherwise I am not sure what to propose. I can't debug this here. You'd have to gdb through logind on your system, to see where the EINVAL comes from. Attach to the running instance, set a breakpoint on method_take_device() and step through it, to see where the einval is generated.

**Comment by muktupavels** [comment]
EINVAL comes from session_device_open() -> open(). Any idea why open fails and/or how to debug it?

**Comment by poettering** [comment]
what's the device name that is attempted to be open()ed here?

if open() on the dri device node fails with EINVAL, then this suggests a kernel problem really, you'd have to ask the drm maintainers. @dvdhrm any idea?

**Comment by muktupavels** [comment]
"/dev/dri/card1" is name of device. Ok, this is not bug in systemd. Can you please tell me where to report this bug and/or search for help?

**Comment by poettering** [comment]
uh, no idea where to reach the DRM maintainers upstream. I am sure they have some mailing list or so... To my knowledge @dvdhrm is a maintainer there now, maybe he can comment?

Anyway, closing this here.
