### ISSUE TITLE
systemd-veritysetup-generator failed with error code 127

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#5096]
With recent git, on a VM with GPT partition table, no verity configuration:
```
[   11.579100] rawhide systemd[1]: Set hostname to <rawhide>.
[   11.580545] rawhide systemd[901]: /usr/lib/systemd/system-generators/systemd-veritysetup-generator failed with error code 127.
```

**Comment by poettering** [comment]
uh... this sounds really strange. The tool will either exit with 0, or 1, but never with 127. If this dies with 127, then something must be very wrong, something is calling exit() and really shouldn't.

Here's my educated guess: maybe this is generated from the initrd, and dracut missed some library dependency of this tool, and it's actually the dynamic loader that generates the exit code, because it can't find it?

Is this in the initrd? Can you run the tool by hand in the initrd, does it work there? Can you reproduce this on the host when invoking this directly?

**Comment by poettering** [comment]
@keszybz hmm, if this is not reproducible I think we should close the bug until someone can in which case we can reopen it...

**Comment by keszybz** [comment]
Yeah, I meant to close it. Must have pushed the wrong button.

**Comment by dtardon** [comment]
FTR, I just debugged a similar issue happening during an update in RHEL and it turned out to be caused by a version mismatch. A function from `shared` was changed to an inline wrapper, hence the symbol was dropped from `libsystemd-shared-XYZ.so`. As a result, some generators from `systemd-udev` package (still at old version) failed when systemd was reexec'd in `systemd` package's `%post`.

**Comment by keszybz** [comment]
Hmm, I guess it's time to finally move the reexec to `%posttrans`. We've had a TODO entry since 2021 for this. But that's a downstream issue.

**Comment by poettering** [comment]
hmm, maybe insert the full rpm NVR into the XYZ of the libsystemd-shared-XYZ.so name? would avoid such issues

**Comment by keszybz** [comment]
It would avoid *some*, but not all. E.g. let's say that we remove or rename a generator. Then if we reexec too early, we'll execute the unwanted old binary. A much cleaner solution is to wait until the old package has been removed and we're in the fresh new filesystem state. We do unit restart in a transaction trigger, so we should do the same with daemon-reexec.

**Comment by keszybz** [comment]
→ https://src.fedoraproject.org/rpms/systemd/pull-request/132
