### ISSUE TITLE
(Re?) Enable the use of service names in addition to port numbers (ref. "getservbyname")

### ISSUE THREAD

**Issue by hhucke** [systemd/systemd#5108]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Ubuntu xenial (16.04)

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …

### Description of Request For Enhancement

It is common use to allow the use of service names ("http", "ssh", "ipp", "who", etc pp) where service port numbers (80/tcp, 22/tcp, 631/tcp, 513/udp, etc pp) have to be specified. As far as I can see this is not possible with systemd.

**Comment by poettering** [comment]
Hmm, so, we generally avoid calling into NSS (the glibc name service switch, i.e. the getXbyY() calls and related calls), as they can block and we can't have that in PID 1.

Moreover I am not convinced that this API is really such a good anyway, the services database is kinda a historic artifact, I doubt the extra indirection is really a good idea and helps the user. Moreover, I am pretty sure very few people actually make use of it IRL... (I mean, it took five years since systemd's inception until this bug here was filed).

I am also concerned about mandated /etc/services to be around, by making use of the database. I mean, if you ask me the database should really never have existed anyway, and I think a lean system should probably just do away with it...

Hence, I am sorry, but I don't think we should add this. Not only is it technically very complex to support this (as we have to fork off a helper process for the lookup so that we don't have to block on the NSS call), but also semantically not clearly an advantage.

I hope this makes some sense. I hope it's OK if I close this bug. Sorry!

**Comment by hhucke** [comment]
Lennart and Team,

please keep in mind that _not only very big hosting environment_ for micro services need to be considered but **also** office, small and medium scale environments. And at least for office and small environments my twenty years of experience taught me that its often enough helpful to specify (additional) service ports via name service and configure ports via names where possible.
