### ISSUE TITLE
systemd 233 breaks luks-encrypted root device

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#5178]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 233 (current git HEAD)

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> exherbo

### In case of bug report: Expected behaviour you didn't see

> dracut should ask for my "btrpool" root device password, decrypt it and use it (works fine with systemd 232)

### In case of bug report: Unexpected behaviour you saw

> dracut asks for a non existant "root" device password, then for the correct "btrpool" password, and boot fails

### In case of bug report: Steps to reproduce the problem

> update from systemd 232 to current git HEAD and regenerate initrd

**Comment by poettering** [comment]
we need more info than this. what does "boot fails" mean? can you provide error messages? log output? anything?

**Comment by Keruspe** [comment]
It's quite hard to get the logs as I'm not dropped to an emergency shell when this happens.

If I understand correctly:
- systemd-cryptsetup asks for my passphrase either for "root" or "btrpool" (the order vary) and then opens it
- systemd-cryptsetup asks for my passphrase for "root" or "btrpool" depending on the one it opened before
- the open fails as both "root" and "btrpool" are the same device, thus the dependencies to mount the real root are not satisfied as systemd put both the volumes there, and it just stops there with "dependency failed for /sysroot, Initrd Root File System, etc.

With systemd 232, btrpool gets opened sucessfully and then sysroot is mounted correctly according to crypttab and fstab

**Comment by poettering** [comment]
hmm, so are you using the root partition uuid listed here?

https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/

if so, you enabled that systemd should discover the partition for you, and place it under the "root" DM device. This has been documented since forever, actually, even though the implementation for it was only recently added.

It's fine to ship your own crypttab info that overrides what the GPT auto discovery finds, but you still have to match the device name, i.e. call it "root", so that you properly override the GPT auto discovery.

So, if you do use these GPT part types, then I'd claim this is simply a local config error, and chaning btrpool → root should fix the issue. If you however use other GPT part types, then this would really be a bug...

**Comment by Keruspe** [comment]
Heh, it looks like I did set that uuid at some point indeed.

Now if I just declare it as a regular partition it doesn't boot complaining about gpt-auto-root not existing and if I rename it to root it still tries to so something with a now nonexistant btrpool, but that seems to be a dracut problem, thus closing
