### ISSUE TITLE
journalctl --since cannot parse ISO8601

### ISSUE THREAD

**Issue by ashb** [systemd/systemd#5194]
I had a service logging it's own timestamps in ISO8601 and copied that and tried to use it like this:

```
# journalctl --since 2017-01-30T16:04:01.498138595Z
Failed to parse timestamp: 2017-01-30T16:04:01.498138595Z
```

It would be nice if the only sensible datetime format was natively supported :)

**Comment by poettering** [comment]
I am not sure it's that sensible. We deliberately opted for a different native format we output and parse, since the "T" and "Z" stuff is hardly friendly for humans to read...

Anyway, we probably could permit enough redundancy so that we also parse ISO times...

**Comment by arvidjaar** [comment]
> since the "T" and "Z" stuff is hardly friendly for humans to read

My use case would be

```
START=$(date --iso-8601=ns)
do something
journalctl --since="$START"
```
Not so much for human consumption but for scripting.

**Comment by poettering** [comment]
If that's what you want to do, my recommendation would be this:

```
START=$(date +%s)
do something
journalctl --since=@$START
```

This is generally the better option anyway, as it avoids confusion around daylight saving (as during the daylight saving switch the same calendar hour happens twice, leaving an ambiguity which precise point in time you meant). Converting to calendar time for any other use than human readability is always a poor choice, especially on UNIX where a generally accepted linear timescale exists.

**Comment by arvidjaar** [comment]
> `journalctl --since=@$START`

Ah, thanks! Missed it in manual.

**Comment by poettering** [comment]
that `@` syntax wasn't invented by us btw, the coreutils "date" tool supports that too.

**Comment by rmunn** [comment]
I'd also like to see `--since` and `--until` accept ISO8601 format: there is no daylight-savings time ambiguity as long as a time zone is specified (either as an offset from UTC, or as "Z" indicating UTC). E.g., when daylight savings time ends this year in New York City, the time will go from `2017-11-05T01:59:59-0400` to `2017-11-05T01:00:00-0500`.

A daylight-savings-time ambiguity can only exist if the time zone is not specified. Granted, that's going to happen sooner or later, since most people get lazy about that. But there are a few ways that this ambiguity could be dealt with:

1. If no timezone is specified, assume the user means local time (unless, of course, the `--utc` option was also passed on the command line, in which case consider the timestamp as having been specified in UTC). If this results in an ambiguity (or a completely invalid time, e.g., 1:30 AM during a "spring forward" date), print a warning to that effect, and then adjust the requested time as follows:
    * In the case of `--since`, use the *earlier* of the two ambiguous times. Or if the time specified is a "skipped" time during a "spring forward" adjustment, convert the requested time to the second (or milli/micro/nanosecond) immediately *before* the skip. (The precision would match whatever precision the user specified in their input timestamp.)
    * In the case of `--until`, use the *later* of the two ambiguous times. Or if the time specified is a "skipped" time during a "spring forward" adjustment, convert the requested time to the second (or milli/micro/nanosecond) immediately *after* the skip. (The precision would match whatever precision the user specified in their input timestamp.)
    * The guiding principle here is to resolve the ambiguity in the direction that results in the *most* output.
    * A warning should probably be printed to stderr, saying "Time zone not specified, assuming (offset)", whether or not the specified date/time was ambiguous. That way the user is put on notice that their input was incorrectly formatted.

1. If no timezone is specified, output (to stderr) an explicit "WARNING: no time zone specified in `--since`, assuming UTC", then proceed as if a UTC time was specified (UTC cannot be ambiguous). This may not be what the user thought they were typing in, but it will teach them the necessity of specifying timezones, and they'll at least get some output (if not the output they were expecting).

1. If no timezone is specified, reject the timestamp as invalid, and produce an error message and no log output.

Of those three options, I prefer the first, since it's most in accordance with Postel's Law.

**Comment by wwalker** [comment]
+1  I'd love something of the %Y-%m-%d %H:%M:%S form

**Comment by wwalker** [comment]
Also, most of the issues that rmunn is talking about (time zone things) are already in journalctl because "03:15" doesn't have a time zone either.

**Comment by k1tzu** [comment]
Just run into the issue. I have events collected from different servers in different timezones. So I save them in ISO. And now I logged in to server to analyse an issue more precise and did "journalctl --since 2018-05-19T11:00:01.000Z" without luck.

**Comment by erikarvstedt** [comment]
For scripting, better use µs accuracy (`date +%s.%6N`):
```
START=$(date +%s.%6N)
#do something
journalctl --since=@$START
```

**Comment by dvska** [comment]
`journalctl -n500 -u my.service --since="2018-11-26 07:42:53.415778" -p 3 -o json --no-pager --utc`
works @ systemd versions 237, 239,


while systemd v.219 (CentOS 7) fails with 
`Failed to parse timestamp: 2018-11-26 07:42:53.415778`

**Comment by ypid** [comment]
I opened https://github.com/systemd/systemd/issues/14515 which is related to this issue.

**Comment by marc-h38** [comment]
> my recommendation would be this: START=$(date +%s)

It works but +%s is not human readable at all.

I don't understand why human readable and parsable are considered mutually exclusive. "Programs must be written for people to read, and only incidentally for machines to execute."
`date --iso-8601=seconds` and `date --rfc-3339=seconds` are both readable and parsable with no timezone or daylight savings ambiguity. People who did these standards had some idea of what they were doing.

OK, maybe the "_best_ readable" format for systemd `output` shouldn't be parsable but `--since` isn't about that, it's about scripting. 

> 3. If no timezone is specified, reject the timestamp as invalid, and produce an error message and no log output.

KISS. Otherwise you end up with daylight savings bug open for 10 years: https://bugs.mysql.com/bug.php?id=50658

> Of those three options, I prefer the first, since it's most in accordance with Postel's Law.

https://en.wikipedia.org/wiki/Robustness_principle#Criticism

**Comment by nickbroon** [comment]
https://github.com/danos/vyatta-log/blob/master/rfc3339_to_systemd_time/rfc3339_to_systemd_time.py

Is a wrapper around journalctl that accept rfc3339 format timestamps for --since and --until and converts them to something journal understands.

**Comment by poettering** [comment]
as I mentioned already in my first comment, I am happy to review/merge a patch that makes the code accept iso timestamps in addition to what it already accepts. I am just not convinced that ISO timestamps are a good fit for humans to read, i.e. not suitable as default output choice.

Anyway, please send a patch that tweaks the parser, and python scripting around it is not necessary...

**Comment by nickbroon** [comment]
I agree that systemd natively supporting parsing rfc3339 timestamps as input would be preferable. And also agree that it should not be a default output choice.

Writing this function:

``` python
def rfc3339_to_systemd_time(rfc3339_time: str) -> str:
    """Convert a rfc3339 timstamp into systemd.time timstamp"""
    _date_obj = iso8601.parse_date(rfc3339_time)
    _date_utc = _date_obj.astimezone(pytz.utc)
    _date_utc_zformat = _date_utc.strftime('%Y-%m-%d %H:%M:%S.%f UTC')
    return _date_utc_zformat
```

seemed a lot easier than attempting to understand https://github.com/systemd/systemd/blob/master/src/basic/time-util.c#L812:1 and extending it also support rfc3339.

I'll leave that to others more familiar with the systemd time parser and motivated to do so. :-)

**Comment by leolchat** [comment]
I personally keep having to copy a date from journalctl output, and feed it back to journalctl `--since` option (first quick glance like with `-p warning` then deeper dive). Currently I have to edit every time I paste the date...
I need to use microseconds, so there are only 3 outputs which provides it:
- `-o short-iso-precise`
- `-o short-precise`
- `-o short-unix`
and only the unix version can be fed back to `--since`, which is really sad since it is the less readable for humans.

`short-iso-precise` would be nice, `short-precise` even nicer since it is the most human readable.

If it is a concern that parsing generic dates is tricky/ambiguous, maybe only accepting to parse those when the `-o` is set accordingly, or have a `-i` option for specifying input format?

**Comment by dvanders** [comment]
How about supporting any date parseable by `date -d`? e.g.
```
# date -d '2021-02-11T11:11:11GMT'
Thu Feb 11 12:11:11 CET 2021
# date -d 'Feb 11'
Thu Feb 11 00:00:00 CET 2021
# date -d 'Feb 11 2020'
Tue Feb 11 00:00:00 CET 2020
# date -d '2021/02/11'
Thu Feb 11 00:00:00 CET 2021
```

**Comment by yrro** [comment]
ISO 8601 also allows durations to be specified. So `journalctl --since=P3D1H` would be nice (equivalent to `1 day 3 hour ago`).

**Comment by arvidjaar** [comment]
> So journalctl --since=P3D1H would be nice (equivalent to 1 day 3 hour ago).

If I read ISO 8601 correctly then

1. This duration specification is incorrect. It should be `P3DT1H`
2. It means `3 days 1 hour ago`
3. `1 day 3 hour ago` would be `P1DT3H`
