### ISSUE TITLE
[Section] headers should be case insensitive

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#5208]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

> well, networkd doesn't uppercase this on its own

https://github.com/systemd/systemd/issues/5205#issuecomment-276925994

It appears systemd itself does. But networkd should tolerate case differences in headers.

**Comment by poettering** [comment]
Humpf. I am pretty sure we shouldn't start being case-insensitive on this. On UNIX, files and directories, environment variables, all these things are case sensitive. The shell is, C is, everything. I am pretty sure we shouldn't start being case-insensitive in systemd, for one isolated concept (the section headers).

quite frankly, I am sure that for most folks this would be quite surprising even, as we'd be the one exception there.

Case insensitive comparison is also extremely difficult if you want to do it right, due to the special semantics this involves as soon as you throw i18n into the mix. Collation is hard, and I am pretty sure I want to stay away from it.

Sorry, but I think this would be a bad choice! i will close this now. I hope this makes sense!

**Comment by mixmastamyk** [comment]
The problem seems to be not that headers/keys are case-sensitive, but that they are MixedCase instead of lower case---making them difficult to get just right without cutting and pasting.  

One reason everything tends to be lower-case in UNIX is _because_ it is case sensitive.

But, that ship has sailed, no?

**Comment by poettering** [comment]
> One reason everything tends to be lower-case in UNIX is because it is case sensitive.

Is that so? Not the UNIX I know. If I look around in my systemd source tree I see "Makefile" for example... And the X binary is called "X" traditionally, and not "x"... And that just from the top of my head...

> But, that ship has sailed, no?

Yes it has.

**Comment by mixmastamyk** [comment]
Things that need to be typed are lowercase in Unix:

```
    > /bin/ls /
    bin   cdrom  dev  home        vmlinuz  lib64       media  opt   root  sbin  srv	tmp  var
    boot  core   etc  initrd.img  lib      lost+found  mnt    proc  run   snap  sys	usr  
```

Things meant to be viewed primarily sometimes have mixed case for reasons of readability, but the corresponding part that needs to be typed frequently is usually lower case as well:

- Makefile --> make
- X --> startx

An example of an easier to compose ini (without error) file is here:  http://supervisord.org/configuration.html.  Upstart got this part right as well, though of course it has other limitations.

I understand, it is very hard to get platform interfaces just right, due to them practically being set in stone on their first release.

**Comment by poettering** [comment]
@mixmastamyk well, I happen to think that the unit file format while not perfect is actually nicer than the supervisord format, simply because it's less cryptic and brief ("chmod"…)

But ultimately this is really just bikeshedding at this point, I don't think we'll get into agreement here, and it's too late to change this anyway...

(And if I'd start another project again today, I am pretty sure I'd reuse an ini-file-like config file format again, with similar syntax as unit files...)
