### ISSUE TITLE
network: Propagate DNS server information via DHCP FORCERENEW

### ISSUE THREAD

**Issue by derekstavis** [systemd/systemd#521]
The following `enp2s0.network` file allows us to create a rudimentary NAT:

```
[Match]
Name=enp2s0

[Network]
IPMasquerade=yes
Address=172.16.0.1/16
DHCPServer=yes
```

As far as I know, `DHCPServer` feature was designed for containers use-case, where DNS-related stuff can be handed to standard `resolv.conf` mechanism. Thinking outside this use-case, it would be great to implement DNS integration in DHCP server, so physical clients also acquire DNS addresses.

I'd be happy to contribute building this feature, but we might discuss the best strategy for implementing it.

**Comment by poettering** [comment]
Yes, we'd like a logic that can propagate DNS server information from the host to clients to its dhcp server. This would require a number of changes:
- when putting together the dhcp lease we should add all DNS servers configured on all other links.
- we need to implement dhcp service-side FORCERENEW stuff, so that the dhcp server can let the client know that things changed, whenever we learn or lose a dns server. (rfc3203)
- we need to implement the dhcp client-side of the FORCERENEW stuff, so that networkd as client acts properly on it.
- we need to actually hook up the FORCERENEW events on the server side with dns servers learnt and lost.

iirc we'd have to implement FORCERENEW slight different than the RFC says, and not strictly require authentication for it.

I think @teg looked into this once, not sure what the latest on it is, Tom?

**Comment by teg** [comment]
The client already supports this, and the server library does too (but it is not hooked up). We just need to push the info into the server at runtime (rather than just when starting the server) and then trigger the FORCERENEW with sd_dhcp_server_forcerenew() once something changed. We may want to make the client support for this optional as discussed, currently it is unconditionally enabled.

**Comment by derekstavis** [comment]
Looks like this functionality have been merged in #1055 with `EmitDNS=` directive. Thanks @poettering :+1:

**Comment by poettering** [comment]
@derekstavis the functionality in #1055 does not refresh the client's lease data via FORCERENEW when the propagated data changes. That's still left to do. With the new logic you might have to lower the lease time to get somewhat "live" propagation of uplink metadata into place.

**Comment by ssahani** [comment]
It's implemented . Let's close this. https://github.com/systemd/systemd/pull/14904

**Comment by derekstavis** [comment]
Thank you for working on it!
