### ISSUE TITLE
impossible shutdown

### ISSUE THREAD

**Issue by frpatte2** [systemd/systemd#5244]
### Submission type

  - [ x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

>fedora 25

### In case of bug report: Expected behaviour you didn't see

> complete shutdown 

### In case of bug report: Unexpected behaviour you saw

> At shutdown request, screen turns black and computer does not stop untill power button is pressed

### In case of bug report: Steps to reproduce the problem

> shutdown
[files.zip](https://github.com/systemd/systemd/files/754950/files.zip)

[Uploading files.zip…]()

**Comment by poettering** [comment]
The logs you append indicate that systemd managed to run the binaries included in /usr/lib/systemd/system-shutdown. This happens very late during boot. After that the only thing system still does is either call reboot() or pass control back to the initrd (if one is used and set up for that). Since you are using Fedora, it appears that the latter is the case and hangs for you. Either way, systemd is not in control at that point anymore. Hence, please contact the dracut folks about this, we can't help you!

Sorry!
