### ISSUE TITLE
Dell XPS L702X 3 touch keys

### ISSUE THREAD

**Issue by fawtytoo** [systemd/systemd#5341]
This is a bug report.

The Dell XPS 17 L702X has 3 touch keys to the right of the power button.
Key 1 -> Super_L + Q
Key 2 -> Brightness Down
Key 3 -> Doesn't seem to do anything and xev doesn't report any key codes

Other Dell XPS models have the same keys and the same issue.

I created /lib/udev/hwdb.d/70-keyboard.hwdb:
```
# Dell XPS L702x
evdev:atkbd:dmi:bvnDellInc.:bvrA19:bd09/07/2012:svnDellInc.:pnDellSystemXPSL702X:pvr:rvnDellInc.:rn03RG89:rvrFAB1:cvnDellInc.:ct8:cvr0.1:
 KEYBOARD_KEY_84=scale
 KEYBOARD_KEY_85=cyclewindows
```
This at least allows the 3 keys to be usable as shortcuts.

The prefix of the udev: line is specific to my laptop model. I have no idea how to make a rule for it, or make it more general to other XPS models.

This occurs with systemd versions up to 232-14 (Debian Stretch).

**Comment by poettering** [comment]
@martinpitt somethong for you?

**Comment by poettering** [comment]
@phenest btw, if you have a patch for this, could you please file it as proper PR?

**Comment by martinpitt** [comment]
One of the best pictures that I've found is https://cnet4.cbsistatic.com/img/ae5l7n4bB0nD8tMgalTI4CiEn_g=/830x467/2011/06/28/9cdf5cdc-67c3-11e3-a665-14feb5ca9861/34669850_TP.JPG

But it's still unclear what they are supposed to do. The leftmost one could be a large and a small cog, so maybe something like "settings", which we commonly assign to `KEY_PROG1` (so that users can assign it to something useful in GNOME keyboard settings or similar).

The second one looks like a 3D coordinate system, is that the one you assigned "scale" to? And the third one like a big "W". Does that come with any documentation what they are supposed to do? Do you know what they do under Windows? (I tried to Google, but didn't find anything). I wouldn't like to assign random unrelated functionality to these, like "cyclewindows". Just generic ones like prog1/2/3 seem okay, so that they explicitly stay available for user mapping?

**Comment by phenest** [comment]
I've since sold my XPS and couldn't remember what they did in Windows, but I found someone on eBay selling one who described them.
From the left:
The 1st one (the 2 "cogs") provides access to a control panel.
The 2nd one is for audio settings.
The 3rd one is meant to be programmable, that is, set to any application of the users choice.

**Comment by poettering** [comment]
OK, let's close this, as there's little we can do without a patch and given that @phenest doesn't have the laptop anymore we couldn't test this either
