### ISSUE TITLE
Don't require a terminal as an argument for systemd-vconsole-setup

### ISSUE THREAD

**Issue by abbradar** [systemd/systemd#5367]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232

### Used distribution

> NixOS Unstable pre-17.03

`systemd-vconsole-setup` currently requires a "main terminal" as an argument, defaulting to `/dev/tty0`. It tries to set the settings there and only if it works proceeds to applying them for all the other terminals.

I propose instead to just loop over all the terminals and try to set settings for all of them. Current behavior is difficult to deal with: you can't restart the service from X11 (it would fail because `/dev/tty0` in this case would be the terminal controlled by X). You can override the service to use some other terminal (for example `/dev/tty1` or `/dev/tty2`) but this seems flaky because you don't know what terminals are currently owned by X or other kinds of graphical servers.

See https://github.com/NixOS/nixpkgs/issues/22470 for corresponding bug in NixOS. We currently want to workaround this by specifying `/dev/tty1` as the "master" terminal (we have X on `tty7`) but because of reasons described above it's not ideal (for example I have plans to try and move us to X-on-`/dev/tty1` somewhere in the future :D).

**Comment by abbradar** [comment]
By the way, since I'm reporting on `systemd-vconsole-setup`; we currently add those to the service:
```
Before=display-manager.service
After=systemd-udev-settle.service
```
The first unit is our distribution-provided one (that starts display manager of choice) but the second can be moved to upstream, I think. This is needed because udev may load video drivers which then change the resolution and fonts/keymaps on tty become messed up.

**Comment by poettering** [comment]
udev-settle has no place in a clean boot. it's a legacy concept, a work-around for software that is crappy enough to assume that there's a point in time at boot where "all devices have shown up".

**Comment by abbradar** [comment]
Is there any better unit to wait for then, or it needs to be fixed in `systemd-vconsole-setup` itself?

**Comment by keszybz** [comment]
@msoltyspl Now you're the person who understands this best... What do you think?

**Comment by msoltyspl** [comment]
Yea, the bug report seems correct. Out of my head ideas would be:

a) add setting in vconsole.conf that lets user / distro set specific console (which they know won't have X running on it and will be otherwise in sensible state for setting fonts on it)

b) same as a) - but just do it automatically if tty0 is unusable

**Comment by keszybz** [comment]
b) sounds much better. Should we just loop over all terminals until we don't hit an error? Would that work?

**Comment by msoltyspl** [comment]
Yes - we set all possible terminals either way - so which one of those is initially used as a "reference" one is not really relevant.

Ok to prep patch for it ?

**Comment by keszybz** [comment]
Yes, please!

**Comment by msoltyspl** [comment]
Uhh, sorry for long delay. This I think should fix the issues mentioned this bugreport. (https://github.com/msoltyspl/systemd/commit/375b4881fcccb7f5c2cee15f20eb2cd5c9ebd64c is the only commit, earlier ones auto referenced here are obsolete).

**Comment by msoltyspl** [comment]
Updated the code, so there is no more pointer to static array and the all the functions follow -errno or >= 0 (separate commit corrected few other functions that returned bool)

**Comment by msoltyspl** [comment]
- is_settable() adjusted to return -EBUSY (if console is accessible but not in xlate/unicode) instead of somewhat cumbersome 0; so now it can be used as any other function (and EBUSY seems to be the most logical error code) 
- find_source_vc split into test_source_vc() and find_source_vc() 
- if the whole loop fails, most recent error is returned from the last iteration (should be most useful for the user)
- small things fixed as per Lennart's review

**Comment by msoltyspl** [comment]
Further corrections are per Zbignew's comments.

**Comment by rnhmjoj** [comment]
> udev-settle has no place in a clean boot. it's a legacy concept, a work-around for software that is crappy enough to assume that there's a point in time at boot where "all devices have shown up".

So, what is the right dependency to use instead? I'd like to get rid of it.

**Comment by poettering** [comment]
@rnhmjoj none. Wait for exactly the devices you need. Either via systemd .device units or by listening to udev or rtnetlink yourself in your program code.

**Comment by rnhmjoj** [comment]
Sorry, I should have been clearer: I'm not asking in general, but for systemd-vconsole-setup itself. 
I'm trying to remove all references of udev-settle from NixOS unit files because, as you say, it's a hack.
Apparently there used to be an issue where the console would break after mode setting, so udev-settle was used as a workaround. I have never seen this issue myself, so it's possible it has been fixed and the hack can be removed.

**Comment by rnhmjoj** [comment]
Looks like it: systemd-vconsole-setup is started by udev itself in `90-vconsole.rules` and the service is not even installed anymore.
