### ISSUE TITLE
/etc/resolv.conf is a broken symlink on systems with systemd-resolved disabled

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#5395]
Hi,

When systemd-resolved is built but disabled by default, systemd-tmpfiles creates a symlink /etc/resolv.conf which points to /usr/lib/systemd/resolv.conf. This symlink is created early during boot usually before any network service.

But the symlink confuses tools which are supposed to create resolv.conf and to deal with the network config as the symlink already exists.

There was a similar bug opened here https://bugzilla.redhat.com/show_bug.cgi?id=1313085 which was fixed by http://pkgs.fedoraproject.org/cgit/rpms/systemd.git/tree/0998-resolved-create-etc-resolv.conf-symlink-at-runtime.patch.

I'm not sure to understand why the fix doesn't apply to upstream though.

**Comment by poettering** [comment]
We are creating the symlink if it the file doesn't exist at all. This is a fallback thing at most, and it will only become effective as last resort if nothing else wanted to take possession of the file.

The fedora patch is a work-around, I really don#t like that it has been added to Fedora I must say. Please just fix your software that is supposed to own /etc/resolv.conf to do so properly, maybe at install time or start-up time, or anything else.

The tmpfiles snippet exists primarily to make non-populated /etc work, if nothing else is configured.

**Comment by poettering** [comment]
(Also, changes to /etc at runtime from anything but config mgmt tools are kinda broken anyway, and the fedora hack won#t work as soon as #5283 is merged anyway.)

**Comment by fbuihuu** [comment]
> Please just fix your software that is supposed to own /etc/resolv.conf to do so properly, maybe at install time or start-up time, or anything else.

How does a software is supposed to own /etc/resolv.conf at start-up time if systemd-tmpfiles already created it (even if systemd-resolved is disabled ) ?

Also please consider the following use case:  sysadmin removes /etc/resolv.conf, reboots and expects that resolv.conf is recreated/repopulated by the software managing the network. How can it work if resolved is not used ?

> The tmpfiles snippet exists primarily to make non-populated /etc work, if nothing else is configured.

Isn't the (enabled) network software supposed to handle that instead ?

**Comment by poettering** [comment]
> How does a software is supposed to own /etc/resolv.conf at start-up time if systemd-tmpfiles already created it (even if systemd-resolved is disabled ) ?

Well, who owns it is a distro decision as only one software can sanely own it: make sure you set up the symlink in your installer, or RPM script or something like that. The tmpfiles thing is really just the fallback if noone does anything like that, since there's a good chance that having the symlink point to resolved's version is still better than having no symlink at all. Note again, resolved/tmpfiles won't interfere with any existing link or file, it will just add the symlink if your installer/distro forgot to set something up there.

You can even create the symlink with your own tmpfiles snippet, just order it before the one that creates resolved's symlink. 

If your distro/installer doesn#t create the symlink at install time it's not really compatible with setups where the root distro is read-only, as in that case creating the link after installation isn't possible anymore anyway...

**Comment by poettering** [comment]
> Also please consider the following use case: sysadmin removes /etc/resolv.conf, reboots and expects that resolv.conf is recreated/repopulated by the software managing the network. How can it work if resolved is not used ?

That's a strange expectation I would say. I mean, it's fine if you expect that, but it's not really systemd's job to make that work. If you want the link to point somewhere else, then make that happen, and create it during early-boot, possibly even via tmpfiles...

**Comment by poettering** [comment]
> Isn't the (enabled) network software supposed to handle that instead ?

Well, if it is, why doesn't it do that? then? it could easily drop in its own tmpfiles snippet...

**Comment by fbuihuu** [comment]
> Well, if it is, why doesn't it do that? then? it could easily drop in its own tmpfiles snippet...

I don't really see the point to rely on tmpfiles to (re)create /etc/resolv.conf.

This seems cleaner if the software deals with the initialization of resolv.conf directly during its start-up (as it's done by the "hack" carried by Fedora) than relying on a tmpfiles snippet and easier to deal with the example given previously or the following one : `rm -f /etc/resolv.conf; systemctl restart NetworkManager.service`

**Comment by poettering** [comment]
> I don't really see the point to rely on tmpfiles to (re)create /etc/resolv.conf.

Well, you really don't have to use tmpfiles. You can use anything. again: the resolved tmpfiles snippet won't override what is in place, just make sure you create the symlink at the right time, so that during the entire runtime of the system it is in place. 

if you want nm to take possesion of the symlink, then ship the symlink in the nm rpm, or drop in a tmpfiles snippet, or create the link early enough in some package specific tool, or create it during install time, it's entirely up to you, what is best...

And I figure we have to agree to disagree, I don#t think it's cleaner if resolved writes around in /etc. It should never do that. In fact, that's explicitly what #5283 is about: making sure we never do that, to tighten security.

**Comment by fbuihuu** [comment]
On 02/20/2017 06:02 PM, Lennart Poettering wrote:
> 
> if you want nm to take possesion of the symlink, then ship the symlink
> in the nm rpm, or drop in a tmpfiles snippet, or create the link early
> enough in some package specific tool, or create it during install time,
> it's entirely up to you, what is best...
> 
> And I figure we have to agree to disagree, I don#t think it's cleaner if
> resolved writes around in /etc. It should never do that. In fact, that's
> explicitly what #5283 <https://github.com/systemd/systemd/pull/5283> is
> about: making sure we never do that, to tighten security.
> 

I can see the point in forbidding resolved to write around in /etc.

However making resolved (or any other network software) relying on
another tool to init /etc/resolv.conf at early boot sounds odd:  the
software when started directly (not via a service) will just fail if
resolv.conf is not present.

Or you can't simply switch from one software to another one by
enabling/disabling them, you now need to use another tool.

Maybe (if doable) ReadWritePaths=/etc/resolv.conf ...

**Comment by poettering** [comment]
> However making resolved (or any other network software) relying on another tool to init /etc/resolv.conf at early boot sounds odd: the software when started directly (not via a service) will just fail if resolv.conf is not present.

I don't understand? resolved works fine without /etc/resolv.conf in place as long as nss-resolved is hooked into /etc/nsswitch.conf

**Comment by pemensik** [comment]
I think there is error in packaging. ``/usr/lib/tmpfiles.d/etc.conf`` contains line:
```
L! /etc/resolv.conf - - - - ../run/systemd/resolve/stub-resolv.conf
```
This file is part of systemd package on Fedora 35, which seems wrong. I spent some time checking what created dangling symlink. This instruction should be part of systemd-resolved package, not systemd. It creates dangling symlink both in cases when systemd-resolved is disabled and uninstalled. Prevents for example _dhcpcd_ from creating proper /etc/resolv.conf file, because symlink exists. But target does not.

It seems to me this link should be created maybe as pre-exec of systemd-resolved.service. Without it started, it does not do anything useful. Can it be removed from tmpfiles and moved to related service startup?

**Comment by bughunter2** [comment]
If /etc/resolv.conf exists, systemd will not touch it and therefore won't create the dangling symlink. Good.

However, a case can be made for a tiny behavioral change. For example, when one is debugging issues, one may want to disable systemd-resolved temporarily. When one is debugging an issue it would be very helpful if systemd was smart enough NOT to create a dangling symlink that will stay a dangling symlink. And let's be honest, debugging is like juggling, one needs to hold a lot of context in mind. Fixing this in systemd would be very helpful.

A fix would be relatively easy on the systemd side: only create the /etc/resolv.conf symlink if and only if systemd-resolved is enabled and /etc/resolv.conf does not yet exist. In all other cases, don't touch it. This is only a tiny change in behavior, but makes life easier for everyone. After all, only in that case systemd can actually assume that it's safe to create the dangling symlink, because only in this case systemd can be sure that it will soon become a working symlink once systemd-resolved is started.

Thanks in advance!
