### ISSUE TITLE
Add Instance regex check

### ISSUE THREAD

**Issue by RoiEXLab** [systemd/systemd#5450]
A problem I came across recently:
Instances are great! They enable you to reuse a single service file for many services.
But let's say we want %i to match a special requirement, let's say we want %i to be a number between 00 and 99 with a leading 0 for 0-9, because without this 0 some things will go wrong.
Regex could be the solution.
If you added another field like `InstanceRegexReq` we could add our own regex which we would require to successfully launch our service.
Of course we could validate the arguments inside our launch script, but this would make it seem like the script is broken since the user isn't getting an instant message...

**Comment by poettering** [comment]
I am not convinced we need something like this natively. regexes on instance names are just one way how people might want to check things before a unit starts, and I really don't see why we should treat them speical and support them natively.

note that there are already mechanisms to make available what you are looking for. Specifically:

1. you can do such validation before invoking "systemctl start", on the client side, in a shell script or suchlike, and then simply invoke the shell script instead of the "systemctl start" command directly.
2. you can do such validation inside of ExecStartPre= and tell systemd whether the validation succeeded by returning a non-zero exit code from the process invoked there. Use `%i` to pass the instance name to the binary you can invoke.

I hope that makes sense, closing.
