### ISSUE TITLE
`coredumpctl` warns because it sees `systemd-coredump@0.service`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5477]
```
systemctl list-units --all --no-pager --no-legend | grep core
```
`v231` (`systemd-231-12.fc25.x86_64`)
```
system-systemd\x2dcoredump.slice   loaded    active   active    system-systemd\x2dcoredump.slice
systemd-coredump.socket            loaded    active   listening Process Core Dump Socket
```
`master`
```
systemd-coredump@0.service             loaded    inactive dead      Process Core Dump
system-systemd\x2dcoredump.slice       loaded    inactive dead      system-systemd\x2dcoredump.slice
systemd-coredump.socket                loaded    active   listening Process Core Dump Socket
```

**Comment by poettering** [comment]
hmm? what is this about? i don't see anything wrong here?

Note that Accept=yes socket units generally keep at least one instance loaded, that they'll use for the next incoming connection. SELinux kinda forces that upon us, since we need to calculate the label for the socket from the binary we are going to run for it, but we can only do that if we actually have loaded the service unit.

Hence, I am not sure I see anything wrong here?

**Comment by evverx** [comment]
> v231 (systemd-231-12.fc25.x86_64)

Hm, "vanilla" systemd-231 always shows `systemd-coredump@0.service`.

> Hence, I am not sure I see anything wrong here?

Well, `man systemctl(1)` says
> List units that systemd currently has in memory. This includes units that are either referenced directly or through a dependency, units that are pinned by applications programmatically, or units that were active in the past and have failed.

What is `systemd-coredump@0.service`?

**Comment by poettering** [comment]
systemd-coredump.socket is a socket unit, which activates an instance of systemd-coredump@.service for each incoming connection. When a coredump happens on the system, then it will be passed to this service and be processed inside of a separate systemd-coredump@.service instance.

Socket activation service instances are numbered, the first connection coming in is systemd-coredump@0.service, the next one systemd-coredump@1.service, … and so on. Note though that as the connection comes in we'll actually downgrade that to an alias, and the primary name will then include information about the peer instead. 

As mentioned, due to selinux we'll always keep one connection unit instance referenced even before the actual connection for it comes in. But that's entirely OK: when it comes in, it will be used for that, change it's primary name as described above, and thus isn't leaked or anything.

Hence, there isn't really a bug here...

Or to say this differently: as soon as you encounter your first crash systemd-coredump@0.service will change its identity, enter running mode, then finish, and then die off, and be GC'ed.

**Comment by evverx** [comment]
> Hence, there isn't really a bug here...

Sure. I've removed that label. 

I think `man systemctl` is unclear. Maybe, it doesn't really matter. I'm closing.

**Comment by keszybz** [comment]
So it's a bug in coredumpctl. I'll push a fix.
