### ISSUE TITLE
journalctl interprets level/pid in messages unexpectedly

### ISSUE THREAD

**Issue by thread13** [systemd/systemd#5498]
### Submission type

  - [ x] Bug report
  - [ ] Request for enhancement (RFE)

Basically journalctl seems to replace stuff like '[INFO]' with a '[pid]'. `rsyslog` on the same machine does not do that.

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
    $ journalctl --version

    systemd 229
    +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 16.04 LTS

### In case of bug report: Expected behaviour you didn't see

see http://bugs.python.org/issue29675 -- the attached python scripts must produce output:

    Feb 28 21:30:05 hostname <test_test_test>[INFO]: logging was configured for process <7117>  # bad.py
    Feb 28 21:30:04 hostname <test_test_test>INFO: logging was configured for process <7114> # good.py

### In case of bug report: Unexpected behaviour you saw

    Feb 28 21:30:05 hostname <test_test_test>[7117]: logging was configured for process <7117> # bad.py
    Feb 28 21:30:04 hostname <test_test_test>INFO[7114]: logging was configured for process <7114> # good.py

So essentially for some reason '[INFO]' is replaced with a pid, and 'INFO' (with no surrounding square brackets) is replaced with 'INFO[pid]' . This does not happen on earlier non-systemd-based distributions, e.g. on Ubuntu 14.04 with rsyslog.

### In case of bug report: Steps to reproduce the problem

  1. Have a systemd-based system, e.g. Ubuntu 16.04 LTS with Python 2.7.
  2. Get good.py and bad.py from http://bugs.python.org/issue29675 .
  3. run `journalctl -f ` on one console and `tail -f /var/log/syslog` on another.
  4. run e.g. `bad.py` .
  5. Observe the difference ( as cited above ).

**Comment by poettering** [comment]
we do minimal normalization of log messages and insert the PID after the syslog "TAG" if it is missing, and override if specified incorrectly, in order to make log messages trustable. Or in other words we'll enforce the effect of LOG_PID if clients didn't specify it when using libc syslog() or openlog().

While syslog is weakly defined, the format tends to be:

```
"<" PRIORITY ">" TIME " " HOSTNAME " " TAG ":" MESSAGE
```
and TAG usually consists of the process name, usually followed by the PID:

```
NAME "[" PID "]"
```

Now, you are departing from that format for you case, and encoding the priority in "[" and "]:", which is where the PID is usually placed and where glibc places it.

Now, syslog as mentioned is crappily defined, but I am pretty sure, that if you use the local /dev/log socket (as opposed to network syslog), then you should follow the syntax that libc uses when generating messages, and that means you place a colon after the TAG, and do not add the priority in there first.

Sorry, but I don't think we should change anything here in the journal. It's simply that your client should follow the preicse syslog syntax that local clients normally use instead of departing from that.

**Comment by poettering** [comment]
Anyway, closing this as it appears the python bug explicitly departs from the usualy format string and picks something else. You are welcome to do that of course, but it's not particularly surprising that software processing your logs won't grok this anymore. 

I hope this makes sense.

**Comment by thread13** [comment]
Well, I guess this is your software after all. As long as you guys don't mess with the data and let rsyslog pick it as is, I suppose I'm fine with that.

**Comment by poettering** [comment]
well, if your rsyslog setup uses journald's ForwardToSyslog= setting, then yes, we'll just pass the original string unmodified.

However, many distros don#t setup rsyslog that way anymore. Instead they turn off ForwardToSyslog=, and make rsyslog read the runtime journal as it is written, thus being able to benefit from early-boot messages and structured metadata. And of course, in that case journald's parsing and fixing will have an effect.

Hence, my recommendation would be: use glibc-compatible format strings, don't make up random ones.

**Comment by thread13** [comment]
Thank you, I shall probably write back to Python documentation maintainers and tell them your advice on how a standard log format should look like. In the meantime, both Redhat 7 and Ubuntu 16.04 LTS seem to have  "ForwardToSyslog=yes" enabled by default, so we can benefit from both nice reliable output from journalctl, and nice untouched messages in /var/syslog, what makes them look the same on all Unix systems, what in turn makes looking for certain messages a bit easier.
