### ISSUE TITLE
systemd-tmpfiles: Cannot set file attribute for /var/log/journal: Operation not supported on ext4

### ISSUE THREAD

**Issue by andreyv** [systemd/systemd#5607]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

systemd 232

### Used distribution

Arch Linux x86-64

### Problem description

Starting from Linux 4.10, I see the following warnings on boot:

```
systemd-tmpfiles[538]: Cannot set file attribute for '/var/log/journal', value=0x00800000, mask=0x00800000: Operation not supported
systemd-tmpfiles[538]: Cannot set file attribute for '/var/log/journal/ebb5e652c375408696fbe8eb6937da85', value=0x00800000, mask=0x00800000: Operation not supported
systemd-tmpfiles[538]: Cannot set file attribute for '/var/log/journal/remote', value=0x00800000, mask=0x00800000: Operation not supported
```
Linux 4.9 was fine. My root filesystem is ext4 and my mount options are `rw,noatime,data=ordered`.

This is related to #663. If the warning is legitimate, then it would be fine, but I suspect some kind of regression here.

**Comment by evverx** [comment]
https://github.com/torvalds/linux/commit/d14e7683ecf06aa4365ee96adf74494114341dbe
> ext4: be more strict when verifying flags set via SETFLAGS ioctls

> Currently we just silently ignore flags that we don't understand (or
that cannot be manipulated) through EXT4_IOC_SETFLAGS and
EXT4_IOC_FSSETXATTR ioctls. This makes it problematic for the unused
flags to be used in future (some app may be inadvertedly setting them
and we won't notice until the flag gets used). Also this is inconsistent
with other filesystems like XFS or BTRFS which return EOPNOTSUPP when
they see a flag they cannot set.

**Comment by andreyv** [comment]
Thanks for the link. If this is not a bug, this issue can be closed.

**Comment by evverx** [comment]
I think the warning message isn't very user-friendly. Who on earth knows that `00800000` is `FS_NOCOW_FL`? :-)

> If this is not a bug, this issue can be closed.

OK, I'm closing this one. Thanks.

**Comment by ghost** [comment]
Hello,

Is there anything we can do on either systemd / kernel / ext4 fs configuration to avoid such warning in the journal logs, please ?

My understanding of the problem (hoping it is good) is that systemd-tempfiles is using chattr with flags not supported by ext4 filesystem. If so the expected behavior is to have systemd-tempfiles use appropriate flags, isn't it ?

Thank you very much in advance for your comments here.

**Comment by evverx** [comment]
`journal-nocow.conf` can be masked by doing the following:
```sh
ln -s /dev/null /etc/tmpfiles.d/journal-nocow.conf
```

**Comment by ghost** [comment]
It worked liked a charm, thank you very much.

**Comment by poettering** [comment]
Reopening this one, we should probably downgrade the warning here in case of EOPNOTSUPP...

The kernel broke API here afaics, but I figure it's probably a good change they made, hence we should probably adapt and simply accept that not all file systems are equally powerful and EOPNOTSUPP shouldn't be considered a problem.

**Comment by evverx** [comment]
> we should probably downgrade the warning here in case of EOPNOTSUPP

I would prefer not hiding such messages.

I'm not sure I understand what the problem is. `systemd-tmpfiles` simply prints a harmless warning. It doesn't return an error code.

**Comment by Stebalien** [comment]
> I would prefer not hiding such messages.

Why?  When NOCOW isn't supported, the filesystem doesn't support COW so the files are implicitly NOCOW.

> I'm not sure I understand what the problem is. `systemd-tmpfiles` simply prints a harmless warning. It doesn't return an error code.

For good reason, people assume that warnings indicate trouble.

**Comment by evverx** [comment]
> For good reason, people assume that warnings indicate trouble.

Applying a wrong attribute is a trouble, isn't it? Why should I upgrade a log level to just see that my system is misconfigured?

**Comment by Stebalien** [comment]
> Applying a wrong attribute is a trouble, isn't it?

Yes and no. On one hand, systemd-tempfiles *is* failing to do something you're telling it to do. However, in this case, you're asking the systemd-tmpfiles to disable COW for the file and, as far as I know, all systems that support COW also support the NOCOW attribute. This means that, if disabling COW fails, COW wasn't enabled in the first place so there's no real issue. IMO, it would be nice if ext4 simply supported the NOCOW option as a no-op/future-proofing but I'm probably alone in that opinion.

A better solution might be to support a `?` suffix (or a `-` prefix) to indicate that the tempfiles directive should fail silently (`h? /some/path - - - - +C`) but that may not be worth it.

**Comment by evverx** [comment]
> A better solution might be to support a ? suffix (or a - prefix) to indicate that the tempfiles directive should fail silently (h? /some/path - - - - +C) but that may not be worth it

I like that.

Anyway, so far we are choosing between hiding all the messages and hiding nothing, and I prefer the latter.

**Comment by poettering** [comment]
> I'm not sure I understand what the problem is. systemd-tmpfiles simply prints a harmless warning. It doesn't return an error code.

Well, I think we should not log a warning in the clean boot case. I mean, let's not forget, setting NOCOW only matters on btrfs, and is only defined there. It's completely supported to run a systemd system on ext4 however, and in that case we should generate zero warnings at boot, because there's exactly nothing wrong if we can't set NOCOW on those files.

I am not suggesting to downgrade all warnings for all line types. I am just suggesting we should dowwngrade ENOTSUPP on the chattr() lines, and only those. chattr flags after all generally aren't crucial for operation, they are just auxiliary flags.

I am not convinced that adding a new prefix modifier (such as "?") would really be desirable... We already have syntax that is more complicated than I'd like it to be, and this particular case appears a big too nichey to warrant another addition to the syntax.

**Comment by poettering** [comment]
Hence, what I'd suggest: downgrade chattr() EOPNOTSUPP to LOG_DEBUG, and document in the man page that chattr lines are NOPs on file systems that don't support the specified flags
