### ISSUE TITLE
Unable to prevent systemd from not unmounting mount point

### ISSUE THREAD

**Issue by codekipper** [systemd/systemd#5669]
### Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232-r3

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Axis custom distro

### In case of bug report: Expected behaviour you didn't see

> We're seeing that mount points created by our mounting manager are umounted first when we do a reboot. We would like to see the mounting manager to unmount whatever it has mounted. 

### In case of bug report: Unexpected behaviour you saw

> On shutdown the mount points are unmounted well before the mounting manager starts its shutdown.

### In case of bug report: Steps to reproduce the problem

> We start the mounting application, mount a network point, reboot and observe the serial debug. We can see that the mounts are unmounted early and the mounting application then complains that it couldn't unmount the mount point.

I've looked into masking the mount, tried adding Before=mounting manager.service etc with no luck. 

The only success I had was adding Before=mounting manager to shutdown.target. But this looks very wrong.

BR,
CK

**Comment by poettering** [comment]
Well, systemd manages mounts to a certain level and will remove mounts during shutdown. You have pretty precise control on when it will do so howver, by appropriately placing ordering dependencies. Also, mounts picked up through /proc/self/mountinfo will by default be ordered before "local-fs.target"/"remote-fs.target", and since on systemd the shutdown order of two units is always the inverse of the startup order, this means that local-fs.target first has to go away before any such mount is removed. This then means that if you want your service to run before any such mounts go away, it is sufficient to order it after "local-fs.target". Note that by default all services are configured that way, unless you explicitly set "DefaultDependencies=no" for them. (or to be fully accurate they get a default order against basic.target which in turn is ordered against local-fs.target).

Anyway, there's nothing to fix here in systemd afaics. Please just place the right deps in your units (or on your mounts), things will work then. (you can even do per-mount point explicit deps if you like, using the new x-systemd.before= mount option).

I hope this makes sense. Closing.

(Also note, if you need community support, the right place to ask is the mailing list, not this bug tracker)

**Comment by utezduyar** [comment]
I don't see local-fs.target. So this is a bug?

systemctl show:

Names=var-volatile-spool-storage-NetworkShare.mount
Requires=-.mount system.slice var-volatile.mount
Wants=network-online.target
Conflicts=umount.target
Before=remote-fs.target umount.target
After=-.mount remote-fs-pre.target network.target network-online.target system.slice var-volatile.mount
RequiresMountsFor=/var/volatile/spool/storage

**Comment by poettering** [comment]
oh, this is a network share? in that case "remote-fs.target" is used in place of "local-fs.target", hence all looks good. 

However, unlike "local-fs.target" units are not implicitly ordered after "remote-fs.target" but have to declare this ordering explicitly, regardless of DefaultDependencies=no|yes...

Hence: simply add "After=remote-fs.target" to the service that wants to to use the network fs and all should be good.
