### ISSUE TITLE
`systemd-run --property=...` stopped supporting specifiers

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#5699]
```sh
-bash-4.3# systemd-run -t --property Environment='NAME=%n' sh -c 'echo $$NAME'
Running as unit: run-u3.service
Press ^] three times within 1s to disconnect TTY.
%n
```
The regression was introduced by 4f4afc88ecd8ab9cfe9.

**Comment by evverx** [comment]
I reopened the issue because many settings are still not supporting specifiers in them. I don't think the issue is so critical, so I removed the `v234` milestone.

**Comment by yuwata** [comment]
It seems that #7444 fixes this issue.

**Comment by poettering** [comment]
Actually in #7444 i removed all specifier expansion from transient unit setting interpretation. i.e. I am pretty sure we shouldn't do that on a low-level API. We should do that on unit files and suchlikes, to make them reusable, but on a low-level API i think we should guarantee that the data is used as-is with no additional processing at execution time.

I mean, if you have a programmatic client side that creates units (rather than static unit files on disks) it's much easier to write adaptable unit definitions anyway, hence I doubt specifier expansion would do any good there. Clients can resolve specifiers on their own really, before pushing the data through the bus

As it turns out we only did specifier expansion for two properties anyway, hence removing that there too was a very easy choice...

**Comment by evverx** [comment]
> As it turns out we only did specifier expansion for two properties anyway

All the properties passed via `--property`, `--description` and so on had been supporting specifiers in them before https://github.com/systemd/systemd/commit/4f4afc88ecd8ab9cfe9e1eeea7e3aeb937811937 was merged. That is basically what this issue is about.

> Clients can resolve specifiers on their own really, before pushing the data through the bus

I'm not sure I understand the logic. Does that mean that `systemd-run` is not a client?

**Comment by poettering** [comment]
> > As it turns out we only did specifier expansion for two properties anyway
> 
> All the properties passed via --property, --description and so on had been supporting specifiers in them before 4f4afc8 was merged. That is basically what this issue is about.

Uh, well, but do note that this was a bug, that this ever worked for all props: we ultimately ended up re-reading the unit file, even though we applied the settings directly, and since we didn't escaped properly this would happen by side effect, not by intention...




> > Clients can resolve specifiers on their own really, before pushing the data through the bus
> 
> I'm not sure I understand the logic. Does that mean that systemd-run is not a client?

Well, whatever calls systemd-run is a client. i.e. if you have a shell script it can replace this:

```
systemd-run --description="my hostname is %H" …
```

by this:

```
systemd-run --description="my hostname is $HOSTNAME"…
```

The specifiers most exist in order to make static unit file writing a bit less static, add some minimal, restricted dynamic logic to it, so that templating can work, and a few similar usecases. However, transient unit files and systemd-run are not static anyway, they are the pinnacle of dynamic, they can generate *everything* fully dynamic anyway, since they are *code* and not static files. In fact, they are *much* better at generating things anyway, as the specifier logic only has a very very minimal vocabulary...

**Comment by evverx** [comment]
I agree that scripts can do whatever they want to, but I'm not sure why people who use `systemd-run` should remember that it functions in a different mode and be careful when they paste parts of static unit files or the output of `systemd-cat` into the command line.

Does anybody know if there is any documentation where I can read about what I should pass to `systemd-run` to make `/bin/bash -c 'printf "50%%\n"'` work and how it is different from what I specify in `ExecStart=`?

**Comment by evverx** [comment]
I haven't found any documentation, but it seems that to make `printf "50%%\n"` work
* `50%%` should be passed to `systemd-run`
* `50%%%%` should be specified in `ExecStart=`

I don't think this is very intuitive.

**Comment by bl33pbl0p** [comment]
There are a few things shell scripts cannot figure out (%n or %N for example) without taking the $INVOCATION_ID and getting the unit name using D-Bus (and unescaping/escaping them). I feel this is sometimes surprising they don't expand, one expects them to behave the same way other units do, and I feel making this work would be better than not because:
* People would expect them to work the same way units do (and since transient units are also units, just created programmatically).
* Some things like %n as I pointed out end up requiring more work than a single word. One also can just pass static names through --unit, or maybe dynamic and store the value of the variable in the script, but if they don't, there's no other way to get this bit back.
* Behaviour ends up being uniform in all places (transient and static units), hence no need to explicitly remember how things behave in different places.

**Comment by evverx** [comment]
It seems this issues in unlikely to be fixed so I don't think it makes much sense to keep it open.
