### ISSUE TITLE
Automounted drive system dead lock when not available

### ISSUE THREAD

**Issue by jpclaveranne** [systemd/systemd#5714]
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora 24

### In case of bug report: Expected behaviour you didn't see

> I am using systemd automount for a usb hard-drive backup system running on cron. When HD is off or not connected the system should operate normaly

### In case of bug report: Unexpected behaviour you saw

> system commands dead locks on "lstat /srv/BACKUP ..." (my python script, df, xfe-xfe ....)

### In case of bug report: Steps to reproduce the problem

> I am using a python script relaying on "os.path.ismount ...." on a automounted usb drive configured with "noauto,nofail,x-systemd.device-timeout=1,x-systemd.mount-timeout=1,x-systemd.automount,x-systemd.idle-timeout=300". The script is running throught cron. When using a file onto the mounted system to test the file system I don't have the same behaviour.

**Comment by poettering** [comment]
Hmm, is this still an issue?

 It appears to me that using automounts is simply not the right approach here, and the issue is just a misunderstanding what automounts do. By definition, it will wait until the device is plugged in before being able to mount it. That's how automounting works: all access is stalled until the backend can be fulfilled.

If this is not what you want, then do not use automounts, but mount the thing from your script or so, on demand, if the device is around.

**Comment by poettering** [comment]
Let's close this due to lack of response and probably automounts aren't the right choice here anyway.

**Comment by jpclaveranne** [comment]
Yes i agree
