### ISSUE TITLE
journald not clearing the unix socket buffer 

### ISSUE THREAD

**Issue by guru2018** [systemd/systemd#5720]
Using syslog API i am logging around 1500 log messages per second, and once a while(once in 200 times) the call takes more time around 0.1 sec,  in normal case it takes around 50 to 100  micro second. During this time (0.1 second) my application will be blocked.

 After further analysis I found the issue is because the sendto call done by the syslog is taking more time,  which in turn due to buffer is full and the its waiting for buffer to get free.
 The buffer is getting full because the systemd-jorunald is not reading the messages fast enough from the remote end unix domain socket.

 I tried modifying below values from journald.conf, its not of much help.
 RateLimitIntervalSec=1s
 RateLimitBurst=2000
 
 Issue is only in MIPS Octeon 2 HW, same works fine in x86 HW. 

 Could you please suggest how can I make systemd-journald read the remote socket fast enough that the buffer will not get full.
 syslog socket type: unix domain socket. DGRAM.
 systemd version: 232
 kernel version: 4.4.36

**Comment by guru2018** [comment]
After further analysis found the issue is with getting data from the proc file system and processing it. If ucred block of code is commented in journald-server.c issue is not seen. Could some one spread some light on why reading from data from the proc file system is more time taking. 
Issue is only on mips. On x86 it works fine.

**Comment by poettering** [comment]
We try to enlarge the AF_UNIX/SOCK_DGRAM maximum qlen and socket buffer size early at boot, in order to make clients block as late as possible, even if journald takes some time to acquire and process the metadata for it. 

There have been PRs in the past to cache the metadata and reuse it, so that we don't have to acquire them again on each message, which is quite expensive. This work was never finished though.

There also was some work of providing a (hidden) way to turn off acquiring of some of the metadata in order to optimize things at the cost of providing less implicit metadata for each message.

**Comment by poettering** [comment]
Closing now that #6392 has been merged.
