### ISSUE TITLE
systemd-importd over dbus crashes with no output to journald

### ISSUE THREAD

**Issue by cpg1111** [systemd/systemd#5737]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> debian stretch

### In case of bug report: Expected behaviour you didn't see

> When sending a dbus request of object path `/org/freedesktop/import1` and message name `org.freedesktop.import1.Manager.ImportTar`, systemd-Importd Imports a tarball as a machine image.

### In case of bug report: Unexpected behaviour you saw

> When sending a dbus request of object path `/org/freedesktop/import1` and message name `org.freedesktop.import1.Manager.ImportTar`, systemd-importd dies with no output to journald.

### In case of bug report: Steps to reproduce the problem

> 
```
systemctl start systemd-importd.service
```
NOTE: I was using github.com/godbus/dbus and this is just code that isolated the issue to what was relevant, not the code I originally encountered the error with.
```
import (
    "os"

    "github.com/godbus/dbus"
)

func main(){
    conn, err := dbus.SystemBusPrivate()
    if err != nil {
        panic(err)
    }
    defer conn.Close()
    methods := []dbus.Auth{dbus.AuthExternal(strconv.Itoa(os.Getuid()))}
    err = conn.Auth(methods)
    if err != nil {
        panic(err)
    }
    obj := conn.Object("org.freedesktop.import1", dbus.ObjectPath("/org/freedesktop/import1"))
    img, err := os.Open("/path/to/a/tar/ball")
    if err != nil {
         panic(err)
    }
    fd := img.Fd()
    res := obj.Call("org.freedesktop.import1.Manager.ImportTar", 0, int(fd), "some-local-name", false, false)
    if res.Err != nil {
         panic(res.Err)
    }
}
```

as root: `go run main.go`

and then I have the error `read unix @->/var/run/dbus/system_bus_socket: EOF` and systemd-importd.service shows a status of dead.

Any insight as to what is happening is greatly appreciated.

**Comment by evverx** [comment]
This looks like https://github.com/systemd/systemd/issues/3996.

@cpg1111 , could you provide what `systemctl cat systemd-importd.service` prints, please?

**Comment by cpg1111** [comment]
```
[Unit]
Description=Virtual Machine and Container Download Service
Documentation=man:systemd-importd.service(8)
Documentation=http://www.freedesktop.org/wiki/Software/systemd/importd

[Service]
ExecStart=/lib/systemd/systemd-importd
BusName=org.freedesktop.import1
WatchdogSec=3min
KillMode=mixed
CapabilityBoundingSet=CAP_CHOWN CAP_FOWNER CAP_FSETID CAP_MKNOD CAP_SETFCAP CAP_SYS_ADMIN CAP_SETPCAP CAP_DAC_OVERRIDE
NoNewPrivileges=yes
MemoryDenyWriteExecute=yes
RestrictRealtime=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @obsolete @raw-io
```

Here you go @evverx

**Comment by evverx** [comment]
Thanks. That is definitely not #3996.

Could you elaborate what you mean by "crashes with no output to journald"? Have you seen a coredump?

Does `machinectl import-tar` work?

**Comment by cpg1111** [comment]
What I mean is my go client sends the dbus message, and receives `read unix @->/var/run/dbus/system_bus_socket: EOF` and within that time `systemctl status systemd-importd` shows `Active: active (running)` beforehand and the same command shows `Active: inactive (dead)` afterwards. The last message in the journal is `Started Virtual Machine and Container Download Service.`. I did not see a coredump as far as I can tell, and `machinectl import-tar` does work.

**Comment by evverx** [comment]
> the same command shows Active: inactive (dead) afterwards

`systemd-importd` exits if it is inactive.

**Comment by cpg1111** [comment]
Yes, I understand that, but there seems to be an error with it interfacing dbus and there's no feedback as to what happened.

**Comment by poettering** [comment]
importd exits when it isn't used, and systemd will start it again automatically when it is used the next time. Are you saying this doesn't work for you?

What makes you say "crash"? just exiting on idle is not a crash. A crash is an exit with SIGABRT, SIGILL or a coredump of some kind. Have you encountered something like that?

I am not sure I grok where the problem is supposed to be, can you elaborate?

**Comment by cpg1111** [comment]
So perhaps crash isn't the right word.  The main issue, as I see it, is that I can confirm the message reaches dbus.  However, importd has no logs or any sort of feedback. While it is possible the dbus message doesn't reach importd, I see nothing indicating this in dbus. So my main point is that there is no feedback/insight (I assume through logs would be the desired medium) to what's happening, whether it be on the dbus side saying the destination is not reachable, or importd does not accept the message, or some other issue within importd itself.

**Comment by poettering** [comment]
well, we generally don't log every api call by default, already for performance reasons. 

There are multiple ways however to trace the bus requests made, and see what reaches importd. For example use "busctl monitor" for a live trace of bus messages in flux. Or set SYSTEMD_LOG_LEVEL=debug for the importd service (to spell that out: issue "systemctl edit systemd-importd", then write the two lines "[Service]" and "Environment=SYSTEMD_LOG_LEVEL=debug" into the editor that spawns, and save/exit, then issue "systemctl restart systemd-importd"). If you do, importd will log a brief line for each bus message received or sent by it.

Both of these work for any bus service btw, they are not specific to importd.

Closing since debugging functionality for this exists, but being debugging functionality must be explicitly requested.

**Comment by cpg1111** [comment]
Thanks, that'll certainly help.
