### ISSUE TITLE
controlgroups for services running as multiple users

### ISSUE THREAD

**Issue by vdloo** [systemd/systemd#5759]
Hi. On ubuntu precise without systemd I was able to use cgroups to limit the memory usage of multiple services where the master process ran as one user (often root) and other processes ran as another user (various users other than root), and put processes started by specific users in the shell in this group as well.

For example PHP-FPM:

```
# ps aux | grep fpm
root     17657  0.0  1.7 490252 36272 ?        Ss   Apr14   0:46 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)                      
phpuser  17658  0.0  2.1 719088 44620 ?        S    Apr14   2:31 php-fpm: pool www                                                            
phpuser  17659  0.0  2.3 719056 47184 ?        S    Apr14   2:33 php-fpm: pool www                                                            
phpuser  25190  0.0  2.1 719012 43124 ?        S    Apr16   1:02 php-fpm: pool www
```

It seems like that has become impossible with systemd without directly interacting with the systemd created cgroup and therefore possibly introducing undefined behavior on my system.

Previously I'd specify a cgroup with a memory limit in `/etc/cgconfig.conf` and the cgconfig service would create and mount it. Then the cgred daemon would place the processes in the cgroup according to the cgrules. Additionally the [pam_cgroup PAM module](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/Resource_Management_Guide/#proc-pam_cgroup) would place processes in the cgroup without waiting for cgred.

```
# cat /etc/cgrules.conf 
phpuser             memory          mygroup
otheruser           memory          mygroup
```

Now on systemd I can not do exactly this. I've created a slice with a memory limit:

```
# /etc/systemd/system/mygroup.slice
[Unit]
Description=Less essential processes

[Slice]
MemoryLimit=1024M
```

This creates the cgroup mygroup.slice, which is great and it shows exactly what is in this slice with `systemctl status`, but I can't seem to configure it for my specific use case.

If I configure the FPM service unit file to use my created slice it will also place the master process in the group. If I linger a user with loginctl it will place all the processes in the user group. Both is not what I want. I can edit configuration files like `./systemd/system/user@.service` but specifying a slice there will have no use if used in combination with pam_systemd, processes will all end up in user slices instead of only doing that for specific users (and not in the newly created slice but always in an implicit user slice).

So what I've come up with now is to keep using pam_cgroup.so in /etc/pam.d/ and use cgrules to put processes in the systemd created cgroup for the slice.

```
# cat /etc/cgrules.conf 
phpuser             memory          mygroup.slice
otheruser           memory          mygroup.slice
```

But this doesn't seem to be the right way to do it. It works, the processes are placed in the created cgroup (I can see this with cat /proc/1234/cgroup and the memory line specifies that the process is in the mygroup.slice group) but in systemctl status the process will show up as belonging to another slice. 

Is there a right way to do this in systemd? Is it likely that my approach will break in the future?

**Comment by poettering** [comment]
using something like cgrules is explicitly not supported on a systemd system: there should only be one writer to the cgroup tree, except for expressly delegated subtrees.

There always was the plan to add a per-use configurable slice setting, but this never materialized since the UNIX passwd database isn't extensible, and no generic database materialized that could carry such additional information.

Note that logind is about managing "human" users though, i.e. clients that log in via a terminal of some kind. It's not intended to manage services, that's what systemd itself is for. And for system services it's easy to assign them to specific slices, simply by using the Slice= option.

If you run multiple PHPFPM instance, I'd suggest running them as system service instances, and use Slice= to assign them to the right slice.

**Comment by reikred** [comment]
SHORT VERSION: I would like systemd to assign any instance of the rsync binary to a specific cgroup, automatically. How? Details?

LONG VERSION: I have a very similar concrete problem as OP. It used to be solvable by cgred.service and /etc/cgrules.conf. Could someone please show me how to do this with systemd:

When I run rsync for (large) backups I need to limit the memory usage because otherwise rsync will use up all the RAM as file buffer., and the system as a whole will become unresponsive to other tasks. I used to manage this by assigning the rsync binary to a certain cgroup, via /etc/cgrules.conf.

How do I do this in systemd? With some gory details, please. I 'm on Fedora 25, and when I did a dnf update yesterday, cgred.service was removed, presumably being replaced by systemd. And my rsync jobs eat all the memory and makes the system dreadfully slow.

**Comment by Werkov** [comment]
Hi.
Limiting *any* `rsync` instance implicitly as you describe is not possible with systemd as cgroup manager. However, that's still a bit overkill for the your usecase. I believe you are running your backup as a regular job, presumably not a systemd .timer but a cron task.

Then you can wrap it in a scope assigned to particular slice, e.g.
```
0 1 * * 7 root /usr/bin/systemd-run --scope --slice=system-backup.slice /usr/local/bin/backup.sh
```

```
cat > /etc/systemd/system/system-backup.slice <<EOD
[Slice]
MemoryLimit=1G
EOD
```

(Note I did not test it but I'm happy to help if you run into troubles.)

**Comment by reikred** [comment]
Thanks for the recipe. The limitation that systemd cannot control cgroup for ALL rsync instances is a pretty severe one. Imagine the case where the destination of the backup is a remote machine. That machine must also run an rsync process, and presumably the machine has no idea what cgroup to run rsync in, because there is no way to tell it that information. So then the remote machine will still have the same problem, namely that all memory will be sucked up as buffer space if the backup fileset is large. Wow, I really wish cgred and systemd were compatible with each other.

**Comment by poettering** [comment]
let's close this here. The design of systemd's cgroups use is not going to change, and the rest appear to be more support questions than bug reports, and those should better be directed to the mailing list. Closing hence.
