### ISSUE TITLE
systemd-resolved doesn't switch to fallback DNS if the priority DNS is not responding

### ISSUE THREAD

**Issue by vladimirtiukhtin** [systemd/systemd#5771]
### In case of bug report: Unexpected behaviour you saw

> systemd-resolved switch to FallBack list if primary server is not responding

### In case of bug report: Steps to reproduce the problem

> Run systemd-resolved, stop DNS server, systemd-resolved doesn't switch DNS server to FallBack list

**Comment by poettering** [comment]
This is not what the fallback list is for. The fallback server list is only used if there are no other DNS servers configured otherwise. If there are any DNS servers configured then it's these configufres ones that are used, and are the only ones used. 

Hence: if you want to define some extra servers to use if the primary configured servers don't work, simply add them to the list of servers. resolved will cycle through all defined servers until it finds one that responds.

Closing, as this is intended (and documented) behaviour, and as there's a well-defined way to achieve what you want to do.
