### ISSUE TITLE
sd_bus vtable doesn't support duplicate methods

### ISSUE THREAD

**Issue by daurnimator** [systemd/systemd#578]
`sd_bus_add_object_vtable` will fail with `EEXISTS` if you give it the same member twice.
This prevents users from exposing overloaded methods.

**Comment by dvdhrm** [comment]
Correct.

We never used method-overloading so far. I'm also not a big fan of the concept in general. However, I'll let Lennart decide on this. Regardless, you might have to implement it yourself and send us patches.

**Comment by poettering** [comment]
I am very strongly of the opinion that we should not allow overloaded functions. Only very few languages support that. C doesn't. C++ does. Python and Java don't afaik. Since D-Bus really should be accessible and usable from all languages we should stay conservative and not allow them.

Sorry.

**Comment by daurnimator** [comment]
> Only very few languages support that. C doesn't. 

In C, I 'overload' via a macro:

```
#define NARG_(_15, _14, _13, _12, _11, _10, _9, _8, _7, _6, _5, _4, _3, _2, _1, N, ...) N
#define NARG(...) NARG_(__VA_ARGS__, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)
#define PASTE(a, b) a ## b
#define XPASTE(a, b) PASTE(a, b)

int foo(int a, int b) {
    return 1;
}
#define foo2(a,b) foo((a), (b))
#define foo1(x) foo2(x,0)
#define foo(...) XPASTE(foo, NARG(__VA_ARGS__))(__VA_ARGS__)
```

> C++ does. 
> 
> Python and Java don't afaik.

Python functions don't have types; they also have default arguments.
It's not unusual to do different things based on type of arguments:

``` python
def foo(a, b=None):
    if type(a) == str:
        a = something()
    somethingelse(a, b)    
```

> Since D-Bus really should be accessible and usable from all languages we should stay conservative and not allow them.

Languages don't have to for sd-bus to support it.

Let's imagine I've got an established dbus interface with a certain signature, but I realise that in the majority of use cases I need to have an extra argument (quite common no matter the language, e.g. on linux `eventfd` => `eventfd2`).

I'd like to add a new method with the same name but different signature.

**Comment by poettering** [comment]
> I'd like to add a new method with the same name but different signature.

No, please don't! This is not compatible with gdbus code generators for example. If you wnat a second method, then name it different, maybe DoFoobar() and DoFoobarEx() or DoFoobar2(), or DoFoobarWithFlags() or whatever, but do not overload methods under the same name. This will break for clients that use a language where overloading is not supported. And really, your C example just is a very good reason why we should never ever support something like that!

@smcv, maybe we should officially document in the dbus spec that method overloading is not accepable and that language bindings can rely on methods being uniquely defined per interface?

**Comment by daurnimator** [comment]
> This will break for clients that use a language where overloading is not supported.

I feel like that's a problem for those languages then.
They already have to deal with Variants, which are in dbus.

> @smcv, maybe we should officially document in the dbus spec that method overloading is not accepable and that language bindings can rely on methods being uniquely defined per interface?

What's the point of signatures if you can assume that a given member always has the same signature?
It seems like dbus was purposefully designed to allow multiple signatures for the one member (i.e. overloading).

**Comment by smcv** [comment]
D-Bus can be viewed as a stack of related specifications. The lowest-level is pure message-passing; higher-level layers impose constraints (such as "a method call gets exactly one reply") to turn it into something that can interoperate with practical language bindings without resulting in remotely-crashable services. You _can_ bypass higher-level layers via lower-level APIs, but that isn't the same as saying you _should_. In particular, if a service uses low-level APIs to give itself an unconventional D-Bus interface, then all of its clients are going to have to use the same low-level APIs to interoperate with it.

We have high-level APIs for a reason: they make the easy things easy, make the hard things less hard, and guide service implementors towards designing interfaces that don't violate least-astonishment.

I do not consider method overloading to be part of the interoperable subset of D-Bus that should be supported by any high-level API. You _can_ do it (by using lower-level message-passing APIs), but you _shouldn't_, and it is OK that higher-level (object-oriented) convenience APIs just don't support it at all. In interoperable D-Bus API designs, an (interface, method) pair has a unique signature (list of "in" and "out" argument types).

There are many other designs that could have been chosen, but they weren't; this one is the convention we have.

> What's the point of signatures if you can assume that a given member always has the same signature?

Robustness. Without a signature, you cannot parse a message at all; and if a service and its client disagree on the expected signature for a message (perhaps because one of them is outdated or buggy), the result should be a graceful runtime error, not a crash or a silently misinterpreted message. When D-Bus is used on the system bus, a remotely-triggerable crash is a denial of service vulnerability, and it does not seem particularly unlikely that a crafted message with a different signature could lead to a confused-deputy vulnerability.

If you want the sort of thing that C++ or Python would represent by overloading or varargs, either have methods with different names - use names like `AddWidget` and `AddWidgetWithName` if you need to - or have an explicit argument of type `av` (array of variants) where you can put whatever you want.

If you want named arguments (like `def foo(**kwargs)` in Python) or other extensibility mechanisms, have an explicit argument of type `a{sv}` where you can put whatever you want.

> In C, I 'overload' via a macro

I'm glad you're enjoying the flexibility of the C preprocessor, but please don't try to merge that into any project I'm involved with.
