### ISSUE TITLE
systemd-modules-load fails to start when the kernel has no module loading capability

### ISSUE THREAD

**Issue by benallard** [systemd/systemd#5812]
### Submission type

  - Bug report

### systemd version the issue has been seen with

systemd 215
+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR

### Used distribution

debian jessie

### In case of bug report: Unexpected behaviour you saw

```
# systemctl status systemd-modules-load
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static)
   Active: failed (Result: exit-code) since Wed 2017-04-26 10:04:45 UTC; 1min 52s ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 233 ExecStart=/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 233 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
### In case of bug report: Steps to reproduce the problem

Build a kernel without module support,
reboot

**Comment by benallard** [comment]
Adding
```
ConditionPathExists=/proc/sys/kernel/modules_disabled
```
just After
```
ConditionCapability=CAP_SYS_MODULE
```

In the service definition file does the trick.

**Comment by mbiebl** [comment]
That seems like half a fix only. You can have
/proc/sys/kernel/modules_disabled being set to 1

**Comment by benallard** [comment]
I used that path as an indicator about the availability of the dynamic module loading capability. Maybe there is another one that fit better.

About the value itself, it is meant to be set to 1 first after boot, when all modules are loaded (it is then impossible to set it back to 0). So at boot time, when that unit is triggered, the chance of it being "1" are really small. Do you have scenarii in mind where the unit can be triggered long after the boot ?

**Comment by poettering** [comment]
Hmm, I am not sure this is really a bug. I mean, on a normal system /etc/load-modules.d should be basically empty. If you add entries to that, then this means you want this to be in effect, and if we can't put it into effect, because kernel module loading is disabled we should probably consider this an actual failure cause. I mean, module loading *did* fail in this case...

So I am not convinced it's that clear we should condition the unit out in this case...

**Comment by benallard** [comment]
On my system:

 * **/etc/modules-load.d** has an empty file (well, a symlink to **/etc/modules**, which is empty, well, when you remove the comments - does ``ConditionDirectoryNotEmpty`` also considers comment ?)
 * **/lib/modules-load.d** has a configuration file installed by ``python-fuse`` that basically says ``fuse``. Because the ``python-fuse`` packaging somehow thought that it would better work if the fuse module is loaded at some point.

I don't think we can blame the ``python-fuse`` package for that. Beside there are probably dozen of other packages that also install some files in there, because they claim that they will work better if their corresponding module is loaded at boot-time.

In my case, I built a kernel that fits my need (for instance, it has fuse builtin). So I take the responsibility (by installing the said kernel) that I know what I am doing. I can't take the responsibility to cleanup those modules-load.d directory, that would be a move against the packages I installed on my system.

I think every installed kernels without dynamic module loading capability is carefully tailored for their system. As such, indeed, /etc/modules-load.d *should* be empty, but there might still be entries under /lib/modules-load.d, and those entries *should* be taken into account by the person who built the kernel without module support. Still, it is a failure to try to start the systemd-modules-load service.

How I came to notice about that issue ? the ``netfilter-persistent`` unit depends on the ``systemd-modules-load`` one, and thus fails to load, hence, to *apply my firewall settings*. Would a better fix be to relax the dependency between the two ? What about other units  that might decide that they want such a dependency as well ? (Of course, I have the ``iptables-filter`` stuff builtin in my custom kernel).

What I think I need a custom kernel without dynamic module loading capability ? Some grey-bard guy in the company thought that would improve the security of our product.

**Comment by poettering** [comment]
> /lib/modules-load.d has a configuration file installed by python-fuse that basically says fuse. Because the python-fuse packaging somehow thought that it would better work if the fuse module is loaded at some point.

This is simply unnecessary. The FUSE kernel module comes with the right modalias info so that udev will create /dev/fuse at boot causing fuse.ko to be auto-loaded at first access. There's no point to load that module explicitly and that package should really just drop this. Loading the module only when it is needed and at the moment it is needed makes things simpler, more robust and increases compatibility with cases like yours. Please file a patch against the package in question. Thank you.

**Comment by poettering** [comment]
> netfilter-persistent unit depends on the systemd-modules-load one

This sounds strange. We generally recommend to use "Wants=" instead of "Requires=" unless it is absolutely clear that the depending service can't work at all without the depended on service. Please file a bug against the package asking them to donwgrade this dep. This should make the issue go away in a much nicer way

**Comment by poettering** [comment]
I am pretty sure that the usecase at hand is much better fixed in a different way, with the two packaging changes suggested above. It feels to me that making the change requested in this bug would be more akin to taping over real issues and it's simply better to fix those real issues properly instead.

Hence I'll close this bug now. I hope this makes sense!

**Comment by benallard** [comment]
I understand your reasoning. Thanks for explaining it.

I've checked the latest version of the packaging of both packages as well, and it seems that the fix is already in there.
