### ISSUE TITLE
[Bug] systemd loads unit file with options it can't understand

### ISSUE THREAD

**Issue by RichiH** [systemd/systemd#5813]
#### On my system: 
````
Arch        : x86_64
Version     : 219
Release     : 30.el7_3.7
````
#### grawity on #systemd on irc.freenode.net:

233

### Used distribution

CentOS

### In case of bug report: Expected behaviour you didn't see

Unit file should fail to load if it can not be fully parsed

### In case of bug report: Unexpected behaviour you saw

Unit file was loaded with partial config and no error on CLI when running `systemctl start prometheus`. journalctl logged
````
Apr 26 12:33:02 <host> systemd[1]: [/etc/systemd/system/prometheus.service:10] Unknown lvalue '-storage.local.retention' in section 'Service'
````
but systemctl was silent. This is opposed to e.g.
````
[root@<host> ~]# systemctl start prometheus
Failed to start prometheus.service: Unit is not loaded properly: Invalid argument.
See system logs and 'systemctl status prometheus.service' for details.
[root@<host> ~]# 

Apr 26 12:32:31 <host> systemd[1]: prometheus.service lacks both ExecStart= and ExecStop= setting. Refusing.
````
when there's so much as a commented-out ExecStart in the service section of the unit file.

### In case of bug report: Steps to reproduce the problem

Run this unit file, observe that storage.local.retention and following are ignored.
````
[Unit]
Description=Prometheus
After=syslog.target network.target

[Service]
User=adm
TimeoutStopSec=1800
LimitNOFILE=120000
ExecStart=/home/prometheus/bin/prometheus/prometheus \
        -config.file /home/prometheus/configs/prometheus.yml \
        -storage.local.path /home/prometheus/data/ \
        -storage.local.target-heap-size=42949672960 << Missing backslash here!
        -storage.local.retention=817600h \
        -storage.local.chunk-encoding-version=2 \
        -alertmanager.url=http://localhost:9093
WorkingDirectory=/home/prometheus/working/

[Install]
WantedBy=multi-user.target
````

Contrary to that, run this unit file:
````
[Unit]
Description=Prometheus
After=syslog.target network.target

[Service]
User=adm
TimeoutStopSec=1800
LimitNOFILE=120000
#ExecStart=/home/prometheus/bin/prometheus/prometheus \
ExecStart=/home/prometheus/bin/prometheus/prometheus \
        -config.file /home/prometheus/configs/prometheus.yml \
        -storage.local.path /home/prometheus/data/ \
        -storage.local.target-heap-size=42949672960 << Missing backslash here!
        -storage.local.retention=817600h \
        -storage.local.chunk-encoding-version=2 \
        -alertmanager.url=http://localhost:9093
WorkingDirectory=/home/prometheus/working/

[Install]
WantedBy=multi-user.target
````
and systemd refuses to start.

Unit files being descriptive is, in my opinion, the single most useful property of systemd. The behaviour above runs counter to that.

**Comment by poettering** [comment]
The fact that we don't consider unknown unit file directives a fatal parse failure but just log about it and continue is a deliberate design decision, and I am not convinced we should change that. The one major reason we follow this scheme is compatibility of unit files with a variety of different versions: we want that people may adopt settings from newer systemd versions,  without rendering the file entirely unusable on older systemd versions. Yes, while making that choice we did realize that in some cases this might be problematic, as some options are not redundant, and not having them in effect will result in mistakes, but in general we figured things would be reasonably safe, given the declarative nature of systemd unit files.

In your case you ran into a problem which I figure is mostly just a side effect of that design decision: due to the missing backslash the parse understood something that assignment that wasn't supposed to be one. That is definitely unfortunate, but I am not sure it's strong enough a reason to step away from the logic explained above.

So, I do acknowledge that the behaviour you encountered isn't ideal, but the alternative you are suggesting, and systematically refusing unknown settings doesn't like the right approach to me. It's a dilemma, all solutions are awful in some way, though I pretty sure the current solution is a bit less awful.

I hpoe that explanation makes some sense. Sorry!

**Comment by RichiH** [comment]
I understand the reasoning and it's valid.

A potential middle ground: Escalate those parse errors to CLI when `systemctl {re}start` is run as it's not obvious to the average user that things are being (almost) silently dropped.

A potentially even better option: Have `systemctl daemon-reload` call `systemd-analyze verify` on all unit files and print a warning at that time.

The latter has the advantage of automagically considering `X-foo` as non-defective.

**Comment by poettering** [comment]
There have been requests before to add live service log output in "systemctl start" (and we added that to the TODO). I figure that would make a lot of sense (though not precisely trivial to implemnt without races), and yes, if we add that then I think we should also show such parse failure.

"systemctl status" should already show the parse errors, but of course by default only shows a brief excerpt of the logs, and the relevant bits might already be scrolled out of view...

**Comment by RichiH** [comment]
It does make sense.

80/20 seems to be the latter option as `systemctl daemon-reload` touches all unit files anyway and `systemd-analyze verify` exists and catches my problem above already; and putting everything else into TODO.

**Comment by RichiH** [comment]
Just to close this mentally either way: Will this issue remain closed or is the reload-time checking something that we can agree on?

**Comment by poettering** [comment]
not sure what you are asking, but "systemctl daemon-reload" should already result in log messages for all unit files with errors.
