### ISSUE TITLE
"systemctl status" should show the masking symlink instead of /dev/null as source unit file when a unit is masked.

### ISSUE THREAD

**Issue by wodny** [systemd/systemd#582]
One can usually use systemctl [show](http://serverfault.com/questions/692771/find-the-location-of-a-systemd-service) or [status](http://serverfault.com/questions/692771/find-the-location-of-a-systemd-service) to determine the file defining a service. But this method works badly if there is a symlink somewhere in between. It's completely useless for masked services when the symlink points to `/dev/null`.

```
$ systemctl status checkroot.service
● checkroot.service
   Loaded: masked (/dev/null)
   Active: inactive (dead)
```

Lennart Poettering [confirmed](http://lists.freedesktop.org/archives/systemd-devel/2014-July/020877.html) that this bug exists about one year ago. It's present in versions 215 in Debian Jessie (stable) and 221 in current Archlinux.

I think there should be an easy method to determine where the service came from and which symlink optionally masks it.

**Comment by poettering** [comment]
@wodny that mail you linked appears completely unrelated. 

Masking a service means taking away the configuration file effectively, and overriding it with /dev/null, so that it is never ever read. Hence the output of "systemctl status" looks how I think it should look like.

Or are you asking that instead of showing /dev/null, it should show the symlink that points to /dev/null?

Currently we will resolve all symlinks for this output, which is usually the right thing. It would make some sense indeed however, for the special case of /dev/null symlinks to instead show the last symlink in the symlink chain, rather than the ultimate target that is /dev/null. Is that what you are asking for? If so, we should rename the issue.

**Comment by wodny** [comment]
Both concern presentation of FragmentPaths in presence of symlinks along the path and their resolving process. It looked related.

I mean something closer to the second suggestion with a remark that I'm not sure if the symlink path should appear in FragmentPath. Maybe it could be another field? For sure I would like to know which file in which directory enables masking without checking all the directories by hand.

But the case is not limited to the /dev/null target. There is no way to traverse symlinks backwards so even if the target is not /dev/null it's not easy to say why systemd read a file, i.e. in which of configuration directories the symlink path originated.

**Comment by poettering** [comment]
I am pretty sure "systemd-delta" is the right way to figure out what is altering vendor configuration locally, including which masking links in /etc override what is in /usr. I think that is sufficient, and I don't think this all should necessarily be exposed in systemctl status, beyond that. Sorry.

I agree though that we should probably show the last symlink in the symlink chain if a unit is masked, instead of the /dev/null symlink. Will rename issue accordingly.

**Comment by wodny** [comment]
What about a situation when a unit is not altered and exists only in one of directories? For example in one of directories we place a `foo.service` symlink to `/usr/local/lib/systemd/system/foo.service`. `systemd-delta` won't show anything and `systemctl show/status` will show the target in `/usr/local`. There will be no information if the symlink was read because it was in /etc, /lib or /run.

And there are curious cases like in Debian Jessie: `sshd.service` in `/etc` which is a symlink to `ssh.service` (without d) in /lib. `systemctl list-unit-files` shows two `enabled` units. `systemctl show sshd.service` and `systemctl show ssh.service` show the same information (including `FragmentPath=/lib/systemd/system/ssh.service`).

In all of those cases what is missing for me is the path from which a unit originated.

**Comment by YHNdnzj** [comment]
Fixed by https://github.com/systemd/systemd/commit/e8630e695232bdfcd16b55f3faafb4329c961104 already, closing.
