### ISSUE TITLE
nofail drive option not default for non root partition drives

### ISSUE THREAD

**Issue by GABeech** [systemd/systemd#5836]
### Submission type

  - [x] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 219 (But all versions of systemd have this issue)

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> CentOS 7

### In case of bug report: Expected behavior you didn't see

> When a non-root Hard drive is not longer physically present, but still listed in /etc/fstab I expect the system to continue booting as normal (with a warning level message) to allow me to fix the issue without having to resort to single user mode to edit /etc/fstab.

### In case of bug report: Unexpected behavior you saw

> When a Virtual disk fails in my server and the server is rebooted, it goes into emergency mode due to 

### In case of bug report: Steps to reproduce the problem

> Remove drive that is listed in /etc/fstab, reboot

The request here is fairly simple: 

1. Non-root partition drives (any drive not needed for the OS to boot to a minimal operational state) should be nofail as the default. 

Essentially, if the drive is not required for Linux to boot there is no reason to halt the box and drop into emergency mode. Some very common scenarios where forgetting to comment out a drive before rebooting will bite you are: 

* Rebooting to reconfigure a RAID back Virtual Disk - in this case you need to reconfigure and reformat before mounting
* Replacing a failed drive
* Replacing a failed Virtual Disk on RAID hardware

Systemd's current behavior is a regression from before Systemd was a thing where the only time you would hit an emergency console is when the underlying drive on the boot partition had failed in some way. 

Additionally, having the default behavior be to fail instead of the reverse causes extra overhead and work for operations teams since for the vast majority of times you don't want the whole machine to not come up when a non-critical drive fails.

**Comment by poettering** [comment]
This has been discussed multiple times before. However: it's generally not a good idea to ignore such mount failures due to security reasons: it's simply not safe to continue booting by default if a configured file system doesn't show, because this might reveal files and directories lying underneath that shouldn't really be visible, and wouldn't be if the mount would have succeeded properly. The stuff becoming accessible might have access permissions that are problematic if they suddenly come into effect but normally aren't. Moreover if writes to the relevant dirs suddenly hit the wrong file system taking away it's disk space this is a problem of its own. In addition a variety of other security problems might arise if failures like this are transient and programs sometimes write in the mounted file system and sometimes not. For example: let's say you split out /var/log/journal, and every now and then it fails to mount but we continue booting. Suddenly all writes go to the file system underneath. If you then run journalctl you'll not see an earlier logs. But if you then reboot and suddenly the mount works again you'll not be able to see the journal entries of the intermediary boot. And that's particularly bad.

systemd cares for the "nofail" mount option here, and I am pretty sure that's the right thing to do, and in line with its original definition (after all that mount option predates systemd by a long shot): it's better be safe than sorry. Hence we require admins to explicitly mark mounts that are not essential with "nofail" to get the behaviour you are looking for. It must be up to the admin whether he thinks its safe that the directory underneath is a safe replacement should the mount fail.

Note that "nofail" doesn't have any effect on the root file system though, as the system is entirely incapable of booting up if the root disk isn't found since the OS itself is stored on it after all...

I hope the above makes sense. Sorry if this is disappointing. Closing.
