### ISSUE TITLE
systemd-update-done: Failed to move "(null)" to "/etc/.updated": File exists

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#5861]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

ccefd046c6c68520f91e49165a4f79f38ca0428e

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Gentoo

### Summary

systemd-update-done.service failed on my last reboot.

```
Apr 29 19:45:57 naomi systemd[1]: Starting Update is Completed...
Apr 29 19:45:57 naomi systemd-update-done[620]: Failed to move "(null)" to "/etc/.updated": File exists
Apr 29 19:45:57 naomi systemd[1]: systemd-update-done.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 19:45:57 naomi systemd[1]: Failed to start Update is Completed.
Apr 29 19:45:57 naomi systemd[1]: systemd-update-done.service: Unit entered failed state.
Apr 29 19:45:57 naomi systemd[1]: systemd-update-done.service: Failed with result 'exit-code'.
```

I suspect this was broken by 5a1d67639d8d3c25f817cf2958348c3f3193a573.

**Comment by floppym** [comment]
CC @codekipper @keszybz

**Comment by poettering** [comment]
ah, right, this can't work... O_TMPFILE is useless for atomically updating files since there's no way to atomically link an O_TMPFILE and replacing any pre-existing target. There's only a way to link it if the target doesn't exist yet. This means we cannot use O_TMPFILE for this case and instead have to always use a linked file and rename()...
