### ISSUE TITLE
Can't sync time when time is incorrect due to dnssec

### ISSUE THREAD

**Issue by sjoerd-ccu** [systemd/systemd#5873]
### Submission type
  - [x ] Bug report
### systemd version the issue has been seen with
233
### Used distribution
Debian

### In case of bug report: Steps to reproduce the problem
On systems without an RTC battery (typical little arm devboards) I'm running into an interesting issue where on boot the system time is set to something reasonably by timesyncd (e.g. last recorded date/time) but can still be a few days or weeks of depending on when the board was last turned on.

Unfortunately, the time being wrong causes all DNS lookups via resolved to fail (invalid signatures) which means timesyncd can never contact an ntp server to correct time..

Not entirely sure what a proper solution could be here; Downgrading when getting expired certificates while the system isn't ntp synchronized could be one option ofcourse.

**Comment by grawity** [comment]
Something like [tlsdate](https://github.com/ioerror/tlsdate) or [roughtime](https://www.imperialviolet.org/2016/09/19/roughtime.html) would be necessary to remain secure. (I think OpenBSD's ntpd will pick up the rough time from TLS as well.)

**Comment by poettering** [comment]
There's a bit of a chicken and egg problem here: you need dnssec for authenticating the time server name, but you need correct time for authenticating dnssec...

I figure timesyncd at least should turn off DNSSEC validation explicitly when doing lookups, to break this cycle. And for the other NTP servers implementations I figure a way out would be to make nss-resolve introduce an env var $NSS_RESOLVE_DISABLE_DNSSEC or so, which when set would make all lookups bypass DNSSEC...

**Comment by keszybz** [comment]
Right. I need to dig up and finalize my dnssec-mode-per-request patch set. Yet another reason to do that. But I don't think this is v234 material.

**Comment by fuelflo** [comment]
@keszybz @poettering any progress with this one yet?

**Comment by ranolfi** [comment]
@keszybz Would you be willing to share the unfinished patch set? I can review it and maybe finish your work.

**Comment by nagualcode** [comment]
this is important

**Comment by gearhead** [comment]
3 years old and still no work around other than to disable DNSSEC? I am spinning my wheels on this one as well. All Pis and others w/o battery rtc will probably suffer from this.

**Comment by DLGolden** [comment]
I've been following this since I got my Raspberry PI 4 because it was a pain. But all most all of the articles I read said that disabling DNSSEC accross was a bad idea. If it wasn't for the PI not having a RTC the problem wouldn't exist. So I approached as strictly a work around issue and created a script to work around the problem. It only happens a boot, so why not just set the time before time sync is started.

**Comment by DLGolden** [comment]
This is the content of set-date shell script:
```
#!/bin/sh -e

# Depending on the how long the pi has ben powered down,
# it is likely that the defalt setting for the resolver
# will fail with DNSSEC error and the system timesync
# cannot reach any ntp serers to set the clock. To work
# around this we can use nslookup to get the address
# and set the date from a web page (google.com) in this
# case.

NAMESERVER='192.168.1.254'	# Name server for local net
WGETTARGET='google.com'		# Target to obtain date

# Setup regexpr for IP version 4 and 6
IPv4RE='^Address: +[[:digit:]]+\.'
IPv6RE='^Address: +[[:xdigit:]]*\:'

# Uncoment one of the folowing depending on your
# IP version
UseRE=$IPv4RE	# For IPv4
#UseRE=$IPv6RE	# For IPv6

if TargetAddr=$(/usr/bin/nslookup $WGETTARGET $NAMESERVER | \
		/bin/grep -E "$UseRE")
then
	#echo $TargetAddr
	:
else
	exit
fi

/bin/date -s "$(wget -qSO- --max-redirect=0 $TargetAddr 2>&1 | grep Date: | cut -d' ' -f5-8)Z"

exit
```
I actually put this code into /etc/rc.local

**Comment by gearhead** [comment]
@DLGolden Looks like nice solution. 
My solution has been to disable systemd-resolved and use resolvconf on my RPis. I am no expert, but DNSSEC and systemd-resolved seems to be desired/needed when the device in question is a router. I noted that a full Arch install with NetworkManager on the desktop does not enable systemd-resolved. I have used dig and dnslookup on the RPi and it appears that DNSSEC is used when a DNS lookup is successful from the RPi without systemd-resolved. If I am off base, please educate me. If this logic is sound, it seems strange that systemd-resolved would default to be 'enabled' unless asked or unless used with systemd-networkd. I am using connman/iwd and have *much* better lookup and ping times w/o systemd-resolved.

**Comment by voidpointertonull** [comment]
Wondering if I'm missing something, or if the workaround regressed, but I'm once again in the odd situation of having a silly system which fails to synchronize time due to the block being off, and DNSSEC being enabled.

The setup is a not particularly heavily modified Ubuntu 24.04 environment configured to use systemd-resolved.
What's odd, that even avoiding systemd-timesyncd, and going straight for `SYSTEMD_NSS_RESOLVE_VALIDATE=0 resolvectl query ntp.ubuntu.com` shows `ntp.ubuntu.com: resolve call failed: DNSSEC validation failed: signature-expired`.

Some searching shows that SYSTEMD_NSS_RESOLVE_VALIDATE usage might require nss-resolve to be used in nsswitch.conf which is definitely not the default configuration in Ubuntu at least, but resolvectl doesn't even seem to check that config, presumably just going straight for systemd-resolved.

Guessing that maybe resolvectl doesn't actually support SYSTEMD_NSS_RESOLVE_VALIDATE as it's documented to be a part of nss-resolve, I also restarted systemd-timesyncd after changing nsswitch.conf to include nss-resolve, but could only observe the continued log spam of DNSSEC validation failures. The configuration of systemd-timesyncd doesn't appear to be the issue as `Environment=SYSTEMD_NSS_RESOLVE_VALIDATE=0` is present.

A more generic approach like #34230 would have saved me (and others using different resolvers), but it's still odd that seemingly `SYSTEMD_NSS_RESOLVE_VALIDATE=0` isn't working.
