### ISSUE TITLE
document that SELinuxContext= gets silently ingnore when used together with User=/Group=

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#5875]
### Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with
233
> …

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution
fedora 26
> …

### In case of bug report: Expected behaviour you didn't see
SELinuxContext= does not work when used together with User= and/or Group=
Systemd with *silently* ignore SELinuxContext= in this case

> …

### In case of bug report: Unexpected behaviour you saw

systemd silently ignores SELinuxContext= when used together with User= and/or Group=

> …

### In case of bug report: Steps to reproduce the problem

Create a service unit that sets both User= , Group=, as well as SELinuxContext=
Note that systemd silently ignores SELinuxContext=
Now comment out User=, Group=
Note that systemd honors SELinuxContext=

> …

**Comment by poettering** [comment]
This is not how this is implemented. We'll first change the uid/gid, and then will always fix up the selinux context if one is configured. If that works and what precisely it results in is up to the libselinux code and policy howver.

hence, there's nothing to document here, as the code is properly invoking setexeccon() in any case.

I am not an selinux guru and the implications of user id switching on selinux transitions using setexeccon() aren't clear to me. Hence I am not sure how to suggest you to debug this best. However, for starters I'd use "strace -p1 -f" right before forking off tell systemd to start such a service. It's also a good idea to provide us with the unit file here you are reproducing this with. Moreover, please check "systemctl show" on the unit and look for User=/Group=/SElinuxContext= in the output and verify it was correctly set.

**Comment by garyttierney** [comment]
> I am not an selinux guru and the implications of user id switching on selinux transitions using setexeccon() aren't clear to me. 

This wouldn't be an issue.  SELinux doesn't care about UIDs.

> It's also a good idea to provide us with the unit file here you are reproducing this with.

It's quite simple to reproduce. I changed the type of /usr/bin/sleep (`chcon -t httpd_exec_t /usr/bin/sleep`) to test it and created a simple unit which sleeps for 500s:

```
[Unit]
Description=Foo

[Service]
SELinuxContext=system_u:system_r:httpd_t:s0:c666
ExecStart=/usr/bin/sleep 500

[Install]
WantedBy=multi-user.target
```

This works correctly as shown:

```
> $ ps auxZ | grep sleep                                                                                                                                                                                                                                                                                                       
system_u:system_r:httpd_t:s0:c666    root     23588  0.0  0.0 114540   728 ?        Ss   13:22   0:00 /usr/bin/sleep 500
```

After we add `User=` and `Group=` directives and do the `systemctl daemon-reload && systemctl restart {...}` dance, we get the correct user and group, but not the correct SELinux context.

```patch
+User=gtierney
+Group=gtierney
```

```
> $ ps auxZ | grep sleep
system_u:system_r:httpd_t:s0    gtierney 25710  0.0  0.0 114540   744 ?        Ss   14:11   0:00 /usr/bin/sleep 500
```

I would expect this process to have the correct label of `system_u:system_r:httpd_t:s0:c666`, instead SELinux transitions automatically because a manual transition wasn't requested by systemd.

> However, for starters I'd use "strace -p1 -f" right before forking off tell systemd to start such a service.

Good idea.  This is strace output from a unit including `User=/Group=/SELinuxContext=`

```
[pid 13131] setrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4*1024}) = 0
[pid 13131] setresuid(1000, 1000, 1000) = 0
[pid 13131] prctl(PR_GET_SECUREBITS)    = 0
[pid 13131] capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, NULL) = 0
[pid 13131] capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=0, permitted=0, inheritable=0}) = 0
[pid 13131] getuid()                    = 1000
[pid 13131] execve("/usr/bin/sleep", ["/usr/bin/sleep", "500"], [/* 7 vars */]) = 0
```

And this is output from a unit only including `SELinuxContext=` and not `User=` or `Group=`.

```
[pid  9830] setrlimit(RLIMIT_NOFILE, {rlim_cur=1024, rlim_max=4*1024}) = 0
[pid  9830] prctl(PR_GET_SECUREBITS)    = 0
[pid  9830] capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, NULL) = 0
[pid  9830] capget({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=1<<CAP_CHOWN|1<<CAP_DAC_OVERRIDE|1<<CAP_DAC_READ_SEARCH|1<<CAP_FOWNER|1<<CAP_FSETID|1<<CAP_KILL|1<<CAP_SETGID|1<<CAP_SETUID|1<<CAP_SETPCAP|1<<CAP_LINUX_IMMUTABLE|1<<CAP_NET_BIND_SERVICE|1<<CAP_NET_BROADCAST|1<<CAP_NET_ADMIN|1<<CAP_NET_RAW|1<<C
AP_IPC_LOCK|1<<CAP_IPC_OWNER|1<<CAP_SYS_MODULE|1<<CAP_SYS_RAWIO|1<<CAP_SYS_CHROOT|1<<CAP_SYS_PTRACE|1<<CAP_SYS_PACCT|1<<CAP_SYS_ADMIN|1<<CAP_SYS_BOOT|1<<CAP_SYS_NICE|1<<CAP_SYS_RESOURCE|1<<CAP_SYS_TIME|1<<CAP_SYS_TTY_CONFIG|1<<CAP_MKNOD|1<<CAP_LEASE|1<<CAP_AUDIT_WRITE|1<<CAP_AUDIT_CONTROL|1<<CAP_SETFCAP|1<<CAP_MAC_OVE
RRIDE|1<<CAP_MAC_ADMIN|1<<CAP_SYSLOG|1<<CAP_WAKE_ALARM|1<<CAP_BLOCK_SUSPEND|1<<CAP_AUDIT_READ, permitted=1<<CAP_CHOWN|1<<CAP_DAC_OVERRIDE|1<<CAP_DAC_READ_SEARCH|1<<CAP_FOWNER|1<<CAP_FSETID|1<<CAP_KILL|1<<CAP_SETGID|1<<CAP_SETUID|1<<CAP_SETPCAP|1<<CAP_LINUX_IMMUTABLE|1<<CAP_NET_BIND_SERVICE|1<<CAP_NET_BROADCAST|1<<CAP_
NET_ADMIN|1<<CAP_NET_RAW|1<<CAP_IPC_LOCK|1<<CAP_IPC_OWNER|1<<CAP_SYS_MODULE|1<<CAP_SYS_RAWIO|1<<CAP_SYS_CHROOT|1<<CAP_SYS_PTRACE|1<<CAP_SYS_PACCT|1<<CAP_SYS_ADMIN|1<<CAP_SYS_BOOT|1<<CAP_SYS_NICE|1<<CAP_SYS_RESOURCE|1<<CAP_SYS_TIME|1<<CAP_SYS_TTY_CONFIG|1<<CAP_MKNOD|1<<CAP_LEASE|1<<CAP_AUDIT_WRITE|1<<CAP_AUDIT_CONTROL|
1<<CAP_SETFCAP|1<<CAP_MAC_OVERRIDE|1<<CAP_MAC_ADMIN|1<<CAP_SYSLOG|1<<CAP_WAKE_ALARM|1<<CAP_BLOCK_SUSPEND|1<<CAP_AUDIT_READ, inheritable=0}) = 0
[pid  9830] getuid()                    = 0
[pid  9830] open("/proc/thread-self/attr/exec", O_RDWR|O_CLOEXEC) = 3
[pid  9830] write(3, "system_u:system_r:httpd_t:s0:c66"..., 34) = 34
[pid  9830] close(3)                    = 0
[pid  9830] execve("/usr/bin/sleep", ["/usr/bin/sleep", "500"], [/* 3 vars */]) = 0
```

We see a getuid() call immediately preceding the setexeccon() call.  It looks like systemd only wants to setexeccon() when UID == 0 for some reason, so setexeccon is not being correctly invoked (it's not being invoked at all).

This comes from here:

```C
bool mac_selinux_use(void) {
        if (!mac_selinux_have())
                return false;

        /* Never try to configure SELinux features if we aren't
         * root */

        return getuid() == 0;
}
```

What is the rationale behind this?  Unprivileged users can configure SELinux features with no problems or drawbacks on the system.  And as seen here, preventing them from doing that could cause its own problems.


As an aside from this...

> Moreover, please check "systemctl show" on the unit and look for User=/Group=/SElinuxContext= in the output and verify it was correctly set.

I thought this was strange... `SElinuxContext=` doesn't appear in `systemctl show` output in either case, but as shown in the first working example it is being applied.  This is probably an unrelated bug.

Output from `systemctl show my-service-test` with a working unit (i.e., without `User=` and `Group=`) - http://pastebin.centos.org/85031/raw/
Output from `systemctl show my-service-test` with the failing unit (with `User=` and `Group=`) - http://pastebin.centos.org/85036/

**Comment by fsateler** [comment]
> What is the rationale behind this? Unprivileged users can configure SELinux features with no problems or drawbacks on the system.

#1941 was filed, and 6355e75610a8d47fc3ba5ab8bd442172a2cfe574 introduced this check.

**Comment by ghost** [comment]
That was a mistake. He jumped the gun. It should be reverted. This commit breaks all things all over.

The solution to issue #1941 was really simple: Just do not log to audit if you don't have access. Use journal instead.

**Comment by poettering** [comment]
I figure we sould actually check for the context we run in, i.e. whether Manager->running_as == MANAGER_SYSTEM.

**Comment by ghost** [comment]
We just need that commit reverted because:

We need working socket activation for systemd --user
We need the ability to contain systemd --user and to contain access to its assets
We need to be able to user SELinuxContext= together with User=

Why are you so adverse about reverting that commit? You admit that you aren't a SELinux Guru (to say the least), yet you decide about these issues so easily without even realising the implications of your decisions

**Comment by mbiebl** [comment]
@doverride please calm down. Let's keep this discussion civil

**Comment by poettering** [comment]
@doverride well, selinux support in systemd is generally something we expect the selinux hackers to maintain because the systemd hackers only have a finite knowledge of it, and I am pretty sure we'll not turn on explicit selinux transition support on anything unless the selinux hackers ask us to, already because selinux operations not defined in the policy are unlikely to work. They didn't really request us to turn it on for --user (their original patches were added when there was no properly supported --user functionality, and simply didn't cover that case at all), hence I am pretty sure it should stay off, until they ask for it.

hence, if this stuff is important to you, then make sure the selinux people care, get involved, understand what the systemd concepts involved mean, and send us patches/tell us what to do, and simulatenously with these changes also update the selinux database.

This isn't any different for SMACK support or apparmor support or anything else btw, which requires external policy support and which isn't really the stuff we fully grok.

**Comment by ghost** [comment]
The --user functionality *was* working fine with the exception that unprivileged users aren't allowed to log to audit. This is no different with dbus --session which is also a SELinux user space object manager. It was a mistake to remove this functionality. The fact that unprivileged users cannot use audit has little to do with SELinux. Linux audit is a different beast altogether.

**Comment by poettering** [comment]
well, as you just said, it didn't work correctly: selinux called into audit where it really shouldn't have. I'll leave it to the libselinux folks to figure that one out...

**Comment by garyttierney** [comment]
@poettering 

I'm not sure that we need the check for run_as == MANAGER_SYSTEM.  Consider a --user unit that uses socket activation (PulseAudio for example).  When the socket is created for the respective service and setsockcreatecon() is about to be called, systemd will evaluate the check for mac_selinux_use() to false since neither run_as == MANAGER_SYSTEM or getuid() == 0.  With this we wind up with a mislabelled socket and correctly labelled service, which I think is a bug.  From what I can see this would previously have been fine until the getuid() == 0 check was introduced.

if the concern is preventing unprivileged users from abusing SELinux features, then we can always apply far finer access controls in policy.

**Comment by ghost** [comment]
@stephensmalley could you please comment on the following:

> well, as you just said, it didn't work correctly: selinux called into audit where it really shouldn't have. I'll leave it to the libselinux folks to figure that one out...

**Comment by ghost** [comment]
> They didn't really request us to turn it on for --user i original patches were added when there was no properly supported --user functionality, and simply didn't cover that case at all), hence I am pretty sure it should stay off, until they ask for it.

It was turned on from day 1. The moment **you** turned it **off** i went up in arms. I practically begged you to not remove that functionality. You ignored me. Now a year later all kinds of issues related to your decision surface. Sorry if i cannot be sympathetic

I have hundreds of packages installed. Am i expected to work on all of them? Do I get any time to work on my own project? Maybe I should just pay for a Microsoft license...

**Comment by stephensmalley** [comment]
FWIW, dbus code added this code to fix the audit issue before calling audit_open():
capng_get_caps_process ();
if (!capng_have_capability (CAPNG_EFFECTIVE, CAP_AUDIT_WRITE))
    return;

So audit_fd remains -1 if the process lacks CAP_AUDIT_WRITE, and therefore the logging callback function never tries to send it to audit.  I assume systemd could do the equivalent in its get_audit_fd() function.

It isn't a problem with the SELinux code.  libselinux just calls the callback provided by systemd, and the systemd callback (log_callback) tries to write to the audit socket if audit_fd has been set.  Just fix get_audit_fd() to not set the audit_fd unless we can write to it.

systemd shouldn't disable SELinux transitions, labeling, etc for non-root uid  or --user.

cc @rhatdan

**Comment by garyttierney** [comment]
I have a tree here based on Stephen's comments which should do the trick: https://github.com/garyttierney/systemd/tree/fix-selinux.  Tests pass and everything seems to be in working order, will submit a PR once I've verified everything works how we'd want it to.

We reinstate systemd --user instances as userspace object managers by removing the getuid() == 0 test, and just prevent them from logging from auditd when it's not available.

**Comment by stephensmalley** [comment]
LGTM.

**Comment by poettering** [comment]
#5883 (the supposed fix) looks really strange to me, as it second-guesses the kernel before opening the audit socket. I mean, we general leave it to the kernel to deny stuff to us, why would we check this first on our own here? 

If the issue at hand is really just about suppressing audit for user stuff, then it sounds much cleaner to me to try to opening it, and accept if we get EPERM back, and simply proceed without.

**Comment by garyttierney** [comment]
@poettering with what you've proposed we still see the intended behaviour, but we get unwanted error messages logged to the journal when trying to open an audit socket for unprivileged users (since we don't want to bother trying for those processes).

However, I don't think this is a real problem and agree that the EPERM check would be a better solution, so I think we can go with that and deal with the error message separately.

**Comment by stephensmalley** [comment]
audit_open() won't fail; that's the point.  You don't need CAP_AUDIT_WRITE to open the audit socket; you just need it to send userspace audit messages via it.  Checking CAP_AUDIT_WRITE before trying to open is what dbusd does currently.

**Comment by garyttierney** [comment]
Ah... Stephen is right, my mistake.  We don't see the problem until we hit this condition https://github.com/systemd/systemd/blob/master/src/core/selinux-access.c#L120-L132.

**Comment by stephensmalley** [comment]
To be clear, the failure occurs within audit_log_user_avc_message() in libaudit.
Looking at audit sources, audit_log_user_avc_message() doesn't propagate the error return if the caller lacks CAP_AUDIT_WRITE; it just falls back to calling syslog() with "Can't send to audit system:" followed by the audit message, and then returns 0.
So systemd never sees EPERM at all, neither from audit_open() nor audit_log_user_avc_message().
Anyway, leaving audit_fd < 0 if the process lacks CAP_AUDIT_WRITE is more efficient and cleaner, because then we skip all audit-related processing and fall back to internal logging as appropriate.  The only reason to set audit_fd if you lack CAP_AUDIT_WRITE is if you are a listener of audit messages.

**Comment by poettering** [comment]
i really don't like this second guessing of the kernel permission checks, I'd much prefer if we could just issue the audit message and deal gracefully if it fails with EPERM... but ok
