### ISSUE TITLE
document incompatibility of --private-users and --bind (or maybe even revert this bit in systemd-nspawn@.service)

### ISSUE THREAD

**Issue by RussianNeuroMancer** [systemd/systemd#5900]
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232, 233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu Server 17.04, 17.10, both with Linux 4.10.

### In case of bug report: Expected behaviour you didn't see

> Owner and group of folders from Bind directory (from host into container) is same in nspawn container and on host, like it was with systemd 229.

### In case of bug report: Unexpected behaviour you saw

> Owner and group of few files and folders from Bind directory visible as nobody/nogroup when I check permission from within nspawn container.

### In case of bug report: Steps to reproduce the problem

> Create testing.nspawn: 
> ```
> [Files]
> Bind=/patch/to/folder
> ```
> Use some folder with many subfolders, to expand the test coverage. Check if owners of all subfolders and files in Bind directory inside container is the same as on host.

**Comment by RussianNeuroMancer** [comment]
Issue is also reproducible for files and folder within container, if container is btrfs subvolume instead of disk image. Example:
```
~$ LANG=C sudo whoami
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
~$ LANG=C ls -l /usr/bin/sudo
-rwsr-xr-x 1 nobody nogroup 140944 Jan 14 07:41 /usr/bin/sudo
~$ LANG=C ls -l /var/lib/machines/builder/usr/bin/sudo
-rwsr-xr-x 1 root root 140944 Jan 14 07:41 /var/lib/machines/builder/usr/bin/sudo
```

**Comment by poettering** [comment]
This is a side effect of the "private users" logic (i.e. user namespacing). Consider dropping --private-users= from your instance.

**Comment by poettering** [comment]
(I figure we need to document that better, and possibly not default to userns anymore...

**Comment by RussianNeuroMancer** [comment]
> Consider dropping --private-users= from your instance.

It wasn't set before. I set it to 0, and this fixes issue for me. Report can be closed or keep it until you make this changes? 

> we need to document that better, and possibly not default to userns anymore

**Comment by agowa** [comment]
I noticed the same behavior and want to add my thoughts about it.
It is obvious by design of the separated namespaces. This point should not be changed.
But what I would expect either
a) The bind directory getting owned by the root user (if not part of the containers namespace) within the container
or
b) nspawn proxies the requests to these files, so that they are accessed as the user nspawn was invoked with on the host side and root (initially) within the container. Of course this would require to store some mapping separately.
or
c) using acls to store additional permissions on the mounted files within the acl tables (would require that the filesystem is mounted with acls), this would require the least development. But I personally would want a way to specify the permissions for the mount point within the unit (.nspawn) file. So that my containers are stateless and my content being outside the container.

For b and c the (additional) permissions (new owner and group) could be stored within the "Bind=" command line as additional parameters.

e. g. without changing permissions (currently):
```
--bind=/etc/FooBar
--bind=/opt/BarFoo,/etc/BarFoo
```
or within an unit file:
```
[Files]
Bind=/etc/FooBar
Bind=/opt/Bar,/etc/BarFoo
```

with changing permissions (proposed addition):
```
--bind=/etc/FooBar,,root,root
--bind=/opt/BarFoo,/etc/BarFoo,,root,root
```
or within an unit file:
```
[Files]
Bind=/etc/FooBar,,root,root
Bind=/opt/BarFoo,/etc/BarFoo,root,root
```

Personally I prefer c and for systems not supporting acl's b (or acl's being implemented by systemd :p ).

Current workaround (if this is considered the best solution, only adding this to the documentation is enough for me):
add an acl (or change user and group to) the id of an user within the container.
For that first do:
`ls -al /var/lib/machine/CONTAINERNAME/bin/bash`
and note the number displayed in the user and group section of ls.
Now just do
```
setfacl -m "u:$UserID:$Permissions" /path/to/bind/dir
setfacl -m "g:$GroupID:$Permissions" /path/to/bind/dir
```
or
`chown $UserID:$GroupID /path/to/bind/dir`

**Comment by poettering** [comment]
Fix waiting in #7365

**Comment by poettering** [comment]
uh, normally, github will close issues automatically, when the matching PR is merged. No need to merge that manually.

**Comment by ochilan** [comment]
I know this issue is closed but since the systemd update hit me today on my server and basically rendered all containers unusable, I still have a question about the new behavior:

If I wish to share a certain directory on the host with several containers, and I also wish to use the private-users option, what is the way to go regarding permissions on the host? Setting up an ACL containing all the UIDs of the users of each container?

Also, what about binding e.g. devices from /dev to containers (e.g. when using X11 in a container). Can I set ACLs on devices? Or is it better not to use private-users in the first place in this case?

**Comment by yuwata** [comment]
@ochilan Please file as a new issue. This is a documentation issue.

**Comment by poettering** [comment]
@ochilan actually, I think questions like yours are best discussed on the mailing list. This is a bug and RFE tracker, and general discussions and Q&A should take place on the mailing list. Thanks.
