### ISSUE TITLE
Control over forward logs in journald

### ISSUE THREAD

**Issue by rfrail3** [systemd/systemd#5938]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> v232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch

As a plus over the options ForwardToSyslog=, ForwardToKMsg=, ForwardToConsole=, ForwardToWall=, it would be helpfull  to control wich of all logs do you need to forward.

For example, send the logs from a particular unit or syslog facility/severity level to a particular receiver.

**Comment by poettering** [comment]
uh, I am not convinced this would really be a good idea. journald is not supposed to be a generic rule engine. If you want such a system, consider configuring that in rsyslog or syslog-ng or whatever you connect to journald via the forwarding logic...

**Comment by poettering** [comment]
(also note that a number of distros don't use the forwarding logic at all anymore, but instead make rsyslog read the log data directly from the journal, so that the get the extended metadata it provides. THat's why syslog forwarding is actually disabled by default these days. And I'd claim that such a solutoin is much preferrable, and hence I am not very keen on extending the forwarding logic any further...)

**Comment by rfrail3** [comment]
Ok Lennart, you know what it's the scope of this part of the project, thanks for the clarification.

For those interested in the rsyslog module "imjournal": http://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html
