### ISSUE TITLE
Add "CPUQuota" property to systemd dbus interface

### ISSUE THREAD

**Issue by yunchih** [systemd/systemd#5939]
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### Description

It seems that the `CPUQuota` property cannot be set via the dbus interface `org.freedesktop.systemd1.Manager`: I will get 

```
org.freedesktop.DBus.Error.PropertyReadOnly: Cannot set property CPUQuota, or unknown property.
```

This property is used in my project to limit user session CPU usage and I think it might be useful
to other users as well.  Maybe consider adding it?  Thanks!

**Comment by poettering** [comment]
the property is read-only. In fact all our unit properties are exposed read-only only. Please use the Unit interfaces' SetProperties() call instead, which permits you to change multiple propertries at the same time.

Also, the property is called "CPUQuotaPerSecUSec" via that function, because it is normalized differently thatn the configuration file optoin.

This all is a bit underdocumented, admittedly. Please have a look at what "systemctl set-property" does in the sources for details
