### ISSUE TITLE
RFE: Decouple the implicit Requires= from BindsTo=

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#5966]
### Submission type

  - [ ] Bug report
  - [X] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

BindsTo= does not imply Requires=, user/generator can add Requires= or nothing depends on the actual necessity; in other word BindsTo= should be a pure complement to PartOf=

### In case of bug report: Unexpected behaviour you saw

BindsTo= implies Requires=. While users often want BindsTo= for its "stop upon failure / disappearance" part, they do not necessarily need/want the Requires= part (i.e. start job). The current way BindsTo= is implemented prevents user from having the flexibilty when they only want the former. It is also problemtic and probably non-sensical when the listed unit is a device.

This is especially true when user service is considered. In the case of system service, user may be able to configure the service to be wanted only by the device it binds to instead of the default target, so the implicit Requires= wouldn't really matter and hence cause no trouble. However, if it is a user service, we sort of need it to be wanted by both the default target and the device, to guarantee that it will be started no matter the device is inserted before login or after login.

### In case of bug report: Steps to reproduce the problem

```
[Unit]
BindsTo=sys-subsystem-sound-devices-%i.device

[Service]
ExecStart=/usr/bin/jackd -d alsa -d hw:%I -P -r 44100
KillSignal=SIGKILL

[Install]
WantedBy=default.target sys-subsystem-sound-devices-%i.device
```

**Comment by poettering** [comment]
Well, we can't change behaviour of the deps drastically like this, for compatibility reasons, even if we wanted.

**Comment by tomty89** [comment]
Yeah I am aware of that after some testing. I bail. Closing.

**Comment by poettering** [comment]
(Note that I am not totally opposed to adding new dep types, but we need to a very convincing case for that)

**Comment by tomty89** [comment]
@poettering It seems to me that it would be great if there is a dep type that checks only whether a device exists / is active (note: I thought of Requisite but it apparently doesn't work as expected for device).

**Comment by tomty89** [comment]
A dep type that works like BindsTo= but implies Requisite= instead of Requires=? I wonder if we can add a Requisite= check to BindsTo=, that is, if both exists for the same unit, spawn JOB_VERIFY_ACTIVE instead of JOB_START.

**Comment by poettering** [comment]
> A dep type that works like BindsTo= but implies Requisite= instead of Requires=? I wonder if we can add a Requisite= check to BindsTo=, that is, if both exists for the same unit, spawn JOB_VERIFY_ACTIVE instead of JOB_START.

Hmm, interesting idea, I think I like it, and I can't think of anything wrong with such an approach. If you prep a patch and test it I'd review/merge it...

**Comment by bl33pbl0p** [comment]
@tomty89 If you just care about propagation on stop/restart/disappearance that cause state change, use Before= with BindsTo=, this will cause the job to be enqueued, but your unit will have its job dispatched (and checked against unit state for completion) before the unit bound to does. However, since there is a job waiting on us (at the very least) the internal checks for BindsTo= do not do anything.

**Comment by bl33pbl0p** [comment]
Hmm, so I thought about this a bit.

I initially suggested Before= with BindsTo=, that gives semantics of not waiting on the bound unit's job (seems GH nuked my comment) (but yours doesn't fail either because the internal check treats a job's existence in unit's job slot as something fine). Also, the device unit's start job cannot wait on anything else (but on the device through the internal state machine) so it gets deleted. However, when the device gets plugged in (or was already plugged in ofcourse), if and ever, going to inactivate will propagate stop jobs to your unit.

Now, this does pull in the unit's start job in the transaction, and you don't get Requisite= like semantics (but if and ever the device becomes active and then goes to inactive, you will react to inactive change, and the job ordered after us will not make us fail really). However, I don't think this required yet another dependency type that replaces start job propagation with verify active propagation.

Since BindsTo= conflates two orthogonal concepts (start job propagation from the subject and stop/restart propagation on all those state changes that either make it go to inactive/failed or due to jobs triggered on unit), it will be better if the new dependency type only does propagation in case of retroactively triggering stop jobs for the units bound to it only in case of abrupt state change not caused by job engine.

This would mean this new InterruptedBy= directive or so would have to be combined with Requires=, PartOf= and After= to get effect like BindsTo=, but could be used alone or with the combination of any of those (or Requisite=) thereof.

If this approach is acceptable, I can try working on a patch (when time permits).
