### ISSUE TITLE
Broadcasts considered harmful

### ISSUE THREAD

**Issue by Bierysowihe-Kleschnie** [systemd/systemd#598]
By default, `systemd-tty-ask-password-agent` sends broadcast messages to all TTYs when it needs a user to enter a password. Maybe it can be an effective way to attract the user's attention, but it makes unusable all opened pseudographical programms like Alsamixer and causes unjustifiable pain.

Yes, it's documented behaviour, but it's not what the user can expect from the default settings and it's not easy to disable. Moreover, in most cases, the user already knows, that the password is needed, because it happens after an explicit command (or during a boot process).

Screenshots from the latest Fedora live-CD:

![one](https://cloud.githubusercontent.com/assets/8818438/8705750/28fa8aca-2b1b-11e5-8d5a-5421619da870.png)

![two](https://cloud.githubusercontent.com/assets/8818438/8705752/319b3760-2b1b-11e5-9af8-b4df7062e17f.png)

**Comment by poettering** [comment]
Sorry, but this is UNIX behaviour, since 1970s, and is exposed by tools like "write", "talk", "wall", "shutdown", "mesg", "syslog", the kernel, and more.

UNIX' solution to this is pressing Ctrl-L, which will cause a screen repaint. You'll find that alsamixer supports that as well.

Sorry, but I am pretty sure we shouldn't try to "fix" UNIX on this one. UNIX is weird, sure, but that's how it is. If you want pretty, then use a graphical UI... the terminal is the way the terminal is...
