### ISSUE TITLE
Logical order in fstab not followed

### ISSUE THREAD

**Issue by suntong** [systemd/systemd#6010]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> as early as 232-21ubuntu3, up to the latest systemd version

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu zesty 17.04

### In case of bug report: Expected behaviour you didn't see

> > The order of records in fstab is important because fsck(8), mount(8), and umount(8) sequentially iterate through fstab doing their thing, though at boot time mountall(8) may process the file out-of-order when it believes it is safe to do so. 

> I'm expecting systemd only mount in parallel when it is safe to do so. 

### In case of bug report: Unexpected behaviour you saw

> However, the systemd from 232-21ubuntu3 onward becomes too aggressive, causing my bind mount to fail. 

### In case of bug report: Steps to reproduce the problem

> This is my setup:

```
LABEL=mp1 /mnt/mp1 auto    defaults,noatime,nodiratime,barrier=1,ro 0       2
/pkg/fonts/myttf /usr/share/fonts/truetype/myttf auto bind,ro  0 2
```

And most importantly, `/pkg` is a symlink pointing to `/mnt/mp1/pkg`. Because of this "_hidden_" dependency, systemd from 232-21ubuntu3 onward failed to detect it and mount them in parallel instead. Thus causing the mount problem for me. 

The Ubuntu 16.04.1 LTS version that I'm currently using, however, does not exhibit such aggressive behavior, so my fstab is working fine within it. 

Please confirm. 
Thanks

**Comment by poettering** [comment]
Yeah, the ordering of /etc/fstab is not relevant on systemd, it will try to mount as much in parallel as possible, but also derive order from path prefixes as much as possible. It also doesn't permit duplicate /etc/fstab entries for the same path. 

So, what you are trying to do is knowingly not supported, and this is unlikely to change.

On recent systemd versions you may define manual per-mount ordering to /etc/fstab via the "x-systemd.after=" and "x-systemd.before=" mount options, see systemd.mount(5) for help.

Closing, as this is known and not supported due to explicit design decisions.

**Comment by arvidjaar** [comment]
> derive order from path prefixes as much as possible

But in this case we have `/pkg -> /mnt/mp1/pkg` link. Should not it order `/pkg/whatever` mount point after `/mnt/mp1` then?

**Comment by suntong** [comment]
Thanks @arvidjaar, that's exactly what I meant to ask.

**Comment by poettering** [comment]
> But in this case we have /pkg -> /mnt/mp1/pkg link. Should not it order /pkg/whatever mount point after /mnt/mp1 then?

systemd is designed to put together the initial transaction very early without knowing much about the existance of actual files on disks. After that it simply executes the transaction it calculated, step by step. And I believe this is the right way to do that.

Now, you may disagree with that, and I accept that. But, if we'd follow symlinks before the initial transaction already, so that we could include its effect in the initial transaction, then this would generally not work, as the symlinks might be located on a file systems that only become available as the transaction is executed step by step. Yes, it might work for some specific cases where the symlinks are located on the root partition, but not it in the general case. To cover the general case we'd have to reculculate the transaction each time a new mount becomes available, and I am convinced that's something to avoid...

Hope that makes sense?

**Comment by suntong** [comment]
Yeah, make sense to me. Thanks for explaining.
