### ISSUE TITLE
Fall back gracefully when LimitNPROC cannot be done inside an LXC container

### ISSUE THREAD

**Issue by tkedwards** [systemd/systemd#6011]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 229-4ubuntu17

### Used distribution

> Ubuntu 16.04

### The problem

When running systemd inside an LXC/LXD container loading a systemd splice unit which uses the LimitNPROC option fails. The comment from the LXC/LXD devs on this issue is:

> Setting devices.allow in the devices cgroup is not allowed for unprivileged containers for security reasons so this is not something LX{C,D} can do something about
(https://github.com/lxc/lxd/issues/3336#issuecomment-302983953)

For example:

    install openvpn and create a client config file to it as /etc/openvpn/myvpnservice.conf
    systemctl start openvpn@myvpnservice

Expected behaviour:
Starts openvpn and loads /etc/openvpn/myvpnservice.conf as the config file, just as it does on Ubuntu 16.04 NOT run inside a container

Actual behaviour:
Fails with this kind of message in the logs:

Jul 13 09:52:56 lb systemd[1]: Failed to set devices.allow on /system.slice/system-openvpn.slice/openvpn@server.service: Operation not permitted
Jul 13 09:52:56 lb systemd[1]: Failed to set devices.allow on /system.slice/system-openvpn.slice/openvpn@server.service: Operation not permitted
Jul 13 09:52:56 lb systemd[1]: Failed to set devices.allow on /system.slice/system-openvpn.slice/openvpn@server.service: Operation not permitted
Jul 13 09:52:56 lb systemd[1]: Failed to set devices.allow on /system.slice/system-openvpn.slice/openvpn@server.service: Operation not permitted
Jul 13 09:52:56 lb systemd[1]: Failed to set devices.allow on /system.slice/system-openvpn.slice/openvpn@server.service: Operation not permitted

### Requested enhancement

Currently you have to comment out the LimitNPROC line in /lib/systemd/system/openvpn@.service to get this working. Instead it would be good if systemd issues a warning but falls back gracefully to use whatever the closest available value for the given limit is.

### Related issue

https://github.com/lxc/lxd/issues/3336

**Comment by poettering** [comment]
hmm? Is this about DeviceAllow= or about LimitNPROC=? Not following?

**Comment by tkedwards** [comment]
It's about LimitNPROC. I think I quoted the wrong comment in the LXC/LXD bug, this from Stephane Graber explains it:

> the devices.allow messages aren't the problem here.
> 
> The problem is that systemd fails to spawn the unit if LimitNPROC is set to a value that the user isn't allowed to set (which happens in unprivileged containers).
> 
> You either need to override the unit or systemd needs to be changed to complain but not fail in such cases (just use whatever the closest available value for the given limit is).

**Comment by poettering** [comment]
@tkedwards we actually adjust the requested resource limit to the highest value we can set it to, see the code:

https://github.com/systemd/systemd/blob/master/src/core/execute.c#L2682
https://github.com/systemd/systemd/blob/master/src/basic/rlimit-util.c#L32

Are you saying this isn't working? What's the precise error that happens in LXC/LXD if RLIMIT_NPROC is changed?

**Comment by tkedwards** [comment]
The error message I got was:
systemd[1]: Failed to set devices.allow on /system.slice/system-openvpn.slice/openvpn@server.service: Operation not permitted

I've tried but can't reproduce the problem again, but I don't have access to the original computer where I saw it at the moment

**Comment by zabullet** [comment]
Do you think this is related to https://bugs.launchpad.net/ubuntu/+source/openvpn/+bug/1631104 ?

**Comment by evverx** [comment]
I've just read https://askubuntu.com/questions/747023/systemd-fails-to-start-openvpn-in-lxd-managed-16-04-container/ and https://bugs.launchpad.net/ubuntu/+source/openvpn/+bug/1631104.

`openvpn` seems to be run by `systemd` "successfully", but fails later with
```
daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
```
The `daemon` code looks like this
```c
int
daemon(int nochdir, int noclose)
{
#if defined(HAVE_FORK) && defined(HAVE_SETSID)
    switch (fork())
    {
        case -1:
            return (-1);

        case 0:
            break;

        default:
            exit(0);
    }
...
```
It fails to fork because of having reach the limit and removing `LimitNPROC` fixes that.

On the other hand, `daemon` is called by `possibly_become_daemon` which looks like this
```c
    bool ret = false;

#ifdef ENABLE_SYSTEMD
    /* return without forking if we are running from systemd */
    if (sd_notify(0, "READY=0") > 0)
    {
        return ret;
    }
#endif

    if (options->daemon)
    {
        ASSERT(!options->inetd);
        /* Don't chdir immediately, but the end of the init sequence, if needed */
        if (daemon(1, options->log) < 0)
        {
            msg(M_ERR, "daemon() failed or unsupported");
        }
```
that is, `daemon` shouldn't normally be called when `openvpn` is configured with `--enable-systemd`.

To sum up, `systemd` starts the daemon and sets the limit, but for some reason the daemon reaches the limit and I'm not sure this can be fixed on the `systemd` side.

It would be great to see the logs.

**Comment by zabullet** [comment]
@evverx I'm not sure you're right about the daemon function.....in this case I think it's calling http://man7.org/linux/man-pages/man3/daemon.3.html , not the compatibility version defined by openvpn

**Comment by evverx** [comment]
@zabullet , thanks for pointing this out. The function being called depends on `HAVE_DAEMON` which I missed. Anyway, the `glibc` implementation does almost the same as the `openvpn` implementation:
```c
daemon (int nochdir, int noclose)
{
        int fd;

        switch (__fork()) {
        case -1:
                return (-1);
        case 0:
                break;
        default:
                _exit(0);
        }
```

@tkedwards , have you seen the failure of `setrlimit`? If not, I think we can close the issue because it has nothing to do with `systemd`.

**Comment by poettering** [comment]
> The error message I got was:
> systemd[1]: Failed to set devices.allow on /system.slice/system-openvpn.slice/openvpn@server.service: Operation not permitted

As was indicated elsewhere: this message has nothing to do with RLIMIT_NPROC, and is mostly cosmetic.

**Comment by tkedwards** [comment]
I still don't have access to the original container where I saw this problem, but it seems I can reproduce the problem on another computer:
```
vim /lib/systemd/system/openvpn@.service # ensure LimitNPROC=10 is NOT commented out (i.e. that the file is in it's out-of-box state)
systemctl daemon-reload
systemctl start openvpn@mullvad_se # where mullvad_se is /etc/openvpn/mullvad_se.conf
```
In my /var/log/syslog I see:

```
May 29 09:27:26 vpncontainer ovpn-mullvad_se[14524]: daemon() failed or unsupported: Resource temporarily unavailable (errno=11)
May 29 09:27:26 vpncontainer ovpn-mullvad_se[14524]: Exiting due to fatal error
May 29 09:27:26 vpncontainer systemd[1]: openvpn@mullvad_se.service: Control process exited, code=exited status=1
May 29 09:27:26 vpncontainer systemd[1]: Failed to start OpenVPN connection to mullvad_se.
May 29 09:27:26 vpncontainer systemd[1]: openvpn@mullvad_se.service: Unit entered failed state.
May 29 09:27:26 vpncontainer systemd[1]: openvpn@mullvad_se.service: Failed with result 'exit-code'.
```

TBH a lot of the above comments went over my head a bit, but is there any logs or anything I can collect that might help? Or is this really not a systemd issue?

**Comment by poettering** [comment]
So the problem you are having is caused by the fact that you are running containers that do not employ user namespacing. This has the effect that the user databases of your containers are all shared, and means that all users of the same UID on the entire system (i.e. in each container and on the host) will share the very same RLIMIT_NPROC setting, and the total number of processes of the users will be counted against it. That's a well-known security hole in containers that do not user user namespacing and is nothing systemd can fix for you.

You basically have three options now:

1. The secure way: use user namespacing, so that code running in the container cannot alter limits of the host and other containers and vice versa, and can deplete the pool of processes these limits build up. This is the only way you can properly close the local DoS attack your container manager opens between local containers.
2. The hackish way: continue without user namespacing, but make sure each container assigns a different UID to the relevant user, so that each instance will count against a different limit. This will remove the error at hand, but is of course still unsecure as fuck, as each container can still deplete the process pool for everybody else, if it wants too. The only difference is that it won't do so by default.
3. Disable LimitNPROC= in all your unit files, in the contianer and in the host, for UIDs you intend to share. Doesn't remove the DoS vulnerability, and in fact makes the system a whole lot unsafe, but is a cheap way out.

THere's nothing we can do about all of this from the systemd side of things. It's a problem with your container mangaer or the way you set it up: it's the lack of isolation you get by not using user namespacing.

Closing this, as this is not a systemd problem.

**Comment by tkedwards** [comment]
Ok, thanks, makes sense now. In this case I'm the only one using that container and I also control the host, so there's no security issue. As far as I understand it if I used unprivileged containers (user namespace on the host) Openvpn running inside the container wouldn't be able to create its tunX device, so I have no choice in using priveleged

**Comment by poettering** [comment]
unprivileged containers and user namespaces are distinct.

**Comment by brauner** [comment]
So, not to turn this into a pointless discussion. :) But `LXD` uses user namespaces per default. You need to explicitly opt-in to not use user namespaces so this alone can't be the reason. @tkedwards's config file https://github.com/lxc/lxd/issues/3336#issuecomment-304622488 also shows that he's using user namespaces. What could however be a problem (I haven't completely followed the discussion.) is that he's not mapping his own {u,g}id meaning `host_{g,u}id(1000) == container_{u,g}id(1000)`. So he's mapping all other {u,g}ids but keeps his own.

**Comment by evverx** [comment]
I'd like to say that the issue has nothing to do with `lxd/lxc` as well.

The limit is reached, so the question is why this happens.

The kernel checks the [following](https://github.com/torvalds/linux/blob/d024baa58a4a7e5eb6058017771d15b9e47b56db/kernel/fork.c#L1600):
```c
	retval = -EAGAIN;
	if (atomic_read(&p->real_cred->user->processes) >=
			task_rlimit(p, RLIMIT_NPROC)) {
		if (p->real_cred->user != INIT_USER &&
		    !capable(CAP_SYS_RESOURCE) && !capable(CAP_SYS_ADMIN))
			goto bad_fork_free;
	}
``` 
but I guess you can simply count how many processes with the same uid are running.

**Comment by bt90** [comment]
> You basically have three options now:
> 
> 1. The secure way: use user namespacing, so that code running in the container cannot alter limits of the host and other containers and vice versa, and can deplete the pool of processes these limits build up. This is the only way you can properly close the local DoS attack your container manager opens between local containers.
> 2. The hackish way: continue without user namespacing, but make sure each container assigns a different UID to the relevant user, so that each instance will count against a different limit. This will remove the error at hand, but is of course still unsecure as fuck, as each container can still deplete the process pool for everybody else, if it wants too. The only difference is that it won't do so by default.
> 3. Disable LimitNPROC= in all your unit files, in the contianer and in the host, for UIDs you intend to share. Doesn't remove the DoS vulnerability, and in fact makes the system a whole lot unsafe, but is a cheap way out.

Sorry for necromancing this issue but would [TasksMax](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#TasksMax=N) be a safer alternative to option number 3 nowadays?

At least the [documentation](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Process%20Properties) seems to recommend it:

> LimitNPROC= This limit is enforced based on the number of processes belonging to the user. Typically it's better to track processes per service, i.e. use `TasksMax=`, see [systemd.resource-control(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#).
