### ISSUE TITLE
Permit "systemd --user" to select/inherit the default umask

### ISSUE THREAD

**Issue by sebasth** [systemd/systemd#6077]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Debian

### In case of bug report: Expected behaviour you didn't see

Applications launched by `systemd --user` do not inherit the *umask* from the parent process. This causes `pam_umask` to be ineffective as a way setting the default umask for user sessions with Gnome3.

In my opinion, the obvious fix would be changing `systemd --user` **not to alter the umask for applications launched by it**. Having to configure umask elsewhere, such as editing all gnome unit files locally or having a another configuration option for DefaultUmask, would only complicate system administration.

***Current configuration:***

 I've configured `pam_umask` and default umask to `0027` in `pam.d/common-session` and `pam.d/systemd-user`. These settings are applied for gnome session and "systemd --user" instance, but processes which are dbus launched via systemd have umask of 0022 instead of the desired umask 0027.

**Comment by vdcbb** [comment]
Mr. Poettering, is there a workaround for this issue until it is fixed? Using gnome 3.22 in Debian Stretch (which uses systemd for umask), how can one change the default umask?

**Comment by jamalm** [comment]
Has this been resolved?

**Comment by anthonydonegan** [comment]
Since this effectively breaks multiuser security/privacy in Debian Stretch, with no mention of it in their Release Notes, the insouciance shown by systemd, gnome and Debian personnel is astonishing. Why cannot systemd conform to decades of unix file permission usage and conventions? Why does nobody fix it?

**Comment by sourcejedi** [comment]
I noticed a problem in the opposite direction.  gnome with systemd seems to have broken a working pattern, which was used to provide group directories with default read-write access.  Exactly like the Public folder on Windows.

In some sense the common umask 0022 is over-cautious.  Modern installs tend to give users a primary group which matches their username.  Then it's reasonable for an admin to choose 0002 as a default umask.  Even if the user's home directory is accessible by others (as per Debian defaults), others will not be able to write to it.

Before systemd was used and broke inheriting the umask 0002, it allowed setting up read-write group directories, using the set-group-id mode bit.

This problem surfaced in practice as intimidating lock icons on files in the shared directory, and DigiKam being buggy and silently not updating photo metadata when asked to.

(The other possibility is to support group directories where users can only delete their own files, using the sticky bit.  umask 0022 could be used in this case.  However it excludes the other case.  Nowadays we have ACLs, so you can set umask 0002, and use `setfacl -m default:group:mygroup:r-x sticky-mygroup-dir`).

**Comment by jamalm** [comment]
I have found a workaround since i was looking , I can't say it is the most secure method but it definitely works for me using CentOS7.4 Gnome3

I posted my solution [here](https://unix.stackexchange.com/a/418224/262925) on stack exchange where many were looking for a solution to this.

**Comment by sourcejedi** [comment]
...of course the pattern I mentioned is not accidental.  It's possible I reverse-engineered it :) or just forgot where I read it.  Apparently it is documented explicitly in RedHat, going back as far as 2002 with RHL 7.3 (the original RHL, not RHEL).  Just search "linux user private group"; google finds the redhat docs and highlights a very clear [explanatory blog post](https://security.ias.edu/how-and-why-user-private-groups-unix).

**Comment by thedonquixotic** [comment]
hi All, I'm trying to set up a NextCloud server and I have gotten all my permissions issues ironed out EXCEPT for this one. Is there a fix for this? I tried @jamalm work around and it did not work for me I'm afraid. :( 

Using Ubuntu 18 link to my nextcloud forum thread for more context of what I've been donig: https://help.nextcloud.com/t/permissions-issues-on-local-external-folders/34958/9

**Comment by rmunn** [comment]
See also https://github.com/systemd/systemd/issues/901#issuecomment-131542810 where, in 2015, @poettering decided that umask should *not* be configurable system-wide. This decision was, IMHO, a mistake, because this breaks existing expectations across the board. See:

- https://bugzilla.gnome.org/show_bug.cgi?id=780622#c54
- https://unix.stackexchange.com/questions/254378/how-to-set-umask-for-the-entire-gnome-session/
- https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1685754/comments/21
- https://www.reddit.com/r/gnome/comments/6s2w0l/anybody_found_a_workaround_for_gnome_318_bug_that/

And that's with just a few minutes of Googling.

@poettering, please reconsider allowing umask to be set system-wide. The feature request in this issue (inheriting umask from the parent process) will allow setting umask in the standard `/etc/login.defs` config file. The current behavior of systemd badly breaks the Principle of Least Surprise, since `/etc/login.defs` has been the standard for years, and prevents distros and system admins from setting umask defaults in a simple way. The desired feature of having "software [not] break in unexpected ways because umask defaults to different values in different installations" is currently the opposite of reality: everything is breaking in unexpected ways because admins *cannot* set the default umask on their installation, as witnessed by the puzzlement and frustration in the bugs I've linked above.

**Comment by rmunn** [comment]
I should also note that @poettering's concern was to guarantee a "fixed, documented default for all services" to avoid confusion when unit files are moved from one system to another — and this can be addressed by keeping the behavior of `systemd --system` as-is. This issue only asks for `systemd --user` to be changed. As evidenced by the bug reports I linked to last week, most people's expectations are that user services will be affected by the system-wide umask that they have set up in `/etc/login.defs`, and that if they want something *other* than the default umask from `/etc/login.defs`, they can set it themselves in the service's unit file.

IMHO, accepting this issue would address almost everyone's concerns: unit files for system services could still count on a standard default umask that would not vary (if there's a use case for setting a global umask for *system* services, I haven't found it yet in my Googling; all the bug reports I've found are about the unexpected behavior of umask for GNOME and other *user* services), while user services would be configurable by setting umask in `/etc/login.defs` the way everyone expects.

**Comment by zaltysz** [comment]
2.5 years later it is still a problem for multiuser environments which rely on systemd user services (i.e. GNOME), but need different umask than 022.

I see that "PID1" label is assigned to this issue. Is it really appropriate? The problem isn't the system service manager which runs as pid1, the problem is user service manager (systemd --user), which runs as logged in user and spawns services for that user. 

Can we get status update from maintainers? Bugs filled against GNOME sway towards this being a systemd issue, however here it has already been hanging multiple years without resolution. Is this "more or less by design" or "patches are welcome" situation?

**Comment by Werkov** [comment]
This [invocation](https://github.com/systemd/systemd/blob/a63932778cafdf6cb2d6542d3ffa21b518abc148/src/core/execute.c#L3417) together with this [init](https://github.com/systemd/systemd/blob/a63932778cafdf6cb2d6542d3ffa21b518abc148/src/core/execute.c#L4085) is a security bug[1] in environments where users are supposed to have stricter umask than 022.
The [invocation](https://github.com/systemd/systemd/blob/a63932778cafdf6cb2d6542d3ffa21b518abc148/src/core/execute.c#L3417) can't be simply dropped because of [PID 1 behavior](https://github.com/systemd/systemd/blob/a63932778cafdf6cb2d6542d3ffa21b518abc148/src/core/main.c#L2459). So there are two levels of tackling this:

1. systemd shouldn't unset any umask bits (security), e.g. 027 to 022,
2. units that don't specify `UMask=` should be started with inherited umask.

IMO, 1. is patch(es) welcomed, 2. is for discussion.

[1] Strictly speaking, not a security bug because any process can umask(0) but in the perspective of user utilities that (rely on|delegate decision to) the value from `login.defs`, this is a concern.

**Comment by anthonydonegan** [comment]
[1] Strictly speaking, not a security bug because any process can umask(0) but in the perspective of user utilities that (rely on|delegate decision to) the value from login.defs, this is a concern.
Um, why is making everything world-readable when it wasn't before NOT a security bug? If it looks like a bug, sounds like a bug, and clobbers existing documented behaviour like a bug, then it probably is a bug.

**Comment by fbuihuu** [comment]
@Werkov or how about making _user_ units only inherit their umask from the user instance and leave pid1 set the default umask for _system_ units to 0022 (possibly making this value configurable) ?

Currently there's no way to configure the default umask set by pid1 or user instances. Umask can't be inherited by system units as pid1 uses the special value 0. Therefore it might make sense in this case to define a default value for system units (currently 0022) which could be tuned in system.conf.

OTOH, a user instance can have their umask redefined via either UMask= or login.def and it makes sense in this case that user units reuse/inherit this value from its parent.

**Comment by Werkov** [comment]
IIUC, empty/unspecified UMask= would mean:
- 0022 (in system units) -- i.e. no change,
- inherited value from (user) service manager (in user units) -- i.e. minimal necessary change.

Sounds good to me.

> user instance can have their umask redefined via either UMask= or login.def 

FTR, I looked at `exec_child()` and umask() happens before setup_pam() so only the latter is effective.
