### ISSUE TITLE
[RFE] resolved: Support wildcard hostnames in /etc/hosts

### ISSUE THREAD

**Issue by tadfisher** [systemd/systemd#6081]
### Submission type

 - Request for enhancement (RFE)

It would be useful for `systemd-resolved` to support wildcard matching of names in `/etc/hosts`. For example, an entry such as

```
192.168.1.100 *.example.com
```

would cause `resolved` to resolve any subdomain of `example.com` to a static address.

A concrete use case is for redirecting traffic to certain domains to a local caching proxy. To serve this purpose currently, one must either:

- Define a potentially unbounded list of FQDNs in `/etc/hosts`, or
- Run an additional DNS server such as `dnsmasq` and configure `resolved.conf` to use this server.

It seems that `resolved` should be more than capable of matching DNS queries to wildcard patterns without the need for additional network infrastructure, and this isn't really extending the scope of `resolved`.

**Comment by poettering** [comment]
WHile I see the usefulness of this I am strongly opposed to adding this, as we aren't the ones who define the /etc/hosts file format and its semantics, it was somewhat standardized in RFC952 in 1985, and implemented in different ways on the various OSes. The Linux format is defined by glibc/nss-files, and not by systemd, and hence I think we should try to be close to that, but not deviate from that and in particular not extend its syntax...

I hope that makes sense?

Closing, sorry!

**Comment by alexanderadam** [comment]
Just to be sure: so wildcards as, [for example `dnsmasq` is supporting](https://coderwall.com/p/feyzzw/networkmanager-dnsmasq-wildcard-subdomains-for-development), aren't available with `systemd` components generally (I'm not a friend of the `/etc/hosts` proposal as well), right?
Therefore the only solutions are additionally installing _another_ DNS resolver or don't use `systemd` components for resolving DNS. Is that correct?

So [in order to avoid conflicts a DNS service which has the features you want and `systemd-resolved`](https://unix.stackexchange.com/questions/304050/how-to-avoid-conflicts-between-dnsmasq-and-systemd-resolved/304798), like [`systemd-resolved` using 100% CPU](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1670959), someone has to [disable the DNS stub service](https://github.com/systemd/systemd/pull/4061#issuecomment-256799225) by setting `DNSStubListener=no` in the `resolved.conf`.

PS: is this issue related to [issue 766](https://github.com/systemd/systemd/issues/766)?

**Comment by kirbyfan64** [comment]
You can still use dnsmasq without systemd-resolved. If it's not working for you, it's likely your distro's fault, not systemd's.

**Comment by zocky** [comment]
In any case, this is something that needs to be fixed somewhere. Semantics of wildcards are entirely clear, and it would be trivial to implement them in various pieces of software that read hosts files. Literally one line of code. In fact, AFAIK, Windows already does this.

To get the same behaviour, you know need to install and configure additional software, and even worse, disable or uninstall system utilities that come preinstalled and preconfigured with your distro.

**Comment by Danny3** [comment]
@refi64,
No, I cannot use Dnsmasq
Everytime that I tried someting breaks
Either internet browsing is not working anymore or Dnsmasq breaks with some error message about too many queries.
I gave up because I'm tired of this.
I just put again the domains that I want in the hosts file like I did before knowing about Dnsmasq.
And no, it's not distro's fault
I'm using Kubuntu 19.04 and I have been using Dnsmasq for years on Ubuntu based distros without any problems, but since systemd decided to take over even the networking code I'm having this unsolvable problem.
I really don't understand what is so hard for systemd developers to make this wildcard resolving so  we can have one of the best feateres of Dnsmasq without the need to install it or stop breaking Dnsmasq.

**Comment by frank-dspeed** [comment]
@Danny3 i have a small tutorial on state 2019 how to use systemd-resolve for developers simply use the dnsmasq part

**Comment by craigbarnes** [comment]
@poettering Are you open to supporting wildcard hostnames via some other config file (like e.g. `dnsmasq --addn-hosts=/etc/wildcard-hosts`)...?

**Comment by denji** [comment]
@Danny3 https://www.knot-resolver.cz ( https://knot-resolver.readthedocs.io/en/stable/ )

**Comment by shaung75** [comment]
@frank-dspeed 3 years on, but you're my hero! Was using dnsmasq fine in Ubuntu 18.04, but just upgraded to 22.04 and everything stopped working. Your tutorial got me going again. Thanks man!
