### ISSUE TITLE
Assertion in mac_selinux_generic_access_check() with systemd --user

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#6120]
Hi,

Now that the systemd is again checking SELinux permissions for the --user instance, I can see an assertion in mac_selinux_generic_access_check() function. (`assert_return((sd_bus_creds_get_augmented_mask(creds) & SD_BUS_CREDS_SELINUX_CONTEXT) == 0, -EPERM);`)

This causes various issues, like some environment variables not being set in the `dbus` or `systemd --user` (child) processes.

The assert is happening because `GetConnectionSELinuxSecurityContext` D-Bus call is failing when asking the SELinux context of `dbus-daemon` itself ('org.freedesktop.DBus'). This first idea was to fix this in dbus itself, but Simon has a second thought about this now.

**Comment by smcv** [comment]
The problem case here is where someone (gnome-session is a typical example) calls `UpdateActivationEnvironment()` on the `dbus-daemon` itself, and we are delegating activation to `systemd --user`. Callers like gnome-session assume that doing that is enough to get the specified environment variables pushed into all D-Bus-activated services; when we introduced `systemd --user` activation, that assumption became false and things started failing. To address that, we changed the `dbus-daemon` so that when it got `UpdateActivationEnvironment()`, in addition to updating its internal environment, it turns round and [passes on the new environment variables to `systemd --user` via `SetEnvironment`](https://bugs.freedesktop.org/show_bug.cgi?id=92857).

That results in a method call message with sender `org.freedesktop.DBus`. `systemd` didn't like that, because it was unable to get the uid and pid of the message, and rejected it; we fixed that by changing the implementations of `GetConnectionUnixUser()`, `GetConnectionUnixProcessID()` and the equivalent fields in the result of `GetConnectionCredentials()`, so that when system queries the credentials of the special pseudo-bus-name `org.freedesktop.DBus`, it gets the creds of the dbus-daemon itself.

When checking SELinux permissions, systemd seems to be blindly assuming that if the uid and pid are available, then so is `GetConnectionSELinuxSecurityContext()`. However, so far `GetConnectionSELinuxSecurityContext()` was not implemented for the pseudo-bus-name `org.freedesktop.DBus`, leading to the assertion failure seen in this bug report. @bigon contributed an implementation of `GetConnectionSELinuxSecurityContext()` for `org.freedesktop.DBus`, which is in dbus git master, although not in any release yet.

However... ideally, systemd would use `GetConnectionCredentials()`, which gets all this stuff (and potentially more in future) as a single request, with fields included or omitted depending what we know. The `LinuxSecurityLabel` member of the returned dict is defined to be the result of the `SO_PEERSEC` getsockopt, as a bytestring, with a trailing `\0` added if required. I would really prefer to avoid having legacy individual-LSM method calls be strictly better than the unified version, because the unified version drastically reduces round-trips, and round-trips are usually the bottleneck for D-Bus speed and maintainability.

I sketched out an implementation of `GetConnectionCredentials()`→`LinuxSecurityLabel` for `org.freedesktop.DBus`, but it does not seem to be possible to obtain a bytestring that is guaranteed to be equivalent to what we'd get from `SO_PEERSEC`. The closest I've been able to find is reading `/proc/self/attr/current`, which is what happens in the libselinux code that @bigon calls - but for AppArmor, `/proc/self/attr/current` contains a trailing newline even though the result of `SO_PEERSEC` doesn't, which makes me uncomfortable about using this different kernel API. Worst-case, an LSM could put something completely different there. I'm very keen to keep this LSM-agnostic, because that just makes sense, but I don't want to assume equivalence (and trim the newline) unless I can get a guarantee from kernel LSM people that that's OK.

I also tried making a temporary `socketpair()` inside the `dbus-daemon`, and using `SO_PEERSEC` to get the identity of the initiator of those sockets (i.e. itself) in a form that is guaranteed to match `SO_PEERSEC`, but that [apparently doesn't work, at least for SELinux](https://marc.info/?l=selinux&m=149736790118332&w=2). I think there might also be some confusion here from the fact that sockets are files, and in SELinux, files are labelled too (unlike AppArmor, where only processes are labelled) - so there is a possibility of accidentally getting the label of the socket, not the label of the process that initiated the socket.

If you think about it, it's a little nonsensical to ask the dbus-daemon who the dbus-daemon is, because on systems with LSM mediation you are already trusting the dbus-daemon not to lie to you when you ask about other processes - so it's already well within your trust boundary (TCB).

One possibility for a way to address this without further contortions in dbus-daemon would be for sd-bus to special-case `org.freedesktop.DBus` and, instead of calling methods on the dbus-daemon, use `SO_PEERSEC` (or its libselinux/libapparmor wrappers like getpeercon_raw) to query who it is in a more direct way. I asked @bigon to test whether this gave the expected results on a SELinux system, but I've lost track of what the result was.

Another possibility would be for systemd to just let dbus-daemon do whatever it wants, skipping the access check, on the basis that the dbus-daemon is already in the TCB (or at least, it's as powerful as the union of all of its possible clients, because if it was malicious then it could pretend to be any of them).

Another, which just occurred to me while I was writing this, would be for dbus-daemon to lie to systemd when composing its `SetEnvironment` method call message, and pretend the message had come from the caller of `UpdateActivationEnvironment`. That would require either setting `NO_REPLY` or doing some very weird special-case filtering, though, to avoid the reply being sent back to the caller.

Any opinions?

**Comment by bigon** [comment]
Maybe @stephensmalley might have an opinion on this as well?

**Comment by stephensmalley** [comment]
You should likely ask on linux-security-module about /proc/self/attr/current and SO_PEERSEC guarantees. I can't speak to all security modules, and AppArmor's code for implementing SO_PEERSEC isn't even in mainline AFAICS. SELinux is fine with an equivalence assumption and with trimming any newline (which it won't ever include). Looks like Smack returns equivalent strings but does differ in whether it treats the NUL byte as part of the label (/proc/pid/attr returns strlen(), SO_PEERSEC returns strlen()+1).  TOMOYO doesn't implement SO_PEERSEC at all.

SO_PEERSEC on socketpair()-created sockets can't work on any LSM since we are missing a LSM hook to establish the relationship.  Not just SELinux.  There isn't a concern about getting confused with socket file labels btw; the socket file is an entirely separate kernel object and won't ever be returned by getsockopt(SO_PEERSEC) or even fgetfilecon() on the socket fd.

Having sd-bus use SO_PEERSEC on the socket it is using to communicate when getting the context for org.freedesktop.DBus should work AFAICS, and seems more reliable than dbusd providing an arbitrary value.

I don't think skipping checking entirely on org.freedesktop.DBus is a good idea.

Not sure I understand the last one, but it sounds rather convoluted and prone to error.

**Comment by smcv** [comment]
> You should likely ask on linux-security-module about /proc/self/attr/current and SO_PEERSEC guarantees

I did, http://kernsec.org/pipermail/linux-security-module-archive/2017-June/001842.html

> AppArmor's code for implementing SO_PEERSEC isn't even in mainline AFAICS

I keep forgetting how much of the kernel side of AppArmor is (still!) an Ubuntu-specific patchset :-(

> Looks like Smack returns equivalent strings but does differ in whether it treats the NUL byte as part of the label (/proc/pid/attr returns strlen(), SO_PEERSEC returns strlen()+1)

Last time I brought this up on linux-security-module, the consensus was that the presence or absence of the trailing `\0` is not (allowed to be) significant. dbus-daemon normalizes to a form where the trailing `\0` is included, because that's the most convenient for C-based ABIs.

**Comment by poettering** [comment]
hmm, i am tempted to say that sd-bus/systemd is broken here, and there's nothing to fix in dbus-daemon. Specifically, I would say that we should have a special case that if the credentials of the org.freedesktop.Bus service are requested we should shortcut that and simply return the peer's credentials instead.

(and yeah, we should use GetConnectionCredentials() these days. The only reason we don't is that it didn't exist yet when i started hacking on that code)

**Comment by smcv** [comment]
> I would say that we should have a special case that if the credentials of the org.freedesktop.Bus service are requested we should shortcut that and simply return the peer's credentials instead.

It's o.fd.DBus, with the D, but yes. Assuming that works, it seems the most appealing option.

I'll try to add `LinuxSecurityLabel` to the result of `GetConnectionCredentials()` anyway, but if the kernel interface makes it needlessly complicated to do so then I might give up.

**Comment by bigon** [comment]
Wouldn't this bug break Fedora that is enabling SELinux by default?

This should maybe be fixed for the 234 release?

**Comment by poettering** [comment]
Fix waiting in #6201.

**Comment by poettering** [comment]
(the fix does the creds shortcut for org.freedesktop.DBus as well as port things to use GetConnectionCredentials() btw)
