### ISSUE TITLE
RFE: Exponentially increasing RestartSec=

### ISSUE THREAD

**Issue by OlafvdSpek** [systemd/systemd#6129]
When a service fails to start, a retry is done after 100ms for a total of 5 tries, after which it's not tried automatically again. Does this make sense?

If a service crashes (for the first time) it might not make sense to wait 100ms.
If a start attempt doesn't succeed, it might make sense to wait more than 100ms. Perhaps some exponential backoff should be used up to a minute or so, instead of not trying at all after about 1s.

215-17+deb8u7 @ Debian 8

**Comment by agutikov** [comment]
+1

**Comment by zioproto** [comment]
+1

**Comment by vsinitsyn** [comment]
+1

**Comment by jmleoni** [comment]
+1

**Comment by JasonWoof** [comment]
Instead of exponential can we please just specify the successive retry delays?

Examples:

- backwards-compatible flat: RestartSec=1
- aggressive for a few tries, then back off: RestartSec=1,1,1,1,30
- exponential, min=1, max=10: RestartSec=1,2,4,8,10

(last value repeated automatically as needed)

**Comment by matthijskooijman** [comment]
+1 for explicitely specifying the delays.

I believe this would also fulfill the question asked at #2416. That issue asks to *not* stop trying to restart a service when the start limit burst rate is reached, but instead only delay it until the start limit interval passes. IOW, that issues asks for, with the default settings, trying 5 restarts with a 100ms delay each, then waiting for 9.5s before trying again, which is something which could be perfectly implemented with the proposal above.

**Comment by greencoloured** [comment]
+1 for this. Also creating implicit ranges would be awesome:

```
1..10   = 1,2,3,4,5,6,7,8,9,10
1,3..10 = 1,3,5,7,9
1..     = 1,2,3,4,5, to infinity and beyond
```

**Comment by KlavsKlavsen** [comment]
Would be very  nice to have this.. when a heavy java process dies - it eats up all my cpu, on restarting continuously :(

**Comment by greencoloured** [comment]
> Is such complexity really needed?
> I think I'd be fine with:
> 
>     1. Restart without delay on a 'crash'.
> 
>     2. Restart every 5 minutes on repeated 'failures'.
> 
> 
> Counting RestartSec from time of last start (attempt) rather then time of stop / crash would be enough for this. RestartSec could then default to a more sane value.

Backoff (exponential or otherwise) is important for services that can interact to give them a chance to get back to a stable state before retrying and being able to specify what that backoff looks like is also important as not using the same backoff for every service can also play an important role when services are all trying at once to start every 5 minutes it's not much better than if they just kept trying to restart.

**Comment by OlafvdSpek** [comment]
> Would be very nice to have this.. when a heavy java process dies - it eats up all my cpu, on restarting continuously :(

RestartSec = 1 would fix that

**Comment by KlavsKlavsen** [comment]
> RestartSec = 1 would fix that

Not really.. if my daemon dies.. I WANT it to be restarted immediately (thats why I am telling systemd to do so ;) - BUT if it turns out - it just dies again.. something is obviously wrong, and currently systemd does the stupid thing of just trying again, and again.. indefinetely.. - and since my process is heavy on the system when it starts up - thats very resource intensive..
Hence the need for a backoff mechanism.. exactly as described above.. f.ex. just increasing time between tries exponentially or something would be very nice..
I'd like it to try immediately.. then wait 5 minutes.. then wait 30 minutes.. and 3 hours.. and in the end it should not retry more than "once a day" or something.. (the situation could correct itself - who knows - but I'd be fine with it just doing X tries max)..

**Comment by KlavsKlavsen** [comment]
I'd be fine with settings like:
RestartInterval=5m
RestartIntervalIncreaseFactor=6
#Optionals
RestartMaxTries=5

Meaning systemd would restart immediately, if it still fails "within RestartInterval" - it'll wait 5 minutes, and then try again.. and if it again dies within RestartInterval (5m) - then it'll wait RestartInterval*6 (ie. 30 min), and then next time it would wait 30*6 etc.

**Comment by AlD** [comment]
+1, and add a ceiling for the interval:
`RestartIntervalMax=60m`

**Comment by JasonWoof** [comment]
exponential (or anything with multiplying) doesn't allow you to have the first restart be immediate.

**Comment by KlavsKlavsen** [comment]
> exponential (or anything with multiplying) doesn't allow you to have the first restart be immediate.

What? its all just code.. so ofcourse it can restart immediately.. and then start increasing restart intervals after first restart.

**Comment by kootenpv** [comment]
I'd like to indeed have the following:

```
RestartSec=
  1..10   = 1,2,3,4,5,6,7,8,9,10
  1,3..10 = 1,3,5,7,9
  1..     = 1,2,3,4,5, to infinity and beyond
  auto = let's decide on a good default strategy*
```

My vote for auto would be something like: 0,1,2,4,8,60

The benefits are clear of having this syntax + options: 

- it's very understandable
- doesn't require any formulas
- you only need to set 1 line
- it is as flexible as you'd want it to be.

**Comment by leodaher** [comment]
This issue is not fixed yet, is it? This exponential increasing restart delay would be very useful for a project I'm working on. Can I work on this issue and make a PR?

**Comment by runejuhl** [comment]
As far as I know, from following this issue, there hasn't yet been any work on an implementation. You're more than welcome to work on a PR, and I'd love to review it.

Mon May 27 22:22:11 GMT+02:00 2019 leodaher <notifications@github.com>:

**Comment by leodaher** [comment]
@runejuhl Great! Could you give me some guidance on which part of the code to start? It would be really helpful.

**Comment by c4milo** [comment]
@poettering, something reasonable to address thundering herd problems upon reload or restart will be of high value to have in systemd.

**Comment by AdamWill** [comment]
Would really like to see this too (specifically for fedora messaging consumers, see https://github.com/fedora-infra/fedora-messaging/pull/214 ).

**Comment by mgkuhn** [comment]
The `RestartSec=1,1,1,1,30` solution proposed above for backing off the rate at which rapidly failing services get restarted has a problem: it increases the restart delay monotonically and therefore a brief temporary problem will limit the restart time for the rest of the systemd uptime. If I understood it correctly, it does not merely take into account how many restarts there have been _recently_.

Imagine you have a long-running service on a long-running system. That service encounters a problem about once a month where it fails for a couple of seconds (e.g., because something else is rebooting), but then it is completely fine again. If you only back off based on a count of the total number of restarts so far (e.g., since pid 1 started), the `RestartSec=1,1,1,1,30` specification would always lead to a 30 second delay eventually, even after the service has been running fine for weeks, just because it has restarted 5 times many months ago.

If we add any kind of restart back-off mechanism, it should also have a way to forget failures and restarts from the distant past, such that the back-off starts afresh if the service has been fine recently.

Alternatives to restart delays based on a persistent restart count include for example:
* a [leaky-bucket algorithm](https://en.wikipedia.org/wiki/Leaky_bucket)
* a time window for forgetting recent restarts when counting them
* a (linear or exponential?) decay rate in the cumulative count of restarts

(The last option is probably easiest to implement.)

**Comment by greencoloured** [comment]
@mgkuhn 

in the wrapper script I wrote to provide this functionality. There is the concept of a stable service, where it has been running for a given amount of time without restarting. 

Stable restarts start from the beginning of the backoff. 
Unstable restarts increase the backoff.

This script provides another useful feature, jitter where the backoff is not exact but has some randomness applied to prevent multiple services trying to start at the same time because they are on the same backoff schedule.

**Comment by OlafvdSpek** [comment]
> it increases the restart delay monotonically and therefore a brief temporary problem will limit the restart time for the rest of the systemd uptime.

Depends on whether you count from the time of the crash or from the time of the previous start. ;)

**Comment by nyuszika7h** [comment]
I support this, it would be a great addition. I find myself trying to balance the restart time for services where I do want it to restart ASAP but I don't want it to retry excessively if it fails thousands of times.

**Comment by psvz** [comment]
Did it get anywhere? I would even be happy with a timeout **after** restart attempt not before as in _RestartSec_ because it would make the first restart attempt as soon as possible and the second one could be whenever as it is likely to indicate a persistent issue.

**Comment by yawaramin** [comment]
The [idea](https://github.com/systemd/systemd/issues/6129#issuecomment-405980796) to specify a comma-separated list of delays is a good one. It lets us flexibly implement exponential or Fibonacci or any other type of backoff. Plus it's completely backwards-compatible.

If service unit files would also support the [random jitter](https://www.freedesktop.org/software/systemd/man/systemd.timer.html#RandomizedDelaySec=) option that timers support, that would complete the picture.

**Comment by psvz** [comment]
Cheers @yawaramin - is it a planned thing for a certain future?

**Comment by hin7141** [comment]
it is insane that this issue is still here in the end of 2022. This is poorly maintained given that it is such a common feature.

**Comment by dtardon** [comment]
> it is insane that this issue is still here in the end of 2022. This is poorly maintained given that it is such a common feature.

Well, send a patch? This doesn't look like something that would require a week of work and detailed knowledge of systemd internals...

**Comment by hilbix** [comment]
I really can't hear it anymore!  Things like "It's open source, so you can send in patches!"

Please, what for hell is this for an inhuman attitude?
Do you think all people on this planet have to be good programmers?
And all need to speak C better than their native language?  Or what?

I really cannot imagine **any** excuse for discussing that way.
Sorry for this, but I am very very angry now.

**Comment by AlD** [comment]
> Please, what for hell is this for an inhuman attitude? Do you think all people on this planet have to be good programmers? And all need to speak C better than their native language? Or what?

I don't think anyone expects that. You can contribute in other ways. May I suggest setting up a bounty for this at bountysource.com for example.

Another way to contribute would be to write up a concrete implementation design for this feature and getting that reviewed by a systemd developer. This would save the person doing the implementation considerable amount of time and effort.

**Comment by dtardon** [comment]
> I really can't hear it anymore! Things like "It's open source, so you can send in patches!"

I really can't hear it anymore either! Things like "You still haven't implemented minor feature X! Your software is _unusable_!"
 
> Please, what for hell is this for an inhuman attitude?

It's an attitude of scratching one's itch. IOW, if one wants something, one should be prepared to spend some effort to make it happen. Not just twiddle one's thumbs and make snide remarks. And, as @AID noted, writing code is just the most direct way, not the only one.

You're offended that _someone_ hasn't yet done something _you_ want. What kind of arrogant attitude is _that_?

**Comment by YHNdnzj** [comment]
Please give #26902 a try :) But it does have problems mentioned in https://github.com/systemd/systemd/issues/6129#issuecomment-651041811, at least for now

**Comment by positron96** [comment]
@YHNdnzj  Hello. Just wanted to clarify. With this implementation, if the service fails and gets restarted regularly but rarely (e.g once a month), will it still reach maximum restart delay after some time?

**Comment by YHNdnzj** [comment]
> @YHNdnzj Hello. Just wanted to clarify. With this implementation, if the service fails and gets restarted regularly but rarely (e.g once a month), will it still reach maximum restart delay after some time?

Yeah. Currently the only way restart counter will be reset is to restart the service manually. I do think we should implement something like `RestartResetSec=`, but I haven't got time to work on that.

**Comment by positron96** [comment]
Maybe factor in some logic from StartLimitInterval/StartLimitBurst?
