### ISSUE TITLE
systemd 233 breaks bond interfaces

### ISSUE THREAD

**Issue by DirkSchmitt** [systemd/systemd#6184]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233

### Used distribution

> ubuntu 16.04 
 in combination with https://launchpad.net/~dirk-computer42/+archive/ubuntu/c42-backport
and with kernel 4.8.0-56-generic
### In case of bug report: Expected behaviour you didn't see

> bond0 interface starting 

### In case of bug report: Unexpected behaviour you saw

>Jun 20 16:14:45 odie systemd-networkd[1484]: bond0: Could not bring up interface: Operation not supported

### In case of bug report: Steps to reproduce the problem

> upgrade from systemd from 232 (as in https://launchpad.net/~dirk-computer42/+archive/ubuntu/c42-preserve-systemd/+packages)
> The network is configured as below:

* 10-c42-bond0.netdev
```
[NetDev]
Name=bond0
Description=c42Cfg configured bond device [generateBondDev]
Kind=bond
MTUBytes=9000
MACAddress=…

[Bond]
Mode=802.3ad
TransmitHashPolicy=layer2+3
LACPTransmitRate=fast
MIIMonitorSec=100s
DownDelaySec=4s
```
* 10-c42-bond0.network
```
[Match]
Name=bond0

[Network]
Description=c42Cfg configured  network for bond0 [generateBondDev]
BindCarrier=bslave1 bslave2
LLDP=true
LinkLocalAddressing=no
IPv6AcceptRA=no
```
* 10-c42-bslave1.link / 10-c42-bslave2.link similar 
```
[Match]
MACAddress=…

[Link]
Name=bslave1
MTUBytes=9000
```
* 10-c42-bslave1.network / 10-c42-bslave2.network similar
```
[Match]
Name=bslave1

[Network]
Description=c42Cfg configured internal network for bond slave devices bslave1 [generateBondDev]
Bond=bond0
DHCP=no
LinkLocalAddressing=no
IPv6AcceptRA=no
```

**Comment by DirkSchmitt** [comment]
Some more informations:
- To mitigate the problem I downgraded the system to systemd 232.
- The network configuration is untouched since ~ 1 year.
- On top of the bond0 interface is a ovs bridge (Due to the lack of systemd support configured outside)
- On another system with similar setup and kernel 4.10.* the problem doesn't exist

**Comment by gdamjan** [comment]
afaik, `bond0` is automatically created by the kernels "bonding" module/driver, so trying to also create it by a .netdev file could fail.

use bond1?

**Comment by gdamjan** [comment]
OTOH, you can also set the `max_bonds=0` option to the `bonding` module, and it won't create any default devices (which is a stupid idea anyway, and only exists for legacy reasons).

**Comment by DirkSchmitt** [comment]
@gdamjan Thanks for your feedback. 
The configuration works for over a year below systemd 229 (ubuntu 16.04 default) and 232.
For 233 it breaks with kernel 4.8.* but not with kernel 4.10.* 
So I suspect it is an regression and not a configuration problem.

**Comment by poettering** [comment]
Does this work if you pass max_bonds=0 to the bonding module? (which quite frankly should be the default anyway)

**Comment by DirkSchmitt** [comment]
```
cat /etc/modules-load.d/network-bonding.conf 
```
> bonding max_bonds=0

```
 systemctl  restart systemd-modules-load.service 
```
> Job for systemd-modules-load.service failed because the control process exited with error code.
See "systemctl status systemd-modules-load.service" and "journalctl -xe" for details.

**Comment by gdamjan** [comment]
@DirkSchmitt 
the correct directory is `/etc/modprobe.d/` and a file there (let's say it's `/etc/modprobe.d/bonding.conf`) needs to have:
```
options bonding max_bonds=0
```

then reboot (systemd-modules-load.service will not remove modules)

**Comment by h1z1** [comment]
What distro has max_bonds=0 by default??  Forcing this will break things upstream.

**Comment by andrewdunndev** [comment]
@poettering I'd say that it's a bit of a confusing default. 

@DirkSchmitt I moved over to using a named bond rather than `bond0`, (e.g. `bondxg` or something). It's documented within the [ArchWiki](https://wiki.archlinux.org/index.php/VLAN#systemd-networkd_bonded_interface). I'll report that I had a couple machines using `bond0` and they were _occasionally_ affected by the race condition in naming, but for the most part worked. Switching over to a convention that avoids `bond0` has resulted in me seeing no more problems in this domain.

**Comment by DirkSchmitt** [comment]
I applied both suggestions:
- max_bonds=0
- using bond1 instead bond0

This resolves the issue for my installations.
Also the ubuntu 16.04 hwe-kernel is now updated to 4.10.x

This problem here leafs me to the RFE #6427

**Comment by poettering** [comment]
Anyway, closing this: if max_bonds=0 isn't set, the kernel creates bond0 automatically, and this conflicts with a .netdev file creating the same. We really shouldn't work around this kernel behaviour here, we shouldn't immediately remove a networkd device the kernel created first, just to work around weird kernel behaviour.

Please set max_bonds=0 for your kernel module, so that the kernel doesn't do what it's doing here. Ideally there'd be a kernel option to make this the default, but there currently isn't. THe next best thing would be if distros would set this by default in the modprobe snippets they ship, but I am pretty sure we shouldn't work around this on the systemd side, by actively undoing what the kernel just did instants before.

Please talk to you distribution and ask them to make max_bonds=0 the default for their kernels/modules. Thank you!

**Comment by poettering** [comment]
(I will add a line to README commenting about this, so that packagers know this in future)

**Comment by xnox** [comment]
I've also hit this issue, and previously reported it. Let me propose shipping a modprobe.d drop in by default. As this should prevent any other confusion by any feature users, of at least unmodified upstream systemd builds.
