### ISSUE TITLE
systemd-resolved does not use DNS for local resolution

### ISSUE THREAD

**Issue by johndoe31415** [systemd/systemd#6224]
### Submission type

 - Bug report

### systemd version the issue has been seen with
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

Ubuntu 17.04

### In case of bug report: Unexpected behaviour you saw

I run a local DNS and DHCP. The DHCP issues the domainname "homelan.net" (i.e., /etc/resolv.conf 'search') and BIND9 is configured to be authoritative for that domain. This worked great before (dnsmasq) and still works with the following manually edited /etc/resolv.conf:

```
nameserver 192.168.1.1
search homelan.net
```

Now I've switched to Ubuntu 17.04 and systemd-resolved became the default. I.e., my resolv.conf now reads

```
nameserver 127.0.0.53
```

And host does not work anymore:

```
$ time host curie
;; connection timed out; no servers could be reached

real	0m10,014s
user	0m0,007s
sys	0m0,007s
```

When I sniff traffic with Wireshark, I see a couple of attempts (six) at LLMNR resolution, but no outgoing DNS.

I followed the instructions of @poettering in https://github.com/systemd/systemd/issues/5755 and turned up debug logging. This is what `journalctl -u systemd-resolved -f` said when trying to resolve:

```
Jun 28 18:25:55 reliant systemd-resolved[2954]: Got DNS stub UDP query packet for id 43424
Jun 28 18:25:55 reliant systemd-resolved[2954]: Looking up RR for curie IN A.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:25:55 reliant systemd-resolved[2954]: Transaction 41880 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Delaying llmnr transaction for 24148us.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Processing query...
Jun 28 18:25:55 reliant systemd-resolved[2954]: Timeout reached on transaction 41880.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Retrying transaction 41880.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:25:55 reliant systemd-resolved[2954]: Transaction 41880 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Sending query packet with id 41880 on interface 3/AF_INET.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Got LLMNR UDP query packet for id 41880
Jun 28 18:25:55 reliant systemd-resolved[2954]: Timeout reached on transaction 41880.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Retrying transaction 41880.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:25:55 reliant systemd-resolved[2954]: Transaction 41880 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Sending query packet with id 41880 on interface 3/AF_INET.
Jun 28 18:25:55 reliant systemd-resolved[2954]: Got LLMNR UDP query packet for id 41880
Jun 28 18:25:56 reliant systemd-resolved[2954]: Timeout reached on transaction 41880.
Jun 28 18:25:56 reliant systemd-resolved[2954]: Retrying transaction 41880.
Jun 28 18:25:56 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:25:56 reliant systemd-resolved[2954]: Transaction 41880 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:25:56 reliant systemd-resolved[2954]: Sending query packet with id 41880 on interface 3/AF_INET.
Jun 28 18:25:56 reliant systemd-resolved[2954]: Got LLMNR UDP query packet for id 41880
Jun 28 18:25:56 reliant systemd-resolved[2954]: Timeout reached on transaction 41880.
Jun 28 18:25:56 reliant systemd-resolved[2954]: Retrying transaction 41880.
Jun 28 18:25:56 reliant systemd-resolved[2954]: Transaction 41880 for <curie IN A> on scope llmnr on eno1/INET now complete with <attempts-max-reached> from none (unsigned).
Jun 28 18:25:56 reliant systemd-resolved[2954]: Freeing transaction 41880.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Got DNS stub UDP query packet for id 43424
Jun 28 18:26:00 reliant systemd-resolved[2954]: Looking up RR for curie IN A.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:26:00 reliant systemd-resolved[2954]: Transaction 36708 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Delaying llmnr transaction for 1196us.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Processing query...
Jun 28 18:26:00 reliant systemd-resolved[2954]: Timeout reached on transaction 36708.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Retrying transaction 36708.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:26:00 reliant systemd-resolved[2954]: Transaction 36708 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Sending query packet with id 36708 on interface 3/AF_INET.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Got LLMNR UDP query packet for id 36708
Jun 28 18:26:00 reliant systemd-resolved[2954]: Timeout reached on transaction 36708.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Retrying transaction 36708.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:26:00 reliant systemd-resolved[2954]: Transaction 36708 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Sending query packet with id 36708 on interface 3/AF_INET.
Jun 28 18:26:00 reliant systemd-resolved[2954]: Got LLMNR UDP query packet for id 36708
Jun 28 18:26:01 reliant systemd-resolved[2954]: Timeout reached on transaction 36708.
Jun 28 18:26:01 reliant systemd-resolved[2954]: Retrying transaction 36708.
Jun 28 18:26:01 reliant systemd-resolved[2954]: Cache miss for curie IN A
Jun 28 18:26:01 reliant systemd-resolved[2954]: Transaction 36708 for <curie IN A> scope llmnr on eno1/INET.
Jun 28 18:26:01 reliant systemd-resolved[2954]: Sending query packet with id 36708 on interface 3/AF_INET.
Jun 28 18:26:01 reliant systemd-resolved[2954]: Got LLMNR UDP query packet for id 36708
Jun 28 18:26:01 reliant systemd-resolved[2954]: Timeout reached on transaction 36708.
Jun 28 18:26:01 reliant systemd-resolved[2954]: Retrying transaction 36708.
Jun 28 18:26:01 reliant systemd-resolved[2954]: Transaction 36708 for <curie IN A> on scope llmnr on eno1/INET now complete with <attempts-max-reached> from none (unsigned).
Jun 28 18:26:01 reliant systemd-resolved[2954]: Freeing transaction 36708.
```

I expect that the domain name suffix that is given by DHCP is honored and that DNS resolution is performed regularly. How can I fix this?

Thanks for your assistance,
Johannes

**Comment by xnox** [comment]
@johndoe31415 

This is an inappropriate bug report to be filed upstream, because this is a distribution policy issue. At the moment this issue has been identified and the Ubuntu Foundations team are working with Security team on changing the defaults policy, such that out of the box these things work under certain conditions.

There is no inherent limitation in resolved, as this particular behavior is fully configurable both via config files and the resolved dbus API. But just like with many things in systemd collection of projects, there is a sensible consistent set of defaults of one way to do things, and distributions package and adapt their own policy on things.

It is a correct observation that currently in artful/zesty we have regressions and change of behavior vs xenial. And we are working on fixing that.

Whilst that is in progress you can for example set domain in /etc/systemd/resolved.conf or adjust your networking. As  a temporary workaround / solution, until the default policy in Ubuntu is changed.

If you need further assistance feel free to open a bug report on launchpad, and/or ping me on the IRC.

**Comment by johndoe31415** [comment]
Hi Dimitri,

fair enough, if this really is configurable then I'd agree that it's a Ubuntu issue. But the one piece of information I need to verify is: how can I adapt my resolved.conf to work again? I've searched and found numerous issues, all pointing to "DNSSec=no" (e.g., https://superuser.com/questions/1153203/ubuntu-17-04-systemd-resolved-dns-lookups-randomly-fail or http://www.hecticgeek.com/2017/04/ubuntu-17-04-systemd-dns-issues/  or https://www.ryanschulze.net/archives/1842).

However, this does *not* solve my issue. I've also tried "LLMNR=no", which changes the timeouts to a

```
Host curie not found: 2(SERVFAIL)
```

Error message. Also, note that my Ubuntu stock resolved.conf is empty (i.e., all lines except [Resolve] are commented out). So unless that's a Ubuntu change, I'm seeing the stock resolved behavior. Which would be, even though you technically would be correct that Ubuntu could "configure" it correctly, still odd/crappy default behavior.

If you could give me a pointer at how you think I can fix this issue, I'd happily try it out and report back if this solves my problem.

**Comment by johndoe31415** [comment]
Hi again,

I re-read your message just now and notices that you *do* have the solution in there:

```
Domains=homelan.net
```

in `/etc/systemd/resolved.conf`fixes the issue. Thanks for this, I'll close this ticket. But according to your message I take it there isn't a Launchpad report for this yet? If so, then I'd like to create one.

**Comment by johndoe31415** [comment]
...aaaand the issue is back. With no change whatsoever. First, setting "Domains=" worked, now it doesn't again. It's difficult for me to believe this is not resolved's fault. I'll repoen the issue.

**Comment by poettering** [comment]
> $ time host curie

So you are trying to resolve a single-label name A/AAAA here. resolved will never pass that on to DNS as is, and that's really by design, also see #5549,  https://github.com/systemd/systemd/issues/2514#issuecomment-179203186 and https://github.com/systemd/systemd/issues/4821#issuecomment-264995354 . What it will do however is pass on those names to LLMNR, as that's considered part of the local scope we pass lookups too.  But LLMNR lookups for missing names need to time out (because it is a true multicasting peer-to-peer protocol, and a name that doesn't exist means that there's nobody responding to an LLMNR query), but the `host` command on the client side times out even earlier than that, and then doesn't continue with the search domains, as search domains have to be honoured client-side, i.e. inside the "host" command.

Not sure what to suggest about this. If you don#t need LLMNR, then you can simply turn off LLMNR support in resolved, and the name lookup should fail immediately, causing `host` to continue with the first search domain.

I am not sure we can change much about this on the server side though: as long as LLMNR is on, it's 
how we resolve names...

I'd assume that "getent hosts curie" behaves better on this. Does that work correctly?

**Comment by CharAznableLoNZ** [comment]
I have a local domain that I have various servers on.  Some of these are on different networks as is my DNS server.  My domain follows a domain.suffix format.  At the very least, if I define a private DNS server it should be respected as used as the priority server instead of whatever this does now.  Before this was installed, all lookups worked through my local DNS server.  

It works after changing the resolved.conf to my local server.  My main issue here is it is hard to recommend something to a customer or client if they have to modify files just to get it to work.  This should be easily done through the OS GUI.

**Comment by xnox** [comment]
In 17.10 / artful-proposed, search stanzas are generated in `/etc/resolv.conf` and thus this should start working again, once v234 based systemd migrates. Currently blocked on failing integration tests.

**Comment by ossilator** [comment]
i'm using systemd 234 as packaged in debian unstable, and i'm seeing this issue which seems quite related: listing a domain in Domains actively _breaks_ DNS resolution for that domain even if the host is supplied as an fqdn (instant SERVFAIL). so when i have Domains=kde.org, looking up www.kde.org fails immediately. looking up just "www" otoh yields ";; connection timed out; no servers could be reached" from dig, pretty much as expected.

**Comment by perolausson** [comment]
I've spent some time battling with this issue myself and reading this error report what stands out to me is that noone is asking if a /etc/systemd/network/NNNN.network file was setup on the server.

I too started out fiddling with /etc/resolv.conf and had no luck with it. In the end, my understanding is that to get this to work properly the solution is to configure the network correctly by telling systemd.network where the corresponding DNS is for my local private domain.

Example: 

```
$ cat /etc/systemd/network/eno1.network
[Match]
Name=eno1
[Network]
DNS=192.168.1.1
DNSSECNegativeTrustAnchors=lan
DHCP=yes
Domains=lan
[DHCP]
UseDomains=true
```

This solves the issue for systemd.resolve based systems, meaning that I get consistent replies to DNS queries for my LAN, including search requests (ie. requests with short names) but it still doesn't work satisfactorily for non-systemd.resolve based systems since systemd.resolve will try to resolve only using LLMNR until timed out and only then ask the DNS what the answer might be.

I've not seen any way to set the LLMNR timeout value, if someone knows how please enlighten me.

Hope this helps someone...

**Comment by xnox** [comment]
Debian does not use resolved by default... And Debian configuration of resolved is very different from Ubuntu. Please use correct upstream bug trackers for distribution issues, bugs.debian.org/systemd and launchpad.net/ubuntu/+source/systemd

**Comment by christhomas** [comment]
I found this, try the solution from #8

**Comment by dlitster** [comment]
The issue here is that the default behavior has changed and requires workarounds with every ubuntu physical/VM/container that is provisioned on a local lan and needs to get resources from another host on that lan.

Most home users on standard routers won't have a search domain set up or have an FQDN set up for their local lan.  The default behavior for local single-label queries is unexpected.

> @johndoe31415
> 
> This is an inappropriate bug report to be filed upstream, because this is a distribution policy issue. At the moment this issue has been identified and the Ubuntu Foundations team are working with Security team on changing the defaults policy, such that out of the box these things work under certain conditions.

Do you have an issue link?  This behavior is still the case in 18.04.2.

> There is no inherent limitation in resolved, as this particular behavior is fully configurable both via config files and the resolved dbus API. But just like with many things in systemd collection of projects, there is a sensible consistent set of defaults of one way to do things, and distributions package and adapt their own policy on things.

It seems like a design issue or overlooking a default use case for local single-label names, not a "distro policy" issue.

@poettering said in [#8967](https://github.com/systemd/systemd/issues/8967#issuecomment-389934581 )that
> resolved will never allow single-label lookups to leak onto unicast DNS, i.e. the Internet. It will resolve them only via LLMNR or expand them via the search list if one is configured. This is in-line with what Internet bodies such as the IAB suggest for single-label names:

> [https://www.iab.org/documents/correspondence-reports-documents/2013-2/iab-statement-dotless-domains-considered-harmful/](https://www.iab.org/documents/correspondence-reports-documents/2013-2/iab-statement-dotless-domains-considered-harmful/)

Yet in that link, the 3rd paragraph clearly states:
_This behavior was developed in the DNS **precisely** because most users entering single-label names **want** them to be resolved in a local context, and they do not expect a single name to refer to a TLD. The behavior is specified within a succession of standards track documents developed over several decades, and is now implemented by hundreds of millions of Internet hosts. **This standard approach enables single-label names to be conveniently used as shortcuts to hosts within a local administration,**_

Again, from https://github.com/systemd/systemd/issues/8967#issuecomment-389934581 
> Following that logic we won't route single-label names (i.e. "dotless" domains, i.e. "TLDs") to classic DNS, and instead resolve them in a purely local context, i.e. LLMNR or based on search domains (search domains are not apply on queries coming in via local DNS though, only to those coming in via NSS or dbus). And yes, this is documented, but I figure we could make this even more explict.

LLMNR is an appropriate fallback only **after** consulting the local DNS server provided by DHCP, which resolved doesn't appear to do by default in this case.

from [RFC 4795](https://tools.ietf.org/html/rfc4795) 
_The goal of Link-Local Multicast Name Resolution (LLMNR) is to enable name resolution in scenarios in which conventional DNS name resolution is not possible._

In this case, it's CLEARLY possible when I manually specify my local DNS server:
david@server:~$ nslookup ansible-nas 10.0.1.1
Server: 10.0.1.1
Address: 10.0.1.1#53

Name: ansible-nas
Address: 10.0.1.37

I don't know what more to say.  Go set up a consumer-grade router, install latest Ubuntu or Fedora with on 2 machines, then see if you can have them talk to each other using their hostname after getting DHCP addresses.  Windows and OS X can do it, why has systemd-resolve d broken this?

from the systemd-resolved [man page](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html):
_Single-label names are routed to all local interfaces capable of IP multicasting, using the LLMNR protocol. Lookups for IPv4 addresses are only sent via LLMNR on IPv4, and lookups for IPv6 addresses are only sent via LLMNR on IPv6. Lookups for the locally configured host name and the "gateway" host name are never routed to LLMNR._

OK, so the man page contradicts both the [Wikipedia](https://en.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution) page for LLMNR and the 2 [Microsoft](https://docs.microsoft.com/en-us/previous-versions//bb878128(v=technet.10)) [pages](https://blogs.technet.microsoft.com/networking/2008/04/01/how-to-benefit-from-link-local-multicast-name-resolution/) announcing LLMNR, which was designed for ad-hoc networks without a local DNS server.

Sorry for the essay, but when literally thousands of users install a new os and are confused that default behavior has changed, especially when that use case is **clearly** understood to be the expected behavior, that is a design problem.

This isn't just me talking, please listen to your users.  We are begging you as the designers of this software to make sensible defaults that don't break longstanding expectations.

Works cited:
#4821 #5549 #2514 #8967 

https://bugs.launchpad.net/network-manager/+bug/1624317
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1636375
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1624320/comments/8
https://www.freedesktop.org/software/systemd/man/hostnamectl.html

**Comment by mabod** [comment]
I am suffering from the same issue. resolving local host names with systemd-resolved worked for me since a long while but is broken now after one of the last updates (Manjaro Testing).

Example:
When it worked I could do "`ping unten`" where unten is the PC one floor down. Nowadays it does not work anymore. The command sits there for 10 s and comes back with an error:
```
19# ping unten
ping: unten: Name or service not known
```

While the FQDN works fine:
```
20# ping unten.fritz.box
PING unten.fritz.box (192.168.132.53) 56(84) bytes of data.
64 bytes from unten.fritz.box (192.168.132.53): icmp_seq=1 ttl=64 time=0.756 ms
```
With this resolv.conf

```
nameserver 127.0.0.53
options edns0
```

and this /etc/systemd/resolved.conf

```
[Resolve]
DNS=84.200.69.80 84.200.70.40 

# fallback from CCC
FallbackDNS=194.150.168.168

# Domains=fritz.box
# LLMNR=yes
#MulticastDNS=yes
DNSSEC=allow-downgrade
#DNSSEC=no
#DNSOverTLS=no
#Cache=yes
#DNSStubListener=udp
```
I did not change that config from what it was when it still worked. And if I uncomment `Domains=fritz.box` it does not even resolve the FQDN:
```
22# ping unten.fritz.box
ping: unten.fritz.box: Name or service not known
```

**Comment by fermulator** [comment]
Does anyone know for this backwards compatibility breakage suffered by "distro default configs" ... what the proper workaround (by systemd-resolv configuration) is?  (we don't want to wait for distros to fix this)

I am on a standard residential network, no domain.  What configuration in `/etc/systemd/resolved.conf` is required in order to get systemd-resolv to allow local single-label lookups sent to the local DNS server again?

I've been scouring https://www.freedesktop.org/software/systemd/man/systemd.network.html and trying a few key configurations but nothing is completely obvious.

I have too many systems, too many servers, ranging of varying implementations -- I cannot currently go and rework my whole network config by adding a domain to the router; too fearful of the repercussions across systems.

**Comment by poettering** [comment]
I think we can close this one. Since e6b2d948f8f5aabf6cdede8bd39256fe83db205e we write out `/run/systemd/resolve/stub-resolv.conf` which is preferably used as symlink target for `/etc/resolv.conf`. It lists the search domains discovered, and hence should fix the original issue reported here, as in that case the search path logic will then be done client-side. Closing hence.
