### ISSUE TITLE
o_O

### ISSUE THREAD

**Issue by sixtyfive** [systemd/systemd#6265]
Dear Lennart,

answering an issue in a timely manner is a great thing and I thank you for it. Thanking me for my understanding is an assumption, but one that was made in a polite manner. Some of the other language employed in your response to #6259 feels borderline-aggressive to me and I do not understand why you felt it was necessary. If you felt threatened by what I had written then I'd like to apologize for it. What I find outright offensive, though, is the way in which you immediately locked the issue down again. It would be immensely sad if you felt that that was something you had to do. It seems to me that systemd has become the fault line of the biggest changes in the FOSS world and its attached noncommercial and commercial ecosystems. My heartfelt compassion if the pressure thus exerted upon you as the systemd maintainer causes such feelings, and consequently, behaviour.

Maybe yourself, Linus and a couple of others from both sides of that fault line need to have a long, private meeting with lots of your respective preferred beverages and work through all of the things that will lead to more and more hardship if the only way they're being addressed is in internet fora such as this.

Please don't bother unlocking #6259 or even locking this issue here. In fact, I suggest that you append all three messages to #6237 where they would have originally belonged and then delete the newer issues. I will not concern myself or bother you with this any further.

All the best,
and I mean that,

Jonathan

**Comment by poettering** [comment]
This is a bug and feature tracker, and not a discussion forum. We have a tonload of work to do, and we will lock down bugs if they aren't on topic about a bug or feature. You know, when we locked the #6237 bug we did so, because the peanut gallery started posting agressively there, this is *not* reddit after all, but is supposed to remain a useful bug tracker. We ended up deleting a number of insulting comments, and then locked things down. 

This isn't the first time something like this happen, and we often end up opening up those issues again after a week or two, when the Internet (i.e. reddit) lost interest and only the people who actually care and have something smart to say remain. You know, but if you then try to circumvent the lockdown, and just open one new bug and then another, then that's really just a way to majorly piss us off...

You know, you should think for one instant how it is if you sit on the other end of the project and get all the shit you can get regardless if there's actually anything real, or just redditors gone crazy.

Anyway, this bug is wildly off-topic too. Closing and locking this one too, hence. And please, don't be a dick about this, this is a bug and feature tracker, not a discussion forum without bounds. If you just look for a place to vent your opinion, please do so on reddit, it's the much much better place, and you'll find a ton more like-minded people there. And btw, I do browse through it from time to time too, hence nothing is really lost for you, if you want my attention you have a good chance you'll get it there too, and that with the great benefit of not also pissing us off by misusing our bug tracker for something else.
