### ISSUE TITLE
"Cgroup: Remount Is Not Allowed" on shutdown and reboot 

### ISSUE THREAD

**Issue by flaphoschi** [systemd/systemd#6314]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd >= 233.75

### Used distribution

Archlinux

### In case of bug report: Expected behaviour you didn't see

This message should not printed on shutdown or reboot.

### In case of bug report: Unexpected behaviour you saw

On shutdown or reboot this message is printed on the terminal. 

### In case of bug report: Steps to reproduce the problem

1. No special configuration regarding CGROUPS
2. _systemctl_ reboot OR _systemctl poweroff_

Hello!
I assume that this message is a false positive, but I can't proof it. At least all affected systems seem to work without a real problem. At least since the upgrade to >= 233.75 a bunch of users have noticed this message and are worried about a possible malfunction. Please note, that the message is not included in _journalctl_, probably because "/" is already read-only or unmounted.

Thank you

Further resources:
https://bugs.archlinux.org/task/54746
https://bbs.archlinux.org/viewtopic.php?id=227974

**Comment by poettering** [comment]
Hmm, is "Cgroup: Remount Is Not Allowed" the precise wording you see? We do not generate any such message in the systemd codebase, which confuses me.

Do you get this on a physical machine or in some container of some form?

**Comment by flaphoschi** [comment]
Hmm. Probably it is related to https://github.com/systemd/systemd/issues/2275?
Archlinux [seems](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/systemd&id=96a755435827f54f326c3b6a44f6f43c9040e91d) to use the hybrid-mode.

**Comment by evverx** [comment]
The kernel prints this warning when something tries to remount `cgroups`. The message has been changed recently by https://github.com/torvalds/linux/commit/5136f6365ce3eace5a926e10f16ed2a233db5ba9#diff-f1d702fa7c504a2b38b30ce6bb098744L1550 though.

Could you run the following commands
```sh
cat >/usr/lib/systemd/system-shutdown/debug.sh <<_EOF_
#!/bin/sh
mount -o remount,rw /
dmesg > /shutdown-log.txt
mount -o remount,ro /
_EOF_

chmod a+x /usr/lib/systemd/system-shutdown/debug.sh
systemctl reboot
```
and then paste the output of
```
grep -i 'remount is not allowed' /shutdown-log.txt
```
?

Do you know whether `systemd` is being used by your `initramfs` or not?

**Comment by flaphoschi** [comment]
Hi!
Done. Here the result, but it doesn't show much:

```
$ grep -i 'remount is not allowed' /shutdown-log.txt
$ grep -i 'remount' /shutdown-log.txt
[  405.995827] systemd-shutdown[1]: Remounting '/' read-only with options 'stripe=32717,data=ordered'.
[  406.023014] systemd-shutdown[1]: Remounting '/' read-only with options 'stripe=32717,data=ordered'.

```

As the kernel will remove the message, we will likely see nothing with the upcoming 4.13?

> Do you know whether systemd is being used by your initramfs or not?

Are you refereing to the [HOOKS](https://wiki.archlinux.org/index.php/mkinitcpio#Common_hooks)? No, I'm using the default configuration:

`HOOKS="base udev autodetect modconf block filesystems keyboard fsck"
`

**Comment by evverx** [comment]
Thank you for the quick reply.

> Here the result, but it doesn't show much

It shows that `systemd` doesn't try to remount `cgroups`.

> As the kernel will remove the message, we will likely see nothing with the upcoming 4.13?

The message wasn't removed, it was changed to `cgroup2: unknown option ...`.

It seems that something tries to remount `cgroups` and it doesn't appear to be `systemd`. I'd suggest taking a look at `shutdown` from `initramfs`.

**Comment by flaphoschi** [comment]
Thanks you. I informed downstream (Archlinux)! Maybe just something which was already wrong in first place, causes this now to appear with systemd-233?

**Comment by falconindy** [comment]
Arch just runs systemd-shutdown in the initramfs...

**Comment by flaphoschi** [comment]
:confused:
As you run Archlinux, do you see the message yourself? The only modification in my _mkinitcpio.conf_ is early loading of _i915_ (high-res kernel-mode-setting), _GRUB2_ is using the default-config generated by  _grub-mkconfig_. The first machine is a ThinkPad X220 (UEFI) and the second a T420 (BIOS). I don't use RAID, LUKS or any weird stuff.

**Comment by evverx** [comment]
I might have found a wrong script, but It seems that https://git.archlinux.org/mkinitcpio.git/tree/shutdown#n82 is supposed to unmount everything before running `shutdown` or `reboot`. Also, `shutdown` doesn't seem to be a link to `systemd-shutdown` because `systemd-shutdown` doesn't understand the `-f` option. Could you give a link to the script which you are using as `/shutdown`?

**Comment by falconindy** [comment]
Arch has two shutdown ramfs mechanisms:

1) The shutdown script you found -- that needs to be explicitly added via the 'shutdown' hook in mkinitcpio.conf.
2) [mkinitcpio-generate-shutdown-ramfs.service](https://git.archlinux.org/mkinitcpio.git/tree/systemd/mkinitcpio-generate-shutdown-ramfs.service) -- which is preferred and staticly enabled if the user isn't opting into option 1. This is what causes systemd-shutdown to be installed as /run/initramfs/shutdown.

Since voidhoschi@ isn't using the shutdown hook, I can only assume that it's the latter being used.

**Comment by flaphoschi** [comment]
` 52 HOOKS="base udev autodetect modconf block filesystems keyboard fsck"
`

**Comment by evverx** [comment]
I'm not sure what is going on, but I think that the issue should be reopened.

@voidhoschi , could you try using the `shutdown` hook to check whether the warning disappears or not?

**Comment by evverx** [comment]
I've reproduced the issue. `systemd-shutdown` tries to remount `/oldroot/sys/fs/cgroup/unified` before unmounting it:

![screen shot 2017-07-13 at 19 44 45](https://user-images.githubusercontent.com/10195800/28177568-df36be4a-6803-11e7-952f-938012a36a31.png)

**Comment by evverx** [comment]
I've also read https://bugs.archlinux.org/task/54746 and https://bbs.archlinux.org/viewtopic.php?id=227974. Some people seem to assume that the warning is critical, but, in fact, it can be ignored.

**Comment by poettering** [comment]
Hmm, so did I get this right? ArchLinux calls systemd-shutdown in the initrd shutdown script as last step, i.e. it gets run a second time? I admit I like that concept, even though that never crossed my mind that that could be done...

This second invocation is done with the old root including all of /sys, /proc and so on mounted on /oldroot?

Right now systemd-shutdown will remount everything read-only before attempting to unmount it. For an explanation why, see the commenting on the sources:

https://github.com/systemd/systemd/blob/master/src/core/umount.c#L401

Note that on the first systemd-shutdown invocation, the tool will actually exclude /sys from this remount/umount stuff since its an API VFS, and the exercise hence unnecessary: there's no data that needs syncing. On the second invocation it won't do that anymore, since the paths for the API VFS changed /sys → /oldroot/sys and so on, and it has no special logic for excluding that too.

I think the simplest and prettiest solution would probably be if the kernel would just stop logging about this, and just refuse/ignore the R/O remount request quietly.

One might thinkg we could also special-case /oldroot/sys and not attempt to remount/umount that but I think this wouldn't work ultimately: after all the whole reason we transition back into the initrd is to get rid of /oldroot, and hence not getting rid of /oldroot/sys would be a big problem...

@htejun any chance you can change the kernel to just stop logging about the remount R/O attempts of cgroupfs? Is there any really good reason to keep that?

**Comment by flaphoschi** [comment]
I assume this is just a [workaround](https://bugs.archlinux.org/task/54746#comment159336) and not a solution?

**Comment by falconindy** [comment]
Arch's shutdown ramfs (the one relevant to this discussion) calls systemd-shutdown as the *only* step. It's installed as /run/initramfs/shutdown.

**Comment by htejun** [comment]
cgroup2 now has mount options anyway (nsdelegate), might as well support ro too. I'll look into it. Thanks.

**Comment by htejun** [comment]
Ah, ro support happened automatically with the nsdelegate change. The new kernels should succeed with the ro mounting.

**Comment by evverx** [comment]
@htejun , thank you. I didn't notice that https://github.com/torvalds/linux/commit/5136f6365ce3eace5a926e10f16ed2a233db5ba9#diff-f1d702fa7c504a2b38b30ce6bb098744L1550 had fixed remounting as well, so I wrote that the kernel was going to print something like `cgroup2: unknown option ...`. In fact, that warning is printed when a totally unknown option is passed to `mount`, for example
```sh
bash-4.3# mount -o remount,unknown-mount-option /sys/fs/cgroup
bash-4.3# dmesg | grep cgroup
...
[ 1439.426346] cgroup: cgroup2: unknown option "unknown-mount-option"
```
The issue can be closed. I'm sorry about the mix-up.

**Comment by flaphoschi** [comment]
Thanks :smile:

**Comment by BurhanDanger** [comment]
systemd 235.0-1 Creates `cgroup: cgroup2: unknown option "nsdelegate"` message with linux-lts 4.9.54-1

**Comment by mbiebl** [comment]
> systemd 235.0-1 Creates cgroup: cgroup2: unknown option "nsdelegate" message with linux-lts 4.9.54-1

@BurhanDanger this requires Linux 4.13, see https://github.com/systemd/systemd/commit/4095205ecccdfddb822ee8fdc44d11f2ded9be24 and
https://patchwork.kernel.org/patch/9807945/

Afaics, the warning is harmless though

**Comment by BurhanDanger** [comment]
I know it's for 4.13 . Just wondering if it'll cause any problem.

**Comment by cirrusUK** [comment]
Just to say Archlinux using kernel [ 4.12.14-1-ck-nehalem](https://wiki.archlinux.org/index.php/linux-ck) and systemd 235.0-1
 also shows `cgroup: cgroup2: unknown option "nsdelegate"`
i just installed 4.13 tho i've not yet rebooted to check if persists, if so i will report back.

**Comment by htejun** [comment]
Yeah, the kernel added a new cgroup2 option nsdelegate and systemd now tries to mount with the option specified first, which triggers the warning in kernels which don't support them. They're harmless and will go away on kernels v4.13+. systemd *can* check kernel version to decide whether to try nsdelegate or not if this is too annoying.

**Comment by hphilm** [comment]
Would be great if **systemd** is able to check if the function is available or not before trying it ...

**Comment by evverx** [comment]
I'm not sure checking a kernel version works when `nsdelegate` is backported, so it seems that the only reliable way to ensure that `nsdelegate` is available is to try using it.

**Comment by philmmanjaro** [comment]
**openrc** fixed it with: https://github.com/OpenRC/openrc/commit/a769ea1b92f47254edf11458d2c8b79d3819e0e6 https://github.com/OpenRC/openrc/commit/2a203b9b6e91e4ed140750eb9223012035870864. See also https://github.com/OpenRC/openrc/issues/164

**Comment by evverx** [comment]
@philmmanjaro the code you mentioned does roughly the same as `systemd`: it checks whether `cgroup2` is supported and then try mounting `cgroup2` with `nsdelegate`. Moreover, the author of the code wrote the following:
> Currently I'm not sure of a way to know whether I can use the nsdelegate option without trying it and failing, so that message is harmless.

Could you elaborate on why you think that the message has gone?
