### ISSUE TITLE
Avoid requiring a "kvm" system group

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#6360]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234, master

### Used distribution

> Debian unstable

PR #5597 introduced a rule for `/dev/kvm`. This now causes a journal error

    systemd-udevd: Specified group 'kvm' unknown

in any place where it doesn't exist. That could be initrds, non-x86 systems (which don't have this concept) or simply machines which don't have QEMU installed, where it doesn't make sense to create the  group. "kvm" is not at all a generally useful and LSB defined standard group, so creating it everywhere seems like a waste.

As this rule is pretty much a Fedora-ism, would you be okay with not writing it at all if `--with-dev-kvm-mode` isn't being set?

**Comment by keszybz** [comment]
> It's not a basic system group in Debian and thus not always available. The qemu package creates that group on demand.

That's the whole reason for the change: the device node always exists (when the kernel/hardware supports kvm), and it's confusing if the ownership of the device node changes after qemu package is installed. During the original discussion people raised the issue that it's entirely reasonable to use qemu not from the official package, but a statically combined or a self-compiled version, and we want to support that without any additional steps.

So I'd prefer to just consider kvm group standard… The fact that LSB does not define it doesn't matter much, it's a dead standard, and we go outside of it in countless ways (starting with `/run`).

> As this rule is pretty much a Fedora-ism, would you be okay with not writing it at all if --with-dev-kvm-mode isn't being set?

That'd be yet another thing to remember when setting compilation options and another way to subtly break the system. I guess we can do it if you really need that, but I'm at most +0 because of the additional complexity that brings.

**Comment by mbiebl** [comment]
I find it more confusing (and wasteful) if the udev package had to create a kvm system user on a variety of architectures and environments which will never have kvm.
The only alternative is to patch out that rule downstream, but we'd rather avoid that if possible.

**Comment by poettering** [comment]
The groups listed in sysusers.d/basic.conf are really the baseline of groups we expect. Yes, some archs don't have KVM, but some services have no audio either, yet we install the "audio" group. I am pretty sure that expecting this really really basic group to be around is not too much to ask, KVM has been around long enough, and shipping the udev rules isn't particularly crazy...

If distros lack the group I think the systemd package/build script/... should just add it in.

**Comment by poettering** [comment]
> or simply machines which don't have QEMU installed

BTW, qemu is not the only user of that device node, there are a number of other clients, and I think some might even be packaged for Debian (that minimal one shipped along the linux kernel iirc, as well as current virtualbox iirc). Hence Debian should probably pull out the group/udev rule from qemu anyway... It's really a generic OS feature now, not private property of qemu

**Comment by mbiebl** [comment]
@poettering can you be more specific about those other clients. I can't find any information regarding them using /dev/kvm.

**Comment by poettering** [comment]
This uses /dev/kvm, but is not qemu:

https://packages.debian.org/sid/kvmtool

**Comment by poettering** [comment]
(i assumed kvmtool was part of the kernel these days, but apparently that was only the plan but never happened)

**Comment by poettering** [comment]
and the vbox thing I apparently misunderstood, sorry. I assumed recent vbox versions gave up on their own kernel extensions and just used kvm as backend too, but apparently i was mistaken, at least my google skills don't show that...

**Comment by poettering** [comment]
Anyway, I am very sure that /dev/kvm should be considered a standard system concept now, sharedby apps, and generic enough to be set up by systemd properly. I hope this makes some sense, and will close this now...

**Comment by stsp** [comment]
As dosemu2 uses KVM, we have a
very big problems because of this
decision and https://github.com/endlessm/systemd/commit/8e7e8e42554cb27caf8f06fd0733c5b18bc0347a
in particular.
It seems the decision here was that
only qemu needs KVM, but it is actually
backwards: other projects that _could_
use KVM (vbox, dosbox) can't do so.
dosemu2 seeks for work-arounds.
Also it seems the decision here was
made around @poettering opinion...
Could this be please reconsidered?
Each individual package should not
strive to set up the kernel device nodes.

**Comment by mbiebl** [comment]
The Debian package fwiw does no longer ship this patch. See
https://salsa.debian.org/systemd-team/systemd/-/commit/4fc3fa53bfa6e16ceb6cd312f49003839b56144a from 2018

**Comment by stsp** [comment]
Oh, thanks!
So its just a matter of adding proper
deps.
But I am a bit confused.
Most rules seems to be provided by
the udev package, but this one - by
systemd itself. So should I add a dep
on systemd-240 (where this seems to
be fixed), rather than on udev?
Not that its a biggest problem in the
world, but I never considered to add
a dep on systemd before...

**Comment by stsp** [comment]
The log msg says:
`Make /dev/kvm accessible to local users and group kvm.`
Does this mean that the local user
will _not_ have to add himself to the
kvm group to access /dev/kvm?

**Comment by mbiebl** [comment]
> The log msg says:
> `Make /dev/kvm accessible to local users and group kvm.`
> Does this mean that the local user
> will _not_ have to add himself to the
> kvm group to access /dev/kvm?

Correct. This assumes your local user has an active logind session.
That said, the documentation regarding uaccess could certainly be better, see #4288

**Comment by stsp** [comment]
Thanks, that should be an adequate
solution then. From what I could gather,
it assigns an acl to /dev nodes upon
the user login.
I added the dep for udev-240, which
unfortunately means dropping everything
prior to eoan. But at least its a solution.
