### ISSUE TITLE
systemd does not change the user and group ownership of `RuntimeDirectory` when `root` is not explicitly assigned to `User`

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#6391]
How to reproduce:
```sh
cat <<'EOF' >/etc/systemd/system/a.service
[Service]
RuntimeDirectory=rd
RuntimeDirectoryPreserve=yes
ExecStart=/bin/sh -x -c 'id; ls -l /run'
User=systemd-coredump
EOF

systemctl daemon-reload

systemctl start a

ls -l  d /run/rd
# drwxr-xr-x 2 systemd-coredump systemd-coredump 40 Jul 17 20:49 /run/rd

sed -i 's/^\(User\)/#\1/' /etc/systemd/system/a.service

systemctl daemon-reload

systemctl start a

ls -ld /run/rd
# drwxr-xr-x 2 systemd-coredump systemd-coredump 40 Jul 17 20:49 /run/rd
# should be
# drwxr-xr-x 2 root root 40 Jul 17 20:49 /run/rd
```

Using `User=root` explicitly works well
```sh
echo 'User=root' >>/etc/systemd/system/a.service

systemctl daemon-reload

systemctl start a

ls -ld /run/rd
# drwxr-xr-x 2 root root 40 Jul 17 20:49 /run/rd
```

**Comment by evverx** [comment]
Actually, `RuntimeDirectoryPreserve` has made the bug visible, but it is not needed to reproduce the missing `chown`. Here is a way to reproduce the bug without `RuntimeDirectoryPreserve`
```sh
mkdir /run/rd
chown systemd-coredump:systemd-coredump /run/rd
cat <<'EOF' >/etc/systemd/system/a.service
[Service]
RuntimeDirectory=rd
ExecStart=/bin/sh -x -c 'id; ls -ld /run/rd'
EOF
systemctl daemon-reload
systemctl start a
```
```
+ id
uid=0(root) gid=0(root) groups=0(root)
+ ls -ld /run/rd
drwxr-xr-x 2 systemd-coredump systemd-coredump 40 Jul 17 23:22 /run/rd
a.service: Executing: /bin/sh -x -c 'id; ls -ld /run/rd'
```

**Comment by yuwata** [comment]
@evverx I've posted a fix in PR #6384. Please take a look.

**Comment by ghost** [comment]
So what is there rationale for {State,Cache,Log,Configuration}Directory=, or is there none and is this just an exercise to add more code

**Comment by yuwata** [comment]
@doverride Please see the discussion in PR #6384. Also, I am planning that I will use the option for systemd's daemons.

**Comment by ghost** [comment]
Thanks, very far fetched. but i suppose sky is the limit...

**Comment by evverx** [comment]
`chown` had stopped working long before #6384 was opened, so this issue has nothing to do with `{State,Cache,Log,Configuration}Directory=`. I think it is better to continue the discussion in #6384.

**Comment by evverx** [comment]
On the other hand, if two commits had not been squashed, backporting the fix would be much easier.

**Comment by ghost** [comment]
That and i just think {State,Cache,Log,Configuration}Directory= is a bad idea, even after reading #6384

**Comment by evverx** [comment]
@doverride I'm just trying to say that it would be great if you could add a comment explaining why you think that `*Directory=` is a bad idea.

**Comment by ghost** [comment]
I wonder whether there is any realistic demand for this. Also I think the name might be misleading since it seems that this is nothing like RuntimeDirectory. I fear that this functionality might get abused.

     It's really useful for running unprivileged daemons with properly owned resources files in /var, that are created on demand rather than in advance via tmpfiles.


1. There is no VarDirectory=
2. The name implies Directory not file
3. You dont need to create that "var file" every time the service unit is started because /var isnt on a tmpfs like /run is

     useful when running things in early-boot (i.e. before tmpfiles ran), and for the ability to have unit file be self sufficient to describe the execution environment of a service, so that dropping in the unit file (or running an ad-hoc one via systemd-run) is entirely sufficient to get the full environment into place.

Any realistic examples?

    Then, I think this is useful as a pretty way to get host resources for RootImage=/RootDirectory= units, without having to rely on specific BindPaths= stanzas.

And it is most likely going to be abused

    Then, I think this is useful to eventually provide a generic "systemctl reset" command or so, which could be used something like this:

    systemctl reset --what=logs,state,cache httpd.service

    which would clean the relevant bits of the service.

How does this relate to .*Directory=?
Directory is a directory. Its not a directory and files in it

Besides, so is systemd now going to delete let's say a service log file now? If so what is the use of that log file in this scenario?

**Comment by ghost** [comment]
From what I hear, it seems that systemd-tmpfiles is a mistake. It should have been implemented into systemd seems to be the argument if i understand correctly. So the solution is to make systemd a little bit tmpfiles-like?

How about dropping tmpfiles and just make systemd do all the tmpfiles stuff.

Systemd is already all-powerful, and doing way more than any normal system manager is supposed to be doing.

I just this its excessive, pervers in a way. Just because something is possible does not automatically mean its the right thing to do.

Anyhow i just gave my opinion. I dont expect sympathy. Just want to vent my dissatisfaction.

**Comment by poettering** [comment]
> There is no VarDirectory=

There's StateDirectory= under /var/lib. Daemons tend not to own files directly below /var.

> The name implies Directory not file

Yes, that's how /var/lib, /var/log, /var/cache are usually managed: every service gets its own subdir there.

> Any realistic examples?

Pretty much any service that has a dir below /var/lib, /var/log or /var/cache. Just look through there...

> How does this relate to .*Directory=? Directory is a directory. Its not a directory and files in it

When "systemctl reset --what=logs httpd.service" is executed then systemd would simply empty /var/log/httpd (or whatever is delcared in httpd.service), that's all.


> Besides, so is systemd now going to delete let's say a service log file now? If so what is the use of that log file in this scenario?

Hmm, not sure I follow? This is simply about adding a way how services can be reset to their factory defaults, simply by flushing out their state data. Of course, services shouldn't using StateDirectory= if they can't start with an empty state directory in the first place...

**Comment by ghost** [comment]
Yes I think the issue is that you do not understand my concerns. I am trying to contain systemd to the exltent possible. You are duplicating tmpfiles functionality in systemd.

Now systemd needs to be able to create config cache log state directories, and be able to unlink the corresponding content. This is something tmpfiles is allowed to do.

Why not just call tmpfiles in a unit instead to deal with this? Why do we have to associate these excessive permission with systemd when we have tmpfiles?

I just think this is excessive, far fetched. If i am wrong then give me a real example and not some hypotheticals.

But you dont have to justify your decisions to me. It is ok. Ill just have to deal with the fall-out

**Comment by poettering** [comment]
> From what I hear, it seems that systemd-tmpfiles is a mistake.

Not at all, there are numerous cases where files below /var or /run are not directly related to a single service, and for those cases there is tmpfiles.d. However, I think for running a service with its own private resource dir there's no need to bother with tmpfiles.d and there and it would be nicer, and more obvious to simply declare those within the service itself
