### ISSUE TITLE
systemd should provide utility/functionality to validate the assumption about the os/distribution

### ISSUE THREAD

**Issue by DirkSchmitt** [systemd/systemd#6427]
### Submission type

 - Request for enhancement (RFE)

Systemd makes some assumption about the underlying os (distribution).
Some examples: 

- #6184 here seems to be  _max_bonds=0_  an implicit assumption.
- #6369 expressed an assumption about the hostnames.
- #6237 expressed an assumption about usernames.
- …

For the _normal_ sysadmin (as systemd user) this is nontransparent and hard to maintain.

At least there should be an evolving list of such assumptions, as we are already known or discovered by bug reports.

If this assumption not already covered by the systemd configuration validation, there should be an utility which can check the current installation and flag assumptions which are not correct on this machine.

**Comment by poettering** [comment]
systemd is not an app you install, it's something your distribution has to integrate, and they really need to know what they are doing. We have a document DISTRO_PORTING in place, that gives some rough guidelines, but it's not a comprehensive document, and it can't really be one.

The distributions integrate systemd, and possibly alter it to make it fit their requirements. And that's entirely OK, and it#s really not out business to then second-guess that, by providing funcitonality to complain about that again.

Setting things like max_bonds=0 by default is really something your distro should do for you, and if they don't, complain to them please. It's nothing an admin should ever have to bother with, it should just be set up correctly by default. Given that this isn't really documented right now, I'll now add a quick paragraph about this to README, next to the list of other requirements we make on the underlying kernel.

The restrictions systemd makes on the User=/Group= setting are documented already in detail in the man page:

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#User=

It's OK if distros enforce less strict rules for normal user names btw, systemd doesn't really care. It only cares for the system users of system services where systemd does privilege dropping, where it's stricter in order to keep them portable.

I will close this now, since I don#t think such validation functionality would really be a good idea. We don't police downstream, we just offer them software and leave it to downstreams to adapt them to whatever they want. Most requirements we make to run systemd unmodified are already encoded in the requirements list in README, and we shoul extend that wherever we need to, and it's up to the distros to honour that or ignore our recommendations. (And I'll add the max_bonds=0 thing there)
