### ISSUE TITLE
systemd-networkd-wait-online seems to fail for no reason

### ISSUE THREAD

**Issue by fabiocannizzo** [systemd/systemd#6441]
### Submission type

 - Bug report
 

### systemd version the issue has been seen with

> 233

### Used distribution

> Linux Arch

### In case of bug report: Unexpected behaviour you saw

> The default openvpn-server configuration file depends on systemd-networkd-wait-online, which times out with error:
systemd-networkd-wait-online[279]: Event loop failed: Connection timed out
>My system has only 2 interfaces:
> - lo, which is ignored
> - eth0, is up and running and perfectly configured

> It may be useful to report my interface configuration, and some additional sysctl I add:

### /etc/systemd/network/eth0.network
[Match]
Name=eth0
[Network]
#DHCP=ipv4
Address=192.168.1.2/24
Gateway=192.168.1.1
DNS=8.8.8.8
IPForward=ipv4
LinkLocalAddressing=no

### sysctl.conf
net.ipv4.ip_forward=1
net.ipv4.conf.default.forwarding=1
net.ipv4.conf.all.forwarding=1
net.ipv4.conf.eth0.forwarding=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.eth0.disable_ipv6=1
net.ipv4.conf.default.rp_filter=0
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.eth0.rp_filter=0

### this shows the interface is configured. It also works correctly, although I do not show that here.
[root@cassandra ~]# ip a show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:41:05:c1:fd:49 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever

### In case of bug report: Steps to reproduce the problem

[root@cassandra ~]# /usr/lib/systemd/systemd-networkd-wait-online -i eth0
Event loop failed: Connection timed out

**Comment by poettering** [comment]
That happens when waiting for a connection times out. You can use systemd-networkd-wait-online's default timeout of 2min with the --timeout= switch it has. We could certainly improve the log message though, saying all that.

Consider doing "networkctl status -a" to have a detailed look at the interface's state and to get an idea why the tool doesn't consider the interface to be fully ready.

**Comment by fabiocannizzo** [comment]
Hi Lennart

Thanks for your reply.

I think there is already a timeout, after two minutes it fails but openvpn starts anyway. It just delays openvpn startup (arguably I could remove the dependency from the openvpn service file, but I prefer not to modify the default file provided by Linux Arch).

networkctl shows eth0 is 'configuring'. I am not sure why that is the case, in fact, I am connecting to the machine using ssh via that interface. May be because I disabled ipv6?  Do you have any suggestion to point me in the right direction? A part from configuring the interface with systemd-networkd and applying that sysctl.d file, I do not do any other configuration.

Thanks

* 2: eth0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/eth0.network
            Type: ether
           State: routable (configuring)
            Path: platform-1c50000.ethernet
      HW Address: 02:41:05:c1:fd:49
         Address: 192.168.1.2
         Gateway: 192.168.1.1 (Technicolor)
             DNS: 8.8.8.8

**Comment by software-artificer** [comment]
I'm having pretty much the same issue with `systemd-networkd-wait-online`. It does not work if you disable IPv6 stack and don't have IPv6 sitting on your interface.

I have something very similar to what you are describing with PPPoE interface, because my provider does not support IPv6 and `ppp0` interface never receives IPv6 it just times out. See https://github.com/systemd/systemd/issues/5841.

**Comment by software-artificer** [comment]
There is a working patch in https://github.com/systemd/systemd/issues/2713, I tested it and can confirm that it works with IPv6 stack disabled.

**Comment by vindicatorr** [comment]
Is this patch supposed to fully clear up the wait?

On Arch using https://github.com/systemd/systemd-stable/commit/743b771c559c6101544f7358a42c8c519fe4b0db I still have the timeout issue.

It's fine if I specify the interface to wait for, but the plain-jane "/usr/lib/systemd/systemd-networkd-wait-online" with no interface specified ends up timing out.
If I specify the interface (ethernet OR ppp (both dhcp4 only)), it's fine.

"netctl/network wait-online" does not exhibit the timeout issue that systemd's implementation does.

**Comment by ghost** [comment]
> We could certainly improve the log message

Definitely. It should at the very least say on which interface timeout was hit.

**Comment by fabiocannizzo** [comment]
In my opinion the solution is not to just improve the error message.If ipv6 is explicitly disabled, which is a legitimate use case, it should not wait for ipv6 at all.

**Comment by ghost** [comment]
It's not a solution of course - it's just generic remark that the better error message would be beneficial regardless if ipv6 or anything else causing the failure.

**Comment by ssahani** [comment]
Tested with current git no more reproducible.

cat /lib/systemd/network/20-en1.network
```
[Match]
Name=host

[Network]
Address=192.168.1.2/24
Gateway=192.168.1.1
DNS=8.8.8.8
IPForward=ipv4
LinkLocalAddressing=no
```

**Comment by mikken** [comment]
I still have this with systemd 237 in Arch and in Gentoo.

**Comment by kmansoft** [comment]
Ubuntu 18.04 (beta 2), systemd 237-3ubuntu7

I've disabled NetworkManager and network services, wanting to use systemd-networkd and systemd-resolved.

My /etc/systemd/network/wired.network:

> [Match]
> Name=enp0s31f6
> 
> [Network]
> #DHCP=yes
> #DNS=8.8.8.8
> #DNS=8.8.4.4
> Address=192.168.88.202/24
> Gateway=192.168.88.1
> 
> [DHCP]
> UseDNS=false

DNS servers are set in /etc/systemd/resolved.conf

> [Resolve]
> DNS=8.8.8.8 8.8.4.4
> #FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
> #Domains=
> #LLMNR=yes
> DNSSEC=allow-downgrade
> Cache=yes
> #DNSStubListener=udp

My networking is working, everything's just fine.

$ networkctl status -a

> ● 1: lo
>        Link File: /lib/systemd/network/99-default.link
>     Network File: n/a
>             Type: loopback
>            State: carrier (unmanaged)
>          Address: 127.0.0.1
>                   ::1
> 
> ● 2: enp0s31f6
>        Link File: /lib/systemd/network/99-default.link
>     Network File: /etc/systemd/network/wired.network
>             Type: ether
>            State: routable (configuring)
>             Path: pci-0000:00:1f.6
>           Driver: e1000e
>           Vendor: Intel Corporation
>            Model: Ethernet Connection (2) I219-V
>       HW Address: b0:6e:bf:30:21:8e (ASUSTek COMPUTER INC.)
>          Address: 192.168.88.202
>          Gateway: 192.168.88.1 (Routerboard.com)
>     Connected To: MikroTik on port bridge

And yet:

$ sudo systemctl status systemd-networkd-wait-online.service 

> ● systemd-networkd-wait-online.service - Wait for Network to be Configured
>    Loaded: loaded (/lib/systemd/system/systemd-networkd-wait-online.service; enabled; vendor preset: enabled)
>    **Active: failed (Result: exit-code)** since Sun 2018-04-08 15:16:33 MSK; 4h 1min ago
>      Docs: man:systemd-networkd-wait-online.service(8)
>  Main PID: 1099 (code=exited, status=1/FAILURE)

$ sudo systemctl start systemd-networkd-wait-online.service 

> Job for systemd-networkd-wait-online.service failed because the control process exited with error code.
> See "systemctl status systemd-networkd-wait-online.service" and "journalctl -xe" for details.
> 

status again:

> Apr 08 19:18:14 tammy systemd[1]: Starting Wait for Network to be Configured...
> Apr 08 19:18:14 tammy systemd-networkd-wait-online[20530]: ignoring: lo
> Apr 08 19:20:14 tammy systemd-networkd-wait-online[20530]: Event loop failed: Connection timed out
> Apr 08 19:20:14 tammy systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILU
> Apr 08 19:20:14 tammy systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
> Apr 08 19:20:14 tammy systemd[1]: Failed to start Wait for Network to be Configured.

What exactly is it trying to do? Why is "event loop failed" - "connection timed out" - connection to what? why? My networking is already up, what is it doing?

---

I like systemd managed networking, NetworkManager just tried to do too much and creates a mess. But this failure is just really weird.

Is it because the network interface is stuck at "configuring"?

How can I tell what it's waiting for?

**Comment by fabiocannizzo** [comment]
@ssahani The problem seems still there. Have you tried to reproduce by setting the following sysctl? 
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.eth0.disable_ipv6=1

**Comment by mikken** [comment]
Bug's still present in systemd 239.

**Comment by sknaumov** [comment]
I have the same problem if one of my ethernet interfaces with static address has no carrier and I explicitly ask systemd to bring it up using ConfigureWithoutCarrier=yes.
systemd-networkd-wait-online shouldn't wait for such an interface, as it is expected that cable may be unplugged.

**Comment by ReubenM** [comment]
systemd-networkd-wait-online really needs an option somthing like "--any_of=" with support for globbing and lists so that when used, any matching non-local interface being configured would be sufficient to qualify the system as being online.

Right now the only options available are explicit and exclusive. This doesn't work when I have a mobile system with multiple interfaces. Only one is normally used, and which one depends on the whim of whoever is plugging it in.

**Comment by aTanW** [comment]
Just the same thing happens in multilink env, agree with @ReubenM

**Comment by n8v8R** [comment]
just started to see this happening with 240.34-2 on Arch Linux.

**Comment by llamahunter** [comment]
seeing with CoreOS 1967.4.0

**Comment by jo-so** [comment]
For me, `systemd-networkd-wait-online` runs into a timeout, because the virtual interface *anbox0* never goes online. Maybe s-n-w-o could ignore bridges, too. I can't patch all calls of s-n-w-o to ignore *anbox0*.

```
/sys/class/net/anbox0/addr_assign_type:1:1
/sys/class/net/anbox0/address:1:22:e6:e9:e9:44:c2
/sys/class/net/anbox0/addr_len:1:6
/sys/class/net/anbox0/broadcast:1:ff:ff:ff:ff:ff:ff
/sys/class/net/anbox0/carrier:1:1
/sys/class/net/anbox0/carrier_changes:1:0
/sys/class/net/anbox0/carrier_down_count:1:0
/sys/class/net/anbox0/carrier_up_count:1:0
/sys/class/net/anbox0/dev_id:1:0x0
/sys/class/net/anbox0/dev_port:1:0
/sys/class/net/anbox0/dormant:1:0
/sys/class/net/anbox0/flags:1:0x1003
/sys/class/net/anbox0/gro_flush_timeout:1:0
/sys/class/net/anbox0/ifindex:1:6
/sys/class/net/anbox0/iflink:1:6
/sys/class/net/anbox0/link_mode:1:0
/sys/class/net/anbox0/mtu:1:1500
/sys/class/net/anbox0/name_assign_type:1:3
/sys/class/net/anbox0/netdev_group:1:0
/sys/class/net/anbox0/operstate:1:unknown
/sys/class/net/anbox0/proto_down:1:0
/sys/class/net/anbox0/tx_queue_len:1:1000
/sys/class/net/anbox0/type:1:1
/sys/class/net/anbox0/uevent:1:DEVTYPE=bridge
/sys/class/net/anbox0/uevent:2:INTERFACE=anbox0
/sys/class/net/anbox0/uevent:3:IFINDEX=6
```

**Comment by llamahunter** [comment]
It appears that if ipv6 is disabled after boot (i.e. not via kernel args), this failure will occur.

**Comment by jo-so** [comment]
At me, IPv6 is enabled and I'm using it.

**Comment by thedemonium** [comment]
me have too  systemd 237-3ubuntu10.13
root@system ~ # time /lib/systemd/systemd-networkd-wait-online
Event loop failed: Connection timed out

real	2m0.126s
user	0m0.004s
sys	0m0.012s

ipv6 is disabled in 
linux	/vmlinuz-4.15.0-43-generic root=ZFS=rpool/ROOT/ubuntu ro  quiet splash ipv6.disable=1 $vt_handoff

**Comment by kolcon** [comment]
Bug still there in 241-r1

**Comment by yuwata** [comment]
After v241 was released, I've updated networkd and wait-online. If possible, please test the current git master. Thank you.

**Comment by aude** [comment]
Thanks a lot @yuwata! I want to test once it's available at my system.

I use Arch Linux, and the current release is from [v241-stable](https://github.com/systemd/systemd-stable/tree/v241-stable). I checked, and your commits are not merged there.

To me, it looks like your fix will be available once v242 is released. Excited!

**Comment by jo-so** [comment]
I've tested »systemd 241 (241-1158-g84ce204)« and it still fails with: Event loop failed: Connection timed out.

BTW: Why is --any not the default? Running systemd-networkd-wait-online --any returns immediately

**Comment by mullnerz** [comment]
For me disabling  IPv6 with the sysctl method caused the issue (in an environment with Ubuntu 18.04 LXC containers)

Found a workaround by adding the following lines to the interface in the netplan yaml config:

```
      dhcp6: false
      accept-ra: no
      link-local: [ ]
```

With this netplan generated the neccesary lines to `/run/systemd/network/10-netplan-eth*.network`
```
[Network]
DHCP=ipv4
LinkLocalAddressing=no
IPv6AcceptRA=no
```

After this change `networkctl status -a` shows the correct state for the interface (before the workaround it showed "configuring"):

```
           State: routable (configured)
```

And finally also systemd-networkd-wait-online started to work as it should (before the workaround it waited for 2 minutes):

```
# time /lib/systemd/systemd-networkd-wait-online
ignoring: lo
managing: eth1

real	0m0.007s
user	0m0.000s
sys	0m0.006s
```

Thanks you, and I hope it could help others.

**Comment by jo-so** [comment]
I didn't know about *networkctl*. Here's what it gives at me.

```
● 1: lo
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: n/a
            Type: loopback
           State: carrier (unmanaged)
         Address: 127.0.0.1
                  ::1

● 2: wlp59s0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/20-dhcp.network
            Type: wlan
           State: routable (configured)
            Path: pci-0000:3b:00.0
          Driver: iwlwifi
          Vendor: Intel Corporation
           Model: Wireless 7260 (Dual Band Wireless-AC 7260)
      HW Address: ac:fd:ce:3d:9e:83 (Intel Corporate)
         Address: 192.168.178.22
                  2a02:810a:87c0:3a11:aefd:ceff:fe3d:9e83
                  fe80::aefd:ceff:fe3d:9e83
         Gateway: 192.168.178.1 (AVM Audiovisuelles Marketing und Computersysteme GmbH)
                  fe80::ca0e:14ff:febf:fcd0 (AVM Audiovisuelles Marketing und Computersysteme GmbH)

● 18: anbox0
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/20-anbox0.network
            Type: bridge
           State: no-carrier (configuring)
          Driver: bridge
```

The *anbox0* interface is down, but it's a bridge and shouldn't block *systemd-networkd-wait-online*, but it does. When I bring the interface up, *systemd-networkd-wait-online* returns immediately.

**Comment by keszybz** [comment]
> The anbox0 interface is down, but it's a bridge and shouldn't block systemd-networkd-wait-online, but it does.

Why do you think systemd-networkd-wait-online should ignore it?

**Comment by aude** [comment]
For me, I'd like to have an option to say that "we're online" if _one_ Internet-facing interface is up. Because that's enough to reach the Internet.

For example, I have 2 Internet-facing interfaces: wifi and ethernet. I don't want to wait for both to be up, because some times I'm docking my computer somewhere I don't have any known WiFi nearby. (And I don't want my boot to wait for WiFi when ethernet is already up.)

It is possible to exclude certain interfaces from systemd-networkd-wait-online, with `ConfigureWithoutCarrier=yes`, which is probably correct for @jo-so's `anbox0` interface. I'm using this method now for my wifi interface, which means systemd-networkd-wait-online always will ignore whether WiFi is up or not.

But there is no way to say "use either one of wifi and ethernet". Now, _both_ must be online in order for systemd-networkd-wait-online to say "we're online".

**Comment by yuwata** [comment]
@mullnerz I hope your case is already supported by #11748. If you are interested in, please test the current git master of v242-rc release (or newer, of course).

@aude 
> I use Arch Linux, and the current release is from v241-stable. I checked, and your commits are not merged there.

Yeah, #11748 or wait-online updates within v242 release are mostly new features. So, I think they will not be backported to v241.

> But there is no way to say "use either one of wifi and ethernet". Now, both must be online in order for systemd-networkd-wait-online to say "we're online".

The `--any` option added by #12160 will help you. The PR is already included in v242-rc release.

**Comment by aude** [comment]
That's fantastic news. Thanks for doing the work to make that happen!

**Comment by mullnerz** [comment]
> The _anbox0_ interface is down, but it's a bridge and shouldn't block _systemd-networkd-wait-online_, but it does. When I bring the interface up, _systemd-networkd-wait-online_ returns immediately.

@jo-so Wouldn't an `optional: true` in netplan config help in this case? Give it a try!

**Comment by jo-so** [comment]
@mullnerz What's netplan? I use systemd-networkd.

**Comment by jo-so** [comment]
> > The anbox0 interface is down, but it's a bridge and shouldn't block systemd-networkd-wait-online, but it does.
> 
> Why do you think systemd-networkd-wait-online should ignore it?

Because it's a bridge interface, nothing that should have a real connection to outside.

Why doesn't *systemd-networkd-wait-online* look for a default route to be available? Something like this:
```
% ip --json l l $(ip r get 1.1.1.1 |grep -o 'dev [^ ]*') |jq '.[].operstate'
"UP"
```

**Comment by keszybz** [comment]
@jo-so, you seem to assume that your specific use-case is the only one possible. On my machine, for example, the bridge interface is the one and only interface with an address, so ignoring bridge interfaces would be inappropriate. s-n-w-o is defined as "wait for all configured interfaces to be operational". This certainly is not something that serves all usecases, but it's a well-defined operation.

> Why doesn't systemd-networkd-wait-online look for a default route to be available?

Yeah, that'd be another useful option. We have `--any`, we should add `--default-route`.

**Comment by jo-so** [comment]
@keszybz: could you send the output of `networkctl list` to see, why your hardware interfaces not detected as operational?

In the [last release](https://github.com/systemd/systemd/blob/v241/man/systemd-networkd-wait-online.service.xml#L37), s-n-w-o »By default, it will wait for all links it is aware of and which are managed by systemd-networkd.service(8) to be fully configured or failed, and for at least one link to gain a carrier.« Hence, it should return when at least one default route exists.

**Comment by keszybz** [comment]
> could you send the output of networkctl list to see, why your hardware interfaces not detected as operational?

I have a bunch of network cards, physical and virtual, all enslaved to one bridge. Everything works fine. It's just an example of configuration where ignoring bridge devices would not be appropriate.

**Comment by yuwata** [comment]
> In the [last release](https://github.com/systemd/systemd/blob/v241/man/systemd-networkd-wait-online.service.xml#L37), s-n-w-o »By default, it will wait for all links it is aware of and which are managed by systemd-networkd.service(8) to be fully configured or failed, and for at least one link to gain a carrier.« Hence, it should return when at least one default route exists.

@jo-so I've slightly updated the explanation recently :-)

**Comment by josdotso** [comment]
I've got an ipv6-only box that seems to have this issue. Wild idea: Does this check use an IPv4-only to confirm network up?

**Comment by yuwata** [comment]
> I've got an ipv6-only box that seems to have this issue. Wild idea: Does this check use an IPv4-only to confirm network up?

@josdotso No. Both IPv4 and IPv6 settings in .network files are checked.
Please test with v242 if you do not use v242. And please provide the follwoing:
- .network (and .netdev) files
- debugging logs of `systemd-networkd`. The debugging log can be generated by creating the following file.
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
- Also, please try to run `wait-online` with debug option:
```
# SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd-wait-online
```

**Comment by teknoraver** [comment]
It could be useful to have the possibility to login if physical access is possible on the machine (tty, serial, etc.) instead of being just locked out

**Comment by keszybz** [comment]
@teknoraver wrong bug?

So... does anyone have a case where s-n-w-o is not working as expected with systemd-243? This bug has been open for a long time and we made many changes that improve the situation.

**Comment by teknoraver** [comment]
> @teknoraver wrong bug?
> 
> So... does anyone have a case where s-n-w-o is not working as expected with systemd-243? This bug has been open for a long time and we made many changes that improve the situation.

Hi,

Occasionally (no DHCP server, bad cable, etc.) I get the message "waiting for online.." with a 60 second timeout, which always gets kicked 10 seconds more and more.
I don't know if it's exactly this bug, but it can be useful if a local user is allowed to login and troubleshoot this.

**Comment by keszybz** [comment]
Ability to log in is not directly related to s-n-w-o. If your distro or local configuration orders login sessions after s-n-w-o, than it's not a systemd issue. (I think it would be a stupid setup, but that's not our thing to say.)

**Comment by troyengel** [comment]
> So... does anyone have a case where s-n-w-o is not working as expected with systemd-243? This bug has been open for a long time and we made many changes that improve the situation.

Yes, I maintain a very small piece of software for Dynamic DNS updates and an Arch user reported around February 2019 it stopped working correctly, where it had been working correctly for a long time (I have not updated the code in some time, it just works). Specifically, the timer unit set to activate on boot (`OnActiveSec=0s`) started showing s-n-w-o was not working correctly anymore.

I built a fresh Arch VM and recreated the bug with both `netctl` and `systemd-networkd` wait-online services and can see if fail. The configuration is using DHCP passthrough to my external DHCP server on the network ("bridged nat" I believe VirtualBox calls it); in the case of systemd-networkd, the configuration in in a sub-include file; in the case of netctl, it's a standard setup for that tool - there appears to be no difference in behavior, they both fail the same way. The sub-units are both enabled as appropriate (systemd-networkd-wait-online or netctl-wait-online) as per the systemd docs.

What I seem to see happening generally goes like this at boot:

 - waiting for network-online (and "fails" within milliseconds)
 - failure that timer could not be started due to w-o dependency failure
 - network messages begin that the link is coming online

Basically, when watching the boot you see the network-online target just fail almost immediately, which led me to believe it's not even trying to trigger the sub-unit for a status check; so I updated the s-n-w-o unit (and netctl) to feed it an incorrect, fake network device and set the timeout to something high; running the sub-unit manually, it hangs as expected waiting for a fake NIC to show up. However, when I reboot the wait-online target fails _immediately_, when it should have hung up for awhile waiting for something I injected to cause it to hang.

After network-online target fails almost immediately, a few other unit messages come up _then_ I see the network units start to come to life and work (It's more noticeable with netctl, the output on screen shows it attempting to get the DHCP link for a second or so). And then I can start network-online target manually and it works perfectly.

The best I can make of it is that the wait-online target is simply ignoring that it should be running the linked sub-unit to actually _wait_ for the network to come online, failing immediately as not-online and _then_ the actual network units start to configure. Running it by hand after we get a login shell works, I see the sub-units get activated (my fake-NIC test hangs as expected) when I simply `systemctl start network-online.target`.

Hope this helps! Given I could recreate it as easily as I did, I think others might be able to as well - just the basic Arch setup, nothing fancy, inside a VirtualBox container with bridged NAT and DHCP used inside the VM.

**Comment by filakhtov** [comment]
I haven't followed this issue for a while. My original report of an IPv6 problem is no longer applicable. All other problems I ever faced seems can be remediated by tweaking one network/device configuration option or the other.

**Comment by keszybz** [comment]
@troyengel thank you for the detailed report. It does **not** appear that s-n-w-o is malfunctioning in your case. Instead, it seems that the dependencies between units are not set up as you expect/want them to be. Requisite= means "fail if the listed unit is not started already". You most likely want Requires= instead. Without knowing all the details of your setup, in particular which units are enabled and so on, it is hard to say what exactly is going wrong there. But I think it is your configuration problem, not something to to with s-n-w-o which is not even started.

@filakhtov thanks.

I'll close this then.

**Comment by emmanuelux** [comment]
for me, the problem came from NetworkManager, I had forgot to remove auto eth0 connection. I used only wifi connection on the device (raspberry). So uncheck auto connection in NetworkManager applet.

**Comment by codeseedr** [comment]
Had a very similar problem as Arch Linux user, perhaps my report helps someone. 

I configured `eth0` to have a static IP address through `netctl`/`netctl-ifplugd`. In my case `eth0` was in the state of "configuring" as reported by `networkctl`. Ultimately I found that `/etc/systemd/network/eth0.network` had:
```
[Network]
DHCP=yes
```
Changed it to `no` and the issue went away.

**Comment by tconrado** [comment]
we had a consistent timeout event, setting optional: true in netplan solved it!

**Comment by zwets** [comment]
This issue resurfaced after I upgraded my servers from Ubuntu 20.04 to 20.10. Not sure what caused it, but the fix was simple: adding `link-local: [ ]` to every interface in the `netplan` configuration solves the issue. (See [here](https://askubuntu.com/a/1289039/134479).)

This fix/workaround points to the likely root cause: this happens on servers with a disabled IPv6 stack (kernel parameter `ipv6.disable_ipv6=1`). The netplan default for `link-local` is `[ ipv6 ]`, meaning it should only bring up IPv6 link-local addresses (see `netplan(5)`). It seems that `s-n-w-o` takes this to mean that they _will_ be brought up, whereas this won't happen due to the IPv6 stack being disabled.

**Comment by ZeclintrYzath** [comment]
I am using the enp0s0 network interface bridge mode in conjunction with the br0 bridge.
But br0 was not configured and wrote an error:

    systemd-networkd-wait-online [1132]: Event loop failed: Connection timed out
    systemd-networkd-wait-online.service: Main process exited, code = exited, status = 1 / FAILURE
    systemd-networkd-wait-online.service: Failed with result 'exit-code'.
    Failed to start Wait for Network to be Configured.
    systemd-networkd-wait-online.service has failed


First, to make it easier to start `systemd-networkd-wait-online`(since this service expects a network setup with a working link state equal to or higher than "degraded") I disabled some minor
interfaces like loopback, VRF using the `ConfigureWithoutCarrier` option, and left only br and tap. But it still didn't help me.
I figured it was caused by missing some options in the [Network] section as a fact of regression.
But i tried to edit / i advise "**Edit this file properly**" enp0s0.network network adapter to synchronously enable the enslaved br0 which brings up the whole oneshot service and reboots systemd-networkd:


    $ sudo nano /etc/systemd/network/enp0s0.network

      [Match]
      Name = enp0s0

      [Network]
      Bridge = br0
      DHCP = ipv4
      LinkLocalAddressing = ipv4
      IPForward = yes
      DHCPServer = yes
      IPMasquerade = no
      ConfigureWithoutCarrier = yes

      [Link]
      RequiredForOnline = yes

    $ journalctl -b -u systemd-networkd-wait-online

    systemd [1]: Starting Wait for Network to be Configured ...
    systemd-networkd-wait-online [1104]: managing: br0
    systemd-networkd-wait-online [1104]: managing: enp0s0
    systemd-networkd-wait-online [1104]: ignoring: lo
    systemd [1]: Started Wait for Network to be Configured.

The error disappears, but only if you use enp0s0 (as DHCPServer) with br0 !!!

**Comment by szycha76** [comment]
What a wonderful display of human creativity in an heroic effort to solve the problem of the automated universal system designed to make our lives easier, which seems to have created the problem in the first place.

Reminds me heroic efforts of communist system I had a doubtful pleasure to watch in my youth.  They were constantly trying to solve problems the communist system was creating each and every day.

Now should you ever tried Slackware, and if the distribution provided solutions didn't meet your needs, all you have to do is to write your own 4-8-lines long script to set up your interfaces, and forget.

Yes, I know - doesn't scale well. Or does it? But you'd have a chance to become a networking expert in the process, not the expert of the ever-changing-but-still-buggy systemd tool.

Have fun (anyway)! :-)

**Comment by aTanW** [comment]
@szycha76 ,
1. Communist system all its life fight against external pressure far more, than with internally born problems.
2. But what if you already networking expert? :-) Right, you'll go to find tool like systemd.
3. Not a systemd is a ever-changing-but-still-buggy tool, but all the way the world evolutes computer software.

Anyway, have the fun! ;-)
