### ISSUE TITLE
documentation how to register scopes via the bus is lacking, for example to permit docker to register its containers as scope units for per-container journal ratelimiting

### ISSUE THREAD

**Issue by bobrik** [systemd/systemd#6487]
### Submission type

 - [ ] Bug report
 - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> any

### Used distribution

> any

### Enhancement description

Here's a great blog post that sums up the issue many were seeing with docker and journald:

* https://segment.com/blog/bob-loblaws-log-blog/

There are three issues:

1. Rate limiting is applied per systemd unit, this doesn't work well with containers.
2. Rate limiting decisions are not visible in `journalctl` output for rate limited units, only for `systemd-journald` unit.
3. Performance of `journald` is not where it could be, it's way too easy to saturate it.

I'm not sure what to do with the latter, so this issue is about the first two.

To address the first issue, I propose to configure rate limiting bucket for units. By default the bucket name should be equal to the unit name:

```
RateLimitBucket=${_SYSTEMD_UNIT}
```

For the Docker scenario we want to apply limits by per container, so we can put the following in the `docker.service`:

```
RateLimitBucket=${_SYSTEMD_UNIT}:${CONTAINER_ID}
```

This doesn't allow us to configure limits per bucket, but it does allow us to avoid limiting all containers because of one rogue container.

To address the second issue, I propose to copy rate limiting messages to the unit logs the same way we copy start / stop actions:

```
Jul 30 21:52:20 myhost systemd[1]: Stopping myservice...
Jul 30 21:52:20 myhost systemd[1]: Stopped myservice.
Jul 30 21:52:20 myhost systemd[1]: Started myservice
```

For rate limiting it could look like:

```
Jul 30 21:52:26 myhost systemd[1]: Suppressed 84659 messages from docker:b4ed391322a6
```

This solves the issue for regular services, but doesn't solve the issue for docker containers, because rate limiting issue is not tied to a specific container. You won't see it when you do:

```
journalctl -f CONTAINER_TAG=my-docker-container-tag
```

It'd be nice to address this too, but at least we can automate this part easily it when we ship journald logs elsewhere.

cc @dfuentes @alberts @dqminh

**Comment by poettering** [comment]
well, in order to properly do more fine-grained rate-limiting we'd need a safe way how docker would let journald know about its containers. From journald's and systemd's PoV docker is a larger, single service without further distinction below it. The recommended way to let systemd and journald about "subdivisions" of such a large super-daemon would be to register a "scope" unit for each. That not only exposes that "subdivision" (which in the docker case would be a "container") as a systemd concept for introspection and such, but has an effect on the logs as well: as soon as a set of daemons run as their own scope unit, journald will do specific rate-limit for it. 

Unfortunately there isn't much documentation for creating scope units, but it is basically one bus call it would have to issue for each individual container: StartTransientUnit(). (which is what systemd-run --scope does, if you need an example). 

For system containers there's also the option to register them with "systemd-machined", which internally also does StartTransientUnit() for you, but does a couple of more things as well.

Anyway, I'll leave this bug open, as we really should document better what super "super-daemons" should do, to get their "subdivisions" exposed properly in systemd and journald, but technically everything is already in place to make all this happen -- it's just that if docker doesn't let us know anything more fine-grained we cannot act anymore fine-grained.

**Comment by poettering** [comment]
There's nowdays https://systemd.io/CGROUP_DELEGATION.html which explains this in detail. Mostly with the focus on cgroups, but given that the per-service logging is based on the cgroup membership this implicitly answers that too. Let's close hence.
