### ISSUE TITLE
journalctl --list-boots not accurate

### ISSUE THREAD

**Issue by archuserr** [systemd/systemd#6488]
### Submission type

 - Bug report

This might be related to issue #6447.

### systemd version the issue has been seen with

systemd 234
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

Arch

### In case of bug report: Expected behaviour you didn't see

`journalctl --list-boots` lists the current and previous boot times.

### In case of bug report: Unexpected behaviour you saw

I wrote an Arch image to disk today (2017-07-30). I booted once (approx 16:20), and then rebooted (17:55). Here's what journalctl gives me:

```
~$ journalctl --list-boots
 0 844b2b73957a46238ffa59ea4bd7b255 Wed 2017-07-26 14:05:15 PDT—Sun 2017-07-30 17:58:26 PDT
~$ uptime
 18:05:28 up 10 min,  1 user,  load average: 0.00, 0.00, 0.00
~$ date
Sun Jul 30 18:05:47 PDT 2017
```

`--list-boots` kind of got the first boot. I don't know where 2017-07-26 came from. The Arch image? And the shutdown time (17:58:26) can't be right if the current time is 18:05:28 and uptime is 10min.

The second boot is missing.

I don't know if the following is related to the above:

On the second boot, I found these in `dmesg`:

```
[   11.173003] systemd-journald[210]: Received request to flush runtime journal from PID 1
[   11.207562] systemd-journald[210]: File /var/log/journal/02a779f1e8814f5191229b29da0e07e9/system.journal corrupted or uncleanly shut down, renaming and replacing.
```

```
~$ journalctl --file /var/log/journal/02a779f1e8814f5191229b29da0e07e9/system.journal --verify
PASS: /var/log/journal/02a779f1e8814f5191229b29da0e07e9/system.journal
```

Looking at the journal, it looks like the first boot shutdown correctly. Here are the last lines of the journal:

```
Jul 30 16:21:35 test7 systemd[1]: Reached target Final Step.
Jul 30 16:21:35 test7 systemd[1]: Starting Reboot...
Jul 30 16:21:35 test7 systemd[1]: Shutting down.
```

But on another computer, I also have these lines: 

```
Jul 27 02:20:18 server systemd-shutdown[1]: Sending SIGTERM to remaining processes...
Jul 27 02:20:18 server systemd-journald[177]: Journal stopped
```

### In case of bug report: Steps to reproduce the problem

I've only seen this once. I don't know if it's reproducible.

**Comment by poettering** [comment]
"journalctl" simply shows the date of the newest and the oldest log entry associated with a specific boot ID for each line. Please use `journalctl -o verbose _BOOT_ID=… -n 5` and `journalctl -o verbose _BOOT_ID=… -n 5 --reverse` to have a detailed look at the five oldest and newest log messages associated with a specific boot ID.

Note that linear iteration through corrupted journal files might result in more entries than searching through them by some field (the way --list-boots does it), simply because the corruptions might affect the search data structures. (or to say this differently: if the system was shutdown with unwritten buffers, and those unwritten buffers affect the log data itself you cannot view it, neither iterating linearly nor searching for it. But if the searching data structures are affected and the log data itself was written we can still show it to you if you don't use the searching.

Not sure why your journal file was corrupted though. This should only happen if the system is turned off forcibly, or if journald takes too much time to sync it to disk on shut down, so that it gets cleaned up in the last boot phase forcibly. But that's nasty to debug since the instant journald is gone logging becomes hard, because logging is not available anymore.

Please have a look at these docs:

https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1

Specifically the debug script shutdown drop-in mentioned there. Consider adding that, and in case you manage to reproduce it, please have a look at the log data this generated at the previous iteration.
