### ISSUE TITLE
service_enter_dead() should not honour Restart= if there was a stop job queued when it started

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6504]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd-233-6.fc26.x86_64

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

a password prompt (then a shell prompt).

system should also respond to ctrl+alt+del, but it doesn't.

I just see boot messages and "Welcome to Fedora" on a text console.  I can use shift+page up to scroll up; there's nothing hidden in the previous screen-full of text either.

Some further investigation seems to be needed.

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

* install Fedora 26
* enter GRUB boot menu, hit `e` to edit
* edit line starting `linux16` to add `systemd.unit=emergency.target`
* boot (ctrl+x, or F10 on efi system)

rescue.target works as expected.

**Comment by sourcejedi** [comment]
Booting without an initrd works though.  (On a VM, I had to change the disk to the SATA bus.  The virtio drivers don't seem to be built in to the Fedora kernel.  I edited the command line to use `root=sda3`).

The failed boot ends like this

```
[  OK  ] Started Cleaning Up and Shutting Down Daemons.
[  OK  ] Stopped udev Kernel Device Manager.
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Stopped Create list of required sta…vice nodes for the current kernel.
[  OK  ] Stopped dracut pre-udev hook.
[  OK  ] Stopped dracut cmdline hook.
[  OK  ] Closed udev Kernel Socket.
[  OK  ] Closed udev Control Socket.
         Starting Cleanup udevd DB...
[  OK  ] Started Cleanup udevd DB.
[  OK  ] Started Plymouth switch root service.
[  OK  ] Started Setup Virtual Console.
[  OK  ] Reached target Switch Root.
         Starting Switch Root...
...

Welcome to Fedora 26 (Workstation Edition)!

[  OK  ] Stopped Journal Service.
[  OK  ] Stopped Switch Root.
```

Debug log (serial console) from the start (truncated some time after "Stopped Switch Root" due to apparent infinite loop in output):  https://gist.github.com/sourcejedi/282fc203c9e863092addeff80ad1a144#file-systemd-issue-6504-debuglog

**Comment by sourcejedi** [comment]
Booting with `audit=0 systemd.unit=emergency.target` succeeds.

**Comment by poettering** [comment]
Hmm, so reading your logs this is what happens: we transition from the initrd to the host, and for that first send SIGTERM to all processes not marked specifically to survive the transition. the transitioned systemd on the host side sees journald exiting as one of the first things happening. Because journald has Restart= set in the unit file it actually immediately ends up starting journald again. Which is normally not a problem, since journald is supposed to start during boot, but in this case is not intended, as you start emergency mode. At the same time as journald is scheduled for restart we put together the new transaction to enter emergency mode, and it expressely means stopping journald. So, now we have a restart job waiting to happen and a stop job enqueued. Because a restart is the combination of a stop and a start, the stop job can be fulfilled by the restart, and that's where things go bad: we just fulfilled a stop request with a restart request... And at that point we enter a state we can never exit from: we want to go on and stop the audit socket journald listens on, but can't do that before journald is gone, except that it isn't gone, because we just restarted it, and the stop job is already fulfilled...

I figure we can fix this relatively easily: ensure that Restart= will never be acted upon if ther are stop jobs pending for a unit.

**Comment by poettering** [comment]
> I figure we can fix this relatively easily: ensure that Restart= will never be acted upon if there are stop jobs pending for a unit.

Or actually, we already do that. But what we need to ensure is that Restart= will never be acted upon if there was a stop job pending at the moment we entered the dead state of the unit. i.e. at the top of service_enter_dead() we need to remember whether a stop job is pending, before we invoke service_set_state() for the first time. And if we do, we need to skip queing of timer and entering of SERVICE_AUTO_RESTART

**Comment by arvidjaar** [comment]
> we transition from the initrd to the host, and for that first send SIGTERM to all processes not marked specifically to survive the transition. the transitioned systemd on the host side sees journald exiting as one of the first things happening.

That sounds like just another reincarnation of https://github.com/systemd/systemd/issues/3436

**Comment by poettering** [comment]
Could you give #6581 a whirl and check if it fixes your issue?

**Comment by sourcejedi** [comment]
Yep, that gets me to the root password prompt!

(All my logins are failing to run a shell with `Permission Denied`, but that's clearly not related. It's something about how I installed systemd from source. This is why I snapshotted the VM first :-).
