### ISSUE TITLE
"systemctl show" prints values that areformatted in a way not understood as unit file settings

### ISSUE THREAD

**Issue by ikrabbe** [systemd/systemd#6511]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

Centos 7

### In case of bug report: Expected behaviour you didn't see

I use `systemctl show nginx.service` for example to read out default values. When I put these default values into a service file then systemd fails to start the service because it cannot read the values that it prints.

**Comment by ikrabbe** [comment]
Example value:
LimitCPU=18446744073709551615

**Comment by yuwata** [comment]
Related to #4295.

**Comment by poettering** [comment]
> I use systemctl show nginx.service for example to read out default values. When I put these default values into a service file then systemd fails to start the service because it cannot read the values that it prints.

While the properties shown by "systemctl show" are close to the stanzas used in unit files they are considerably more low-level and are not the same. For example, all time settings on the unit file level are called "XyzSec", while the properties are exposed as "XyzUSec", since internally we calculate with much more fine-grained time by default. Moreover setting such as ExecStart= are exposed structured, and carry both configuration and runtime data, and hence cannot be translated 1:1 to unit file settings anyway.

Yupp, it's a bit ugly this way, but we can't really change this at this point anymore I fear...

That all said, we shouldn't dump -1 as 18446744073709551615. Even if we aren't 1:1 mappable, we should try to keep the differences mininmal

**Comment by keszybz** [comment]
I think we're pretty good now, apart from a few problematic entries:
```console
$ systemctl show systemd-journald
...
UID=4294967295
GID=4294967295
...
AmbientCapabilities=(null)
...
```

If you see any more properties that are incorrectly or misleadingly formatted, please report specific examples.
