### ISSUE TITLE
fstab-generator does not read /etc/fstab in containers

### ISSUE THREAD

**Issue by volth** [systemd/systemd#6569]
There have been two commits (4 and 3 years ago): https://github.com/systemd/systemd/commit/689aede8c622ba68d9060e4edee27364445b2007 and https://github.com/systemd/systemd/commit/00b4ffdecbb39d849af65c0ab741be482325a4a9 which prohibit read ```/etc/fstab``` in the container environment:

The point was:
```
fstab-generator: when running in a container, ignore fstab entries 
referring to device nodes

Since these device nodes will never appear in the container anyway
there's no point in waiting for them.

This makes it easier to boot images generated with general purpose
installers like Anaconda which unconditionally populate /etc/fstab to
boot in containers.
```

It is basically not true at least for ```libvirt_lxc``` containers which can have device nodes, so you can use a physical hard disk or a partition only in a container.

With

```xml
    <disk type="block" device="disk">
      <driver name="qemu" type="raw" cache="none" io="native"/>
      <source dev="/dev/sdi"/>
      <target dev="vdb"/>
    </disk>
```
there will be ```/dev/vdb``` inside container, but it has to be mount manually because ```fstab-generator``` does not pick the corresponding entry from ```/etc/fstab```

<hr/>

```<hostdev>``` also allows to have block devices inside ```libvirt_lxc``` containers:
```xml
    <hostdev mode='capabilities' type='storage'>
      <source>
        <block>/dev/sdf1</block>
      </source>
    </hostdev>
```

**Comment by poettering** [comment]
Well, /sys is not virtualized on Linux, hence while raw block devices might get mounted to /dev, you cannot properly enumerate them, in particular if they are called /dev/vdb and thus don't even match the data from /sys anymore in name.

When systemd mounts a file system it tracks udev/sysfs and waits for the device to be announced by the kernel before doing anything. None of that work inside of a container, and devices will never appear properly announced in it, the ".device" units required by the ".mount" units will never become active, and hence the ".mount" units will never be activatable either.

I am all for supporting this, but it's not as simple as this. We need to wait for the kernel to properly virtualize device management, so that /sys and udev can refelect precisely what is around and what isn't inside the container, and at that point we can turn this on in systemd too. But before the kernel caught up and did its homework on this we can't support that either. Sorry!

**Comment by volth** [comment]
So the only option to work around it is to execute ```mount -a``` sometime later (e.g. in a dummy oneshot service)?

**Comment by poettering** [comment]
yeah, I figure that could be a work-around for now

**Comment by agherzan** [comment]
@poettering Would it make sense to assume active plugged on devices units when in a container? The problem that I currenly have is that I can't use in any way mount services in container even if the devices are all fine. So testing an OS container with mount services needs a lot of changes because of this limitation.

**Comment by boucman** [comment]
so it's impossible to "reserve" a partition for a container image, or decrypt then mount a block device in a container ?
