### ISSUE TITLE
/var/tmp pollution

### ISSUE THREAD

**Issue by zabbal** [systemd/systemd#66]
There a plenty of systemd-private-632623626-smth folders in /var/tmp. Is there a way to move all that into /var/tmp/systemd/... if so than it's probably a documentation bug (hard to find) otherwise consider it a feature request.

**Comment by mbiebl** [comment]
What would be better by moving them into a subdirectory? Is this only a cosmetic/astethic issue?

**Comment by zabbal** [comment]
Pretty much the same reasons as for ~/.config/ in XDG spec: aesthetics and saner backup. Note there's no such issue with /tmp cause it's content is discarded on reboot anyway.

**Comment by mbiebl** [comment]
Aside from the fact that I don't understand why you would want to backup /var/tmp in the first place, why is it harder to exclude /var/tmp/systemd-private-\* then /var/tmp/systemd/\* ?

**Comment by zabbal** [comment]
Not all the tools support proper globing but you're right - that's more of an aesthetics issue.

**Comment by xnox** [comment]
I was never sure why those things are placed in /var/tmp instead of like somewhere in /run. Are these meant to persist across reboots? I thought each time a thing like that is started it will get a newly unique private tmp, and thus there is not need for these things to persist across reboots, and hence they have no place on /var/tmp.

**Comment by keszybz** [comment]
On Thu, Jun 04, 2015 at 05:42:28AM -0700, Dimitri John Ledkov wrote:

> I was never sure why those things are placed in /var/tmp instead of like somewhere in /run. Are these meant to persist across reboots? I thought each time a thing like that is started it will get a newly unique private tmp, and thus there is not need for these things to persist across reboots, and hence they have no place on /var/tmp.

/run is memory-backed, /var/tmp is not.
We need both /tmp/systemd-private-\* and /var/tmp/systemd-private-\* for
the same reason that we have /tmp and /var/tmp.

There's two problems with switching to a scheme with /tmp/systemd/private-xxx
and /var/tmp/systemd/private-xxx:
1. upgrades: we support live upgrades, so by suddenly starting to
   require /var/tmp/systemd and /tmp/systemd to be under our control
   opens up an dos opportunity during upgrade.
2. booting: how do you ensure that we get a chance to create
   /tmp/systemd and /var/tmp/systemd before anything else which might
   create it is started? For /tmp it's trivial, but /var/tmp might
   be mounted relatively late. We'd have to make sure to pre-create
   /var/tmp/systemd at the right moment. This adds another synchronization
   point to the boot sequence.

It just doesn't seem to be worth the trouble.

**Comment by poettering** [comment]
Using a guessable name under /tmp and /var/tmp opens a DoS vulnerability, hence we should avoid that, as @keszybz already indicated above. Now, we could work around that, by pre-creating the dirs using tmpfiles, which is what we do to reserve the dirs X11 needs in /tmp. However, this is a hack around a broken way to use /tmp, nothing more, and we really should not introduce new cases where things are used in a broken way.

Hence, closing.

**Comment by zabbal** [comment]
How about prepending . to those semi-random names? That's the usual way to hide stuff which is meant for internal use only. All those folders are inaccessible to user anyway so there's little use to have them visible in file manager by default.

**Comment by poettering** [comment]
Humm? /tmp is for temporary files. It is not shown in the UI normally. There's no point in hiding files in it, since the entire directory should be considered hidden anyway.

**Comment by zabbal** [comment]
/tmp is also for stuff which is 'opened' instead of 'saved' by browser/mail client etc. but I've been talking about /var/tmp which survive between reboots and might be often use to store some temporary content by user.

**Comment by poettering** [comment]
but if the browser "opened" such a link, how does it matter then whether the files are visible in /tmp?

/tmp is a system-wide directory. users browsing for files there would be really confused anyway, since they'll see other user's files too, and most file browsers wouldn't show that either...

Really /tmp is not a directory a normal user should _ever_ browse through. Sorry.

**Comment by donbright** [comment]
By using UTF8 filenames the same level of entropy could be achieved without cluttering the UI of command line terminal users. 

> systemd-private-312c82c4ea3942ef9f516f69106b2a47-systemd-timesyncd.service-h9Z5Yu

vs

> systemd夫兵者不祥之器物或惡之故有道者不處

**Comment by keszybz** [comment]
The name of the directory contains useful hints: "systemd", "private", and the name of the service "systemd-timesyncd.service". If the administrator wants to look at the private /tmp of some service, they can use those hints to find the right directory. Replacing that with random unicode would increase entropy but decrease readability.

There's also a good reason to use a limited charset: you might want to read this on a tty or a serial console without good fonts. Sticking to plain ASCII is a must.

**Comment by jidanni** [comment]
Couldn't these be put into their own directory tree instead of
cluttering up /tmp?

$ ls -ld /tmp/systemd*
drwx------ 3 root root 60 06-25 21:40 /tmp/systemd-private-432bdf52490840dc91ecc3aa7a4a4ef5-systemd-logind.service-PiLxfA
drwx------ 3 root root 60 06-25 21:40 /tmp/systemd-private-432bdf52490840dc91ecc3aa7a4a4ef5-systemd-resolved.service-Fs7xZj
drwx------ 3 root root 60 06-25 21:54 /tmp/systemd-private-432bdf52490840dc91ecc3aa7a4a4ef5-systemd-timesyncd.service-fJJlTm

How about
/tmp/systemd/private-432bdf52490840dc91ecc3aa7a4a4ef5-systemd-logind.service-PiLxfA
/tmp/systemd/private-432bdf52490840dc91ecc3aa7a4a4ef5-systemd-resolved.service-Fs7xZj
/tmp/systemd/private-432bdf52490840dc91ecc3aa7a4a4ef5-systemd-timesyncd.service-fJJlTm

or even
/tmp/systemd/private/432bdf52490840dc91ecc3aa7a4a4ef5/systemd-logind.service-PiLxfA
/tmp/systemd/private/432bdf52490840dc91ecc3aa7a4a4ef5/systemd-resolved.service-Fs7xZj
/tmp/systemd/private/432bdf52490840dc91ecc3aa7a4a4ef5/systemd-timesyncd.service-fJJlTm
etc. instead?

OK after reading all the other comments maybe for this boot have the dir
be /tmp/systemd.6HxiQ/* thus defeating all the forces of evil, but still
keeping /tmp tidy just like we would expect of other programs.

**Comment by keszybz** [comment]
> Really /tmp is not a directory a normal user should ever browse through. Sorry.

**Comment by jidanni** [comment]
Well you are also revealing details of what's going on shared systems
systemd-private-de5337649a1640c3a0cbf4662311530b-apache2@apache2-adamant.service-JXN01j
systemd-private-de5337649a1640c3a0cbf4662311530b-apache2@apache2-argon.service-oqvBbZ
systemd-private-de5337649a1640c3a0cbf4662311530b-apache2@apache2-blow.service-Q99IU2
more than users can find out with ps(1) etc.

**Comment by jidanni** [comment]
Also the more programs that treat /tmp as a flat dir. instead of a tree,
the larger ls -dl /tmp becomes in size, to the detriment (increasing the
search size) of all programs.
