### ISSUE TITLE
service: cgroup_empty handler races sigchld handler on the unified cgroup hierarchy

### ISSUE THREAD

**Issue by joukewitteveen** [systemd/systemd#6608]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> `SIGCHLD` is dealt with before cgroup_empty.

### In case of bug report: Unexpected behaviour you saw

> On the unified hierarchy, we [rely](https://github.com/systemd/systemd/blob/v234/src/core/service.c#L3112) on notifications for the cgroup_empty event. As a consequence, `service_notify_cgroup_empty_event` may be called before `service_sigchld_event`. I have no example of when exactly this leads to trouble, but the implemented logic seems to assume `SIGCHLD` is dealt with before cgroup_empty. It could be that the late handling of `SIGCHLD` puts the service in a success state after the cgroup_empty handler has put the the unit into a failed state.

### In case of bug report: Steps to reproduce the problem

> The reversed order was observed with

```
[Unit]
Description=forking: sigchld versus cgroup empty

[Service]
Type=forking
ExecStart=/usr/bin/sleep 3
```

```
systemd[1]: forking.service: cgroup is empty
systemd[1]: Received SIGCHLD from PID 19529 (sleep).
```

**Comment by poettering** [comment]
SIGCHLD handling is processed at SD_EVENT_PRIORITY_NORMAL-7.

cgroup agent events (i.e. legacy cgroup events) at SD_EVENT_PRIORITY_NORMAL-5.

cgroup inotify events (i.e. unified cgroup events) at SD_EVENT_PRIORITY_NORMAL.

Now, I think we should change the latter to also be at SD_EVENT_PRIORITY_NORMAL-5 to make behaviour in the unified and non-unified cases more alike, but at the moment SIGCHLD is processed earlier than either (smaller priorities mean earlier processing), so we should be mostly fine -- assuming that the kernel passed SIGCHLD at least as early as the inotify event to us.

But yeah, I can't explain the order of the two log lines either I must say, except if the kernel doesn't actually give us the guarantee that SIGCHLD is visible to userspace before the inotify. @htejun, can you comment?

**Comment by poettering** [comment]
After discussing this with @htejun it appears we need to fix systemd here, as cgroup empty notifications are quite different in the unified hierarchy than in the legacy hierarchy. In the old one, we knew exactly, when we got one, the cgroup was empty, and as long as we dispatched that event after SIGCHLD all was good. But this now different: we just get a generic inotify event, and then asynchronously figure out what might have changed. And right now, this means we might already see stuff when checking this that happened after the SIGCHLD before, and thus we act on it before the SIGCHLD... This means we need to fix systemd like this: whenever we get an inotify event on some cgroup, check if the cgroup is now empty, and if so, enqueue a new event, with a lower prio than the SIGCHLD, so that we can be sure that any SIGCHLD is again processed before we process the inotify.

**Comment by poettering** [comment]
Fix waiting in #6928

**Comment by fbuihuu** [comment]
> But this now different: we just get a generic inotify event, and then asynchronously figure out what might have changed. And right now, this means we might already see stuff when checking this that happened after the SIGCHLD before, and thus we act on it before the SIGCHLD...

@poettering , I'm not sure to understand this... could you clarify ? Thanks.

**Comment by poettering** [comment]
> > But this now different: we just get a generic inotify event, and then asynchronously figure out what might have changed. And right now, this means we might already see stuff when checking this that happened after the SIGCHLD before, and thus we act on it before the SIGCHLD...
> 
> @poettering , I'm not sure to understand this... could you clarify ? Thanks.

in cgroupsv2 there's the `cgroup.events` file. That file is a bit magic: if you create an inotify watch on it, you'll be notified every time something interesting happens about the cgroup, most importantly when the "populated" state of the cgroup changes from "empty" to "populated" or back. Now, systemd adds all cgroups it cares about to such an inotify watch, and each time we get an event we now have to figure out what actually is going on. Since the inotify even doesn't tell us anything about what precisely changed we then open `cgroup.events` and read the `populated` attribute it contains. Now, this logic is asynchronous: between the inotify event and us checking the attribute pretty much anything else can happen. Moreover, inotify events are coalesced: if we don't take notice quickly enough of the inotify event, multiple changes might be merged into one wakeup event. Thus, it might happen that we are woken up because a cgroup got populated: but at the time we check that the cgroup might already have been emptied again, so that we never see the first event. This is normally not a big problem, because we actually only really care about the "empty" event, not the "populated" event for systemd. However, it creates problems with the ordering of event dispatching. Specifically: consider a regular service terminates. its main process will exit, and its cgroup runs empty. For that we'll get an inotify event as well as a SIGCHLD containing the main process' exit status. The latter is a lot more interesting than the former, since the latter tells us whether the process finished successfully or with an error, which is information we might to decide what to do next. Hence, we always want to see the SIGCHLD first, and the cgroup empty second, because then we can change state safely early on, using the full information we might get. 

Why do we care about the cgroup empty event at all? Some units don't have a known main process, or not a main process which is child of PID 1, and thus we won't get any SIGCHLD from, and hence we rely on the cgroup empty event for them. What#s worse in many cases we don't even know in advance whether we'll get a SIGCHLD or not for the service. 

Now, given that we want both events, but find SIGCHLD a lot more interesting, we need to make sure we process it first. But as we have seen above it might happen that we get an inotify wen a cgroup was first populated but by the time we check that it is already empty. In that case we really should not start acting on it, but first check if there are possibly any SIGCHLD pending, before we come to the conclusion that there's nothing and we should act on the cgroup empty event. Thus, with the new PR I prepped after noticing the cgroup being empty we'll enqueue a "defer" event, with a lower event loop priority than the sigchld handler. That ensures we only process cgroup empty after any queued sigchld, and solves the problem.

And do note that this race happens IRL. In fact it's very like to be triggered by a service that wraps a short-lived process that exits instantly: in that case systemd will get inotify for "cgroup populated" very quickly, and if it the goes and checks what is going on it might already find that the cgroup is empty, and then should not act on it immediately, but first look for SIGCHLD.

**Comment by fbuihuu** [comment]
Thanks for your detailed explanation !

Are there any guaranties that the kernel will always deliver the SIGCHLD event before the inotify one when a main process dies and the corresponding cgroup becomes empty ?

**Comment by poettering** [comment]
that's a valid question, but afaiu as long as we check explicitly with waitid() and the cgroup check before doing aynthing we should be fine, and that in fact is what we do.

**Comment by fbuihuu** [comment]
> -- assuming that the kernel passed SIGCHLD at least as early as the inotify event to us.

This is where actually I'm not confident.

I'm not really sure but it seems that someone has been hit by this issue even with the legacy hierarchy, see : https://bugzilla.opensuse.org/show_bug.cgi?id=1062188

It happens on Leap 42.3 (v228).

From the coredump attached to the BZ report I can see:

```
 #7  0x0000557efe28832b in manager_dispatch_sigchld (m=m@entry=0x557eff900040) at src/core/manager.c:1822
 1815        /* And now figure out the unit this belongs
 1816         * to, it might be multiple... */
 1817        u1 = manager_get_unit_by_pid_cgroup(m, si.si_pid);
 1818        if (u1)
 1819                invoke_sigchld_event(m, u1, &si);
 1820        u2 = hashmap_get(m->watch_pids1, PID_TO_PTR(si.si_pid));
 1821        if (u2 && u2 != u1)
 1822 =>            invoke_sigchld_event(m, u2, &si);
 
 (gdb) p si
 $21 = {si_signo = 17, si_errno = 0, si_code = 1, _sifields = {_pad = {31604, 0 <repeats 27 times>},
     _kill = {si_pid = 31604, si_uid = 0}, _timer = {si_tid = 31604, si_overrun = 0, si_sigval = {
        sival_int = 0, sival_ptr = 0x0}}, _rt = {si_pid = 31604, si_uid = 0, si_sigval = {sival_int = 0,
        sival_ptr = 0x0}}, _sigchld = {si_pid = 31604, si_uid = 0, si_status = 0, si_utime = 0,
     si_stime = 0}, _sigfault = {si_addr = 0x7b74, si_addr_lsb = 0, si_addr_bnd = {_lower = 0x0,
         _upper = 0x0}}, _sigpoll = {si_band = 31604, si_fd = 0}, _sigsys = {_call_addr = 0x7b74,
     _syscall = 0, _arch = 0}}}
 (gdb) p u1
 $18 = (Unit *) 0x0
```

So `manager_get_unit_by_pid_cgroup()` didn't found the relevant unit and since the unit has service type (see below) that probably means that the empty event has been processed **before**.

```
 (gdb) down
 #6  0x0000557efe2a5fa4 in service_sigchld_event (u=0x557eff91b790, pid=<optimized out>, code=1, status=0)
    at src/core/service.c:2701
 2699
 2700             default:
 2701 =>                  assert_not_reached("Uh, main process died at wrong time.");
 2702            }
 
 (gdb) p *((Service *)u)
 $24 = {meta = {manager = 0x557eff900040, type = UNIT_SERVICE, load_state = UNIT_LOADED,
     merged_into = 0x0, id = 0x557eff988940 "syslog-ng.service", instance = 0x0, names = 0x557eff92dda0,
     dependencies = {0x557eff95ea80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x557eff9a3e80, 0x0, 0x0,
     0x557eff9aadb0, 0x0, 0x557eff9a3340, 0x557eff9a8cb0, 0x0, 0x0, 0x557eff962920, 0x0, 0x0, 0x0,
     0x557eff9acfd0, 0x557eff9a5590}, requires_mounts_for = 0x0,
     description = 0x557eff988960 "System Logging Service", documentation = 0x0,
     fragment_path = 0x557eff9544f0 "/usr/lib/systemd/system/syslog-ng.service", source_path = 0x0,
     ...
     state = SERVICE_DEAD, ...
```
Here the unit has `SERVICE_DEAD` state which seems to confirm that the empty cgroup event has been completely processed.

Can you see another path which could have put the service in the `SERVICE_DEAD` state ?
