### ISSUE TITLE
RFE: stricter checks on the PID read from PIDFile= or sd_notify()'s MAINPID=

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#6632]
### Submission type

 [x] Bug report

### systemd version the issue has been seen with

 systemd 229                                                                                                                                 
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

### Used distribution

Ubuntu 16.04

### Report 
Hello,
Due to the last CVE for nagios-nrpe-server[1], I wanted to make sure that my systems with systemd are safe. I thought that this CVE[1] would only apply to old init systems that rely strongly on PIDfiles. So I've started my Ubuntu 16.04 Container with systemd 229 and verified that CVE[1] with systemd. And indeed it seem to stop the systemd service:

```
Aug 17 14:27:35 motoko systemd[1]: Stopping LSB: Start/Stop the Nagios remote plugin execution daemon...
Aug 17 14:27:35 motoko nagios-nrpe-server[4969]:  * Stopping nagios-nrpe nagios-nrpe
Aug 17 14:27:35 motoko systemd[1]: Received SIGTERM from PID 4972 (start-stop-daem).
Aug 17 14:27:35 motoko systemd[1]: Reexecuting.
Aug 17 14:27:35 motoko systemd[1]: systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUT
LS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN)
Aug 17 14:27:35 motoko systemd[1]: Detected virtualization systemd-nspawn.
Aug 17 14:27:35 motoko systemd[1]: Detected architecture x86-64.
```

We had a discussion about this in the `#systemd`-Channel in Freenode. So I've tried that in my Arch Linux Container with `systemd-234` as well and I didn't had this in my Logs.

*but* one of the guys in the channel said that this still exists due to not existing checks for `sd_notify("MAINPID=...)` and he has accomplished something like this:

```
    CGroup: /system.slice/test.service            
            └─367351 python /home/grawity/test.py 
            ‣ 367337 /usr/bin/htop                
```

So I guess that this is still a thing and should be fixed. 

[1] http://www.openwall.com/lists/oss-security/2017/08/16/7

**Comment by poettering** [comment]
Well, what precisely would you expect us to check there? Checking the user ID of the new process isn't really doable, as we permit daemons to change uids freely. Checking the cgroup doesn't work either, as we support damons whose main process lives outside of the original cgroup they created (that's the default in gettys after all). Note that sd_notify() is restricted already via NotifyAccess=, and it defaults to not available, unless explicitly enabled (either via NotifyAccess= set to something else than "no", or via Type=notify), hence this is already well protected I figure. 

That said, I am open to more strict checks here, but I am not sure what they would look like, do you have any suggestions? @grawity maybe you?

**Comment by grawity** [comment]
I'm not sure really. But, how many daemons live outside the original cgroup _and_ try to change their mainpid? (As far as I can see, agetty definitely always lives in …/system-getty.slice/getty@.service – only its child /sbin/login process is moved out, and that happens via privileged PAM, not via sd_notify().)

**Comment by poettering** [comment]
wel, it's not just about how many there are, it's more about "do we think that daemon should be able to do that even if they currently don't do that..."

What about this: we change the logic so that one of the following two rules must hold:

a) the sender UID of MAINPID= matches the UID of the PID specified therein
b) the sender UID is either root or whatever is configured in User=

I think with that we should cover most cases safely. 

Does that make sense?

**Comment by shibumi** [comment]
@poettering that sounds much better as the status quo! 👍

**Comment by dhke** [comment]
I'm not sure the scope of this issue is already sufficiently covered, here, since the suggested fixed only cover `MAINPID` as obtained via `sd_notify()`.

Given that e.g. `ExecStop=` by default runs with the privileges of the unit, I would have expected systemd to perform the kill (e.g. for `KillMode=mixed`) with the privileges of the unit's user, e.g. do something like what would have previously been

    MAINPID=`head -1 -- "$PIDFILE"`
    su -u "$USER" -c "/usr/sbin/kill -- '$MAINPID'"

or even have functionality similar to `killproc`, which has additional validation with regard to the path of the killed process. I would at least have assumed that it only resorts to using elevated privileges when the low privilege kill does not result in the expected outcome.

The current implementation rather seems to be the equivalent of

    kill "`head -1 $PIDFILE`"

with the only validation of  `$PIDFILE`'s contents being that it contains a valid integer.

As already noted, this allows a non-privileged unit to potentially trick the system into killing an arbitrary process by writing a PID to a specific file owned by the unit's user. This may even happen by accident, if the PID file write from the daemon is not atomic and only a partial PID was written (that's probably purely a theoretical problem).

While, obviously, this requires root privileges to hand the privilege to the unit and thus doesn't seem to be a strong attack vector, it was still sufficient to lull me into a false sense of security. I fully expected the kill to happen with user privileges, given that I seemed to have an option to turn that security off (namely `PermissionsStartOnly=`).

Also, having less secure defaults with the rationale that systemd also caters to daemons where $MAINPID leaves the unit's cgroup seems to be at odds with the seemingly ubiquitous notion that the service cgroup isolates the processes of a service.

**Comment by thoger** [comment]
Any thoughts on @dhke's question regarding why not send signal with dropped privileges instead of root when service is configured to run as non-root User/Group?

**Comment by poettering** [comment]
> Any thoughts on @dhke's question regarding why not send signal with dropped privileges instead of root when service is configured to run as non-root User/Group?

Well, changing creds in PID 1 is quite problematic, we'd need to fork off a stub which does setresuid(), does the kill(), then exits, and the parent must wait for it. Which is possible, but not easy to get right, since you need to be reasonably protected from the user doing stuff with your process after you dropped privs and stuff... you also need to protect yourself from RLIMIT_NPROC games and such. I mean, this is all doable, but one needs to be very careful with what you do.

In general though, I am not sure this is the right approach in the first place. there's suid binaries and stuff, clients can change identity as much as they want, and in general they have every right to, and we need to handle that correctly even if the user the service uses is not declared in the unit file... Hence, we need a code path that does not rely on changing identities to some known target unit, and thus it's a question why bother at all with that...

(And finally, I think it's already kinda nice that if a service uses sigwaitinfo() that the creds of the sender are actually the creds of PID 1 and not of some stub that isn't around anymore)

**Comment by ret2libc** [comment]
@poettering @shibumi Are you ok with me requesting a CVE for this issue? I think it's a local Denial of Service and it would help us, and others, keep track of the problem.

**Comment by keszybz** [comment]
The original issue was fixed in systemd 237, two releases ago. I don't think it makes sense to open a CVE for it now.

> why not send signal with dropped privileges instead of root when service is configured to run as non-root User/Group?

This would create an easy DOS, where any unit which forks any setuid binaries becomes unkillable. Doesn't seem to be a good idea at all.

**Comment by poettering** [comment]
> @poettering @shibumi Are you ok with me requesting a CVE for this issue? I think it's a local Denial of Service and it would help us, and others, keep track of the problem.

It's not really a vulnerability. the newer checks are tighter than the old ones, but the NotifyAccess= logic was already an effective access check in this regard. We didn't allow arbitrary service processes to do whatever they want with the main PID, you had to be privileged already to install the service file, and you'd then also have to open up access to the sd_notify() logic as a second step to do anything about this.

So, this is not really vulnerability in the first place I'd say, and has been made stricter a long time ago. As long as CVEs are however what they are (i.e. considered a form of currency that security people deal in?), and as long as every minor CVE in systemd is something big tech news sites think it's worth doing long articles about I'd prefer not having CVEs assigned to stuff that isn't really a vulnerability and has been made stricter long time ago. I hope this makes sense?

**Comment by dhke** [comment]
For what it's worth, please note my original post:

>  I would at least have assumed that **it only resorts to using elevated privileges when the low privilege kill** does not result in the expected outcome.

The rationale behind this being, that one should always try flipping the switch. This discussion has already significantly digressed from that

> Well, changing creds in PID 1 is quite problematic, we'd need to fork off a stub which does setresuid(), does the kill(), then exits, and the parent must wait for it. 

Isn't that what it needs to happen, if

`ExecStop=/usr/sbin/kill -TERM $MAINPID`

is specified and don't the mentioned issues apply here, too?

**Comment by shibumi** [comment]
I agree with @poettering. Scheduling a CVE for this is a little bit late. The issue has been fixed since weeks or maybe even months. Moreover killing the systemd main pid process would just result into a restart of pid 1 and please  don't forget that you need enough permissions to place the malicious pid file and you have to wait for the root user to send the kill signal to the maliciously placed pid.

**Comment by bl33pbl0p** [comment]
> Moreover killing the systemd main pid process would just result into a restart of pid 1

That seems incorrect, usually if an assertion is hit, PID1 freezes itself and (since recently) continues reaping orphans. This means you cannot talk to systemd anymore, control none of the services, lose all of its functionality (watchdog, sockets, timers, path events, etc), but still continue to use the system. OTOH, the kernel reboots the system anyway if PID1 goes down. You cannot "kill" PID1 on Linux unless it wants itself to be killed.

**Comment by ret2libc** [comment]
> It's not really a vulnerability. the newer checks are tighter than the old ones, but the NotifyAccess= logic was already an effective access check in this regard. We didn't allow arbitrary service processes to do whatever they want with the main PID, you had to be privileged already to install the service file, and you'd then also have to open up access to the sd_notify() logic as a second step to do anything with this.

I was mainly referring to the content's replacement of the pid file of a non-root service. For that, I think there was no check in place. And that's not really something systemd can do anything about. You can't prevent admins from allowing a service to run as a different user (you do support that indeed), so the mainpid file could be writable by an un-privileged user (either because the unprivileged user has local access and can directly overwrite the mainpid file content or because, maybe, the service is vulnerable and allows somehow an attacker to replace the mainpid file's content).

That said, CVEs are just a way to give names to security related issues and they are not always a big deal  (like in this case, for example), so not something to be aware of. The issue was fixed a couple of releases ago, but that would not block us from requesting a CVE. It would only help people who use systemd, and in particular those that still use an older version of systemd (e.g. RHEL, Debian, etc.), to keep track of things that may be security-relevant and choose for themselves what they want to do with them.

WRT having to be privileged already to install the service file, that's true but the flaw is not in installing the service file. That would just make the flaw harder to exploit and decrease even more its impact, because an attacker would have to find already some configurations/services in place. However, this is, I think, the only point that may prevent us from requesting a CVE and consider this just security hardening.

**Comment by poettering** [comment]
> I was mainly referring to the content's replacement of the pid file of a non-root service. For that, I think there was no check in place. And that's not really something systemd can do anything about. You can't prevent admins from allowing a service to run as a different user (you do support that indeed), so the mainpid file could be writable by an un-privileged user (either because the unprivileged user has local access and can directly overwrite the mainpid file content or because, maybe, the service is vulnerable and allows somehow an attacker to replace the mainpid file's content).

Well, the daemon code is not entirely untrusted. It's chosen by the admin, and the PID file is carefully configured by the admin (at least that's the idea). I mean, it's good validating everything here, but it's not that anyone on sysv ever validated this stuff this thoroughly, and PID files are ultimately merely sysv compat. We are actively breaking compat here if you so will because we are more strictly validating PID files than any sysv script ever did...

Quite frankly, PID files shouldn't exist anymore. We support them for sysv compat, and they come with most of the pitfalls, security issues, lifecycle issues they always came with, and that's certainly not systemd's fault. 

Or to say this differently: it's a bit like assigning a CVE to the fact that when systemd runs a SysV script it doesn't turn on PrivateTmp=. Because, yes, we don't do that, but SysV compat is sysv compat, and you should compare the security of real sysv implementations with our compat layer and you'll notice we are aleady tons more careful there already, and we can't do anything about the fact that sysv services worked the way sysv services worked.

> That said, CVEs are just a way to give names to security related issues and they are not always a big deal (like in this case, for example), so not something to be aware of.

But that's really not how they are used or understood by the wider industry. They are used as a currency, they are counted and traded. And yes, systemd is under some extra scrutiny there, for some reason I don't fully understand. I am not sure we should needlessly play a part in that if there's no real reason to, because well, we are more strict now than the original concept of PID files ever was.

**Comment by poettering** [comment]
(What about this: please file a CVE against sysvinit/the sysv script concept/various sysv services and their PID file handling. Then we could claim that we fix all that with systemd, because that's what we do...)

**Comment by evverx** [comment]
> But that's really not how they are used or understood by the wider industry. They are used as a currency, they are counted and traded.

@poettering on the bright side, when CVEs are assigned to issues (whether it's justified or not is another matter), the fixes are more likely to be backported to older systems because everybody apparently cares about security (where "caring about security" usually just means reacting to CVEs). There are much more severe issues (security-wise) that were fixed a long time ago nobody cares about because they're just bugs without CVEs.

**Comment by evverx** [comment]
@ret2libc what I don't understand, though, is why you're asking @poettering and @shibumi whether they are OK with a CVE. If you think it should be assigned then, well, nobody can stop you.

**Comment by bl33pbl0p** [comment]
@shibumi Yes, I was confused because you said "killing" which is not the same as sending SIGTERM. Also, I tested locally and what is killing there in your service seems to be start-stop-daemon, if I put 1 in a PIDFile of a dummy service running as root (without any of the restrictions hence), systemd seems to complain that it is the manager and refuses to take it as MainPID.

**Comment by ret2libc** [comment]
> @ret2libc what I don't understand, though, is why you're asking @poettering and @shibumi whether they are OK with a CVE. If you think it should be assigned then, well, nobody can stop you.

@evverx I'm asking because upstream developers usually can provide some insights that I may miss and I don't want to request a CVE where I'm not 100% sure and that may just be rejected short time later. Also, it's a good practice to inform upstream and/or having upstream acknowledge the security issue before requesting the CVE.

> @poettering on the bright side, when CVEs are assigned to issues, the fixes are more likely to be backported to older systems because everybody apparently cares about security

And I agree with this. That's why we shouldn't be too afraid of assigning CVE even for low impact issues when it makes sense (and this may not be the case...)

> Quite frankly, PID files shouldn't exist anymore. We support them for sysv compat, and they come with most of the pitfalls, security issues, lifecycle issues, PID race issues they always came with, and that's certainly not systemd's fault.

@poettering this is a very good point. I guess the whole concept of having to trust a file to detect the main PID of a service is broken and it moves the responsibility of securing the file to whoever creates it. So I'm personally ok with considering this just hardening and not an actual flaw. Thanks for the explanations.

**Comment by evverx** [comment]
@ret2libc now that you put it like that I have no more questions. It's just that I would have interpreted it correctly if the original question had been more direct, that is something like "I'm going to request a CVE and at the moment trying to assess the impact. Thoughts?". But I'm not a native speaker of English so maybe it's just me. Sorry for the noise.

**Comment by poettering** [comment]
> And I agree with this. That's why we shouldn't be too afraid of assigning CVE even for low impact issues when it makes sense (and this may not be the case...)

Well, but we are the ones who are on the receiving side of the shitstorm we get whenever some CVE shows up. I mean, we get blamed even for polkit security problems nowadays (even though polkit is entirely separate, written by different people, with independent code and everything; see twitter for example), and i simply see no reason for triggering such shitstorms if there's no vulnerability in the first place.

CVEs are highly political. I might have a very different perspective on them than you, because well, systemd comes with a lot of political baggage, and I am not a security guy primarily, but I'd always be very conservative with piling CVEs on, and giving the peanut gallery more fodder than really necessary...

**Comment by evverx** [comment]
> i simply see no reason for triggering such shitstorms if there's no vulnerability in the first place.

@poettering the problem is that sometimes it's hard to tell whether an issue you're looking at is a vulnerability or not. For example, I don't consider the issues found in https://github.com/systemd/systemd/pull/10190 vulnerabilities because I simply don't use that code. But if I did, they would definitely bother me. If assigning CVEs to issues like that is the only way to get the fixes backported, I personally have no problem with that. Last time I checked the mute button on Twitter worked just fine.

@ret2libc there're 20 fuzzers that keep finding issues like the ones I just mentioned and, for example, https://github.com/systemd/systemd/pull/9979. I'm pretty sure you'll find something interesting if you take a look.

**Comment by evverx** [comment]
I'd also add that everything would probably be less chaotic if we had a process of handling security issues that would be different from simply reporting them to large distributions and hoping for the best. I'm not sure if it's helpful but I was watching https://www.youtube.com/watch?v=sNjylW8FV9A&feature=youtu.be the other day and, by the way, one of the presenters happens to be a member of the systemd organization, who maybe could help.

**Comment by poettering** [comment]
@evverx yeah, the process is shitty right now, but there's something resembling a process right now: if you find an issue, report it downstream, not upstream (as those bug trackers generally have a concept of "hidden" security reports), this is mentioned here:

https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#security-vulnerability-reports

The downstream folks then hopefully know how to contact upstream folks. And we now have an upstream git repo om gitlab we discuss security PRs at (we can add you there if you want btw, if you have an account at gitlab.com).

This all is awful quite frankly, and a giant hack around the fact that github has not very helpful when it comes to a security workflow as there is neither a concept of "secret" issues, nor of secret PRs, but it's at least something, and is the best we could come up with.

**Comment by evverx** [comment]
I could create a private repository, set up Travis CI there and run daily cron jobs to sync the repositories. In fact, I've just created one and invited you as a collaborator. Let me know what you think. It seems to me it would be better than an abandoned repository on GitLab with no CI whatsoever.

**Comment by evverx** [comment]
Just to be clear, I have no problem with GitLab. It's just that it's usually hard to replicate everything (especially tooling) there.

**Comment by evverx** [comment]
> there's something resembling a process right now: if you find an issue, report it downstream, not upstream (as those bug trackers generally have a concept of "hidden" security reports), this is mentioned here

That's exactly what I meant by "reporting security issues to large distributions and hoping for the best" :-) In my case, it doesn't work because I'm the one receiving those reports and I can't forward them left and right for predominantly legal reasons :-)

> https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#security-vulnerability-reports

@shibumi while we're at it, could you add a word or two about how to report issues to the Arch security team?

**Comment by poettering** [comment]
@keszybz can probably elaborate why we didn't go for the github private repo option.

**Comment by keszybz** [comment]
We didn't really have money we could spend on it. I guess we could create a smaller organization just for the security issues, and pay for a smaller number of seats there, and add and remove users as necessary over time. We probably would need much less "seats" there, maybe 15–20 (a bunch of the core contributors, + people from each distro, + the reporters and reviewers for specific issues). That'd be $1620-$2160 per annum. Do you think it's worth it?

**Comment by evverx** [comment]
> I guess we could create a smaller organization just for the security issues

As far as I know it's impossible to transfer issues between repositories owned by different organizations. That is it will be hard to make a public issue private to hide it and make the same issue public again when everything has been hopefully disclosed responsibly.

> That'd be $1620-$2160 per annum. Do you think it's worth it?

I think it depends. Maintaining two different repositories and two different bug trackers hosted on two different platforms properly and switching between them is usually much more expensive.

**Comment by evverx** [comment]
I forgot to mention that in general CI for private repositories on GitHub isn't free either so it should be taken into account too.

**Comment by shibumi** [comment]
@evverx We have a mail for security issues: security@archlinux.org + our dedicated flyspray bugtracker that allows us to close issues (but we will switch to another bugtracker in the future).

It's a shame that github doesn't support private issues. I see only three options here:
* leave it as it is currently (github + private gitlab repository)
* use github only as mirror (what will happen with all current issues?) and migrate everything to gitlab
* host your own gitlab/git repository with bugtracker?

wouldn't it make sense to host an own gitlab on freedesktop.org?

**Comment by evverx** [comment]
> @evverx We have a mail for security issues: security@archlinux.org + our dedicated flyspray bugtracker that allows us to close issues (but we will switch to another bugtracker in the future).

I'm sure you have a way to handle security issues. What I was trying to say is that it'd be great if you could update https://github.com/systemd/systemd/blob/master/docs/CONTRIBUTING.md#security-vulnerability-reports.

> I see only three options here

I'm not sure why you excluded a private repository on GitHub :-) Keeping everything as is on GitHub and paying for a private repository is an option too. I kind of understand that it's expected that open source developers should suffer and that their time apparently cost nothing and can be wasted right and left, but, come on.

**Comment by evverx** [comment]
> No, actually please don't. The intent wasn't to provide for many or most distributions, but instead to have one or two ways to do it. 

Which effectively means that Arch/NixOS/... users should spin up a distribution they never use to report a vulnerability. No wonder they are likely to go public.

**Comment by keszybz** [comment]
"Sign up" only means that they have to create an account. I have accounts of on Ubuntu, Debian, RHEL, OpenSuse, Arch, and probably some others, and it only means that I interacted and reported some bugs there in the past. I don't consider this too onerous.

Although, maybe we should consider creating a private google group for this. We have one for the code of conduct (completely dormant actually).

**Comment by evverx** [comment]
> "Sign up" only means that they have to create an account.

I'm not sure I understand. Are you saying that it's OK for NixOS users to report bugs to, for example, the Fedora project?

> Although, maybe we should consider creating a private google group for this.

That sounds great. Though, it doesn't help with private PRs from GitLab that don't pass CI on GitHub. It's a bummer to backport a fix downstream just to find out that it doesn't exactly work and backport another fix to fix the fix.

**Comment by poettering** [comment]
(Let me stress I don't think the security workflow we have now was great at all, it has serious flaws [such as the no-CI thing]. However it's also not a complete failure either. my ideal solution would be if github would care about open source projects enough and provide us with some much needed functionality in this area, such as private PRs/issues with CI and stuff. I am totally happy with switching to a better a approach for all of this if one pops up. In fact I even considered moving the whole shebang to GitLab because of this, but I am quite concerned about losing drive-by submitters that way — and also the work...)

**Comment by poettering** [comment]
(adding a private mailing list sounds good to me, if anyone wants to set that up)

**Comment by evverx** [comment]
@poettering GitHub kind of provides a way to do it but it isn't free (which is the main problem here as far as I can see and I get it. That's exactly where caring about security stops in most cases). And I agree that moving to GitLab isn't as easy as it might seem to be. Just to be clear, I have no problem with that and it isn't the worst process I've ever seen. At some point I just realized that changing anything might make things worse so I just decided to stop keep bothering everybody. Sorry for the noise.

**Comment by ret2libc** [comment]
Bringing the discussion back to the original issue.. :)

After talking with other people about it, I'm probably going to ask for a CVE about it. The reason being that it is possible for a unprivileged user to request killing of a privileged process.

I agree that PIDFile comes from somewhat an older time, but it's still very well supported and sometimes it's the only way to work with some services that do fork (thus you need Type=forking AFAIK). Moreover, that's not about being better/worse than sysv. Systemd has the ability to stop this (it did, indeed), so it should. Assigning a CVE will make the tracking/backport (where deemed necessary) much easier. As already said, it will probably be a low/medium impact flaw, but nonetheless a flaw, because the privileges boundaries should not be crossed (otherwise, why would I run a service as user A and not directly as root, if not for privilege separation?)

> Quite frankly, PID files shouldn't exist anymore. We support them for sysv compat, and they come with most of the pitfalls, security issues, lifecycle issues, PID race issues they always came with, and that's certainly not systemd's fault.

As previously said, that's true, but we shouldn't allow an unprivileged process to kill a privileged one. Yes, it could kill another process belonging to the unprivileged user, but that's not a big problem, because if we think the user is malicious, he can already kill his own processes. The important bit should be that a service with User=A, would not be able to kill a random process for User B (or at least not from root).

> Well, changing creds in PID 1 is quite problematic, we'd need to fork off a stub which does setresuid(), does the kill(), then exits, and the parent must wait for it. Which is possible, but not easy to get right, since you need to be reasonably protected from the user doing stuff with your process after you dropped privs and stuff... you also need to protect yourself from RLIMIT_NPROC games and such. I mean, this is all doable, but one needs to be very careful with what you do.

Again, as said by others, I think a change of creds is happening when you do `ExecStop=`, right? And yes, many trick may be done by the user, but if we assume the user is malicious, he can do already whatever he wants with his own processes (e.g. he could just re-run that process, if he doesn't want to be killed by systemd etc.)

**Comment by poettering** [comment]
> After talking with other people about it, I'm probably going to ask for a CVE about it. The reason being that it is possible for a unprivileged user to request killing of a privileged process.

Well, only if both hold:

1. PIDFile= is used, which requires privs, as it is encoded in the unit file
2. It points to a file in a directory chown()ed to some non-root user (which also requires extra privs, as chown()ing is privileged)

Or in other words: this is only exploitable for daemons that are poorly written and write out there PID files from unprivileged code. Correct SysV daemon code will not do that: it will fork in the parent, drop privs in the child, write out the PID file in the parent, exit in the parent. Your vulnerability is in the daemons that don#t do it that way. Please file bugs against those! Any daemon that writes out PID files from *unprivileged* code, i.e. that needs their PID files' directory to be writable to unpriv code is doing it wrong, hence please file bugs against *those* services. It's in the interest of everybody, because it means you fix the bugs where they are then, and other systems benefit too which still rely on double-forking+pid-files to work correctly, i.e. RHEL 5, RHEL 6, all the BSDs, and so on.

Anyway, please understand that I strongly disagree with sticking a CVE on anything in your path. I really don't appreciate the internet bs that follows each time, that *we* are the target of.

**Comment by ret2libc** [comment]
> Any daemon that writes out PID files from unprivileged code, i.e. that needs their PID files' directory to be writable to unpriv code is doing it wrong, hence please file bugs against those services

Why does systemd support `User=unprivileged-user` + `Type=forking` + `PIDFile`? Why does the documentation says that `The PID file does not need to be owned by a privileged user,`? It's for legacy, probably, but whatever are the reasons, it seems it needs to support them and the fact that systemd kills any process without looking at the user it belongs to is (actually, was) a flaw.

Assuming that you do need to support PIDFile for services that belong to an unprivileged user, there may be multiple ways to write to the PID file: the attacker is able to login as that user, the service is exploited somehow, etc. Now, if I exploit a service running as user X and I'm able to trick systemd into killing a service running as root, that's a flaw for me.

> PIDFile= is used, which requires privs, as it is encoded in the unit file

An attacker doesn't need to write PIDFile= himself. He just needs to write into the PID file of a service that uses PIDFile=

> It points to a file in a directory chown()ed to some non-root user (which also requires extra privs, as chown()ing is privileged)

The attacker doesn't need to setup the directory himself.

What I assume for the attack to be successful is: there's a service running as User X, that uses PIDFile. The attacker is *somehow* able to write files as user X and overwrites the content of the pid file with a random root-owned process pid. This is, I think, a supported scenario (as said, if you do not suppose that you can have a service run with `User=X`, then I think you should completely ignore PID files not owned by root)

**Comment by ret2libc** [comment]
> And you are in the comfortable position that any CVE you attach to stuff gets you credit points.

Actually that doesn't give me any point nor credit :) It's not like I discovered the flaw or anything. I just request the CVE, that's all. Nobody is going to say "ehi Riccardo has discovered flaw XXXX in systemd". 

I have to do this because it is important for many people that can't follow upstream development closely, so they can see what's security relevant and what's not and in that way distributions can backport these fixes too.

And I don't think there is going to be such a storm for a Low/Medium impact flaw. I can't just hide my head under the sand and pretend I didn't see anything. The flaw is there, an attacker can use it (under the right circumstances), so pretending this is not what it is will just hurt many projects. Flaws are everywhere... you are not bad if you admit you have some.

I absolutely don't want to make systemd looks bad. The opposite! I really think this is a great project!

**Comment by kavol** [comment]
> Anyway, attaching CVEs to issues where systemd is now stricter than than sysvinit, and hence sending the signal that systemd is bad while we are actually doing good here by being better than sysvinit now, is what I think sucks hard.

well ... I don't get this logic ... a bug existed (still exists in many distributed versions) in systemd, how does a comparison to sysvinit help here? - looks like a textbook example of red herring to me ...

while testing a CVE for mysql/mariadb, I have found that systemd suffers the same problem

so I thought if this was CVE-worthy for mysql/mariadb, it's automatically CVE-worthy for systemd (the more that it affects a subset of services in the distro, not just one badly written initscript)

but it didn't get assigned/linked to my bugreport for RHEL, and when I'm checking what happened to the bug >a month after being reported, I came into middle of this discussion

now we're not considering CVE by the security impact, but rather if it "makes upstream developers unhappy" ... great, bravo, once again I'm left speechless ...

**Comment by evverx** [comment]
> if it went through standard security channels, we could have already fixed it, it wouldn't need to wait for someone to discover that our distro is vulnerable as a sideeffect of other testing, like it happened to me 

@kavol just out of curiosity, could you expand on what those "standard security channels" are? Looks like currently it's just sitting and waiting for someone else to report a security issue (ideally, with a CVE assigned) or looking for the word "CVE" on GitHub. How is this different from what is happening here?

**Comment by ret2libc** [comment]
> If you're going to request a CVE, could you drop a comment here when it's assigned so that we could block the issue?

Sure, I will.

**Comment by evverx** [comment]
@ret2libc thank you.

@kavol I apologize for the tone of my comments. It was absolutely uncalled for.

Don't get me wrong, in fact, I kind of like it when security researchers analyze the code and the more they do it, the better. If they think that CVEs should be assigned, then so be it (I personally have no problem with that) :-) In the end, it's systemd that's getting better bit by bit. To quote docs/HACKING.md, happy hacking!

**Comment by shibumi** [comment]
@ret2libc will you open CVEs for any other init system as well? They might have the same issue ;)

**Comment by eli-schwartz** [comment]
@poettering On the security reporting thing I think the only practical solution would be to have a "real" bugtracker for systemd, because Github issues simply aren't a bugtracker -- as this discussion demonstrates. Even being able to transfer issues to/from a private repo is kind of a terrible hack.

Maybe it would be possible/make sense to get a dedicated "Community projects" subproject on the redhat bugtracker and simply use this? Especially if you're recommending people use that very tracker as basically an upstream tracker anyway.

**Comment by evverx** [comment]
Plus as far as I understand it's already possible to open private issues on GitLab (it's just not documented anywhere).

**Comment by eli-schwartz** [comment]
https://bugzilla.redhat.com it's a bugzilla with an extension called Bugzilla::Extension::ExternalBugs that allows you to track the statuses of external trackers from a wide variety of sources including Github issues/PRs. It should be feasible to handle PRs here, and issues there -- assuming systemd wishes to do so and can get the necessary bureaucratic bits together to create a https://bugzilla.readthedocs.io/en/5.0/administering/categorization.html#products with an associated group for the systemd developers with edit rights.

Or set up a systemd-specific external tracker with more capability than the github one -- the problem is finding one that you don't have to self-host. :p

**Comment by evverx** [comment]
@eli-schwartz just to clarify, it's not that I can't create an account there. I've just received a confirmation email so I'm all set but I have already forgotten what I wanted to report :-)

**Comment by poettering** [comment]
> Maybe it would be possible/make sense to get a dedicated "Community projects" subproject on the redhat bugtracker and simply use this? Especially if you're recommending people use that very tracker as basically an upstream tracker anyway.

(Quite frankly, I think bugzilla is an abomination. It's UI is so bad, probably matching its choice of its programming language: perl. I am very sure there are better bug trackers than github, but I am also very sure that bugzilla is not it and a step backwards, not forward)

**Comment by ret2libc** [comment]
CVE-2018-16888 has been assigned to this flaw.

See https://bugzilla.redhat.com/show_bug.cgi?id=1662867
