### ISSUE TITLE
cryptsetup-generator: use path_startswith("/dev") rather than is_device_path() when adding deps on key files from /etc/crypttab

### ISSUE THREAD

**Issue by ettavolt** [systemd/systemd#6647]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

234.11

### Used distribution

Arch Linux

I'm trying to setup encrypted root partition in plain mode with hashed SecureBoot PK entry as key. This way system may boot without user interaction. (BTW, it's nice that systemd-cryptsetup can hash content of keyfile in contrary to cryptsetup).

Currently systemd adds a require for sys-firmware-efi-efivars-PK\x2dsome\x2dvery\x2dlong\x2dguid\x2dhere.device. Obviously, no such device exists. After I get to emergency console, I see efivars mounted. And there is no efivars.device unit.

Thus for my setup cryptsetup-generator should either add requirement for correct unit (device-hugepages maybe, judging for API File Systems documentation) or not require device for keyfile at all (efivars are said to be mounted 'early', if available).

P.S. If anyone is interested, I can write why I assume this setup somewhat 'secure'. Was going to do this after successful setup.

**Comment by poettering** [comment]
Can you elaborate what your configuration files actually look like? Did you simply specify a path to /sys/firmware/... in /etc/crypttab?

**Comment by ettavolt** [comment]
Yes, I've put /etc/crypttab into initramfs with contents like
```
root	PARTUUID=df06fff2-5a26-48e1-943d-697cc4a140b6	/sys/firmware/efi/efivars/PK-guid	plain,discard,cipher=aes-xts-plain64,size=512,hash=sha512
```
BTW, looking at the code, I think that's just ``bool is_device_path(const char *path)`` in path-util need to differentiate between ``/sys/`` subdirectories.

**Comment by poettering** [comment]
Usually, checking for both /dev and /sys for the purpose of deps is actually the right thing (that's because we reference device-node-less devices via sysfs paths, while those which have a device node via their /dev paths). In this case we however need to actively read from the path, and that only makes sense if the specified path refers to a device node or regular file, hence using is_device_path() makes no sense here, and we should instead use path_startswith(path, "/dev")...

btw, a PR for this would be greatly appreciated, if you want to see this fixed soon. i figure the patch would actually be quite simple...

**Comment by ettavolt** [comment]
Just built systemd with the change from PR - works as I want it.

**Comment by poettering** [comment]
Closing, as #6732 has been merged.
