### ISSUE TITLE
FE: Support similar functionality to incrond - passing notify options to service Units

### ISSUE THREAD

**Issue by spstarr** [systemd/systemd#668]
It would be great if systemd path units let you pass information to the service Unit. Similar to what incrond does, you can pass the specific file that changed or the type of inotify event.

This would be handy as the service Unit could act on this information passed by systemd.

**Comment by poettering** [comment]
This cannot work, as systemd .path units only start units if they are not started yet. If you make multiple changes at once, then only a single service unit will be started for it until it decides to exit. Thus, systemd does not propagate individual inotify events to service start events, but always coalesces many into one. A service thus has to check what happened on its own, without access to the actual events that took place.

Also, inotify queues can overflow, that means that even if we'd pass the events on a daemon requires a strategy to handle cases where an overflow happens by rechecking the dirs being watched on his own. That makes it much less interesting to propagate the events, since the recheck code needs to be in place as well.

Sorry, but I don't think this really fits the systemd model. I think this is better something to leave to incrond.

Sorry.

**Comment by spstarr** [comment]
~~incrond is abandoned however, so what other options? Aside from keeping it alive.~~

I've worked around this issue and now can just use .path unit easy. Great work!
