### ISSUE TITLE
systemd-networkd: Add support for not "enslaved" gre tunnels

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#6695]
It seems to be necessary to create some kind of network (e.g. eth0.network) to create tunnel interfaces. The eth0.network then has to contain Tunnel= entries. And as I found out in #6693, will remove the IP addresses from eth0.

As we already know, this requirement ended rather bad for me. It would therefore be good to be able to create gre interfaces which are not assigned to a specific network. I mean these "gre0@NONE" interfaces instead of "gre0@eth0".

**Comment by poettering** [comment]
Philosophy of networkd is to either manage an interface in full or not at all. If you create a matching .network then this means it will manage the interface. If you don't want that, then don't create a matching .network.

I am not convinced it would be a good idea to support any "half-managed" mode in networkd.

That said, IIRC .netdev tunnels should work without Tunnel=. All that Tunnel= does is bind the tunnel's state to an interface state. And if you don#t want that and the interface the tunnel runs on exists perpetually, then don't make use of Tunnel, but just define the .netdev of your choice.

@ssahani might comment on this too.

It appears to me there's nothing to fix here, really, except maybe better documentation.

**Comment by ghost** [comment]
Thanks for the feedback. But the netdev will not be started without Tunnel= in the "parents" .network at the moment. Maybe @ssahani can point me to the correct way to create a gre .netdev which is started even without the .network.

Right now I've tested (the goal of this ticket):

/etc/systemd/network/25-gretunnel.netdev

    [NetDev]
    Name=gretunnel
    Kind=gre
    
    [Tunnel]
    Local=1.2.3.4
    Remote=1.2.3.5
    TTL=64

/etc/systemd/network/25-gretunnel.network

    [Match]
    Name=gretunnel
    
    [Link]
    MTUBytes=1400
    
    [Address]
    Address=5.0.0.1/32
    Peer=5.0.0.2/32

systemd-networkd completely ignored these entries and performed no actions. It only started gretunnel when I've added the 25-eth0.network file (see #6693 why this was a really big mistake by me):

    [Match]
    Name=eth0
    
    [Network]
    Tunnel=gretunnel

**Comment by ssahani** [comment]
@charlemagnelasse I understand your requirement. Now it's not possible because we are creating netdev is same as `sudo ip link add gretap type gretap local 192.168.200.1 remote 172.16.0.1 dev enp0s3` .
Hmm so how the arch now is we don't know the which ifindex until all the links are created. Once all the netdevs are created we come to know the link index number. from .network files we come to know link index that we feed to netlink message so it comes like ` gretap@enp0s3:` . 

Now we create netdev which are not dependent on other too 
```
 NETDEV_CREATE_INDEPENDENT, (veth,tuntap etc) 
 NETDEV_CREATE_MASTER, (bridge bond)
  NETDEV_CREATE_STACKED (tunnel)
```
Now the gretap is `.create_type = NETDEV_CREATE_STACKED,` . So we need a .network file.
For your use case we need to configure the `create_type` itself and so that we can create a tunnel without a network file and that will show ` gretap@NONE:` .
