### ISSUE TITLE
add example for creating your own target unit that builds on top of a well-known target like rescue.target or so

### ISSUE THREAD

**Issue by Fry-kun** [systemd/systemd#67]
I have a bunch of headless servers that sometimes need manual fsck of the /
It would be really nice to have an "emergency with networking" option, if possible

Without it, it's required to connect a KVM every time this happens...

**Comment by mbiebl** [comment]
So you want networking and ssh being started from the same file system you want to check?
In this specific use case, I think it would be better if you used something like dropbear in your initramfs, where you can actually safely check the root fs.

That said, I think the idea to have an emergency mode + network could be useful. Say because systemd dropped you into the emergency shell as it couldn't find all devices listed in /etc/fstab.

**Comment by Fry-kun** [comment]
I think most of the time the root fs is stable enough to run ssh daemon. Considering the drives nowadays are measured in TBs, it's not likely a particular error is on the ssh binaries/configs.
Although if the system's exact ssh config can't be used, ssh server must not be started -- it's probably a security risk

**Comment by poettering** [comment]
Well, I can see why in some cases this might make sense, but I doubt we should introduce this a a concept, since it's so arbitrary: people's usecases are so vastly different here, and some might want a target that sets up networking only on some specific ifaces, others might want to run both ssh and ntworking, others only networking. And so on. Given that this is all that unclear I think it's better to leave definition of such targets to the user: just create your own target "my-networked-rescue.target" and then add in as deps rescue.target and whatever else you want. 

Or, alternatively, just use systemd.wants=systemd-networkd.service on the kernel cmdline option (or whatever service is responsible for your networking), without any local configuration. THis will just pull in that one specific service, and not change anything else.

**Comment by Fry-kun** [comment]
That sounds reasonable.
Maybe you can add a few examples like that to the documentation so it's easier to figure out?

**Comment by poettering** [comment]
Sure, adding more docs always makes sense. Consider filing a feature request issue for that. or even better even provide a patch as PR...

**Comment by Fry-kun** [comment]
Can we just update this issue to "add to docs" RFE?

**Comment by poettering** [comment]
ok, done.

**Comment by lkraav** [comment]
Hey all. Did anything about this ever get documented?

**Comment by keszybz** [comment]
Nope, still open.
