### ISSUE TITLE
resolve: NSEC3 parser appears borked

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#671]
The NSEC3 parse invokes  dns_packet_append_types() at the end, which appends (not reads) RR parts, no?

The DNS_TYPE_NSEC parser appears to never exit its loop if the total size of the windows inside the RR don't actually match exactly the rdlength. That's exploitable!

@teg? @zonque?

Please be more careful with parsers like this!

**Comment by poettering** [comment]
All issues introduced by PR #588 btw.

**Comment by poettering** [comment]
Hmm, also, please never ever use a type like "unsigned long long", like the Bitmap code does. That's the same as "uint64_t", always, it's just stupidly defined and hard to read. Please use "uint64_t" instead.

**Comment by poettering** [comment]
Actually, I think what you wanted to sa with "unsigned long long" is uintmax_t, no? Please use that instead!

**Comment by poettering** [comment]
Hmm, also, why is base32hexchar() called that way? why the "hex"? base32char() does not include a "hex", so what's the point? specifically, since i don't see what base32 would have to do with hex encoding?

**Comment by crrodriguez** [comment]
Unfortunately uintmax_t is unsigned long long only in 32 bit hosts.. in 64 bit targets it is "unsigned long"

**Comment by teg** [comment]
The appending instead of reading bug is fixed in:https://github.com/teg/systemd/commit/3695a5a67b3e903d06d9746fa45514d25d08c70e (still pending in PR #622).

I don't see the infinite loop in the NSEC parser. If we go past the size of the message, dns_packet_read_type_window() will fail (as it always reads at least one byte).

Regarding the naming of base32hex(), the RFC states "This encoding may be referred to as base32hex". This encoding should not be regarded as the same as the "base32" encoding and should not be referred to as only "base32".  This encoding is used by, e.g., NextSECure3 (NSEC3)" https://tools.ietf.org/html/rfc4648#section-7

I don't understand the claim "base32char() does not include a "hex", so what's the point?". There is no base32char(), only base32hexchar()... What am I missing?

**Comment by teg** [comment]
I merged Daniel's patch (thanks!), so with that (and my unmerged patch) I think all the comments have been addressed?

**Comment by zonque** [comment]
On 07/23/2015 04:41 AM, Lennart Poettering wrote:

> The DNS_TYPE_NSEC parser appears to never exit its loop if the total
> size of the windows inside the RR don't actually match exactly the rdlength.

We never read beyond the limits of the packet, and we can't end up in an
endless loop because we require at least 3 bytes to be read in each
iteration, and bail out if that's not possible.

But yes, in order to avoid bogus reads, we should make sure
`dns_packet_read_type_window()` does not eat more data than `rdlength`
specified. I'll prep a patch for that.

**Comment by teg** [comment]
I've picked up the patch Daniel wrote for the type_window() reads and will submit that together with some other fixes.

**Comment by poettering** [comment]
@crrodriguez why is that unfortunate? I think uintmax_t would be a fine type for this, as it's the biggest integer type the compiler can handle nicely. But uint64_t (as it is now after the newest commits) is fine too.

**Comment by poettering** [comment]
@teg ah, i wasn't aware that base32 and base32hex are two different things. Can you maybe add a comment to one of the functions pointing people to this difference? I was just confused by the "base64" vs "base32hex" nomenclature, and assumed it the "hex" are just left-over from the original hexmem() functions. Sorry for the confusion.

I think after the latest PRs are merged we are good. Thanks for fixing.

**Comment by teg** [comment]
I'll include a comment to that effect in one of my next PRs. Closing this now.
