### ISSUE TITLE
logind: document the syntax restrictions on seat names, and the reasons for very long names and the implications of it somewhere

### ISSUE THREAD

**Issue by n3rdopolis** [systemd/systemd#6745]
### Submission type

 - Request for enhancement (RFE)

(master, at least when I checked the source for the maximum seat name size
 
> …

### Debian

> …

logind permits seat names to be 255 chars long (as far as I tested, and verified with the source.
It's probably too late to change with backwards compatibility and all, but it is my belief that 255 is far too large.

The VFS file name limitation in the kernel is also 255 bytes.

This IMHO can cause problems if the file name needs to depend on a seat name.

Such as 
something_hwlog_${SEAT}.log
or
wl_greeter_${SEAT}
       and
wl_greeter_${SEAT}.lock

A seat name that is very large, which is legal, could cause problems with software that depends on having seat names in its files.

I am not sure if anything can be done about this though...
> …

> …

> …

**Comment by poettering** [comment]
Oh, well, logind defines what a seat is, and the requirements it makes on them permit them to be used as file names, but not necessarily as part of filenames that have some concatenated extra strings.

Note that we automatically generate seat names from sysfs information, and because of that it is really useful if we can safely generate valid seat names from that information, and a very short limit on that would make that quite complicated for us. 

My guess is that programs which use seat names like that should be fixed, and the folks doing that, should have pinged us first (or looked at the logind sources), to see if it is actually safe to include seat names in filenames (I mean, after all if we would have permitted "/" as part of seat names the whole logic would fall apart).

I think the assumptions made by consumers of this are simply wrong, but I am not sure we can do much about this from the systemd side of things.

I will treat this as documentation issue now, I figure we can add some docs to the right places about this, pointing users to the fact that this is an issue, and they need to think about it.
