### ISSUE TITLE
Please prevent rebooting by accident

### ISSUE THREAD

**Issue by Harvie** [systemd/systemd#6783]
I accidentaly executed command `systemctl reboot nut-driver` instead of `systemctl restart nut-driver` which resulted in unwanted reboot. It surely was my fault and it was not big deal, however i can imagine servers at which this would be big issue.

Can you please prevent reboot, shutdown and similar commands from executing in cases when additional arguments do not make any sense? One day it might prevent small disaster.

Thank you.

**Comment by floppym** [comment]
The systemctl manual documents `reboot` as taking an optional argument to be passed to the reboot syscall. I do not think it is possible for systemctl to determine if this argument "makes sense".

> If the optional argument arg is given, it will be passed as the optional argument to the reboot(2) system call. The value is architecture and firmware specific. As an example, "recovery" might be used to trigger system recovery, and "fota" might be used to trigger a “firmware over the air” update.

**Comment by floppym** [comment]
Also, systemctl already checks for too many arguments.

```
# systemctl poweroff foo
Too many arguments.
# systemctl halt foo
Too many arguments.
# systemctl reboot foo bar
Too many arguments.
```

**Comment by ghost** [comment]
Note that Harvie gave one suggestion for one proposed solution - but there can
be other solutions.

It is more a question over how much customization is allowed.

Harvie wants to redefine that particular behaviour for his own
use case. So the focus should less be on the particular suggestion
per se, and more as to whether the change of the behaviour would
be allowed.

You can see customization being possible in e. g. git + git config or
vim + vimrc and so forth.

Similar customization could be possible here, too; Harvie could use
three commands, or perhaps even one aggregate command (but
three commends probably are more logical since he mentioned 
3 commands), to change the behaviour to one that he prefers
for his particular use case - if it is possible.

**Comment by poettering** [comment]
I am not sure we can really do anything about this i fear. As @floppym points out the additional argument for "systemctl reboot" is actually relevant and passed to the kernel API ultimately. This is documented and established behaviour we cannot really change anymore without breaking API. 

I sympathize with the issue @Harvie ran into, but I doubt we can do much about that at this point in time. "systemctl" is a dangerous tool in some ways, there's no turning back there really, and the checks we make for this are already pretty stringent and don't permit more than actually make sense. I can see that for many the additional argument is unexpected, but then again it is expected by others and document behaviour.

I will close this now, because I don't think we can change much in systemd upstream at this point. But then again, I am open to ideas.

**Comment by Harvie** [comment]
At least i am happy that this is not the case with halt and poweroff, since that can be even worse, because some systems don't have means to power up remotely.

**Comment by Harvie** [comment]
On the other hand i think that systemd can implement some feature that will mimick behaviour of "molly-guard" package. That means you have to manualy enter first part of hostname of the system before shutdown/reboot. However this should be turned off by default, since i guess most systems do not need such feature.

I use molly-guard wrapper on my sensitive systems, but it works only with legacy init commands like reboot and shutdown. It does not affect systemctl commands. I guess this can be quite easy to implement.
