### ISSUE TITLE
man: explicitly distinguish "automatic dependencies" and "default dependencies"

### ISSUE THREAD

**Issue by johnlinp** [systemd/systemd#6793]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

234

### Used distribution

Arch Linux

### Report

At first, I was reading "AUTOMATIC DEPENDENCIES" in `systemd.target(5)`, and there were only default dependencies that can be turned on/off by `DefaultDependencies=`. So I assumed that "automatic dependencies" == "default dependencies".

Then I read "AUTOMATIC DEPENDENCIES" in `systemd.target(5)`, and saw some of the dependencies are related to `DefaultDependencies=` and some are not. That made me a bit confused.

After all that, I read "AUTOMATIC DEPENDENCIES" in `systemd.unit(5)` and found that "automatic dependencies" and "default dependencies" are not the same.

I suggest that we can explicitly distinguish "automatic dependencies" and "default dependencies" in documentation to prevent confusion.

I will spend some time to reorganize those descriptions. Any suggestions?

**Comment by poettering** [comment]
Oh, yupp there's some confusion about this in the docs indeed. We should fix that.

Maye we should settle on different names though: "default deps" and "implicit deps"? I think "implicit" is a better name than "automatic", since both default and implicit deps are kind automatic.

Would be happy to merge a fix for this. I'd suggest to rename the section Default and implicit dependencies and explain both in the section, but start the section each time with a very brief sentence saying that one are always in effect and the other only when DefaultDependencies=no is not set.

Does that make sense?

(I am also happy with other ways to reorg and improve this btw, consider the above just an idea of how to reorg it)

**Comment by johnlinp** [comment]
Yes! I was thinking about giving them different names, but I didn't come up a good one. "Implicit" sounds good to me. I would start working on it.
