### ISSUE TITLE
The PID reuse race window can be held open arbitrarily long for scope units with After=

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6803]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

Code analysis on v234-397-g724b9f957, testing on v233.

### Used distribution

Fedora 26

### Bug report

`systemd-run` shows that scope units are not excepted from After.  E.g.

```
systemd-run --user --unit=test.service --service-type=oneshot -- sleep 1h &
systemd-run --user --scope --property After=test.service  -- sleep 1h
```

It sounds beautifully elegant that this is able to work.  Until you realize that the cgroup is only created and populated once the unit is started.  Populated using numeric process identifiers, which are subject to re-use (if the process terminates between now and then).

Since the above commands appear to work so naturally, we should aim to exclude this wide race window somehow.  At minimum by documenting the issue, so that people can think twice before creating situations like this.

Note that `After=` cannot simply be banned from scope units.  It is required to ensure correct shutdown ordering.  See the ordering dependencies used by the session scope units, created by logind.

I believe it is technically possible to keep the window narrow in this case, by using process handles.  Process handles (`struct pid *` [in-kernel](http://elixir.free-electrons.com/linux/latest/source/include/linux/pid.h)) are available to userspace by opening `/proc/pid/` (you can potentially even avoid the race on open if you open /proc/self/ and send it where necessary), and allow checking that a process is still alive at some later point.  We would have narrow race windows at open time, and between the check and writing the pid to the cgroup.  Found via [HN comment](https://news.ycombinator.com/item?id=12648674).

As described [elsewhere](https://lwn.net/Articles/677671/), systemd does not in principle eliminate PID race conditions[*].  But AIUI the other race windows tend to be quite narrow.  Hence the probability of such issues is low, given the 2^31 space of pids.  Their impact might be reduced during shutdown, as the victims must be newly spawned processes, but many native systemd service units will not need any new process in order to achieve shutdown.  (Another good reason to follow Fedora and not use `ExecStop=/usr/sbin/httpd -k stop` for no reason :).  Although mount units do use an external process at stop time.

[*] And sadly switching from killall5 to stopping session scope units has introduced a new PID race condition.  Again the practical risks are not as high as you might first imagine: session scopes are stopped before the mount units, and the same is true for `systemd --user` (user@.service).  Scopes v.s. LSB services is the risk I would worry about.

**Comment by poettering** [comment]
> the 2^31

It's 2^15 IRL, see /proc/sys/kernel/pid_max

**Comment by poettering** [comment]
UNIX PIDs are a racy concept by design. I am not sure we can really solve this, this is primarily something the kernel folks have to fix. Most commands dealing with processes (kill(), setpriority(), and so on) take a PID, and so does the cgroup kernel APIs, and there's no real better handle to processes in view. File handles to /proc aren't that either, since you cannot pass one to kill() or so, and you don't get one out of SCM_CREDENTIALS or so either. And the combination of a PID + an fd to /proc doesn't work either, since you can convert one to the other only in a racy way. 

I am not sure we should try to fix this from the systemd side, we cannot fully fix it anyway. The kernel folks have to fix the PID concept first, and then we can adapt to that, but without the kernel folks cleaning up their act I think the best we can do is pretend the problem doesn't exist the way UNIX has been doing it since 30 years...

We have a TODO list item to bump pid_max from 2^15 to 2^31 by default. But I figure the peanut gallery would hate us again for that, and make the PID reuse problem a systemd thing even though it's a general UNIX misdesign...

**Comment by sourcejedi** [comment]
Sorry, I have code to submit now to prevent scopes being delayed on start and fail instead.  I've just been looking at some other stuff.

That keeps the race nice and tight.  I think it makes a sensible interim measure, and I don't think it would have a big impact.  It's slightly weird that starting a scope can be delayed anyway.  I made sure to document it as "currently", to try and get people not to rely on the failure, and then get broken when the world is eventually fixed :).

**Comment by poettering** [comment]
btw, i'd still be willing to do the pids_mx bumping. We could just add that to one of our sysctl files we ship by default, and then wait and see how people react. Distros may revert it if they don't like it. It would slightly decrease the chance of PID reuse.

**Comment by poettering** [comment]
(and given that we have TasksMax= these days — and even set it by default for all services – the number of actual PIDs in use remains relatively restricted as before)

**Comment by sourcejedi** [comment]
Nitpick: `man proc` says the limit is 2^22, and can only be increased on 32-bit systems.

**Comment by poettering** [comment]
on my system it's by default 2^15, but i can increase it to 2^22, but not further. and it's x86_64...

**Comment by sourcejedi** [comment]
What I should have written is the maximum the limit can be raised to is 2^22, and of course it can be increased to that on 64-bit systems.  However it cannot on 32-bit systems, there it is limited to 2^15 still.
