### ISSUE TITLE
Some device units are really long and hit fs limits.

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#6867]
### Submission type

 - Bug report

### systemd version the issue has been seen with
219, but the problem should be general

### In case of bug report: Unexpected behaviour you saw
With some HW systemd generates a really long device unit name, that hits fs limits:

Aug 27 13:57:31 p9n02 systemd[1]: Failed to open directory /etc/systemd/system/sys-devices-pci0001:00-0001:00:00.0-0001:01:00.0-0001:02:01.0-0001:03:00.0-host1-port\x2d1:0-expander\x2d1:0-port\x2d1:0:10-expander\x2d1:1-port\x2d1:1:3-expander\x2d1:4-port\x2d1:4:10-end_device\x2d1:4:10-target1:0:71-1:0:71:0-block-sdcm-sdcm1.device.wants: File name too long

**Comment by poettering** [comment]
urks. Not sure what we can do about that... what a mess

**Comment by lnykryn** [comment]
Yep :-/ The only idea I had so far is to decrease a log level in this case. Our original bug report was just about weird error messages in journal. And if user wants to put there some dependencies for device they should use some shorter name of a unit from the following set.

**Comment by dougmill-ibm** [comment]
Note, the device paths should not be hitting any OS limits, if they were being properly decoded. Note that the "\x2d" is an encoded slash character. If you convert those to slashes you get a valid path. Otherwise, that last component of that path exceeds NAME_MAX, in addition to being just plain wrong. I believe that either the OS should be decoding these strings before trying to use them as paths, or else they should not be getting encoded in the first place.

**Comment by dougmill-ibm** [comment]
So, if this is actually something systemd is doing to "flatten" a sysfs path into a filename, that design is obviously flawed.

I guess I don't know where this string originates. If it comes from the hardware then this is a bug in the vendor's firmware. But if it is being generated by systemd then it is a bug in systemd.

**Comment by dougmill-ibm** [comment]
Sorry for the thrashing, but I think I understand this string now. The "filename" is actually a flattened sysfs path, but not as I previously thought. The bare dash characters are actually encoded slashes, while the "\x2d" are original dashes prior to encoding the slashes. So, a "sed" command to translate would be:
```
        sed -e 's;-;/;g' -e 's;\\x2d;-;g'
```
This string must originate in the OS, as it contains references that only the OS knows. It also matches valid sysfs paths. This does not seem to be a problem with device firmware. It is still not clear to me how systemd got this string, but it seems apparent that something (if not systemd) is trying to use a sysfs path as a filename, which as previously asserted is not going to work.

**Comment by arvidjaar** [comment]
> It is still not clear to me how systemd got this string

`man systemd.unit` and search for "escape".

**Comment by dougmill-ibm** [comment]
@arvidjaar I do understand the mechanics of how this string was created. The problem is that the design of using a path as a filename, without checking its length, is flawed and is what is causing the problem. I am unfamiliar with the internals of systemd and so haven't even located the higher level code responsible for this. If the reason the encoding of the path is done is so that software can subsequently decode and recover the original path, then a more complicated solution is required. But the fundamental design is wrong, as a path length can easily exceed the system limit for a filename length.

**Comment by keszybz** [comment]
I think we should just hash the name if it is above the length limit:
`sys-devices-pci0001:00-0001:00:00.0-0001:01:00.0-0001:02:01.0-0001:03:00.0-host1-port\x2d1:0-expander\x2d1:0-port\x2d1:0:10-expander\x2d1:1-port\x2d1:1:3-expander\x2d1:4-port\x2d1:4:10-end_device\x2d1:4:10-target1:0:71-1:0:71:0-block-sdcm-sdcm1.device.wants` → `ea01668388affa88ef1c981acfd94d00d249ad83d5c0a98e355a06bdabf48483.device.wants`

This replacement would be triggered when the length of the filename is longer than some fixed value (255 characters probably).

**Comment by poettering** [comment]
Well. So far the scheme is reversible and the various specifiers we define (such as %f) rely on that...

**Comment by mbiebl** [comment]
You could store the original path in the device unit itself?

**Comment by keszybz** [comment]
After a quick discussion with @poettering  and @lnykryn and @msekletar in person, my understanding is:

* the error is "caused" by systemd itself, because systemd checks for the presence of .wants and .d directories for all units, and in this case such a directory does not exist and could not exist. 
* the error should be downgraded (actually even log_debug is unecessary, and `ENAMETOOLONG` should be treated the same as `ENOENT`).
* my solution with hashing the *file* name (the unit would still retrain the original name) is workable, but not necessary at this time. If anyone ever wants to create .wants directories for units with such long names, we can revisit this.

**Comment by dougmill-ibm** [comment]
The proposed solution sounds good for our customers. I'm not aware of anyone needing these ".wants" directories. The log messages are a problem, though, so is there a fix for that coming soon?

**Comment by dougmill-ibm** [comment]
I'm not convinced that the commit from #7525 actually fixes the problem I've been seeing. Looking at the commit, it will eliminate a "Failed to canonicalize path" message but this issue was opened for "Failed to open directory" messages. Are there more places that require the same code change?

**Comment by keszybz** [comment]
Please test and report back ;)
