### ISSUE TITLE
cgroup/scope: pids are moved away from our watch when using PAM

### ISSUE THREAD

**Issue by joukewitteveen** [systemd/systemd#6875]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> With `PAMName=login`, a new scope is created after the initial cgroup creation. When the processes of the cgroup are migrated to the new scope, any watch we have on the old cgoup should be migrated too.

### In case of bug report: Unexpected behaviour you saw

> The watch is left untouched and fires an undesirable cgroup_empty event after the processes have been migrated. The new cgroup is not monitored and relevant cgroup_empty events will not be triggered on the unit to which the processes belonged.

### In case of bug report: Steps to reproduce the problem

> As in #6045.

### Analysis

> In `scope_start` we [call](https://github.com/systemd/systemd/blob/v234/src/core/scope.c#L338) `unit_attach_pids_to_cgroup`, which in turn [calls](https://github.com/systemd/systemd/blob/v234/src/core/cgroup.c#L1364) `cg_attach_many_everywhere`. These functions are not used anywhere else. Their semantics is incomplete as they do not take care of the watch present on the cgroup they move processes out of.

**Comment by poettering** [comment]
Hmm, so this is a misunderstanding. It's actually supposed to be OK if the main or control processes of a service are not a member of the cgroup of the service (which happens when they migrate to a different scope, for example due to a PAM sessin). systemd is generally able to handle that. A process may thus be associated with two cgroups at the same time, except that that has been broken for the cgroup empty event a while back. (or to turn this around, the set of processes that define the lifetime of a service are all processes of the cgroup, plus the main and control pids, should they be outside of that).

#6932 should fix the handling of cgroup empty in this regard. 

Closing this issue hence.
