### ISSUE TITLE
systemctl status thinks boot time is in the future

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#708]
Version: 222
I'm using LOCAL time (via /etc/adjtime) and my timezone is CEST (Europe/Berlin)
Running systemctl status, I get

```
$ systemctl status
● pluto
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Fr 2015-07-24 14:07:41 CEST; 1h 7min left
```

systemd thinks my boot time is 2 hours in the future.
journal entries show the correct date.

**Comment by poettering** [comment]
Well, that's what you get if you run things in LOCAL time: during early boot the wallclock will be off.

LOCAL is inherently broken, that's why you get a warning about it if you turn it on with "timedatectl".

**Comment by dvdhrm** [comment]
I don't think patching timestamps late is a good idea, so this will probably never be supported. I doubt anyone here wants to spend time on fixing UI bugs for local-time, so I'll close this now. Feel free to re-open, if you have comments on this.

**Comment by mbiebl** [comment]
I think, dual boot systems are still a very common setup, so dealing with that more nicely sounds worthwile.

**Comment by poettering** [comment]
@mbiebl we cannot really support that, it's a really really broken concept. Windows doesn't tell us whether they changed the clock after a summer time change, and hence we can never support co-booting with windows in this mode without completely corrupting the time every now and then.

So, we support local-in-RTC only to the absolute minimum, and make no guarantees about it correctly working in the general case, and hence warn about it.

Instead of trying to fix Linux there, fix Windows instead, and just teach Windows the UTC-RTC thing (which is not that difficult, just set a registry key and you are done).

**Comment by mbiebl** [comment]
UTC support for windows was still incomplete last time I tried  it. I ran into all sorts of weird issues, so I switched back to local time.
