### ISSUE TITLE
/proc/cmdline handling should accept \n as whitespace separator

### ISSUE THREAD

**Issue by uzytkownik** [systemd/systemd#7097]
### Submission type

Bug report

### systemd version the issue has been seen with

233-235

### Used distribution

Gentoo

### In case of bug report: Expected behaviour you didn't see

System boots

### In case of bug report: Unexpected behaviour you saw

System time outs on `dev-gpt\x2dauto\x2droot.device`

### In case of bug report: Steps to reproduce the problem

1. Compile kernel and create dracut initramfs
2. Compile both using code below
3. Boot the system

```
objcopy \
    --add-section .osrel=/etc/os-release --change-section-vma .osrel=0x20000 \
    --add-section .cmdline="$(dirname $0)"/cmdline.txt --change-section-vma .cmdline=0x30000 \
    --add-section .linux=arch/x86/boot/bzImage --change-section-vma .linux=0x40000 \
    --add-section .initrd=/boot/$MACHINEID/$KERNELVERSION/initramfs.img --change-section-vma .initrd=0x3000000 \
    /etc/secureboot/linuxx64.efi.stub /boot/$MACHINEID/$KERNELVERSION.efi
```

The system boots but for some reason it requires dev-gpt\x2dauto\x2droot.device:

```
+ cat /proc/cmdline
rd.luks.uuid=luks-<LUKSUUID>
rd.luks.allow-discards=luks-<LUKSUUID>
rd.lvm.lv=<VG>/root
rd.lvm.lv=<VG>/swap
root=/dev/mapper/<VG>-root
rootfstype=btrfs
rootflags=rw,thread_pool=8,relatime,compress=lzo,ssd,space_cache,subvol=/<SUBVOL>,autodefrag
init=/usr/lib/systemd/systemd
rd.shell
(...)
[   17.093586] localhost systemd[1]: Reached target Basic System.
[   17.645017] localhost dracut-initqueue[2090]: Scanning devices dm-0  for LVM logical volumes <VG>/root <VG>/swap
[   17.661488] localhost dracut-initqueue[2090]: inactive '/dev/<VG>/<UNRELATED>' [350.00 GiB] inherit
[   17.661619] localhost dracut-initqueue[2090]: inactive '/dev/<VG>/swap' [64.00 GiB] inherit
[   17.661684] localhost dracut-initqueue[2090]: inactive '/dev/<VG>/root' [400.00 GiB] inherit
[   17.694181] localhost kernel: BTRFS: device fsid <FSID> devid 1 transid 83930 /dev/dm-1
[   17.696311] localhost systemd[1]: Found device /dev/mapper/<VG>-root.
[   17.732590] localhost kernel: dracut-initqueu (2090) used greatest stack depth: 10280 bytes left
[   17.729054] localhost systemd[1]: Started dracut initqueue hook.
[   17.729334] localhost systemd[1]: Reached target Remote File Systems (Pre).
[   17.729384] localhost systemd[1]: Reached target Remote File Systems.
[   94.214959] localhost systemd[1]: dev-gpt\x2dauto\x2droot.device: Job dev-gpt\x2dauto\x2droot.device/start timed out.
[   94.215553] localhost systemd[1]: Timed out waiting for device dev-gpt\x2dauto\x2droot.device.
[   94.215634] localhost systemd[1]: Dependency failed for Initrd Root Device.
```

I cannot reproduce it when initramfs is loaded by systemd-boot as opposed to compiled-in.

**Comment by poettering** [comment]
did i get this right? this is a luks encrypted root disk?

**Comment by poettering** [comment]
So, normally systemd-gpt-generator's root partition logic becomes a NOP as soon as root= is specified on the kernel cmdline (unless it is set to root=gpt-auto), because it's not necessary then.

I am puzzled why this doesn't work for you... any chance you boot with dracut, break in the initrd, and then invoke "mkdir -p /tmp/xyz && SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/system-generators/systemd-gpt-auto-generator /tmp/xyz /tmp/xyz /tmp/xyz".

Then, please paste here the precise stderr output this generates as well as which files it dropped in /tmp/xyz with what context.

**Comment by uzytkownik** [comment]
Are you sure you got the variable right? It output only:

```
Found container virtualization none.
Adding /sysroot: /dev/gpt-auto-root n/a
Creating /tmp/xyz/systemd-fsck-root.service
```

What's interesting I was unable to mount neither my / nor any other BTRFS filesystem with error 'missing codepage' or something similar. However btrfs is not even compiled as module so something inside linuxx64.efi.stub is preventing mounting /. 

> did i get this right? this is a luks encrypted root disk?

yes

**Comment by poettering** [comment]
> Adding /sysroot: /dev/gpt-auto-root n/a

So, the gpt-auto-root logic is enabled here in this run, even though your /proc/cmdline contains root=. I am very much surprised by this. If I look at the code, I don't see how we would ever enable the GPT root logic if root= is set. 

What's the precise contents of your /proc/cmdline when you call this? THe dump above suggests there are newlines between the words, that's not true though, is it?

This is systemd 235?

The only explanation I have is that there's something wrong with proc_cmdline_parse(). In order to figure that out, any chance you can run the generator like this within gdb? Then set a breakpoint onto  parse_proc_cmdline_item(), and check for which parameters it is invoked, and specifically what happens when it is invoked for the "root" parameter.

**Comment by uzytkownik** [comment]
> What's the precise contents of your /proc/cmdline when you call this? THe dump above suggests there are newlines between the words, that's not true though, is it?

The file contains newlines, yes. I'll check /proc/cmdline soon.

> This is systemd 235?

Yes

> The only explanation I have is that there's something wrong with proc_cmdline_parse(). In order to figure that out, any chance you can run the generator like this within gdb? Then set a breakpoint onto parse_proc_cmdline_item(), and check for which parameters it is invoked, and specifically what happens when it is invoked for the "root" parameter.

That might be problematic. I don't have gdb in my initrd and it might take some time for me to figure out how to do it. Is there a way to force reading something else than /proc/cmdline to attempt repro this problem.

**Comment by uzytkownik** [comment]
Yes, it looks like systemd generator does not handle newlines in `/proc/cmdline` even though kernel/linuxx64.efi.stub does support them.

**Comment by poettering** [comment]
uh. So what's the precise byte-wise contents of /proc/cmdline for you? i.e. hexdump -C /proc/cmdline

**Comment by uzytkownik** [comment]
Sorry - I had troubles getting the data out. The parameters are separated by either '\n' or ' '. So for example <param1>\n<param2>.

**Comment by nos1609** [comment]
Having the same issue on archlinux. The cmdline is inside the unified .efi file, but it is not passed to the kernel. Once booted, the only things I see is the message in the OP and nothing inside /proc/cmdline. Since my machine is Dell, which neglects any cmdline options passed through UEFI itself, the only solution for me was https://github.com/xdbob/sbtools but I can't get through the error still. My systemd version is 238.76

**Comment by vvl-rulez** [comment]
Have same issue on archlinux - but I'm using mkinitcpio-systemd-tool with it's own fstab and dont send kernel parameters.
https://github.com/random-archer/mkinitcpio-systemd-tool/issues/2

**Comment by larrabee** [comment]
Im found this code in source of "linuxx64.efi.stub":
https://github.com/systemd/systemd/blob/master/src/boot/efi/stub.c#L65
So, if secure boot is disabled built in cmdline replaced by cmdline passed from bootloader. 
If cmdline passed from bootloader not contain `root=` option systemd waiting for `/dev/gpt-auto-root`.
If you want to use built in cmdline you should enable secure boot.

**Comment by poettering** [comment]
@uzytkownik, is this still a problem? I tried to reproduce the issue here on current systemd, but newlines are handled totally fine these days. I added testcases for this now in #11983.
