### ISSUE TITLE
nspawn: unable to terminate nspawn created scope unit via machinectl terminate

### ISSUE THREAD

**Issue by jscotka** [systemd/systemd#7105]
### Bug report
I have command:
```
sudo systemd-nspawn --machine=contA -D /tmp/dddd1 sleep 100
```

and I'm uanble to stop this scope unit:
```
 machinectl status contA
contA(cec95201ea5c43f78f3ce52dcdc71862)
           Since: Mon 2017-10-16 13:15:16 CEST; 16s ago
          Leader: 25694 (sleep)
         Service: systemd-nspawn; class container
            Root: /tmp/dddd1
              OS: Fedora 26 (Twenty Six)
            Unit: machine-contA.scope
                  └─25694 sleep 100
```

#### Commands
are unable to stop this machine
```
machinectl terminate contA
machinectl terminate --kill-who=all -s9 contA
```

and more strange is that after this terminate after `sleep 100` finishes, it shows this service as `Container contA terminated by signal KILL.`

#### Command what works well immediatelly
```
sudo systemctl kill --kill-who=all -s9 machine-contA.scope
```

**Comment by poettering** [comment]
which systemd version is this?

**Comment by SamyCookie** [comment]
Hi, same issue for me. I am using version 234-3~bpo9+1 in Debian Stretch.

**Comment by poettering** [comment]
Actually, looking at this again: the original command can't shutdown correctly because you are starting /bin/sleep as PID 1, and that binary is not prepared to run as PID 1, it doesn't follow the special protocol PID 1 needs to implement. Specifically it expects to be terminated by SIGTERM, but PID 1 usually use SIGTERM as indication to reexec and require SIGPWR/SIGRTMIN+3 for shutdown instead.

You can have two options now:

1. The correct way: don't run processes that aren't read for it as PID1. Specifically, run them as PID2 and let nspawn handle PID1 for you. Simply extend your cmdline with `-a` for that.

2. Tweak the kill signal to use, by using `--kill-signal=SIGTERM`.

This is documented in systemd-nspawn(1) btw.

Closing hence.
