### ISSUE TITLE
RFE: ReadWrite{Directories,Paths}= should override ProtectHome=yes for child directories of /home

### ISSUE THREAD

**Issue by zackw** [systemd/systemd#7153]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

>     # systemctl --version
>     systemd 232
>     +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Debian 9.1 (stretch)

### Requested feature

When a unit file specifies both ProtectHome=(either 'yes' or 'read-only') and one or more ReadWriteDirectories= or ReadWritePaths= pointing below /home, the ReadWrite directives should win.  For instance,

    ProtectHome=yes
    ReadWriteDirectories=/home/service

should give the service a virtual /home containing only /home/service, but /home/service should be the real directory (in the root filesystem namespace) and it should be writable.

**Comment by zackw** [comment]
(N.B. I can only find references to ReadWritePaths in the manpages, but the unit files shipped with this system seem to be using both ReadWritePaths and ReadWriteDirectories.)

**Comment by poettering** [comment]
Hmm, so this should actually work already:

```
ProtectHome=read-only
ReadWriteDirectories=/home/service
```

But doing the same with `ProtectHome=yes` doesn't work, since in that case /home is entirely empty and hence no mount point exists init we could mount /home/service on...

**Comment by zackw** [comment]
Indeed,

    ProtectHome=read-only
    ReadWriteDirectories=/home/service

works with the service whose data directory I was trying to move onto a larger partition.  Thanks for the suggestion.

I guess with `ProtectHome=yes`, the setup code would need to create a directory to use as a mount point?

**Comment by poettering** [comment]
> I guess with ProtectHome=yes, the setup code would need to create a directory to use as a mount point?

Well, yes. We'd have to mount a tmpfs, to the place, then populate it with the minimal directory structure you need, and then overmount the leaves...

That all said, the current fs namespace logic in systemd actually tries to be smart and does the exact opposite of what you are asking for, and so far we considered that a feature: it will detect when any kind of ReadOnlyPaths= or ReadWritePaths= mount is obstructed by an InaccessiblePaths= further up, and if so, the mounts are suppressed entirely, in an effort to fully minimize the mount table of all services. (and ProtectedHome=yes is more or less mappled internally to InaccessiblePath=/home)

I figure, if we make possible what you are asking for, then we should a new setting GhostPaths= or so, which is similar to InaccessiblePath=, but actually does two things differently: paths marked that way would not be made unreadable via the access mode, and we'd create these inner "skeleton" dirs so that we can mount submounts onto the leaves.

That said, doing this properly isn't entirely trivial, since the access modes/ownership of these "sekeleton" dirs should probably be inherited from the host versions of these dirs, and that makes the code kinda complex and nasty.

**Comment by zackw** [comment]
I was working on similar code for a sandboxing utility a few months ago, so
I’m aware of how nasty it gets and I want to say that there is absolutely
no urgency here.

**Comment by yuwata** [comment]
I've created PR #7908 for this. In the PR, new option `empty` is added to `ProtectHome=`. By combining `ProtectHome=empty` with `Read{Write,Only}Paths=/home/baz`, the home directories excepts /home/baz are hided from the processes invoked by the unit.

**Comment by yuwata** [comment]
Please use `ProtectHome=tmpfs` and `Bind{,ReadOnly}Paths=` as a workaround for this. For example,
```
ProtectHome=tmpfs
BindPaths=/home/service
```
may be sufficient, I think.

**Comment by con-f-use** [comment]
The manpage "SYSTEMD.EXEC(5)" says this:

>        ProtectHome=
>            Takes a boolean argument or the special values "read-only" or "tmpfs". If true, the directories /home, /root and /run/user are made inaccessible and empty for processes invoked by this unit. If set to "read-only", the three
>            directories are made read-only instead. If set to "tmpfs", temporary file systems are mounted on the three directories in read-only mode. The value "tmpfs" is useful to hide home directories not relevant to the processes
>            invoked by the unit, while necessary directories are still visible by combining with BindPaths= or BindReadOnlyPaths=.
> 
>            Setting this to "yes" is mostly equivalent to set the three directories in InaccessiblePaths=. Similarly, "read-only" is mostly equivalent to ReadOnlyPaths=, and "tmpfs" is mostly equivalent to TemporaryFileSystem=.
> 
>            It is recommended to enable this setting for all long-running services (in particular network-facing ones), to ensure they cannot get access to private user data, unless the services actually require access to the user's
>            private data. This setting is implied if DynamicUser= is set. This setting cannot ensure protection in all cases. In general it has the same limitations as ReadOnlyPaths=, see below.

There is no mention of the value `empty` and no mention of `yes` preventing `ReadWritePath` to work. But `ProtectHome=yes` causes `ReadWritePath=/home/something` to be ignored , while it works with `ProtectHome=empty` on my Ubuntu Bionic with Systemd v240. 

Is empty an undocumented alias of `tmpfs`? Should these facts be reflected in the manpages of `ProtectHome` and `ReadWritePath`?

**Comment by keszybz** [comment]
There's no "empty", there's just "tmpfs" and "yes".

https://github.com/systemd/systemd/pull/12364 adds a bit more text to explain this.
