### ISSUE TITLE
Provide resolvconf(8)-compatible interface for systemd-resolved

### ISSUE THREAD

**Issue by zx2c4** [systemd/systemd#7202]
The standard way for various programs to manage DNS in an ad-hoc non-centralized way -- such as when separate programs are not centrally managed, like VPNs -- is `resolvconf(8)`. The best implementation of resolvconf is [openresolv](https://roy.marples.name/projects/openresolv), which provides numerous useful options such as `-x` for exclusive, `-m` for metric, Here's [a man page for it](http://nxmnpg.lemoda.net/8/resolvconf). A resolvconf is available in all distributions, except the RPM ones, and it's in the BSDs too. It appears to be the "de facto" standard for ad-hoc programs contributing to the pool of nameserver knowledge that eventually results in a `resolv.conf`.

systemd-resolved has a dbus API, but no command line interface for accessing it (AFAIK). In the same way that systemd reimplemented shutdown, halt, and so forth, to retain the same well-known interface, but under the hood talk dbus to systemd's pid 1, I'd like to propose that systemd-resolved provides a "resolvconf" -- something with the same options as openresolv, but that translates these to systemd-resolved dbus commands.

This would lead to easy adoption of systemd-resolved, as well as conformity across distributions, whether they're using a Debian resolvconf, an openresolv resolvconf, or a systemd-resolved resolvconf. In Redhat-world, now that NetworkManager has a systemd-resolved plugin, it would also be a simple way for interacting with that too.

Is this idea interesting to the systemd-resolved developers?

**Comment by dkg** [comment]
I like this idea, though i'm not sure that systemd would need to implement the full complement of the resolvconf interface.  At any rate, a simple command-line interface that knows how to speak to systemd-resolved to perform the most common basic operations (adding a resolver, removing a resolver) would be useful.

**Comment by zx2c4** [comment]
On Oct 28, 2017 4:35 PM, "dkg" <notifications@github.com> wrote:
> I like this idea, though i'm not sure that systemd would need to implement
> the full complement of the resolvconf interface. At any rate, a simple
> command-line interface that knows how to speak to systemd-resolved to
> perform the most common basic operations (adding a resolver, removing a
> resolver) would be useful..


It's attitudes like this one that contribute to fragmentation and
abstraction bloat. resolvconf(8) is a de facto standard interface, which
systemd can embrace just like many others it already has, such as halt,
shutdown, fstab, etc.

In any case I'm mostly interested in hearing from systemd devs the
technical concerns (or lack thereof) with this approach. Namely, is the
input format it takes (resolv.conf files, essentially) sufficient an API?

**Comment by yuwata** [comment]
C.f. #7014.

**Comment by yuwata** [comment]
Especially https://github.com/systemd/systemd/pull/7014#discussion_r143653613.

**Comment by poettering** [comment]
hmm, I think this would be OK to have actually, maybe as a multi-call overloading of the existing systemd-resolve tool.

**Comment by poettering** [comment]
so what's precisely the minimal options we'd have to support? I figure only "resolvconf -a IFACE.<protocol>" matters really, the rest can be NOPs, including "resolvconf -d", as we notice on our own when interfaces go away...

**Comment by zx2c4** [comment]
`-m` and `-x` are the biggies.

http://nxmnpg.lemoda.net/8/resolvconf

**Comment by poettering** [comment]
"-m" doesn't really translate. Note sure I fully grok "-x", but it doesn't really translate either...

**Comment by poettering** [comment]
as first step i prepped #7576 now. It doesn't add a compatible interface, but we can add that later building on this new code. Since the semantics don't map 1:1 i'd rather have a native interface first, exposing the right semantics, before we add compat kludges to provide debian/ubunti semantics too

**Comment by zx2c4** [comment]
The `-x` means that the given name server becomes the _exclusive_ one for the machine. This is important if people don't want DNS requests "leaking" through a different nameserver when bringing up VPN devices.

**Comment by tixxdz** [comment]
@poettering FWIW I also think that we should support this.

**Comment by poettering** [comment]
I figure "-x" could be translated to "add '.' to the list of routing domains for the interface". In resolved doing that means that DNS traffic for domains that aren't listed as search/routing domains otherwise is directed to that interface. It wouldn't have quite the same semantics, as a more specific domain-routing rule would still win, but in the big picture the difference shouldn't be too bad...

The "-m" metric stuff doesn't translate at all though: resolved doesn't priorize DNS configuration over each other, it doesn't have to, as it can route traffic to multiple servers on multiple interfaces simultaneously and take the first positive answer (or last negative one). To which interfaces traffic goes is purely decided on search/routing domains, which is a lot more fine-grained and expressive than priority based systems. Most likely we should just ignor the value.

**Comment by zx2c4** [comment]
> Most likely we should just ignor the value.

Perhaps ignore and spit a warning? Or ignore silently like debian's resolvconf does. Your call.

**Comment by bl33pbl0p** [comment]
+1 for this.

**Comment by poettering** [comment]
A PR implementing this is waiting in #8296
