### ISSUE TITLE
some nfs4 mounts fail at boot...

### ISSUE THREAD

**Issue by Brane2** [systemd/systemd#7207]
### Submission type

 - Bug report

### systemd version the issue has been seen with

>systemd-git_repo

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> all mounts succeed

### In case of bug report: Unexpected behaviour you saw
I have  some 15+ nfs4 mounts that have to be automounted at boot and each time some 7-8 of them fail, not always the same ones. It looks like systmed-mountd overwhelms the server with bunch of mount requests and then fails if server can't respond immediately. I tried using more rpc.mountd daemons on the server and that showed some improvement ( 1 or two additional mounts succeed at boot), but problem is stil there.

I can remount all failed mounts after boot without a problem. BTW, all my mounts have mount file in /etc/systemd/system ( they are nto generated from /etc/fstab) if that means something.

Is there a workaround, some option that I can use to retry failed mount after a few seconds ?

my typical mount file looks like this:

`
[Unit]
After=network-online.target
Before=remote-fs.target

[Install]
WantedBy=remote-fs.target

[Mount]
What=192.168.11.x:/MY_MOUNT
Where=/home/MY_MOUNT
Type=nfs4
Options=async,fg,hard,sharecache,sec=sys,intr,nocto,proto=tcp,noexec,rw,intr,ac,_netdev
TimeoutSec=5   `

### In case of bug report: Steps to reproduce the problem

> …

**Comment by poettering** [comment]
Uh, sorry, but we can't really help you with that, it's really something for the NFS community. Please contact them.

The retry thing has been requested before, see #4468, but I am still not convinced this would be good to add to systemd. I am very sure this should be implemented in NFS itself instead.

Sorry. Closing.

**Comment by charles-dyfis-net** [comment]
I don't see how this *could* reasonably be implemented in NFS. If due to a transient failure one can't even get confirmation that the server / remote path / etc. that the user is asking for *exist at all*, how can a `mount.nfs` command (or its equivalent for any other remote filesystem) be acting in good faith by claiming to have succeeded?

For the remote filesystem to report at least some classes of potentially-transient failures as fatal if they happen at mount time strikes me as completely legitimate. For the user to want to be able to automate retry after those failures occur, likewise.
