### ISSUE TITLE
Configuration option to select vt number user is placed

### ISSUE THREAD

**Issue by jeffscode** [systemd/systemd#7247]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235.38-1

### Used distribution

> Arch Linux

### Feature Request

> Add configuration option to select vt number user is placed  at after reboot when not using display manager. 

> ie: After reboot, end up at login on tty1. Would prefer a different tty# without having to Ctrl+Alt+F#.  I had to create a service file in /etc/systemd/system with only one line, chvt#, then enable it to get the  results I request. Would having this configurable in a conf somewhere be a reasonable request?

> If I missed something in the documentation, please point it out. Could not get assistance or info upon request in Arch forums.

**Comment by keszybz** [comment]
You can use a simple service like this:
```ini
# /etc/systemd/system/switch-vt.service
[Unit]
After=getty.target
[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/bin/chvt 5
[Install]
WantedBy=multi-user.target
```

**Comment by jeffscode** [comment]
Thanks for info! Your example is cleaner than mine.

I left out some details. My service file actually calls a bash one-liner with chvt7 in it. It works, as does your example. Problem is using either method,  can no longer scroll boot messaged in tty1 configured for "no clear". 

Would be nice to redirect or actually tee all messages to file. Unfortunately I can only get about half to redirect.

**Comment by sourcejedi** [comment]
`tty1` is the (upstream kernel) default already.  I assume you want a different tty from that.  For some reason.  If you need kernel messages to "redirect" right from the start, you need a [kernel option](https://help.ubuntu.com/community/vt.handoff) which is not available upstream.

If you're interested in system's "status" messages (`[  OK  ] Started GNOME Display Manager.`), Fedora manages to write status messages to /var/log/boot.log.  It's a default feature of `plymouth`.  The log includes some messages from the initrd (but not those before plymouth is started).

The kernel messages are also logged, see `dmesg`.  Or the systemd journal, which also logs service statuses, just with a different message format.

Boot messages don't go to tty1 by default.  They go to tty0 - the current tty at the time.  (Because this is the default target for the [console](https://unix.stackexchange.com/questions/60641/linux-difference-between-dev-console-dev-tty-and-dev-tty0/384792#384792)).  It's just that when you switch consoles all the scrollback history is lost.

If you want userspace to switch VTs early than you've been able to, you need to modify the initramfs.  Which may or may not use systemd.

I've seen this desire before (maybe you asked on unix.stackexchange.com), but it seems fairly obscure to me.  I don't see why systemd would want to include a unit like the above.

If you want to run something different on the default tty, tty1, that should be perfectly possible AFAIK.  You can replace getty.service@tty1... the restriction is you can't necessarily do so by installing package files in /usr; you have to use a mask in /etc.  systemd-logind can't do autovt@ for tty1, and therefore getty.service@tty1 is enabled "statically" in /usr.  But it should work fine if you mask that and run your own thing.  You would `systemctl mask getty@tty1` (which creates a file in /etc).  If it feels like a fragile hack, you can de-configure autovts altogether in `logind.conf` (and enable your desired `getty`s manually).

**Comment by poettering** [comment]
So let me get that right: you want that the kernel's and systemd's boot-time log output go to tty1, but that it isn't visible by default, but instead tty2, where a login prompt eventually is shown?

**Comment by jeffscode** [comment]
I need some time to investigate and absorb what sourcejedi is suggesting. 

To recap what I'm asking for:

1)  A configuration that allows you to select what tty# you're placed at upon reboot. Rather than having to create a service file, and if it's a practical and reasonable feature request.

 I have the system's "status" messages ([ OK ] Started GNOME Display Manager.), set up for "no clear" in tty1, which allows scroll back to the beginning of the messages. One could use journalctl with various filters to get the same info, but my thoughts are the status messages are already filtered and a good place to start if there is an issue. Might as well use them since they're available.

When I create a service file to get the behaviour requested in 1),  I am placed at tty7 upon reboot. If I switch to tty1 to scroll the messages prior to login, they will not scroll, because of the new service file. 

2)  If feature request 1 is implemented, would it be possible to implement in such a way to allow scrolling of "status" messages on tty1 prior to login.

How this is all accomplished "behind the scene" is beyond my current knowledge. Appreciate the feedback.

**Comment by poettering** [comment]
I am sorry, but the kernel implements the virtual console, and is the one flushing out the scrollback when you switch VTs. We can't really do anything about this. If you want this, please talk to the kernel people.

Sorry! But this is nothing systemd can do anything about. Sorry!

**Comment by jeffscode** [comment]
Appreciate you taking time to look into this Lennart. So the second part of my request is not doable and I get it. I ended up installing plymouth for this, only for the logging function as I don't want login to graphical environment. I plan on looking into the possible using the logging part of the code as stand alone.

Would it still be reasonable to ask for the first part, select a tty <n> to be implemented in a configuration within systemd? Have an editable configuration placed somewhere to just change a number?

This does not seem like a reasonable kernel issue, to supply a user config for tty <n>. I did try to append the kernel line in the boot loader with tty<n>, and it didn't work.  I then created a service file calling a one line bash script with chvt <n>. Then I learned I could implement the command without calling the bash script, ie: ExecStart=/bin/chvt 7. That method still required creating a new service file. From a non programmer Linux users perspective, figuring out how to accomplish this was not trivial, even though the unit files are said to be in a very simple declarative format. As a Linux user, I'm quite comfortable with shell scripting. Perhaps in time I'll "get" systemd.  I'm sharing this as perhaps "a majority" of Linux users today. 

With all that said, thanks either way!

**Comment by poettering** [comment]
hmm, i am not sure we really should add config settings for really every possible option in the world... If we add something it needs a strong and common usecase, and the next best replacement needs to be substantially more complex or impossible to implement. I am not sure this qualifies so far.

I mean, invoking chvt as a service as suggested by @keszybz should already do what you are asking for, right? What's missing there? Moreover, what's actually wrong with using tty1 for logins? If all you want is route boot-time logs to a different place than tty1, then console=tty2 or so should already work, no?

**Comment by jeffscode** [comment]
QUOTE: "I mean, invoking chvt as a service as suggested by @keszybz should already do what you are asking for, right? What's missing there? Moreover, what's actually wrong with using tty1 for logins?"

You make a good point with this and not being to accommodate every ones personal (possibly obscure) config requests ... It does work well, and there is also nothing wrong with logging into tty1 .... except a personal habit when it comes right down to it. 

Thanks for your time.

**Comment by leifliddy** [comment]
> You can use a simple service like this:
> 
> ```ini
> # /etc/systemd/system/switch-vt.service
> [Unit]
> After=getty.target
> [Service]
> Type=oneshot
> RemainAfterExit=true
> ExecStart=/bin/chvt 5
> [Install]
> WantedBy=multi-user.target
> ```

Thank for this, you seriously helped me me out more then you know. I needed to modify this just a bit, mainly just changing the Type to ```Type=idle``` but, yeah it works perfect for my slightly bizarre use-case scenario.

**Comment by keszybz** [comment]
I updated my example to use "idle".
