### ISSUE TITLE
systemctl daemon-reload needed when modifying fstab

### ISSUE THREAD

**Issue by bigon** [systemd/systemd#7291]
Hi,

Read on twitter (and actually it bit me once as well) somebody complaining about the fact that `systemctl daemon-reload` must be issued when modifying the `/etc/fstab`

Shoudln't this be automatic if starting a .mount service is requested? Should a inotify watch be added to `/etc/fstab`?

Calling `systemctl daemon-reload` is quite unexpected requirement and breaks "the good old workflow"

**Comment by poettering** [comment]
Sorry, but automatically reloading systemd configuration on config file changes is nothing we will add. It's necessarily, racy as we never know when changes in /etc/fstab are complete, and we might end up reloading during a change, and then load incomplete or duplicate configuration, and that's definitely not desirable.

This has come up every now and then, but I am very sure we should not change the behaviour here, as it would be racy. Moreover, the raw util-linux commands still honour /etc/fstab directly, hence this isn't actually really a change in behaviour: if you stick to the old commands everything behaves as it always did. It's only that systemd's own logic regarding this will not take notice of any config file changes until you tell it so...

THis has been documented for quite some time on the incompatibilities list btw:

https://www.freedesktop.org/wiki/Software/systemd/Incompatibilities/

See the second to last item there. 

Sorry if this is disappointing.

**Comment by mzealey** [comment]
This is actually very dangerous. For most other systemd integrations you explicitly know you are dealing with systemd and it will prompt you to daemon-reload if it looks like something changed. For fstab most sysadmin wouldn't expect this. Here's why this is very dangerous: We performed a data migration from one set of disks to another, updated fstab with the new UUIDs and remounted. We then hot-removed the old disks and suddenly systemd started unmounting the new mounts, even though they have not been removed. All attempts at running a `mount` again succeeded fine but didn't mount as systemd was immediately unmounting them because the other device had been removed. This was on centos 8.1 and is very bad and dangerous behaviour.

**Comment by reidliu41** [comment]
hi, @mzealey. I am curious about your migration, but not very clearly. You mean automatically run "daemon-reload" is dangerous or run daemon-reload is dangerous?

**Comment by mzealey** [comment]
NOT automatically running reload in this case was very dangerous.

**Comment by reidliu41** [comment]
@mzealey thank you for your confirmation

**Comment by okay456okay** [comment]
I did the same operations and experienced the same issue as you, @mzealey . I don't know the systemctl daemon-reload operation, then production accident happened, it's making a disaster.
