### ISSUE TITLE
More colorful journal

### ISSUE THREAD

**Issue by davispuh** [systemd/systemd#736]
Currently journal isn't really colorful.

Compare `dmesg` which is very pretty (so same style for journal would be nice)
![dmesg screenshot](http://i.imgur.com/Yq3v0HR.png)

with `journalctl`
![journal screenshot](http://i.imgur.com/jjpMvjB.png)

**Comment by poettering** [comment]
Well, I like my bikeshed green.

We tried to find a middle ground between too colourful and colourful enough to be useful. Thus we only used two colors where the meaning is relatively clear to the uninitiated: hightlight → means important; red → means error or worse.

Or to turn this around: in the dmesg tool the colours green and brown/yellow I think are not too useful, since their meaning is not intentionally clear (time is green? process names brown???) Also, they emphasize stuff that shouldn't be emphasized, as the time is certainly usually the least relevant contents of the line.

Hence, I strongly disagree with making this more colorful, in fact dmesg should probably reduce the number of colors it uses, too.

Sorry.

**Comment by davispuh** [comment]
It's very subjective thing so I think if it would be configurable in `journald.conf` then everyone could use however they like :)

**Comment by poettering** [comment]
First of all journald.conf configures the daemon (hence the "d" in the filename), not the client.

But more importantly: options come at a cost. Unix systems are complicated enough, but just adding any option we can think of and making everything configurable makes things just worse. To me this issue is a clear case where configurability is unnecessary and ultimately just harmful because complicates things for little gain and confuses the users, just to accomodate for a tiny minority.

Sorry!
