### ISSUE TITLE
[networkctl] networkctl status should link to the IP of the container in context to the host

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#7418]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

systemd 235
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

Arch Linux

### Feature Request

At the moment networkctl provides an IP address of the container that is wrong in the context of the host. Example:

`host` describes the host that manages the containers
`container` describes the container

`root@host# networkctl status ve-container`
```
[..]
         Address: 10.0.0.17
                  169.254.162.216
                  fe80::b84a:79ff:fe41:5892
[..]
```
```


The given address is not the IP of the container in context to the host. You can't ssh into that address from the host, for example. But `machinectl status container` provides the right address:
[..]
         Address: 10.0.0.25
                  169.254.234.124
                  fe80::acdc:39ff:fec9:b8d6%5
[..]
```

It would be nice to have this information of machinectl status in networkctl status for the container. The addresses are not consistent at the moment and confuses more as it helps.

EDIT: I thought machinectl does it wrong, but seems like networkctl does it wrong and machinectl does it right.

**Comment by poettering** [comment]
hmm, wut? "networkctl status" shows the *host* side of the virtual network tunnel, i.e. the IP the host uses as *source IP address* when communicating with the container. "machinectl status" shows the *container* side of the virtual network tunnel, i.e. the IP the host uses as *destination IP address* when communicating with it.

Hence, all looks completely the way it should, and yes, of course if you use *any* of the IP addresses "networkctl status" shows, you'll end up on the local host, not on the containers. That's expected of course, since those are *host* IP addresses.

**Comment by shibumi** [comment]
@poettering thanks for the clarification.
