### ISSUE TITLE
Container uptime == host uptime

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#753]
Running `uptime` inside a `systemd-nspawn` container shows the uptime of the host system.

`uptime` determines the system's uptime based on the data from `/proc/uptime`, e.g.:

```
# cat /proc/uptime && uptime 
747966.78 1121328.70
 08:32:02 up 8 days, 15:46, 10 users,  load average: 0.98, 1.34, 2.45
```

I'm not sure whether `/proc/uptime` inside a container could be provided by `systemd-nspawn` instead.
If that's not possible in a reasonable way, it should probably be documented at least in the `systemd-nspawn` docs.

**Comment by richardmaw-codethink** [comment]
uptime is not namespaceable, but you might be able to fake it like systemd-nspawn does for `/proc/kmsg`.

The following script intercepts `/proc/uptime` with a fifo (since a Unix socket can't just be opened) and provides the actual system uptime, which implies the fifo approach at least isn't a dead-end.

``` python
#!/usr/bin/python


import contextlib
import os
import select
import shutil
import subprocess
import tempfile


@contextlib.contextmanager
def bind(src, dest):
    subprocess.check_call(['mount', '--bind', src, dest])
    try:
        yield
    finally:
        subprocess.check_call(['umount', dest])


td = tempfile.mkdtemp()
try:
    fake_uptime_dest = os.path.join(td, 'fake')
    real_uptime_dest = os.path.join(td, 'real')
    with open(real_uptime_dest, 'w'):
        pass

    with bind('/proc/uptime', real_uptime_dest):
        os.mkfifo(fake_uptime_dest, 0444)

        with bind(fake_uptime_dest, '/proc/uptime'):
            while True:
                fd = os.open(fake_uptime_dest, os.O_WRONLY)
                f = os.fdopen(fd, 'w')
                with open(real_uptime_dest, 'r') as uptime_f:
                    shutil.copyfileobj(uptime_f, f)
finally:
    shutil.rmtree(td)
```

To do this for `systemd-nspawn` we'd have to fork off a similar process (or spawn a thread, since AFAICT you can't select on the read-end being opened) which fills in suitable dummy data, possibly from the uptime of the nspawn process.

**Comment by poettering** [comment]
We cannot really fix this in userspace without kernel support, as the uptime is exported as kernel API via /proc and clock_gettime(). Please file an RFE against the kernel asking for uptime virtualization for containers.

Sorry.

**Comment by eliasp** [comment]
It look like there are a few things happening which might finally make this possible: https://lwn.net/Articles/765835/
