### ISSUE TITLE
when receiving overly long DHCP fqdns for the local system, truncate at first dot, to make them single label, until they fit in the Linux hostname length limit

### ISSUE THREAD

**Issue by drcrallen** [systemd/systemd#7563]
### Submission type

 - Bug report

### systemd version the issue has been seen with

```
$ sudo init --version
systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN default-hierarchy=legacy
```

### Used distribution

> Container Linux (CoreOS) 1520.8.0

More information at https://github.com/coreos/bugs/issues/2273

### In case of bug report: Expected behaviour you didn't see

systemd networkd fails to set hostname on GCE instances with sufficiently long instance name, leaving hostname as `localhost`

### In case of bug report: Steps to reproduce the problem

1. Launch container linux instance in GCE with a "long" instance name and / or instance group name, causing the FQDN to exceed 64 bytes.
1. Look at the journalctl -b logs for a hostname setting error
1. Notice that the hostname is set to localhost and not the instance name.

COS (Google's internal one powering GKE) seems to set it correctly, even if the instance name is long.

**Comment by poettering** [comment]
well, the linux kernel only allows a maximum host name length of 64 chars. So what do you think we should do in that case?

try this in your shell:
```
$ getconf HOST_NAME_MAX
64
```

**Comment by bgilbert** [comment]
GCE limits the instance name to 63 characters, but sets the DHCP Host Name option to the machine's FQDN, as allowed by RFC 2132.  It seems that COS uses only the hostname part.

**Comment by poettering** [comment]
so you are suggesting if the fqdn passed through dhcp is too long for linux we truncate it at the first dot, instead of falling back to "localhost"? such a strategy probably makes sense.

**Comment by lucab** [comment]
@poettering in order to make this more consistent (i.e. avoid different behaviors on `node1` vs. `node01`), can we try to always truncate the hostname when a FQDN is passed through DHCP?

**Comment by poettering** [comment]
uh, that's a hot issue... there are conflicting philosophies there. some people think that fqdns as hostnames are the best thing since sliced bread, I am mostly convinced that it's a bad idea (already because the Linux definition of a valid hostname differs from the DNS definition of a valid fqdn in regards to max length and stuff), but I'll bet you if we'd systematically shorten fqdns there to single labels, then somebody will file an issue the next week complaining. I think using the passed name as is if possible and logging and truncating to the first label if not is the way to go, simply to avoid such a discussion... that way the dhcp server can pick the name and we basically outsource the problem to users...
