### ISSUE TITLE
Retrieve remote ip (and port) on udp socket activation

### ISSUE THREAD

**Issue by lal12** [systemd/systemd#7584]
I want to enable a self written service with systemd socket activation, which should answer with an UDP Unicast to the sender of the activating packet.
Maybe I just overlooked something, but it seems, that the REMOTE address is only passed for TCP Sockets and not for udp sockets?

If I am right and there is no such way, then I would recommend to use the xinetd compatible way by passing the source addr as an env variable.

**Comment by poettering** [comment]
well, socket activation for UDP means you get the original listening socket on activation where the incoming datagrams are readable from. But each datagram might come from a different source, hence setting en env var in that case doesn't really make sense, since it might apply to the first message, but most likely not for any subsequent datagrams...

TCP is different: if you set Accept=yes there, it's the connection socket that is passed to the activated program, and on that one it's only one peer you are talking to hence it makes sense to set those env vars...

Sorry.

**Comment by lal12** [comment]
Ah ok, I didn't know, that all the datagrams are redirected on the same handle. I assumed that for every datagram a new instance is spawned. Therefore I see your point, but still by means of inetd compatibility such a feature would be nice.

**Comment by poettering** [comment]
hmm, are you suggesting inetd was doing that?

**Comment by lal12** [comment]
I just tried it with xinetd:
```
service test
{
        disable         = no
        type            = UNLISTED
        socket_type     = dgram
        protocol        = udp
        user            = root
        wait            = yes
        port            = 8888
        server          = /bin/bash
        server_args     = /root/test.sh
}
```
passes `$REMOTE_HOST`, it does not seem to pass the remote port, maybe this depends on configuration, but I guess if you pass the REMOTE_IP, why not also the REMOTE_PORT.

**Comment by poettering** [comment]
But to what is $REMOTE_HOST set in that case? to the sender of the first datagram in the queue? but the datagram remains in the queue?

quite frankly such behaviour sounds really strange to me...
