### ISSUE TITLE
Service fails due to existing StateDirectory 

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#7605]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v235-909-g5e8727704

### Used distribution

Fedora 27

### Bug report

After installing this version of systemd on Fedora, I noticed a service fails:

```
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-12-11 10:02:21 GMT; 17min ago
     Docs: man:systemd-timesyncd.service(8)
  Process: 569 ExecStart=/usr/lib/systemd/systemd-timesyncd (code=exited, status=238/STATE_DIRECTORY)
 Main PID: 569 (code=exited, status=238/STATE_DIRECTORY)

Dec 11 10:02:21 fedora27-vm systemd[1]: systemd-timesyncd.service: Service has no hold-off time, scheduling restart.
Dec 11 10:02:21 fedora27-vm systemd[1]: systemd-timesyncd.service: Scheduled restart job, restart counter is at 5.
Dec 11 10:02:21 fedora27-vm systemd[1]: Stopped Network Time Synchronization.
Dec 11 10:02:21 fedora27-vm systemd[1]: systemd-timesyncd.service: Start request repeated too quickly.
Dec 11 10:02:21 fedora27-vm systemd[1]: systemd-timesyncd.service: Failed with result 'exit-code'.
Dec 11 10:02:21 fedora27-vm systemd[1]: Failed to start Network Time Synchronization.
```

Sadly the actual error message is not included above.  Here it is.

```
Mon 2017-12-11 10:02:21.888592 GMT [s=c457950558794b8cac7ab77d1cde480b;i=412;b=9fc19835bc9a4ed1993467901ac5ae49;m=12af143;t=5600da161145b;x=32f408f5423a1ce9]
    _MACHINE_ID=ec36f0d290614a989246ce31e09df42e
    _HOSTNAME=fedora27-vm
    SYSLOG_FACILITY=3
    _UID=0
    _GID=0
    _SYSTEMD_SLICE=system.slice
    _SELINUX_CONTEXT=system_u:system_r:init_t:s0
    PRIORITY=3
    SYSLOG_IDENTIFIER=systemd
    _TRANSPORT=journal
    _EXE=/usr/lib/systemd/systemd
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9fc19835bc9a4ed1993467901ac5ae49
    UNIT=systemd-timesyncd.service
    _COMM=(imesyncd)
    _CMDLINE=(imesyncd)
    CODE_FILE=../src/core/execute.c
    ERRNO=17
    _SYSTEMD_CGROUP=/system.slice/systemd-timesyncd.service
    _SYSTEMD_UNIT=systemd-timesyncd.service
    CODE_LINE=3553
    CODE_FUNC=exec_spawn
    MESSAGE_ID=641257651c1b4ec9a8624d7a40a9e1e7
```

```
    MESSAGE=systemd-timesyncd.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-timesyncd: File exists
```

```
    EXECUTABLE=/usr/lib/systemd/systemd-timesyncd
    INVOCATION_ID=f024c829f6cd4b869b1be2ba132dd39d
    _PID=563
    _SYSTEMD_INVOCATION_ID=f024c829f6cd4b869b1be2ba132dd39d
    _SOURCE_REALTIME_TIMESTAMP=1512986541888592
```

This is strange because a state directory is by definition expected to exist already.  (Also see the [blog on this feature](http://0pointer.net/blog/dynamic-users-with-systemd.html)).  However it looks as if the code did not anticipate this.

https://github.com/systemd/systemd/blob/5e8727704/src/core/execute.c#L2030

**Comment by poettering** [comment]
Hmm, so your build already includes 949befd3f09e8c06a908ec99efd241666c21d944, right? that'd be my first guess

**Comment by poettering** [comment]
Note that mkdir_parents_label() and mkdir_safe_label() are both OK with the relavant dirs already existing...

Does /var/lib/systemd/timesync already exist for you? if so, is it a directory, or is it a symlink? Does /var/lib/private/systemd/timesync exist?

Any chance you can do "strace -f -s500 -p 1" right before doing "systemctl start systemd-timesync.service" when it fails. Than exit strace, and paste the output it generated here? in particular the output of the forked off child, so that we can see which EEXIST is actually returned for you, and what systemd sees is already in place when it goes through this.

**Comment by sourcejedi** [comment]
`/var/lib/systemd/timesync` exists.  It is a directory.  `/var/lib/private/systemd/timesync` also exists as a directory.

So if I try to start it and grab the strace, the fatal EEXIST is when it tries to create the symlink.  https://gist.github.com/sourcejedi/9df963e59f197a8983ddb3aec99a622c

I can't see any difference between the journal logs for the first failure of systemd-timesyncd, and the subsequent retries.

**Comment by sourcejedi** [comment]
I have likely run a pre-949befd systemd on this VM for a bit.  I had run a git bisect, so you can imagine a bit of back-and-forth going on.

The private one seems to be empty, while the non-private one is not.  Dunno whether sprinkling some `rmdir` calls would make this more robust, when people run git bisect or something :).

**Comment by poettering** [comment]
Ah, right, so yeah if you ran a post-v235 snapshot that didn't have the conversion code in place then you'll run into this problem.

I am not sure we should do rmdir() here in this case to cover for cases like this, simply because the dir might have been modified in other ways even though it's empty, and we probably shouldn't drop that (for example, it might have a changed access mode now, or ACLs or whatnot). 

Let's close this given that this is only an issue when upgrading from an unreleased version to a current one...
