### ISSUE TITLE
bootctl: input/output error

### ISSUE THREAD

**Issue by Spindel** [systemd/systemd#7635]
### Submission type  
 - Bug report

### systemd version the issue has been seen with  
systemd-233-7.fc26.x86_64

### Used distribution  
Fedora 26

### In case of bug report: Expected behaviour you didn't see

some status output from bootctl

### In case of bug report: Unexpected behaviour you saw

```
[root@spring default]# bootctl 
Failed to probe partition scheme "/boot/efi": Input/output error

```

### In case of bug report: Steps to reproduce the problem

Run bootctl  on my NAS server.

The machine succesfully boots, and uses EFI.  /boot is a raid1 across multiple devices, with metadata format 1.0, and the machine succesfully boots and handles that. However,  bootctl doesn't.

**Comment by yuwata** [comment]
I am not sure but it seems that we need to add some special care for raid device.

**Comment by poettering** [comment]
This came up recently on the mailing list. See my comments here:

https://lists.freedesktop.org/archives/systemd-devel/2017-December/039970.html

**Comment by poettering** [comment]
Let's close this here. This would have to be fixed in libblkid, not systemd, as that does all partition probing for us. And then there's the question whether doing something like this is actually safe anyway...

Please file a bug against libblkid if you want them to detection partitions properly on md devices too!
