### ISSUE TITLE
kernel keyring support is borked in containers that do not block the relevant syscalls

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#7655]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235-3 Debian sid

### Used distribution

> Debian sid sparc64

### Expected to see

Ignore key error or something? Why does it need it?

### In case of bug report: Unexpected behaviour you saw

```
# journalctl -fu systemd-networkd &
# systemctl start systemd-networkd
Job for systemd-networkd.service failed because the control process exited with error code.
See "systemctl  status systemd-networkd.service" and "journalctl  -xe" for details.

Dec 15 11:08:48 t5240 systemd[1]: systemd-networkd.service: Failed to set invocation ID on control group /system.slice/systemd-networkd.service, ignoring: Operation not permitted
Dec 15 11:08:48 t5240 systemd[1]: Starting Network Service...
Dec 15 11:08:48 t5240 systemd[104]: Failed to attach 104 to compat systemd cgroup /system.slice/systemd-networkd.service: No such file or directory
Dec 15 11:08:48 t5240 systemd[104]: systemd-networkd.service: Failed to change ownership of session keyring: Permission denied
Dec 15 11:08:48 t5240 systemd[104]: systemd-networkd.service: Failed to set up kernel keyring: Permission denied
Dec 15 11:08:48 t5240 systemd[104]: systemd-networkd.service: Failed at step KEYRING spawning /lib/systemd/systemd-networkd: Permission denied
Dec 15 11:08:48 t5240 systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=237/KEYRING
Dec 15 11:08:48 t5240 systemd[1]: systemd-networkd.service: Failed with result 'exit-code'.
```

Starting it from a machinectl shell just works

```
# /lib/systemd/systemd-networkd &
[1] 77
host0: IPv6 successfully disabled
Enumeration completed
host0: Gained carrier
host0: Could not set route: Network is unreachable
```
> …

### In case of bug report: Steps to reproduce the problem

> Merely trying to start systemd-networkd as a system service within an nspawn container.

**Comment by jengelh** [comment]
If and only if {nspawn is started as a service AND networkd-inside is started as a service} does it show. In all other cases (nspawn started from prompt OR networkd-inside started from a prompt), that keyring seems to be set up and networkd can use it.

**Comment by poettering** [comment]
the kernel keyring logic is not properly virtualized for containers, and hence some of the operations PID 1 does on them fail. We do mask out the relevant syscalls in nspawn however with seccomp, due to that, hence normally the container should run just fine, and assume that kernel keyring support is turned off.

My educated guess is that this doesn't work for you however, since libseccomp is not available/doesn't work on sparc64?

Not sure what we can do about it. To make this work correctly in containers the kernel keyring API has to be blocked somehow in containers. This can either be done by making libseccomp work on sparc64 or by maybe changing the debian kernels to disable kernel keyring support on sparc64 altogether until that's fixed?

There's also #7098 which was an attempt on making systemd deal gracefully with kernels where the keyring stuff is borked, and undo any half setup keyring setup if this is recognized. However that PR is stalled. I guess if there's interest, somebody could start resurrecting that though, i.e. implement what is proposed in: https://github.com/systemd/systemd/pull/7098#issuecomment-342542490

Or instead, fix the kernel side properly, to make the keyring stuff compatible with containers

**Comment by jengelh** [comment]
I did get nspawn to work in a subsequent try - all that I changed was adding `--private-users=0` to the configuration.

**Comment by jimisan** [comment]
cry a lot again... subscribed to crooked software of globalization, here's my solution:  `The bug report talks about how to configure the LXD profile to blacklist a sycall. If you were to use the command on a specific container instead, it would be lxc config set myarch security.syscalls.blacklist "keyctl errno 38" and that's it.`
