### ISSUE TITLE
Configuration file X is marked world-inaccessible spam

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#770]
It appears that some files, for some to me unknown reasons, has to be chmod'd to 640 as per Common Criteria (see https://bugzilla.redhat.com/show_bug.cgi?id=1241565). Is this warning really necessary? To me it also (as to the original reporter) seems like a spurious message with no real meaning. Let me know if I should create a PR removing this particular check.

**Comment by poettering** [comment]
We added this in order to make people fix their unit files to have more useful access modes, because wpa supplicant and auditd didn't gat that right. chmodding things to 640 is completely bogus, that secures nothing as the data is queriable anyway via the bus without such restrictions. It's just massively annoying, as it breaks "systemctl cat" and things, creating a false sense of security, where there is no security, in a weird attempt of hiding stuff where there is no point in hiding (everybody can download those files from the fedora repo anyway...).

**Comment by jsynacek** [comment]
Yeah, I thought something along those lines as well. Ok, thanks for the response.

**Comment by parsley42** [comment]
Does this message give a false sense of insecurity? It's a fairly common practice to configure some services w/ e.g. Ansible that have secrets/credentials passed to the daemon as environment variables. In my case, github.com/lnxjedi/ansible-role-gopherbot stores the Slack bot token in GOPHER_SLACK_TOKEN. I was dismayed to see the warning about values being accessible via the API, though super glad that my unprivileged user couldn't fetch it with a simple `systemctl cat gopherbot`. I know very little about DBUS or any APIs for systemd, so wanted to ask - is there some means by which a non-privileged user can access the values provided with `Environment=...` lines?

**Comment by poettering** [comment]
@parsley42 if you have questions do not use the github issue tracker, please. use the mailing list. but yes, there is.
