### ISSUE TITLE
rc.local is starting to early

### ISSUE THREAD

**Issue by DirkSchmitt** [systemd/systemd#7703]
In the *„good old times“* rc.local was defined and guaranteed to run as last init script. This was an oldtime unix behaviour replicated by the linux distributions in the early '90 and haven't changed till systemd .

I'm aware that rc.local is seem for many as a „hack“ and a „real“ startup script/unit should be used instead.
But the rc.local behaviour to run after all the other stuff comes in some use cases very handy.

I was relying on it for:

- send out email with a 'reboot repot'
- check some machine/service properties on reboot 

The current behaviour to run after the *network.target* is reached , this is for some of my requirements is to early.

### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 233
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid

### Used distribution

> ubuntu 16.04

### In case of bug report: Expected behaviour you didn't see

> rc.local shout run as **last** unit

### In case of bug report: Unexpected behaviour you saw

> invocation is controlled by ```After=network.target```

### In case of bug report: Steps to reproduce the problem

> add rc.local and reboot your system

**Comment by floppym** [comment]
systemd doesn't really have any way to ensure that something executes after everything else, without explicitly defining "everything else".

I suppose you could add `After=multi-user.target` to the service file. That doesn't mean it will execute after _everything_, but it would delay it more than `After=network.target`.

**Comment by arvidjaar** [comment]
Then it should be really `default.target`; this still fails if unit name is passed explicitly on startup.

Probably timer event like `OnSystemRunning` would be the best match to old behavior. I actually thought something like this was discussed and implemented, but cannot find it.

**Comment by boucman** [comment]
you could do something like #7023 

not something for mainline, but it could solve your problem

**Comment by arvidjaar** [comment]
@DirkSchmitt 

Try `Type=idle`, it should delay actual start until all other units has been processed.

**Comment by mbiebl** [comment]
We evaluated that for Debian, but decided against it. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822151

**Comment by arvidjaar** [comment]
@mbiebl 

`idle` does not directly affect ordering dependencies nor does it delay starting of service. It delays actual execution of `ExecStart` command after forking, in child. And `simple` service is declared as started as soon as fork happened.

Of course if followup service does need `rc.local` to have completed, `idle` would be wrong indeed. But then `rc.local` by definition cannot run "after everything else" because "everything else" must wait for `rc.local`.

Looking at code we again have usual case of (intentionally?) incomplete documentation. `idle` is not really  "delayed until all jobs are dispatched" as documentation makes users to believe; it is delayed up to the fixed non-configurable timeout which is hard-coded at 5 seconds (it is up to 6 seconds in total due to implementation).

**Comment by poettering** [comment]
So this is indeed one place where we simply aren't compatible with SysV's definition, because we cannot provide conceptually for a "last service" in our boot process, since we are heavily parallelized, event- and request-based. We provide similar functionality, but not with the exact same semantics, and that's simply something we have to accept and document.

I have added this to this list now:

https://www.freedesktop.org/wiki/Software/systemd/Incompatibilities/

And I figure we should add something similar to the rc-local-generator man page.

Or in other words, I figure this issue is a documentation issue, and not something we can or should conceptually fix.

**Comment by poettering** [comment]
I prepped a PR in #7735 that documents this divergence from classic SysV semantics

**Comment by jdebp** [comment]
For the record, the initial claim, and the resultant systemd doco, are wrong. `/etc/rc.local` isn't a System 5 thing, and it didn't run last.  It pre-dated System 5, was common in the BSD world, and ran _about halfway down_ `/etc/rc`.

* http://jdebp.eu./FGA/rc.local-is-history.html

**Comment by mj-harvey** [comment]
f**king systemd.

**Comment by aki-k** [comment]
@jdebp It ran "last" on Linux systems pre-systemd. I don't know why you'd drag BSD into this issue:

https://www.linux.co.cr/distributions/review/1997/red-hat-5.0/doc081.html
http://coewww.rutgers.edu/www1/linuxclass2003/lessons/lecture7.html
