### ISSUE TITLE
[regression] systemd-236: failed to start service with User=nobody (unable to access config file owned by nobody)

### ISSUE THREAD

**Issue by enihcam** [systemd/systemd#7717]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 236

### Used distribution

> Archlinux

### In case of bug report: Expected behaviour you didn't see

> shadowsocks-libev-server@config starts successfully

### In case of bug report: Unexpected behaviour you saw

> shadowsocks-libev-server@config failed due to unable to access a config file owned by 'nobody'

### In case of bug report: Steps to reproduce the problem

> pacman -Sy shadowsocks-libev systemd
> create config.json with owner=nobody
> systemctl start shadowsocks-libev-server@config

For more details:
https://git.archlinux.org/svntogit/community.git/tree/trunk/shadowsocks-libev-server@.service?h=packages/shadowsocks-libev

**Comment by yuwata** [comment]
https://bugs.archlinux.org/task/56802?project=5&string=shadowsocks-libev

**Comment by yuwata** [comment]
Cannot reproduced. I've tested the following. It seems not our bug.
```
$ systemctl cat hoge@.service
# /etc/systemd/system/hoge@.service
[Service]
User=nfsnobody
ExecStart=/bin/sh -c 'test -r /etc/hoge/%i.txt'
$ ls -la /etc/hoge 
total 0
drwxr-xr-x 1 root      root   16 Dec 21 21:18 .
drwxr-xr-x 1 root      root 2864 Dec 21 21:17 ..
-rw-r--r-- 1 nfsnobody root    0 Dec 21 21:18 hoge.txt
$ sudo systemctl start hoge@hoge.service
```
Please check that the config file and its parent directory is owned by nobody.
(Note that I've tested this on Fedora, on which nobody user named nfsnobody.)

**Comment by enihcam** [comment]
@yuwata You have to chmod 640 on hoge.txt and its directory before test.

**Comment by yuwata** [comment]
Could you report like my test case? Especially, `ls -la /etc/shadowsocks`.

**Comment by keszybz** [comment]
BTW, it's a really bad idea to run a service as nobody user. It's supposed to be used for users outside of the current user name space, instead a dedicated user should be used for a service (either allocated statically or with DynamicUser=1.)

**Comment by enihcam** [comment]
@yuwata 

```
/etc/shadowsocks $ ls -la
total 8.0K
drwxr-xr-x 1 root root 28 Apr 24 2017 ./
drwxr-xr-x 1 root root 1.7K Dec 21 18:47 ../
-rw-r----- 1 nobody root 411 Nov 21 13:20 s1.json
-rw-r----- 1 nobody root 411 Nov 21 13:20 s2.json

```

`sudo -u nobody /usr/bin/ss-server -c /etc/shadowsocks/s1.json` works fine, but the service unit cannot do the same.

```
[Service]
Type=simple
User=nobody
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/ss-server -c /etc/shadowsocks/%i.json
```

Let me know if you need more details.

**Comment by enihcam** [comment]
@keszybz  Thanks, I forwarded your suggestion to the package owner.

**Comment by enihcam** [comment]
To workaround this, I have to `chmod 644` on my config file which contains credential. This never happened on systemd v235. @yuwata

**Comment by enihcam** [comment]
A similar issue happened on my another machine which just upgraded systemd to v236:
```
Dec 22 14:54:31 avahi-daemon[233]: Found user 'avahi' (UID 84) and group 'avahi' (GID 84).
Dec 22 14:54:31 avahi-daemon[233]: Successfully dropped root privileges.
Dec 22 14:54:31 avahi-daemon[233]: avahi-daemon 0.7 starting up.
Dec 22 14:54:31 avahi-daemon[233]: Successfully called chroot().
Dec 22 14:54:31 avahi-daemon[233]: Successfully dropped remaining capabilities.
Dec 22 14:54:31 avahi-daemon[233]: **Failed to read /etc/avahi/services**.
```

**Comment by yuwata** [comment]
Still cannot be reproduced for me. After `chmod 640` the file, the previous test still success.
Could you give me several information: 
- passwd and group entries in `/etc/nsswitch.conf`
- `id nobody`
- `cat /usr/lib/sysusers.d/basic.conf | grep Nobody`

~~And what happens when the `User=` is changed to some static user, e.g., `User=shadowsocks`. Of course when testing it, you need to `chown` the config files, or `chmod 644`.~~
And could you test for example `hoge@.service` in the above or something similar to. In other word, please report the results without `shadowsocks`. Otherwise, we cannot judge this is our bug or not.

**Comment by enihcam** [comment]
@yuwata 

```
$ sudo systemctl status test@test
● test@test.service
   Loaded: loaded (/etc/systemd/system/test@.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-12-22 21:06:42 CST; 3s ago
  Process: 511 ExecStart=/usr/bin/cat /tmp/test.json (code=exited, status=1/FAILURE)
 Main PID: 511 (code=exited, status=1/FAILURE)

Dec 22 21:06:42 cat[511]: /usr/bin/cat: /tmp/test.json: Permission denied
Dec 22 21:06:42 systemd[1]: test@test.service: Main process exited, code=exited, status=1/FAILURE
Dec 22 21:06:42 systemd[1]: test@test.service: Failed with result 'exit-code'.
```

```
$ cat /etc/systemd/system/test@.service
[Service]
Type=simple
User=nobody
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
ExecStart=/usr/bin/cat /tmp/%i.json
```

```
$ ls -l /tmp/test.json
-rw-r----- 1 nobody root 0 Dec 22 21:04 test.json
```



```
$ cat /etc/nsswitch.conf
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files mymachines systemd
group: files mymachines systemd
shadow: files

publickey: files

hosts: files mymachines resolve [!UNAVAIL=return] dns myhostname
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```

```
$ id nobody
uid=99(nobody) gid=99(nobody) groups=99(nobody)
```

```
$ cat /usr/lib/sysusers.d/basic.conf | grep nobody
# The nobody user for NFS file systems
u nobody  65534 "Nobody"     -
```

**Comment by poettering** [comment]
Uh, systemd is built incorrectly for your system. You appear to have a user nobody on UID "99", but systemd's built-in logic assumes the name of UID 65534 is "nobody".

Most likely your distro builds systemd incorrectly, not matching the build configuration correctly to their /etc/passwd setup. They need to tell systemd right right UID as build-time, using "meson -D nobody_user=foobar -D nobody_group=foobar", and it has to be the name used on uid 65534. Please report this to your distribution. Thanks.

**Comment by jimis** [comment]
In my setup UID 65543 is "nfsnobody". But that's not what matters most in my opinion. 

@poettering What if somebody changes manually the system-assigned UIDs? There are valid reasons to do that, like migrating to different OS, satisfying legacy apps, network filesystems etc. The only "standard" UID in UNIX is zero, i.e. the superuser, and [even that is not to be hardcoded to "root"](https://unix.stackexchange.com/questions/8447/how-do-you-rename-root). Are there technical reasons that systemd requires now setting these username-UID bindings in compile time? I've read a [blog post](http://0pointer.net/blog/dynamic-users-with-systemd.html) and [a commit](https://github.com/systemd/systemd/commit/7e61fd02b0a9b2c4455974eb795da08b39352927) and the reason I see is for avoiding NSS lookups. Why is that desirable? Is there more information on the subject?

**Comment by keszybz** [comment]
I suspect this is a mismatch between what systemd thinks is uid for "nobody" and what some other nss module defines. Please verify with `ls -ln` what the UID on disk really is. It might be possible to work around your issue by creating `/etc/systemd/dont-synthesize-nobody` (see 24eccc3414a29a14b319d639531bd23c158b20e1).

We're trying to standarize the names of the few UIDs that are used by the kernel. We need a name for the overflow/unmapped user, 65534, and by convention that name is "nobody". You can define it to something else, if you absolutely must use "nobody" name for something else, but that is very strongly discouraged because it's assumed by many different things that "nobody" is that specific user. So the best option is to stop using "nobody" for anything else, and let it be used for the overflow user.

**Comment by poettering** [comment]
> @poettering What if somebody changes manually the system-assigned UIDs? 

Then they void their warranty. On Linux UIDs 0, 65534, 65535, 4294967295 all have very specific meanings, and you cannot just redefine them wildly. If you do, you are on your own, and things will break. See this document for details:

https://github.com/systemd/systemd/blob/master/UIDS-GIDS.md

> There are valid reasons to do that, like migrating to different OS, satisfying legacy apps, network filesystems etc. 

No. The four UIDs above cannot be redefined wildly. (And to emphasize this: this is a *Linux* thing, not a systemd one). Your distro has some limited leverage regarding the name associated with the 65534 user, but that's about it.

> The only "standard" UID in UNIX is zero, i.e. the superuser, and even that is not to be hardcoded to "root".

Well, we are on Linux. On Linux there are more that are special.

> Are there technical reasons that systemd requires now setting these username-UID bindings in compile time? 

Yes, these UIDs are special, the kernel uses them in special ways for user namespacing and such, and we need to make sure they are properly defined.

> I've read a blog post and a commit and the reason I see is for avoiding NSS lookups. Why is that desirable? Is there more information on the subject?

PID 1 is the superservice that forks off and manages all other services. This includes starting things on demand when services are requested via socket activation bus activation or any other kind of activation. As such it's very problematic if PID1 itself would end up being a client to any of the services it manages, because then it might deadlock: it requests something from a service, waiting for it to reply, but in order to be able to reply it would need to be activated, but that can't happen while PID 1 is waiting for the reply and can't process the activation request. Now, any NSS lookup might potentially involve querying a local daemon (think LDAP, SSSD, samba, NIS, …) synchronously, hence doing NSS from PID 1 is off limits to us, we might just deadlock. Since we need to deal with UID 0 and 65534 frequently however, and given they have special definitions we hence hardcode their user data.

**Comment by jimis** [comment]
Thanks for the technical details!

For the example of "nfsnobody" being 65534 that I mentioned, I'm quite sure I remember the NFS server on that network being an old RHEL system. And indeed a quick google search finds the following line in [the spec file from nfs-utils](https://src.fedoraproject.org/cgit/rpms/nfs-utils.git/tree/nfs-utils.spec):

```
# Using the 16-bit value of -2 for the nfsnobody uid and gid
%define nfsnobody_uid	65534
```

So what that means is that on new OSes with systemd, nfs will squash all UIDs to the "nobody" user, instead of the "nfsnobody", as used to be the case. Just FYI, as this can potentially hide security side-effects.
