### ISSUE TITLE
RFE: Downtime-free unit restarts

### ISSUE THREAD

**Issue by chrissnell** [systemd/systemd#7809]
### Submission type
 - Request for enhancement (RFE)

### systemd version the issue has been seen with

236.0

### Used distribution

Arch Linux

### RFE: Downtime-free restarts

I have a service, a DNS resolver, that supports downtime-free restarts on Linux >= 3.9.  You do this by starting a second instance of the service up and then killing the first once the second is running.

I would like to be able to achieve this with systemd without multiple units and hacky coordinating services.  It would be neat to have a systemd.service(5) option that directed this restart strategy.  Ideally, the replacement instance needs a way to signal that it's ready but a simple time delay option would be sufficient for my needs.

**Comment by shawnl** [comment]
Does every program that supports downtime-free restarts support it the same way?

**Comment by chrissnell** [comment]
See SO_REUSEPORT here:

http://man7.org/linux/man-pages/man7/socket.7.html

**Comment by shawnl** [comment]
I worked on a [SO_REUSEPORT patch supporting pools](https://github.com/shawnl/systemd/commit/753273163a380704c3ebc486ce339ae764e9d86c), but never got it working inside the systemd event loop.

**Comment by shawnl** [comment]
> Ideally, the replacement instance needs a way to signal that it's ready

See http://0pointer.de/public/systemd-man/sd_notify.html READY=1

**Comment by chrissnell** [comment]
I think sd_notify(3) is a great way to do it but there should also be a way for users to manually provide a Wait = [...] for programs not supporting sd_notify.

**Comment by poettering** [comment]
So, we support this already in various ways, however we won't allow service code to survive a service restart, because we guarantee that code is fully replaced and spawned in a pristine context during a restart. 

However, you can already do:

1. During service *reload* a service can change its main process in two ways: the nice way is by sending MAINPID= via sd_notify(), containing the new main PID. The not so nice way that works too is by simply updating the PID file if there's any and then exiting from the old process.

2. To make downtime-free *restarts* possible, you have two options: use socket activation so that systemd manages the listening socket for you. In the old service invocation stop accepting new connections and finish off old connections. Then simply exit. The new invocation is then started, and can accept new connections, continuing where the old instance left off. Of course, this only works if all connections are short-lived. The other option is to pass fds to PID 1 for safe-keeping right away, then exiting. systemd will then pass those fds back into the new instance. Sending fds to PID 1 is done by sd_pid_notify_with_fds() and FDSTORE=1. The best approach is usually to combine socket activation and the fdstore logic into one, so that things become the most robust.

And yes, we should advertise this better. I have been planning to do a blog story about this, but never found the time to.

I understand you are looking for a way to hand off process execution during restart yourself, but that's something I am very sure we shouldn't allow. Users should have the guarantee that the execution context is in a fully defined, clean state in all cases during execution. It's OK to permit passing some very specific select resources from one invocation to the next (the way we allow it via the fdstore), but I am very sure we should not allow a blanket passing of resources.

I hope that makes sense?

Closing, as I think we are already covering this pretty OK now, to some extent at least.

**Comment by chrissnell** [comment]
I ended up figuring out a work-around for my service (`dnscrypt-wrapper`).  For those stumbling upon this, here's how I did it.  It feels a little hacky but it works well.

My service is started like this:
```
# /usr/lib/systemd/system/dnscrypt-wrapper@.service
[Unit]
Description=DNSCrypt wrapper
Documentation=man:dnscrypt-wrapper(8)
After=network.target iptables.service firewalld.service

[Service]
Type=simple
EnvironmentFile=-/etc/default/dnscrypt-wrapper
#  dnscrypt-wrapper.sh is just a simple shell script that does the key generation for dnscrypt-wrapper
ExecStart=/usr/local/bin/dnscrypt-wrapper.sh
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Then I have a service that swaps and rotates two dnscrypt-wrapper@ services:
```
# /usr/lib/systemd/system/dnscrypt-service-rotate.service
[Unit]
Description=dnscrypt-wrapper service rotation

[Service]
Type=oneshot
ExecStart=/usr/local/bin/dnscrypt-service-rotate.sh
TimeoutStartSec=10
```

This service is triggered by a .timer unit running every 8 hours.   The service unit kicks off this shell script to do a no-downtime swap of the services:

```
#! /usr/bin/env bash

systemctl -q is-active dnscrypt-wrapper@a
A_RUNNING=$?

systemctl -q is-active dnscrypt-wrapper@b
B_RUNNING=$?

if [[ $A_RUNNING -eq 0 && $B_RUNNING -gt 0 ]]; then
    echo "Preparing to replace dnscrypt-wrapper@a.service with dnscrypt-wrapper@b.service ..."
    echo "Startring dnscrypt-wrapper@b.service ..."
    systemctl start dnscrypt-wrapper@b.service
    sleep 5
    echo "Shutting down dnscrypt-wrapper@a.service ..."
    systemctl stop dnscrypt-wrapper@a.service
fi

if [[ $A_RUNNING -gt 0 && $B_RUNNING -eq 0 ]]; then
    echo "Preparing to replace dnscrypt-wrapper@b.service with dnscrypt-wrapper@a.service ..."
    echo "Startring dnscrypt-wrapper@a.service ..."
    systemctl start dnscrypt-wrapper@a.service
    sleep 5
    echo "Shutting down dnscrypt-wrapper@b.service ..."
    systemctl stop dnscrypt-wrapper@b.service
fi 

if [[ $A_RUNNING -gt 0 && $B_RUNNING -gt 0 ]]; then
    echo "Neither dnscrypt-wrapper@a.service or dnscrypt-wrapper@b.service are running."
    echo "Startring dnscrypt-wrapper@a.service ..." 
    systemctl start dnscrypt-wrapper@a.service 
fi
```

**Comment by ngrilly** [comment]
> Of course, this only works if all connections are short-lived.

It makes sense, but what if the connections are long-lived (a few tens of seconds)?
