### ISSUE TITLE
Cannot "mount --bind /dev /tmp/dev" inside systemd-nspawn container

### ISSUE THREAD

**Issue by deep-42-thought** [systemd/systemd#7814]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 236.0

### Used distribution

> archlinux (on x86_64)

### In case of bug report: Expected behaviour you didn't see

> content of /dev being available in /tmp/dev (inside the container)

### In case of bug report: Unexpected behaviour you saw

> "mount: /tmp/dev: wrong fs type, bad option, bad superblock on /dev, missing codepage or helper program, or other error."

### In case of bug report: Steps to reproduce the problem

(set up container)
> mkdir /var/lib/machines/test
> pacstrap -i -c -d /var/lib/machines/test base
> seq 0 7 | sed 's|^|pts/|' >> /var/lib/machines/test/etc/securetty

(start container)
> systemctl start systemd-nspawn@test

(login as root)
> machinectl login test

(now, inside the container)
> mkdir /tmp/dev
> mount --bind /dev /tmp/dev

Note, that other directories are mounted flawlessly, I tested successfully `/dev/shm`, `/home`, `/sys`, `/tmp`

**Comment by deep-42-thought** [comment]
Some more trials reveal, that also `/` and `/run` cannot be bind-mounted from inside the container.

**Comment by poettering** [comment]
Uh, this is because the /dev is owned by the userns of the host, and you run your containers with userns turned on, and the kernel's userns code doesn#t allow creating bind mounts of mounts owned by other userns. It's a security feature.

it should work if you turn off userns support for your container (PrivateUsers= in your .nspawn file). Please verify.

i am not sure there's anything to fix here...

You can

**Comment by deep-42-thought** [comment]
you're right. I thought, I had tried that option previously, but apparently I have not.
Sry for the noise.
