### ISSUE TITLE
Docs: How does "systemctrl stop ..." work

### ISSUE THREAD

**Issue by guettli** [systemd/systemd#7931]
### Submission type

 - Request for enhancement (RFE)

man systemctl:

> stop PATTERN…
>
>    Stop (deactivate) one or more units specified on the command line.

Source: https://www.freedesktop.org/software/systemd/man/systemctl.html#stop%20PATTERN%E2%80%A6

Please elaborate the man page for "stop".

How does systemctl stop a service?

This question should be answered at above place in the man page, **or** there should be a hint where new users can find the details about stopping a service.

**Comment by sourcejedi** [comment]
There are several types of unit; service is only one.

> Name
> 
> systemctl — Control the systemd system and service manager
> Synopsis
> 
> systemctl [OPTIONS...] COMMAND [NAME...]
> Description
> 
> systemctl may be used to introspect and control the state of the "systemd" system and service manager. Please refer to systemd(1) for an introduction into the basic concepts and functionality this tool manages.

`man 1 systemd`

> CONCEPTS

...

> The following unit types are available:
>
> 1. Service units, which start and control daemons and the processes
           they consist of. For details, see systemd.service(5).

It's not 100% clear

> Description
>
> A unit configuration file whose name ends in .service encodes information about a process controlled and supervised by systemd.
>
> This man page lists the configuration options specific to this unit type. See systemd.unit(5) for the common options of all unit configuration files. The common configuration items are configured in the generic "[Unit]" and "[Install]" sections. The service specific configuration options are configured in the "[Service]" section.
>
> Additional options are listed in systemd.exec(5), which define the execution environment the commands are executed in, and in systemd.kill(5), which define the way the processes of the service are terminated, and in systemd.resource-control(5), which configure resource control settings for the processes of the service.

and partly because you want to look at both `[Service]ExecStop=` and `ExecStopPost=` as well as systemd.kill.  Pure reference documentation is also not really helpful as an introduction.  Fortunately it also follows the manpage convention of having EXAMPLES at the end, which is easier to learn from.  The examples both talk about ExecStop= and point to systemd.kill.

**Comment by sourcejedi** [comment]
Hi @guettli.  Can you be more specific about what you're trying to do?  Or do you have any more detailed suggestions on how you think the documentation could be improved to help you, after reading my comment above?  I'm tempted to close this, if we don't have a more specific idea of a change that would help you.  

Broadly, I can imagine it would not be so obvious to a new Linux user, that service processes are typically stopped by sending the TERM signal.  But I can't guess exactly why it would be important for the `systemctl stop` section to teach that.

For a more experienced user who wants to know exactly how a specific systemd service will be stopped... it seems intuitive that you would look at the options for the relevant service unit file, and of course the default values for the configuration options.  I.e. I would expect people to find their way to `systemd.service`.  Even if they miss the entry point in `man systemd`, and have to use some web searches before they find their way to `systemd.service`.

**Comment by guettli** [comment]
> ... that service processes are typically stopped by sending the TERM signal. 

If this is what systemd does, then I think should be documented. You said "typically" this sounds like there are other ways for systemd to stop a process.

**Comment by sourcejedi** [comment]
Yes, there are different ways to stop processes depending on what the config files for the specific service unit says.

This is already documented.  I stepped through it above including quotes, how to find examples of different configurations in `man systemd.service`, and the reference documentation in `man systemd.kill`.  Starting from `man systemctl` just as you mentioned.

I am not able to work out a useful change that would help you, from the information provided.

---

I've also tried to explain why the section for `systemctl stop` cannot point to more information on stop for services only, and `systemctl start` to information on start for services only etc.

And you will notice the description of `systemctl start` is equally non-specific about how the service process is _started_.  The intended role of `systemctl` is very much 'introspect and control the state of the "systemd" system and service manager', as per the manpage opening sentence.  Since systemd acts as a service manager, it is necessary that the service process is spawned by the service manager, and not directly by `systemctl`.  The stop proceedure is delegated in the exact same way.  For example in the popular case of sysvinit compatibility, it is the service manager that will spawn `/etc/init.d/my-service stop`, symmetric with the start case.

My opinion is the shortness of the section for `systemctl stop` is a useful feature.  If we bloated every section with too many links, it would make it harder to understand everything.  Probably like this thread.  

---

> There are several types of unit. service is only one. Different types of units do different things on start, stop etc. The docs are at least trying to point you to the right place, see below.

---

> For a more experienced user who wants to know exactly how a specific systemd service will be stopped... it seems intuitive that you would look at the options for the relevant service unit file, and of course the default values for the configuration options. I.e. I would expect people to find their way to systemd.service. Even if they miss the entry point in man systemd, and have to use some web searches before they find their way to systemd.service.
