### ISSUE TITLE
Document that timedatectl set-ntp == systemctl {enable/disable} systemd-timesyncd.service

### ISSUE THREAD

**Issue by wlcrls47** [systemd/systemd#798]
I'm confused by the documentation, on whether timedatectl set-ntp ONLY enables or disables systemd-timesyncd.service, or if it does this AND other things.  Are they interchangeable?  I'm betting they aren't interchangeable, because the other systemd services don't have a non-systemctl way to be enabled/disabled (as far as I've ran into.)

Asking, because "timedatectl set-ntp true" fails from the boot cd in arch-chroot with "Failed to create bus connection: No such file or directory".  But, systemctl runs without needing a bus connection.

**Comment by falconindy** [comment]
systemctl runs without a bus connection because it has fallback logic to enable/disable units in the absence of a usable bus connection. timedatectl defers work to timedated by communicating with it over the bus. So, it makes sense that systemctl works and timedatectl fails in the absence of a system bus. This situation ought to improve once kdbus is around.

Looking at the code, calling `timedatectl set-ntp true` is equivalent to calling `systemctl --now enable systemd-timedated`. Similarly, `timedatectl set-ntp false` is equivalent to calling `systemctl --now disable systemd-timedated`.

**Comment by poettering** [comment]
It only controls systemd-timesyncd.service. 

Today the setting is pretty redundant since "systemctl enable systemd-timesyncd.service" is also hooked up to PolicyKit, and thus clients such as GNOME could just invoke that directly.

**Comment by poettering** [comment]
We should probably update the man page to explain in more detail what this does.

**Comment by wlcrls47** [comment]
Just tried using systemctl enable systemd-timesyncd.service

**Comment by poettering** [comment]
We should still document this. Reopening hence.

**Comment by richardmaw-codethink** [comment]
http://www.freedesktop.org/software/systemd/man/timedatectl.html#set-ntp%20%5BBOOL%5D seems clear to me that it's about enabling/disabling the service.
