### ISSUE TITLE
systemd user instance is not creating files with correct labels

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#8004]
### Submission type

 - Bug report
 - Request for enhancement (RFE)

### systemd version the issue has been seen with
=< 236
> …

### Used distribution
Fedora Rawhide
> …

### In case of bug report: Expected behaviour you didn't see

systemd --user stance does not create activated socket files, paths, CacheDirectory etc with proper labels like systemd --system does
> …

### In case of bug report: Unexpected behaviour you saw
systemd --user creates activated socket files, paths, CacheDirectory= etc with wrong contexts
> …

### In case of bug report: Steps to reproduce the problem
```
echo '(filecon "HOME_DIR/mytest(/.*)?" any (system_u object_r irc_home_t ((s0)(s0))))' > mytest.cil && semodule -i mytest.cil
matchpathcon $HOME/mytest
# need to reexec so that systemd flushes its cache
systemctl --user daemon-reexec
mkdir -p ~/.config/systemd/user
cat > ~/.config/systemd/user/mytest.path <<EOF
[Unit]
Description=My Test

[Path]
DirectoryNotEmpty=%h/mytest
Unit=mytest.service
MakeDirectory=yes
EOF
cat > ~/.config/systemd/user/mytest.service <<EOF
[Unit]
Description=My Test

[Service]
ExecStart=/usr/bin/id -Z
EOF
systemctl --user daemon-reload
systemctl --user restart mytest.path
ls -dZ ~/mytest
seq 1000 > ~/mytest/afile
```
> …
For some reason it looks like systemd --user instance is not using `setfscreate` and `setsockcreate` like systemd --system instance

**Comment by poettering** [comment]
uh, for selinux support we really require contributions as we are no selinux gurus ourselves, and don't really want to make changes on these security-relevant things like this without fully grokking things.

**Comment by garyttierney** [comment]
ACK on requiring contributions for the SELinux stuff.  I'll have a look at this over the weekend and see if I can get a patch put together.

**Comment by ILMostro** [comment]
Potentially outside the scope of this github-issue, but relevant nonetheless:
Perhaps the additional contributions for SELinux items with respect to `systemd` might lead to better integration of the two across other distributions as well.  For example, a lot of the work on ArchLinux was put together by Arch devs/contributors, in order to get SELinux supported on a system using `systemd`.  Conversely, SELinux on Gentoo systems with `systemd` is still not supported.  It could be part of `lsb-release` efforts, or something similar that would bring the `systemd` project more in line to a cross-distro tool-set.
