### ISSUE TITLE
[RFE] extend StandardOutput= to take multiple values

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8011]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

236

### RFE

* Add a way to write to a file in append-only mode when using `StandardOutput=file:/path/to/file`.

* Extend `StandardOutput=` to take multiple values so that one could combine file:/path/to/file and journal to log to multiple targets at once, or file:/path/to/file and syslog+console. That is, StandardOutput= is extended to take multiple values and then output goes to all of the targets specified.

Intended use case: 
Output to two or more files
`StandardOutput=file:/path/to/file1 file:/path/to/file2 file:/path/to/file3`
Output to a file as well as to the journal
`StandardOutput=file:/path/to/file journal`
and so on.

**Comment by poettering** [comment]
StandardOutput=append: has been added with #9500. 

Renaming this issue hence, since only the other request is missing. (That said, I am not convinced the other request is overly desirable to implement, as it means some multiplexing services would have to sit on the other side of the stdout/stderr fifo/socket, and if that's journald then this means journald would have to write files all over the place...

**Comment by bl33pbl0p** [comment]
Yes, I think the other request probably makes little sense. Closing.

**Comment by MrKich** [comment]
I think it would be nice to have a way to write stderr of a service to journal as well as to its own log file, where stdout goes.
