### ISSUE TITLE
Systemd support for Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by WSLUser** [systemd/systemd#8036]
### Submission type

 - Request for enhancement (RFE)

Work with Microsoft on [Github](https://github.com/Microsoft/WSL) to assist bringing `systemd` functionality to the Windows Subsystem for Linux (WSL).

<del>This will require work on systemctl</del> as filed [here](https://github.com/Microsoft/WSL/issues/1579). Also will require MS to change their `init` from proprietary to becoming a service called on by native `init` [?]

The current MS `init` has coding allowing some interop with Windows 10 applications similar to Wine but performs superior to Wine but does have limitations.  

### systemd version the issue has been seen with

WSL has:

< systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

EDIT: however `init` is replaced on WSL with a proprietary stub, and attempting to run systemd will naturally say stuff like ["Trying to run as user instance, but the system has not been booted with systemd."](https://github.com/Microsoft/WSL/issues/994#issuecomment-361221608)

### Used distribution

> Ubuntu or OpenSuse but will be relevant to any distro installed on WSL.

---

This post edited by @sourcejedi, without any intent to remove the original content.

**Comment by sourcejedi** [comment]
FWIW, https://github.com/Microsoft/WSL/issues/1579 does not make any concrete suggestion about work on `systemctl`.  On the contrary, the first comment suggests that without a running `systemd`, there is no point expecting `systemctl` to do anything :-P.

Note systemd already has an [interface](https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/) they can engage with if they want :-P.  Speculating wildly, this might only need slight adaptations.  I imagine MS might want to hack in a few `/sys` features, whereas systemd in container has so far been written to expect a read-only `/sys`.  If a read-write /sys is detected, we will try to run `udev`, and that probably won't do anything sensible :).  If nothing else it might have to be `ConditionVirtualization=!wsl`.

[IMO the real question is how they want to inject the per-window `/bin/bash` processes into the Linux system.  It might be able to work fine without any additional accommodation on the systemd side](https://github.com/Microsoft/WSL/issues/994#issuecomment-361221608).  Again, this is wild speculation, but I've commented it on their github as you suggest.  How's that for co-operation ;-).

**Comment by sourcejedi** [comment]
Note this is really broad as tracking bug.  I suggest any concrete issues that need to be addressed, will  benefit from being raised separately.  (I.e. on a broad issue like this, any relevant information is at risk of just being buried).

**Comment by DarthSpock** [comment]
@sourcejedi Thanks for the quick follow-up. Yes I'm quite aware of how broad this is. There are other related issues to the one I listed in which errors are generated but essentially yes, there's no read-write. Some things as you know depend on that. `udev` is extremely limited as we're still waiting for support for `libusb` for example. There is another issue requesting the ability to perform shutdowns/reboots though was too wide to wanting to control Windows with that functionality. General consensus there was to simply have it limited to the particular distro you execute it in. Another issue is there is no auto-start of services so you have manually start any required services. Some syscalls will autostart services related to a particular package installed when you run it, but some things such as `dbus` or `ssh` need to be manually started. There are so many things dependent on `systemd` or something else such as `systemctl` that has a dependency on `systemd` there's more of an advantage to getting it as fully implemented as possible without breaking anything. I'm just hoping that filing this issue can help expedite issues users of WSL experience get fixed faster since there is a small team that does the work for WSL to begin with and as you know, there are many, many things to be worked on. Having outside help from people with the specialized know-how for particular thing such as `systemd` might go a long way in helping them figure out and troubleshoot issues. I can try to generate some specific use cases later but I believe I've seen a few already in the WSL issue tracker (even if they are marked as dupes of already existing issues.)

**Comment by sourcejedi** [comment]
I should be 100% clear. I don't think we're interested in unmet use cases that depend on running `/lib/systemd/systemd`, until you have some way to run `/lib/systemd/systemd` as PID 1.  And meet the other essential requirements. Which systemd makes a good effort to document IMO.

I've seen no details about switching from their PID 1. It's their decision. It sounds cool enough to me that I was happy speculating and cheering for it to happen. But funnily enough I don't have any source code or APIs to test or analyze to switch their PID 1 :).

systemd is written for Linux. WSL needs to look like... some possible Linux kernel environment... w.r.t. the requirements for systemd.

It's possible there are some requirements (documented correctly or not) which we can accept tweaks for, and importantly _maintain_, without extra effort. Note, trying to not bother us about the stuff where we have no control, and not even much information, would be helpful in keeping this effort acceptable :).  (More paragraphs and less wall-of-text are nice as well :-P).

Also, this was probably just distracting, but: the point about systemd-udevd is that we absolutely do not support it on Linux containers.  If you want udev, you must run a VM.  (Or make a good enough impression of one - and then there's no reason to change systemd anyway).

The reason I thought this might be practical, is that systemd has already been adapted to work in Linux containers.  And to work despite some capabilities being withheld, although we are still recommending against it.  So my assumption is that they would work on the requirements for systemd as run in a Linux container, aka [ContainerInterface](https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/).  (Other reqs are covered in README).

**Comment by DarthSpock** [comment]
Yes I understand everything you're saying. It's my impression that MS would eventually make the move to change PID 1 to systemd and is only a matter of time. Because of things stated such as someone saying "I don't think MS wants to maintain their own userland...", which if they continue with this project would end up happening without making the change over to systemd, especially since the distros already have that work done. 

(Here's your paragraph break :P)

The idea behind WSL is that there is no container. The Linux kernel lives inside the NT kernel. Thus no need for a VM, Docker, or any other containerization. It truly is supposed to be as "native" as real Linux. That's the end state, which may never be reached but that's the idea creating WSL. Otherwise it would simply be a matter of MS doing nothing and allow Docker or virtualization companies such as VMware (or their very own HyperV) do everything. This is a huge potential gain to be had by making it natively accessible on the same machine without having any special setup, least of which is performance (an ongoing effort for years now) and ease of use. We can't make MS turn away from Windows but they can make it work alongside Linux. They should of been doing this from the beginning of Windows but I digress.

I think udev will come to life simply because the hardware is there and just needs exposing. In order to gain the potential performance boost, among other benefits, there will be need of having access the same hardware Windows has access to. Problem is much of `lib\blah\blah` hasn't really been setup. It's been stubbed just enough to make things  *work* for what's it worth for considering what exactly is *working*. If MS can take some aspects of WSL out of the user session and into the actual OS, this will alleviate some obstacles as well.

**Comment by fpqc** [comment]
@sunilmut @benhillis Probably worth tagging you guys in here.

**Comment by DarthSpock** [comment]
@fqpc Yes I'm trying to be forward-looking with support for udev. I think a driver API should be opened up but for now, we have a ways to go. Overall motivation here is to bring WSL to as close to native Linux as possible. Because while MS is only considering devs at the target audience, eventually they'll need to support normal users as well. And from the angle of devs are creating products and services for normal users, it would logically make sense that devs need the same abilities that normal users have for proper simulation in a lab environment. As it stands now, anything done in WSL will have to be moved over to a real Linux box for proper testing before deploying to users. Also with lack of communication in issues such as getting `systemd` supported, it leaves a giant *cricket* in the air that has impression of nothing is happening here. I'm not asking for the job of coordinator but if that's what MS needs to get features implemented then I'd do my best and if something I explain isn't entirely accurate, someone can address the inaccuracies/provide more technical details. I know that I have limitations to some of the engineering fundamentals of Linux, I originally had focused more on Windows and even there my dev experience is much less than my SA/DBA/etc. experience, of which I have plenty of on all manner of things. Anything I'm explaining here is most likely gathered from personal research and keeping track of the technical details of issues that exist on the WSL issue tracker. I also will have some assumptions based on what MS publicly announces because I do have that SA experience that I go off of more often than not.

**Comment by sourcejedi** [comment]
This does not appear to leave anything for us to do now, so I am closing this issue to help keep things managable.  Issues can be commented and re-opened, or new issues created etc. if needed.

**Comment by DarthSpock** [comment]
It's actually a bit more containerized than that. There's some stuff in Insiders that show more support for groups and even some kind of systemd functionality. The thread I linked above now has a test case for getting it to run but isn't consumer-friendly as of yet. There might be more to help in the Fast-Ring builds now in getting it up and running but I think the support is slowly being built out in the background (there's been no official advertisement from the WSL team).

**Comment by peteraldous** [comment]
In case anyone needs a concrete example of something failing, I just tried to upgrade my WSL distro to Ubuntu cosmic. It tried and failed to install snapd, which relies on systemd. Now apt is going to bark at me every time I try to update my software.

**Comment by estape** [comment]
![Anotação 2020-04-18 232009](https://user-images.githubusercontent.com/13343583/79678093-0b3cc700-81ce-11ea-82b5-ea682604eb1e.png)
![Notebook](https://user-images.githubusercontent.com/13343583/79678094-0d068a80-81ce-11ea-991e-9c2bbb41d9de.png)
 I was unable to run tasksel in order to run Ubuntu GUI.

**Comment by ningacoding** [comment]
any update?

**Comment by keszybz** [comment]
@ningacoding see https://github.com/microsoft/WSL/issues/994 instead.

**Comment by ningacoding** [comment]
OK, sorry. Regards.

**Comment by eaglegoboom** [comment]
so basically running windows subsystem for linux WSL 2 is still broken, and useless. If you cant run this as PID 1, a great many of the applications on it cant even be tested , let alone developed.

**Comment by relief-melone** [comment]
There actually is a hacky way of doing it. I hope I will find the blog post again that described the complete process and I will post it here, but it is part of the script I set up to get all the tools I need for my wsl (I basically needed it for microk8s as this utilizes snap as well which depends on systemd)

https://gitlab.com/relief-melone/wsl-initial-setup

It very basically uses unshare to create a systemd process down the road and use that one as your PID1 when you log into your wsl

If you want nothing but the systemd just clone the repo and

    ./install.sh

and quit after the first run. If you want some more stuff exit wsl login with the user you chose install.sh to create again and run ./install.sh again. (It's also in the readme though ;))

I still hope Microsoft decides to natively integrate systemd as PID1 because there are some features you'll be missing afterwards (e.g. with systemd as PID1 you won't be able to start vs-code directly from wsl to your host machine and will have to use

    wsl -- /bin/bash
)

to get back to microsofts intended init to do that. So you will definately have to switch from time to time. Still better than nothing I guess

**Comment by ZloiDyadka** [comment]
Я так понимаю проблема с systemctl ещё не решена?(As I understand it, the problem with systemctl has not been resolved yet?)

**Comment by trallnag** [comment]
There is this project: https://github.com/arkane-systems/genie
