### ISSUE TITLE
[nspawn/networkd] Link-local address assigned to host veth interface

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#8047]
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd --version
systemd 236
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

cat /etc/debian_version
buster/sid

### In case of bug report: Expected behaviour you didn't see

the host interface of a bridged veth interface should not have link-local address assigned.

### In case of bug report: Unexpected behaviour you saw

systemd-nspawn and/or systemd-networkd assign link-local address to the host veth interface created by the bridge option of an nspawn container. i personally dont believe that having an IP assigned to the host interface of a bridged veth interface make sense as it is basically only the end of a virtual cable coming from the container network interface that you virtually plug into a virtual bridge. i have also no clue how to configure a firewall within the virtual bridge to restrict the traffic between these link-local IPs.

networkctl status vb-server003
● 32: vb-server003
       Link File: /lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/vb.network
            Type: ether
           State: degraded (configured)
          Driver: veth
      HW Address: ba:74:a5:ae:bb:db
         Address: **fe80::b874:a5ff:feae:bbdb**

cat /etc/systemd/nspawn/server003.nspawn
[Exec]
PrivateUsers=False

[Network]
**Bridge=br0**

it is also not possible to manually disable the link-local addressing as the parameter seems to be getting ignored.

cat /etc/systemd/network/vb.network
[Match]
Name=vb-*

[Network]
**LinkLocalAddressing=no**

### In case of bug report: Steps to reproduce the problem

setup a container with a bridged veth interface and examine the host veth interface with networkctl.

**Comment by yuwata** [comment]
Could you test with v241 or newer? The PR #11423 (which is included in v241) may help the situation.

**Comment by poettering** [comment]
Closing due lack of response.

**Comment by celogeek** [comment]
I try to add the
LinkLocalAddressing=no

The result is the status is now configured. no more local ipv6 on the vb-* address.

The issue is that the vb-* is not added to the bridge anymore.
I can see that the brctl show is empty.

The machines can't connect to anything until I add it manually to the bridge.

Does LinkLocalAddressing=no has effect on the bridge configuration ?

**Comment by yuwata** [comment]
@celogeek Could you open a new issue with the following? Otherwise, we can easily forget your issue, as this is already closed.
- version of systemd
- related .network, .netdev, .link, and .nspawn files.
- debugging logs of networkd

You can generate debugging logs of networkd by creating the following drop-in config:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
I recommend to use `sudo systemctl edit systemd-networkd.service` for creating the above drop-in.
