### ISSUE TITLE
stricter PIDfile handling breaks several daemons

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#8085]
### Submission type

 - Bug report

### systemd version the issue has been seen with

v237

### Used distribution

Debian sid
Also reported downstream  as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889144

Quoting from the downstream bug report:

> The upstream commit db256aab13d8a89d583ecd2bacf0aca87c66effc "core: be 
stricter when handling PID files and MAINPID sd_notify() messages"
breaks several daemons in Debian.

> Known issues exist for

 > - munin-node https://bugs.debian.org/889073
 > - ulogd2
 > - dnsmasq https://lists.debian.org/debian-user/2018/01/msg01331.html

> and possibly others.

> Symptom is a timeout during service start, constant service restarts (if
> configured) and log messages like:

> Feb  2 14:22:49 HOST systemd[1]: ulogd2.service: Permission denied while opening PID file or unsafe > symlink chain: /run/ulog/ulogd.pid
> Feb  2 14:23:54 HOST systemd[1]: munin-node.service: Permission denied while opening PID file or unsafe symlink chain: /run/munin/munin-node.pid

In all those cases, a directory /run/foo/ is created, which is not owned by root (but a system user foo), the pid file that is written by the daemon is owned by root:root though. The pid file is not a symlink though.

The daemon in those cases drops privileges on its own and places additional files in that /run/foo directory, afaiu. Which is why the directory has to be owned by foo, so the unprivileged process can actually place files there.

As the pid file is not a symlink, I think systemd is incorrectly rejecting it.

**Comment by mbiebl** [comment]
I.e., I understand the attack vector that results from /run/foo/foo.pid being a symlink pointing at a root owned file. But in this case, /run/foo/foo.pid is root:root owned whereas /run/foo is foo:foo owned. That seems perfectly valid. If systemd is rejecting that, I think it would be prudent to at least document why.

**Comment by shartge** [comment]
Correction: The issue is with 237 and not 231.

**Comment by mbiebl** [comment]
> Correction: The issue is with 237 and not 231.

indeed, sorry for the typo. corrected

**Comment by shartge** [comment]
I can see the reason behind https://github.com/systemd/systemd/commit/db256aab13d8a89d583ecd2bacf0aca87c66effc : even if the PIDfile in `/run/foo` is owned by root:root, as long as the directory is owned by a different user, it can meddle with it.

Problem is: many programs (or programmers) create PIDfiles at the wrong time, with the wrong user or in the wrong place with the wrong permissions. And so far any init system accepted that, even if inherently insecure.

Changing that now is bound to subtly break existing systems without any warning before.

**Comment by sourcejedi** [comment]
It looks like we could fall back to chase_symlinks() without CHASE_SAFE, and treat that case the same as if the PIDFile was not owned by root.  (I.e. require that the pid is one that belongs to the unit's cgroup).

**Comment by poettering** [comment]
Hmm, so the code in those services is problematic even if we accept the PID file with the additional in-cgroup restrictions: creating guessable files as root in non-root directories is almost always a vulnerability: the non-root user can first create a symlink in the directory under the PID file's name, and thus make root write to any file in the file system it likes.

I wonder if we hence should log about cases like this either way, i.e. even if we accept the PID file with in.-cgroup restrictions. There might be false positives about the warning though: if your service creates the PID file under a randomized (i.e. non-guessable name) first, and then renames it to the real name things should be safe — as long as it's only the directory the file is created in itself is owned by non-root (if there are more dirs in the prefix you are fucked either way, as the user then can replace them by symlinks too)...

**Comment by keszybz** [comment]
If it does `open(..., O_CREAT|O_EXCL|O_NOFOLLOW)` then it's safe too, no?

Anyway, I don't think we should reject the case when a root-owned file is located in a non-root-owned directory. The daemon can do this properly and safely, and we cannot distinguish this from the unsafe case. Also, the alternative is to force the daemon to chown() the file to the user, which doesn't seem to be an improvement, since it requires additional code in the daemon and makes it easier for the unprivileged code to overwrite the pid file. Overall, I think the proper solution is to just accept that case, without any warning.

**Comment by poettering** [comment]
@mbiebl btw, I think it would be nice to let the service maintainers know that what they are doing there is almost certainly unsafe, and they should fix their code, even if we relax things a bit...

**Comment by poettering** [comment]
> If it does open(..., O_CREAT|O_EXCL|O_NOFOLLOW) then it's safe too, no?

yeah, but only within the "only one prefix dir owned non-root" restriction too.

> 
> Anyway, I don't think we should reject the case when a root-owned file is located in a non-root-owned directory. The daemon can do this properly and safely, and we cannot distinguish this from the unsafe case.

**Comment by mbiebl** [comment]
> @mbiebl btw, I think it would be nice to let the service maintainers know that what they are doing there is almost certainly unsafe, and they should fix their code, even if we relax things a bit...

What should they do instead? I don't think we have proper documentation for that where I can point maintainers at.

**Comment by poettering** [comment]
> What should they do instead? I don't think we have proper documentation for that where I can point maintainers at.

Well, long story short is: "when root writes to non-root owned directories you must be very very careful, and the chance you get it wrong is waaaay higher than the chance you get it right." There might be some UNIX security howtos that explain the whys, but this is mostly because symlinks and hardlinks work the way they work...

Note that even now our own tmpfiles doesn't get all this stuff right (see #7986 for example), and we try very hard and know the pitfalls...

One great way to avoid all this: don't write out PID files altogether and use Type=notify instead, but of course that requires patching...

**Comment by poettering** [comment]
Prepped the suggested fix in #8133 now. @mbiebl could you check if that makes things work for you?

**Comment by sjuxax** [comment]
Adding this mostly for the record and Googleability. After a reboot on Arch Linux, this issue makes PostgreSQL fail to start when `/var/lib/postgres` is symlinked to another drive (`/mnt/postgres`):
```
Feb 08 12:46:46 my_host postgres[20451]: 2018-02-08 12:46:46.150 EST [20453] LOG:  database system is ready to accept connections
Feb 08 12:46:46 my_host systemd[1]: postgresql.service: Permission denied while opening PID file or unsafe symlink chain: /var/lib/postgres/data/postmaster.pid
```

I've worked around this for now by modifying `postgresql.conf` to write an external PID at `/run/postgresql/postmaster.pid` and then updating the systemd service file to reference that.

```
# systemctl --version
systemd 237
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid
```

```
# trizen -Qi systemd      
Name            : systemd                        
Version         : 237.0-2
```

```
# trizen -Qi postgresql   
Name            : postgresql          
Version         : 10.1-1
```

**Comment by mbiebl** [comment]
@shartge since you were affected by this, could you test #8133

**Comment by shartge** [comment]
I will. If you could provide with test packages with #8133 included I can do this faster than if I have to build them myself.

**Comment by keszybz** [comment]
> I've worked around this for now by modifying postgresql.conf to write an external PID at /run/postgresql/postmaster.pid and then updating the systemd service file to reference that.

So... that's a win-win outcome. Solves the potential security issue *and* using /run for the pid file is much better then /var/lib.

**Comment by shartge** [comment]
@mbiebl Your upload to Debian was faster than my ability to test the change, but, for the sake of completeness: I tested 237-2 with munin-node and ulogd2 and can confirm this problem to be solved.

**Comment by Deepesh125** [comment]
I have service which was working fine with RHEL 7.5, now I have upgraded to RHEL 8 and same service is failing with below status:
Service.service - LSB: Web Server
   Loaded: loaded (/etc/rc.d/init.d/Service; generated)
   Active: failed (Result: protocol) since Mon 2020-04-06 12:02:21 IST; 38min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 403 ExecStart=/etc/rc.d/init.d/Service start (code=exited, status=0/SUCCESS)

Apr 06 12:02:21 localhost.localdomain systemd[1]: Starting LSB: Web Server...
Apr 06 12:02:21 localhost.localdomain Service[403]: httpd (pid 29434) already running
Apr 06 12:02:21 localhost.localdomain systemd[1]: Service.service: Refusing to accept PID outside of service control group, acquired through unsafe symlink chain:
/usr/local/apache/logs/Service.pid
Apr 06 12:02:21 localhost.localdomain systemd[1]: Service.service: Refusing to accept PID outside of service control group, acquired through unsafe symlink chain:
/usr/local/apache/logs/Service.pid
Apr 06 12:02:21 localhost.localdomain systemd[1]: Service.service: Failed with result 'protocol'.
Apr 06 12:02:21 localhost.localdomain systemd[1]: Failed to start LSB: Web Server
I dont have much experience in this kind of studff. Any help here would be appreciated.

**Comment by sourcejedi** [comment]
@Deepesh125 this issue thread is not a support channel, e.g. for asking whether RHEL 8's version is expected to include the fix or not.

I have an account on unix.stackexchange.com. You might create a question there, include e.g. the full output of `systemctl cat Service`, and you can send me a link to it by email. My address is alan.christopher.jenkins@gmail.com.
