### ISSUE TITLE
Coredumpd should use Zstandard for compression

### ISSUE THREAD

**Issue by thiagomacieira** [systemd/systemd#8097]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 234

### Used distribution

> OpenSUSE

Currently, coredumpd is able to compress the core dumps with either LZ4 or LZMA (xz), which are extremes of speed (with little compression) and good compresion (at high CPU usage). I propose an intermediary: Zstandard (see https://github.com/facebook/zstd). The default compression level (3) achieves almost double the compression ratio compared to LZ4, reaching almost the default zlib compression, at a minimal increase in CPU usage.

The following tests were done with a handful of coredumps captured by coredumpd. Compression numbers (sorted by compression time):

Type | Size (kB) | Time to compress (s) | Max RSS (kB)
-----|-----------|----------------------|-------------
Uncompressed | 2066980 | N/A | N/A
lz4   | 106836 | 1.55 | 7084
zstd -2 | 57976 | 1.92 | 3192
zstd  | 55152 |  2.14 | 4260
gzip  | 66616 | 19.32 | 1724
xz -0 | 45740 | 24.29 | 4656
zstd -14 | 45956 | 25.14 | 31384
xz -9 | 33456 | 182.56 | 691460

Like other compressors of the LZ family, decompression time is not affected by compression at standard levels, only memory usage. And yet the standard tool requires less than lz4.  Decompression numbers (sorted by time):

Compressor | Time (s) | Max RSS (kB)
-----------|----------|-------------
lz4        | 0:01.03  | 7012
zstd -14   | 0:01.06  | 6284
zstd -2    | 0:01.14  | 2912
zstd       | 0:01.16  | 3256
xz -9      | 0:05.67  | 67696
xz -0      | 0:06.99  | 2420
gzip       | 0:08.36  | 1524

**Comment by poettering** [comment]
definitely would make sense to add!

**Comment by nolange** [comment]
First, Id like to support this feature.

Then... something almost unrelated: would it be possibly to use external tools (zstd, lzma) et all instead of having to link to a compressor library?
Could be even oneway without decompression, at the loss of functionality.

Potential benefits would be a bit RAM saved (one less DSO loaded), some Storage saved if the zstd is installed but the dso is not required (the tool is not linked against the DSO).
And some backdoor to configure compression parameters even if systemd supports the format.

example /etc/systemd/coredump.conf
```
CompressCmd=zstd -19 %I
CompressCmdExt=.zst
```

**Comment by poettering** [comment]
Implemented in ef5924aa313d1892bb491c870ba3c429454dfc76

**Comment by cnlohr** [comment]
For anyone curious who ends up here from a web search, you can disable compression so the dumps can work again with things like VS Code/manual gdb operation by editing `/etc/systemd/coredumpctl.conf` and setting `Compress=no`
