### ISSUE TITLE
After upgrading, it says "Starting version (previous version)"

### ISSUE THREAD

**Issue by betseg** [systemd/systemd#816]
I upgraded systemd from 221 to 222. When booting up it says "Starting version 221". I solved it with running mkinitcpio but occured again when I upgraded to 223.

**Comment by zonque** [comment]
Sure, you need to copy systemd to your initrd, in what ever way your distro achieves this. Not sure what the upstream project has to do with this?

**Comment by kaihendry** [comment]
I upgraded from 223 to 224 with the same results. There must be some problem with Archlinux? https://youtu.be/95oEUAyO0XU

**Comment by zonque** [comment]
I don't see a relation between the original issue and the problem described in the video. In order to make your initrd contain the latest version of systemd, you need to rebuild it. In whatever way this is done with your distribution.

The latter, however, seems to describe a case where the kernel doesn't match the installed modules. Why do you think this is a systemd issue?

**Comment by poettering** [comment]
This really appears to be a distro problem: the initrd needs to be rebuilt after OS upgrades to container the right version of systemd that matches the host. If you don't do that you will of course get the old version there... Will close this now, please bring this up with your distro!
