### ISSUE TITLE
systemd-fstab-generator should ignore bind/move mounts

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#8176]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

229-4ubuntu21.1

verified source in master branch and no special handling for bind/move mounts in fstab-generator

### Used distribution

Ubuntu-16.04

### In case of bug report: Expected behaviour you didn't see

Absence of a warning.

### In case of bug report: Unexpected behaviour you saw

systemd-fstab-generator[73071]: Checking was requested for "/var/ozlabs", but it is not a device.

### In case of bug report: Steps to reproduce the problem

/etc/fstab containing:
/var/ozlabs    /home/ozlabs     none         bind         0 1

**Comment by poettering** [comment]
This warning is generated if the sixth column in your fstab line is non-zero on mounts where file system checking makes no sense, because such a line makes little sense. Please set the sixth column to `0`, so that you don't request fsck on bind mounts...

It's a friendly indication that there's something wrong with your fstab line, and it is right, there really is something wrong with it!

**Comment by grooverdan** [comment]
ah cool. Sorry should of looked up what those meant. Sorry for the interruption.
