### ISSUE TITLE
Do not load x11. The system stops on the boot screen

### ISSUE THREAD

**Issue by Xoppop** [systemd/systemd#8254]
### Submission type
 - Bug report
 

### systemd version the issue has been seen with
systemd-233-7.fc26.x86_64

### Used distribution
Fedora 26

### In case of bug report: Unexpected behaviour you saw

When the system boots, x11 does not start. The system load is stopped by 76%. I can enter into the console ctrl + alt + 9.
From the console it turns out to start x11. In the system boot logs, I did not find anything, there is not even an attempt to start GDM.
The system is loaded over the network, the root is mounted on nfs. So load several other computers, video cards are the same for all.

[cmdline.txt](https://github.com/systemd/systemd/files/1748219/cmdline.txt)
[journal.txt](https://github.com/systemd/systemd/files/1748220/journal.txt)
[systemd-dump.txt](https://github.com/systemd/systemd/files/1748221/systemd-dump.txt)
[systemd-test.txt](https://github.com/systemd/systemd/files/1748223/systemd-test.txt)

**Comment by poettering** [comment]
Sorry, but this is a systemd bug tracker, i.e. one very low level component of the OS. Your issue appears to be way higher up in the stack, and is probably something to contact your distribution about, i.e. the Fedora community. Hence, please talk to them first, and if they find that the actual issue is with systemd they'll escalate it back to us then. 

Thanks you for understanding.
