### ISSUE TITLE
segfaulting app breaks init and the login screen never appears

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#8260]
- Bug report
systemd 237.64-1
linux 4.15.4-1
Arch Linux

A recent rsyslog 8.33.0-1 segfaults on start, which has the effect of locking-up the systemd init process.  This seems to involve some interaction with nftables, in the sense that, though there seems to be nothing wrong with nftables, the systemd screen shows a continuous, alternating, "A start process is running" message, with one process waiting for DefaultTimeoutStartSec and the other process showing "No Limit".  The time-out timer always re-starts.  The start-up never times-out, and the getty@.service never runs.  Disabling the segfaulting rsyslog service allows the system to boot to a login screen, but still...

Do I need to say that the systemd init process should never, ever, "lock-up"?

And, where does that "No Limit" time-out come from?

Perhaps there is some bad interaction between the service files for rsyslog and nftables?  rsyslog.service has "Restart=on-failure", where the process segfaults instantly, and nftables.service has "Before=network-pre.target" where "network-pre" is never reached - but then, maybe that is just a symptom and nothing to do with the problem.

$ cat /usr/lib/systemd/system/rsyslog.service
[Unit]
Description=System Logging Service
Requires=syslog.socket
Documentation=man:rsyslogd(8)
Documentation=http://www.rsyslog.com/doc/

[Service]
Type=notify
PIDFile=/run/rsyslogd.pid
ExecStart=/usr/bin/rsyslogd -n -i /run/rsyslogd.pid -iNONE
StandardOutput=null
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=syslog.service

$ cat /usr/lib/systemd/system/nftables.service
[Unit]
Description=Netfilter Tables
Documentation=man:nft(8)
Wants=network-pre.target
Before=network-pre.target

[Service]
Type=oneshot
ExecStart=/usr/bin/nft -f /etc/nftables.conf
ExecReload=/usr/bin/nft flush ruleset ';' include '"/etc/nftables.conf"'
ExecStop=/usr/bin/nft flush ruleset
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by keszybz** [comment]
nftables has Type=oneshot, which means that has TimeoutStartSec=infinity by default.

This looks like a bug in the way those services are put together. Since neither nftables.service nor syslog.service are defined upstream, this isn't something that we can fix. It's possible that those services trigger some bug in the systemd transaction logic, but there's nothing to suggest that in the information you provided, so most likely systemd is just doing what it was told to do correctly.

Please take it up with your distribution, since they are responsible for putting services together. Thanks for understanding.

**Comment by mbiebl** [comment]
@keszybz if rsyslog segfaults, any log message will trigger a start of syslog.service via syslog.socket. I vaguely remember, that we rate-limiting of socket activated services did not work properly when I last encountered this, so systemd tried to start syslog.service over and over again in a loop. I'm not sure if that is fixed today. Should probably be easy to test though, by enabling ```ForwardToSyslog=yes``` and having a dummy syslog.service with ExecStart=/bin/false or so

**Comment by thx1111** [comment]
> Thanks for understanding.

"Bottom line", though, no matter what the excuse, is that systemd init can block indefinitely, making the machine practically unusable.

And you want to blame this on someone else?!  Are you a child?

If you were to argue that systemd is just a programming environment, and that there exists a programming error in the service file "programs", then, what - specifically - is this programming error?

Even still, we shall say that systemd is "fragile", and breaks easily and catastrophically, which is indicative of bad design, and inexperienced designers.

It might be easier to simply guarantee that getty@.service will *always* be run, no matter what the circumstances or the state of the system.

**Comment by poettering** [comment]
> I vaguely remember, that we rate-limiting of socket activated services did not work properly when I last encountered this, so systemd tried to start syslog.service over and over again in a loop. I'm not sure if that is fixed today.

Please file a bug about this, if this is reproducible, and we'll look into this

**Comment by poettering** [comment]
> And you want to blame this on someone else?! Are you a child?

This isn't helpful. 

Please understand that we have a massive workload to deal with. To keep things manageable, we generally prefer if issues are propagated to us by downstreams if they are confirmed to actually be in systemd and not solely caused by problematic configuration. Thus, whenever we get vague bug reports like yours about a complex combination of third party software we prefer if you'd first contact your downstreams about this, since downstreams are in the business of combining software to form a distribution and deal with the integration issues that are caused by that, and we are not, we just build a set of building blocks. 

We are not saying that there wasn't a bug in systemd here, we are simply asking you to contact the more appropriate forum for help first and let them propagate things to us if they actually find something wrong in systemd, and can provide a specific description and maybe a reproducer.

Thank you for understanding.

**Comment by mbiebl** [comment]
> Please file a bug about this, if this is reproducible, and we'll look into this

I'll put that on my long list of TODOs :-)
