### ISSUE TITLE
ConditionFirstBoot=true does not fire if /etc/machine-id is present but empty

### ISSUE THREAD

**Issue by superseed** [systemd/systemd#8268]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> Any until now, according to the code

### Used distribution

> Slightly altered Ubuntus

### In case of bug report: Expected behaviour you didn't see

> Units with `ConditionFirstBoot=true` should be started when `/etc/machine-id` exists but is empty.

> systemd currently decides that it is in a state of first boot (which will trigger `ConditionFirstBoot`) [only if `/etc/machine-id` is not present](https://github.com/systemd/systemd/blob/30663b6c256b9efe3f626094ceb85d35bf65d206/src/core/main.c#L1777L1785). Including the case where `/etc/machine-id` is present but empty would more closely match [the options given for the generation of a machine-id on a first boot](https://github.com/systemd/systemd/blob/28e176cc2df83368d52151dd702bf8773c6afd28/src/core/machine-id-setup.c#L122L127), i.e. `/etc/machine-id` not present with `/etc` writable, or `/etc/machine-id` present but empty, in which case a machine-id is generated and committed later. systemd-tmpfiles also considers an empty `/etc/machine-id` to equate an unpopulated `/etc` since [this commit](https://github.com/systemd/systemd/commit/d8dab75789ec1ffd53fc06f5f370220ae7b31d9d). Finally, it would allow for setups where the bootloader boots into the system with read-only mounts (later remounted read-write by systemd's remount filesystems service) including `/etc` and a service that starts on first boot only (using `ConditionFirstBoot`) is needed for setup purposes using systemd's builtin facilities.

### In case of bug report: Unexpected behaviour you saw

> Units with ConditionFirstBoot=true weren't started

### In case of bug report: Steps to reproduce the problem

> Boot a systemd distribution with `/etc/machine-id` present but empty and services with `ConditionFirstBoot=true`.

**Comment by bl33pbl0p** [comment]
This will break systemd-firstboot.service. The current mechanism is (also read machine-id(5) for details):
* Empty /etc means no machine-id, ConditionFirstBoot is true and firstboot wizard is fired for setup.
* Empty /etc/machine-id, which means if you are rolling images, you can drop an empty /etc/machine-id and it will be populated on the first boot but no wizard would be run, if /etc is read-only, a temp file is bind mounted there.

Making ConditionFirstBoot= also do the latter breaks the current way of doing things. systemd-firstboot.service itself relies on it and will otherwise fire with an empty machine-id even when that is not desired.

Empty machine-id is populated at boot anyway, see https://www.freedesktop.org/software/systemd/man/machine-id.html

You could instead use ConditionFileNotEmpty=!/etc/machine-id for your use case (or extend firstboot if you require that). There is also systemd-machine-id-setup to do this while making images.

**Comment by superseed** [comment]
It would indeed mean that systemd-firstboot would run when `/etc/machine-id` exist but is empty, but I don't see how that's a problem ?

From the docs and sources, I understand that "this is the first boot" really means "there is no machine-id here yet". What I'm asking is "`/etc/machine-id` exists and is empty" to also mean "there is no machine-id", as "`/etc/machine-id` isn't present" does. To me, those statements are equivalent.

**Comment by superseed** [comment]
I know they are considered differently, and this is precisely what I am objecting. Why would you not want the case where `/etc/machine-id` is empty to be considered a first boot ? I am deploying server images and what I need is the first boot of a server from these images _to actually be considered a first boot_.

I would argue that it makes more sense to opt-in to not having `systemd-firstboot` run on an actual first boot by disabling `systemd-firstboot` itself in the image.

Also, `ConditionFileNotEmpty=!/etc/machine-id` won't work in this case since [one of the first things](https://github.com/systemd/systemd/blob/848e863acc51ecfb0f3955c498874588201d9130/src/core/main.c#L2370) `systemd` does is setting up `/etc/machine-id`, before resolving conditions, which means there will be something in it.

I would rather have `systemd` say it's a first boot, and happily use the condition in my units, or check the flag file, etc.

**Comment by cgwalters** [comment]
> There is a usecase where you don't want the interactive firstboot program to run and want the machine-id to be populated without it, 

Yeah, this is a definite concern; empty machine ID but not wanting firstboot (and presets) is exactly the situation that e.g. current Fedora Atomic Host is in, and I think the "classic" Fedora Cloud Base image.  Based on what you're saying we're not alone.

Of course if it had worked this way from the start we'd almost certainly have adapted and been ready, but I know for a fact some of our setup is not ready for the system to be preset from scratch (we write units in `/etc` not `/usr` at image time).

So...in the end we may need some sort of opt-in behavior here.

> Also, ConditionFileNotEmpty=!/etc/machine-id won't work in this case since one of the first things systemd does is setting up /etc/machine-id, before resolving conditions, which means there will be something in it.

Ugh, yeah.  How about `systemd.image_machine_id=1` kernel cmdline argument  (bikeshed on naming here) to mean "treat empty /etc/machine-id as `ConditionFirstBoot`).  Or at least for our case (Fedora CoreOS) we could easily change the initramfs to pass a file in `/run` or whatever too.

**Comment by poettering** [comment]
So, currently the protocol implemented by systemd is this:

1. If /etc/machine-id exists and is populated, we use it and all is good. We'll not assume this to ba a first-boot case. Let's call this the `POPULATED` state.

2. If /etc/machine-id is missing entirely, we will populate it if we can. [If we can't (because read-only) we fail.] This case we'll consider a first-boot case. Let's call this the `UNPOPULATED` state.

3. If /etc/machine-id exists but it is empty, we'll write a new machine ID into it (case 3a). If this fails (because read-only), we'll over-mount it with a temporary one (case 3b). In the latter case, during boot the `systemd-machine-id-commit.service` runs after the file system was changed to writable, and it will try to atomically write the temporary one to disk, to the file underneath the over-mount (case 3c). This is graceful: if it works it works, if it doesn't we won't fail. Let's call this the `EPHEMERAL` state (which sometimes can be changed into POPULATED). We do not consider this a first-boot case.

The use-cases the above covers are the following:

a. After a factory reset /etc is entirely empty but for the future persistent. We basically start from zero, but only once. This uses case 2. i.e. we are initially UNPOPULATED, and future boots are POPULATED.

b. You build an immutable image coming up from zero on each boot, with an /etc entirely empty, but on a tmpfs and modifiable during runtime. This uses case 2 as well. Each boot will be UNPOPULATED.

c. You build an entirely immutable image, but with an otherwise configured /etc. Because it is immutable, a new machine ID is generated on each boot that is valid for exactly that one boot. It can't be written to /etc though because that is read-only. This uses case 3b. Each boot will be EPHEMERAL.

d. You build a golden image that is fully set up, and configured, and shall be fully writable during runtime. Consider a distro installer for example, that sets up a traditional distro, by dd'ing or untarring some ready-made image onto disk. This  either comes up writable from the beginning (case 3a) or comes up read-only initially, but is mounted writable during boot (case 3c). It will be EPHEMERAL first, and then is converted to POPULATED.

Now, you want to change the protocol so that case 3a, 3b, 3c are thrown away. I think that's a big loss, as this makes usecases c and d impossible, and I think they matter a lot. 

What I don't get about your usecase: what's the point of shipping the file at all in your case? I mean, the only reason why an empty but existing file is something we care for is so that we can over-mount it in case we are read-only during early boot. But in that case assuming "first boot" state, and thus doing the whole unit file preset logic is not gonna work anyway, as that stuff is about making changes to /etc. So, let me ask you explicitly: why would you create the file in /etc if you create it empty and if you are not interested in read-only operation?

**Comment by poettering** [comment]
> Ugh, yeah. How about systemd.image_machine_id=1 kernel cmdline argument (bikeshed on naming here) to mean "treat empty /etc/machine-id as ConditionFirstBoot". Or at least for our case (Fedora CoreOS) we could easily change the initramfs to pass a file in /run or whatever too.

But why? Why do you want to create /etc/machine-id empty in your case? Why not just not have it at all? I really don't get it...

**Comment by boucman** [comment]
bind mounting a file from a R/W partition on top of it, maybe ?

**Comment by cgwalters** [comment]
As far as I know, no Fedora edition/artifact shipped upstream has ever made use of `ConditionFirstBoot=`.  

It doesn't happen with per-user Anaconda because there the system is configured *before* rebooting, in fact by [this bit in the systemd.spec %post](https://src.fedoraproject.org/rpms/systemd/blob/5306894742943e5d46ac705a3f2d5db1a48a0a67/f/systemd.spec#_480).

And while we also use Anaconda to generate our "golden images" for cloud environments (Fedora Atomic Host, Fedora Cloud Base), we have always been doing an empty machineid (overriding that `%post): [cloud base kickstart](https://pagure.io/fedora-kickstarts/blob/66d587dc5471dde149f7a71427185218bb0d8a3a/f/fedora-cloud-base.ks#_254) and for FAH the status quo is from [this commit](https://github.com/projectatomic/rpm-ostree/commit/3bf7926adc9e72f7f6bb0593b8ac201f524b1a02) until recently we [support the empty case](https://github.com/projectatomic/rpm-ostree/pull/1425).

Now here's another fact: All Fedora systems today have the rootfs handled "traditionally" - mounted read-write via `systemd-remount-fs.service`.

And combining these two facts, we arrive at the problem that the original poster wrote here:

> Finally, it would allow for setups where the bootloader boots into the system with read-only mounts (later remounted read-write by systemd's remount filesystems service) including /etc and a service that starts on first boot only (using ConditionFirstBoot) is needed for setup purposes using systemd's builtin facilities.

Now, as we switch to Fedora CoreOS and adopt Ignition, the model requires us to mount the rootfs writable in the initramfs.  And hence avoiding this problem.

But, I agree with the OP that we shouldn't require conflating having the rootfs mounted `rw` at switchroot time with "no firstboot".

**Comment by cgwalters** [comment]
Now, you listed a rather head-spinning variety of use cases.  I'm honestly not sure I'd agree *every* one of those makes sense but let's set that aside for now.  It seems clear to me the most conservative path is to add a 4th state for `/etc/machine-id` that is *explicitly* asking to opt-in to firstboot, even if `/` isn't yet writable.

State `4)` is exactly like `3` except it begins with: "If /etc/machine-id exists but contains the contents `firstboot`..."

**Comment by poettering** [comment]
> Finally, it would allow for setups where the bootloader boots into the system with read-only mounts (later remounted read-write by systemd's remount filesystems service) including /etc and a service that starts on first boot only (using ConditionFirstBoot) is needed for setup purposes using systemd's builtin facilities.

This can't work. When the first-boot condition is set two things happen:

 1. before putting together the initial transaction (i.e. really really early on) systemd will do more or less what `systemctl preset-all` does. 
 2. services marked with ConditionFirstBoot= are run

Now, of these two, the first one (which from systemd's PoV is kinda the main one) only works if /etc is writable that early already. This however also means that /etc/machine-id doesn't have to exist, as it can be created just fine.

What you are looking for is apparently a first boot mode where 1 doesn't happen but 2 still does?

**Comment by cgwalters** [comment]
> What you are looking for is apparently a first boot mode where 1 doesn't happen but 2 still does?

Nope, we want `1` too.  I think the implementation path here would be to invoke `systemd-remount-fs` very early on.

Or honestly, maybe we decide here that the simplest thing is just to change to having the initramfs mount `/` as `rw` by default for anyone who wants to make use of `ConditionFirstBoot=`.  I'd probably be fine with that.

**Comment by poettering** [comment]
> Nope, we want 1 too. I think the implementation path here would be to invoke systemd-remount-fs very early on.

that's a chicken and egg issue: you want to run a service before when run the first services ;-)

**Comment by poettering** [comment]
> Or honestly, maybe we decide here that the simplest thing is just to change to having the initramfs mount / as rw by default for anyone who wants to make use of ConditionFirstBoot=. I'd probably be fine with that.

This is what you really should do. There's no real value anymore in starting out read-only if you have an initrd, which will fsck the root fs anyway before mounting it. Just make it simple, and mount it writable right away. That's what the first-boot protocol is designed for.

> EDIT: Or maybe what we should do is change systemd in the initramfs to check before pivoting whether /sysroot/etc/machine-id exists, and if it doesn't, remount / as rw?

But why? It's much simpler if you just mount the root dir writable anyway, there's no point in mounting it readonly and then immediately writable right after.

**Comment by cgwalters** [comment]
OK, so e.g. anyone using dracut should specify e.g. `rootflags=rw` in their initial kernel commandline.  Seems straightforward.  I guess the thing I just have to wrap my head around is that changes a longstanding "tradition".

@superseed - can you do that for your use case too?

I just looked at [the code we're using for Fedora CoreOS](https://github.com/dustymabe/ignition-dracut/blob/master/dracut/30ignition/ignition-remount-sysroot.service) and (derived from a Container Linux comment) it looks like at least some bootloaders inject `ro` by default.   Doesn't look like it affects us today but a gotcha to look out for for people trying this out.

BTW Lennart - while we shouldn't grow the scope of this issue too much, do think about all the implications if we were to try to do `ConditionFirstBoot=` by default with Fedora + Anaconda today.  One thing that would immediately break is everyone doing e.g. `systemctl enable` in Kickstart `%post` which is a whole lot of people I'm sure.  Unless we basically had a mode where we turned `systemctl enable` into preset invocations...which brings us right to issues like [this one](https://github.com/systemd/systemd/issues/9476).  Even without thinking through user-derived kickstarts, we'd have to walk over all the bits of code involved in the installation path and change them to write to `/usr` rather than `/etc`, and that's a nontrivial set.  Perhaps in the big picture Anaconda simply conflicts with `ConditionFirstBoot=` - it's trying to configure things *before* booting the first time (which has definite advantages too though).

**Comment by cgwalters** [comment]
Hm, a reading of [the code in dracut](https://github.com/dracutdevs/dracut/blob/99df3d22be14690260371311086a439c83fdc6b4/modules.d/99fs-lib/fs-lib.sh#L225) here looks like `rootflags=rw` won't work¹, one needs the classic `rw`.  But it'd probably be easy to fix.

¹ or at least one would end up with `ro,rw` and I'm not sure which wins

**Comment by poettering** [comment]
> OK, so e.g. anyone using dracut should specify e.g. rootflags=rw in their initial kernel commandline. Seems straightforward. I guess the thing I just have to wrap my head around is that changes a longstanding "tradition".

Hmm, isn't it systemd-fstab-generator that parses root= on dracut? I though it was. Are you sure that dracut overrides that? @haraldh?

But yeah, systemd-fstab-generator defaults to "ro", too, currently.

**Comment by poettering** [comment]
> BTW Lennart - while we shouldn't grow the scope of this issue too much, do think about all the implications if we were to try to do ConditionFirstBoot= by default with Fedora + Anaconda today. One thing that would immediately break is everyone doing e.g. systemctl enable in Kickstart %post which is a whole lot of people I'm sure. Unless we basically had a mode where we turned systemctl enable into preset invocations...which brings us right to issues like this one. Even without thinking through user-derived kickstarts, we'd have to walk over all the bits of code involved in the installation path and change them to write to /usr rather than /etc, and that's a nontrivial set. Perhaps in the big picture Anaconda simply conflicts with ConditionFirstBoot= - it's trying to configure things before booting the first time (which has definite advantages too though).

So, yes, I doubt that marrying Anaconda with the first-boot concept is really desirable. While I personally would always design my systems with a first-boot concept in mind, it's entirely OK to fully set up the system in advance and not use the first-boot logic. And that's what Anaconda does.

The first-boot concept is nice if you want to be able to bring up the system nicely with an empty /etc or /var (or in fact empty root dir except for /usr). It's also nice if you want to minimize your installer codebase, as it means you can "minimally" populate /etc (where "minimally" can also mean "completely empty"), and everything else happens on the first boot fully automatically. But if neither of that is what you want to do, then there's no point in making use the first-boot logic.

I mean, I'd love to see Fedora adopt all this fully, i.e. so that it's officially supported to boot with entirely empty /var and /etc (i.e. tmpfiles.d/ and sysusers.d/ all the way), but the convincing necessary, the politics involved with making such a major kinda scared me away...

**Comment by jlebon** [comment]
> before putting together the initial transaction (i.e. really really early on) systemd will do more or less what `systemctl preset-all` does.
>
> Now, of these two, the first one (which from systemd's PoV is kinda the main one) only works if /etc is writable that early already.

I noticed that as well yesterday and concluded that indeed requiring the rootfs to be r/w at switchroot is reasonable given the circumstances.

Both `rw` and `rootflags=rw` seem to work on Fedora 28 at least.

**Comment by poettering** [comment]
OK, so let's close this then, as existing but empty /etc/machine-id already has a meaning and we shouldn't redefine it as it has good usecases. Hope this makes sense.

**Comment by superseed** [comment]
Sorry, I just realized there had been some movement on this issue.

@poettering, to answer your question:
> But why? Why do you want to create /etc/machine-id empty in your case? Why not just not have it at all? I really don't get it...

I'm in case d, where I build golden images ready-to-be-used. But my problem is that before the `systemd-remount-fs` service is started, `/etc` will be read-only because that's how the bootloader mounted it, and early init leaves it like that. As per your explanation, `systemd` will fail and complain that `/etc` is read-only. I would need to edit early init behavior in all distribs shipped (not necessarily dracut-based) to have `/etc` read-write at that point. That doesn't seem like the right thing to do, so I went with the "empty `/etc/machine-id`" route and expected it to work.

@cgwalters Did you end up using an initramfs `rw` option in your use case ?

**Comment by cgwalters** [comment]
> @cgwalters Did you end up using an initramfs rw option in your use case ?

Yes, Fedora CoreOS will use that approach.

I struggle a bit actually to remember why in Unix tradition the filesystem started out `ro` - among other things with journaling filesystems it's not truly `ro` anyways.  Does anyone know?

**Comment by superseed** [comment]
Thanks, I guess it's either that or not using `ConditionFirstBoot`, but I'm really reluctant at overriding shipped distribution behavior.

Good question really. I believe it's due to the real init possibly needing to run `fsck`s on the filesystem and other operations of that nature?
