### ISSUE TITLE
--output json doesn't produce json output

### ISSUE THREAD

**Issue by joejulian** [systemd/systemd#83]
Many systemctl commands do not produce json output when --output json is set.

```
# systemctl -o json list-dependencies glusterd
glusterd.service
● ├─system.slice
● └─basic.target
●   ├─alsa-restore.service
●   ├─alsa-state.service
●   ├─dnf-makecache.timer
●   ├─fedora-autorelabel-mark.service
●   ├─fedora-autorelabel.service
●   ├─fedora-loadmodules.service
●   ├─firewalld.service
●   ├─paths.target
●   ├─slices.target
●   │ ├─-.slice
●   │ └─system.slice
●   ├─sockets.target
●   │ ├─avahi-daemon.socket
●   │ ├─cups.socket
●   │ ├─dbus.socket
●   │ ├─dm-event.socket
...
```

**Comment by keszybz** [comment]
From the manpage: -o: When used with status, controls the formatting of the journal entries that are shown.

**Comment by joejulian** [comment]
It would still be nice if it would produce machine readable outputs for better integration with tools like saltstack, puppet, or any other user created tool that wants to do something with the output.

**Comment by eliasp** [comment]
Although I agree that `-o json` should return proper JSON,  believe the proper way for external tools like SaltStack etc. to talk to systemd is DBus. See also https://github.com/saltstack/salt/issues/20392 - everything else is more or less just hack-ish and prone to break easily.

**Comment by keszybz** [comment]
Some of the verbs implemented by systemctl are designed to provide a high-level overview in a human readable format. All that information is available over dbus, and/or journalctl, systemctl show. We _could_ provide that information in json format, but there's a second problem. Information and format of information printed by e.g. systemctl status is not stable. Since the output is not suitable for programmatic consumption anyway, there's no need to provide it in a machine readable format.

But for things like 'list-dependencies', output _is_ simple enough that we could add the ability to dump it in json format. In principle, this information is already available through other means, but it is actually a fair amount of work to gather it in this form, and I think it could be useful to open it up to programmatic consumption. I'm not going to work on this myself, but if somebody comes up with a patch, I'd be happy to review and merge.

**Comment by poettering** [comment]
I am not convinced adding JSON for all of this is really a good idea. I mean, I am all for providing good APIs to integrate systemd's concepts with other projects, but I'd try to keep things minimal there, and focus on as few sets of APIs as possible, but then keep the quality of them high. Now, for scripting languages I am pretty sure the bus APIs are the best option. The largest part of our APIs is exposed via dbus. The journal is an exception, for performance reasons much of it happens on the client side, hence it probably makes sense to support the JSON exporting for it directly. However, that really doesn't mean we should expose everything else in JSON too... In particular as JSON itself is a just a passive format, and not a real RPC... If we'd want to turn it into one we'd need REST and HTTP and whatnot, and I am not really sure we should cover all that in systemd itself...

**Comment by njam** [comment]
What is the recommended API to retrieve _dependencies_ of a unit/target?
I can't find anything on the [D-Bus interface](https://www.freedesktop.org/wiki/Software/systemd/dbus/), is there something else?

**Comment by poettering** [comment]
@njam please direct questions like yours to the proper channels, i.e. the systemd mailing list. Random github issues are really not the place to ask such questions.

**Comment by njam** [comment]
@poettering sorry about that!
-> https://lists.freedesktop.org/archives/systemd-devel/2016-August/037401.html

**Comment by MrM40** [comment]
I don't think it's a good argument, that just because you can retrieve the information from the lower level dbus interface, that it shouldn't be possible to provide these information from a JSON output.
If that argument were valid, then you can say, that you can always get any data from a lower-level source all down to reading raw machine code, hence no output-tools is necessary at all incl. systemctl

dbus is not that simple to use, that's why so "many" is asking for an JSON option. 
And "many" end up doing all kind of ugly conversion solutions from the std. output to JSON.....if it was so easy to retrieve data from dbus they wouldn't bother, but they do.

In my own case I make heavily use of systemctl in my C# applicaiton. I did try to go the dbus-way, but I simple gave up. My conclusion was it would take longer time to get working than making ugly serialization of the human-output of systemctl which I ended up doing. It seems, judging by a web-search and threats in here, that I'm not the only one.

**Comment by rokejulianlockhart** [comment]
Why doesn't `systemctl` at least produce an error? `hostnamectl` does.

**Comment by spirobel** [comment]
so systemctl list-units --output json
works but systemctl status doesnt ....

come on guys .... you were so close  @poettering

**Comment by Torxed** [comment]
> I am all for providing good APIs to integrate systemd's concepts with other projects, but I'd try to keep things minimal there

The issue is that systemd has become a vital part of so many lives at this point.
That you are bound to need output from systemd in one way or another.

And people *(including myself)* finds ourselves doing things like: https://github.com/archlinux/archinstall/blob/495fffe70a6ebc0b856acd02f9de388d6c6ac5d3/archinstall/lib/locale/utils.py#L9-L12

And it's a brittle way of interacting between two systems, parsing human readable strings are bound to be a bad idea. And we really need machine - to - machine readable formats to properly do things.

JSON is a pretty standardized output format, and there's really solid libraries to output to it too.

**Comment by tjstebbing** [comment]
Many systems don't want to use dbus, I agree that the above arguments are poor, -o json is a documented feature that doesn't work in the obvious way people expect it to, and `systemctl status` specifically is just weird with mixed json/text output and the json itself that's outputted doesn't even parse as it's not formatted as an array.

**Comment by poettering** [comment]
We nowadays generate JSON output in a ton of our commands. If you are missing JSON output in some, by all means send a patch.

**Comment by gbraad** [comment]
FYI

### EL9 (like AlmaLinux) does not:
```
$ systemctl --version
systemd 252 ...
$ systemctl status --output json --no-pager
● [hostname]
    State: running
    Units: 117 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
    Since: Mon 2025-03-17 15:09:43 CST; 3h 6min ago
  systemd: 252-46.el9_5.2.alma.1
   CGroup: /
```

### Fedora 41 does not:
```
$ systemctl --version
systemd 256 ...
$ systemctl status --output json --no-pager
● [hostname]
    State: degraded
    Units: 672 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 2 units
    Since: Sat 2025-01-11 00:07:20 CST; 2 months 4 days ago
  systemd: 256.11-1.fc41
   CGroup: /
           ├─init.scope
...
```
