### ISSUE TITLE
systemctl: complain if unit name mangling is used

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#8302]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> archlinux, centos7

### In case of bug report: Expected behaviour you didn't see

> instance units unescape the instance name correctly when using `%I`

### In case of bug report: Unexpected behaviour you saw

> instance units replace `-` characters in the instance name with `/` when using `%I`

### In case of bug report: Steps to reproduce the problem

> Create an instance unit that uses `%I`
> Pass an instance name using a path like `foo-bar`
> `%I` will be incorrectly unescaped to `foo/bar`

[See this gist](https://gist.github.com/zfjagann/adfe79645837169fbf09fb40066b15ab)

This works, however if you run the instance name through `systemd-escape` first, which leads me to believe that instance names aren't being escaped in the same way.

**Comment by filbranden** [comment]
This is working as intended.

See [systemd-escape](https://www.freedesktop.org/software/systemd/man/systemd-escape.html) for more details.

```shell
$ systemd-escape --unescape foo-bar
foo/bar
```

Why do you think this is a bug? Why can't you use `%i` instead if you don't want the unescaping?

**Comment by kalgynirae** [comment]
The title of the issue is a bit misleading. It seems the *escaping* that `systemctl` performs on its command-line arguments is wrong. If I `systemd-escape foo-bar/baz`, I get `foo\x2dbar-baz`. Why then does `systemctl start hello@foo-bar/baz` end up escaping it as `foo-bar-baz`, rather than escaping it the same way `systemd-escape` does?

**Comment by zfjagann** [comment]
@filbranden The escaping isn't working as intended though. `%i` should be an escaped string, and `%I` should be the instance name verbatim, with no escaping. That's clearly not the current behavior, since `%I` is different from the instance name provided.

It seems like `systemctl` (or systemd) should escape the instance name with `systemd-escape` but it's not doing that since the escaped string (`%i`) is different from what `systemd-escape` returns provided the same string.

@kalgynirae :+1: I fixed the title, thanks. :)

**Comment by boucman** [comment]
maybe systemctl should print a warning... what you said makes perfect sense, but is hard to discover and understand through experiment.

**Comment by kalgynirae** [comment]
Agreed, a warning from systemctl like "mangling invalid unit name (maybe you should use systemd-escape?)" would go along way toward making this behavior understandable.

**Comment by poettering** [comment]
> maybe systemctl should print a warning... what you said makes perfect sense, but is hard to discover and understand through experiment.

Well, I think people would complain loudly if we'd start complaining that "systemctl start httpd" now results in a warning message because it wasn't written as "systemctl start httpd.service". I mean, we added that in the first place because people complained so hard they had to fully specify a unit name with the .service suffix... And I figure all those folks would come back and complain if we'd start again to complain.

Also note that the mangling has some other tricks up its sleeve. For example if I do "systemctl status /boot", then it will use ".mount" as a suffix here, i.e. generate "boot.mount" from this, i.e. absolute paths are converted to mount unit names rather than service names.

**Comment by kalgynirae** [comment]
The other types of mangling are intuitive and documented in the `systemctl` man page (under Parameter Syntax). It's only the changing-slashes-into-hyphens type of mangling (in unit names that are not absolute paths) that is not intuitive (in my opinion) and also not mentioned in the man page. Is it possible to add the warning only for that specific type of mangling?
