### ISSUE TITLE
man: on split-usr systems all paths in man pages are wrong

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8359]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Linux From Scratch

### In case of bug report: Expected behaviour you didn't see

> The file `/usr/lib/systemd/resolv.conf`, mentioned in the manual page systemd-resolved(8), is missing.

### In case of bug report: Unexpected behaviour you saw

> Only `/lib/systemd/resolv.conf` is installed.

### In case of bug report: Steps to reproduce the problem

> Build systemd and install it on a system with `/usr` not merged yet.

**Comment by paulmenzel** [comment]
```
$ git grep "/usr/lib/systemd/res"
NEWS:          this DNS server is now shipped in /usr/lib/systemd/resolv.conf. It is
man/resolved.conf.xml:    <para><filename>/usr/lib/systemd/resolved.conf.d/*.conf</filename></para>
man/systemd-resolved.service.xml:      <listitem><para>A static file <filename>/usr/lib/systemd/resolv.conf</filename> is provided that lists
src/nspawn/nspawn.c:#define STATIC_RESOLV_CONF "/usr/lib/systemd/resolv.conf"
```

**Comment by floppym** [comment]
The systemd developers have basically refused to make the manpage text conditional on the split-usr option. This issue is very unlikely to be fixed.

**Comment by floppym** [comment]
I should revise that: there have been several attempts in the past to make the documentation match the configure options, but nothing seems to have "stuck".

For example: https://github.com/systemd/systemd/pull/903

**Comment by poettering** [comment]
Uh, I am not sure whether it's a good idea fixing that. We couldn't fix this properly anyway, since a large chunk of people will google for docs instead of looking into the man pages of the relevant installed systems. 

I think split-usr systems are fine to support, but let's not go too far with that. I am pretty sure split-usr is the past really, and we should gently push downstreams to go for unified-usr instead, and I think this is one very gentle way, given that nothing really breaks...

**Comment by keszybz** [comment]
The time to fix this has passed, I agree. Even Debian does not support boot with /usr mounted late now [see https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#late-mounting-usr], which means that for all intents and purposes `/usr/lib/systemd/resolv.conf` is **not** missing. Whether the path is really `/usr/lib/systemd/resolv.conf` or `/lib/systemd/resolv.conf`is an unimportant implementation detail. We should continue to describe just the merged-/usr paths, and finish the transition.

**Comment by LorenzoAncora** [comment]
> Whether the path is really /usr/lib/systemd/resolv.conf or /lib/systemd/resolv.confis an unimportant implementation detail.

@keszybz I recently had difficulty finding the file and, considering that those who want to use it are still configuring internet access (and therefore may not have a way to see the online documentation), it would be a good idea to make an exception and update the manual, specifying all possible filesystem paths.
I say this because the average user will probably try:
```
find / usr -name resolv.conf -type f
```
...and he/she is unlikely to look for a configuration file in `/lib`.
You should not forget that not all users are systemd powerusers and a detailed manual can save their time. ;-)
