### ISSUE TITLE
A combination of BindsTo and KillMode=control-group may prevent a unit from restarting

### ISSUE THREAD

**Issue by exg** [systemd/systemd#8374]
### Submission type
 - Bug report

### systemd version the issue has been seen with
systemd 237

### Used distribution

Manjaro

### In case of bug report: Steps to reproduce the problem
I have a system composed of a main service A and a service B on which A depends. service A unit file is as follows:
```
[Unit]
Description=ServiceA
Requires=serviceB.service
After=serviceB.service

[Service]
Type=simple
ExecStart=serviceA
Restart=always
KillMode=control-group

[Install]
WantedBy=multi-user.target
```
While service B unit file is
```
[Unit]
Description=ServiceB
BindsTo=serviceA.service

[Service]
Type=simple
ExecStart=serviceB
Restart=always

[Install]
WantedBy=multi-user.target
```
Note that serviceB binds to serviceA. Also, Service A creates child processes. Now, if I 'kill -9' the main (parent) process of serviceA, the service enters failed state, despite having specified 'Restart=always'. Instead, if service A does not create any child process, the service **does** get restarted. This issue seems to be caused by the fact that either
1. serviceB binds to serviceA, or
2. serviceA KillMode is set to control-group

or the combination thereof. Indeed, the issue does not occur if I either change KillMode to 'process' in serviceA or change 'BindsTo' to 'PartOf' in serviceB. Here is a minimal example of serviceA and serviceB that I used to reproduce the issue:
ServiceA
```
#include <unistd.h>
int main(int argc, char **argv)
{
    pid_t pid = fork();
    if (pid < 0)
        return 1;
    pause();
    return 0;
}
```
ServiceB
```
#include <unistd.h>
int main(int argc, char **argv)
{
    pause();
    return 0;
}
```

**Comment by arvidjaar** [comment]
> the issue does not occur if I either change KillMode to 'process' in serviceA 

This is red herring and likely simply changes relative timing

> ...  or change 'BindsTo' to 'PartOf' in serviceB

And that is the real reason. `BindsTo` causes systemd to stop serviceB when serviceA fails and this causes it to also queue stop request for serviceA due to `Requires` directive. (Explicitly) stopping service disables restart logic. Replacing `BindsTo` with `PartsOf` skips this implicit stop request.

I am not sure this is a bug. You have circular dependencies (A requires B and B requires A). I do not see how it can reasonably be handled.

**Comment by exg** [comment]
> And that is the real reason. BindsTo causes systemd to stop serviceB when serviceA fails and this causes it to also queue stop request for serviceA due to Requires directive. (Explicitly) stopping service disables restart logic. Replacing BindsTo with PartsOf skips this implicit stop request.

Understood, thanks. I suspected this was the case, but the fact that this is racy made the behaviour non obvious.

> I am not sure this is a bug. You have circular dependencies (A requires B and B requires A). I do not see how it can reasonably be handled.

I am not sure either. However, systemd could at least handle this case consistently by always failing, if possible.

**Comment by poettering** [comment]
Yeah, the bindto means the a stop request is explicitly propagated and that cancels the effect of Restart=. This is a pretty racy affair all in all, since B is ordered before A but binds to it. i.e. on one hand you say "B should die if A isn't around", but at the same time you say "make sure to run B before A, i.e. at a time A isn't running yet". Hence you immediately trigger a race there....
