### ISSUE TITLE
Why /run/systemd/netif* directories are created always

### ISSUE THREAD

**Issue by rudimeier** [systemd/systemd#8443]
networkd tmp files are created by default in `tmpfiles.d/systemd.conf` and require to have user `systemd-network` even though networkd is disabled on the host.

For me it looks like the daemon is able to create them alone. Or at least the unit file should use RuntimeDirectory=.

**Comment by poettering** [comment]
This is because the stuff in libsystemd-network/ uses the runtime dir as inotify-based API and it should really work unconditionally, even if networkd isn't running yet.

That said, there's #5513, which is supposed to split this into its own tmpfiles snippet, so it can be packaged independently. That PR is kinda dead though. If anyone cares please submit an update PR for it, and we can merge it.

**Comment by rudimeier** [comment]
On Tuesday 20 March 2018, Lennart Poettering wrote:
> This is because the stuff in libsystemd-network/ uses the runtime dir
> as inotify-based API and it should really work unconditionally, even
> if networkd isn't running yet.

I do not mean case "not running yet" but "running never/disabled". Users 
of the inotify-based API should probably check if the directory exists 
before using it.

> That said, there's #5513, which is supposed to split this into its
> own tmpfiles snippet, so it can be packaged independently. That PR is
> kinda dead though. If anyone cares please submit an update PR for it,
> and we can merge it.

Packaging networkd separately would be nice for distro cosmetics. 
However it would be also nice to be able to *completely* disable a 
service even though it is installed.

I thought systemd cares about "on-demand" etc.

**Comment by poettering** [comment]
> I do not mean case "not running yet" but "running never/disabled". Users of the inotify-based API should probably check if the directory exists before using it.

Well, that's extremely nasty to do with inotify: watching the creation of a directory you want to watch. In general: it's just one directory, that we consider part of an API, and it really shouldn't matter much if it exists or not.



> I thought systemd cares about "on-demand" etc.

Well, you can opt to not start networkd and all will work fine. It's just that one directory that will always be created, that's not really that bad, is it? 

We basically have these two options:

1. teach libsystemd-network to watch the prefix of the dir to watch, which is nasty to develop, and creates redundant wakeups as this means potentially watching the root dir and /run for dirs to be created.

2. just create the dir anyway, even if it will never be needed.

We opted for 2, because it's so much simpler and safer, and the price to pay for it is diminutive. I hope that makes some sense?

**Comment by rudimeier** [comment]
On Wednesday 21 March 2018, Lennart Poettering wrote:
> > I do not mean case "not running yet" but "running never/disabled".
> > Users of the inotify-based API should probably check if the
> > directory exists before using it.
>
> Well, that's extremely nasty to do with inotify: watching the
> creation of a directory you want to watch. 

Why not just not watching if it does not exist? What it is currently 
doing if the directory wouldn't exist?

Actually your inotify-explanation is even another good reason why this 
dirctory should not exist at all. I don't want that programms which I 
don't need are watching whe whole time for files which my system will 
never provide.

> > I thought systemd cares about "on-demand" etc.
>
> Well, you can opt to not start networkd and all will work fine. It's
> just that one directory that will always be created, that's not
> really that bad, is it?

See above, it's not only created. It's used by whatever 
inotify-watchers.

It may seem not really bad for this single case. However if all daemon 
programmers would do it like you, then we would have hundreds of 
useless/unused directories.

**Comment by poettering** [comment]
> Why not just not watching if it does not exist? What it is currently doing if the directory wouldn't exist?

networkd is disabled. resolved is running. Now you start networkd. I am pretty sure resolved should pick up networkd's DNS data now. Except it can't if it is neither watching the netif dir, nor /run, nor /... it wouldn't ever notice that the data is now available.

Hence, we create the dir early and unconditionally, even if it is not populated until networkd is started, so that resolved can watch the dir safely and always, and there are only very focussed wakeups in resolved and nowhere else.

**Comment by poettering** [comment]
> It may seem not really bad for this single case. However if all daemon programmers would do it like you, then we would have hundreds of useless/unused directories.

The idea with #5513 is that as long as you compiled and installed networkd you'll get both /usr/lib/systemd/systemd-networkd and /run/systemd/netif installed. If you decide to either not compile it or not install it you won't. I think that behaviour makes a ton of sense. But expecting that if you compiled and installed networkd you'd only get /usr/lib/systemd/systemd-networkd but not /run/systemd/netif is nothing I think we need to care for.

**Comment by rudimeier** [comment]
Unfortunately my distro has compiled with networkd. It would be nice if you could provide a way for the distros to make their users happy regardless if they enable it or not.

In general it would be also nice if an uninstalled daemon behaves *exactly* the same way like an installed but disabled daemon.
