### ISSUE TITLE
RFE: RuntimeDirectoryOwner= or similar to control runtime dir ownership

### ISSUE THREAD

**Issue by notroj** [systemd/systemd#8560]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 234

### Used distribution

> Fedora

### Description

We'd like to use `RuntimeDirectory=` for httpd.service to manage `/run/httpd`, but we need to control the (group and user) ownership not just the permissions.  That directory needs to be chown root.apache so we can make it readable by the less-privileged apache user, but not writable.  Could we get a `RuntimeDirectoryOwner=` or similar to mirror `RuntimeDirectoryMode=`?

**Comment by sourcejedi** [comment]
> For runtime directories that require more complex or different configuration or lifetime guarantees, please consider using tmpfiles.d(5).

Why do you want to migrate from tmpfiles.d?  Don't you still need to create `/run/httpd/htcacheclean`?  If so, what's the advantage of using RuntimeDirectory= and having to create htcacheclean/ manually instead of by tmpfiles.d? (contents like htcacheclean/ will be removed on service shutdown, so you'd have to create it on startup).

---

Survey of default Fedora: openvpn seems to want the same ownership style, and uses tmpfiles.d as suggested.

I think we have user/group separated in other settings.  If this was added maybe it would just be `RuntimeDirectoryGroup=`.  Since the use case is to use a different group for a daemon started as `root:root`.

I guess you could set `Group=apache` instead of `RuntimeDirectoryGroup=`, but it doesn't sound like a very safe change to make underneath existing daemon code :).

**Comment by notroj** [comment]
Hmmm, interesting.  Is setting `User=` or `Group=` by default going to change the behaviour of any other unit  settings... can't think what, PrivateTmp?

Looks like it would work, but seems a bit fragile. If someone wants to overrides the `ExecStart=` etc in the system httpd.service they'll have to know to do the same `!` prefix, it's quite a big break in current behaviour.  I'll try to get v235 and test further.

**Comment by notroj** [comment]
> Why do you want to migrate from tmpfiles.d?

I don't particularly, but we've seen issues where users moved the "apache" user definition to NIS (or LDAP) and then end up with awkward service startup ordering issues.  Using RuntimeDirectory= looks neater than using tmpfiles if we could solve the ownership issue, but probably `ExecStart=!` would hurt more than it would cure.

**Comment by arthur-s** [comment]
Hello, to keep ownership and mode for runtime folder, I add PermissionsStartOnly=True, this works for me:
```
[Service]
PermissionsStartOnly=True
User=arthur
Group=http
RuntimeDirectory=appfolder
RuntimeDirectoryMode=0755
```

**Comment by galaxy4public** [comment]
@poettering, your approach is a bit of a hack :) and implies that the daemon will drop its privileges properly.

@arthur-s, your approach also opens up a security issue since it would mean that everything except `ExecStart=` will run with escalated privileges.

I strongly support introducing at least `RuntimeDirectoryGroup=` support (would not mind `RuntimeDirectoryUser=` too) for the following use case:

A have a process that is quite dumb and does not require any privileges (e.g. OpenDKIM milter filter), let's call this process a **producer**.  Now, the process itself is useless unless it has a communication channel with another process on the system which is also non-privileged (e.g. Postfix), let's call this process a **consumer**.  The communication between two is supposed to be through a unix socket.

The way how I usually configure this and keep the system as tight as possible is the following:

1. **producer** is started through systemd (`Type=simple`, `User=producer`, `Group=producer`, `RuntimeDirectory=producer`, `RuntimeDirectoryMode=0710`)
2. **consumer** is started through systemd (`Type=simple`, `User=consumer`, `Group=consumer`)
3. **consumer** is configured to use the `/run/producer/producer.sock` for the communication purposes

Now, the challenge is how to get the `/run/producer` directory the `consumer` group ownership, so **consumer** could actually descend into the `/run/producer` directory, yet nobody else on the system could.

All the proposed approaches are compromising on one side or another -- you either give unnecessary permissions to the **producer** service (e.g. `PermissionsStartOnly=True` followed by something like `StartPost=/bin/chrp -h consumer /run/producer` -- actually this is the work around I am using at the moment) or by giving unnecessary privileges to the **consumer** (e.g. by giving it a membership in producer's group).

I think it would be nice and in line with all other arguments like `SocketUser=` and `SocketGroup=` to have `RuntimeDirectoryUser=` and `RuntimeDirectoryGroup=`.

**Comment by poettering** [comment]
> Why do you want to migrate from tmpfiles.d?
> 
> I don't particularly, but we've seen issues where users moved the "apache" user definition to NIS (or LDAP) and then end up with awkward service startup ordering issues. Using RuntimeDirectory= looks neater than using tmpfiles if we could solve the ownership issue, but probably ExecStart=! would hurt more than it would cure.

In general I'd always recommend using RuntimeDirectory= rather than tmpfiles.d if it is sufficient. It neatly integrates the lifecycles of both, and unifies things in one file only. Also, in particular for apache I figure people might take the the original unit file, and copy it to run adjusted, specialist instances, and if they do it's good if the RuntimeDirectory= stanza in there tells them that they need to care about that too.

**Comment by poettering** [comment]
@galaxy4public the issue you describe sounds more like a request for some minimal ACL hookup for runtime directories. i.e. RuntimeDirectoryAddACL= or so, which could be used to give specific users access. After all you don't actually want to pass ownership of the dir to "consumer", as that implies read *and* write access. Instead you just want to pass read access over...

**Comment by poettering** [comment]
Anyway, closing this, as the `!` really should cover this already, and in fact was added precisely for this usecase. @galaxy4public please file a new explicit RFE issue if you want the ACL thing to happen.
