### ISSUE TITLE
systemd-gpt-auto-generator with only one GPT partition

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#8561]
if there is only one root partition and only one EFI System Partition partition, systemd-gpt-auto-generator shall consider them for mounting even if LoaderDevicePartUUID is not set (just because it is clear which EFI System Partition was used, if there is only one).

**Comment by poettering** [comment]
but how would it determine that there's "only one"? We never know how long hw takes to show up. It can take any time it wants.

**Comment by dilyanpalauzov** [comment]
At the time I wrote this the idea was to make some conclusions during the boot process, when the boot loader (incl. the kernel uefi stub) does not pass the appropriate GPT parameters.  I do not remember now which parameters were these.  In any case, it seemed suitable to fill the parameters, when the boot loader does not pass them and the system boots from GPT partition.

**Comment by poettering** [comment]
I am sorry, but I simply don't know how we would implement this. "only one" cannot be reliably determined, hw can take any time it wants to show up, hence when would we decide that we have now seen evrything and can determine that it is just one?

Closing this, since I simply see no way to implement this unless hte boot loader tells us.
