### ISSUE TITLE
Shutdown very often very much delayed on Linux Mint when there are network shares

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#8571]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 230

Well, what is the most recently recent version? I looked around these pages and I could not find the answer.

### Used distribution

> Mint 18.3 x64 (though I updated systemd beyond that which ships with Mint 18.3, in an effort to solve the problem. It didn't solve it).

### In case of bug report: Expected behaviour you didn't see

> A shutdown that took fewer than two minutes, on a very fast laptop.

### In case of bug report: Unexpected behaviour you saw

> The infamous stop jobs.

### In case of bug report: Steps to reproduce the problem

> I don't know exactly what causes it. But, on my system as it is: set up network shares, whether via fstab or autofs or the fun that is mount and automount units, and then - I *think* this is a prequisite - try to use them and reboot some time later. However, the problem seems intermittent.

I followed the instructions on [this page](https://freedesktop.org/wiki/Software/systemd/Debugging/#shutdowncompleteseventually) to generate a debug log, but none seemed to be generated. I've tried closing and/or killing many of my various running programs, and I've updated to a recent version of Conky, and I've tried unmounting the shares before shutdown, and nothing works.

(I had a problem too, in which I think systemd is implicated, with encrypted swap, but I gave up on that entirely in the end.)

**Comment by poettering** [comment]
> Well, what is the most recently recent version? I looked around these pages and I could not find the answer.

It's listed here:

https://github.com/systemd/systemd/releases

**Comment by poettering** [comment]
Please update to something more current, we only track current systemd versions here usptream, specifically issues in 237 and 238. There have been a number of changes with handling network mounts in systemd in the recent versions, hence there's a good chance what you describe is already fixed in the mean time.

Note that getting the ordering right for detaching network mounts is not only a systemd job btw, it requires support from the downstream distributions to order things propery against remote-fs.target and such. Please contact your downstream distro about that.

Anyway, closing this here. Please reopen if there's an issue in current upstream versions and you made sure that your downstream distro sets up their networking units properly, with all the necessary ordering.
