### ISSUE TITLE
systemd 238 (+ patch) breaks my mouse

### ISSUE THREAD

**Issue by Baughn** [systemd/systemd#8579]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238.0

> 238.0 + https://github.com/systemd/systemd/pull/8493

### Used distribution

> NixOS 18.03pre-git (Impala)

### In case of bug report: Expected behaviour you didn't see

> All mouse buttons should work

### In case of bug report: Unexpected behaviour you saw

> For 238.0: Mouse does not work at all.
> For 238.0 + patch: Some buttons no longer work.

### In case of bug report: Steps to reproduce the problem

- Purchase a MadCatz MMO 7 mouse, or (likely) any other mouse with >16 buttons.
- Run `xev` to confirm that some buttons don't function.

### Further information

The original bug is https://github.com/systemd/systemd/issues/8460, which was patched by https://github.com/systemd/systemd/pull/8493. Unfortunately, this patch causes the system to ignore any buttons beyond the first sixteen.

The mouse worked fine with systemd 237, so this is a regression.

**Comment by whot** [comment]
sorry, was on holidays.

can you confirm that `sudo evemu-record` shows events for all buttons? If not -> kernel issue
what driver are you using? libinput or evdev? or wayland (in which case it's libinput)

The reason I'm asking: the `ID_INPUT` tags have *no* effect on button reporting, they literally only say "this is a mouse" or "this is a touchpad" but don't do anything about the event processing itself. So the only two options I can see are either the kernel got updated together with systemd and that broke things or libinput is confused about something now.

**Comment by tr37ion** [comment]
Applying ae5fd19 did fix the mouse issue #8460 and using `sudo evemu-record` shows all buttons are working. While `xev | egrep ^Button` only recognizes some of the buttons. 

With KDE Plasma's "Input Device/Joystick" settings all buttons are working and even the special `ModeSet` button (20) switches the `pressed` state of buttons 1,2 and 22. Which is well, because this makes it possible to apply a complete new subset of button assignments for each of those three  button's `pressed` state.

**Comment by whot** [comment]
Taking the silence as a 'yes'
