### ISSUE TITLE
systemd-rfkill: Failed to open device rfkill2: No such device

### ISSUE THREAD

**Issue by pacho2** [systemd/systemd#8586]
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237 and 238

### Used distribution

> Gentoo Linux

### In case of bug report: Expected behaviour you didn't see
> No errors shown in logs after resuming

### In case of bug report: Unexpected behaviour you saw
> When resuming from suspend I see this message, I don't know if it's normal (because it is shown in "red" color) or maybe I have some kernel option disabled or so :/
mar 24 23:49:00 dell-2017 systemd[1]: Starting Load/Save RF Kill Switch Status...
mar 24 23:49:00 dell-2017 bluetoothd[343]: Endpoint unregistered: sender=:1.57 path=/MediaEndpoint/A2DPSink
mar 24 23:49:00 dell-2017 upowerd[449]: unhandled action 'unbind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1
mar 24 23:49:00 dell-2017 bluetoothd[343]: Endpoint unregistered: sender=:1.29 path=/MediaEndpoint/A2DPSource
mar 24 23:49:00 dell-2017 systemd-rfkill[3774]: Failed to open device rfkill2: No such device
mar 24 23:49:00 dell-2017 bluetoothd[343]: Endpoint unregistered: sender=:1.29 path=/MediaEndpoint/A2DPSink

### In case of bug report: Steps to reproduce the problem
> Having a laptop with bluetooth device, suspending and resuming

**Comment by poettering** [comment]
hmm, i figure this is simply race: when you suspend i figure some rfkill devices are powered down and thus disappear from the system. We already catch one error due to this race explicitly (ENOENT), but i figure we also need to handle the error you are seeing (ENODEV), and maybe ENXIO, and not complain in that case, but just assume the device vanished already since we got notified about it.

**Comment by pacho2** [comment]
Thanks!
