### ISSUE TITLE
RFE: Add support to configure IPv6 MTU separately

### ISSUE THREAD

**Issue by klausenbusk** [systemd/systemd#8632]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 238

### Used distribution

> ArchLinux

I want to specific a static IPv6 address for my server, but due to the fact that my ISP use 6RD for IPv6 I need to lower the MTU to 1480. I can use do that by specifying `MTUBytes=1480` in the `.netdev` file, but that change the MTU at the link level, which means it also affect IPv4 packets.

Ideally systemd should provide a way to change the MTU for IPv6 only (`/proc/sys/net/ipv6/conf/.../mtu `). As this closed PR https://github.com/systemd/systemd/pull/1533

**Comment by flo-wer** [comment]
I suppose you use some sort of NDP proxy on your router as the tunnel interface which terminates 6RD should be able to use a different MTU without affecting your normal IPv4 traffic. If you get a lager prefix than /64, it is better to enable routing between your networks because this allows you to use different MTUs with PMTUD.

If your prefix isn't stable and you have to use SLAAC, you can use [IPv6Token=](https://www.freedesktop.org/software/systemd/man/systemd.network.html#IPv6Token=) to keep at least the host part stable.

**Comment by klausenbusk** [comment]
Hi @flo-wer 

> I suppose you use some sort of NDP proxy on your router as the tunnel interface which terminates 6RD should be able to use a different MTU without affecting your normal IPv4 traffic.

The router is provided and controlled by my ISP, so I have no idea how it is configured. I simply want to add a static IPv6 address for my server, without affecting the IPv4 traffic.

> If you get a lager prefix than /64, it is better to enable routing between your networks because this allows you to use different MTUs with PMTUD.

PMTUD is TCP only as far as I know.

> If your prefix isn't stable and you have to use SLAAC, you can use IPv6Token= to keep at least the host part stable.

That could work, but it seems more like a hack?
