### ISSUE TITLE
Recommendation on how to handle slice units and Delegate, particularly in cgroupv2

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#8645]
This is a follow up on the discussion on systemd/systemd#8573.

So let me try to define some concepts, to make sure we're all on the same page:
- `slice`: A unit meant to group other units. It should have no tasks (no pids) attached to it, it should only have children cgroup (which can be services or scopes.)
- `scope`: A "leaf" unit. Needs to have at least one pid in it. Typically, it shouldn't have any children cgroups under it.

Also:
- `Delegate=` option. From the man page: "Turns on delegation of further resource control partitioning to processes of the unit." The way I see it, that means handing control of the cgroup to an external entity that is not systemd. That external entity may:
  - Modify resource limits on the cgroup (?)
  - Add other pids to the cgroup (?)
  - Create sub-cgroups below this one. (I'm fairly sure this is part of it.)

As a side effect of `Delegate=yes`, the unit will get all cgroups (memory, cpu, etc.) created on it.

I'm not 100% sure of all this, so please correct it if I made mistakes. (I can come back and edit the post to do that later.)

---

Now let me try to describe my use case. It's about running containers. Yes, it's Kubernetes. And yes, docker is somewhat involved (though not necessarily, could be cri-o, containerd, rktlet too.)

I have hosts running two separate daemons:
- The "node manager" (kubelet) which receives requests for containers to be scheduled and does the necessary steps to do so.
- The "container manager" (docker, cri-o, containerd, rktlet) which receives requests from the node manager and starts containers to fulfill those requests.

The node manager uses "pods" to group related containers. These containers typically share at least the network namespace. And these containers get one pool of shared resources (memory, cpu, etc.) that allow restricting the set of related containers together.

A pod doesn't have any tasks or pids attached to it. A pod is simply used to group a set of containers (leaf cgroups) together.

So a pod is implemented as a slice. I think that makes sense. Right?

Now, whenever we need containers created on a pod, the node manager will contact the container manager and ask it to create a container. As part of the request, it will send it the name of the [parent cgroup](https://github.com/kubernetes/kubernetes/blob/v1.10.0/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L266) under which it should create its own leaf cgroup.

The container manager then creates a leaf cgroup (scope) under that parent (slice) and creates a container from it. The leaf cgroup will have tasks in it, since it's a running container, so scope is a good fit for it. It's also a leaf, so scope suits it well.

So far, all of this makes sense, right?

---

So this all works if everyone is using systemd. Well, kind of. But we'll get to this later.

But the main question here is how to set this up for delegation in case (not everybody) is using systemd.

Both managers are using [libcontainer](https://github.com/opencontainers/runc/tree/v1.0.0-rc5/libcontainer), which offers two cgroup drivers, [systemd](https://github.com/opencontainers/runc/tree/v1.0.0-rc5/libcontainer/cgroups/systemd) and [cgroupfs](https://github.com/opencontainers/runc/tree/v1.0.0-rc5/libcontainer/cgroups/fs). The cgroupfs driver simply does the operations (mkdir, add pids to tasks, etc.) directly in the /sys/fs/cgroup tree. The systemd driver talks to systemd over D-Bus.

How can we use delegation here, if the node manager is using systemd for the pods, but the container manager is using cgroupfs for the leaf containers? Ideally, we would like to keep the pods as "slices", since that's conceptually what they are... But if a slice unit can't delegate, then apparently that's not an option...

Ok, so should we use a "scope" for that case? Sounds like a hack, since first we'll need a dummy pid to add to the scope (just launch a "sleep forever" for that? why the overhead?), then we would actually have a "scope" that has sub-cgroups in it (while that's the purpose of a slice actually.)

Ok, so let's say we do that... What if now we want to switch the container manager to use systemd as well. We can't! Because with the setup above, the container manager would receive a scope (with delegation enabled), but when it asks systemd to create a sub-cgroup there, systemd would refuse, since it doesn't create cgroups under a scope...

So, in a way, preventing slices from delegate makes it *harder* for us to migrate from cgroupfs to systemd.

There's also the question of what to do if node manager is using cgroupfs. Right now, it's simply creating a cgroup at the root (/kubepods) and then creating its own tree under it. Looks like this should be a scope with Delegation (/kubepods.scope), but then again we need a dummy pid to add to it. And, conceptually, it's not a scope, but a slice, since its purpose is to keep the tree of cgroups in it.

---

There's also the problem of libcontainer stop working on systemd v238.

That's partly because libcontainer [tries to set `Delegate=yes` on a slice](https://github.com/opencontainers/runc/blob/v1.0.0-rc5/libcontainer/cgroups/systemd/apply_systemd.go#L151) and this started failing now. (It turns out they use a scope to detect whether `Delegate=` is available, then assume it's available on slices too. I can fix that, just need some guidance first on this discussion here.)

So, that's a minor quirk, I'm sure we can figure that one out... But I think we need some clear guidance here.

---

So, in short, I think for my use case above, slices and scopes are used in the right places. And, unless I completely misunderstand delegation, I think delegation at the slices makes sense too...

In fact, I think if you wanted to restrict delegation to slices _only_, I think that would actually make sense, since for an application wanting to do its own thing, starting from a slice would be best (it's akin to starting at root.) On the other hand, keeping scopes and services as leafs only would keep them much more well defined.

Did I misunderstand how Delegate is supposed to work?

Do you have a better suggestion on how to implement this?

I'm fine with more restrictions in cgroupv2. For instance, forbidding tasks in slices, that's fine. Enforcing that scopes and services must be leafs (they aren't today, with delegation, right?), that's fine. Maybe even enforcing that either systemd manages it (without delegation) or another party manages it (with delegation) but not both at the same time, that's fine.

What's your guidance here?

Thanks!
Filipe

**Comment by poettering** [comment]
> scope: A "leaf" unit. Needs to have at least one pid in it. Typically, it shouldn't have any children cgroups under it.

Uh, no. Having subcgroups is totally fine. When nspawn is called from the cmdline it will register a scope and set Delegate=yes on it, so that it can have its own private cgroup subtree for the container. It will then invoke the payload in it, which is typically another systemd instance, which then manages the cgroup subtree delegated to it this way. 

Yes, there are scope units that have Delegate=no set (for example the scope units allocated for each PAM session), and there are scope units that have Delegate=yes set (the aforementioned nspawn scopes when you run it from the cmdline). There's no rule about whether it "should" or "shouldn't" have child cgroups, both are entirely fine.

**Comment by poettering** [comment]
> Delegate= option. From the man page: "Turns on delegation of further resource control partitioning to processes of the unit." The way I see it, that means handing control of the cgroup to an external entity that is not systemd. That external entity may:

To say this clearly: Delegate= primarily is about direct write access to cgroupfs.

> 
>     Modify resource limits on the cgroup (?)

No. The cgroup belonging to the scope/service itself is managed by systemd, Delegate=yes doesn't change that. That means the resource settings on the cgroup itself are off limits to everybody else. However, the resource settings on subcgroups are exclusive territory of whoever manages the subtree.

>     Add other pids to the cgroup (?)

Well, here too: the cgroup of the unit itself remains property of systemd, and hence nobody else should add pids to it really. That said, recent systemd versions added a bus call to add this, which is useful to move processes between unrelated subtrees (which is something cgroupsv2 normally disallows)

>     Create sub-cgroups below this one. (I'm fairly sure this is part of it.)

Yes, this is what you may do. You can create as many children as you like, and systemd won't interfere. They are your exclusive territory.

BTW, have you had a look at the docs for all of this?

https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/

it's not the most up-to-date, and the part about delegation aren't particularly extensive, but it does introduce basic concepts.

**Comment by poettering** [comment]
> The container manager then creates a leaf cgroup (scope) under that parent (slice) and creates a container from it. The leaf cgroup will have tasks in it, since it's a running container, so scope is a good fit for it. It's also a leaf, so scope suits it well.
> 
> So far, all of this makes sense, right?

Yes, it appears to me so.

**Comment by filbranden** [comment]
> BTW, have you had a look at the docs for all of this?
> https://www.freedesktop.org/wiki/Software/systemd/ControlGroupInterface/

Yes, I've read that before. Looking at it again to refresh my memory.

(BTW, I just found "Service and scope units know a special `Delegate` boolean property." haha.)

I didn't think of the nspawn example, that's a good example of a scope with a tree in there. But nspawn is kind of managing its own, in that it's not asking systemd (pid 1 outside the container) to create subcgroups below it...

I guess my main issue here is that it sounds that the best way to implement a pod is:
- a slice, if the container manager is asking systemd to create its cgroups; or
- a scope, otherwise.

But given I want to just use systemd and ignore whatever the container managers are doing, that's a problem with me... slice with Delegate=yes seems like the right approach for that.

(And I know @aru777's use case is slightly different, but still similar. From what I know about it, it seems slice with Delegate=yes is also the best fit for them.)

What's so wrong an unmaintainable with slices with Delegate=yes? Are there other measures we could do to still allow slices with Delegate=yes but keep the situation contained in cgroupv2?

**Comment by poettering** [comment]
> So, in a way, preventing slices from delegate makes it harder for us to migrate from cgroupfs to systemd.

note that the clear separation between inner and leaf nodes is not a concept we came up with, it's kinda inherited from the stricter cgroupsv2 semantics, where you cannot place PIDs in inner nodes at all, the kernel will refuse that. The cgroupsv2 delegation model wants clear subtree ownership, we just reflect that...

**Comment by poettering** [comment]
I don't know kubernetes, but to me it appears the right fix would be to improve the communication between kubernetes and its backends, no? if you want such a "pluggable backend" logic then there should be a clear way how you can communicate what the backend supports in one direction and then what to do in the other, no?

Alternatively, there's always the cheap way out: just set Delegate=yes for the kubernetes service as a whole, and then you have your own cgroup tree and you can do whatever you want it below it, and run everything below it. i.e. not use systemd's slice/scope/service abstractions at all, but manage the whole of kubernetes as one big service with a myriad of cgroup subtrees underneath itself. Of course, doing it this way is not as sexy I think, since kubernetes is very much one big opaque blob to systemd then, but maybe this is what you want, dunno?

**Comment by filbranden** [comment]
> note that the clear separation between inner and leaf nodes is not a concept we came up with, it's kinda inherited from the stricter cgroupsv2 semantics, where you cannot place PIDs in inner nodes at all, the kernel will refuse that. The cgroupsv2 delegation model wants clear subtree ownership, we just reflect that...

Hmmm, interesting... And how does the nspawn case with the scope with Delegate=yes and sub-cgroups work in that case? Because the top process nspawn starts will be in the scope itself, right?

And my general comment:

> So, in a way, preventing slices from delegate makes it harder for us to migrate from cgroupfs to systemd.

Not sure why you mentioned placing PIDs in the inner nodes in reply to that... Since in either case the "pods" (slices) have no pids in them.

When container manager is using systemd cgroup driver, node manager creates `/kubepods.slice/pod123.slice/`, hands that to container manager, which creates `containerABC.scope/` under it (thorugh systemd D-Bus, transient unit, etc.) and PIDs in the container are placed there.

When container manager is using cgroupfs cgroup driver (but node manager still using systemd!), then node manager creates `/kubepods.slice/pod123.slice/` (with `Delegate=yes`), hands that to container manager, which mkdir's `/kubepods.slice/pod123.slice/containerABC/` and places its PIDs all there inside `containerABC/`.

**Comment by poettering** [comment]
> Ok, so should we use a "scope" for that case? Sounds like a hack, since first we'll need a dummy pid to add to the scope (just launch a "sleep forever" for that? why the overhead?), then we would actually have a "scope" that has sub-cgroups in it (while that's the purpose of a slice actually.)

So the disconnect here is that so far the assumption was that managers of cgroup subtrees are also the ones which allocated the scope for it. I guess the issues you are running into stem from the fact that you have this weird split where one component wants to set up part of the hierarchy "dry", and then another set of components is supposed to populate it further. 

Currently scopes have a clear lifecycle: if they have processes in them they are running, if they don't they are dead. And there's only one transition permitted: from running to dead. This way we have correct reference counting: a running process keeps the scope around, and we have automatic clean-up: as soon as the processes are gone the scope goes down and can be GC'ed. If we'd allow scopes to be created empty this would be complicated: suddenly the scope lifecycle would have to be decouple, there's no ref-by-resource logic available anymore. Hence I am not overly enthusiastic about adding such a mode, but I guess it would be acceptable. It would after all just reflect the behaviour RemainAfterExit= exposes for service units, hence it wouldn't be entirely new.

**Comment by poettering** [comment]
> Hmmm, interesting... And how does the nspawn case with the scope with Delegate=yes and sub-cgroups work in that case? Because the top process nspawn starts will be in the scope itself, right?

nspawn can run in two modes: in the "command line mode" where the nspawn process itself remains in whatever cgroup it was started in, and only the child it forks off (i.e. the PID 1 of the container) is placed in a newly allocated scope. And in the "background service mode" where then nspawn process itself is the main process of a service unit with Delegate=yes set. In the latter mode nspawn is started directly inside the cgroup that belongs to the service. Since we want to allow container payloads such as systemd to manage their own cgroup subtrees we can't leave it like that though, because of the cgroupsv2 no-inner-node-processes rule. Hence the first thing we do in that case is create two subcgroups below the service cgroup: supervisor/ and payload/. We then move nspawn into the former, and the PID 1 of the container to start into the latter. That way the contraint isn't broken.

To further complicate things, when systemd then runs as PID1 inside the container it will as first thing move itself into one level down, again because of the no-inner-node-processes rule: systemd itself can't be in the top cgroup of the container if it wants to create any further cgroups.

hence, if you run systemd-nspawn as service (for example by using `systemd-nspawn@.service`) and systemd as payload you'll get this cgroup path for the container's PID 1:

`machine.slice/systemd-nspawn@foobar.service/payload/init.scope/`

And nspawn it self will live in 

`machine.slice/systemd-nspawn@foobar.service/supervisor/`

**Comment by poettering** [comment]
> machine.slice/systemd-nspawn@foobar.service/payload/init.scope/

And to extend this further. In this cgroup path there are subtreesdelegated to three different players:

the cgroup root, `machine.slice/` and `/machine.slice/systemd-nspawn@foobar.service` are managed by systemd on the host. The "payload/" subcgroup is then managed by nspawn, and "init.scope/" is then managed by the container's own systemd instance...

**Comment by filbranden** [comment]
> Currently scopes have a clear lifecycle: if they have processes in them they are running, if they don't they are dead. 

Reading through your explanation of nspawn below, it seems that the need to have processes in them _anywhere in the subtree_, not necessarily in the top scope cgroup. Correct?

**Comment by poettering** [comment]
> Currently scopes have a clear lifecycle: if they have processes in them they are running, if they don't they are dead.
> 
> Reading through your explanation of nspawn below, it seems that the need to have processes in them anywhere in the subtree, not necessarily in the top scope cgroup. Correct?

correct. We (and the kernel) define emptiness recursively. A cgroup is only considered empty when it contains no processes, and when all its children are empty too.

**Comment by poettering** [comment]
(regarding the create-scopes-empty thing. if this would be helpful to you, please file an RFE bug and I'll look into it)

**Comment by poettering** [comment]
ah, fuck, pressed wrong button, sorry

**Comment by filbranden** [comment]
> If we'd allow delegation on slices, then this rule is broken, as systemd and your code would both try to manage children of the slice's cgroup.

Yes, I can see that point.

One could make an argument that a slice with `Delegate=yes` would be *only* managed by an external process and systemd would refuse to create anything on it... But that doesn't help me either, since I'm trying to tackle the inter-operate case, where I start using systemd everywhere and if the container managers are still using cgroupfs it still works...

In a way, slices with `Delegate=yes` where systemd refuses to create anything under it would essentially be the same as the empty scopes...

I'll see whether I need an empty scope or not and file an RFE for it if it's the case. I'm reluctant to push the node manager itself to it (since it's running as a service, and I want it managed as a service, that's correct.) Pushing a dummy "sleep" or "pause" process there wouldn't really add value and there's no guarantee it's going to go away when the node manager is stopped... So maybe an empty scope would make sense for that purpose?

In that case, would StopUnit() work on it? I mean, would I be able to get rid of it eventually if I needed to? Once it's really empty?

**Comment by poettering** [comment]
> In that case, would StopUnit() work on it? I mean, would I be able to get rid of it eventually if I needed to? Once it's really empty?

yes, you can kill scopes, and you can even configure which signal to send.

**Comment by poettering** [comment]
> Pushing a dummy "sleep" or "pause" process there wouldn't really add value and there's no guarantee it's going to go away when the node manager is stopped... 

Maybe fork off a stub child process, that just invokes `pause()` in a loop. In the child invoke prctl() with PR_SET_PDEATHSIG first though, so that it is automatically SIGKILLed by the kernel when you are done. That should make things pretty robust...

> So maybe an empty scope would make sense for that purpose?

If that's what it takes, please file an RFE!

**Comment by keszybz** [comment]
> Currently scopes have a clear lifecycle: if they have processes in them they are running, if they don't they are dead. And there's only one transition permitted: from running to dead. This way we have correct reference counting: a running process keeps the scope around, and we have automatic clean-up: as soon as the processes are gone the scope goes down and can be GC'ed. If we'd allow scopes to be created empty this would be complicated: suddenly the scope lifecycle would have to be decouple, there's no ref-by-resource logic available anymore. Hence I am not overly enthusiastic about adding such a mode, but I guess it would be acceptable.

It seems that for the kubernetes use case, something simpler would be enough: the ability to pre-create the .slice without any units underneath. If then we allowed the slice to go away after it has had at least one child unit and when we detect we it has no children anymore (in other words, add a third state PRE, with allowed transitions PRE → RUNNING → DEAD). This would be an option if turns out desirable to pre-create the slice unit.

**Comment by filbranden** [comment]
Not sure I follow you, @keszybz ...

> the ability to pre-create the .slice without any units underneath.

Yes, that's how we create slices now... We then pass the slice unit name to docker/containerd (using the equivalent of the `--cgroup-parent` option of `docker run`) and it creates its scope there.

We do all management of the slice already, we want to control when to take it away.

In fact, if both kubelet and docker/containerd are using systemd cgroup driver, everything works well this way and I'm fairly confident it will keep working once we go to systemd v237+ (well, there's one bug in libcontainer I need to fix for that, since it's still trying to delegate slices, even though it's not needed for this case, and it's not possible anymore) or to cgroup v2.

The problem is for the other cases... The "mixed" case, of kubelet using systemd driver (creating a slice) but docker/containerd using cgroupfs is a case that *could* be made to work if using slice + Delegate=yes, but that goes away in v237 and also I agree with the arguments that cgroup v2 makes that impossible to work...

For the case where everyone is using cgroupfs, right now we're creating a top-level cgroup /kubepods using mkdir. We should probably switch to creating a top-level scope /kubepods.scope, but then under it everything else should keep working as is. (This is the case described in https://github.com/systemd/systemd/issues/8645#issuecomment-378335252)

Considering the case where everyone uses systemd works, is likely to keep working and should make the transition to cgroup v2 easy (or at least easier), I'm looking at how to make this something closer to the default... Some of my thoughts are have libcontainer be able to "detect" if what it was passed was a slice, then use systemd cgroup driver to create a scope underneath it, otherwise fallback to the cgroupfs driver way of handling it...

For now, it doesn't look like I'll need an "empty" scope, so not filing an RFE for it right away... Creating one with the fork of the current process and setting PR_SET_PDEATHSIG is a bit inconvenient and slightly painful, but I think it can be dealt with, if we have to...

Cheers!
Filipe

**Comment by filbranden** [comment]
So I actually have a few follow-ups on cgroup v2, if you don't mind...

Regarding the way nspawn handles the cgroups in a scope, to always keep processes in the leaf:

> Hence the first thing we do in that case is create two subcgroups below the service cgroup: supervisor/ and payload/. We then move nspawn into the former, and the PID 1 of the container to start into the latter. That way the contraint isn't broken.

So for a short while there, the rule is broken, since at some point nspawn is still in the scope cgroup and there is already at least one supervisor/ sub-cgroup under it...

Does cgroup v2 do some "hard" enforcement of the rule that everything needs to be in a leaf?

If not, then is it more of a convention than a rule? (Or will things really really break if the rule is not followed?)

If it's a hard rule, then how is that conflict resolved?

---

The second follow up is about creating cgroups directly under the root. As I mentioned above, when using cgroupfs we just create a /kubepods right at the top of the tree. (Which seems to work, even under systemd, that's mainly systemd v229 that I've been testing, Ubuntu 16.04.) The main reason for doing that and not creating a scope is, well, using cgroupfs basically means not trying to interact with systemd (though I'm looking at ways to possibly change that...)

Will this kind of thing break under v237+ or under cgroup v2? Creating cgroups using mkdir right at the top of the tree?

(I think I saw some mention of scanning for them, maybe warning... But will they actually get broken?)

Thanks!
Filipe

**Comment by keszybz** [comment]
> So for a short while there, the rule is broken, since at some point nspawn is still in the scope cgroup and there is already at least one supervisor/ sub-cgroup under it...

Please see https://www.kernel.org/doc/Documentation/cgroup-v2.txt, the "No Internal Process Constraint"
> Non-root cgroups can distribute domain resources to their children
only when they don't have any processes of their own.  In other words,
only domain cgroups which don't contain any processes can have domain
controllers enabled in their "cgroup.subtree_control" files.
> Note that the restriction doesn't get in the way if there is no
enabled controller in the cgroup's "cgroup.subtree_control".  This is
important as otherwise it wouldn't be possible to create children of a
populated cgroup.  To control resource distribution of a cgroup, the
cgroup must create children and transfer all its processes to the
children before enabling controllers in its "cgroup.subtree_control"
file.

> Will this kind of thing break under v237+ or under cgroup v2? Creating cgroups using mkdir right at the top of the tree?

The kernel defines the restraints and enforces them. There is no "convention", all constraints are checked before any operation and will results in EBUSY, EINVAL, ESRCH, EPERM as appropriate, so it's easy to test them manually using `echo`.

systemd sets some "soft" constraints too, namely it wants to manage its cgroup hierarchy exclusively, and only allows other processes to manage parts that have been delegated using Delegate=. That way there is always one owner, either systemd or something else, with clearly defined boundaries. But there is no hard enforcement of this, a user or process with privileges can move stuff around in the cgroup hierarchy, change settings, etc. systemd might undo those changes later, or it might not. Either way, doing this is unsupported and you get to keep the pieces.

Or in other words: in the part of the hierarchy that is delegated, you can do anything that the kernel allows. Anything that is not delegated, should only by touched by systemd.

**Comment by keszybz** [comment]
Good to close?

**Comment by htejun** [comment]
So, I'm not sure how much the no-internal-process rule has to do with whether a slice could be delegated or not. A slice is an inner cgroup grouping sub-cgroups. When a subtree is delegated to a different manager, the root of the delegated subtree will be used as the nested root, which fits with the "inner cgroup grouping sub-cgroups" definition at least intuitively and I can't think of technical reasons why delegating a slice wouldn't work.

**Comment by poettering** [comment]
@htejun well, the issue here is that slice units are inner nodes of our tree, and we attach services and scopes to them freely. If we'd allow delegation to them, then they'd be very weird, as suddenly it would be us creating children in them, as well as somebody else. And as I understood you, this is not how you wanted cgroupsv2 to be used or understood, i.e. it means two managers fight for the exact same cgroup, and that's the big problem. You originally wanted to have a single writer for the whole tree iirc, and then the delegation model was added to break this a up a bit, as long as each partitioned subgraph of the whole tree has only one writer.

I mean, the whole concept of systemd's "slices" exist only as being the attachment location for our unit types that manage processes. If we'd allow delegation of slices, then that concept is turned on its head, as we couldn't use it that way anymore: slices with delegation on would become leaves of our tree, and that's not what they are supposed to be...

Or to say this differently: we already have two concepts for leaves of our tree, and those are services and slices, for stuff *we* invoke and stuff *others* invoke. If people want to attach code to our tree then that's where they should place stuff, it's what it's for, and how the semantics make sense.

Or to say this even differently: when we'd allow delegation in slices, and somebody asks me what the difference between a delegated slice and a scope unit is, then I have really no answer, because there wouldn't be any...

**Comment by poettering** [comment]
I mean, the issue here really stems from the fact that kubernetes only wants to pass raw cgroups information around, and that is simply not compatible with backends that want to make use of systemd concepts. I mean, if you want to integrate nicely with systemd, then by all means do it, I'd very much like to see that, but don't start by building on behaviour that always was expressly against systemd's design concept, and only worked because we mistakenly forgot to check our input strictly enough in one case, and that on Linux everyone with root privs can make any change to cgroupfs he likes...

**Comment by htejun** [comment]
Oh, absolutely, a delegated slice shouldn't have any further systemd units in it. The only point, I think, is that .scope or .service looks like ass when used for internal cgroups for sub-managers. For example, monitoring infrastructure / ppl looking at it might not care who's controlling which part of hierarchy, they just want to know the logical composition of the system and how resources are being consumed across the system. It's just nice to be able to use the same concepts and terms across them. So, the only thing which makes sense would be making a delegated .slice behave like a delegated, empty (to systemd's eyes) and persistent service.

**Comment by filbranden** [comment]
I think this one has served its purpose... Thanks everyone for the comments and the new docs that came from this discussion!

**Comment by ssup2** [comment]
@filbranden 
Hi. Now I'm researching cgroup driver for kubelet or docker. In [K8s Official document](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers) or [kubeadm Issue](https://github.com/kubernetes/kubeadm/issues/1394#issuecomment-462878219) there are below comments about cgroupfs

> We have seen cases in the field where nodes that are configured to use cgroupfs for the kubelet and Docker, and systemd for the rest of the processes running on the node becomes unstable under resource pressure.

@mauilion and @neolit123 mention this issue. So I skimmed this issue. But I can't find the answer to above comments. I understand about management policy conflict with cgroupfs driver and systemd. But I don't think it makes the system unstable. Because from the kernel's point of view, cgroupfs is not designed to managed by only one application.

Is there anything I'm misunderstanding? Cloud I get a clue about this?
Thanks.

**Comment by poettering** [comment]
@ssup2 that text reads as if kubernetes insists to place its cgroups in the top-level cgroup tree. That's not supported from systemd. They need to ask for delegation and do their stuff inside their own subcgroup tree. Yes, this will become unstable, since if you do not ask for delegation, you will live in systemd's namespace and systemd might migrate your processes around. It's a really bad idea to do this. And it's explicitly documented not to do that.

**Comment by ssup2** [comment]
@poettering 

> since if you do not ask for delegation, you will live in systemd's namespace and systemd might migrate your processes around.

Thanks reply. But I can't understand the above comment. Does it mean that systemd move the processes not in systemd's namespace to systemd's namespace forcibly??

**Comment by poettering** [comment]
@ssup2 if systemd service runs on a systemd system, then systemd will place it in a cgroup, and whenever appropriate (for example when the user change's the resource management properties of such a system service via systemd apis, or on any of its siblings), then systemd will re-realize the cgroup and migrate your process back where they belong.

I meant namespace in the general sense, i.e. not Linux CLONE_NEWCGROUP sense. i.e. systemd any cgroup in the root of cgroupfs it assumes are its own. And if you place your own cgroups there then you'll end up fighting for those names.

Delegation was documented for years. If Kubernetes people chose to ignore that actively I can't really do much about it, except repeating that this is all broken and people should just follow the frickin' docs.

**Comment by ssup2** [comment]
@poettering 
Thanks for the kind reply. I think k8s people don't ignore the official documents about cgroup driver. Many k8s tools such as kubeadm recommend to use systemd cgroup driver with systemd. And I also consider the use of systemd cgroup driver instead of cgroupfs cgroup driver.

Before applying the cgroupfs cgroup driver, I want to know the effect of cgroupfs driver with systemd exactly. Because if this is critical to the kubernetes cluster, I have to change all kubelet setting right now. But this work is not easy for me because of too many cluster nodes. 

If what I understand is correct, cgroupfs cgroup driver with systemd is not critical right now. So I will change kubelet option slowly. Thanks.

**Comment by hxysayhi** [comment]
If I modify the value of subtree_control, then when I restart the service, systemd will try to overwrite the value of subtree_control. For example, if I add a `cpu` controller to subtree_control, systemd will remove it from subtree_control when the service is restarted. If I create a subdirectory at this time, and there are still processes in the subgroup when restarting, the startup will fail. The error is as follows:   
```
Control process exited, code=exited, status=219/CGROUP
...
Unit process 543222  (xxx) remains running after unit stoped.
....
```
Which seems to be a failure when rewriting the subtree_control. 

I want to manage subtree_control by myself when delegation is turned on, I hope systemd doesn't modify it.

Is there any way to solve this problem, please?

**Comment by Werkov** [comment]
That sounds like a bug to me (provided the offending unit has `Delegate=yes` or `Delegate=cpu`), `cgroup.subtree_control` should not be modified in such a way.

@hxysayhi Can you please file a new issue with minimal reproducer (a unit file) attached and ping me? Thanks.

(I'd treat the restart with subcgroups and processes separately. The processes should be terminated to begin with.)
