### ISSUE TITLE
Default coredump Behaviour

### ISSUE THREAD

**Issue by tmarques** [systemd/systemd#8680]
### Submission type

> Request for enhancement (RFE)

### systemd version 

> systemd 238.51-1

### Used distribution

> Arch Linux ARM

### Request
> Make coredumps disabled by default

### Rationale

Systemd, by default, dumps crashed processes into the root drive. For big processes like Firefox, it causes disk thrashing and can fill up root partitions that have a bigger, separate /home.
Given this is mostly useful for programmers, consider making coredumps disabled by default so non-technical users of modern systems don't get their drives filled by coredumps (eMMC drives are small and common).
Usually coredumps were available at a users home folder, so the user could free up space. In this case, I had to also 'du' the root drive to find where the dumps were (or read the docs), which is as user unfriendly as it gets.

**Comment by poettering** [comment]
Note that there's plenty of infrastructure to push coredump extracts upstreams from enduser systems, in order to figure out how software behaves in the wild. Our coredump logic hence needs to keep the coredumps around for a while, on any kind of system, not just developer's machines. 

You can turn off coredump collection locally, see coredump.conf(5).

Also note that systemd's coredump collection by default will not use more than 10% of the file system size of /var/, and also ensure that at least 15% of the file system always remain free. Moreover coredumps are automatically cleaned up after 3d, through a tmpfiles rule. These three rules together should make sure that filling up your harddisk persistently should not happen.

Hence, I don't think there's anything to fix upstream. The currentl logic is very defensive, is helpful for debugging, and documented. If you disagree with this, please consider talking to your downstreams maybe they are willing to change the defaults for your downstream. Otherwise: local configuration for this is available already, and permits you to make the desired changes easily without either upstream nor downstream support.

I hope this make sense!
