### ISSUE TITLE
TemporaryFileSystem= is remounted between ExecStartPre= and ExecStart=

### ISSUE THREAD

**Issue by npmccallum** [systemd/systemd#8695]
I want to override a unit file (i.e. `systemctl edit my.service`) and specify `TemporaryFileSystem=`. Then I want to specify a command in `ExecStartPre=` which creates a custom execution environment on top of the temporary file system. However, apparently the `tmpfs` is remounted between `ExecStartPre=` and `ExecStart=`; the latter command always sees an empty tmpfs.

I can override `ExecStart=` directly, but then I don't get further distribution changes to `ExecStart=` for free. Would it be possible to change this behavior? Possibly behind an option?

**Comment by sezaru** [comment]
Is this still being considered?

Seems like a very good improvement to allow tools like [vault-cli](https://github.com/peopledoc/vault-cli) and [envconsul](https://github.com/hashicorp/envconsul) to safely store secrets in a tmpfs directory that will be removed when the service stops.

**Comment by poettering** [comment]
So I think we should close this: It appears to me that you should put your data in RuntimeDirectory=. It is backed by tmpfs, lives as long as the service, and is not cleaned up between invoked processes. It's useful for exchanging data, which appears to be the goal here.

Hence closing.

**Comment by riobard** [comment]
@poettering I propose to reconsider the issue, but for a different use case.

Remounting `TemporaryFileSystem=` prevents `ExecStartPre=` from doing initialization work for `ExecStart=` in a completely isolated directory from host file system. For example, programs in `ExecStart=` cannot have dynamically generated `/etc/resolv.conf` from `ExecStartPre` to use custom name servers. 

A typical use case is WireGuard's [Routing & Network Namespace Integration](https://www.wireguard.com/netns/), where you run programs in an isolated network namespace to route all traffic thru VPN. But the example leaks DNS queries because name resolution is still done by host's `/etc/resolv.conf` (e.g. via `systemd-resolved` over D-Bus because of `/etc/nsswitch.conf`).

`ip netns` automatically bind mount network-related config files in `/etc/netns/[NETNS]` to `/etc`, but `systemd.exec` does not (and should not) do so because it creates unnamed network namespace by default.

A workaround is to use `BindPaths=` to bind mount selective files from host file system, but it lacks the flexibility to dynamically generate system-wide config files on-the-fly (i.e. files which might be different for templated service units). `ConfigurationDirectory=` does not help either because it's located under host's `/etc/[user_defined_name]/` where here we want to customize files in `/etc` itself.

In general, `TemporaryFileSystem=` without remounting among `Exec*=` could provide ideal scratch space for a service's various helper processes to collaborate without touching host file system. Correct me if wrong but I haven't find any simpler alternatives.

**Comment by philfry** [comment]
Exactly my use case.

Has anyone ever found a workaround for that, i.e. preseeding files in that tmpfs? With the tmpfs being remounted between `ExecStartPre` and `ExecStart` the only way would be to use a wrapper script that does `ExecStartPre`'s work in `ExecStart`. And that's pretty ugly.
