### ISSUE TITLE
Stopping systemd-nspawn@machine.service timing out after 90s

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#870]
http://s.natalian.org/2015-08-05/debug-container-shutdown.png

How do I debug this? So I can figure out where the problem lies?

status and journalctl aren't giving me something to blame.

**Comment by richardmaw-codethink** [comment]
When you try to stop an nspawn'ed service, unless you have modified it from the defaults, it will send `SIGRTMIN+3` to the container, which the systemd in the container interprets as equivalent to running `systemctl halt`, so starts `halt.target`.

As I understand it, systemd should only need to kill the container if it fails to reach `halt.target` quickly enough, since after that is reached, `systemd-nspawn` should notice and terminate successfully.

If you're not getting any useful output at this point, you could try increasing the log level by running `systemctl edit --full systemd-nspawn@arch.service` and appending `--log-level=debug` to the `ExecStart=` line.

**Comment by poettering** [comment]
@kaihendry can you boot the container with "systemd.log_level=debug" on the nspawn command line (which has the same effect as adding it to the kernel cmdline, except we do it for containers...). THen, please paste the end part of journalctl -b in the container).

Most like this is a cgroup notification problem, and there was a user still logged into the container when it was shutdown. This will be fixed with the move to the unified hierarchy...

**Comment by kaihendry** [comment]
I'm booting my arch container like so:

```
sudo /usr/bin/systemd-nspawn --boot --link-journal=try-guest --network-veth --machine=arch -- --log-level=debug
```

When I terminate or poweroff or ]]] it shuts down in an instant. However if I run `sudo systemctl stop systemd-nspawn@arch.service` it take 90s... I don't understand why the service file has different behaviour? And I am not sure how to pass "systemd.log_level=debug" in the service file nor the system-nspawn command line.

Judging by the network orientated messages: http://s.natalian.org/2015-08-06/stop-90s.png

I think it has something to do with OpenVPN running. And sure enough, if I stop that service before stopping the container, it shuts down in an instant. There must be something wrong with https://projects.archlinux.org/svntogit/packages.git/tree/trunk/openvpn@.service?h=packages/openvpn

I should try https://github.com/OpenVPN/openvpn/blob/master/distro/systemd/openvpn-client@.service to see if it fixes the issue.

**Comment by kaihendry** [comment]
I can confirm the upstream OpenVPN's service file works better. Although they were missing  /usr/lib/tmpfiles.d/openvpn.conf

https://bugs.archlinux.org/task/43278#comment137975
