### ISSUE TITLE
CPUQuota property can be set but not retrieved via systemctl

### ISSUE THREAD

**Issue by troyengel** [systemd/systemd#8853]
### Submission type

 - Bug report (maybe RFE? not sure)

### systemd version the issue has been seen with

* Debian 9: 232-25+deb9u3
* ArchLinux: 238.76-1

### Used distribution

* Debian 9
* ArchLinux

### In case of bug report: Steps to reproduce the problem

```
# systemctl start httpd.service
# systemctl set-property httpd.service CPUQuota=200%

# systemctl show httpd.service -p CPUQuota
(no output)

# cat /etc/systemd/system.control/httpd.service.d/50-CPUQuota.conf 
# This is a drop-in unit file extension, created via "systemctl set-property"
# or an equivalent operation. Do not edit.
[Service]
CPUQuota=200%
```

Basically, we can set the property runtime or via an override.conf (`systemctl edit ...`), but we cannot query the property at runtime easily due to the mechanics of how it's converted internally to shares and slices. If it was adjusted using `--runtime` then we lack a config file to go look it up as well.

Users should be able to query the `CPUQuota` property generically and have systemctl/systemd do the reverse calculations and display the expected percentage result. If the property has been set using `systemctl set-property --runtime ...` it's incredibly hard to determine what the current setting is given the lack of querying CPUQuota as a collected/calculated value.

**Comment by poettering** [comment]
Note that "systemctl show" shows low-level bus properties, and those don't map 1:1 to the unit file settings, as they are generally normalized, generalized and more precise over the unit file settings.

The CPUQuota= setting is exposed as `CPUQuotaPerSecUSec` property. Instead of a percentage it takes a value in µs per 1s of CPU time. Converting that a percentage is pretty easy. If you read the property as p it is `p / 10000`.

Closing, as this is already available...

And yes, this is admittedly a bit surprising, but "show" is supposed to be more low-level and not lose the greater granularity used internally... I hope that makes some sense. (Note that this is documented in the systemctl show man page btw, though not specifically for CPUQuota=)

**Comment by troyengel** [comment]
Hi Lennart, did you perhaps mean `1000` not `10000`? The value has a trailing 'ms' so it's now become a pain to script this out from a user perspective, shouldn't systemctl do this for us? It can be automated easily by the software and save everyone the hassle of manually calculating it.

```
tengel@peanut:~$ cat /etc/systemd/system/boinc-client.service.d/override.conf 
[Service]
CPUQuota=19%

tengel@peanut:~$ sudo systemctl show boinc-client -p CPUQuotaPerSecUSec
CPUQuotaPerSecUSec=190ms

tengel@peanut:~$ echo "($(sudo systemctl show boinc-client -p CPUQuotaPerSecUSec | cut -f2 -d= | sed 's/ms$//g')/1000)*100" | bc -l
19.00000000000000000000
```
Not exactly user-friendly at all, and not documented in the `CPUQuota` resource control doc on needing to do this as well. If nothing else, this should be documented and the example process given to derive this value for the average systems administrator using systemd. $0.02.

The absolute best case is an RFE to systemctl to implement `get-property` to align with `set-property`, I'm only using `show` because this is the only knob available - I was surprised to find no `get-property` existed yet to be honest. (this in reply to your comment about bus interfaces, which means little to the system administrator on the outside running the system who is not a systemd coder)
