### ISSUE TITLE
Make systemctl status --lines=0 as its default behavior until journald becomes reasonably fast

### ISSUE THREAD

**Issue by ko-zu** [systemd/systemd#8864]
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

### Used distribution

> ubuntu 18.04 bionic beaver

### In case of bug report: Expected behaviour you didn't see

for `systemctl status`,  `--lines=0` should be its default behavior to mitigate heavy IO load on systems that have large /var/log/journal.

### In case of bug report: Unexpected behaviour you saw

As discussed in https://github.com/systemd/systemd/issues/2460
`systemctl status` implies `--lines=10` and it causes heavy IO on the journald storage.

Currently journald does not have ability to query the last few lines of a unit efficiently. Until journald implement that, `--lines=10` should be disabled by default. The last 10 logs might be helpful but not necessary for the purpose of `systemctl status`.

### In case of bug report: Steps to reproduce the problem

Generate large amount of journald logs, then run `systemctl status systemd-journald`

**Comment by poettering** [comment]
Uh, yes, journal performance degrades if you have tons of individual journal files on rotating media, but it's generally fine in most other cases. 

Yes, it's unfortunate if this is slow for you, but I am not convinced that individual cases really mean we should turn this off for everybody. I mean, it's very easy to turn this off locally for yourself, simple set "alias systemctl=systemctl --lines=0" in your bashrc or suchlike.

I hope this makes sense, but let's close this here, and instead fix the actual issues, rather than degrade things for everybody.
