### ISSUE TITLE
order in fstab doesn't seem to be honoured.

### ISSUE THREAD

**Issue by Brane2** [systemd/systemd#89]
I have in fstab mount bind line ( /A /B none bind 0 0 ), followed by nfs4 mount to /A/mountA.

Expected end result be to have nfs share mounted on /A/mountA and local files on /B/mountA.

But systemd generators seem to make mount in inverted order, so I get nfsmount on both ends of bind-mount. 

That is, it first does nfs mount to /A/mountA and then mount-binds that to /B/mountA.

BTW; I haven't had the chance to try the latest git yet but v220, but suspect it does the same...

**Comment by poettering** [comment]
The current behaviour is intended behaviour really. We automatically determine dependencies from each /etc/fstab line, and only follow the minimal ordering necessary, and mount as much as we can in parallel. For bind mounts this means that we mount everything required for the source and for the destination before the bind mount itself. Which is the behaviour you see here.

Yes, this is a change of behaviour from classic sysv, but I am pretty sure systemd's behaviour is the better one.

I am sorry this breaks what you intend to do, but I am still sure systemd should do this all the way it does.

Closing hence! Sorry!

**Comment by Brane2** [comment]
I have nfs mount on my laptop and I need extra bind mount so that I have access to underlying map so I can copy files there for situations without access to nfs mount.

this means that my programs will see data in /A/mountA all the time, either nfs4 mount or local map.

And /B/mountA with access to underlying loacl map, so I can manually copy nfsmounted /A/mountA to local map.

I don't see how this can be efficiently done with current system.

Parallel mount is fine, but you should have some dependency map of all mounts.

Otherwise fstab would be totally useless for combined mounts.

**Comment by xnox** [comment]
Instead of using /etc/fstab you can create .mount units yourself in /etc/systemd/system/ with the ordering & behaviour the way you like.

**Comment by Brane2** [comment]
BTW, shouldn't you have more than personal opinion when implementing something that significantly deviates from existing standard behaviour ?

**Comment by xnox** [comment]
"The  order  of records in fstab is important because fsck(8), mount(8), and umount(8) sequentially iterate through fstab doing their thing, though at boot time mountall(8) may process the file out-of-order when it believes it is safe to do so."

Systemd implements functionality that a mountall would do, and strong guarantees are in place to determine what is safe to do. There are alternative options available to implement a different strategy.

**Comment by poettering** [comment]
Brane2: if you have mounts to mount where the ordering in which to apply them can only be derived from the order in which you list them rather than from the contents of them, then my recommendation would be to place them in a shell script and execute that shell script directly, because you actually want a stateful language in that case, instead of just a declaration of mounts...

Well, we implemented things the way they are after discussion in the systemd community. This hardly a "personal" design choice...

**Comment by johannbg** [comment]
@xnox users should not be forced to bypass fstab and write .mount units manually ( or write shell scripts for that matter ). 

If they have to do so arguably that's failure on our end. 

@Brane2 in v220 new systemd dependency fstab options got added, have you tested those to see if they dont already solve your issue? 

Some examples are given by @karelzak  in https://github.com/systemd/systemd/commit/3519d230c8bafe834b2dac26ace49fcfba139823
