### ISSUE TITLE
Make documentation that we won't look up TLD queries via classic DNS (but only via LLMNR) more explicit

### ISSUE THREAD

**Issue by ysangkok** [systemd/systemd#8967]
**systemd version the issue has been seen with**

master

**Used distribution**
Ubuntu 18.04

**Expected behaviour you didn't see**
Documentation doesn't state that records on TLD's can't be looked up, and that all links to TLD's, which have been valid on all systems I previously used, are now broken.

**Unexpected behaviour you saw**
I failed to find a note in documentation that looking up records on TLD's will result in SERVFAIL, because systemd-resolve defers to LLMNR even for TLD's.  It is a big gotcha, since I thought I was just switching DNS servers with the upgrade to 18.04. I never heard about LLMNR, and I didn't expect its introduction to break this DNS feature.

**Steps to reproduce the problem**
```
nslookup dk.
nslookup ai.
```

See also https://github.com/systemd/systemd/issues/6224#issuecomment-312639959

**Comment by lucaswerkmeister** [comment]
The following can be found in [**systemd-resolved**(8)](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html):

> Lookup requests are routed to the available DNS servers and LLMNR interfaces according to the following rules:
> *Lookups for the special hostname "localhost" are never routed to the network. (A few other, special domains are handled the same way.)
> * Single-label names are routed to all local interfaces capable of IP multicasting, using the LLMNR protocol. Lookups for IPv4 addresses are only sent via LLMNR on IPv4, and lookups for IPv6 addresses are only sent via LLMNR on IPv6. Lookups for the locally configured host name and the "_gateway" host name are never routed to LLMNR.
> * Multi-label names are routed to all local interfaces that have a DNS server configured, plus the globally configured DNS server if there is one. Address lookups from the link-local address range are never routed to DNS.

Except for the terminology of a “single-label name” instead of a “top-level domain”, this seems to me to be the documentation you’re looking for.

You can also bypass `systemd-resolved` by explicitly specifying a different DNS server, e. g. with `nslookup dk. 8.8.8.8`, `dig @1.1.1.1 dk.` or `host dk. 9.9.9.9`.

**Comment by poettering** [comment]
So resolved is really supposed to be a DNS client for applications, and tries to make the safest and most appropriate choices for that. There's this statement from the IAB:

https://www.iab.org/documents/correspondence-reports-documents/2013-2/iab-statement-dotless-domains-considered-harmful/

Following that logic we won't route single-label names (i.e. "dotless" domains, i.e. "TLDs") to classic DNS, and instead resolve them in a purely local context, i.e. LLMNR or based on search domains (search domains are not apply on queries coming in via local DNS though, only to those coming in via NSS or dbus). And yes, this is documented, but I figure we could make this even more explict.

**Comment by filbranden** [comment]
But isn't there a difference between `nslookup ai` (indeed dotless) and `nslookup ai.`, which does have a dot at the end? The latter is pretty much unambigously referring to the TLD...

Perhaps you mean that it's a bad idea to use a TLD in this way...

But (assuming it's possible to differentiate them) perhaps it would be good to resolve that correctly, no?

**Comment by poettering** [comment]
@filbranden note that the trailing dot thing never hits the wire. Also, almost noone uses it or is even aware it exists...

**Comment by underrun** [comment]
`uz.` can be added to the list of `dk.` and `ai.` 

@lucaswerkmeister these technically are /not/ single label domain names as they include the DNS root label (which is an empty string after the trailing dot) - these names have 2 labels specified.

@filbranden is right to point out that this creates significant ambiguity.

@poettering the iab doc linked makes it very clear the problem isn't TLDs but the literal dots:

> Since the advent of the DNS, Internet naming systems have always relied on the presence of dots in names to distinguish between names that are intended to be interpreted locally, and names that are intended to be looked up on the Internet.

it makes total sense to follow that recommendation as it applies to not attempting to check the root zone for a name with no dots in it, but there's nothing in there about ignoring dots in names.

I'm not going to claim that empty label as a name for the root zone or FQDNs with trailing dots are widely known. But really if /almost/ noone uses them or are even aware of their existence, what you will end up with is a class of bugs that are incredibly subtle and difficult to diagnose.

I'm surprised and concerned to hear that "the trailing dot thing never hits the wire." This is a foundational design flaw in a DNS resolver.

**Comment by poettering** [comment]
I guess we document this now, since 2bd5e1b272cf6f639e024794cb236de1a2f9835e (and you can turn the behaviour off, if you really want to). Closing.

**Comment by underrun** [comment]
@poettering as noted earlier in this issue, in the documentation liked in 2bd5e1b and in the iab doc that solutions is not intended to cover the use case of looking up TLDs but rather if no public DNS is configured.

maybe that documentation is a little clearer but people will still only know that resolved doesn't behave appropriately if they read the description of an option that is designed to be used to implement a different kind of broken behavior.

to be clear, a single label with no dot should not be forwarded to external resolver. a single label FQDN with a trailing dot should be treated as an external name.

there's no way to achieve that behavior (the correct standards compliant behavior) with resolved and its still not /clearly/ documented.

**Comment by poettering** [comment]
> From resolved point of view... Can you tell whether the user asked for `dk.` or `dk` and handle them differently?

This is pointless. Yes, some DNS gurus will do "ping foo." to find their machine "foo" in the local network, if they use LLMNR. But most people will instead just type "ping foo". I for one do.

So, yes, we could of course distuingish dot suffixed and non dot suffixed names, but given that noone uses the former and everyone uses the latter and we don't want this stuff to needlessly leak onto the internet it's a pointless check to make. if we'd make it then the stuff everyone does will leak onto the internet, but that's what we want to avoid.

**Comment by underrun** [comment]
> Yes, some DNS gurus will do "ping foo." to find their machine "foo" in the local network, if they use LLMNR.

It's unlikely that anyone looking for `foo.` would ever want `foo` on a local network even using LLMNR. The trailing dot, especially to "DNS gurus" means we're looking for something relative to the root domain.

> if we'd make it then the stuff everyone does will leak onto the internet, but that's what we want to avoid.

In fact, differentiating is exactly the way to avoid leaking bare labels onto the public internet. The "solution" resolved has implemented for non-public DNS is a terrible way to approach this issue as it make is way /more/ likely that people will end up leaking these things onto the internet by enabling `ResolveUnicastSingleLabel` when they are connected to the public internet. Resolving a single label on the public internet should never be done and it really shouldn't be done when working in a non-public network either. Users and software should be required to use a multi-label name to query externally and one of those labels allowed should be the root domain as specified by a trailing dot (`dk.` is a two label name and `dk` is a single label).

>This is pointless.

From a user standpoint and with `ping` or `nslookup` or whatever that might be a reasonable argument. People unfamiliar with DNS standards are not likely to grok the nuances of names vs labels and that root is actually a label that consists of an empty string and why this matters technically to the global internet. 

The real problem here is NOT end user experience (which would be better and safer if people could never resolve single labels except via search domains or LLMNR and that if they really need to do ask about TLDs they learn that they need to specify a trailing dot). 

The real problem here is that linux systems using resolved run software that assumes a working DNS resolver. Systems software the implements standards compliant attempts at name resolution should not fail because systemd gets in their way and refuses to lookup `dk.` on the public internet. It's not users but software that cares about using DNS correctly that is negatively impacted the most here.

Sure - there's a work around. I've got to install a real DNS resolver on my system or network and configure my software to use that instead of default DNS. Frankly this sucks.

Marginalizing the use cases of systems software, cybersecurity, and internet mapping/exploration/research isn't a good way for a project so important, core and widely distributed to go. 

`ResolveUnicastSingleLabel` is a bad idea that undermines your stated goal to keep "the stuff everyone does" from leaking onto the internet. 

The standards compliant resolution for anyone who needs to set that option would instead be to query their label with a trailing dot. That option is dangerous and counter to what anyone who wants to be able to look up `dk.` or any of the other top level domains through DNS wants to actually do.

Documentation still doesn't make it clear that resolved is refusing standards compliance with two-label trailing dot names like `dk.` which includes the root label and so is not a single label.

**Comment by marka63** [comment]
@poettering 

Please read what the IAB said again.  They where telling people who intended to get a TLD that user@TLD won't work for email and that https://TLD/ also won't work as well as any similar use.  It was a expectation setting exercise for those wanting to purchase a TLD from ICANN.

It was, most definitely, not a directive to resolver developers to not not send queries for TLD names to the root servers.  If you got the idea that it was telling DNS developers to do anything at all you where mistaken.  If there is ever such a directive it will come in the form of a RFC from the DNSOP working group of the IETF.

As someone who has maintained resolver code in BIND for the last 30 years.  Breaking existing behaviour introduces security problems.  You are being told you are doing this.  Pay attention.

**Comment by letoams** [comment]
The argument that trailing dots is for geeks only is wrong. Whether or not you like it, it is an established API for 20+ years.
Documenting won't help code that depends on this correct behaviour.

With query minimalization you will also see a lot more single label queries. Handles these correctly is extremely important.

systemd-resolved needs to be fixed to handle the trailing dot.

**Comment by pemensik** [comment]
> > From resolved point of view... Can you tell whether the user asked for `dk.` or `dk` and handle them differently?
> 
> This is pointless. Yes, some DNS gurus will do "ping foo." to find their machine "foo" in the local network, if they use LLMNR. But most people will instead just type "ping foo". I for one do.
> 
> So, yes, we could of course distuingish dot suffixed and non dot suffixed names, but given that noone uses the former and everyone uses the latter and we don't want this stuff to needlessly leak onto the internet it's a pointless check to make. if we'd make it then the stuff everyone does will leak onto the internet, but that's what we want to avoid.

Maybe it would help also, if queries received over DNS preferred DNS resolution over local LLMNR. Resolve bare names with nss_resolve first over LLMNR, no problem with that. But if query arrived via DNS, it should be resolved via DNS first. LLLMNR should be used only as a backup. And not used at all with trailing dot.

**Comment by poettering** [comment]
No, it shouldn't matter how local apps pass requests to our local stub, we should do what is configured. We are not in political business of saying DNS good LLMNR bad. We just do what is configured.

BTW, the trailing dot thing was implemented in 3354f5003cc162bd5b549b23b92265874a0842b0

**Comment by pemensik** [comment]
> No, it shouldn't matter how local apps pass requests to our local stub, we should do what is configured. We are not in political business of saying DNS good LLMNR bad. We just do what is configured.

Yes, you are. Just the other party. When you can choose something other than DNS, you *always* choose that. LLMNR should be done exclusively for requests over nss (where llmnr module would be instead resolve). When asked name over DNS, it has to prefer DNS. Because /etc/resolv.conf is configuration of DNS. So do what is configured and answer DNS queries by DNS, please. Use helper fallbacks only when primary queries fail.
