### ISSUE TITLE
per-user iptables rules don't work with systemd-resolved

### ISSUE THREAD

**Issue by Spongman** [systemd/systemd#8987]
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

Ubuntu 18.04 LTS

with systemd-resolved disabled, iptables per-user rules can be used to filter/redirect outgoing DNS traffic.

with systemd-resolved installed, these rules don't seem to have any effect.

**Comment by poettering** [comment]
The traffic is generated by systemd-resolved, which runs under its own user ID, and his heavily sandboxed. It implements a system-wide cache. All this together means that not all queries actually result in traffic, and when they do they will be attributed to the systemd-resolved user, not the original user issuing the request.

This is a design choice, in order to build a more secure and efficient system.

On cgroupsv2 systems you can filter and account IP traffic for systemd-resolved with IPAddressAllow=/IPAddressDeny= and IPAccounting, but you can also use iptables and match for the systemd-resolve user.

Anyway, I don't think there's anything to change here, this is done on purpose, and is supposed to be a good thing. Hence closing, I hope that makes sense.
