### ISSUE TITLE
nspawn & networkd not configure right IP address

### ISSUE THREAD

**Issue by GongT** [systemd/systemd#8996]
**systemd version the issue has been seen with**
> systemd 238 on Fedora 28

**the issue**
Systemd (or maybe other thing?) changing my network interface IP address. So I can not connect to the container

### create machine:
**install files:**
```bash
ROOT="/var/lib/machines/DevelopmentEnvironment"
dnf \
    --setopt=config_file_path=/etc/dnf/dnf.conf \
    --setopt=reposdir=/etc/yum.repos.d \
    --releasever=/ \
    --installroot="$ROOT" \
    systemd bash net-tools
chroot "$ROOT" systemctl enable systemd-networkd systemd-resolved
```
**.nspawn:**
```
[Exec]
Boot=yes
[Network]
Bridge=bridge0
[Files]
Bind=/data:/data
```

### start the machine:
```bash
systemd-nspawn --settings=trusted --machine DevelopmentEnvironment
sleep .5
# AAA
machinectl shell DevelopmentEnvironment /usr/sbin/ifconfig host0
sleep 5
# BBB
machinectl shell DevelopmentEnvironment /usr/sbin/ifconfig host0
# CCCC
machinectl shell DevelopmentEnvironment /usr/bin/journalctl -ocat --no-pager -u systemd-networkd
```

## Result:
* **AAA:** IP = 10.0.0.53 💯 
* **BBB:** IP = 169.254.94.169 🤕
* **CCC:**     
```
host0: Cannot disable kernel IPv6 accept_ra for interface: Read-only file system
host0: IPv6 successfully enabled
Enumeration completed
Started Network Service.
host0: Gained carrier
host0: DHCPv4 address 10.0.0.53/16 via 10.0.0.1
Not connected to system bus, not setting hostname.
host0: Gained IPv6LL
host0: Configured
```

**Comment by poettering** [comment]
169.254.94.169 is an IPv4LL address. It's usually assigned in addition to any static IP address, unless you turn it off via LinkLocalAddressing= in the .network file.

"ifconfig" has been obsolete since a long time. Don't use it. It's confusing and does not understand that  a single interface can have multiple IP addresses assigned. Use "ip" again, which has been the right tools to use since more than a decade, and it does handle this properly.

If you invoke "ip addr" rather than "ifconfig", everything shold look correctly. You'll early on get the static IP address, and then a little bit later the IPv4LL address is added too, after it was probed for uniqueness. 

Closing, hence.
