### ISSUE TITLE
RFE: Add settle to udev library

### ISSUE THREAD

**Issue by tasleson** [systemd/systemd#9010]
If would be helpful for libudev to include a function that provides the same functionality as `udevadm settle`.  This would prevent software from having to fork & exec the command line tool.

If this seems like a reasonable request and would be acceptable, I'm willing to provide a PR that does just that.

Thanks!

**Comment by poettering** [comment]
Software should wait for the devices it needs to show up, and not wait for a generic "wait until 'everything' is settled". I am pretty sure we should not add something like this, as it invites sloppy programming. At this point in time we really should not encourage any APIs that focus on sloppy "wait for everything" operations...

**Comment by tasleson** [comment]
In my particular use case, I'm  creating block devices and have no need to wait for them them to show up, I'm interacting with it using an IOCTL interface and I'm not touching the block device and have no need for it to "show up".  The problem is everyone else in user space gets excited about the block device udev event and access it, eg.  identify it by running blkid and others which causes me to not be able to manage the the device as it's busy.  So in this case I'm simply waiting for all of the other programming to get done doing it's thing so that I can do my thing.  What would you suggest I do in this case where I need to wait for everyone else to get out of my way?

**Comment by mvollmer** [comment]
You can use flock to arbitrate access to the block device.  While you have an exclusive lock, udevd wont process any rules for it.  Once you are done, make sure to trigger a explicit "change" event if that is necessary.

**Comment by poettering** [comment]
What @mvollmer is described here btw: https://systemd.io/BLOCK_DEVICE_LOCKING.html

**Comment by poettering** [comment]
> In my particular use case, I'm creating block devices and have no need to wait for them them to "show up" on the filesystem, I'm interacting with it using an IOCTL interface. The problem is everyone else in user space gets excited about the block device udev event and access it, eg. identify it by running blkid and others which causes me to not be able to manage the the device as it's busy. So in this case I'm simply waiting for all of the other programming to get done doing it's thing so that I can do my thing. What would you suggest I do in this case where I need to wait for everyone else to get out of my way?

So, as @mvollmer suggested, take a lock. udev when probing takes it too, hence if you take a blocking BSD lock you should be fine, and can wait until the right moment where either udev is done probing the device or — if you happen to be quick — before it started doing that.

The udev settle concept is racy for this. udev is fully async, hence it might happen that settle tells you that all devices finished processing, but only because they haven't been started processing yet. The BSD locking otoh makes all of this racefree.

> Once you are done, make sure to trigger a explicit "change" event if that is necessary.

This is not necessary btw. udev watches most block devices (those with a 'watch' option set in udev rules) for close() inotify events, and if so reprobes automatically. This means normally, it's entirely sufficient to open() the device, then take the BSD lock, and eventually close it and udev will behave nicely just like that, without any other special magic, and no explicit retriggering.

**Comment by poettering** [comment]
Anyway, I think the BSD lock approach is the much better way out for the usecase, hence let's close this issue. Hope that makes sense.
