### ISSUE TITLE
Have systemd-boot remember last boot

### ISSUE THREAD

**Issue by neersighted** [systemd/systemd#909]
I believe that a useful option for systemd-boot (nee gummiboot, if I am not mistaken) would be for it to have the option to remember the last booted entry as the default. A config option like `default last` or something like it (`$last`?) could enable this feature. Any thoughts?

**Comment by grawity** [comment]
Would be nice, but IIRC this was already rejected earlier due to possible reliability issues... Can't find the relevant mailing-list post though.

That is, using EFI variables for this (as with the existing LoaderEntryDefault) could easily cause troubles with broken firmware &ndash; there exist systems which stop allowing EFI variable writes, or even outright brick the machine, after reaching some amount of writes to the nvram. That's kinda bad.

Storing this in the EFI system partition (as grub does) would probably work better, but ask @kaysievers about the fragility of FAT32.

(Though IMHO it's mostly caused by poor drivers. Linux corrupts my /boot/efi _way_ more often than Windows corrupts my flash drives.)

**Comment by neersighted** [comment]
A fair point. Part of the issue could be solved by only setting the variable if it has to be (ie we boot a different application than the last boot), but I can see that nvram wear-and-tear could be an issue. As far as the ESP goes, I've never had any issues with mine. I assume that the FS drivers are provided by the EFI firmware? If so, that may be the best option.

**Comment by kaysievers** [comment]
We have a plan to install along with the kernel image:
  /boot/EFI/Linux/distro-4.1.2-00343.efi
a file with the same name:
    /boot/EFI/Linux/distro-4.1.2-00343.loader
which contains:
  BOOT_ATTEMPTS=3

The boot manager would find that file, check that the value. If it is 0 already, it would skip this entry/kernel. If it is larger than 0, decrement the value in the file by 1 and execute the kernel .

The running system would read the boot managers instruction and if the system appears fine, just delete the entire *.loader file.

That would provide the "we installed the update and this kernel boots, let's mark it as active" functionality.
