### ISSUE TITLE
Is there any way to configure systemd (pid=1)'s limits?

### ISSUE THREAD

**Issue by jeffrey4l** [systemd/systemd#9205]
**systemd version the issue has been seen with**
centos7: systemd-219-42.el7.x86_64
arch linux: systemd 238.76-1

I found different systemd on different OS using different limits. 

```
# centos 7.4
$ prlimit -p 1 | grep NOFILE
NOFILE     max number of open files               65536     65536 
```

```
# archlinux
$ sudo prlimit -p 1  | grep NOFILE 
NOFILE     max number of open files             1048576   1048576 files
```

I can not find a way to config this. 

I also find if we use `LimitNOFILE=infinity` in `*.service` file, it is not a really infinity. it use the systemd (pid=1) limit as the infinity. 

like 

```
[root@node2 systemd]# prlimit -p 1
RESOURCE   DESCRIPTION                             SOFT      HARD UNITS
...
NOFILE     max number of open files               65536     65536 
...

[root@node2 systemd]# systemctl cat docker 
# /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network-online.target firewalld.service
Wants=network-online.target

[Service]
...
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
...

[root@node2 systemd]# systemctl show docker | grep NOFILE
LimitNOFILE=18446744073709551615

[root@node2 systemd]# ps aux | grep dockerd
root       868  0.1  0.9 1412052 79508 ?       Ssl  09:34   0:02 /usr/bin/dockerd
root      7786  0.0  0.0 112664   976 pts/3    S+   09:57   0:00 grep --color=auto dockerd

[root@node2 systemd]# prlimit -p 868
RESOURCE   DESCRIPTION                             SOFT      HARD UNITS
...
NOFILE     max number of open files               65536     65536 
...
```

**Comment by kirbyfan64** [comment]
See [systemd-system.conf(5)](https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html#DefaultLimitCPU=) (TL;DR is that you probably want to set DefaultLimitNOFILE= under the [Manager] section in /etc/systemd/system.conf in /etc/systemd/user.conf).

**Comment by poettering** [comment]
This is a bug and feature request tracker, not a support forum. Please direct questions like this to the systemd mailing list instead.

That said: the kernel does not permit an "unlimited" RLIMIT_NOFILE. You can easily see that by typing "ulimit -n unlimited" in a root shell, which is refused.

In current versions, systemd will set for itself RLIMIT_NOFILE to the highest value the kernel allows, which is the value readable from /proc/sys/fs/nr_open. systemd needs to deal with a lot of file descriptors, hence operating with the kernel's default of 1K is not going to work. (In particular as the kernel's default of 1K is primarily this low because select() couldn't deal with more, and thus if you run code that uses select() with a higher limit you are in trouble). systemd will pass on the original resource limit passed in by the kernel to all processes it forks off. You can adjust that though by setting DefaultLimitNOFILE= in system.conf. As the name of that option is supposed to clarify it only controls the *default* limit for units, but won't change anything for PID 1 itself.

Also, most code that adjusts resource limits will automatically fall back to the closest available value if it can't set the value to the requested one due to EPERM.
