### ISSUE TITLE
tmpfs mounted in XDG_RUNTIME_DIR makes previous content of the directory unavailable

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#9269]
**systemd version the issue has been seen with**
> systemd-238

**Used distribution**
 > Fedora

**Expected behaviour you didn't see**
 > XDG_RUNTIME_DIR contains content that was populated by PAM modules that run prior to pam_systemd.so.

**Unexpected behaviour you saw**
 > When user first logs in we mout tmpfs filesystem to ```/run/user/<UID>```, but we don't check the content of the directory and we simply over mount any content that is in the directory. This is problematic for example in cases when sssd PAM module obtains kerberos ticket on user's behalf and stores the ticket in the XDG_RUNTIME_DIR. Of course this is the generic problem not specific to sssd at all.

**Comment by poettering** [comment]
well, sssd shouldn't do that. systemd introduced the dir, and defines its runtime. Accessing it before its set up and has all the right perms and stuff is simply not supported. Also, we had that discussion a year or two ago already, and back then sssd switched its kerberos ticket storage to the kernel keyring. Which solves the problem properly and the right way.

What is there left to fix here?

**Comment by msekletar** [comment]
Well, sssd can (and I think by default in Fedora uses) use kernel keyring.  However, you can still configure file-based ticket cache.

Lifetime of the directory is more-less defined by ordering of PAM modules and our module kicks in late in the PAM dance.

**Comment by poettering** [comment]
Well, sssd should not write to the runtime directory before its set up. It's lifecycled by logind, and sssd really should *never* access it unless it has been set up by logind.

I am sorry, but this simply buggy in sssd, they need to find a different place to store their stuff, if they don't want to use the kernel keyring anymore...

If the PAM stack is aborted while it runs (because some PAM module says "oh no"), then the runtime dir stuff is only reverted if pam_systemd sets it up. It's hence essential that pam_systemd does it. It's the only way it's correctly set up.

logind has been using tmpfs for this since v211, back in 2014, four years ago, and it's done for a good reason: so that we can put a limit on the per-user runtime data. sssd was already fixed like this, and it shouldn't do what it did there in the first place...

Anyway, closing this, please file a bug against sssd asking them to stop doing this, it's 2018 now...

(one thing they could do if they insist to do this from PAM, is to run their module twice: once early in the stack, before pam_systemd runs, then store the ticket material in pam_set_data() of the PAM context, and then a second time after pam_systemd where they write the data out. That way they can run before systemd but still write to a properly set up runtime dir.)
