### ISSUE TITLE
systemd-networkd: make sure RouterMetric= also applies to routes to the local subnet

### ISSUE THREAD

**Issue by cshapeshifter** [systemd/systemd#928]
I have a wireless and an ethernet adaptor. If the ethernet is connected, I don't want the wireless to connect, even if there's a known AP in range. There is currently no way to configure this in systemd-networkd and I have to use an alternative like networkmanager.

**Comment by poettering** [comment]
Hmm, we actually wanted to support a per-interface metric setting that would then be inherited by all the interface's routes. That way you could have multiple interfaces up at the same time, but traffic gets routed to the interface with the routes with the lowest metric.

@teg what happened to the plans to add a per-interface default metric setting that would then be inherited by all dhcp or static routes on the iface?

@cshapeshifter would that not suffice for you?

**Comment by cshapeshifter** [comment]
I guess that would work for me, as long as it's working reliably. It's all about forcing traffic over a preferred connection (e.g. because the wifi would be slow or unstable). Then again, I could imagine some people would like their wifi to stay completely disconnected as long as there is a working ethernet connection available. I think these are two distinct features, each with their own merits and use cases.

**Comment by Mic92** [comment]
I do the following:

```
$ cat ethernet.network
[Match]
Name=enp0s25

[Network]
DHCP=both

[DHCP]
RouteMetric=512
```

```
$ cat wlan.network
[Match]
Type=wlan

[Network]
DHCP=both

[DHCP]
RouteMetric=1024
```

which leads to something like this

```
$ ip route
default via 10.100.0.1 dev enp0s25  proto dhcp  src 10.100.19.142  metric 512
default via 10.100.0.1 dev wlp3s0  proto dhcp  src 10.100.18.141  metric 1024
```

If you want immediately failover you might want to have a look at bonding.

**Comment by dhaines** [comment]
I would love to see this implemented. As it stands currently, the RouteMetric works for routed packets, but not for those that remain on the local subnet:

```
$ ip route
default via 172.16.0.1 dev ens9  proto dhcp  src 172.16.0.16  metric 512 
default via 172.16.0.1 dev wlp2s0  proto dhcp  src 172.16.0.16  metric 1024 
10.0.0.0/8 via 172.16.0.4 dev ens9  proto dhcp  metric 512 
10.0.0.0/8 via 172.16.0.4 dev wlp2s0  proto dhcp  metric 1024 
172.16.0.0/24 dev ens9  proto kernel  scope link  src 172.16.0.16 
172.16.0.0/24 dev wlp2s0  proto kernel  scope link  src 172.16.0.16 
172.16.0.1 dev ens9  proto dhcp  scope link  src 172.16.0.16  metric 512 
172.16.0.1 dev wlp2s0  proto dhcp  scope link  src 172.16.0.16  metric 1024 
```

**Comment by Mic92** [comment]
This is indeed unexpected. networkd sets a metric for the gateway on this interface,
but not for the subnet, where the allocated ip is included.
dhcpcd does apply a metric to both:

```
default via 172.23.75.193 dev wlp3s0  src 172.23.75.213  metric 305 
...
172.23.75.192/26 dev wlp3s0  proto kernel  scope link  src 172.23.75.213  metric 305 
```

Is there a reason for behaving like this?

**Comment by Kaned1as** [comment]
It seems subnet routes are configured with no metric via `address_configure` in `networkd-address.c` when obtaining an IP and dhcp-provided routes with metric are processed later via `link_set_dhcp_routes` in `networkd-dhcp4.c`.

**Comment by cgpe-a** [comment]
Although the subnet route metric problem could be addressed, from my experiences, I don't think this will be a complete solution for what people want. Let me explain...

The subnet routes are added by the kernel as a side effect of systemd-networkd adding interface addresses. manager_rtnl_process_route() could be updated to recognise these new routes by computing that they are network routes corresponding to known addresses on managed interfaces, then it could change the metric of the routes. The source of this metric could be the DHCP/RouteMetric setting if the DHCP client added the address, or a new Address/RouteMetric setting if the address is statically configured. It doesn't really make sense to borrow the Route/Metric setting in the static case, because there could be several - or none of them.

This would fix the problem of LAN traffic going to an unpredictable interface when both interfaces are up, but there would be another problem when one of the interfaces is down...

When the addresses are assigned by the DHCP client (or IPv4LL, etc) all is well, because carrier loss leads to address removal by systemd-networkd and therefore subnet route removal by the kernel, thanks to the link_stop_clients() call in link_carrier_lost().

However, if one or both of the addresses is statically configured, then there is nothing to remove the address on carrier loss, so there will always be a subnet route present. The kernel will pick the route with the lowest metric regardless of the oper-state (or the first route added if the metrics are the same), potentially sending traffic to a dead interface. This is unlikely to be what the user wanted.

For example...

Configure the wired interface with a static IP and the wifi with dynamic IP, then disconnect the wire. The user would expect to be able to contact LAN hosts over wifi, but may not be able to, because (with the fix above) the metric of the still present wired subnet route is lower than the wifi subnet route. I've had exactly this problem although a bit more random, because without the metric fix whether the traffic goes to the wifi depends on which interface address was added first.

So perhaps in addition to the metric fix, we need a setting that allows addresses (and routes) to be withdrawn when an interface is down. It could be implemented in an analogous way to DHCP by adding a "static client".

Any better ideas? I bet IPV6 has extra complications I don't know about (Address/PrefixRoute?).

**Comment by jonjonw** [comment]
For anyone else running into this, here is a hack I'm using until it's resolved: https://gist.github.com/jonjonw/f4f38e57681d11d9f611515c6701aa7c
It's not great but it's better than nothing if you need it.

**Comment by ssahani** [comment]
@jonjonw thanks for the example is not the below configuration does the same ?

```
[Match]
Name=veth-test

[Route]
Destination=192.168.0.0/24
Metric=2048

```

and

```
(route-subnet-928)⚡ % ip route                                                                                                                                         ~/tt/route-subnet-928
192.168.0.0/24 dev veth-test proto static metric 2048 
```

**Comment by pgnd** [comment]
@poettering 

> Hmm, we actually wanted to support a per-interface metric setting that would then be inherited by all the interface's routes. That way you could have multiple interfaces up at the same time, but traffic gets routed to the interface with the routes with the lowest metric.
> 
> @teg what happened to the plans to add a per-interface default metric setting that would then be inherited by all dhcp or static routes on the iface?
> 
> @cshapeshifter would that not suffice for you?

Did this^ issue get andwered/resolved elsewhere? Or still open here?

Looking to solve the laptop-with-wired-and-wlan-interfaces switching issue ...

**Comment by maddes-b** [comment]
I just tested with systemd 246 on Ubuntu server 20.10 and it is not implemented yet. There is no "RouteMetric=" option (or similar) for the "[Address]" section of [systemd.network][1].
If systemd would implement giving the kernel route a metric, then this would dramatically ease setups of machines with multiple NICs. Please note that I do not know _if_ - or since when - the Linux kernel allows this.

_Made up example for expected result:_
```
eth0.network:
...
[Address]
Address=10.1.2.3/8
**RouteMetric=100**
...

# ip route show
10.0.0.0/8 dev eth0 proto kernel scope link src 10.1.2.3 **metric 100**
```

_Workaround:_
Right now (246; assuming 247 too, see [changelog][2]) you have to work with route tables and explicit route policy rules to give different priorities to multiple nics on a single machine. Also there is a bug with the "AddPrefixRoute=" option of the "[Address]" section in systemd 246 failing to create default routes (will create a separate issue for this soon) which requires additional planning and rules to create the right nic handling.
I only have static addresse and gave each device its own route table with default route (Gateway=) and other routes (Destination=). Via the policy rules these are selected in the wanted priority order. I used priority 50 for the rules to select the correct table when a source address is specified, and if no source address specified I used priorities 100-10x for the first "available" device (=filled table) with the highest priority.
If you additionally use DHCP this may not work for you, but you may adopt that system.

```
eth0.network:
...
[Address]
Address=10.1.2.3/8

[Route]
Destination=10.0.0.0/8
PreferredSource=10.1.2.3
Table=100

[Route]
Gateway=10.99.99.99
PreferredSource=10.1.2.3
Table=100

[RoutingPolicyRule]
From=10.1.2.3/32
Table=100
Priority=50

[RoutingPolicyRule]
Table=100
Priority=100
...

eth1.network:
...
[Address]
Address=10.4.5.6/8

[Route]
Destination=10.0.0.0/8
PreferredSource=10.4.5.6
Table=101

[Route]
Gateway=10.99.99.99
PreferredSource=10.4.5.6
Table=101

[RoutingPolicyRule]
From=10.4.5.6/32
Table=101
Priority=50

[RoutingPolicyRule]
Table=101
Priority=101
```
[1]: https://www.freedesktop.org/software/systemd/man/systemd.network.html
[2]: https://github.com/systemd/systemd/blob/master/NEWS
