### ISSUE TITLE
sd_bus_message_unref() appears to use assert() instead of assert_return()

### ISSUE THREAD

**Issue by hal0** [systemd/systemd#9313]
Following the guidelines from https://github.com/systemd/systemd/pull/9309#discussion_r195683980, I noticed that `sd_bus_message_unref()` uses `assert()` instead of a return code.

https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/bus-message.c#L895

The same appears to be true for `_ref()`.

https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-bus/bus-message.c#L884

Is this intentional? It was causing random failures in a portion of code that weren't entirely deterministic nor helpful upon debugging (albeit truly errors in the application, _not_ in libsystemd).

**Comment by poettering** [comment]
It's actually intentional. If the reference counter is invalid, then we have a memory corruption, and in that case we should abort. I mean, if we are in this state then we are fucked anyway, and it's a bit better to abort early than to wait for the memory corruption to hit later in other ways.

So yes, use assert_return() when validating parameters and such coming in from the user, if they might indicate misuse or inproper validated data, but memory corruptions and such a much worse error and should still result in assert()

**Comment by keszybz** [comment]
Yep, I think that's reasonable. Presumably, this memory was already `free`d before. If we called `free` again, glibc would abort if it detected that. We should abort too.
