### ISSUE TITLE
Impact of Transaction Sizes and Numbers on boottime

### ISSUE THREAD

**Issue by basav1989** [systemd/systemd#9316]
**Is your feature request related to a problem? Please describe.**
When bringing up systemd based OS on raspberry pi, I traced the transaction sizes(number of jobs in a transaction). But cannot understand the relation between transaction sizes and boottime. 
 -> So, Is it correct to say that as size of transactions increases , boot time also increases linearly??
 -> Or transaction size has negligible impact on boot times??

**Describe the solution you'd like**
A clear description/documentation on transaction handling and the relation between fast/slower boottimes and transaction  sizes.

**Describe alternatives you've considered**
As I understand, there is no global dependency graph. Dependencies are modelled as forest of trees/transactions and am trying a brute force check by varying transaction sizes and boottimes.

**Comment by keszybz** [comment]
There is no straightforward relationship. Generally, bigger transactions are expected to take longer, because there is more "stuff" to do, but the total time really depends on how much time individual job take, and one long job can take more time than thousands of short ones. So looking at the number of jobs is not useful to optimize the boot time. You should look at the slow jobs and which jobs block other jobs from starting.

**Comment by basav1989** [comment]
Thanks for the clarification. Will profile for jobs accordingly.

**Comment by boucman** [comment]
this is not the place for a complete explanation but have a loog at man:systemd-analyze in particular the subcommands plot, critical-chain, time and blame
