### ISSUE TITLE
sysusers: somewhat predictable ids

### ISSUE THREAD

**Issue by gdzx** [systemd/systemd#9326]
## Problem:
When using privileged containers, it's useful to give access to some hardware capabilities like graphics rendering, sharing some files to serve via HTTP and things like that. These functionalities are owned by specific groups (namely `render`, `video` and `http`).

However, ids with `systemd-sysusers` are not fully predictable since adding dynamic users/groups from different packages in `sysusers.d` on two different machines could result in them sharing the same ids (hence the issue when these machines are containers of the same system).

### Configuration file to fix some ids
Existing configuration files allow to override system-provided settings. One could just specify the ids to fix and override the dynamic behaviour. Unfortunately, the following issues arise:

1. the overriden files contain more information than just ids and these would need to be tracked down from the source package into the overriding file (the most important being the location of the shell and the home directory, with `git-shell` for instance),
2. a single file shared with multiples containers could create uneeded users and groups for packages that are not installed on a particular machine.

Thus, `systemd-sysusers` could **accept an additional config file allowing to specify desired ids for each user/group names to use instead of a fully dynamic allocation**. That would allow to lazily create users and groups, without overriding system-provided settings and still being able to have predictable ids for the dynamic allocation. `systemd-sysusers` will also have to report conflicts between this config file and existing settings (like fixing an id that is not marked as dynamic).

### Hashing user/group names
Instead of allocating the ids in numerical order, we could first try to map them using a hash function and modulus of the digest in the target range. That would effectively map one user/group name to one id in a predictive way, without an additional configuration file, regardless of the creation order of these users/groups. In case of collision, one can resort to the first available id based on some numerical order (but that would make it non-predictable in these cases).

**Comment by yuwata** [comment]
> systemd-sysusers could accept an additional config file allowing to specify desired ids for each user/group names to use instead of a fully dynamic allocation.

Why do not you add configs with specific UID/GIDs to override the default configs? Does not it work?

> systemd-sysusers will also have to report conflicts between this config file and existing settings

I thought that `systemd-sysusers` actually warns about the duplicated settings.
https://github.com/systemd/systemd/blob/3fe910794b60de8ae99b9e93b81463ace26d0f12/src/sysusers/sysusers.c#L1668

**Comment by poettering** [comment]
All of systemd's configuration files, including the tmpfiles.d drop-ins can be overriden in /etc/ by matching file name. i.e. if you want to assign fixed UIDs to the users defined in /usr/lib/sysusers.d/foo.conf then just copy the file to /etc/sysusers.d/foo.conf and change the second column to your liking. If you do, then the original file will be overriden by the one you define, as long as the name foo.conf matches.

**Comment by gdouezangrard** [comment]
@yuwata 

> Why do not you add configs with specific UID/GIDs to override the default configs? Does not it work?

I specifically don't want to override the default configs for the following reasons:

1. I don't want to override users/groups that needs specific IDs (there is a couple that are fixed in Arch for instance, but that may not be the case with other distros),
2. I don't want `systemd-sysusers` to create uneeded users/groups (let's say I override the git config, I now always have a git user with `/usr/bin/git-shell` on machines that may not even have git installed),
3. I don't want to track each package `sysusers.conf` (home directories and shell can depend on packaging and may not be valid cross-distros, and I would prefer to not duplicate these settings).

@poettering 

> All of systemd's configuration files, including the tmpfiles.d drop-ins can be overriden in /etc/ by matching file name. i.e. if you want to assign fixed UIDs to the users defined in /usr/lib/sysusers.d/foo.conf then just copy the file to /etc/sysusers.d/foo.conf and change the second column to your liking. If you do, then the original file will be overriden by the one you define, as long as the name foo.conf matches.

I do even worse currently, I create `/etc/sysusers.d/0-base.conf` that contains everything I want to fix even before I actually install `systemd` in the rootfs, but with the previously outlined drawbacks.

The idea was to have a simple file (type, name, ID) that can fix IDs **only** in case of dynamic allocation (instead of overriding + adding the actual user/group). This solution allows to:

1. Not override IDs that are already fixed, only those who are dynamic and about to be allocated,
2. Not override any system-provided files,
3. Not create uneeded users/groups,
4. Not having to track subtle differences in packaging cross-distros.

**Comment by poettering** [comment]
> I don't want to override users/groups that needs specific IDs (there is a couple that are fixed in Arch for instance, but that may not be the case with other distros),

Then leave those lines unmodified?

>     I don't want systemd-sysusers to create uneeded users/groups (let's say I override the git config, I now always have a git user with /usr/bin/git-shell on machines that may not even have git installed),

Why is that so bad? I mean, you have to reserve the UIDs anyway. If sysusers won't acquire them then something else will sooner or later, for example your distros regular adduser. If you want fixed uid/gid assignments you need to allocate them in advance to make sure the space is blocked.

**Comment by poettering** [comment]
So currently sysusers.d is already a 2nd level configuration from which a 1st level file is derived (i.e. /etc/passwd). Adding a 3rd level of indirections here sounds like a really bad idea. Who is supposed to grok this still? Moreover, it doesn't actually fix the problem, does it, given that the UID ranges need to be blocked so that they cannot be allocated by something else (as pointed out above).

**Comment by gdouezangrard** [comment]
> Why is that so bad? I mean, you have to reserve the UIDs anyway.

I might end up in a situation where I reserve some group `foo`, that due to packaging reason doesn't have the same home directory between different distros, and it will always get overridden (because it will be created in advance).

Or, I reserve some group `bar` with a specific GID that is actually fixed in the system configuration and that will prevent the creation of the proper system user (let's say I want `render:39` in Arch, if I use the same config in Debian I will prevent the creation of the group `irc`).

The configuration file I propose only applies to dynamic allocation and doesn't override anything, so none of the above would be possible.

> If sysusers won't acquire them then something else will sooner or later, for example your distros regular adduser. If you want fixed uid/gid assignments you need to allocate them in advance to make sure the space is blocked.

Even running `useradd` before `systemd-sysusers` with a config reserving the same ID for two different users/groups will end up in the situation where `systemd-sysusers` cannot allocate the one I need.

> So currently sysusers.d is already a 2nd level configuration from which a 1st level file is derived (i.e. /etc/passwd). Adding a 3rd level of indirections here sounds like a really bad idea. Who is supposed to grok this still?

Most of the systemd users don't need to care about these levels of indirection. Only those who want more control over the dynamic allocation need to know about this additional configuration, which doesn't break anything else.

---

A concrete example is the `sudo` and `wheel` groups in the system config:

```
arch/usr/lib/sysusers.d/basic.conf
----------------------------------
g wheel   -     -            -
```
```
debian/usr/lib/sysusers.d/basic.conf
------------------------------------
g sudo       27    -
```

If want these groups to have the same GID, I currently have to manage two different configurations for each distro, otherwise, if I use the following on both, the fixed `sudo` group in Debian will not get created (`sudo`'s GID will be taken by `wheel` that would be created in advance).

```
debian/etc/sysusers.d/0-base.conf
----------------------------------
g wheel   27     -            -
```

---

> Moreover, it doesn't actually fix the problem, does it, given that the UID ranges need to be blocked so that they cannot be allocated by something else (as pointed out above).

Now indeed, I only wanted to avoid the random behavior if possible, without actually reserving any IDs, which implies that this additional config file only contains *hints* to the dynamic IDs allocator that might not actually be satisfied.

Unfortunately, you seem to be right, there might not be any satisfying solution that works reliably anyway: `mail` in Arch is `8:12` whereas it's `8:8` in Debian (where `man` is associated with `12`), and even then, a lot of packages in Debian still use manual `adduser` so...I guess I will have to copy-paste from `/usr/lib/sysusers.d` and fix when that breaks :D.

Thanks for your time.
