### ISSUE TITLE
Attach stdin/stdout to a running service

### ISSUE THREAD

**Issue by evg-kazartseff** [systemd/systemd#9492]
**Is your feature request related to a problem? Please describe.**
Hello, I'm a beginner developer from Eltex in Russia. I'm interested in the question, is there any possibility to implement stdin / stdout joining my console to the service in the process of work?

**Describe the solution you'd like**
To solve this problem, you can use the file descriptors. (fd :) and special mediator program for associating with the current terminal using the command (systemctl attach servicename)

**Comment by poettering** [comment]
You can get live (line-based) access to a service's stdout/stderr/syslog through "journalctl -fu $SERVICE"...

There's no concept for connecting to stdin of a service however, and also no byte-wise interactivity as that would generally require allocation of a pty, and buffering of screen contents somewhere, which sounds a bit like overkill, since that would turn us into a terminal multiplexer in a way, like `tmux` or `screen`
