### ISSUE TITLE
Arch Linux Freeze on Boot with Systemd 239.0-2

### ISSUE THREAD

**Issue by john01dav** [systemd/systemd#9529]
**systemd version the issue has been seen with**
> 239.0-2

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
**Unexpected behaviour you saw**
 > I recently updated via pacman to the new systemd version listed above. I expected it to automatically work, as all previous updates have. Instead, the system hangs on boot some time between running fsck on my / partition and loading gdm to allow for graphical

**Steps to reproduce the problem**
I am unsure of exactly what causes this problem, but I know for sure systemd is, at least partially, at fault (updating this and only this package produces the issue exactly on my system). I do not know what, if any, other packages are involved. It is possible that gdm is also involved, for I noticed an error from Glib running in gdm's process about a failed assertion as the last log before the system hang. I can not access this message when my system is fully loaded, and able to copy/paste the message into something like a web browser, so I can not provide the exact message. Journalctl does not seem to provide any way to access older messages, and I need to reboot in single-user mode (where I saw the message) to undo the systemd update. Based on this, the most likely steps to reproduce this are as follows:

1. Install Arch Linux (with the latest packages as of July 5th 2018 in the Arch Linux package archives
2. Install gdm
3. Set gdm to launch on the system's startup
4. Update systemd to the latest version (2.3.9.0-2, at the time of writing) in Arch's repositories, optionally updating the other packages to the latest version as well.
5. Reboot and observe as the computer is Temporarily Bricked™

To undo the issue and Unbrick™ the computer:

1. When booting, press "e" on the Arch Linux menu entry in grub, or do the equivalent in your bootloader.
2. Replace the word "quiet" with "S" on the line near the bottom beginning with the word "linux".
1. Use the Arch Linux package archives to downgrade all packages to their latest versions as of July 5th 2018.
4. Reboot to a no-longer-up-to-date but also Unbricked™ system.

**Comment by poettering** [comment]
This looks like a downstream issue. There's no indication systemd's own code is really causing this. Please contact your downstream distribution for help on this one. I am sure they'll help you tracking this down further. They will also escalate this back to us if there's really a problem with systemd itself.

Thank you very much for understanding...

**Comment by pthoem** [comment]
I've had the same problem for months now with ArchLinux 4.18.16 (was driving me mad), but finally I could solve it after many many tests and debugging. The problem comes somehow from the `systemd-fsck@dev-sdxy.service` (xy = a1, a2, ..., b1, b2, ...). So I did following:

1.) I **disabled checking my root file system at boot time** by adding '**fsck.mode=skip**' to the bootloader's kernel command line...

```
   # vi /boot/grub/grub.cfg
   ...
   menuentry "Linux, ..." {
     linux   /boot/vmlinuz-linux root=... fsck.mode=skip
```

2.) I disabled all boot-time fsck by setting the '**pass**' parameter (6th column) in **/etc/fstab** to **0**...

```
   # vi /etc/fstab
   ...
   /dev/sda1  /              ext4   rw,relatime,data=ordered  0 1
   /dev/sda2  none           swap   defaults                  0 0
   /dev/sda3  /data0         ext4   defaults                  0 0
   /dev/sdb1  /data1         ext4   defaults                  0 0
   /dev/sdc1  /data2         ext4   defaults                  0 0
```

3.) I **avoid starting X (startx) automatically**, but I boot into the text console only

4.) I updated **~/.bashrc** such, that the **main data disks are check after I logged in**...

```
   # vi /etc/sudoers (SHIFT + G, ESC + I)
   ...
   Cmnd_Alias CMDS1 = /usr/bin/mount,/usr/bin/umount,/usr/bin/fsck
   myusername ALL = (root) NOPASSWD: CMDS1

   # vi /home/myusername/.bashrc   (SHIFT + G, ESC + I)
   ...
   if [ "$DISPLAY" = "" ]
   then
     echo " "
     sudo umount /dev/sdb1
     sudo fsck -y /dev/sdb1
     sudo umount /dev/sdc1
     sudo fsck -y /dev/sdc1
     sudo mount -a
     echo " "
   fi
```

That's it!

So now, after I logged in to the text console, I first **watch all messages** to be OK, then I type '**startx**' to get into my desktop manager (XFCE4). From there I **log out** (not shut down), when finished with my work. Then I type '**shutdown now**' on the text console to shutdown the system.
