### ISSUE TITLE
nspawn, dont hang on "systemd-nspawn -D . --private-users=3598450688:65536"

### ISSUE THREAD

**Issue by alban** [systemd/systemd#956]
`systemd-nspawn --private-users` should not accept a host UID with the most significant bit set to 1 because devpts does not support that.

The first command does not work and the second works fine:

```
sudo mount -t devpts devpts /tmp/devptsdir -o newinstance,ptmxmode=0666,mode=620,uid=3598450688,gid=3598450693
sudo mount -t devpts devpts /tmp/devptsdir -o newinstance,ptmxmode=0666,mode=620,uid=1000,gid=1000
```

The [devpts function parse_mount_options()](http://lxr.free-electrons.com/source/fs/devpts/inode.c?v=4.0#L189) uses `match_int` (signed integer) and does not accept negative numbers.

Additionally, the error reporting is not great: the following command just freezes without any error message:

```
systemd-nspawn -D . --private-users=3598450688:65536
```

**Comment by poettering** [comment]
That really looks like a devpts bug to me, please file a bug against the kernel. We accept the full uid_t range, except for (uint16_t) -1 and (uint32_t) -1 (since (uid_t) -1 has special meaning for many calls such as setresuid() for example, and uid_t used to be uint16_t until it was changed to uint32_t). We are very careful when parsing this actually,

Hence, please file a bug in kernel bz, they really need to fix that on their side...

THat said, we should of course fail gracefully and not hang in the case you describe. Hence leaving bug open, to fix that.

**Comment by dongsupark** [comment]
A little surprising, but this looks like a real kernel bug. Apparently no one has paid attention to this corner case. Moreover, it's not the only place where uid/gid mount options are simply parsed as signed int type. Actually the ancient match_int() calls should be replaced with kstrto*(). But there are too many places to be corrected.

Anyway, I wrote a patch only for fixing devpts. If it works, I could send it to lkml too.
Commit: https://github.com/dongsupark/linux/commit/692839ff7158dbb96dd20ce8e36c13f85fa64fd7
Tree: https://github.com/dongsupark/linux/tree/devpts_uint32

**Comment by alban** [comment]
@dongsupark : Thanks for working on this patch! I tested your patch v2 and it solves the problem for me.
