### ISSUE TITLE
239 - Before/After Dependency between timers not respected

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#9577]
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > It is not clearly documented if this should work, but I have one service (A) with `OnCalendar=hourly` that runs for ~5 minutes and the other (B) `OnBootSec=5min` that completes in seconds. One of them has a Before/After dependency on the other, but I noticed they sometimes run simultaneously. They are both `Type=Oneshot`

**Unexpected behaviour you saw**
 > Service B has a `Before` dependency on service A, but I noticed systemd doesn't respect this, and starts the B while A is active. While ordering is debatable, I think they definitely shouldn't run simultaneously.
> journal when this happens:
```
11:00:19 host systemd[1]: Starting Service-A...
11:00:47 host systemd[1]: Starting Service-B...
11:00:47 host systemd[1]: service-b.service: Main process exited, code=exited, status=1/FAILURE
11:00:47 host systemd[1]: service-b.service: Failed with result 'exit-code'.
11:00:47 host systemd[1]: Failed to start Service B.
11:00:59 host systemd[1]: Started Service A.
```
> 
> I'll create testcases if needed

**Comment by sourcejedi** [comment]
The `Before=` dependency could only work as desired, if it is set on _service-b.service_, not _service-b.timer_. Did you set it on the service?

**Comment by SjonHortensius** [comment]
@sourcejedi yes it is set on the service, not the timer

**Comment by sourcejedi** [comment]
Oh, I understand now. My apologies.

`service-b.service` has `Before=service-a.service`. Currently, this means that when `service-b.service` is activating, `service-a.service` will wait for it.

When you start service B, systemd can't send a signal back in time to delay the activation of service A. (If nothing else, time-travel causes paradoxes).

But systemd would complain noisily if you told it to make B wait for A *and* A wait for B. You can't satisfy both ordering constraints if A and B are started as part of the same transaction. Ordering cycles normally suggest some mistake or conflict in the unit files. (AIUI it will break the cycle by ignoring one of the ordering constraints, effectively chosen at random).

To implement your desired behaviour I think you would need some rather new feature.  You want a "dependency" type that doesn't care about ordering, it just cares that A & B are not allowed to run at the same time.

The normal approach for this is to write A & B so that they use a file lock somewhere. From systemd's point of view, A and B will be running at the same time, but they can avoid internal conflicts. It will distort the systemd timings a bit, and hence any systemd timeouts that apply to the units. However, timeouts are already disabled by default for oneshot services, which is what are usually used with timers.

I don't know whether or not adding the feature to systemd is a good fit.

**Comment by sourcejedi** [comment]
EDIT: I would say this "shouldn't" work / is not really "debatable". I think the documentation includes enough information that it more-or-less specifies this. Whether it is clear enough is another question :).

You described this in terms of a bug.  If you want a new feature in systemd to support your use case, maybe clearest to write it as a separate RFE.
