### ISSUE TITLE
Allow ipv6 RA but without ip autoconf

### ISSUE THREAD

**Issue by Toniob** [systemd/systemd#9582]
Hi,

The configuration with my provider is quite strange. I have to activate ipv6 RA to obtain a default route. But I don't want to have the address via autoconf. For that, I use a dhcpv6 pd, with static ip configuration
after that.

It should be great to be able to keep RA active but without autoconf. Currently, in my .network
conffile, I've got this :
```
IPv6AcceptRA=True
```
and I've created a file /etc/sysctl.d/local-ipv6.conf :
```
  net.ipv6.conf.all.use_tempaddr = 0
  net.ipv6.conf.default.use_tempaddr = 0
  net.ipv6.conf.ens3.use_tempaddr = 0
  net.ipv6.conf.all.autoconf = 0
  net.ipv6.conf.default.autoconf = 0
  net.ipv6.conf.ens3.autoconf = 0
  net.ipv6.conf.all.accept_ra_pinfo = 0
  net.ipv6.conf.default.accept_ra_pinfo = 0
  net.ipv6.conf.ens3.accept_ra_pinfo = 0
```
but I still get an address automatically :
```
  inet6 xxx::xxx/64 scope global mngtmpaddr noprefixroute dynamic
```

Networkd should add an "IPv6Autoconf" configuration parameter to disable the configuration of ipv6 addresses via Router Advertisement. Maybe with 3 values : yes, no and kernel ?

**Comment by Fanfwe** [comment]
Hi,
I also support this RFE.
One of the main French dedicated server hosting company (Online) has a weird IPv6 deployment which would require this.
They require the servers to do a DHCPv6 request (with a specific DUID) to enable the routing of an IPv6 prefix to that server, but the default gateway still has to be provided through the RA.
This means that we have to configure the network with IPv6AcceptRA=true because it's the only way to get a default route (and it is on a link-local address, so we can't really set a static route).
But when doing so, the RA also advertises a prefix which makes the system take an IP which is not routed upstream.
The right IP (assigned by the hosting company) has to be manually assigned, and it works great, but since the server has two global IPs with the same prefix (/64) any outgoing connection uses the bad one from the RA (since it came up last).
Having a way to tell systemd to only use the default gateway from the RA, but not the address prefix would solve this issue.
The sysctl net.ipv6.conf.<interface>.accept_ra_pinfo seems to be there for that reason and it would be great to have it exposed as an option in systemd.

**Comment by yuwata** [comment]
If possible, please test the PR #11689.
