### ISSUE TITLE
v239 failure to establish watch on symbolic link of /etc/localtime 

### ISSUE THREAD

**Issue by gvlx** [systemd/systemd#9602]
**systemd version the issue has been seen with**
> v239

**Used distribution**
 > Archlinux ARM

**Expected behaviour you didn't see**
 > normal startup

**Unexpected behaviour you saw**
 > [   14.429708] systemd[1]: Detected architecture arm.
[   14.466434] systemd[1]: Set hostname to <remicourt>.
[   14.519163] systemd[1]: Failed to create timezone change event source: Too many levels of symbolic links
[   14.535323] systemd[1]: Failed to allocate manager object: Too many levels of symbolic links
[   14.556312] systemd[1]: Freezing execution.

**Steps to reproduce the problem**
- Install v239
- `timedatectl set-timezone UTC`
- restart

**Cause**
Commit https://github.com/systemd/systemd/blame/1e75824cb005f7fa0089792e45c2747c4d059601/src/core/manager.c#L424 does not follow symbolic links properly.

**Workaround**
- remove disk from original machine and mount it on another system
- `# mount /dev/sdXY /mnt`
- `# ls -l /mnt/etc/ | grep time`
> lrwxrwxrwx 1 root root     25 Jul  1 22:26 localtime -> ../usr/share/zoneinfo/UTC
- `# rm /mnt/etc/localtime`
- `# cp /mnt/usr/share/zoneinfo/UTC /mnt/etc/localtime`
- `# umount /mnt`
- remove disk from other system and mount it back on original machine

**Comment by poettering** [comment]
Hmm, I am a bit puzzled by this one. I don't see how we could ever get ELOOP (which is what "Too many levels of symbolic links" means) here, as we pass IN_DONT_FOLLOW to inotify_add_watch(), as you see in the the sources you linked. This means we watch the link itself instead of what it points too, which is exactly what we want here. We *expect* this to be a symlink, and 

If inotify_add_watch() returns ELOOP then this can only happen afaics if within the path /etc/localtime  there's a symlink cycle or so (maybe /etc itself?), or maybe that the kernel is too old (what is it?)

I mean, I run with /etc/localtime being a symlink myself too, it's what we really push people to do, it's what timedated actually sets things up as, hence I am really confused by this, and can't see a way how this could be triggered.

Is this reproducible for you? Is there anything interesting regarding setup of /etc or the file system in general?

(That said, even if this fails, we really shouldn't bail out on it. Will prep a patch for that shortly. But this will only fix the effect of the ELOOP issue, not the ELOOP issue itself, and if this is reproducible I'd really like to fix that too, but first need to understand that.)

**Comment by poettering** [comment]
(oh, and for me with /etc/localtime being exactly the symlink you suggest everything works fine and perfectly)

one more question: is /usr split into a separate file system for you, or something like that?

**Comment by poettering** [comment]
hmm, any chance you can strace this somehow?

**Comment by poettering** [comment]
#10392 addresses the freeze issue.

**Comment by zonidjan** [comment]
This happened to me after upgrading Debian to unstable (from Jessie or perhaps Stretch). No separate filesystems or anything. I'm happy to put the symlink back in place and strace if you can tell me how to strace it, given that it occurs at (and prevents) boot.

BTW, the only error printed in my case was "Failed to allocate manager object: Too many levels of symbolic links.". I'm not sure if that's because I wasn't passing some boot options or such.

**Comment by poettering** [comment]
> This happened to me after upgrading Debian to unstable (from Jessie or perhaps Stretch). No separate filesystems or anything. I'm happy to put the symlink back in place and strace if you can tell me how to strace it, given that it occurs at (and prevents) boot.

hmm, that depends. one simple way might be do replace /usr/sbin/init with a shell script that does something like this:

```sh
#!/bin/sh
exec strace -s 500 -o /tmp/init.strace -D /usr/sbin/init.real "$@"
```

Under the assumption you moved the real init binary to /usr/sbin/init.real first, and installed strace.

**Comment by poettering** [comment]
(and the `-D` switch to strace is what is relevant here, as it makes sure that strace gets a PID != 1 and the real init remains PID 1 — normally strace starts processes as its own children which wouldn't work for an init system which *must* be PID 1)

**Comment by poettering** [comment]
Let's drop this from the v240 milestone for now, as this is currently not actionable

**Comment by zonidjan** [comment]
FYI, I got a kernel panic trying to strace it this way, but I don't have time to investigate further.

**Comment by poettering** [comment]
Closing due to lack of response.

**Comment by gvlx** [comment]
v241.7-2 (archlinux armv7l with kernel 3.5.7-14) seems to work correctly.

**Comment by ValdikSS** [comment]
@poettering, I'm running Debian 12, systemd 252.17-1~deb12u1 on kernel 3.2 (I know about borderline requirements, I've backported some of the required changes).

It seems that the file is `open`'ed with `O_NOFOLLOW`, but `inotify_add_watch` does not have it.

```
statx(AT_FDCWD, "/etc/localtime", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW|AT_NO_AUTOMOUNT, STATX_BASIC_STATS, 0xbed29718) = -1 ENOSYS (Function not implemented)
fstatat64(AT_FDCWD, "/etc/localtime", {st_mode=S_IFLNK|0777, st_size=35, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 8
statx(8, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_BASIC_STATS, 0xbed29690) = -1 ENOSYS (Function not implemented)
fstatat64(8, "", {st_mode=S_IFLNK|0777, st_size=35, ...}, AT_EMPTY_PATH) = 0
inotify_init1(IN_NONBLOCK|IN_CLOEXEC)   = 9
epoll_ctl(4, EPOLL_CTL_ADD, 9, {events=EPOLLIN, data={u32=3069354744, u64=3069354744}}) = 0
inotify_add_watch(9, "/proc/self/fd/8", IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVE_SELF) = -1 ELOOP (Too many levels of symbolic links)
close(8)                                = 0
```

**Comment by yuwata** [comment]
It seems that the kernel is too old. Please try with a newer kernel.
