### ISSUE TITLE
idleaction logic doesn't work for ssh sessions, and it probably should, which would mean waching utmp to acquire tty info for ssh session which is not supplied through pam

### ISSUE THREAD

**Issue by andersthomson** [systemd/systemd#9622]
I'm not sure if it ever worked on my install, bu reading the net it appears it should. 

I've IdleAction configured to suspend after 120s. An ssh to the system keeps it up as expected. However, if I'm only on logged into the console (text, no X11 graphics), it suspends after 120 sec. All reports on the net suggests to tweak LidSwitch settings, but This is not a Laptop. It's an old desktop minitower.

What's the best way to figure out why systemd does not count my console as session? Checking the journal, I get a "Started Session 1 of user root" for the console, just as I get for ssh.

This is on v236, gentoo.

**Comment by andersthomson** [comment]
Spot on. If "work there" equals staring at the screen. If I actively hit the keyboard every so often, it won't suspend. Somehow, ssh inhibits the entire thing (no input required), whereas the console requires input to not suspend.

loginctl show-session (on the console)
EnableWallMessages=no
NAutoVTs=6
KillUserProcesses=no
RebootToFirmwareSetup=no
IdleHint=no
IdleSinceHint=1531945265609859
IdleSinceHintMonotonic=5168071114
InhibitDelayMaxUSec=5s
HandlePowerKey=poweroff
HandleSuspendKey=suspend
HandleHibernateKey=hibernate
HandleLidSwitch=suspend
HandleLidSwitchDocked=ignore
HoldoffTimeoutUSec=30s
IdleAction=suspend
IdleActionUSec=2min
PreparingForShutdown=no
PreparingForSleep=no
Docked=yes
RemoveIPC=yes
RuntimeDirectorySize=196444160
InhibitorsMax=8192
NCurrentInhibitors=0
SessionsMax=8192
NCurrentSessions=1
UserTasksMax=10813

I do notice that loginctl show-session on ssh shows:
EnableWallMessages=no
NAutoVTs=6
KillUserProcesses=no
RebootToFirmwareSetup=no
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
InhibitDelayMaxUSec=5s
HandlePowerKey=poweroff
HandleSuspendKey=suspend
HandleHibernateKey=hibernate
HandleLidSwitch=suspend
HandleLidSwitchDocked=ignore
HoldoffTimeoutUSec=30s
IdleAction=suspend
IdleActionUSec=2min
PreparingForShutdown=no
PreparingForSleep=no
Docked=yes
RemoveIPC=yes
RuntimeDirectorySize=196444160
InhibitorsMax=8192
NCurrentInhibitors=0
SessionsMax=8192
NCurrentSessions=2
UserTasksMax=10813

...and the IdleSinceHint* fields are now zero...

**Comment by poettering** [comment]
Well, but then everything works as intended: logind detects whether your console session is idle by watching the mtime of the tty device, and that gets updated whenever you press some keys. If you just let the tty hang around idle however the mtime will stay unmodified and logind will eventually act on the IdleAction. Hence, afaics everything is perfectly in order.

It appears to me you want something very different here than the idle logic provides you with. i.e. you are looking for automatic suspend if there are no sessions around, regardless if those sessions are idle or not, right?

**Comment by andersthomson** [comment]
Yes. It seems it works according to spec. However, the end user experience between ssh and console differs which is, imho, not optimal. Is ssh doing something specific to inhibit IdleAction? Is there a way to introspect what ssh does? Any way to teach the console login side to behave similar to ssh?

Afaict, ssh does start a Session, so something _is_ inhibiting the idleAction when ssh's sessions are idle.

**Comment by poettering** [comment]
So, the key of the problem here is that when ssh registers its PAM session it sets the PAM_TTY attribute (which is supposed to contain the TTY of the session) to "ssh" rather than the actualy tty used (i.e. something resembling "/dev/pts/1" or so). It does that because it registers the PAM session much earlier than allocating the pty, hence it doesn't know yet which pts it's going to use.

Now, because PAM doesn't get the right tty ssh uses, logind won't either. This means ssh sessions tracked by logind will not have a tty property set, but loging needs the pty to do idle detection, as we do that by watching the mtime of the tty...

This is messy to fix. We could probably watch the utmp file with inotify to acquire that information. After all ssh will register the pty in utmp as it allocates it (i.e. pam registration is done early, and utmp much later). But this would be asynchronous and hence a bit ugly. But i guess it would be good enough to make the idle logic work...

Will make this issue an RFE for this now. Also see #9697 that adds a couple of code comments explaining what is going on. That PR doesn't change anything to make work what you are looking for, but it makes things more discoverable for hackers at least.

**Comment by poettering** [comment]
Fix waiting in #9824
