### ISSUE TITLE
man: replace wording of "Ports" in "BindCarrier=" documentation into "Interfaces"

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#964]
systemd.network(5)
BindCarrier=
           A port or a list of ports. When set, controls the behavior of the current interface. When all ports in the list are in an operational down state, the current interface is brought down. When at least one port has carrier, the current interface is brought up.

---

Presumably, the term "port" is used in the same sense of a "port" in a Transport Layer Protocol such as TCP or UDP, and refers to a "port number" as listed in /etc/services.  So then, what is the meaning of the phrase "When at least one port has carrier"?  I have never heard of Transport Layer Protocol "port" having a "carrier".

Was this meant to say something like "When at least one port is in an operational up state..."?
Or was this meant to describe some kind of dependency upon a literal network interface "carrier"?
Or what is this trying to say???

**Comment by poettering** [comment]
"Port" in this context refers to "physical (ethernet) ports", i.e. a network link or interfae. It does not refer to TCP/IP ports or suchlike.

The original patch adding this came from folks building routers, and they of course focus on the lower levels of the stack where a port refers to the physical network connector rather than an IP port...

But yeah, we should probably change this to always say "interface" instead of "port", and then explain that this focusses on the link layer of the interface, rather than the transport layer.

**Comment by keszybz** [comment]
Fixed by 2ae7505f011441d4209216e99398e677d7dbbcab.
