### ISSUE TITLE
Option to use LinkLocalAddressing only when DHCP fails

### ISSUE THREAD

**Issue by tdphette** [systemd/systemd#9648]
I have a use case in which I desire only one address assigned to the network interface, but I want to use LinkLocalAddressing as a fallback when DHCP resolution fails. Currently systemd-networkd can have both DHCP and LinkLocalAddressing on, but that means you get a 169.254.*.* address even when DHCP succeeds (two valid addresses are active). We previously used avahi-autoipd to do this, but it only works with dhclient, and we are already migrating to networkd. Rather than add networkd support to avahi, I think adding a LinkLocalAddressing 'fallback' option to networkd makes more sense.

My questions for my fellow developers are:

1) Am I missing some obvious solution that does not require writing new code?
2) Would the systemd community be open to this feature if I contributed it?
3) What should the syntax in the config file look like? I was thinking something like this:

LinkLocalAddressing=fallback

Or if you wanted it only for a specific protocol, use 'ipv4fallback' or ipv6fallback'. Another possibility would be to include an additional flag like 'LinkLocalAddressingFallback=yes' (or ipv4, ipv6). I'm open to suggestions on syntax.

**Comment by heinemml** [comment]
Just found this because I have pretty much the same issue. I was actually a bit surprised, that getting a IPv4LL fallback was not the default case (for example dhcpcd does this by default).

I'm not to firm in the Standards, but is there a current "best practice"?. Is it preferable to always have a Link-Local IPv4 address configured? I'm working on a firmware for an embedded device and want to be an "a good as possible" citizen in a clients network.

**Comment by tdphette** [comment]
I've got a pull request for this almost ready to go. I just need to clean it up a bit and update the man pages with the new config options. They are as follows:

Within the [Network] section I've added a LinkLocalFallback option that takes the same parameters as LinkLocalAddressing (yes,no,ipv4,ipv6). This will allow IPv4 and IPv6 to be configured independently. Selecting LinkLocalFallback assumes LinkLocalAddressing is turned on for that protocol family, so there is no need to select both. Thus if you do LinkLocalFallback=ipv4, there is no need to do LinkLocalAddressing=ipv4... that is assumed. If you do both, it is fine... but the fallback feature will take precedence. Note that I've only implemented ipv4 so far. It will let you set ipv6 in the config, but I don't have the plumbing in place to support it yet, so it will just be ignored.

In the [DHCP] section I've added a FallbackTimeout option that allows you to set how many seconds DHCP should try before failing and falling back to some other addressing mechanism. I gave it a generic name to support other addressing schemes like static or future things yet to be invented. Only Link Local Addressing is currently supported. If no fallback mechanism is active, the timeout will be ignored. The default value is 15 seconds. If seconds are not granular enough, I could make this milliseconds... I'm open to persuasion on that.

**Comment by yuwata** [comment]
@tdphette I would like to see that. Could you submit it as a PR?

**Comment by weinholt** [comment]
I'm using mDNS and LLMNR and have a network interface that needs to work both when directly connected to another machine and when hooked up to a full network. The first case is handled by enabling LinkLocalAddressing and the second by enabling DHCP. The client will also enable link-local addresses and be able to communicate with my interface when directly connected. But if there is a DHCP server on the network then the client will remove its link-local addresses. Unfortunately, systemd still advertises the link-local address so that when the client resolves my hostname it will get both the link-local address and the DHCP-provided address. In many cases the client tries to connect to the link-local address and fails because it only has the DHCP-provided address configured. The client in this case is any arbitrary Windows or macOS machine and I suspect Avahi does the same.

Having the fallback feature described in this issue would let me configure systemd to work like Windows and macOS. An alternative would be to stop advertising the unreachable link-local address via mDNS/LLMNR if another address is configured, but that seems more error prone.
