### ISSUE TITLE
file name /usr/lib/systemd/system/-.slice - seriously???

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#965]
cd /usr/lib/systemd/system/

$ ls *slice
/bin/ls: invalid option -- '.'
Try '/bin/ls --help' for more information.

$ grep device *
grep: invalid option -- '.'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

---

Obviously, "ls -- *slice" and "grep device -- *".  The problem is caused by the existence of the file "-.slice", which is included in the expansion of "*", when using bash, for instance.  Thus the apparent command line switch "-.", which is an invalid option for many many commands.

But still - seriously???  Why did you choose a distinctly problematic file name?  Was that really necessary?  Or you just like to "mess" with people?

How about choosing a new and less problematic file name for the "Root Slice".  Perhaps it could be named something like "root.slice".

**Comment by nathwill** [comment]
just gonna leave [this](http://www.defensecode.com/public/DefenseCode_Unix_WildCards_Gone_Wild.txt) here. small consolation (i agree this is weird, and assume it's an artifact of how the code translates the hyphenated filename into a system path), but it's not a problem unique to systemd.

fwiw, the way to handle this kind of problem is to tell the program you're done passing options:

``` bash
[root@wyrd ~]# cd /usr/lib/systemd/system/
[root@wyrd system]# ls -al -- *.slice
-rw-r--r--. 1 root root 405 Aug  3 23:23 machine.slice
-rw-r--r--. 1 root root 403 Aug  3 23:23 -.slice
-rw-r--r--. 1 root root 433 Aug  3 23:23 system.slice
-rw-r--r--. 1 root root 392 Aug  3 23:23 user.slice
```

edit: which i see now you already mentioned :P

**Comment by thx1111** [comment]
> just gonna leave this here.

Ha!  Yeah - that's good.

Yes - systemd.unit(5) says: 'Basically, given a path, "/" is replaced by "-"...'  So, "root.slice" is "/.slice" and becomes "-.slice".  But it is still "juvenile mischief" and not "professional practice" for a software engineer.  It's funny, but not something anyone would actually _do_, for real.

**Comment by poettering** [comment]
Well, sure, the conflict is suboptimal, but as a UNIX admin one should be very careful with blanket statements involving just "*", anyway, in case one invokes this on a foreign, potentially rogue directory. (i.e. consider somebody sending you a tarball containing a file "-rf" or so, which could have bad unexpected consequences if you try to delete the contents of it via "rm *").

One option to avoid problems like this is to always specify "./_" rather than "_", or to specify "--" before the "*"... This is works like this for all UNIX commands in general.

Anyway, I see this is annoying, but it's a general problem with the way UNIX works, and in this case the effect is simply annoying but should not be destructive. We cannot really change this to "root.slice", since that actually translates to a path like "/root", rather than "/", if you so will. More importantly this is API now, and we cannot change this anymore really.

Sorry!

**Comment by VasiliPupkin256** [comment]
We had a general problem in UNIX so we created another one and wontfix it

**Comment by kirbyfan64** [comment]
This issue has literally been closed for two and a half years. It's was already past the point where it could be debated and is even more now.

**Comment by VasiliPupkin256** [comment]
@kirbyfan64 it is always time to discuss bad decisions. First, you learn on errors. Second, authors of bad architectural decisions should be limited from making architectural decisions. One shouldn't comfort himself that bad decision can be dealt with with some effort and there are other bad decisions in the world, so it is fine.

**Comment by stevegt** [comment]
@poettering In your 2015 comment before you closed this bug, you talk about how unusual filenames create risk.  But systemd created unusual filenames, increasing that same risk.  Unusual filenames on any operating system always have unintended effects far beyond the comprehension of their creator, and a basic tenet of UNIX-like systems is...don't create unusual filenames.  This filename pattern is a design mistake in systemd.  In closing this bug you refused to consider improving the situation; I don't buy the argument that it's too late to change -- you had the temerity to replace the entire SysV Init system yourself.  I think you can afford to consider doing better.
