### ISSUE TITLE
systemd-networkd: Not connected to system bus, not setting hostname.

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9699]
**systemd version the issue has been seen with**

239-7 in Debian unstable

**Used distribution**

Debian unstable

**Expected behaviour you didn't see**

I do not see `systemd-networkd[340]: Not connected to system bus, not setting hostname.`

**Unexpected behaviour you saw**

`journalctl -lu systemd-networkd.service` gives

```
Jul 23 12:02:57 debian-unstable systemd-networkd[340]: Not connected to system bus, not setting hostname.
```
Adding
```
After=dbus.service
Requires=dbus.service
```
to `systemd-networkd.service` solved the problem.

**Steps to reproduce the problem**
Just boot the Linux.

**Comment by mbiebl** [comment]
This is intentional afaics, so networkd can be started during early boot. See also d7afd945b5aad5b262a3de97614f486d63d94612

**Comment by ryutaroh-matsumoto** [comment]
@mbiebl Thank you very much again. Then it seems to me that logging `Not connected to system bus, not setting hostname.` is more suitable at the `debug` log level. So I leave this issue open but closure of this issue is also OK.

**Comment by yuwata** [comment]
It is not a bug. After networkd connects to system bus, hostname is set.
https://github.com/systemd/systemd/blob/915fa2854916740c57704b2cb897407d401a9a3d/src/network/networkd-manager.c#L106-L119
I think making log level lower and slightly updating log message are sufficient for this issue.

**Comment by dachshund-digital** [comment]
This issue is A BUG, a design bug not a code logic but if you will... it needs to be fixed.  The fact that the hostname is NOT set, is NOT correct behavior.  The normal function should be that the hostname is set.  This BREAK DHCP hostname option, thus this is also a security issue, in that hostnames are NOT properly top-down in controlled manner set from authorized entity, in the case I am noting, DHCP configuration, is not also DNS static configuration.

**Comment by boucman** [comment]
@dachshund-digital I'm not sure I understand... this bug is about
1) networkd starts early
2) networkd complains and does not set the hostname
3) dbus starts
4) networkd retries and does set the hostname

In other word, the bug is about a spurious error message, not about the hostname not being set... did you manage to trigger a different bug ? if yes you need to open another ticket in order to keep the correct bugflow process

thank you

**Comment by dachshund-digital** [comment]
The sequence you documented, does not work as noted.  Using Debian 9 stretch, with systemd 232. The systemd-networkd service starts, DHCP sequence provides IP address, as well as other information, including the host-name option.  However, the transient host name is never set.  The expected behavior is that the host name should be set, per your defined sequence.  This issue should be reopened?  Rather than a new issue, because it is the same issue, regression or not?
