### ISSUE TITLE
systemd-journald strips whitespace from messages forwarded to syslog socket

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#98]
We (as in RHEL and Fedora) have received complaints that $subject. To prevent having rather moot discussion in Red Hat bugzilla I'd like to gather upstream feedback first. @martinpitt  any opinions in Ubuntu/Debian camp on this one?

**Comment by poettering** [comment]
@msekletar what's the rhbz id?

What kind of whitespace is stripped, and why is that a problem?

This is about ForwardSyslog=yes, did I get this right?

**Comment by msekletar** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1227396

No it is not about forwarding to syslog rather about handling messages from /dev/log

**Comment by msekletar** [comment]
We strip whitespace in `src/journal/journald-server.c:1206` before we call `server_process_syslog_message`.

**Comment by poettering** [comment]
well, the BSD syslog protocol is very vaguely defined. Given that I am pretty sure we should suppress trailing and leading whitespace, to make the messages somewhat uniform.

Where precisely is this an issue?

**Comment by msekletar** [comment]
I think that motivation was formatting in /var/log/messages. On RHEL/Fedora rsyslog defaults to imjournal plugin thus it will read log data from journal with whitespace characters stripped. Thus /var/log/messages is not formatted the same way on older (e.g. RHEL{5,6}) and newer systems, which might be confusing for sysadmin, I guess...

**Comment by poettering** [comment]
I am pretty sure that we should continue to strip whitespace. Trailing whitespace is a menace anyway, and leading whitespace is particularly annoying since we need to parse the timestamp as first parameter out of log lines.

Note that the journal does not store unmodified syslog lines anyway, it parses them out, and if you want to reconstruct them you need to do so manually. Among other things this will correct timezone data for you.

We really have no intention to pass on the byte-exact syslog messages, we will give you enough data to regenerate something that looks like it, but that's it. 

Sorry, but I am very much against against pretending we'd allow byte-exact regeneration. if you want this then use the forwarding socket, but don't look at the journal at all.

**Comment by theinric** [comment]
> Given that I am pretty sure we should suppress trailing and leading whitespace, to make the messages somewhat uniform.

Thanks for the reply.
Is this documented anywhere?

**Comment by poettering** [comment]
Nope. In general, BSD syslog and thge behaviour around it is very much underdocumented, both when it comes to systemd's support for it, as well as generally outside of it.

**Comment by davidelang** [comment]
The problem with stripping whitespace from messages is that since there is no formally "correct" format, the existing log parsers in all sorts of tools have been written to handle exactly what the applications output. If you strip the whitespace from them, the parsers aren't going to work.

If this was only a few messages with local admin generated parsers, this could be fixed. But you are talking about a LOT of messages that are going to change, and lots of parsers maintained by third parties (and a lot of expensive log analysis tools) that are going to be broken. Worse, the same software will now 'generate' different log messages depending on if the messages go through journald or not.

**Comment by poettering** [comment]
@davidelang well, we only strip leading and trailing whitespace, nothing else.

And again, if you want the byte-exact version, then use the syslog forwarding, don't try to read things from the journal. The journal is simply not a transport for unmodified syslog messages, and if you want to use it like that you are simply using it wrong.

**Comment by davidelang** [comment]
Ok, then we need to get the distros (at least any that are aiming at the business market where logs are used) to disable the journal. Thanks for the clear statement.

**Comment by poettering** [comment]
@davidelang well, if you think that byte-exact syslog msg forwarding is what defines a business, then go ahead!

But again, you can also use ForwardToSyslog=yes, and you get the byte exact stuff delivered to a socket, exactly as you did without journald in the mix.

Also, you cannot actually turn off the journal in systemd. It's not an optional component, unlike most others.

**Comment by theinric** [comment]
@mezcalero

> Trailing whitespace is a menace anyway, and leading whitespace is
> particularly annoying since we need to parse the timestamp as first
> parameter out of log lines.

I think you misunderstood the issue. The whitespace is not at the beginning of the syslog message, but at the beginning of the CONTENT part of the syslog message. I'd argue most senders aren't really interested in the syslog messages, but only in the actual text the messages are carrying.

> Note that the journal does not store unmodified syslog lines anyway,
> it parses them out, and if you want to reconstruct them you need to
> do so manually.  <...>

Can't be done if journald throws parts of it away.

> We really have no intention to pass on the byte-exact syslog
> messages, <...>

As stated above, the syslog message is a red herring. The relevant part is the user supplied content. If you use logger(1), you usually don't care about the metadata it adds around your message.

**Comment by theinric** [comment]
@mezcalero

> But again, you can also use ForwardToSyslog=yes, and you get the byte
> exact stuff delivered to a socket, exactly as you did without
> journald in the mix.

Aren't we trying to teach people to use, primarily, journald?
How can they easily migrate if we are deliberately breaking backwards compatibility?

**Comment by theinric** [comment]
> Sorry, but I am very much against against pretending we'd allow 
> byte-exact regeneration.

Actually you are[0]:

"The output you will get looks like a pixel-perfect copy of the 
traditional /var/log/messages format, but actually has a couple of 
improvements over it"

By not documenting this behavior, you are deliberately misleading users.

I think this issue should be reopened and the behavior described here should be reverted.
A less than perfect solution would be to introduce an option to change the behavior back.
At the very least, the behavior should be documented somewhere.

[0] http://0pointer.de/blog/projects/journalctl.html

**Comment by theinric** [comment]
I've tried couple paths of delivering messages to journald to see whether they trim whitespace:

logger: YES
systemd-cat: YES
journal.send() from the Python API: NO
sd_journal_sendv(): NO

@mezcalero This looks a bit inconsistent. Do you think it's really a good idea not to document this behavior?

**Comment by poettering** [comment]
I'd be willing to add a patch that maintains the original whitespace indentation at the beginning (but not the end) of the actual log msg body. I am very sure though we should drop whitespace at the beginning of the full msg and at the end of it.

@theinric "looks like" doesn't mean "is". And we tend to avoid documenting behaviour we don't want to turn into API. Documentation means commiting to interfaces. I am not sure we should do that here because we are not the defining body of this interface, and it's generally so badly standardized that I am sure I don't want to become the one defining it.

**Comment by davidelang** [comment]
Modifying the message at all is going to break some parsers, but modifying only the end and not the beginning is going to break fewer parsers.

I don't disagree that messages that have such whitespace in them are badly formatted and this sort of thing should be avoided, but in the real world programmers do a lot of things that I think are bad practice. I have to live with them.

Altering the message is going to break things. If you think it's really a great idea, at least have (and document) an option to not alter the behavior so that people can avoid the breakage.

**Comment by xnox** [comment]
and parsers break a lot upon locale changes (some locales use different symbol for decimal separation etc) and many other things. Thus if you are parsing logs, and want it uniform, instead of fighting around precise number of whitespace and/or regexp to catch them all, one should convert to fully structured logging as provided by journald APIs.

**Comment by davidelang** [comment]
@xnox, this is what I mean about the difference between how I wish programmers did things and how they actually do things.

I really wish that programmers wrote nice, structured logs, but I can't afford to ignore all software from programmers who don't.

And until the logging calls become something other than journald specific, I'm going to continue to recommend that people log using the traditional API, but with the log message being structured JSON.

**Comment by poettering** [comment]
> Altering the message is going to break things. If you think it's really a great idea, at least have (and document) an option to not alter the behavior so that people can avoid the breakage.

As mentioned about a gazillion times right now: use ForwardToSyslog=yes if you want the byte-exact data.

The journal will not carry the byte-exact original msg, that's simply not going to happen, and you can stop asking for that now.

But again, I'd be willing to add a patch that keeps the whitespace after the syslog "tag" and before the actual log text in place, so that any indenting done by programs survives. But other than that: we are not a transport for BSD syslog messages. We just import them into our own format, and that _is_ lossy, and we want it to be lossy. And you won't change my mind on that.

**Comment by theinric** [comment]
@poettering

> well, the BSD syslog protocol is very vaguely defined. Given that I
> am pretty sure we should suppress trailing and leading whitespace, to
> make the messages somewhat uniform.

Why does journald care about the contents of the messages?
If it's because journalctl and systemctl-status need to print them, that can be handled on the output side, not when storing the data.

So far the only argument given was

> Trailing whitespace is a menace anyway

Could you elaborate on why stripping them is absolutely necessary?

> Documentation means commiting to interfaces. I am not sure we should
> do that here because we are not the defining body of this interface,
> and it's generally so badly standardized that I am sure I don't want
> to become the one defining it.

You'll become, de facto, the one defining it by just implementing it, whether you document it or not.

**Comment by filbranden** [comment]
Fixed in #156.

**Comment by jan-matejka** [comment]
I'd like to have the option to make journalctl show output with the original leading whitespace. The case where the leading whitespace is stripped is annoying to read when pretty formatted tracebacks are logged.
