### ISSUE TITLE
Conditions are ignored for mount units

### ISSUE THREAD

**Issue by omgold** [systemd/systemd#9875]
**systemd version the issue has been seen with**

219, 239

**Used distribution**

Centos7, Arch

**Expected behaviour you didn't see**

no attempt is made to start the mount unit, in case a condition fails

**Unexpected behaviour you saw**

systemd tries to start mount unit as if there was no condition specified

**Steps to reproduce the problem**

- save the following mount unit as /etc/systemd/system/foobar.mount
- systemctl start foobar.mount

```
[Unit]
Description=Foobar mount
ConditionPathExists=/foofoo

[Mount]
What=/dev/foobar
Where=/foobar
```

**Comment by arvidjaar** [comment]
Conditions prevent execution of start commands (or equivalent), they do not prevent normal logic when start request is received. I.e. unit activation is still queued normally together with any dependencies. This is what I see here - systemd times out waiting for `/dev/foobar` and activation request for `foobar.mount` fails due to missing dependency. Systemd does not attempt to start (i.e. dequeue for execution) `foobar.mount` at all, so it never even checks conditions.

If you see something different, please provide logs at debug level.

**Comment by omgold** [comment]
Ah, I see. I guess it was a misunderstanding on my side, then.

I found that it works, when the condition is also added to the device unit via an overlay.

**Comment by poettering** [comment]
Yeah, as @arvidjaar explained, this all works the way it does. conditions don't affect the jobs pulled in or waited for, they just skip the execution of the job's own operation, that's all. Closing this hence.
