### ISSUE TITLE
Build will fail with future versions of Meson

### ISSUE THREAD

**Issue by jeandet** [systemd/systemd#9883]
HI, 

We have a nightly build of some projects with Meson, trying to build master branch of each project with master branch of Meson. 
Here is the issue(log as guest):
https://hephaistos.lpp.polytechnique.fr/teamcity/viewLog.html?buildId=32167&buildTypeId=mesonbuild_SystemdNightly&tab=buildLog&_focus=1101#_state=1091

This has been introduced by this commit https://github.com/mesonbuild/meson/commit/d83f77109a7ac22da53acfad8f7ff078d929cd9d

I didn't go deeper in the investigations.
Regards.

**Comment by jpakkane** [comment]
On Sun, Aug 19, 2018 at 8:21 PM, Zbigniew Jędrzejewski-Szmek <
notifications@github.com> wrote:

> I prepped a PR for this. Nevertheless, I think grabbing names like this
> from the common namespace is not good. Meson uses the b_ prefix for some
> stuff and that is good. I think it should declare some prefix for itself (
> m_ ?), and only add stuff under that.
>

Our goal is to add these kinds of arguments very rarely (this is the first
one in ages that I can remember). Those options will also be of "global,
generally useful" type which really should be shared across all projects
(regardless of the language they are using). A m_ prefix would not really
work because then every top level option would need to have it too, leading
to variable names such as m_prefix, m_datadir and so on.
