### ISSUE TITLE
Remove offensive words from code

### ISSUE THREAD

**Issue by nontrinaryalternativeblackmale** [systemd/systemd#9894]
There is 29 "slave" and 64 "master" words in a code. Do you support slavery or something like this? CoC (freedesktop.org) says that's unacceptable behavior. Some projects removed offensive terms, so i think it will be great if you will follow that examples:

https://github.com/django/django/pull/2692

https://github.com/antirez/redis/issues/3185

**Comment by mbiebl** [comment]
It's all about context and in context of computer science master/slave has a well defined meaning which has nothing to do with slavery.

**Comment by yuwata** [comment]
What an offensive issue :-( Do you really think that changing such words makes the world better?

**Comment by poettering** [comment]
Hmm, so to clarify this: our use of the "slave" word is exclusively and without exception when we call kernel APIs named this way, e.g. mount()'s MS_SLAVE flag, the POSIX pty' subsystem's "slave" tty concept, the bridge or bonding driver's "enslaving" logic, the block subsystem's "slave" devices. We have not introduced any concepts of our own naming in systemd code using the "master" or "slave" terminology.

Or in other words, if this is important to you, please make the kernel folks rename their APIs, otherwise there's nothing much we can do, as we are just the consumers of those APIs, and if the kernel names those APIs that way we have to call them under those names. If we'd replace these words with something else then our tree would simply not build anymore, as that's not how these concepts are called in the .h API definitions.
