### ISSUE TITLE
getty login prompt sometimes does not appear on VCs when brltty is used

### ISSUE THREAD

**Issue by webczat** [systemd/systemd#994]
Hello.

I have a laptop, packard bell easynote TE69BM, running newest archlinux, kernel 4.1, systemd-224 with no changes to /etc/systemd/*.conf files.
The problem is that often when I press ctrl+alt+fx or alt+arrows to switch to a different terminal 1 through 6 that was currently unused, getty does not appear on this terminal (journal does not show any messages meaning that getty would start).
It happens for me very often, but I do not know anyone else who does have this problem. Sometimes when I switch terminals getty appears, sometimes it does not. When it does not appear once, it never will, probably unless rebooted. When it appears, it works. I can also systemctl start getty@ttyx to force it, it works too in this case.
I suppose that could be something like a hard to reproduce race condition related to logind, or problem in kernel related to notifying that the tty is active? I am not sure about this.
I think about race conditions because of my cpu, intel celeron dualcore 2.13 ghz. it's default cpu frequency scaling mode is set in such a way that the minimum frequency is really low, like 533 mhz, and it runs using such a low freq until it needs more power.

**Comment by poettering** [comment]
Is something keeping the VTs open at that time? Do you have any software like "gpm" or screenreaders running?

What does "fuser -v /dev/tty\* /dev/vcs*" say when this happens, when you run it as root?

**Comment by webczat** [comment]
Okay.

I want to describe what I did now:
I turned on my computer, logged in to gui. gdm takes tty1, gnome x 
session takes tty2.
I have pressed ctrl+alt+f3 through f6, and then returned to tty2.
I have checked journald. It seems tat tty3 and tty6 started, tty4 and 
tty5 did not start (I mean their respective agettys).
Then, as requested I executed:
fuser -v /dev/tty\* /dev/vcs\* from gnome-terminal.
Here is the result:

UŻYTKOWNIK  PID DOSTĘP POLECENIE
/dev/tty0:           root        225 F.... brltty
/dev/tty1:           root        375 F.... systemd-logind
                      gdm         449 F.... gdm-wayland-ses
/dev/tty2:           root        375 F.... systemd-logind
                      webczat     673 F.... gdm-x-session
                      webczat     675 F.... Xorg
                      root        677 F.... xf86-video-inte
/dev/tty3:           root       1178 F.... agetty
/dev/tty6:           root        375 F.... systemd-logind
                      root       1184 F.... agetty
/dev/vcsa:           root        225 F.... brltty
[root@wlap webczat]#

**Comment by webczat** [comment]
Also for your information, after sending the previous reply, I have 
pressed ctrl+alt+f4 and f5 to again switch to ttys that didn't work. 
after each of those two switches I checked the output of the fuser 
command, and this time both ttys appeared.

**Comment by poettering** [comment]
I'd bet this is due to brltty, keeping open the VCS after it is otherwise unused. That means logind will not consider starting a getty on the VCS because it assumes the tty is still busy... Not sure what to do about this best, but I figure brltty might have to be changed to close the VCS and not keep it busy after use...

**Comment by webczat** [comment]
Then, actually, why some terminals do start correctly? Sometimes you 
have to try few times to make them sart.

W dniu 21.08.2015 o 00:05, Lennart Poettering pisze:

**Comment by poettering** [comment]
@webczat well, most likely brltty keeps some of the VCs open, but others not. I am nto sure how precisely brltty works, and when it decides to open a VC... THis might be a discussion to involve the brltty devs in...

**Comment by poettering** [comment]
Let's close this here. brltty should really close VT devices when it doesn't use them. Only then logind will automatically start new gettys on them. If brltty keeps the device open continously then logind will assume the tty is used and not start a getty on it. Or in other words: if brltty *uses* the device, then a getty would only conflict with it.

logind checks whether a tty is used via VT_GETSTATE's `.v_state` field. It's essential that brltty gives up it's VT devices so that the tty bits are unset in there.

Alternatively, if brltty wants to open the devices all the time it can simply spawn the autovt@.service instances on its own, when it seems appropriate, even when it keeps the tty busy. After all it's logind that checks the flags bits, not the getty itself.

Anyway, let's close this here, since we cannot really do anything about this from logind's side, short of disabling the auto-spawn logic altogether.
