### ISSUE TITLE
Option to mount root directory/image on /usr instead of /

### ISSUE THREAD

**Issue by aledomu** [systemd/systemd#9948]
**Is your feature request related to a problem? Please describe.**
For those cases where the root directory/partition (not disk) image only has a `/usr` directory in the root, I'd like it's contents to be bundled directly in the root of the directory/image but still mount it correctly.

**Describe the solution you'd like**
If the above happens and a boolean value like `RootIsUsr` is true, mount the root directory/image under `/usr` instead of `/` in the filesystem namespace in the service.

For portable services, if `systemd-portabled` doesn't detect a `/usr` directory in the directory/image (whether it's empty or not), it would turn on this option in the drop files for each service unit file copied to the host. Note that this could interact with other directory checks like the one I suggested in #9947, so I guess this should be the first check to do and append the `/usr` directory as the base path to the following checks if the conditions are met.

**Describe alternatives you've considered**
Don't bother with cosmetic details.

**Comment by sourcejedi** [comment]
I don't think it's a good idea to expose e.g. `/mnt` from the host just because a different container format is detected.  So I imagine `/` would have to be mounted like `TemporaryFilesystem=`, which would allow creating the necessary mount points. 

So far I prefer the idea of having all your mount points pre-created in the image, rather than creating them in a tmpfs.  I notice that right now you can't "only [have] a /usr directory in the root" _and_ treat the image as strictly immutable, which seems to be the pattern systemd encourages.  Even if you don't ask for `StateDirectory=` or so, I guess you will get a `PrivateTmp=yes` mount...

I personally would be cautious about defining a new format for container trees, until there is a more specific reason than "cosmetic details".

I guess it's the same as e.g. a read-only `/usr` partition... I don't think those are used in container images, they are used by things like Fedora Atomic, but I don't think that makes for a good example of something you'd want to pull a service from.  `systemd-nspawn` can't boot disk images with a separate /usr partition either, "to avoid the risk of accidentally mixing and matching incorrect combinations" when there are "multiple OS installations on the same disk".

**Comment by aledomu** [comment]
Yeah, the bit about `systemd-nspawn` is right, but it isn't what I'm talking about (though any directory/image with just the `/usr` directory contents would only work as a service). Of course exposing the root of the host directly is undesirable, but rather I'd expect a separate standard root directory structure (immutable to the service environment) put in place by systemd.

Note that I'm saying that this should be implemented as a feature for "classic" services as well, and portable services should build upon it if the image doesn't have the typical root directory structure. The format keeps being the same.

AFAIK this is the way Flatpak apps are packaged: they bundle only the contents of `/app`. Then all the other directories are placed by Flatpak when the app is started.
