### ISSUE TITLE
User journal files are not defragmented on btrfs

### ISSUE THREAD

**Issue by Self-Perfection** [systemd/systemd#9984]
**systemd version the issue has been seen with**
233 - 239 (I'm observing this behaviour for about a year)

**Used distribution**
Arch linux

**Expected behaviour you didn't see**
All journal files should be defragmented after rotation.

**Unexpected behaviour you saw**
Only `system*journal` files are defragmented. `user*journal` files are left as is.

**Steps to reproduce the problem**

1. Run journald with `SplitMode=uid` and persistent logs on btrfs
2. Start monitoring journald ioctls: `strace -tTy -e trace=ioctl -p $(systemctl show --value -p MainPID systemd-journald.service) |& grep '/var/log'`
3. Run `journalctl --rotate`
4. Observe in strace output that BTRFS_IOC_DEFRAG was issued only for `system*journal` file

**Comment by poettering** [comment]
hmm, this is strange, looks like some pattern matching issue in journal_file_rotate()...

**Comment by poettering** [comment]
OK, so I had a closer look: these defragmentations are actually requested, but in a delayed fashion. This is because of the "deferred close" logic introduced with #2650: instead of syncing/closing journal files in the main journald thread this is done in a background thread. During rotation this might sometimes have the effect that we won't defrag right away, but only when the journal is closed later.

Sooner or later you should see the defrag ioctls being invoked on the relevant fds, for example if you rotate again

**Comment by poettering** [comment]
closing this since i don't really think this constitues a bug. when precisely the defrag happens doesn't really matter as long as it is not forgotten, and it is not.
